### ISSUE TITLE
Document SecurityFilterChain bean based configuration

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-security#10003]
The current release (`5.5.1` at the time of writing this) has no documentation on `SecurityFilterChain` `@Bean` based configuration. Since configuration support is one the central aspects to Spring Security, and this approach has been referred to as recommended going forward (see spring-projects/spring-boot#23421), I find it unfortunate that 9+ months after it hit the GA there's still mention of it in the docs.

I've been trying to educate the developers within my organization about this new approach, but that's quite challenging without the proper resources in place.

**Comment by ghusta** [comment]
The link to the blog post aforementioned : 
- https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter
