### ISSUE TITLE
Remove Code from Issue No:9223

### ISSUE THREAD

**Issue by ganeshan123** [spring-projects/spring-security#10000]
Hi Team,

Some days back I created a spring security issue (Issue No:9223) under spring projects,

The URL is https://github.com/spring-projects/spring-security/issues/9223,

This issue is currently closed and I cannot edit this issue to remove the code snippet entered as part of the description,

Can you please help me to edit the description and remove the code snippet,

Appreciate your quick response , Thanks in advance.

Thanks,
Ganeshan

**Comment by jgrandja** [comment]
@ganeshan123 Code snippet has been removed.

**Comment by ganeshan123** [comment]
Thanks a lot Grandja,

Thanks,
Ganeshan
