### ISSUE TITLE
Update links on wiki to point to migrated samples 

### ISSUE THREAD

**Issue by marcospds** [spring-projects/spring-security#10006]
Samples have been migrated to spring-security-samples project, but broken links point to old location, [wiki](https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide#examples-matrix-1). I corrected in [fork](https://github.com/marcospds/spring-security/wiki/OAuth-2.0-Migration-Guide#examples-matrix-1), but it is not possible to do PR for a wiki.

**Comment by marcusdacoregio** [comment]
Thanks for your report @marcospds.

I've updated the link to point to the right location and ran a link checker which didn't report any broken links left.
I'm closing this as solved but feel free to discuss if any broken link was left behind.
