### ISSUE TITLE
Update to use s01.oss.sonatype.org  Maven Publishing

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#10015]
We need to update all active branches to use s01.oss.sonatype.org  for publishing to Maven Central. See https://github.com/spring-projects/spring-security/issues/9988#issuecomment-870083827

NOTE: This will need backported to all supported branches.

**Comment by rwinch** [comment]
Fixed via ad45a74b346b9d7afc36c5594ee448ca27db11e4

**Comment by spring-projects-issues** [comment]
Fixed via ad45a74b346b9d7afc36c5594ee448ca27db11e4
