### ISSUE TITLE
Remove -PdeployDocsHost=docs-ip.spring.io from Build

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#10021]
The update of build conventions means the default docs server is correct, so we can remove the explicit setting of the host.

See gh-10020 and https://github.com/spring-gradle-plugins/spring-build-conventions/pull/93

**Comment by rwinch** [comment]
Fixed via 84118a7d44a39e2a69928d788a7fc50f4a90f630

**Comment by spring-projects-issues** [comment]
Fixed via 84118a7d44a39e2a69928d788a7fc50f4a90f630
