### ISSUE TITLE
SEC-745: Provide general strategies for Url navigation (redirects and forwards for error handling, login entry points, post-login targets etc)

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1005]
["Martino Piccinato":https://jira.spring.io/secure/ViewProfile.jspa?name=martino.piccinato](Migrated from ["SEC-745":https://jira.spring.io/browse/SEC-745?redirect=false]) said:

I propose to introduce a mechanism similar to the one introduced with SEC-516 to give the possibility to resolve dinamically:
- logout urls with LogoutFilter
- entry points with CasProcessingFilterEntryPoint

Different implementations of TargetUrlResolver interface could be used for default cases leaving open the possiblity to use more complex strategies.

My case with this (and with previous SEC-516) is providing different themes/behaviours to different organizations/departments using the same cas single sign on system. Now I have to use a custom implementation of AuthenticationEntryPoint and a customer Filter that just copy 90% of the current spring security class code but add my desired behaviour.

If you accept this I could provide a patch against latest trunk.

**Comment by spring-issuemaster** [comment]
This issue supersedes #1358
