### ISSUE TITLE
AuthenticationFailureEvent does not exist

### ISSUE THREAD

**Issue by dmitrilc** [spring-projects/spring-security#10062]
**Describe the bug**
The Spring Security doc, section 10.21 and 12.3.26 references **AuthenticationFailureEvent**, but it does not exist.

Looks like the class to be injected is **AbstractAuthenticationFailureEvent** instead. 

The side-by-side Kotlin code example uses the correct **AbstractAuthenticationFailureEvent** class, while the Java version, throughout the doc, references the non-existent **AuthenticationFailureEvent** several times.

A. https://github.com/spring-projects/spring-security/blob/006b9b960797d279b31cf8c8d16f1549c5632b2c/docs/manual/src/docs/asciidoc/_includes/servlet/authentication/events.adoc

B. https://github.com/spring-projects/spring-security/blob/e30b45c6fbf99ccef774b40fa0aad57a97df41b0/docs/manual/src/docs/asciidoc/_includes/servlet/oauth2/oauth2-resourceserver.adoc

**To Reproduce**
Go to https://docs.spring.io/spring-security/site/docs/current/reference/html5/#servlet-events

**Expected behavior**
The doc should mention **AbstractAuthenticationFailureEvent** instead.

**Comment by jzheaux** [comment]
Thanks, @dmitrilc, for the report. Are you able to submit a PR to fix the documentation?

**Comment by dmitrilc** [comment]
Hi. I created PR https://github.com/spring-projects/spring-security/pull/10064
