### ISSUE TITLE
Facility to set relaystate

### ISSUE THREAD

**Issue by rajn** [spring-projects/spring-security#10073]
**Expected Behavior**

Moving from Spring SAML Extension to Spring SAML 2 Provider. Except for global logout have been able to get most things sorted out. I found the new library very light weight and to the point. Congrats on that.
The issue I have is, in a SAML library there should be an easy way to set RelayState.

**Current Behavior**

There seems no api to set the relaystate.

**Context**

I'm using 5.4.6 of the saml2 provider.

**Comment by eleftherias** [comment]
Hi @rajn, are you aware of the `Saml2AuthenticationRequestContextResolver`?
You can expose a bean of this type to set the relay state on the `Saml2AuthenticationRequestContext`. Take a look at the reference documentation for an [example](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#servlet-saml2login-sp-initiated-factory-custom-authnrequest) on how it can be used.

**Comment by rajn** [comment]
thanks @eleftherias will take a look.

**Comment by eleftherias** [comment]
Hi @rajn, were you able to accomplish your goal by using `Saml2AuthenticationRequestContextResolver`?

**Comment by rajn** [comment]
> Hi @rajn, were you able to accomplish your goal by using `Saml2AuthenticationRequestContextResolver`?

Hi @eleftherias thanks for checking. We didnt need the relaystate for this particular situation. So didnt explore that option.

**Comment by eleftherias** [comment]
Thanks @rajn, I will go ahead and close this issue.
