### ISSUE TITLE
Build failed with error "Task :checkstyleNohttp FAILED"

### ISSUE THREAD

**Issue by kishorkunal-raj** [spring-projects/spring-security#10072]
**Describe the bug**
I am trying to build spring-security on ppc64le architecture host but its failing with an error "Task :checkstyleNohttp FAILED
> Task :spring-security-acl:compileJava UP-TO-DATE
> Task :spring-security-aspects:compileAspectj UP-TO-DATE
> Task :spring-security-web:compileJava UP-TO-DATE
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':checkstyleNohttp'.
> java.lang.IllegalStateException: Could not load file 'etc/nohttp/allowlist.lines'
"

**To Reproduce**
Using ppc64le host, so i did following
1. git clone git@github.com:spring-projects/spring-security.git
2. cd spring-security/
3. ./gradlew publishToMavenLocal ---------> Passed
4. ./gradlew build -----------> Failed

**Expected behavior**
Ideally it should result to successful build

NOTE: Issue is similar to issue #9346. Only thing is user reported issue on IDE and appears successful to him on terminal. But in my case the build is failing on terminal itself

**Comment by jzheaux** [comment]
@kishorkunal-raj is there a reason that you feel this should be addressed in Spring Security instead of [NoHttp](https://github.com/spring-io/nohttp)?

**Comment by kishorkunal-raj** [comment]
> @kishorkunal-raj is there a reason that you feel this should be addressed in Spring Security instead of [NoHttp](https://github.com/spring-io/nohttp)?

@jzheaux, there are no any specific reason for this. I brought this to you as because I encountered build failure for the repository, So in order to seek any specific requirement or reason behind the failure. If this is irrelevant, than request you to close the issue.

**Comment by kishorkunal-raj** [comment]
@jzheaux, Thanks for addressing the issue. There are no any specific reason for this. I brought this to you as because I encountered build failure for the repository, So in order to seek any specific requirement or reason behind the failure. If this is irrelevant, than request you to close the issue.

**Comment by jzheaux** [comment]
Gotcha, @kishorkunal-raj. I'm thinking that if you can reproduce this without Spring Security - say just a sample project that uses NoHttp, then you could post an issue to that project.

**Comment by jzheaux** [comment]
@kishorkunal-raj, have you already tried reproducing the error with [just NoHttp](https://github.com/spring-io/nohttp/tree/main/samples/nohttp-gradle-sample)? The linked sample doesn't have an `etc/nohttp/allowlist.lines` file, but one could be added.

You might also consider adding some more lines to the exception you posted. This may help narrow down the component that is having the issue.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
