### ISSUE TITLE
SEC-748: Support and basic implementation for CAS single sign out protocol

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1008]
["Martino Piccinato":https://jira.spring.io/secure/ViewProfile.jspa?name=martino.piccinato](Migrated from ["SEC-748":https://jira.spring.io/browse/SEC-748?redirect=false]) said:

I've seen in SEC-601 you've added support for new cas single sign out protocol but I guess it's "just" new client dependency. I think it could be interesting to provide real support for this. 

I have some code I could clean up and submit including a needed filter for cas logout process requests supporting different logout strategies plus a default ehcache based implementation.

If you are interested I'll try to post it as soon as I can (hope to make for 2.0 final...)

**Comment by spring-issuemaster** [comment]
This issue relates to #1954

**Comment by rwinch** [comment]
The CAS `LogoutHandler` not integrates with `HttpServletRequest.logout()` which Spring Security overrides to invoke the configured Spring Security `LogoutHandler`s which do provide integration with the `Authentication`.
