### ISSUE TITLE
Add PostFilter support for Optionals

### ISSUE THREAD

**Issue by markbanierink** [spring-projects/spring-security#10109]
**Expected Behavior**
Add functionality to use `@PostFilter` on `Optional` return types.

**Current Behavior**
Currently filtering is supported for collections, arrays, maps and streams. To add support for optional filtering, you have to create a custom handler extending the `DefaultMethodSecurityExpressionHandler`, add an implementation for optionals filtering (through stream filtering) and then register this new handler. This is very cumbersome.

**Comment by jzheaux** [comment]
This is related to [an earlier discussion about `@PostAuthorize`](https://github.com/spring-projects/spring-framework/issues/20433#issuecomment-453460051).

In addition to Rob's recommendation (above) to use `.orElse`, `@PostFilter` is intended for [filtering collections](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#filtering-using-prefilter-and-postfilter), so I'd be hesitant to support non-collection return types.
