### ISSUE TITLE
Customize filter instance with HttpSecurity#formLogin call

### ISSUE THREAD

**Issue by arthursalimkhanov** [spring-projects/spring-security#10116]
**Expected Behavior**
FormLoginConfigurer could have a method to call AbstractAuthenticationConvigurer#setAuthenticationFilter(). UsernamePasswordAuthenticationFilter would become the default filter if we don't call the setter

**Current Behavior**
Now there is no way to redefine the filter without crutches. The use of UsernamePasswordAuthenticationFilter is hardcoded although AbstractAuthenticationConvigurer has a setter method.
![image](https://user-images.githubusercontent.com/7391906/126159947-97408095-b793-401c-9363-3f01758bcd60.png)

![image](https://user-images.githubusercontent.com/7391906/126159988-4ef5fb50-3341-44fe-bef5-4f382be67a4b.png)

**Context**

**Comment by jzheaux** [comment]
Thank you for the suggestion, @arthursalimkhanov.

You can replace a filter by doing:

```java
http.addFilter(new MyCustomUsernamePasswordAuthenticationFilter());
```

Or if needed, you can still use the `formLogin()` DSL and then post-process the filter [using an object post-processor](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#post-processing-configured-objects).

**Comment by arthursalimkhanov** [comment]
> Thank you for the suggestion, @arthursalimkhanov.
> 
> You can replace a filter by doing:
> 
> ```java
> http.addFilter(new MyCustomUsernamePasswordAuthenticationFilter());
> ```
> 
> Or if needed, you can still use the `formLogin()` DSL and then post-process the filter [using an object post-processor](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#post-processing-configured-objects).

this is not at all what you suggest. 'Or if needed, you can still use the formLogin() DSL and then post-process the filter using an object post-processor.' - Why such difficulties if you can just add the ability to select this filter during configuration? I have a feeling that you are rejecting the request without understanding the problem.

**Comment by arthursalimkhanov** [comment]
[PR](https://github.com/spring-projects/spring-security/pull/10114) Here is the PR that solves the problem. And it seems I'm not the only one who stumbled upon this bug, which does not allow configuring without problems.

**Comment by quaff** [comment]
> [PR](https://github.com/spring-projects/spring-security/pull/10114) Here is the PR that solves the problem. And it seems I'm not the only one who stumbled upon this bug, which does not allow configuring without problems.

It's incredible we both stumbled at the same time.

**Comment by arthursalimkhanov** [comment]
> > [PR](https://github.com/spring-projects/spring-security/pull/10114) Here is the PR that solves the problem. And it seems I'm not the only one who stumbled upon this bug, which does not allow configuring without problems.
> 
> It's incredible we both stumbled at the same time.

It seems to me that this is such an obvious point that why no one has fixed it so far.

**Comment by jzheaux** [comment]
> I have a feeling that you are rejecting the request without understanding the problem.

I'm sorry you are feeling that way, let's keep working on this. Does [this comment](https://github.com/spring-projects/spring-security/pull/10114#issuecomment-883441152) address what you are trying to do?

**Comment by arthursalimkhanov** [comment]
[comment](https://github.com/spring-projects/spring-security/pull/10114#issuecomment-883798216) No, it adds a new filter instead of replacing the old one, it does not have the old filter settings that were added at the time of configuration. The implementation made in this [PR](https://github.com/spring-projects/spring-security/pull/10114) will work for me. Thanks for reviewing my issue.
