### ISSUE TITLE
ACL docs refer to nonexistent sample apps

### ISSUE THREAD

**Issue by sgrimm** [spring-projects/spring-security#10110]
The [ACL docs](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#domain-acls) say:

> You’ll also need to populate the database with the four ACL-specific tables listed in the last section (refer to the ACL samples for the appropriate SQL statements).

The samples are described in the previous section of the docs as:

> Two samples ship with Spring Security that demonstrate the ACL module. The first is the Contacts Sample, and the other is the Document Management System (DMS) Sample.

But neither of those samples exists in the spring-security-samples repo, and none of the existing samples seem to refer to the ACL tables.

EDIT: Originally I thought this meant the schemas were undocumented, but I see they're documented in an appendix. The main part of the docs should probably point to the appendix instead of the samples.

**Comment by marcusdacoregio** [comment]
Thanks @jzheaux and @sgrimm.

I've updated an [already created ticket](https://github.com/spring-projects/spring-security-samples/issues/22) to include those two ACL samples.

**Comment by marcusdacoregio** [comment]
Thanks @sgrimm. The two samples are now migrated to the new samples repository and I have updated the documentation to point to those samples.
