### ISSUE TITLE
Implement reactive support for JWT as an Authorization Grant

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#10147]
This ticket addresses the reactive support for gh-6053.

**Comment by sjohnr** [comment]
Hi @jonathannaguin, that's a good question.

In this case, the goal was to align the reactive implementation with `JwtBearerOAuth2AuthorizedClientProvider`, which uses the authentication principal. All I can say for certain is that the `password` grant implementations do require context attributes to capture the credentials from request parameters (see [docs](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2Client-authorized-manager-provider)) whereas other implementations (intentionally) do not. This most likely has to do with the need to access the request, which would not be available to a (`Reactive`)`OAuth2AuthorizedClientProvider`.
