### ISSUE TITLE
Allow extend ClientRegistration class to load client secret lazily

### ISSUE THREAD

**Issue by kzwang** [spring-projects/spring-security#10160]
In our setup, the client secret is an encrypted property, and decrypt requires a remote call which affects the startup time of the app. It would be nice if we can extend the `ClientRegistration` class and override `getClientSecret` to load it lazily so we can decrypt the secret only when that's been used.

**Comment by jgrandja** [comment]
@kzwang I would recommend lazily loading `ClientRegistration` via `ClientRegistrationRepository.findByRegistrationId()`. Here you could decrypt `clientSecret` before returning the `ClientRegistration` for use.

I'm going to close this based on the recommended implementation strategy.

**Comment by jgrandja** [comment]
@kzwang Thanks for the detailed explanation. I understand the challenge you have. Let's figure out the best solution for you.

Are there any other special use cases that I need to be aware of? I'd like to account for all use cases before we figure out 
a solution.

**Comment by jgrandja** [comment]
@kzwang Are you still looking for a solution here? If so, please respond to my previous comment and we can figure it out from there.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
