### ISSUE TITLE
Upgrade Unboundid to 6.0.6

### ISSUE THREAD

**Issue by mdiskin** [spring-projects/spring-security#10210]
**Expected Behavior**

Support latest improvements and better defaults for security protocols such as removing SHA1 prefering TLS1.3. Also for embedded you no longer need to enable the operational attriubutes.

https://nawilson.com/2021/05/28/unboundid-ldap-sdk-for-java-6-0-0/

**Current Behavior**

Works but falling a number of major versions behind which can be an audit concern.

**Context**

The initial request was related to bug (not unboundid  but in the autoconfig) in embedded ldap springboot 
https://github.com/spring-projects/spring-boot/issues/23030

**Comment by jzheaux** [comment]
Before marking this at `6.x`, let's see there is a way to have `5.6.x` support both UnboundId 4 and the latest, similar to what was done with #9095. This way, `5.6.x` can have the latest UnboundId support while allowing folks to stay on UnboundId 4.x if needed.

**Comment by rwinch** [comment]
For this issue we should also ensure old unboundid support is removed in 6.0.x

**Comment by marcusdacoregio** [comment]
Unboundid 6.x already [works with Spring Security 5.x](https://github.com/spring-projects/spring-security-samples/blob/6e6ec5845ea04ef673260c0928518fdb2039f35e/servlet/spring-boot/java/ldap/build.gradle#L17), users can opt into it if they want. Spring Boot also [uses Unboundid 6.x in 2.7](https://github.com/spring-projects/spring-boot/blob/0f4d98b1f47a733be97b19136612d5040043d1e0/spring-boot-project/spring-boot-dependencies/build.gradle#L1881).
