### ISSUE TITLE
Exception messages cannot be properly internationalized

### ISSUE THREAD

**Issue by Hccake** [spring-projects/spring-security#10227]
**Describe the bug**

AbstractUserDetailsAuthenticationProvider class defines an attribute messages, and gives the initial value for it  。

```java
	protected MessageSourceAccessor messages = SpringSecurityMessageSource.getAccessor();
```

But this class also implements MessageSourceAware，AbstractApplicationContext# initMessageSource () method will ensure that the container will always be a messageSource , when the user does not customize messageSource , an empty DelegatingMessageSource will be registered.

This leads to AbstractUserDetailsAuthenticationProvider messageSource attribute is never in the initial value, because always triggers MessageSourceAware#setMessageSource ()  

Exception messages thrown in this class will always be defaultMessage unless the user manually registers the messageSource and scans basename "org.springframework.security.messages".  

**Expected behavior**

Hope in the user without configuration messageSource, back to use SpringSecurityMessageSource, this ensures that the internationalization of correct error message

**Comment by eleftherias** [comment]
Thanks for reaching out @Hccake.
Have you registered a `MessageSource` bean in your application?
```
@Bean
public MessageSource messageSource() {
    ReloadableResourceBundleMessageSource messageSource = new ReloadableResourceBundleMessageSource();
    messageSource.addBasenames("classpath:org/springframework/security/messages");
    return messageSource;
}
```

**Comment by Hccake** [comment]
@eleftherias 

When I register such a messageSource, it works.

But if MessageSourceAccessor is provided by default, why should users register messageSource themselves ?

**Comment by eleftherias** [comment]
Thank you for confirming that, @Hccake.

I'm not sure I understand your question. Perhaps this section of the reference [documentation](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#localization) is able to answer it?

**Comment by Hccake** [comment]
What I mean by this is whether spring-Security can also provide support for internationalization without users manually registering messageSource.

**Comment by Hccake** [comment]
@eleftherias 

hello，I have created a PR for this issue, can you have a look

**Comment by eleftherias** [comment]
The message source is necessary to distinguish between the localization that is provided by Spring Security (which can be seen [here](https://github.com/spring-projects/spring-security/tree/main/core/src/main/resources/org/springframework/security)) and any custom messages that you have added.

If you feel that we are missing any language, we are happy to accept a PR directly in Spring Security with the internationalized messages.

**Comment by Hccake** [comment]
@eleftherias 

When users use Spring Security, they do not enjoy internationalization by default,  You must register a `MessageSource` and add is called "the classpath: org/springframework/security/messages" the basename to realize internationalization. 
 
I don't think this is a great experience, and ideally, users can enjoy the internationalization of Spring Security error messages without having to sign up for MessageSource. 
 
`SpringSecurityMessageSource` useless at present, by default, he will be replaced by an empty `MessageSource`, when the user registration `MessageSource`, replaced by the user registration `MessageSource`.

**This allows `SpringSecurityMessageSource` lost its meaning.**

**Comment by elfwine** [comment]
I also had this problem with the latest Spring boot (2.6.7) and spring security(5.6.3).
I also tried to register MessageSource but it's not picking up.  I debugged if AbstractUserDetailsAuthenticationProvider#setMessageSource is called and  it did not.
What I did is I copied the spring security's InitializeUserDetailsBeanManagerConfigurer class into a new one and set the MessageSource inside of the configure method.
I think it will be better if MessageSource is set in InitializeUserDetailsManagerConfigurer by default just like how UserDetailService and PasswordEncoder where set.

**Comment by pearl88** [comment]
> I also had this problem with the latest Spring boot (2.6.7) and spring security(5.6.3). I also tried to register MessageSource but it's not picking up. I debugged if AbstractUserDetailsAuthenticationProvider#setMessageSource is called and it did not. What I did is I copied the spring security's InitializeUserDetailsBeanManagerConfigurer class into a new one and set the MessageSource inside of the configure method. I think it will be better if MessageSource is set in InitializeUserDetailsManagerConfigurer by default just like how UserDetailService and PasswordEncoder where set.

 Spring Boot (3.1) and spring security(6.1),There is still this problem,MessageSourceAware without effect

**Comment by pearl88** [comment]
> 



> I also had this problem with the latest Spring boot (2.6.7) and spring security(5.6.3). I also tried to register MessageSource but it's not picking up. I debugged if AbstractUserDetailsAuthenticationProvider#setMessageSource is called and it did not. What I did is I copied the spring security's InitializeUserDetailsBeanManagerConfigurer class into a new one and set the MessageSource inside of the configure method. I think it will be better if MessageSource is set in InitializeUserDetailsManagerConfigurer by default just like how UserDetailService and PasswordEncoder where set.

Therefore, I can only copy the language files in the 'org.springframework.security' directory to my own project for modification
