### ISSUE TITLE
Buggy  PostInvocationAdviceProvider::supports(Class<?> clazz)   implementation

### ISSUE THREAD

**Issue by jvmlet** [spring-projects/spring-security#10236]
The current implementation doesn't allow to support `MethodInvocation` - inherited classes :
````java
@Override
	public boolean supports(Class<?> clazz) {
		return clazz.isAssignableFrom(MethodInvocation.class);
	}
````
Looks like the intention was the opposite :

````java
@Override
	public boolean supports(Class<?> clazz) {
		return MethodInvocation.class.isAssignableFrom(clazz);
	}
````

Please change [here](https://github.com/spring-projects/spring-security/blob/006b9b960797d279b31cf8c8d16f1549c5632b2c/core/src/main/java/org/springframework/security/access/prepost/PostInvocationAdviceProvider.java#L76)

**Comment by jzheaux** [comment]
Thanks, @jvmlet, for pointing this out. Are you able to provide a PR to make this change?

**Comment by jvmlet** [comment]
@jzheaux , please merge  #10300
