### ISSUE TITLE
Add Documentation for Static Methods Classes for `mockJwt()` and `jwt()`

### ISSUE THREAD

**Issue by miller79** [spring-projects/spring-security#10254]
I'm looking through the documentation for testing [Spring Security with WebFlux](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#webflux-testing-jwt) and it shows a static method being used `mockJwt()` and `jwt()` but it doesn't have any references to what class that comes from. The method appears to be in `org.springframework.security.test.web.reactive.server.SecurityMockServerConfigurers.java` but I feel the documentation should reflect this so users do not have to go searching for this when their IDE is unable to autocomplete the class.

**Comment by marcusdacoregio** [comment]
Hi @miller79, thanks for reaching out.

Are you able to submit a PR to address this issue?

**Comment by miller79** [comment]
I should be able to just got to get a little time.  I'll see if I can throw something out there today sometime.

**Comment by marcusdacoregio** [comment]
Ok @miller79, the issue is yours now.

Take your time to do that, and, if you aren't able to submit a PR, please let me know so I can do that.

**Comment by miller79** [comment]
@marcusdacoregio I have created this PR and fixed a few other issues I saw on the way.

https://github.com/spring-projects/spring-security/pull/10255

Not sure I have the ability to link the issue with the PR.
