### ISSUE TITLE
OAuth2 Token Response Customization

### ISSUE THREAD

**Issue by bishoybasily** [spring-projects/spring-security#10260]
**Summary**

Provide a way to customize the token response being extracted by `OAuth2BodyExtractors` before parsing it.

**Current Behavior**
Using `WebClient` to authenticate against a server that returns custom JSON Response, for example: {"Token":"xyz"},
where "xyz" is the token and "bearer" is the type, but since the server doesn't follow the right naming convention and some properties are missing,  I can't read the token.

**Desired Behavior**
A way to customize the raw `Map<String, Object>` before it gets decoded by `OAuth2BodyExtractors`

**Comment by jzheaux** [comment]
Thanks for the suggestion, @bishoybasily. I think it makes sense to add a `setBodyExtractor` method to `AbstractWebClientReactiveOAuth2AccessTokenResponseClient`. This would allow an application to take the `ReactiveHttpInputMessage` and transform it in the way that they need to.

Are you able to submit a PR to add this?

**Comment by bishoybasily** [comment]
Yes, Sure!
let me validate my understanding,, 
you want `setBodyExtractor` to set the `OAuth2AccessTokenMapCustomizer` inside the `AbstractWebClientReactiveOAuth2AccessTokenResponseClient` instead of implementing it right?
also, let me know if the interface name is ok? we can call it `OAuth2AccessTokenMapEnahncer` or if you have a better name in mind?

**Comment by bishoybasily** [comment]
Hi @jzheaux,
Sure! 
just let me validate my understanding,, 
you want `setBodyExtractor` to set the `OAuth2AccessTokenMapCustomizer` inside the `AbstractWebClientReactiveOAuth2AccessTokenResponseClient` instead of implementing it right?
also, let me know if the interface name is ok? we can call it `OAuth2AccessTokenMapEnahncer` or if you have a better name in mind?

**Comment by bishoybasily** [comment]
Hi @jzheaux Done!

**Comment by bishoybasily** [comment]
Hi @jzheaux, Yes submitted 
Please check #10269
