### ISSUE TITLE
Support for changing prefix and suffix in `DelegatingPasswordEncoder`

### ISSUE THREAD

**Issue by heowc** [spring-projects/spring-security#10273]
**Expected Behavior**

I can change `prefix` and `suffix`.

**Current Behavior**

I can not change `prefix` and `suffix`.
See https://github.com/spring-projects/spring-security/blob/main/crypto/src/main/java/org/springframework/security/crypto/password/DelegatingPasswordEncoder.java#L124...L126

**Context**

We can increase the flexibility for `DelegatingPasswordEncoder`.
ex) 
```
{bcypt}blabla~~~  -->  bcypt$blabla~~~
```

**Comment by rwinch** [comment]
Thanks for the issue @heowc! Would you be willing to submit a PR (with tests)?

**Comment by heowc** [comment]
> Thanks for the issue @heowc! Would you be willing to submit a PR (with tests)?

Of course! 😀

**Comment by rwinch** [comment]
Closed in favor of gh-10278
