### ISSUE TITLE
Allows users to extend the Encoders while using PasswordEncoderFactories

### ISSUE THREAD

**Issue by Hccake** [spring-projects/spring-security#10280]
Hope to use PasswordEncoderFactories create DelegatingPasswordEncoder, can extend the default encodersMap.  

For example, when a user needs to add or replace an Encoder, he must copy the source code ，if this feature is added, users can easily extend it.

**Comment by marcusdacoregio** [comment]
Thanks for the report @Hccake.

This is a duplicate of https://github.com/spring-projects/spring-security/issues/5939.
You can check out that issue for a workaround.
