### ISSUE TITLE
OAuth2ClientPropertiesRegistrationAdapter improve issuerUri value check

### ISSUE THREAD

**Issue by bitxon** [spring-projects/spring-security#10322]
**Expected Behavior**
`OAuth2ClientPropertiesRegistrationAdapter.getBuilderFromIssuerIfPossible` should validate that `issuer` is `not blank`
Because few lines after, code throws exception if this `issuer` is `null` or `emptyString` or `blankString`

**Current Behavior**
`OAuth2ClientPropertiesRegistrationAdapter.getBuilderFromIssuerIfPossible` validates that `issuer` is `not null`

**Context**
```java
class OAuth2ClientPropertiesRegistrationAdapter {
  ...
  private static Builder getBuilderFromIssuerIfPossible(...) {
      ...
      if (issuer != null) {  // this code performs only null check
        Builder builder = ClientRegistrations.fromIssuerLocation(issuer).registrationId(registrationId);
        return getBuilder(builder, provider);
      }
      ...
  }
  ...
}
```
```java
public static ClientRegistration.Builder fromIssuerLocation(String issuer) {
  Assert.hasText(issuer, "issuer cannot be empty"); // this code perform null check + String content check
  ...
}
```

**Comment by marcusdacoregio** [comment]
Hi @bitxon, thank you for reaching out.

Since the `OAuth2ClientPropertiesRegistrationAdapter` class is from Spring Boot, can you open the issue on [its repository](https://github.com/spring-projects/spring-boot/issues)?

**Comment by bitxon** [comment]
> Hi @bitxon, thank you for reaching out.
> 
> Since the `OAuth2ClientPropertiesRegistrationAdapter` class is from Spring Boot, can you open the issue on [its repository](https://github.com/spring-projects/spring-boot/issues)?

Hello, I have created a new issue in spring-boot repo:  https://github.com/spring-projects/spring-boot/issues/28139

**Comment by marcusdacoregio** [comment]
Thanks, @bitxon. Closing this in favour of https://github.com/spring-projects/spring-boot/issues/28139
