### ISSUE TITLE
Resolve HttpSecurityDsl Package Tangle

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#10333]
Resolve package tangle between `org.springframework.security.config.web` and `org.springframework.security.config.annotation.web`.

**Comment by nor-ek** [comment]
Okay, so the task is to move all Dsl files from `org.springframework.security.config.web.servlet` that have dependencies to `org.springframework.security.config.annotation.web`?

You can assign me to that task. I'll do this on the branch and that will wait till `6.x`. I'm open to other tasks for `first-timers`.

**Comment by jzheaux** [comment]
@nor-ek, the `6.0.x` branch is now available. Thanks for taking a look.

**Comment by nor-ek** [comment]
@jzheaux sorry for the mess above. Finally, I've got [Pull Request](https://github.com/spring-projects/spring-security/pull/10474).
