### ISSUE TITLE
Add support for JSR 107 cache

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-security#10363]
Since we will drop the EhCache2 support in 6.0, we should add support for JCache which EhCache3 is fully compliant

**Comment by rwinch** [comment]
What specific cache are you thinking? I wonder if we should or already have an implementation that uses Spring abstraction which has implementations for all sorts of caches?

**Comment by marcusdacoregio** [comment]
Thanks @rwinch, yes we do have the `org.springframework.security.core.userdetails.cache.SpringCacheBasedUserCache` that uses the Spring abstraction. I'll close this as invalid.
