### ISSUE TITLE
Documentation has wrong code example in the 'Customizing OpenSAML’s AuthnRequest Instance' section

### ISSUE THREAD

**Issue by nyszilard** [spring-projects/spring-security#10364]
In the [Customizing OpenSAML’s AuthnRequest Instance section](https://docs.spring.io/spring-security/site/docs/5.5.x/reference/html5/#servlet-saml2login-sp-initiated-factory-custom-authnrequest) the code example is wrong, because: 
- There is no parameterless DefaultSaml2AuthenticationRequestContextResolver constructor
- OpenSamlAuthenticationRequestFactory is deprecated, so it should use OpenSaml4AuthenticationRequestFactory instead
- It should use Converter<**Saml2AuthenticationRequestContext**, AuthnRequest> instead of Converter<**MySaml2AuthenticationRequestContext**, AuthnRequest>

**Comment by nor-ek** [comment]
Hey @nyszilard here is the pull request https://github.com/spring-projects/spring-security/pull/10463. I'm not sure about resolver creation example.
