### ISSUE TITLE
SEC-778: exceptionMappings configuration in default namespace

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1037]
["Neil Anderson":https://jira.spring.io/secure/ViewProfile.jspa?name=neila29](Migrated from ["SEC-778":https://jira.spring.io/browse/SEC-778?redirect=false]) said:

Would it be possible to update the namespace based configuration to allow exception mappings to be created for the default authentication processing filter created via the form-login. This would be useful when cutting down the XML required to configure spring security.

Regards
Neil

**Comment by spring-issuemaster** [comment]
This issue duplicates #1005
