### ISSUE TITLE
SEC-779: GrantedAuthorityImpl constructor throws IllegalArgumentException during Hessian deserialization

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1038]
["Chin Huang":https://jira.spring.io/secure/ViewProfile.jspa?name=cthuang](Migrated from ["SEC-779":https://jira.spring.io/browse/SEC-779?redirect=false]) said:

Calling the attemptAuthentication method of the org.springframework.security.providers.rcp.RemoteAuthenticationManager interface throws an IllegalArgumentException when Hessian attempts to deserialize a GrantedAuthorityImpl object.
If the object does not have a no-argument constructor, Hessian calls another constructor with null, 0 or false as the arguments.  An Assert in the GrantedAuthorityImpl constructor throws IllegalArgumentException if the passed argument is null.

This issue is related to issue SEC-123.

**Comment by spring-issuemaster** [comment]
This issue is related to #384
