### ISSUE TITLE
Syntactially wrong Javadoc for AbstractRequestMatcherRegistry

### ISSUE THREAD

**Issue by lmroil** [spring-projects/spring-security#10382]
**Describe the bug**
https://github.com/spring-projects/spring-security/blob/6db58cbf8a26296a15eb9f9c187176f099acaa77/config/src/main/java/org/springframework/security/config/annotation/web/AbstractRequestMatcherRegistry.java#L101 has a copy-and-paste mistake from the `antMatchers` method below it.

**To Reproduce**
Look at the Javadoc.

**Expected behavior**
~~~java
/**
 * @param antPatterns the ant patterns to create the
 * {@link org.springframework.security.web.util.matcher.AntPathRequestMatcher} from.
 * If {@code null} or empty, then matches on nothing.
*/

**Comment by sjohnr** [comment]
Hi @lmroil, thanks for the report. Would you be interested in submitting a PR for this?

**Comment by lmroil** [comment]
@sjohnr No, I'm not interested in submitting a PR. It's more efficient if you do it yourself. :)
