### ISSUE TITLE
Resource server configured with JwtIssuerAuthenticationManagerResolver should publish authentication events

### ISSUE THREAD

**Issue by cselagea** [spring-projects/spring-security#10433]
**Expected Behavior**

A single-tenant resource server with default configuration uses `ProviderManager` for authentication, which publishes authentication success and failure events using a `DefaultAuthenticationEventPublisher`.

A multi-tenant resource server configured to use `JwtIssuerAuthenticationManagerResolver` should publish the same authentication events.

**Current Behavior**

No authentication events are published.

**Context**

After it is determined that the issuer of the JWT can be trusted (e.g. via `TrustedIssuerJwtAuthenticationManagerResolver`) and the JWT is deemed valid, I'd like to deduce the tenant and store the tenant ID in a `ThreadLocal` context.

I could accomplish this using a filter placed after the Spring Security filter chain, but I think a cleaner solution would be listening for `AuthenticationSuccessEvent`, getting the issuer from the `JwtAuthenticationToken`, and then populating the tenant context.

**Comment by cselagea** [comment]
I think this could be accomplished by adding an `AuthenticationEventPublisher` field initialized to a `NullEventPublisher` in `JwtIssuerAuthenticationManagerResolver` and then providing a setter for the publisher field.

```java
private AuthenticationEventPublisher eventPublisher = new NullEventPublisher();

public void setAuthenticationEventPublisher(AuthenticationEventPublisher eventPublisher) {
	Assert.notNull(eventPublisher, "AuthenticationEventPublisher cannot be null");
	this.eventPublisher = eventPublisher;
}
```

Then in `TrustedIssuerJwtAuthenticationManagerResolver`, instead of returning a `JwtAuthenticationProvider` directly, which has no event-publishing capabilities, an `AuthenticationEventPublishingJwtAuthenticationProvider` (or whatever it would be named) would be returned. This class would implement the `AuthenticationManager` contract by delegating to a `JwtAuthenticationProvider` instance and then use the publisher to publish `AuthenticationSuccessEvent`.

As for authentication failure, since `BearerTokenAuthenticationFilter` catches `AuthenticationException`, I suppose you wouldn't want to catch `AuthenticationException` in `AuthenticationEventPublishingJwtAuthenticationProvider`, so authentication failure events would be published by `BearerTokenAuthenticationFilter`.

**Comment by cselagea** [comment]
@jzheaux could I give it a shot to create a PR for this?

**Comment by jzheaux** [comment]
Yes, @cselagea, that sounds great. Though I believe I misspoke when I said the setter should be unnecessary at first. Since an `AuthenticationEventPublisher` cannot be constructed without an `ApplicationEventPublisher`, the only reasonable default is a null publisher, which will need to be overridden to get events published.

**Comment by cselagea** [comment]
@jzheaux, understood.

Should I base my work on the 5.7.x branch (to match the milestone) or main (as per the contribution guidelines)?

**Comment by jzheaux** [comment]
Actually, will you please base it off of `5.8.x`? The ticket appears to be out of date.

**Comment by cselagea** [comment]
@jzheaux, done. I opened PR #11281.

**Comment by cselagea** [comment]
@jzheaux, here's what I've currently got. With the addition of `SupplierJwtDecoder` in 5.6, I think I can simplify it to look more like your code sample while maintaining lazy initialization of `JwtDecoder`.

```java
@Bean
public JwtIssuerAuthenticationManagerResolver authenticationManagerResolver(
        IssuerRegistry issuerRegistry,
        AuthenticationProviderFactory authenticationProviderFactory,
        AuthenticationEventPublisher eventPublisher) {
    
    Predicate<String> trustedIssuerTest = issuerRegistry.getIssuers()::contains;
    AuthenticationManagerResolver<String> authenticationManagerResolver =
            new TrustedIssuerJwtAuthenticationManagerResolver(trustedIssuerTest, authenticationProviderFactory, eventPublisher);
    return new JwtIssuerAuthenticationManagerResolver(authenticationManagerResolver);
}
```

```java
class TrustedIssuerJwtAuthenticationManagerResolver implements AuthenticationManagerResolver<String> {

    private final Map<String, AuthenticationManager> authenticationManagers = new ConcurrentHashMap<>();

    // other fields and constructor omitted

    @Override
    public AuthenticationManager resolve(String issuer) {
        if (this.trustedIssuer.test(issuer)) {
            AuthenticationManager authenticationManager = this.authenticationManagers.computeIfAbsent(issuer,
                    key -> {
                        AuthenticationProvider authenticationProvider = authenticationProviderFactory.createProvider(issuer);

                        return authentication -> {
                            Authentication authenticationResult = authenticationProvider.authenticate(authentication);
                            eventPublisher.publishAuthenticationSuccess(authenticationResult);
                            return authenticationResult;
                        };
                    });
            logger.debug("Resolved AuthenticationManager for issuer '{}'", issuer);
            return authenticationManager;
        } else {
            logger.debug("Did not resolve AuthenticationManager since issuer is not trusted");
        }
        return null;
    }

}
```

```java
class AuthenticationProviderFactory {

    // fields and constructor omitted

    public AuthenticationProvider createProvider(String issuer) {
        JwtDecoder jwtDecoder = jwtDecoderFactory.createDecoder(issuer);
        JwtAuthenticationProvider authenticationProvider = new JwtAuthenticationProvider(jwtDecoder);
        authenticationProvider.setJwtAuthenticationConverter(jwtAuthenticationConverter);
        return authenticationProvider;
    }

}
```

```java
class IssuerJwtDecoderFactory implements JwtDecoderFactory<String> {

    // fields and constructor omitted

    @Override
    public JwtDecoder createDecoder(String issuer) {
        NimbusJwtDecoder jwtDecoder = JwtDecoders.fromOidcIssuerLocation(issuer);
        jwtDecoder.setJwtValidator(jwtValidatorFactory.createValidator(issuer));
        return jwtDecoder;
    }

}
```

**Comment by jzheaux** [comment]
Thanks, @cselagea, that helps. 

It seems like you need a custom `AuthenticationManagerResolver` anyway in order to set the `JwtAuthenticationConverter` and `JwtValidator`, so I don't think that setting an event publisher on `JwtIssuerAuthenticationManagerResolver` is going to reduce your configuration any. You'd either call the setter there or you'd call it on the `ProviderManager` you are constructing.

Given that, I'm going to close this issue for now, but please feel free to reopen it if it feels like I misunderstood.

As a side note I wonder if something like this would simplify your arrangement:

```java
@Cacheable(unless="#result==null")
public AuthenticationManager resolve(String issuer) {
    if (this.trustedIssuer.test(issuer)) {
        ProviderManager manager = new ProviderManager(authenticationProviderFactory::createProvider);
        manager.setAuthenticationEventPublisher(publisher);
        return manager;
    }
    return null;
}
```
As you said, it could be that this is further simplified by using `SupplierJwtDecoder`.
