### ISSUE TITLE
Retriving RelayState in authenticating SAMLResponse step

### ISSUE THREAD

**Issue by fr2lancer** [spring-projects/spring-security#10434]
### Summary
Current codes doesn't seem to provide the way to get RelayState from authenticationManager, Saml2AuthenticationTokenConverter in order to work with custom logic.

### Actual Behavior
There seems to have no methods to provide RelayState from SAMLResponse step.
So need to create Saml2AuthenticationToken, Saml2AuthenticationTokenConverter.
Ended up, I got blocked by OpenSaml4AuthenticationProvider

### Expected Behavior
I want to have RelayState value in the scope of setResponseAuthenticationConverter or authenticationConverter

### Configuration
spring security saml provider, spring

### Version
spring security saml provider - 5.5.3

### Sample

```java
AuthenticationProvider.setResponseAuthenticationConverter((Converter)new CustomResponseSaml2AuthenticationTokenConverter(
                        relyingPartyRegistrationResolver));
                (responseToken) -> {
// responseToken.getRelayState() like this? or other steps in processing SAMLResponse
});
```

**Comment by fr2lancer** [comment]
Hi. Today now I can test this with 5.6.0-RC1 ( 5.6.0-RC3 hasn't been released yet..?)

when I tested "ResponseToken.token.authenticationRequest " with http request, it actually get null before the getting RelayStatus() The reason seems to be below :

1. HttpSessionSaml2AuthenticationRequestRepository::loadAuthenticationRequest is loaded and the codes look like this :

```
	private static final String DEFAULT_SAML2_AUTHN_REQUEST_ATTR_NAME = HttpSessionSaml2AuthenticationRequestRepository.class
			.getName().concat(".SAML2_AUTHN_REQUEST");
...

@Override
	public AbstractSaml2AuthenticationRequest loadAuthenticationRequest(HttpServletRequest request) {
		HttpSession httpSession = request.getSession(false);
		if (httpSession == null) {
			return null;
		}
		return (AbstractSaml2AuthenticationRequest) httpSession.getAttribute(this.saml2AuthnRequestAttributeName);
	}
```
2. so it won't take the value from my http request by the logic above.

3. And I also found this code : 
```
public void setAuthenticationRequestRepository(
			Saml2AuthenticationRequestRepository<AbstractSaml2AuthenticationRequest> authenticationRequestRepository) {
		Assert.notNull(authenticationRequestRepository, "authenticationRequestRepository cannot be null");
		this.loader = authenticationRequestRepository::loadAuthenticationRequest;
	}

	private AbstractSaml2AuthenticationRequest loadAuthenticationRequest(HttpServletRequest request) {
		return this.loader.apply(request);
	}
```
	
4. So, is that designed to use custom Saml2AuthenticationRequestRepository in order to read values from the http request?

Thank you.

**Comment by fr2lancer** [comment]
Somehow I am able to get RelayState from session by using ' .apply(sharedHttpSession())' on the setup of MockMvcWebTestClient.
Instead need to send a pre-request of SAMLRequest in order to store RelayState beforehand.

Thanks you all.

**Comment by meghariani** [comment]
Hello @fr2lancer,

I am trying to retrieve the relaystate value from the session and I'm getting null when using getAttribute(). Can you please elaborate on how you fixed your issue? A code snippet will be very appreciated. 

Thanks,
