### ISSUE TITLE
Remove CAS module

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-security#10441]
We should remove the CAS module entirely since we depend on the [java client](https://github.com/apereo/java-cas-client) and there are no plans to support Jakarta EE 9 in it.

**Comment by Emkas** [comment]
Hello @marcusdacoregio,
Since me and my team have been using `spring-security-cas` (and `cas-client-core`) for years, can you tell us is there any link or resource online about Apereo doesn't want to support Jakarta EE 9 so we could read this and maybe debate about it? I saw this issue last week and I tried to find some info about this, but with no results.

**Comment by marcusdacoregio** [comment]
Hi @Emkas, thanks for reaching out.

I tried to get in touch with them through some emails sent to their [mailing lists](https://apereo.github.io/cas/Mailing-Lists.html), but it seems that those lists are not working.

Disabling the CAS module is not a definitive action and can be reverted if they release a version of their library that supports Jakarta EE 9.

Any help to get in touch with them would be awesome if you are interested.

**Comment by Emkas** [comment]
OK, so it's based on silence, not on some plain statement. I was afraid of that.

Not so long ago I've sent some PR's in `java-cas-client`. For a start. To see how their are working (as I did in Spring Security :-)). I get no feedback. And well.... `java-cas-client` looks like an abandoned project, only changes that are approved are PR's from bots with dependency updates (separate branches and then merged - or not - to the master - by another bot?).

I'm interested, but unfortunately I don't have any inside knowledge or contacts.

------

I've starting to write this message and in the meantime, I've bump my PR in `java-cas-client` and it was merged within 3 minutes. Maybe not the best place, but I'll try to get some info there.

**Comment by Emkas** [comment]
From https://github.com/apereo/java-cas-client/pull/612#issuecomment-957926013

 > As you surely know, this is an open-source project. There are no "plans" to do anything. Plans are made when someone shows up with a pull request, or someone pays someone to work on a pull request. Since those are unknown, I cant tell you about a pre-defined plan. All I can tell you is, atm, there are no plans since there is no pending PR, and AFAIK, nobody is paid to work on that feature. (Even pending PRs would be revi

> As you surely know, this is an open-source project. There are no "plans" to do anything. Plans are made when someone shows up with a pull request, or someone pays someone to work on a pull request. Since those are unknown, I cant tell you about a pre-defined plan. All I can tell you is, atm, there are no plans since there is no pending PR, and AFAIK, nobody is paid to work on that feature. (Even pending PRs would be reviewed as time allows)
> 
> Support for Jakarta generally would happen around the time of Spring Boot 3 and Spring 6. Too soon to "plan" for anything.

**Comment by marcusdacoregio** [comment]
Thank you for getting that information with the maintainers.

I guess that there isn't much to do from our side but wait on them. We have some time before next Spring's major versions go GA.

**Comment by xhaggi** [comment]
The CAS client has just been updated to JDK 17 + Jakarta EE. I've create an issue #11674 to re-add the CAS module.
