### ISSUE TITLE
SEC-798: Common way for redirect url config

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1045]
["Björn Voß":https://jira.spring.io/secure/ViewProfile.jspa?name=bjoern.voss](Migrated from ["SEC-798":https://jira.spring.io/browse/SEC-798?redirect=false]) said:

It would be great to have a single way to configure redirect urls for AccessDeniedHandlerImpl, AuthenticationProcessingFilterEntryPoint, AuthenticationProcessingFilter and so on.
In some you a property (useRelativeContext or serverSideRedirect) in some not.
What I want to suggest is a url pattern to do so.
For example:
/path/site.html -> serverSideRedirect=false,useRelativeContext =false
//path/site.html -> serverSideRedirect=false,useRelativeContext =true
# //path/site.html -> serverSideRedirect=true,useRelativeContext =true
# /path/site.html -> serverSideRedirect=true,useRelativeContext =false

**Comment by spring-issuemaster** [comment]
This issue is related to #1005
