### ISSUE TITLE
Automate updating to next development version in `gradle.properties`

### ISSUE THREAD

**Issue by sjohnr** [spring-projects/spring-security#10461]
**Note:** version to update to varies depending on branch

**Comment by nor-ek** [comment]
@sjohnr Are you able to explain me what needs to be done in this task?

**Comment by sjohnr** [comment]
Hi @nor-ek, actually see #10455 for a similar issue that I'd like to focus on first. Both of these issues can be solved with a gradle task in our build that updates the `version` property of `gradle.properties` with a given version number. Later, we will include that in a pipeline that performs the steps of our release.
