### ISSUE TITLE
Facility to add keyinfo to AuthnRequest xml

### ISSUE THREAD

**Issue by rajn** [spring-projects/spring-security#10478]
Expected Behavior

Moving from Spring SAML Extension to Spring SAML 2 Provider. 
The issue I have is, in the old extension the AuthnRequest used to go out with the keyinfo in the xml (ie. the certificate is part of the xml). Some IDPs are looking for this keyinfo in the authnrequest xml.

Current Behavior

There seems no way to set this keyinfo value on the AuthnRequest. Is there?

Context

I'm using 5.4.6 of the saml2 provider.

**Comment by marcusdacoregio** [comment]
Hi @rajn. This is now covered by https://github.com/spring-projects/spring-security/pull/9746 from version `5.6.0`.

Are you able to upgrade your Spring Security dependency version?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by rajn** [comment]
@marcusdacoregio thanks! that will be good enough for me.
