### ISSUE TITLE
spring-security-saml2-service-provider  - Single Logout

### ISSUE THREAD

**Issue by fl0gru85** [spring-projects/spring-security#10488]
### Summary

Currently I cannot find a way to trigger a global logout via the spring-security-saml2-service-provider module. Is this planned for future releases because I found the class 'Saml2LogoutRequest.java' is already there.

### Actual Behavior

Single SAML logout is not supported

### Expected Behavior

Single SAML logout is working and available in the documentation

### Version

5.5.3

**Comment by jzheaux** [comment]
Thanks for reaching out, @fl0gru85. This is added [in 5.6](https://docs.spring.io/spring-security/servlet/saml2/logout.html)
