### ISSUE TITLE
Javadocs search is broken

### ISSUE THREAD

**Issue by richardcs** [spring-projects/spring-security#10487]
Searching for things using the search feature (in the upper right) returns 404's

**To Reproduce**
https://docs.spring.io/spring-security/site/docs/current/api/
Search for InMemory
Pick one

**Expected behavior**
Search should not return 404's but the pages selected

**Comment by rwinch** [comment]
Thanks for the report! I see that this was reported before gh-10944 but I'm going to close this issue as a duplicate given there is already quite a bit of discussion on the later report. Thanks again!
