### ISSUE TITLE
SEC-788: x509 authentication does not work properly

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1049]
["Michel Zanini":https://jira.spring.io/secure/ViewProfile.jspa?name=michelz](Migrated from ["SEC-788":https://jira.spring.io/browse/SEC-788?redirect=false]) said:

x509 authentication does not work properly

I have an application with x509 authentication configured.

First:

In RC1 release my application startup properly. In final 2.0.0 release this exception occur:

org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: No AuthenticationEntryPoint could be established.

If I write the entry point bean like this:

<bean id="x509EntryPoint" class="org.springframework.security.ui.x509.X509ProcessingFilterEntryPoint" />

everything work properly.
I think 2.0.0 should work automatic like RC1 "OR" x509 documentation section in the reference manual should document it.

Second:

When I do the first login with x509 certificate in my application, a 403 http status code occurs.
This happens only if a http->https redirection is needed. 

Example:
First page is "IS_AUTHENTICATED_ANONYMOUSLY" and HTTP. Then user goes to a secure page over HTTPS.
The browser dialog appers to select the certificate. Then a 403 occur.

If the first page is HTTPS everything work properly.

I will attach the applicationContext and the error log.

Sorry for my bad english.

**Comment by spring-issuemaster** [comment]
This issue is related to #1036
