### ISSUE TITLE
Multi-tenancy Documentation - `com.nimbusds.jwt.proc.JWTProcessor` does not have a `setJWTClaimSetJWSKeySelector ` method

### ISSUE THREAD

**Issue by jmax01** [spring-projects/spring-security#10504]
In line 326 of [docs/modules/ROOT/pages/servlet/oauth2/resource-server/multitenancy.adoc#L326](https://github.com/spring-projects/spring-security/blame/09a14bf8a087d68b7ab6964c4add27c423f4decf/docs/modules/ROOT/pages/servlet/oauth2/resource-server/multitenancy.adoc#L326) there is a reference to a  `com.nimbusds.jwt.proc.JWTProcessor`  method called `setJWTClaimSetJWSKeySelector`. 

There is no such method on `com.nimbusds.jwt.proc.JWTProcessor` there is a `setJWTClaimsSetAwareJWSKeySelector` method however.

![image](https://user-images.githubusercontent.com/789402/141830240-7e69c6d2-f796-4722-b92b-f0805f9ca7e2.png)

**To Reproduce**
 Read the doc

**Expected behavior**
Replace with the correct call.

**Comment by jzheaux** [comment]
Thanks, @jmax01! Are you able to submit a PR with the correction?

**Comment by jmax01** [comment]
@jzheaux I can if `setJWTClaimsSetAwareJWSKeySelector` is the correct method?
