### ISSUE TITLE
Allow for comma-delimited scopes in OAuth2 authorization request

### ISSUE THREAD

**Issue by alefarendsen** [spring-projects/spring-security#10526]
Currently, scopes are space-delimited in the authorization request (in security.oauth2.core.endpoint.OAuth2AuthorizationRequest). This is according to the spec, so if services behave nicely, all is fine. There are however services out there that do not adhere to the spec (such as Strava). Passing in a space-delimited list of scopes causes the request to fail, indicating an invalid scope.

Any comma's passed into the list of scopes get converted into spaces by Spring Security. Great behaviour for services that adhere to the spec, but not for me, wanting to talk to Strava. So, this, for example, doesn't work.

`scope: activity:read,read_all`

It'd be great if somehow the delimiter could be configured in the ClientRegistration. Sure, it is not how things are supposed to work, but currently, I cannot use Spring Security with Strava.

For reference, it's currently hard-coded in org.springframework.security.oauth2.core.endpoint.OAuth2AuthorizationRequest

Changing getParameters(......) to the following does the trick for me.

```
private Map<String, Object> getParameters() {
            Map<String, Object> parameters = new LinkedHashMap();
            parameters.put("response_type", this.responseType.getValue());
            parameters.put("client_id", this.clientId);
            if (!CollectionUtils.isEmpty(this.scopes)) {
                parameters.put("scope", StringUtils.collectionToDelimitedString(this.scopes, ","));
            }
```

p.s. here's a similar issue, from gravitee https://github.com/gravitee-io/issues/issues/1001

**Comment by sjohnr** [comment]
Hi @alefarendsen, thanks for your interest in the project!

It does indeed appear difficult to customize the behavior of encoding the scopes in the request to the authorization server. One possible solution would be to add this customization option to the `OAuth2AuthorizationRequest.Builder`. Since the `DefaultOAuth2AuthorizationRequestResolver` already has a `Consumer<OAuth2AuthorizationRequest.Builder> authorizationRequestCustomizer`, directly affecting the builder should be possible, we only need to make it possible to override the default delimiter in the builder for encoding scopes in the URL.

I believe that would be preferred over propagating something this specific from the `ClientRegistration` itself. Would you be interested in trying your hand at submitting a PR for this?

**Comment by alefarendsen** [comment]
Hey Steve,

It's been a while, but yes I can do that. Will take a bit of time though,
I'm a little busy the next week or so.

Alef

**Comment by jgrandja** [comment]
@alefarendsen 

It's already possible to override the default `scope` parameter by converting it from space-delimited to comma-delimited. 

As noted by @sjohnr, the customization point is:

> Since the `DefaultOAuth2AuthorizationRequestResolver` already has a `Consumer<OAuth2AuthorizationRequest.Builder> authorizationRequestCustomizer`, directly affecting the builder should be possible, we only need to make it possible to override the default delimiter in the builder for encoding scopes in the URL

Here is a sample configuration to override it:

```java
this.resolver.setAuthorizationRequestCustomizer((customizer) ->
		customizer.parameters((params) -> {
			// Override any of the default parameters (before encoding)

			// Override the default scope parameter using comma delimiter
			String scope = (String) params.get(OAuth2ParameterNames.SCOPE);
			String[] scopes = StringUtils.delimitedListToStringArray(scope, " ");
			params.put(OAuth2ParameterNames.SCOPE, StringUtils.arrayToDelimitedString(scopes, ","));
		})
);
```

Please refer to the reference for additional details on [customizing the authorization request](https://docs.spring.io/spring-security/reference/servlet/oauth2/client/authorization-grants.html#_customizing_the_authorization_request).

I'm going to close this as the solution provided allows for customization.

**Comment by alefarendsen** [comment]
Thanks Joe,

this is helpful, as always.

cheers,
Alef

**Comment by sjohnr** [comment]
Ah, perfect! I had somehow missed the `parametersConsumer`.
