### ISSUE TITLE
Reference Documentation uses Both "multi-tenancy" and "multitenancy" through out

### ISSUE THREAD

**Issue by jmax01** [spring-projects/spring-security#10572]
Documentation uses both "multi-tenancy" and "multitenancy" through out

**To Reproduce**
Read/search the reference documentation 

**Expected behavior**
Use either "multi-tenancy" or  "multitenancy" not both

**_Usages of both "multitenancy " and "multi-tenancy"_**

- https://github.com/spring-projects/spring-security/blob/main/docs/modules/ROOT/pages/reactive/oauth2/resource-server/multitenancy.adoc
- https://github.com/spring-projects/spring-security/blob/main/docs/modules/ROOT/pages/servlet/oauth2/resource-server/multitenancy.adoc

**_"multi-tenancy" only_**
- https://github.com/spring-projects/spring-security/blob/main/docs/modules/ROOT/pages/reactive/oauth2/login/core.adoc
- https://github.com/spring-projects/spring-security/blob/main/docs/modules/ROOT/pages/servlet/oauth2/login/core.adoc

**Comment by eleftherias** [comment]
Thanks for bringing this up @jmax01.
Are you interested in submitting a pull request to fix this?

**Comment by jmax01** [comment]
I would have but I didn't know which version to choose

**Comment by eleftherias** [comment]
@jmax01 I agree, let's standardize the documentation to use "multi-tenancy".
