### ISSUE TITLE
Prevent using both `authorizeRequests` and `authorizeHttpRequests`

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-security#10573]
When users configure the `SecurityFilterChain` they can opt to use `authorizeHttpRequests` or `authorizeRequests`. Using both configurations does not make sense since they do the same thing.

Using `authorizeHttpRequests` is preferable now, since `authorizeRequests` is gonna be deprecated.

We should ensure that only one of them is configured inside the filter chain.

**Comment by rwinch** [comment]
@marcusdacoregio Can you please ensure this version is updated to 5.7.0-M1 ?
