### ISSUE TITLE
Add hasIpAddress to Kotlin DSL

### ISSUE THREAD

**Issue by sjohnr** [spring-projects/spring-security#10577]
This issue adds support for hasIpAddress in the Kotlin DSL.

Related #10571

**Comment by LEQADA** [comment]
Seems like it was closed here https://github.com/spring-projects/spring-security/pull/10579 ?

**Comment by sjohnr** [comment]
@atrifyllis this is for the non-reactive DSL.

**Comment by brunodmartins** [comment]
@sjohnr @atrifyllis I want to work on this issue!

**Comment by sjohnr** [comment]
It's yours @brunodmartins!
