### ISSUE TITLE
Login using Incognito Browser, then start another Incognito session. Already logged in

### ISSUE THREAD

**Issue by tomaytotomato** [spring-projects/spring-security#10597]
**Describe the bug**

After authenticating locally on a Spring boot app with an incognito browser. 
When I open a new Incognito browser, I should be challenged/forced to authenticate again.

**To Reproduce**

Spring Boot + Security: **5.5.2.**

0. Start Spring boot service locally (localhost)
1. Start Firefox or Chrome private/incognito browser instance
2. Login to Spring Boot App (Spring Boot Security + Oauth2)
3. Login successful 
4. Open another private/incognito browser instance
5. Navigate to secure webpage
6. No prompt to login, automatically access the webpage

or

Rename or delete JSESSIONID cookie in Incognito browser, refresh page. A new one is generated.

**Expected behavior**

Every incognito/private browser session should be forced to authenticate.

**Comment by eleftherias** [comment]
Hi @tomaytotomato, this is the [intended behaviour](https://bugs.chromium.org/p/chromium/issues/detail?id=24690) in Chrome.
You will notice that this is not specific to Spring Security applications. 
If you log into any website, for example, Gmail, Facebook etc you will notice the same behavior.
