### ISSUE TITLE
Sources and javadocs missing in latest snapshots

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-security#10602]
The latest published snapshots do not have the sources or javadoc jar present. This appears to be the case for [`6.0.0-SNAPSHOT`](https://repo.spring.io/ui/native/snapshot/org/springframework/security/spring-security-core/6.0.0-SNAPSHOT), [`5.6.1-SNAPSHOT`](https://repo.spring.io/ui/native/snapshot/org/springframework/security/spring-security-core/5.6.1-SNAPSHOT) and [`5.7.0-SNAPSHOT`](https://repo.spring.io/ui/native/snapshot/org/springframework/security/spring-security-core/5.7.0-SNAPSHOT).

**Comment by rwinch** [comment]
This appears to be an issue with Artifactory and we are working with them on resolving it.

**Comment by rwinch** [comment]
In the meantime a workaround is to publish to a local repository location by running the following command:

```
./gradlew publishMavenJavaPublicationToLocalRepository
```

A maven repository will be published locally at build/publications/repos/ and contains accurate binary, source, and javadoc. 
NOTE: You'd need to use JDK 16 for Security 6 (on main) and JDK 11 (this is to support optional OpenSaml4 support which is JDK 11) for Security 5.7 and 5.6

You can then point your build to a Maven repository with a file URL. Something like `/home/rwinch/code/spring-projects/spring-security/build/publications/repos/`

**Comment by trevormarshall** [comment]
https://github.com/jfrog/build-info/issues/625
