### ISSUE TITLE
How to increase `RemoteJwkSet` timeout?

### ISSUE THREAD

**Issue by andreas-trvlk** [spring-projects/spring-security#10610]
**Expected Behavior**

No timeout.

**Current Behavior**

```
Caused by: java.lang.IllegalStateException: com.nimbusds.jose.RemoteKeySourceException: Couldn't retrieve remote JWK set: Read timed out
	at org.springframework.security.oauth2.jwt.JwtDecoderProviderConfigurationUtils.getSignatureAlgorithms(JwtDecoderProviderConfigurationUtils.java:107)
	at org.springframework.security.oauth2.jwt.JwtDecoders.withProviderConfiguration(JwtDecoders.java:122)
	at org.springframework.security.oauth2.jwt.JwtDecoders.fromOidcIssuerLocation(JwtDecoders.java:66)
```

**Context**

I am using Spring Security 5.5.3

Our team set up some JWT Decoder by utilizing `JwtDecoders` like this:
```java
@Bean
  JwtDecoder jwtDecoder() {
    final NimbusJwtDecoder jwtDecoder = (NimbusJwtDecoder)
        JwtDecoders.fromOidcIssuerLocation(issuer);

    final OAuth2TokenValidator<Jwt> audienceValidator = new AudienceValidator(apiAudience);
    final OAuth2TokenValidator<Jwt> withIssuer = JwtValidators.createDefaultWithIssuer(issuer);
    final OAuth2TokenValidator<Jwt> withAudience = new DelegatingOAuth2TokenValidator<>(withIssuer, audienceValidator);

    jwtDecoder.setJwtValidator(withAudience);

    return jwtDecoder;
  }
```
In the current implementation, I see it is now trying to obtain signature algorithms and it possibly can cause timeout.

I already tried to look around, but the answer is not good enough. This similar discussion https://github.com/spring-projects/spring-security/issues/4474 seems left hanging. This [stackoverflow thread](https://stackoverflow.com/questions/68643595/auth0-couldnt-retrieve-remote-jwk-set-read-timed-out) has hacky solution. This [one](https://stackoverflow.com/questions/68129558/how-to-configure-remote-jwk-timeout) also is not conclusive.

**Comment by jgrandja** [comment]
@andreas-trvlk Please see the reference doc on how to [configure timeouts](https://docs.spring.io/spring-security/reference/servlet/oauth2/resource-server/jwt.html#oauth2resourceserver-jwt-timeouts).

I'll close this as answered.

**Comment by vishal423** [comment]
@jgrandja, I believe you have overlooked the problem reported over here. `JwtDecoders` doesn't provide a way to specify the timeout and if you try to rewrite the custom `JwtDecoders` code, then, you will notice the underlying `JwtDecoderProviderConfigurationUtils` class has package visibility.

I think the problem reported over here and also in the linked JHipster issue comes from the below line of code. The current implementation doesn't specify the `ResourceRetriever` bean object as the 2nd constructor argument of `RemoteJWKSet` and thus internally defaults to ` DefaultResourceRetriever` bean object with connection and read timeouts as `500ms`. 
```
    private static JwtDecoder withProviderConfiguration(Map<String, Object> configuration, String issuer) {
        ...
        RemoteJWKSet<SecurityContext> jwkSource = new RemoteJWKSet(url(jwkSetUri));
        ...
    }
```

Can we extend `JwtDecoders` class to provide a method to allow specification of RestOperations and ResourceRetriever as input parameters?

**Comment by jgrandja** [comment]
@vishal423 Please see [comment](https://github.com/spring-projects/spring-security/issues/10610#issuecomment-1006029539). There are no references to `JwtDecoders`?

>  I believe you have overlooked the problem reported over here. `JwtDecoders` doesn't provide a way to specify the timeout and if you try to rewrite the custom `JwtDecoders` code

If you link through to the referenced sample code, the solution is provided:

```java
@Bean
public JwtDecoder jwtDecoder(RestTemplateBuilder builder) {
    RestOperations rest = builder
            .setConnectTimeout(Duration.ofSeconds(60))
            .setReadTimeout(Duration.ofSeconds(60))
            .build();

    NimbusJwtDecoder jwtDecoder = NimbusJwtDecoder.withJwkSetUri(jwkSetUri).restOperations(rest).build();
    return jwtDecoder;
}
```

**Comment by vishal423** [comment]
@jgrandja, In the sample code, you are expected to have `jwkSetUri` to build the `JwtDecoder`, however, the issue raised is for `JwtDecoders` trying to create a `JwtDecoder` from oidc `issuerUri` using the `fromOidcIssuerLocation` factory method. Unless I missed something, you can't pass a timeout to that factory method.

**Comment by jgrandja** [comment]
@vishal423 `JwtDecoders` does not fulfill all use cases, e.g. you cannot configure timeouts. It's designed as a utility for simple/convenient use cases. For more advanced use cases, e.g. configure timeouts, you need to explicitly create/configure the `NimbusJwtDecoder` as mentioned in previous comment.

**Comment by vishal423** [comment]
@jgrandja , I feel the default `500ms` as connect/read timeout is too small in a low bandwidth usage scenario and we should update that to a more reasonable number.

I also tried to write custom `JwtDecoders` with configurable timeouts, however, noted that the underlying used `JwtDecoderProviderConfigurationUtils` class has package visibility. Can we change that to `public` to allow easy extension in such scenarios?

**Comment by ankit-donor360** [comment]
> @jgrandja , I feel the default `500ms` as connect/read timeout is too small in a low bandwidth usage scenario and we should update that to a more reasonable number.
> 
> I also tried to write custom `JwtDecoders` with configurable timeouts, however, noted that the underlying used `JwtDecoderProviderConfigurationUtils` class has package visibility. Can we change that to `public` to allow easy extension in such scenarios?

@vishal423  Did you find the solution? I am facing same issue

**Comment by antonholmCO** [comment]
In case anyone on Spring Boot 4+ lands here, I was able to use the [JwkSetUriJwtDecoderBuilderCustomizer](https://docs.spring.io/spring-boot/api/java/org/springframework/boot/security/oauth2/server/resource/autoconfigure/servlet/JwkSetUriJwtDecoderBuilderCustomizer.html) to modify the timeout.

```java
@Bean
public JwkSetUriJwtDecoderBuilderCustomizer jwkSetUriTimeoutsCustomizer(RestTemplateBuilder builder) {
	RestOperations rest = builder
			.connectTimeout(Duration.ofSeconds(2))
			.readTimeout(Duration.ofSeconds(2))
			.build();

	return decoderBuilder -> decoderBuilder.restOperations(rest);
}
```
