### ISSUE TITLE
Support Azure B2C as OAuth2 Resource Server for Spring Security Reactive 

### ISSUE THREAD

**Issue by jsmwoolf** [spring-projects/spring-security#10611]
**Expected Behavior**

Should have the ability to integrate with Azure B2C for Webflux resource servers.

**Current Behavior**

Doesn't seem to be possible to actually use Azure B2C as part of an OAuth2 resource server.

**Context**
I would like the ability to use an event based model for a web server and need to use it with Azure B2C.  While there is support for MVC servers, we're expecting several thousand requests and we don't think that MVC will suit us.

I have a StackOverflow question that goes into more details:  https://stackoverflow.com/questions/70358027/webflux-cant-authenticate-jwt-token-from-azure-b2c

**Comment by sjohnr** [comment]
I'll go ahead and close this in favor of the stackoverflow issue for now, as this seems to be a question and not an enhancement. We prefer to use GitHub issues only for bugs and enhancements.
