### ISSUE TITLE
StrictHttpFirewall.setAllowSemicolon(true) doesn't work in 5.6.1

### ISSUE THREAD

**Issue by yilativs** [spring-projects/spring-security#10662]
**Describe the bug**
StrictHttpFirewall.setAllowSemicolon(true) doesn't work in 5.6.1
it used to work, however after upgrading to 5.6.1 it stopped working and now it cuts the url to the ;
i.e. if you pass /endpoint/123|45 
only 123 will be passed to the endpoint.

**To Reproduce**
in web configuration add following bean.
@Bean
    public HttpFirewall allowSemicolonHttpFirewall() {
        var firewall = new StrictHttpFirewall();
        // allowing semicolon in url, due to such endpoints as PATCH: /assets/{assetId}.
        // In most cases (at the moment always) assetId contains semicolon and without this config spring does not allow api call.
        firewall.setAllowSemicolon(true);
        return firewall;
    }

**Expected behavior**
StrictHttpFirewall.setAllowSemicolon(true)  should allow | in urls

**Comment by yilativs** [comment]
It worked with version 5.5.4

**Comment by sjohnr** [comment]
Hi @yilativs, would you be able to provide a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) for this issue?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
