### ISSUE TITLE
WebInvocationPrivilegeEvaluator Bean should support multiple `SecurityFilterChain`s

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-security#10680]
Related to https://github.com/spring-projects/spring-security/issues/10554

**Comment by marcusdacoregio** [comment]
Fixed via https://github.com/spring-projects/spring-security/commit/994e93741bfbe42b04befdeb4a4dcdd8021452f6

**Comment by jkuipers** [comment]
Thanks for looking into this, Andy! (esp. during the weekend)
I've opened up https://github.com/spring-projects/spring-security/issues/10937 to report this as a Spring Security issue now.
