### ISSUE TITLE
405 Method Not Allowed is blocked by authentication

### ISSUE THREAD

**Issue by bigboynaruto** [spring-projects/spring-security#10691]
**Describe the bug**
OS: macOS Big Sur 11.6
JDK: corretto-1.8 
Spring boot: 2.6.1

Consider an API with a single mapping `POST /foo` and the following 4 test cases:
* `POST /foo`
* `POST /foo/`
* `GET /foo`
* `GET /foo/`

Controller:
```java
@RestController
public class MainController {

    @PostMapping(path = "/foo", consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.TEXT_PLAIN_VALUE)
    private String foo() {
        return "this is foo";
    }
}
```

Without spring security (or with a configurer that permits all requests) the result will be the following:
* `POST /foo` -> 200 OK
* `POST /foo/` -> 200 OK
* `GET /foo` -> 405 Method Not Allowed
* `GET /foo/` -> 405 Method Not Allowed

Spring security configuration:
```java
@Configuration
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
                .and()
                .csrf().disable()
                .authorizeRequests()
                .anyRequest()
                .permitAll();
    }
}
```
---
If the configuration is changed in the way to permit only `/foo` mvc matcher, then the test result will change in the following way:
* `POST /foo` -> 200 OK
* `POST /foo/` -> 200 OK
* `GET /foo` -> 405 Method Not Allowed
* `GET /foo/` -> 403 Forbidden

Spring security configuration:
```java
@Configuration
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
                .and()
                .csrf().disable()
                .authorizeRequests()
                .mvcMatchers("/foo").permitAll()
                .anyRequest()
                .authenticated();
    }
}
```
For some reason while `POST /foo/` succeeds, `GET /foo/` fails the authentication.

**To Reproduce**
Apply `permitAll()` only to `/foo` path using mvc matcher.

**Expected behavior**
`GET /foo/` to work the same way as `GET /foo`, because these requests are the same from spring mvc's perspective.

**Sample**
[Sample project to reproduce](https://github.com/bigboynaruto/spring-security-issue-10691-demo)

**Comment by eleftherias** [comment]
I noticed that this case is already mentioned in the `mvcMatchers` Javadocs
https://github.com/spring-projects/spring-security/blob/525f40490ceb4e268b8a3b929e7a059c5ae8ee8b/config/src/main/java/org/springframework/security/config/annotation/web/AbstractRequestMatcherRegistry.java#L129-L130
Please reopen the issue if you believe additional changes are needed.
