### ISSUE TITLE
SEC-810: User Lockout Manager

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1071]
["Nomadeous":https://jira.spring.io/secure/ViewProfile.jspa?name=nomadeous](Migrated from ["SEC-810":https://jira.spring.io/browse/SEC-810?redirect=false]) said:

Hi,

In my work, I needed in a few projects to provide a locking account mechanism.
When too many bad login attemps are done with bad password, the following attemps will be locked.
Having worked on Weblogic or OpenLDAP, i found those mechanisms in 
- "UserLockout Manager" for Weblogic
- "Ppolicy" module for OpenLDAP

Common configuration options are :
- threshold (maximum of bad login attemps)
- duration of lock (automatic unlocking after a certain time)
  - for in-memory systems (like SS), cache size for login attempts 

Other Functionnalities needed :
- unlock users
- determine if a user account is locked

I find that such a module could be very useful for the community.

**Comment by spring-issuemaster** [comment]
This issue duplicates #873
