### ISSUE TITLE
SpringOpaqueTokenIntrospector does not convert scopes to GrantedAuthorities

### ISSUE THREAD

**Issue by DerThanne** [spring-projects/spring-security#10735]
Our IdP returns the scope claim as JSON Array which is not converted properly by SpringOpaqueTokenIntrospector because of this line:
https://github.com/spring-projects/spring-security/blob/feff7476693e47a1b28543521dae2bb79e8a1b3e/oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/introspection/SpringOpaqueTokenIntrospector.java#L216

But it would work out of the box if SpringOpaqueTokenIntrospector checked for List<String> as well.
Attached see a token.json as example.

[token.txt](https://github.com/spring-projects/spring-security/files/7877176/token.txt)

**Comment by eleftherias** [comment]
Thanks for reaching out @DerThanne. 
This is not a change we will be making because [the introspection RFC states that `scope` is a string](https://tools.ietf.org/html/rfc7662#section-2.2).

Please see #9270 for additional details and the recommended mitigation.
