### ISSUE TITLE
checkContentLength

### ISSUE THREAD

**Issue by YasuhiroOguro** [spring-projects/spring-security#10767]
https://github.com/spring-projects/spring-security/blob/dffa0ed43001d20d3f2d596db9b38d5bc06cf74e/web/src/main/java/org/springframework/security/web/util/OnCommittedResponseWrapper.java#L638

` checkContentLength(len - off)`

**Comment by jzheaux** [comment]
Hi, @YasuhiroOguro. What are you trying to achieve with the above change?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by YasuhiroOguro** [comment]
> Hi, @YasuhiroOguro. What are you trying to achieve with the above change?

あなた方のこの不具合のせいで、私は常に自分でoffsetを計算する必要があります。
Due to this bug, I always have to calculate the offset myself.

このメソッドを正しく動かすためにはoffsetを常に０にする必要があるからです。
This is because offset must always be 0 for this method to work properly.

**Comment by jzheaux** [comment]
This doesn't seem correct. `off` is which position in `buf` to start reading. `len` is how much data to write.

Since `checkContentLength` is intended to track how much should be written, I don't see why it's needed to subtract `off`.

Can you provide a sample that shows what is breaking for you?

**Comment by YasuhiroOguro** [comment]
@jzheaux Oh. I see.

Thank you for your work.
