### ISSUE TITLE
Consider deprecating `X-XSS-Protection` header DSL

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-security#10777]
This header has been deprecated by modern browsers and its use can introduce additional security issues on the client side. See https://owasp.org/www-project-secure-headers/#x-xss-protection

**Comment by jzheaux** [comment]
This seems related to https://github.com/spring-projects/spring-security/issues/9631.

**Comment by marcusdacoregio** [comment]
Closing as duplicate of #9631
