### ISSUE TITLE
DefaultLoginPageGeneratingFilter - fix incomplete localization of the default login page

### ISSUE THREAD

**Issue by razilein** [spring-projects/spring-security#10798]
**Expected Behavior**

All labels and buttons in the default login page should be localized on the basis of message.properties

**Current Behavior**

When using another language than english only errormessages and tooltips are localized.
The labels, placeholder and button-text are staying english.

Thats because these are harcoded. For instance "Please sign in".
https://github.com/spring-projects/spring-security/blob/main/web/src/main/java/org/springframework/security/web/authentication/ui/DefaultLoginPageGeneratingFilter.java#L221

**Context**

The localization is incomplete and always stays english.

**Comment by sjohnr** [comment]
Hi @razilein, thanks for your interest in the project. Would you be interested in submitting a pull request for this issue? I think it would be really nice to have full localization support on the default login page!

Also, have you tried implementing a custom login page, such as in [this sample](https://github.com/spring-projects/spring-security-samples/tree/main/servlet/java-configuration/authentication/username-password)?

**Comment by razilein** [comment]
Hello @sjohnr,

yes I had a custom login page before, but I switched to the default-one.
My custom login page had no major differences to the default one.

I struggled a bit with the options maximumSessions and maxSessionsPreventsLogin with my custom page.
With the default login page this feature worked fine for me, so I switched to it and want to keep it.

**Comment by razilein** [comment]
I've created #10811 to solve my problem.

**Comment by sjohnr** [comment]
Closing this issue for now. Please see [this comment](https://github.com/spring-projects/spring-security/pull/10811#issuecomment-1041923727) for an explanation.
