### ISSUE TITLE
JWKMatcher created by NimbusJwtEncoder fails to detect signing key

### ISSUE THREAD

**Issue by rgala** [spring-projects/spring-security#10807]
When a key has **Digital Signature** and **Key Encipherment** usages, **NimbusJwtEncoder** fails to detect a key, cause it expects it have **KeyUse.SIGNATURE** extension, however the **KeyUse** detected by **com.nimbusds.jose.jwk.KeyUse** **from(final X509Certificate cert)** method for such certificate is **KeyUse.ENCRYPTION**:

> 		// digitalSignature && keyEncipherment
>		// (e.g. RSA TLS certificate for authenticated encryption)
>		if (cert.getKeyUsage()[0] && cert.getKeyUsage()[2]) {
>			return KeyUse.ENCRYPTION;
>		}

This leads to **org.springframework.security.oauth2.jwt.JwtEncodingException: An error occurred while attempting to encode the Jwt: Failed to select a JWK signing key** exception because the **JWKMatcher** is build to only expect **KeyUse.SIGNATURE**:

>			return new JWKMatcher.Builder()
>					.keyType(KeyType.forAlgorithm(jwsAlgorithm))
>					.keyID(headers.getKeyId())
>					.keyUses(KeyUse.SIGNATURE, null)
>					.algorithms(jwsAlgorithm, null)
>					.x509CertSHA256Thumbprint(Base64URL.from(headers.getX509SHA256Thumbprint()))
>					.build();
>		}

I believe the JWKMatcher should be build with both **KeyUse.SIGNATURE** and **KeyUse.ENCRYPTION** though there is a risk that signing may fail in situations when a key has **Key Encipherment** usage but it does not have **Digital Signature** usage.

**Comment by rgala** [comment]
I have asked people responsible for Nimbus library and it looks like there is a workardound for this:

https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/461/issue-with-key-having-digital-signature

**Comment by jgrandja** [comment]
@rgala 

> When a key has Digital Signature and Key Encipherment usages, `NimbusJwtEncoder` fails to detect a key, cause it expects it have `KeyUse.SIGNATURE` extension

The current behaviour is correct. As per javadoc for `NimbusJwtEncoder`:

> An implementation of a {@link JwtEncoder} that encodes a JSON Web Token (JWT) using the
 JSON Web Signature (JWS) Compact Serialization format. The private/secret key used for
 signing the JWS is supplied by the {@code com.nimbusds.jose.jwk.source.JWKSource}
 provided via the constructor.

The current implementation only supports JWS and **does not support JWE**. This **MAY** be introduced at a later point  via gh-4435.

I'm going to close this as works-as-designed.
