### ISSUE TITLE
Case insensitive for validateName method in OpenSamlLogoutRequestValidator 

### ISSUE THREAD

**Issue by ameti** [spring-projects/spring-security#10803]
Hi guys,

Thank you for your work. Does it make sense to make validateName() configurable to use equalsignorecase() instead of equals()?

**Comment by jzheaux** [comment]
The [SAML spec](https://docs.oasis-open.org/security/saml/v2.0/saml-profiles-2.0-os.pdf) (line 1299) says:

> The principal MUST be identified in the request using an identifier that strongly matches the identifier in
the authentication assertion the requester issued or received regarding the session being terminated, per
the matching rules defined in Section 3.3.4 of [SAMLCore].

And [Section 3.3.4 of SAMLCore](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf) (line 1949) states:

> If S2 includes an identifier element (<BaseID>, <NameID>, or <EncryptedID>), then S1 MUST
include an identical identifier element...

Given that, I don't think we want to encourage customization of `OpenSamlLogoutRequestValidator` along those lines.

That said, you can switch out the validator for one of your own. If you want to reuse the existing validator, your custom validator can call it and then remove the unwanted error message.
