### ISSUE TITLE
Document Authorize HTTP Requests for Reactive Security

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#10801]
Similar to https://docs.spring.io/spring-security/reference/servlet/authorization/authorize-http-requests.html but for ServerHttpSecurity

**Comment by mraible** [comment]
Sweet! What's the publishing process for Spring Security Docs? Will it be in the next release or does it get published as part of the current one?

**Comment by mraible** [comment]
Nevermind, you sent an email with the link. It looks like it gets published as part of the current release. https://docs.spring.io/spring-security/reference/5.6.2/reactive/authorization/authorize-http-requests.html

**Comment by rwinch** [comment]
For anyone else that is here that wants to know:

The docs will appear in the version specific URL until we release.

https://docs.spring.io/spring-security/reference/5.6.2/reactive/authorization/authorize-http-requests.html

When it is the current release, it will appear in the versionless URL and the version specific URL will redirect to the versionless URL

https://docs.spring.io/spring-security/reference/reactive/authorization/authorize-http-requests.html

When the next version is released, the version specific URL will stop redirecting.
