### ISSUE TITLE
Add Kotlin example for logout configuration of reactive authentication 

### ISSUE THREAD

**Issue by talerngpong** [spring-projects/spring-security#10819]
**Expected Behavior**

It should provide both of Java and Kotlin examples for a logout configuration of reactive authentication.

**Current Behavior**

It provides only a Java example.

**Context**

When walking through [Reactive X.509 Authentication](https://docs.spring.io/spring-security/reference/reactive/authentication/x509.html), its page contains both of Java and Kotlin examples for reactive x509 configurations by toggling. Then, after walking to its next page of [Logout](https://docs.spring.io/spring-security/reference/reactive/authentication/logout.html), there is only a Java example.

**Comment by eleftherias** [comment]
Closed via 015036741be0f8ed92d1cdb27a87a07cc1fb42a1
