### ISSUE TITLE
OpenSaml4AuthenticationRequestResolver should have a customizable URI

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#10840]
Related to https://github.com/spring-projects/spring-security/issues/8873

It would be nice if `OpenSaml4AuthenticationRequestResolver` could take a custom URI.

**Comment by deepakchethan** [comment]
Hello, @jzheaux I would love to work on this. I'm pretty new to this codebase, would be great if you could give me some pointers. Thanks!

**Comment by marcusdacoregio** [comment]
Hello @deepakchethan, thanks for volunteering, and welcome to the project!

I think adding a `setRequestMatcher(RequestMatcher)` to `OpenSamlAuthenticationRequestResolver` and do the same in `OpenSaml4AuthenticationRequestResolver` which in turn will call the `OpenSamlAuthenticationRequestResolver::setRequestMatcher`.

It is recommended to take a look at the [contributing doc](https://github.com/spring-projects/spring-security/blob/main/CONTRIBUTING.adoc) which can help you with some questions.

Feel free to ask any questions here.

**Comment by deepakchethan** [comment]
> Hello @deepakchethan, thanks for volunteering, and welcome to the project!
> 
> I think adding a `setRequestMatcher(RequestMatcher)` to `OpenSamlAuthenticationRequestResolver` and do the same in `OpenSaml4AuthenticationRequestResolver` which in turn will call the `OpenSamlAuthenticationRequestResolver::setRequestMatcher`.
> 
> It is recommended to take a look at the [contributing doc](https://github.com/spring-projects/spring-security/blob/main/CONTRIBUTING.adoc) which can help you with some questions.
> 
> Feel free to ask any questions here.

Got it, Will get right on it. Thank you!
