### ISSUE TITLE
Make NimbusJwtClientAuthenticationParametersConverter support Microsoft identity platform.

### ISSUE THREAD

**Issue by chenrujun** [spring-projects/spring-security#10897]
**Expected Behavior**

`NimbusJwtClientAuthenticationParametersConverter` can be used directly for [Microsoft identity platform](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-certificate-credentials) .

**Current Behavior**

`NimbusJwtClientAuthenticationParametersConverter` can **not** be used directly for [Microsoft identity platform](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-certificate-credentials) .

**Context**

**Reason**
I guess it's caused by:
1. There is no "typ" and "x5t" in the header.
2. There is no "nbf" in the claim set.

**Proposals**
1. Add these fields ("typ", "x5t" and "nbf") in `NimbusJwtClientAuthenticationParametersConverter`.
2. Make these fields ("typ", "x5t" and "nbf") configurable in `NimbusJwtClientAuthenticationParametersConverter`. For example, pass in by constructor.

**Comment by jgrandja** [comment]
@chenrujun This is a duplicate of gh-9852. We'll soon be adding support for customizing claims via gh-9855.
