### ISSUE TITLE
Support Microsoft Identity Platform in CommonOAuth2Provider

### ISSUE THREAD

**Issue by chenrujun** [spring-projects/spring-security#10896]
**Expected Behavior**

Include `MICROSOFT` in [CommonOAuth2Provider](https://github.com/spring-projects/spring-security/blob/5.6.2/config/src/main/java/org/springframework/security/config/oauth2/client/CommonOAuth2Provider.java). 

**Current Behavior**

CommonOAuth2Provider contains `GOOGLE`, `GITHUB`, `FACEBOOK`, `OKTA`, but not contains `MICROSOFT`.

**Context**

Here is the link to doc about Microsoft Identity Platform -> OAuth 2.0 and OpenID Connect protocols: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols

**Comment by jgrandja** [comment]
@chenrujun This ticket is similar to gh-9047. Please see this [comment](https://github.com/spring-projects/spring-security/issues/9047#issuecomment-701516346) for additional context.
