### ISSUE TITLE
DefaultSecurityFilterChain: Wrong log message "Will not secure"

### ISSUE THREAD

**Issue by SebastianS90** [spring-projects/spring-security#10909]
**Describe the bug**
Log displays *Will not secure ...* instead of *Will secure ... with ...*.

**To Reproduce**
Configure a `SecurityFilterChain` bean and use log level `info`.

**Expected behavior**
Log shows *Will secure ... with ...*.

The condition [here](https://github.com/spring-projects/spring-security/blob/5.6.2/web/src/main/java/org/springframework/security/web/DefaultSecurityFilterChain.java#L51-L56) needs to be inverted.

**Comment by linghengqian** [comment]
In my test of spring security 5.6.2, some SecurityFilterChain​ Beans are also `will not secure`, while others are `will secure`. Is this because on spring security 5.6.2, `WebSecurityConfigurerAdapter` has not been deprecated, or is there more explanation in the official website documentation?

**Comment by jzheaux** [comment]
Hi, @linghengqian. If no filters are assigned to that particular request, then Spring Security can do no securing. Typically, this is induced by using `web.ignoring()` which skips all Spring Security filters for that request.
