### ISSUE TITLE
DelegatingOAuth2UserService stream mechanism that can cause oauth2 exceptions

### ISSUE THREAD

**Issue by NotFound403** [spring-projects/spring-security#10904]
**Describe the bug**
`DelegatingOAuth2UserService` stream mechanism that can cause oauth2 exceptions

**To Reproduce**

`DelegatingOAuth2UserService`:
```java
this.userServices.stream().map((userService) -> userService.loadUser(userRequest))
				.filter(Objects::nonNull)
				.findFirst()
				.orElse(null);
``` 
u see , the first stream element maybe not be the right one. when unsuited `OAuth2UserService` that will cause some exception like that  
```
[missing_openid_attribute] Missing required "some param" attribute in UserInfoEndpoint for Client Registration : some provider
``` 
and it will request all IDP user endpoint:

try wrong 1 
try wrong 2
try wrong 3
oh  right here  

**Expected behavior**
 
accurate  `OAuth2UserService`

**Comment by sjohnr** [comment]
@NotFound403, thanks for reaching out. I'm not quite clear on what your current vs expected behavior is. For example, are you receiving an error after the first IDP user info endpoint is tried, and the next one is not tried?

Can you perhaps provide a `MockMvc` test that demonstrates the issue? Or could you provide a suggestion for how `DelegatingOAuth2UserService` can be improved that would help clarify the issue?

**Comment by NotFound403** [comment]
okey, this a the mocktest
```java
    /***
     *   just like  loop
     */
    @Test
    public void streamAlwaysOrdered()  {
          // idp1 service
        OAuth2UserService<OAuth2UserRequest, OAuth2User> idp1CustomService = userRequest -> {

            String registrationId = userRequest.getClientRegistration().getRegistrationId();
            //  request  to auth server
            if (!registrationId.equals("idp1")) {
                // not suitable request 
                // this is a  simulation .   required param missing   http 405
                throw new RuntimeException(" this is a exception in  auth  server ");
            }

                List<GrantedAuthority> authorities = AuthorityUtils.createAuthorityList("USER");

                Map<String, Object> attributes = new HashMap<>();
                attributes.put("username", "idp1");
                attributes.put("age", 22);
                attributes.put("avatar", "https://avatars.githubusercontent.com/u/22664375?s=80&v=4");
                String nameAttributeKey = "username";
                return new DefaultOAuth2User(authorities, attributes, nameAttributeKey);


        };

        // idp2  service
        OAuth2UserService<OAuth2UserRequest, OAuth2User> idp2CustomService = userRequest -> {

            String registrationId = userRequest.getClientRegistration().getRegistrationId();
            //  request  to auth server
            if (!registrationId.equals("idp2")) {
                // not suitable request 
                // this is a  simulation     required param missing   http 405
                throw new RuntimeException(" this is a exception in  auth  server ");
            }
                List<GrantedAuthority> authorities = AuthorityUtils.createAuthorityList("USER");

                Map<String, Object> attributes = new HashMap<>();
                attributes.put("username", "idp2");
                attributes.put("age", 22);
                attributes.put("avatar", "https://avatars.githubusercontent.com/u/22664375?s=80&v=4");
                String nameAttributeKey = "username";
                return new DefaultOAuth2User(authorities, attributes, nameAttributeKey);
        };

        // default service
        DefaultOAuth2UserService defaultOAuth2UserService = new DefaultOAuth2UserService();
        List<OAuth2UserService<OAuth2UserRequest, OAuth2User>> oAuth2UserServices = Arrays.asList(idp1CustomService,
                idp2CustomService,
                defaultOAuth2UserService);
        OAuth2UserService<OAuth2UserRequest, OAuth2User> oAuth2UserService = new DelegatingOAuth2UserService<>(oAuth2UserServices);


        Instant now = Instant.now();
        OAuth2AccessToken accessToken = new OAuth2AccessToken(OAuth2AccessToken.TokenType.BEARER,"xxxxx", now, now.plusSeconds(180));


        // when i  use  idp1’s userRequest          ignore  some params
        ClientRegistration idp1 = ClientRegistration.withRegistrationId("idp1")
                .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
                .clientId("idp_client")
                .clientSecret("noop")
                .redirectUri("{baseUrl}/login/oauth2/code/{registrationId}")
                .authorizationUri("https://idp1.com/authorize/oauth2")
                .tokenUri("https://idp1.com/token/oauth2")
                .userInfoUri("https://idp1.com/user/oauth2")
                .build();
        OAuth2UserRequest idp1Request = new OAuth2UserRequest(idp1, accessToken);

     Assertions.assertNotNull(oAuth2UserService.loadUser(idp1Request));


        // when i  use  idp2’s userRequest          ignore  some params
        ClientRegistration idp2 = ClientRegistration.withRegistrationId("idp2")
                .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
                .clientId("idp_client")
                .clientSecret("noop")
                .redirectUri("{baseUrl}/login/oauth2/code/{registrationId}")
                .authorizationUri("https://idp2.com/authorize/oauth2")
                .tokenUri("https://idp2.com/token/oauth2")
                .userInfoUri("https://idp2.com/user/oauth2")
                .build();
        OAuth2UserRequest idp2Request = new OAuth2UserRequest(idp2, accessToken);
        // always
        Assertions.assertThrows(RuntimeException.class,()->oAuth2UserService.loadUser(idp2Request));
    }
```

**Comment by sjohnr** [comment]
@NotFound403, thanks so much for the mock test, that is extremely helpful in illustrating your reported issue. Here are my thoughts on this:

The `DelegatingOAuth2UserService` is a very simple composite implementation that tries a list of delegates in order, and simply expects null as the return value. This is a pretty simple contract to understand: as long as your requests succeed in such a way that the delegate provides `null`, you will not have an issue.

When the requests being issued through the composite are not valid for some of the providers, a legitimate OAuth2 error could be returned. I'm not sure it would make sense for this implementation to try and suppress or handle those errors. In this case, I feel it would be up to your application to provide adequate error handling for your use case. For example, you could wrap your delegates with another delegate that catches and handles the exception triggered by the 405 response, if that is appropriate. You can log it or do whatever you like, and then return `null`. Something like:

```java
public class ErrorHandlingOAuth2UserService implements OAuth2UserService<OAuth2UserRequest, OAuth2User> {
	private final OAuth2UserService<OAuth2UserRequest, OAuth2User> delegate;

	public ErrorHandlingOAuth2UserService(OAuth2UserService<OAuth2UserRequest, OAuth2User> delegate) {
		this.delegate = delegate;
	}

	@Override
	public OAuth2User loadUser(OAuth2UserRequest userRequest) throws OAuth2AuthenticationException {
		try {
			return this.delegate.loadUser(userRequest);
		} catch (Exception ex) {
			// TODO: Handle exception...
			return null;
		}
	}
}
```

What do you think of this approach?

**Comment by sjohnr** [comment]
Thanks for the dialogue and feedback, @NotFound403!

I think I see what you're saying, and I agree that in your situation, the `DelegatingOAuth2UserService` is probably not suitable. However, you provided your own implementation above that could be simplified to only use the `registrationId` to lookup a suitable `OAuth2UserService` from a `Map`. This seems to be the way your use case needs it to work. I'd recommend just using that implementation as a custom composite `OAuth2UserService`. The interface is pretty easy to implement, as you've already done it! I would actually advise using that same pattern of building composites and using delegation whenever you need to in Spring Security, there's nothing wrong with that (in my opinion).

Having said all of that, I'm not sure it's extremely important for that example implementation you provided to be contributed back into Spring Security, nor does it seem desirable to change the existing `DelegatingOAuth2UserService` to work that way as it unnecessarily complicates the existing code.

I think I've gathered enough information to close this issue, as the recommended solution is to build your own delegating implementation. I'm hoping that this conversation will be helpful to others looking to do something similar. As always, if I've missed anything or you have more to add, please add additional comments to keep the conversation going.
