### ISSUE TITLE
Investigate options for removing Spring Boot's ErrorPageSecurityFilter

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-security#10919]
/cc @rwinch 

- [x] https://github.com/spring-projects/spring-security/issues/11466
- [x] https://github.com/spring-projects/spring-security/issues/11467
- [x] https://github.com/spring-projects/spring-security/issues/11623

**Comment by marcusdacoregio** [comment]
Addressed via https://github.com/spring-projects/spring-boot/issues/31703
