### ISSUE TITLE
Documentation missing for 'BearerTokenConverter' in 'Oauth2ResourceServer'  configuration.

### ISSUE THREAD

**Issue by muhdalavu** [spring-projects/spring-security#10927]
There should be documentation for BearerTokenConverter in reactive OAuth2ResourceServer [docs](https://docs.spring.io/spring-security/reference/reactive/oauth2/resource-server/jwt.html#webflux-oauth2resourceserver-jwt-sansboot).

Example configuration.

```
@Bean
SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
	http
		.authorizeExchange(exchanges -> exchanges
			.pathMatchers("/message/**").hasAuthority("SCOPE_message:read")
			.anyExchange().authenticated()
		)
		.oauth2ResourceServer(oauth2 -> oauth2
                        .bearerTokenConverter(myCustomBearerTokenConverter())
			.jwt(withDefaults())
		);
	return http.build();
}
```

**Comment by jzheaux** [comment]
@muhdalavu have you already checked here: https://docs.spring.io/spring-security/reference/reactive/oauth2/resource-server/bearer-tokens.html#webflux-oauth2resourceserver-bearertoken-resolver

Maybe the documentation could link better to that location. Do you have any recommendations?

**Comment by muhdalavu** [comment]
Thank you for your update. 
Having a dedicated bearer token doc page makes sense.
