### ISSUE TITLE
SEC-839: Allow ObjectIdentity to be not only entity Identity but entity properties to

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1097]
["Alexander Gavrilov":https://jira.spring.io/secure/ViewProfile.jspa?name=lucker](Migrated from ["SEC-839":https://jira.spring.io/browse/SEC-839?redirect=false]) said:

In the current implementation it is possible to create ObjectIdentity and ACL's only for entities. But in the complex systems is requred to controll access non only to the entities, but entity properties to. Suppose, whe have entity User with two properties "homeAddress" and "businessAddress" (this is not entities, but value objects in the OO terms), and for someone whe need to grant access to only  homeAddress of User with name Bob, but for another peoples we need to grant access to boss addresses. We can do this using permissions, but this requres to support different permission sets for different entities types ant this is limited only by number 32 - 4.  I believe the best way to impliment this is to change Class getJavaType(); property of ObjectIdentity to String getType(); This will allow to write ObjectIdentities like User#homeAddress (of Bob) and User#businessAddress (of Bob). Im looked at code and found that in all cases getJavaType() value used only as String value of returned class name to query databse. So i beleave there will be no difficulties 
to patch code. I can make patch if is it required. Another approach is to add optional String getPath(); property to ObjectIdentity and use it value to construct String representation of Object Identity Type. This change will keep new code working for older users to.

**Comment by spring-issuemaster** [comment]
This issue duplicates #903
