### ISSUE TITLE
Update saganCreateRelease task property referenceDocUrl

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-security#11016]
Currently, the `referenceDocUrl` is using `https://docs.spring.io/spring-security/site/docs/{version}/reference/html5/` as the URL, this is an old URL and gives a 404 for the new docs deployment.

The task should use `https://docs.spring.io/spring-security/reference/{version}/index.html` as the new URL for the version `5.6.x` onwards.

**Comment by Enkosz** [comment]
Hi @marcusdacoregio! I can handle it to take some work off from you guys and somehow help the team

**Comment by marcusdacoregio** [comment]
Hi @Enkosz, I appreciate your disponibility. You can work on it, just make sure that the base branch is `5.7.x` instead of `main` when you open the PR.

You can comment here if you need any help. Thank you.

**Comment by Enkosz** [comment]
@marcusdacoregio I've made a PR(https://github.com/spring-projects/spring-security/pull/11031)
