### ISSUE TITLE
Default use of RequestAttributeSecurityContextRepository instead of NullSecurityContextRepository

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#11026]
Rather than totally ignoring saving the SecurityContext we should place it on the request as a request attribute to ensure that other dispatch types work properly.

Related gh-10918

**Comment by marcusdacoregio** [comment]
Hi @akovalyev, I think that your scenario is a bug, I create [this ticket](https://github.com/spring-projects/spring-security/issues/11606) to track that.
