### ISSUE TITLE
Trigger CI from release automation

### ISSUE THREAD

**Issue by sjohnr** [spring-projects/spring-security#11022]
Currently, a `git push` from `release-next-version.yml` does not trigger the CI process (GitHub seems to suppress it to avoid infinite loops). We should update the process to trigger the CI update after updating `gradle.properties`.

**Comment by eleftherias** [comment]
This was done by using an explicit GitHub token, rather than the default token in GitHub Actions.
See https://github.community/t/push-from-action-does-not-trigger-subsequent-action/16854
