### ISSUE TITLE
Authorization on Every Dispatch Type

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#11027]
Currently `FilterSecurityInterceptor` and `AuthorizationFilter` only perform authorization checks on the first request. Authorization should be performed on dispatch. We should make it simple to permitAll on other dispatch types for users that do not wish to do this.

NOTE: We may consider only making these changes to AuthorizationFilter rather than FilterSecurityInterceptor since we are moving towards using AuthorizationManager rather than the old authorization APIs.

Related gh-10919

**Comment by marcusdacoregio** [comment]
Fixed via https://github.com/spring-projects/spring-security/issues/11107
