### ISSUE TITLE
Custom RelayState with the new OpenSamlAuthenticationRequestResolver

### ISSUE THREAD

**Issue by exeba** [spring-projects/spring-security#11065]
With the deprecated `Saml2AuthenticationRequestContext` it was possible to set a custom RelayState, but with the new `OpenSamlAuthenticationRequestResolver` it is always initialized to:

```
String relayState = UUID.randomUUID().toString();
```

I don't see a way to overcome this without implementing my own AuthenticationRequestResolver, is there a reason for this?

**Comment by jzheaux** [comment]
Hi, @exeba. The purpose of deprecating the other classes was to simplify the API to a single interface. So, to have a custom relay state, you create a custom resolver that delegates like so:

```java
@Bean 
Saml2AuthenticationRequestResolver authenticationRequestResolver(
        RelyingPartyRegistrationResolver registrations) {
    OpenSaml4AuthenticationRequestResolver authenticationRequests = 
            new OpenSaml4AuthenticationRequestResolver(registrations);
    return (request) -> {
        Saml2PostAuthenticationRequest post = authenticationRequests.resolve(request);
        RelyingPartyRegistration registration = registrations.resolve(request, "registration-id");
        String relayState = resolveCustomRelayState(request);
        return Saml2PostAuthenticationRequest.withRelyingPartyRegistration(registration)
                .samlRequest(post.getSamlRequest())
                .authenticationRequestUri(post.getAuthenticationRequestUri())
                .relayState(relayState)
                .build();
    }
}
```

That said, I think this can be simplified. For example, it would be nicer to not have to waste the CPU on generating a relay state if the app is going to override it. To that end, I think we should add a `setRelayStateResolver(Converter<HttpServletRequest, String> relayStateResolver)` method. The default value would be one that randomly generates the relay state.

The resulting configuration would then instead be:

```java
@Bean 
Saml2AuthenticationRequestResolver authenticationRequestResolver(
        RelyingPartyRegistrationResolver registrations) {
    OpenSaml4AuthenticationRequestResolver authenticationRequests = 
            new OpenSaml4AuthenticationRequestResolver(registrations);
    authenticationRequests.setRelayStateResolver(this::resolveCustomRelayState);
    return authenticationRequests;
}
```

Would this address your concern and, if so, are you able to submit a PR that adds the setter?

**Comment by cjburgawork** [comment]
@jzheaux, Thanks for posting the code for the relay state resolvers.

I'm having trouble understanding the *non* functional interface (first) example.  I would like to get this code working for an older version of Java and the Spring library.  Specifically, where does the `request` object come from in the `authenticationRequestResolver` method?
```
return (request) -> {
        Saml2PostAuthenticationRequest post = authenticationRequests.resolve(request);
        RelyingPartyRegistration registration = registrations.resolve(request, "registration-id");
        String relayState = resolveCustomRelayState(request);
```
The signature for the `authenticationRequestResolver` only has a `RelyingPartyRegistrationResolver` as an argument:
```
Saml2AuthenticationRequestResolver authenticationRequestResolver(
        RelyingPartyRegistrationResolver registrations)
```
FYI, I was able to implement the functional interface (second) example (without testing), `CustomRelayStateResolver implements Converter<HttpServletRequest, String>`, for a newer version of Java.

Thanks again for your time and support in what you posted already.

**Comment by Martin-Office** [comment]
Hi @jzheaux, Your bean proposition to set custom relayState look interesting but sadly there is no bean RelyingPartyRegistrationResolver registrations for autowiring. How can I use the instance created by the framework?
In my configuration I only do this: 
`http.saml2Login(saml -> saml.successHandler(new Saml2AuthenticationSuccessHandler()))`

**Comment by Martin-Office** [comment]
Ok I can use autowiring of Saml2RelyingPartyProperties to avoid hardcoding the configuration... 
`	@Bean
	public RelyingPartyRegistrationRepository relyingPartyRegistrations(
		Saml2RelyingPartyProperties relyingPartyProperties) {
`
then it become managable....

**Comment by RaghuselvapraveenS** [comment]
@Martin-Office were you able to set the custom RelayState value in the SAMLRequest? We also having the same need
We are using spring-security-sam2-service-provider-6.3.0 and my Security Config and RelyingPartyRegistration looks like below, can you provide some details about how to set RelayState in SAMLRequest,

@Bean SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {

    http
    .authorizeHttpRequests(authorize -> 
         authorize.anyRequest().authenticated()
    ).saml2Login(saml2Login ->
    {
        try {
            saml2Login.relyingPartyRegistrationRepository(relyingPartyRegistrationRepository())
            .authenticationRequestUri("/demo/{registrationId}")
            .loginProcessingUrl("/demo/demoRedirect")
            .successHandler(customSAMLAuthenticationHandler)
            ;
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
);
    
    RelyingPartyRegistrationResolver relyingPartyRegistrationResolver = new DefaultRelyingPartyRegistrationResolver(relyingPartyRegistrationRepository());
    Saml2MetadataFilter filter = new Saml2MetadataFilter(relyingPartyRegistrationResolver, new OpenSamlMetadataResolver());
    http.addFilterBefore(filter, Saml2WebSsoAuthenticationFilter.class);

    return http.build();
}

@Bean
RelyingPartyRegistrationRepository relyingPartyRegistrationRepository() throws CertificateException {
    
    RelyingPartyRegistration registration = RelyingPartyRegistrations
            .fromMetadataLocation("<App Federation Metadata Url>")
            .registrationId("demosso")
            .assertionConsumerServiceLocation("https://demo.com/demo/demoredirect")
            .entityId("demo.sso.saml")
            .build();
    return new InMemoryRelyingPartyRegistrationRepository(registration);
}

**Comment by Martin-Office** [comment]
@RaghuselvapraveenS In my case, I needed the RelayState based on the caller origin. Since we are using individual development environment with dedicated URL I needed to support multiple RelayState. To be able to achieve this I save the URL in the request session with a OncePerRequestFilter when the selvletPath is "/saml2/authenticate/". Again in my case the client must provide a valid relayState. I mean for security reason it must be in the expected configured sub domain. 

```
http.addFilterBefore(new BeforeSaml2AuthenticationRequestFilter(...config), Saml2WebSsoAuthenticationRequestFilter.class);

//In BeforeSaml2AuthenticationRequestFilter
    String relayState = request.getParameter(RELAY_STATE);
    //validate
    request.getSession().setAttribute(RELAY_STATE, relayState);\
```

Then on successful login I manually redirect to the proper RelayState. 

``` 
httpSecurityBuilder.saml2Login(saml -> saml.successHandler(new Saml2AuthenticationSuccessHandler()));

//In Saml2AuthenticationSuccessHandler override onAuthenticationSuccess(...)
String targetUrl= request.getSession().removeAttribute(RELAY_STATE);
```

The Saml2AuthenticationSuccessHandler extends SavedRequestAwareAuthenticationSuccessHandler. Then I suggest you overwrite the onAuthenticationSuccess and change the targetUrl with what you need. 

In fact, the SAML server act as a proxy to redirect to the proper URL on success.

Hope this can help you.
