### ISSUE TITLE
When browser language is 'Korean', can't see korean debug message

### ISSUE THREAD

**Issue by juunini** [spring-projects/spring-security#11086]
**Describe the bug**
When browser language is 'Korean', can't see korean debug message

**To Reproduce**

- When browser language is Korean

![image](https://user-images.githubusercontent.com/41536271/162577342-eb545ecb-0ad7-4ffc-b032-5dd78174e274.png)

- When browser language is Japanese

![image](https://user-images.githubusercontent.com/41536271/162577450-79a8b74e-7f69-4142-87a8-30779275e9ae.png)

- When browser language is German

![image](https://user-images.githubusercontent.com/41536271/162577670-ddd75161-eb81-4c59-9f63-880e4cb298c4.png)

**Expected behavior**

I think file name `messages_ko_KR.properties` change to `messages_ko.properties`
it maybe fix

![image](https://user-images.githubusercontent.com/41536271/162577784-2c599dd9-9b0d-43fb-8073-7d2036d23893.png)

**Comment by sjohnr** [comment]
@juunini, I am unable to see what you're seeing when setting a different language for the browser. Where are you seeing it printed out in multiple languages in your console? I would not expect the browser to be able to influence what language messages are printed to in the server's logs.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by sjohnr** [comment]
Hi @juunini, just in case you missed my comment above, do you have any thoughts on it?

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
