### ISSUE TITLE
Add AuthorizationManager that uses ExpressionHandler

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#11105]
In order to better facilitate the use of `AuthorizationManager` in JSP, Thymeleaf, and XML configuration support, we should add an expression-based `AuthorizationManager`.

This can also help folks who may be migrating from `authorizeRequests` which supports expressions and also expression-based voters.

**Comment by evgeniycheban** [comment]
@jzheaux I'd like to take this.

**Comment by evgeniycheban** [comment]
@jzheaux I've opened the PR, please take a look when you have time.
