### ISSUE TITLE
Conflict between xml <security:http> and Java SecurityFilterChain declaration configurations

### ISSUE THREAD

**Issue by KWSimon** [spring-projects/spring-security#11108]
### Summary
I posted this question on StackOverflow : [https://stackoverflow.com/questions/71871306/spring-security-how-to-mix-xml-securityhttp-and-java-securityfilterchain-de](https://stackoverflow.com/questions/71871306/spring-security-how-to-mix-xml-securityhttp-and-java-securityfilterchain-de)

When mixing xml configuration and Java configuration, if a `<security:http>` element exists in the xml configuration file the `SecurityFilterChain` created in the Java configuration is not used. The method creating the bean is called but it is not present in the `FilterChainProxy` when requests are processed.

### Actual Behavior

By using this sample it is possible to reproduce the issue : 
[https://github.com/KWSimon/minoshill/tree/main/SpringSecurityIssue](https://github.com/KWSimon/minoshill/tree/main/SpringSecurityIssue)

- Run the application : 
`mvn clean package tomee:run`

This resource shouldn't be reachable because it is protected by the `SecurityFilterChain` declared in the `testapp.SecurityConfiguration` class : 
[http://localhost:8180/testapp/secured/secured.html](http://localhost:8180/testapp/secured/secured.html)

- Stop the application
- Comment or remove the following element from the SpringConfig.xml file : `<security:http pattern="/page/**" security="none"/>`

- Run the application : 
`mvn clean package tomee:run`

The following resource is now protected by the filter : 
[http://localhost:8180/testapp/secured/secured.html](http://localhost:8180/testapp/secured/secured.html)

### Expected Behavior

Both xml and Java configuration should allow to declare and add filters to the SecurityFilterChain.

### Version

Spring Security 5.6.2

### Sample

By using this sample it is possible to reproduce the issue : 
[https://github.com/KWSimon/minoshill/tree/main/SpringSecurityIssue](https://github.com/KWSimon/minoshill/tree/main/SpringSecurityIssue)

**Comment by KWSimon** [comment]
Any idea if it is a configuration issue, an incorrect use of Spring Security or a bug ?

**Comment by marcusdacoregio** [comment]
Hi @KWSimon, sorry for the delay.

I have reached out to the team to see if that setup is possible, and, if so, how to make it work. I'll get back to you once I have a clear answer for that.

**Comment by rwinch** [comment]
Mixing `<http>` and `@EnableWebSecurity` is not intended to work together. The problem that is happening is that the XML configuration and Java Configuration are both creating a bean by the name of `springSecurityConfiguration`. The second bean (XML Configuration) overrides the first bean (Java configuration) which is why it is not working.

Can I ask why you want to use XML and Java Configuration together?

**Comment by KWSimon** [comment]
While waiting for a clean solution I imagined this workaround : [https://stackoverflow.com/a/71924315/14838319](https://stackoverflow.com/a/71924315/14838319). 
But as a said in my answer, it uses reflection and therefore could only be a very short term solution : 

```java
/**
 * Method listening to the Spring Application context initialization, detects
 * missing SecurityFilterChain from the FilterChainProxy and add the missing
 * chains to the FilterChainProxy.
 * 
 * @param ctxRefreshed
 */
@EventListener
public void handleContextRefreshEvent(ContextRefreshedEvent ctxRefreshed) {
    List<SecurityFilterChain> missingChains = filterChains.stream()
            .filter(chain -> !filterChainProxy.getFilterChains().contains(chain)).collect(Collectors.toList());

    if (missingChains.isEmpty()) {
        return;
    }

    try {
        Field filterChainsField = filterChainProxy.getClass().getDeclaredField("filterChains");
        boolean accessibleStatus = filterChainsField.isAccessible();
        try {
            filterChainsField.setAccessible(true);
            List<SecurityFilterChain> chains = (List<SecurityFilterChain>) filterChainsField
                    .get(filterChainProxy);
            if (chains == null) {
                throw new IllegalStateException(
                        "Unable to add the missing security filter chains to the existing filter chains list of the FilterChainProxy. The list from the FilterChainProxy is null");
            }
            missingChains.forEach(chain -> chains.add(chain));
        } finally {
            filterChainsField.setAccessible(accessibleStatus);
        }
    } catch (NoSuchFieldException | IllegalArgumentException | IllegalAccessException e) {
        throw new IllegalStateException(
                "Unable to add the missing security filter chains to the existing filter chains list of the FilterChainProxy: "
                        + e.getMessage(),
                e);

    }
}
```

**Comment by rwinch** [comment]
You can combine the XML and Java Configuration and exposes it as a different bean name using something like this:

```java
@Configuration
public class AggregateSpringSecurityConfiguration {
	public static final String AGGREGATE_SPRING_SECURITY_FILTER_CHAIN_ID = "aggregateSpringSecurityFilterChain";

	/**
	 * Provide a new FilterChainProxy that contains both XML and Java Configuration
	 * @param webSecurityConfiguration
	 * @return
	 * @throws Exception
	 */
	@Bean(AGGREGATE_SPRING_SECURITY_FILTER_CHAIN_ID)
	Filter aggregateSpringSecurityFilterChain(WebSecurityConfiguration webSecurityConfiguration) throws Exception {
		FilterChainProxy javaConfigFcp = (FilterChainProxy) webSecurityConfiguration.springSecurityFilterChain();
		return new FilterChainProxy(javaConfigFcp.getFilterChains());
	}

}
```

Then ensure your XML configuration picks it up:

```xml
<bean id="aggregateConfiguration" class="testapp.AggregateSpringSecurityConfiguration" />
```

Finally, you need to update your web.xml to use the bean named `aggregateSpringSecurityFilterChain` instead of `springSecurityFilterChain`.

```xml
	<filter>
		<!-- matches AggregateSpringSecurityConfiguration.AGGREGATE_SPRING_SECURITY_FILTER_CHAIN_ID -->
		<filter-name>aggregateSpringSecurityFilterChain</filter-name>
		<filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
	</filter>

	<filter-mapping>
		<filter-name>aggregateSpringSecurityFilterChain</filter-name>
  		<url-pattern>/*</url-pattern>
	</filter-mapping>
```

I created a PR for your sample repository that demonstrates the fixes. The PR also adds some tests so that you can test without starting a container. See the commit history for comments as well. https://github.com/KWSimon/minoshill/pull/1

**Comment by KWSimon** [comment]
Thanks a lot @rwinch for the explanation, the suggested solution and the sample. I might not use it immediately to avoid breaking changes since I'm working on a library and doesn't have control on the web.xml file of the applications. But I'll do it as soon as I see an opportunity.

**Comment by hellokkiyer** [comment]
@rwinch , @KWSimon
I recently tried this setup in my spring mvc application and I am getting this error:

```
Caused by: org.springframework.security.config.annotation.AlreadyBuiltException: This object has already been built
		at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:41)
		at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.springSecurityFilterChain(WebSecurityConfiguration.java:121)
		at com.test.abc.security.oauth2.config.AggregateSpringSecurityConfiguration.aggregateSpringSecurityFilterChain(AggregateSpringSecurityConfiguration.java:22)
		at com.test.abc.security.oauth2.config.AggregateSpringSecurityConfiguration$$SpringCGLIB$$0.CGLIB$aggregateSpringSecurityFilterChain$0(<generated>)
		at com.test.abc.security.oauth2.config.AggregateSpringSecurityConfiguration$$SpringCGLIB$$FastClass$$1.invoke(<generated>)
		at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
		at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:348)
		at com.test.abc.security.oauth2.config.AggregateSpringSecurityConfiguration$$SpringCGLIB$$0.aggregateSpringSecurityFilterChain(<generated>)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:569)
		at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:146)
```
Is there any other solution available for mixing xml and java based securityFilterChain ?
