### ISSUE TITLE
SEC-861: Set TargetResolverimpl justUseSavedRequestOnGet to false by default

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1116]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-861":https://jira.spring.io/browse/SEC-861?redirect=false]) said:

We are coming across a lot of situations where supporting a POST request makes sense (particularly with Spring Web Flow), so ths property should really default to false.

**Comment by spring-issuemaster** [comment]
This issue is related to #772
