### ISSUE TITLE
Feature-branch build should fail if its main-branch Antora configuration is missing

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#11179]
When a feature branch is added, like `5.8.x`, it currently needs to be added to the `antora-playbook.yml` and `local-antora-playbook.yml` files on the `main` branch, which is easy to forget to do.

It would be nice if there were a build step that checked this.

**Comment by rwinch** [comment]
This has been resolved via 466b882d8226bcb6ce3796d9286eab6c67607dcd by using patterns within the [branches key](https://docs.antora.org/antora/latest/playbook/content-branches/#branches-key).
