### ISSUE TITLE
SAML 2.0 Logout filters should match on any request by default

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-security#11182]
**Describe the bug**
Each `RelyingParty` can specify its own logout URL properties, but doing that results in having to change the `RequestMatcher` used by `Saml2LogoutRequest/ResponseFilter` manually to match those different URLs. It could be confusing to allow multiple relying parties to be defined with different locations that ultimately have no effect (or an undefined effect) on the behavior.

In both the logout request and logout response filters, the payload validation is going to check the URI against the registration's configured URI, anyway. With that said, we should change the default `RequestMatcher` in the logout filters to match any request by default.

**Expected behavior**
`Saml2LogoutRequestFilter` and `Saml2LogoutResponseFilter` should match on any request by default.

Related:
 - https://github.com/spring-projects/spring-boot/issues/30128

**Comment by marcusdacoregio** [comment]
Both the login filters and logout filters match on requests that contain either `SAMLRequest` or `SAMLResponse` as a parameter. If the Logout filters match on any request, they will try to process requests for login as well, causing problems.

**Comment by jzheaux** [comment]
Another scenario to consider is that sometimes the logout link is clicked when the user is already logged out. In this circumstance, the relying party must be looked up from the URL in order to still provide a logout response to the IdP.
