### ISSUE TITLE
The title of Digest Authentication document doesn't render properly

### ISSUE THREAD

**Issue by skaifun** [spring-projects/spring-security#11272]
**Describe the bug**
The title of Digest Authentication in document (path: `servlet/authentication/passwords/digest.adoc`) doesn't render properly.

**To Reproduce**
https://docs.spring.io/spring-security/reference/servlet/authentication/passwords/digest.html

**Expected behavior**
The title "Digest Authentication" should render as a h1 element.

**Comment by sjohnr** [comment]
Thanks @skaifun! I believe it's just missing a newline before `=`. Are you interested in submitting a PR?

**Comment by skaifun** [comment]
I have submitted a PR. And I think the extra * symbol caused the problem.

**Comment by sjohnr** [comment]
Thanks @skaifun. I missed that because I was viewing it in the github rendered preview.
