### ISSUE TITLE
Support multiple SingleLogoutService bindings

### ISSUE THREAD

**Issue by emopti-jrufer** [spring-projects/spring-security#11286]
**Expected Behavior**

Should be specify mulitple SingleLogoutService bindings. This would be incorporated into  Saml2LogoutRequestFilter, Saml2LogoutResponseFilter and OpenSamlMetadataResolver.

**Current Behavior**

RelyingPartyRegistration only support adding a single singleLogoutServiceBinding.

**Context**

Trying to migrate off of Spring SAML Extension. Existing behavior in the Spring SAML Extension allows support for multiple SLO bindings. 

Have not identified a workaround. This is preventing us from migrating since we currently support both REDIRECT and POST bindings for the SingleLogoutService and are unable to migrate all customers to utilize a single binding.

**Comment by jzheaux** [comment]
Hi, @emopti-jrufer, thanks for the suggestion and the PR. We'll take a look and see if it's feasible to add into the next milestone release.
