### ISSUE TITLE
SEC-875: SavedRequestAwareRequestWrapper causes duplication of URL parameters

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1130]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-875":https://jira.spring.io/browse/SEC-875?redirect=false]) said:

The changes for SEC-830 and SEC-857 appear to have cause an issue with duplicate parameter values appearing when getParameterValues() is called on the wrapper. This will only apply to URL parameters. When deciding how to combine the values from the saved and wrapped request (or if we should), then whether they both contain the same values should be take into account.

**Comment by spring-issuemaster** [comment]
This issue is related to #1091
This issue is related to #1113
