### ISSUE TITLE
phoneNumberVerified field is Boolean type

### ISSUE THREAD

**Issue by ziponia** [spring-projects/spring-security#11315]
https://github.com/spring-projects/spring-security/blob/b78a28be5fa714f8f6afe283a9b468969ff8cc43/oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/oidc/OidcUserInfo.java#L252-L254

[https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.5.1](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.5.1)

According to the documentation, `phoneNumberVerified` must be of type Boolean.

**Comment by sjohnr** [comment]
Thanks for the report, @ziponia! It looks like this method could be deprecated in the 5.8.x branch and a new method with type `boolean` added. The getter in `StandardClaimsAccessor` already returns a `boolean`.

Are you interested in submitting a PR for this?

**Comment by ziponia** [comment]
@sjohnr

ok! i submitted PR.
If it's not enough, please tell me again
