### ISSUE TITLE
SEC-877: Extension of AbstractPreAuthenticatedProcessingFilter, which obtains username and other values supplied in the request.

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1132]
["Valery Tydykov":https://jira.spring.io/secure/ViewProfile.jspa?name=isobretatel](Migrated from ["SEC-877":https://jira.spring.io/browse/SEC-877?redirect=false]) said:

Extension of AbstractPreAuthenticatedProcessingFilter, which obtains username and other values supplied in the request
(in headers, or in cookies, or in HttpServletRequest.getRemoteUser()), for use with SSO systems.
Has additional usernameSource property.

Extension of WebAuthenticationDetailsSource, which obtains arbitrary attributes supplied in the request. Defines source of the attributes associated with pre-authenticated authentication request. The attributes can be supplied in the cookies, request header, or property (configuration file).

**Comment by spring-issuemaster** [comment]
This issue is related to #1133
This issue is related to #1138
