### ISSUE TITLE
Simplify Java Configuration RequestMatcher Usage

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#11347]
By default, we should reject using the built in RequestMatcher implementations other than MvcRequestMatcher in a MvcRequestMatcher application.

Alternatively we can deprecate/remove antMatcher, regexMatchers, and mvcMatchers from the DSL and have a requestMatcher that is automatic based on the classpath. Users that want to opt out of this would need to use `requestMatchers(new RegExRequestMatcher(...))`. This makes it much more difficult to get the wrong configuration.

**Comment by evgeniycheban** [comment]
I can take this.

**Comment by rwinch** [comment]
@evgeniycheban Thank you for the volunteering. This is going to be a pretty tricky issue with quite a bit of design necessary. For that reason, I'm not sure if it is an ideal for contribution issue.
