### ISSUE TITLE
Remove `final` from `SecurityExpressionRoot::getAuthentication`

### ISSUE THREAD

**Issue by ch4mpy** [spring-projects/spring-security#11356]
Please remove `final` keyword from `getAuthentication()` signature so that `SecurityExpressionRoot` descendents can override  `getAuthentication()` returned type with a specific `Authentication` implementation.

`SecurityExpressionRoot`, takes an `Authentication` as constructor param.

When providing an implementation for this abstract class, I know which type of `Authentication` I'm providing to parent constructor and would like to avoid a cast after each `getAuthentication()` call.

**Comment by rwinch** [comment]
This is intended for use with SpEL. Please provide a complete example of how you are using this in a way that needs a cast.
