### ISSUE TITLE
Spring Security 5.7 xsd is not published to https://www.springframework.org/schema/security/

### ISSUE THREAD

**Issue by elishaebenezer** [spring-projects/spring-security#11353]
### Summary

spring-security-5.7.xsd should be published under https://www.springframework.org/schema/security/

### Actual Behavior

spring-security-5.7.xsd is not available under https://www.springframework.org/schema/security/ causing XML schema validation failures in IDEs

### Expected Behavior

spring-security-5.7.xsd should be available under https://www.springframework.org/schema/security/  to enable successful XML schema validation in IDEs

### Version

Spring Security 5.7.1

**Comment by sjohnr** [comment]
Thanks for the report @elishaebenezer! We will look into this.

**Comment by sjohnr** [comment]
**Note:** Per recommendation from @trevormarshall, we can replace the `htdocs/schema/security` directory (which serves `https://www.springframework.org/schema/security/`) with a softlink to `/opt/www/domains/spring.io/docs/htdocs/autorepo/schema/spring-security/current`. This will allow the current process of uploading the schema files (along with our docs) to the autorepo directory to automatically publish the latest schema.

cc: @jzheaux

**Comment by cgraefe** [comment]
We've had issues this morning due to a missing schema at https://www.springframework.org/schema/security/spring-security-oauth2.xsd which was available, previously. Could this be caused by by the softlink quick-fix mentioned above? Should this be intentional, what would be the correct new location for the spring-security-oauth2.xsd?

**Comment by Kdecherf** [comment]
@cgraefe see #11357

**Comment by sjohnr** [comment]
@cgraefe I haven't performed this task yet, so they are unrelated in this case.
