### ISSUE TITLE
KeyInfo missing in AuthnRequest when using OpenSaml4AuthenticationRequestResolver

### ISSUE THREAD

**Issue by chschu** [spring-projects/spring-security#11354]
**Describe the bug**
When switching from the (deprecated) `DefaultSaml2AuthenticationRequestContextResolver` and `OpenSaml4AuthenticationRequestFactory` to `OpenSaml4AuthenticationRequestResolver`, the `AuthnRequest`'s signature no longer contains a `KeyInfo` element.

**To Reproduce**
- configure an `OpenSaml4AuthenticationRequestResolver` (e.g. by adding it as a Spring Bean)
- configure an X.509 signing credential
- start a SAML authentication

**Expected behavior**
The `AuthnRequest` signature contains a `KeyInfo` when using `OpenSaml4AuthenticationRequestResolver`.

Possible source: In `org.springframework.security.saml2.provider.service.web.authentication.OpenSamlSigningUtils`, no `NamedKeyInfoGeneratorManager` is configured in the `SignatureSigningConfiguration`. This is different from the two `OpenSamlSigningUtils` in other packages.

**Comment by jzheaux** [comment]
Thanks, @chschu, for the report. We will prioritize getting this into the next point release.
