### ISSUE TITLE
spring-security-oauth2.xsd is gone

### ISSUE THREAD

**Issue by whaan** [spring-projects/spring-security#11359]
**Describe the bug**
http://www.springframework.org/schema/security/spring-security-oauth2.xsd is gone
This breaks startup of all our applications because we rely on getting the XSD files from the spring website, but now the XSD files have been removed.

<img width="712" alt="Screen Shot 2022-06-10 at 07 45 41" src="https://user-images.githubusercontent.com/77047327/173002183-52988d0b-d4cf-4060-808d-54fed31bd97a.png">

Could the XSD be fixed urgently in the meantime?

**To Reproduce**
visit http://www.springframework.org/schema/security/spring-security-oauth2.xsd and verify that the XSD is gone

**Expected behavior**
spring-security-oauth2.xsd should be present at http://www.springframework.org/schema/security/spring-security-oauth2.xsd at all time.

**References**
This has happened before in 2020:

- [http://www.springframework.org/schema/security/spring-security.xsd is gone!?IN: CONFIG](https://github.com/spring-projects/spring-security/issues/8104) 
- [Failed to read schema document 'http://www.springframework.org/schema/security/spring-security-oauth2.xsd'STATUS: WAITING-FOR-TRIAGE](https://github.com/spring-attic/spring-security-oauth/issues/1835)  
- [Provide spring-security-5*.xsd for https://www.springframework.org/schema/security/IN: CONFIG](https://github.com/spring-projects/spring-security/issues/8091)

**Comment by lukasondrak96** [comment]
Check this closed issue: #11357

**Comment by MikeN123** [comment]
I feel that, given the existing issue with using the XSD from the JAR in the spring-security-oauth project, this is a bit of a weird move. It breaks apps all over the place and there is really no good reason to inflict so much damage...

**Comment by whaan** [comment]
switching the url from http to https actually fixed the issue for us.

FYI: https://www.springframework.org/schema/security/spring-security-oauth2-2.0.xsd
also returns 404 , page not found, but that is not an issue, because in the [spring.schemas](https://github.com/spring-attic/spring-security-oauth/blob/2.3.x/spring-security-oauth2/src/main/resources/META-INF/spring.schemas) file in the META-INF folder, all requests for `https\://www.springframework.org/schema/security/spring-security-oauth2.xsd` get redirected to  `org/springframework/security/oauth2/spring-security-oauth2-2.0.xsd`

![Screen Shot 2022-06-10 at 13 12 04](https://user-images.githubusercontent.com/77047327/173053109-d12a22d0-e0fa-47b2-9c41-3eadb418fd8e.png)

So the XSD doesn't have to looked up from the internet. As long as you use https, it will simply look it up from the classpath

**Comment by jgrandja** [comment]
@whaan Closing this as a duplicate. Please see [comment](https://github.com/spring-projects/spring-security/issues/11357#issuecomment-1151443885)
