### ISSUE TITLE
OnCommittedResponseWrapper.java，Can you add null protection here

### ISSUE THREAD

**Issue by li-yongji** [spring-projects/spring-security#11352]
**Expected Behavior**

**spring-security-main\web\src\main\java\org\springframework\security\web\util\OnCommittedResponseWrapper.java，public PrintWriter append(CharSequence csq)，if csq is null。then throw nullpointerException。Can you add null protection here **

**Context**

**Comment by li-yongji** [comment]
The business configures the security response header for the interface. If the interface returns null, the security response header filter will throw an exception。

**Comment by sjohnr** [comment]
Hi @li-yongji.

> The business configures the security response header for the interface.

Apologies, but I'm not able to determine your use case from the information provided. Please provide a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the issue. I'm going to close this request, but feel free to provide a sample and we can re-open to investigate further.
