### ISSUE TITLE
Add an option to customize ServerRedirectStrategy in the OAuth2AuthorizationRequestRedirectWebFilter 

### ISSUE THREAD

**Issue by igorbolic** [spring-projects/spring-security#11373]
It would be nice to be able to customize the redirect strategy within `OAuth2AuthorizationRequestRedirectWebFilter`, so that we are able to return to the client e.g. HTTP Status **200 OK** with redirect URL in the response payload, instead of the default behavior of HTTP Status **302 Found** with **Location** header containing redirect URL.

Our FE is SPA and BE is Spring Boot application. The FE uses [XMLHttpRequests](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) client to retrieve the redirect URL from our BE service for the OAuth authorization flow.
The current `OAuth2AuthorizationRequestRedirectWebFilter`'s response causes the FE client library to automatically follow **Location** URL. 
Sending the response as HTTP Status **200 OK** and having redirect URL as part of the payload via custom `ServerRedirectStrategy`, would allow us inform the FE client of the redirect URL and use the value to send the user to the OAuth providers page for authorization.

ATM we have a custom implementation of `OAuth2AuthorizationRequestRedirectWebFilter`, where we have changed only the `ServerRedirectStrategy` to achieve the above mentioned behavior.

**Comment by rwinch** [comment]
Thanks for reaching out @igorbolic Would you be interested in submitting a pull request for this?

**Comment by igorbolic** [comment]
Of course, I'll try to find some time this week... Thanks for quick reply 👍

**Comment by igorbolic** [comment]
@rwinch I've created a PR #11387 to resolve this issue

**Comment by rwinch** [comment]
Closing this as duplicate in favor of gh-11387
