### ISSUE TITLE
SEC-883: RoleHierarchyVoter

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1141]
["Thomas Champagne":https://jira.spring.io/secure/ViewProfile.jspa?name=lafeuil](Migrated from ["SEC-883":https://jira.spring.io/browse/SEC-883?redirect=false]) said:

With the current role hierarchy implementation, you must use a UserDetailService and use the wrapper UserDetailsServiceWrapper in hierarchicalroles package. 

In the forum, Luke sayed it would be better to use voters because it's not a good solution to modify the userDetails for each user : 
http://forum.springframework.org/showpost.php?p=185994&postcount=2

There is an implementation of RoleHierarchyVoter  in the forum thread.

Thomas

**Comment by spring-issuemaster** [comment]
This issue supersedes #1124
