### ISSUE TITLE
AbstractWebClientReactiveOAuth2AccessTokenResponseClient use WebClientCustomizer to customize the webclient rather that using a setter

### ISSUE THREAD

**Issue by lmcdasi** [spring-projects/spring-security#11445]
Hi,

   Would it be possible for AbstractWebClientReactiveOAuth2AccessTokenResponseClient to have the WebClient instance customized by a WebClientCustomizer bean ?
   Since the  WebClientAutoConfiguration proposes the WebClient.Builder webClientBuilder(ObjectProvider<WebClientCustomizer> customizerProvider) to customize a webclient, it looks to me akward that I have to replace the webclient via a setter. And when doing so I have to cast to proper class.
    Thx.

BR,
Dan S.

**Comment by sjohnr** [comment]
Hi @lmcdasi, thanks for reaching out!

> And when doing so I have to cast to proper class.

Can you give an example or explain what you mean by this?

**Comment by lmcdasi** [comment]
I can do it without casting if the accessTokenResponseClient is set as the Abstract class.

`AbstractWebClientReactiveOAuth2AccessTokenResponseClient<OAuth2ClientCredentialsGrantRequest> **accessTokenResponseClient** =
                    new WebClientReactiveClientCredentialsTokenResponseClient();
 accessTokenResponseClient.setWebClient(webClientBuilder.build());
lientCredentialsProvider = new ClientCredentialsReactiveOAuth2AuthorizedClientProvider();
            clientCredentialsProvider.setAccessTokenResponseClient(**accessTokenResponseClient**);`

I still think the webclientbuilder injection would be more of a 'spring framework' way of working rather than codding the setter myself.

At the same time why not using proxyWithSystemProperties() in the abstract class directly, since if proxy is not present it would do as it is now ...

`@Component
public class OauthWebClientCustomizer implements WebClientCustomizer {
    private static final Logger LOGGER = LoggerFactory.getLogger(OauthWebClientCustomizer.class);

    @Override
    public void customize(Builder webClientBuilder) {
        LOGGER.info("WebClientCustomizer - customize webclient proxyWithSystemProperties if present");
        webClientBuilder.clientConnector(new ReactorClientHttpConnector(HttpClient.create()
                .proxyWithSystemProperties()));
    }
}`
