### ISSUE TITLE
Improve RememberMe docs

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-security#11450]
The [RememberMe docs](https://docs.spring.io/spring-security/reference/servlet/authentication/rememberme.html) is pretty light on configuration samples, there are only XML configuration fragments.

It should be improved with at least a more modern way to configure it, using Java Configuration and defining the Beans from a Java class.

**Comment by priya1712d** [comment]
Hello!
Can I work on this?

**Comment by marcusdacoregio** [comment]
Hi @priya1712d, of course, the ticket is yours!

Feel free to ask any questions about the solution here.

**Comment by cotnic** [comment]
Hello @marcusdacoregio, it seems this issue is not being worked on. Could I take it over?

**Comment by marcusdacoregio** [comment]
Hello @cotnic. It's been a while since we had an update about this.

@cotnic I think it should be fine for you to work on this. If @priya1712d is still willing to work on this issue you can both work on the doc and the PR review.

**Comment by petrovskimario** [comment]
Is this resolved ? 
If not i can pick this up

**Comment by marcusdacoregio** [comment]
Hi @petrovskimario, this is not resolved yet.

It became stale because we have not had any updates from @cotnic and @priya1712d.
I'll assign it to you then. Thanks!

**Comment by petrovskimario** [comment]
Hello @marcusdacoregio 
I have submitted a pull request which provides the Java beans configuration.
Please review and if you have any suggestions for improving, let me know.
