### ISSUE TITLE
Outdated example in Javadoc of UrlAuthorizationConfigurer

### ISSUE THREAD

**Issue by deeaitche** [spring-projects/spring-security#11487]
The example in Javadoc of ``UrlAuthorizationConfigurer`` is referring its default constructor that no longer exists.

**Comment by cotnic** [comment]
Hello, @marcusdacoregio I opened a PR for this issue. Hope it is still relevant and resolves the issue that was exposed. The PR is available https://github.com/spring-projects/spring-security/pull/12103.

**Comment by cotnic** [comment]
@marcusdacoregio I've prepared the PR https://github.com/spring-projects/spring-security/pull/12147 and if it is necessary this issue can be assigned to me.

**Comment by marcusdacoregio** [comment]
Fixed via https://github.com/spring-projects/spring-security/commit/f39f215140ebf042852935a0bc61cccef289fd5e
