### ISSUE TITLE
Add remaining methods from ExpressionUrlAuthorizationConfigurer to MessageMatcherDelegatingAuthorizationManager

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#11509]
Related #11360 

- [ ] Add `rememberMe` to `MessageMatcherDelegatingAuthorizationManager`
- [ ] Add `fullyAuthenticated` to `MessageMatcherDelegatingAuthorizationManager`
- [ ] Add `anonymous` to `MessageMatcherDelegatingAuthorizationManager`

**Comment by evgeniycheban** [comment]
@jzheaux I can take this.

**Comment by sjohnr** [comment]
@evgeniycheban unless you or anyone else is aware of a reason we have to have this in the 5.8.0-M1 milestone, I'm going to move this to 5.8.0-M2 in preparation for Monday's release. Josh is out on PTO today so I'm not sure anyone would review a PR if it were to get submitted this weekend (in case that is your plan). Thanks for volunteering!
