### ISSUE TITLE
Add isFullyAuthenticated to AuthenticatedTrustResolver

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#11510]
Since `isFullyAuthenticated` is a composition of `isAnonymous` and `isRememberMe`, a default convenience method can be added:

```java
default boolean isFullyAuthenticated(Authentication authentication) {
    return !isAnonymous(authentication) && !isRememberMe(authentication)
}
```

This would be nice for `SecurityExpressionRoot#isFullyAuthenticated` and [`AuthenticatedAuthorizationManager#fullyAuthenticated`](https://github.com/spring-projects/spring-security/pull/11495)

**Comment by karthikeyan-r** [comment]
Can i work on this implementation ?

**Comment by jzheaux** [comment]
Yep! The issue is yours.
