### ISSUE TITLE
使用这个spring-security-oauth2-authorization-server做为认证服务器时，资源服务器使用什么依赖来管理资源？ boot-starter-security?

### ISSUE THREAD

**Issue by ArchieSean-YH** [spring-projects/spring-security#11600]
**Expected Behavior**

**Current Behavior**

**Context**

**Comment by jzheaux** [comment]
Thanks for reaching out, @ArchieSean-YH. If you are reporting a bug or feature request, please re-post in English. If you've got a question, please post on [StackOverflow](https://stackoverflow.com).

**Comment by ArchieSean-YH** [comment]
> Thanks for reaching out, @ArchieSean-YH. If you are reporting a bug or feature request, please re-post in English. If you've got a question, please post on [StackOverflow](https://stackoverflow.com).

Thanks ,I'll ask stackoverflow.
