### ISSUE TITLE
Getting 401 Error on /userinfo endpoint call 

### ISSUE THREAD

**Issue by mak0128** [spring-projects/spring-security#11639]
### Summary
I have setup the Spring security authorization server which has a client registered in its registry. I have configured the authorization server with formLogin so that when a user tries to login to client app, it is thrown a login page by auth server.
Other side I have client app that uses spring-boot-starter-oauth2-client module to integrate with auth server. My integration is openid based for scopes (openid, email, profile) 

Everything is fine when I am accessing a controller endpoint in my client app if the scope is configure only with openid. I know in case of only openid scope the /userinfo endpoint is not called by client on auth server. If I configure multiple scopes like openid, email, profile then the /userinfo endpoint is called but the auth server is returning the 401 error. 

I tried to debug the filter chain in auth server side and I found there is no filter to server the /userinfo endpoint. Am I missing something in configuration.  

### Actual Behavior

Auth server is throwing the 401 error when /userinfo endpoint is called by client app. Here is the code I am using in client app.

  @Bean
  SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
    http
        .csrf().disable()
        .authorizeRequests(authorizeRequests -> authorizeRequests.anyRequest().authenticated())
        .oauth2Login(oauth2Login -> oauth2Login.loginPage("/oauth2/authorization/articles-client-oidc")
            .userInfoEndpoint()
            // .userAuthoritiesMapper(this.userAuthoritiesMapper())
            .oidcUserService(this.oidcUserService()))
        .oauth2Client(withDefaults());
    return http.build();
  }

  private OAuth2UserService<OidcUserRequest, OidcUser> oidcUserService() {
    final OidcUserService delegate = new OidcUserService();

    return (userRequest) -> {
      String userInfoUri = userRequest.getClientRegistration().getProviderDetails().getUserInfoEndpoint().getUri();

      // Delegate to the default implementation for loading a user
      OidcUser oidcUser = delegate.loadUser(userRequest);

      OAuth2AccessToken accessToken = userRequest.getAccessToken();
      Set<GrantedAuthority> mappedAuthorities = new HashSet<>();

      // 3) Create a copy of oidcUser but use the mappedAuthorities instead
      oidcUser = new DefaultOidcUser(mappedAuthorities, oidcUser.getIdToken(), oidcUser.getUserInfo());

      return oidcUser;
    };
  }

### Configuration

    @Bean
    @Order(Ordered.HIGHEST_PRECEDENCE)
    public SecurityFilterChain authServerSecurityFilterChain(HttpSecurity http) throws Exception {
        OAuth2AuthorizationServerConfiguration.applyDefaultSecurity(http);
        return 
            http
            .csrf().disable()
            .cors().disable()
            .formLogin((formLogin) -> 
                formLogin.loginPage(formLoginUrl)
                    .loginProcessingUrl(contextPath+"/openid/authenticate")
            )
            .addFilterAfter(legacyTokenCheckFilter(), LogoutFilter.class)
            .build();
    }

### Version

implementation group: 'org.springframework.security', name: 'spring-security-oauth2-authorization-server', version: '0.3.1'

**Comment by jgrandja** [comment]
@mak0128 We'll enhance the samples to show how to configure. Please track [spring-authorization-server#847](https://github.com/spring-projects/spring-authorization-server/issues/847)

**Comment by Vageesh-Jayaraman** [comment]
Even we used `spring-boot-starter-oauth2-authorization-server` and `spring-boot-starter-oauth2-client` for our project, and we pretty much ended up with the same error:

---

### How it all started...

My server was running on port 8000 (`localhost:8000`) and client in 8080 (`127.0.0.1:8080`).  
Now, once I go to `127.0.0.1:8080`, it would redirect me to `localhost:8000/login`.  
But even after a successful login, I wasn't redirected back to the client and instead was redirected to: `localhost:8000/login?error` where we got this error message: **`ERR_TOO_MANY_REDIRECTS`**

---

### So we added the below lines in the server's `application.yml`:

```yaml
logging:
  level:
    org.springframework.security.oauth2: TRACE
    org.springframework.security.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.session: DEBUG
```

Now, if we ran it again, the logs were pretty clear and we got the below log:

```
org.springframework.security.oauth2.core.OAuth2AuthenticationException: [invalid_user_info_response] 
An error occurred while attempting to retrieve the UserInfo Resource from 'http://localhost:8000/userinfo': 
response contains invalid content type 'text/html;charset=UTF-8'. 
The UserInfo Response should return a JSON object (content type 'application/json') that contains a collection of name and value pairs 
of the claims about the authenticated End-User. 
Please ensure the UserInfo Uri in UserInfoEndpoint for Client Registration 'idp-server' conforms to the UserInfo Endpoint, 
as defined in OpenID Connect 1.0: 'https://openid.net/specs/openid-connect-core-1_0.html#UserInfo'
```

---

###  So what did we do finally?

In the `SecurityConfig.java` file of the Authorization Server, we modified the below function:

```java
@Bean
public AuthorizationServerSettings authorizationServerSettings(){
    return AuthorizationServerSettings.builder()
           .issuer("http://localhost:8000") // Server url
           .oidcUserInfoEndpoint("/userinfo") // added this line
           .build();
}
```


### 🎉 And it worked like a charm!!!
