### ISSUE TITLE
SEC-911: Make petclinic tutorial Spring 2.5.5 compatible

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1164]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-911":https://jira.spring.io/browse/SEC-911?redirect=false]) said:

It now requires the instrumented classloader in tomcat, as per the readme.

**Comment by spring-issuemaster** [comment]
This issue is related to https://jira.spring.io/browse/SPR-4992
