### ISSUE TITLE
SEC-913: SwitchUserProcessingFilter modifies the switchFailureUrl member variable on failure

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1166]
["Niklas Therning":https://jira.spring.io/secure/ViewProfile.jspa?name=niklas@trillian.se](Migrated from ["SEC-913":https://jira.spring.io/browse/SEC-913?redirect=false]) said:

The code in redirectToFailureUrl() prepends the contextPath to the member variable every time there is a failure. If the contextPath isn't "" this means that the second time there is a failure the client will be redirected to an invalid page. Here's the faulty code:

```
    if (switchFailureUrl != null) {
        switchFailureUrl = request.getContextPath() + switchFailureUrl;
        response.sendRedirect(response.encodeRedirectURL(switchFailureUrl));
    } else {
```

Why not use the sendRedirect() method which is used for targetUrl? E.g.:

```
    if (switchFailureUrl != null) {
        sendRedirect(request, response, switchFailureUrl);
    } else {
```

This fix also means that the useRelativeContext property will actually be used also on failures. I think the user of SwitchUserProcessingFilter would expect that.

**Comment by spring-issuemaster** [comment]
This issue is related to #1005
