### ISSUE TITLE
Re-add support for CAS

### ISSUE THREAD

**Issue by xhaggi** [spring-projects/spring-security#11674]
The CAS client (4.0.0-SNAPSHOT) has just been updated to JDK 17 + Jakarta EE.

https://github.com/apereo/java-cas-client/commit/496adb1cf6bcc4ec55e7911c5eb5b75b5325bdf6

**Comment by marcusdacoregio** [comment]
Hi @xhaggi, thanks for the report.

In order to re-add the support, we need to ensure that there is a GA release before our scheduled GA release. I'll keep an eye on the repository and when there is a new milestone or GA release we can assign it accordingly to ours.

**Comment by o-frias** [comment]
Apereo has just published [cas-client-4.0.0-RC1](https://github.com/apereo/java-cas-client/releases/tag/cas-client-4.0.0-RC1)

Maybe this helps

**Comment by marcusdacoregio** [comment]
I could not find the schedule for the GA, therefore we cannot add the support now since we are not sure that there is gonna be a GA release before ours. Anyway, the support can be re-added in a minor version.

**Comment by marcusdacoregio** [comment]
When the CAS support is re-added we should consider https://github.com/spring-projects/spring-security/pull/9881

**Comment by marcusdacoregio** [comment]
Java CAS Client v4 has been released https://github.com/apereo/java-cas-client/releases/tag/v4.0.0

**Comment by marcusdacoregio** [comment]
The issue https://github.com/spring-projects/spring-security/issues/12304 should be addressed while re-adding the support

**Comment by marcusdacoregio** [comment]
Closed via https://github.com/spring-projects/spring-security/commit/b4d3ac6665dfe291d64525c72f80c953293bbb2b, https://github.com/spring-projects/spring-security/commit/e0284a450307cd3b4be862ea0013e9a73053cc4b and https://github.com/spring-projects/spring-security/commit/04369cf2da962c662066dee7ee670641f500fdf9

**Comment by marcusdacoregio** [comment]
Hi folks, the support has been re-added. It would be great if folks tried the 6.1.0-SNAPSHOT and give some feedback about it before the GA. Thanks!

**Comment by ElKhattoutiMohamed** [comment]
Just tried the 6.1.0-SNAPSHOT, it works just fine in my project.

**Comment by chavocarlos** [comment]
> Just tried the 6.1.0-SNAPSHOT, it works just fine in my project.

Hello @ElKhattoutiMohamed, I am developing some project using spring-security 6.2 and CAS 7, and have some problems validating the ticket in the spring app that cause an improperly redirection. Can you guide me in some way? due that you got fine with your project. 

Regards a lot buddy.
