### ISSUE TITLE
SAML2 Login fails with CSP in chrome based browsers

### ISSUE THREAD

**Issue by torstenwerner** [spring-projects/spring-security#11676]
I have checked out the branch 5.8.x, started 

    ./gradlew :servlet:spring-boot:java:saml2:login:bootRun

and opened http://localhost:8080/ . It redirects to http://localhost:8080/saml2/authenticate/one but this page fails with this error message

    Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'sha256-ePniVEkSivX/c7XWBGafqh8tSpiRrKiqYeqbG7N1TOE='". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

in the javascript console of chromium based browsers. The form submit does not work. The CSP (Content Security Policy) is inlined in the HTML of the page as a &lt;meta&gt; element.

It works in firefox. But that would exclude a majority of users.

If it is possible to turn off the inline CSP I would be happy to use it as a quick workaround.

**Comment by marcusdacoregio** [comment]
One option that we have is instead of relying on the HTML event handler `onload` attribute, we could add:
```html
<script>window.onload = () => document.forms[0].submit();</script>
```

Recompute the hash for this javascript and add in the meta-tag
