### ISSUE TITLE
ReactiveSecurityContextHolder.getContext() is null always with custom AuthenticationToken (Sample provided)

### ISSUE THREAD

**Issue by Nida96** [spring-projects/spring-security#11722]
val messageByUsername: Mono<String>  = ReactiveSecurityContextHolder.getContext()
                        .map(SecurityContext::getAuthentication)
                        .map(Authentication::getName)

always returns null, even when authentication has been done.

Code for authentication : 
 return webFilterChain.filter(serverWebExchange).contextWrite {
                    var cont = ReactiveSecurityContextHolder.withSecurityContext(
                        Mono.just(
                            SecurityContextImpl(
                                injectSecurityPrincipal(reqHeaders[USER_ID_ATTRIBUTE]!!.first(), scopes)
                            )
                        )
                    )

**Comment by sjohnr** [comment]
Duplicate of gh-11721.
