### ISSUE TITLE
SEC-919: Introduce new JdbcUserDetailsService class with extended user properties as an alternative to JdbcDaoImpl

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1172]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-919":https://jira.spring.io/browse/SEC-919?redirect=false]) said:

JdbcDaoImpl only supports the "enabled" flag for backward compatibility issues. This could be expanded for the next major release.

**Comment by ro0sterjam** [comment]
So is this not going to be handled?

**Comment by rwinch** [comment]
@ro0sterjam Honestly, I'm not sure what else would be done (the issue was closed in 2009 within JIRA and just was migrated as closed recently)
