### ISSUE TITLE
Allow custom RestTemplate for ClientRegistrations.fromIssuerLocation 

### ISSUE THREAD

**Issue by joshiste** [spring-projects/spring-security#11760]
**Expected Behavior**

Allow to use custom RestTemplate configuration for ClientRegistrations.fromIssuerLocation.

**Current Behavior**

can't be customised

**Context**

need to configure custom certificate chain.

**Comment by jgrandja** [comment]
@joshiste Please see this [comment](https://github.com/spring-projects/spring-security/issues/8882#user-content-client-registrations):

> `ClientRegistrations` is intended to be used as a utility/convenience class. It was designed to fulfill most use cases, however, it may not be suitable for certain use cases. For example, if the internal network traffic must be routed through a Proxy, you can bypass discovery by configuring the `authorization-uri` and `token-uri` property instead of the `issuer-uri` property.
> 
> **NOTE:** The underlying HTTP Client used in `ClientRegistrations` was purposely encapsulated and there is no plan to expose it.
