### ISSUE TITLE
Improve OAuth2LoginConfigurer with more configuration options 

### ISSUE THREAD

**Issue by markixy** [spring-projects/spring-security#11770]
**Expected Behavior**

I want to customize the authenticationResultConverter field in the OAuth2LoginAuthenticationFilter.
just using such as `.oauth2Login().authorizationEndpoint().authenticationResultConverter(xxx)`

**Context**
spring-security-oauth2-client-5.7.1.jar

**Comment by marcusdacoregio** [comment]
Hi, @markixy. Have you tried using the `ObjectPostProcessor`?

```java
http
	.oauth2Login(Customizer.withDefaults())
	.objectPostProcessor(new ObjectPostProcessor<OAuth2LoginAuthenticationFilter>() {
		@Override
		public <O extends OAuth2LoginAuthenticationFilter> O postProcess(O object) {
			object.setAuthenticationResultConverter(myAuthenticationResultConverter);
			return object;
		}
	});
```

**Comment by markixy** [comment]
thanks, it works.
