### ISSUE TITLE
Setting logoutRequestRepository via Saml2LogoutConfigurer for LogoutFilter

### ISSUE THREAD

**Issue by filipvondracek** [spring-projects/spring-security#11790]
**Expected Behavior**
I would like to be able to set a `logoutRequestRepository` for `Saml2RelyingPartyInitiatedLogoutSuccessHandler` in `LogoutFilter` via `Saml2LogoutConfigurer`.

**Current Behavior**
Currently, I can set only `logoutRequestRepository` for `Saml2LogoutResponseFilter` via `Saml2LogoutConfigurer`.

**Context**
It is not possible to configure a repository to save Saml2LogoutRequest, so the request is not saved to the desired storage.

**Comment by jzheaux** [comment]
Duplicate of #11363
