### ISSUE TITLE
SEC-932: Map-based implementation for Attributes2GrantedAuthoritiesMapper

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1187]
["Yannick Menager":https://jira.spring.io/secure/ViewProfile.jspa?name=ymenager](Migrated from ["SEC-932":https://jira.spring.io/browse/SEC-932?redirect=false]) said:

Included in the attached zipfile is an additional map-based implementation for Attributes2GrantedAuthoritiesMapper, together with its unit test class.

**Comment by spring-issuemaster** [comment]
This issue duplicates #978
