### ISSUE TITLE
ProviderManager  eventPublisher  is null

### ISSUE THREAD

**Issue by tofdragon** [spring-projects/spring-security#11883]
**Describe the bug**

In version spring boot 2.6.8, eventPublisher was set up in ProviderManager as follows

` 
@Configuration
public class RestSecurityConfigurerAdapter extends WebSecurityConfigurerAdapter {
    	@Override
        protected void configure(HttpSecurity http) throws Exception {
       }   
}`
![image](https://user-images.githubusercontent.com/7513852/191165265-9682250e-0c28-4e70-815b-304849a9fe30.png)
![image](https://user-images.githubusercontent.com/7513852/191165334-77f8769d-4a84-44e3-b62e-b155d3b1e0a9.png)

In version spring boot 2.7.3, eventPublisher was set up null in ProviderManager as follows

![image](https://user-images.githubusercontent.com/7513852/191165630-725b1cf2-6ff2-4391-ace0-fc2498ca1c4d.png)

**To Reproduce**

`@Bean
public SecurityFilterChain restSecurityFilterChain(HttpSecurity http) throws Exception {
   return http.build();
 }`

**Expected behavior**
eventPublisher  is not null, The same behavior as Spring Boot 2.6.8 is guaranteed

**Comment by marcusdacoregio** [comment]
Hi @tofdragon, thanks for the report.

This was fixed via https://github.com/spring-projects/spring-security/issues/11449 and should be available in [Spring Security 5.6.8](https://github.com/spring-projects/spring-security/milestone/267).
