### ISSUE TITLE
AnonymousAuthenticationFilter should cache its Supplier<SecurityContext>

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#11900]
The `Supplier<SecurityContext>` in `AnonymousAuthenticationFilter` gets invoked several times on each request. Essentially, any time `getContext` is invoked downstream of it. While each call is quick, it seems a bit wasteful.

One way to cache it would be `SingletonSupplier`

**Comment by evgeniycheban** [comment]
Hey, @jzheaux I can work on this.
