### ISSUE TITLE
Default to Xor CSRF protection

### ISSUE THREAD

**Issue by sjohnr** [spring-projects/spring-security#11960]
We should default to Xor CSRF tokens in 6.0:

* Use `XorCsrfTokenRequestAttributeHandler` in `CsrfFilter`
* Use `XorServerCsrfTokenRequestAttributeHandler` in `CsrfWebFilter`

Related gh-4001

**Comment by GijsCalis** [comment]
This should also get mentioned in the migration guide to Spring Security 6.x as this is a breaking change for at least applications using Angular.
