### ISSUE TITLE
Saml2MetadataFilter response should configure writer to UTF-8

### ISSUE THREAD

**Issue by SebastianS90** [spring-projects/spring-security#12026]
In [this line](https://github.com/spring-projects/spring-security/blob/5.7.3/saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/Saml2MetadataFilter.java#L108), the `Saml2MetadataFilter` sends out the response without specifying an encoding. The response will therefore be encoded using the default `ISO-8859-1` encoding (see `getWriter` Javadoc).

However, the xml file itself starts with `<?xml version="1.0" encoding="UTF-8"?>`.

This results in a broken file when using `OpenSamlMetadataResolver.setEntityDescriptorCustomizer` to add a `<md:ServiceDescription>` element containing special characters like German umlauts (äöü).

**Comment by hschmachtel** [comment]
I fear the fix in [53148dc](https://github.com/spring-projects/spring-security/commit/53148dc7b50fb303469d328c9ae00c25095d42e6) still has a problem (wich is not easily detectable in the unit test):
The `Content-Length` header is set to the number of _characters_ in the string with the XML metadata, not the number of bytes in UTF-8 encoding.

Yes, the XML metadata gets written to the request completely, as shown by the test case, but browsers may (and do!) cut off the response after the given number of bytes has been reached. This results in a truncated XML metadata file being downloaded.
