### ISSUE TITLE
Possible misconfiguration of SecurityContextRepository

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-security#12023]
The default `SecurityContextRepository` for stateless applications is now `RequestAttributeSecurityContextRepository`. However, `SecurityContextConfigurer` sets the `SecurityContextRepository` to `HttpSessionSecurityContextRepository` if it isn't already set as a shared object. This results in the context being saved by the `RequestAttributeSecurityContextRepository` but loaded from `HttpSessionSecurityContextRepository` for an error dispatch.

**Comment by sjohnr** [comment]
Related gh-11026
