### ISSUE TITLE
SEC-950: LDAP bind fails if the search result contains special characters

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1206]
["Denis Cabasson":https://jira.spring.io/secure/ViewProfile.jspa?name=dcabasson](Migrated from ["SEC-950":https://jira.spring.io/browse/SEC-950?redirect=false]) said:

The LDAP binds fail if the returned DN contains special character. We have \ in our cns, so the returned DN is :
"CN=Cabasson\, Denis - SDD/DDS,OU=SDD-DDS,OU=INFO-INFO,OU=IMF-SIM"

The quotes are part of the returned string. Acegi then appends the searchbase, and the bind fails because the DN is malformed :
FINE: Creating InitialDirContext with environment {java.naming.provider.url=ldap://statcan.ca:389/dc=statcan,dc=ca, java.naming.factory.initial=com.sun.jndi.ldap.LdapCtxFactory, java.naming.security.principal=CN=ccadmin - SDD/DDS,OU=SDD-DDS,OU=INFO-INFO,OU=IMF-SIM,OU=STATCAN,DC=statcan,DC=ca, com.sun.jndi.ldap.connect.pool=true, java.naming.security.authentication=simple, java.naming.security.credentials=*****_}
Aug 8, 2008 9:52:19 AM org.acegisecurity.ldap.DefaultInitialDirContextFactory connect
FINE: Creating InitialDirContext with environment {java.naming.provider.url=ldap://statcan.ca:389/dc=statcan,dc=ca, java.naming.factory.initial=com.sun.jndi.ldap.LdapCtxFactory, java.naming.security.principal="CN=Cabasson\, Denis - SDD/DDS,OU=SDD-DDS,OU=INFO-INFO,OU=IMF-SIM",ou=STATCAN,dc=statcan,dc=ca, java.naming.security.authentication=simple, java.naming.security.credentials=**_***}
Aug 8, 2008 9:52:19 AM org.acegisecurity.providers.ldap.authenticator.BindAuthenticator2 handleBindException
WARNING: Failed to bind to LDAP: userDn"CN=Cabasson\, Denis - SDD/DDS,OU=SDD-DDS,OU=INFO-INFO,OU=IMF-SIM",ou=STATCAN,dc=statcan,dc=ca  username=cabaden
javax.naming.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C090334, comment: AcceptSecurityContext error

**Comment by spring-issuemaster** [comment]
This issue relates to #1909
