### ISSUE TITLE
Update Javadoc on SpringBootWebSecurityConfiguration

### ISSUE THREAD

**Issue by ullenboom** [spring-projects/spring-security#12075]
As part of #10902 update the Javadoc of https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/servlet/SpringBootWebSecurityConfiguration.java and remove WebSecurityConfigurerAdapter:

 /** The default configuration for web security. It relies on Spring
  * Security's content-negotiation strategy to determine what sort of
  * authentication to use. If the user specifies their own
  * ~~{@code WebSecurityConfigurerAdapter} or~~ {@link SecurityFilterChain} bean
  * this will back-off completely and the users should specify all the bits
  * that they want to configure as part of the custom security configuration.
  */

**Comment by jzheaux** [comment]
Thanks, @ullenboom, for the report. I think it would be best to file this issue with [the Spring Boot project](https://github.com/spring-projects/spring-boot/issues/new). Will you please open a ticket there instead?
