### ISSUE TITLE
SEC-956: Remove MapBasedMethodDefinitionSource.lookupAttributes

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1210]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-956":https://jira.spring.io/browse/SEC-956?redirect=false]) said:

This protected method won't actually work with the current implementation as it does a lookup in the methodMap using the method as the key, when in fact a combination of method name and target class is used, so it will never find a match. It should be removed

**Comment by spring-issuemaster** [comment]
This issue is related to #1209
