### ISSUE TITLE
SecuredAuthorizationManager should allow customizing underlying authorization manager

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#12233]
Dependent on https://github.com/spring-projects/spring-security/issues/12232, exposing this authorization manager will allow applications to customize it. This can be handy in circumstances where, for example, authorization is externalized to service or database.

**Comment by evgeniycheban** [comment]
I can take this.

**Comment by remal** [comment]
@jzheaux, @evgeniycheban, how can this functionality be used?

My goal is to add `RoleHierarchy` to `@Secured` functionality. Unfortunately, I couldn't find a way to customize `SecuredAuthorizationManager` by any customizer or `BeanPostProcessor`.
