### ISSUE TITLE
Wrong principal type OIDC

### ISSUE THREAD

**Issue by mmarcadella** [spring-projects/spring-security#12239]
### Summary

I configured a Spring Boot app to use OIDC login. The (minimalistic) security confguration is provided below.
Logging in work fine, but I notice that the pricipal I get back is an instance of DefaultOauthUser, instead of the expected OidcUser (given that I use a OidcUserService). It backfires during the logout process since OidcClientInitiatedLogoutSuccessHandler is expecting a principal instance of OidcUser (if not it just skips the OIDC logout).
The strange thing is that I placed a breakpoint at the first line of OidcUserService.loadUser and it never stop there, confirming that this userService is never used. So there is definitely something fishy here...

### Configuration

Here is the security config. There is no other beans.

```
@Configuration
public class SecurityConfig {

    @Autowired
    private ClientRegistrationRepository clientRegistrationRepository;

    private LogoutSuccessHandler oidcLogoutSuccessHandler() {
        OidcClientInitiatedLogoutSuccessHandler oidcLogoutSuccessHandler =
                new OidcClientInitiatedLogoutSuccessHandler(
                        this.clientRegistrationRepository);
        oidcLogoutSuccessHandler.setPostLogoutRedirectUri("/uio");
        return oidcLogoutSuccessHandler;
    }

    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        OidcUserService oidcUserService = new OidcUserService();
        http.authorizeRequests(authorizeRequests ->
                        authorizeRequests.anyRequest().authenticated()
                )
                .csrf().disable()
                .oauth2Login(oauthLogin ->
                        oauthLogin.userInfoEndpoint().oidcUserService(oidcUserService))
                .logout(logout -> logout
                        .logoutSuccessHandler(oidcLogoutSuccessHandler()));
        return http.build();
    }
}
```

### Version

Spring boot 2.7.5

**Comment by mmarcadella** [comment]
I dug a bit further:
OAuth2LoginConfigurer.init() adds the following AuthenticationProviders to the ProviderManager;
- Oauth2LoginAuthenticationProvider
- OidcAuthorizationCodeAuthenticationProvider
Since the ProviderManager attempts authentication in order and stops at the first successful provider, it returns an Oauth2User and skips the OidcProvider.

That doesn't look like the intended behavior, does it?? Shouldn't it add the OidcAuthorizationCodeAuthenticationProvider **before** Oauth2LoginAuthenticationProvider??

**Comment by sjohnr** [comment]
@mmarcadella sorry for the delay on this, and apologies but I'm having a hard time following the comments. Would you be able to provide a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) with full steps to reproduce the issue? If your setup involves an authorization server, please also describe the setup required for the authorization server.

**Comment by mmarcadella** [comment]
When re-reading my last comment, I have to admit I am confused too... Why would `withProviderConfiguration()` get any scopes from the .well-known file??
For anyone experiencing the same symptoms, the solution is simple: make sure you add `openid` to the scope list  
```spring.security.oauth2.client.registration.[registrationId].scope```
in your .properties file.
