### ISSUE TITLE
Add Authority String AuthorizationManager

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#12231]
It would be helpful to have an AuthorizationManager that takes the needed authorities as context.

Something like (pseudocode):

```java
AuthorizationManager<Collection<String>> manager = (authentication, authorities) -> 
        (authentication hasAnyAuthority authorities) ? granted : denied;
```

**Comment by evgeniycheban** [comment]
Hi, @jzheaux I created a PR that adds this new `AuthorizationManager` and refactors the existing `AuthorityAuthorizationManager` to use it internally.
