### ISSUE TITLE
SEC-972: Allow use of non-numeric (i.e. string) values for ObjectIdentity.getIdentifier() with the default JDBC implementation

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#1224]
["Zachary Roadhouse":https://jira.spring.io/secure/ViewProfile.jspa?name=zroadhouse](Migrated from ["SEC-972":https://jira.spring.io/browse/SEC-972?redirect=false]) said:

I am integrating the Spring Security ACL module into our application which uses a mixture of UUID and numeric primary keys as our domain object identifiers.  Based on reading the interface documentation fo ObjectIdentity, I had hoped that our UUID identifiers would work with the JdbcMutableAclService implementation without any customizations to the source.  This is not currently true as the JdbcMutableAclService and related classes all assume that the identifier value can be converted to a Long.  This assumption is limited to a small number of points in the implementation.

This is a request to change the implementation to allow the choice of Long vs. String to be made into a configuration setting (or alternate implementation).

**Comment by spring-issuemaster** [comment]
This issue supersedes #740

**Comment by mamuf** [comment]
I would much like to see broader extensibility in the `org.springframework.security.acls.jdbc.BasicLookupStrategy` class. Both `JdbcAclService` and `JdbcMutableAclService` can be easily extended via setters and/or protected methods, but the `BasicLookupStratedy` has all implementation details hidden in private methods.

I suggest updating this class at least such that:
  - `ObjectIdentity` extraction from `ResultSet` can be reimplemented, or
  - one could provide custom `ProcessResultSet` implementation

With these modifications, I believe extensions such as UUID fork by Paul Wheeler mentioned in previous comments would be possible more easily.

**Comment by arash** [comment]
Is this issue still on the roadmap?

**Comment by hasancansaral** [comment]
I am looking forward for this to be resolved. The only workaround I could find is to implement my own `LookupStrategy` to support a couple of non-primitives such as `String`.

**Comment by pwheel** [comment]
Raised #4424 to fix this issue
