### ISSUE TITLE
Error in ACLS document

### ISSUE THREAD

**Issue by Wilson-Emmanuel** [spring-projects/spring-security#12270]
Please could you take a look at this document.
[ACLS Document](https://github.com/spring-projects/spring-security/blob/6.0.0/docs/modules/ROOT/pages/servlet/authorization/acls.adoc/#acl_tables)

In the points that describe the four (4) tables used in the default implementation of the ACL Module, you did not provided any point for the `ACL_OBJECT_IDENTITY ` table, even though it appear in the explanations. However, there seem to be a repeated explanation for the `ACL_CLASS ` table.

**Comment by sjohnr** [comment]
Thanks for reaching out, @Wilson-Emmanuel!

It looks as though an editing pass was made but the merge to the `main` branch had an errant conflict resolved that resulted in removing the `ACL_OBJECT_IDENTITY` point and duplicating the `ACL_CLASS` point. The duplicated (second) `ACL_CLASS` point does looks as though it does not contain the edits.

I _think_ the second `ACL_CLASS` point can be removed and the `ACL_OBJECT_IDENTITY` from `5.8.x` could be restored in `main` (perhaps with an edit or two for consistency with the other points).

https://github.com/spring-projects/spring-security/blame/413c47311e88cb0038276038ff259f36e444538d/docs/modules/ROOT/pages/servlet/authorization/acls.adoc#L70-L72

Would you be interested in submitting a PR?

**Comment by Wilson-Emmanuel** [comment]
Thank you for the explanations. I have submitted a PR with the correction.

**Comment by sjohnr** [comment]
Hi @Wilson-Emmanuel. Apologies, I was traveling last week and have been quite busy the last few weeks. This is on my list today!

**Comment by sjohnr** [comment]
Merged via edd1915d1bd06d7d05f9f9c7da43c23ec72008e5 and polished via ed657a8fac70d34f072d5f782a912c96d04c0c7d to include edits from gh-9668.
