### ISSUE TITLE
SEC-977: CAS gateway feature support

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1229]
["Martin Buechler":https://jira.spring.io/secure/ViewProfile.jspa?name=mdmd](Migrated from ["SEC-977":https://jira.spring.io/browse/SEC-977?redirect=false]) said:

Acegi CAS client integration should also allow CAS gateway calls for configurable entry points like home/welcome/landing pages:
Reference: http://www.ja-sig.org/products/cas/client/gateway/index.html, and http://thread.gmane.org/gmane.comp.java.jasig.cas.user/32 from 2006!

**Comment by rwinch** [comment]
Closing since this was superseded by gh-40
