### ISSUE TITLE
OAuth 2.0 Resource Server Multi-tenancy - documentation improvement

### ISSUE THREAD

**Issue by TobiasSuhrborg** [spring-projects/spring-security#12295]
**Expected Behavior**
Preamble: I don't know the correct way to voice this issue, so if it's not the correct way, please tell me how to do it right.

While copying code from [the OAuth 2.0 Resource Server Multi-tenancy section](https://github.com/spring-projects/spring-security/blob/6.0.0/docs/modules/ROOT/pages/servlet/oauth2/resource-server/multitenancy.adoc#resolving-the-tenant-by-claim)
I noticed some inconsistencies. I expect the documentation to be usable code.

**Current Behavior**

2 code snippets contain bad code.
I tried creating a PR, but was not able to.

Here is the diff with the fixes:
![image](https://user-images.githubusercontent.com/21169723/203979795-8b1f16f9-9ffd-4102-b22e-aa3c57f47ddf.png)
2 parameters are provided, but not used. At the same time 2 fields are used, which are not described and resemble those parameters. 
I assume that this is a mix-up.

![image](https://user-images.githubusercontent.com/21169723/203979865-ec496c61-c59b-499f-9038-9120a5d410ed.png)
A non-existing class name is used.

**Comment by jzheaux** [comment]
Thanks, @TobiasSuhrborg, for the report. Are you able to submit a pull request with the fix? If so, please make it on the `5.6.x` branch.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
