### ISSUE TITLE
Prepare upgrade of `reactor-core` to version `3.5.0`

### ISSUE THREAD

**Issue by be0x74a** [spring-projects/spring-security#12291]
As per the `reactor-core:3.5.0` [release notes](https://github.com/reactor/reactor-core/releases/tag/v3.5.0) some deprecated methods were removed.
Although it's not yet possible to pass upgrade the version due to transitive dependencies from spring-boot using removed methods, we should start paving the work by remove the usage of the removed methods.

**Comment by marcusdacoregio** [comment]
Hi @be0x74a,

see [this issue](https://github.com/spring-projects/spring-security/issues/12229) to understand why we are not upgrading the version.

**Comment by be0x74a** [comment]
> Hi @be0x74a,
> 
> see [this issue](https://github.com/spring-projects/spring-security/issues/12229) to understand why we are not upgrading the version.

Ah alright. Sorry I tried to look up for similar issues before raising this, but clearly failed.
