### ISSUE TITLE
XFrameOptionsHeaderWriter with WhiteListedAllowFromStrategy doesn't work.

### ISSUE THREAD

**Issue by indyaah** [spring-projects/spring-security#123]
I have this JavaConfig set up for spring security (extending WebSecurityConfigurerAdapter and @EnableWebSecurity)

And I add header writer from xframe to http using following.

``` java
...
http().addHeaderWriter(new XFrameOptionsHeaderWriter(new WhiteListedAllowFromStrategy(getWhitelistUrls())))
...
```

``` java
    private List<String> getWhitelistUrls(){
        String urls = environment.getProperty("application.whitelist.urls");
        return Arrays.asList(urls.split("\\s*,\\s*"));
    }
```

Context boots up properly but now when I start using the application, always the header coming in request is DENY so the response goes with the same header as per `writeHeaders` method in **XFrameOptionsHeaderWriter**.

Shouldn't my header contain all the ALLOW-FROM : <URL>  specified by my config?

**Comment by schuch** [comment]
> I am also seeing an issue with WhiteListedAllowFromStrategy. If I use this headers() configuration:
> 
> ```
> .addHeaderWriter(new XFrameOptionsHeaderWriter(new WhiteListedAllowFromStrategy(Arrays.asList("http://example.com"))))
> ```
> The following response header is generated:
> 
> ```
> X-Frame-Options:ALLOW-FROM DENY
> ```
> Using StaticAllowFromStrategy for a single origin works fine:
> 
> ```
> .addHeaderWriter(new XFrameOptionsHeaderWriter(new StaticAllowFromStrategy(new URI("http://example.com"))))
> ```
> produces
> 
> ```
> X-Frame-Options:ALLOW-FROM http://example.com
> ```

The `ALLOW FROM DENY` issue was fixed with https://github.com/spring-projects/spring-security/pull/4559
