### ISSUE TITLE
OAuth2 client: default redirection to login page is done on wrong socket when SSL is enabled (authorization-server instead of client)

### ISSUE THREAD

**Issue by ch4mpy** [spring-projects/spring-security#12307]
**Describe the bug**
SSL is enabled by default for my spring-boot apps (I have set `SERVER_SSL_KEY_PASSWORD`, `SERVER_SSL_KEY_STORE` and `SERVER_SSL_KEY_STORE_PASSWORD` environement variables).

I configured a very simple OAuth2 client with `oauth2Login`. Spring client application runs on port 8080 and authorization-server (Keycloak) on port 8443. When trying to first access a secured page, I'm redirected to spring-boot generated login page on wrong socket: authorization-server socket instead of client socket (https://localhost:8443/oauth2/authorization/spring-addons-public when I'd expect https://localhost:8080/oauth2/authorization/spring-addons-public).

If I manually visit https://localhost:8080/oauth2/authorization/spring-addons-public, authorization-code flow is successful but I'm last redirected to the wrong socket again (sent to authorization-server index instead of client's one).

Interestingly enough, redirections are done on the right port if I explicitly disable SSL (`server.ssl.enabled=false`).

**To Reproduce**
- start an authorization-server. Sample configuration below expects a Keycloak instance running on port 8443 with SSL and a `spring-addons-public` client (with authorization-code flow enabled and no  client secret)
- start a spring-boot OAuth2 client servlet on port 8080 **with ssl enabled** and `oauth2Login` (detailed configuration below)
- visit https://localhost:8080/secured.html

**Expected behavior**
First redirection should be to https://localhost:8080/oauth2/authorization/spring-addons-public to initiate authorization-code flow from generated login page (instantly followed by another redirection to https://localhost:8443/realms/master/protocol/openid-connect/auth as there is only one provider in my conf)

## Sample
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.0.0</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	<artifactId>demo</artifactId>
	<properties>
		<java.version>17</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-oauth2-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```
```yaml
server:
  ssl:
    enabled: true
spring:
  security:
    oauth2:
      client:
        registration:
          spring-addons-public:
            client-id: "spring-addons-public"
            client-secret: ""
            client-name: "spring-addons-public"
            provider: "keycloak"
            scope: 
              - "openid"
              - "profile"
            client-authentication-method: "none"
            authorization-grant-type: "authorization_code"

        provider:
          keycloak:
            issuer-uri: "https://localhost:8443/realms/master"
            authorization-uri: "https://localhost:8443/realms/master/protocol/openid-connect/auth"
            token-uri: "https://localhost:8443/realms/master/protocol/openid-connect/token"
```
```java
@Configuration
@EnableWebSecurity
public class SecurityConfig {
	@Bean
	SecurityFilterChain uiFilterChain(HttpSecurity http) throws Exception {
		// @formatter:off
		http.authorizeHttpRequests()
			.requestMatchers("/login/**").permitAll()
			.requestMatchers("/oauth2/**").permitAll()
			.anyRequest().authenticated();
		// @formatter:on
		http.oauth2Login();

		return http.build();
	}
}
```
`src/main/resources/static/index.html`:
```html
<!DOCTYPE html>
<head>
	<title>secured</title>
</head>
<body>
	<h1>Secured</h1>
</body>
```
## Workarounds
When using a port that is not one of the two registered in `PortMapperImpl` default constructor, there is no alteration. So, the easiest solution, by far, is to **use any port but 80 or 8080 when SSL is enabled**. `PortMapperImpl` is initialised with 80 -> 443 and 8080 -> 8443 and components like `LoginUrlAuthenticationEntryPoint` alter the request port using this mapper, and even if you define your own port mapper in the application context, it is not picked => you'll have to configure it explicitly as done above by @sjohnr (but _1._ it gets funny when you have several client registrations with authorization code, and _2._ reconfiguring just the authentication entry-point is not enough as there are other places where the port is altered by `PortMapperImpl`). 

Port mapper being ignored with absolute URIs, the second option is to **use absolute URIs for login page, post login redirection URIs and inside authorization request resolver**.

**Warning: explicitly configuring the `loginPage` also requires to implement a controller to handle it.**
```yaml
scheme: http
hostname: localhost
base-uri: ${scheme}://${hostname}:${server.port}

server:
  port: 8080
  ssl:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: ssl

server:
  ssl:
    enabled: true

scheme: https
```

Then in the OAuth2 client configuration, I can use this ${base-uri} like that:
```java
@Order(Ordered.HIGHEST_PRECEDENCE + 1)
@Bean
SecurityFilterChain springAddonsClientFilterChain(
        HttpSecurity http,
        OAuth2AuthorizationRequestResolver authorizationRequestResolver,
        @Value("${base-uri}") URI base-uri) throws Exception {

    http.oauth2Login(login -> {
        login.loginPage(UriComponentsBuilder.fromUri(base-uri).path("/login").build().toString());
        login.authorizationEndpoint().authorizationRequestResolver(authorizationRequestResolver);
    });
    login.defaultSuccessUrl(UriComponentsBuilder.fromUri(base-uri).path("/home").build().toString(), true);

    ...

    return httpPostProcessor.process(http).build();
}

@ConditionalOnMissingBean
@Bean
OAuth2AuthorizationRequestResolver oAuth2AuthorizationRequestResolver(ClientRegistrationRepository clientRegistrationRepository) {
    return new SpringAddonsOAuth2AuthorizationRequestResolver(clientRegistrationRepository);
}

public class SpringAddonsOAuth2AuthorizationRequestResolver implements OAuth2AuthorizationRequestResolver {

    private final OAuth2AuthorizationRequestResolver defaultResolver;

    public SpringAddonsOAuth2AuthorizationRequestResolver(ClientRegistrationRepository clientRegistrationRepository) {
        defaultResolver = new DefaultOAuth2AuthorizationRequestResolver(clientRegistrationRepository,
                OAuth2AuthorizationRequestRedirectFilter.DEFAULT_AUTHORIZATION_REQUEST_BASE_URI);
    }

    @Override
    public OAuth2AuthorizationRequest resolve(HttpServletRequest request) {
        return toAbsolute(defaultResolver.resolve(request), request);
    }

    @Override
    public OAuth2AuthorizationRequest resolve(HttpServletRequest request, String clientRegistrationId) {
        return toAbsolute(defaultResolver.resolve(request, clientRegistrationId), request);
    }

    private OAuth2AuthorizationRequest toAbsolute(OAuth2AuthorizationRequest defaultAuthorizationRequest,
            HttpServletRequest request) {
        final var clientUriString = request.getRequestURL();
        if (defaultAuthorizationRequest == null || clientUriString == null) {
            return defaultAuthorizationRequest;
        }
        final var clientUri = URI.create(clientUriString.toString());
        final var redirectUri = UriComponentsBuilder.fromUriString(defaultAuthorizationRequest.getRedirectUri())
                .scheme(clientUri.getScheme()).host(clientUri.getHost())
                .port(clientUri.getPort()).build().toUriString();
        return OAuth2AuthorizationRequest.from(defaultAuthorizationRequest).redirectUri(redirectUri).build();
    }
}
```

This is lot of configuration code for a Boot application, but I isolated it in alternate starters wrapping `spring-boot-starter-oauth2-client` which makes my OAuth2 clients "bootiful" enough (configurable from properties with little to no Java conf). For the curious, the starters are [here](https://github.com/ch4mpy/spring-addons/tree/master/webmvc/spring-addons-webmvc-client) for servlets and [there](https://github.com/ch4mpy/spring-addons/tree/master/webflux/spring-addons-webflux-client) for reactive apps. Both come with additional _"worthless"_ auto-configuration controlled with properties (0 Java conf):
- CSRF with the right request handler and a filter to actually set the cookie when cookie repo is chosen, because this is so much easier and saves so much time wasted to sort this CSRF errors with security 6 and JS frontends like Angular (stopped counting  Stackoverflow questions and, even more serious, blog posts, with sessions enabled and CSRF protection disabled)
- authorities mapping (source claims, prefix and case transformation), so that I don't have to provide with a user service or a `GrantedAuthoritiesMapper` in each app
- logout success handler for OIDC Providers not strictly following the RP-Initiated Logout standard (exotic parameter names or missing `end_session_endpoint` in OpenID configuration). Auth0 and Amazon Cognito are samples of such OPs
- basic access control: `permitAll` for a list of path matchers and `authenticated` as default (to be fine tuned with method security or a configuration post-processor bean)
- an implementation for the client side of the Back-Channel Logout (remove corresponding authorized client from the repository and invalidate user session if it was its last authorized client with authorization-code)
- fine grained CORS configuration (per path matcher), so that I can provide allowed origins as environment variable when switching from localhost to dev or prod environments

**Comment by sjohnr** [comment]
@ch4mpy sorry for the delay on this. 

Does this issue only occur when both client/server run on localhost? Does the behavior change if you use 127.0.0.1 as the host for the client and configure the redirect uri accordingly in Keycloak?

Have you tried configuring `http.portMapper()`? I wonder if a setup with http port 8080 mapping to https port 8443 and configuring (the default) `PortMapperImpl` would improve the situation?

If that doesn't yield a result, is there an easier way to set up a reproducing test than manually configuring SSL for both client/server? Can you provide a minimal sample with a test SSL setup and a mock oauth2 server? I think demonstrating the first incorrect redirect would be enough to get started triaging the issue.

**Comment by ch4mpy** [comment]
The code source included in the description is a complete reproducer (authorization-server excluded)

**Comment by ch4mpy** [comment]
It is actually quite simple to start a new Keycloak instance over https with a self-signed certificate (takes less than 3 minutes).

## Generating a self-signed certificate and adding it to `cacerts` files
By running [this script](https://raw.githubusercontent.com/ch4mpy/self-signed-certificate-generation/main/self_signed.sh), you can generate certificates valid for a year and add it to your JREs / JDKs `cacerts` files. 

All required setup is setting 2 environment variables (3 if `JAVA_HOME` is not set, 4 if you set `SERVER_SSL_KEY_STORE` to have boot app start over https by default). Details in README of the [same repo ](https://github.com/ch4mpy/self-signed-certificate-generation)

## Running a local Keycloak instance with SSL on port 8443
Provided that
- `SERVER_SSL_KEY_STORE_PASSWORD` is set as environment variable (as per the setup to generate the certificates with the script above) 
- `SERVER_SSL_KEY_STORE` is set as environment or shell variable and is pointing to the self-signed `.jks` (something like `file:C:/Users/ch4mp/.ssh/bravo-ch4mp_self_signed.jks`):
```bash
if [[ "$OSTYPE" == "darwin"* ]]; then
  SED="sed -i '' -e"
else
  SED="sed -i -e"
fi
curl https://github.com/keycloak/keycloak/releases/download/20.0.3/keycloak-20.0.3.zip -O -J -L
unzip ./keycloak-20.0.3.zip
rm -f ./keycloak-20.0.3.zip
echo "https-key-store-file=$SERVER_SSL_KEY_STORE" >> ./keycloak-20.0.3/conf/keycloak.conf
$SED "s/file://g" "./keycloak-20.0.3/conf/keycloak.conf"
echo "https-key-store-password=$SERVER_SSL_KEY_STORE_PASSWORD" >> ./keycloak-20.0.3/conf/keycloak.conf
echo "https-port=8443" >> ./keycloak-20.0.3/conf/keycloak.conf
if [[ "$OSTYPE" == "msys" ]]; then
  ./keycloak-20.0.3/bin/kc.bat start-dev
else
  bash ./keycloak-20.0.3/bin/kc.sh start-dev
fi
```

## Declare a client
- browse to [https://localhost:8443](https://localhost:8443)
- create an admin account for "Administration Console"
- browse to [https://localhost:8443/admin/master/console/#/master/clients](https://localhost:8443/admin/master/console/#/master/clients) and click "Create client"
- set `spring-addons-public` as client name and ensure "Standard flow" is enabled in next step
- set `https://localhost:8080/*` as "Valid redirect URIs" and "Valid post logout redirect URIs". Also set `https://localhost:8080` as "Web origins"
- save

**Comment by ch4mpy** [comment]
@sjohnr I updated my previous comment to better answer your questions

**Comment by sjohnr** [comment]
@ch4mpy, I've looked into this and set up an OAuth2 client configured for SSL and an authorization server also configured for SSL. When configuring the client to run on port 8080, I do see the behavior you've outlined.

However, this behavior would exist in any application with Spring Security. Consider the following security config:

```java
@Configuration
@EnableWebSecurity
public class SecurityConfig {

	@Bean
	public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
		http
			.authorizeHttpRequests((authorize) -> authorize
				.anyRequest().authenticated()
			)
			.formLogin(Customizer.withDefaults());

		return http.build();
	}

}
```

When the application is configured to run on port 8080 with SSL enabled, visiting https://localhost:8080 I am redirected to https://localhost:8443/login. The reason for this is the default `PortMapper` and `PortResolver` configured with Spring Security assume that an SSL-enabled app will use port 8443.

I don't seem to find much information on this topic in the reference, so this is a topic that could use some better documentation. 

If we don't wish to accept the defaults, we do have to configure Spring Security to use port 8080. You would do so by defining that you use port 8080 as the SSL port, like so:

```java
	@Bean
	public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
		http
			// ...
			.portMapper((ports) -> ports
				.http(8080).mapsTo(8080)
			);

		return http.build();
	}
```

I would expect this to be enough to configure redirects to work properly. However, it appears this `portMapper()` configuration is not honored by the `LoginUrlAuthenticationEntryPoint`, which also uses a `PortResolver` that internally uses another `PortMapper`. I'm not sure the exact history behind this, but this has been in place in Spring Security since at least 2009.

I think the solution would be to allow the above configuration to configure 8080 as the SSL port, if you really want to do so. It should be used by both the `PortMapper` *and* the `PortResolver`.

However, 8443 is the default for SSL and nothing would tell Spring Security you wish to use 8080 unless you configure it. I believe this makes sense since an application could be serving traffic on both 8080 and 8443 simultaneously and the defaults make sense in this (very common) case.

In the meantime, you can work around this with the following configuration:

```java
@Configuration
@EnableWebSecurity
public class SecurityConfig {

	@Bean
	public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
		http
			// ...
			.oauth2Login(Customizer.withDefaults())
			.exceptionHandling((exceptions) -> exceptions
				.authenticationEntryPoint(authenticationEntryPoint())
			);

		return http.build();
	}

	private AuthenticationEntryPoint authenticationEntryPoint() {
		PortMapperImpl portMapper = new PortMapperImpl();
		portMapper.setPortMappings(Map.of("8080", "8080"));

		PortResolverImpl portResolver = new PortResolverImpl();
		portResolver.setPortMapper(portMapper);

		LoginUrlAuthenticationEntryPoint authenticationEntryPoint =
				new LoginUrlAuthenticationEntryPoint(
						"/oauth2/authorization/spring-addons-public");
		authenticationEntryPoint.setPortMapper(portMapper);
		authenticationEntryPoint.setPortResolver(portResolver);

		return authenticationEntryPoint;
	}

}
```

**Comment by ch4mpy** [comment]
When I configure `server.port=8080`, I expect it to be picked even if app is served with https (this is the case for server port binding already) and I'd expect it to be picked by spring-security as default. 

At minimum when using Spring-boot, couldn't auto-configuration pick server host and port and set spring-security defaults accordingly?

**Comment by sjohnr** [comment]
@ch4mpy 

> At minimum when using Spring-boot, couldn't auto-configuration pick server host and port and set spring-security defaults accordingly?

I think that would be a spring boot question though given everything else we’re discussing I wouldn’t expect that to be a feature request that would be considered. 

> When I configure `server.port=8080`, I expect it to be picked even if app is served with https (this is the case for server port binding already) and I'd expect it to be picked by spring-security as default.

Keep in mind that just specifying port 8080 is not enough in an SSL scenario because you also need to redirect from an http port to an https port for browser based apps (which an OAuth client is). Your configuration does not account for this, which makes it a non-standard setup.

**Comment by ch4mpy** [comment]
Unless I want spring apps to be served with SSL only (end-to-end encryption) and let the Middleware handle redirections

**Comment by ch4mpy** [comment]
@sjohnr appart from the issue related to **clients** served with `server.ssl.enabled=true`, there might be another one when the **providers** configured with https (client having `server.ssl.enabled=false`). Consider the following configuration:
```yaml
server:
  port: 8080
  ssl:
    enabled: false

spring:
  security:
    oauth2:
      client:
        registration:
          spring-addons-public:
            client-id: "spring-addons-public"
            client-secret: ""
            client-name: "spring-addons-public"
            provider: "keycloak"
            scope: 
              - "openid"
              - "profile"
            client-authentication-method: "none"
            authorization-grant-type: "authorization_code"

        provider:
          keycloak:
            issuer-uri: "http://localhost:8442/realms/master"
            authorization-uri: "http://localhost:8442/realms/master/protocol/openid-connect/auth"
            token-uri: "http://localhost:8442/realms/master/protocol/openid-connect/token"
```
Things work as expected

Now, if I switch provider URIs to https://localhost:8443
1. http://localhost:8080/ is redirected to http://localhost:8080/oauth2/authorization/spring-addons-public
2. http://localhost:8080/oauth2/authorization/spring-addons-public is redirected to https://localhost:8443/realms/master/protocol/openid-connect/auth with redirect_uri=http://localhost:8080/login/oauth2/code/spring-addons-public
3. after authentication, I am redirected to http://localhost:8080/login/oauth2/code/spring-addons-public with `state`, `session_state` and `code` parameters
4. http://localhost:8080/login/oauth2/code/spring-addons-public redirects to itself with exact same parameters
5. a request is issued to https://localhost:8080/login/oauth2/code/spring-addons-public with the same parameters as in step 3 and 4 and fails

**Comment by sjohnr** [comment]
@ch4mpy 

> When starting a spring-boot app with SSL enabled and no port specified, the app is bound to 8080 as usual.

Spring security does not know about Spring Boot configuration as it can be used with and without Spring Boot. Security only knows that 8080 is used for SSL based on configuration as discussed above. 

> Wouldn't `ServerProperties::getPort` tell which port the application is actually bound to

ServerProperties is a Spring Boot class which isn’t part of spring-security. It sounds like you are asking for features like the one discussed above that would be part of Boot auto configuration. If so, please open an issue on the boot [issue tracker](https://github.com/spring-projects/spring-boot/issues). 

If you believe you’ve found another bug/issue, please open a separate issue.

**Comment by ch4mpy** [comment]
> 8443 is the default for SSL

I don't agree with that (no more than 8080 is default for http). Defaults are 443 for https and 80 for http. 

Additionally, 8080 is the default for spring-boot applications, no matter of `server.ssl.enabled` is true or false (but, I understood, spring-boot apps are not the subject).

> please open an issue on the boot [issue tracker](https://github.com/spring-projects/spring-boot/issues)

What would be the point considering that you (spring-security team) decide what is done regarding security configuration in boot and:

> I think that would be a spring boot question though given everything else we’re discussing I wouldn’t expect that to be a feature request that would be considered.

Let's save Spring Boot team some time and post here a work around for spring-security assumptions on the ports used.

In my spring-boot  applications, I set a property with the fully qualified URI of the service like so:
```yaml
scheme: http
hostname: localhost
base-uri: ${scheme}://${hostname}:${server.port}

server:
  port: 8080
  ssl:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: ssl

server:
  ssl:
    enabled: true

scheme: https
```

Then in the OAuth2 client configuration, I can use this ${hostname} like that:
```java
@Order(Ordered.HIGHEST_PRECEDENCE + 1)
@Bean
SecurityWebFilterChain clientFilterChain(
        ServerHttpSecurity http,
        ServerOAuth2AuthorizationRequestResolver authorizationRequestResolver,
        @Value("${base-uri}") String baseUri) throws Exception {
    http.authorizeExchange().pathMatchers("/login/**", "/oauth2/**").permitAll().anyExchange().authenticated();

    http.exceptionHandling(exceptionHandling -> exceptionHandling
            .authenticationEntryPoint(new RedirectServerAuthenticationEntryPoint("/login")))
        .oauth2Login(oauth2 -> oauth2
            .authorizationRequestResolver(authorizationRequestResolver)
            .authenticationSuccessHandler(new RedirectServerAuthenticationSuccessHandler("%s/".formatted(baseUri, clientProperties.getPostLoginRedirectPath())))
            .authenticationFailureHandler(new RedirectServerAuthenticationFailureHandler("%s/login".formatted(baseUri, clientProperties.getLoginPath()))));

    ...

    return http.build();
}

@ConditionalOnMissingBean
@Bean
ServerOAuth2AuthorizationRequestResolver serverOAuth2AuthorizationRequestResolver(
        ReactiveClientRegistrationRepository clientRegistrationRepository,
        SpringAddonsOAuth2ClientProperties clientProps) {
    return new SpringAddonsServerOAuth2AuthorizationRequestResolver(clientRegistrationRepository,
            clientProps.getClientUri());
}

static class SpringAddonsServerOAuth2AuthorizationRequestResolver implements ServerOAuth2AuthorizationRequestResolver {

    private final ServerOAuth2AuthorizationRequestResolver defaultResolver;
    private final URI clientUri;

    public SpringAddonsServerOAuth2AuthorizationRequestResolver(ReactiveClientRegistrationRepository clientRegistrationRepository,
            URI clientUri) {
        defaultResolver = new DefaultServerOAuth2AuthorizationRequestResolver(clientRegistrationRepository);
        this.clientUri = clientUri;
    }

    @Override
    public Mono<OAuth2AuthorizationRequest> resolve(ServerWebExchange exchange) {
        return defaultResolver.resolve(exchange).map(this::toAbsolute);
    }

    @Override
    public Mono<OAuth2AuthorizationRequest> resolve(ServerWebExchange exchange, String clientRegistrationId) {
        return defaultResolver.resolve(exchange, clientRegistrationId).map(this::toAbsolute);
    }

    private OAuth2AuthorizationRequest toAbsolute(OAuth2AuthorizationRequest req) {
        if (req == null) {
            return null;
        }
        final var redirectUri = UriComponentsBuilder.fromUriString(req.getRedirectUri())
                .scheme(clientUri.getScheme()).host(clientUri.getHost())
                .port(clientUri.getPort()).build().toUriString();
        return OAuth2AuthorizationRequest.from(req).redirectUri(redirectUri).build();
    }
}
```

That's a lot of code for a Boot application, but I isolated it in alternate starters wrapping `spring-boot-starter-oauth2-client` which makes my OAuth2 clients "bootiful" enough (configurable from properties with little to no Java conf). For the curious, the starters are [here](https://github.com/ch4mpy/spring-addons/tree/master/webmvc/spring-addons-webmvc-client/src/main/java/com/c4_soft/springaddons/security/oauth2/config/synchronised) for servlets and [there](https://github.com/ch4mpy/spring-addons/tree/master/webflux/spring-addons-webflux-client/src/main/java/com/c4_soft/springaddons/security/oauth2/config/reactive) for reactive apps.

**Comment by ch4mpy** [comment]
@sjohnr I edited a lot my preceding comment, but it is stable now. It could be worth a second read.

**Comment by ch4mpy** [comment]
@rwinch thank you for your feedback.

I moved the workarounds section to the first comment to save others with the same need the reading of all the intermediate comments. This could be useful until the fix to https://github.com/spring-projects/spring-security/issues/12971 is released (or to those stuck with an earlier version).

**Comment by ch4mpy** [comment]
I wanted to apologize to @sjohnr too, it always takes me ages and ten edits to explain my point. Sorry for that.

**Comment by sjohnr** [comment]
Thanks @ch4mpy! No problem.

**Comment by sandipchitale** [comment]
I think the issue is https://github.com/spring-projects/spring-security/blame/22000b42e9e84d2a8b5479b076dbdf1998a91e17/config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2LoginConfigurer.java#L564 which simply creates a `LoginUrlAuthenticationEntryPoint` which is not accessible. If it were to be allowed to be post processed, then it would have been easy to configure PortMapper/Resolver on it. This `PortMapper` business has caused us all kinds of grief and I am glad to hear it will be removed.
