### ISSUE TITLE
v6.0.0 release notes no mention of WebSecurityConfigurerAdapter being removed

### ISSUE THREAD

**Issue by murphy-25** [spring-projects/spring-security#12320]
**Describe the bug**
When looking at the release notes for v6.0.0, there is no mention of the WebSecurityConfigurerAdapter being completely removed: https://github.com/spring-projects/spring-security/releases/tag/6.0.0

After upgrading I noticed all the deprecation notices for WebSecurityConfigurerAdapter have disappeared and they are now compile errors. So as it's now being removed shouldn't this feature inside the release notes? For some reason when reading the what's coming for spring v3.0.0 way back I thought WebSecurityConfigurerAdapter wouldn't be removed completely just yet.

Thanks,
Mark.

**Comment by jzheaux** [comment]
Thanks for reaching out, @murphy-25. It is listed in the release candidate: https://github.com/spring-projects/spring-security/releases/tag/6.0.0-RC1

What I'd recommend is first updating to 5.8 and reading [the 5.8 migration guide](https://docs.spring.io/spring-security/reference/5.8/migration/index.html) as this will walk you through each step needed to prepare for moving to 6.0, including strategies for removing `WebSecurityConfigurerAdapter` from your application.

I'll reach out to the team to see if there is a better way to surface all changes across all milestones in the GA release notes. A blog post that collects the main points across the release may be helpful.

**Comment by jzheaux** [comment]
I will also add that [the what's new in 6.0](https://docs.spring.io/spring-security/reference/whats-new.html) in the reference manual lists all the breaking changes.

**Comment by jzheaux** [comment]
I've modified the 6.0 announcement to include [a section on breaking changes](https://spring.io/blog/2022/11/21/spring-security-5-8-and-6-0-are-now-ga#breaking-changes) that refers directly to `WebSecurityConfigurerAdapter` removal.
