### ISSUE TITLE
Add AuthorizationRequestRepository option in securityconfig

### ISSUE THREAD

**Issue by LoliWolf** [spring-projects/spring-security#12350]
**Expected Behavior**

developer can custom AuthorizationRequestRepository implement if they dont want to use session

**Current Behavior**

we cant set custom AuthorizationRequestRepository now, we need extend Oauth2Filter and rewrite constructor to solve this.

**Comment by jzheaux** [comment]
You can already customize the `AuthorizationRequestRepository` through `HttpSecurity` like so:

```java
@Bean 
SecurityFilterChain appSecurity(HttpSecurity http) {
    http
        .oauth2Login((oauth2) -> oauth2
            .authorizationCodeGrant((grant) -> grant
                .authorizationRequestRepository(myCustomRepository)
            )
        )
        // ...
    return http.build();
}
```
For more details, please see [the `AuthorizationRequestRepository` section](https://docs.spring.io/spring-security/reference/5.8/servlet/oauth2/client/authorization-grants.html#_storing_the_authorization_request) in the reference manual
