### ISSUE TITLE
[Webflux] 500 error when violating a `PreAuthorize` constraint with http basic auth

### ISSUE THREAD

**Issue by antholeole** [spring-projects/spring-security#12374]
**Describe the bug**
Setting up spring security, I have a security config that uses http basic auth. I have two users; rob, who is not an admin, and admin who is an admin. Here are the following 3 cases when trying to hit an endpoint secured by `@\PreAuthorize("hasRole('ADMIN')")`: 

✅ Attempt to hit the endpoint with no or incorrect (i.e. user / pass does not map to a user) http basic auth: 403 forbidden.
✅ Attempt to hit the endpoint with user / pass "admin", "admin": the request completes successfully!
❌ Attempt to hit an endpoint with a user that does not have admin role (rob, in this case): 500 error. [Stacktrace](https://raw.githubusercontent.com/antholeole/spring-security-bug-example/main/500_stack_trace.txt)

Ideally, case 3 should be a 403 error, not a 500. Note that this does not happen if `public SecurityWebFilterChain securityWebFilterChain` is not included; the routes work correctly in this case.

Running on spring-security 6.0.0 - I did reproduce it on 4.7.x though. Did not run a bisect.

**To Reproduce**
Security Config:

```java
@Configuration
@EnableWebFluxSecurity
@EnableReactiveMethodSecurity(useAuthorizationManager = true)
public class SecurityConfig {
    @Bean
    public MapReactiveUserDetailsService userDetailsService() {
        User.UserBuilder userBuilder = User.withDefaultPasswordEncoder();
        UserDetails rob = userBuilder.username("rob")
                .password("rob")
                .roles("USER")
                .build();
        UserDetails admin = userBuilder.username("admin")
                .password("admin")
                .roles("USER","ADMIN")
                .build();
        return new MapReactiveUserDetailsService(rob, admin);
    }

    @Bean
    public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
        return http
                .httpBasic()
                .and()
                .csrf()
                .disable()
                .build();
    }
}
```

Rest controller:
```java
@RestController
public class StandardController {
    @PreAuthorize("hasRole('ADMIN')")
    @GetMapping("/hello")
    public Mono<Map<String, String>> hello() {
        final Map<String, String> map = new HashMap<>();
        map.put("hi", "hi");
        return Mono.just(map);
    }

}
```

**Expected behavior**
You should get a 403 when getting rejected by @/PreAuthorize, not a 500.

**Sample**

[A link to a GitHub repository with a minimal, reproducible sample](https://github.com/antholeole/spring-security-bug-example)

Let me know if anything else is needed.

**Comment by marcusdacoregio** [comment]
Hi @antholeole, thanks for the report.

Is there any particular reason why you are not using `authorizeExchange()`? At first, it should not interfere with method security, but I'm curious if that's a use case since when adding it the problem does not happen.

**Comment by antholeole** [comment]
@marcusdacoregio I do use `authorizeExchange` for routes targetable by globs. I have some routes though that require specific permissions; I like to put them directly over the route for aesthetic purposes. I find it `@PreAuthorization(hasRole(...))` to be easier to read then having to go to the security config and mentally match the glob.

In short, I think it looks better :)

**Comment by marcusdacoregio** [comment]
Keep in mind that combining filter chain security and method security is recommended since you will have a more in-depth security posture. Anyway, I don't think it should interfere with the response status code. I'll reach out to the team if they have more context on this since that can be reproducible in older versions.

**Comment by antholeole** [comment]
Thanks for letting me know - do you have any documentation on the security posture you mentioned? I’d like to take a look. Unfortunately I don’t fully understand that comment but I’d like to so I can be sure I’m maximizing my security. Thanks!On Dec 15, 2022, at 8:04 AM, Marcus Hert Da Coregio ***@***.***> wrote:﻿
Keep in mind that combining filter chain security and method security is recommended since you will have a more in-depth security posture. Anyway, I don't think it should interfere with the response status code. I'll reach out to the team if they have more context on this since that can be reproducible in older versions.

**Comment by marcusdacoregio** [comment]
I remember reading a discussion somewhere but I cannot find it now. But, as an example, if some malicious user is able to bypass the security rules in the filter chain, they will still have to deal with the method security.

**Comment by antholeole** [comment]
test case:

```kotlin
package org.springframework.security.config.web.server

import org.junit.Before
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.context.ApplicationContext
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.security.access.prepost.PreAuthorize
import org.springframework.security.config.annotation.method.configuration.EnableReactiveMethodSecurity
import org.springframework.security.config.annotation.web.reactive.EnableWebFluxSecurity
import org.springframework.security.config.test.SpringTestContext
import org.springframework.security.config.test.SpringTestContextExtension
import org.springframework.security.core.userdetails.MapReactiveUserDetailsService
import org.springframework.security.core.userdetails.User
import org.springframework.security.core.userdetails.UserDetails
import org.springframework.security.web.server.SecurityWebFilterChain
import org.springframework.test.web.reactive.server.WebTestClient
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController
import org.springframework.web.reactive.config.EnableWebFlux


@ExtendWith(SpringTestContextExtension::class)
class ServerMethodSecurityDslTests {
    @JvmField
    val spring = SpringTestContext(this)

    private lateinit var client: WebTestClient

    @Autowired
    fun setup(context: ApplicationContext) {
        this.client = WebTestClient
                .bindToApplicationContext(context)
                .configureClient()
                .build()
    }

    @Test
    fun `PreAuthorize failed with WebFilterChain then 401 unauthorized`() {
        this.spring.register(
                SimpleWebFilterChainConfig::class.java,
                UserDetailsConfig::class.java,
        ).autowire()

        this.client.get()
                .uri("/")
                .exchange()
                .expectStatus()
                .isOk
    }

    @Configuration
    @EnableWebFluxSecurity
    @EnableWebFlux
    @EnableReactiveMethodSecurity(useAuthorizationManager = true)
    open class SimpleWebFilterChainConfig {
        @Bean
        open fun springWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
            return http { }
        }

        @RestController
        internal open class PathController {
            @PreAuthorize("hasRole('USER')")
            @RequestMapping("/")
            open fun path() {
            }
        }
    }

    @Configuration
    open class UserDetailsConfig {
        @Bean
        open fun userDetailsService(): MapReactiveUserDetailsService {
            val user = User.withDefaultPasswordEncoder()
                    .username("user")
                    .password("password")
                    .roles("USER")
                    .build()
            return MapReactiveUserDetailsService(user)
        }
    }
}

```

**Comment by antholeole** [comment]
Test case:

```java
@Test
	// gh-12374
	public void webFluxConfigurationAndMethodLevelSecurityOnDenyRespondsWith401() {
		@Configuration
		@EnableWebFluxSecurity
		@EnableWebFlux
		@EnableReactiveMethodSecurity(useAuthorizationManager = true)
		class ReactiveMethodSecurityConfig {
			@Order(Ordered.HIGHEST_PRECEDENCE)
			@Bean
			SecurityWebFilterChain apiHttpSecurity(ServerHttpSecurity http) {
				http.securityMatcher(new PathPatternParserServerWebExchangeMatcher("/api/**")).authorizeExchange()
						.anyExchange().denyAll();
				return http.build();
			}

			@RestController
			static class DenyAllResolver {
				@RequestMapping("/**")
				@PreAuthorize("denyAll")
				String resolver() {
					return "How did this happen???";
				}
			}
		}
		
		this.spring.register(ReactiveMethodSecurityConfig.class).autowire();
		// @formatter:off
		WebTestClient client = WebTestClient
				.bindToApplicationContext(this.spring.getContext())
				.build();
		client.get()
				.exchange()
				.expectStatus()
				.isUnauthorized(); // currently fails; return 400
	}
```

**Comment by marcusdacoregio** [comment]
Hi @antholeole, I contacted the team to get some context on this.

The `ExceptionTranslationWebFilter` is only added if you are using `authorizeExchange()`, without that, Spring Security will just let the exception go all the way to the web handler, which interprets it as 500. So, it would be preferable to at least use `authorizeExchange().authenticated()` as a catch-all. If you feel like annotations have a better look, this still affords the option to have a global policy at the filter level and a fine-grained policy at the method level. Alternatively, you can add the `ExceptionTranslationWebFilter` using `http.addFilterAt`.
