### ISSUE TITLE
Secured Annotation published no SuccessEvent if the verification was successful

### ISSUE THREAD

**Issue by npriebe** [spring-projects/spring-security#12371]
**Describe the bug**
If a check via the Secured Annotation fails, the spring event: AuthorizationFailureEvent is published. If the check was successful, no AuthorizationSuccessEvent is published.

Is there another way to publish a spring event if authentication via the Secured() annotation was successful ?

**Comment by marcusdacoregio** [comment]
Hi @npriebe, thanks for the report.

Which Spring Security version are you using?

**Comment by npriebe** [comment]
Hi @marcusdacoregio ,

I use this for a oauth2 resource server.
This is the dependecy:

``` xml    
<dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
      <version>2.6.3 </version>
</dependency>
```
My security configuration (for resource server):

``` java
@EnableWebSecurity
@EnableGlobalMethodSecurity(securedEnabled = true)
public class SecurityConfiguration extends WebSecurityConfigurerAdapter
{
    @Override
    public void configure(HttpSecurity http) throws Exception
    {
        http.oauth2ResourceServer().jwt();
    }
}
```

And my rest method:
``` java
@Secured("user_role")
@GetMapping
public void restMethod()
{

}
```
And I have illustrated my problem with a diagram:

![MissingSuccessEventDiagram](https://user-images.githubusercontent.com/54103655/207794427-8f5be75e-0ea8-41ba-a74b-222121b15d5f.png)

The problem is that no SuccessEvent is published if the check on the Secured Annotation was successful.

This has then led to the following error:
If the JWT was valid. An "`AuthenticationSuccessEvent`" was published.
After that the role was checked via the Secured Annotation. And here this was invalid. So an `AuthorizationFailedEvent` was published afterwards.

Thus, I could no longer track via the events whether the request was now valid or invalid.

Maybe there is also a possibility to create a custom event after checking the Secured annotation? I have not found a way to do this.

Maybe there is a solution for this :)

**Comment by marcusdacoregio** [comment]
Hi @npriebe, I assume that you are using the `SpringAuthorizationEventPublisher`, which is an implementation that only publishes `AuthorizationDeniedEvent`. Because `AuthorizationGrantedEvent`s have the potential to be quite noisy, they are not published by default.

You should probably need to create an `AuthorizationEventPublisher` implementation to do that for you, this [section of the documentation](https://docs.spring.io/spring-security/reference/servlet/authorization/events.html#authorization-granted-events) might help.
