### ISSUE TITLE
6.0.x should use samplesBranch=6.0.x

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-security#12380]

**Comment by Leila-Codes** [comment]
Hey there. Do you know if there are any samples or examples up online anywhere for Spring Security 6? 

I just started a fresh Spring Boot project and added security and I cannot for the life of me get anything to work properly with the HttpSecurity and SecurityConfig stuff 😿 

I'd prefer to be on the latest and greatest but if I have to I'll roll it back to 5.

**Comment by Leila-Codes** [comment]
Please do! Or otherwise would it be possible to update the links to point at the Spring Security Samples repo on the Spring website?

**Comment by marcusdacoregio** [comment]
Hi @Leila-Codes, is this what you are looking for? https://docs.spring.io/spring-security/reference/samples.html

**Comment by Leila-Codes** [comment]
Doh 🤦‍♀️

I never thought to clock the word "Samples."

My bad. Thank you!!

**Comment by marcusdacoregio** [comment]
It would be great to have this done first https://github.com/spring-projects/spring-security-samples/issues/117
