### ISSUE TITLE
Incorrect Javadoc for class ExpressionAuthorizationDecision

### ISSUE THREAD

**Issue by ghusta** [spring-projects/spring-security#12411]
Javadoc says `ExpressionAuthorizationDecision` was introduced since 5.6.

But in reality it was introduced in 5.8.

See source : https://github.com/spring-projects/spring-security/blob/5.8.x/core/src/main/java/org/springframework/security/authorization/ExpressionAuthorizationDecision.java

**Comment by marcusdacoregio** [comment]
Hi @ghusta,

are you interested in submitting a PR targeting the 5.8.x branch that updates the since tag?

**Comment by ghusta** [comment]
Hi

OK why not. In my opinion there is only one character to change, it shouldn't be too hard 😉

**Comment by marcusdacoregio** [comment]
Sounds good, I'll assign this issue to you then.
