### ISSUE TITLE
Document @EnableWebFluxSecurity requiring @Configuration in 6.0.0

### ISSUE THREAD

**Issue by ashish-b-choudhary-db** [spring-projects/spring-security#12434]
Upon migrating an application to Spring Boot 3 I found that security config had stopped working.
I went through all the migration docs at https://docs.spring.io/spring-security/reference/migration/reactive.html to see if I missed something obvious. But didn't find anything.
Upon debugging and looking at examples, I realized that `@Configuration` has been removed from `@EnableWebFluxSecurity` annotation.

Not sure whether this change was really needed, anyways this being documented would be good.

**Comment by marcusdacoregio** [comment]
Hey @ashish-b-choudhary-db, thanks for the report.

This is documented in the [5.8 version of the documentation](https://docs.spring.io/spring-security/reference/5.8.1/migration/servlet/config.html#_add_configuration_to_enable_annotations).

However, it's under the **Servlet Migrations**, I think we should consider copying it to the **Reactive Migrations** too.
