### ISSUE TITLE
SEC-997: Upgrade spring-aws-maven and remove extra repository

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1248]
["Carlos Sanchez":https://jira.spring.io/secure/ViewProfile.jspa?name=carlos](Migrated from ["SEC-997":https://jira.spring.io/browse/SEC-997?redirect=false]) said:

When a new version 1.2.4 of spring-aws-maven is released upgrade and remove repository http://s3.amazonaws.com/maven.springframework.org/external from pom

See SPR-5189

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-5189
