### ISSUE TITLE
Enhancement  FormLoginConfigurer Adaptation custom UsernamePasswordAuthenticationFilter

### ISSUE THREAD

**Issue by chengweng** [spring-projects/spring-security#12537]
**Expected Behavior**
spring security version:5.7.6
custom UsernamePasswordAuthenticationFilter unable obtain HttpSecurity configure Initialize

FormLoginConfigurer‘s constructor newly added UsernamePasswordAuthenticationFilter type class incoming parameter
![图片](https://user-images.githubusercontent.com/26996504/212232954-5c5ec6c0-cf3f-4231-ac74-a3185699ab81.png)
add a constructor
```
public FormLoginConfigurer(UsernamePasswordAuthenticationFilter filter,url) {
  super(filter, url);
  usernameParameter("username");
  passwordParameter("password");
}
```
![图片](https://user-images.githubusercontent.com/26996504/212233196-844bbc27-c861-45f4-9a0a-bd40c9ef7cd2.png)
this method call `addFilter` method insert `custom UsernamePasswordAuthenticationFilter `

**Current Behavior**
![图片](https://user-images.githubusercontent.com/26996504/212231866-fb3fb5ef-76f2-49ea-811e-e31cefe8ac7c.png)

default new UsernamePasswordAuthenticationFilter()

Make Custom UsernamePasswordAuthenticationFilter  use HttpSecurity configure Initialize
**Context**

**Comment by sjohnr** [comment]
@chengweng thanks for opening your first issue! However, I am having a very hard time understanding your suggestion. I noticed you also commented on #11909. For that reason, I believe you're possibly reporting something very similar and I'm going to close for the same reason as mentioned in [this comment](https://github.com/spring-projects/spring-security/issues/11909#issuecomment-1263722646).

If I'm simply misunderstanding you, I do apologize. However, if you believe there is a bug in verison 5.7.6, please provide a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) and I'll be happy to take a further look.

**Comment by chengweng** [comment]
custom CustomLoginAuthenticationFilter extends AbstractAuthenticationProcessingFilter，CustomLoginAuthenticationFilter  Unable to inject HttpSecurity configure，
![图片](https://user-images.githubusercontent.com/26996504/215255688-fcd7beaa-bd04-4760-b3b2-62ee5afef25d.png)
![图片](https://user-images.githubusercontent.com/26996504/215256888-84b396eb-69f9-4439-b365-fa3948a6bf84.png)



[CustomLoginAuthenticationFilter.txt](https://github.com/spring-projects/spring-security/files/10526815/CustomLoginAuthenticationFilter.txt)

**Comment by GeTOUO** [comment]
这么实用的增强为什么关掉了呢。目前对于`UsernamePasswordAuthenticationFilter` 的自定义不是很方便

**Comment by GeTOUO** [comment]
这么实用的增强为什么关掉了呢。目前对于`UsernamePasswordAuthenticationFilter`的自定义不是很方便
