### ISSUE TITLE
Kotlin DSL should contain `formLogin.disable`

### ISSUE THREAD

**Issue by Sineaggi** [spring-projects/spring-security#12552]
**Expected Behavior**

In the `HttpSecurityDsl`, formLogin should contain a `disable()` method.

```kotlin
formLogin {
    disable()
}
```
should work like
```kotlin
csrf {
    disable()
}
```

**Current Behavior**

There is no disable() method on the formLogin dsl

**Context**

<img width="270" alt="Screen Shot 2023-01-17 at 12 28 03 PM" src="https://user-images.githubusercontent.com/889237/212994226-606bb7ff-86cc-4308-8410-6b70b08d5bac.png">

Any configurable object that extends from `AbstractHttpConfigurer` and therefore has a `disable()` method should be callable from the kotlin security dsl.

**Comment by jzheaux** [comment]
Thanks, @Sineaggi. This makes sense, are you able to provide a PR to add the missing method?

**Comment by Sineaggi** [comment]
> Thanks, @Sineaggi. This makes sense, are you able to provide a PR to add the missing method?

Created a pr here https://github.com/spring-projects/spring-security/pull/12554
