### ISSUE TITLE
AuthorizeHttpRequestsConfigurer#XXXrole methods should ensure the role does not begin with the role prefix

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#12581]
Similar to how `User.UserBuilder` works, configuration should fail if configurations like the following are attempted:

```java
hasRole('ROLE_USER')
hasAnyRole('ROLE_USER')
```

Otherwise, scenarios like [this SO question](https://stackoverflow.com/questions/75225700/hasrolerole-user-not-working-in-spring-boot3-with-springsecurity6/75227337#75227337) crop up.

**Comment by bist220** [comment]
Can I work on this?

**Comment by bist220** [comment]
submitted a pr #12760

**Comment by super-iterator** [comment]
When this PR is expected to be mainstreamed?

**Comment by super-iterator** [comment]
I'd like to add that in addition to this issue, hasAuthority('ROLE_USER') doesn't work, and I have to use either hasAnyRole('ROLE_USER') or hasRole('ROLE_USER') with the `ROLE_` prefix for this to work. I hope that both issues will be considered.

**Comment by bist220** [comment]
`hasAuthority("ROLE_USER")` works fine, atleast in [6.0.1](https://github.com/spring-projects/spring-security/releases/tag/6.0.1) Also `hasAnyRole` or `hasRole` should not start with `ROLE_` prefix

**Comment by super-iterator** [comment]
I'm using 6.0.2 and it doesn't work with me (talking about hasAuthority)

**Comment by bist220** [comment]
can you show your config file, if possible, or some code snippet?

**Comment by super-iterator** [comment]
It turned out that the Spring Resource Server decoder was adding a ROLE_ prefix, which messed the whole thing up. I also updated to the most recent Spring version [6.0.5](https://github.com/spring-projects/spring-framework/releases/tag/v6.0.5), and now I have hasRole, hasAnyRole, and hasAuthority work as they should.
