### ISSUE TITLE
Allow using different cookie name for rememeber me authentication.

### ISSUE THREAD

**Issue by hurelhuyag** [spring-projects/spring-security#12608]
**Describe the bug**
Currently `RememberMeConfigurer` does not allow using non-default cookie names for authentication. I hope It should.

**To Reproduce**
See the `RememberMeConfigurer.validateInput` method.

Here is direct link:
https://github.com/spring-projects/spring-security/blob/main/config/src/main/java/org/springframework/security/config/annotation/web/configurers/RememberMeConfigurer.java#L302

**Expected behavior**
This configuration should work
```
.rememberMe()
                    .rememberMeServices(rememberMeServices)
                    .rememberMeParameter("customParameter")
                    .rememberMeCookieName("customCookieName")
                    .tokenValiditySeconds(60*60*24*7)
```

**Sample**
The linked source code is obvious.

**Comment by marcusdacoregio** [comment]
Hi @hurelhuyag,

I'd like to understand your use case a little bit better: if you are using a custom `RememberMeServices` why you can't do `rememberMeServices.setCookieName(myCookieName)`?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
