### ISSUE TITLE
We should deprecate .and() along with non lambda DSL methods

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#12629]
We should encourage users to switch over to the lambda DSL by deprecating methods that are only valid for the old way (using `and()`) of configuring Spring Security.

**Comment by wilkinsona** [comment]
I wonder if this should be an enhancement rather than a task so that it appears in the changelog? It's something that users may want to learn about when reviewing what's changed. It's also a breaking change for anyone compiling with `-Werror` so it feels worth listing from that perspective as well.

**Comment by marcusdacoregio** [comment]
Thanks @wilkinsona , I updated the issue
