### ISSUE TITLE
Build Automation

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#12648]
This issue is a theme for the Spring Security 6.1 release. Issues that relate to this will be added below.

# Build Improvements

- [x] :star2: #12575
- [ ] :star2: #10460
- [ ] :sparkles: #11308
- [ ] :sparkles: #11257
- [ ] :sparkles: #10454 

# Build Re-usability

- [ ] :star2: Extract validate release milestone GitHub Action
- [ ] :star2: Extract update scheduled release version GitHub Action
- [ ] :star2: Extract wait for artifacts GitHub Action
- [ ] :star2: Extract create GitHub release GitHub Action
- [ ] :star2: Extract update next development version GitHub Action
- [ ] :sparkles: Extract schedule release train GitHub Action

---

**Labels:**
- :beetle: Bug
- :star2: Enhancement
- :sparkles: Enhancement (nice-to-have)

**Comment by sjohnr** [comment]
# Build Improvements
- [ ] :star2: #12575
- [ ] :star2: #11257
- [ ] :star2: #10460
- [ ] :sparkles: #11308
- [ ] :sparkles: #10454 

# Build Re-usability
- [ ] :star2: Extract validate release milestone GitHub Action
- [ ] :star2: Extract update scheduled release version GitHub Action
- [ ] :star2: Extract wait for artifacts GitHub Action
- [ ] :star2: Extract create GitHub release GitHub Action
- [ ] :star2: Extract update next development version GitHub Action
- [ ] :sparkles: Extract schedule release train GitHub Action

---

**Labels:**
- :beetle: Bug
- :star2: Enhancement
- :sparkles: Enhancement (nice-to-have)

**Comment by sjohnr** [comment]
Carrying theme forward to 6.2 via gh-13176.
