### ISSUE TITLE
SAML migration questions: RelyingPartyRegistrations#fromMetadata() doesn't work with a federation catalog that has a mix of SP:s and IdP:s et.c

### ISSUE THREAD

**Issue by stnor** [spring-projects/spring-security#12664]
I am trying to migrate from the old SAML extension project to the new. on Spring 5.8.x (not boot).

It would be good if i could use `RelyingPartyRegistrations.collectionFromMetadataLocation()` could skip "SP" entries instead of throwing exceptions.

Right now I am getting `org.springframework.security.saml2.Saml2Exception: Metadata response is missing the necessary IDPSSODescriptor element`

Ideally there should be a flag to skip entities without IDPSSODescriptor. In this federation, there are `SPSSODescriptor`:s mixed in the same metadata as the IdP:s in this case.

See `https://fed.skolfederation.se/prod/md/skolfederation-3_1.xml` (A Federation for school owners (IdP) ca 200+ and e-learning resources (SPs) in Sweden).

Since the classes are package private and final, it is hard to work around the issue at present.

The only possible workaround seems to be to copy classes.. 

Also, how does one parse and store the other metadata, that was read by the old implementation, such as "organisation.name" when `RelyingPartyRegistration` is final and there are no hooks in the code afaik. Couldn't it be an interface instead? Or expose the XMLObject?

I have a dropdown list to select the IdP by OrgName in my implementation today, that's using the old project.

I'm unable to find a migration guide, and the docs are pretty sparse.

Thanks.

**Comment by jzheaux** [comment]
Hi, @stnor, thanks for the detailed report.

Looks like there are a couple of things here. 

- Address SPSSODescriptor error handling
- Add to SAML Metadata documentation for getting the underlying XMLObject (already supported, undocumented, though)

I've added https://github.com/spring-projects/spring-security/issues/12667 to address the second one. As for the first one, yes, I think that makes sense to add and am happy to use this ticket to address that.

> I'm unable to find a migration guide

It is in our Wiki: https://github.com/spring-projects/spring-security/wiki/SAML-2.0-Migration-Guide - note that the main page didn't have it in the bullet list, so I've added it there to make it easier to see.

**Comment by stnor** [comment]
Great, thanks for the prompt response.

I am looking at the migration guide right now, and I am unable to tell if the URL:s are the same form that page. Granted, I can look at the code, but ideally the URL:s should be documented if they are changed.

I am using this configuration at the moment. I can't tell if they're considered "default" or not.
```
// new DefaultSecurityFilterChain(new AntPathRequestMatcher("/saml/login/**"), samlEntryPoint()),
// new DefaultSecurityFilterChain(new AntPathRequestMatcher("/saml/login/**"), samlLogoutFilter()),
// new DefaultSecurityFilterChain(new AntPathRequestMatcher("/saml/logout/**"), samlEntryPoint()),
// new DefaultSecurityFilterChain(new AntPathRequestMatcher("/saml/SingleLogout/**"), samlLogoutProcessingFilter()),
// new DefaultSecurityFilterChain(new AntPathRequestMatcher("/saml/metadata/**"), samlMetadataDisplayFilter()),
// new DefaultSecurityFilterChain(new AntPathRequestMatcher("/saml/SSO/**"), samlWebSSOProcessingFilter(authenticationManager)),
// new DefaultSecurityFilterChain(new AntPathRequestMatcher("/saml/SSOHoK/**"), samlWebSSOHoKProcessingFilter(authenticationManager)),
// new DefaultSecurityFilterChain(new AntPathRequestMatcher("/saml/discovery/**"), samlIdpDiscovery())
````

**Comment by stnor** [comment]
Ah, I found this: https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/saml2/custom-urls

**Comment by stnor** [comment]
Another question I have if you know if the workaround for AD FS 2.0 and SHA-256 described here https://stackoverflow.com/a/33023514/818090 is needed for SAML 2.0?

**Comment by stnor** [comment]
I think I might be asking for the wrong thing here after looking at #10551 ?

@jzheaux To be clear, I want to participate in the Federation mentioned above as an SP and let the user select what IdP to use for authenticating with my service.

Is this possible with 'new' SAML at present? How to go about it?

**Comment by jzheaux** [comment]
@stnor, yes this is possible. The key is to [reuse the same relying party configuration](https://docs.spring.io/spring-security/reference/servlet/saml2/login/overview.html#servlet-saml2login-rpr-duplicated) for each relying party registration instance.

**Comment by jzheaux** [comment]
Are you able to provide a PR for improving `OpenSamlAssertingPartyDetailsConverter` as you described?

**Comment by stnor** [comment]
I was unsure in which branch you wanted the PR for... The PR is for main, but I am running 5.8.

**Comment by stnor** [comment]
> If you want to have the exact same callback URL for all IdPs, then you will need to [specify how to perform the lookup](https://docs.spring.io/spring-security/reference/servlet/saml2/login/overview.html#servlet-saml2login-rpr-relyingpartyregistrationresolver).

I think it's a shame that the project doesn't provide a more backwards compatible way of migrating from the old project, like a alternative resolver with the same URL for all, but I will take a look at this and see if I can solve it on my own.

Another issue is that is the federation I am in, many of the entityIds are URLs, which you can't have in the non-query string part of the url. The old SAML extension used `login?id={url-encoded}` whereas the new uses /login/{id}

**Comment by stnor** [comment]
Adding what I've got so far. Remaining work includes making /authenticate to work with a query string and hooking in a custom authenticator.

````
    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http,
                                           RefreshableRelyingPartyRegistrationRepository rpRepo) throws Exception {
        RelyingPartyRegistrationResolver relyingPartyRegistrationResolver =
                new DefaultRelyingPartyRegistrationResolver(rpRepo);
        http.saml2Login(samlLogin ->
                samlLogin
                        .authenticationConverter(new Saml2AuthenticationTokenConverter(relyingPartyRegistrationResolver))
                        .loginProcessingUrl("/saml/SSO"));
        http.saml2Logout(samlLogout ->
                samlLogout
                        .logoutUrl("/saml/SingleLogout")
                        .relyingPartyRegistrationRepository(rpRepo));
//        Saml2MetadataFilter metadataFilter = new Saml2MetadataFilter(relyingPartyRegistrationResolver,
//                new OpenSamlMetadataResolver());
//        http.addFilterBefore(metadataFilter, Saml2WebSsoAuthenticationFilter.class);
````

````
@Component
public class RefreshableRelyingPartyRegistrationRepository
        implements RelyingPartyRegistrationRepository, Iterable<RelyingPartyRegistration> {

    private final static Logger LOGGER = LoggerFactory.getLogger(RefreshableRelyingPartyRegistrationRepository.class);
    private static final char[] SAML_JKS_PASSWORD = "pass".toCharArray();
    public static final String SAML_JKS_PATH = "classpath:saml/saml.jks";
    public static final String SAML_JKS_ALIAS = "keyalias";

    private final Map<String, RelyingPartyRegistration> relyingPartyRegistrations = new ConcurrentHashMap<>();

    private static final ResourceLoader resourceLoader = new DefaultResourceLoader();
    private final Saml2X509Credential signingCredentials;

    public RefreshableRelyingPartyRegistrationRepository() {
        this.signingCredentials = createSigningCredentials();
        refreshMetadata();
    }

    @Override
    public RelyingPartyRegistration findByRegistrationId(String registrationId) {
        return this.relyingPartyRegistrations.get(registrationId);
    }

    @Override
    public Iterator<RelyingPartyRegistration> iterator() {
        return this.relyingPartyRegistrations.values().iterator();
    }

    @Scheduled(fixedDelay = 30, timeUnit = TimeUnit.MINUTES)
    public void refreshMetadata() {
        fetchMetadata();
    }

    void fetchMetadata() {
        LOGGER.info("Fetching metadata from Skolfederation");

        //All IdP:s
        RelyingPartyRegistrations
                .collectionFromMetadataLocation("https://fed.skolfederation.se/prod/md/skolfederation-3_1.xml")
                .forEach(builder -> {
                    builder.entityId("https://nomp.se");
                    builder.assertionConsumerServiceLocation("https://nomp.se/saml/SSO");
                    builder.signingX509Credentials(credentials -> credentials.add(this.signingCredentials));
                    builder.assertingPartyDetails(apdBuilder -> {
                        apdBuilder.wantAuthnRequestsSigned(true);
                    });
                    RelyingPartyRegistration idp = builder.build();
                    this.relyingPartyRegistrations.put(idp.getRegistrationId(), idp);
                });
    }

    private Saml2X509Credential createSigningCredentials() {
        try {
            KeyStore ks = KeyStore.getInstance("JKS");
            ks.load(resourceLoader.getResource(SAML_JKS_PATH).getInputStream(), SAML_JKS_PASSWORD);
            var cert = (X509Certificate) ks.getCertificate(SAML_JKS_ALIAS);
            var key = (PrivateKey) ks.getKey(SAML_JKS_ALIAS, SAML_JKS_PASSWORD);
            return new Saml2X509Credential(key, cert, Saml2X509Credential.Saml2X509CredentialType.SIGNING);
        } catch (Exception e){
           throw new RuntimeException(e);
        }
    }

}

````

**Comment by stnor** [comment]
I think I have most things working now, but I cannot figure out how to register a success and failure handler with the `Saml2WebSsoAuthenticationFilter`.

**Comment by stnor** [comment]
Is there support for discovery?
I have the following in my metadata today:
````
<md:Extensions>
<idpdisco:DiscoveryResponse xmlns:idpdisco="urn:oasis:names:tc:SAML:profiles:SSO:idp-discovery-protocol" Binding="urn:oasis:names:tc:SAML:profiles:SSO:idp-discovery-protocol" Location="https://nomp.se/saml/login?disco=true" index="0"/>
</md:Extensions>
````
Today I point the login button to /saml/login which, if logged in, gets the user signed on without Idp selection. Otherwise to idp selection. Using saml2 I'm getting a 404 unless I specify an RP using my `?idp=`-QueryStringRelyingPartyResolver

**Comment by stnor** [comment]
I ended up with this to fix the 404:
````
@Controller
public class Saml2LoginRedirectController {
    public final static String LOGIN_REDIRECT = "/saml/login";

    @RequestMapping(LOGIN_REDIRECT)
    public RedirectView redirectToLogin() {
        return new RedirectView("/start/login/saml");
    }
}
````
and
````
        http.saml2Login(samlLogin ->
                samlLogin
                        .loginPage(LOGIN_REDIRECT)
````

@jzheaux Any feedback appreciated. Also please take a look at the PR.

**Comment by stnor** [comment]
Thanks @jzheaux!
So, other than the incorrect branch, you're happy with the PR? If so, I'll close the PR and provide another for 5.7.x.

**Comment by stnor** [comment]
Apologies. I am not able to fix the previous PR. It's beyond my git/committer skills :(

Closing the old: https://github.com/spring-projects/spring-security/pull/12742

**Comment by stnor** [comment]
> I think the easiest way for me to comment on your project is to have a GitHub sample. I'd be happy to provide a PR that simplifies what you've got so far, including providing feedback on the 404, etc.

I cannot tell you how much I appreciate this. See https://github.com/stnor/fed-saml-example/issues/1

**Comment by abinesh-s** [comment]
@stnor , request you to take a look at below one and suggest how that can be handled

https://github.com/spring-projects/spring-security/issues/12812

**Comment by lasselindqvist** [comment]
@jzheaux is there any plan to release this fix as part of the 5.8.x version?
The fix cmmit (https://github.com/stnor/spring-security/commit/ccb292ca6ab59dba7dc4b885147ccf46ae1a567b) is not in 5.8.1 at least.

What would be the way to get it into the next milestone? (https://github.com/spring-projects/spring-security/milestone/285)

**Comment by jzheaux** [comment]
@lasselindqvist, that was added in `5.8.x` as 6c7703789a06b44730f5659e3c4eb0b0bdd9b2b5, so that will go out in the `5.8.3` release.

**Comment by jzheaux** [comment]
I've created https://github.com/spring-projects/spring-security/issues/13054 now to clarify that.
