### ISSUE TITLE
samples/xml/insecuremvc is empty

### ISSUE THREAD

**Issue by KitPyles** [spring-projects/spring-security#12666]
I am trying to code along with the [Hello Spring MVC Security Java Config](https://docs.spring.io/spring-security/site/docs/4.1.3.RELEASE/guides/html5/hellomvc-javaconfig.html) guide. However, the referenced directory doesn't include any project files. The guide states that I need to run the `insecuremvc` project to verify that it works. But, there is no project to run. I have tried using both the zip file linked in the guide, & this repo. The referenced directory has no project.

**Comment by jzheaux** [comment]
Hi, @KitPyles, sorry you are having trouble. The link you provided is for Spring Security 4.1.3, and so you'd find the samples [in the `4.1.x` branch](https://github.com/spring-projects/spring-security/tree/4.1.x/samples/xml/insecuremvc).

That said, Spring Security 4 is no longer supported. Please consider using the [Spring Security Samples project](https://github.com/spring-projects/spring-security-samples/tree/main/servlet) instead.
