### ISSUE TITLE
Typo in Authentication Migrations page

### ISSUE THREAD

**Issue by buzzerrookie** [spring-projects/spring-security#12660]
In the [Authentication Migrations](https://docs.spring.io/spring-security/reference/migration/servlet/authentication.html) page, there's a typo in the frist section.

**Describe the bug**
`by setting rethrowAuthenticationServiceException too true`

**Expected behavior**
`by setting rethrowAuthenticationServiceException to true`

**Comment by buzzerrookie** [comment]
I've created a PR to fix this, https://github.com/spring-projects/spring-security/pull/12661

**Comment by jzheaux** [comment]
Closed in https://github.com/spring-projects/spring-security/commit/26fc15a8b3b7a2cd81265a63024f0cfbe4c12b9a
