### ISSUE TITLE
Remove deprecated `SecurityContextPersistenceFilter` from docs

### ISSUE THREAD

**Issue by wiketool** [spring-projects/spring-security#12690]
**Expected Behavior**
The [Authentication](https://docs.spring.io/spring-security/reference/servlet/authentication/architecture.html#servlet-authentication-authentication) is set on the [SecurityContextHolder](https://docs.spring.io/spring-security/reference/servlet/authentication/architecture.html#servlet-authentication-securitycontextholder). Later, if you need to save `SecurityContext` , `SecurityContextRepository#saveContext` must be explicitly invoked.See the [`SecurityContextHolderFilter`](https://docs.spring.io/spring-security/site/docs/6.0.1/api/org/springframework/security/web/context/SecurityContextHolderFilter.html) class.

**Current Behavior**
The [Authentication](https://docs.spring.io/spring-security/reference/servlet/authentication/architecture.html#servlet-authentication-authentication) is set on the [SecurityContextHolder](https://docs.spring.io/spring-security/reference/servlet/authentication/architecture.html#servlet-authentication-securitycontextholder). Later, the SecurityContextPersistenceFilter saves the SecurityContext to the HttpSession. See the [SecurityContextPersistenceFilter](https://docs.spring.io/spring-security/site/docs/6.0.1/api/org/springframework/security/web/context/SecurityContextPersistenceFilter.html) class.

[link to related pages](https://docs.spring.io/spring-security/reference/servlet/authentication/architecture.html#servlet-authentication-securitycontextholder:~:text=The%20Authentication%20is%20set%20on%20the%20SecurityContextHolder.%20Later%2C%20the%20SecurityContextPersistenceFilter%20saves%20the%20SecurityContext%20to%20the%20HttpSession.%20See%20the%20SecurityContextPersistenceFilter%20class.)

**Comment by sjohnr** [comment]
Thanks @wiketool! Let me know if you are interested in submitting a PR.

**Comment by wiketool** [comment]
> Thanks @wiketool! Let me know if you are interested in submitting a PR.

Thank you! I feel very proud to become a contributor Spring Security. I have made a pr in #12747.
