### ISSUE TITLE
SEC-1022: Remove use of static methods/initializers in Acl Permissions

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1272]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-1022":https://jira.spring.io/browse/SEC-1022?redirect=false]) said:

This has caused some problems and reduces the pluggability of Permission generation strategies, so we've agreed it should be modified in 2.5. PermissionFactory should probably also be modified to contain more of the methods that are currently static, allowing implementations to be called when evaluating expressions, for example (see PermissionEvaluator, AclPermissionEvaluator).

**Comment by spring-issuemaster** [comment]
This issue supersedes #1253
