### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by coding-career** [spring-projects/spring-security#12754]
**Describe the bug**
Failed to read schema document 'http://www.springframework.org/schema/security/spring-security-oauth2-2.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not xsd:schema.

Where this file moved and where should refer to now?

BTW, this directory is just new changed today: https://www.springframework.org/schema/security/, but where the oauth2 related files have been moved?

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

Please help provide the solution ASAP since our production env has crashed now.

**Comment by antharir** [comment]
I'm also facing the similar issue for https://www.springframework.org/security/spring-security.xsd

**Comment by jakeab** [comment]
My application in a test environment is failing to start because of the 404 of
http://www.springframework.org/schema/security/spring-security-oauth2-2.0.xsd

While I understand that the library is no longer maintained, keeping compatibility for production applications seems reasonable:
https://github.com/spring-attic/spring-security-oauth/

Right now I assume my production cluster will fail to start any fresh containers.

**Comment by coding-career** [comment]
Anyone can help? Thanks in advance.

**Comment by glydecovy** [comment]
I'm also facing the similar issue for "https://www.springframework.org/security/spring-security.xsd."

please recover this file.

**Comment by fkfausa** [comment]
We are also facing the missing https://www.springframework.org/security/spring-security.xsd issue. We have experimented by updating to exact version and that seems work.

**Comment by jbrugge** [comment]
We have been able to get around the issue for the time being by replacing references to the XSD online with references to it in the JAR file. For the OAuth2 XSD at "http://www.springframework.org/schema/security/spring-security-oauth2-2.0.xsd", we instead refer to our particular installation via "jar:file:///usr/local/tomcat/webapps/ROOT/WEB-INF/lib/spring-security-oauth2-2.5.2.RELEASE.jar!/org/springframework/security/oauth2/spring-security-oauth2-2.0.xsd".

**Comment by coding-career** [comment]
> We have been able to get around the issue for the time being by replacing references to the XSD online with references to it in the JAR file. For the OAuth2 XSD at "http://www.springframework.org/schema/security/spring-security-oauth2-2.0.xsd", we instead refer to our particular installation via "jar:file:///usr/local/tomcat/webapps/ROOT/WEB-INF/lib/spring-security-oauth2-2.5.2.RELEASE.jar!/org/springframework/security/oauth2/spring-security-oauth2-2.0.xsd".

So many thanks, @jbrugge. since I ever read an article that the local file has been not supported so haven't tried it ever. I'll have a try, it's good news.

**Comment by coding-career** [comment]
The local version can work, and the remote http/https services also could access now. Close it then.
