### ISSUE TITLE
Document relationship between registrationId, EntityID, and resolving a relying party

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#12764]
Based on https://github.com/spring-projects/spring-security/issues/12664, the documentation around SAML 2.0 URIs could be clearer.

Specifically, it should be clearer when and why setting a `registrationId` or configuring relying party lookup is important. One reason that it is important is that `RelyingPartyRegistrations` defaults the `registrationId` to be the asserting party's entity id, which cannot be placed in the path of URIs like `/authenticate/{registrationId}`. Either the relying party lookup strategy needs or the registration id needs to change.

**Comment by stnor** [comment]
Regarding this, it's not practical to "invent" new id:s for 200 IdPs in a large federation. The business key in the metadata is the entityId, right?

**Comment by jzheaux** [comment]
@stnor thanks for the feedback, but I think this strays from the focus of this issue which is to improve the documentation. 

I'm very happy about your interest in migrating to Spring Security, and I want to help. So far, I realize that I've been responding to your thoughts and questions wherever they are appearing. Going forward, please feel free to open a ticket if you have an enhancement you want to discuss. Otherwise, you can engage me and the team over chat on [Gitter](https://gitter.im/spring-projects/spring-security) and/or [Stackoverflow](https://stackoverflow.com). That will help keep each ticket focused on its primary task.

**Comment by jzheaux** [comment]
Also note that as part of the documentation improvement here, https://github.com/spring-projects/spring-security-samples/issues/122 was added.
