### ISSUE TITLE
Since WebSecurityConfigurerAdapter is removed, any alternative solution for WebSecurityConfigurerAdapter.getHttp() method?

### ISSUE THREAD

**Issue by JasmineXieCCD** [spring-projects/spring-security#12773]
**Expected Behavior**

**Current Behavior**

**Context**

**Comment by marcusdacoregio** [comment]
Hi @JasmineXieCCD,

can you describe your use case in detail?

**Comment by sivrim** [comment]
@JasmineXieCCD , You can get HttpSecurity bean through dependency injection unless you have very custom solution. WebSecurityConfigurerAdapter has been replaced with SecurityFilterChain for making the flow more component oriented, but the common usage patterns remain almost same. Please see [this article](https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter)

**Comment by marcusdacoregio** [comment]
I think this has been answered, therefore I'm closing this. @JasmineXieCCD, feel free to continue discussing if you still have a problem.
