### ISSUE TITLE
Use RoleHierarchy bean in Method Security Configuration

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#12783]
`authorityHttpRequests` picks up a `RoleHierarchy` bean. If method security does the same thing, then it will simplify security configuration overall.

Currently, method security role hierarchy must be configured for each authorization manager individually via `DefaultMethodSecurityExpressionHandler` for pre-post annotations, `AuthoritiesAuthorizationManager` for secured annotations, and via a custom authorization manager for JSR-250 annotations.

**Comment by kandaguru17** [comment]
Happy to work on this :) @jzheaux 

Have Some Queries here :

1. In the issue description `authorityHttpRequests picks up a RoleHierarchy bean.`, does this means `AuthorizeHttpRequestsConfigurer` uses the injected `ApplicationContext` to retrieve the `RoleHierarchy` bean
2. Enabling a similar behavior in `DefaultMethodSecurityExpressionHandler` and `AuthoritiesAuthorizationManager`  would need us to inject the `ApplicationContext` in the constructor of both the classes, and is there any suggestion you have to handle the side effects of this as the default constructor is used in some places.

Please correct me if my understanding is not correct

**Comment by wilx** [comment]
This issue is linked from the docs at <https://docs.spring.io/spring-security/reference/servlet/authorization/architecture.html#authz-hierarchical-roles> with a note:

> RoleHierarchy bean configuration is not yet ported over to @EnableMethodSecurity. As such this example is using AccessDecisionVoter. If you need RoleHierarchy support for method security, please continue using @EnableGlobalMethodSecurity until [github.com/spring-projects/spring-security/issues/12783](https://github.com/spring-projects/spring-security/issues/12783) is complete.

Is the note still valid?
