### ISSUE TITLE
404 not found for link in OAuth 2.0 docs

### ISSUE THREAD

**Issue by Anubhav-2000** [spring-projects/spring-security#12824]
In https://docs.spring.io/spring-security/reference/servlet/oauth2/login/core.html , the link for [OAuth 2.0 Login sample](https://github.com/spring-projects/spring-security-samples/tree/main/boot/oauth2login) leads to 404 not found.

**Comment by jzheaux** [comment]
Thanks, @Anubhav-2000! I believe the correct link is https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/oauth2/login

Are you able to provide a PR that updates the link in the `6.0.x` branch? I should likely be like this:

```
{gh-samples-url}/servlet/spring-boot/java/oauth2/login
```

**Comment by lbkulinski** [comment]
@jzheaux I have created a PR to fix this issue. Please let me know if anything is needed. Thanks!
