### ISSUE TITLE
@PreAuthorize is not working after migration from authorizeRequests to authorizeHttpRequests

### ISSUE THREAD

**Issue by roon-replica** [spring-projects/spring-security#12861]
**Describe the bug**
I migrated to spring boot 3 and changed `authorizeRequests` to `authorizeHttpRequests`. But `@PreAuthorize` is not working in my RestController after migration. 
I digged a little about why. When Using `authorizeRequests`, `FilterSecurityInterceptor` is configured in filterChain(which is deprecated now). But when using `authorizeHttpRequests`, `AuthorizationFilter` is in use on behalf of `FilterSecurityInterceptor`.
In `AuthorizationFilter`, AuthorizationDecision's granted field is false. So AccessDeniedException occur and `AbstractPreAuthenticatedProcessingFilter`'s doAuthenticate() does not invoked.

---

**SecurityConfig.java**
```java
@EnableMethodSecurity
@EnableWebSecurity(debug = true)
@Configuration
public class SecurityConfig {

	@Bean
	public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
		http.csrf().disable()
				.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS).and()
				.headers().frameOptions().disable().and()
				.authorizeRequests().requestMatchers("/").permitAll().and() // @PreAuthorize works
//				.authorizeHttpRequests().requestMatchers("/").permitAll().and() // @PreAuthorize does not works
				.exceptionHandling().authenticationEntryPoint(http403ForbiddenEntryPoint());

		return http.build();
	}

	@Bean
	public AdminAuthenticationProvider adminAuthenticationProvider() {
		return new AdminAuthenticationProvider();
	}

	@Bean
	public AdminAuthenticationFilter adminAuthenticationFilter() {
		return new AdminAuthenticationFilter(adminAuthenticationProvider(), -1);
	}

	@Bean
	public AuthenticationEntryPoint http403ForbiddenEntryPoint() {
		return new Http403ForbiddenEntryPoint();
	}
}
```

**SampleMethodSecurityController.java**
```java
@PreAuthorize("hasRole('ADMIN')")
@RestController
public class SampleMethodSecurityController {

	@GetMapping("/health-check")
	public String healthCheck(){
		return "ok";
	}
}
```

**Sample**
you can see my example code in [my github repo](https://github.com/roon-replica/spring-security-lecture/tree/test/pre-auth-not-working)
Also created [pull request](https://github.com/roon-replica/spring-security-lecture/pull/1) to be able to see only related changes.

**Comment by roon-replica** [comment]
I realized reason of malfunction. Default request with no auth rule is denied as default in spring security 6. So I changed to permit all requests and partially applied @PreAuthorize on resources to protect.

**Comment by AnzhiZhang** [comment]
> I realized reason of malfunction. Default request with no auth rule is denied as default in spring security 6. So I changed to permit all requests and partially applied @PreAuthorize on resources to protect. This works for me. Close issue myself.

But is there a way to set use @PreAuthorize on a controller method, when set anyRequest have to be authenticated?
One way is use requestMatchers().permitAll, but I do not want split my controller and permit in two places

**Comment by straurob** [comment]
> So I changed to permit all requests and partially applied @PreAuthorize on resources to protect. This works for me.

I don't have much experience with Spring Security, but this sounds like a flaw. The documentation explicity recommends using a "catch-all" approach with `anyRequest().authenticated()`. 

Is there no other way to resolve this problem?

**Comment by falconwoods** [comment]
> > So I changed to permit all requests and partially applied @PreAuthorize on resources to protect. This works for me.
> 
> I don't have much experience with Spring Security, but this sounds like a flaw. The documentation explicity recommends using a "catch-all" approach with `anyRequest().authenticated()`.
> 
> Is there no other way to resolve this problem?

Agreed, should have an approach to set default behavior as authenticated for all APIs and then use @PreAuthorize("permitAll()") to make some APIs public explicitly.
Better than explicitly making some APIs protected.

**Comment by aminabromand** [comment]
I do not understand, why this was closed.
Ok, the workaround might work, but it is a workaround not a solution, isn't it?

**Comment by dreamstar-enterprises** [comment]
I have the same problem. @preauthorize does not work on any of my services.
