### ISSUE TITLE
Incomplete documentation for Reactive apps with CSRF cookie repo?

### ISSUE THREAD

**Issue by ch4mpy** [spring-projects/spring-security#12871]
**Describe the bug**
Following the [migration guide for reactive applications](https://docs.spring.io/spring-security/reference/5.8/migration/reactive.html#_i_am_using_angularjs_or_another_javascript_framework), 
I configured a WebFlux application with `http.csrf().csrfTokenRepository(CookieServerCsrfTokenRepository.withHttpOnlyFalse()).csrfTokenRequestHandler(new XorServerCsrfTokenRequestAttributeHandler()::handle)` and a `WebFilter` bean to "ensure the token is subscribed to",
but I can't find any CSRF cookie  anywhere in my browser debugging tools (neither with `XSRF-TOKEN` "standard" name, nor with any other name: the only cookie is the session one).

**To Reproduce**
With this very simple Boot app:
```java
@SpringBootApplication
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

	@EnableWebFluxSecurity
	@Configuration
	static class WebSecurityConf {
		@Bean
		SecurityWebFilterChain securityFilterChain(ServerHttpSecurity http, ServerProperties serverProperties) {
			http.oauth2Client();
			http.authorizeExchange().pathMatchers("/login/**", "/oauth2/**").permitAll().anyExchange().authenticated();
			http.oauth2Login();
			http.logout().logoutUrl("/logout");

			CookieServerCsrfTokenRepository tokenRepository = CookieServerCsrfTokenRepository.withHttpOnlyFalse();
			XorServerCsrfTokenRequestAttributeHandler delegate = new XorServerCsrfTokenRequestAttributeHandler();
			http.csrf().csrfTokenRepository(tokenRepository).csrfTokenRequestHandler(delegate::handle);
			return http.build();
		}

		@Bean
		WebFilter csrfCookieWebFilter() {
			return (exchange, chain) -> {
				Mono<CsrfToken> csrfToken = exchange.getAttributeOrDefault(CsrfToken.class.getName(), Mono.empty());
				return csrfToken.doOnSuccess(token -> {
					System.out.println(token);
				}).then(chain.filter(exchange));
			};
		}
	}
}
```
This prints `null` and I have no CSRF cookie.

**Expected behavior**
I expect a CSRF cookie to be set

**Sample**
https://github.com/ch4mpy/gh-12871

**Comment by Shaquu** [comment]
Relates to #12869

**Comment by ch4mpy** [comment]
> Relates to #12869

@Shaquu not exactly: my problem is not related CSRF token validation, it is I don't have a cookie at all.

**Comment by ch4mpy** [comment]
@lglauer I had missed that part, thank you for pointing me to it. This works for servlets but, unfortunately, the doc seems to be [missing something for reactive applications](https://docs.spring.io/spring-security/reference/5.8/migration/reactive.html#_i_am_using_angularjs_or_another_javascript_framework) (and I'm trying to configure a `spring-cloud-gateway` instance).

I updated the issue with what is in the migration guide for reactive apps.

**Comment by ch4mpy** [comment]
Found my issue: I had accidentally imported `org.springframework.security.web.csrf.CsrfToken` instead of `org.springframework.security.web.server.csrf.CsrfToken` which caused the `WebFilter` to fail retrieving the CSRF token from exchange attributes.
