### ISSUE TITLE
BCryptPasswordEncoder apparently uses an incorrect pattern

### ISSUE THREAD

**Issue by NadChel** [spring-projects/spring-security#12929]
It sounds implausible, but it seems the pattern that `BCryptPasswordEncoder` uses is incorrect. It has an unescaped slash. If I escape it manually, the match occurs 🤷‍♂️

![2023-03-26_14-12-27](https://user-images.githubusercontent.com/121400546/227773230-b7877f3b-6543-42af-ac1a-d66e167053b9.png)
![2023-03-26_14-12-41](https://user-images.githubusercontent.com/121400546/227773240-ba0aeade-2ec9-4e1a-bc7a-005029ad7c36.png)
![2023-03-26_14-22-10](https://user-images.githubusercontent.com/121400546/227773246-8c5532a2-6d59-4fce-ac32-a7cffa721fb3.png)
![2023-03-26_14-25-50](https://user-images.githubusercontent.com/121400546/227773254-13dff424-0be7-4d8f-b0f8-55f55140ee94.png)

**Comment by NadChel** [comment]
> Hi, @NadChel, thanks for the report. Can you do me a favor by adding to your report something a bit more copy-pastable? The images, while helpful for context, are difficult to use in the way of generating a unit test that can confirm the behavior you are seeing. A [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) is ideal.
> 
> Note that the following unit test passes, which makes me think we are missing something here:
> 
> ```java
> @Test
> public void matches() {
>     BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
>     String password = "mickey";
>     String encoded = encoder.encode(password);
>     assertThat(encoder.matches(password, encoded)).isTrue();
> }
> ```
> 
> Furthermore, something roughly like your hash also passes:
> 
> ```java
> @Test
> public void slashPasses() {
> 	Pattern pattern = Pattern.compile("\\A\\$2(a|y|b)?\\$(\\d\\d)\\$[./0-9A-Za-z]{53}");
> 	assertThat(pattern.matcher("$2a$10$zJijCisT3IVbh5v2AitaJOwkfEy3VPvBmaYzdf/K.0/rCS7S3glQe").matches()).isTrue();
> }
> ```
> 
> If I were to guess, the issue is the `{bcrypt}` value on the front which is, indeed, not a valid prefix for a BCrypt hash. That is added/removed when using `PasswordEncoderFactories.createDelegatingPasswordEncoder()`. So, if you encoded with that encoder, but then decoded directly with `BCryptPasswordEncoder`, then that would cause this behavior. For example:
> 
> ```java
> @Test
> public void failsToMatch() {
>     PasswordEncoder delegating = PasswordEncoderFactories.createDelegatingPasswordEncoder();
>     BCryptPasswordEncoder bcrypt = new BCryptPasswordEncoder();
>     String password = "mickey";
>     String encoded = delegating.encode(password);
>     assertThat(bcrypt.matches(password, encoded)).isFalse();
> }
> ```
> 
> Is that enough context to address the issue?

You were right, removing `{bcrypt}` indeed resolved the situation (a while ago, actually). I'm sorry I didn't inform you earlier. I can't say I understood your explanation (I was told in one course video to include those `{bcrypt}` prefixes in my table), but I appreciate your effort 🙏

**Comment by jzheaux** [comment]
Glad you got it working, @NadChel.

The `{bcrypt}` prefix is needed if you are using `PasswordEncoderFactories`, for example:

```java
@Bean 
PasswordEncoder passwordEncoder() {
    return PasswordEncoderFactories.createDelegatingPasswordEncoder(); // should use {bcrypt} prefix
}
```

If you are using `BCryptPasswordEncoder` directly (or any other password encoder directly), then the prefix is not needed. For example:

```java
@Bean 
PasswordEncoder passwordEncoder() {
    return new BCryptPasswordEncoder(); // should not use {bcrypt} prefix
}
```

The reason is because `PasswordEncoderFactories` supports many formats simultaneously. So, it requires a prefix to tell which algorithm is used for each hash.
