### ISSUE TITLE
SEC-1045: Allow use of custom SecurityContextRepository stratgey through the namespace

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1296]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-1045":https://jira.spring.io/browse/SEC-1045?redirect=false]) said:

An security-context-repository-ref attribute will  be added to the <http> element.

**Comment by spring-issuemaster** [comment]
This issue depends on #1290
