### ISSUE TITLE
Access to "/" on actuator on dedicated port with security configuration does not work.

### ISSUE THREAD

**Issue by frederic-kneier** [spring-projects/spring-security#12968]
**Describe the bug**
Access to "/" on a dedicated actuator port is not allowed, even if specified in security filter chain.

**To Reproduce**

Add `http.authorizeRequests().requestMatchers(EndpointRequest.toAnyEndpoint()).permitAll()` to security filter chain.
Add `management.server.port=8081` to application.properties

Access `http://localhost:8081/` will lead to HTTP 401.

**Expected behavior**
Since index is included in EndpointRequest.toAnyEndpoint(), acess should be allowed to "/" on dedicated actuator port.

**Comment by marcusdacoregio** [comment]
Hi @frederic-kneier,

I tried myself with the configuration you provided and instead I get a 404, therefore the endpoint is allowed.
I was not able to reproduce the 401, can you provide a minimal, reproducible sample where I can replay the same behavior?

**Comment by frederic-kneier** [comment]
Of cause. The following setup will require login to the root of the management endpoint on port 9000. In this config it leads to a basic login request.

Dependencies
``` kotlin
implementation("org.springframework.boot:spring-boot-starter-webflux:3.0.5")
implementation("org.springframework.boot:spring-boot-starter-actuator:3.0.5")
implementation("org.springframework.boot:spring-boot-starter-security:3.0.5")
```
Application.yaml
```yaml
management:
  server:
    port: 9000
  endpoints:
    web:
      base-path: /
```

Application:

```kotlin
@SpringBootApplication
open class Application {
    @Bean
    open fun securityChain(http:ServerHttpSecurity) = http.run {
        authorizeExchange().matchers(EndpointRequest.toAnyEndpoint()).permitAll()
        build()
    }
}

fun main(args: Array<String>) {
    runApplication<Application>(args = args)
}

```
