### ISSUE TITLE
Release 5.8.3

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#12988]

**Comment by lasselindqvist** [comment]
Hi. Not sure if this is the right place to mention this, but I believe as the fix for https://github.com/spring-projects/spring-security/issues/12664 is in 5.8.x branch, it should be included in this milestone, but currently is not.

**Comment by jzheaux** [comment]
@lasselindqvist, thanks for reaching out. It looks like the 5.8.x forward port ticket didn't get created. You can see it here now: https://github.com/spring-projects/spring-security/issues/13054
