### ISSUE TITLE
RoleHierarchyImpl should support simple tree hierarchies

### ISSUE THREAD

**Issue by chkpnt** [spring-projects/spring-security#13065]
**Expected Behavior**

Using the following `RoleHierarchyImpl`, I would expect `ROLE_ADMIN` contains `ROLE_EDITOR_A` and `ROLE_EDITOR_B`:

```java
RoleHierarchyImpl roleHierarchy = new RoleHierarchyImpl();
roleHierarchy.setHierarchy("ROLE_ADMIN > ROLE_EDITOR_A \n ROLE_ADMIN > ROLE_EDITOR_B");
```

**Current Behavior**

Only `ROLE_ADMIN > ROLE_EDITOR_A` is parsed, due to this condition in [buildRolesReachableInOneStepMap](https://github.com/spring-projects/spring-security/blob/5.8.x/core/src/main/java/org/springframework/security/access/hierarchicalroles/RoleHierarchyImpl.java#L168 )

**Context**

On the one hand, I do not think this is a bug, since the code is that old that such a simple non-working role mapping as defined should have been discovered much earlier. 

On the other hand,
```java
RoleHierarchyUtils.roleHierarchyFromMap(Map.of("ROLE_ADMIN", Arrays.asList("ROLE_EDITOR_A", "ROLE_EDITOR_B")))
```
[is returning](https://github.com/spring-projects/spring-security/blob/5.8.x/core/src/main/java/org/springframework/security/access/hierarchicalroles/RoleHierarchyUtils.java#L47-L59) this non-working `roleHierarchyStringRepresentation`.

**Comment by jzheaux** [comment]
Hi, @chkpnt, thanks for reaching out.

I'm sorry, I'm not able to reproduce the behavior you are describing. Please see [this test](https://github.com/spring-projects/spring-security/blob/5.8.x/core/src/test/java/org/springframework/security/access/hierarchicalroles/RoleHierarchyImplTests.java#L92) which demonstrates the behavior working as you describe (or at least how I'm understanding your report).

While there may still be a bug, I'm going to need more information from you. Would you please post a failing unit test?

**Comment by chkpnt** [comment]
Well... I have to say, I'm a little embarrassed not to be able to reproduce it myself! Furthermore, I do not see the issue in the code which I saw last week. I really can't tell what I did wrong last week. But this is working as it should:

```java
@Test
public void testSimpleComplexRoleHierarchy() {
    List<GrantedAuthority> authoritiesInput1 = AuthorityUtils.createAuthorityList("ROLE_A");
    List<GrantedAuthority> authoritiesOutput1 = AuthorityUtils.createAuthorityList("ROLE_A", "ROLE_B", "ROLE_C");
    RoleHierarchyImpl roleHierarchyImpl = new RoleHierarchyImpl();
    roleHierarchyImpl.setHierarchy("ROLE_A > ROLE_B\nROLE_A > ROLE_C");
    assertThat(HierarchicalRolesTestHelper.containTheSameGrantedAuthorities(
		roleHierarchyImpl.getReachableGrantedAuthorities(authoritiesInput1), authoritiesOutput1)).isTrue();
}
```

Sorry for wasting your time. :-/
