### ISSUE TITLE
rolePrefix with empty string returns HTTP 400 as of version 6.0.3

### ISSUE THREAD

**Issue by mbreevoort** [spring-projects/spring-security#13079]
**Describe the bug**
In version 6.0.3 our application returns a HTTP 400 with message `Administrator should not start with  since  is automatically prepended when using hasAnyRole. Consider using hasAnyAuthority instead.` This is an IllegalArgumentException

Change is here (check on the prefix which triggers on empty string) 
[AuthorityAuthorizationManager.java#L128](https://github.com/spring-projects/spring-security/blame/f588f9fa9a03aa7219712facdffc66b0465e892a/core/src/main/java/org/springframework/security/authorization/AuthorityAuthorizationManager.java#L128)

This is because we use rolePrefix "" (empty string)
```
final JwtGrantedAuthoritiesConverter authoritiesConverter = new JwtGrantedAuthoritiesConverter();
        authoritiesConverter.setAuthorityPrefix("");
        ....
        
GrantedAuthorityDefaults grantedAuthorityDefaults() {
        return new GrantedAuthorityDefaults("");
    }
```

When using rolePrefix empty string Jsr250AuthorizationManager it calls
 `return AuthorityAuthorizationManager.hasAnyRole(Jsr250AuthorizationManager.this.rolePrefix,`

**To Reproduce**
Set rolePrefix to empty String

**Expected behavior**
If allowed for security reasons same behavior as version 6.0.2, allow empty string for role prefix.

**Comment by jzheaux** [comment]
Thanks, @mbreevoort, I've assigned this to the next maintenance release.

Out of curiosity, why are you using `hasRole` and no role prefix? That sounds quite similar to `hasAuthority`. I wonder if `hasAuthority` would address your issue.

**Comment by almeidaah** [comment]
@jzheaux is there any official date to the release?  thanks
