### ISSUE TITLE
SAML: Logging of requests, and improved logging for troubleshooting in general

### ISSUE THREAD

**Issue by stnor** [spring-projects/spring-security#13138]
**Expected Behavior**
I would like to log incoming SAML requests and responsesm which was straightforward in the old SAML-extension.

**Current Behavior**
I don't think there is a straightforward way to log requests for debugging purposes?

**Context**
I am trying to resolve issues with SAML auth but even at trace logging, requests do not get logged.

In general, there is a need to provide a better logging experience for troubleshooting issue at debug and/or trace perhaps. Presently I don't get enough logging to troubleshoot issues from the log.

**Comment by jzheaux** [comment]
Thanks, @stnor. Please feel free to follow https://github.com/spring-projects/spring-security/issues/11592 for this feature.
