### ISSUE TITLE
Broke link in OAuth 2.0 migration link

### ISSUE THREAD

**Issue by ciis0** [spring-projects/spring-security#13149]
> Spring Security exposes the same functionality [via the Spring Security DSL](https://github.com/spring-projects/spring-security/blob/master/config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java#L2308), which is configured by extending WebSecurityConfigurerAdapter.
> 
> -- https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide/c6ad6ba60790576f61a1f586608ec19f717b7281#a-simplified-dsl

at that point in time that was likely https://github.com/spring-projects/spring-security/blob/5.3.0.RELEASE/config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java#L2308

maybe a link to javadoc is more useful?

https://docs.spring.io/spring-security/site/docs/5.8.x/api/org/springframework/security/config/annotation/web/builders/HttpSecurity.html#oauth2ResourceServer()

**Comment by sjohnr** [comment]
Wiki updated via [9235bb2](https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide/_compare/c6ad6ba60790576f61a1f586608ec19f717b7281...9235bb258f04501ca58846d326678840cce35628)
