### ISSUE TITLE
Make DefaultMethodSecurityExpressionHandler#createSecurityExpressionRoot(Supplier<Authentication>, MethodInvocation) to public or proteced

### ISSUE THREAD

**Issue by XiaotianZha** [spring-projects/spring-security#13151]
https://github.com/spring-projects/spring-security/blob/a4e13c520b351c48378d0287167e53cfc581de46/core/src/main/java/org/springframework/security/access/expression/method/DefaultMethodSecurityExpressionHandler.java#L100

As the title, so we can extends DefaultMethodSecurityExpressionHandle easizer to create out own MethodSecurityExpressionRoot

**Comment by jzheaux** [comment]
This is a duplicate of #12331.

As a side note, please see the documentation in https://docs.spring.io/spring-security/reference/5.8/migration/servlet/authorization.html#_use_a_custom_bean_instead_of_subclassing_defaultmethodsecurityexpressionhandler for usage details.
