### ISSUE TITLE
Samples directory was deleted, cannot upgrade oauth flow 

### ISSUE THREAD

**Issue by samqhr** [spring-projects/spring-security#13189]
This link is 404 d.  thanks for deleting the samples my friends good work https://github.com/spring-projects/spring-security/tree/main/samples/boot/oauth2webclient

**Comment by jgrandja** [comment]
@samqhr The samples have been moved to a new repository https://github.com/spring-projects/spring-security-samples for quite some time now.

See https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/oauth2/webclient
