### ISSUE TITLE
Remove LazyCsrfTokenRepository usage

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#13194]
`CsrfConfigurer` and `CsrfBeanDefinitionParser` use the deprecated `LazyCsrfTokenRepository`; however, this is no longer necessary given that `CsrfFilter` [calls `CsrfTokenRepository#loadDeferredToken`](https://github.com/spring-projects/spring-security/blob/0e3ee8990299436223c3037afb096f454f17ef5e/web/src/main/java/org/springframework/security/web/csrf/LazyCsrfTokenRepository.java#L31).

The `CsrfFilter` JavaDoc should also be updated.

**Comment by kandaguru17** [comment]
Can I pick this one? @jzheaux

**Comment by kandaguru17** [comment]
Created a Draft PR for the same,
waiting for confirmation to work on this one, 
will move it to ready for review upon confirmation  :)
