### ISSUE TITLE
SEC-1069: Localization is done too soon in the request chain

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1320]
["Nicolas Romanetti":https://jira.spring.io/secure/ViewProfile.jspa?name=nicolas](Migrated from ["SEC-1069":https://jira.spring.io/browse/SEC-1069?redirect=false]) said:

SpringSecurity assumes that the Locale present in the LocaleContextHolder is the prefered locale.

This is often not the case as the SpringSecurity filter is in general defined before let's say the spring mvc controller interceptors.
Actually, one of these interceptor, the LocaleChangeInterceptor sets the prefered locale for the current request.

Since this locale change occurs after SpringSecurity, SpringSecurity cannot take it into account when it resolves an error message such 
as an invalid login or password.
As a result, the message displayed to the end use is not in the prefered locale.

Therefore, I think Spring Security should somehow also provide the message key (in the exception thrown ?) and let the view (ie jsp page) 
resolve the message using the prefered locale.

**Comment by spring-issuemaster** [comment]
This issue duplicates #761
