### ISSUE TITLE
authorizeHttpRequests should consider GrantedAuthorityDefaults

### ISSUE THREAD

**Issue by dmngb** [spring-projects/spring-security#13215]
We use a custom prefix for our roles (e.g. we want roles to be something like MYPREFIX_USER instead of ROLE_USER):

```java
    @Bean
    public GrantedAuthorityDefaults grantedAuthorityDefaults() {
        return new GrantedAuthorityDefaults("MYPREFIX_"));
    }
```

If we define our security filter like below (with deprecated `authorizeRequests`), everything works as expected and the custom prefix is taken into account:

```java
    @Bean
    public SecurityFilterChain myFilterChain(HttpSecurity http) throws Exception {
        return http.authorizeRequests(c -> c.anyRequest().hasRole("USER")).formLogin(withDefaults());
    }
```
If we change our code to use the recommended `authorizeHttpRequests`, then the custom prefix is ignored and `ROLE_` is used instead:

```java
    @Bean
    public SecurityFilterChain myFilterChain(HttpSecurity http) throws Exception {
        return http.authorizeHttpRequests(c -> c.anyRequest().hasRole("USER")).formLogin(withDefaults());
    }
```

Our workaround is to use something like : 
```java
    @Bean
    public SecurityFilterChain myFilterChain(HttpSecurity http) throws Exception {
        return http.authorizeHttpRequests(c -> c.anyRequest().hasAuthority("MYPREFIX_USER")).formLogin(withDefaults());
    }
```

Found in Spring Boot 3.1.0 / Spring Security 6.1.0

**Comment by kandaguru17** [comment]
@marcusdacoregio, Can I work on this one?

**Comment by marcusdacoregio** [comment]
Absolutely @kandaguru17, it's yours.
