### ISSUE TITLE
SEC-1071: RoleHierarchyImpl: Add DAO-aware subclass.

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1322]
["Alan B. Canon":https://jira.spring.io/secure/ViewProfile.jspa?name=alancanon](Migrated from ["SEC-1071":https://jira.spring.io/browse/SEC-1071?redirect=false]) said:

In <a href="http://forum.springsource.org/showthread.php?t=65515">DAO-Aware subclass of RoleHierarchyImpl, I supply five classes that add out-of-the-box support for managing RoleHierarchies using data access.

Attached is my reference implementation. I have not extensively tested the feature, but I am sure the code provided is close to working, if not there yet.

**Comment by rwinch** [comment]
Closing as the source is no longer available on this and the code base has changed a lot since then. Please discuss in a ticket before providing a PR on this ticket to ensure that it would be accepted.
