### ISSUE TITLE
Deprecated hint on BasicAuthenticationFilter

### ISSUE THREAD

**Issue by mczul** [spring-projects/spring-security#13231]
Hi Spring Security Team,

first of all: Thanks for your effort and your amazing work!

I recently read through the JavaDoc of `BasicAuthenticationFilter` and was a bit irritated by lines 84 to 86 where `Digest Auth` was described as a better alternative for `Basic Auth` which is certainly a deprecated artifact and conflicts with the [warning stated on the official tutorial](https://docs.spring.io/spring-security/reference/servlet/authentication/passwords/digest.html).   

It's not a big deal for readers with basic security knowledge... but maybe unsophisticated project setups can be prevented if deprecated hints like this are removed.

https://github.com/spring-projects/spring-security/blob/9ec3e80e15c709502633447beeef36f957e2c4e4/web/src/main/java/org/springframework/security/web/authentication/www/BasicAuthenticationFilter.java#L84-L86

**Comment by jzheaux** [comment]
Good catch, @mczul! Can you provide a PR to update the JavaDoc? And would you please base that change on `5.7.x`?
