### ISSUE TITLE
Use SecurityContextHolderStrategy in CasAuthenticationFilter

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-security#13265]
The filter should use the `SecurityContextHolderStrategy` in its `successfullAuthentication` method instead of accessing the holder statically.

**Comment by kandaguru17** [comment]
@marcusdacoregio can i work on this one?

**Comment by marcusdacoregio** [comment]
Yes @kandaguru17, it's yours

**Comment by marcusdacoregio** [comment]
Closing in favor of #13418
