### ISSUE TITLE
Custom Form Login is causing too many redirects and cannot get the login page for Spring Security v6.1.0

### ISSUE THREAD

**Issue by mainul35** [spring-projects/spring-security#13285]
I defined the **SecurityFilterChain** bean like below

```
@Bean
	public SecurityFilterChain securityFilterChain (HttpSecurity http) throws Exception {
		// We are disabling CSRF so that our forms don't complain about a CSRF token.
		// Beware that it can create a security vulnerability
		return http.csrf(AbstractHttpConfigurer::disable)
				// Here we are configuring our login form
//				.formLogin(Customizer.withDefaults())
				.formLogin(formLogin -> {
							formLogin
									.loginPage("/login") // Login page will be accessed through this endpoint. We will create a controller method for this.
									.loginProcessingUrl("/login-processing") // This endpoint will be mapped internally. This URL will be our Login form post action.
									.usernameParameter("username")
									.passwordParameter("password")
									.permitAll() // We re permitting all for login page
									.defaultSuccessUrl("/") // If the login is successful, user will be redirected to this URL.
									.failureUrl("/login?error=true"); // If the user fails to login, application will redirect the user to this endpoint
						}
				)
		.authorizeHttpRequests(authorize ->
						authorize
								// We are permitting all static resources to be accessed publicly
								.requestMatchers("/images/**", "/css/**", "/js/**").permitAll()
								// We are restricting endpoints for individual roles.
								// Only users with allowed roles will be able to access individual endpoints.
								.requestMatchers("/course/add").hasRole("ADMIN")
								.requestMatchers("/course/show-all").hasAnyRole("ADMIN", "USER")
								.requestMatchers("/course/edit").hasAnyRole("USER")
								// Following line denotes that all requests must be authenticated.
								// Hence, once a request comes to our application, we will check if the user is authenticated or not.
								.anyRequest().authenticated()
				)

				.logout(logout ->
						logout
								.logoutUrl("/logout")
								.logoutSuccessUrl("/")
				)
				.build();

	}
```

Unfortunately, this code does not work for custom form login, but works perfectly for form login with default configuration (which is also commented in the code),

**Comment by mainul35** [comment]
As a result, I am getting the following page.
![image](https://github.com/spring-projects/spring-security/assets/9724178/ef74d9f8-b176-4a13-abac-7ce22360b3cd)

**Comment by marcusdacoregio** [comment]
Hi @mainul35,

can you provide more details about the configuration, like the related code for the custom login page, the `/login-processing` endpoint etc?

**Comment by mainul35** [comment]
Hello @marcusdacoregio , this project was in Spring 5.2.11 before. I am migrating to Spring 6.x for my updating my articles. It was working perfectly. Moreover, just after the release of Spring 6.0, I migrated one of my projects to Spring 5 from Spring 5, and it perfectly works. Here is that project security configuration file link that is currently in Spring 6.0 migrated from 5.x

https://github.com/mainul35/University-QA-Board/blob/master/src/main/java/com/springprojects/config/security/SecurityConfig.java

- I will enable TRACE log and let you know the logs ASAP.
- I just tried the suggeded configuration that you just commented above. It didn't work.

**Comment by mainul35** [comment]
Hello @marcusdacoregio , after enabling the TRACE log for Spring Security, I found the following line in the log.
![image](https://github.com/spring-projects/spring-security/assets/9724178/44e48f58-5279-4b9c-a005-cb1a9dd2c545)

So I set the authorization of my view page location, **"/WEB-INF/views/**"** in my case to permitAll()

```

authorize
								// We are permitting all static resources to be accessed publicly
								.requestMatchers("/images/**", "/css/**", "/js/**", **_"/WEB-INF/views/**"_**).permitAll()
								// We are restricting endpoints for individual roles.
								// Only users with allowed roles will be able to access individual endpoints.
								.requestMatchers("/course/add").hasRole("ADMIN")
								.requestMatchers("/course/show-all").hasAnyRole("ADMIN", "USER")
								.requestMatchers("/course/edit").hasAnyRole("USER")
								// Following line denotes that all requests must be authenticated.
								// Hence, once a request comes to our application, we will check if the user is authenticated or not.
								.anyRequest().authenticated()

```

And it worked like a charm!

Thank you for your kind support :)

**Comment by christ774** [comment]
Good afternoon, I've been trying to solve this error for a long time and I haven't been able to. following your pos it is no longer possible to redirect to a custom login in the latest version of spring

My view is made in html, css and javascript and I also have some images, can you please tell me how I can do it?
I also want to ask you if it is more convenient to make a controller, the front connects to it and from there login, it is instead of redirecting the spring security login.

I thank you very much


  }
  /*@Override
    public void addViewControllers(ViewControllerRegistry viewControllerRegistry){
        viewControllerRegistry.addViewController("/login").setViewName("login.html");

    }*/
    @Bean
    public SecurityFilterChain securityFilterChain(HttpSecurity httpSecurity) throws Exception {
      httpSecurity.csrf(AbstractHttpConfigurer::disable)// lo desactive por que no me deja trabajar en postman
                .authorizeRequests(authorize ->  authorize
               .requestMatchers("/admin", "/admin/save", "/contenido/save").permitAll()
                        .requestMatchers("src/main/resources/templates").permitAll()
                .anyRequest().authenticated()
              )
              .formLogin(formLogin-> formLogin
                                      .loginPage("/login")
                                      .permitAll()
              );

@Controller
public class ControllerLogin {

    @RequestMapping(value="/login", method= RequestMethod.GET)
    public String login() {
        return "redirect:/login.html";
    }
This page isn’t workinglocalhost redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

}

**Comment by mainul35** [comment]
First of all, set `/WEB-INF/views/**` to permit all, like the code below in your spring security http configuration 
`requestMatchers("/images/**", "/css/**", "/js/**", "/WEB-INF/views/**").permitAll()`

Next, in your controller method, return should be only your view name. Replace `return "redirect:/login.html";` to `return "login";`

If your view page is in the correct location, it should work.

**Comment by abhisable** [comment]
It's not working when we are using below code , which is required in latest version. Any suggestions what could be resolution?
@Bean
	public SecurityFilterChain settingUpSecurityFilterChain() throws Exception {
		

		httpSecurity.authorizeHttpRequests(customizer->{
			customizer.requestMatchers(mvc.pattern("/hello"),mvc.pattern("/helloworld"))
			.authenticated();
			
			customizer.requestMatchers(mvc.pattern("/bye")).permitAll();
			customizer.requestMatchers(mvc.pattern("/WEB-INF/views/**")).permitAll();
		});
		
		httpSecurity.formLogin(formLoginCustomizer->{
			formLoginCustomizer.loginPage("/myCustomLogin");
		});
//		httpSecurity.formLogin(Customizer.withDefaults());
		httpSecurity.httpBasic(Customizer.withDefaults());
		
		return httpSecurity.build();
	}

**Comment by sudheerUzumaki** [comment]
First, let's examine why localhost is redirecting too many times. Here, when an unauthorized request is made, Spring Security redirects it to the login page URL. Since the login page URL is also restricted, it will again redirect back to the login page URL, creating a loop. This results in the error: localhost has redirected too many times.


Solution: Configure HttpSecurity for form login as follows: httpSecurity.formLogin(f -> f.loginPage("/loginpage").permitAll());
If the login page URL is not the URL for the page and it redirects you to the page, allow "/page.html" without authentication in the request matchers.

HttpSecurity.authorizeHttpRequests(customizer ->
		customizer.requestMatchers("/page.html").permitAll());

**Comment by SuleymanCommits** [comment]
> The configuration `httpSecurity.formLogin(formLoginCustomizer -> formLoginCustomizer.loginPage("/myCustomLogin"));` instructs Spring Security to redirect unauthorized requests to `/myCustomLogin`.
> 
> To understand why localhost is redirecting excessively, consider this: when an unauthorized request occurs, Spring Security redirects to the login page URL. If this URL requires authentication, it creates a redirect loop back to itself, resulting in the 'localhost redirected too many times' error.
> 
> Solution: The solution is to set up HttpSecurity for form login like so: `httpSecurity.formLogin(f -> f.loginPage("/loginpage").permitAll());`.
> 
> If the login page URL is not the URL for the actual page causing the redirection, you should allow "/page.html" without authentication in the request matchers.
> 
> HttpSecurity.authorizeHttpRequests(customizer -> customizer.requestMatchers("/page.html").permitAll());

I've configured form login like that but still experiencing a redirect loop. 
`                        .requestMatchers(new AntPathRequestMatcher("/user", "POST")).permitAll() // Allow POST requests to /user without authentication
`

**Comment by SuleymanCommits** [comment]
> > > The configuration `httpSecurity.formLogin(formLoginCustomizer -> formLoginCustomizer.loginPage("/myCustomLogin"));` instructs Spring Security to redirect unauthorized requests to `/myCustomLogin`.
> > > To understand why localhost is redirecting excessively, consider this: when an unauthorized request occurs, Spring Security redirects to the login page URL. If this URL requires authentication, it creates a redirect loop back to itself, resulting in the 'localhost redirected too many times' error.
> > > Solution: The solution is to set up HttpSecurity for form login like so: `httpSecurity.formLogin(f -> f.loginPage("/loginpage").permitAll());`.
> > > If the login page URL is not the URL for the actual page causing the redirection, you should allow "/page.html" without authentication in the request matchers.
> > > HttpSecurity.authorizeHttpRequests(customizer -> customizer.requestMatchers("/page.html").permitAll());
> > 
> > I've configured form login like that but still experiencing a redirect loop. `.formLogin(form -> form.loginPage("/login").permitAll()) `
> 
> login is not the page,it returns the page,instead it should be login.jsp or login.html  or you can allow it :
> http..authorizeHttpRequests((authorize) -> authorize
> 									.requestMatchers("/login.extension")
> 									.permitAll().anyRequest().authenticated())

doesn't matter, /login is a controller that returns "login" or login.html

**Comment by sudheerUzumaki** [comment]
> > > > The configuration `httpSecurity.formLogin(formLoginCustomizer -> formLoginCustomizer.loginPage("/myCustomLogin"));` instructs Spring Security to redirect unauthorized requests to `/myCustomLogin`.
> > > > To understand why localhost is redirecting excessively, consider this: when an unauthorized request occurs, Spring Security redirects to the login page URL. If this URL requires authentication, it creates a redirect loop back to itself, resulting in the 'localhost redirected too many times' error.
> > > > Solution: The solution is to set up HttpSecurity for form login like so: `httpSecurity.formLogin(f -> f.loginPage("/loginpage").permitAll());`.
> > > > If the login page URL is not the URL for the actual page causing the redirection, you should allow "/page.html" without authentication in the request matchers.
> > > > HttpSecurity.authorizeHttpRequests(customizer -> customizer.requestMatchers("/page.html").permitAll());
> > > 
> > > 
> > > I've configured form login like that but still experiencing a redirect loop. `.formLogin(form -> form.loginPage("/login").permitAll()) `
> > 
> > 
> > login is not the page,it returns the page,instead it should be login.jsp or login.html  or you can allow it :
> > http..authorizeHttpRequests((authorize) -> authorize
> > .requestMatchers("/login.extension")
> > .permitAll().anyRequest().authenticated())
> 
> doesn't matter, /login is a controller that returns "login" or login.html


yes,you are allowing login end point without authentication,but not login.html ,you can also allow it without authentication by :
http..authorizeHttpRequests((authorize) -> authorize
.requestMatchers("/login.html")
.permitAll().anyRequest().authenticated())

**Comment by SuleymanCommits** [comment]
> > > > > The configuration `httpSecurity.formLogin(formLoginCustomizer -> formLoginCustomizer.loginPage("/myCustomLogin"));` instructs Spring Security to redirect unauthorized requests to `/myCustomLogin`.
> > > > > To understand why localhost is redirecting excessively, consider this: when an unauthorized request occurs, Spring Security redirects to the login page URL. If this URL requires authentication, it creates a redirect loop back to itself, resulting in the 'localhost redirected too many times' error.
> > > > > Solution: The solution is to set up HttpSecurity for form login like so: `httpSecurity.formLogin(f -> f.loginPage("/loginpage").permitAll());`.
> > > > > If the login page URL is not the URL for the actual page causing the redirection, you should allow "/page.html" without authentication in the request matchers.
> > > > > HttpSecurity.authorizeHttpRequests(customizer -> customizer.requestMatchers("/page.html").permitAll());
> > > > 
> > > > 
> > > > I've configured form login like that but still experiencing a redirect loop. `.formLogin(form -> form.loginPage("/login").permitAll()) `
> > > 
> > > 
> > > login is not the page,it returns the page,instead it should be login.jsp or login.html  or you can allow it :
> > > http..authorizeHttpRequests((authorize) -> authorize
> > > .requestMatchers("/login.extension")
> > > .permitAll().anyRequest().authenticated())
> > 
> > 
> > doesn't matter, /login is a controller that returns "login" or login.html
> 
> yes,you are allowing login end point without authentication,but not login.html ,you can also allow it without authentication by : http..authorizeHttpRequests((authorize) -> authorize .requestMatchers("/login.html") .permitAll().anyRequest().authenticated())


`Securing GET /login
2024-08-12T13:11:23.906+04:00 DEBUG 127703 --- [nio-8080-exec-1] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2024-08-12T13:11:23.915+04:00 DEBUG 127703 --- [nio-8080-exec-1] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorized filter invocation [GET /login] with attributes [permitAll]
2024-08-12T13:11:23.916+04:00 DEBUG 127703 --- [nio-8080-exec-1] o.s.security.web.FilterChainProxy        : Secured GET /login
2024-08-12T13:11:23.949+04:00 DEBUG 127703 --- [nio-8080-exec-1] o.s.security.web.FilterChainProxy        : Securing GET /error
2024-08-12T13:11:23.950+04:00  WARN 127703 --- [nio-8080-exec-1] o.s.w.s.h.HandlerMappingIntrospector     : Cache miss for ERROR dispatch to '/error' (previous null). Performing MatchableHandlerMapping lookup. This is logged once only at WARN level, and every time at TRACE.
2024-08-12T13:11:23.958+04:00 DEBUG 127703 --- [nio-8080-exec-1] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2024-08-12T13:11:23.959+04:00 DEBUG 127703 --- [nio-8080-exec-1] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorized filter invocation [GET /error] with attributes [permitAll]
2024-08-12T13:11:23.959+04:00 DEBUG 127703 --- [nio-8080-exec-1] o.s.security.web.FilterChainProxy        : Secured GET /error`

I don't know why it's redirecting to /error, I've permitted both /login and /login.html and also did
`                .formLogin(form -> form.loginPage("/login").permitAll())
`

**Comment by wizzy-abhishek** [comment]
@Bean
    public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
        http
                .csrf(AbstractHttpConfigurer::disable) // Disable CSRF for simplicity, enable in production with proper configuration
                .authorizeHttpRequests(authorize -> authorize
                        .requestMatchers(HttpMethod.GET, "/api/resource").permitAll() // Allow GET requests to /api/resource
                        .requestMatchers(HttpMethod.POST, "/api/resource").hasRole("ADMIN") // Allow POST requests to /api/resource for users with USER role
                        .requestMatchers(HttpMethod.PUT, "/api/resource").hasRole("ADMIN") // Allow PUT requests to /api/resource for users with ADMIN role
                        .requestMatchers(HttpMethod.DELETE, "/api/resource").hasRole("ADMIN") // Allow TO DELETE requests to /api/resource for users with ADMIN role
                        .anyRequest().authenticated()) // All other requests need to be authenticated
                .formLogin(form ->
                        form
                                .loginPage("/login")
                                .permitAll()
                        )
                .httpBasic(Customizer.withDefaults());

        return http.build();
    }
    
    
    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hospital Login Page</title>
    <link rel="stylesheet" href="login.css">
    <link
    href="https://cdn.jsdelivr.net/npm/remixicon@4.3.0/fonts/remixicon.css"
    rel="stylesheet"
/>
</head>
<body>

    <div class="main-container">
        <div class="custom-shape-divider-top-1724907512">
            <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
                <path d="M0,0V46.29c47.79,22.2,103.59,32.17,158,28,70.36-5.37,136.33-33.31,206.8-37.5C438.64,32.43,512.34,53.67,583,72.05c69.27,18,138.3,24.88,209.4,13.08,36.15-6,69.85-17.84,104.45-29.34C989.49,25,1113-14.29,1200,52.47V0Z" opacity=".25" class="shape-fill"></path>
                <path d="M0,0V15.81C13,36.92,27.64,56.86,47.69,72.05,99.41,111.27,165,111,224.58,91.58c31.15-10.15,60.09-26.07,89.67-39.8,40.92-19,84.73-46,130.83-49.67,36.26-2.85,70.9,9.42,98.6,31.56,31.77,25.39,62.32,62,103.63,73,40.44,10.79,81.35-6.69,119.13-24.28s75.16-39,116.92-43.05c59.73-5.85,113.28,22.88,168.9,38.84,30.2,8.66,59,6.17,87.09-7.5,22.43-10.89,48-26.93,60.65-49.24V0Z" opacity=".5" class="shape-fill"></path>
                <path d="M0,0V5.63C149.93,59,314.09,71.32,475.83,42.57c43-7.64,84.23-20.12,127.61-26.46,59-8.63,112.48,12.24,165.56,35.4C827.93,77.22,886,95.24,951.2,90c86.53-7,172.46-45.71,248.8-84.81V0Z" class="shape-fill"></path>
            </svg>
        </div>
        
        <div class="left-section">
            <h1>Hospital Name</h1>
            <h3>Your expertise , enhanced by our technology</h3>
            <img src="doctors2.jpg" alt="">
        </div>

        
        <div class="right-section">
            <form action="authenticate"  method="post" class="authenticate">
                <h2>Welcome Back</h2>
                <div class="input-group">
                    <span class="icon"><i class="ri-user-line"></i></span> 
                    <input type="text" id="username" name="username" placeholder="Username" required>
                </div>
                <div class="input-group">
                    <span class="icon"><i class="ri-lock-line"></i></span> 
                    <input type="password" id="password" name="password" placeholder="Password" required>
                </div>
                <div class="form-options">
                    <label class="checkbox">
                        <input type="checkbox"> Remember Me
                    </label>
                    <a href="#" class="forgot-password">Forgot Password?</a>
                </div>
                <button type="submit" class="submit-btn">Login</button>
                <p class="register-link">Don't have an account? <a href="#">Register</a></p>
            </form>
        </div>
    </div>
</body>
</html>
Its a .jsp page

![image](https://github.com/user-attachments/assets/f3e312c2-6c6f-4974-b70a-d7582edc46a5)
spring.mvc.view.suffix=.jsp
spring.mvc.view.prefix=/views/

I am stuck kindly help

**Comment by sudheerUzumaki** [comment]
you should allow "/views/login.jsp" without authentication in the request matchers.

**Comment by koisurunippon** [comment]
Thanks so much, I had the same problem and your solution above saved me.

**Comment by ranjit485** [comment]
.requestMatchers("/static/**", "/css/**", "/js/**", "/images/**","/WEB-INF/views/**").permitAll() This worked for me

**Comment by CRj0001** [comment]
Hey Everyone!! I am stuck with TOO MANY REDIRECTS..
Kindly help me with the code

SpringSecurity:

	@Bean
	public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
		http
		.csrf().disable()
		.authorizeRequests().requestMatchers("/logins", "/register", "/webapp/views/**", "/css/**", "/js/**", "/images/**").permitAll()
		.anyRequest().authenticated()
		.and()
		.formLogin()
		.loginPage("/logins")
		.permitAll()
		.defaultSuccessUrl("/", true)
		.and()
		.logout().invalidateHttpSession(true)
		.clearAuthentication(true)
		.logoutRequestMatcher(new AntPathRequestMatcher("/logout"))
		.logoutSuccessUrl("/logout-success").permitAll();
		
		return http.build();
	    
	}

Controller:

	@RequestMapping("/")
	public String callHome()
	{
		System.out.println("Calling Homepage...");
		return "Index";
	}
	
	@RequestMapping("/logins")
	public String loginPage()
	{
		return "demologin";
	}
	
	@RequestMapping("/logout-success")
	public String logoutPage()
	{
		return "logout";
	}

demologin.jsp

<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8" isELIgnored="false"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>Login</h1>
	
	${SPRING_SECURITY_LAST_EXCEPTION.message}
	<form action="login" method="POST">
		<table>
			<tr>
				<td>User: </td>
				<td> <input type = "text" name = "username" value = ''> </td>
			</tr>
			
			<tr> 
				<td>Password: </td>
				<td> <input type = "password" name = "password"> </td>
			</tr>
			
			<tr>
				<td> <input name = "submit" type = "submit" value = "submit" /> </td>
			</tr>
		</table>
	</form>
</body>
</html>


Jsp path:

/springmvcbootdemo/src/main/webapp/views/demologin.jsp

**Comment by karenworld** [comment]
i am having problem directing spring boot 3  to index.html on start up and here's the trace. Any help would be appreciated!

[2m2025-09-11T15:56:15.724+08:00[0;39m [32mDEBUG[0;39m [35m22056[0;39m [2m---[0;39m [2m[nio-8082-exec-1][0;39m [2m[0;39m[36mo.s.s.web.DefaultRedirectStrategy       [0;39m [2m:[0;39m Redirecting to http://localhost:8082/login

It will keep directing me to thymleaf login no matter what

I have tried various ways like : .httpBasic(httpBasic -> httpBasic.disable()).

By removing templates under src\main\resources\META-INF\resources but it will produce more error so I got to keep it.

removed enabledWebSecurity as I read that this will not led to the thymleaf login

Here's my security config  


	@Bean
	public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
	
		http
        .csrf(csrf -> csrf.disable())
        .sessionManagement(session -> session.sessionCreationPolicy(SessionCreationPolicy.STATELESS))
        .authorizeHttpRequests(auth -> auth // Allow frontend static files (HTML, JS, CSS) 
				.requestMatchers("/", "/index.html", "/static/**", "/assets/**", "/oauth2/**", "/favicon.ico","/actuator/**", "/api/**").permitAll().anyRequest().anonymous())
			.oauth2Login(oauth2 -> oauth2.loginPage("/index.html")
					.failureHandler(failureHandler)
	            .successHandler(successHandler)	        ) 
	      
	        .httpBasic(httpBasic -> httpBasic.disable())
	        .exceptionHandling(exceptionHandling -> exceptionHandling
	                .defaultAuthenticationEntryPointFor(
	                    new HttpStatusEntryPoint(HttpStatus.UNAUTHORIZED),
	                    AnyRequestMatcher.INSTANCE
	                )
	            ).logout(logout -> logout.logoutSuccessUrl("/index.html").permitAll())		       
	        
	        .addFilterBefore(new JwtAuthFilter(jwtService), UsernamePasswordAuthenticationFilter.class);

	    return http.build();
	}
