### ISSUE TITLE
Add Support for Passkeys

### ISSUE THREAD

**Issue by asaikali** [spring-projects/spring-security#13305]
Passkeys have emerged as the industry standard consumer facing solution to get rid of passwords see [passkeys.dev](https://passkeys.dev) with first class support from Google, Apple, and Microsoft. Passkey looks like it will become quite common in the consumer space. Spring security should make it easy to implement Passkey support in application.

Ongoing work can be followed at https://github.com/rwinch/spring-security-webauthn/tree/passkeys

Related gh-5238 (Passkeys is a subset of WebAuthn)

**Comment by osiegmar** [comment]
This issue duplicates #5238
