### ISSUE TITLE
CsrfToken Description

### ISSUE THREAD

**Issue by MathBergamo** [spring-projects/spring-security#13367]
Hello,

I noticed that in the documentation for the org.springframework.security.web.server.csrf package, there is no description for CsrfToken. I hope this can be helpful in some way.

![imagem_2023-06-16_181721579](https://github.com/spring-projects/spring-security/assets/108043388/734caaac-c4b2-4db0-9067-8a675a79b3de)

**Comment by marcusdacoregio** [comment]
Hi, @MathBergamo.

What version is that API doc? At least in all supported versions, it is already fixed https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/web/csrf/package-summary.html (change `current` to the version you want to check). With that said, I'll close this as solved.
