### ISSUE TITLE
AOT Fails to proxy

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#13368]
The spring-aot-proxy-tests [fail](https://ge.spring.io/s/2rti3dpf2yzik/tests/:security:security-method:appTest/com.example.security.method.SecuredAotTests/anonymousCanCallOnlyAnonymousMethod(AssertableOutput)?top-execution=1) when trying to proxy methods. The problem seems to be related to this change https://github.com/spring-projects/spring-security/commit/31f1604f665fb786eb71fd404244280139ca6d1f

cc @wilkinsona

**Comment by marcusdacoregio** [comment]
Closed via https://github.com/spring-projects/spring-security/commit/2686af0c4dea7c7423915da3dc592b3076b2a60a
