### ISSUE TITLE
Unable to Find 'filterProcessingUrl' Method in Spring Security 6.1.1 Saml2LoginConfigurer Configuration

### ISSUE THREAD

**Issue by sumeetpri** [spring-projects/spring-security#13417]
I am using version 6.1.1 of Spring Security and I need to configure a single response processing endpoint for a federated IDP. I have referred to the [Spring documentation](https://docs.spring.io/spring-security/reference/servlet/saml2/login/authentication.html) which provides an example code snippet. However, I couldn't find the `filterProcessingUrl` method in the `Saml2LoginConfigurer` class. As a result, I'm getting a compile error stating that `filterProcessingUrl` is not found.

Here is the example code mentioned the Spring documentation under SAML2 Authentication Responses section:

```java
@Bean
SecurityFilterChain securityFilters(HttpSecurity http) throws Exception {
    http
        // ...
        .saml2Login((saml2) -> saml2.filterProcessingUrl("/saml2/login/sso"))
        // ...

    return http.build();
}
```

And here is my code for the SAML 2.0 configuration:

```java
SecurityFilterChain configure(HttpSecurity http) throws Exception {
    OpenSaml4AuthenticationProvider authenticationProvider = new OpenSaml4AuthenticationProvider();
    http.authorizeHttpRequests(requests -> requests
            .requestMatchers("/saml2/service-provider-metadata/**")
            .permitAll()
        ).addFilterAfter(authTokenSessionRestore, SecurityContextHolderFilter.class)
        .saml2Login((saml2) -> saml2
            .authenticationManager(new ProviderManager(authenticationProvider))
            .relyingPartyRegistrationRepository(relyingPartyRegistrationRepository)
            .successHandler(loginSuccessHandler)
            .failureHandler(loginFailureHandler)

        ).saml2Logout(withDefaults());

    return http.build();
}
```

I'm wondering why I'm unable to find the `saml2.filterProcessingUrl` method in my code.

We have multiple federated idp and want single assertion url for all idp like /saml2/SSO . How do we can achieve single Assertion url for all idp not dynamic by registration Id ?

**Comment by sumeetpri** [comment]
@marcusdacoregio Looking for your expert input !

**Comment by marcusdacoregio** [comment]
Thanks for the report @sumeetpri, the property should be `loginProcessingUrl` instead of `filterProcessingUrl`. This is now fixed.

**Comment by ssharma1011** [comment]
hi @sumeetpri  - were you able to find a solution for this in your original question:
"We have multiple federated idp and want single assertion url for all idp like /saml2/SSO . How do we can achieve single Assertion url for all idp not dynamic by registration Id ?"

My use case - idp1 sends an assertion - i find out from that assertion that it is coming from a particular idp and process the sso. Happy to open another issue if it is against guidelines.

**Comment by jzheaux** [comment]
@ssharma1011, at this point, you should be able to set the value to `/saml2/SSO`, which you can read about here: https://docs.spring.io/spring-security/reference/servlet/saml2/login/authentication.html#saml2-response-processing-endpoint

**Comment by jzheaux** [comment]
I see, @ssharma1011, let's do this instead. So that this ticket stays focused to the discussion about filterProcessingUrl, will you please post your question to [StackOverflow](https://www.stackoverflow.com)? You can paste a link to your question here, and I'd be happy to follow up with you there.
