### ISSUE TITLE
SEC-1091: link to source repository incorrect

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1342]
["Brian Ewins":https://jira.spring.io/secure/ViewProfile.jspa?name=bazzargh](Migrated from ["SEC-1091":https://jira.spring.io/browse/SEC-1091?redirect=false]) said:

The link on http://static.springframework.org/spring-security/site/source-repository.html is to the old acegi repo, should point to https://src.springframework.org/svn/spring-security/

The source of the error is in pom.xml:
<url>http://acegisecurity.svn.sourceforge.net/viewcvs.cgi/acegisecurity/spring-security/trunk</url>

**Comment by spring-issuemaster** [comment]
This issue duplicates #1331
