### ISSUE TITLE
ClientAuthenticationMethod not support Oauth2.0 tls_client_auth and self_signed_tls_client_auth method

### ISSUE THREAD

**Issue by mujianfenghe** [spring-projects/spring-security#13439]
**Expected Behavior**

in the spring-security-oauth2-core project, the class of ClientAuthenticationMethod  support Oauth2.0 tls_client_auth and self_signed_tls_client_auth method

**Current Behavior**

in the spring-security-oauth2-core project, the class of ClientAuthenticationMethod not support Oauth2.0 tls_client_auth and self_signed_tls_client_auth method,so the spring-security-oauth2-authorization-server project can not use tls_client_auth and self_signed_tls_client_auth method,
**Context**

Will it be supported in the future? Is there another way to implement it?

**Comment by jgrandja** [comment]
Closing as duplicate of gh-4498
