### ISSUE TITLE
A qustion for WebSecurityConfigurerAdapter deprecated

### ISSUE THREAD

**Issue by goldthree-shit** [spring-projects/spring-security#13445]
In new Spring Security, what should I do to replace these code follw:
`@Override
    protected void configure(AuthenticationManagerBuilder auth) throws Exception {
       auth.userDetailsService(userService).passwordEncoder(passwordEncoder).and().eraseCredentials(false);
}
`

**Comment by marcusdacoregio** [comment]
Hi @goldthree-shit, please refer to [this post](https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter) and [this guide](https://docs.spring.io/spring-security/reference/5.8/migration/servlet/config.html#_stop_using_websecurityconfigureradapter). If you have further questions, you can browse on StackOverflow or in this issue tracker.
