### ISSUE TITLE
No permission to download dependencies from repo.spring.io when building documentation

### ISSUE THREAD

**Issue by KevinBlandy** [spring-projects/spring-security#13451]
I tried to build the documentation via `./gradlew :spring-security-docs:antora`, but the following exception occurred.

```txt
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'spring-security'.
> Could not resolve all files for configuration ':classpath'.
   > Could not download spring-javaformat-formatter-shaded-0.0.35.jar (io.spring.javaformat:spring-javaformat-formatter-shaded:0.0.35)
      > Could not get resource 'https://repo.spring.io/plugins-snapshot/io/spring/javaformat/spring-javaformat-formatter-shaded/0.0.35/spring-javaformat-formatter-shaded-0.0.35.jar'.
         > Could not GET 'https://repo.spring.io/plugins-snapshot/io/spring/javaformat/spring-javaformat-formatter-shaded/0.0.35/spring-javaformat-formatter-shaded-0.0.35.jar'. Received status code 401 from server:

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

```

It looks as if the visitor does not have permission to download the dependency from repo.spring.io.

Any suggestions? Thanks!

**Comment by marcusdacoregio** [comment]
Hi @KevinBlandy, those repositories now need authentication as per https://spring.io/blog/2022/12/14/notice-of-permissions-changes-to-repo-spring-io-january-2023.

I have removed them [here](https://github.com/spring-projects/spring-security/commit/afec90c8e8805c2e66e613be733bddf108a9a581), can you try it again?

**Comment by Clarkzv** [comment]
Hey, I'm dealing with the same problem. Any tips on how to fix it? I'm a beginner to java.
