### ISSUE TITLE
public addSessionAuthenticationStrategy in SessionManagementConfigurer

### ISSUE THREAD

**Issue by leshalv** [spring-projects/spring-security#13455]
Integrated user-defined session policies without changing original configurations

**Comment by jzheaux** [comment]
Thanks for the report, @leshalv. To make sure this is the right addition to the DSL, can you please describe in more detail what it is that you are trying to do?

In the meantime, note that you can add a user-defined session policy already by post-processing the `CompositeSessionAuthenticationStrategy` like so:

```java
http
    .sessionManagement((session) -> session
        .withObjectPostProcessor(new ObjectPostProcessor<CompositeSessionAuthenticationStrategy>() {
            @Override
            public <O extends CompositeSessionAuthenticationStrategy> O postProcess(O strategy) {
                return new CompositeSessionAuthenticationStrategy(new MyStrategy(), strategy);
            }
        })
    )
```

**Comment by leshalv** [comment]
> ```java
> CompositeSessionAuthenticationStrategy
> ```

If it is processed through postProcess, the original auto-configured policy will take effect, and I want to extend the custom policy on top of the auto-configuration.

**Comment by leshalv** [comment]
> Thanks for the report, @leshalv. To make sure this is the right addition to the DSL, can you please describe in more detail what it is that you are trying to do?
> 
> In the meantime, note that you can add a user-defined session policy already by post-processing the `CompositeSessionAuthenticationStrategy` like so:
> 
> ```java
> http
>     .sessionManagement((session) -> session
>         .withObjectPostProcessor(new ObjectPostProcessor<CompositeSessionAuthenticationStrategy>() {
>             @Override
>             public <O extends CompositeSessionAuthenticationStrategy> O postProcess(O strategy) {
>                 return new CompositeSessionAuthenticationStrategy(new MyStrategy(), strategy);
>             }
>         })
>     )
> ```

Thanks for this solving my problem
