### ISSUE TITLE
Cannot invoke "io.micrometer.observation.Observation$Scope.getPreviousObservationScope()" because "scope"

### ISSUE THREAD

**Issue by chechoochoo** [spring-projects/spring-security#13450]
As mentioned in https://github.com/reactor/reactor-core/issues/3522 - reopening an issue in spring-security project.

Kindly refer to https://github.com/reactor/reactor-core/issues/3522#issuecomment-1617707475 for sample project to reproduce this issue.

**Comment by jzheaux** [comment]
This is a duplicate of https://github.com/spring-projects/spring-security/issues/13415
