### ISSUE TITLE
The Doc Sidebar has something wrong in `servlet application`

### ISSUE THREAD

**Issue by awxiaoxian2020** [spring-projects/spring-security#13503]
https://docs.spring.io/spring-security/reference/servlet/index.html

![sidebar-issue](https://github.com/spring-projects/spring-security/assets/69554233/0035405b-fa15-4f7d-8dcf-7636327f7f52)

**Comment by ilkou** [comment]
it's bugged in all pages

![image](https://github.com/spring-projects/spring-security/assets/48165230/2cf1dc7f-09f3-4634-9852-960741013b39)

**Comment by marcusdacoregio** [comment]
Thanks @awxiaoxian2020, I'm closing this in favor of https://github.com/spring-io/antora-ui-spring/issues/110
