### ISSUE TITLE
How to return `AuthenticationManagerBuilder` without `and()` method

### ISSUE THREAD

**Issue by awxiaoxian2020** [spring-projects/spring-security#13549]
```java
@Bean
    public AuthenticationManager authenticationManager(HttpSecurity security) throws Exception {
        return security
                .getSharedObject(AuthenticationManagerBuilder.class)
                .userDetailsService(authorizeService)
                .and()
                .build();
    }
```
Is there a Lambda DSL alternative?

**Comment by marcusdacoregio** [comment]
Hi @awxiaoxian2020, we do not really recommend publishing an `AuthenticationManager` using the `AuthenticationManagerBuilder` as it can [lead to some unexpected behaviors](https://github.com/spring-projects/spring-security/issues/12343). Instead, prefer creating the `AuthenticationManager` by yourself, as mentioned [here](https://github.com/spring-projects/spring-security/issues/11926).
