### ISSUE TITLE
SEC-1107: Support java.lang.Number as identifier or throw an appropriate Exception when identifier is no java.lang.Long

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1357]
["Martin Pietsch":https://jira.spring.io/secure/ViewProfile.jspa?name=peach](Migrated from ["SEC-1107":https://jira.spring.io/browse/SEC-1107?redirect=false]) said:

There are some places which expect objectIdentity.getIdentifier() to return a java.lang.Long.

I my case the objects I wanted to secure had an Id of type Integer. Since Integers do have a longValue() I expected no problems. But the MutableAclServiceImpl was not able to deal with it.

In JdbcMutableAclService. createAcl(ObjectIdentity objectIdentity) the call readAclById(objectIdentity) fails with a NotFoundException although createObjectIdentity() should have ensured the existence.

public MutableAcl createAcl(ObjectIdentity objectIdentity)
        throws AlreadyExistsException {

```
    // [...]
    // Create the acl_object_identity row
    createObjectIdentity(objectIdentity, sid);

    // Retrieve the ACL via superclass (ensures cache registration, proper retrieval etc)
    Acl acl = readAclById(objectIdentity);
    // [...]
```

}

Example for the explicit expectation of Long can be found in 

protected void createEntries(final MutableAcl acl) in JdbcMutableAclService.java:

line 136:
stmt.setLong(1, ((Long) acl.getId()).longValue());

**Comment by spring-issuemaster** [comment]
This issue depends on #1224
