### ISSUE TITLE
Incorrect link in the documentation

### ISSUE THREAD

**Issue by limvik** [spring-projects/spring-security#13577]
**Expected Behavior**

The link associated with `Spring Security’s Filters instances` in the [AuthenticationManager](https://docs.spring.io/spring-security/reference/servlet/authentication/architecture.html#servlet-authentication-authenticationmanager) section of the documentation should be changed to the following link:
https://docs.spring.io/spring-security/reference/servlet/architecture.html#servlet-security-filters

![AuthenticationManager](https://github.com/spring-projects/spring-security/assets/37972432/6b6f6e4e-1897-4f22-9a0a-1305839c96f8)

**Current Behavior**

The `Spring Security’s Filters instances` link in the AuthenticationManager section is currently directed to https://docs.spring.io/spring-security/reference/servlet/authentication/architecture.html#servlet-security-filters.

So it doesn't move to any new location.

**Context**

This will help reduce confusion for individuals studying Spring Security.

**Comment by sjohnr** [comment]
Thanks @limvik! Would you like to submit a PR for this?

**Comment by limvik** [comment]
> Thanks @limvik! Would you like to submit a PR for this?

@sjohnr Sure, I will submit a PR for this.
