### ISSUE TITLE
[Spring Security 6.1] different logic for processing assertions in OpenSaml4AuthenticationProvider.process()

### ISSUE THREAD

**Issue by fr2lancer** [spring-projects/spring-security#13586]
**Describe the bug**
* In version 5.x

OpenSaml4AuthenticationProvider.process
1. this.responseValidator.convert(responseToken));
1. then check assertion

* In version 6.1

OpenSaml4AuthenticationProvider.process

1. check if getEncryptedAssertions exists
1. this.responseValidator.convert(responseToken));
1. then check assertion

because of the checking getEncryptedAssertions earlier, this workaround is meaningless. (https://github.com/spring-projects/spring-security/issues/10162)
```
OpenSaml4AuthenticationProvider authenticationProvider = new OpenSaml4AuthenticationProvider();
Converter<ResponseToken, ResponseToken> decrypt = (responseToken) -> {
	DecryptionParameters parameters = new DecryptionParameters();
	// ... set parameters as needed
	Decrypter decrypter = new Decrypter(parameters);
	Response response = responseToken.getResponse();
  	EncryptedAssertion encrypted = response.getEncryptedAssertions().get(0);
  	try {
  		Assertion assertion = decrypter.decrypt(encrypted);
  		response.getAssertions().add(assertion);
  	} catch (Exception e) {
  	  	throw new Saml2AuthenticationException(...);
  	}
	return response;
};
authenticationProvider.setResponseValidator(decrypt.andThen(createDefaultResponseValidator()));
```

**Expected behavior**
responseValidator should be executed earlier than checking getEncryptedAssertions exists
or alternative solution

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by fr2lancer** [comment]
Hi Any updates on this? Thank you

**Comment by santoshdahal12** [comment]
I am having same problem. Though the recommended approach seems to be working, but this approach also introduces another problem of parsing xml two times which is expensive operation. Any suggestion or guidance. I have to do this for an app that needs to validate SAML token for many SPs .
