### ISSUE TITLE
SEC-1112: Fix split packages found in security bundles

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1359]
["Ivica Loncar":https://jira.spring.io/secure/ViewProfile.jspa?name=iloncar](Migrated from ["SEC-1112":https://jira.spring.io/browse/SEC-1112?redirect=false]) said:

Spring security is distributed as osgi ready but unfortunately it contains split packages which could cause problems in OSGI environments.

Examples of split packages can be found in spring-security-acl and spring-security-core:
- org.springframework.security.afterinvocation
- org.springframework.security.vote

For more info on split packages see:
- http://www.osgi.org/blog/2006/04/misconceptions-about-osgi-headers.html
- http://code9.com/2008/08/22/tip-split-packages-and-visibility/

Last link provides Chris Aniszczyk article explaining how eclipse does it.

I suggest complete removal of split packages in next major release.

**Comment by spring-issuemaster** [comment]
This issue duplicates #1302
