### ISSUE TITLE
Spring Security metric names should not contain dashes

### ISSUE THREAD

**Issue by Ducius6** [spring-projects/spring-security#13660]
When upgrading to Spring Boot 3 we had issue in new spring security metrics exposed with Micrometer. Issue seems to be that these metrics end up having "-" in it's name.
And since we are using prometheus, scraping/parsing of metrics did not work since prometheus can't have dash in it's metric name.

Exact metric that was causing the issue is "spring_security_filterchains_session_url-encoding_before_total" which is located in ObservationFilterChainDecorator.class.

Should naming of these metrics change so it can be used with prometheus?

**Comment by jzheaux** [comment]
Hi, @Ducius6. Yes, let's make the change and remove the `-` in `url-encoding` and `eager-create`.

Are you able to provide a PR?

**Comment by Ducius6** [comment]
Yes, sure. Will do!

**Comment by Ducius6** [comment]
Hi, create PR [here](https://github.com/spring-projects/spring-security/pull/14032)
