### ISSUE TITLE
Documentation contains inaccurate information about permitting the FORWARD dispatcher in Kotlin

### ISSUE THREAD

**Issue by username1103** [spring-projects/spring-security#13728]
**Describe the bug**

In the provided [documentation](https://docs.spring.io/spring-security/reference/servlet/authorization/authorize-http-requests.html#match-by-dispatcher-type), there is a code snippet that suggests using DispatcherType within the authorizeHttpRequests block as follows:
```kt
authorizeHttpRequests {
    authorize(DispatcherType.FORWARD, permitAll)
    authorize(anyRequest, authenticated)
}
```
However, it appears that there is no method available that accepts DispatcherType as an argument within the authorize method. As a result, users might encounter confusion when trying to implement authorization based on DispatcherType.

**To Reproduce**

![screenshot](https://github.com/spring-projects/spring-security/assets/67570061/23be23ad-1d10-40f3-bd56-1e132708c7b3)

**Expected behavior**

It seems like there might be potential for modifying the document as follows
```kt
authorizeHttpRequests {
    authorize(DispatcherTypeRequestMatcher(DispatcherType.FORWARD), permitAll)
    authorize(anyRequest, authenticated)
}
```
or considering an approach to overload the method that accepts the DispatchType in the “authorize” function.

**Comment by marcusdacoregio** [comment]
Closing in favor of https://github.com/spring-projects/spring-security/pull/13729
