### ISSUE TITLE
Add hasScope for authorization rules

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#13754]
`AuthorizationManager` makes the following possible in the DSL:

```java
http
    .authorizeHttpRequests((authorize) -> authorize
        .anyRequest().access(hasRole("USER"))
    )
```

It would be nice to be able to do the same with scopes, like so:

```java
http
    .authorizeHttpRequests((authorize) -> authorize
        .anyRequest().access(hasScope("resource:read"))
    )
```

This could be done in a static factory class like `OAuth2AuthorizationManagers` in `oauth2-core`. It could have `hasScope` and `hasAnyScope`. They might be implemented by delegating to `AuthorityAuthorizationManager` like this:

```java
public static <T> AuthorityAuthorizationManager<T> hasScope(String scope) {
    return AuthorityAuthorizationManager.hasAuthority("SCOPE_" + scope);
}
```

**Comment by petrovskimario** [comment]
Hello @jzheaux 
I would like to contribute for this one. Is this open ?

Question regarding the implementation
Should we just create a class like OAuth2AuthorizationManagers with hasScope and hasAnyScope and just that ?

**Comment by petrovskimario** [comment]
Hey @jzheaux 

I know this wasn't assigned to me yet, but i have already created the PR.
Can you please review if this is what we want ?
https://github.com/spring-projects/spring-security/pull/13769
Thanks

**Comment by petrovskimario** [comment]
Hey one more question
Why is the build failing with the following error : 
Error: eckstyle] [ERROR] /home/runner/work/spring-security/spring-security/oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/ScopeAuthorizationManagerFactory.java:36:69: Lambda argument missing parentheses. [SpringLambda]

It is failing on this part :
String[] mappedScopes = Arrays.stream(scopes).map(s -> "SCOPE_" + s).toArray(String[]::new);

Should i change it like this : 
String[] mappedScopes = Arrays.stream(scopes).map(s -> {
	return "SCOPE_" + s;
}).toArray(String[]::new);

Is this necessary ?
