### ISSUE TITLE
Support custom http authentication schemes

### ISSUE THREAD

**Issue by reda-alaoui** [spring-projects/spring-security#13779]
**Expected Behavior**

I'd like a filter similar to `BearerTokenAuthenticationFilter` that would support custom http authentication schemes.

**Current Behavior**

As its name indicates, `BearerTokenAuthenticationFilter` only supports the `Bearer` authentication scheme.

**Context**

I need to support a custom authentication scheme.

**Comment by marcusdacoregio** [comment]
Hi @reda-alaoui, can you elaborate more on your use-case? What is your custom authentication scheme? Have you tried using the `AuthenticationFilter`? Have you tried customizing the `BearerTokenAuthenticationFilter` properties?

**Comment by reda-alaoui** [comment]
Hi @marcusdacoregio ,
Here are some examples of registered authentication schemes => https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml
I need to define a specific, unregistered one.

I didn't know the existence of `AuthenticationFilter`. Looks like it's a good solution. Should be enough for me, but I think an `AuthenticationFilter` dedicated to custom authentication scheme would be better.

**Comment by marcusdacoregio** [comment]
> I need to define a specific, unregistered one.

In that case you have to implement your own. To do that, you can use the AuthenticationFilter as I mentioned before
