### ISSUE TITLE
Cannot reproduce scrypt encoded password

### ISSUE THREAD

**Issue by ChrisCho-H** [spring-projects/spring-security#13780]
`SCryptPasswordEncoder` provides `encode()` method but the salt is generated internally each time call the method.
To reproduce scrypt encoded password, it should also allow to pass salt in parameter.

it could be very useful in many ways.
For example,
1. user enters password which is gonna be used as a key to encrypt data
2. for security, encode password with scrypt
3. encrypted data is stored in any storage(and not encoded key)
4. to decrypt data, user enters password and then reproduce scrypt key to decrypt

**Comment by marcusdacoregio** [comment]
Hi, @ChrisCho-H. The idea of the salt is really to be randomly generated each time you encode a password, so two same strings become different hashes.

**Comment by ChrisCho-H** [comment]
I know. What I meant is to generate random byte outside of module and use that as a salt parameter, so that reproduce scrypt key.

**Comment by marcusdacoregio** [comment]
I don't see how the question that you linked relates to what you are asking. If you want, you can specify the `saltGenerator` inside the SCrypt implementation.
