### ISSUE TITLE
Customizable Exception for Invalid Client Registration ID in OAuth2AuthorizationRequestRedirectFilter

### ISSUE THREAD

**Issue by leewin12** [spring-projects/spring-security#13793]
Thank you for your continuous efforts in maintaining and improving spring security.
I would like to discuss a potential enhancement that could benefit many users.

**Expected Behavior**

Allow users to receive a more descriptive custom error message or be redirected to a specific error URL when an invalid client registration is provided during the OIDC process.

**Current Behavior**

1. A user enters the Client Registration ID and initiates the OIDC login process on our SPA page.
1. The SPA frontend constructs an OIDC initiation URL as https://{domain}/oauth2/authorization/{ClientRegistrationId}.
1. The user's browser redirects to the URL mentioned and reaches DefaultOAuth2AuthorizationRequestResolver via OAuth2AuthorizationRequestRedirectFilter.
1. If the ClientRegistrationId is invalid, DefaultOAuth2AuthorizationRequestResolver throws either an [IllegalArgumentException (5.7.x)](https://github.com/spring-projects/spring-security/blob/ff4745a461ee06bf554ff97b0c3c28f6366e856e/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/DefaultOAuth2AuthorizationRequestResolver.java#L152) or an [InvalidClientRegistrationIdException (5.8.x)](https://github.com/spring-projects/spring-security/blob/96d1763fc49e8121e15c5d595e84f8599cc6d2bf/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/DefaultOAuth2AuthorizationRequestResolver.java#L151).
1. OAuth2AuthorizationRequestRedirectFilter interrupts the filter chain and returns HttpStatus.INTERNAL_SERVER_ERROR. [(code)](https://github.com/spring-projects/spring-security/blob/9de717ac7a4eb78daf5b726d593dc362342a79af/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/OAuth2AuthorizationRequestRedirectFilter.java#L177)
1. The user is redirected to https://{domain}/error, triggering a white-label page.

**Context**

1. Pre-validating the ClientRegistrationId cannot prevent this situation.
1. In step (5), because OAuth2AuthorizationRequestRedirectFilter interrupts the filter chain, any additional error-handling filters become ineffective.
1. Overriding OAuth2AuthorizationRequestRedirectFilter offers no benefit due to the private accessor of unsuccessfulRedirectForAuthorization.
1. To the best of my knowledge, checking the ClientRegistrationId is not part of the OIDC process, so the framework might allow individual applications to set their own policies on this matter.

**Comment by sjohnr** [comment]
@leewin12 thanks for the report.

I think the current intention of the framework is that such an invalid `registrationId` case would be a configuration error, and is not intended to be handled (it should instead be fixed).

Having said that, there is room for improving error handling in this area and making it more flexible. I believe it would be fairly challenging though, so it could require some iterating to come up with a solution. Do you have any ideas for something we could introduce to make it more customizable? Would you be interested in opening a PR with such changes when we get to that point? I'm happy to help work with you on it.

**Comment by leewin12** [comment]
Greetings @sjohnr ,

Thank you for your insights on this issue.

I'm indeed willing to open a PR; Please excuse that it might take several weeks due to my current schedule.

My initial thought is to introduce an error handling interface along with a default implementation. If you have any other ideas, or if you believe my approach might not align with the framework's direction, please let me know.

I'd like to take this opportunity to express my gratitude to all the Spring Security framework contributors. Your efforts are deeply appreciated.

**Comment by sjohnr** [comment]
> (I'd like to take this opportunity to express my gratitude to all the Spring Security framework contributors. Your efforts are deeply appreciated.)

Thank you for the kind words! I'll pass on your appreciation to the team.

> My initial thought is to introduce an error handling interface along with a default implementation.

My only thought at this point would be to suggest trying to use an existing interface before creating a new one. When you get closer to that point we can discuss possible options. We probably want to aim for more general solutions than ones specific to a single type of error.
