### ISSUE TITLE
java.lang.ClassNotFoundException in spring-security-test

### ISSUE THREAD

**Issue by voy13k** [spring-projects/spring-security#13813]
java.lang.ClassNotFoundException: o.s.security.oauth2.server.resource.authentication.JwtGrantedAuthoritiesConverter received when using ``o.s.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.jwt()`` in the ``@SpringBootTest @AutoConfigureMockMvc`` tests.

**Manual fix**
As is, a ``spring-boot-starter-oauth2-authorization-server`` test dependency has to be added to the project separately.

**Expected behavior**
Since ``SecurityMockMvcRequestPostProcessors.jwt()`` comes from ``spring-security-test`` package the expected behavior would be for it to come with all the dependencies required to use it. Or at least to declare ``spring-boot-starter-oauth2-authorization-server`` as its optional dependency.

**Sample**
[Bug Demo](https://github.com/voy13k/bugdemo)
To see the bug run ``./mvnw test``.
To see success run ``./mvnw test -P fixed``.
The ``fixed`` profile adds the missing dependency explicitly.

**Comment by Imrnkhan** [comment]
Check Dependencies and add some dependencies and update project this way

<dependency>
    <groupId>org.springframework.security</groupId>
    <artifactId>spring-security-test</artifactId>
    <version></version>
    <scope>test</scope>
</dependency>

**Comment by Imrnkhan** [comment]
[<dependency>
    <groupId>org.springframework.security</groupId>
    <artifactId>spring-security-test</artifactId>
    <version></version>
    <scope>test</scope>
</dependency>
](url)

**Comment by voy13k** [comment]
> Hi, @voy13k. The `spring-security-test` provides some utility classes and methods that can be used to test our application. The `SecurityMockMvcRequestPostProcessors#jwt()` expects that you are using the [Spring Security OAuth 2.0 Resource Server support](https://docs.spring.io/spring-security/reference/servlet/oauth2/resource-server/index.html), therefore, you need the `spring-security-oauth2-resource-server` dependency.
> 
> That behavior is expected because `spring-security-test` won't bring all the dependencies for you if, for example, you just want to use `@WithMockUser`.

Whay not add such dependencies to spring-security-test POM as optional then? It was done in the gradle, why not maven? Would have save me and countless other some headaches trying to search the internet.

**Comment by voy13k** [comment]
> [ org.springframework.security spring-security-test test ](url)

Your suggestion doesn't work. Please read the full report.
