### ISSUE TITLE
SEC-1139: acl_object_identity.owner_sid should be 'not null' in schema

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1386]
["Brian Ewins":https://jira.spring.io/secure/ViewProfile.jspa?name=bazzargh](Migrated from ["SEC-1139":https://jira.spring.io/browse/SEC-1139?redirect=false]) said:

In the documentation (src/docbkx/appendix-db-schema.xml), acl_object_identity.owner_sid is defined as:
owner_sid bigint,

but in the code, AclImpl.java requires that the owner sid is not null, and in fact you'll get an exception from BasicLookupStrategy attempting to create sids with null values if you read an object identity with a null owner_sid. Triggered this bug migrating data from a non-spring/acegi acl implementation which didn't use owners.

https://fisheye.springsource.org/browse/spring-security/trunk/src/docbkx/appendix-db-schema.xml

**Comment by spring-issuemaster** [comment]
This issue supersedes #740
