### ISSUE TITLE
SEC-1140: ace masks are not being compared as bitmasks.

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1388]
["Brian Ewins":https://jira.spring.io/secure/ViewProfile.jspa?name=bazzargh](Migrated from ["SEC-1140":https://jira.spring.io/browse/SEC-1140?redirect=false]) said:

Granting permissions with bitmasks with more than one bit set does not have the expected result, eg:

```
    MutableAcl acl = (MutableAcl) mutableAclService.readAclById(objectIdentity);
    Permission perm = BasePermission.buildFromMask(BasePermission.CREATE.getMask() | BasePermission.DELETE.getMask());
    acl.insertAce(0, perm, sid, true);
    assert(acl.isGranted(new Permission[]{BasePermission.CREATE}, new Sid[] {sid}, false));
```

As well as the forum link above, this gets mentioned other times in the forum:
http://forum.springsource.org/showthread.php?p=235305
http://forum.springsource.org/showthread.php?t=68655
and as one of the many issues in SEC-479. I'm raising this to split this one issue into a separate bug.

each time its come up, the outcome is that people are reimplementing AclImpl, BasicLookupStrategy etc. In our case we're migrating data from a different acl system, and this results in us having to split up every individual permission in the database, (since otherwise the CumulativePermission loaded never matches). It does seem to defeat the purpose of these things being bitmasks, as well as meaning we need to store 32x as many rows.

**Comment by spring-issuemaster** [comment]
This issue supersedes #740
