### ISSUE TITLE
OAuth2RefreshTokenAuthenticationProvider java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class org.springframework.security.core.Authentication (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; org.springframework.security.core.Authentication is in unnamed module of loader 'app')

### ISSUE THREAD

**Issue by burakbalim** [spring-projects/spring-security#13971]
Hello, 

I'm getting an error

`java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class org.springframework.security.core.Authentication (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; org.springframework.security.core.Authentication is in unnamed module of loader 'app') on OAuth2RefreshTokenAuthenticationProvider `

when I used JdbcOAuth2AuthorizationService (for MySQL)

<img width="1641" alt="image" src="https://github.com/spring-projects/spring-security/assets/9086942/828a5d02-5b0b-497b-ae2d-4d3f88ffe2c5">

	DefaultOAuth2TokenContext.Builder tokenContextBuilder = DefaultOAuth2TokenContext.builder()
				.registeredClient(registeredClient)
				.principal(authorization.getAttribute(Principal.class.getName())) --> error occurred in this line
				.authorizationServerContext(AuthorizationServerContextHolder.getContext())
				.authorization(authorization)
				.authorizedScopes(scopes)
				.authorizationGrantType(AuthorizationGrantType.REFRESH_TOKEN)
				.authorizationGrant(refreshTokenAuthentication);

**Comment by marcusdacoregio** [comment]
Hi, @burakbalim. If I am seeing correctly, this seems to be an issue related to Spring Authorization Server. Would you please open an issue in [their issue tracker](https://github.com/spring-projects/spring-authorization-server/issues)?

**Comment by burakbalim** [comment]
Sorry for late response, yes I can open new issue, I spent a lot of time using object mapper for different ways and I can’t solve it, and lastly I found making new desarilazer for convert to Authenticationtoken model but I need to spend a lot of time of it, really bad experience for me, I will open new issue about this problem, main problem is object mapper parsing data from coming MySQL data

**Comment by karthikkudukuntla3959** [comment]
@burakbalim can you please provide the deserializer code .

**Comment by burakbalim** [comment]
I have started to write but have not finished yet (I have urgent other codes) I think, spring should provide this(I don't understand why they did this)

<img width="1603" alt="image" src="https://github.com/spring-projects/spring-security/assets/9086942/db01ba1b-53e6-40fa-8e7f-947d29599ff4">
