### ISSUE TITLE
Broken links to Api Docs on https://spring.io/projects/spring-security#learn

### ISSUE THREAD

**Issue by mrotteveel** [spring-projects/spring-security#14056]
The "Api Doc" links on https://spring.io/projects/spring-security#learn are broken for all versions except "6.2.0-SNAPSHOT", "5.7.12-SNAPSHOT" and "5.7.11". The problem is that the links of the other versions (5.8.x, 6.0.x and 6.1.x) all point to `https://docs.spring.io/spring-security/docs/<version>/api/` while they should point to `https://docs.spring.io/spring-security/site/docs/<version>/api/`.

The fact that "6.2.0-SNAPSHOT" does point to a working link suggests it may have been fixed for that version, but this should also be fixed for the versions 5.8.x, 6.0.x and 6.1.x

**Comment by marcusdacoregio** [comment]
Thanks, @mrotteveel. This is now fixed.

**Comment by mrotteveel** [comment]
Thanks @marcusdacoregio
