### ISSUE TITLE
SEC-1154: LdapAuthenticationProvider.createSuccessfulAuthentication() returned object should include authentication.getDetails() if using useAuthenticationRequestCredentials

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1406]
[Juan Pablo Santos](https://jira.spring.io/secure/ViewProfile.jspa?name=juanpablo) (Migrated from [SEC-1154](https://jira.spring.io/browse/SEC-1154?redirect=false)) said:

the createSuccessfulAuthentication(UsernamePasswordAuthenticationToken auth, UserDetails user) method from LdapAuthenticationProvider returns a new UsernamePasswordAuthenticationToken based on auth's password, depending on useAuthenticationRequestCredentials boolean.

In the case this happens, shouldn't the returned object also include auth.getDetails()? I.e., something like:

protected Authentication createSuccessfulAuthentication(UsernamePasswordAuthenticationToken authentication, UserDetails user)
{
  Object password = useAuthenticationRequestCredentials ? authentication.getCredentials() : ((Object) (user.getPassword()));
  if (useAuthenticationRequestCredentials)
  {
      UsernamePasswordAuthenticationToken token = new UsernamePasswordAuthenticationToken(user, password, user.getAuthorities());
      token.setDetails(authentication.getDetails());
      return token;
  }
  return new UsernamePasswordAuthenticationToken(user, password, user.getAuthorities());
}

(as part of our current project, we are building a custom authenticationProvider which extends LdapAuthenticationProvider, and we expected this behaviour. Not very sure this should be marked as bug or as an improvement, though)

**Comment by spring-issuemaster** [comment]
This issue duplicates #1335
