### ISSUE TITLE
SEC-1155: Potential NPEs in RoleVoter and RoleHierarchyVoter

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1407]
[Pavel Tcholakov](https://jira.spring.io/secure/ViewProfile.jspa?name=pcholakov) (Migrated from [SEC-1155](https://jira.spring.io/browse/SEC-1155?redirect=false)) said:

The implementations of RoleVoter and RoleHierarchyVoter can throw a NPE if called with a null authentication object. It may sometimes be desirable to call AccessDecisionManager.decide() with a null parameter, e.g. see my comment under SEC-884 for one such case where it can be used to implement the ifNotGranted feature correctly.

These problems can be fixed trivially as follows

In RoleVoter.java:

```
GrantedAuthority[] extractAuthorities(Authentication authentication) {
    return authentication != null ? authentication.getAuthorities() : new GrantedAuthority[]{};
}
```

In RoleHierarchyVoter.java:

```
GrantedAuthority[] extractAuthorities(Authentication authentication) {
    return roleHierarchy.getReachableGrantedAuthorities(super.extractAuthorities(authentication));
}
```

The latter method can do the null check itself rather than calling super, but this way there is less repetition although arguably it's less clear what is happening ;-)

**Comment by spring-issuemaster** [comment]
This issue is related to #1136
