### ISSUE TITLE
Bugs occur when roles and authorities are built at the same time

### ISSUE THREAD

**Issue by vanga-top** [spring-projects/spring-security#14089]
**Describe the bug**
Bugs occur when roles and authorities are built at the same time.
The content is overwritten by the latter

**To Reproduce**

when use code under line to build UserDetails, the value of authorities will be empty.

```java
           UserDetails userDetails = User.withDefaultPasswordEncoder()
                    .username("admin")
                    .password("123456")
                    .roles("admin")
                    .authorities("admin:get")
                    .build();
```

<img width="973" alt="image" src="https://github.com/spring-projects/spring-security/assets/39117876/058e7f0d-be4f-4270-b783-908555c271d7">

the reason is at line 444 under package org.springframework.security.core.userdetails and class User

<img width="804" alt="image" src="https://github.com/spring-projects/spring-security/assets/39117876/919d3f5c-0029-40be-81cb-8d6d66173ccc">

**Expected behavior**

Since a method of continuous execution is provided, the results should be as expected.

so it should be :

```java
    this.authorities.addAll(authorities);
```

**Versions**
spring-security-core:6.1.5

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by sjohnr** [comment]
@vanga-top thanks for your interest in the project and the suggestion

> when use code under line to build UserDetails, the value of authorities will be empty.

I'm not sure I understand this but it seems to be an inaccurate statement, which is demonstrated by your screenshot.

> Since a method of continuous execution is provided, the results should be as expected.
> 
> so it should be :
> 
> ```java
>     this.authorities.addAll(authorities);
> ```

The change you are suggesting is a breaking change. The builder methods `authorities(..)` and `roles(...)` are intended to replace the authorities. You can achieve the desired result with the following:

```java
           UserDetails userDetails = User.withDefaultPasswordEncoder()
                    .username("admin")
                    .password("123456")
                    .authorities("ROLE_admin", "admin:get")
                    .build();
```

Perhaps it would be worthwhile to open an enhancement for additional builder methods that only add a single authority to the list, e.g. `role(String)`, `authority(String)`. But in any case, that would be a separate enhancement.

I'm going to close this issue as we don't want to make a breaking change.
