### ISSUE TITLE
Raised Issues are closed without allowing response - no way to reopen them

### ISSUE THREAD

**Issue by dbnex14** [spring-projects/spring-security#14083]
**Expected Behavior**
I should be able to reopen the issue if I feel there was no response that solves the issue or reaches an agreement.

I should be able to reopen the issue. In the above case, I have good points that I am bringing up and they are obvious.  But the issue gets marked as closed effectively making it no longer helpful as closed issues are also resolved issues.  This is not resolved though.

**Current Behavior**
If someone creates an issue, the person has no opportunity to response to comment prior issues being closed.  This means that options to create an issue here are just a formality.  The moderator in this issue https://github.com/spring-projects/spring-security/issues/14079 simply provided response that makes little sense and decided to close the issue.  I had no chance to debate and find solution while issue is open.  While I can respond to his comment, I have no ability to reopen the issue effectively making my reported issue useless.  

Issues are closed arbitrarily making them useles.  If someone can close the issue by providing *any* answer and assuming that that is the *correct* answer and closing the issue, then creating issues for Spring Security makes no sense at all.

**Context**

**Comment by marcusdacoregio** [comment]
Hi, @dbnex14. I am sorry that you felt that I wanted to interrupt the discussion when I closed the issue, but that is not what I meant and that is not what a closed issue means too, a closed issue can always be reopened.

Your last comment was 2 hours ago and I haven't had time to read it thoroughly yet, please be patient.

**Comment by dbnex14** [comment]
@marcusdacoregio nothing personal, I used that jira as an example to show the workflow isssue.  If the issue is closed prematurely, the initiator may loose interest commenting on it further or creating new issues.  Also, other users may loose interest in issue if it is marked as closed.  Again, nothing personal and thank you.  Please reopen that issue as the provided answer and suggestions are contradicting each other and as you can imagine, seeing in an organization logs stating "anonymous context will be used for read-write operations" raises red flags all over the place.  I have answered that item and I have explained to my best, please let me know and please reopen it.  Thank you
