### ISSUE TITLE
Improve logging in NimbusReactiveJwtDecoder

### ISSUE THREAD

**Issue by ThomasHagelberg** [spring-projects/spring-security#14091]
**Catched exception should be logged before JwtException is thrown**

Before a JwtException is thrown, the catched errorMsg should logged on an appropriate level. In order to quickly be able to identify the root cause in the event of a problem.

**Current Behavior**
Plugin: 
- org.springframework.boot: 3.1.3

Artifacts: 
- org.springframework.boot:spring-boot-starter-webflux:3.1.3
- org.springframework.security:spring-security-oauth2-jose:6.1.3

It simply throws:
`throw new BadJwtException("Failed to validate the token", ex);` which is used for logging in AuthenticationWebFilter at DEBUG level only

In a real world application, proper logging to monitor the application state is crucial. At the moment only a verbose message "Failed to validate the token" is logged at DEBUG level, which is not really used in prod profiles? Also the errorMsg doesn't provide any more information than the 401 Unauthorized response code that is returned regardless.

**Context**
After I got my NimbusReactiveJwtDecoder to work with jwks validation. I wanted to see how the implementation handles invalid scenarios, logging etc. And to my surprise, there is in practice no logging at all. There is a lot of exceptions carrying different messages, but eventually they all end up in the WebFilter as: "Authentication failed: Failed to validate the token".

Is it possible that the NimbusReactiveJwtDecoder actually log the catched exceptions?
One practical example is when the jwks public key signature is a mismatch from the private key used to sign the JWT that is used as Authorization Bearer:

[Here](https://github.com/spring-projects/spring-security/blob/main/oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusReactiveJwtDecoder.java#L298) you can see how the BadJWSException is thrown when the signature is invalid. Originally thrown from DefaultJWTProcessor in com.nimbusds.jwt.proc

![image](https://github.com/spring-projects/spring-security/assets/77971394/27fb21a4-0c3e-48b6-b42c-8c71e6905127)

![image](https://github.com/spring-projects/spring-security/assets/77971394/f8e7ce77-44ca-4c8f-803b-2757c424c017)

This flow makes it really hard to use in production environment, because if any of these JwtExceptions would occur (due to invalid Jwt signatures being sent etc.), it would be of great value to see the reason for the actual exception, and preferably not at debug level. Either some bean config that enables additional logging or some other smart way would be hugely beneficial to have.

I'm more than happy to answer additional questions :)

I wish all of you to have a lovely week.
Sincerely, Thomas

**Comment by ThomasHagelberg** [comment]
Hi and thanks for your answer @jzheaux. I will try to get a PR sorted.

**Comment by ThomasHagelberg** [comment]
Hi and sorry for asking @jzheaux, do you want the thrown exception message to be changed to what is originally thrown:
![image](https://github.com/spring-projects/spring-security/assets/77971394/c6e425c2-8af8-456a-9bde-4f95cb66ce4c)

Or do you simply want the caused exception (stacktrace?) to be logged?
![image](https://github.com/spring-projects/spring-security/assets/77971394/b35c146c-d82d-4203-b5d4-511022e23b25)

Or do you want me to check what exception is thrown in JwtReactiveAuthenticationManager, and have some specific flow based on that?
![image](https://github.com/spring-projects/spring-security/assets/77971394/2d4aee0a-0655-4c5b-bfe9-495e0209095b)

**Comment by jzheaux** [comment]
No problem, @ThomasHagelberg! Thanks for asking.

I was thinking that we should add the causing exception to [this line](https://github.com/spring-projects/spring-security/blob/main/web/src/main/java/org/springframework/security/web/server/authentication/AuthenticationWebFilter.java#L128).

So:

```java
(ex) -> logger.debug(LogMessage.format("Authentication failed: %s", ex.getMessage())));
```

would change to

```java
(ex) -> logger.debug(LogMessage.format("Authentication failed: %s", ex.getMessage()), ex));
```

This would make so that the reason for the failure isn't lost.

**Comment by ThomasHagelberg** [comment]
Lovely thank for the reply @jzheaux

This is how it would look now:
![image](https://github.com/spring-projects/spring-security/assets/77971394/6a3d9e64-d287-4e0b-9f3e-1e6865e71974)

Ok to setup a PR? And if so, do you want the commit message as: 
"Improve logging in AuthenticationWebFilter
Closes #14091"

I'm checking the contributing guide, but your feedback would be appreciated.

**Comment by jzheaux** [comment]
Sorry for the delay, @ThomasHagelberg. Yes, that looks typical for a DEBUG log to me.

The only tweak I'd make to the commit message is that we usually use the infinitive like this: "Improve Logging ..." instead of "Improves Logging ..."

**Comment by ThomasHagelberg** [comment]
Hi @jzheaux!

I apologize for the delay in opening the PR, I have been busy with new and different programming concepts recently. However, I'm now turning my attention back to the OIDC project. Wishing you a pleasant weekend in the meantime! :)
