### ISSUE TITLE
Broken link in the servlet starting page adoc

### ISSUE THREAD

**Issue by Ruffeng** [spring-projects/spring-security#14118]
**Describe the bug**
There's one of the links on the home page that does not lead you to the desired section. This is because the headline has a different ID than the anchor name. Checking the adocs page, it seems that the headline has 2 specific id and it only processes the last one(which doesn't match)

**To Reproduce**
[Steps to reproduce the behaviour.](https://docs.spring.io/spring-security/reference/servlet/getting-started.html) go into the page and search for "Better understand [what Spring Boot enables in Spring Security by default](https://docs.spring.io/spring-security/reference/servlet/getting-started.html#hello-expectations)". You will notice that this link goes nowhere when clicked.

**Expected behaviour**
I expect to go into the next section called Runtime Expectations

**Comment by marcusdacoregio** [comment]
Thanks @Ruffeng, closing in favor of #14119 .
