### ISSUE TITLE
SEC-1164: Spring Security extension does not seem to support security namespace config in Open Graph

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1412]
[Willie Wheeler](https://jira.spring.io/secure/ViewProfile.jspa?name=wwheeler) (Migrated from [SEC-1164](https://jira.spring.io/browse/SEC-1164?redirect=false)) said:

Please see the Spring forum reference above, and in particular, the message I posted on Mar 29, 2009.

I've installed the Spring IDE Spring Security Extension (2.2.4.RELEASE) and would have expected that this would allow me to use Open Graph to visualize security namespace configurations, such as <http>, <authentication-provider>, <user-service> and so forth.  (The Spring Batch Extension allows me to visualize the custom Spring Batch namespace just fine.)  Not sure if my expectation is wrong or whether I'm just missing something.

**Comment by spring-issuemaster** [comment]
This issue depends on #1435
This issue depends on #1444
