### ISSUE TITLE
JdbcUserDetailsManager does not implement UserDetailsPasswordService, which causes passwords not to be upgraded

### ISSUE THREAD

**Issue by geirhe** [spring-projects/spring-security#14126]
**Describe the bug**
While testing spring authorization server I noticed my client secrets were updated, but not my user secrets. I think I tracked it back to JdbcUserDetailsManager not implementing UserDetailsPasswordService, like InMemoryUserDetailsManager does.

**To Reproduce**
Set up a basic spring authorization server according to the documentation, with JdbcUserDetailsManager configured for users, make a user with a secret of "{noop}secret".

**Expected behavior**
The secret should be updated to a bcrypted hash

**Comment by jzheaux** [comment]
Hi, @geirhe. Thanks for reaching out. This is a duplicate of https://github.com/spring-projects/spring-security/issues/7750. Please feel free to add any needed conversation there.
