### ISSUE TITLE
SEC-1165: Relax the requirement that the ObjectIdentity "type" be a Java class 

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1413]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1165](https://jira.spring.io/browse/SEC-1165?redirect=false)) said:

This is really just a piece of metadata to identify the specific domain object type (e.g. Contact) to which an ACL applies. In practice it is converted to a String (the classname) when stored in the database. There's no real requirement that it should be a unique Java class or that the class should be loadable when the ObjectIdentity is created. It would be more flexible if it was just treated as a String.

The  method

 Class<?> getJavaType();

on the interface should be changed to return a String, and the property should be changed to "type" or "objectType" or something similar.

**Comment by spring-issuemaster** [comment]
This issue supersedes #740
This issue supersedes #1097
