### ISSUE TITLE
SEC-1166: Provide strategy interface for AclImpl isGranted() method. 

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1414]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1166](https://jira.spring.io/browse/SEC-1166?redirect=false)) said:

This will allow more flexibility in the way the permission bitmasks are evaluated. The existing auditLogger should be moved to the default implementation, as this is the only place logging occurs in AclImpl.

**Comment by spring-issuemaster** [comment]
This issue supersedes #740
