### ISSUE TITLE
SEC-1167: Introduce more flexible SavedRequest handling

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1415]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1167](https://jira.spring.io/browse/SEC-1167?redirect=false)) said:

The current SavedRequest approach is rather restricted. It would be better if a strategy was introduced which handled the generation of a SavedRequest. With that in mind, SecurityContextHolderAwareRequestFilter should also use a strategy for generating the wrapper, rather than being configured with a wrapper class.  This would handle the request matching and generation of the wrapped request, if required.

Interfaces:

RequestPersister {
     saveRequest(HttpServletRequest request);
}

(default implementation produces a SavedRequest and stores it in the session). Possibly make SavedRequest an interface to allow customization.

RequestFactory {
     HttpServletRequest createRequest(HttpServletRequest request);
}

(reloads the saved request and returns a wrapper delegating to it). The existing SavedRequestAwareWrapper would be used in a modified form (it currently does the matching itself but that would be done by the factory implementation).

The default SavedRequestHandler could implement both interfaces.

It should also be possible to disable SavedRequest use completely in ExceptionTranslationFilter when the application always uses a default target, for example.

**Comment by spring-issuemaster** [comment]
This issue supersedes #1062
