### ISSUE TITLE
SEC-1171: Allow multiple namespace <http> elements to support multiple filter chain configurations

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1419]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1171](https://jira.spring.io/browse/SEC-1171?redirect=false)) said:

The main use case for this is supporting stateless and stateful URLs within the same application (different session creation policies). For example, a normal application which users can log into may also expose REST service endpoints.

**Comment by spring-issuemaster** [comment]
This issue supersedes #1712
