### ISSUE TITLE
OAuth2RestTemplate deprecated from spring boot 3

### ISSUE THREAD

**Issue by VanitaDhanagar** [spring-projects/spring-security#14216]
Question Summary
If applicable, please mention:

Environment: Cloud Foundry
Additional information
I want to migrate a application from spring boot 2 to 3 and we are stuck wth OAuth2RestTemplate which is no longer supported

	<dependency>
		<groupId>org.springframework.security.oauth</groupId>
		<artifactId>spring-security-oauth2</artifactId>
		<version>2.5.0.RELEASE</version>
	</dependency>
More info on code https://github.com/SAP-samples/cloud-espm-cloud-native/blob/main/worker/src/main/java/com/sap/refapps/espm/config/EnterpriseMessagingConfig.java

Kinldy guide us in migrating the application with steps and examples

Regards,
vanita

**Comment by marcusdacoregio** [comment]
Hi, @VanitaDhanagar.

Spring Security OAuth 2.x is not longer supported, the support was migrated into Spring Security. Check the [migration guide](https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide) and the [reference documentation](https://docs.spring.io/spring-security/reference/servlet/oauth2/index.html) to help you migrate.
