### ISSUE TITLE
New approach to AuthenticationManager

### ISSUE THREAD

**Issue by ximq33** [spring-projects/spring-security#14243]
In my previous project i had AuthenticationManager configured like this:

   @Bean
    AuthenticationManager authenticationManager(HttpSecurity http, BCryptPasswordEncoder bCryptPasswordEncoder, UserDetailsService userDetailsService)
            throws Exception {
        return http.getSharedObject(AuthenticationManagerBuilder.class)
                .userDetailsService(users())
                .passwordEncoder(bCryptPasswordEncoder)
                .and()
                .build();
    }

But now i see that ".and()" is deprecated. What would be the new approach for this?

**Comment by andreilisa** [comment]
This question is for StackOverflow, you could ask it there using `spring-security` tag. Also you could find something similar on my answer about it [updating-to-latest-spring-security-replacing-deprecated-methods](https://stackoverflow.com/questions/76828540/updating-to-latest-spring-security-replacing-deprecated-methods/76828647#76828647)

**Comment by jzheaux** [comment]
Hi, @ximq33, thanks for reaching out. And @andreilisa thanks for the links. I added my response to the link; I hope it helps.
