### ISSUE TITLE
SEC-1181: Active Directory LDAP Authentication Provider

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1429]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1181](https://jira.spring.io/browse/SEC-1181?redirect=false)) said:

Active directory is sufficiently different from standard LDAP and is very commonly used, so we should probably have a specific authentication provider which handles typical AD authentiation, plus namespace support.

**Comment by spring-issuemaster** [comment]
This issue supersedes #1215
This issue supersedes #1427
