### ISSUE TITLE
Link to article with remember-me-persistent-token strategy is broken

### ISSUE THREAD

**Issue by ram0973** [spring-projects/spring-security#14358]
Here
[https://docs.spring.io/spring-security/reference/servlet/authentication/rememberme.html#remember-me-persistent-token](https://docs.spring.io/spring-security/reference/servlet/authentication/rememberme.html#remember-me-persistent-token)
is link to article
[http://jaspan.com/improved_persistent_login_cookie_best_practice](http://jaspan.com/improved_persistent_login_cookie_best_practice)
Site (jaspan.com) can't be opened and is requesting a login.
Maybe, we can add a link to original article, and additions from web-archive?
[https://fishbowl.pastiche.org/2004/01/19/persistent_login_cookie_best_practice](https://fishbowl.pastiche.org/2004/01/19/persistent_login_cookie_best_practice)
[https://web.archive.org/web/20180819014446/http://jaspan.com:80/improved_persistent_login_cookie_best_practice](https://web.archive.org/web/20180819014446/http://jaspan.com:80/improved_persistent_login_cookie_best_practice)

**Comment by marcusdacoregio** [comment]
Hi @ram0973, are you interested in submitting a PR to fix it?

**Comment by YangSiJun528** [comment]
The issue has been fixed in 5.8.x by [this commit](https://github.com/spring-projects/spring-security/commit/95a1ccb52cdeeda7fa92999f9c2050316df38a51). However, this change doesn't seem to be reflected from the 6.0.x version onwards.
