### ISSUE TITLE
Application context fails to load: Couldn't find FilterChainProxy

### ISSUE THREAD

**Issue by agrgat** [spring-projects/spring-security#14370]
**Describe the bug**
Application context fails to load after upgrading from spring boot version 3.1.5 to 3.2.1 with error message: “Couldn't find FilterChainProxy” in a list of Filters.

SecurityConfig is defined as follows: 
`
@Configuration
@EnableWebSecurity(debug = true)
class SecurityConfig {
	@Bean
        fun filterChain(http: HttpSecurity): SecurityFilterChain {…}
}
`

The issue is in the debug flag of the @EnableWebSecurity annotation. If the debug flag is set to true, the Filter is instantiated with the type of DebugFilter instead of the FilterChainProxy.

**Comment by marcusdacoregio** [comment]
Thanks, @agrgat. This has been fixed via https://github.com/spring-projects/spring-security/commit/7cd626fe2569346b945feec40fa16f231a558fde.

**Comment by adnsimona** [comment]
Oh yes I see here https://github.com/spring-projects/spring-security/commit/7cd626fe2569346b945feec40fa16f231a558fde 6.2.2 clicking the (...) Thanks for the fix. I check it out.
