### ISSUE TITLE
IllegalStateException: Couldn't find FilterChainProxy

### ISSUE THREAD

**Issue by momer524** [spring-projects/spring-security#14398]
**Describe the bug**
when security web run in debug mode, it throw 
```
IllegalStateException: Couldn't find FilterChainProxy
```

**To Reproduce**
environment
```
jdk17
maven:3.9.5
spring-boot-starter-web:3.2.1
spring-boot-starter-security:6.2.1
```
any example using anotation
```java
@EnableWebSecurity(debug = true)
```
reason
![image](https://github.com/spring-projects/spring-security/assets/68207391/e87e31a1-aa65-462e-bda0-afa4d2f8c791)
![image](https://github.com/spring-projects/spring-security/assets/68207391/3aeb83a4-0381-4032-bce8-4e170bfe68cc)
![image](https://github.com/spring-projects/spring-security/assets/68207391/65ec117e-0e4f-45d2-8621-e4139e528ec0)

**Sample**
git@github.com:momer524/security-debug-model-issue.git

**Comment by marcusdacoregio** [comment]
Hi, @momer524. This is a duplicate of https://github.com/spring-projects/spring-security/issues/14370
