### ISSUE TITLE
Add Documentation About Serialization Between Minor Versions

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-security#14409]
Documentation and maybe a blog post should be added for https://github.com/spring-projects/spring-security/issues/3737

**Comment by marcusdacoregio** [comment]
https://spring.io/blog/2024/01/19/spring-security-6-3-adds-passive-jdk-serialization-deserialization-for/

**Comment by seabamirum** [comment]
What are we supposed to do if we've been waiting on this issue since version 6.1.9 and need to upgrade?
