### ISSUE TITLE
Request to add Custom Properties to AuthenticationConfiguration

### ISSUE THREAD

**Issue by CHOICORE** [spring-projects/spring-security#14451]
Dear. Spring Developers

Although late, I sincerely hope that you receive many blessings in the new year.

**Expected Behavior**
Would you be so kind as to create a method for utilizing the AuthenticationManager directly, or perhaps devise a property to bypass or eliminate the Default Provider, particularly in circumstances where the AuthenticationManager can be used outright?

**Current Behavior**
Currently, there is no way to register and use the AuthenticationManager object as a global bean.
I am trying to register a custom Provider, but...

I believe that the DaoAuthenticationProvider is not necessary in the Bearer Token authentication method. Therefore, I did not implement UserDetailsService. However, when I inject the ProviderManager and run authenticate, a proxy object is injected, and a StackOfFlow occurs when trying to find a Bean

```java
    @Bean
    public AuthenticationManager authenticationManager(AuthenticationConfiguration authenticationConfiguration) throws Exception {
        ProviderManager authenticationManager = (ProviderManager) authenticationConfiguration.getAuthenticationManager();
        authenticationManager.getProviders().add(new CustomProvider());
        return authenticationManager;
    }
```

```java
public class CustomFilter extends OncePerRequestFilter {

    private final AuthenticationManager authenticationManager;

    public CustomFilter(final AuthenticationManager authenticationManager) {
        this.authenticationManager = authenticationManager;

    }

    @Override
    public void afterPropertiesSet() throws ServletException {
        super.afterPropertiesSet();
        ProviderManager providerManager = (ProviderManager) authenticationManager;
        providerManager.getProviders().removeAll(providerManager.getProviders());
        providerManager.getProviders().add(new CustomProvider());
    }

    @Override
    protected void doFilterInternal(
            final HttpServletRequest request,
            final HttpServletResponse response,
            final FilterChain filterChain)
            throws ServletException, IOException {
        CustomToken user = new CustomToken(List.of(new SimpleGrantedAuthority("USER")));
        authenticationManager.authenticate(user);
        filterChain.doFilter(request, response);
    }
}
```
![image](https://github.com/spring-projects/spring-security/assets/41681972/85a2803f-7e1d-4d92-9c96-a4f8713bb731)

![image](https://github.com/spring-projects/spring-security/assets/41681972/fc13482c-a71b-4f48-afab-028cef2f1e95)

**Comment by marcusdacoregio** [comment]
Hi, @CHOICORE. Thanks for the good wishes.

I believe that the documentation about [how to publish a `AuthenticationManager` bean](https://docs.spring.io/spring-security/reference/servlet/authentication/passwords/index.html#publish-authentication-manager-bean) and [this issue](https://github.com/spring-projects/spring-security/issues/12343) might help you fixing the issue.
If you still believe that there is some place for enhancement or if there is a bug, feel free to comment back in this issue and we can consider reopening it.
