### ISSUE TITLE
Spring Security 6 with Spring Boot 3.2.1 403 Forbidden after migration.

### ISSUE THREAD

**Issue by mikebgrep** [spring-projects/spring-security#14450]
I am providing a simple reproduction project.
After I migrate from Spring boot 2.8.7 to Spring Boot 3.2.1 with Spring Security 6 when the Security configuration is with anyRequest().authenticated() I receive 403 Forbidden if i permitAll() requests, everything work as generating JWT and using the application.

``` Securing POST /accounts
2024-01-13T16:18:04.537+02:00 DEBUG 73343 --- [nio-8082-exec-1] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2024-01-13T16:18:04.539+02:00 DEBUG 73343 --- [nio-8082-exec-1] o.s.s.w.a.Http403ForbiddenEntryPoint     : Pre-authenticated entry point called. Rejecting access
2024-01-13T16:18:04.546+02:00 DEBUG 73343 --- [nio-8082-exec-1] o.s.security.web.FilterChainProxy        : Securing POST /error
2024-01-13T16:18:04.547+02:00 DEBUG 73343 --- [nio-8082-exec-1] o.s.s.w.a.AnonymousAuthenticationFilter  : Set SecurityContextHolder to anonymous SecurityContext
2024-01-13T16:18:04.547+02:00 DEBUG 73343 --- [nio-8082-exec-1] o.s.s.w.a.Http403ForbiddenEntryPoint     : Pre-authenticated entry point called. Rejecting access
```
You can take a look the simple project its use H2 as databse.
Reproduction repository link:
https://github.com/mikebgrep/simple-spring-security-reporoduction

_Originally posted by @mikebgrep in https://github.com/spring-projects/spring-security/issues/14410
#issuecomment-1890472477_

**Comment by kse-music** [comment]
Because in the current version, the default error request is processed by the security filter chain,see `AuthorizationFilter` 108 Line.
In the demo you give, there are two ways to solve this problem:
1. permit error request ,modify as below
   `private static final String[] WHITE_LIST_URL = { "/auth/**", "/error", "/account"};`
2. error request not handle ,use BeanPostProcessor implements
```
    @Component
    public class MyBeanPostProcessor implements BeanPostProcessor{

        @Override
        public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
            if (bean instanceof AuthorizationFilter authorizationFilter) {
                authorizationFilter.setFilterErrorDispatch(false);
            }
            return bean;
        }

    }
```

**Comment by mikebgrep** [comment]
@kse-music Thank you for the response. I will try the suggestions.
Hi, not exactly. I have a problem retrive the token as this implementation works before the update .Also, any request returns 403, even if it is without authentication in the Spring Security configuration.
I will check the suggestions tomorrow.

**Comment by mikebgrep** [comment]
@kse-music I add the example you provided, and I got an error message this time still can't retrieve the token from the login request.I add both examples. I am not sure that this supposes to fix the issue. Please take a look.

```
{
    "timestamp": "2024-01-19T08:33:51.121+00:00",
    "status": 401,
    "error": "Unauthorized",
    "message": "Full authentication is required to access this resource",
    "path": "/api/v1/auth/login"
} 
```



@marcusdacoregio I am not sure the link you share is applicable here since I can't get the token at first place to authenticate at the rest of the requests.

**Comment by mikebgrep** [comment]
@marcusdacoregio You were right appear that the implementation of the endpoints paths was the problem and the changes about the /error endpoint lead me to misunderstanding of the problem @kse-music Thank you for the answer it was help me a lot.
There was a problem also with hibernate before I log this issue so the problem was multy dimensional :100:

**Comment by mehaksaini2811** [comment]
Hello everyone, I'm facing a similar issue upon upgrading my `spring-boot-starter web` dependency from 2.6.7 to 3.2.5. I'm able to access the api from Postman but it throws a 403 (CORS 403 on OPTIONS call) when accessed from outside applications.

**Comment by hasandg** [comment]
Is it possible that you used Basic Auth on Postman etc. You used Bearer Authorization on JwtAuthenticationFilter.java file.
I had same error and I realised that I used Basic Auth, It should No Auth and Headers section Authorization "Bearer <JWT token>" or directly Bearer Token! with no Header
