### ISSUE TITLE
Support Specifying Identifier for relying-party-registrations Element

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#14487]
When using `<relying-party-registrations>` to configure a `RelyingPartyRegistrationRepository`, it would be helpful to be able to give it an identifier so that it can be referred to other custom SAML components like so:

```xml
<relying-party-registrations id="ref">
    <relying-party-registration ..../>
    <asserting-party ... />
</relying-party-registrations>

<b:bean class="org.springframework.security.saml2.provider.service.web.authentication.OpenSaml4AuthenticationRequestResolver">
    <b:constructor-arg ref="ref"/>
    <b:property ref="relayStateResolver"/>
</b:bean>

...
```

This would involve updating `RelyingPartyRegistrationsBeanDefinitionParser`, its test file, and the accompanying `.rnc` file.

Related to gh-14417

**Comment by abhishek-bafna-amdhan** [comment]
Hello @jzheaux. I noticed another issue that can be looked along with this issue (https://github.com/spring-projects/spring-security/issues/14645)

Both these issues may require changes in `RelyingPartyRegistrationsBeanDefinitionParser`. Please do have a look into the issue and provide your valuable feedback.
