### ISSUE TITLE
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain': Failed to instantiate [org.springframework.security.config.annotation.web.configuration.WebMvcSecurityConfiguration$CompositeFilterChainProxy]: Constructor threw exception

### ISSUE THREAD

**Issue by dalingjiuling** [spring-projects/spring-security#14497]
**Describe the bug**
According to the official website,[defining required components](https://docs.spring.io/spring-authorization-server/reference/getting-started.html#defining-required-components). When the annotation is set to @ enableWebSecurity (debug=true), an error occurs during project startup. error message：org.springframework.beans.factory.BeanCreationException: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain': Failed to instantiate [org.springframework.security.config.annotation.web.configuration.WebMvcSecurityConfiguration$CompositeFilterChainProxy]: Constructor threw exception.

Upon reviewing the source code, it was found that when debug=true, the returned object is DebugFilter, while when debug=false, the returned object is FilterChainProxy. When the returned object is DebugFilter, an exception is thrown when executing the findFilterChainProxy method while creating the CompositeFilterChainProxy object.
**To Reproduce**

@Configuration
@EnableWebSecurity(debug = true)
public class SecurityConfig {
......
}

**Expected behavior**
How can I start normally when @ Enabling WebSecurity (debug=true) is enabled?

**Sample**
[sample url](https://github.com/dalingjiuling/issue-example/tree/master/spring/spring-authorization-server)

**Comment by marcusdacoregio** [comment]
Hi, @dalingjiuling. Thanks for the report.

This appears to be a duplicate of https://github.com/spring-projects/spring-security/issues/14370
