### ISSUE TITLE
RestClient : interceptors are executed 2 times

### ISSUE THREAD

**Issue by rawadolb** [spring-projects/spring-security#14520]
**Describe the bug**
When RestCient is initialized by a RestTemplate using _RestClient.builder(restTemplate)_ the interceptors are executed 2 times.

**To Reproduce**
Create a RestTemplate with an interceptor (loggingInterceptor to make it simple).
Initialize a RestClient and then perform a call _restClient.get().uri(uri).retrieve().body(YourObject.class)_
LoggingInterceptor will be executed 2 times because 2 _ClientHttpRequestInterceptor_ object are created. (Please find attached)

**Expected behavior**
The interceptor must be executed once

![RestClient](https://github.com/spring-projects/spring-security/assets/36637981/2b409c3a-2513-4a5c-a82a-8424c440a7c0)

**Comment by marcusdacoregio** [comment]
Hi, @rawadolb. `RestClient` is from Spring Framework and not from Spring Security, you will find better support by opening an issue in [their issue tracker](https://github.com/spring-projects/spring-framework/issues).
