### ISSUE TITLE
Filter order documentation appears to be inconsistent

### ISSUE THREAD

**Issue by jpmsilva** [spring-projects/spring-security#14531]
**Describe the bug**
The order of the security filters is documented at [org.springframework.security.config.annotation.web.HttpSecurityBuilder#addFilter](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/annotation/web/HttpSecurityBuilder.html#addFilter(jakarta.servlet.Filter)), but that order does not appear to be consistent with what the actual code at [org.springframework.security.config.annotation.web.builders.FilterOrderRegistration#FilterOrderRegistration](https://github.com/spring-projects/spring-security/blob/af2d210ccb62a00374983ff276e1a16e5773b130/config/src/main/java/org/springframework/security/config/annotation/web/builders/FilterOrderRegistration.java#L71) does.
Notice, for instance, that the order of  `ForceEagerSessionCreationFilter` and `DisableEncodeUrlFilter` are switched between the documentation and the actual code.

**Comment by jpmsilva** [comment]
Quick comment regarding the PR #14533: I mentioned the order of `ForceEagerSessionCreationFilter` and `DisableEncodeUrlFilter` merely as an example. There are other inconsistencies between the documentation and the actual implementation.

WebAsyncManagerIntegrationFilter, SecurityContextHolderFilter, HeaderWriterFilter, CorsFilter, CsrfFilter, OAuth2AuthorizationRequestRedirectFilter, Saml2WebSsoAuthenticationRequestFilter, OAuth2LoginAuthenticationFilter, Saml2WebSsoAuthenticationFilter, OAuth2AuthorizationCodeGrantFilter, AuthorizationFilter are missing from the documentation.

**Comment by marcusdacoregio** [comment]
Closing in favor of https://github.com/spring-projects/spring-security/pull/14552
