### ISSUE TITLE
SEC-1211: Create strategy for session handling on successful authentication

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1454]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1211](https://jira.spring.io/browse/SEC-1211?redirect=false)) said:

The code for session-fixation protection is currently duplicated between the AbstractAuthenticationProcessingFilter and the SessionFixationProtectionFilter. The former deals needs to create a new session before it redirects to the required target, the latter handles authentication which has occurred during the current request.

A strategy implementation could be shared between them and also deal with updating the session registry, deciding what attributes to migrate etc.

**Comment by spring-issuemaster** [comment]
This issue supersedes #1328
This issue supersedes #1301
