### ISSUE TITLE
SEC-1226: Introduce RedirectStrategy to replace RedirectUtils

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1461]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1226](https://jira.spring.io/browse/SEC-1226?redirect=false)) said:

All classes which perform redirects should be able to customize the way the redirection URL is built, to make working with proxies etc easier.

**Comment by spring-issuemaster** [comment]
This issue supersedes #1405
