### ISSUE TITLE
Prepost annotation on entity field with Spring-EL expression no longer works on repository interface in 3.2.2

### ISSUE THREAD

**Issue by Jef-VDD** [spring-projects/spring-security#14637]
**Describe the bug**
When adding an `@PreAuthorize` annotation to my repository interface that checks certain entity fields the following error occurs even when the entity is not null :
`org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field '*fieldName*' cannot be found on null`

**To Reproduce**
Create repository with `@PreAuthorize` annotation and perform check on any entity field.

**Expected behavior**
Authorization on fields is possible and throws the AccessDeniedException when pre authorize fails

**Sample**
Demo project with 2 tests that execute an authorization that should fail and an authorization that should work
https://github.com/Jef-VDD/spel-demo

**Extra info**
This appears to be working when running with versions of _org.springframework:spring-aop_ of 6.1.2 or lower. If this is not an issue with _spring-security_ feel free to close this ticket and I will try to move my issue to the correct project (I assume either [spring-expression](https://github.com/spring-projects/spring-framework/tree/main/spring-expression) or [spring-aop](https://github.com/spring-projects/spring-framework/tree/main/spring-aop))

If related to [Spring AOP does not propagate arguments for dynamic prototype-scoped advice](https://github.com/spring-projects/spring-framework/issues/31963) I will upgrade when possible!

**Comment by kse-music** [comment]
It looks like this issue has been fixed by this [commit](https://github.com/spring-projects/spring-framework/commit/5656eaccb7245b8a3799529bc774dee907ece4d1)

**Comment by jzheaux** [comment]
Thanks for the report, @Jef-VDD! This appears to have been fixed already in Spring Framework, as @kse-music indicated. When I update your application to use `<spring-framework.version>6.1.4</spring-framework.version>`, the tests pass again.

As I check against future issues, I've added a test in https://github.com/spring-projects/spring-security/commit/c639d0a5143f99ea541e351800069cb807f42c0f
