### ISSUE TITLE
Link in the In-Memory Authentication documentation is wrong

### ISSUE THREAD

**Issue by lukasdo** [spring-projects/spring-security#14688]
The link to "accept a username and password" on the page [In-Memory Auth](https://docs.spring.io/spring-security/reference/servlet/authentication/passwords/in-memory.html) does not work. The issue seems to be that the link references a section in another doc.

Suggestion as stated in the [docs](https://docs.asciidoctor.org/asciidoc/latest/macros/inter-document-xref/) a solution could be using an inter-document xref.

**Comment by marcusdacoregio** [comment]
Closing in favor of https://github.com/spring-projects/spring-security/pull/14689
