### ISSUE TITLE
Ask Connect2id for a BOM containing their product versions

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-security#14696]
We should open a ticket on [Connect2id's issue tracker](https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions) requesting a creation of a BOM containing all compatible versions of their products, that would allow us to seamlessly update the dependency versions avoid problems as seem in the related issues

Related:
- https://github.com/spring-projects/spring-security/issues/13843
- https://github.com/spring-projects/spring-security/issues/14245

**Comment by marcusdacoregio** [comment]
https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/issues/463/provide-a-bom-containing-the-compatible

**Comment by xak2000** [comment]
@marcusdacoregio So what is the result of the request? :)

The linked page just shows:

> This issue is submitted and being reviewed.

without any details.

I'm not sure why is it. Maybe Bitbucket hides closed issues from non-members of the project? Strange..

**Comment by marcusdacoregio** [comment]
Looks like I don't have access to it anymore too. I'll investigate what happened.
