### ISSUE TITLE
Mention all required dependencies in LDAP documentation

### ISSUE THREAD

**Issue by Harsh4902** [spring-projects/spring-security#14699]
**Expected Behavior**

- I think we should mention all the required dependencies in this documentation so it will be more helpfull.

**Current Behaviour**

- There is no mention of `spring-security-ldap` dependency in [this](docs/modules/ROOT/pages/servlet/authentication/passwords/ldap.adoc) document, though it is required.

**Context**

- I was trying to do basic LDAP setup and going through this documentation I added some dependencies, but I was not aware about to add `spring-security-ldap`.  This thing put me in trouble, and then I had to go through some other blogs and videos. So it's my suggestion to add all the required dependencies so it can be easy for users.

**Comment by jzheaux** [comment]
I agree, @Harsh4902. Would you be able to contribute a PR that adds it to [this section](https://docs.spring.io/spring-security/reference/servlet/authentication/passwords/ldap.html#servlet-authentication-ldap-embedded)?

**Comment by Harsh4902** [comment]
@jzheaux Sure I will raise a PR for this issue. Give me some time, thank you.

**Comment by Harsh4902** [comment]
@jzheaux Can I describe required dependencies in `Prerequisites` section of [this](https://docs.spring.io/spring-security/reference/servlet/authentication/passwords/ldap.html#servlet-authentication-ldap-prerequisites) document?

**Comment by jzheaux** [comment]
@Harsh4902, sorry that I missed your message. I think it would be better in https://docs.spring.io/spring-security/reference/servlet/authentication/passwords/ldap.html#servlet-authentication-ldap-embedded or in a new section in between the two. The `PreRequisites` section seems to be more about architectural groundwork.
