### ISSUE TITLE
SEC-1224: BasicLookupStrategy, JdbcAclService, and JdbcMutableAclService should support Catalog and Schema

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1475]
[Stephen M. Kennedy](https://jira.spring.io/secure/ViewProfile.jspa?name=kennedyz) (Migrated from [SEC-1224](https://jira.spring.io/browse/SEC-1224?redirect=false)) said:

Some systems may have security objects and normal application objects seperated in to different domains, and those domains may be defined in different database catalogs and/or schemas.

The BasicLookupStrategy, JdbcAclService, and JdbcMutableAclService classes should account for a database catalog and schema.  A developer and/or integrator should be able to specify the catalog and schema for said classes when defining the beans in their context configurations.

**Comment by spring-issuemaster** [comment]
This issue duplicates #1178
