### ISSUE TITLE
Refactoring Test Code to Reduce Duplication of Mock Object Creation

### ISSUE THREAD

**Issue by gzhao9** [spring-projects/spring-security#14768]
Dear Spring Security Developers,

I have been reviewing your test code and noticed an issue with repeated creation of mock objects in your tests. Here are four examples where this occurs:

## Example 1

This example is found in [ActiveDirectoryLdapAuthenticationProviderTests](https://github.com/spring-projects/spring-security/blob/0078462e410eefbe27b3550f88fba058231f45bb/ldap/src/test/java/org/springframework/security/ldap/authentication/ad/ActiveDirectoryLdapAuthenticationProviderTests.java#L4).
The repeated code fragment is as follows:
```java
DirContext ctx = mock(DirContext.class);
given(ctx.getNameInNamespace()).willReturn("");
```
The issue with this code is that `willReturn("")` is unnecessary because Mockito defaults the return of `String` methods to `""`. This piece of code is used 18 times across 8 test cases.
Thus, I propose the following solution:

1. Remove `given(ctx.getNameInNamespace()).willReturn("");`
2. Move `DirContext ctx = mock(DirContext.class);` to `@BeforeEach`

This change reduces the code by 16 lines. I have created a [Draft PR](https://github.com/gzhao9/spring-security/pull/1), and you can view the changes [here](https://github.com/gzhao9/spring-security/pull/1/files).

## Example 2

This code is repeated in 8 test cases across 3 test classes:

- [AuthorizationManagerAfterMethodInterceptorTests](https://github.com/spring-projects/spring-security/blob/0078462e410eefbe27b3550f88fba058231f45bb/core/src/test/java/org/springframework/security/authorization/method/AuthorizationManagerAfterMethodInterceptorTests.java)

- [AuthorizationManagerBeforeMethodInterceptorTests](https://github.com/spring-projects/spring-security/blob/0078462e410eefbe27b3550f88fba058231f45bb/core/src/test/java/org/springframework/security/authorization/method/AuthorizationManagerBeforeMethodInterceptorTests.java)

- [PostFilterAuthorizationMethodInterceptorTests](https://github.com/spring-projects/spring-security/blob/0078462e410eefbe27b3550f88fba058231f45bb/core/src/test/java/org/springframework/security/authorization/method/PostFilterAuthorizationMethodInterceptorTests.java)

The repeated code is as follows:
```java
SecurityContextHolderStrategy strategy = mock(SecurityContextHolderStrategy.class);
// other statements
given(strategy.getContext()).willReturn(new SecurityContextImpl(authentication));
```

The creation and given content of `SecurityContextHolderStrategy` mocks are very similar each time, except for the return value.
My solution is to create a `MockSecurityContextHolderStrategy` function, which is called each time a mock is needed:
```java
public class MockSecurityContextHolderStrategy {
    static SecurityContextHolderStrategy getmock(SecurityContextImpl securityContextImpl){

        SecurityContextHolderStrategy strategy = mock(SecurityContextHolderStrategy.class);
        given(strategy.getContext()).willReturn(securityContextImpl);
        return strategy;
    }
}
```
The code after calling it would look like this:
```java
SecurityContextHolderStrategy strategy = MockSecurityContextHolderStrategy.getmock(new SecurityContextImpl(authentication));
```

I have created a [Draft PR](https://github.com/gzhao9/spring-security/pull/2), and you can view the changes [here](https://github.com/gzhao9/spring-security/pull/2/files).

## Example 3

Similar to Example 2, I found repetition in the test class [ConcurrentSessionFilterTests](https://github.com/spring-projects/spring-security/blob/0078462e410eefbe27b3550f88fba058231f45bb/web/src/test/java/org/springframework/security/web/concurrent/ConcurrentSessionFilterTests.java) when creating mocks for `SessionRegistry` as follows:
```java
SessionRegistry registry = mock(SessionRegistry.class);
SessionInformation information = new SessionInformation("user", "sessionId",
        new Date(System.currentTimeMillis() - 1000));
information.expireNow();
given(registry.getSessionInformation(anyString())).willReturn(information);
```
This repetition occurs in 6 test cases.

My solution is to create a `mockSessionRegistry`:
```java
private SessionRegistry mockSessionRegistry(){
    SessionRegistry registry = mock(SessionRegistry.class);
    SessionInformation information = new SessionInformation("user", "sessionId",
            new Date(System.currentTimeMillis() - 1000));
    information.expireNow();
    given(registry.getSessionInformation(anyString())).willReturn(information);
    return registry;
}
```
To create a `SessionRegistry`, simply call as follows:
```java
ConcurrentSessionFilter filter = new ConcurrentSessionFilter(mockSessionRegistry());
```

I have created

 a [Draft PR](https://github.com/gzhao9/spring-security/pull/3), and you can view the changes [here](https://github.com/gzhao9/spring-security/pull/3/files).

## Example 4

This repetition occurs in [ExceptionTranslationFilterTests](https://github.com/spring-projects/spring-security/blob/0078462e410eefbe27b3550f88fba058231f45bb/web/src/test/java/org/springframework/security/web/access/ExceptionTranslationFilterTests.java) with the following code:
```java
FilterChain fc = mock(FilterChain.class);
willThrow(new BadCredentialsException("")).given(fc)
    .doFilter(any(HttpServletRequest.class), any(HttpServletResponse.class));
```
This occurs in 8 different test cases, each returning a different `Exception`.

My solution is to create a method `mockFilterChainWithException` that takes different `Exception`s as parameters:
```java
private FilterChain mockFilterChainWithException(Object exception) throws ServletException, IOException {
    FilterChain fc = mock(FilterChain.class);
    willThrow((Throwable) exception).given(fc).doFilter(any(HttpServletRequest.class), any(HttpServletResponse.class));
    return fc;
}
```

To create a `FilterChain` mock, call it like this:
```java
FilterChain fc = mockFilterChainWithException(new BadCredentialsException(""));
```

I have created a [Draft PR](https://github.com/gzhao9/spring-security/pull/4), and you can view the changes [here](https://github.com/gzhao9/spring-security/pull/4/files).

---

These are the four instances of repeated mock test code I found, along with my solutions for refactoring the test code. I believe these changes will 

1. reduce the LOC for each test case
2. allowing tests to focus more on testing rather than on recreating objects. 
3. Most importantly, consolidating repetitive parts improves code maintainability.

Dear Spring Security developers, Do you like the solution proposed in the issue? I'm very much looking forward to your response, and I'm ready to start submitting PRs if you're interested. If you have any suggestions for improvements, I would greatly appreciate them.

**Comment by jzheaux** [comment]
Thank you for your effort @gzhao9 to simplify these tests! To accelerate the review process, will you please instead open a PR to [the main repository](https://github.com/spring-projects/spring-security/compare) and I'll take a look?

**Comment by gzhao9** [comment]
> Thank you for your effort @gzhao9 to simplify these tests! To accelerate the review process, will you please instead open a PR to [the main repository](https://github.com/spring-projects/spring-security/compare) and I'll take a look?


Thank you very much for your reply. I have submitted PR #15256. Please review it at your convenience.

I apologize for the delayed response as I've been occupied with some real-life matters over the past two months. I'm now back and actively engaged.
