### ISSUE TITLE
SEC-1233: Remove NTLM support

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1481]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1233](https://jira.spring.io/browse/SEC-1233?redirect=false)) said:

NTLM support will not be continued in Spring Security 3.0. Mike Wiesner has been working on a kerberos solution and we feel that we would be better to put our resources into that rather than into NTLM. The kerberos module is part of the new Security Extensions project:

http://jira.springsource.org/browse/SES

**Comment by spring-issuemaster** [comment]
This issue supersedes #1340
This issue supersedes #1254
