### ISSUE TITLE
Documentation images should render clearly in both light and dark mode

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-security#14834]
Tried this in both opera, opera incognito, and chromium (which I never use (maybe ever on this computer)). I doubt this is limited to spring security, but I'm not certain how spring generates its documentation.

![Screenshot from 2024-04-03 06-13-51](https://github.com/spring-projects/spring-security/assets/5517/25d8992b-384b-45e6-a9c7-d878497de5d4)

**Comment by jzheaux** [comment]
Thanks, @xenoterracide, I wonder if this is due to the images using a transparent instead of white background. I'll take a look.

**Comment by jzheaux** [comment]
Related https://github.com/spring-io/antora-ui-spring/issues/229
