### ISSUE TITLE
Documentation links for 5.x are broken

### ISSUE THREAD

**Issue by zemian** [spring-projects/spring-security#14830]
All the docs for 5.x series seems to show "Page Not Found" error.

https://docs.spring.io/spring-security/reference/5.8/whats-new.html

**Comment by void-spark** [comment]
Everything but the 'last' version seems missing, almost all links from https://spring.io/projects/spring-security#learn are broken.

**Comment by marcusdacoregio** [comment]
Thanks for the report, I'm looking into it.

**Comment by marcusdacoregio** [comment]
Thanks again for the report. It has been fixed now. The cause was [this commit](https://github.com/spring-projects/spring-security/commit/3bf79cc70cec20cdde34da9e9b95570cc5f6d12c).
