### ISSUE TITLE
Wrong information for RequestCacheAwareFilter in the Spring Security documentation.

### ISSUE THREAD

**Issue by angel-gruevski** [spring-projects/spring-security#14855]
The documentation for Spring Security, section Servlet Architecture -> Architecture mentions the following: 
 "The RequestCacheAwareFilter uses the RequestCache to save the HttpServletRequest." 
The statement above is incorrect, because the RequestCacheAwareFilter uses the RequestCache to get the saved HttpServletRequest after the user authenticates, while the ExceptionTranslationFilter uses the RequestCache to save the HttpServletRequest after the user requested protected resource in an unauthenticated request.

https://docs.spring.io/spring-security/reference/servlet/architecture.html#requestcacheawarefilter

**Comment by jzheaux** [comment]
Fair point, @angel-gruevski. Are you able to submit a PR, correcting the documentation?

**Comment by angel-gruevski** [comment]
Yes, I've just submitted a PR https://github.com/spring-projects/spring-security/pull/14860

**Comment by marcusdacoregio** [comment]
Closing in favor of https://github.com/spring-projects/spring-security/pull/14860
