### ISSUE TITLE
The continueOnError value is inconsistent with that described in the java doc

### ISSUE THREAD

**Issue by kse-music** [spring-projects/spring-security#14870]
**Describe the bug**
The code line [setContinueOnError](https://github.com/spring-projects/spring-security/blame/main/web/src/main/java/org/springframework/security/web/server/authentication/DelegatingServerAuthenticationConverter.java#L68)
The default value of continueOnError is false, but the java doc describes the default value as true

**Comment by marcusdacoregio** [comment]
Closed in favor of https://github.com/spring-projects/spring-security/pull/14871
