### ISSUE TITLE
Allow customization of redirect strategy in `CasAuthenticationEntrypoint`

### ISSUE THREAD

**Issue by kakawait** [spring-projects/spring-security#14881]
**Expected Behavior**

Allow more customization or inheritance for `CasAuthenticationEntrypoint`

**Current Behavior**

`CasAuthenticationEntrypoint` has `final` keyword on 

```java
@Override
public final void commence(final HttpServletRequest servletRequest, HttpServletResponse response,
		AuthenticationException authenticationException) throws IOException {
...
}
```

that prevent developer to change behavior.

If removing `final` isn't acceptable, otherwise allow changing hardcoded `new DefaultRedirectStrategy()` inside `commence` to allow injecting `RedirectStrategy` inside _constructor_

**Context**

Allow developer to apply different strategy without having copying `CasAuthenticationEntrypoint`, could resolve #3123 for example

---

I'm totally ok to propose a PR, but I'd like to get validation that is something acceptable

**Comment by rishiraj88** [comment]
Looks like a nice suggestion. Flexibility should be favoured unless there is a strong blocker.

**Comment by marcusdacoregio** [comment]
Thanks for the report @kakawait. I've repurposed the ticket to allow customization of the redirect strategy if you are okay with it.
