### ISSUE TITLE
Documentation links for 6.2 are broken

### ISSUE THREAD

**Issue by ClausMie** [spring-projects/spring-security#14897]
**Describe the bug**
Links for reference documentation version 6.2, such as https://docs.spring.io/spring-security/reference/6.2/index.html, end in 404 Page Not Found.

**Expected behavior**
As with other versions, I expect to see the reference documentation of the latest 6.2 release and not a 404.
For versions not currently the `current` version, say exchange the 6.2 for 6.1 for example, you will get to the reference documentation of the latest release of that version.

**Comment by marcusdacoregio** [comment]
Hi, @ClausMie. I believe that the since 6.2 is the current version it is not indexed that way by antora, @rwinch can you confirm that?

Do you remember where did you find the link in that format? Or did you replaced another version by 6.2?

**Comment by sjohnr** [comment]
Hi @ClausMie. We have worked through improvements to Antora docs and I believe this is now resolved. The [link](https://docs.spring.io/spring-security/reference/6.2/index.html) in your issue comment now works. I'm going to close this as resolved, but let me know if you see any other issues.
