### ISSUE TITLE
ProxyRestrictionConditionValidator is missing in the OpenSaml4AuthenticationProvider.SAML20AssertionValidators class

### ISSUE THREAD

**Issue by ek-ma** [spring-projects/spring-security#14931]
**Error**
An error is triggered when trying to validate an Assertion that contains a ProxyRestriction as one of its conditions. The following error is displayed : 
`Invalid assertion [xxx] for SAML response [xxx]: Unknown Condition '{urn:oasis:names:tc:SAML:2.0:assertion}ProxyRestriction' of type 'null' in assertion 'xxx'`

It may be due to the fact that the conditions present in the OpenSaml4AuthenticationProvider.SAML20AssertionValidators do not include the ProxyRestrictionConditionValidator.

**Expected behavior**
The expected behavior is to have all of the conditions 

Thanks,

**Comment by jzheaux** [comment]
Thanks for the report, @ek-ma! This is now merged and will go out in the next maintenance release.
