### ISSUE TITLE
SEC-1246: Introduce EL-based authorization tag

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1494]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1246](https://jira.spring.io/browse/SEC-1246?redirect=false)) said:

The use of a tag which uses something like <authorize access="some access-control expression" /> and links in with the WebSecurityExpressionHandler in the application context would provide all the functionality of the existing authorize tag and much more. The implementation could extend the existing tag to continue to support the legacy syntax.

**Comment by spring-issuemaster** [comment]
This issue supersedes #1136
