### ISSUE TITLE
AnonymousConfigurer not work using Custom DSL

### ISSUE THREAD

**Issue by shihyuho** [spring-projects/spring-security#14941]
I'm using

- Spring Boot 3.2.5
- Spring Security 6.2.4

**Describe the bug**

While playing around with [Custom DSL](https://docs.spring.io/spring-security/reference/servlet/configuration/java.html#jc-custom-dsls), I noticed adding an anonymous configurer does not work

**To Reproduce**

```java
@Configuration
@EnableWebSecurity
public class Config {
  @Bean
  public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
    return http
      .with(new MyCustomDsl(), withDefaults())
      .build();
  }
}

public class MyCustomDsl extends AbstractHttpConfigurer<MyCustomDsl, HttpSecurity> {

  @Override
  public void init(HttpSecurity http) throws Exception {
    http.anonymous(anonymous -> anonymous.principal("myAnonymousUser"));
  }
}
```

**Expected behavior**

I expected the anonymous principal to be `myAnonymousUser`, but the actual result was `anonymousUser`, which is the default name set by [AnonymousConfigurer](https://github.com/spring-projects/spring-security/blob/main/config/src/main/java/org/springframework/security/config/annotation/web/configurers/AnonymousConfigurer.java#L52).

**Sample**

https://github.com/shihyuho/anonymous-configurer-issue

**Additional Notes**

Upon tracing the code, the reason appears to be:

In [HttpSecurityConfiguration](https://github.com/spring-projects/spring-security/blob/main/config/src/main/java/org/springframework/security/config/annotation/web/configuration/HttpSecurityConfiguration.java#L123), `.anonymous(withDefaults())` is already set once when creating `HttpSecurity` instance, and in the `init` method of [AnonymousConfigurer](https://github.com/spring-projects/spring-security/blob/main/config/src/main/java/org/springframework/security/config/annotation/web/configurers/AnonymousConfigurer.java#L147-L150), the `authenticationFilter` is initialized.

As a result, although the `principal` can still be changed later with custom DSL, the filter is not recreated, which prevents the changes from taking effect.

**Comment by kse-music** [comment]
I think to modify the added `Configurer`, you need to modify it before building like so

```
  @Bean
  public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
    return http
      .anonymous(anonymous -> anonymous.principal("myAnonymousUser"))
      .with(new MyCustomDsl(), withDefaults())
      .build();
  }
```

**Comment by shihyuho** [comment]
> I think to modify the added `Configurer`, you need to modify it before building like so
> 
> ```
>   @Bean
>   public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
>     return http
>       .anonymous(anonymous -> anonymous.principal("myAnonymousUser"))
>       .with(new MyCustomDsl(), withDefaults())
>       .build();
>   }
> ```

Thank you for your suggestion @kse-music , but this is not what I am looking for. The [document](https://docs.spring.io/spring-security/reference/servlet/configuration/java.html#jc-custom-dsls) mentions that it is possible to add other configurators to a custom DSL. 

![image](https://github.com/spring-projects/spring-security/assets/2764992/f6bdb1f7-1646-4f3f-9f33-229843a2a67c)

Therefore, I'm planning to design some custom DSLs targeted at our common scenarios, providing a quick configuration to build HttpSecurity for developers

**Comment by kse-music** [comment]
If the init method of the custom `Configurer `supports modifying the configuration of the `Configurer `that has been added to `HttpSecurity`, can I understand that because the custom `Configurer `is initialized last, it will cause inconsistency of the behavior in the init method and the configure method. For example like so:

```
  @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        return http
                .with(new MyCustomDsl(), withDefaults())
                .build();
    }

    static class MyCustomDsl extends AbstractHttpConfigurer<MyCustomDsl, HttpSecurity> {

        @Override
        public void init(HttpSecurity http) throws Exception {
            http.sessionManagement(c -> c.enableSessionUrlRewriting(true).sessionCreationPolicy(SessionCreationPolicy.STATELESS));
        }

    }
```

When the `SessionManagementConFigurer `initializes, the variable enableSessionUrlrewroting = false, sessionPolicy = if_required in init method, but the variable enableSessionUrlrewroting = true, sessionPolicy = STATELESS in configure method.

I think there are still some  `Configurer ` like this
