### ISSUE TITLE
SEC-1250: RequestHeaderPreAuthenticatedProcessingFilter cannot be use to fail back to another authentication type

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1500]
[Clement OUDOT](https://jira.spring.io/secure/ViewProfile.jspa?name=coudot) (Migrated from [SEC-1250](https://jira.spring.io/browse/SEC-1250?redirect=false)) said:

Hello,

I use preauth to get connected user through an HTTP header. This works fine, but I would like to ba able to failback to another authentication method if no header is present. The goal is to be able to manage user's connected with the WebSSO and other accessing the application in direct.

There is no security problems because we manage different virtualhost to protect the webapp (one wirtualhost is handled by the WebSSO, another checks that the user do not forge its own headers and connects directly to the webapp).

I join a class that we made to extend RequestHeaderPreAuthenticatedProcessingFilter, but I think this could be nice to have a parameter like "ContinueWithoutHeader", that will be false by default.

We can provide any help to solve this.

Thank you,

Clément.

**Comment by spring-issuemaster** [comment]
This issue is related to #1499
