### ISSUE TITLE
RelyingPartyRegistrations does not verify signatures

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-security#15018]
**Describe the bug**
When an `EntitiesDescriptor`, `EntityDescriptor`, or `IDPSSODescriptor` is being parsed, any included `Signature`s must be verified against a supplied trust store. This is especially critical if the metadata is fetched over an insecure channel. However, the methods in `RelyingPartyRegistrations` do not do this. Nor is it clear how someone might do it after the fact.

The underlying OpenSaml library provides all the necessary functionality. Spring Security just needs to call it. The now unsupported [spring-security-saml](https://github.com/spring-attic/spring-security-saml) does this correctly.

**To Reproduce**
The current API does not provide any way to provide trust material, even if it tried to verify signatures.

**Expected behavior**
See above.

**Additional Information**
This may qualify as a security issue, if people were expecting the previous behaviour of SAML metadata being cryptographically verified.

**Comment by OrangeDog** [comment]
Indeed, there's a big warning in the OpenSAML documentation against the design of spring-security-saml-provider:

> It is very dangerous to attempt to use parts of the library in isolation without making use of all of its relevant components. In particular, implementing your own XML processing code, using XML parsing classes other than the ParserPool components provided by the library, using your own security processing code, omitting proper support for SAML metadata, etc. are all risky choices that may lead to security flaws and incomplete, unsafe, and ill-advised SAML solutions. The Shibboleth Project discourages such approaches in the strongest possible terms. Use all of it that applies to the task at hand, or use none of it.

**Comment by OrangeDog** [comment]
A safer approach is to have OpenSAML do the fetch and validation together, as the previous extension did.

Some example configuration:

```java
@Bean(initMethod = "initialize", destroyMethod = "destroy")
public BasicParserPool parserPool() {
    return new BasicParserPool();
}

@Bean
public HttpClient httpClient() {
    return new net.shibboleth.utilities.java.support.httpclient.HttpClientBuilder().buildClient();
}

@Bean
public MetadataFilter metadataFilter(SignatureTrustEngine trustEngine) {
    MetadataFilter roleFilter = new EntityRoleFilter(List.of(IDPSSODescriptor.DEFAULT_ELEMENT_NAME));
    SignatureValidationFilter validationFilter = new SignatureValidationFilter(trustEngine);
    validationFilter.setRequireSignedRoot(METADATA_URI.getScheme().equals("http"));
    validationFilter.setSignaturePrevalidator(new SAMLSignatureProfileValidator());
    MetadataFilterChain filterChain = new MetadataFilterChain();
    filterChain.setFilters(List.of(validationFilter, roleFilter));
    return filterChain;
}

@Bean(initMethod = "initialize", destroyMethod = "destroy")
public HTTPMetadataResolver metadataResolver(HttpClient httpClient) {
    HTTPMetadataResolver resolver = new HTTPMetadataResolver(httpClient, METADATA_URI.toString());
    resolver.setId("default");
    resolver.setRequireValidMetadata(true);
    return resolver;
}
```

You then need an adaptor to expose the resulting `EntityDescriptor`s to Spring Security.

**Comment by jzheaux** [comment]
Thanks for the report and the suggested changes. Since this is connected with [an earlier ticket](https://github.com/spring-projects/spring-security/issues/12116), I'll close this as a duplicate and continue from there.
