### ISSUE TITLE
Prevent incorrect merges between branches

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-security#15028]
Recently, a wrong merge happened from `main` into `6.2.x`, since the merge was a fast-forward it went unnoticed until a contributor reported it in https://github.com/spring-projects/spring-security/issues/15016. The result was that `6.2.x` was synced with `main`.

We should prevent it from happening again, a few suggestions are:

 - A Gradle task that checks if we are in a branch that matches `*.x` and then compare it with the `version` in `gradle.properties`. The `check` task would depend on this new task.
 - A pre-commit hook that does the same as above
 - A CI task/workflow that does the same as above
 - Use no fast-forward option (`--no-ff`), this will create a merge commit even when a fast-forward is possible, making it easier to spot the mistake

**Comment by sjohnr** [comment]
@marcusdacoregio I like the pre-commit hook idea as a possible solution. The issue with workflows is that it would be too late to prevent it, right? The gradle task is nice too but it's technically optional to run it locally and can be skipped.

**Comment by marcusdacoregio** [comment]
Closed via https://github.com/spring-projects/spring-security/wiki/Working-with-Git-branches
