### ISSUE TITLE
jpms spring-security-rsa

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-security#15035]
please add jpms support, at least automatic modules for now. However, this issue or another issue should be added for full module-info at sometime in the future. Referencing this upstream spring issue (specifically comment) which shows all of the dependencies that could be included via the code generator https://github.com/spring-projects/spring-framework/issues/18079#issuecomment-2087396680

**Comment by sjohnr** [comment]
@xenoterracide thanks for reaching out!

> please add jpms support

This and the accompanying paragraph in this comment is not enough information. Please provide sufficient context and information on this issue for it to be easily understood by others. What is JPMS support? What benefits will it provide? What steps or follow-up might be required for full support?

Also, I want to point out we will likely wait to move on anything related to this until the framework team prioritizes the issue you linked, which doesn't seem to be case right now.

**Comment by xenoterracide** [comment]
Java platform module system? Is what I believe it stands for... Honestly I'd have to double check that acronym. 

I would assume that you've read the ticket I referenced?

All you need to provide right now is an automatic module name so people trying to use this module can compile against it If they enable jpms by setting up their own module info. From the looks of it all of the other spring security modules already provide an automatic module name. I assume that this one was an oversight when it got pulled into this repo recently.

**Comment by sjohnr** [comment]
> From the looks of it all of the other spring security modules already provide an automatic module name. I assume that this one was an oversight when it got pulled into this repo recently.

Thanks @xenoterracide, that is indeed helpful context.

**Comment by sjohnr** [comment]
Related gh-14202

**Comment by marcusdacoregio** [comment]
Hi, @xenoterracide. `spring-security-rsa` is not a standalone module anymore, its API is part of `spring-security-crypto` now. Therefore you can rely on the automatic module name from `spring-security-crypto`. See https://docs.spring.io/spring-security/reference/6.3-SNAPSHOT/whats-new.html#_spring_security_rsa_is_now_part_of_spring_security_14202

**Comment by xenoterracide** [comment]
ok, so the list provided in the comment where this is in "red" no longer applies? just double verifying as that shows it as a dependency. As long a future version this will not be "red" I'm happy ;) .

**Comment by marcusdacoregio** [comment]
Yes, it has been migrated to `spring-security-crypto` in 6.3 and that module is yellow.

**Comment by xenoterracide** [comment]
Thanks for verifying
