### ISSUE TITLE
SEC-1277: The authorization tag libraries are totally wrong!

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1504]
[vincent lee](https://jira.spring.io/secure/ViewProfile.jspa?name=daquan198163) (Migrated from [SEC-1277](https://jira.spring.io/browse/SEC-1277?redirect=false)) said:

<security:authorize ifAllGranted="ROLE_SUPERVISOR">
<td>
  <a href="del.htm?id=<c:out value="${contact.id}"/>">Del</a>
</td>
/security:authorize

I think it is more reasonable to protect a resource like this：
<security:authorize ifAllAuthorised="*del*.htm">
<td>
  <a href="del.htm?id=<c:out value="${contact.id}"/>">Del</a>
</td>
/security:authorize

Because the relationship between resources and roles may change in the future,
even more,the role name may change.

**Comment by spring-issuemaster** [comment]
This issue duplicates #787
