### ISSUE TITLE
spring-security/docs/modules/ROOT/pages/servlet/authorization /method-security

### ISSUE THREAD

**Issue by douxiaofeng99** [spring-projects/spring-security#15045]
**Describe the bug**
In the method-security document,  the Enabling Certain Annotations, should use AuthorizationManagerAfterMethodInterceptor.

```
@Configuration
@EnableMethodSecurity(prePostEnabled = false)
class MethodSecurityConfig {
	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	Advisor postAuthorize() {
		return AuthorizationManagerBeforeMethodInterceptor.postAuthorize();
	}
}
```

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
<img width="1131" alt="image" src="https://github.com/spring-projects/spring-security/assets/16471638/ecfe8ee8-8168-4ecd-a75a-8976a70742bb">

At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by sjohnr** [comment]
@douxiaofeng99 thanks for the report. Would you like to submit a PR to fix the docs?

**Comment by douxiaofeng99** [comment]
summited a PR to fix the docs
