### ISSUE TITLE
Clarify the behavior of Concurrent Session Management when an IdP is involved

### ISSUE THREAD

**Issue by jsantana3c** [spring-projects/spring-security#15071]
**Expected Behavior**

the current tutorial for spring concurrent session management says it works out of the box with OAuth:
https://docs.spring.io/spring-security/reference/6.3-SNAPSHOT/reactive/authentication/concurrent-sessions-control.html

but it seems to not be clear about what happens for logout, the code isn't proceeding with an RP-Initiated Logout / Back Channel logout, which seems that needs to be done manually somehow? 

**Current Behavior**
when using the **InvalidateLeastUsedServerMaximumSessionsExceededHandler**, the logout on the application works properly, but when logging in back, the redirect to the IDP (Spring Authorization Server in my case) is still logged in (even though the IDP implements the same 1 session concurrency).

**Context**
**How has this issue affected you?**
isn't possible to logout from IDP, even when the IDP has already the concurrent session to 1, because the filter isn't applied on OAuth server matchers? 
**What are you trying to accomplish?**
logout in both application & IDP
**What other alternatives have you considered?**
writing myself an OidcBackChannelLogoutWebFilter / ConcurrentSessionControlServerAuthenticationSuccessHandler

**Are you aware of any workarounds?**
not as of now

**Comment by marcusdacoregio** [comment]
Hi, @jsantana3c. Have you tried creating a `ServerAuthenticationSuccessHandler` that invokes `OidcClientInitiatedServerLogoutSuccessHandler`? I think that would solve the issue for you.

I wonder if we should configure it automatically if the application uses concurrent sessions and OIDC Logout. What do you think @sjohnr?

**Comment by joaquinjsb** [comment]
> Hi, @jsantana3c. Have you tried creating a `ServerAuthenticationSuccessHandler` that invokes `OidcClientInitiatedServerLogoutSuccessHandler`? I think that would solve the issue for you.
> 
> 
> 
> I wonder if we should configure it automatically if the application uses concurrent sessions and OIDC Logout. What do you think @sjohnr?

Where should I implement it? In my IDP or on the Application ? I tried adding to my filter chain of the Auth server a session management of 1 but no luck

**Comment by marcusdacoregio** [comment]
You will add it to your OAuth2 Client configuration since it's where the OIDC Logout will be initiated.

**Comment by jsantana3c** [comment]
that's the workaround I wanted to do, take the code of the session concurrency control, when the concurrent sessions have reached my parameter on the ServerAuthenticationSuccessHandler, i logout one, but that is like duplicating the session management in my code, one for session, and one for sso

**Comment by jsantana3c** [comment]
sorry, probably my english was the fault in the beginning, let me fix your quote real quick
>but it seems to not be clear about what happens for logout, the code isn't proceeding with an RP-Initiated Logout / Back Channel logout, which seems ~~to be done manually?~~ that needs to be done manually somehow?


having this DSL:

```java
@Bean
    SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
        http
                .authorizeExchange(authorizeRequests -> authorizeRequests
                        .anyExchange()
                        .authenticated()
                )
                .sessionManagement(sessions -> sessions
                        .concurrentSessions(concurrency -> concurrency
                                .maximumSessions(SessionLimit.of(1))
                        )
                )
                .csrf(ServerHttpSecurity.CsrfSpec::disable)
                .oauth2Login(spec -> spec
                        .oidcSessionRegistry(sessionRegistry)
                )
                .logout(logout -> logout
                        .logoutSuccessHandler(oidcLogoutSuccessHandler())
                )
                .oauth2Client(withDefaults());

        return http.build();
    }
```
when the max is reached, the standard session is logged out on the APP, when logging in back with the IDP (Spring Authorization Server), the session is still up(within the OAuth context).

**Comment by marcusdacoregio** [comment]
> when the max is reached, the standard session is logged out on the APP, when logging in back with the IDP (Spring Authorization Server), the session is still up(within the OAuth context).

That is the expected behavior, the concurrent session management is intended to invalidate sessions current registered in the `ReactiveSessionRegistry`, it has no way to know whether there is a session in the IdP. If you need to add such behavior, you must, as I mentioned, configure a `ServerMaximumSessionsExceededHandler` that does that for you where you could probably reuse the `OidcClientInitiatedServerLogoutSuccessHandler`.

With that said, I agree that the documentation could benefit from some improvement where such scenarios happen, I'll repurpose this ticket to cover that if you are ok with it.

**Comment by joaquinjsb** [comment]
Yes, that's what I tried, but the OidcClientInitiatedServerLogoutSuccessHandler needs an exchange for some the uri components etc, so I ended up duplicating the ConcurrentSessionControlServerAuthenticationSuccessHandler to do the proper processing, so I don't know if maybe this is the proper way of doing it, or, if the MaxiumSessionsContext/handle method, could be enriched with the exchange to improve "deeper" processing?

but if the documentation in that sense is improved, maybe that's not a lot of an issue for other people
