### ISSUE TITLE
Allow authorities loading customization in ActiveDirectoryLdapAuthenticationProvider

### ISSUE THREAD

**Issue by noavarice** [spring-projects/spring-security#15138]
**Expected Behavior**
You can change `ActiveDirectoryLdapAuthenticationProvider`'s [`loadUserAuthorities`](https://github.com/spring-projects/spring-security/blob/main/ldap/src/main/java/org/springframework/security/ldap/authentication/ad/ActiveDirectoryLdapAuthenticationProvider.java#L185) behavior somehow (by extending the class or, probably more cleanly, with some delegate component).

**Current Behavior**
`ActiveDirectoryLdapAuthenticationProvider` is final so you cannot extend it, and `loadUserAuthorities` method does not use delegate components, so you cannot change method's behavior.

**Context**
It would be handy to have plain LDAP group DN's as authority values, rather than CN only.

**Comment by noavarice** [comment]
Also you can't really modify `doAuthenticate` (e.g., if you need to use some information from your local database, such ability to lock user without using Active Directory)

**Comment by jzheaux** [comment]
Thanks for the report, @noavarice. This was recently added in the 6.3 release as part of #4490, so please feel free to check it out and let me know if any improvements are needed. For now, I'll close this as a duplicate of that.
