### ISSUE TITLE
SpringSecurityCoreVersion.SERIAL_VERSION_UID is wrong in Spring Security 6.3

### ISSUE THREAD

**Issue by yu-shiba** [spring-projects/spring-security#15154]
**Describe the bug**
The SpringSecurityCoreVersion.SERIAL_VERSION_UID, which is updated on major and minor updates, is still 620L.
https://github.com/spring-projects/spring-security/blob/6956ed693c734bc2359bd625e6d9bd76c0bffed5/core/src/main/java/org/springframework/security/core/SpringSecurityCoreVersion.java#L43

**To Reproduce**
We can check it on the code.

**Expected behavior**
In Spring Security 6.3 it must be set to `630L`.

**Comment by marcusdacoregio** [comment]
Hi, @yu-shiba. The serial version is right, please see https://github.com/spring-projects/spring-security/issues/3737

**Comment by yu-shiba** [comment]
Hi, @marcusdacoregio. Sorry. I did not gather enough information.
I have read the [Blog ](https://spring.io/blog/2024/01/19/spring-security-6-3-adds-passive-jdk-serialization-deserialization-for) and now understand the background.
Thank you very much.
