### ISSUE TITLE
SEC-1289: Successful registration event

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1515]
[Nickolay Mazurkin](https://jira.spring.io/secure/ViewProfile.jspa?name=nickmz) (Migrated from [SEC-1289](https://jira.spring.io/browse/SEC-1289?redirect=false)) said:

With 3.0M2 and before I used the following code to register successful registrations and save client's IPs

[code]
public class AuthenticationListener implements ApplicationListener {

```
@Override
public void onApplicationEvent(ApplicationEvent event) {
    if (event instanceof AuthenticationSuccessEvent) {
        onAuthenticationSuccessEvent((AuthenticationSuccessEvent) event);
    }
}

public void onAuthenticationSuccessEvent(AuthenticationSuccessEvent authenticationSuccessEvent) {
    // my code
}
```

}
[/code]

With 3.0RC1 there are no AuthenticationSuccessEvent events any more. I've found the following comment for org.springframework.security.authentication.DefaultAuthenticationEventPublisher

"The default strategy used by <tt>ProviderManager</tt> for publishing authentication events."

But when I looked in ProviderManager I've found that the default strategy is NullEventPublisher which is created by private field's initializer.

I thought that it's possible to inject DefaultAuthenticationEventPublisher with default XML security scheme but I've found no entry point to do this.

**Comment by spring-issuemaster** [comment]
This issue duplicates #1522
