### ISSUE TITLE
Documentation clarification after #12783 has been closed is needed.

### ISSUE THREAD

**Issue by wilx** [spring-projects/spring-security#15208]
This is related to https://github.com/spring-projects/spring-security/issues/12783#issuecomment-1888798267. 

> This issue is linked from the docs at https://docs.spring.io/spring-security/reference/servlet/authorization/architecture.html#authz-hierarchical-roles with a note:
> 
> > RoleHierarchy bean configuration is not yet ported over to @EnableMethodSecurity. As such this example is using AccessDecisionVoter. If you need RoleHierarchy support for method security, please continue using @EnableGlobalMethodSecurity until https://github.com/spring-projects/spring-security/issues/12783 is complete.

Is the note still valid? Or is the documentation outdated with respect to this issue's state?

**Comment by jzheaux** [comment]
Thanks, @wilx, I'd agree that the documentation needs updating here. Thank you for alerting me to the missed comment.
