### ISSUE TITLE
SEC-1274: JdbcMutableAclService has concurrency problems on Oracle

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1523]
[Martin Kneissl](https://jira.spring.io/secure/ViewProfile.jspa?name=mkneissl) (Migrated from [SEC-1274](https://jira.spring.io/browse/SEC-1274?redirect=false)) said:

The algorithm of doing the insert with an auto identity column and then checking for the most recent identity value does not work very cleanly on Oracle.

1st problem: There is no auto identity mechanism in Oracle. This can be worked around by creating a sequence and a before insert trigger, leading to the second problem:

2nd problem: Sequences in Oracle are not transactional. When two new objects are created in the database at the same time in different transactions, there would be two sequence values created. 
Assume transaction 1 ("T1") inserts first, T2 second. T2 will then fail due to the unique constraint. The current sequence value will not be rolled back. That means that the wrong sequence value may be retrieved in T1, if the insert of T2 is interleaved between insert and identity query of T1.

This is related to issues SEC-1076 and SEC-479 (issue 4).

**Comment by rwinch** [comment]
Marking this as declined as no additional feedback was provided
