### ISSUE TITLE
SEC-1303: Remove commons codec dependency from core

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1524]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1303](https://jira.spring.io/browse/SEC-1303?redirect=false)) said:

To be replaced with internal code to reduce external dependencies. This Base64 implementation (also used in OWASP ESAPI) would be a good start:

http://iharder.sourceforge.net/current/java/base64/

**Comment by spring-issuemaster** [comment]
This issue supersedes #1547
