### ISSUE TITLE
A broken link in Spring Security reference

### ISSUE THREAD

**Issue by jourteen** [spring-projects/spring-security#15288]
The following snippet from [Method Security](https://docs.spring.io/spring-security/reference/servlet/authorization/method-security.html) section of Spring Security reference contains a broken link to `AuthorizationManagerBeforeMethodInterceptor`:

> Spring AOP invokes its proxy method for `readCustomer`. Among the proxy’s other advisors, it invokes an [AuthorizationManagerBeforeMethodInterceptor](https://docs.spring.io/spring-security/site/docs/6.3.1/api/org/springframework/security/authorization/method/AuthorizationManagerBeforeMethodInterceptor/html) that matches [the @PreAuthorize pointcut](https://docs.spring.io/spring-security/reference/servlet/authorization/method-security.html#annotation-method-pointcuts)

The URL ending should be changed from '/html' to '.html'.

**Comment by rishiraj88** [comment]
LGTM

**Comment by jzheaux** [comment]
Thanks for the report, @jourteen. This will go into the next maintenance release.
