### ISSUE TITLE
Document setting up `client_credentials` with access tokens scoped to the application

### ISSUE THREAD

**Issue by sjohnr** [spring-projects/spring-security#15304]
We should add a clear example to the reference for setting up an application with the `client_credentials` grant type. Often, this use case requires access tokens scoped to the application instead of individual users in session.

Related gh-15295

**Comment by FryingHellfish** [comment]
Hi @sjohnr,

Would you be kind enough to share some code snippets related to this example, specifically for reactive applications? We're encountering similar issues as described in gh-10083 and gh-13816, and we're very interested in finding a solution.

Thank you in advance.
