### ISSUE TITLE
SEC-1284: Support 'proxy-target-class' attribute for global-method-security element of security namespace

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1533]
[Chris Beams](https://jira.spring.io/secure/ViewProfile.jspa?name=cbeams) (Migrated from [SEC-1284](https://jira.spring.io/browse/SEC-1284?redirect=false)) said:

Expected: `<sec:global-method-security/>` should expose a `proxy-target-class` attribute, following suit with `<tx:annotation-driven/>`, `<aop:config/>`, etc.

Actual: It does not expose this attribute, and so users are forced to work around the namespace and drop down to low-level bean defs if they need to influence the proxy creation strategy.

**Comment by spring-issuemaster** [comment]
This issue is related to https://jira.spring.io/browse/SWS-551

**Comment by spring-issuemaster** [comment]
This issue is related to https://jira.spring.io/browse/SWS-551

**Comment by spring-issuemaster** [comment]
This issue is related to https://jira.spring.io/browse/SWS-551

**Comment by spring-issuemaster** [comment]
This issue is related to https://jira.spring.io/browse/SWS-551

**Comment by spring-issuemaster** [comment]
This issue is related to https://jira.spring.io/browse/SWS-551

**Comment by spring-issuemaster** [comment]
This issue is related to https://jira.spring.io/browse/SWS-551

**Comment by spring-issuemaster** [comment]
This issue is related to https://jira.spring.io/browse/SWS-551

**Comment by spring-issuemaster** [comment]
This issue is related to https://jira.spring.io/browse/SWS-551
