### ISSUE TITLE
Use Spring SSL bundle in SAML2 signing

### ISSUE THREAD

**Issue by gertvv** [spring-projects/spring-security#15366]
**Expected Behavior**

When acting as a SAML2 client, allow the lovely [Spring SSL bundles](https://spring.io/blog/2023/06/07/securing-spring-boot-applications-with-ssl) to be used to specify the certificates in configuration. For example, by setting `spring.security.saml2.relyingparty.registration.<reg-id>.signing.credentials.bundle`.

**Current Behavior**

The `private-key-location` and `certificate-key-location` must be set separately and don't seem to have useful functionality offered by the SSL bundles, such as loading from a keystore and decrypting the private key.

**Context**

I'm looking for good ways to inject these secrets into the configuration and ideally without decrypting the key file on disk.

**Comment by jzheaux** [comment]
I think this sounds reasonable, though it would be something that Spring Boot would need to support as they are using those properties to construct an instance of `RelyingPartyRegistration`. Will you please [file a ticket there](https://github.com/spring-projects/spring-boot/issues/new) and cc me in the description? I'd be happy to help coordinate.
