### ISSUE TITLE
Response header ``Vary`` since Spring Security 6.2.0

### ISSUE THREAD

**Issue by renetrefft** [spring-projects/spring-security#15378]
After upgrading from Spring Boot 3.1.* to Spring Boot 3.2.0 which includes Spring Security 6.2.0, responses of REST services provided by ``@Controller`` classes have ``Vary`` headers if ``org.springframework.boot:spring-boot-starter-security`` is in classpath.

Is this intended? We immediately noticed this change since our CDN Akamai does not cache responses with this header.

**Comment by malaquf** [comment]
Hi @renetrefft, we've observed the same issue and I believe [this is the change/fix](https://github.com/spring-projects/spring-framework/commit/d27b5d0ab6e8b91a77e272ad57ae83c7d81d810b#diff-d854062b0e7c407eadbc755d6226f401R62) that causes it.

**Comment by malaquf** [comment]
Hi @renetrefft , we also noticed this issue and I believe [this is the commit](https://github.com/spring-projects/spring-security/commit/618847418f415ac818be3ad92ecf1afe0635958c) that introduces it. Now CorsFilter is configured by default, if CorsConfigurationSource is present.

**Comment by malaquf** [comment]
I believe this side effect is not intended, as HandlerMappingIntrospector implements CorsConfigurationSource and is instantiated by default by WebMvcConfigurationSupport in spring boot auto configure.

**Comment by jzheaux** [comment]
I agree that this is likely not the intent. It may be best for Spring Security to be more conservative for the time being and pick up only `UrlBasedCorsConfigurationSource` instances.

**Comment by baezzys** [comment]
Hi @jzheaux I'd like to contribute to this issue. Can I work on it?

**Comment by marcusdacoregio** [comment]
Closed via https://github.com/spring-projects/spring-security/commit/3d4bcf1b4483e927eec05f2c01c5359e0b714267

**Comment by piotrooo** [comment]
I think this change should be interpreted as a **breaking change** since, after the update from 3.3.2 to 3.3.3, it is no longer working.

FYI @marcusdacoregio, @baezzys and @jzheaux 

```java
@Configuration
public class CorsWebConfiguration implements WebMvcConfigurer {
    @Override
    public void addCorsMappings(CorsRegistry registry) {
        registry.addMapping("/web/**")
                .allowedOriginPatterns("https://*.example.com")
                .allowedMethods("GET", "POST", "PUT", "DELETE", "OPTIONS", "HEAD");
    }
}
```
