### ISSUE TITLE
Documentation for ServletBearerExchangeFilterFunction incomplete or incorrect

### ISSUE THREAD

**Issue by jpmsilva** [spring-projects/spring-security#15425]
Documentation for [ServletBearerExchangeFilterFunction ](https://docs.spring.io/spring-security/site/docs/6.3.1/api/org/springframework/security/oauth2/server/resource/web/reactive/function/client/ServletBearerExchangeFilterFunction.html)is incomplete or incorrect, as it mentions this regarding locating a bearer token:

> To locate the bearer token, this looks in the Reactor Context for a key of type [Authentication](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/core/Authentication.html). Registering , as a @Bean will take care of this automatically

It does not specify what to register exactly.

Looking at the [source code](https://github.com/spring-projects/spring-security/blob/5870a45a3d8e29a0efd4c42565e66c0d9ec04b3d/oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/web/reactive/function/client/ServletBearerExchangeFilterFunction.java#L54) we see:

> Registering {@see org.springframework.security.config.annotation.web.configuration.OAuth2ResourceServerConfiguration.OAuth2ResourceServerWebFluxSecurityConfiguration.BearerRequestContextSubscriberRegistrar}, as a {@code @Bean} will take care of this automatically

The class mentioned does not appear to exist, which explains why the Javadoc appears incomplete, and as an API user it is unclear what needs to be done for `ServletBearerExchangeFilterFunction` to work as expected.

(Edited to remove some remarks that turned out to be unrelated - this appears to be simply a documentation issue).

**Comment by jzheaux** [comment]
Thanks for the report, @jpmsilva, this is now merged into `5.8.x`, `6.2.x`, `6.3.x`, and `main` and will go out in the next set of maintenance releases.
