### ISSUE TITLE
Broken documentation link for 6.4.0-M1

### ISSUE THREAD

**Issue by breun** [spring-projects/spring-security#15442]
On https://spring.io/projects/spring-security#learn the link for 6.4.0-M1 links to https://docs.spring.io/spring-security/reference/6.4/index.html, which returns 404 Not Found.

**Comment by jzheaux** [comment]
Hi, @breun, the link you posted works for me at this point. I'll close, but please feel free to reopen with any additional information.

**Comment by breun** [comment]
Indeed works now.
