### ISSUE TITLE
SEC-1300: ArrayIndex out of bounds in AclImpl

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1546]
[Tim ](https://jira.spring.io/secure/ViewProfile.jspa?name=timreilly) (Migrated from [SEC-1300](https://jira.spring.io/browse/SEC-1300?redirect=false)) said:

In AclImpl#verifyAceIndexExists(...)
I think this is an "off by one" bug. I may be wrong but shouldn't 
this:

```
    if (aceIndex > this.aces.size()) {
        throw new NotFoundException("aceIndex must correctly refer to an index of the AccessControlEntry collection");
    }
```

be this:

```
    if (aceIndex > this.aces.size() - 1) {
        throw new NotFoundException("aceIndex must correctly refer to an index of the AccessControlEntry collection");
    }
```

Since I'm getting the exception but wondered how it passed verifyAceIndexExists?:

eption Handler execution resulted in exception - forwarding to resolved error view
                                 java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
        at java.util.ArrayList.RangeCheck(ArrayList.java:572)
        at java.util.ArrayList.remove(ArrayList.java:415)
        at org.springframework.security.acls.domain.AclImpl.deleteAce(AclImpl.java:131)
        at com.acme.app.springframework.security.AclSecurityServiceImpl.replaceUserPermissions(AclSecurityServiceImpl.jav

**Comment by spring-issuemaster** [comment]
This issue duplicates #1399
