### ISSUE TITLE
HeadersConfigurer.PermissionsPolicyConfig breaks fluent api

### ISSUE THREAD

**Issue by sfilipiak-inpost** [spring-projects/spring-security#15478]
**Describe the bug**
`HeadersConfigurer.permissionsPolicy(Customizer<PermissionsPolicyConfig> permissionsPolicyCustomizer)` breaks fluent api because it returns `PermissionsPolicyConfig` instead of `HeadersConfigurer`

**To Reproduce**
Following code does not compile.
```java
public SecurityFilterChain securityFilterChain(HttpSecurity httpSecurity) throws Exception {
    return httpSecurity
        .headers(
            headers ->
                headers
                    .permissionsPolicy(Customizer.withDefaults())
                    // Compilation failure, cannot find symbol
                    .httpStrictTransportSecurity(Customizer.withDefaults())
        )
        .build();
}
```

**Expected behavior**
Above code compiles.

**Sample**
Provided above

**Comment by marcusdacoregio** [comment]
Hi @sfilipiak-inpost, thanks for the report. This is a duplicate of https://github.com/spring-projects/spring-security/issues/14803.
