### ISSUE TITLE
Request for Webflux support for Auth Server

### ISSUE THREAD

**Issue by dreamstar-enterprises** [spring-projects/spring-security#15502]
I believe this is a request. Are there any plans soon by the Sping Team for an asynchronous Auth Server?

Currently, when querying a DocDB database, I use this for my UserDetailsService. 
But I do get memory leaks in the server log, I think because Project Loom is still in beta. 

Just wondered if there might be upcoming support for a Webflux AuthServer?

// using Java Virtual Threads (Project Loom), since Spring does not yet support reactive Auth Servers
// https://github.com/spring-projects/spring-authorization-server/issues/152
// https://kt.academy/article/dispatcher-loom

```
@Configuration
class ExecutorConfig {

    private val executor = Executors.newVirtualThreadPerTaskExecutor()

    @Bean
    fun coroutineDispatcher(): CoroutineContext = executor.asCoroutineDispatcher()

    @PreDestroy
    fun cleanUp() {
        executor.close()
    }
}

@Service
internal class VirtualThreadManager(
    @Autowired
    private val userRepo: UserRepositoryImpl,
    private val dispatcher: CoroutineContext
) {

    internal fun fetchUserEntity(userEmail: String): UserEntity? {

        return try {
            // run the coroutine blocking the current thread until it completes
            runBlocking {
                // switch to the custom dispatcher created from the executor
                withContext(dispatcher) {
                    getUserEntity(userEmail)
                }
            }
        } catch (ex: RejectedExecutionException) {
            throw RuntimeException("Executor was shut down, unable to execute task", ex)
        }
    }

    // get userEntity from DocDatabase
    private suspend fun getUserEntity(userEmail: String): UserEntity? {
        val userEntity = userRepo.getUserByEmail(userEmail)
        return userEntity
    }
}
```

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by sjohnr** [comment]
@dreamstar-enterprises, I believe this has been answered in [this comment](https://github.com/spring-projects/spring-authorization-server/issues/152#issuecomment-727957644).
