### ISSUE TITLE
`InMemory[Reactive]OAuth2AuthorizedClientService` does not support changes to the `ClientRegistration` at runtime

### ISSUE THREAD

**Issue by kzander91** [spring-projects/spring-security#15511]
**Describe the bug**
We're calling an API that requires JWTs for authentication. The JWTs are obtained from an authorization server using Client Credentials Grant.
The authorization server requires us to periodically rotate the client secret. We store the secret in a separate configuration service (where we can update it out-of-band) and we have implemented a custom `ReactiveClientRegistrationRepository` that retrieves the secret from there.

This setup works fine until the secret is changed: We noticed that our app keeps using the _previous_ secret, even though our `ReactiveClientRegistrationRepository` is returning the _new_ secret.

We have tracked this down to `InMemoryReactiveOAuth2AuthorizedClientService#loadAuthorizedClient` which internally uses our repository implementation:
https://github.com/spring-projects/spring-security/blob/6adc3b3d99be1452b2900e1d5f9a05cee01157fa/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/InMemoryReactiveOAuth2AuthorizedClientService.java#L60-L67
Note how the `ClientRegistration` retrieved from our `clientRegistrationRepository` (containing the _current_ secret) is effectively ignored in favor of the `ClientRegistration` cached in the `authorizedClients` map (as a member of `OAuth2AuthorizedClient`). This means that the client secret that was current at the time of the first token request is used forever, even if the `ClientRegistration` changes afterwards.
After we rotated the secret, the authorization server rejects the previous one, resulting in all token requests to fail shortly after a secret rotation.

**Expected behavior**
The `InMemoryReactiveOAuth2AuthorizedClientService` should consider the fact that the `ClientRegistration` may change at runtime and thus not ignore it after fetching it from the registration repository.

**Workaround**
* First quick workaround was to reboot our app after every secret rotation.
* Next, we implemented our own `ReactiveOAuth2AuthorizedClientService` that is basically a copy of `InMemoryReactiveOAuth2AuthorizedClientService`, but with the following modification to `loadAuthorizedClient`:
```java
return this.clientRegistrationRepository.findByRegistrationId(clientRegistrationId)
  .mapNotNull(clientRegistration -> {
    OAuth2AuthorizedClientId id = new OAuth2AuthorizedClientId(clientRegistrationId, principalName);
    OAuth2AuthorizedClient cachedAuthorizedClient = this.authorizedClients.get(id);
    if (cachedAuthorizedClient == null) {
      return null;
    }
    // Use current registration here  vvvvvvvvvvvvvvvvvv
    return new OAuth2AuthorizedClient(clientRegistration, cachedAuthorizedClient.getPrincipalName(), cachedAuthorizedClient.getAccessToken(), cachedAuthorizedClient.getRefreshToken());
  });
```

Note that the non-reactive version has the same behaviour, so this isn't specific to the reactive implementation.

---

Is there a specific reason for why the service behaves that way? What would be the recommended way to implement an OAuth2 client with secrets that can change at runtime?

The R2DBC implementation for example _does_ behave as expected and always returns the `ClientRegistration` from the repository, see here:
https://github.com/spring-projects/spring-security/blob/6adc3b3d99be1452b2900e1d5f9a05cee01157fa/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/R2dbcReactiveOAuth2AuthorizedClientService.java#L150-L156

**Comment by kzander91** [comment]
Hi @sjohnr, no worries!

I am aware that the in-memory implementations of various beans aren't recommended for production use, but my interpretation of the reason behind that was always that there's no mechanism to limit the size of the map. Are there other reasons for it not being recommended for production?

In my use case, the map will only ever contain a single mapping, because the user in the `SecurityContext` will always be the same, single user, and API calls will only ever be made to the same endpoint with bearer tokens obtained from the same IDP. Thus, the complexity of setting up a database for that (plus the additional latency reading from/writing to the DB) just isn't worth it and the in-memory variant should be perfectly suitable for that use case.

**Comment by sjohnr** [comment]
> Are there other reasons for it not being recommended for production?

The in-memory implementations are just not designed for production use. Any issues they have would be specific to their implementation.

Having said that, we still want to fix bugs that are obviously incorrect (and not directly related to being in memory), so I think the bug you mention here could be fixed since the r2dbc version doesn't have the same issue. Would you be interested in sending a PR?

**Comment by kzander91** [comment]
@sjohnr sure I'll give it a shot! Would you say that the workaround I showed above was a suitable fix? Then I'd try submitting that as a PR.

**Comment by sjohnr** [comment]
> Would you say that the workaround I showed above was a suitable fix?

Yes, I think so! Though I would find it preferable to use a fluent return value by nesting `flatMap`:

```java
// @formatter:off
return (Mono<T>) this.clientRegistrationRepository.findByRegistrationId(clientRegistrationId)
	.flatMap((clientRegistration) -> Mono.just(new OAuth2AuthorizedClientId(clientRegistrationId, principalName))
		.mapNotNull(this.authorizedClients::get)
		.map((authorizedClient) -> new OAuth2AuthorizedClient(clientRegistration,
			authorizedClient.getPrincipalName(),
			authorizedClient.getAccessToken(),
			authorizedClient.getRefreshToken()))
	);
// @formatter:on
```

**Comment by kzander91** [comment]
@sjohnr #16133 is ready for your consideration.
