### ISSUE TITLE
Backchannel logout requires JSESSIONID, but Spring session calls it SESSIONID

### ISSUE THREAD

**Issue by dreamstar-enterprises** [spring-projects/spring-security#15539]
I wasn't sure if this was a contradiction. 

It says here that the session cookie should be called: JSESSIONID

https://docs.spring.io/spring-security/reference/reactive/oauth2/login/logout.html#oauth2login-advanced-oidc-logout

But Spring Session calls the cookie: SESSIONID

So will BackChannel Logout not work when I'm using Spring Session?

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by jzheaux** [comment]
Hi, @dreamstar-enterprises. Please follow https://github.com/spring-projects/spring-security/issues/14904 for updates.
