### ISSUE TITLE
Support refresh token for Token Exchange

### ISSUE THREAD

**Issue by icruces** [spring-projects/spring-security#15534]
I have recently integrated **Token Exchange** into my project as I need to perform long-lived background tasks on behalf of the user. It exchanges the original access token from the user authentication for another with _offline_access_, which needs to be refreshed periodically (Keycloak).

Unfortunately, the current implementation of **TokenExchangeOAuth2AuthorizedClientProvider** doesn't support the _refresh_token_ token type.

I managed to implement a custom version of the Token Exchange provider to support this and make it compatible with the Refresh Token provider, but It would be good to have it built in Spring Security as it is a common case.

**Comment by icruces** [comment]
@sjohnr thanks for reply. I was actually asking for an enhancement. The `TokenExchangeOAuth2AuthorizedClientProvider ` is not compatible with `RefreshTokenOAuth2AuthorizedClientProvider` as `OAuth2AuthorizedClient` created by the former doesn't store the refresh token in the new `OAuth2AuthorizedClient`:

```
        // TokenExchangeOAuth2AuthorizedClientProvider source code
        @Override
        @Nullable
	public OAuth2AuthorizedClient authorize(OAuth2AuthorizationContext context) {
		...
                ...
                // tokenResponse.getRefreshToken() is not passed to the constructor so it is discarded

		return new OAuth2AuthorizedClient(clientRegistration, context.getPrincipal().getName(),
				tokenResponse.getAccessToken());
	}
```

**Comment by sjohnr** [comment]
Hi @icruces. I'm not able to determine from the information you've provided whether you have tried setting things up correctly to have refresh tokens work. They should work if you are using `OAuth2AuthorizedClientManager` correctly. At the current time I don't believe the enhancement is needed and suspect that things are not set up correctly on your end. If you can provide a minimal example that demonstrates what you've tried, I will be able to either suggest what you are missing, or determine where an enhancement is required and we can go from there.

**Comment by sjohnr** [comment]
@icruces thank you for bringing this up. I see in the spec ([Section 2.2.1](https://datatracker.ietf.org/doc/html/rfc8693#section-2.2.1-2.11)) that refresh tokens can be returned in offline access scenarios. I see what you are saying and am reopening this issue.

**Comment by icruces** [comment]
@sjohnr Sounds great. Sorry, maybe I didn't express myself very well in English.

**Comment by sjohnr** [comment]
Not at all. I read your first comment and didn't get the point, but your second comment made the point, I just didn't read it carefully enough.
