### ISSUE TITLE
SEC-1316: Remove "removeAfterRequest" functionality from AnonymousAuthenticationFilter

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1560]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1316](https://jira.spring.io/browse/SEC-1316?redirect=false)) said:

This should no longer be necessary. See SEC-1313.

**Comment by spring-issuemaster** [comment]
This issue supersedes #1557
