### ISSUE TITLE
Add Reactive One-Time Token Login support

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-security#15699]

**Comment by CrazyParanoid** [comment]
Hi @marcusdacoregio, can I take this issue to work?

**Comment by marcusdacoregio** [comment]
Yes, absolutely @CrazyParanoid. This ticket is yours.

**Comment by CrazyParanoid** [comment]
Hi @marcusdacoregio, this issue requires the development of a number of reactive components, e.g. `OneTimeTokenReactiveAuthenticationManager` or `ServerOneTimeTokenAuthenticationConverter`. 
I have opened a PR with the implementation of the `OneTimeTokenLoginSpec` solution. It will probably be better if the maintainers carefully review this issue if it is accepted.
