### ISSUE TITLE
OidcBackChannelLogoutTokenValidator should not throw an NPE when issuer is missing

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#15771]
Related to https://github.com/spring-projects/spring-boot/issues/42172#issue-2510291998, when `ClientRegistration` does not have an `issuerUri` configured, it should give a better error than an NPE.

This needs to be addressed for both the imperative and reactive versions of the class.

Please base this change off the `6.2.x` branch so it can be forward-ported when merged.

**Comment by wapkch** [comment]
Hi @jzheaux , may i work on this?

**Comment by jzheaux** [comment]
Yes, please. :) Thanks for offering, the issue is yours.
