### ISSUE TITLE
SEC-1331: Allow omission of password field in user-service users

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1579]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1331](https://jira.spring.io/browse/SEC-1331?redirect=false)) said:

For such users, the namespace would generate a random password value, preventing authentication as those users. This makes sense in situations where the service is only used to load supplementary post-authentication data (user authorities). Typically this is the case with CAS, OpenID, Pre-Authentication.

**Comment by rwinch** [comment]
This issue supersedes #1576

**Comment by spring-issuemaster** [comment]
This issue supersedes #1576

**Comment by spring-issuemaster** [comment]
This issue supersedes #1576

**Comment by spring-issuemaster** [comment]
This issue supersedes #1576
