### ISSUE TITLE
SEC-1332: Support OpenID Provider Authentication Policy Extension (PAPE)

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1580]
[Dan Lynn](https://jira.spring.io/secure/ViewProfile.jspa?name=dan_lynn) (Migrated from [SEC-1332](https://jira.spring.io/browse/SEC-1332?redirect=false)) said:

Implement http://openid.net/specs/openid-provider-authentication-policy-extension-1_0.html using org.openid4java.message.pape.PapeRequst and org.openid4java.message.pape.PapeResponse

**Comment by rwinch** [comment]
Closing since OpenID 2.0 is deprecated in favor of OpenID Connect See gh-7153
