### ISSUE TITLE
carrier thread be suspended by synchronized in RemoteJWKSet

### ISSUE THREAD

**Issue by me0106** [spring-projects/spring-security#15866]
RemoteJWKSet use synchronized for synchronization. 
But this will suspend the carrier thread.
In some specific situations, it may cause the server to hang: 

`single carrier thread.(Single core CPU). And call itself to retrieve jwk`.

`RemoteJWKSet is deprecated`. Should we replace it with `JwkSourceBuilder`?

> SpringBoot: 3.3.1
> Java: Temurin-21.0.4+7

![image](https://github.com/user-attachments/assets/5f0dab95-56e8-4ab1-a704-8d5f23c480f3)
![image](https://github.com/user-attachments/assets/99c77866-c571-46ff-86bb-b0be78a346ec)

**Comment by rwinch** [comment]
Thank you for the report. Would you be interested in submitting a pull request to replace RemoteJWKSet?

**Comment by CrazyParanoid** [comment]
Hi @rwinch, in this issue we need to replace the old jose api with a new one. This is not a very simple issue, for example `JWKSetCache` is now deprecated, and it is needed for `JwkSourceBuilder`. I can think about how to solve this issue.

**Comment by rwinch** [comment]
Closing as duplicate of gh-16251

**Comment by frido37** [comment]
Removing the deprecated usages of RemoteJWKSet ([issue #16251](https://github.com/spring-projects/spring-security/issues/16251)) did not resolve the underlying issue: there is still a remote HTTP call performed within a critical section. While the synchronization mechanism has changed from synchronized to a ReentrantLock, the fundamental concern remains.

To address this, I’ve proposed a fix in [pull request #17669](https://github.com/spring-projects/spring-security/pull/17669).
