### ISSUE TITLE
SEC-1353: SessionManagementFilter can invoke other filters after sending redirect

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1597]
[Artem Anisimov](https://jira.spring.io/secure/ViewProfile.jspa?name=artem.anisimov) (Migrated from [SEC-1353](https://jira.spring.io/browse/SEC-1353?redirect=false)) said:

SessionManagementFilter::doFilter() fails to stop request processing in branch "No security context or authentication present" (at SessionManagementFilter.java:89). More precisely, it does not return after calling redirectStrategy.sendRedirect(), but passes to the next filter.

This causes an error if there are controllers that define methods taking a HttpSession argument, because in this case AnnotationMethodHandlerAdapter attempts to call request.getSession(), which is not permitted after a redirect had been sent.

**Comment by rwinch** [comment]
This issue duplicates #1578
