### ISSUE TITLE
The StrictFirewallServerWebExchange causes the ServerWebExchange.getRequest().mutate() contract to break as headers become readonly

### ISSUE THREAD

**Issue by spencergibb** [spring-projects/spring-security#15989]
Rob and I chatted about it

https://github.com/spring-projects/spring-framework/blob/c27a5687dcc8708584edd0141630af66ce6cbe90/spring-web/src/main/java/org/springframework/http/HttpHeaders.java#L1890

headers is read only, AND headers.headers is read only, so calling HttpHeaders.writableHttpHeaders() does not, in fact, result in writable headers.

The question is, is it a security or framework bug.

/cc @rwinch @rstoyanchev

**Comment by rwinch** [comment]
For those experiencing this issue, DO NOT disable Spring Security's firewall as a workaround to the underlying [Spring Framework issue](https://github.com/spring-projects/spring-framework/issues/33789). Instead, you can use the following as a workaround:

```java
@Bean
@Order(Ordered.HIGHEST_PRECEDENCE)
WebFilter writeableHeaders() {
	return (exchange, chain) -> {
		HttpHeaders writeableHeaders = HttpHeaders.writableHttpHeaders(
				exchange.getRequest().getHeaders());
		ServerHttpRequestDecorator writeableRequest = new ServerHttpRequestDecorator(
				exchange.getRequest()) {
			@Override
			public HttpHeaders getHeaders() {
				return writeableHeaders;
			}
		};
		ServerWebExchange writeableExchange = exchange.mutate()
			.request(writeableRequest)
			.build();
		return chain.filter(writeableExchange);
	};
}
```

You can find a complete demo of the workaround at https://github.com/rwinch/spring-sample/tree/spring-framework-33789-readonly-headers

**Comment by dongKos** [comment]
@rwinch 
your solution works like magic thanks!

**Comment by TimofejOv** [comment]
> For those experiencing this issue, DO NOT disable Spring Security's firewall as a workaround to the underlying [Spring Framework issue](https://github.com/spring-projects/spring-framework/issues/33789). Instead, you can use the following as a workaround:
> 
> @Bean
> @Order(Ordered.HIGHEST_PRECEDENCE)
> WebFilter writeableHeaders() {
> 	return (exchange, chain) -> {
> 		HttpHeaders writeableHeaders = HttpHeaders.writableHttpHeaders(
> 				exchange.getRequest().getHeaders());
> 		ServerHttpRequestDecorator writeableRequest = new ServerHttpRequestDecorator(
> 				exchange.getRequest()) {
> 			@Override
> 			public HttpHeaders getHeaders() {
> 				return writeableHeaders;
> 			}
> 		};
> 		ServerWebExchange writeableExchange = exchange.mutate()
> 			.request(writeableRequest)
> 			.build();
> 		return chain.filter(writeableExchange);
> 	};
> }
> 
> You can find a complete demo of the workaround at https://github.com/rwinch/spring-sample/tree/spring-framework-33789-readonly-headers

Hello.

What could be the solution for WebMvc case?
I get UnsupportedOperationException in app with spring-cloud-gateway-mvc  (4.3.1)+ spring-security (6.5.5) + spring-webmvc (6.2.11).

Thank you.

**Comment by rodrigorodrigues** [comment]
> For those experiencing this issue, DO NOT disable Spring Security's firewall as a workaround to the underlying [Spring Framework issue](https://github.com/spring-projects/spring-framework/issues/33789). Instead, you can use the following as a workaround:
> 
> @Bean
> @Order(Ordered.HIGHEST_PRECEDENCE)
> WebFilter writeableHeaders() {
> 	return (exchange, chain) -> {
> 		HttpHeaders writeableHeaders = HttpHeaders.writableHttpHeaders(
> 				exchange.getRequest().getHeaders());
> 		ServerHttpRequestDecorator writeableRequest = new ServerHttpRequestDecorator(
> 				exchange.getRequest()) {
> 			@Override
> 			public HttpHeaders getHeaders() {
> 				return writeableHeaders;
> 			}
> 		};
> 		ServerWebExchange writeableExchange = exchange.mutate()
> 			.request(writeableRequest)
> 			.build();
> 		return chain.filter(writeableExchange);
> 	};
> }
> You can find a complete demo of the workaround at https://github.com/rwinch/spring-sample/tree/spring-framework-33789-readonly-headers

Hi @rwinch, can you please suggest a solution that works for Spring Boot 4? It seems this method `HttpHeaders.writableHttpHeaders` is being removed.

<img width="1012" height="329" alt="Image" src="https://github.com/user-attachments/assets/5d8de02b-fb3f-49b4-b318-050061125f36" />

**Comment by alcharkov** [comment]
@rodrigorodrigues answered already in your IDE class provided documentation. Just write `new HttpHeaders(exchange.getRequest().getHeaders())` instead of HttpHeaders.writableHttpHeaders..
