### ISSUE TITLE
UnsupportedOperationException when an http header is being added to a mutated ServerWebExchange request due to the new StrictFirewallHttpHeaders class

### ISSUE THREAD

**Issue by sestrel** [spring-projects/spring-security#16002]
Spring Boot 3.3.5 includes spring-security-web-6.3.4.jar. The newly introduced class org.springframework.security.web.server.firewall.StrictServerWebExchangeFirewall$StrictFirewallServerWebExchange$StrictFirewallHttpRequest$StrictFirewallHttpHeaders isn't supported by org.springframework.http.HttpHeaders.writableHttpHeaders(). As a result the following exception is being thrown if the ServerWebExchange webflux request is being mutated and an http header is modified or added:
`java.lang.UnsupportedOperationException: null
	at org.springframework.http.ReadOnlyHttpHeaders.put(ReadOnlyHttpHeaders.java:130) ~[spring-web-6.1.14.jar:6.1.14]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.test.web.reactive.server.SecurityMockServerConfigurers$MutatorFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/api/mycontroller" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.springframework.http.ReadOnlyHttpHeaders.put(ReadOnlyHttpHeaders.java:130) ~[spring-web-6.1.14.jar:6.1.14]
		at org.springframework.http.ReadOnlyHttpHeaders.put(ReadOnlyHttpHeaders.java:39) ~[spring-web-6.1.14.jar:6.1.14]
		at org.springframework.http.HttpHeaders.put(HttpHeaders.java:1779) ~[spring-web-6.1.14.jar:6.1.14]
		at org.springframework.http.server.reactive.DefaultServerHttpRequestBuilder.header(DefaultServerHttpRequestBuilder.java:110) ~[spring-web-6.1.14.jar:6.1.14]
		at app.SetHttpHeaderWebFilter.filter(SetHttpHeaderWebFilter.java:21) ~[main/:na]
		at org.springframework.web.server.handler.DefaultWebFilterChain.invokeFilter(DefaultWebFilterChain.java:114) ~[spring-web-6.1.14.jar:6.1.14]`

I set up a small github project [github StrictFirewallHttpHeaders](https://github.com/sestrel/StrictFirewallHttpHeaders). Simply run "gradlew clean test" to reproduce the error.

**Comment by evgeniycheban** [comment]
Hi, @jzheaux, can I work on this?

**Comment by jzheaux** [comment]
Sure, @evgeniycheban. You might begin by writing a failing test and seeing if it passes once you update to the latest Spring Framework snapshot.

**Comment by cy4n** [comment]
weighing in from another app, same usage (using ServerWebExchange.mutate() to add headers in a filterchain)
can confirm:
6.1.14 broke the feature to add headers in the WebFilterChain by wrapping the (formerly) ReadOnlyHttpHeaders in the StrictFireWallHttpHeaders

the mentioned fix in https://github.com/spring-projects/spring-framework/commit/a06bbccf9ecccd41f1099e0462005478cc84974b unwraps this again and it works for my app.
(tested with snapshot version spring-web-6.1.15-20241025.124905-16.jar (also used -sources.jar to debug))

thanks for the fix. is there any ETA for the 6.1.15 release? will it follow the "normal" patch cycle?

**Comment by rwinch** [comment]
Closing as duplicate of https://github.com/spring-projects/spring-security/issues/15995 which is superseded by https://github.com/spring-projects/spring-framework/issues/33789

**Comment by keerthimunikoti1807** [comment]
@rwinch I use putHeaders function where it replaces original headers with new headers. Could you please tell me how I can modify this to work?
                    
private void putHeaders(HttpHeaders origHeaders, HttpHeaders newHeaders) {
        newHeaders.forEach((key, value) -> origHeaders.put(key, value));
    }
    
ServerHttpRequest request =
                    exchange.getRequest().mutate().headers(headers -> putHeaders(headers, newHeaders)).build();

**Comment by rwinch** [comment]
@keerthimunikoti1807 Did you see the workaround in [the the issue that I indicated that this duplicates](https://github.com/spring-projects/spring-security/issues/16002#issuecomment-2442649184)?
