### ISSUE TITLE
StrictServerWebExchangeFirewall behavior in Spring-Security-Web 6.3.4

### ISSUE THREAD

**Issue by kpolli** [spring-projects/spring-security#16019]
**Expected Behavior**

StrictServerWebExchangeFirewall should be overridable so that allowEncodedSlashes can be set.

**Current Behavior**

allowEncodedSlashes in StrictServerWebExchangeFirewall can not be set.

**Context**

I recently updated Spring Security Web to 6.3.4 and immediately noticed requests were failing with T`he request was rejected because the URL contained a potentially malicious String \"%2F\"`

This was previously working so I dug into the code and noticed the error being thrown in this [line](https://github.com/spring-projects/spring-security/blob/1d32263a837312f378f7eab2aedd836e63d7c10a/web/src/main/java/org/springframework/security/web/server/firewall/StrictServerWebExchangeFirewall.java#L581) . Then looking up the call list, I see that StrictServerWebExchangeFirewall object is created in the [WebFilterChainProxy](https://github.com/spring-projects/spring-security/blob/1d32263a837312f378f7eab2aedd836e63d7c10a/web/src/main/java/org/springframework/security/web/server/WebFilterChainProxy.java#L50) class which means StrictServerWebExchangeFirewall is not a bean I can create a custom copy that allows me allowEncodedSlashes. The walk-around which I'm currently trying to get to work is create WebFilterChainProxy as a bean in the [WebFluxSecurityConfiguration](https://github.com/spring-projects/spring-security/blob/1d32263a837312f378f7eab2aedd836e63d7c10a/config/src/main/java/org/springframework/security/config/annotation/web/reactive/WebFluxSecurityConfiguration.java#L84) class.
I would have marked this a bug but I can't tell if Spring Security wants to stop supporting encoded slashes so downgraded to feature enhancement.

Thank you.

**Comment by kse-music** [comment]
It was fixed by [adc66e](https://github.com/spring-projects/spring-security/commit/adc66e134b376bc79c3beacdd15831b9a3956cda) and release in next verision 6.3.5

**Comment by rwinch** [comment]
This is indeed a duplicate of https://github.com/spring-projects/spring-security/issues/15974 which contains a workaround until the release.
