### ISSUE TITLE
OpenSamlAssertingPartyMetadataRepository should initialize OpenSAML

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#16042]
All `OpenSamlXXX` components should attempt to initialize OpenSAML.

For example, when `OpenSaml5AssertingPartyMetadataRepository#withMetadataLocation` is called, the method will fail if another component hasn't already initialized OpenSAML.

**Comment by ig-jinwoo** [comment]
Hi @jzheaux, Could I work on this issue?

**Comment by jzheaux** [comment]
Sure, @ig-jinwoo! It should involve adding the following:

```java
static {
    OpenSamlInitializationService.initialize();
}
```

to both `OpenSaml4` and `OpenSaml5AssertingPartyMetadataRepository`.

**Comment by jzheaux** [comment]
Also, note that this ticket is time-sensitive as it is targeting a release on November 18. If you get tied up and aren't able to put together a PR in the next few days, go ahead and let me know and I'll take care of things.

**Comment by ig-jinwoo** [comment]
Hi @jzheaux , thank you for providing additional details. I’ll aim to submit a PR as soon as possible, and if I cannot submit the PR by November 13, I’ll let you know.
