### ISSUE TITLE
Data flow style change from if-else to water flow.

### ISSUE THREAD

**Issue by mosbat** [spring-projects/spring-security#16119]
Hi guys, I'd like to contribute even with small changes or improvements for practice or just to purely satisfy my coding habits.

I found an if else statement and after studying/observing it for a while, it felt a bit awkward (understandably); and would love to propose just a mere style change from if-else to waterfall style.

I do not expect you to like my changes; but if you'd like to discuss them or you have the same passion as I do, I'm happy to listen to comments and maybe hints.

I was thinking btw, the class is deprecated but still seems to be in use, or am I wrong?

PR if you'd like to review! #16118

**Comment by sjohnr** [comment]
Closing based on [this comment](https://github.com/spring-projects/spring-security/pull/16118#issuecomment-2484291907).
