### ISSUE TITLE
SEC-1370: Refactor security interceptor hierarchy

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1613]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1370](https://jira.spring.io/browse/SEC-1370?redirect=false)) said:

It might be possible to introduce an interface here and generic secured object types to simplify things.

**Comment by rwinch** [comment]
This is superseded by gh-8900
