### ISSUE TITLE
Add JavaDoc to HttpSessionEventPublisher#sessionIdChanged

### ISSUE THREAD

**Issue by 12OneTwo12** [spring-projects/spring-security#16211]
I noticed that the `sessionIdChanged` method in the `HttpSessionEventPublisher` class does not have a Javadoc comment. In contrast, other methods in the same class (`sessionCreated` and `sessionDestroyed`) are well-documented with Javadoc.

The `sessionIdChanged` method appears to play an important role in handling session ID changes by publishing a `HttpSessionIdChangedEvent`. However, without proper Javadoc, it is harder to understand its purpose and behavior compared to the other methods in the class.

Is there a specific reason why this method lacks Javadoc?  

Thank you for your time, and I look forward to your feedback! 😊

**Comment by jzheaux** [comment]
It looks like there is JavaDoc in the parent interface for that method, which may be why it wasn't added.

However, I think it would be fine to add the following to `HttpSessionEventPublisher#sessionIdChanged`:

```
/**
  * @inheritDoc 
  */
```

Are you able to submit a PR that adds this to `sessionIdChanged`?

**Comment by 12OneTwo12** [comment]
Thank you for the clarification!

That makes sense

I'll go ahead and prepare a PR to add the suggested Javadoc to `HttpSessionEventPublisher#sessionIdChanged`. Please let me know if there are any additional details you'd like me to consider

Thanks again for your guidance!
