### ISSUE TITLE
JDBC WebAuthn Repositories

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#16224]
Spring Security currently only has in memory implementations of webauthn repositories. We should add the option to use JDBC

**Comment by franticticktick** [comment]
Hi @rwinch , can I take this to work?

**Comment by rwinch** [comment]
@franticticktick Thanks for the offer! Yes please send a PR

**Comment by franticticktick** [comment]
@rwinch i sent it, could you review it?
