### ISSUE TITLE
SEC-1388: Support for custom AuthenticationDetailsSource in form-login tag.

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1629]
[Mauricio Noda](https://jira.spring.io/secure/ViewProfile.jspa?name=mnoda) (Migrated from [SEC-1388](https://jira.spring.io/browse/SEC-1388?redirect=false)) said:

When using the <form-login /> tag, there´s no way to configure a custom AuthenticationDetailsSource.

The workaround is to reconfigure UsernamePasswordAuthenticationFilter as a custom filter and reconfigure LoginUrlAuthenticationEntryPoint with its loginFormUrl property. Spring XML becomes more polluted and some minor functionality like the <http> auto-config and the built-in form login page are lost.

**Comment by rwinch** [comment]
This issue duplicates #1382
