### ISSUE TITLE
State mismatch due to URL encoding

### ISSUE THREAD

**Issue by ZIRAKrezovic** [spring-projects/spring-security#16309]
**Describe the bug**

State parameter is generated using Base64 url encoder [1]. It ends up containing an "equals" sign at the end most of the time, for example

![image](https://github.com/user-attachments/assets/7ba19e99-a37e-497b-8e2d-726995d1f7c7)

When passing the state as query parameter, it gets uri encoded [2]

The state in the URL looks like

![image](https://github.com/user-attachments/assets/63270aaa-19b6-453f-8631-0c707c60abf8)

When processing OIDC callback, the state is decoded without URL decode in [3]

(the pictures diverge here, my login attempt expired while writing the bug - but both request and response can be seen)

![image](https://github.com/user-attachments/assets/87c1181a-05b8-4987-aa78-0faab9b358e4)

This results in `invalid_state_parameter` error within OidcAuthorizationCodeReactiveAuthenticationManager

![{3AF0188A-2210-4353-A03E-F8AF623886E5}](https://github.com/user-attachments/assets/aef9f205-ef51-4cbb-854c-c12ee6ca9c71)

[1] https://github.com/spring-projects/spring-security/blob/main/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/server/DefaultServerOAuth2AuthorizationRequestResolver.java#L82
[2] https://github.com/spring-projects/spring-security/blob/main/oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/endpoint/OAuth2AuthorizationRequest.java#L455
[3] https://github.com/spring-projects/spring-security/blob/main/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/server/OAuth2AuthorizationResponseUtils.java#L68

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Sample**

A link to a GitHub repository with a [minimal, reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).

Reports that include a sample will take priority over reports that do not.
At times, we may require a sample, so it is good to try and include a sample up front.

**Comment by kse-music** [comment]
Based on your description, I don't see any issues in my local. Could you provide a minimal sample that reproduces the steps? I'd be happy to take a look.

Ps: I'm tested in Spring Boot 3.4.1.

**Comment by ZIRAKrezovic** [comment]
I cannot reproduce it with Spring Boot 3.4. I am stuck on 3.2, which is out of OSS support. Closing.

**Comment by xuchen-plus** [comment]
We actually encountered the same issue with Springboot 4.0.6 with spring-security 7.0.5. We ended up with customized authorizationRequestResolver using uuid as state:
```java
@Bean
public ServerOAuth2AuthorizationRequestResolver authorizationRequestResolver(
        ReactiveClientRegistrationRepository clientRegistrationRepository) {

    DefaultServerOAuth2AuthorizationRequestResolver resolver =
            new DefaultServerOAuth2AuthorizationRequestResolver(clientRegistrationRepository);

    // Customize the state parameter generation
    resolver.setAuthorizationRequestCustomizer(builder ->
            builder.state(UUID.randomUUID().toString().replace("-", ""))
    );

    return resolver;
}
```
Then pass this resolver to `oauth2Login`.
