### ISSUE TITLE
how to config httpclient timeout in spring gateway?

### ISSUE THREAD

**Issue by hogger0** [spring-projects/spring-security#16315]
When the server ip of the auth server is incorrectly written, or the server is unavailable, the timeout time configured according to the document does not work, and the default is like 30 seconds.
```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
</dependency>
```
The following link is a description of the problem, take a look
[https://github.com/spring-cloud/spring-cloud-gateway/issues/3652](url)

**Comment by kse-music** [comment]
You can try define implements  `JwkSetUriJwtDecoderBuilderCustomizer `interface like so
 ```
   @Component
    public class CustomJwkSetUriJwtDecoderBuilderCustomizer implements JwkSetUriJwtDecoderBuilderCustomizer {

        @Override
        public void customize(NimbusJwtDecoder.JwkSetUriJwtDecoderBuilder builder) {
            RestTemplateBuilder restTemplateBuilder = new RestTemplateBuilder();
            restTemplateBuilder.connectTimeout(Duration.ofSeconds(60));
            builder.restOperations(restTemplateBuilder.connectTimeout(Duration.ofSeconds(10)).build());
        }
        
    }
```

**Comment by hogger0** [comment]
> You can try define implements `JwkSetUriJwtDecoderBuilderCustomizer `interface like so
> 
> ```
>   @Component
>    public class CustomJwkSetUriJwtDecoderBuilderCustomizer implements JwkSetUriJwtDecoderBuilderCustomizer {
> 
>        @Override
>        public void customize(NimbusJwtDecoder.JwkSetUriJwtDecoderBuilder builder) {
>            RestTemplateBuilder restTemplateBuilder = new RestTemplateBuilder();
>            restTemplateBuilder.connectTimeout(Duration.ofSeconds(60));
>            builder.restOperations(restTemplateBuilder.connectTimeout(Duration.ofSeconds(10)).build());
>        }
>        
>    }
> ```

It seems to be the same result。

**Comment by hogger0** [comment]
> You can try define implements `JwkSetUriJwtDecoderBuilderCustomizer `interface like so
> 
> ```
>   @Component
>    public class CustomJwkSetUriJwtDecoderBuilderCustomizer implements JwkSetUriJwtDecoderBuilderCustomizer {
> 
>        @Override
>        public void customize(NimbusJwtDecoder.JwkSetUriJwtDecoderBuilder builder) {
>            RestTemplateBuilder restTemplateBuilder = new RestTemplateBuilder();
>            restTemplateBuilder.connectTimeout(Duration.ofSeconds(60));
>            builder.restOperations(restTemplateBuilder.connectTimeout(Duration.ofSeconds(10)).build());
>        }
>        
>    }
> ```

```java
@Component
public class CustomJwkSetUriJwtDecoderBuilderCustomizer implements JwkSetUriJwtDecoderBuilderCustomizer {
    @Override
    public void customize(NimbusJwtDecoder.JwkSetUriJwtDecoderBuilder builder) {
        RestTemplateBuilder restTemplateBuilder = new RestTemplateBuilder();
        restTemplateBuilder.setConnectTimeout(Duration.ofSeconds(10));
        restTemplateBuilder.setReadTimeout(Duration.ofSeconds(10));
        RestTemplate build = restTemplateBuilder.build();
        builder.restOperations(build);
    }
}
```

**Comment by kse-music** [comment]
If you use Reactive please define `JwkSetUriReactiveJwtDecoderBuilderCustomizer ` implements  like so
 
```
    @Component
    public class CustomJwkSetUriReactiveJwtDecoderBuilderCustomizer implements JwkSetUriReactiveJwtDecoderBuilderCustomizer {

        @Override
        public void customize(NimbusReactiveJwtDecoder.JwkSetUriReactiveJwtDecoderBuilder builder) {
            HttpClient httpClient = HttpClient.create().responseTimeout(Duration.ofSeconds(10))
                    .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, (int) Duration.ofSeconds(10).toMillis());
            ReactorClientHttpConnector connector = new ReactorClientHttpConnector(httpClient);
            builder.webClient(WebClient.builder().clientConnector(connector).build());
        }
    }
```

**Comment by hogger0** [comment]
> @Override
>         public void customize(NimbusReactiveJwtDecoder.JwkSetUriReactiveJwtDecoderBuilder builder) {
>             HttpClient httpClient = HttpClient.create().responseTimeout(Duration.ofSeconds(10))
>                     .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, (int) Duration.ofSeconds(10).toMillis());
>             ReactorClientHttpConnector connector = new ReactorClientHttpConnector(httpClient);
>             builder.webClient(WebClient.builder().clientConnector(connector).build());
>         }

All right ，as expected。
thank you。
