### ISSUE TITLE
SEC-1394: Credentials stored in authentication object

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1637]
[Jarrod Carlson](https://jira.spring.io/secure/ViewProfile.jspa?name=jcarlson) (Migrated from [SEC-1394](https://jira.spring.io/browse/SEC-1394?redirect=false)) said:

Maybe I'm missing something obvious, but is there a reason that after a successful login (using the <form-login /> approach) the "credentials" from login (the user's password) are kept in clear text in the Authentication object stored in the SecurityContext?

After login, any part of my application can simply do:

<code>SecurityContextHolder.getContext().getAuthenticati on().getCredentials();</code>

This returns the plain-text password supplied at login, even if login was dozens of requests ago. Why is this? Does that not seem somewhat insecure to anyone else?

**Comment by rwinch** [comment]
This issue duplicates #1616
