### ISSUE TITLE
SEC-1406: Create a DelegatingAuthenticationEntryPoint

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1651]
[Mike Wiesner](https://jira.spring.io/secure/ViewProfile.jspa?name=mikewiesner) (Migrated from [SEC-1406](https://jira.spring.io/browse/SEC-1406?redirect=false)) said:

It is sometime required that different AuthenticationEntryPoints are selected based on request information such as IP-Address or other headers. For example, one might use Kerberos SSO automatically only for requests which come from the LAN and for everything else a HTML form or Basic.

A DelegatingAuthenticationEntryPoint will select between different AuthenticationEntryPoints based on a RequestMatcher (SEC-1405)

**Comment by spring-issuemaster** [comment]
This issue depends on #1650
This issue supersedes https://jira.spring.io/browse/SES-32

**Comment by spring-issuemaster** [comment]
This issue depends on #1650
This issue supersedes https://jira.spring.io/browse/SES-32

**Comment by spring-issuemaster** [comment]
This issue depends on #1650
This issue supersedes https://jira.spring.io/browse/SES-32

**Comment by spring-issuemaster** [comment]
This issue depends on #1650
This issue supersedes https://jira.spring.io/browse/SES-32

**Comment by spring-issuemaster** [comment]
This issue depends on #1650
This issue supersedes https://jira.spring.io/browse/SES-32

**Comment by spring-issuemaster** [comment]
This issue depends on #1650
This issue supersedes https://jira.spring.io/browse/SES-32

**Comment by spring-issuemaster** [comment]
This issue depends on #1650
This issue supersedes https://jira.spring.io/browse/SES-32

**Comment by spring-issuemaster** [comment]
This issue depends on #1650
This issue supersedes https://jira.spring.io/browse/SES-32

**Comment by spring-issuemaster** [comment]
This issue depends on #1650
This issue supersedes https://jira.spring.io/browse/SES-32
