### ISSUE TITLE
SEC-1407: Refactor URL Matching to use RequestMatcher interface

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1652]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1407](https://jira.spring.io/browse/SEC-1407?redirect=false)) said:

At the moment classes like FilterChainProxy and DefaultFilterInvocationSecurityMetadataSource use a UrlMatcher and store a map of paths (patterns). They do the work of converting incoming URLs to lower case etc.

It would make more sense if they used RequestMatchers as the Map key, with Ant and Regex path matchers a special case. This would allow for more flexible request matching and also for cleaner code, as the matcher implementations would encapsulate the upper/lower case logic etc.

**Comment by spring-issuemaster** [comment]
This issue supersedes #1670

**Comment by spring-issuemaster** [comment]
This issue supersedes #1670

**Comment by spring-issuemaster** [comment]
This issue supersedes #1670
