### ISSUE TITLE
SEC-1431: Make OpenID sample work with Yahoo and Google

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1674]
Migrated from [SEC-1431](https://jira.spring.io/browse/SEC-1431?redirect=false)

**Comment by spring-issuemaster** [comment]
This issue depends on #1700

**Comment by spring-issuemaster** [comment]
This issue depends on #1700

**Comment by spring-issuemaster** [comment]
This issue depends on #1700
