### ISSUE TITLE
SEC-1438: Remove JoinPoint support from AbstractSecurityMetadataSource

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1681]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1438](https://jira.spring.io/browse/SEC-1438?redirect=false)) said:

Following the changes for SEC-1262, this should no longer be required.

**Comment by spring-issuemaster** [comment]
This issue is related to #1511

**Comment by spring-issuemaster** [comment]
This issue is related to #1511

**Comment by spring-issuemaster** [comment]
This issue is related to #1511
