### ISSUE TITLE
SEC-1463: Users defined in XML can't login when their username contains capital

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1703]
[Hans Desmet](https://jira.spring.io/secure/ViewProfile.jspa?name=desmethans) (Migrated from [SEC-1463](https://jira.spring.io/browse/SEC-1463?redirect=false)) said:

The following users (see reference documentation), defined in XML, can login:
<authentication-manager>
    <authentication-provider>
      <user-service>
        <user name="jimi" password="jimispassword" authorities="ROLE_USER, ROLE_ADMIN" />
        <user name="bob" password="bobspassword" authorities="ROLE_USER" />
      </user-service>
    </authentication-provider>
  </authentication-manager>

When the usernames begin with a capital, those users can't login.
When submmitting the default form generated by <form-login> you get an error: Your login attempt was not successful, try again. Reason: Bad credentials
<authentication-manager>
    <authentication-provider>
      <user-service>
        <user name="Jimi" password="jimispassword" authorities="ROLE_USER, ROLE_ADMIN" />
        <user name="Bob" password="bobspassword" authorities="ROLE_USER" />
      </user-service>
    </authentication-provider>
  </authentication-manager>

When you define users in a datbase (via <jdbc-user-serivce>) this problem doesn't occur.

**Comment by spring-issuemaster** [comment]
This issue is related to #1704
