### ISSUE TITLE
SEC-1471: Session-based request playback can fail when multiple windows share the same session

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1710]
[Keith Donald](https://jira.spring.io/secure/ViewProfile.jspa?name=kdonald) (Migrated from [SEC-1471](https://jira.spring.io/browse/SEC-1471?redirect=false)) said:

My use case:
- Two brower windows are open.  One displaying a secure page that is doing some Ajax polling.  Another displaying the application index page.
- Suppose on the index page I click "Sign Out".  The poller running on the secure page continues to poll, but it's now receiving authentication entry point redirect responses (since I'm no longer authenticated).  This particular poller expects JSON content, so it is ignoring the HTML content generated by following the sigin-in redirect.
- Now lets say I access a secure page from the window displaying the index page by clicking a secure link.  I'm not authenticated, so I get redirected to the sign-in page.  All is good. However, after login, I get erroneously redirected back to the poller's resource (/messages) URL instead of the secure link I selected, because it was the last request to be executed in that session.  In my app, I actually get a Download dialog for a JSON file, which is obviously not correct.  Closing the window doing the polling resolves the problem when I try to re-authenticate.

The problem here seems to be use of session scope for storage of the last request when multiple windows are open concurrently.

**Comment by spring-issuemaster** [comment]
This issue supersedes #772
