### ISSUE TITLE
SEC-1490: Google App Engine authentication support

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1729]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1490](https://jira.spring.io/browse/SEC-1490?redirect=false)) said:

Direct support for authenticating users in GAE. This would probably consist of two parts:
1. an AuthenticationEntryPoint which calls the GAE UserService to provide an authentication URL (http://code.google.com/appengine/docs/java/users/overview.html)
2. A standard JEE Pre-Authentication configuration, accessing the servlet API to obtain the user ID (http://code.google.com/appengine/docs/java/config/webxml.html#Security_and_Authentication). See SEC-1093.

By using the pre-authentication framework, we can easily supplement the limited functionality that GAE appears to provide in terms of user roles etc.

**Comment by spring-issuemaster** [comment]
This issue depends on #1344
