### ISSUE TITLE
SEC-1491: Add support for Enum in Secured Annotation

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1730]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1491](https://jira.spring.io/browse/SEC-1491?redirect=false)) said:

In an RBAC style application, with operations protected by specific "rights" rather than roles, it makes sense to define these rights using an enum. The Secured annotation should support an additional attribute which directly provides a collection of ConfigAttributes that are required, in addition to the current approach of using Strings. The Enum should implement ConfigAttribute, and also potentially GrantedAuthority, to provide efficient lookup in a custom voter which takes into account the use of an authority set (or EnumSet) to store the current user's authorities.

SecuredAnnotationSecurityMetadataSource needs to be altered to support the extra attribute on the annotation.

**Comment by spring-issuemaster** [comment]
This issue depends on #1943
