### ISSUE TITLE
SEC-1492: Support generic mapping of user attributes to GrantedAuthorities throughout the framework

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1732]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1492](https://jira.spring.io/browse/SEC-1492?redirect=false)) said:

Currently, AuthenticationProvider/UserDetailsService implementations do not have a consistent way of creating authorities (case-conversions, role prefixes, mapping to rights etc). It would make sense to inject an Attributes2GrantedAuthoritiesMapper instance which can be used to provide full control over the authority values. This can also be used to implement RBAC style rights, performing mapping of assigned roles to permissions recognised by the application.

**Comment by spring-issuemaster** [comment]
This issue is related to #1730
This issue supersedes #1432
