### ISSUE TITLE
SEC-1500: Target-URL changes while switching between secure and insecure channel, when it was encoded according to RFC 3986

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1743]
[Kai Moritz](https://jira.spring.io/secure/ViewProfile.jspa?name=kai.moritz) (Migrated from [SEC-1500](https://jira.spring.io/browse/SEC-1500?redirect=false)) said:

This issue is simmilar to the issue SEC-1255 "Target-URL after successfull login differes from original URL, when it was encoded according to RFC 3986"
http://jira.springframework.org/browse/SEC-1255

When switching the channel, AbstractRetryEntryPoint rebuilds the URL from its decoded parts.
So, when switching on a URL, that containes a special character (like '?'), which is encoded according to RFC 3986, it changes the URL.
For example, the URL "/foo%3Fbar.html", where "%3F" encodes the "?", becomes "/foo?bar.html", which is not encoded correctly, thus resulting in a 404-Error.

Encoding the rebuild URL would not work, becaus all special characters (like contained slashes for example) would be encoded than, which is, as far as I know, not correct. 

I fixed the issue in my local git repository by calling the UrlUtils, which were fixed in issue SEC-1255, for building the redirect URL.
I will apply my patch to this bug-report.

**Comment by spring-issuemaster** [comment]
This issue is related to #1656
