### ISSUE TITLE
SEC-1502: The Session Management Filter can throw exception in the case of session time-out

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1746]
[Mohamed Elsayed Sahmoud](https://jira.spring.io/secure/ViewProfile.jspa?name=msahmoud) (Migrated from [SEC-1502](https://jira.spring.io/browse/SEC-1502?redirect=false)) said:

I am developing an application using Flex as UI and Java as server side core. I am facing an issue for handling session time-out since the only option available is redirecting the the response to a URL otherwise the system will throw access denied exception.

I hope you can add a new improvement in the configurations that allow throwing exception in the case of session time-out if configured.

**Comment by rwinch** [comment]
You can configure a custom `InvalidSessionStrategy` to handle invalid sessions in a custom way.
