### ISSUE TITLE
SEC-1515: Radius based authentication

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1756]
[Ido Tzang](https://jira.spring.io/secure/ViewProfile.jspa?name=idotzang) (Migrated from [SEC-1515](https://jira.spring.io/browse/SEC-1515?redirect=false)) said:

I'd love to see some Radius authentication capabilities built into Spring Security.
I have a requirement in one of my projects to add Radius based auth. (we currently uses LDAP and JDBC) 

In the forum post I attached (http://forum.springsource.org/showthread.php?t=37184), haroon.rafique posted his solution.

Thanks !

**Comment by rwinch** [comment]
Closing as we don't plan on implementing this and no contribution was submitted
