### ISSUE TITLE
SEC-1516: Create Security Context Accessor interface

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1757]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1516](https://jira.spring.io/browse/SEC-1516?redirect=false)) said:

The current approach for accessing the security context in user code involves using the SecurityContextHolder directly, which is quite cumbersome in unit tests and involves setting up a context beforehand and tearing it down to avoid leaking threadlocals.

Using an interface which could be injected into components which want to use programmatic security would allow mocking and could also provide methods to make it easier to perform common functions such as looking up authorities.

It's also possible that some internal components which require access to the context could make use of the same interface

**Comment by spring-issuemaster** [comment]
This issue supersedes #1790

**Comment by rwinch** [comment]
User's wishing to do this should leverage `Supplier<SecurityContext>`
