### ISSUE TITLE
SEC-1527: Internationalize one of the sample applications

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1768]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1527](https://jira.spring.io/browse/SEC-1527?redirect=false)) said:

People get confused because Spring Security's filters don't automatically suppport i18n, even when it is working in Spring MVC. Adding support to one of the sample applications would provide a useful reference.

**Comment by rajadileepkolli** [comment]
Where is the sample available?? Can we create an hyperlink so that users can refer it

**Comment by vikasvats** [comment]
hi luke,

Could you please provide any link to the sample or config code for this ?

Thanks

**Comment by php-coder** [comment]
I'm also interested in having such example.

CC @rwinch
