### ISSUE TITLE
SEC-1528: HttpSession.setAttribute() must be called if the SecurityContext is modified during a request

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1769]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1528](https://jira.spring.io/browse/SEC-1528?redirect=false)) said:

The current logic in HttpSessionSecurityContextRepository does not set the session attribute if it finds that the current thread-local context matches the value in the session. This works fine in a single JVM. However, in a cluster or cloud environment where requests for the same session may be handled in different JVMs, the changes must be propagated to other nodes and the setAttribute() call is required to achieve this.

**Comment by spring-issuemaster** [comment]
This issue is related to #1552
