### ISSUE TITLE
SEC-1538: Reduce number of pre-authenticated AuthenticationDetails implementations

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1780]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1538](https://jira.spring.io/browse/SEC-1538?redirect=false)) said:

I don't believe we need PreAuthenticatedGrantedAuthoritiesWebAuthenticationDetails and PreAuthenticatedGrantedAuthoritiesAuthenticationDetails. If they are used at all it is a minority of situations where a custom implementation should be used. Pre-authentication is part of the web module and assumes a dependency on the servlet API, so these extra implementations seem largely redundant.

**Comment by spring-issuemaster** [comment]
This issue is related to #1781
