### ISSUE TITLE
SEC-1539: More flexible run-as authentication and security context propagation support

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1781]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1539](https://jira.spring.io/browse/SEC-1539?redirect=false)) said:

It should be possible to set up infrastructure for running a service (or service method) with a particular SecurityContext. This could be done either to satisfy internal security constraints within the application or to allow the propagation of credentials for invoking a remote service (e.g. s3), which would also require protocol-specific integration. This would thus be a superset of the existing run-as functionality which would be superseded and removed from the security interceptor. It would also supersede functionality like the WebSphere2SpringSecurityPropagationInterceptor.

**Comment by rwinch** [comment]
This can be done using [`DelegatingSecurityContextRunnable`](https://docs.spring.io/spring-security/site/docs/5.5.x/reference/html5/#delegatingsecuritycontextrunnable)
