### ISSUE TITLE
SEC-1557: add a getter method to DelegatingMethodSecurityMetadataSource

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1798]
[Wolfgang Winter](https://jira.spring.io/secure/ViewProfile.jspa?name=wwinter) (Migrated from [SEC-1557](https://jira.spring.io/browse/SEC-1557?redirect=false)) said:

Hi,

For the next release of Cibet control framework (www.logitags.com/cibet) I have integrated Spring Security authorization. It was possible but I had to do some 'dirty' hacks which could be avoided if Spring Security provides some very small changes:

I exchange the DelegatingMethodSecurityMetadataSource in MethodSecurityInterceptor with an own implementation CibetDelegatingMethodSecurityMetadataSource.  My implementation must work also with standard Spring Security authorization. Therefore I need to set the list of MethodSecurityMetadataSource from DelegatingMethodSecurityMetadataSource into my CibetDelegatingMethodSecurityMetadataSource. 

Problem: Not possible because getter is missing. 
Workaround: I use field access reflection on private field methodSecurityMetadataSources (dirty hack)
Solution: add a getter to DelegatingMethodSecurityMetadataSource:

public List getMethodSecurityMetadataSources() {
  return methodSecurityMetadataSources;
}

**Comment by spring-issuemaster** [comment]
This issue relates to #1799
