### ISSUE TITLE
SEC-1560: AccessControlListTag should use PermissionEvaluator

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1801]
[Thomas Champagne](https://jira.spring.io/secure/ViewProfile.jspa?name=lafeuil) (Migrated from [SEC-1560](https://jira.spring.io/browse/SEC-1560?redirect=false)) said:

With the version 3.0, I think AccessControlListTag should use the new interface PermissionEvaluator to check the permission on an object.

I join a new AccessControlListTag that gets the permissionEvaluator from spring context. It is based on the current code.

**Comment by spring-issuemaster** [comment]
This issue relates to #2246
This issue relates to #2248
