### ISSUE TITLE
SEC-1566: There is a bug in the Spring Security security.tld file

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1807]
[Wang Yiming](https://jira.spring.io/secure/ViewProfile.jspa?name=wym0291) (Migrated from [SEC-1566](https://jira.spring.io/browse/SEC-1566?redirect=false)) said:

There is a bug in the Spring Security security.tld file. 

```
    <attribute> 
        <description>Set HTML escaping for this tag, as a boolean value.</description> 
        <name>htmlEscape</name> 
        <required>false</required> 
        <rtexprvalue>true</rtexprvalue> 
    </attribute> 
```

should be 

```
    <attribute> 
        <name>htmlEscape</name> 
        <required>false</required> 
        <rtexprvalue>true</rtexprvalue> 
        <description>Set HTML escaping for this tag, as a boolean value.</description> 
    </attribute> 
```

Caused by: org.jboss.xb.binding.JBossXBException: Failed to parse source: The content of element type "attribute" must match "(name,required?,rtexprvalue?,type?,description?)". @ vfs:///Users/matt/Projects/qato/deploy/qato.war/WEB-INF/lib/spring-security-taglibs-3.0.3.RELEASE.jar/META-INF/security.tld[117,21]

**Comment by spring-issuemaster** [comment]
This issue duplicates #1739
