### ISSUE TITLE
SEC-1628: add authentication-success-handler to <remember-me> tag

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1821]
[Christopher Smith](https://jira.spring.io/secure/ViewProfile.jspa?name=w_c_smith) (Migrated from [SEC-1628](https://jira.spring.io/browse/SEC-1628?redirect=false)) said:

We are using an AuthenticationSuccessHandler to post-process login information to cache attributes into the HttpSession (we're using a third-party servlet that can handle some database queries by itself but needs the appropriate keys, etc.).  However, after a remember-me login, there is no way to insert a success handler to perform the appropriate initialization for the new session.

It would be helpful to have an authentication-success-handler-ref attribute on the <remember-me> tag analogous to the attribute on the <*-login> tags, triggered after the RememberMeServices handles a persistent login.

(The forum link is not my post, but there appears to be a significant desire for this feature.)

**Comment by spring-issuemaster** [comment]
This issue duplicates #1842
