### ISSUE TITLE
SEC-1594: HttpSessionContextIntegration filter assumes that the authentication is the only part of the security context which should determine if it is saved in the session

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1833]
[Paudi Moriarty](https://jira.spring.io/secure/ViewProfile.jspa?name=pmoriarty) (Migrated from [SEC-1594](https://jira.spring.io/browse/SEC-1594?redirect=false)) said:

The use of authenticationTrustResolver.isAnonymous(Authentication) to determine whether the context should be stored in the session does not allow for this to be decided based on _other_ parts of the context or even other aspects of the Authentication!

Would be better to use a separate class to decide this based on the entire SecurityContext rather than reusing the AuthenticationTrustResolver in this way.

The default could still use authenticationTrustResolver.isAnonymous (via delegation) but I should be able to decide for myself when I want the context to be stored in the session.

**Comment by rwinch** [comment]
If you want to remove authenticationTrustResolver.isAnonymous check you can replace the AuthenticationTrustResolver with a custom implementation that returns true all of the time.
