### ISSUE TITLE
SEC-1657: Support naming of filter chains in the namespace to allow for easier integration with external services like OAuth

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1853]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1657](https://jira.spring.io/browse/SEC-1657?redirect=false)) said:

Since the namespace now supports multiple filter chains, this will allow an id to be added for each list of filters in the bean registry, which will make it easier for other services such as OAuth to specify which filter chain they want to integrate with.

**Comment by spring-issuemaster** [comment]
This issue relates to #1963
