### ISSUE TITLE
SEC-1614: Status 404 with Apache Tiles

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1855]
[Johannes Scharf](https://jira.spring.io/secure/ViewProfile.jspa?name=scharfj) (Migrated from [SEC-1614](https://jira.spring.io/browse/SEC-1614?redirect=false)) said:

We use Apache Tiles 2.1.4 to render our pages. After we've upgraded to Spring Security 3.0.4 we received a "HTTP Status 404" error page from tomcat when accessing some pages.
When we use a custom HttpFirewall and FirewalledRequest, which does nothing, the errors disappear.

As far as I found out all pages are impacted which are "excluded" from Spring Security's FilterChainProxy, as our login and logout pages for example.
I think that issue is related to SEC-1608. 

Tiles does various forwards/includes during the rendering phase which (obviously) will change the ServletPath and PathInfo
To track down the error, I've developed a custom "RequestWrapper" which outputs the original and stripped version of the ServletPath and PathInfo:
Constructor - StrippedServletPath: /main - StrippedPathInfo: /login/login.htm
getServletPath() - stripPaths: true - strippedServletPath: /main - servletPath: /main
getPathInfo() - stripPaths: true - strippedPathInfo: /login/login.htm - pathInfo: /login/login.htm
getServletPath() - stripPaths: true - strippedServletPath: /main - servletPath: /main
getServletPath() - stripPaths: true - strippedServletPath: /main - servletPath: /main
getServletPath() - stripPaths: true - strippedServletPath: /main - servletPath: /main
getPathInfo() - stripPaths: true - strippedPathInfo: /login/login.htm - pathInfo: /login/login.htm
getServletPath() - stripPaths: true - strippedServletPath: /main - servletPath: /WEB-INF/layouts/plain.jsp

As you can see at the end of the request the "strippedServletPath" and "servletPath" are different while "stripPaths" is still true. Therefore the "wrong" stripped ServletPath gets returned and Tiles fails to render the response correctly.
getPathInfo() - stripPaths: true - strippedPathInfo: /login/login.htm - pathInfo: null

**Comment by spring-issuemaster** [comment]
This issue duplicates #1848
