### ISSUE TITLE
SEC-1627: Global method security in dmServer causing ReflectionWorldException

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1868]
[Igor Mihalik](https://jira.spring.io/secure/ViewProfile.jspa?name=imihalik) (Migrated from [SEC-1627](https://jira.spring.io/browse/SEC-1627?redirect=false)) said:

There's a problem if spring-security is used in application deployed to dmServer. At happens when "global-method-security" is defined in spring context. When using "global-method-security" "org.springframework.security.config.method.ProtectPointcutPostProcessor" is created. However in dmServer "OsgiServiceFactoryBean" bean is created by default in application context and "PPPP" tries to match "OSFB" with the given expression. 

If application bundle does not "import" package "org.springframework.osgi.service.exporter.support" an exception is thrown (attached). One option is to declare "import" in spring-security-config bundle, however that would bias spring-security towards dmServer.

Other option, and that is what is proposed in this improvement, suggests to modify the attemptMatch (#107) method in org.springframework.security.config.method.ProtectPointcutPostProcessor to handle reflection exception. 

Currently attemptMatch reads like this:
<code>
  // Determine if the presented AspectJ pointcut expression matches this method
  boolean matches = expression.matchesMethodExecution(method).alwaysMatches();
</code>

Proposed change:
<code>
  // Determine if the presented AspectJ pointcut expression matches this method
   boolean matches = false;
  try {
    matches = expression.matchesMethodExecution(method).alwaysMatches();
  } catch (ReflectionWorld.ReflectionWorldException ex) {
    // no match
  }
</code>

An exception occurring there could easily be interpreted as a non match.

---

**Comment by rwinch** [comment]
Thank you for the report.

Spring Security intentionally removed OSGi support as part of SEC-2506 This is because Spring's [OSGi repository is now frozen](http://ebr.springsource.com/repository/app/faq#q2) and [Spring Framework](https://jira.spring.io/browse/SPR-8903?focusedCommentId=95987&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-95987) (which Spring Security depends on) no longer supports OSGi.

> The SpringSource EBR was made read-only in September, so Spring Framework 3.2.x (and any other) releases after that date will not be published there. Please refer to [the FAQ](http://ebr.springsource.com/repository/app/faq;jsessionid=8D7AE5A1694DCB1E680FEAFB21FE1B3D.jvm1#q2) and the [announcement](http://www.eclipse.org/forums/index.php/t/516636/) over in the [Eclipse Bundle Recipes](http://eclipse.org/ebr/) project which should be the successor to the SpringSource EBR.
> 
> SpringSource made available the [necessary information](http://www.eclipse.org/forums/index.php/t/513222/) for the community to take over creation of OSGi bundles for Spring Framework, so you may like to collaborate with others in the creation of Spring Framework 3.2.5 bundles which could then be published to Maven Central.
