### ISSUE TITLE
SEC-1629: Add @WithPermission annotation

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1869]
[Michiel Trimpe](https://jira.spring.io/secure/ViewProfile.jspa?name=mtrimpe) (Migrated from [SEC-1629](https://jira.spring.io/browse/SEC-1629?redirect=false)) said:

Please consider adding the @WithPermission annotation which can be used to prevent a large number of Pre/Post annotations like:

```
@PreAuthorize("hasPermission(#contact, 'admin')")
@PostFilter("hasPermission(filterObject, 'read')")
```

and replace them with:

```
    public void delete(@WithPermission Interview interview) {
        em.remove(interview);
    }

    public @WithPermission Interview find(long interviewId) {
        return em.find(Interview.class, interviewId);
    }
```

**Comment by rwinch** [comment]
You can create your own annotation and it will be picked up by the framework through Spring's meta-annotation support. For example:

```java
@Retention(RetentionPolicy.RUNTIME)
@PreAuthorize("hasPermission(#contact, 'admin')")
@PostFilter("hasPermission(filterObject, 'read')")
public @interface WithPermission {
}
```

NOTE: We cannot really create the annotation for users as we don't know the arguments to `hasPermission`.
