### ISSUE TITLE
SEC-1658: JA-SIG CAS Single Sign Out feature conflict with session-fixation protection

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1897]
[DUBOIS Fabrice](https://jira.spring.io/secure/ViewProfile.jspa?name=fdubois92) (Migrated from [SEC-1658](https://jira.spring.io/browse/SEC-1658?redirect=false)) said:

I run into problems with CAS Single Sign Out feature working with session-fixation protection feature.

Indeed, Spring Security ConcurrentSessionControlStrategy always invalidate the existing session (call of session.invalidate( )) and create a new one to prevent from session-fixation attacks.

So, after CAS login process, SingleSignOutHttpSessionListener.sessionDestroyed( ) is called causing "ST to original session mapping" to be removed from SingleSignOutFilter's SESSION_MAPPING_STORAGE member.

When a single sign out request is posted, the new session isn't invalidated because "ST to new session mapping" was never been registered in SingleSingOutFilter's SESSION_MAPPING_STORAGE member.

**Comment by jgribonvald** [comment]
Thanks for the tip this helped me a lot !

Just one other tip : you need to update authentication details on implementing a custom SessionFixatgionProtectionStrategy else you keep in authentication object the old sessionId (not totaly usefull, it's only for logging event that used this object)

**Comment by rwinch** [comment]
This should be changed in CAS rather than Spring Security

**Comment by nchava1** [comment]
Hi. How this was fixed? I see same issue on spring 5.x and cas server 6.5.4 and cas client 3.1.12.

Thanks
