### ISSUE TITLE
SEC-1687: Refactor SecurityExpressionRoot as an Interface rather than an Abstract Class

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1906]
[Benjamin Goh](https://jira.spring.io/secure/ViewProfile.jspa?name=masotime) (Migrated from [SEC-1687](https://jira.spring.io/browse/SEC-1687?redirect=false)) said:

3.1.x introduced refactoring of the SecurityHandlers, particularly with the introduction of the AbstractSecurityExpressionHandler<T>, which provides a very convenient abstract method createSecurityExpressionRoot that makes it easy for the developer to define their own SecurityExpressionHandler.

However, the return type is set as SecurityExpressionRoot, which is an abstract class that enforces a parameterized constructor which passes in an Authentication object.

It would be more convenient if SecurityExpressionRoot is an interface rather than an abstract class, with the current SecurityExpressionRoot remaining as an abstract class that implements this interface.  This would allow a developer more flexibility in writing their own SecurityExpressionRoot (opting to implement the interface manually or extend the abstract class).

More specifically, the current SecurityExpressionRoot, by enforcing that a runtime entity (the Authentication object) be part of its construction, makes it impossible to define it as a Spring managed bean, making it difficult to inject services such as a SessionFactory or to apply automatic transactional advice with e.g. @Transactional.  As an interface, and in combination with Lookup Method Injection (http://static.springsource.org/spring/docs/3.0.x/spring-framework-reference/html/beans.html#beans-factory-lookup-method-injection), it would be possible to define a custom prototype-scoped SecurityExpressionRoot with easy access to Spring-injected services.

**Comment by spring-issuemaster** [comment]
This issue relates to #1928
