### ISSUE TITLE
SEC-1721: "Double securing" very sensitive actions with explicit Login/Authentication

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1935]
[Konstantinos Kostarellis](https://jira.spring.io/secure/ViewProfile.jspa?name=kosta) (Migrated from [SEC-1721](https://jira.spring.io/browse/SEC-1721?redirect=false)) said:

It would be great to have an option in the style of the token "IS_AUTHENTICATED_FULLY / isFullyAuthenticated()" to let the user re-authenticate for certain very sensitive actions.

Thinking of it in a way of making the user aware that he is now doing something major, similar to sudo on linux and osx. (IS_AUTHENTICATED_EXPLICITLY / isExplicitlyAuthenticated()).

Is this something that can be implemented by a CustomVoter ?

**Comment by rwinch** [comment]
This is superseded by gh-2603
