### ISSUE TITLE
SEC-1704: add flag ExceptionMappingAuthenticationFailureHandler to decide if we want to save exception.

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1941]
[chun ping wang](https://jira.spring.io/secure/ViewProfile.jspa?name=cablepuff) (Migrated from [SEC-1704](https://jira.spring.io/browse/SEC-1704?redirect=false)) said:

currently the ExceptionMappingAuthenticationFailureHandler does not save the exception populated by SimpleUrlAuthenticationFailureHandler. 

Their should be flag that overrides it, to allow saving of exception. 

onAuthenticationFailure(....) {
   if (saveException) {
       super.saveException(..);
   }
    .....
   super.onAuthenticationFailure(..)
}

This way user don't need to extend a class just so that they can get the authentication exception.

**Comment by rwinch** [comment]
To achieve this you can leverage `DelegatingAuthenticationFailureHandler` which allows mapping the `Exception` to an arbitrary `AuthenticationFailureHandler` including `SimpleUrlAuthenticationFailureHandler` which will persist the `Exception`.
