### ISSUE TITLE
SEC-1709: AbstractAuthenticationToken does not define a serialVersionUID

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1945]
[Jeff Martin](https://jira.spring.io/secure/ViewProfile.jspa?name=jeff.martin) (Migrated from [SEC-1709](https://jira.spring.io/browse/SEC-1709?redirect=false)) said:

Similar to SEC-338, org.springframework.security.authentication.AbstractAuthenticationToken does not define a serialVersionUID. This is causing failures in our development environment because we pass an authentication token around in RMI (thus the serialization). The exception is:

2011-03-26 13:29:11,278 ERROR [STDERR](http-0.0.0.0-8280-1) Caused by: org.springframework.remoting.RemoteAccessException: Could not access remote service [rmi://x.x.x.x:x/RmiAdapter]; nested exception is java.rmi.ServerException: RemoteException occurred in server thread; nested exception is: 
       java.rmi.UnmarshalException: error unmarshalling arguments; nested exception is: 
       java.io.InvalidClassException: org.springframework.security.authentication.AbstractAuthenticationToken; local class incompatible: stream classdesc serialVersionUID = -3194696462184782834, local class serialVersionUID = 1043617290326266361

Please add a serialVersionUID to AbstractAuthenticationToken and it's subclasses. Or, since this has come up before in other classes (SEC-338, etc), add serialVersionUID's to all serializable classes. It's an Eclipse compile option that we require for all of our code.

**Comment by mkopylec** [comment]
I have a problem with this mechanism because the `AbstractAuthenticationToken`s sub classes have different `serialVersionUID`s comparing to different Spring Security versions. This causes an error on our production platform, because the underlying session is backed by Couchbase database using Spring Session:
```
java.io.InvalidClassException: org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationToken; local class incompatible: stream classdesc serialVersionUID = 410, local class serialVersionUID = 400
```
The error occurs when we try to deploy a new version of our app which has an upgraded Spring Security version.

Now we are stuck and cannot deploy the new version of our app.
Any sugestions how to resolve this problem?

**Comment by mkopylec** [comment]
I have also found the following note in `SpringSecurityCoreVersion` class:
```java
        /**
	 * Global Serialization value for Spring Security classes.
	 *
	 * N.B. Classes are not intended to be serializable between different versions. See
	 * SEC-1709 for why we still need a serial version.
	 */
	public static final long SERIAL_VERSION_UID = 410L;
```
Why classes are not intended to be serializable between versions?
As I know the `serialVersionUID` should only change when the new version of class introduces incompatible changes. See http://docs.oracle.com/javase/7/docs/platform/serialization/spec/version.html#5172

**Comment by peikuo** [comment]
Yes, I have the same question, if I upgrade spring security, then the token serialized cannot use. It wil cause big risk on project upgrade.

**Comment by peikuo** [comment]
For example:

I use spring oauth2 with token serializied to DB implement. If I upgrade spring security version and put online, The token in DB cannot work for UsernamePasswordAuthenticationToken.class and WebAuthenticationDetails.class cannot deserialize, then refresh token failed. 

Or I use spring session, after upgrade spring security version, SecurityContextImpl.class cannot deserialize then restore session failed.

**Comment by juliusspencer** [comment]
Hi, I have the same issue trying to migrate from 2.0.9 to 2.1.6 of spring-boot:

> java.lang.IllegalArgumentException: java.io.InvalidClassException: org.springframework.security.core.authority.SimpleGrantedAuthority; local class incompatible: stream classdesc serialVersionUID = 500, local class serialVersionUID = 510

Is there any article that details how to get handle this with a number of users who have Oauth access and refresh tokens?

**Comment by wilius** [comment]
I solved that problem in two ways. Through the solutions below, please keep in mind that `SimpleGrantedAuthority` and `UsernamePasswordAuthenticationToken` classes were the problematic classes and I totally focused on them. Also, for my case, the expected `serialVersionUID` was 510 but the actual one got from newer version was 560. So, I replaced 560s to the 510s. I could be different for your case. 

The first one is via java reflection:
```
public static void main(String[] args) throws Exception {
        updateSerialVersionUID(org.springframework.security.core.authority.SimpleGrantedAuthority.class);
        updateSerialVersionUID(org.springframework.security.authentication.UsernamePasswordAuthenticationToken.class);
        SpringApplication.run(UserServiceApplication.class, args);
    }

    private static void updateSerialVersionUID(Class<?> clazzToCustomize) throws Exception {
        Field theUnsafeField = Unsafe.class.getDeclaredField("theUnsafe");
        theUnsafeField.setAccessible(true);
        Unsafe theUnsafe = (Unsafe) theUnsafeField.get(null);

        Field staticFinalFieldToReplace = clazzToCustomize.getDeclaredField("serialVersionUID");
        setFinalStatic(staticFinalFieldToReplace, Long.valueOf(510L));
    }

    static void setFinalStatic(Field field, Object newValue) throws Exception {
        field.setAccessible(true);
        Field modifiersField = Field.class.getDeclaredField("modifiers");

        // wrapping setAccessible
        AccessController.doPrivileged((PrivilegedAction) () -> {
            modifiersField.setAccessible(true);
            return null;
        });

        modifiersField.setInt(field, field.getModifiers() & ~Modifier.FINAL);
        field.set(null, newValue);
    }
```

second solution is much more hacky. I copied the package of the problematic classes and created a package with exactly same name in my codebase:
![image](https://user-images.githubusercontent.com/1589960/192836525-9b396f23-2620-4250-9931-e88c14a9546e.png)
and copied the content of them from the source code without any modification. After that point on, just replaced their `serialVersionUID` with the desired one. As I mentioned before, I replaced the 560s to the 510s. 

![image](https://user-images.githubusercontent.com/1589960/192837547-bcb476fb-c969-4ed3-b84d-6f56efe17d37.png)
![image](https://user-images.githubusercontent.com/1589960/192837610-16a64497-2ea0-4a34-b0db-8e33adbf3f7b.png)

**Comment by pvsreejesh** [comment]
@wilius which jdk version you used to modify the serialVersionUID, I think in the newer jdk21 it wont work.
