### ISSUE TITLE
SEC-1716: Improve BasicLookupStrategy  'object_id_identity' field handling, to support other Serializable primitive types in addition to 'long'.

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#1952]
[Boris Kobilkovsky](https://jira.spring.io/secure/ViewProfile.jspa?name=boriskob) (Migrated from [SEC-1716](https://jira.spring.io/browse/SEC-1716?redirect=false)) said:

Documentation mentions that the object id must be `Serializable`. This is perfect as I am working on the system where object ids are strings (generated UUIDs). I was surprised to discover that `org.springframework.security.acls.jdbc.BasicLookupStrategy` can only work with `Long`. 

The fix is very simple, please see the attached patch. It would be great if the fix could is incorporated into trunk builds of v3 (and super wonderful if it is also put into v2.0.7).

bq. I do realize that, strictly speaking, this fix does not make the strategy to work with any `Serializable`, but it presents more options in addition to `Long`.

**Comment by spring-issuemaster** [comment]
This issue duplicates #1224

**Comment by rwinch** [comment]
Closed as duplicate
