### ISSUE TITLE
SEC-1723: Support use of bean names in expressions via @beanName notation

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#1960]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1723](https://jira.spring.io/browse/SEC-1723?redirect=false)) said:

SEC-1294 originally implemented this in a custom fashion. SPR-7173 adds a custom notation for this which we should probably support instead.

**Comment by spring-issuemaster** [comment]
This issue supersedes #1540
