### ISSUE TITLE
SEC-1765: make protected the org.springframework.security.web.DefaultRedirectStrategy.calculateRedirectUrl(String, String) method in order to extend URL redirection behavior

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#1998]
[Ludovic Praud](https://jira.spring.io/secure/ViewProfile.jspa?name=ludovic.praud) (Migrated from [SEC-1765](https://jira.spring.io/browse/SEC-1765?redirect=false)) said:

To be more RESTful if need redirection given from an URL param. I can't override DefaultRedirectStrategy.calculateRedirectUrl method because it is private so I must copy paste the code of DefaultRedirectStrategy.
Should DefaultRedirectStrategy.calculateRedirectUrl(String, String) method be made protected ?

**Comment by deki** [comment]
Duplicates #2173

**Comment by jgrandja** [comment]
Closing this issue as it's been resolved by #2173
