### ISSUE TITLE
SEC-1769: Decouple from HttpSession

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2002]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-1769](https://jira.spring.io/browse/SEC-1769?redirect=false)) said:

There are places in the code where HttpSession is still used and cannot be changed using what is provided. An example is the AbstractPreAuthenticatedProcessingFilter which stores the last exception in session. One thought would be to introduce a strategy for saving exceptions similar to how SecurityContextRepository works.

**Comment by rwinch** [comment]
AbstractPreAuthenticatedProcessingFilter no longer requires the `HttpSession`
