### ISSUE TITLE
SEC-1785: Remove auto-config from namespace docs

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2021]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1785](https://jira.spring.io/browse/SEC-1785?redirect=false)) said:

auto-config provides little gain over a simple configuration and causes confusion. It shouldn't be in the first namespace example configuration that we provide.

**Comment by spring-issuemaster** [comment]
This issue relates to #2402
