### ISSUE TITLE
SEC-1787: spring-security-config declares mandatory dependence on openid4java

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2022]
[Dave Syer](https://jira.spring.io/secure/ViewProfile.jspa?name=david_syer) (Migrated from [SEC-1787](https://jira.spring.io/browse/SEC-1787?redirect=false)) said:

spring-security-config declares mandatory dependence on openid4java, which can't be right?  I haven't looked that the other dependencies, so there may be other lurkers in there.

**Comment by spring-issuemaster** [comment]
This issue duplicates #1974
