### ISSUE TITLE
SEC-1801: Please put generated POMs in samples and include with git source code

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2031]
[Dave Syer](https://jira.spring.io/secure/ViewProfile.jspa?name=david_syer) (Migrated from [SEC-1801](https://jira.spring.io/browse/SEC-1801?redirect=false)) said:

Please put generated POMs in samples and include with git source code.  I'd really like to be able to clone the project and use the samples immediately from STS without knowing anything about gradle.  Spring Integration do this quite successfully I think, so I can suggest a patch (remind me).

**Comment by rwinch** [comment]
Gradle has become much easier to use in IDEs. Additionally, the samples have since moved outside of Spring Security.  For that reason, I'm closing this invalid.
