### ISSUE TITLE
SEC-1805: Add encodeUrl method to Base64 utility

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2034]
[Luke Taylor](https://jira.spring.io/secure/ViewProfile.jspa?name=luke) (Migrated from [SEC-1805](https://jira.spring.io/browse/SEC-1805?redirect=false)) said:

Common requirement for OAuth, JWT etc.

**Comment by eleftherias** [comment]
The Spring Security Base64 utility is now deprecated.
`java.util.Base64` should be used instead, which provides this functionality with `getUrlEncoder`.
