### ISSUE TITLE
SEC-1807: logout success failed on tomcat due to NPE

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2039]
[Ludovic Praud](https://jira.spring.io/secure/ViewProfile.jspa?name=ludovic.praud) (Migrated from [SEC-1807](https://jira.spring.io/browse/SEC-1807?redirect=false)) said:

Due to issue SEC-1762, the targetUrlParameter is default set to null in SimpleUrlLogoutSuccessHandler constructor. When login out on tomcat 6, it throws NPE because it uses java.util.Hashtable which does not allow retrieving value with a null key.
There is no problem on jetty-7 because it uses org.eclipse.jetty.util.MultiMap which allows null.

Work around : revert to spring-security-3.0.5

The problem is also that is cannot found anywhere the responsible commit. The 3.0.6 exists in maven repo but nowhere released in JIRA or GIT. Very strange !

<code>
java.lang.NullPointerException
    java.util.Hashtable.get(Hashtable.java:334)
    org.apache.tomcat.util.http.Parameters.getParameterValues(Parameters.java:195)
    org.apache.tomcat.util.http.Parameters.getParameter(Parameters.java:240)
    org.apache.catalina.connector.Request.getParameter(Request.java:1065)
    org.apache.catalina.connector.RequestFacade.getParameter(RequestFacade.java:355)
    javax.servlet.ServletRequestWrapper.getParameter(ServletRequestWrapper.java:158)
    org.springframework.security.web.authentication.AbstractAuthenticationTargetUrlRequestHandler.determineTargetUrl(AbstractAuthenticationTargetUrlRequestHandler.java:86)
    org.springframework.security.web.authentication.AbstractAuthenticationTargetUrlRequestHandler.handle(AbstractAuthenticationTargetUrlRequestHandler.java:67)
    org.springframework.security.web.authentication.logout.SimpleUrlLogoutSuccessHandler.onLogoutSuccess(SimpleUrlLogoutSuccessHandler.java:28)
    org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:100)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:381)
    org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:79)
    org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:381)
    org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:168)
    org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
    org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
    org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
    org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
    org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
    org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
</code>

**Comment by spring-issuemaster** [comment]
This issue duplicates #2035
