### ISSUE TITLE
SEC-1813: not able to fetch the queries from the property file using spring message source

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2043]
[Ganesh Mohan](https://jira.spring.io/secure/ViewProfile.jspa?name=rockgans) (Migrated from [SEC-1813](https://jira.spring.io/browse/SEC-1813?redirect=false)) said:

When I tried injecting the Dao class ( which uses spring message source to fetch the queries from a  .properties file) as a property to the custom implementation of PermissionEvaluator , I got the circular bean initialization error because of NPE at the Dao Class. Not sure is that a bug.

**Comment by spring-issuemaster** [comment]
This issue duplicates #2042
