### ISSUE TITLE
SEC-1831: org.springframework.security.web.savedrequest.HttpSessionRequestCache should allow developer set the session attribute name

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2061]
[wayne zheng](https://jira.spring.io/secure/ViewProfile.jspa?name=waynezhengcq) (Migrated from [SEC-1831](https://jira.spring.io/browse/SEC-1831?redirect=false)) said:

In the Class org.springframework.security.web.savedrequest.HttpSessionRequestCache
code:
static final String SAVED_REQUEST = "SPRING_SECURITY_SAVED_REQUEST";
and saveRequest/getRequest/removeRequest use the SAVED_REQUEST as session attribute name.
it's not a good idea.

thus, it should Like 
class org.springframework.security.web.context.HttpSessionSecurityContextRepository
which has a method named "setSpringSecurityContextKey".

So, the HttpSessionRequestCache class should have a method like setSavedRequestKey(String ...)
and allow developer to set the session attribute name.

for example:
/user should use /user/login as login entrypoint
but
/manager should use /manager/login as login entrypoint
and must use different springSecurityContextKey, and HttpSessionRequestCache should use different session attribute key.

**Comment by rwinch** [comment]
This was fixed via aa5df61eff0f7410bed09b5990c5ed1830d16c60
