### ISSUE TITLE
SEC-1840: UserMap is deprecated and InMemoryDaoImpl uses it; what to do?

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2072]
[The Alchemist](https://jira.spring.io/secure/ViewProfile.jspa?name=the_alchemist) (Migrated from [SEC-1840](https://jira.spring.io/browse/SEC-1840?redirect=false)) said:

`org.springframework.security.core.userdetails.memory.UserMap` is deprecated but `org.springframework.security.core.userdetails.memory.InMemoryDaoImpl` still uses it.

If I wrote a patch for `org.springframework.security.core.userdetails.memory.InMemoryDaoImpl` to use a `HashMap` or whatever, would you guys take it?

My motivation for this is https://issuetracker.springsource.com/browse/STS-1970, where Roo generates code and config that, by default, gives deprecated warnings, which, IMHO, isn't a great idea.

**Comment by rwinch** [comment]
`UserMap` no longer exists so I'm marking this as invalid.
