### ISSUE TITLE
SEC-1844: Add the HTTPonly flag to the rememberMe cookie even it is not Servlet 3.0 API

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2078]
[Michael Furman](https://jira.spring.io/secure/ViewProfile.jspa?name=michaelf) (Migrated from [SEC-1844](https://jira.spring.io/browse/SEC-1844?redirect=false)) said:

Hi!
It is important to add the HTTPonly flag to the rememberMe cookie.
Version 3.1.0 is the first version that add the flag to the cookie.
Unfortunately, it happens only if it is Servlet 3.0 API
I think it is important to do it for any  Servlet API specifications.
The provided patch allow to add the HTTPonly flag to the rememberMe cookie even it is not Servlet 3.0 API
Best regards,
   Michael

**Comment by rwinch** [comment]
Spring Framework itself requires Servlet 3.1+ now.
