### ISSUE TITLE
SEC-1845: In case of the failed authentication add the delay before the next authentication to block Brute Force Attacks

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2079]
[Michael Furman](https://jira.spring.io/secure/ViewProfile.jspa?name=michaelf) (Migrated from [SEC-1845](https://jira.spring.io/browse/SEC-1845?redirect=false)) said:

Hi!
The simplest way to block Brute Force Attacks is to add the delay before the next authentication in case of the failed authentication.
See https://www.owasp.org/index.php/Blocking_Brute_Force_Attacks
Please find attached patch that allows to do it.
Probably it will be required to modify the configuration and the configuration.
Best regards,
    Michael

**Comment by marcusdacoregio** [comment]
@rwinch is this something that we have an idea already if we are going to do or not? Maybe we should close it since there are many different approaches to prevent brute force attacks by extending what Spring Security already provides

**Comment by rwinch** [comment]
Thanks @marcusdacoregio I don't think we want to add a delay as this can cause a DoS attack by blocking the available threads for servicing requests.
