### ISSUE TITLE
SEC-1875: SessionRegistry.registerNewSession invoked twice after successful authentication

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2080]
[Alvin Chee](https://jira.spring.io/secure/ViewProfile.jspa?name=alvincys) (Migrated from [SEC-1875](https://jira.spring.io/browse/SEC-1875?redirect=false)) said:

In Spring Security 3.1.0, SessionRegistry.registerNewSession is now invoked twice, due to SessionFixationProtectionStrategy.onAuthentication calling onSessionChange (this call wasn't there in previous versions up to 3.0.7).

I'm using a custom SessionRegistry implementation which uses a database table as the session registry, thus facing a constraint error if the same session is registered twice.

Perhaps ConcurrentSessionControlStrategy.onAuthentication need not invoke sessionRegistry.registerNewSession now?

**Comment by spring-issuemaster** [comment]
This issue relates to #1477
