### ISSUE TITLE
SEC-1860: Add <http-digest> similar to <http-basic> to the security namespace

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2095]
[Eugen Paraschiv](https://jira.spring.io/secure/ViewProfile.jspa?name=eugenparaschiv) (Migrated from [SEC-1860](https://jira.spring.io/browse/SEC-1860?redirect=false)) said:

The <http> element of the security namespace has <http-basic> to support basic authentication. Similar support would be helpful for digest authentication as well, via a <http-digest> element in the security namespace.

**Comment by rwinch** [comment]
Closing because Digest authentication is considered insecure. See gh-9810
