### ISSUE TITLE
SEC-1871: AbstractRememberMeServices method getCookiePath()

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2103]
[Jon Osborn](https://jira.spring.io/secure/ViewProfile.jspa?name=jonnio) (Migrated from [SEC-1871](https://jira.spring.io/browse/SEC-1871?redirect=false)) said:

For some implementations behind proxy services, the CookiePath must be 'url encoded' to transform the path into a public path that the browser will recognize. There should be a property on the RememberMeServices to enable response.urlEncode() for the cookie path.

patch attached. includes beandefinitionparser

**Comment by rwinch** [comment]
The path is properly encoded/decoded by the servlet container, so we should not do any additional encoding/decoding.
