### ISSUE TITLE
SEC-1888: Mixing @Secured and @PreAuthorize annotations on a secured object causes one or the other to be silently ignored

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2116]
[Richard Bradley](https://jira.spring.io/secure/ViewProfile.jspa?name=richard.bradley@softwire.com) (Migrated from [SEC-1888](https://jira.spring.io/browse/SEC-1888?redirect=false)) said:

If I secure an object with a mixture of `@PreAuthorize` and `@Secured` annotations, then one or the other is silently ignored:

```
@PreAuthorize("isAuthenticated()")
public class FooHelper {

  // you have to be logged in to do this
  public Foo getFoo(int id) {
    ...
  }

  @Secured("ROLE_FOO_EDITOR")
  public void saveFoo(Foo newFoo) {
    ...
  }
}
```

In the above example, I wanted to use @Secured where I had a role-based restriction, as it's prettier than @PreAuthorize, but I had to use @PreAuthorize for the isAuthenticated() restriction, as that is not expressable with @Secured.

I have had a look at the code, and I believe the culprit is here:
core/src/main/java/org/springframework/security/access/method/DelegatingMethodSecurityMetadataSource.java:49

```
            // No cached value, so query the sources to find a result
            Collection<ConfigAttribute> attributes = null;
            for (MethodSecurityMetadataSource s : methodSecurityMetadataSources) {
                attributes = s.getAttributes(method, targetClass);
                if (attributes != null && !attributes.isEmpty()) {
                    break;
                }
            }
```

The "break" means that only the first MethodSecurityMetadataSource is considered. I think all should be considered.

I have attached my attempted fix with a unit test, however it breaks another test, and I can't immediately see why.
Please could someone have a look and see if they can fix it up?

(Also, I assume that returning multiple ConfigAttributes here will AND them together, is that correct?)

Many thanks,

Rich

**Comment by kdejaeger** [comment]
I think this changed in the latest versions, didn't it. We upgraded to spring boot 3 and noticed both annotations are now enforced. Or maybe @Secured is being preferred now.

**Comment by kdejaeger** [comment]
Did some more tests, Yea it seems both annotations in spring boot 3.1 get evaluated now ... . But to be sure I combined them into one @PreAuthorized :)
