### ISSUE TITLE
SEC-1899: please publish jar for Spring Security SAML support

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2129]
[Steve Strassmann](https://jira.spring.io/secure/ViewProfile.jspa?name=straz) (Migrated from [SEC-1899](https://jira.spring.io/browse/SEC-1899?redirect=false)) said:

It looks like spring-security-saml2-core is available as part of Spring Security extensions source tree, but there are no released jars.

As a VMware employee, it'd be nice to have this available on our maven repo. (http://<redacted>/nexus/index.html#nexus-search;quick~spring-security)

**Comment by rwinch** [comment]
The support has been published See https://docs.spring.io/spring-security/site/docs/5.3.x/reference/html5/#servlet-saml2
