### ISSUE TITLE
SEC-1900: sec:authorize ifAllGranted does not work if Authorities are deprecated GrantedAuthorityImpl

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2130]
[Janning Vygen](https://jira.spring.io/secure/ViewProfile.jspa?name=janning) (Migrated from [SEC-1900](https://jira.spring.io/browse/SEC-1900?redirect=false)) said:

<sec:authorize ifAllGranted="ROLE_ADMIN">

did not work for me after upgrading to 3.1.0 

reason: i added some role manually in my own UserDetails like this:

  GrantedAuthority granted = new GrantedAuthorityImpl(rolle.toString());
  authorities.add(granted);

GrantedAuthorityImpl is deprecated and ifAllGranted, too. But i think it is still a bug.

You can fix it by using simpleGrantedAuthority

GrantedAuthority granted = new SimpleGrantedAuthority(rolle.toString());
authorities.add(granted);

the bug is somewhere in the Collection class in an equals method. It checks if the containing element is of class SimpleGrantedAuthority.

**Comment by Fire-Star** [comment]
use "access"
