### ISSUE TITLE
SEC-1911: <security:debug/> enables SecurityDebugBeanFactoryPostProcessor which ignores <context:annotation-config/>

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2139]
[kevin s](https://jira.spring.io/secure/ViewProfile.jspa?name=kevin) (Migrated from [SEC-1911](https://jira.spring.io/browse/SEC-1911?redirect=false)) said:

```
<bean id="customBasedAuthenticationProvider" class="com.test.admin.auth.CustomBasedAuthenticationProvider">
    <property name="configBean" ref="annotationBean" />
</bean>


<context:annotation-config/>
<security:debug/> 

 <security:authentication-manager>
    <security:authentication-provider ref="customBasedAuthenticationProvider">
    </security:authentication-provider>
</security:authentication-manager>
```

---
## configBean

@Component("annotationBean")
@Scope(BeanDefinition.SCOPE_SINGLETON)
public class AnnotationConfigBean implements InitializingBean {
    @Autowired
    public AutowiredBean bean;

```
/* (non-Javadoc)
 * @see org.springframework.beans.factory.InitializingBean#afterPropertiesSet()
 */
@Override
public void afterPropertiesSet() throws Exception {
    if(bean==null)
        throw new RuntimeException("noconfigbean");

}
```
## autowiredBean

@Component
public class AutowiredBean {

}

when injecting  annotationBean into customBasedAuthenticationProvider the @Autowired AutowiredBean is not set on the annotationBean. This occurs only when  security:debug/  is enabled.

**Comment by spring-issuemaster** [comment]
This issue duplicates #2113
