### ISSUE TITLE
SEC-1915: Add cutomisation of search filter in ActiveDirectoryLdapAuthenticationProvider

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2143]
[Tseliso Molukanele](https://jira.spring.io/secure/ViewProfile.jspa?name=tseliso%20molukanele) (Migrated from [SEC-1915](https://jira.spring.io/browse/SEC-1915?redirect=false)) said:

Currently the search filter used when retrieving user details is hard coded to '(&(objectClass=user)(userPrincipalName={0}))'.

When this hard coded filter is not consistent with the actual active directory instance it causes a org.springframework.dao.IncorrectResultSizeDataAccessException because the search returns with empty results after successful authentication.

A possible solution is to modify the class org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider to allow a configurable search filter via bean configuration.

Another possible solution is to make the class org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider extendable instead of final with protected instead of private functional methods to allow for easier customisation.

See question 
http://stackoverflow.com/questions/9258047/spring-security-3-1-active-directory-authentication

**Comment by spring-issuemaster** [comment]
This issue relates to #3114
This issue supersedes #2448
