### ISSUE TITLE
SEC-1917: DefaultAuthenticationEventPublisher is never used when an AccountStatusException is thrown

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2145]
[MI](https://jira.spring.io/secure/ViewProfile.jspa?name=benji) (Migrated from [SEC-1917](https://jira.spring.io/browse/SEC-1917?redirect=false)) said:

The ProviderManager created by http namespace coded in 
`org.springframework.security.config.http.HttpSecurityBeanDefinitionParser#createAuthenticationManager` does not register a `DefaultAuthenticationEventPublisher` to the bean registration. This, in combination with the `AccountStatusException` handling in `org.springframework.security.authentication.ProviderManager#authenticate` where the exception is always rethrown, renders the `DefaultAuthenticationEventPublisher` of the parent ProviderManager invisible.

If you consider also that the `org.springframework.security.core.AuthenticationException#getAuthentication` has been deprecated, I cannot find a way to retrieve the cause and the identity of the failed authentication.

**Comment by spring-issuemaster** [comment]
This issue duplicates #2166
