### ISSUE TITLE
SEC-1918: Add Unit Testing Guidelines to Spring Security Docs

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2146]
[Adib Saikali](https://jira.spring.io/secure/ViewProfile.jspa?name=asaikali) (Migrated from [SEC-1918](https://jira.spring.io/browse/SEC-1918?redirect=false)) said:

The official docs contains no mention of how to do unit testing with Spring Security. If you are using global method security to secure services all the service unit and integration tests will break because a security context will not be established. Searching the internet yields all sorts of ways to approach the situation. It would be great if the official reference manual contained information on how to setup spring security with unit tests.

**Comment by eleftherias** [comment]
Closing because the Spring Security reference docs now have a testing section. 
Example: https://docs.spring.io/spring-security/site/docs/5.2.0.RELEASE/reference/htmlsingle/#test
