### ISSUE TITLE
SEC-1930: Documentation Could Use Improvement

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2156]
[Nick Williams](https://jira.spring.io/secure/ViewProfile.jspa?name=guitarking117) (Migrated from [SEC-1930](https://jira.spring.io/browse/SEC-1930?redirect=false)) said:

http://static.springsource.org/spring-security/site/docs/3.1.x/reference/ldap.html#ldap-active-directory

We're using the embedded Apache DS container on our local machines to test things, and then using a real-world provider in QA and Production. The aforementioned documentation was helpful, but it could be improved. Namely, the LDIF file is mentioned in passing but no working examples provided.

I have attached a sample LDIF file that could be included in the documentation. It would make a huge improvement, in my opinion. This is just a file that I was able to formulate that works with the embedded DS AS-CONFIGURED in the documentation. No changes to the LDIF file should be necessary to get it to work as configured, but of course changes could be made.

Hope this is useful.

Nick

**Comment by eleftherias** [comment]
There are now LDAP examples, including LDIF files provided in the [samples](https://github.com/spring-projects/spring-security/tree/master/samples).
