### ISSUE TITLE
SEC-1934: NamspaceHandler logs error if web module not present

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2160]
[Oliver Gierke](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke) (Migrated from [SEC-1934](https://jira.spring.io/browse/SEC-1934?redirect=false)) said:

The `SecurityNamespaceHandler` in the config module tries to load `FilterChainProxy` (which it probably shouldn't anyway?) although one might not have included the Spring Security web module as one might only want to use global methd security in the first place. The `pom.xml` of the config module actually states the web module to be optional but apparently the code is not.

Of course Spring Security works just fine without the web module present but logging an error is at least irritating then.

**Comment by spring-issuemaster** [comment]
This issue duplicates #2100
