### ISSUE TITLE
SEC-1948: Custom AbstractUserDetailsAuthenticationProvider Does not process annotations

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2174]
[asd](https://jira.spring.io/secure/ViewProfile.jspa?name=asd) (Migrated from [SEC-1948](https://jira.spring.io/browse/SEC-1948?redirect=false)) said:

I have a custom class derived from AbstractUserDetailsAuthenticationProvider which needs to use a custom dao (UserDao).  Within this provider I have an @Autowired UserDao field which does not get autowired.  UserDao is successfully autowired into other beans in the same context (all beans reside within the root context).

The hack to get it to work is to manually inject the userDao via xml configuration.  When that happens though, other annotations within UserDao (in this case @Transactional) are also removed.

For more information see:  http://stackoverflow.com/a/10036529/80286

**Comment by spring-issuemaster** [comment]
This issue duplicates #2113
