### ISSUE TITLE
SEC-1951: HttpSessionDestroyedEvent#getSecurityContexts always return empty

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2176]
[grhwood](https://jira.spring.io/secure/ViewProfile.jspa?name=grhwood) (Migrated from [SEC-1951](https://jira.spring.io/browse/SEC-1951?redirect=false)) said:

Looking into the source code of HttpSessionDestroyedEvent.java on line 52:

Object attribute = attributes.nextElement();

This should be: session.getAttribute(attributes.nextElement())

Thanks

**Comment by spring-issuemaster** [comment]
This issue duplicates #2102
