### ISSUE TITLE
SEC-1950: Defensively invoke SecurityContextHolder.clearContext() in FilterChainProxy

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2177]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-1950](https://jira.spring.io/browse/SEC-1950?redirect=false)) said:

In situations where applications try to obtain the SecurityContext globally it may cause a memory leak if the application uses security=none and the SecurityContextHolder is even read from. A similar situation can occur if users manually create the filter chain and do not properly add the SecurityContextPersistenceFilter to the FilterChainProxy. In order to be defensive about memory leaks, it would be good to call SecurityContextHolder.clearContext() in the FilterChainProxy itself.

**Comment by spring-issuemaster** [comment]
This issue relates to #2252
