### ISSUE TITLE
SEC-1954: DaoAuthenticationProvider.retrieveUser should not be final

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2180]
[Andy O'Neill](https://jira.spring.io/secure/ViewProfile.jspa?name=werkshy) (Migrated from [SEC-1954](https://jira.spring.io/browse/SEC-1954?redirect=false)) said:

Javadocs claim that this method is protected, but it is actually protected final. This is also in contradiction with the javadoc comment:
"Allows subclasses to actually retrieve the UserDetails from an implementation-specific location, with the option of throwing an AuthenticationException immediately if the presented credentials are incorrect (this is especially useful if it is necessary to bind to a resource as the user in order to obtain or generate a UserDetails)."

http://static.springsource.org/spring-security/site/docs/3.0.x/apidocs/

**Comment by App-Teck** [comment]
Now its not final :)

**Comment by 25khattab** [comment]
Now it is final, can I get an explanation why is it final, I don't get the benefit of being final especially if I want just to override this method.
I'm new to spring security sorry if that question is kind of dumb
