### ISSUE TITLE
SEC-1958: authentication successful even if it's not in AbstractPreAuthenticatedProcessingFilter

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2181]
[Igo](https://jira.spring.io/secure/ViewProfile.jspa?name=igo) (Migrated from [SEC-1958](https://jira.spring.io/browse/SEC-1958?redirect=false)) said:

Consider scenario using AbstractPreAuthenticatedProcessingFilter with setCheckForPrincipalChanges(true).
1. on first page request authentication is successful and everything is ok
2. on next page request authentication failed, getPreAuthenticatedPrincipal returns null. Method doAuthenticate in current implementation does this:

```
        if (principal == null) {
            if (logger.isDebugEnabled()) {
                logger.debug("No pre-authenticated principal found in request");
            }

            return;
        }
```

This means that no AuthenticationException is raised and no check to continueFilterChainOnUnsuccessfulAuthentication is made.

**Comment by spring-issuemaster** [comment]
This issue duplicates #2192
