### ISSUE TITLE
SEC-1979: Constants for ShaPasswordEncoder

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2203]
[Daniel Holmes](https://jira.spring.io/secure/ViewProfile.jspa?name=dholmes) (Migrated from [SEC-1979](https://jira.spring.io/browse/SEC-1979?redirect=false)) said:

Would be nice to have this class provide public constants (or enum) so that
client code could have a more readable name.  As an enum also would be more specific to allowed values as well.

example
new ShaPasswordEncoder(256);
could be
new ShaPasswordEncoder(SHA256);

**Comment by spring-issuemaster** [comment]
This issue relates to #2206
