### ISSUE TITLE
SEC-1982: Hashing documentation updates

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2206]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-1982](https://jira.spring.io/browse/SEC-1982?redirect=false)) said:
# We should deprecate from the core module in favor of the PasswordEncoder in the crypto lib
# Provide documentation updates (i.e. javadoc) to favor BCrypt over SHA hashing

**Comment by eleftherias** [comment]
Done in gh-2347 and gh-2776.
