### ISSUE TITLE
SEC-1994: Spring security 3.1.1.RELEASE is not JDK 1.5 compatible

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2215]
[Lyor Goldstein](https://jira.spring.io/secure/ViewProfile.jspa?name=lgoldstein) (Migrated from [SEC-1994](https://jira.spring.io/browse/SEC-1994?redirect=false)) said:

Even though the site states that it only requires 1.5+. See maven build exception below as well as javap command result.

Compiled from "Authentication.java"
public interface org.springframework.security.core.Authentication extends java.security.Principal,java.io.Serializable
  SourceFile: "Authentication.java"
  minor version: 0
  major version: 50
  Constant pool:
const #1 = class        #21;    //  org/springframework/security/core/Authentication
const #2 = class        #22;    //  java/lang/Object
const #3 = class        #23;    //  java/security/Principal
const #4 = class        #24;    //  java/io/Serializable
const #5 = Asciz        getAuthorities;
const #6 = Asciz        ()Ljava/util/Collection;;
const #7 = Asciz        Signature;
const #8 = Asciz        ()Ljava/util/Collection<+Lorg/springframework/security/core/GrantedAuthority;>;;
const #9 = Asciz        getCredentials;
const #10 = Asciz       ()Ljava/lang/Object;;
const #11 = Asciz       getDetails;
const #12 = Asciz       getPrincipal;
const #13 = Asciz       isAuthenticated;
const #14 = Asciz       ()Z;
const #15 = Asciz       setAuthenticated;
const #16 = Asciz       (Z)V;
const #17 = Asciz       Exceptions;
const #18 = class       #25;    //  java/lang/IllegalArgumentException
const #19 = Asciz       SourceFile;
const #20 = Asciz       Authentication.java;
const #21 = Asciz       org/springframework/security/core/Authentication;
const #22 = Asciz       java/lang/Object;
const #23 = Asciz       java/security/Principal;
const #24 = Asciz       java/io/Serializable;
const #25 = Asciz       java/lang/IllegalArgumentException;

{
public abstract java.util.Collection getAuthorities();
  Signature: length = 0x2
   00 08

public abstract java.lang.Object getCredentials();

public abstract java.lang.Object getDetails();

public abstract java.lang.Object getPrincipal();

public abstract boolean isAuthenticated();

public abstract void setAuthenticated(boolean)   throws java.lang.IllegalArgumentException;
  Exceptions:
   throws java.lang.IllegalArgumentException
}

---

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project insight-dashboard: Compilation failure
/opt/hudson/workspace/jobs/insight-continuous-jvm1.5/workspace/core/dashboard/src/main/java/com/springsource/insight/dashboard/util/RequireAdminTag.java:[11,-1] cannot access org.springframework.security.core.Authentication
bad class file: /opt/hudson/.m2/repository/org/springframework/security/spring-security-core/3.1.1.RELEASE/spring-security-core-3.1.1.RELEASE.jar(org/springframework/security/core/Authentication.class)
class file has wrong version 50.0, should be 49.0

**Comment by spring-issuemaster** [comment]
This issue relates to #2125
