### ISSUE TITLE
SEC-1995: Setup CI to be able to perform the release

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2219]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-1995](https://jira.spring.io/browse/SEC-1995?redirect=false)) said:

We should update the Spring Security build to be able to release from CI server. Spring framework already uses a process that we can base our work off of. This will make releasing quite a bit easier and ensure issues like SEC-1994 do not happen again. See the [Spring Release Process](https://github.com/SpringSource/spring-framework/wiki/Gradle-build-and-release-FAQ#wiki-release_process) for more info.

Note In all likeliness we may need to update our gradle build to use some of the tasks that are a part of the [spring-build-gradle](https://github.com/SpringSource/spring-build-gradle) project.

**Comment by spring-issuemaster** [comment]
This issue relates to #2215
