### ISSUE TITLE
SEC-1996: Update javadoc to work with JDK 1.5 javadoc bug

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2220]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-1996](https://jira.spring.io/browse/SEC-1996?redirect=false)) said:

The current build fails to generate javadoc with Java 1.5 due to a JDK issue similar to [this jdk bug](http://bugs.sun.com/view_bug.do?bug_id=5082928) (fixed in JDK 1.6). However, we should ensure the entire build can work with JDK 1.5. This should improve the build so that this is possible.

**Comment by spring-issuemaster** [comment]
This issue relates to #2215
