### ISSUE TITLE
SEC-1998: Support for Servlet 3.0/3.1 asynchronous request processing

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2223]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-1998](https://jira.spring.io/browse/SEC-1998?redirect=false)) said:

Similar to SPR-8517 Spring Security should support Asynch Servlet request processing

Note: SEC-2067 has a sample application that should be validated against when fixing this issue

**Comment by spring-issuemaster** [comment]
This issue depends on #2301
