### ISSUE TITLE
SEC-2003: Requires JDK6.0 version of Problem

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2228]
[WanJiDong](https://jira.spring.io/secure/ViewProfile.jspa?name=epim) (Migrated from [SEC-2003](https://jira.spring.io/browse/SEC-2003?redirect=false)) said:

访问 org.springframework.security.access.ConfigAttribute
错误的类文件： G:\Java\Maven\repository\org\springframework\security\spring-security-core\3.1.1.RELEASE\spring-security-core-3.1.1.RELEASE.jar(org/springfr
amework/security/access/ConfigAttribute.class)
类文件具有错误的版本 50.0，应为 49.0(English:Class file has wrong version 50.0 should be 49.0)

**Comment by spring-issuemaster** [comment]
This issue duplicates #2215
