### ISSUE TITLE
SEC-2006: Allow anonymous authentication to expose Principal in HttpServletRequest

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2232]
[Paul Benedict](https://jira.spring.io/secure/ViewProfile.jspa?name=paul4christ79) (Migrated from [SEC-2006](https://jira.spring.io/browse/SEC-2006?redirect=false)) said:

Configuration <anonymous> allows me to set the username but it will not return any Principal for ServletRequest.getUserPrincipal(). This typically makes sense except I need the Authentication object to be exposed to the appserver so my special username gets automatically propagated to the EJB context. I am unable to really use EJBs this way; I am currently needing my own version of the Anonymous filter and SecurityContextHolderAwareRequestWrapper wrapper to work around this.

**Comment by spring-issuemaster** [comment]
This issue duplicates #1333
