### ISSUE TITLE
SEC-2043: Create MediaTypeRequestMatcher

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2267]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2043](https://jira.spring.io/browse/SEC-2043?redirect=false)) said:

It would be nice to have a RequestMatcher for MediaType's. This would be useful for treating JSON and HTML requests differently (i.e. a different AuthenticationEntryPoint for them, ignoring saving requests for JSON, etc). MediaTypeRequestMatcher could use Spring 3.2's ContentNegotiationStrategy to determine the available MediaTypes.

**Comment by spring-issuemaster** [comment]
This issue duplicates #2445
