### ISSUE TITLE
SEC-2045: AbstractAuthorizeTag cannot specify which WebInvocationPrivilegeEvaluator

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2269]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2045](https://jira.spring.io/browse/SEC-2045?redirect=false)) said:

AbstractAuthorizeTag uses the first WebInvocationPrivilegeEvaluator which causes problems when evaluating the url attribute and having multiple <http> elements.

**Comment by spring-issuemaster** [comment]
This issue duplicates #2307
