### ISSUE TITLE
SEC-2047: Upgrade Spring dependency to 3.1.x

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2271]
[Gilles Letare](https://jira.spring.io/secure/ViewProfile.jspa?name=gletare) (Migrated from [SEC-2047](https://jira.spring.io/browse/SEC-2047?redirect=false)) said:

Would be great to depend on the latest version of Spring (3.1.x).

**Comment by spring-issuemaster** [comment]
This issue duplicates #2105
