### ISSUE TITLE
SEC-2049: WebSockets support

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2273]
Migrated from [SEC-2049](https://jira.spring.io/browse/SEC-2049?redirect=false)

**Comment by spring-issuemaster** [comment]
This issue duplicates #2360
This issue relates to https://jira.spring.io/browse/SPR-9356

**Comment by spring-issuemaster** [comment]
This issue duplicates #2360
This issue relates to https://jira.spring.io/browse/SPR-9356

**Comment by spring-issuemaster** [comment]
This issue duplicates #2360
This issue relates to https://jira.spring.io/browse/SPR-9356
