### ISSUE TITLE
SEC-2050: RememberMe cookie can bypass concurrency control

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2274]
[Jan Bols](https://jira.spring.io/secure/ViewProfile.jspa?name=janbols) (Migrated from [SEC-2050](https://jira.spring.io/browse/SEC-2050?redirect=false)) said:

When RememberMeFilter is active together with concurrency session control configured with maximum 1 session, it's still possible to have 2 sessions for the same user open in 2 different browsers. This is because the RememberMeAuthenticationFilter doesn't call the SessionAuthenticationStrategy.onAuthenticate.

**Comment by spring-issuemaster** [comment]
This issue duplicates #2253
