### ISSUE TITLE
SEC-2064: Extract ThrowableAnalyzer, perhaps to Spring Core

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2288]
[Craig Walls](https://jira.spring.io/secure/ViewProfile.jspa?name=habuma) (Migrated from [SEC-2064](https://jira.spring.io/browse/SEC-2064?redirect=false)) said:

It strikes me that ThrowableAnalyzer is not only suitable for its current role in Spring Security and is more generally useful. I've found a need for something along the lines of ThrowableAnalyzer in Spring Social, but do not wish to force a dependency on Spring Security. As things stand currently, I must duplicate ThrowableAnalyzer to avoid the otherwise unnecessary dependency on Spring Security.

I wonder if ThrowableAnalyzer might be better suited for Spring Core's org.springframework.util package? I already depend on Spring Core, so I wouldn't have the same dependency concerns there and would be able to get rid of my duplicate ThrowableAnalyzer.

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-9858

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-9858

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-9858

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-9858

**Comment by rwinch** [comment]
Closing as declined because Spring Framework has closed the dependent issue.
