### ISSUE TITLE
SEC-2070: spring-security-3.0.xsd misses expression-handler tag under filter-security-metadata-source tag

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2294]
[Lukasz Wozniak](https://jira.spring.io/secure/ViewProfile.jspa?name=woznial) (Migrated from [SEC-2070](https://jira.spring.io/browse/SEC-2070?redirect=false)) said:

Schema disallows this tag while configuration parser: FilterInvocationSecurityMetadataSourceParser clearly expects this tag to setup custom expression handler ref.

**Comment by spring-issuemaster** [comment]
This issue relates to #1692
