### ISSUE TITLE
SEC-2106: Incorrect Javadoc on methods of AbstractAuthenticationProcessingFilter

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2308]
[Balazs Zagyvai](https://jira.spring.io/secure/ViewProfile.jspa?name=zagyi) (Migrated from [SEC-2106](https://jira.spring.io/browse/SEC-2106?redirect=false)) said:

Both overloads of
AbstractAuthenticationProcessingFilter.successfulAuthentication()
claims to invoke SessionAuthenticationStrategy, which is not true, as
the invokation happens earlier in doFilter().

**Comment by eleftherias** [comment]
This is a duplicate of gh-2310, which has been closed.
