### ISSUE TITLE
SEC-2103: Querying token for series: thread dump for info level 

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2333]
[Sergey Klimenko](https://jira.spring.io/secure/ViewProfile.jspa?name=smklimenko) (Migrated from [SEC-2103](https://jira.spring.io/browse/SEC-2103?redirect=false)) said:

In case of empty remember me tokens JdbcTokenRepositoryImpl writes thread dump to log file that is not required because it's clear from context:

```
        catch(EmptyResultDataAccessException zeroResults) {
            if(logger.isInfoEnabled()) {
                logger.info("Querying token for series '" + seriesId + "' returned no results.", zeroResults);
            }
        }
```

Is it possible to change level to debug or remove thread dump (better for me)?

**Comment by spring-issuemaster** [comment]
This issue relates to #2189
