### ISSUE TITLE
SEC-2104: Wrong <http> configuration gets accepted and leads to runtime errors.

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2334]
[Alex Khromov](https://jira.spring.io/secure/ViewProfile.jspa?name=alehro) (Migrated from [SEC-2104](https://jira.spring.io/browse/SEC-2104?redirect=false)) said:

Below are two snippets from my spring-security.xml. The first one is buggy the second one is good.
The problem is that I don't see any sensible difference between them and it cost me many hours until I evolved from version 2. to version 1.

1.
```xml
<http pattern="/perm1/**" use-expressions="true">
    <intercept-url pattern="/perm1/**" access="hasRole ( 'ROLE_REGISTERED' )" />
    <form-login />
    <logout />
</http>
<http pattern="/**" security="none" />
```

2.
```xml
<http use-expressions="true">
    <intercept-url pattern="/perm1/**" access="hasRole ( 'ROLE_REGISTERED' )" />
    <intercept-url pattern="/**" access="permitAll" />
    <form-login />
    <logout />
</http>
```

The buggy snippet gives with "http://localhost:8080/spring_security_login" following error page:
HTTP Status 404 -
type Status report
message
descriptionThe requested resource () is not available.

**Comment by jzheaux** [comment]
Hi, [Alex](https://jira.spring.io/secure/ViewProfile.jspa?name=alehro).

The difference is that `access="permitAll"` and `security="none"` are not the same thing.

`permitAll` means only that no authorization rules are applied. All the authentication and web application security defense mechanisms are in place.

`security="none"` means that Spring Securtiy should not participate in those requests at all. These requests won't get any of the defense mechanisms Spring Security offers, for example.

The second snippet is preferred over the first one.
