### ISSUE TITLE
SEC-2118: Update Spring Security 3.1.x to work with Spring Framework 3.2.0 in a OSGI container

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2343]
[Wim Bervoets](https://jira.spring.io/secure/ViewProfile.jspa?name=wbervoets) (Migrated from [SEC-2118](https://jira.spring.io/browse/SEC-2118?redirect=false)) said:

The MANIFEST.MF file in the the 3 Spring Security jars contains Import-Package declarations with a version range that excludes Spring 3.2.0.RELEASE

(eg. org.springframework.beans;version="[3.0.7.RELEASE, 3.2.0)")
In an OSGI environment where Spring 3.2 is deployed, the Spring Security bundle can't be deployed as the Import Packages doesn't include 3.2.0 in the version range.

In attachment you can find patched jars with an update MANIFEST.MF

**Comment by spring-issuemaster** [comment]
This issue duplicates #2359
