### ISSUE TITLE
SEC-2129: AntPathRequestMatcher support case sensitive matches

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2355]
[Michael Osipov](https://jira.spring.io/secure/ViewProfile.jspa?name=michael-o) (Migrated from [SEC-2129](https://jira.spring.io/browse/SEC-2129?redirect=false)) said:

AntPathRequestMatcher claims to work much like AntPathMatcher but treats everything in lowercase.

This has several flaws:
1. AntPathMatcher does not do that. Inconsistent.
2. One has to create a custom matcher in order to get case-sensitivity.
3. You might expose resources which differ in case but should be protected by other means.
4. You rely on `Locale.getDefault()` which might cause problems.

The solution would be to remove the `toLowerCase()` call and add another matcher which retains ci comparison. So we would have four `request-matcher` enum values: regex, ciRegex, ant and ciAnt.

**Comment by Lonzak** [comment]
This was a bad idea 👎  Now the matcher is case sensitive by default and (via XML configuration) there seems to be no way to make it case-insensitive like it was before...

**Comment by jzheaux** [comment]
@Lonzak, sorry that you are having trouble with this change. Given that the change was made over [six years ago](https://github.com/spring-projects/spring-security/issues/3831), I'm guessing that you are trying to move from Spring Security 3.x up to 5.x, which certainly can be daunting! Thanks for putting in the effort to get onto the latest.

In the future, may I recommend posting a question to [StackOverflow](https://stackoverflow.com)? This will likely result in more help from the community and the team. If you haven't already, take a look at the `request-matcher-ref` property.

**Comment by Lonzak** [comment]
@jzheaux Yes you are right - did the long overdue update from 3.X to 5.X recently. I could probably write a migration guide right now ;-) However this change is hopefully the last hurdle to take. And actually I did already write on [Stackoverflow ](https://stackoverflow.com/questions/72050005/how-to-configure-spring-security-antpathrequestmatcher-to-case-insensitive-in-xm) and even put a bounty on it. Regarding the "request-matcher-ref" that is the only solution I can think of right now...however I have to add >30 new beans to our configuration which makes it even more unreadable. But there doesn't seems to be another solution...
