### ISSUE TITLE
SEC-2179: Provide Spring Security WebSocket support

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2360]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2179](https://jira.spring.io/browse/SEC-2179?redirect=false)) said:

We will want to support WebSockets for Spring Security. This task highlights the investigation being done for such support

**Comment by spring-issuemaster** [comment]
This issue relates to https://jira.spring.io/browse/SPR-9356
