### ISSUE TITLE
SEC-2144: using AspectJMethodSecurityInterceptor for authorization the annotated method is ignored in hierarchi

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2370]
[Mohammad Hamed Ar](https://jira.spring.io/secure/ViewProfile.jspa?name=hamed) (Migrated from [SEC-2144](https://jira.spring.io/browse/SEC-2144?redirect=false)) said:

I use  AspectJMethodSecurityInterceptor to authorize my service methods annotated some with @Secured and others with @PreAuthorize. the project compiler is AspectJ1.7.2

it seems the reflection just searches the first direct interfaces implemented by the concrete class to find security annotations. 

If you annotate a method that is on a super super interface it is not detected

Example:

interface SuperSuperInterface{
    @PreAuthoriza("hasRole('ROLE_USER')")
    void m()
}
interface SuperInterface implements SuperSuperInterface{}

class MyClass implements SuperInterface
{
    void m(){}
}

annotation of method m is found reflectivly if annotated signature is moved from SuperSuperInterface to SuperInterface but in above case it is not.

Hamed

**Comment by spring-issuemaster** [comment]
This issue relates to #2372
