### ISSUE TITLE
SEC-2149: Spring Security 3.2.0M1 and 3.1.3 release not compatible with spring framework 3.2.1 release with OSGi

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2375]
[Jack Rudnick](https://jira.spring.io/secure/ViewProfile.jspa?name=ccadjack) (Migrated from [SEC-2149](https://jira.spring.io/browse/SEC-2149?redirect=false)) said:

Attempting to upgrade spring framework to 3.2.1 and spring security to 3.2.0.  The spring security website claims that spring security is compatible with 3.2.0+ of spring framework.  In an OSGi environment, this is not true as spring security bundle manifest attempts spring framework package imports with a version range maximum of 3.2.0. I tried also using spring security 3.2.0M1 and the issue is the same.

**Comment by spring-issuemaster** [comment]
This issue duplicates #2343
