### ISSUE TITLE
SEC-2167: Add XSS Filter

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2393]
[Mike Reedell](https://jira.spring.io/secure/ViewProfile.jspa?name=mreedell) (Migrated from [SEC-2167](https://jira.spring.io/browse/SEC-2167?redirect=false)) said:

Provide a XSS filter to sanitize URL querystrings and headers to mitigate XSS attacks.

See the filter and request wrapper implemented in this blog post (not mine):
http://ricardozuasti.com/2012/stronger-anti-cross-site-scripting-xss-filter-for-java-web-apps/

**Comment by rwinch** [comment]
This can cause problems on its own and can be seen by browsers attempts to sanatize HTML
