### ISSUE TITLE
SEC-2224: ActiveDirectoryLdapAuthenticationProvider throws BadCredentialsException if userPrincipalName not equal to sAMAccountName + @domain

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2448]
[Michael Solano](https://jira.spring.io/secure/ViewProfile.jspa?name=mike.solano.developer@gmail.com) (Migrated from [SEC-2224](https://jira.spring.io/browse/SEC-2224?redirect=false)) said:

When using the sAMAccountName for authentication via ActiveDirectoryLdapAuthenticationProvider, a BadCredentialsException will be thrown if the userPrincipalName is not the sAMAccountName with @domain post-fixed.

For example, if the sAMAccountName is "bwayne" but the userPrincipalName is "bruce.wayne@batcave.net", authentication will fail. The createBindPrincipal method assumes the userPrincipalName will be "bwayne@batcave.net" and not "bruce.wayne@batcave.net". 

The code below shows the details of that method:

```
    String createBindPrincipal(String username) {
        if (domain == null || username.toLowerCase().endsWith(domain)) {
            return username;
        }

        return username + "@" + domain;
    }
```

**Comment by gkibilov** [comment]
Still an issue using Spring 4.0.3, injecting sAMAccountName filter has no effect as searchForUser still uses bindPrincipal when calling searchForSingleEntryInternal!

**Comment by taasjord** [comment]
This is still an issue. In my case the userPrincipalName has a different suffix than domain, ie. while bindPrincipal is "bwayne@batcave.net", the userPrincipalName is "bwayne@gotham.com" and sAMAccountName is "bwayne".

So I need to pass username to match sAMAccountName instead. My solution was just to copy the entire source of ActiveDirectoryLdapAuthenticationProvider (along with a package private exception) and change bindPrincipal to username.

**Comment by adamjhamer** [comment]
Hi,

I've been looking at the issues of sAMAccountName in search filters and the history of requests and changes to ActiveDirectoryLdapAuthenticationProvider, and I believe this issue can now be closed in favour of using the new rootDn and leaving the domain blank.

Flexibility was added to allow the use of a custom search filters, such as sAMAccountName, through #SEC-1915. A change was also made, #SEC-2987, to change the username to the bindPrincipal which then presented the search with username@domain and not just username. I understand the Pre-Win2k domain name is not part of the sAMAccountName attribute, so it is not correct to supply a domain in the search filter (we also have different domain names on the userPrincipalName to the sAMAccountName as @taasjord above). However a domain is required for the searchRoot (error thrown in ActiveDirectoryLdapAuthenticationProvider.searchRootFromPrincipal) - so we end up with a catch-22 -
 hence the workaround @gkibilov provides above.

The latest code though now allows rootDN to be specified for the searchRoot whilst leaving the domain empty. This means we can keep the domain blank which satisfies the filter when using sAMAccountName, but satisfies searchRoot being provided with a rootDn. We copied the latest class in (fbb902c), and specified the rootDn, left the domain blank and its working.

Therefore this issue can be closed again, but I do feel that this position is fragile - so it would be good to allow the username to be also passed in to match the searchFilter as above by @gkibilov:
`return SpringSecurityLdapTemplate.searchForSingleEntryInternal(context,
                    searchControls, searchRoot, searchFilter,
                    new Object[] { bindPrincipal, userName});
`

Thanks
Adam

**Comment by adamjhamer** [comment]
Further to my above comment, it was necessary for us to use a domain in the end because some AD accounts differed between their sAMAccountName and their 'User DN' name (not just the domain!). This meant the username passed in (expecting to match sAMAccountName) wasn't finding them since the user's DN was different. By providing the domain allowed both accounts to be found - a separate rootDn context was not enough.

Being required to provide the domain meant we were back with the problem of the searchFilter using the user@domain format, when sAMAccountName must only have the username. So we modified the latest code to add `new Object[] { bindPrincipal, userName})` (as above) which allows the searchFilter to reference the second argument, the username, with `(&(objectClass=user)(sAMAccountName={1}))`.

So whether this is considered a separate issue I'm not sure! Its not a domain mismatch (which is now catered for in the latest code) but a username DN mismatch which was solved by the change of code to `new Object[] { bindPrincipal, userName})`!

Thanks
Adam

**Comment by taasjord** [comment]
I just want to note that I did try to use rootDN and blank domain, but that doesn't work for me, because the domain is needed in bindAsUser (but cannot be in searchForUser).

The proposed change  to add the necessary flexibility is very small and I don't see what harm it could make.

**Comment by sidamos** [comment]
I strongly vote for accepting this pull request. We have exactly the same problem. 

If at least ActiveDirectoryLdapAuthenticationProvider was not final and the affected method was not private...

**Comment by mdeterman** [comment]
+1
I'm having the same issue.

**Comment by rehmatt** [comment]
+1
Same here

**Comment by shafsongithub** [comment]
This issue still persists even after new code checked-in in RC.

**Comment by taasjord** [comment]
@shafsongithub, did you set the search filter to use it?
Eg: `provider.setSearchFilter("sAMAccountName={1}");`

**Comment by shafsongithub** [comment]
No.. sounds like this will resolve my issue. I will try and let you guys know. BTW When this fix is coming in Release?

**Comment by shafsongithub** [comment]
It worked. Thanks for your timely comment.

**Comment by aivantsov** [comment]
Would you please integrate/cherry-pick [the fix](https://github.com/taasjord/spring-security/commit/2d44c1036d873ae34e656e2efd90ca33be31246e) into the 4.2.x branch. 
Thanks in advance.

N.B. Currently cannot switch to Spring Boot 2.x which would solve the issue due to a third party lib limitation.
