### ISSUE TITLE
SEC-2229: Cleanup Optional Dependencies

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2452]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2229](https://jira.spring.io/browse/SEC-2229?redirect=false)) said:

There are a number of dependencies within Spring Security that should be marked as optional.

For example, spring-jdbc is listed in spring-security-web but not marked as optional. The use of spring-jdbc is restricted to JdbcTokenRepositoryImpl which is used for remember me support.

We should go through all the dependencies and ensure the dependencies that are optional are marked as such.

**Comment by spring-issuemaster** [comment]
This issue supersedes #2401
