### ISSUE TITLE
SEC-2236: Logout of WebSocket Sessions when Logout of HttpSession

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2459]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2236](https://jira.spring.io/browse/SEC-2236?redirect=false)) said:

Determine issues around synchronizing the WebSocket Session and HttpSession

**Comment by spring-issuemaster** [comment]
This issue depends on #2780
