### ISSUE TITLE
SEC-2237: API documentation for FirewalledRequest.reset() incomplete

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2460]
[Dominik Seichter](https://jira.spring.io/secure/ViewProfile.jspa?name=domseichter) (Migrated from [SEC-2237](https://jira.spring.io/browse/SEC-2237?redirect=false)) said:

The API documentation of the method FirewalledRequest.reset is incomplete and ends immendiately before giving the most important piece of information:

Right now, the last setence reads like this:
"An implementation can thus choose to modify the state of the request for the security infrastructure, while still maintaining the [!]"

The important information is what is still maintained. This is missing right now.

**Comment by spring-issuemaster** [comment]
This issue duplicates #2447
