### ISSUE TITLE
SEC-2272: CsrfRequestDataValueProcessor should support Spring 4.2.0M2+

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2485]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2272](https://jira.spring.io/browse/SEC-2272?redirect=false)) said:

RequestDataValueProcessor was changed non-passively in Spring 4.0.0.M2 so we should make changes to CsrfRequestDataValueProcessor to support both versions. See https://jira.springsource.org/browse/SPR-10041

**Comment by spring-issuemaster** [comment]
This issue relates to https://jira.spring.io/browse/SPR-10041
