### ISSUE TITLE
SEC-2273: CORS Suport

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2486]
Migrated from [SEC-2273](https://jira.spring.io/browse/SEC-2273?redirect=false)

**Comment by spring-issuemaster** [comment]
This issue relates to https://jira.spring.io/browse/SPR-9278

**Comment by sdeleuze** [comment]
For people using Spring Security + Spring MVC, see http://docs.spring.io/spring-security/site/docs/current/reference/html/cors.html.

**Comment by rwinch** [comment]
Thanks for the link @sdeleuze This has been solved via spring-web, so closing the issue
