### ISSUE TITLE
SEC-2303: WebSecurity's default expression handler does not have the bean resolver set

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2529]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2303](https://jira.spring.io/browse/SEC-2303?redirect=false)) said:

Similar to SEC-2301

**Comment by spring-issuemaster** [comment]
This issue relates to #2526
