### ISSUE TITLE
SEC-2323: CSFR Protection fails with multipart/form-data

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2551]
[Marten Deinum](https://jira.spring.io/secure/ViewProfile.jspa?name=mdeinum) (Migrated from [SEC-2323](https://jira.spring.io/browse/SEC-2323?redirect=false)) said:

Combining CSFR protection with file uploads seem to break proper CSFR protection. Looks like the parameters aren't available (they are probably part of the body instead of parameters).

**Comment by spring-issuemaster** [comment]
This issue duplicates #2517
