### ISSUE TITLE
SEC-2376: Document/Fix CSRF behavior with pre-auth

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2596]
[Patrick Radtke](https://jira.spring.io/secure/ViewProfile.jspa?name=pradtke) (Migrated from [SEC-2376](https://jira.spring.io/browse/SEC-2376?redirect=false)) said:

3.2.0.RC1 with <http auto-config="true">  with <csrf/> and a preauth filter

When a user first accesses a pre-authed site
1. the CSRF token is added to the session.
2. The pre-auth filter creates the Authentication and related security context
3. The SessionManagementFilter then runs, and since its a new auth and session it calls 'CsrfAuthenticationStrategy' which removes the CSRF token from the session.
4. The return view now has an invalid CSRF token in any forms.

A 2nd GET creates a new CSRF token, and then everything works normally.

---

I posted my workaround in the forum, but it would nice to:
1. Document the behavior/workaround in

http://docs.spring.io/spring-security/site/docs/3.2.x-SNAPSHOT/reference/html/csrf.html

so that others don't have the same issue.
1. Offer a better way (or workaround) to remove the CsrfAuthenticationStrategy from the session management.

Is defining my own custom CSRF filter and repository a "cleaner" workaround to defining my own session management filter?

Or is updating the xsd, and doing something like <csrf auth-strategy="disable"/> a possibility?

**Comment by spring-issuemaster** [comment]
This issue duplicates #2488
