### ISSUE TITLE
SEC-2380: Default configuration of SHA-256 algorithm differs between 1.2.7.3 & 2.0-RC2 versions 

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2605]
[Sergi Jané](https://jira.spring.io/secure/ViewProfile.jspa?name=jagiro) (Migrated from [SEC-2380](https://jira.spring.io/browse/SEC-2380?redirect=false)) said:

Hi,

I would like to report a detail that I have not found in the plugin documentation.

Scenario 1:
    gvm default grails 2.2.1
    grails create-app Scenario1
    Add into BuildConfig.groovy
        compile ":spring-security-core:1.2.7.3"
    grails compile
    grails2-quickstart com.company.domain User Role
    Add into Bootstrap.groovy
        def grailsApplication
        def init = { servletContext ->
            def user = new User(username:"test", password:"test", enabled:true).save()
            def role = new Role(authority:"my").save()
            UserRole.create(user, role)
            println "Password " +  User.findByUsername("test").password  
        }
    grails run-app
    >> the password printed: 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08

Scenario 2:
    gvm default grails 2.3.1
    grails create-app Scenario2
    Add into BuildConfig.groovy
        compile ":spring-security-core:2.0-RC2"
    grails compile
    grails2-quickstart com.company.domain User Role
    Add into Config.groovy
        grails.plugin.springsecurity.password.algorithm='SHA-256'
    Add into Bootstrap.groovy
        def grailsApplication
        def init = { servletContext ->
            def user = new User(username:"test", password:"test").save()
            def role = new Role(authority:"my").save()
            UserRole.create(user, role)
            println "Password " +  User.findByUsername("test").password  
        }
    grails run-app
    >> the password printed: f85f9dafda2e2e35fb5a9d960d15be951d505491800cc8e0315f3b76498cfcdc

The printed passwords differs!

Adding this line has worked.
    grails.plugin.springsecurity.password.hash.iterations=1

It might be good to add to the documentation.

Cheers

**Comment by rwinch** [comment]
Please report issues related to grails plugin to their issue tracker https://github.com/grails-plugins/grails-spring-security-core/issues
