### ISSUE TITLE
SEC-2381: unlimited session count with ConcurrentSessionControlStrategy

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2607]
[Vasyl Khrystiuk](https://jira.spring.io/secure/ViewProfile.jspa?name=msangel) (Migrated from [SEC-2381](https://jira.spring.io/browse/SEC-2381?redirect=false)) said:

ConcurrentSessionControlStrategy.maximumSessions can be "-1" as indication of unlimited session count, but there is not possible to set this value in spring-security context configuration due to XML validation rules:

org.xml.sax.SAXParseException: cvc-minInclusive-valid: Value '-1' is not facet-valid with respect to minInclusive '1' for type 'positiveInteger'.

Used schema: 
http://www.springframework.org/schema/security/spring-security-3.1.xsd

**Comment by spring-issuemaster** [comment]
This issue duplicates #2162
