### ISSUE TITLE
SEC-2398: Ill-formated link in when-to-use-csrf section

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2618]
[Ramnivas Laddad](https://jira.spring.io/secure/ViewProfile.jspa?name=ramnivas) (Migrated from [SEC-2398](https://jira.spring.io/browse/SEC-2398?redirect=false)) said:

In http://docs.spring.io/spring-security/site/docs/3.2.0.RC2/reference/htmlsingle/#when-to-use-csrf-protection, a link is broken.

The text shows: "For example, a malicious user can create ahttp://blog.opensecurityresearch.com/2012/02/json-csrf-with-parameter-padding.html[CSRF with JSON using the following form]"

**Comment by eleftherias** [comment]
This was fixed in 3.2.0.RELEASE.
