### ISSUE TITLE
SEC-2401: A sample application using custom SessionRegistry and not using HttpSession 

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2621]
[Cemo Koc](https://jira.spring.io/secure/ViewProfile.jspa?name=cemkoc) (Migrated from [SEC-2401](https://jira.spring.io/browse/SEC-2401?redirect=false)) said:

It would be really nice to have a sample application at samples which is implementing a custom SessionRegistry and does not rely on HttpSession.

**Comment by rwinch** [comment]
The samples have been externalized to https://github.com/spring-projects/spring-security-samples
