### ISSUE TITLE
SEC-2414: Incorrect use of link in documentation about Clickjacking (X-Frame-Options)

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2630]
[Driss Amri](https://jira.spring.io/secure/ViewProfile.jspa?name=amridri) (Migrated from [SEC-2414](https://jira.spring.io/browse/SEC-2414?redirect=false)) said:

There is a small typo/mistake in the documentation about X-Frame-Options, the link for Clickjacking to wikipedia is showing up incorrectly. 

"This sort of attack is known ashttp://en.wikipedia.org/wiki/Clickjacking[Clickjacking]."

**Comment by spring-issuemaster** [comment]
This issue duplicates #2606
