### ISSUE TITLE
SEC-2417: Make more obvious that pom.xml cannot be used for building Spring Security

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2638]
[Mat Booth](https://jira.spring.io/secure/ViewProfile.jspa?name=mbooth) (Migrated from [SEC-2417](https://jira.spring.io/browse/SEC-2417?redirect=false)) said:

The maven pom.xml files should declare all the dependencies necessary to build a given module, but the pom.xml for the core module does not declare a compile-time dependency on the crypto module.

**Comment by eleftherias** [comment]
The Spring Security samples have now moved to the [spring-security-samples](https://github.com/spring-projects/spring-security-samples) repository.
Each sample can be run independently and you can easily which dependencies are used in the build.gradle for each sample.
