### ISSUE TITLE
SEC-2457: Warning "Method 'setFilterProcessesUrl' is marked deprecated" on http-login and http-logout tag

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2678]
[Fernandez Ludovic](https://jira.spring.io/secure/ViewProfile.jspa?name=dez) (Migrated from [SEC-2457](https://jira.spring.io/browse/SEC-2457?redirect=false)) said:

<security:form-login login-page='/login' default-target-url="/" authentication-failure-url="/loginfailed" />
<security:logout logout-success-url="/" invalidate-session="true" logout-url="/logout" />

Warning appear on each line : "Method 'setFilterProcessesUrl' is marked deprecated"

Is there now a new recommended way to do this?

I have not seen anything in the documentation about it.

**Comment by spring-issuemaster** [comment]
This issue duplicates #2675
