### ISSUE TITLE
SEC-2459: Spring Security Cookie Issue. Cookie not flagged HTTP-Only

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2680]
[Vivek Sharma](https://jira.spring.io/secure/ViewProfile.jspa?name=vivekshrma2010@gmail.com) (Migrated from [SEC-2459](https://jira.spring.io/browse/SEC-2459?redirect=false)) said:

The authentication cookie generated by the spring authentication framework is critical since it contains the session id. The cookie is not marked http-only.
This implies that if the application is vulnerable to XSS, attacker can steal the JSessionId cookie.

The issue can be remediated by marking the cookie HTTP-Only. This can be done in the configuration file as well. Other than this there are many ways to rectify the issue

**Comment by ramesh75** [comment]
Vivek,

Can you share your complete code?
