### ISSUE TITLE
SEC-2463: CSRF documentation should explain EnableWebMvcSecurity

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2684]
[Daniel Fernández](https://jira.spring.io/secure/ViewProfile.jspa?name=dfernandez) (Migrated from [SEC-2463](https://jira.spring.io/browse/SEC-2463?redirect=false)) said:

CSRF section of reference should talk about EnableWebMvcSecurity annotation

**Comment by spring-issuemaster** [comment]
This issue relates to #2656
