### ISSUE TITLE
SEC-2464: Spring MVC form tag no longer inserting CSRF token after upgrading to Spring Security 3.2.0.RELEASE

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2685]
[Anurup Joseph](https://jira.spring.io/secure/ViewProfile.jspa?name=anurup) (Migrated from [SEC-2464](https://jira.spring.io/browse/SEC-2464?redirect=false)) said:

I was using Spring Security 3.2.0.RC2 to secure my web-app and used the Spring MVC form tag to automatically insert the CSRF token in my forms.

After upgrading my Maven POM to reference Spring Security 3.2.0.RELEASE instead of 3.2.0.RC2, I find that the Spring MVC form tag no longer automatically inserts the CSRF token into my forms.  I confirmed that manually inserting the &lt;input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/&gt;

**Comment by spring-issuemaster** [comment]
This issue relates to #2656
