### ISSUE TITLE
SEC-2465: Workaround WebLogic's bug with servletContext.addFilter(...)

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2686]
[Carles Figuera](https://jira.spring.io/secure/ViewProfile.jspa?name=carlinhos) (Migrated from [SEC-2465](https://jira.spring.io/browse/SEC-2465?redirect=false)) said:

OS: Windows 7 (64 bits)
JDK: 1.6.0_45
WebLogic's Version: 12.1.1.0.6
Spring Security Version: 3.2.0.RELEASE

When a filter is created in WebLogic with method servletContext.addFilter(String filterName, Filter filter), the filter is created but never initialized. So WebLogic users must use servletContext.addFilter(String filterName, java.lang.Class<? extends Filter> filterClass) to avoid this bug.

When we extends AbstractSecurityWebApplicationInitializer, this class uses the first addFilter() method mentioned, so in WebLogic, the filter never calls init() method. (AbstractSecurityWebApplicationInitializer.java:213)

It's a WebLogic's fault and not a Spring's one, but I think you may know it.

**Comment by manisk09** [comment]
Rob,

I ran into similar issue with securityFilterChain for WebLogic. Can you please suggest me on how I could implement WebApplicationInitializer in my case. 

Thanks,
Mani.
