### ISSUE TITLE
SEC-2481: Programmatic authentication in a web application is undoable

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2702]
[Adam Walczak - WALCZAK.IT](https://jira.spring.io/secure/ViewProfile.jspa?name=walec51) (Migrated from [SEC-2481](https://jira.spring.io/browse/SEC-2481?redirect=false)) said:

At first glance this seams simple - you can find this code everywhere on the net:

```
UsernamePasswordAuthenticationToken authReq = new UsernamePasswordAuthenticationToken(c.getUsername(), c.getPassword());
authReq.setDetails(new WebAuthenticationDetails(reqAttrs.getRequest()));
Authentication authRes = getAuthenticationManager().authenticate(authReq);
SecurityContext context = SecurityContextHolder.getContext();
context.setAuthentication(authRes);
```

you put it in a controller method and its seams to work at first - your secured code in the same request gets executed. Bah ! you are even able to open another web page which will recognize you authentication properly.

However on the next page (after the first one) your authentication is lost... mind boggling... isn't it ? It works like this all the time. Event if you start putting the SecurityContext to the HTTP session your self. You debug and know its there in the session but to your surprise SecurityContextHolder.getContext().getAuthentication() returns null.

After a whole day of hacking and googling you find one line of code:

```
authReq.setDetails(new WebAuthenticationDetails(reqAttrs.getRequest()));
```

at first it seamed to work but the result just turned out to be totally random. Once you get the Authentication object, once you don't...

**Comment by Horsed** [comment]
This issue is old. What about closing it? If it was a real bug, it would return.

**Comment by rwinch** [comment]
If you want the `SecurityContext` to persist, then you must also save it in the `SecurityContextRepository`.
