### ISSUE TITLE
SEC-2488: Make the PreFilter annotation support filtering of an immutable list.

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2708]
[Quinten Krijger](https://jira.spring.io/secure/ViewProfile.jspa?name=qkrijger) (Migrated from [SEC-2488](https://jira.spring.io/browse/SEC-2488?redirect=false)) said:

I posted a pull request on github, but I haven't heard of it for two months, so I thought JIRA might be a better route.

I put the github pull request in here as Pull Request URL.

**Comment by spring-issuemaster** [comment]
This issue duplicates #2316
