### ISSUE TITLE
SEC-2491: KeyBasedPersistenceTokenService pseudoRandomNumberBytes should default to 32

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2711]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2491](https://jira.spring.io/browse/SEC-2491?redirect=false)) said:

We also need to remove the depreacted setPseudoRandomNumberBits method

**Comment by spring-issuemaster** [comment]
This issue relates to #2614
