### ISSUE TITLE
SEC-2497: checkForPrincipalChanges limited to String Principal

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2716]
[Fabrice Marchal](https://jira.spring.io/secure/ViewProfile.jspa?name=fabricemarchal) (Migrated from [SEC-2497](https://jira.spring.io/browse/SEC-2497?redirect=false)) said:

In AbstractPreAuthenticatedProcessingFilter,
method requiresAuthentication , Principal are assumed to be String 

 if (currentUser.getName().equals(principal)) 

should be

  if (currentUser.getPrincipal().equals(principal))

**Comment by spring-issuemaster** [comment]
This issue duplicates #2302
