### ISSUE TITLE
SEC-2503: CAS Clearpass extension

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2720]
[Misagh Moayyed](https://jira.spring.io/secure/ViewProfile.jspa?name=misagh) (Migrated from [SEC-2503](https://jira.spring.io/browse/SEC-2503?redirect=false)) said:

Provide a way to easily retrieve the principal's password.via the Clearpass extension for CAS.

Once you have:
- Properly configured CAS server clearpass machinery
- Spring Security client side standard CAS with proxy tickets config
- A tiny bit of this ClearPass config (basically it's just a CasAuthenticationProvider bean replacement)
- ...then retrieving a password (after a successful CAS authentication of course) is just a matter of obtaining UserDetails instance from SecurityContext and calling UserDetails#getPassword.

**Comment by spring-issuemaster** [comment]
This issue duplicates #2721
