### ISSUE TITLE
SEC-2544: CAS JavaConfig Sample

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2756]
[Simon Wong](https://jira.spring.io/secure/ViewProfile.jspa?name=simonwg) (Migrated from [SEC-2544](https://jira.spring.io/browse/SEC-2544?redirect=false)) said:

It would be nice if a CAS JavaConfig sample could be provided.

**Comment by spring-issuemaster** [comment]
This issue relates to #2990

**Comment by rwinch** [comment]
The samples have been externalized to https://github.com/spring-projects/spring-security-samples
