### ISSUE TITLE
SEC-2545: Failure to fully configurate SessionFixationProtectionStrategy

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2757]
[Diogo Quintela](https://jira.spring.io/secure/ViewProfile.jspa?name=dquintela) (Migrated from [SEC-2545](https://jira.spring.io/browse/SEC-2545?redirect=false)) said:

In SpringSec 3.0, we were using the following paradigm for configuration of "retainedAttributes"
  in SessionFixationProtectionStrategy, because the namespace configuration doesn't support this attribute.

```xml 
  <http auto-config="false">
    ..
    <session-management session-authentication-strategy-ref="sas" />
    ..
  </http>

  <bean id="sas" class="org.springframework.security.web.authentication.session.SessionFixationProtectionStrategy">
    <property name="migrateSessionAttributes" value="false"/>
    <property name="retainedAttributes">
      <list>
	<value>someAtrributeName</value>
      </list>
    </property>
  </bean>
``` 

  Now, in the upgrade path to SpringSec 3.2.3, it was detected that two instances of SessionFixationProtectionStrategy
  were being deployed - The second - our configured one - failing to be applied because of "request.isRequestedSessionIdValid()"
  returning false in the second instance (in AbstractSessionFixationProtectionStrategy), so efectivelly all session attributes
  were being copied.

  To overcome this, we tried to disabled automatic configured session-fixation-protection configuration to "none" - we are already 
  providing one - fully configured.

```xml 
  <http auto-config="false">
    ..
    <session-management session-fixation-protection="none" session-authentication-strategy-ref="sas" />
    ..
  </http>

  <bean id="sas" class="org.springframework.security.web.authentication.session.SessionFixationProtectionStrategy">
    <property name="migrateSessionAttributes" value="false"/>
    <property name="retainedAttributes">
      <list>
	<value>someAtrributeName</value>
      </list>
    </property>
  </bean>
``` 

  However the namespace configurer "HttpConfigurationBuilder" refuses to accepth both attributes as it might, since this seems a possible use case.

``` 
org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: session-fixation-protection attribute cannot be used in combination with session-authentication-strategy-ref
Offending resource: ServletContext resource [/WEB-INF/applicationContext-security.xml]
...
	at org.springframework.security.config.http.HttpConfigurationBuilder.createSessionManagementFilters(HttpConfigurationBuilder.java:299)
	at org.springframework.security.config.http.HttpConfigurationBuilder.<init>(HttpConfigurationBuilder.java:164)
	at org.springframework.security.config.http.HttpSecurityBeanDefinitionParser.createFilterChain(HttpSecurityBeanDefinitionParser.java:135)
```

**Comment by KyleRogers** [comment]
I think this issue can be closed - the setter for retainedAttributes [got removed](https://github.com/spring-projects/spring-security/commit/6e204fff72b80196a83245cbc3bd0cd401feda00#diff-4386c97d3579fa498f86c314566325d1L162) 18 month ago.

Maybe there can be some cleanup for SessionFixationProtectionStrategy: The attribute ```retainedAttributes``` is never written/assigned and there is a dead code path in createMigratedAttributeMap() left.

**Comment by jgrandja** [comment]
Thanks @KyleRogers and I agree this issue is no longer valid given the `retainedAttributes` property has been removed.
