### ISSUE TITLE
SEC-2550: Classloader leak in Java 7 and 8 but not 6

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2760]
[Arlo O'Keeffe](https://jira.spring.io/secure/ViewProfile.jspa?name=arlo) (Migrated from [SEC-2550](https://jira.spring.io/browse/SEC-2550?redirect=false)) said:

I have an integration test in my application that tests for classloader leaks and it fails since I introduced spring security. Therefore I tried reproducing the problem with the helloworld-jc sample and it also leaks.

To reproduce:
* package the helloworld-jc application
* start a tomcat with java 7 or 8
* deploy the application
* stop the application
* execute 'Find Leaks'
* see that the application leaks

If you start the application with Java 6, everything works. Therefore this might actually be a java problem but I don't know where to report such a problem.

I also took a heap dump and looked for GC roots from the webappclassloader but could not find any.

**Comment by ArloL** [comment]
I have not found any further issues. This can be closed.

**Comment by jgrandja** [comment]
Thanks for getting back to us @ArloL.
