### ISSUE TITLE
SEC-2549: java.lang.IllegalAccessError: class org.springframework.security.config.annotation.authentication.configuration.$Proxy90 cannot access its superinterface <omitted>.AuthenticationConfiguration$LazyBean

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2763]
[Pei-Tang Huang](https://jira.spring.io/secure/ViewProfile.jspa?name=tan9) (Migrated from [SEC-2549](https://jira.spring.io/browse/SEC-2549?redirect=false)) said:

Is it possible to change the visibility of LazyBean marker interface to `public`?

We are planning to pull up spring dependencies as JBoss EAP "module" (shared libraries) to be shared among all of our applications.
Each "module" has its own isolated ClassLoader, and is parallel to the war "module" ClassLoader, so we have to emulate the class loading hierarchy ourselves for compatibility.
The problem is that the aggregated ClassLoader (delegates to "module" classLoader and then the applications's ClassLoader) cannot sees the private LazyBean marker.

**Comment by spring-issuemaster** [comment]
This issue relates to #2744
