### ISSUE TITLE
SEC-2557: GrantedAuthoritiesMapper can't be set in LdapAuthenticationProviderConfigurer

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2768]
[Tony Dalbrekt](https://jira.spring.io/secure/ViewProfile.jspa?name=dalbrekt) (Migrated from [SEC-2557](https://jira.spring.io/browse/SEC-2557?redirect=false)) said:

There is no way to select your own implementation of GrantedAuthoritiesMapper when LdapAuthenticationProviderConfigurer is used to build
LdapAuthenticationProvider. 

LdapAuthenticationProviderConfigurer creates an instance of SimpleAuthorityMapper internally which can't be changed.

**Comment by rwinch** [comment]
Fixed in #82
