### ISSUE TITLE
SEC-2565: Incorporate Password Storage Scheme spec into stored format

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2777]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2565](https://jira.spring.io/browse/SEC-2565?redirect=false)) said:

This would be similar to BCrypt <scheme>$<ver>$<iter count>$<salt>$<digest> This is important so we can upgrade the way users passwords are stored as they authenticate.

NOTE: May be good to support persisting the password differently based upon the user. For example, protect an admin password more than that of average user.

**Comment by rwinch** [comment]
This was taken care of using `DelegatingPasswordEncoder` in #4666 which maps an id to an instance of `PasswordEncoder`.
