### ISSUE TITLE
SEC-2569: SavedRequestAwareWrapper should not override cookies

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2781]
[Igor Mukhin](https://jira.spring.io/secure/ViewProfile.jspa?name=iimuhin) (Migrated from [SEC-2569](https://jira.spring.io/browse/SEC-2569?redirect=false)) said:

Motivation is described in SPR-11698

**Comment by spring-issuemaster** [comment]
This issue supersedes https://jira.spring.io/browse/SPR-11698

**Comment by spring-issuemaster** [comment]
This issue supersedes https://jira.spring.io/browse/SPR-11698

**Comment by spring-issuemaster** [comment]
This issue supersedes https://jira.spring.io/browse/SPR-11698

**Comment by spring-issuemaster** [comment]
This issue supersedes https://jira.spring.io/browse/SPR-11698

**Comment by spring-issuemaster** [comment]
This issue supersedes https://jira.spring.io/browse/SPR-11698

**Comment by spring-issuemaster** [comment]
This issue supersedes https://jira.spring.io/browse/SPR-11698
