### ISSUE TITLE
SEC-2570: LogoutConfigurer supports GET by default when CSRF is enabled

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2782]
[John Vasileff](https://jira.spring.io/secure/ViewProfile.jspa?name=jvasileff) (Migrated from [SEC-2570](https://jira.spring.io/browse/SEC-2570?redirect=false)) said:

Since commit 5082a046 for SEC-2311, the default LogoutRequestMatcher supports all HTTP methods regardless of the CSRF configuration.

You can see in the LogoutConfigurer.java code below that a POST only matcher is created, but not used:

```
    @SuppressWarnings("unchecked")
    private RequestMatcher getLogoutRequestMatcher(H http) {
        if(logoutRequestMatcher != null) {
            return logoutRequestMatcher;
        }
        if(http.getConfigurer(CsrfConfigurer.class) != null) {
            this.logoutRequestMatcher = new AntPathRequestMatcher(this.logoutUrl, "POST");
        }
        return new AntPathRequestMatcher(this.logoutUrl);
    }
```

**Comment by spring-issuemaster** [comment]
This issue duplicates #2755
