### ISSUE TITLE
SEC-2599: HttpSessionEventPublisher should get required ApplicationContext

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2783]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2599](https://jira.spring.io/browse/SEC-2599?redirect=false)) said:

We should use WebApplicationContextUtils.getRequiredWebApplicationContext to get better error messages and avoid NullPointerException

**Comment by spring-issuemaster** [comment]
This issue relates to #2809
