### ISSUE TITLE
SEC-2583: Create Java Config sample for CAS

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2797]
[Dmitriy Kopylenko](https://jira.spring.io/secure/ViewProfile.jspa?name=dmitriy) (Migrated from [SEC-2583](https://jira.spring.io/browse/SEC-2583?redirect=false)) said:

Please provide a Java Config sample for Jasig CAS configuration.

**Comment by spring-issuemaster** [comment]
This issue duplicates #2756
