### ISSUE TITLE
SEC-2587: Improvements in Spring Test

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2801]
Migrated from [SEC-2587](https://jira.spring.io/browse/SEC-2587?redirect=false)

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-8854
This issue depends on https://jira.spring.io/browse/SPR-11466
This issue depends on https://jira.spring.io/browse/SPR-11497

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-8854
This issue depends on https://jira.spring.io/browse/SPR-11466
This issue depends on https://jira.spring.io/browse/SPR-11497

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-8854
This issue depends on https://jira.spring.io/browse/SPR-11466
This issue depends on https://jira.spring.io/browse/SPR-11497

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-8854
This issue depends on https://jira.spring.io/browse/SPR-11466
This issue depends on https://jira.spring.io/browse/SPR-11497

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-8854
This issue depends on https://jira.spring.io/browse/SPR-11466
This issue depends on https://jira.spring.io/browse/SPR-11497

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-8854
This issue depends on https://jira.spring.io/browse/SPR-11466
This issue depends on https://jira.spring.io/browse/SPR-11497

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-8854
This issue depends on https://jira.spring.io/browse/SPR-11466
This issue depends on https://jira.spring.io/browse/SPR-11497
