### ISSUE TITLE
SEC-2590: application can't find spring-security-3.0.4.xsd in http://www.springframework.org/schema/security/

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2805]
[Rakesh](https://jira.spring.io/secure/ViewProfile.jspa?name=rakeshuky) (Migrated from [SEC-2590](https://jira.spring.io/browse/SEC-2590?redirect=false)) said:

Unable to find  spring-security-3.0.4.xsd in http://www.springframework.org/schema/security/

It was working fine till recently and just yesterday or so we had this error showing up in eclipse.

**Comment by Gnafu** [comment]
It's gone again
