### ISSUE TITLE
SEC-2612: Documentation copy/past fail

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2828]
[Maxime Robert](https://jira.spring.io/secure/ViewProfile.jspa?name=marob) (Migrated from [SEC-2612](https://jira.spring.io/browse/SEC-2612?redirect=false)) said:

Hi,

in the documentation page http://docs.spring.io/spring-security/site/docs/3.2.0.CI-SNAPSHOT/reference/html/csrf.html#csrf-multipartfilter, it is written :

<filter-mapping>
    <filter-name>MultipartFilter</filter-name>
    <servlet-name>/*</servlet-name>
</filter-mapping>

"servlet-name"? Where does that come from? I think "url-pattern" would work way better!

Hours wasted on that, so please take a minute to fix it :)

Regards

**Comment by spring-issuemaster** [comment]
This issue duplicates #2687
