### ISSUE TITLE
SEC-2620: Make CachingUserDetailsService constructor public for easy use in Java Config

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2837]
[Marten Deinum](https://jira.spring.io/secure/ViewProfile.jspa?name=mdeinum) (Migrated from [SEC-2620](https://jira.spring.io/browse/SEC-2620?redirect=false)) said:

Trying to configure caching for anything else then the `jdbcAuthentication()` is painful. Where ldap caching is easily configured in XML that feature is (currently) not available in Java Config (at least I couldn't find it).

However to make caching configuration easier it would be nice if the `CachingUserDetailsService` could be made constructable from outside the package (maybe move to another package?). That way overriding the `userDetailsService()` method from the `WebSecurityConfigurerAdapter` would allow easy wrapping of the used `UserDetailsService` with caching

```
@Override
    protected UserDetailsService userDetailsService() {
        UserDetailsService delegate = super.userDetailsService();
        CachingUserDetailsService userDetailsService = new CachingUserDetailsService(delegate);
        userDetailsService.setUserCache(userCache());
        return userDetailsService;
    }
```

That way every `UserDetailsService` can be made cacheable without having to expose `userCache` methods for each configurer.

**Comment by ezraroi** [comment]
Any update on this? How can I use CachingUserDetailsService in my code? Currently i copied the code and made the constructor public

**Comment by mdeinum** [comment]
Apparently more people are having issues with this see http://stackoverflow.com/questions/40766098/springcachebasedusercache-is-null/40782952?noredirect=1#comment68816495_40782952.

**Comment by mofadeyunduo** [comment]
I have trouble too. How can I user CachingUserDetailsService? It has no document comments！

**Comment by Smith-Cruise** [comment]
I have trouble too!!!!!

**Comment by linghengqian** [comment]
This problem has been solved long ago, and it is no longer necessary to build `CachingUserDetailsService` through `ClassUtils.getConstructorIfAvailable(CachingUserDetailsService.class, UserDetailsService.class);`, but to use the parameterized construction function directly. See https://github.com/spring-projects/spring-security/pull/6196 , this issue should be closed to avoid misleading people.

**Comment by eleftherias** [comment]
Thanks @linghengqian! I'm closing this issue as per the comment above.
