### ISSUE TITLE
SEC-2622: Integration Tests for All Samples

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2839]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2622](https://jira.spring.io/browse/SEC-2622?redirect=false)) said:

We should have integration tests for all samples using either MockMvc or fully deployed tests for samples that use JSPs

**Comment by rwinch** [comment]
The samples have been externalized to https://github.com/spring-projects/spring-security-samples
