### ISSUE TITLE
SEC-2718: LdifFileLoader created by ApacheDSContainer should use same ClassLoader as the container

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2846]
[Marvin Frommhold](https://jira.spring.io/secure/ViewProfile.jspa?name=depressiverobot) (Migrated from [SEC-2718](https://jira.spring.io/browse/SEC-2718?redirect=false)) said:

The [Spring Boot Reference Guide](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#build-tool-plugins-gradle-packaging) states that it's possible to create both executable and deployable WAR files. However, it is not possible to have an embedded LDAP which loads the LDIF file from the WAR package. When deploying the WAR file into an external servlet container loading of the LDIF file works. I created a [sample Spring Boot project](https://github.com/depressiveRobot/ldap-embedded-web) to demonstrate this problem.

The reason, why this does not work, is that the LdifFileLoader used by the ApacheDSContainer uses its own ClassLoader instance instead the one from the container. This can be fixed by setting the container's ClassLoader in the constructor of the LdifFileLoader.

**Comment by eleftherias** [comment]
Closing as resolved. See comment above for details.
