### ISSUE TITLE
SEC-2654: API as WebMvcConfigurer

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2872]
[cemo koc](https://jira.spring.io/secure/ViewProfile.jspa?name=cemokoc) (Migrated from [SEC-2654](https://jira.spring.io/browse/SEC-2654?redirect=false)) said:

I have a couple of web modules and they are bundled together and working in embedded application. WebMvcConfigurer part of Spring MVC lets developer to separate necessary logic into different bundles. For example a web module can register its MethodReturnHandler etc... 

Now I would like to separate Social Login part of my application to another bundle but It requires SpringSocialConfigurer to be registered by Spring Security to work properly. 

I think that it would be great to support configurer style for Spring Security.

**Comment by eleftherias** [comment]
Closing as per previous comment.
