### ISSUE TITLE
SEC-2743: Add rememberMeParameter to RememberMeConfigurer

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2877]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=robwinch) (Migrated from [SEC-2743](https://jira.spring.io/browse/SEC-2743?redirect=false)) said:

RememberMeConfigurer is missing a setter for the rememberMeParameter. The rememberMeParameter is only configurable with a xml configuration but not with a java configuration

**Comment by eleftherias** [comment]
Fixed via gh-156.
