### ISSUE TITLE
SEC-2667: Consider Oracle Guidelines

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2887]
Migrated from [SEC-2667](https://jira.spring.io/browse/SEC-2667?redirect=false)

**Comment by rwinch** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12226

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12226

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12226

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12226

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12226

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12226

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12226

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12226

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12226

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12226
