### ISSUE TITLE
SEC-2668: WebSocket Authorization

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2888]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2668](https://jira.spring.io/browse/SEC-2668?redirect=false)) said:

We need to provide authorization

**Comment by rwinch** [comment]
This issue depends on #2891
This issue depends on #2892

**Comment by spring-issuemaster** [comment]
This issue depends on #2891
This issue depends on #2892

**Comment by spring-issuemaster** [comment]
This issue depends on #2891
This issue depends on #2892

**Comment by spring-issuemaster** [comment]
This issue depends on #2891
This issue depends on #2892
