### ISSUE TITLE
SEC-2669: Improvements on Spring Framework integration

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2889]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2669](https://jira.spring.io/browse/SEC-2669?redirect=false)) said:

This describes improvements with how we integrate the Spring Framework that need to be done. Currently I am running some of this by [~rstoya05-aop] to see if there is a different way I should be doing things. Otherwise, these may end up being tickets with Spring Framework.

**Comment by rwinch** [comment]
This issue depends on #2893
This issue depends on #2894

**Comment by spring-issuemaster** [comment]
This issue depends on #2893
This issue depends on #2894

**Comment by spring-issuemaster** [comment]
This issue depends on #2893
This issue depends on #2894

**Comment by spring-issuemaster** [comment]
This issue depends on #2893
This issue depends on #2894
