### ISSUE TITLE
SEC-2672: ChannelInterceptorAdapter not reliable to clear SecurityContextHolder

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2893]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2672](https://jira.spring.io/browse/SEC-2672?redirect=false)) said:

See [spring-websocket-portfolio/security](https://github.com/rwinch/spring-websocket-portfolio/blob/5cb4992766c4eceef3c9cc05014a9391dd4a9399/src/main/java/org/springframework/samples/portfolio/config/WebSocketConfig.java#L66)

A custom ChannelInterceptorAdapter clears the SecurityContextHolder in postSend. However, the postSend in AbstractMessageChannel#send is not invoked within a finally block. Spring Security needs some sort of hook that it can guarantee that the SecurityContextHolder is cleared even if there is an error in any other preSend or the AbstractMessageChannel sendInternal method.

**Comment by rwinch** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11967

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11967

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11967

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11967

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11967

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11967

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11967

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11967

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11967

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11967
