### ISSUE TITLE
SEC-2673: WebSocket / Ease configuration of Client(Inbound|Outbound)Channel Executor

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2894]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2673](https://jira.spring.io/browse/SEC-2673?redirect=false)) said:

See [spring-websocket-portfolio/security](https://github.com/rwinch/spring-websocket-portfolio/blob/5cb4992766c4eceef3c9cc05014a9391dd4a9399/src/main/java/org/springframework/samples/portfolio/config/WebSocketConfig.java#L66)

Adding a ChannelInterceptorAdapter was very simple with @EnableWebSocketMessageBroker. However, it seemed I needed to extend WebSocketMessageBrokerConfigurationSupport in order to customize the clientInboundChannel and clientOutboundChannel Executor. Extending WebSocketMessageBrokerConfigurationSupport seems much more difficult that using the @ EnableWebSocketMessageBroker so some alternative suggestions as to how to integrate would be appreciated.

**Comment by rwinch** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11968

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11968

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11968

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11968

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11968

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11968

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11968

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11968

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11968

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11968
