### ISSUE TITLE
SEC-2676: Spring Security / Spring Data SpEL Support

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2897]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2676](https://jira.spring.io/browse/SEC-2676?redirect=false)) said:

It would be nice to provide SpEL expression support within Spring Data's `@Query` annotations. For example, we could customize a query to only return results that the user is allowed to access using something like the following:

```
@Repository
public interface MessageRepository extends JpaRepository<Message,Long> {
}
```

```
@Repository
public interface SecurityMessageRepository extends MessageRepository {
    @Override
    @Query("select m from Message m where m.to.id = ?#{ principal?.id }")
    List<Message> findAll();

    @PreAuthorize("#m?.to?.id == principal?.id")
    @Override
    <M extends Message> M save(@P("m") M m);

    @PreAuthorize("#m?.to?.id == principal?.id")
    @Override
    void delete(@P("m") Message m);
}
```

**Comment by rwinch** [comment]
This issue depends on https://jira.spring.io/browse/DATAJPA-564

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/DATAJPA-564

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/DATAJPA-564

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/DATAJPA-564

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/DATAJPA-564

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/DATAJPA-564

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/DATAJPA-564

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/DATAJPA-564

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/DATAJPA-564

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/DATAJPA-564
