### ISSUE TITLE
SEC-2680: Fire an event when logout has finished

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2900]
[Marten Deinum](https://jira.spring.io/secure/ViewProfile.jspa?name=mdeinum) (Migrated from [SEC-2680](https://jira.spring.io/browse/SEC-2680?redirect=false)) said:

During login several events can be fired like for instance `AuthenticationSuccessEvent` and `AuthenticationFailureExpiredEvent`. It would be nice that on a logout (successful, session limit exceeded etc.) also an event would be fired.

This would enable to create an `ApplicationListener` which logs the start/end of a user session.

**Comment by ptahchiev** [comment]
+1 on this one.

**Comment by kazuki43zoo** [comment]
This issue is same with #3307.

**Comment by okohub** [comment]
@rwinch hello, is this issue still active? are there any plans to integrate this feature?

**Comment by okohub** [comment]
@rwinch Hello Rob, there is an active another issue about this #3307. Should I open a new PR for this enhancement? What do you think?

**Comment by rwinch** [comment]
Thanks for pointing out the duplicate. If you are able, we'd love for a PR to be submitted.

**Comment by okohub** [comment]
@rwinch hello rob, the PR is open. Do you have a time to check? May be this can be included to 5.2.0 line. thanks! :) 

https://github.com/spring-projects/spring-security/pull/7306
