### ISSUE TITLE
SEC-2687: Follow Spring IO Dependency Versions

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2906]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2687](https://jira.spring.io/browse/SEC-2687?redirect=false)) said:

Rather than re-running all the tests with the additional versions Spring Security should update and use the Spring IO versions explicitly in the poms.

**Comment by rwinch** [comment]
Spring Security 5 now does this
