### ISSUE TITLE
SEC-2698: @EnableGlobalMethodSecurity is not respecting mode = AdviceMode.ASPECTJ

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2921]
[Janning Vygen](https://jira.spring.io/secure/ViewProfile.jspa?name=janning) (Migrated from [SEC-2698](https://jira.spring.io/browse/SEC-2698?redirect=false)) said:

Long description in link to Stackoverflow.

XML Configuration like this:

```
<security:global-method-security mode="aspectj" proxy-target-class="false" pre-post-annotations="enabled">
    <security:expression-handler ref="expressionHandler" />
</security:global-method-security>
```

The AnnotationSecurityAspect is configured by GlobalMethodSecurityBeanDefinitionParser at line 251

With a Javaconfig Class like this:

@Configuration
@EnableGlobalMethodSecurity(mode = AdviceMode.ASPECTJ, prePostEnabled = true)
public class MethodSecurityConfig extends GlobalMethodSecurityConfiguration
{
    @Override
    protected MethodSecurityExpressionHandler createExpressionHandler ( )
    { 
          ...
    }
}

The AnnotationSecurityAspect is not configured. Spring-Security will create some AutoProxy AOP Classes which is bad as I wanted to use aspectj with compile-time-weaving

**Comment by rwinch** [comment]
This issue duplicates #2810
