### ISSUE TITLE
SEC-2700: Register WithSecurityContextTestExecutionListener by default

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2923]
Migrated from [SEC-2700](https://jira.spring.io/browse/SEC-2700?redirect=false)

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11466
This issue supersedes #2771

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11466
This issue supersedes #2771

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11466
This issue supersedes #2771

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11466
This issue supersedes #2771

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11466
This issue supersedes #2771

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11466
This issue supersedes #2771

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11466
This issue supersedes #2771

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11466
This issue supersedes #2771

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-11466
This issue supersedes #2771
