### ISSUE TITLE
SEC-2790: Deprecate @EnableWebMvcSecurity

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2926]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2790](https://jira.spring.io/browse/SEC-2790?redirect=false)) said:

Previously there was a need for `@EnableWebMvcSecurity}] and {{@EnableWebSecurity` so that users could customize the `RequestDataPostProcessor` without needing to implement all the logic of `@EnableWebSecurity`.

Now that Spring Security relies on Spring 4.0+ is now possible for `@EnableWebSecurity` to conditionally expose a `CsrfRequestDataValueProcessor` as a bean.

**Comment by spring-issuemaster** [comment]
This issue relates to #2656
