### ISSUE TITLE
SEC-2712: Allow WithSecurityContextTestExecutionListener to execute after @Before

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2935]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2712](https://jira.spring.io/browse/SEC-2712?redirect=false)) said:

> Hi Rob, great enhancement. Would it be possible somehow to to invoke @WithUserDetails after @Before annotated method or have the execution order configurable? I think it'd be great to be able to create a new fresh user account in some sort of @Before method and then authenticate it with @WithUserDetails. I'm trying to avoid creating new user in @BeforeClass because each @test method can alter user's information, so I configured test to rollback transaction after each @test and create a new user before, however @WithUserDetails tries to call UserDetailsService.loadUserByUsername() before actual user was created in @Before. Any ideas? Thanks a lot!

**Comment by RodrigoGroener** [comment]
+1

**Comment by mleprince** [comment]
+1

**Comment by rwinch** [comment]
I don't think there is a hook in Spring Test to invoke logic after `@Before` but before the `@Test`.

cc @sbrannen

**Comment by sbrannen** [comment]
> I don't think there is a hook in Spring Test to invoke logic after `@Before` but before the `@Test`.

Prior to Spring Framework 5.0, that's correct.

However, I introduced support for before/after execution callbacks in Spring 5.0 M1. See [SPR-4365](https://jira.spring.io/browse/SPR-4365) for details.

**Comment by ejust** [comment]
+1

**Comment by Ordiel** [comment]
+1 ?

**Comment by sbrannen** [comment]
👍
