### ISSUE TITLE
SEC-2714: AuthenticationPrincipal Argument Resolver for messaging Support

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2937]
Migrated from [SEC-2714](https://jira.spring.io/browse/SEC-2714?redirect=false)

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12217

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12217

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12217

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12217

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12217

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12217

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12217

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12217

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12217
