### ISSUE TITLE
SEC-2792: HeaderChecks not applied to Load Balanced https originated redirects

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2938]
[mike hugo](https://jira.spring.io/secure/ViewProfile.jspa?name=mjhugo) (Migrated from [SEC-2792](https://jira.spring.io/browse/SEC-2792?redirect=false)) said:

We have configured HeaderCheckSecureChannelProcessor and HeaderCheckInsecureChannelProcessor to capture the proper HTTP headers from our Amazon AWS Elastic Load Balancer (fronting two tomcat instances running a Grails webapp using spring security).  X-Forwarded-Proto works great for most request, but those requests interacting with  j_spring_security\* endpoints like j_spring_security_check do not seem to be respecting that configuration.  

For example, if a user tries to login via ajax, we get this error in the browser (this is the redirect that the successful login initiates):

```
 Mixed Content: The page at 'https://www.servernamehere.com/' was loaded over HTTPS, but 
 requested an insecure XMLHttpRequest endpoint 'http://www.servernamehere.com/login/ajaxSuccess'.
 This request has been blocked; the content must be served over HTTPS.
```

Notice that the login was successful - it's just that the redirect coming back from the server is specified as http instead of https

More details:
http://stackoverflow.com/questions/27413217/how-to-get-springsecurity-grails-to-play-nicely-with-a-load-balancer-that-is-ter

**Comment by spring-issuemaster** [comment]
This issue relates to https://jira.spring.io/browse/SPR-13614

**Comment by spring-issuemaster** [comment]
This issue relates to https://jira.spring.io/browse/SPR-13614
