### ISSUE TITLE
SEC-2815: @EnableGlobalMethodSecurity prevents postprocessing of DataSource bean

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2950]
[Alex Pogrebnyak](https://jira.spring.io/secure/ViewProfile.jspa?name=alex.spring@reflexion.net) (Migrated from [SEC-2815](https://jira.spring.io/browse/SEC-2815?redirect=false)) said:

Adding `@EnableGlobalMethodSecurity` annotation to my extension of `WebSecurityConfigurerAdapter` prevents embedded database initialization in integration testing.

The problem is very nicely summarized here -> https://gist.github.com/dsyer/ebeb25d5afbdd9242cd5

**Comment by spring-issuemaster** [comment]
This issue supersedes #2881
