### ISSUE TITLE
SEC-2727: Spring security version check reports incorrectly.

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2952]
[Matt Fleshman](https://jira.spring.io/secure/ViewProfile.jspa?name=mfleshman) (Migrated from [SEC-2727](https://jira.spring.io/browse/SEC-2727?redirect=false)) said:

When using spring core version 3.2.10 or greater the spring security version check reports a warning message about minimum version incorrectly.

To recreate run spring core 3.2.11 with spring security 3.2.4.

The issue is in the compare statement of:

```
if (springVersion.compareTo(MIN_SPRING_VERSION) < 0) {
     logger.warn("**** You are advised to use Spring " + MIN_SPRING_VERSION +  " or later with this version. You are running: " + springVersion);
}
```

**Comment by spring-issuemaster** [comment]
This issue duplicates #2920
