### ISSUE TITLE
SEC-2728: Only write cache related headers if no other cache headers found

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2953]
# Updated Description

Spring Security should only write cache related headers (i.e. Cache-Control, Expires, Pragma) if the application has not already provided any of the headers.

# Original Description 

[Mike Noordermeer](https://jira.spring.io/secure/ViewProfile.jspa?name=miken) (Migrated from [SEC-2728](https://jira.spring.io/browse/SEC-2728?redirect=false)) said:

The documentation states about the cache-control header support:

bq. If you actually want to cache specific responses, your application can selectively invoke HttpServletResponse.setHeader(String,String) to override the header set by Spring Security. This is useful to ensure things like CSS, JavaScript, and images are properly cached.

Judging from our own experiments and the code, this is not possible. The `Pragma: no-cache` header will always be set, and is impossible to override, since there is no defined 'cache' value, and no way in the Servlet API to remove a header once set.

This is at least a documentation bug, but it would be nice if the Pragma header is only set when there are no cache-control headers set by the application (but that seems to be hard given the current architecture, since headers are set before the request is passed on in the filter chain).

# Workaround

Many users might consider "ignoring security" for the requests to work around the issue. This is not advised as many other important security features will be disabled for any request that is matched. This is important even for static resources.

Other users might disable only headers support or only cache control. This will cause security vulnerabilities for the rest of the application.

This can be worked around with using a configuration like this:

```java
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		RequestMatcher notResourcesMatcher = new NegatedRequestMatcher(new AntPathRequestMatcher("/resources/**"));
		HeaderWriter notResourcesHeaderWriter = new DelegatingRequestMatcherHeaderWriter(notResourcesMatcher , new CacheControlHeadersWriter());
		http
			.headers()
				.cacheControl().disable()
				.addHeaderWriter(notResourcesHeaderWriter);
	}
}
```

**Comment by rwinch** [comment]
This is related to [SPR-14005](https://jira.spring.io/browse/SPR-14005)

**Comment by eballetbaz** [comment]
This feature is quite incompatible with JSON responses generated with standard the Spring AbstractJackson2View. 
Indeed by default the class AbstractJackson2View is adding header "Cache-Control: no-store" (and only this one). So when using Jackson Views the tag <cache-control> is doing nothing (and so headers Pragma and Expires are not defined)

**Comment by vhadzhipopov** [comment]
Hey Happy New Year @rwinch !

I'm not sure this should be closed, here is a simple REST endpoint I have:
```java
@RequestMapping(value = "/hi", method = RequestMethod.GET)
public ResponseEntity cacheTest() {
    return ResponseEntity.ok()
                         .cacheControl(CacheControl.maxAge(1, TimeUnit.DAYS))
                         .body("Hello World!");
}
```

Using a logging aspect I get:
`....Example.cacheTest() with result = <200 OK,Hello World!,{Cache-Control=[max-age=86400]}>`
But in the browser it's still default Spring Security header:
`Cache-Control:no-cache, no-store, max-age=0, must-revalidate`

When I debugged it, it looked like at HttpEntityMethodProcessor.java:183
```java
if (!entityHeaders.isEmpty()) {
    for (Map.Entry<String, List<String>> entry : entityHeaders.entrySet()) {
        if (!outputHeaders.containsKey(entry.getKey())) {
            outputHeaders.put(entry.getKey(), entry.getValue());
        }
    }
}
```
The Cache-Control header already exists and can't be overriden.

I'm running Spring Boot 1.4.0.RELEASE and Spring Security 4.2.1.RELEASE

If you need anything else don't hesitate to ask. :)

**Comment by nealeu** [comment]
Anyone tearing their hair out at the prospect of having to migrate to JavaConfig for a legacy project (as I was), there does seem to be a way around it.

Ah... by digging around, I think I've avoided the need to do this, you can use the header writer bean with the `<header>` tag which would appear to be only static headers, but can actually take a ref to a `HeaderWriter`.

I now have:

```
    @Bean
    public HeaderWriter selectiveCacheControlHeaderWriter() {

        RequestMatcher paths = new OrRequestMatcher(
                new AntPathRequestMatcher("/resources/**"),
                new AntPathRequestMatcher("/api/**")
        );

        return new DelegatingRequestMatcherHeaderWriter(
                new NegatedRequestMatcher(paths),
                new CacheControlHeadersWriter());
    }
```
and
```
    <headers>
        <cache-control disabled="true"/>
        <header ref="selectiveCacheControlHeaderWriter"/>
    </headers>
```
