### ISSUE TITLE
SEC-2730: Provide an order higher than LOWEST_PRECEDENCE for springSecurityFilterChain that's created by WebSecurityConfiguration

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2955]
[Andy Wilkinson](https://jira.spring.io/secure/ViewProfile.jspa?name=awilkinson) (Migrated from [SEC-2730](https://jira.spring.io/browse/SEC-2730?redirect=false)) said:

The `springSecurityFilterChain` bean that's created by `WebSecurityConfiguration` is unordered. This means that it's considered to have the default order provided by `AnnotationAwareOrderComparator` which is `LOWEST_PRECEDENCE`. This makes the filter go last (or joint last if there are other `LOWEST_PRECEDENCE` filters configured) when a request is being processed. In a Spring Boot application this makes it difficult for a user to configure their own filter which should run after Spring Security's filter.

**Comment by rustyx** [comment]
`0` is not a good priority for `springSecurityFilterChain`, there are many cases when a filter must precede `springSecurityFilterChain`, for example: character encoding, CSRF, HttpSession, rate-limit, logging & exception handling.

However, something like `@Order(100000)` should be sufficient to finally fix this issue.

**Comment by rwinch** [comment]
I"m closing this as won't fix. The reason is that Order does not have any meaning on a Filter outside of Spring Boot, so it should (and is) be handled by Spring Boot.
