### ISSUE TITLE
SEC-2751: AbstractPreAuthenticatedProcessingFilter assumes principal is a string

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2977]
[Patrick Brannen](https://jira.spring.io/secure/ViewProfile.jspa?name=pbrannen) (Migrated from [SEC-2751](https://jira.spring.io/browse/SEC-2751?redirect=false)) said:

I am using pre-authentication alongside form login. I ran into a problem similar to this user:
https://jira.spring.io/browse/SEC-1983?focusedCommentId=93727&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-93727

In working around this problem, I noticed this code inside 
AbstractPreAuthenticatedProcessingFilter.requiresAuthentication():

if (currentUser.getName().equals(principal)) {
            return false;
 }

In my case, principal is an instance of UserDetails. So comparing an instance of String to an instance of UserDetails always returned false.

I had to change the above code to this:
if (currentUser.getPrincipal().equals(principal)) {
            return false;
}

**Comment by spring-issuemaster** [comment]
This issue duplicates #2302
