### ISSUE TITLE
SEC-2758: Consistency with ROLE_

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2984]
[Greg Turnquist](https://jira.spring.io/secure/ViewProfile.jspa?name=gregturn) (Migrated from [SEC-2758](https://jira.spring.io/browse/SEC-2758?redirect=false)) said:
# Updated Description

Spring Security does not treat roles consistently. For example, the Java Configuration allows you to perform something like:

```
.withUser("user").password("password").roles("USER")
```

```
http
   .authorizeRequests()
       .anyRequest().hasRole("USER")
```

Internally, these is automatically prefixed with "ROLE_". This means when using any of the following:

```
// or any other SpEL annotation
@PreAuthorize("hasRole('ROLE_USER')")
```

```
// JSR 250
@RolesAllowed("ROLE_USER")
```

```
<http use-expressions="true">
   <intercept-url pattern="/**" access="hasRole('ROLE_USER')"/>
</http>
```

we must restate the ROLE_ even though it has already been expressed as a role.

h1. How should we improve this?

Anytime we see role elsewhere, it should automatically add the prefix of "ROLE_" if it is not already there (this helps things remain passive). So that means we should be able to do the following (which is the equivalent of the above example):

```
// or any other SpEL annotation
@PreAuthorize("hasRole('USER')")
```

```
// JSR 250
@RolesAllowed("USER")
```

```
<http use-expressions="true">
   <intercept-url pattern="/**" access="hasRole('USER')"/>
</http>
```

h2. Implementation Details

h3. Expressions

To support expressions we will update the `SecurityExpressionRoot` to automatically prefix hasRole and hasAnyRole with "ROLE_" if it does not exist. For example:

```
public abstract class SecurityExpressionRoot implements SecurityExpressionOperations {
    ...
    private String defaultRolePrefix = "ROLE_";

    ...

    /**
     * <p>
     * Sets the default prefix to be added to {@link #hasAnyRole(String...)} or
     * {@link #hasRole(String)}. For example, if hasRole("ADMIN") or hasRole("ROLE_ADMIN") is passed in,
     * then the role ROLE_ADMIN will be used when the defaultRolePrefix is "ROLE_" (default).
     * </p>
     *
     * <p>
     * If null or empty, then no default role prefix is used.
     * </p>
     *
     * @param defaultRolePrefix the default prefix to add to roles. Default "ROLE_".
     */
    public void setDefaultRolePrefix(String defaultRolePrefix) {
        this.defaultRolePrefix = defaultRolePrefix;
    }

    /**
     * Prefixes role with defaultRolePrefix if defaultRolePrefix is non-null and
     * if role does not already start with defaultRolePrefix.
     *
     * @param defaultRolePrefix
     * @param role
     * @return
     */
    private static String getRoleWithDefaultPrefix(String defaultRolePrefix, String role) {
        if(role == null) {
            return role;
        }
        if(defaultRolePrefix == null || defaultRolePrefix.length() == 0) {
            return role;
        }
        if(role.startsWith(defaultRolePrefix)) {
            return role;
        }
        return defaultRolePrefix + role;
    }
}
```

h3. JSR 250

To support JSR 250 we will update how the `RolesAllowed` is parsed by updating `Jsr250MethodSecurityMetadataSource` much in the same way as we did with the expressions. This ensures that the `Jsr250SecurityConfig` is populated with an authority that is prefixed with "ROLE_" by default.

h2. Broken Passivity

If developers return an Authentication or UserDetails that contains authorities that do NOT contain "ROLE_" as the prefix, the above changes introduce a non-passive change. What might this look like and how do we fix it?

h3. Fixing Passivity

_Option A (Ensure roles start with ROLE_)_

The first option to fix things is to change our application to return authorities that are prefixed with "ROLE_". If we do that, then nothing else is needed. For example, with the in memory based solution we might do the following:

```
       ...
        <user name="user" password="password" authorities="ROLE_USER"/>
```

Obviously in a production system this would likely involve a data migration. Alternatively, you could update your UserDetailsService to prefix the roles programatically.

_Option B (Update Configuration)_

Another option is to reconfigure Spring Security. 

Create a BeanPostProcessor that looks like:

```
package org.springframework.security.sample;

import org.springframework.beans.BeansException;
import org.springframework.beans.factory.config.BeanPostProcessor;
import org.springframework.core.PriorityOrdered;
import org.springframework.security.access.annotation.Jsr250MethodSecurityMetadataSource;
import org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler;
import org.springframework.security.web.access.expression.DefaultWebSecurityExpressionHandler;
import org.springframework.stereotype.Component;

@Component
public class DefaultRolesPrefixPostProcessor implements BeanPostProcessor, PriorityOrdered {

    @Override
    public Object postProcessAfterInitialization(Object bean, String beanName)
            throws BeansException {
        if(bean instanceof Jsr250MethodSecurityMetadataSource) {
            ((Jsr250MethodSecurityMetadataSource) bean).setDefaultRolePrefix(null);
        }
        if(bean instanceof DefaultMethodSecurityExpressionHandler) {
            ((DefaultMethodSecurityExpressionHandler) bean).setDefaultRolePrefix(null);
        }
        if(bean instanceof DefaultWebSecurityExpressionHandler) {
            ((DefaultWebSecurityExpressionHandler) bean).setDefaultRolePrefix(null);
        }
        return bean;
    }

    @Override
    public Object postProcessBeforeInitialization(Object bean, String beanName)
            throws BeansException {
        return bean;
    }

    @Override
    public int getOrder() {
        return PriorityOrdered.HIGHEST_PRECEDENCE;
    }
}
```

Then include it in your configuration:

```
  <b:bean class="org.springframework.security.sample.DefaultRolesPrefixPostProcessor"/>
```

or

```
@Bean
public static DefaultRolesPrefixPostProcessor defaultRolesPrefixPostProcessor() {
    return new DefaultRolesPrefixPostProcessor();
}
```

h3. Samples Restoring Passivity

You can find samples attached to this JIRA that demonstrate fixing passivity.
- For XML refer to the differences between SEC-2785-xml.zip and SEC-2785-xml-4.0.zip
- For Java Configuration refer to the differences between SEC-2785-jc.zip and SEC-2785-jc-4.0.zip

h1. Original Description

Just an observation I have when working with Spring Security. You can take it or leave it.

Different APIs use roles differently. What I mean is that certain parts require ROLE_USER, while other parts only require USER. Frankly, I am never sure which one to use and rely upon examples to deduce what. Look at the following:

```
@Override
  public void configure(AuthenticationManagerBuilder auth) throws Exception {

    auth.inMemoryAuthentication()
      .withUser("greg").password("turnquist").roles("USER").and()
      .withUser("ollie").password("gierke").roles("USER", "ADMIN");
  }
```

And then look at this:

```
@PreAuthorize("hasRole('ROLE_USER')")
public interface ItemRepository extends CrudRepository<Item, Long>  {

  @PreAuthorize("hasRole('ROLE_ADMIN')")
  @Override
  Item save(Item s);

  @PreAuthorize("hasRole('ROLE_ADMIN')")
  @Override
  void delete(Long aLong);
}
```

I think we need to somehow clean this up. Probably a major, breaking affect on things, so I can't imagine such an improvement happening before a major release.

If this was scala, I would retool the APIs to either accept raw strings, which would be "ROLE_USER", or accept a case class like Role("USER"), both meaning the same thing in the end. And then down the road, perhaps deprecating the plain strings.

But walking back to good ole Java, I'm not sure what the best design choice would be. This idea comes to mind:

```
public class Role {
    private String roleName;
    public Role(String roleName) { this.roleName = roleName; }
    ...getters/setters perhaps using Lombok...
}

public class RoleUtils {
    public static Role Role(String roleName) { return new Role(roleName); }
}
```

Then with some static imports, 

```
.withUser("greg").password("turnquist").roles(Role("USER"), Role("ADMIN"));
```

A nice little static import would make this work. Just one idea. I imagine that @PreAuthorize requires sticking to strings. If people want to create their own prefixes in lieu of ROLE_, then perhaps they can extend some Spring Security piece of the API and inject it into their configuration.

**Comment by fairoz-sharif** [comment]
Thanks for all the comments, 

I have an concern related to this, as i have no prefix(like ROLE_) for my roles in database. so Spring-Security is treating it as authority not roles. So for now i am using hasAuthority("USER") instead of hasRole("USER")

but at the same time , if i call the function (of Servlet API) request.isUserInRole("USER"), this returns false. i am just worried that this might become some dead-end for me to implement some new feature where i  may not be using Spring's API.

Please respond.
