### ISSUE TITLE
SEC-2850: AbstractRememberMeServices.setAlwaysRemember with java config

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2985]
[Leon Radley](https://jira.spring.io/secure/ViewProfile.jspa?name=leon) (Migrated from [SEC-2850](https://jira.spring.io/browse/SEC-2850?redirect=false)) said:

being able to set always remember via HttpSecurity http.rememberMe().alwaysRemember(true)

or via a spring boot application.properties
security.remember-me.always=true

My main problem is getting spring social working with the remember me functionality. by always having it enabled it works.

**Comment by eleftherias** [comment]
Fixed via b82df4e and 26ad1cb.
