### ISSUE TITLE
SEC-2759: No pdf documentation

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#2986]
[watanabe](https://jira.spring.io/secure/ViewProfile.jspa?name=nabedge) (Migrated from [SEC-2759](https://jira.spring.io/browse/SEC-2759?redirect=false)) said:

http://docs.spring.io/spring-security/site/docs/
There are no PDF version of document in any version.
Please generate PDF document to read them on my kindle/ipad.

**Comment by spring-issuemaster** [comment]
This issue duplicates #2815
