### ISSUE TITLE
SEC-2760: Typo in Spring Security Reference Documentation

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#2987]
[James McShane](https://jira.spring.io/secure/ViewProfile.jspa?name=jamesmcshane) (Migrated from [SEC-2760](https://jira.spring.io/browse/SEC-2760?redirect=false)) said:

There is a typo in the 1.4 Request Matching and HttpFirewall section.  It reads:

If for some reason, you need a more powerful matching strategy, you can use regular expressions. The strategy implementation is then`RegexRequestMatcher`. See the Javadoc for this class for more information.

I believe the "n" before `RegexRequestMatcher` should be a space so that the class name can be highlighted correctly.

**Comment by eleftherias** [comment]
This issue was fixed in 4.1.0.
