### ISSUE TITLE
SEC-2881: Provide an exception handling mechanism for ChannelSecurityInterceptor

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3000]
[zyro](https://jira.spring.io/secure/ViewProfile.jspa?name=zyro) (Migrated from [SEC-2881](https://jira.spring.io/browse/SEC-2881?redirect=false)) said:

currently it looks like an `AccessDeniedException` thrown from a `ChannelSecurityInterceptor` just bubbles up to the `StompSubProtocolHandler` (https://github.com/spring-projects/spring-framework/blob/master/spring-websocket/src/main/java/org/springframework/web/socket/messaging/StompSubProtocolHandler.java#L307) which uses `error.getMessage()` as payload for the resulting message with `SimpMessageType.ERROR`.

so the client sees something like `...  org.springframework.security.access.AccessDeniedException...` in the error message payload.

it would be nice to have some mechanism to hook in there handling the exception gracefully (or at least provide a custom error message payload).

note that i am not 100% sure this has to be implemented within spring-security. as far as i can tell, the described behavior originates from spring-messaging and is not security-specific but would also apply to other exceptions thrown by downstream handlers/interceptors/etc...
so maybe an implementation in spring-messaging would be a good fit, too. if then security exceptions need some special attention, that could be handled by exception type?

thanks, zyro

**Comment by spring-issuemaster** [comment]
This issue relates to https://jira.spring.io/browse/SPR-12732

**Comment by spring-issuemaster** [comment]
This issue relates to https://jira.spring.io/browse/SPR-12732
