### ISSUE TITLE
SEC-2783: XML Configuration Defaults Should Match JavaConfig

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3010]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2783](https://jira.spring.io/browse/SEC-2783?redirect=false)) said:

```
* j_username -> username
* j_password -> password
* j_spring_security_check -> login
* j_spring_cas_security_check -> login/cas
* j_spring_cas_security_proxyreceptor -> login/cas/proxyreceptor
* j_spring_openid_security_login -> login/openid
* j_spring_security_switch_user -> login/impersonate
* j_spring_security_exit_user -> logout/impersonate
* login_error -> error
* use-expressions=true by default
```

**Comment by itm94lj** [comment]
I'm confusing why j_username changed to username.
 In Java™ Servlet Specification version 4.0 13.6.3 section 
"The login form must contain fields for entering a username and a
password. These fields must be named j_username and j_password, respectively." 
Does this means we decide  not to comply with this specification?
My English is poor so ignore any syntax mistake.

**Comment by rwinch** [comment]
This is to avoid [Information Leak (information disclosure)](https://www.owasp.org/index.php/Information_Leak_(information_disclosure))
