### ISSUE TITLE
SEC-2793: Spring Boot Requires "extends WebSecurityConfigurerAdapter"

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3016]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2793](https://jira.spring.io/browse/SEC-2793?redirect=false)) said:

Spring Boot causes ordering issues if using configureGlobal and the class configuring it does not extend WebSecurityConfigurerAdapter. This should be fixed to leverage the `@Enable*` annotations to eagerly initialize these classes.

**Comment by spring-issuemaster** [comment]
This issue duplicates #3042
