### ISSUE TITLE
SEC-2794: AbstractPreAuthenticatedProcessingFilter requires authentication check failure

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3017]
[Kathryn Spinks](https://jira.spring.io/secure/ViewProfile.jspa?name=kathryn.spinks) (Migrated from [SEC-2794](https://jira.spring.io/browse/SEC-2794?redirect=false)) said:

In the AbstractPreAuthenticatedProcessingFilter.requiresAuthentication(HttpServletRequest request) method which is private, there is the following code:

```
    Object principal = getPreAuthenticatedPrincipal(request);

    if (currentUser.getName().equals(principal)) {
        return false;
    }
```

This assumes that the overriden method of getPreAuthenticatedPrincipal(request) will always return a String, when in fact it could be any object. This needs to change to either:
        String principal = request.getUserPrincipal().getName();

```
    if (currentUser.getName().equals(principal)) {
        return false;
    }
```

or provide an abstract method (or at least a protected/public method) in order to do the comparison - see attachment. My getPreAuthenticatedPrincipal(request) returns a FederationPrincipal, and not a String. The only way to deal with it at the moment is to completely copy the AbstractPreAuthenticatedProcessingFilter, and change the tiny bit of code above.

**Comment by spring-issuemaster** [comment]
This issue duplicates #2302
