### ISSUE TITLE
SEC-2808: Possible error on the 'Hello Spring MVC Security Java Config' guide

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3030]
[Manuel Jordan](https://jira.spring.io/secure/ViewProfile.jspa?name=dr_pompeii) (Migrated from [SEC-2808](https://jira.spring.io/browse/SEC-2808?redirect=false)) said:

After to read [StackOverflow answer | http://stackoverflow.com/a/21196152]

For the [Logging out](http://docs.spring.io/spring-security/site/docs/3.2.x/guides/hellomvc.html#logging-out) section it says:

> Update our configuration to use the @EnableWebMvcSecurity annotation which will do the same as @EnableWebMvcSecurity and provide integration with Spring MVC.

Seems error since the @EnableWebMvcSecurity term appears twice, I think the second apparition should be @EnableWebSecurity

**Comment by spring-issuemaster** [comment]
This issue duplicates #3095
