### ISSUE TITLE
SEC-2810: Perhaps rename a link name in the Spring Security home page.

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3032]
[Manuel Jordan](https://jira.spring.io/secure/ViewProfile.jspa?name=dr_pompeii) (Migrated from [SEC-2810](https://jira.spring.io/browse/SEC-2810?redirect=false)) said:

Just a quick observation
In the [Spring Security home project](http://projects.spring.io/spring-security/) below in the right part has the section named 'Additional Resources', where it has the link _Getting Started_ which targets to the page with the title _Spring Security Guides_

How you can see they (bold names) are not related, therefore from the home page is not easy find and arrive to the guides. Is not intuitive.

**Comment by eleftherias** [comment]
Closing because the Spring Security home page has been updated and the mentioned section is no longer there.
