### ISSUE TITLE
SEC-2903: Expire a session via the SessionRegistry interface

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3038]
[Kazuki Shimizu](https://jira.spring.io/secure/ViewProfile.jspa?name=kazuki43zoo) (Migrated from [SEC-2903](https://jira.spring.io/browse/SEC-2903?redirect=false)) said:

I want to expire a session via the `SessionRegistry` interface as same as `SessionRegistry#refreshLastRequest`.

Because i want to implement a class that manage a session information into the database.

**Comment by eleftherias** [comment]
> You can expire a session by implementing SessionRegistry and extending the SessionInformation to override the expireNow method.

See gh-181 for more information.
