### ISSUE TITLE
SEC-2832: CSRF Request attributes not updated on authentication

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3056]
[Benjamin Burgess](https://jira.spring.io/secure/ViewProfile.jspa?name=stillglade) (Migrated from [SEC-2832](https://jira.spring.io/browse/SEC-2832?redirect=false)) said:

The CsrfFilter sets request attributes on each request, exposing the current CsrfToken for later use.  However, if authentication happens during this request, the SessionManagementFilter will cause the CsrfAuthenticationStrategy to fire which will generate a new token.  However, the request attributes are not updated.  As a result, if there is a form being rendered in the response using the CsrfRequestDataValueProcessor, it will use the old CsrfToken instead of the newly generated one.  As a result, when the form is submitted, the request will fail due to CSRF protection.

**Comment by spring-issuemaster** [comment]
This issue relates to #2624
