### ISSUE TITLE
SEC-2839: SecurityNamespaceHandler - related to SEC-1455

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3065]
[Pelit Mamani](https://jira.spring.io/secure/ViewProfile.jspa?name=pelmam) (Migrated from [SEC-2839](https://jira.spring.io/browse/SEC-2839?redirect=false)) said:

After reloading parsers, one needs to call 'get' again.
Please see:
class: org.springframework.security.config.SecurityNamespaceHandler
Method: public BeanDefinition parse(Element element, ParserContext pc) 
Contains:

```
        BeanDefinitionParser parser = parsers.get(name);
        if (parser == null) {
            // SEC-1455. Load parsers when required, not just on init().
            loadParsers();
        }
        if (parser == null) {
        .... /// report error message
```

What's missing is a repeated 'get' after parser were reloaded:

```
        BeanDefinitionParser parser = parsers.get(name);
        if (parser == null) {
            // SEC-1455. Load parsers when required, not just on init().
            loadParsers();
            BeanDefinitionParser parser = parsers.get(name); // HERE
        }
        if (parser == null) {
        .... /// report error message
```

Thanks

**Comment by koosg** [comment]
... and this issue isn't fixed. :(
