### ISSUE TITLE
SEC-2853: Rename WebSocket XML Namespace elements

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3075]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2853](https://jira.spring.io/browse/SEC-2853?redirect=false)) said:

We should rename `<security:messages>` to `<security:websocket-message-broker>` because while the underlying interceptors will work with messages the XML namespace relies on specifics of Spring's websocket namespace. Similarly we should rename `<security:message-interceptor>` to `<security:interceptor-message>` to align with Spring Security's `<interceptor-method>` and `<interceptor-url>`.

**Comment by andremrezende** [comment]
I am using spring version 4.1.0.RELEASE, my security.xml is:
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:security="http://www.springframework.org/schema/security"
       xsi:schemaLocation="
           http://www.springframework.org/schema/beans
           http://www.springframework.org/schema/beans/spring-beans.xsd
           http://www.springframework.org/schema/security
           http://www.springframework.org/schema/security/spring-security.xsd"> 
    <import resource="spring-database.xml" /> 

	<security:http pattern="/resources/**" security="none" />
	<security:http pattern="images/**" security="none" />
	<security:http pattern="/app/error/**" security="none" />
	
	<security:websocket-message-broker>
		<security:intercept-message type="CONNECT" access="permitAll"/>
		<security:intercept-message type="UNSUBSCRIBE" access="permitAll" />
    	<security:intercept-message type="DISCONNECT" access="permitAll" />
		<security:intercept-message pattern="/**" access="permitAll" />
	</security:websocket-message-broker>

</beans>
And the error continues: 
Offending resource: ServletContext resource [/WEB-INF/spring/root-context.xml]; nested exception is org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Security namespace does not support decoration of element [websocket-message-broker]

How Could i fix it?
