### ISSUE TITLE
SEC-2864: Default PathMatcher for WebSocket Destination Matching

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3086]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2864](https://jira.spring.io/browse/SEC-2864?redirect=false)) said:

Spring Security should support default to Springs WebSocket's PathMatcher

http://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html#websocket-stomp-destination-separator

**Comment by spring-issuemaster** [comment]
This issue relates to https://jira.spring.io/browse/SPR-12845

**Comment by spring-issuemaster** [comment]
This issue relates to https://jira.spring.io/browse/SPR-12845
