### ISSUE TITLE
SEC-2872: CsrfAuthenticationStrategy Should Delay Saving CsrfToken

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3093]
Migrated from [SEC-2872](https://jira.spring.io/browse/SEC-2872?redirect=false)

**Comment by spring-issuemaster** [comment]
This issue relates to #2624

**Comment by elhussein** [comment]
@rwinch Can you elaborate more why this behavior has been removed?
As we have a case that we need the token to be created on login success, but found that you removed the token generation immediately, and made it delayed to next request.
