### ISSUE TITLE
SEC-2873: Remember Me XML Configuration Defaults Should Match Java Config 

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3094]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2873](https://jira.spring.io/browse/SEC-2873?redirect=false)) said:
- _spring_security_remember_me -> remember-me
- SPRING_SECURITY_REMEMBER_ME_COOKIE -> remember-me

**Comment by spring-issuemaster** [comment]
This issue relates to #3010
