### ISSUE TITLE
SEC-2882: DefaultLoginPageGeneratingFilter grabs /**/login

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3101]
[Christopher Smith](https://jira.spring.io/secure/ViewProfile.jspa?name=w_c_smith) (Migrated from [SEC-2882](https://jira.spring.io/browse/SEC-2882?redirect=false)) said:

I have the following Groovy security configuration in a Spring Boot web app:

```
@Configuration
@EnableWebSecurity
class SecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.
            authorizeRequests().
                antMatchers("/scratch/secured").hasRole("USER").
                antMatchers("/**").permitAll().
                anyRequest().authenticated().
            and().
            formLogin();
    }
}
```

This does get me the built-in login form at `/login`, but it also hijacks `/foo/something/login`. `DefaultLoginPageGeneratingFilter#matches` appears to treat the `url` as a suffix instead of as an absolute path. Even though the context path should be `/foo/something/login`, the conditional at 262 evaluates to `true`, and the `endsWith` comparison is used. I can't get Eclipse to dump the contents of `request.getContextPath()` right there during debugging.

**Comment by spring-issuemaster** [comment]
This issue relates to #2404
