### ISSUE TITLE
SEC-2898: Use ServletUriComponentsBuilder.fromRequest for URL creation

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3115]
Migrated from [SEC-2898](https://jira.spring.io/browse/SEC-2898?redirect=false)

**Comment by spring-issuemaster** [comment]
This issue relates to #2938
This issue relates to https://jira.spring.io/browse/SPR-13614
This issue relates to https://jira.spring.io/browse/SPR-10110

**Comment by spring-issuemaster** [comment]
This issue relates to #2938
This issue relates to https://jira.spring.io/browse/SPR-13614
This issue relates to https://jira.spring.io/browse/SPR-10110

**Comment by spring-issuemaster** [comment]
This issue relates to #2938
This issue relates to https://jira.spring.io/browse/SPR-13614
This issue relates to https://jira.spring.io/browse/SPR-10110

**Comment by spring-issuemaster** [comment]
This issue relates to #2938
This issue relates to https://jira.spring.io/browse/SPR-13614
This issue relates to https://jira.spring.io/browse/SPR-10110

**Comment by rwinch** [comment]
We don't want to get into directly coding against support for proxies. There are a number of problems with this:

* The code for supporting proxies is spread throughout the entire code base
* Malicious users could inject these headers to modify the request. This is not a problem if there is a proxy that rejects any X-Forwarded-* headers being set by untrusted clients, but if users are not aware of this it can lead to security vulnerabilities. We need a flag to enable / disable looking at the headers.
* There are multiple standards (i.e. [PROXY protocol](http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt)) for supporting proxies and we would need the code to transparently support each mechanism (in lots of places throughout the code base).

Instead I recommend using your application server's proxy configuration setup. For example, Tomcat has a [RemoteIpValve](https://tomcat.apache.org/tomcat-8.0-doc/api/org/apache/catalina/valves/RemoteIpValve.html) and Jetty has [ForwardedRequestCustomizer](https://www.eclipse.org/jetty/documentation/9.3.0.v20150612/configuring-connectors.html#d0e4404).

If  you want a container independent way to configure X-Forwarded-* support, you can look at Spring Framework 4.3's [ForwardedHeaderFilter](https://github.com/spring-projects/spring-framework/blob/v4.3.0.RC2/spring-web/src/main/java/org/springframework/web/filter/ForwardedHeaderFilter.java). Also see [SPR-13614](https://jira.spring.io/browse/SPR-13614)
