### ISSUE TITLE
SEC-2911: ActiveDirectoryLdapAuthenticationProvider - searchRoot should be configurable

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3126]
[John Webber](https://jira.spring.io/secure/ViewProfile.jspa?name=jlweb58) (Migrated from [SEC-2911](https://jira.spring.io/browse/SEC-2911?redirect=false)) said:

In our Active Directory environment we have a single search domain (say mycompany.com), but users have different domains based on being in sister companies (for example users like bob.smith@mycompany.com and charles.smith@othercompany.com). The searchForUser method (line 272 in 3.2.6.RELEASE) creates the searchRoot dynamically from the domain. Since in our case the user domain can be different than the search domain, the lookup fails.
I worked around the problem by copying the code and passing in the search root string with the configuration. Could this be a sensible option for other users?

**Comment by spring-issuemaster** [comment]
This issue duplicates #3204
