### ISSUE TITLE
SEC-2930: Review hasRole/hasAuthority documentation in SecurityExpressionOperations

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3140]
[Alex Panchenko](https://jira.spring.io/secure/ViewProfile.jspa?name=apanchenko) (Migrated from [SEC-2930](https://jira.spring.io/browse/SEC-2930?redirect=false)) said:
1. After the changes from SEC-2758 the hasRole/hasAuthority methods are not 100% synonyms.
2. hasAuthority(String) is described as a synonym for itself

**Comment by spring-issuemaster** [comment]
This issue relates to #2984
