### ISSUE TITLE
SEC-3004: Allow access to WebInvocationPrivilegeEvaluator when using multiple <http>

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3142]
[Mattias Jiderhamn](https://jira.spring.io/secure/ViewProfile.jspa?name=mate) (Migrated from [SEC-3004](https://jira.spring.io/browse/SEC-3004?redirect=false)) said:

When using a Spring Security configuration with a single `<http>` entry, you can easily get hold of the the `WebInvocationPrivilegeEvaluator` by auto wiring.

However that is not so easy when using multiple `<http>`, because it is neither possible to supply a `WebInvocationPrivilegeEvaluator` nor to provide a name for the autowiring capable `DefaultWebInvocationPrivilegeEvaluator` s being created by [HttpConfigurationBuilder.createFilterSecurityInterceptor()](https://github.com/spring-projects/spring-security/blob/master/config/src/main/java/org/springframework/security/config/http/HttpConfigurationBuilder.java#L726), leading to the infamous `expected single matching bean but found N`.

**Comment by marcusdacoregio** [comment]
Fixed via https://github.com/spring-projects/spring-security/pull/10575
