### ISSUE TITLE
SEC-2941: Default RequestPostProcessor overrides additional DefaultRequestPostProcessor

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3149]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-2941](https://jira.spring.io/browse/SEC-2941?redirect=false)) said:

Spring Security's Default RequestPostProcessor implementations override additional RequestPostProcessor implementations.

For example the following fails:

``` java
mvc = MockMvcBuilders.webAppContextSetup(context)
        .apply(springSecurity())
        .defaultRequest(get("/").with(user("default")))
        .build();

mvc
    .perform(get("/admin/abc").with(user("user1").roles("ADMIN","USER")))
    .andExpect(status().isNotFound())
    .andExpect(authenticated().withUsername("user1"));

mvc
    .perform(get("/admin/abc"))
    .andExpect(status().isForbidden())
    .andExpect(authenticated().withUsername("default"));
```

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12945
This issue relates to #3061

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-12945
This issue relates to #3061
