### ISSUE TITLE
SEC-3008: SimpleUrlAuthenticationFailureHandler does not save AuthenticationException in some cases 

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3150]
[Abhijit Sarkar](https://jira.spring.io/secure/ViewProfile.jspa?name=asarkar) (Migrated from [SEC-3008](https://jira.spring.io/browse/SEC-3008?redirect=false)) said:

```
protected final void saveException(HttpServletRequest request,
            AuthenticationException exception) {
        if (forwardToDestination) {
            request.setAttribute(WebAttributes.AUTHENTICATION_EXCEPTION, exception);
        }
// more code
}
```

We have REST services that do not have the concept of a forwarding page but we must catch all auth errors and turn them into something more digestible for the user. The block of code above unnecessarily needed us to subclass [SimpleUrlAuthenticationFailureHandler](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/authentication/SimpleUrlAuthenticationFailureHandler.java). It is short sightedness to check for the existence of a "page" before setting the exception. It could be set in the request anyway.

**Comment by marcusdacoregio** [comment]
You can handle `AuthenticationException` in your REST API by defining a `@RestControllerAdvice` that would do the translation of the exception to the proper message to the user, like so:
```java
@RestControllerAdvice
public class RestApiControllerAdvice {

    @ExceptionHandler(AuthenticationException.class)
    public ResponseEntity<YourErrorResponse> onAuthenticationException(AuthenticationException ex) {
        ...
        YourErrorResponse response = buildYourErrorResponseBasedOnException();
        return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(response);
    }

}
```
You can refer to the Spring Security reference documentation to know more about [Handling Security Exceptions](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#servlet-exceptiontranslationfilter).

I'm closing this but if there is something else to discuss we may reopen it.
