### ISSUE TITLE
SEC-2949: Custom Login not working in Spring 4.0

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3157]
[Rick UPADHYAY](https://jira.spring.io/secure/ViewProfile.jspa?name=rickyinnz) (Migrated from [SEC-2949](https://jira.spring.io/browse/SEC-2949?redirect=false)) said:

i created a simple spring mvc project and added a custom login page. The custom login works fine with 3.2.7 but the same custom login does not work when i upgrade to 4.0.0.Release.

**Comment by spring-issuemaster** [comment]
This issue duplicates #3132
