### ISSUE TITLE
SEC-2951: Document Logouthandler and LogoutSuccesshandler

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3159]
[Gunnar Hillert](https://jira.spring.io/secure/ViewProfile.jspa?name=hillert) (Migrated from [SEC-2951](https://jira.spring.io/browse/SEC-2951?redirect=false)) said:

As a user I would like to see more documentation regarding the Logouthandler and LogoutSuccesshandler. This issue is a follow up for SEC-2944.

**Comment by spring-issuemaster** [comment]
This issue relates to #3153
