### ISSUE TITLE
SEC-2952: Document Spring Security leveraging WebMvcConfigurerAdapter

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3160]
Migrated from [SEC-2952](https://jira.spring.io/browse/SEC-2952?redirect=false)

**Comment by alxkalin** [comment]
Thanks to @rwinch for the solution https://github.com/spring-projects/spring-security/issues/3151 

But maybe it would worth to note that there are no mentions of DelegatingWebMvcConfiguration in https://docs.spring.io/spring-security/site/docs/current/reference/html/mvc.html

As well as in google result if searching by DelegatingWebMvcConfiguration + AuthenticationPrincipal (except the github issue above)
