### ISSUE TITLE
SEC-3020: HttpServletRequest.isUserInRole("ROLE_<anything>") returns false with defaults

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3166]
[Anthony Gerrard](https://jira.spring.io/secure/ViewProfile.jspa?name=anthonygerrard) (Migrated from [SEC-3020](https://jira.spring.io/browse/SEC-3020?redirect=false)) said:

I'm just trying to upgrade from Spring Security 3.1 to 4.0.1 and have discovered a breaking change in the behaviour of request.isUserInRole().

In Spring 3.1 the following was returning true and now returns false:

request.isUserInRole("ROLE_REMEMBER_ME")

In Spring 4.0.1 I had to change it to the following:

request.isUserInRole("REMEMBER_ME")

**Comment by spring-issuemaster** [comment]
This issue relates to #3137
