### ISSUE TITLE
SEC-2958: README.adoc update to Spring 4

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3168]
[Sebastian Hähnel](https://jira.spring.io/secure/ViewProfile.jspa?name=shaehnel) (Migrated from [SEC-2958](https://jira.spring.io/browse/SEC-2958?redirect=false)) said:

README.adoc mentions "Spring Security 3.1 requires Spring 3.0.3 as a minimum and also requires Java 5."
This should reflect the current versions.

**Comment by eleftherias** [comment]
The README has been updated to reflect the current version.
