### ISSUE TITLE
SEC-2960: Bad Spring Security XSD Version Error Message

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3170]
[Brandon Mintern](https://jira.spring.io/secure/ViewProfile.jspa?name=mintern) (Migrated from [SEC-2960](https://jira.spring.io/browse/SEC-2960?redirect=false)) said:

When applicationContext.xml includes an old Spring Security XSD, the error message is misleading, indicating that version 3.2 needs to be used (I was using 3.2), when 4.0+ actually needs to be used.

The Reference URL indicates the erroneous line.

Note that this has been a problem in the past:

https://jira.spring.io/browse/SEC-2145

Perhaps it's worth considering a dynamically-created error message?

**Comment by spring-issuemaster** [comment]
This issue duplicates #3156
