### ISSUE TITLE
SEC-2969: Documentations spelling issue

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3178]
[Chen Li](https://jira.spring.io/secure/ViewProfile.jspa?name=richardwy) (Migrated from [SEC-2969](https://jira.spring.io/browse/SEC-2969?redirect=false)) said:

Affects versions: from 3.2.0 to 4.0.1

expressio should be expression :)

"This object also directly exposed the HttpServletRequest object under the name request so you can invoke the request directly in an expressio If expressions are being used ..."

**Comment by eleftherias** [comment]
This is fixed since 4.1.0.
