### ISSUE TITLE
SEC-2970: InMemoryTokenRepositoryImpl has dependency on spring-tx

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3179]
[Selene Feigl](https://jira.spring.io/secure/ViewProfile.jspa?name=sfmpd) (Migrated from [SEC-2970](https://jira.spring.io/browse/SEC-2970?redirect=false)) said:

The org.springframework.security.web.authentication.rememberme.InMemoryTokenRepositoryImpl class has an dependency on DataIntegrityViolationException, which is in project "spring-tx".

I want to use PersistentTokenBasedRememberMeServices without using any JDBC stuff. But the "tokenRepository" field is preset with InMemoryTokenRepositoryImpl and thus has a dependency on spring-tx.

Is it possible to decouple InMemoryTokenRepositoryImpl from spring-tx?

Caused by: java.lang.NoClassDefFoundError: org/springframework/dao/DataIntegrityViolationException
    at org.springframework.security.web.authentication.rememberme.PersistentTokenBasedRememberMeServices.<init>(PersistentTokenBasedRememberMeServices.java:46) ~[spring-security-web-4.0.1.RELEASE.jar:4.0.1.RELEASE]

**Comment by stenbek** [comment]
Is there any progress on this issue?

**Comment by rwinch** [comment]
I don't see this as a big enough gain to remove the dependency as a consistent exception from the different implementations is desirable. If users really want to remove the dependency it is a simple thing to implement themselves.
