### ISSUE TITLE
SEC-2977: AnonymousAuthenticationFilter.createAuthentication() creates passes incorrect value to the constructor of AnonymousAuthenticationToken

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3187]
[Jacob Lu](https://jira.spring.io/secure/ViewProfile.jspa?name=bigfoot) (Migrated from [SEC-2977](https://jira.spring.io/browse/SEC-2977?redirect=false)) said:

The following code passes userAttribute.getPassword() to the principal field of AnonymousAuthenticationToken constructor, which doesn't seem logical.

AnonymousAuthenticationToken auth = new AnonymousAuthenticationToken(key, userAttribute.getPassword(),  userAttribute.getAuthorities());

**Comment by eleftherias** [comment]
This was fixed as part of gh-2009 in 7344212.
