### ISSUE TITLE
SEC-2979: missing part of reference on website

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3188]
[Soeun Park](https://jira.spring.io/secure/ViewProfile.jspa?name=soeun%20park) (Migrated from [SEC-2979](https://jira.spring.io/browse/SEC-2979?redirect=false)) said:

Contents from line #692  to #797 of index.adoc are missing on website(http://docs.spring.io/spring-security/site/docs/4.0.1.RELEASE/reference/htmlsingle).

**Comment by eleftherias** [comment]
The contents on the lines mentioned contained the section "Handling Logouts".
This section now correctly appears in the reference documentation https://docs.spring.io/spring-security/site/docs/current/reference/html5/#jc-logout
