### ISSUE TITLE
SEC-2990: Fix SecurityNamespaceHandler exception message

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3199]
[Blair Zajac](https://jira.spring.io/secure/ViewProfile.jspa?name=blairzajac) (Migrated from [SEC-2990](https://jira.spring.io/browse/SEC-2990?redirect=false)) said:

Migrating an application from Spring Security 3.2.x to 4.0.x raised this exception:

```
  org.springframework.beans.factory.parsing.BeanDefinitionParsingException:
  Configuration problem: You cannot use a spring-security-2.0.xsd or
  spring-security-3.0.xsd or spring-security-3.1.xsd schema with
  Spring Security 3.2. Please update your schema declarations to the
  3.2 schema.  Offending resource: ServletContext resource
  [/WEB-INF/applicationContext-security.xml]
```

It appears that the exception message in config/src/main/java/org/springframework/security/config/SecurityNamespaceHandler.java needs to be updated.

**Comment by spring-issuemaster** [comment]
This issue duplicates #3156
