### ISSUE TITLE
SEC-3035: SecurityContextHolderAwareRequestWrapper#isUserInRole adds role prefix to already prefixed role

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3201]
[Aleksandr Mashchenko](https://jira.spring.io/secure/ViewProfile.jspa?name=aleksandr) (Migrated from [SEC-3035](https://jira.spring.io/browse/SEC-3035?redirect=false)) said:

SecurityContextHolderAwareRequestWrapper#isUserInRole adds role prefix even if passed role already has one.

Currently calling `request.isUserInRole("ROLE_ADMIN")` fails because `ROLE_ADMIN` becomes `ROLE_ROLE_ADMIN` in `SecurityContextHolderAwareRequestWrapper#isGranted` method.

**Comment by spring-issuemaster** [comment]
This issue duplicates #3166
