### ISSUE TITLE
SEC-2996: Support configuring SecurityExpressionHandler<Message<Object>>

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3206]
[pascal gehl](https://jira.spring.io/secure/ViewProfile.jspa?name=paskos) (Migrated from [SEC-2996](https://jira.spring.io/browse/SEC-2996?redirect=false)) said:
# Description

We should allow easily configuring  `SecurityExpressionHandler<Message<Object>>` via Java Configuration and XML configuration.

h1. Original Description

I work on a project starting to use websockets and we plan to secure it with spring-security-messaging.
We have custom security expressions (_all examples are bogus_) ie. `"hasPaidEnoughMoneyToFIFA()"`
My websocket security config class `extends AbstractSecurityWebSocketMessageBrokerConfigurer` but I can't find a method either in `AbstractSecurityWebSocketMessageBrokerConfigurer` or in `MessageSecurityMetadataSourceRegistry` where I can inject my instance of `SecurityExpressionHandler`.

**Comment by vmax1145** [comment]
Is there any way to pass destination matcher path valiables to expression?
Eg something like this?
.simpSubscribeDestMatchers("/topic/channel-{channelId}").access("hasAccessToChannel(#channelId)")
