### ISSUE TITLE
SEC-3005: prePostEnabled set to true on @EnableGlobalMethodSecurity ignores AspectJ  mode

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3216]
[Craig Chapman](https://jira.spring.io/secure/ViewProfile.jspa?name=craigchapman1975) (Migrated from [SEC-3005](https://jira.spring.io/browse/SEC-3005?redirect=false)) said:

Using Java Config, AspectJ mode is ignored when "prePostEnabled" is set to true on @EnableGlobalMethodSecurity. If only "secured" is set to true, AspectJ mode is honoured. This has been reported previously - see SEC-2595 and SEC-2698. This causes proxy classes to be created and internal method calls annotated with @PreAuthorize are bypassed.

The sample project - [aspectj-jc](https://github.com/spring-projects/spring-security/blob/master/samples/aspectj-jc/src/main/java/sample/aspectj/AspectjSecurityConfig.java) - only sets secured to true so the AspectjInterceptorTests.notProxy() test passes.

The issue is not present with xml config.

My workaround is to remove the @EnableGlobalMethodSecurity annotation and create an xml config with this entry:

``` java
<security:global-method-security
        secured-annotations="enabled" mode="aspectj" pre-post-annotations="enabled">
        <security:expression-handler ref="expressionHandler" />
</security:global-method-security>
```

and include it in my Java config:

``` java
@ImportResource(value = "classpath:/applicationContext-sec.xml")
```

**Comment by spring-issuemaster** [comment]
This issue relates to #2921
This issue relates to #2810
