### ISSUE TITLE
SEC-3010: Misleading error message when using wrong schema

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3220]
[Tilman Hausherr](https://jira.spring.io/secure/ViewProfile.jspa?name=tilman) (Migrated from [SEC-3010](https://jira.spring.io/browse/SEC-3010?redirect=false)) said:

I am using spring and spring security and got this error message:

> org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: You cannot use a spring-security-2.0.xsd or spring-security-3.0.xsd or spring-security-3.1.xsd schema with Spring Security 3.2. Please update your schema declarations to the 3.2 schema

I was using 3.2 schemas. The message got away when changing it to 4.0, same for spring framework.

Suggestion: change the message to something dynamic that doesn't need to be adjusted, e.g. "you used XXXX.xsd but the current software version is YYY. Please update your schema declarations to the current schema."

**Comment by spring-issuemaster** [comment]
This issue duplicates #3199
