### ISSUE TITLE
SEC-3017: AntPathMatcher isn't fully conform Ant Style

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3226]
Migrated from [SEC-3017](https://jira.spring.io/browse/SEC-3017?redirect=false)

**Comment by spring-issuemaster** [comment]
This issue relates to https://jira.spring.io/browse/SPR-13116

**Comment by spring-issuemaster** [comment]
This issue relates to https://jira.spring.io/browse/SPR-13116

**Comment by spring-issuemaster** [comment]
This issue relates to https://jira.spring.io/browse/SPR-13116

**Comment by spring-issuemaster** [comment]
This issue relates to https://jira.spring.io/browse/SPR-13116

**Comment by spring-issuemaster** [comment]
This issue relates to https://jira.spring.io/browse/SPR-13116
