### ISSUE TITLE
SEC-3055: request.isUserInRole add an extra "ROLE_"

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3228]
[Alireza Fattahi](https://jira.spring.io/secure/ViewProfile.jspa?name=afattahi) (Migrated from [SEC-3055](https://jira.spring.io/browse/SEC-3055?redirect=false)) said:

When calling the request.isUserInRole, the underling class: SecurityContextHolderAwareRequestWrapper:isGranted adds an extra "ROLE_" prefix so calling the request.isUserInRole("ROLE_TEST"); will cause too : ROLE_ROLE_TEST.

**Comment by spring-issuemaster** [comment]
This issue duplicates #3166
