### ISSUE TITLE
SEC-3022: GlobalMethodSecurityConfiguration should autowired RoleHierarchy as it does for PermissionEvaluator

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3234]
[Adrien SAUVEZ](https://jira.spring.io/secure/ViewProfile.jspa?name=asauvez) (Migrated from [SEC-3022](https://jira.spring.io/browse/SEC-3022?redirect=false)) said:

In GlobalMethodSecurityConfiguration.setPermissionEvaluator(), the config seeks a PermissionEvaluator from the context and inject it in defaultMethodExpressionHandler.

The defaultMethodExpressionHandler has also a setRoleHierarchy() method. We could expect the same behavior for the roleHierarchy: Seeking a RoleHierarchy and injecting it in defaultMethodExpressionHandler.

```
    @Autowired(required = false)
    public void setRoleHierarchy(
            List<RoleHierarchy> roleHierarchies) {
        if (roleHierarchies.size() != 1) {
            logger.debug("Not autwiring RoleHierarchy since size != 1. Got "
                    + roleHierarchies);
            return;
        }
        this.defaultMethodExpressionHandler.setRoleHierarchy(roleHierarchies
                .get(0));
    }
```

**Comment by eleftherias** [comment]
This behavior was added as part of gh-4020
