### ISSUE TITLE
SEC-3031: DelegatingSecurityContextRunnable & DelegatingSecurityContextCallable should only modify SecurityContext when invoked on new Thread

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3239]
[Michael Martineau](https://jira.spring.io/secure/ViewProfile.jspa?name=mike.martineau) (Migrated from [SEC-3031](https://jira.spring.io/browse/SEC-3031?redirect=false)) said:

When an ExecutorService (ThreadPoolExecutor) is setup with a CallerRunsPolicy for the RejectedExecutionHandler and the caller thread is used to run the task, the spring security DelegatingSecurityContextCallable and DelegatingSecurityContextRunnable blindly clear the security context upon completion - effectively clearing the security context for the calling thread.  In this case, it should not clear the context.

**Comment by spring-issuemaster** [comment]
This issue relates to #3311
