### ISSUE TITLE
SEC-3045: EnableGlobalMethodSecurity mode=ASPECTJ creates proxies if InfrastructureAdvisorAutoProxyCreator is Added

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3251]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-3045](https://jira.spring.io/browse/SEC-3045?redirect=false)) said:

If `InfrastructureAdvisorAutoProxyCreator` exists, then Spring Security will create proxies for security related classes when `@EnableGlobalMethodSecurity(mode=ASPECTJ, ...`.

This is due to the fact that `GlobalMethodSecurityConfiguration` creates a `MethodSecurityMetadataSourceAdvisor`.

Instead we should conditionally create `MethodSecurityMetadataSourceAdvisor` in an `ImportBeanDefintionRegistrar` only when using proxies for Spring Security.

**Comment by spring-issuemaster** [comment]
This issue relates to #3216
This issue relates to #2921
This issue relates to #2810
This issue supersedes #3216
