### ISSUE TITLE
SEC-3048: Passwords as Strings

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3254]
[Varun Achar](https://jira.spring.io/secure/ViewProfile.jspa?name=varunach) (Migrated from [SEC-3048](https://jira.spring.io/browse/SEC-3048?redirect=false)) said:

According to the Java Cryptography Architecture guide:

_It would seem logical to collect and store the password in an object of type java.lang.String. However, here's the caveat: Objects of type String are immutable, i.e., there are no methods defined that allow you to change (overwrite) or zero out the contents of a String after usage. This feature makes String objects unsuitable for storing security sensitive information such as user passwords. You should always collect and store security sensitive information in a  char array instead._

org.springframework.security.core.userdetails.User class handles passwords as String. Any reason why this is done?

**Comment by spring-issuemaster** [comment]
This issue duplicates #3238
