### ISSUE TITLE
SEC-3051: Add AbstractPreAuthenticatedProcessingFilter principalChanged(HttpServletRequest, Authentication)

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3256]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-3051](https://jira.spring.io/browse/SEC-3051?redirect=false)) said:

This will allow implementations to override a method to determine if the principal has changed. See SEC-2078

**Comment by spring-issuemaster** [comment]
This issue relates to #2302
