### ISSUE TITLE
SEC-3063: OnMissingBeanCondition avoid initializing beans

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3264]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-3063](https://jira.spring.io/browse/SEC-3063?redirect=false)) said:

`OnMissingBeanCondition` should use BeanTypeRegistry.getNamesForType to avoid initializing any beans

**Comment by spring-issuemaster** [comment]
This issue relates to #3263
