### ISSUE TITLE
SEC-3067: Distinguishing BadCredentials and UsernameNotFound from events

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3268]
[Xavier Dury](https://jira.spring.io/secure/ViewProfile.jspa?name=kalgon) (Migrated from [SEC-3067](https://jira.spring.io/browse/SEC-3067?redirect=false)) said:

Currently, `DefaultAuthenticationEventPublisher` fires an `AuthenticationFailureBadCredentialsEvent` in case of `BadCredentialsException` or `UsernameNotFoundException`.

Therefore, event listeners cannot distinguish between the 2 scenarios as the same event is fired for the 2 exceptions.

I suppose this was a deliberate choice to prevent displaying different messages and let attackers guess if an account exists or not but in my case I would like to use event listeners for statistics and need to identify each case.

`AuthenticationFailureBadCredentialsEvent` is the only event which is mapped from 2 exceptions, all other events are mapped from a single exception.

**Comment by smifun** [comment]
I understand that for security reason bad credentials and user not found scenarios should be handled in the same way. Still it should be possible to distinguish those two cases ex. to log/report such cases differently. 

With minimal effort it would be possible to pass UsernameNotFoundException as cause to BadCredentialsException.  That way both current behaviour related to handling BadCredentialsException would be preserved and it would be possible to distinguish those two cases based on cause.

**Comment by rwinch** [comment]
> With minimal effort it would be possible to pass UsernameNotFoundException as cause to BadCredentialsException. That way both current behaviour related to handling BadCredentialsException would be preserved and it would be possible to distinguish those two cases based on cause.

Please log a separate issue to discuss this

**Comment by rwinch** [comment]
The reason the publisher publishes the same event for both is conceptually this is the same thing. If the username is not found or the password does not match invalid credentials were entered. If this needs to be customized it can be done so by updating `DefaultAuthenticationEventPublisher.setAdditionalExceptionMappings`
