### ISSUE TITLE
SEC-3071: IE10/11, cache enabled causes web fonts to not load 

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3274]
[Ajdin Hedzic](https://jira.spring.io/secure/ViewProfile.jspa?name=ajdinhedzic) (Migrated from [SEC-3071](https://jira.spring.io/browse/SEC-3071?redirect=false)) said:

In IE11 (probably other IE versions but not verified) if a user added no-cache to headers then JavaScript resources MUST be excluded from that, otherwise resources such as font awesome will not work. 

Works in HTTPS in Chrome/Firefox. 

Should this be added to documentation? If so I can create a pull request.

**Comment by ksamborn** [comment]
This might be the answer to "why?": 

https://connect.microsoft.com/IE/feedbackdetail/view/992569/font-face-not-working-with-internet-explorer-and-http-header-pragma-no-cache

Here's a description that we found of how to do a workaround: https://www.blackpepper.co.uk/blog/ie-ignores-fonts-over-ssl

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
