### ISSUE TITLE
SEC-3083: SecurityMockMvcRequestPostProcessors.user stops working when upgrading from 4.0.0 to 4.0.2

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3288]
[Jean Noel Delavalade](https://jira.spring.io/secure/ViewProfile.jspa?name=jnd77) (Migrated from [SEC-3083](https://jira.spring.io/browse/SEC-3083?redirect=false)) said:

Unit tests of controllers stopped passing when I upgraded Spring Security from 4.0.0 to 4.0.2.

Controller method:

``` java
    @RequestMapping(value = MY_URI, method = RequestMethod.POST)
    @ResponseStatus(value = HttpStatus.CREATED)
    public void postMethod(@AuthenticationPrincipal SecurityUser user) {
        LOG.debug(user.toString());
    }
```

Unit test:

``` java
MockMvc mockMvc = MockMvcBuilders.standaloneSetup(controller)
                .setCustomArgumentResolvers(new AuthenticationPrincipalArgumentResolver())
                .build();
SecurityUser user = mock(SecurityUser.class);
MockHttpServletRequestBuilder request = post(MY_URI)
                .accept(MediaType.APPLICATION_JSON)
                .with(user(user));
mockMvc.perform(request);
```

With 4.0.0, there is no issue.
But with 4.0.2, user is not resolved in the controller and user.toString() throws a NullPointerException.

Thanks a lot for your help.

**Comment by spring-issuemaster** [comment]
This issue relates to #3061
