### ISSUE TITLE
SEC-3087: OAuth token interfaces shoud be Serializable

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3292]
[Libor Ondrusek](https://jira.spring.io/secure/ViewProfile.jspa?name=librucha) (Migrated from [SEC-3087](https://jira.spring.io/browse/SEC-3087?redirect=false)) said:

I think both of OAuth2 token interfaces shoud be serializable.

```
org.springframework.security.oauth2.common.OAuth2AccessToken
org.springframework.security.oauth2.common.OAuth2RefreshToken
```

If somebody will implement own token services using JPA, tokens can be serialized and deserialized using JPA provider way.

**Comment by rwinch** [comment]
Closing as this is for https://github.com/spring-projects/spring-security-oauth/issues
