### ISSUE TITLE
SEC-3091: Issue tracker link is wrong

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3297]
[Emerson Farrugia](https://jira.spring.io/secure/ViewProfile.jspa?name=mers) (Migrated from [SEC-3091](https://jira.spring.io/browse/SEC-3091?redirect=false)) said:

The issue tracker link on the main page (http://projects.spring.io/spring-security/) between the GitHub link and the Bamboo link points to  

http://jira.springsource.org/browse/SEC

which doesn't work. The link should be 

https://jira.spring.io/browse/SEC

The Bamboo link also seems to be broken, since CloudFlare is returning connection timeouts, but it's harder to tell if that's an intermittent problem or whether the link is wrong too.

**Comment by eleftherias** [comment]
Closing this issue, since it refers to an older version of the spring security page.
We no longer have JIRA or Bamboo links on the page.
Additionally, both JIRA links mentioned redirect to the spring-security github, which is what we currently use for issue tracking.
