### ISSUE TITLE
SEC-3100: Modify Content Security Policy to allow LiveReload when devtools enabled

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3305]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-3100](https://jira.spring.io/browse/SEC-3100?redirect=false)) said:

Ensure Spring Security has proper hooks for https://github.com/spring-projects/spring-boot/issues/3894#issuecomment-137814509

**Comment by rwinch** [comment]
We are not planning on this feature since there will be no CSP within Spring Security given CSP is a moving target.
