### ISSUE TITLE
SEC-3105: Support LogoutSuccessEvent

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3307]
[Kazuki Shimizu](https://jira.spring.io/secure/ViewProfile.jspa?name=kazuki43zoo) (Migrated from [SEC-3105](https://jira.spring.io/browse/SEC-3105?redirect=false)) said:

I want to add new event for indicates a logout success.

usage examples :
- Update login status of account (e.g. active -> idle)
- Create a authentication log to database or log file
- etc ... 

This event fires at follows:
- logout in `LogoutFilter`
- logout in `Servlet3SecurityContextHolderAwareRequestWrapper`
- expire in `ConcurrentSessionFilter`

How do think ?
I submit a PR at later.

**Comment by ptahchiev** [comment]
+1

**Comment by domainname** [comment]
Hi @kazuki43zoo, do you have any idea when your commits will be merged into the master branch?

**Comment by rwinch** [comment]
@domainname The branch was deleted, so it cannot be merged

**Comment by rwinch** [comment]
Closing as duplicate of gh-2900
