### ISSUE TITLE
SEC-3106: Option in BasicAuthenticationFilter to log more exception info

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3308]
[Bill Chen](https://jira.spring.io/secure/ViewProfile.jspa?name=billc.cn) (Migrated from [SEC-3106](https://jira.spring.io/browse/SEC-3106?redirect=false)) said:

The current code in `doFilterInternal()` logs in this way:

`logger.debug("Authentication request for failed: " + failed);`

which, in most cases just produces: "Authentication request for failed: org.springframework.security.authentication.BadCredentialsException: Bad credentials". This is neither a correct sentence nor useful for debugging.

Could it be changed so it logs the stack at trace level or something?

**Comment by eleftherias** [comment]
Fixed via gh-7678
