### ISSUE TITLE
SEC-3134: Consider Moving to Github Issues

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3333]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-3134](https://jira.spring.io/browse/SEC-3134?redirect=false)) said:

Github issues does have limitations (i.e. only single fix version). However, we should consider moving to Github Issues to increase collaboration. For this to work we would need a good migration script from JIRA to Github.

**Comment by rwinch** [comment]
We are now moved to GitHub issues
