### ISSUE TITLE
SEC-3185: Broken Link in Reference Doc

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3354]
[Abhijit Sarkar](https://jira.spring.io/secure/ViewProfile.jspa?name=asarkar) (Migrated from [SEC-3185](https://jira.spring.io/browse/SEC-3185?redirect=false)) said:

The link to the blog article for creating a custom decision voter is broken.

Doc page: https://docs.spring.io/spring-security/site/docs/current/reference/html/authz-arch.html

Section: Custom Voters

Broken Link: http://blog.springsource.com/2009/01/02/spring-security-customization-part-2-adjusting-secured-session-in-real-time/

**Comment by LinkedList** [comment]
This was fixed in [this commit](https://github.com/spring-projects/spring-security/commit/5c36c9f659d57c3bc868f82642b4298a6190992d). The issue can be closed.

**Comment by eleftherias** [comment]
Thank you @LinkedList , I am closing this issue.
