### ISSUE TITLE
SEC-3205: Add 'Cache-Control: private' to default security HTTP headers

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3361]
[Michael Osipov](https://jira.spring.io/secure/ViewProfile.jspa?name=michael-o) (Migrated from [SEC-3205](https://jira.spring.io/browse/SEC-3205?redirect=false)) said:

Adding `Cache-Control: private` would helpfully indicate for an intermediate (proxy) that this response is intended for a single user only. See reference.

**Comment by rwinch** [comment]
We already state `no-store` which is more aggressive. It states that the request should not be cached at all where as private states it can be cached so long as it isn't shared with other users. We should prefer `no-store` because private has no impact on shared computers.
