### ISSUE TITLE
SEC-3169: Security context is propagated but not cloned in @Async methods

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3378]
[Mathieu Lachance](https://jira.spring.io/secure/ViewProfile.jspa?name=matlach) (Migrated from [SEC-3169](https://jira.spring.io/browse/SEC-3169?redirect=false)) said:

In Wildfly with Java EE, whenever you run an asynchronous task using @Asynchronous, the security context is getting cloned and then pushed to the new async thread.
see bug:
https://issues.jboss.org/browse/WFLY-2016
and commit:
https://github.com/wildfly/wildfly/pull/5013/files

In Spring Security though, the strategy to propagate the security context is a bit different. Instead of cloning the context, the reference to the context is propagated to the new async thread.

DelegatingSecurityContextCallable/Runnable

```
    public V call() throws Exception {
        this.originalSecurityContext = SecurityContextHolder.getContext();

        try {
            SecurityContextHolder.setContext(delegateSecurityContext);
            return delegate.call();
        }
        finally {
            SecurityContext emptyContext = SecurityContextHolder.createEmptyContext();
            if(emptyContext.equals(originalSecurityContext)) {
                SecurityContextHolder.clearContext();
            } else {
                SecurityContextHolder.setContext(originalSecurityContext);
            }
            this.originalSecurityContext = null;
        }
    }
```

This can lead to concurrency issue if the new async thread alter the security context.
Ex:
1. an authenticated user trigger something asynchronous and the processing of its request is not over
2. within the asynchronous thread we eventually push another principal to let say execute a job on behalf of a system user
3. meanwhile the processing of the original request continue but now with the new system user principal which can lead to weird behavior

Could it be possible to re-implement the Security Context to be duplicated instead to avoid the issue?

Alternatively, instead of duplicating everything, we could at least duplicate the authentication information which is immutable:

```
    public DelegatingSecurityContextCallable(Callable<V> delegate) {
                // proposed fix for SEC-3169 start
                this(delegate, new SecurityContextImpl());
                this.delegateSecurityContext.setAuthentication(SecurityContextHolder.getContext().getAuthentication());
                 // proposed fix for SEC-3169 end
    }
```

If there's anything I've miss let me know,

Thanks,

**Comment by freesoft** [comment]
Is this still considered a bug? IIRC it is related to how SecurityContextHolder is configured, and per-thread is a default. However, this behavior can be changed by setting SecurityContextHolder through

```
@Bean
public MethodInvokingFactoryBean methodInvokingFactoryBean() {
    MethodInvokingFactoryBean methodInvokingFactoryBean = new MethodInvokingFactoryBean();
    methodInvokingFactoryBean.setTargetClass(SecurityContextHolder.class);
    methodInvokingFactoryBean.setTargetMethod("setStrategyName");
    methodInvokingFactoryBean.setArguments(new String[]{SecurityContextHolder.MODE_INHERITABLETHREADLOCAL});
    return methodInvokingFactoryBean;
}
```

or simply pass the environment variable 

```
spring.security.strategy=ODE_INHERITABLETHREADLOCAL
```
when running spring application. 

The ticket seems more than 4 years old, but I think this ticket needs a re-triage for whether the ticket is a bug or not. I personally think current implementation gives more flexibility to the developer though...

**Comment by jukkasi** [comment]
I recently ran into this issue. Changing strategy does not fix the issue, because same SecurityContext instance is always shared between threads that context has been passed to. Therefore any thread changing the context will affect all threads. This is problematic if user who started job threads for example logs out and some running jobs are not completed yet, they will lose access to context at logout time.

Using MODE_INHERITABLETHREADLOCAL or DelegatingSecurityContextExecutor, or both does not fix the issue.

Also using only MODE_INHERITABLETHREADLOCAL has huge security issue if used with thread pools, since created threads will preserve SecurityContext that was passed on creation time and this context might be re-used when thread is reused.

**Comment by rwinch** [comment]
I think it would be useful if someone could put together a sample and detailed instructions on how to reproduce the originally reported issue in wildfly.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
