### ISSUE TITLE
SEC-3175: Migrate to AssertJ

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3384]
[Rob Winch](https://jira.spring.io/secure/ViewProfile.jspa?name=rwinch) (Migrated from [SEC-3175](https://jira.spring.io/browse/SEC-3175?redirect=false)) said:

We should migrate fest assert, JUnit, and Hamcrest assertions to AssertJ

**Comment by TYsewyn** [comment]
@rwinch I'll pick this up further, if it's ok?

**Comment by rwinch** [comment]
@TYsewyn Thanks for the offer! I'm real excited how active you have been :) I think this one will be taken care of in a PR #248 I'm just struggling to get all the PRs I've been getting merged.

**Comment by rwinch** [comment]
Fixed via 71d4ce96add0f
