### ISSUE TITLE
SEC-3187: LdapUserDetailsManager password change with LDAP operation (RFC 3062)

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3392]
[Mark Janssen](https://jira.spring.io/secure/ViewProfile.jspa?name=praseodym) (Migrated from [SEC-3187](https://jira.spring.io/browse/SEC-3187?redirect=false)) said:

Currently the [LdapUserDetailsManager changePassword method](https://github.com/spring-projects/spring-security/blob/1f32e96d31c6a149e480ebdb5ce0274889877995/ldap/src/main/java/org/springframework/security/ldap/userdetails/LdapUserDetailsManager.java#L169-L212) modifies the password attribute directly. It would be better to (optionally) use the [LDAP Password Modify Extended Operation as described in RFC 3062](https://www.ietf.org/rfc/rfc3062.txt). This way, any associated attributes (e.g. Samba NTLM hashed passwords) will also be updated by the LDAP server.

**Comment by quanah** [comment]
This is a security issue, not just an improvement.  By doing a direct modify on the userPassword attribute, the security configuration for userPassword is bypassed.

**Comment by kopax** [comment]
I have clear password stored in my LDAP because of that. Any update on this?

**Comment by carlspring** [comment]
Hi,

Is there any update on this?

**Comment by fuss86** [comment]
+1

**Comment by sbespalov** [comment]
+1

**Comment by carlspring** [comment]
@monowai,
Why the downvotes?

**Comment by jacovt** [comment]
+1

**Comment by jacovt** [comment]
This is raised when putting code through vulnerability analysis tools like Snyk:

https://snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORK-31644

**Comment by carlspring** [comment]
Yeah, we're getting it in our snyk.io reports as well!

Could we have an update on this, please?

**Comment by acooley** [comment]
+1.  This needs to be fixed.

**Comment by steve-todorov** [comment]
Are there any updates on this? @tekul, @rwinch, @jgrandja ping?

**Comment by carlspring** [comment]
Is there any update on this? It's been around for a while now and it's causing our snyk.io checks to fail, (which is, of course the least of our concerns, given the seriousness of the issue). Could we get some sort of update, please?

**Comment by carlspring** [comment]
Thanks for fixing this @jzheaux ! In which version do you think this will be released and any idea when that will be? :)

**Comment by ddillard** [comment]
Is there any plan to get a CVE for this issue?

**Comment by rwinch** [comment]
@ddillard No. This was not a feature that was supported, so users would have been expected to hash it themselves.
