### ISSUE TITLE
SEC-3188: Clearly document the configurers of WebSecurityConfigurerAdapter

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3393]
[Abhijit Sarkar](https://jira.spring.io/secure/ViewProfile.jspa?name=asarkar) (Migrated from [SEC-3188](https://jira.spring.io/browse/SEC-3188?redirect=false)) said:

There is no documentation of how the various configurers of `WebSecurityConfigurerAdapter` work together. You get a different configurer if you use `and()` than if you keep chaining with `.`. The Spring doc still uses examples using XML config where as Java config has been fully supported since 3.x. A search on the internet reveals the usual approach taken by most people is to pick random pieces and shoehorn those together. In other words, throw pasta at the wall and hope that it sticks. This is a dangerous situation with something as crucial as security config.

Expected outcome:
# Document the relationships between the various configurers and filters. Who builds who and what is chained with what else.
# Show some non-trivial examples of customization, like adding a custom filter, authentication provider and access decision manager.
# For advanced users, show example of how to post-process a security related bean.

[SO question](http://stackoverflow.com/questions/34552926/spring-security-why-is-my-custom-accessdecisionvoter-not-invoked/34663180#34663180) that goes into detail of a problem I faced, solution to that, and why I created this ticket.

**Comment by asarkar** [comment]
Hello...anyone here? It's been a year.

**Comment by rwinch** [comment]
Please see https://docs.spring.io/spring-security/site/docs/current/reference/html/jc.html and https://github.com/spring-projects/spring-security/tree/master/samples/javaconfig

**Comment by asarkar** [comment]
@rwinch neither the doc nor the samples explain the relationships between the various configurers and filters. Who builds who and what is chained with what else. Regarding the 2 other points, is there one or two specific examples that you can point to? Right now, I'm looking at the Spring Security Java config doc and a lot of examples, and it seems like trying to find a needle in a haystack.
