### ISSUE TITLE
SEC-3194: AbstractSecurityWebApplicationInitializer don't have way to customize url mappings

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#3397]
[Artur](https://jira.spring.io/secure/ViewProfile.jspa?name=artur-yolchyan) (Migrated from [SEC-3194](https://jira.spring.io/browse/SEC-3194?redirect=false)) said:

AbstractSecurityWebApplicationInitializer don't have way to customize url mappings, if there will be one abstract method which will return the url, so it always not do filter on '/*'

**Comment by marcusdacoregio** [comment]
Thanks for the report.

In the latest releases of Spring Security you are able to customize URL mapping by using the HttpSecurity DSL.
There are [many samples](https://github.com/spring-projects/spring-security-samples) that reproduce what you are trying to achieve, [here is one](https://github.com/spring-projects/spring-security-samples/blob/main/servlet/spring-boot/java/oauth2/resource-server/jwe/src/main/java/example/OAuth2ResourceServerSecurityConfiguration.java).

You can explore the [reference documentation](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#jc-httpsecurity) to have more details about the `HttpSecurity`.
