### ISSUE TITLE
SEC-3196: Broken formatting in chapter 11.1

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3398]
[Michael Osipov](https://jira.spring.io/secure/ViewProfile.jspa?name=michael-o) (Migrated from [SEC-3196](https://jira.spring.io/browse/SEC-3196?redirect=false)) said:

See formatting at the at of the chapter:
!broken-formatting.png|thumbnail!

It shouldn't probably look like that.

**Comment by eleftherias** [comment]
Closing since the documentation has been fixed in all supported versions.
