### ISSUE TITLE
SEC-3202: Add authentication-success-handler-ref to security:jee

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3401]
[Michael Osipov](https://jira.spring.io/secure/ViewProfile.jspa?name=michael-o) (Migrated from [SEC-3202](https://jira.spring.io/browse/SEC-3202?redirect=false)) said:

I have a usecase where the authenticated request from the container needs to be examined and some specific data needs to be written to a database. An `AuthenticationSuccessHandler` is the best approach for this but `security:jee` does not accept `authentication-success-handler-ref` (in contrast to `security:form-login`). Please add this as it would be very helpful for several preauth scenarios.

**Comment by rwinch** [comment]
Duplicates #2101
