### ISSUE TITLE
SEC-3203: GlobalMethodSecurityConfiguration typo in autowiring log message

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3402]
[Robert Novotny](https://jira.spring.io/secure/ViewProfile.jspa?name=novotnyr) (Migrated from [SEC-3203](https://jira.spring.io/browse/SEC-3203?redirect=false)) said:

GlobalMethodSecurityConfiguration has two typos:

* method `setMethodSecurityExpressionHandler` logs a message "Not autwiring PermissionEvaluator since size != 1". However, there are no PermissionEvaluators involved. Instead, method handles `MethodSecurityExpressionHandler`, which may lead to confusing log message. Furthermore, there is a typo in the message
* method `setPermissionEvaluator` logs a message with a typo "Not autwiring PermissionEvaluator since size != 1".

**Comment by novotnyr** [comment]
* `setPermissionEvaluator` typo is obsolete due to changes in bb997eecde68164f1ba5195bfeb2849485588c4f
