### ISSUE TITLE
SEC-3210: Ability to configure remember me cookie domain

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3408]
[Adrien SAUVEZ](https://jira.spring.io/secure/ViewProfile.jspa?name=asauvez) (Migrated from [SEC-3210](https://jira.spring.io/browse/SEC-3210?redirect=false)) said:

I have a site with different locale (en.sample.org, fr.sample.org) and I would like to have to global "remember-me" cookie for all of them. If you are logged on one, your are logged on all of them. It work only if the domain of the cookie is "sample.org" and not "en.sample.org".

You are currently able to configure the name of the cookie, its validity in seconds and if it is secured (RememberMeConfigurer), but not its domain. You have to define a custom RememberMeServices and override setCookie().

It may also be usefull to define the cookie path and if it is httpOnly or not.

Thanks,

Adrien

**Comment by rwinch** [comment]
Support for configuring the domain has been added. If any additional changes are necessary we can create specific tickets for the support
