### ISSUE TITLE
SEC-3213: Please update standard reference about missing default constructor in ConcurrentSessionFilter

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#3411]
[Mohsen Saboorian](https://jira.spring.io/secure/ViewProfile.jspa?name=mohsens) (Migrated from [SEC-3213](https://jira.spring.io/browse/SEC-3213?redirect=false)) said:

Please update the documentation about missing public constructor in org.springframework.security.web.session.ConcurrentSessionFilter.
Please see:
[http://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#session-mgmt]

This part is invalid:

```
<beans:bean id="concurrencyFilter"
class="org.springframework.security.web.session.ConcurrentSessionFilter">
<beans:property name="sessionRegistry" ref="sessionRegistry" />
<beans:property name="expiredUrl" value="/session-expired.htm" />
</beans:bean>
```

**Comment by eleftherias** [comment]
Fixed via gh-4622
