### ISSUE TITLE
SwitchUserFilter.ROLE_PREVIOUS_ADMINISTRATOR cannot be overridden

### ISSUE THREAD

**Issue by andrei-ivanov** [spring-projects/spring-security#3697]
Using the switch user functionality, I'm trying to see if the current user has the PREVIOUS_ADMINISTRATOR role using a different prefix than the standard one.
This fails since the name is hardcoded with the prefix: `org.springframework.security.web.authentication.switchuser.SwitchUserFilter.ROLE_PREVIOUS_ADMINISTRATOR = "ROLE_PREVIOUS_ADMINISTRATOR"`

**Comment by rwinch** [comment]
@andrei-ivanov Thanks for the submission! If this is something you are interested in, can you submit a PR to have a member variable for the previous administrator's role that defaults to  `SwitchUserFilter.ROLE_PREVIOUS_ADMINISTRATOR`. You would then provide a setter to allow overriding the default.

**Comment by andrei-ivanov** [comment]
PR created.

**Comment by andrei-ivanov** [comment]
BTW, why give up on Jira?
I find it much nicer than the GH issues tracker.

**Comment by rwinch** [comment]
@andrei-ivanov Thank you for creating a PR! I have responded to the PR!

> BTW, why give up on Jira?
> I find it much nicer than the GH issues tracker.

Thank you for your feedback. I agree that JIRA has some advantages over GitHub issues. However, we have gotten lots of feedback that users prefer GitHub issues as they already have accounts, integrates better with their tooling, etc. I have also found that the projects using GitHub issues have a lot more community involvement which is something that we are looking for. I hope this makes sense :)

**Comment by andrei-ivanov** [comment]
BTW, I think some mechanism would be nice to set the role prefix in a single place.
Currently I have this in 4 places:
```xml
<bean id="defaultMethodSecurityExpressionHandler" class="org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler">
	<property name="defaultRolePrefix" value="ROLE:" />
</bean>

<bean id="defaultWebSecurityExpressionHandler" class="org.springframework.security.web.access.expression.DefaultWebSecurityExpressionHandler">
	<property name="defaultRolePrefix" value="ROLE:" />
</bean>

<bean id="securityContextHolderAwareRequestFilter" class="org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter">
	<property name="rolePrefix" value="ROLE:" />
</bean>

<bean id="daoUserDetailsService" class="custom.DaoUserDetailsServiceImpl">
	<property name="rolePrefix" value="ROLE:" />
</bean>
```

**Comment by rwinch** [comment]
@andrei-ivanov Thanks for the suggestion. I have been considering this myself. Do you think you could create a new issue (perhaps even a PR)? I'm thinking we could create a Bean that has the defaultRolePrefix on it and then update all the default objects to look for this bean and update the default.
