### ISSUE TITLE
SEC-109: PortMapperImpl property mistake

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#370]
["Emmanuele Bello":https://jira.spring.io/secure/ViewProfile.jspa?name=mannobug](Migrated from ["SEC-109":https://jira.spring.io/browse/SEC-109?redirect=false]) said:

In accordance wuth Acegi Security System Platform Documentation, you can set a custom definition of socket port mapping (by default this is set in this way HTTP: 80/8080, HTTPS: 443/8443).
The definition of the setter method -public void setPortMappings(Map newMappings)- set this property httpsPortMapping. 
But this definition cause an Exception on the property writing. 
To allow the settings the property in applicationContext must be set as "portMapping".

Again, API's report this specifics for method setPortMappiungs:

public void setPortMappings(Map newMappings)

Set to override the default HTTP port to HTTPS port mappings of 80:443, 
and 8080:8443. In a Spring XML ApplicationContext, a definition would look something like 
this:

   <property name="httpsPortMapping">
     <map>
       <entry key="80"><value>443</value></entry>
       <entry key="8080"><value>8443</value></entry>
     </map>
   </property>

Parameters:

newMappings - A Map consisting of String keys and String values, where 
for each entry the key is the string representation of an integer HTTP port 
number, and the value is the string representation of the corresponding 
integer HTTPS port number. 

Throws:

IllegalArgumentException - if input map does not consist of String 
keys and values, each representing an integer port number in the range 
1-65535 for that mapping.

Thanks for attention.
Kind Regards

**Comment by spring-issuemaster** [comment]
This issue duplicates #365
