### ISSUE TITLE
Create single point of defining the default role prefix

### ISSUE THREAD

**Issue by andrei-ivanov** [spring-projects/spring-security#3701]
If one wants to change the default role prefix this must be done in more than one place and this can lead to errors if one of them is forgotten.
Currently I set it in 4 places:
```xml
<bean id="defaultMethodSecurityExpressionHandler" class="org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler">
	<property name="defaultRolePrefix" value="ROLE:" />
</bean>

<bean id="defaultWebSecurityExpressionHandler" class="org.springframework.security.web.access.expression.DefaultWebSecurityExpressionHandler">
	<property name="defaultRolePrefix" value="ROLE:" />
</bean>

<bean id="securityContextHolderAwareRequestFilter" class="org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter">
	<property name="rolePrefix" value="ROLE:" />
</bean>

<bean id="daoUserDetailsService" class="custom.DaoUserDetailsServiceImpl">
	<property name="rolePrefix" value="ROLE:" />
</bean>
```
Some strategy should be created to set the default role in a single place and the other components should use it.

**Comment by rwinch** [comment]
@andrei-ivanov Thanks for creating this! I don't suppose you are interested in creating a PR too?

**Comment by andrei-ivanov** [comment]
I can try. Any suggestions of component? :)

**Comment by rwinch** [comment]
This would be something easy to change as we think more about it. However, perhaps something like `org.springframework.security.config.core.GrantedAuthorityDefaults` makes sense?

**Comment by andrei-ivanov** [comment]
Uf, I'm afraid I got caught with a new project that started and I don't think I'll be able to implement this myself.
I hope you or someone else can :)

**Comment by eddumelendez** [comment]
@rwinch so the expected configuration would be something like this?

```xml
<bean id="defaultMethodSecurityExpressionHandler" class="org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler">
    <property name="defaultRolePrefix" ref="grantedAuthorityDefaults" />
</bean>

<bean id="defaultWebSecurityExpressionHandler" class="org.springframework.security.web.access.expression.DefaultWebSecurityExpressionHandler">
    <property name="defaultRolePrefix" ref="grantedAuthorityDefaults" />
</bean>

<bean id="securityContextHolderAwareRequestFilter" class="org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter">
    <property name="rolePrefix" ref="grantedAuthorityDefaults" />
</bean>

<bean id="grantedAuthorityDefaults" class="org.springframework.security.config.core.GrantedAuthorityDefaults">
    <property name="rolePrefix" ref="ROLE" />
</bean>
```

**Comment by andrei-ivanov** [comment]
I think the top 3 beans should use the ``grantedAuthorityDefaults`` bean by default, without manual configuration :-)

**Comment by rwinch** [comment]
@eddumelendez Thanks for the question. @andrei-ivanov is right. If `GrantedAuthorityDefaults` is defined it would be used by default with no need to define the other beans. 

If user's explicitly define `DefaultMethodSecurityExpressionHandler` (or any of the other beans), then they would need to specify `defaultRolePrefix` explicitly.

**Comment by eddumelendez** [comment]
@andrei-ivanov @rwinch Thanks, I will take into account.

**Comment by kazuki43zoo** [comment]
Hi @rwinch,

I tried this feature on my application.

I changed role prefix to "R_"  as follow:

```java
    @Bean
    GrantedAuthorityDefaults grantedAuthorityDefaults() {
        return new GrantedAuthorityDefaults("R_");
    }
```

Following configuration is working. (It can access by user assigned the "R_USER")

```java
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        // ...
        http.authorizeRequests()
                .anyRequest().access("hasRole('USER')");
        // ...
    }
```

However, following configuration is not working.  (It can't access by user assigned the "R_USER")

```java
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        // ...
        http.authorizeRequests()
                .anyRequest().hasRole("USER");
        // ...
    }
```

Is this behavior correct ?

**Comment by andrei-ivanov** [comment]
Debug it and see where is the root cause :-)

**Comment by rwinch** [comment]
@kazuki43zoo This seems like it should be improved to impact the configuration as well. Can you create a ticket for this?

**Comment by kazuki43zoo** [comment]
Hi @rwinch , of course !!

**Comment by kazuki43zoo** [comment]
> Can you create a ticket for this?

I've created. see gh-4134.
