### ISSUE TITLE
HTTP Public Key Pinning

### ISSUE THREAD

**Issue by TYsewyn** [spring-projects/spring-security#3706]
See http://tools.ietf.org/html/rfc7469

**Comment by rwinch** [comment]
Thanks for the report @TYsewyn! Any chance you would be interested in submitting a PR?

**Comment by rwinch** [comment]
Just saw your tweet https://twitter.com/tysewyn/status/700393662690258944 ! I'm looking forward to seeing the PR :)

**Comment by TYsewyn** [comment]
Since it is labeled as a new feature/improvement, is it safe to assume it will be picked up in the 4.1 release?

**Comment by rwinch** [comment]
@TYsewyn Assuming you get a PR by then, yes that would be the plan :)

**Comment by rwinch** [comment]
PS Getting 4.1 out is going to be my primary goal in the coming days.

**Comment by rwinch** [comment]
@TYsewyn I had one more pass. After that I think we are done!

**Comment by TYsewyn** [comment]
@rwinch All last notes were changed/implemented and all commits were squashed so I think we're good to go here!

**Comment by rwinch** [comment]
@TYsewyn Thanks again for the PR! This is now merged into master :)

**Comment by rwinch** [comment]
@TYsewyn I'm going to mention those that contribute when the release is announced. Do you have a preferred way for me to give you credit (i.e. link to github, link to twitter, link to your website, etc)?

**Comment by TYsewyn** [comment]
Link to twitter is fine for me!

**Comment by rwinch** [comment]
@TYsewyn Great. To make it easier for me later https://twitter.com/TYsewyn
