### ISSUE TITLE
Adding @Secured to an unused action method empties controller fields

### ISSUE THREAD

**Issue by danilcha** [spring-projects/spring-security#3709]
This issue has many times been unsuccessfully questioned in StackOverflow: 
- [@Secured in controller @Autowired not work](http://stackoverflow.com/questions/23193329/secured-in-controller-autowired-not-work) 
- [spring session scope form is null when using @Secured](http://stackoverflow.com/questions/24804845/spring-session-scope-form-is-null-when-using-secured)
- [Struts2 + Spring Security 2.06: Valuestack is null when attempting to use @Secured on an Action method](http://stackoverflow.com/questions/8829346/struts2-spring-security-2-06-valuestack-is-null-when-attempting-to-use-secur?rq=1)

I have `@EnableGlobalMethodSecurity(securedEnabled = true)` and the following controller:
```java
@Controller
public class MyController
{
    private final String hello = new String("hello");

    @RequestMapping("/registration")
    private String registration()
    {
        System.err.println(this + " " + this.hello);
        return "registration";
    }

    @RequestMapping("/secured-place")
    @Secured({"ROLE_USER", "ROLE_ADMIN"})
    public String securedPlace()
    {
        return "secured-view";
    }
}
```
When I open `/registration` url in my browser (and do not even touch `/secured-place`, the value of final (sic!) field is `null`, not `"hello"`. When I remove `@Secured` annotation, the code works as expected.

**Comment by rwinch** [comment]
@danilcha Thanks for the report!

CGLIB proxying will not work properly due to the fact that the `registration` method is private. This is a known limitation with proxy based AOP. If you change the method to public, then `hello` should be non-null.

**Comment by danilcha** [comment]
@rwinch Thank you, yes, I for some reason made it private. Now it works. Can you track such cases and write a warning into the log? Many people were struggling with this, thinking their `@Autowired` or `@Inject` do not work.

In general, I know that `@Secured` should not be used in controllers, OK, I understand why. Is there some alternative that can be used in controllers instead of using `authorizeRequests()` in security configuration? If I have controller action wired to `/login` I then have to remember to include `/login` into the security configuration, that is in a different file. And if I rename the path, I have to rename it in many places.

**Comment by rwinch** [comment]
@danilcha It is fine to use method security on controllers. In fact, we recommend you do both method security and URL security.

**Comment by rwinch** [comment]
Closing since this was resolved by changing the method to public and is working as expected
