### ISSUE TITLE
No CSRF protection on remember-me authentication

### ISSUE THREAD

**Issue by sambiomatters** [spring-projects/spring-security#3711]
There does not appear to be any CSRF protection for remember-me logins using the Java Spring Config (unless you make a custom request matcher). I realise this is probably by design, to allow links to function correctly. The extent of the "attack" would be to cause the current user to be logged in again. I'm not sure if there's any further attack vectors possible after this.

Is there any way we could get an option to enable CSRF protection in a follow on update?

**Comment by sambiomatters** [comment]
Closing as Synchronizer Token flow is not logical for most standard uses of remember me tokens. 

I can see this is probably handled better for our use cases (SPA with REST) by sending the remember me token in the header.

Feel free to re-open if you think the config option has merit.

**Comment by rwinch** [comment]
As already mentioned, CSRF protection for remember me does not make sense. The remember me cookie cannot be set by an external domain, so it cannot trigger a CSRF log in attempt.
