### ISSUE TITLE
@Secured is is not recognizing user roles

### ISSUE THREAD

**Issue by gustavolira** [spring-projects/spring-security#3712]
Hi,

It looks very strange behavior, probably a bug.
I have a Spring boot 1.3.2 as backend API using Rest Service and I have another application using Angular 2 consuming these services.
All the security stuff is working ok with JWT Token, I can restricted my services for logged users, I can check the user logged and so on. Authorization is not working 100%, If I add on my services `@Secured` or `@PreAuthorize` with some user role this work with swagger and with my MockMvc tests using `@WithMockUser(roles="ROLE_TEST")` so it's configured OK.

The problem is that Authorization with `@Secured` or `@PreAuthorize` is not working when I'm accessing via angular application, All my requests that has `@Secured` or `@PreAuthorize` I receive Status 403.

`authentication.getAuthorities()` that all my roles is being loaded perfectly

**Comment by rwinch** [comment]
@gustavolira Thanks for the report. You are going to need to provide me with more details for me to be able to help you. There are tests that demonstrate this work, so this is either a setup issue on your side or some sort of edge case.

**Comment by gustavolira** [comment]
@rwinch thanks for you attention.
I wil put here my configs maybe you can find something wrong.
Controller:
```java
@RequestMapping(method=RequestMethod.GET, produces=MediaType.APPLICATION_JSON_UTF8_VALUE)
@Secured("ROLE_MANTER_INSTITUICAO")
public List<HierarquiaInstituicao> getAll() {
    return service.findAll();
}
```
Spring Security Config:
```java
@Configuration
@EnableWebSecurity
@EnableGlobalMethodSecurity(securedEnabled = true, prePostEnabled=true, jsr250Enabled=true)
public class SpringSecurityConfig extends WebSecurityConfigurerAdapter {

private UserService userService;
private final TokenAuthenticationService tokenAuthenticationService;

public SpringSecurityConfig() {
    super(true);
    this.userService = new UserService();
    tokenAuthenticationService = new TokenAuthenticationService(userService);
}

@Override
protected void configure(HttpSecurity http) throws Exception {

    http.exceptionHandling().and().anonymous().and().servletApi().and()
            .authorizeRequests()
            // Allow anonymous logins
            .antMatchers("/api/auth/**").permitAll()

            // All other request need to be authenticated
            .anyRequest().authenticated().and()

            // Custom Token based authentication based on the header
            // previously given to the client
            .addFilterBefore(new StatelessAuthenticationFilter(tokenAuthenticationService),
                    UsernamePasswordAuthenticationFilter.class);
}

@Override
protected void configure(AuthenticationManagerBuilder auth) throws Exception {
    auth.userDetailsService(userService).passwordEncoder(new BCryptPasswordEncoder());
}

@Bean
@Override
public AuthenticationManager authenticationManagerBean() throws Exception {
    return super.authenticationManagerBean();
}

@Bean
@Override
public UserService userDetailsService() {
    return userService;
}

@Bean
public TokenAuthenticationService tokenAuthenticationService() {
    return tokenAuthenticationService;
}
```
My filter:
```java
public class StatelessAuthenticationFilter extends GenericFilterBean {

private final TokenAuthenticationService authenticationService;

public StatelessAuthenticationFilter(TokenAuthenticationService authenticationService) {
    this.authenticationService = authenticationService;
}

@Override
public void doFilter(ServletRequest request, ServletResponse response, FilterChain filterChain)
        throws IOException, ServletException {

    HttpServletRequest httpRequest = (HttpServletRequest) request;
    HttpServletResponse httpResponse = (HttpServletResponse) response;
    Authentication authentication = authenticationService.getAuthentication(httpRequest);
    if(authentication != null) {
        SecurityContextHolder.getContext().setAuthentication(authentication);
        filterChain.doFilter(request, response);
    }
    else {
        httpResponse.setStatus(HttpStatus.UNAUTHORIZED.value());
    }
    SecurityContextHolder.getContext().setAuthentication(null);

}
```
Main config
```java
@SpringBootApplication
@EnableRedisHttpSession
@EnableJpaRepositories(basePackages = { "xyz.suporte",
		"xyz.cadastral"})
@EntityScan(basePackages = "br.com.entity", basePackageClasses=Jsr310JpaConverters.class)
@EnableTransactionManagement
@EnableSwagger2
public class IssuerApplication {

	public static void main(String[] args) {
		SpringApplication.run(IssuerApplication.class, args);
		
	}

	@Bean
	public RequestContextListener requestContextListener() {
		return new RequestContextListener();
	}
	
	@Bean
	public JedisConnectionFactory connectionFactory() {
		return new JedisConnectionFactory();
	}

	@Bean
	public PasswordEncoder passwordEncoder() {
		return new BCryptPasswordEncoder();
	}

	@Bean
	public Docket documentation() {
		return new Docket(DocumentationType.SWAGGER_2).select().apis(RequestHandlerSelectors.any())
				.paths(regex("/api/.*")).build().pathMapping("/").apiInfo(metadata());
	}

	@Bean
	public UiConfiguration uiConfig() {
		return UiConfiguration.DEFAULT;
	}

	private ApiInfo metadata() {
		return new ApiInfoBuilder().title("xyz").description("xyz").version("0.1")
				.contact("xyz@xyz.com").build();
	}
	
	@Bean
    public WebMvcConfigurer corsConfigurer() {
        return new WebMvcConfigurerAdapter() {
            @Override
            public void addCorsMappings(CorsRegistry registry) {
                registry.addMapping("/api/**").allowedOrigins("*").allowCredentials(true)
                .exposedHeaders("Access-Control-Allow-Origin: *")
                .allowedMethods("GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "TRACE")
                .allowedHeaders("X-PINGOTHER", "content-type", "X-Requested-With", "Authorization");
                
            }
        };
    }
```

**Comment by rwinch** [comment]
@gustavolira Thanks for the update. Nothing in your configuration jumps out at me. Can you put together a complete & minimal example that reproduces the problem?

**Comment by gustavolira** [comment]
I'm using two applications, one with spring and another one that are using angular 2 for you reproduce you would be able to run these two applications, it's ok for you?

**Comment by gustavolira** [comment]
I'm thinking to create this funcional of "@Secured" on hands, putting at beginning of each method the verification of my roles, if role was not found I trow AccessDeniedException, I think would be the same behavior but I don't know about performance

**Comment by rwinch** [comment]
@gustavolira 

> I'm using two applications, one with spring and another one that are using angular 2 for you reproduce you would be able to run these two applications, it's ok for you?

The easier it is for me to run the application(s) the faster you will get a response. I tend to prioritize things that are easier so I can get more done. It also rewards those that are willing to put in effort to simplify the problem for me.

> I'm thinking to create this funcional of "@Secured" on hands, putting at beginning of each method the verification of my roles, if role was not found I trow AccessDeniedException, I think would be the same behavior but I don't know about performance

You can place the code within your method. However, this means you do not have the benefits of AOP.

**Comment by gustavolira** [comment]
@rwinch Just to update. At beginning of the service I put:
```java
HasRole.check("ROLE_MANTER_FILIAL");
```
At method HasRole.check I put:
```java
public static void check(String... roles) {
		
		Collection<? extends GrantedAuthority> authorities = SecurityContextHolder.getContext().getAuthentication().getAuthorities();
		for(String role: roles) {
			if(authorities.contains(new SimpleGrantedAuthority(role))) {
				return;
			} else {
				throw new AccessDeniedException("Você não possui permissão para esta ação");
			}
		}
```
And it's working, so for me sounds like a bug has @Secured not being recognizing user roles.
I agree that you need an environment to be able to reproduce this problem, as soon as possible I will share with you this environment

**Comment by gustavolira** [comment]
I will close this Issue and apologize for time spent.
I could figure out what was happening. was a line break issue in the database records...

**Comment by rwinch** [comment]
@gustavolira I'm glad you figured it out!
