### ISSUE TITLE
Simplify configuration MethodExpressionHandler for @EnableGlobalMethodSecurity

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-security#3735]
Currently when we enable web security and have a class that extends `WebSecurityConfigurerAdapter` and we also want to use `@EnableGlobalMethodSecurity` with a customized `MethodExpressionHandler` we need to add an additional configuration class which extends `GlobalMethodSecurityConfiguration` which (at least I found) often leads to errors regarding that it cannot find an `AuthenticationManager`.

It would be nice if there would be an easier mechanism to extend/modify the security configuration for instance by using an `expression-handler-ref` on the annotation, just like with the namespace or maybe allowing something like a `GlobalMethodSecurityConfigurer` to exist to do additional configuration for some of the requested beans. 

All in all I find the java config less intuitive than the XML configuration (I often revert to XML configuration for the ease of use, or maybe I just want more complex things which are easier to do in XML then in Java :) ).

**Comment by rwinch** [comment]
@mdeinum Thanks for your feedback. 

You should be able to simply expose the `MethodExpressionHandler` as a `@Bean` and it will get picked up by default.

> with a customized MethodExpressionHandler we need to add an additional configuration class which extends GlobalMethodSecurityConfiguration which (at least I found) often leads to errors regarding that it cannot find an AuthenticationManager.

How do you create your `AuthenticationManager`? If you use one of the protected methods it will not be exposed.

> All in all I find the java config less intuitive than the XML configuration

About Java Configuration vs XML Configuration. In many ways the Java Configuration model for Spring (and thus Spring Security) is less mature than the XML configuration model. For example, in XML one can declare:

```<http />```

which makes multiple Spring Beans available.

However, there is no way to have a single statement create multiple beans with Java Configuration. This means Spring Security has needed to provide workarounds to make these things work in Java Configuration. We are still very much learning how to deal with these limitations (and the repercussions of working around them).

I've planted the seed in Spring Framework that it would be ideal if the core framework could have first class support for these sort of DSLs. I'm hoping we will see changes in Spring Framework 5.

Of course, in the mean time, XML configuration is an option if that is what you prefer. Spring is about choice :)

**Comment by rwinch** [comment]
@mdeinum I'm going to close this as resolved. If this doesn't work for you, please reopen.

**Comment by mdeinum** [comment]
@rwinch I totally missed the fact that I could simply declare a bean of that type and that it would be picked up automatically. that will of course work for my use case...

**Comment by rwinch** [comment]
@mdeinum Totally understandable. We have a bit of a documentation crisis (in particular with the Java Config) I hope we are able to start resolving these documentation issues in the coming release.
