### ISSUE TITLE
Question: converting security.xml to java config

### ISSUE THREAD

**Issue by mschipperheyn** [spring-projects/spring-security#3742]
I have two questions on stack regarding converting security.xml to java config

[**How to implement a custom securityMetataSource**](http://stackoverflow.com/questions/35924873/security-xml-to-java-config-how-to-implement-a-custom-securitymetatasource) 

Here we have a custom securityMetadataSource. It doesn't seem to get picked up automatically, and I'm not sure how to include it in the http security wizard. Because we have multiple site configurations that can have various security configurations, we keep the security in a separate site specific config class

[**How to reference position=“LAST”**](http://stackoverflow.com/questions/35902240/security-xml-to-java-config-how-to-reference-position-last)

I wonder if you would mind having a look?

**Comment by rwinch** [comment]
I responded on SO

**Comment by mschipperheyn** [comment]
Thank you.
