### ISSUE TITLE
Add Basic Checkstyle

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#3746]

**Comment by vpavic** [comment]
@rwinch do you need help with this one?
What exact scope of checks did you have in mind? Given the size of the project and the targeted milestone, license header, imports and indentation checks are decent effort for "basic" Checkstyle IMO.

**Comment by rwinch** [comment]
@vpavic Thanks for the offer! 

When you mentioned this I was already nearly done with what I had in mind for a basic checkstyle. If you find the time to make this more complete (i.e. what Spring Session used), I'd be eager to accept the PR #3748 :)
