### ISSUE TITLE
Make AuthenticationPrincipal migration more obvious

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#3771]
It seems like there are a [number of people](http://stackoverflow.com/questions/36219009/spring-security-deprecated-authenticationprincipal) having difficulty migrating to the new `AuthenticationPrincipal`. We should make it more obvious that `org.springframework.security.web.method.annotation.AuthenticationPrincipalArgum‌​entResolver` should be used.

Ideas for where this can be documented

* Migration Guide
* Deprecation notice
* Javadoc of `AuthenticationPrincipal`

**Comment by dgnmst** [comment]
I think It should be on Migration Guide.

**Comment by rwinch** [comment]
@mesutdogan Thanks for the feedback. We will be sure to include information on the migration guide.
