### ISSUE TITLE
how to test many action in MockMvc？

### ISSUE THREAD

**Issue by penghaozhong** [spring-projects/spring-security#3774]
hi ，i have a silly question！how to test many action in MockMvc？
i make a MockMvc test in junit。
eg：
mvc.perform(post("/login").param("username", "15812345678").param("password", "e10adc3949ba59abbe56e057f20f883e"))
        .andDo(print())
        .andExpect(MockMvcResultMatchers.redirectedUrl("/api/loanProgress/accept"));

i want to setting params in /api/loanProgress/accept action ，but i don't how to setting？
please help me， thx

**Comment by rwinch** [comment]
I'm sorry I don't understand your question. Can you please rephrase it?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
