### ISSUE TITLE
Polish variable names in WithSecurityContextTestExecutionListener

### ISSUE THREAD

**Issue by sbrannen** [spring-projects/spring-security#3775]
## Status Quo

Presumably due to copy-n-paste, variables of type `WithSecurityContext` within `WithSecurityContextTestExecutionListener` are currently named `withUser` instead of `withSecurityContext` in the `createSecurityContext()` and `createFactory()` methods.

## Deliverables

- [ ] Rename `withUser` variables to `withSecurityContext` in `WithSecurityContextTestExecutionListener`.

**Comment by rwinch** [comment]
Thanks for the report @sbrannen! This is now fixed in master!
