### ISSUE TITLE
ExpressionUrlAuthorizationConfigurer has no setRolePrefix() method

### ISSUE THREAD

**Issue by p3consulting** [spring-projects/spring-security#3778]
The `ROLE_` prefix is harcoded in `ExpressionUrlAuthorizationConfigurer `while other Spring classes using this functionality have a way to customize it (e.g. `SecurityContextHolderAwareRequestFilter `and `DefaultWebSecurityExpressionHandler`...)
This makes `ExpressionUrlAuthorizationConfigurer ` "special".
Also a common "owner" of the role prefix should be nice... having to post process beans (instances of `SecurityContextHolderAwareRequestFilter  `and `DefaultWebSecurityExpressionHandler`) just for fixing the role prefix, is kinda dirty hack.

**Comment by rwinch** [comment]
Thanks for the report!

> The `ROLE_` prefix is harcoded in ExpressionUrlAuthorizationConfigurerwhile o

If you do not want the `ROLE_ ` prefix, you can use hasAuthority as indicated in the [javadoc of hasRole](http://docs.spring.io/autorepo/docs/spring-security/4.0.2.RELEASE/apidocs/org/springframework/security/config/annotation/web/configurers/ExpressionUrlAuthorizationConfigurer.AuthorizedUrl.html#hasRole(java.lang.String)).

> Also a common "owner" of the role prefix should be nice... having to post process beans (instances of SecurityContextHolderAwareRequestFilterand DefaultWebSecurityExpressionHandler) just for fixing the role prefix, is kinda dirty hack.

Agreed. There is an issue open for this already. Please see #3701

**Comment by rwinch** [comment]
I'm going to close this as I believe I have addressed everything. Please reopen if something is not clear.
