### ISSUE TITLE
SEC-117: JdbcDaoImpl not properly extensible

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#378]
["Fabio Grassi":https://jira.spring.io/secure/ViewProfile.jspa?name=fabio](Migrated from ["SEC-117":https://jira.spring.io/browse/SEC-117?redirect=false]) said:

While the javadoc for JdbcDaoImpl suggests that it is possible to override the initMappingSqlQueries() if the default strategy for customizing the SQL queries doesn't provide enough flexibility, this is in fact _impossible_ because authoritiesByUsernameMapping and usersByUsernameMapping are declared private while they should be protected.

This as far as I can see prevents using this class against an Oracle database that doesn't support boolean fields.

**Comment by spring-issuemaster** [comment]
This issue duplicates #369
