### ISSUE TITLE
Fix missing # in 23.2.2 Path Variables in Web Security Expressions

### ISSUE THREAD

**Issue by ksokol** [spring-projects/spring-security#3781]
Spring Expression Language (SpEL) - [8.5.11 Variables](http://docs.spring.io/spring/docs/4.1.9.RELEASE/spring-framework-reference/htmlsingle/#expressions-ref-variables):

> Variables can be referenced in the expression using the syntax `#variableName`

Leading `#` has been left out in code example in [23.2.2 Path Variables in Web Security Expressions. ](http://docs.spring.io/spring-security/site/docs/4.1.0.BUILD-SNAPSHOT/reference/htmlsingle/#el-access-web-path-variables)

**Comment by rwinch** [comment]
Thanks for the report and the PR! This is now fixed in master via 9c3db557ddd3b2927da071d196a3ba5e67879e54

**Comment by Souchong** [comment]
Hello,
Thank you for this update. I think there is another correction : 
".authorizeUrls()" shouldn't it be replace with ".authorizeRequests()" in code example in 23.2.2 Path Variables in Web Security Expressions ?

I add the code of this example in my application but I have a problem. 
When "checkUserId(Authentication authentication, String userid)" is called, userid is always null.  
Here is my code : 
Access control : 
`        @Override
    protected void configure(HttpSecurity http) throws Exception {
[...]
http
        	.authorizeRequests()
.antMatchers("/{userid}/homes").access("@webSecurity.checkUserId(authentication,#userid)")
[...]
}
[...]
    @Bean
    public WebSecurity webSecurity() {
        return new WebSecurity();
    }  
`

`public class WebSecurity {
	public boolean checkUserId(Authentication authentication, String userid) {
		String uname = authentication.getName();
		return uname.equals(userid);
	}
}`
Any idea ? I pass one day to debug in spring core and spring security...but I do not find where is the problem.

Any help is welcome

**Comment by rwinch** [comment]
@Souchong Thanks for the feedback!

> ".authorizeUrls()" shouldn't it be replace with ".authorizeRequests()" in code example in 23.2.2 Path Variables in Web Security Expressions ?

Good catch! I created #3875 to track this

> I add the code of this example in my application but I have a problem. 
> When "checkUserId(Authentication authentication, String userid)" is called, userid is always null.

Hmm..this is strange because we have [a test that verifies this works](https://github.com/spring-projects/spring-security/blob/4.1.0.RELEASE/config/src/test/java/org/springframework/security/config/annotation/web/configurers/AuthorizeRequestsTests.java#L111). I even [added an additional test](https://github.com/rwinch/spring-security/commit/c88acec39a5d8c95b20c39daeeb9f78aedfeeebc) that is pretty much an exact copy of your example in my branch which passes.

What does the HTTP request path look like? What is the context root? What version of Spring Security are you using? Are you using any BeanPostProcessors? Are you using Boot (if so what version)?

It might be helpful for you to provide a complete example to reproduce this. Once I can reproduce it, we will look into getting a fix.

**Comment by Souchong** [comment]
Hmmmm...I look at the test, I am probably the only error :) ! 
I'm going to build a new project from zero and test it again before annoying you.

**Comment by Souchong** [comment]
Solved !

I used spring-security version 4.0.4.CI-SNAPSHOT. My error...

Thank you again for your time !

**Comment by puresprout** [comment]
If you are using spring-boot-starter-security, get to depends on spring-security 4.0.4
compile("org.springframework.boot:spring-boot-starter-security")

So, You should add following line
compile 'org.springframework.security:spring-security-web:4.1.1.RELEASE'

Use lately spring-security version.

**Comment by aaadipop** [comment]
I have a question ... 

we can get this work?

`.antMatchers("/user/{userId}/**").hasAnyRole("USER_#userId").`

where USER_#userId is a role set at register (ex. ROLE_USER_10)

**Comment by rwinch** [comment]
Try

hasAnyRole("'USER_' + #userId")

**Comment by rwinch** [comment]
PS keep in mind that hasAnyRole automatically prefixes ROLE_

If you don't want the automatic prefix use hasAnyAuthority

**Comment by aaadipop** [comment]
i try to put on the authorities list only the #userId (ROLE_#userId) and in hasAnyRole("#userId") but doesn't work ... 

anyway #730 worked for me 

thanks for your time :)
