### ISSUE TITLE
SimpleUrlAuthenticationFailureHandler does not set WWW-Authenticate Header

### ISSUE THREAD

**Issue by lanoxx** [spring-projects/spring-security#3789]
Hi Spring Security Devs,

I have been using Spring security for a while but only recently started to look at this repository, so I am not sure if this is the right place to report my problem.

I noticed that the class `SimpleUrlAuthenticationFailureHandler` does not set the `WWW-Authenticate` header when its returning HTTP status code 401 in its `onAuthenticationFailure` method. AFAIK this is required by the HTTP standard, so I was wondering if this is an oversight or if there is a particular reason for this? If there exists a reason then maybe it should be documented?

    if (defaultFailureUrl == null) {
        logger.debug("No failure URL set, sending 401 Unauthorized error");
        response.sendError(HttpServletResponse.SC_UNAUTHORIZED,
            "Authentication Failed: " + exception.getMessage());
    }

Other classes such as the `BasicAuthenticationEntryPoint` correctly set this header. Looking forward for your reply.

Cheers
Sebastian

**Comment by rwinch** [comment]
@lanoxx There is a distinction between the HTTP status code and the header itself. The status code simply means you are denied access. If the header is present it means you need to authenticate with HTTP Basic. The `SimpleUrlAuthenticationFailureHandler` is used in instances where you might not be leveraging HTTP Basic.

**Comment by rwinch** [comment]
I'm closing this as resolved. Please feel free to reopen if you feel it is necessary

**Comment by lanoxx** [comment]
Hi,

I just looked this up in the HTTP specification (see https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.47

>The WWW-Authenticate response-header field MUST be included in 401 (Unauthorized) response 
>messages. 

So if I am not mistaken, then not sending the WWW-Authenticate header does not conform to the HTTP specification. Do you still agree?

I guess that If you are not using Basic authentication then the challenge that is contained in the `WWW-Authenticate` header should probably declare the respective authentication method to be used by the browser, such as `WWW-Authenticate=Form-based` or `WWW-Authenticate=MyCustomAuthenticationMethod`.

**Comment by lanoxx** [comment]
@rwinch Do you see my reply?

**Comment by rwinch** [comment]
@lanoxx If you have a `WWW-Authenticate` header it must be in a HTTP 401. However, that does not mean that every 401 needs the `WWW-Authenticate` header.

**Comment by lanoxx** [comment]
@rwinch I still believe you are mistaken. Please take a look at this additional quote:

> 10.4.2 401 Unauthorized

>The request requires user authentication. **The response MUST include a WWW-Authenticate header field (section 14.47) containing a challenge applicable to the requested resource**. The client MAY repeat the request with a suitable Authorization header field (section 14.8). If the request already included Authorization credentials, then the 401 response indicates that authorization has been refused for those credentials. If the 401 response contains the same challenge as the prior response, and the user agent has already attempted authentication at least once, then the user SHOULD be presented the entity that was given in the response, since that entity might include relevant diagnostic information. HTTP access authentication is explained in "HTTP Authentication: Basic and Digest Access Authentication" [43]. 

Source: [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html)
Also take a look at this [SO question](http://stackoverflow.com/questions/17687876/authorization-in-restful-http-api-401-www-authenticate?rq=1).

Thinking about it, that kind of makes sense, when the server returns a 401 code, then it should tell the browser what options there are to authenticate. Does the server require HTTP Basic auth? Maybe it needs NTLM credentials? Or a custom form-based method? Not sending the `WWW-Authenticate` header means that you implicitly assume that the application knows how to authenticate with the server, which may not be the case.

In any case, if the HTTP specification requires the header to be present then I think Spring security should conform to that, or not?
