### ISSUE TITLE
Allow configuration of InvalidSessionStrategy on SessionManagementConfigurer

### ISSUE THREAD

**Issue by mdeinum** [spring-projects/spring-security#3794]
Currently the `SessionManagementConfigurer` allows for setting an `invalidSessionUrl` to be redirected to when the session is detected as invalid. However we would not like to send a redirect but instead send a custom status code.

Currently I would have to create an `ObjectPostProcessor` which overrides or sets the configured `InvalidSessionStrategy`.

**Comment by rwinch** [comment]
@mdeinum Thanks for the issue. Any chance you would be interested in creating a PR?

**Comment by mdeinum** [comment]
@rwinch I'll see what I can come up with.

**Comment by rwinch** [comment]
Thanks!
