### ISSUE TITLE
DefaultMessageSecurityExpressionHandler - SpEL beanResolver is null

### ISSUE THREAD

**Issue by zyro23** [spring-projects/spring-security#3797]
### Summary

looks like by default, `DefaultMessageSecurityExpressionHandler` is not defined as bean and so `ApplicationContextAware` is not applied resulting in the SpEL `beanResolver` being null

### Actual Behavior

using an expression like `@myService.isAllowed(message)` as a messaging security expression, the bean resolution fails because there is no `beanResolver` configured for the expression context

### Expected Behavior

bean resolution should work just like with spring-security-web

### Configuration

some arbitrary `AbstractSecurityWebSocketMessageBrokerConfigurer` impl.

### Version

spring-security-4.0.3

### Workaround

as the autowiring infrastructure for a custom `SecurityExpressionHandler<Message<Object>>` is already available, just defining a `DefaultMessageSecurityExpressionHandler` as a bean "fixes" the issue, e.g.
```java
@Bean
public DefaultMessageSecurityExpressionHandler<Object> messageExpressionHandler() {
	return new DefaultMessageSecurityExpressionHandler<Object>();
}
```

**Comment by rwinch** [comment]
@zyro23 Thanks for the report! I am unable to reproduce this problem. By default the ApplicationContext on `defaultMethodExpressionHandler` will be initialized when the [`ObjectPostProcessor` is autowired](https://github.com/spring-projects/spring-security/blob/4.0.4.RELEASE/config/src/main/java/org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.java#L339).

I have have [pushed a branch](https://github.com/spring-projects/spring-security/pull/3815) that [demonstrates using bean expressions](https://github.com/spring-projects/spring-security/pull/3815/files) is working.

When using `EnableGlobalMethodSecurity` the `ObjectPostProcessorConfiguration` is imported, so this should work. Are you for some reason providing a different `ObjectPostProcessor` which is not populating the `ApplicationContext`?

**Comment by zyro23** [comment]
uhhm yes, grails spring-security-core plugin in fact. so no spring-security java config (except for the messaging part). and currently only for inbound channel security, so no method-level security reg. the messaging.

i will try to add `EnableGlobalMethodSecurity`, check if that works and provide feedback here.

n.b.: as i got already another "workaround" in place by defining a `DefaultMethodExpressionHandler` bean so that `ApplicationContextAware` gets processed, feel free to push the target milestone if this one is blocking a release.

**Comment by rwinch** [comment]
@zyro23 You could also try importing `ObjectPostProcessorConfiguration`

**Comment by rwinch** [comment]
I'm going to remove this from the release as it appears to be working. I'm also going to merge the test (for good measure)

**Comment by zyro23** [comment]
so just tested with `EnableGlobalMethodSecurity` but i think we are talking about two different things here?

the `ObjectPostProcessorConfiguration` registers a `DefaultMethodSecurityExpressionHandler` that gets correctly post-processed (`beanResolver` is set).

however, i am talking about the `DefaultMessageSecurityExpressionHandler` that is used to evaluate the messaging channel security expressions, e.g. (hope u dont mind the groovy code):

```groovy
@Override
protected void configureInbound(MessageSecurityMetadataSourceRegistry messages) {
    messages
        .nullDestMatcher()
            .authenticated()
        .simpSubscribeDestMatchers("/topic/foo")
            .access("""
                hasAnyRole('FOO')
                && @webSocketSecurityService.isTopicAllowed(message)
            """)
        .anyMessage()
            .denyAll()
}
```

and it seems that `expressionHandler` is not post-processed by default (ref. original issue description), unless (currently) manually defined as a spring bean so that `ApplicationContextAware` is triggered..

hope i got this right & it makes sense to you?

**Comment by rwinch** [comment]
@zyro23 Thanks for the updated information and setting me straight on what the problem was. I have created a pull request for the fix. See #3820

**Comment by zyro23** [comment]
thank you for another just-in-time fix :)
