### ISSUE TITLE
What's new in 4.1 RC2

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#3830]

**Comment by pcornelissen** [comment]
The RC1 and RC2 bugfix links lead to an empty list as the filter is "is:open milestone:"4.1.0 RC1" (RC2 has of course the filter at RC2) I assume that you want to show the closed bugs ;-)

**Comment by jgrandja** [comment]
Thank you so much for catching this!

Would you be interested in either creating an Issue or a PR for this?

If you're interested in creating a PR I can guide you on the document to change and the links to update.
