### ISSUE TITLE
More intuitive defaults for AntPathRequestMatcher

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#3831]
We should clean up how `AntPathRequestMatcher` works to provide a more predictable behavior

* We should ensure we disable trimming the path segments. It is not intuitive that trailing slashes within path segments are trimmed
* We should make paths case sensitive. It is not intuitive that a pattern with no wildcards is case insensitive.

**Comment by gdubya** [comment]
PS The spring-security documentation appears to be out of date: https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/

> As mentioned above, the default strategy is to use Ant-style paths for matching and this is likely to be the best choice for most users. The strategy is implemented in the class AntPathRequestMatcher which uses Spring’s AntPathMatcher to perform a **case-insensitive match** of the pattern against the concatenated servletPath and pathInfo, ignoring the queryString.
