### ISSUE TITLE
WithSecurityContextTestExecutionListener supports generic Annotation

### ISSUE THREAD

**Issue by jgoldhammer** [spring-projects/spring-security#3837]
### Summary

After using the newest Spring Security test library Spring Security 4 Snapshot, our own WithSecurityContextFactory does not work anymore as expected. 

### Actual Behavior

Our own XXXTestUserSecurityContextFactory (see below for code) does not receive the argument from the WithSecurityContextTestExecutionListener which calls the factory with the annotation 

```
@SuppressWarnings({ "rawtypes", "unchecked" })
	private SecurityContext createSecurityContext(AnnotatedElement annotated,
			TestContext context) {
		WithSecurityContext withSecurityContext = AnnotationUtils.findAnnotation(
				annotated, WithSecurityContext.class);
		if (withSecurityContext != null) {
			WithSecurityContextFactory factory = createFactory(withSecurityContext, context);
			Class<? extends Annotation> type = (Class<? extends Annotation>) GenericTypeResolver.resolveTypeArgument(factory.getClass(), WithSecurityContextFactory.class);
			Annotation annotation  = AnnotationUtils.findAnnotation(annotated, type);
			try {
				return factory.createSecurityContext(annotation);
			}
			catch (RuntimeException e) {
				throw new IllegalStateException(
						"Unable to create SecurityContext using " + annotation, e);
			}
		}
		return null;
	}
```
When call 	--- return factory.createSecurityContext(annotation); --- , the annotation is null, so we don´t get any data in our factory...

### Expected Behavior

Our own factory is called with the annotation TestWithXXX and not a null argument.

### Configuration

-

### Version

Spring Security 4.1 Snapshot

### Sample

The SecurityContextFactory:
```
public class XXXTestUserSecurityContextFactory implements WithSecurityContextFactory<Annotation> {

	public SecurityContext createSecurityContext(Annotation customUserLikeAnnotation) {
		SecurityContext context = SecurityContextHolder.createEmptyContext();
		String username = (String) ReflectionTestUtils.invokeMethod(customUserLikeAnnotation, "username");
// some more code!!!
               return context;
       }
}
```

One of our annotations for testing with different users:
```
@Retention(RetentionPolicy.RUNTIME)
@WithSecurityContext(factory = XXXTestUserSecurityContextFactory.class)
public @interface TestWithXXX{
	
	/**
	 * The username to be used. The default is rob
	 * @return
	 */
	String username() default "testUser";
}
```

Our junit-class

```
@TestWithXXX
@SpringApplicationConfiguration(classes = XxxApplication.class)
@WebIntegrationTest(randomPort = true)
@TestExecutionListeners(listeners={ServletTestExecutionListener.class,
        DependencyInjectionTestExecutionListener.class,
        WithSecurityContextTestExecutionListener.class})
@ActiveProfiles(profiles = {"fast", "local-dev"})
public class XxxTest{

    @Test
    public void testxxx() throws Exception {

    }
```

### Stacktrace

```
Caused by: java.lang.IllegalArgumentException: Target object must not be null
	at org.springframework.util.Assert.notNull(Assert.java:115)
	at org.springframework.test.util.ReflectionTestUtils.invokeMethod(ReflectionTestUtils.java:391)
	at xxx.CsfTestUserSecurityContextFactory.createSecurityContext(CsfTestUserSecurityContextFactory.java:56)
	at org.springframework.security.test.context.support.WithSecurityContextTestExecutionListener.createSecurityContext(WithSecurityContextTestExecutionListener.java:76)
	... 24 more
```

**Comment by jgrandja** [comment]
Hi @jgoldhammer. Thanks for reporting this.
Would it be possible to provide me a sample application that reproduces this error?
In the meantime, I will try to reproduce with the sample code you provided.
Thanks.

**Comment by jgrandja** [comment]
This issue can be solved
```
public class XXXTestUserSecurityContextFactory implements WithSecurityContextFactory<Annotation> {

    public SecurityContext createSecurityContext(Annotation customUserLikeAnnotation) {
        SecurityContext context = SecurityContextHolder.createEmptyContext();
        String username = (String) ReflectionTestUtils.invokeMethod(customUserLikeAnnotation, "username");
// some more code!!!
               return context;
       }
}

```

**Comment by jgrandja** [comment]
@jgoldhammer Did you get a chance to try out the proposed change? Please let me know as I would like to close out this issue. Thanks!

**Comment by jgoldhammer** [comment]
Hi @jgrandja , 
thanks for the pointer. It just works as you have described. But it is not what I have been looking for...

Background:
I have many rolebased annotations with should be used in our code base. I want to simplify usage in test cases, so the name of the annotation itself describes the role very good and I don´t want that other developers have to handle annotation parameters...

Using the annotation itself I have to write N WithSecurityContextFactories with the same implementation, but with different annotations as parameter.

@TestWithRoleXY - createSecurityContext(TestWithRoleXY customUserLikeAnnotation) {
@TestWithRoleYZ- createSecurityContext(TestWithRoleYZ customUserLikeAnnotation) {

The implementation is the same because I am using Reflection to read the annotation parameters and the annotation parameters are the same for all annotations...

This leads to more code (easy code) and I only want to say that it was easier before...
This ticket can be closed if the previous behaviour will not be reverted... 
I saw some changes by @rwinch in the classes which processes the WithSecurityContextFactories, so maybe you know more, Rob?

Thanks,
Jens

**Comment by rwinch** [comment]
Thanks for the report @jgoldhammer! This is a regression, so we need to find a way to get this to work again.
