### ISSUE TITLE
"What's new in 4.1 RC2" links point to open issues

### ISSUE THREAD

**Issue by pcornelissen** [spring-projects/spring-security#3838]
The links in the document at http://docs.spring.io/spring-security/site/docs/4.1.0.RC2/reference/htmlsingle/#new point to the list of open issues not the closed ones.

**Comment by pcornelissen** [comment]
Sorry took me a while longer to create the PR I was a little bit confused about the change at the bottom of the document, so I dropped edf576c recreated the commit. But it turns out this is just a line feed at the end, which was introduced by the github editor and later by nano on my machine in the second try as well...

**Comment by jgrandja** [comment]
Thanks for the PR! Appreciate that. This is now merged.
