### ISSUE TITLE
Pre-Authentication Filter does not call Failure Handler if Principal is null

### ISSUE THREAD

**Issue by KyleMoser** [spring-projects/spring-security#3851]
### Summary

I am using a recently developed Spring Security feature (4.1.0.RC2) which allows you to use X509 pre-authentication with a failure handler (called 'authenticationFailureHandler' in the X509AuthenticationFilter). I've defined protected resources as being under /protected/** and I've turned off anonymous authentication. If the X509AuthenticationFilter.getPreAuthenticatedPrincipal() returns null, the Spring Security framework unexpectedly allows the user to access protected resources.  

### Actual Behavior

X509AuthenticationFilter.getPreAuthenticatedPrincipal() is returning null (for testing, I've forced this behavior with my debugger) and there is no authentication object in the Spring SecurityContextHolder.getContext().getAuthentication(). This is expected. However, Spring Security is allowing me to access resources that are supposed to be inaccessible to unauthenticated users. 

### Expected Behavior

All resources under the URL pattern "/protected/..." should be protected and should forward me to the error.jsp page.

### Configuration

```
<security:http auto-config="false" pattern="/protected/**" access-decision-manager-ref="..." entry-point-ref="http403EntryPoint">
        <security:anonymous enabled="false"/>
        <security:custom-filter ref="authFilter" position="PRE_AUTH_FILTER" />
</security:http>

<bean id="failureHandler" class="...">
	<property name="useForward" value="true" /> 
	<property name="defaultFailureUrl" value="error.jsp"/>
</bean>	

<bean id="authFilter" class="CustomX509AuthenticationFilter">
	<property name="authenticationManager" ref="authenticationManager" />
	<property name="authenticationFailureHandler" ref="failureHandler"/>
</bean>

<security:authentication-manager alias="authenticationManager">
		    <security:authentication-provider ref="authenticationProvider" />
</security:authentication-manager>
		
<bean id="authenticationProvider" class="... implements AuthenticationProvider" />
```

Note that I am using an "AuthenticationProvider" not a "PreAuthenticatedAuthenticationProvider". 

### Version

4.1 RC2

**Comment by KyleMoser** [comment]
Note: I updated the bug report; previously I thought the bad behavior is only caused if an Exception is thrown by the pre authentication filter, but in fact, any time the filter returns 'null' for the principal, the framework unexpectedly allows access to struts URLs.

**Comment by KyleMoser** [comment]
Suggested fix in the AbstractPreAuthenticatedProcessingFilter:

 ```
private void doAuthenticate(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
		Authentication authResult;

		try {
                   Object principal = getPreAuthenticatedPrincipal(request);
		   Object credentials = getPreAuthenticatedCredentials(request);

		   if (principal == null) {
			if (logger.isDebugEnabled()) {
				logger.debug("No pre-authenticated principal found in request");
			}
                       
                       //this ensures backwards compatibility
                       if (authenticationFailureHandler == null) 
                                     return;

			unsuccessfulAuthentication(request, response, new BadCredentialsException("No principal found in request")); //or whatever AuthenticationException is more appropriate
		}

		if (logger.isDebugEnabled()) {
			logger.debug("preAuthenticatedPrincipal = " + principal
					+ ", trying to authenticate");
		}

			PreAuthenticatedAuthenticationToken authRequest = new PreAuthenticatedAuthenticationToken(
					principal, credentials);
			authRequest.setDetails(authenticationDetailsSource.buildDetails(request));
			authResult = authenticationManager.authenticate(authRequest);
			successfulAuthentication(request, response, authResult);
		}
		catch (AuthenticationException failed) {
			unsuccessfulAuthentication(request, response, failed);

			if (!continueFilterChainOnUnsuccessfulAuthentication) {
				throw failed;
			}
		}
	}
```

Alternatively you could add an additional variable such as 'handleFailureOnNullPrincipal' and if that variable is true, then call unsuccessfulAuthentication() when the principal is null.

**Comment by jgrandja** [comment]
@KyleMoser Please change your security xml configuration as follows:

```
	<security:http use-expressions="true" auto-config="false" entry-point-ref="http403EntryPoint">
		<security:intercept-url pattern="/protected/**" access="authenticated"/>
		<security:anonymous enabled="false"/>
		<security:custom-filter ref="authFilter" position="PRE_AUTH_FILTER" />
	</security:http>	

```
This will ensure that any requests to `/protected/**` will require an Authenticated principal in order to gain access to the protected resource.

If your implementation of `AbstractPreAuthenticatedProcessingFilter` (authFilter) is not able to resolve/extract a pre-authenticated Principal from the incoming request, than a 403 status will be returned.

**Comment by rwinch** [comment]
As @jgrandja described, the `AuthenticationFailureHandler` is used for a failed authentication attempt. If `getPreAuthenticatedPrincipal` returns `null` that means no authentication is attempted so it cannot fail.

For your scenario, I'd setup authorization (as @jgrandja described). If you want to handle the authorization failure, you can set an `AccessDeniedHandler` (for events where the user is authenticated and not authorized to access) or an `AuthenticationEntryPoint` (for events where the user is not authenticated, but must be authenticated).

**Comment by rwinch** [comment]
I'm closing this issue as Works as designed. We must keep the separation of authentication and authorization.
