### ISSUE TITLE
mixed "hasAuthority" And "hasRole" up

### ISSUE THREAD

**Issue by phxism** [spring-projects/spring-security#3856]
### Summary

I'm a newcomer,When I try this sample:spring-security\samples\xml\tutorial
the config-file:"applicationContext-security.xml" and Annotations on BankService.post is "hasRole" that makes any operation is denied.
### Actual Behavior

when i logged as supervisor,I can't post money in any account ,the method was annotated with `@PreAuthorize("hasRole('supervisor') or "
            + "hasRole('teller') and (#account.balance + #amount >= -#account.overdraft)")`
### Expected Behavior

when l log as supervisor or teller.I 'll be able to change the account .but get‘Access Denied’
when I change "@PreAuthorize("hasAuthority('supervisor') or (hasAuthority('teller') and (#account.balance + #amount >= -#account.overdraft))")"
it works.So what the difference between hasRole and hasAuthority.
### Configuration

`
<authentication-manager>
        <authentication-provider>
            <password-encoder ref="encoder" />
            <user-service>
                <user name="rod"
password="$2a$10$75pBjapg4Nl8Pzd.3JRnUe7PDJmk9qBGwNEJDAlA3V.dEJxcDKn5O"
                    authorities="supervisor,user,teller" />`
the attribute "authorities" is the “ROLE” description but why hasRole in the annotation  makes no sense ? 

all in the samples 
### Version

4.1.0.RC2
### Sample

[https://github.com/spring-projects/spring-security/tree/master/samples/xml/tutorial](url)

**Comment by rwinch** [comment]
Does the [following part](http://docs.spring.io/spring-security/site/docs/4.1.x/reference/htmlsingle/#el-common-built-in) of the reference help clarify:

> hasRole([role])
>
> Returns true if the current principal has the specified role. By default if the supplied role does not start with 'ROLE_' it will be added. This can be customized by modifying the defaultRolePrefix on DefaultWebSecurityExpressionHandler.

> hasAuthority([authority])
> Returns true if the current principal has the specified authority.

**Comment by mctdi** [comment]
with version 4.0.4 if you write prefix ROLE_, like hasRole("ROLE_ADMIN")
you get error anyway.

**Comment by phxism** [comment]
can i think like that Role is a SET of Authority? In thymeleaf,  sec:authorize="hasRole('ORDER_CREATE')" is equal to  sec:authorize="hasAuthority('ROLE_ORDER_CREATE')" .

**Comment by eleftherias** [comment]
There is another section of the documentation that explains roles and authorities [here](https://docs.spring.io/spring-security/site/docs/5.2.0.RELEASE/reference/htmlsingle/#tech-granted-authority).
