### ISSUE TITLE
CookieCsrfTokenRepository not working properly with AngularJS

### ISSUE THREAD

**Issue by ACHITERS** [spring-projects/spring-security#3867]
Using servlet-api 3.1, cookies generated by CookieCsrfTokenRepository have HttpOnly set to true.
So, AngularJS can't read them and set properly header X-XSRF-TOKEN.

That is configuration like in manual.
````
 <security:http entry-point-ref="authEntryPoint">
       <security:csrf token-repository-ref="csrfTokenRepository"/>
 </security:http>
<bean name="csrfTokenRepository" class="org.springframework.security.web.csrf.CookieCsrfTokenRepository"/>
````

If I first login with custom written csrf-header filter

```
 <security:http entry-point-ref="authEntryPoint">
       <security:csrf token-repository-ref="csrfTokenRepository"/>
       <security:custom-filter ref="csrfHeaderFilter" after="CSRF_FILTER"/>
 </security:http>
<bean name="csrfTokenRepository" class="org.springframework.security.web.csrf.HttpSessionCsrfTokenRepository">
        <property name="headerName" value="X-XSRF-TOKEN"/>
    </bean>
<bean name="csrfHeaderFilter" class="com.test.CsrfHeaderFilter"/>

public class CsrfHeaderFilter extends OncePerRequestFilter {

    private static final String XSRF_TOKEN = "XSRF-TOKEN";
    private static final String PATH = "/";

    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException {
        CsrfToken csrf = (CsrfToken) request.getAttribute(CsrfToken.class.getName());
        if (csrf != null) {
            Cookie cookie = WebUtils.getCookie(request, XSRF_TOKEN);
            String token = csrf.getToken();
            if (cookie == null || token != null && !token.equals(cookie.getValue())) {
                cookie = new Cookie(XSRF_TOKEN, token);
                cookie.setPath(PATH);
                response.addCookie(cookie);
            }
        }
        filterChain.doFilter(request, response);
    }
}
```
and then rebuild and login login with CookieCsrfTokenRepository, all working fine, till cleaning cookies.

Spring Security 4.1.0
Servlet-api 3.1
AngularJS 1.4.10

**Comment by rwinch** [comment]
@ACHITERS Thanks for the report!

This is a documentation issue. See #3865. In short, you need to use

```xml
<bean name="csrfTokenRepository" class="org.springframework.security.web.csrf.CookieCsrfTokenRepository">
    <property cookieHttpOnly="false"/>
</bean>
```

**Comment by ACHITERS** [comment]
Hm, then, in which cases we can use default cookieHttpOnly="true"? Because, as I see it right now, it is needed to implement filter to intercept that cookie, instead of header.

**Comment by rwinch** [comment]
In the case that you set cookieHttpOnly=true is when you are not accessing it via JavaScript. For example, perhaps you have an HTML view that needs to access the CSRF tokens. You can render it using the same mechanisms listed in [Include the CSRF Token](http://docs.spring.io/spring-security/site/docs/4.1.x/reference/htmlsingle/#csrf-include-csrf-token). Then it would be included in your HTTP parameters or headers using the instructions in the reference.

Yes JavaScript can access the cookie, but it is limited scope (i.e. to the pages that have the token vs all the JavaScript within the domain).

NOTE: Checking that the valid CSRF token is present in a cookie does not make the request secure. Instead, you need to extract the token from a header or HTTP parameter and validate that is equal to the value in the cookie. Spring Security will do the validation bit for you. However, you need to ensure your UI provides the token in POST, PUT, DELETE, etc
