### ISSUE TITLE
Digest authentication and CsrfAuthenticationStrategy

### ISSUE THREAD

**Issue by Slmba** [spring-projects/spring-security#3870]
Hello.
I'm using SS for Digest auth in Spring based application:

Spring Core 4.2.5.
Spring MVC 4.2.5.
Spring Security 4.0.4.

Default java configuration, like in spring documentation.
Before every secured request digest require authentication.
CsrfAuthenticationStrategy class sets csrf token to null after every authentication.
So, every secured request change csrf in the repository.
At classic scheme it's works, but at ajax front-end - no. One time the server send page with CSRF, and all ajax requests use it, but after first request csrf is changing.

I think, it's not valid AuthenticationStrategy for Digest.

**Comment by rwinch** [comment]
If you aren't caching the user credentials in session, then you need to change the strategy for CSRF. For example, you can use CookieCsrfTokenRepository.

**Comment by rwinch** [comment]
Closing. If you have additional follow ups please feel free to reopen

**Comment by Slmba** [comment]
I don't understand why you use caching the user credentials in session for digest, it transfers all security on web server dependent sessions.
May be you will add information to the documentation? - http://docs.spring.io/spring-security/site/docs/4.1.0.RELEASE/reference/htmlsingle/#digest-config
For digest there are a very poor information.
