### ISSUE TITLE
userdetails JdbcDaoImpl loadUserByUsername fails when setEnabledAuthorities is false

### ISSUE THREAD

**Issue by sfat** [spring-projects/spring-security#3872]
### Summary

Basically, I am trying to disable authorities to be handled by `org.springframework.security.core.userdetails.jdbc.JdbcDaoImpl`
After I set setEnableAuthorities to false, the JdbcDaoImpl.loadUserByUsername fails with 

`throw new UsernameNotFoundException(
                    messages.getMessage("JdbcDaoImpl.noAuthority",
                            new Object[] {username}, "User {0} has no GrantedAuthority"), username);`

### Actual Behavior

When jdbcDaoImpl.setEnableAuthorities(false);
jdbcDaoImpl.loadUserByUsername throws `UserNameNotFoundException`
when it reaches this part of the method
````
if (dbAuths.size() == 0) {
            logger.debug("User '" + username + "' has no authorities and will be treated as 'not found'");

            throw new UsernameNotFoundException(
                    messages.getMessage("JdbcDaoImpl.noAuthority",
                            new Object[] {username}, "User {0} has no GrantedAuthority"), username);
}
````
### Expected Behavior

The above if should be disabled (wrapped with an `if (enableAuthorities)`) and not throw an exception
### Configuration

```
 <dependency>
            <groupId>org.springframework.security.oauth</groupId>
            <artifactId>spring-security-oauth2</artifactId>
            <version>2.0.7.RELEASE</version>
        </dependency>
```
### Version

3.2.6.RELEASE (Probably any version is affected by this)

P.S.: I haven't dug too deep inside spring security's userdetails to see what implications it has if that check would be wrapped in the `if (enableAuthorities)`.

**Comment by rwinch** [comment]
You either need authorities or groups enabled (either way an authority must be resolved). If you invoke the following:

```
dao.afterPropertiesSet()
```

you will get a `BeanInitializationException` if both are false.

If you don't want either, you can setup a "dummy" authority using something like:

```java
dao.setAuthoritiesByUsernameQuery("select username, 'ROLE_USER' from user where username = ?");
```

**Comment by rwinch** [comment]
I'm closing. If you have follow up questions, please feel free to reopen
