### ISSUE TITLE
Update Spring Security Getting Started Guide documentation

### ISSUE THREAD

**Issue by Mandya-Naveen** [spring-projects/spring-security#3874]
### Summary

In the "GETTING STARTED---Securing a Web Application" (https://spring.io/guides/gs/securing-web/) guide documentation 
1.  @EnableAutoConfiguration is no where used in the program so no need to confuse the user with explaining what that does.

2. @ComponentScan is also not used so no need to mention what it does.

### Actual Behavior

Documentation speaks about @EnableAutoConfiguration and @ComponentScan which is not used in the sample code

### Expected Behavior

Explain why @EnableAutoConfiguration and @ComponentScan are not explicitly used.

**Comment by rwinch** [comment]
@Mandya-Naveen Thanks for the report!

> Documentation speaks about @EnableAutoConfiguration and @ComponentScan which is not used in the sample code. 

The [guide explains](https://spring.io/guides/gs/securing-web/#run_the_app) that `@SpringBootApplication` automatically adds `@EnableAutoConfiguration` and `@ComponentScan`. From the guide:

> `@SpringBootApplication` is a convenience annotation that adds all of the following:
> * ...
> * `@EnableAutoConfiguration` tells Spring Boot to start adding beans based on classpath settings, other beans, and various property settings.
> Normally you would add @EnableWebMvc for a Spring MVC app, but Spring Boot adds it > automatically when it sees spring-webmvc on the classpath. This flags the application as a web application and activates key behaviors such as setting up a DispatcherServlet.
> * `@ComponentScan` tells Spring to look for other components, configurations, and services in the the hello package.

It also explains what the annotations do. I really think this is explained pretty clear. If you disagree, please create a ticket in the correct repository (see below).

# Using spring-guides for reporting issues

I understand it is probably a bit confusing where to create a ticket with so many Spring Projects.

Typically issues for the guides are reported to their respective repositories. You can find the repository link in the guide. For example, this guide's repository is at https://github.com/spring-guides/gs-securing-web and the link can be found by clicking on the GO TO REPO link shown in the image below:

![image](https://cloud.githubusercontent.com/assets/362503/15119223/81322626-15d5-11e6-985e-9440bccb456e.png)

I hope this helps!

**Comment by rwinch** [comment]
Thanks agian for the report. If you still feel like this is an issue please create a ticket at https://github.com/spring-guides/gs-securing-web
