### ISSUE TITLE
spring-security-4.1.xsd not published

### ISSUE THREAD

**Issue by opinali** [spring-projects/spring-security#3880]
http://www.springframework.org/schema/security/spring-security-4.1.xsd => 404

This is a problem for example in the Eclipse IDE (even with STS installed), validation fails because the XSD validator can't load this XSD.

**Comment by rwinch** [comment]
Thanks for the report @opinali! This appeared to be an issue on our side. The problem should not be fixed. Let me know if you have any further issues.

Thanks again!
