### ISSUE TITLE
XSD's are not reachable

### ISSUE THREAD

**Issue by gleniris** [spring-projects/spring-security#3886]
### Summary

My application cannot access http://www.springframework.org/schema/context/spring-context-4.2.xsd

### Actual Behavior

Entering the following address in an address bar shows an error page with a 522 error of the request having timed out

http://www.springframework.org/schema/context/spring-context-4.2.xsd

### Expected Behavior

The xml file should display

**Comment by rwinch** [comment]
Thanks for the report this was an infrastructure problem that appears to be fixed.

**Comment by gleniris** [comment]
Thanks for the comms Rob. Enjoy the rest of the weekend
