### ISSUE TITLE
WithSecurityContextFactory should allow non Annotations

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#3889]
We should allow non-annotations in WithSecurityContextFactory so that users can allow their annotations to implement an interface (and thus handle multiple annotations with the same properties).

**Comment by rwinch** [comment]
Pushing back as this release is focussed on PRs

**Comment by pvliss** [comment]
Hello @rwinch, I would like to take this one

**Comment by ThomasVitale** [comment]
Hi @rwinch, I would be interested in working on this issue

**Comment by rwinch** [comment]
Thanks @ThomasVitale The issue is yours. Please let me know if you need any help and I will do my best to assist you.

**Comment by ThomasVitale** [comment]
Thanks, could you elaborate on the interface you had in mind?

**Comment by rwinch** [comment]
@ThomasVitale The more I think about this, I'm not sure I like the suggestion anymore. First of all it will be a breaking change. Second of all the idea hasn't had any traction since it was logged 3 years ago. Finally, Spring has since added better support for composed annotations which means we don't even need this.

Sorry for not reviewing this before I confirmed you to work on it.

**Comment by ThomasVitale** [comment]
@rwinch No problem, I get it.
