### ISSUE TITLE
duplicated reference to org.springframework.security.authentication.AuthenticationManager in test

### ISSUE THREAD

**Issue by ppazos** [spring-projects/spring-security#3892]
### Summary

Duplicated reference in https://github.com/spring-projects/spring-security/blob/master/config/src/test/groovy/org/springframework/security/config/annotation/authentication/PasswordEncoderConfigurerTests.groovy

**Comment by rwinch** [comment]
Thanks for the report! I'm sorry, but I don't understand. Can you clarify what the problem is?

**Comment by eddumelendez** [comment]
@rwinch `import org.springframework.security.authentication.AuthenticationManager` appears twice. I have submitted a PR to remove all the unused imports.
