### ISSUE TITLE
Create CompositeLogoutHandler

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#3895]
We should create a `CompositeLogoutHandler` which allows for a `List<LogoutHandler>` to be injected into it. The implementation would simply iterate over all the `LogoutHandler` instances. Then we can leverage the `CompositeLogoutHandler` in places like `LogoutFilter, `HttpServlet3RequestFactory`, `SecurityContextHolderAwareRequestFilter`, and `ConcurrentSessionFilter` 

**UPDATE** 

It would look something like:

```java
public final class CompositeLogoutHandler implements LogoutHandler {
     private final List<LogoutHandler> logoutHandlers;

     public CompositeLogoutHandler(LogoutHandler... logoutHandlers) {
          this.logoutHandlers = Arrays.asList(logoutHandlers);
    }

    public void logout(HttpServletRequest request, HttpServletResponse response, Authentication authentication ) { 
        for(LogoutHandler delegate : delegates) {
            delegate.logout(request, response, authentication);
        }
   }
}
```

**Comment by mdeinum** [comment]
Do we want the current API to be backwards compatible? I.e deprecate the respective constructors and setter methods and create a `CompositeLogoutHandler` in there?

**Comment by rwinch** [comment]
Yes. But probably don't even need to deprecate. Just instantiate the
CompositeLogoutHandler in the constructor. Since it accepts var args it's
convenient to keep around.
