### ISSUE TITLE
It's not possible to configure unlimited number of sessions when using xml config / concurrency-control

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-security#3899]
### Summary

I want to use concurrency-control inside xml configuration, mainly to use session registry, without limiting number of sessions. 

`ConcurrentSessionControlAuthenticationStrategy` states in #setMaximumSessions "The default value is 1. Use -1 for unlimited sessions.". 

### Actual Behavior

Cannot configure max-sessions="-1" because value is a positive integer in XSD, parsing fails.

### Expected Behavior

```<concurrency-control max-sessions="-1" />```

Is a valid configuration.

### Version

4.1.0.RELEASE and lower.

**Comment by rwinch** [comment]
Thanks for the PR!

Any reason you can't just skip configuring it all together?

**Comment by michael-simons** [comment]
Hi Rob,
I want to be able to use the session registry and configuring concurrency control is the most convenient way I found. Thanks.

**Comment by rwinch** [comment]
Thanks again for submitting this issue (and the PR). This is resolved via https://github.com/spring-projects/spring-security/pull/3900#issuecomment-231183304

**Comment by michael-simons** [comment]
👍🏻
