### ISSUE TITLE
DataIntegrityViolationException in InMemoryTokenRepositoryImpl

### ISSUE THREAD

**Issue by raggzy** [spring-projects/spring-security#3901]
### Summary
Currently, InMemoryTokenRepositoryImpl throws DataIntegrityViolationException, which is defined in spring-dao module. This is the only place in spring-security-web and spring-security-config which uses this exception. 
Once you try to configure PersistentTokenRepository for rememberMe - you get a classloading issue.
This forces to include unneeded dependency spring-dao to fix classloading issue.

### Expected Behavior
Should throw another exception. Any, for example RememberMeAuthenticationException.

### Version
spring-security-web-4.0.4.RELEASE

### Sample
https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/authentication/rememberme/InMemoryTokenRepositoryImpl.java#L38

**Comment by jgrandja** [comment]
Hi @raggzy. The `org.springframework.dao.DataIntegrityViolationException` is actually defined in **spring-tx** module. All you need to do is include the dependency **org.springframework:spring-tx:4.2.5.RELEASE**.
`InMemoryTokenRepositoryImpl` is a `PersistentTokenRepository` and the security check that happens in  `createNewToken` that results in a thrown `DataIntegrityViolationException` makes sense because there is a _data integrity_ issue when the check is performed on the _series identifier_ in the token.
Hope this makes sense?

**Comment by raggzy** [comment]
Hi @jgrandja,
Thanks for answering.

Yes, I understand i need to include some module. I did it though i don't need it actually.
But don't you find it strange and wrong to be coupled to some other UNNEEDED module ONLY because of an Exception which will never be thrown? 
```
        PersistentTokenBasedRememberMeServices:44
	private PersistentTokenRepository tokenRepository = new InMemoryTokenRepositoryImpl();
```
Basically, it requires JVM to load class InMemoryTokenRepositoryImpl, which contains that exception in imports section.
But then later, in constructor
```
PersistentTokenBasedRememberMeServices:44
	public PersistentTokenBasedRememberMeServices(String key,
			UserDetailsService userDetailsService,
			PersistentTokenRepository tokenRepository) {
		super(key, userDetailsService);
		random = new SecureRandom();
		this.tokenRepository = tokenRepository;
	}
```
`tokenRepository` gets replaced with actual (possibly null) object.

So even if I never use `InMemoryTokenRepositoryImpl` but I use `PersistentTokenBasedRememberMeService` - i need to satisfy the imports. Looks wrong to me.

My opinion about this place - refactor tokenRepostirory to be null by default and replace exception to some from spring-security. 

That's the whole idea behind posting this case. Decoupling code and avoiding unneeded dependencies. Or if it's justified (which I still think is not) - then please add a maven dependency. So it gets automatically imported and causes no confusion.

I can implement it and create pull request, no worries.

**Comment by jgrandja** [comment]
Hi @raggzy. The 2x current implementations of `PersistentTokenRepository` are `JdbcTokenRepositoryImpl` and `InMemoryTokenRepositoryImpl`. The `JdbcTokenRepositoryImpl` may very well throw `DataIntegrityViolationException` in certain scenarios. And we definitely need to be consistent on what exception we throw between all implementations of `PersistentTokenRepository`.

Also, applications deployed in a production environment that leverage a persistent store will depend on the **spring-tx module** inherently. `InMemoryTokenRepositoryImpl` really should only be used for development/testing environments.

Moreover, `DataIntegrityViolationException` indirectly extends from `DataAccessException` which provides a consistent exception hierarchy for all Spring projects. It's used in Spring Security, Spring Data-related sub-projects, etc. 

I appreciate your feedback here but this design is intended.
Thank you.

**Comment by raggzy** [comment]
Sorry if was edgy. My case is datastax-based Cassandra implementation, no spring-tx/spring-data/spring-dao modules because of lack of support and non-transaction nature of Cassandra. Just wanted to point an attention on that tiny confusing place. 
Will not disturb anymore =)
Thanks!

**Comment by rwinch** [comment]
@raggzy

We did not view this as edgy.

Please don't take our response as "do not disturb". In this instance we happen to disagree but this is the nature of software (software is as much of an art as it is a science). We do appreciate the feedback and want to get more from you!

**Please keep providing feedback!**
