### ISSUE TITLE
Partly working autoconfigurer: rememberMe

### ISSUE THREAD

**Issue by mschipperheyn** [spring-projects/spring-security#3908]
I provide a custom rememberMeServices()

I notice that when you use both a custom rememberMeServices and the autoconfigurer it will silently ignore some of the settings you make on the configurer. E.g.

{code}
.rememberMe()
					.key(key)
					.useSecureCookie(secureCookie)
					.tokenValiditySeconds(5*12*30*24*60*60)
					.authenticationSuccessHandler(new RememberMeLoginSuccessHandler("/", "destination", userMgr, messMgr))
					.rememberMeCookieName(REMEMBER_ME_COOKIE)
					.rememberMeParameter("rememberMe")
					.userDetailsService(userMgr)
					.rememberMeServices(rememberMeServices())  
{code}

So, in this case, I'm setting some stuff like rememberMeCookieName, which will not propagate to the rememberServices implementation.

I think it should propagate. We often use partly customized configs. And I should not have to worry that some settings I **explicitly** set don't propagate to the appropriate interface.

OR, if the idea is as it is now and setting custom elements at some locations leads to other settings to be ignored, there should be a warning or better: an error. Because you're trying to set a value that won't be processed.

**Comment by rwinch** [comment]
@mschipperheyn Thanks for the feedback!

Anytime you provide a custom implementation of an API within Spring Security you are responsible for populating any attributes on the custom implementation. The reason for this is that Spring Security is not aware of your implementation and how to map the configuration to your custom API. For example, if your API doesn't have a way to set the cookie name, we cannot map the property to that implementation.

That said we could provide better validation. I created #3909 to address this.

**Comment by rwinch** [comment]
I'm closing this in favor of better error messages in #3909

Please feel free to comment here / reopen if you feel like this is not properly addressed.
