### ISSUE TITLE
HTTP response splitting attack prevention

### ISSUE THREAD

**Issue by tiwatsuka** [spring-projects/spring-security#3910]
### Summary

When a user set http header value containing CR/LF,  the http response is split.
https://www.owasp.org/index.php/HTTP_Response_Splitting

Of course, users should validate the value to avoid this kind of problems.
However, it's worth to provide measures from framework for careless users.

I think HttpFirewall is suitable place to remove CR/LF in header.

### Actual Behavior

HttpHeaders headers = new HttpHeaders();
headers.add("abc", "abc¥r¥nContent-Length:100¥r¥n¥r¥n <http>...");

abc: abc
Content-Length: 100

<http>
...

### Expected Behavior

HttpHeaders headers = new HttpHeaders();
headers.add("abc", "abc¥r¥nContent-Length:100¥r¥n¥r¥n <http>...");

abc: abc Content-Length: 100  <http> ...

**Comment by rwinch** [comment]
Thanks for the report. Can you expand on this issue?

**Comment by tiwatsuka** [comment]
I'm sorry. I accidentally submitted before writing description.

According to my investigation, some application servers remove CR/LF by default. But not all. 
I confirmed that Undertow does not do it.

**Comment by rwinch** [comment]
@tiwatsuka And how are you able to perform response splitting? Is your application allowing user provided input as the value of the HTTP Response headers? Are you finding Spring Security is doing this? Please elaborate.

**Comment by tiwatsuka** [comment]
I assume that some careless developers use user input as value of the headers without validation.
I think that any CR/LF in the value of the HTTP response headers have to be trimmed off. Isn't it nice if Spring Security do it by default?

At  `org.springframework.security.web.firewall.FirewalledResponse#sendRedirect`, the argument is checked whether it does not contain CR/LF.
Similarly, the value of header can be checked at `addHeader` and `setHeader`.

**Comment by rwinch** [comment]
@tiwatsuka Thanks for the response. Thanks for explaining the context (I was trying to determine if this was a new feature or a bug).

This would be nice. Would you be interested in providing a pull request?

**Comment by eddumelendez** [comment]
@rwinch method `addHeader` is part of `OnCommittedResponseWrapper` but `setHeader` is part of `MessageBuilder` which is in `spring-messaging` artifact. Should `MessageBuilder` manage the same behavior?

**Comment by rwinch** [comment]
@eddumelendez As always thanks for responding! I commented on the PR. Let's continue the discussion there

**Comment by glavoie** [comment]
The fix causes a NullPointerException a "null" value is sent to setHeader(). We integrated the fix in our code and we found such cases. The HttpServletResponse documentation doesn't deny null values, but it seems that the behavior is undefined: https://java.net/jira/browse/SERVLET_SPEC-159

**Comment by rwinch** [comment]
@glavoie Thanks for the report! Do you mind creating a PR to fix this?
