### ISSUE TITLE
spring-security 4.1 logout is broken when using httpBasic

### ISSUE THREAD

**Issue by rburgst** [spring-projects/spring-security#3911]
### Summary

after upgrading to spring-security 4.1 logout does no longer work when also allowing httpBasic()

### Actual Behavior

logout does not redirect to the logout success URL but instead sends an empty response with HTTP Status 204.

### Expected Behavior

logout should redirect to the logout success page.

### Configuration

use the provided samples/boot/helloworld example and add `httpBasic()` to the end of the security config 

```java
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {

	// @formatter:off
	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
				.authorizeRequests()
					.antMatchers("/css/**", "/index").permitAll()
					.antMatchers("/user/**").hasRole("USER")
					.and()
				.formLogin().loginPage("/login").failureUrl("/login-error")
				.and()
				.httpBasic();
	}
```
### Version

only started happening with spring - security 4.1

### Sample

default sample spring boot hello world sample.

https://github.com/spring-projects/spring-security/blob/master/samples/boot/helloworld/src/main/java/org/springframework/security/samples/config/SecurityConfig.java

**Comment by rburgst** [comment]
Note that this is also the configuration specified in the standard documentation 
http://docs.spring.io/autorepo/docs/spring-security/4.1.x/reference/htmlsingle/#jc-httpsecurity

**Comment by rwinch** [comment]
@rburgst Thanks for the report! This does look like an issue and is a duplicate of #3902



Which browser are you using? Exactly how do you reproduce?
