### ISSUE TITLE
AlreadyBuiltException: This object has already been built

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#3916]
From https://github.com/spring-projects/spring-security/issues/3825#issuecomment-223795067

I had the same issue.

I was wiring a custom AuthenticationSuccessHandler into my security configuration that indirectly referenced a @Service bean with an @Autowired reference to AuthenticationManager. After some thought, I'm surprised it worked - but no problems at all at runtime! Perhaps some sort of wiring order / race condition helped me out? However, while running the same vacuous test mentioned by @whittle, I encountered the dreaded AlreadyBuiltException.

Note that in a very stripped down version of my application I was debugging this issue with, I did receive a BeanCurrentlyInCreationException on AuthenticationManager but only during testing - not at runtime. Not exactly the same issue, but could be related behavior. See here: https://github.com/davidkey/SecurityTestErrorPOC.

My fix was to add @Lazy to my AuthenticationSuccessHandler in my security configuration while I rethink my architecture a bit.

HTH.

**Comment by Turbots** [comment]
Hey @rwinch as I already mentioned on Gitter, here's my example of the problem, the latest commit is failing while the commit before that works: https://github.com/Turbots/data-jpa-preautorize-sample

**Comment by rwinch** [comment]
@davidkey Thanks for the comment. I'm trying to reproduce this and unable to. Can you provide exact steps for reproducing the issue?

**Comment by rwinch** [comment]
@Turbots Thanks for creating your sample. I was able to reproduce the issue using your sample. I'm going to break this out into a separate issue since I'd like to confirm your case separately.

**Comment by rwinch** [comment]
@Turbots Turns out your issue is very related to #3916 so I am not going to create a specific issue for it. However, I did add a test case to ensure that your problem is resolved.

**Comment by davidkey** [comment]
@rwinch [Here's a gist](https://gist.github.com/davidkey/fd92bc824665aed49730c6b6d7ba1bc3#file-test-sh) with a full dump of what I'm seeing. Oddly, I was NOT able to reproduce the issue on [travis-ci](https://travis-ci.org/davidkey/SecurityTestErrorPOC). 

Going to give it a shot on a seperate (windows) install on the same machine and see if I see the same behavior. Will report back shortly.

**Comment by davidkey** [comment]
Same PC, running Windows 10 (vs Ubuntu 16) and I **do not** experience the issue. Same versions of source code / dependencies / maven / java (if that even makes a difference?). 

Very strange. Perhaps some weird thread / prioritization issue? Let me know if there's anything else you'd like me to try.

**Comment by rwinch** [comment]
@davidkey Thanks for the fast response. Since you can reproduce the issue in a specific spot. I just pushed some fixes into master that may have fixed your issue.

Perhaps the easiest thing would be for you to try running against the latest SNAPSHOT yourself? To do so you have two options:

* Wait until [the build](https://build.spring.io/browse/SEC-B41X-447) completes and add https://repo.spring.io/libs-snapshot to your maven repositories.
* Alternatively, you can clone master and do a "./gradlew install" which will install the code into your local maven repository.

In  your project you can then define a property of:

```xml
<properties>
    <spring-security.version>4.1.1.BUILD-SNAPSHOT</spring-security.version>
</properties>
```

If you could respond that your issue is fixed or not, that would be greatly appreciated! If it is not, we can continue to hunt for the issue.

**Comment by davidkey** [comment]
@rwinch Using the latest SNAPSHOT fixed it! Awesome - thanks!

**Comment by rwinch** [comment]
@davidkey Thanks for the fast report! Given your feedback I'm going to close this as fixed
