### ISSUE TITLE
Merge PR #3705 into 3.2 stream

### ISSUE THREAD

**Issue by tysonite** [spring-projects/spring-security#3922]
Spring Boot still depends on 3.2 stream of Spring Security by default. Changes made in the PR [3705](https://github.com/spring-projects/spring-security/pull/3705) simplify troubleshooting issues with authentication. It would be very nice if those changes are merged back into 3.2 stream.

**Comment by rwinch** [comment]
@tysonite Thanks for the report. 

First we generally reserve changes to 3.2.x for server bugs. Otherwise, we encourage users to update to 4.x.

Second, I'm not sure I understand your comment. Spring Boot uses Spring Security 4.x See https://github.com/spring-projects/spring-boot/issues/5588 and https://github.com/spring-projects/spring-boot/issues/5869

Can you clarify why you think Spring Boot uses Spring Security 3.2.x?

**Comment by tysonite** [comment]
@rwinch I believe that current GA version of Spring Boot is still 1.3.5. And this version depends on Spring Security 3.2. So, most of the users (I may be wrong, but this is my personal view) prefer to use GA version in production, they do not choose "in devel." versions.

Please, feel free to close this report, if it does not satisfy your regular workflow.

**Comment by rwinch** [comment]
@tysonite THanks for the fast response. You are right that the current GA is 1.3.5. If you look at https://github.com/spring-projects/spring-boot/issues/5588 it is fixed in Boot 1.3.4 which means Boot 1.3.5 uses Spring Security 4.0.4.RELEASE

Since Boot already uses Spring Security 4.x I'm closing this issue

**Comment by tysonite** [comment]
@rwinch Thanks, I got it. My mistake, Spring Boot 1.3.5 depends on Spring Security 4.0.4, but not on 3.2 or 4.1. Looks like, it is needed to wait till Spring Boot integrates Spring Security 4.1

**Comment by rwinch** [comment]
@tysonite Right. Which shouldn't be too long. The 1.4 GA is scheduled for July 7th https://github.com/spring-projects/spring-boot/milestones

**Comment by tysonite** [comment]
@rwinch Thank you for the suggestion. But I prefer to wait for GA release in order to avoid unknown (for me) incompatibilities if any.

Also, I want to give you more background about my initial request. My goal was to implement OAuth2 authentication with Google. I spent some time figuring out why it does not work as expected in corporate environment. And finally find out that the root cause was an impossibility of Spring Security OAuth2 to make direct HTTP requests to Google services, because of a corporate Proxy server. It would be much easier to isolate my problem if exception (in PR 3705) was logged.

By the way, do you think it is reasonable to improve Spring Security OAuth2 to work behind proxy server?

**Comment by rwinch** [comment]
> But I prefer to wait for GA release in order to avoid unknown (for me) incompatibilities if any.

Spring Security 4.1.x is tested against Boot 1.3.x too. You should not have any problems. However, feel free to wait till Spring Boot updates.

> By the way, do you think it is reasonable to improve Spring Security OAuth2 to work behind proxy 
> server? (Or is there already some solution in place?)

Spring Boot already provides generic support for `X-Forwarded-*` headers. See [Use behind a front-end proxy server](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-tomcat-behind-a-proxy-server)

As of Spring Framework 4.3.0 you can also use the [ForwardedHeaderFilter](https://github.com/spring-projects/spring-framework/blob/v4.3.0.RELEASE/spring-web/src/main/java/org/springframework/web/filter/ForwardedHeaderFilter.java)

**Comment by tysonite** [comment]
@rwinch Thanks a lot for replies. I appreciate!
