### ISSUE TITLE
ignoring().antMatchers has global effect in case of multiple @EnableWebSecurity Configurations

### ISSUE THREAD

**Issue by mschipperheyn** [spring-projects/spring-security#3923]
I am using multiple @EnableWebSecurity configurations.

     @Override
	public void configure(WebSecurity security){
	    security
	    	.ignoring()
	    		.antMatchers(
	    				"/assets/**", 
	    				"/uploads/**", 
	    				"/robots.txt", 
	    				"/crossdomain.xml", 
	    				"/favicon.ico"
	    				)
	    	;
	}

When I tried to exclude certain patterns from the first configuration that should be handled by the last one, effectively implementing a configure override per configuration, I found that this ant pattern was excluded from all subsequent Configurations. It would seem to be that this should be processed per configuration.

In my case, I use three configurations. a root one and 2 additional configurations that are sub classes of the root configuration (and inside the same file)

**Comment by rwinch** [comment]
`WebSecurity` impacts all of the application, so ignoring is considered global.

If you are configuring a specific slice of the application, use `HttpSecurity`. For example, you can leverage [the sample in the reference](http://docs.spring.io/spring-security/site/docs/4.1.x/reference/htmlsingle/#multiple-httpsecurity):

```java
@EnableWebSecurity
public class MultiHttpSecurityConfig {
	@Autowired
	public void configureGlobal(AuthenticationManagerBuilder auth) { 1
		auth
			.inMemoryAuthentication()
				.withUser("user").password("password").roles("USER").and()
				.withUser("admin").password("password").roles("USER", "ADMIN");
	}

	@Configuration
	@Order(1)                                                        2
	public static class ApiWebSecurityConfigurationAdapter extends WebSecurityConfigurerAdapter {
		protected void configure(HttpSecurity http) throws Exception {
			http
				.antMatcher("/api/**")                               3
				.authorizeRequests()
					.anyRequest().hasRole("ADMIN")
					.and()
				.httpBasic();
		}
	}

	@Configuration                                                   4
	public static class FormLoginWebSecurityConfigurerAdapter extends WebSecurityConfigurerAdapter {

		@Override
		protected void configure(HttpSecurity http) throws Exception {
			http
				.authorizeRequests()
					.anyRequest().authenticated()
					.and()
				.formLogin();
		}
	}
}
```
