### ISSUE TITLE
spring-security.xsd is not at  http://www.springframework.org/schema/security

### ISSUE THREAD

**Issue by afattahi54** [spring-projects/spring-security#3924]
The spring-security.xsd  file at  http://www.springframework.org/schema/security/spring-security.xsd seems not be valid and eclipse shows an error that can not find the file.
Can this be fixed ?!

I am using spring security 4.1.

**Comment by trepel** [comment]
I've just hit the same issue, please upload the default schema (same as latest version). The other Spring projects still have the default schemas.

**Comment by rwinch** [comment]
Thanks for the feedback @afattahi54 and @trepel! This should be resolved now
