### ISSUE TITLE
RememberMeAuthenticationFilter with successHandler

### ISSUE THREAD

**Issue by em2e** [spring-projects/spring-security#3927]
Hi,

I'm using the RememberMeAuthenticationFilter with a configured successHandler. I have realized that after a successfull remember-me authentication the handler was called as expected, but the request processing didn't continue. I got empty result with 200 ok status code. Only headers inside, no content.

My guess this is because chain.doFilter is not beeing called in this case, the method exits earlier by an unnecessary return statement in line 129:

					if (successHandler != null) {
						successHandler.onAuthenticationSuccess(request, response,
								rememberMeAuth);

						return;
					}

I am using spring security 4.0.4

**Comment by rwinch** [comment]
@em2e Thanks for the reply. This is as expected. AuthenticationSuccessHandler is suppose to terminate the flow of the filter.

Is this causing you problems in trying to achieve something more concrete? Note: You can always have the AuthenticationSuccessHandler forward to an endpoint to do additional processing.

**Comment by em2e** [comment]
@rwinch Thank you for your answer. It seems that I misunderstand the purpose of the AuthenticationSuccessHandler. My objective was to do some additional work after the user is succesfully identified, besides not modifying the normal processing of request.

What confuses me with the AuthenticationSuccessHandler handler is the remember-me authentication is happening just by requesting any resource of the application, for example when the user first queries for the main index page. And it is not clear for me why should the success handler block that and do any special thing instead of letting the user got what he requested.

I see AuthenticationSuccessHandler is not my friend, but I found an other way. I am using InteractiveAuthenticationSuccessEvent now, and it works well.

Thanks again and regards!
Zoltán

**Comment by rwinch** [comment]
Thanks for the response @em2e I'm closing this as you found a way to get what you need and `AuthenticationSuccessHandler` is behaving as expected.
