### ISSUE TITLE
sessionAuthenticationStrategy setter in SessionManagementConfigurer doesn't set the right value

### ISSUE THREAD

**Issue by jebeaudet** [spring-projects/spring-security#3928]
### Summary

The method `sessionAuthenticationStrategy(SessionAuthenticationStrategy sessionAuthenticationStrategy)` in `SessionManagementConfigurer` sets the `sessionFixationAuthenticationStrategy` field and not the `sessionAuthenticationStrategy` field. 

### Actual Behavior

There is no way to set the `sessionAuthenticationStrategy` field. I'm pretty sure it's a simple mistake since you have this in the same class : 
```
	private SessionAuthenticationStrategy getSessionAuthenticationStrategy(H http) {
		if (sessionAuthenticationStrategy != null) {
			return sessionAuthenticationStrategy;
		}
[...]
```

### Configuration
```
http.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS).sessionAuthenticationStrategy(new NullAuthenticatedSessionStrategy())
```
### Version

4.0.4

**Comment by rwinch** [comment]
@jebeaudet Thanks for the report. This appears to be a duplicate of #3341. It is quite intentional that this is done for the reason described in https://github.com/spring-projects/spring-security/issues/3341#issuecomment-180607631  You might notice that the Javadoc also states that this is the intended behavior.

Can you elaborate what the problem you are encountering is?

**Comment by jebeaudet** [comment]
I just reread the javadoc and I see your point, I misunderstood the way the code works I think. I was just trying to set a `NullAuthenticatedSessionStrategy` to a `HttpSecurity`, from what I've gathered, setting it with the `sessionAuthenticationStrategy(SessionAuthenticationStrategy sessionAuthenticationStrategy)` should do it right?

**Comment by rwinch** [comment]
@jebeaudet Correct. If it doesn't behave that way, then please do create a ticket.

I'm closing this issue given your last response.

Thanks again for bringing this up and taking the time to make Spring Security better!
