### ISSUE TITLE
Pbkdf2PasswordEncoder output doubled salt....

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [spring-projects/spring-security#3930]
### Summary

it is not really an issue, but it would be great to cut double salt :

now wrong : 18f7e427924f2fa818f7e427924f2fa82d7a6ba29d87816f79da8d9fbd23f3680afae99b44e2ca5cf84b1c0cf12968ac

correct : 18f7e427924f2fa82d7a6ba29d87816f79da8d9fbd23f3680afae99b44e2ca5cf84b1c0cf12968ac

as you can see 18f7e427924f2fa8 doubled...

thanks a lot for spring!
### Version
spring boot 1.3.5.RELEASE

### Sample

 System.out.println(new Pbkdf2PasswordEncoder("",1024,256).encode("user"));

**Comment by rwinch** [comment]
Thanks for the report! This is indeed a bug. I have pushed a fix for this. User's that leveraged 4.1.0 version of `Pbkdf2PasswordEncoder` will need to migrate their data using:

```java
final int saltLength = KeyGenerators.secureRandom().getKeyLength();
String encodedPassword = "ab1146a8458d4ce4e65789e5a3f60e423373cfa10b01abd23739e5ae2fdc37f8e9ede4ae6da65264";
String originalEncodedPassword = "ab1146a8458d4ce4ab1146a8458d4ce4e65789e5a3f60e423373cfa10b01abd23739e5ae2fdc37f8e9ede4ae6da65264";
byte[] originalBytes = Hex.decode(originalEncodedPassword);
byte[] fixedBytes = Arrays.copyOfRange(originalBytes, saltLength,
		originalBytes.length);
String fixedHex = String.valueOf(Hex.encode(fixedBytes));

assertThat(fixedHex).isEqualTo(encodedPassword);
```
