### ISSUE TITLE
/logout reports status 204 - no content.

### ISSUE THREAD

**Issue by Naros** [spring-projects/spring-security#3936]
### Summary
After upgrading from 4.0.4.RELEASE to 4.1.0.RELEASE, the application no longer redirects the user to the configured logout success url.

### Actual Behavior
Application posts a request to `/logout` and the browser reports the response is a status 204 - No content.

### Expected Behavior
Application posts a request to `/logout` and the browser should be redirected to the configured logout success URL.

### Configuration
    @Configuration
    @EnableWebSecurity
    public class WebSecurity extends WebSecurityConfigurerAdapter {
      @Override
      protected void configure(HttpSecurity http)
      throws Exception {
        http 
         /* configure other settings */
    	.logout()
    	.logoutRequestMatcher( new AntPathRequestMatcher( "/logout" ) )
    	.logoutSuccessUrl( "/sessionEnded.action" )
    	.invalidateHttpSession( true )
    	.deleteCookies( "JSESSIONID" );
      }
    }

### Version
4.1.0.RELEASE

**Comment by eddumelendez** [comment]
@Naros this was a bug. You can read more about it in #3902. It should be fixed now in master.

**Comment by rwinch** [comment]
Thanks for responding @eddumelendez!

@Naros As @eddumelendez mentioned this is a bug that was fixed in master. Please give the latest in master a try.
