### ISSUE TITLE
Add security via role on url.

### ISSUE THREAD

**Issue by mctdi** [spring-projects/spring-security#3942]
### Summary

I try to add security on url via role.

### Actual Behavior

Any role can access report url

### Expected Behavior

Only admin role can access report url.

### Configuration

In a class (don't have any annotation on it) who extends WebSecurityConfigurerAdapter

```
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests().antMatchers("/rest/**").authenticated();
        http.authorizeRequests().antMatchers("/rest/report/**").hasRole("ADMIN");
        http.csrf().disable();
        http.exceptionHandling().authenticationEntryPoint(authenticationEntryPoint);
        http.formLogin().successHandler(authenticationSuccessHandler);
        http.formLogin().failureHandler(authenticationFailureHandler);
        http.logout().logoutUrl("/logout");
        http.logout().logoutSuccessUrl("/");
   }
  ...
```

```
public enum RoleEnum {
    ADMIN, USER;
}

```
I have a class UserApp who have RoleEnum attribute.

```
public class CustomUserDetails implements UserDetails {
   ...
   @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        Collection<GrantedAuthority> authorities = new ArrayList<>();
        RoleEnum userRole = this.userApp.getRole();

        if (userRole != null) {
            SimpleGrantedAuthority authority = new SimpleGrantedAuthority(userRole.name());
            authorities.add(authority);
        }
        return authorities;
    }
}

public class UserServiceImpl implements UserDetailsService, UserService {
    ...
    @Override
    public UserDetails loadUserByUsername(String userName) throws UsernameNotFoundException {

        UserApp userapp = repository.findByUsername(userName);

        if (userapp == null) {
            throw new UsernameNotFoundException("Username " + userName + " not found");
        }

        return new CustomUserDetails(userapp);
    }
}

```
### Version

spring boot 1.3.5
spring security 4.0.4

**Comment by rwinch** [comment]
@mctdi Thanks for the report! Can you provide the debug logs?

You mention (emphasis mine)

> In a class **(don't have any annotation on it)** who extends WebSecurityConfigurerAdapter

You need to have an annotation (i.e. `@Configuration`) on it for it to be picked up. Can you provide the entire class?

**Comment by mctdi** [comment]
```
public class GymApplicationSecurity extends WebSecurityConfigurerAdapter {

    @Autowired
    private RESTAuthenticationEntryPoint authenticationEntryPoint;

    @Autowired
    private RESTAuthenticationFailureHandler authenticationFailureHandler;

    @Autowired
    private RESTAuthenticationSuccessHandler authenticationSuccessHandler;

    @Autowired
    private UserDetailsService userDetailsService;

    @Override
    protected void configure(AuthenticationManagerBuilder auth) throws Exception {
        auth.userDetailsService(userDetailsService);
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {
	

        http.authorizeRequests().antMatchers("/rest/**").authenticated();
        http.authorizeRequests().antMatchers("/rest/report/**").hasRole("ADMIN");
        http.csrf().disable();
        http.exceptionHandling().authenticationEntryPoint(authenticationEntryPoint);
        http.formLogin().successHandler(authenticationSuccessHandler);
        http.formLogin().failureHandler(authenticationFailureHandler);
        http.logout().logoutUrl("/logout");
        http.logout().logoutSuccessUrl("/");
    }

}
```

if i put @Configuration i get this error

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration': Injection of autowired dependencies failed; nested exception is java.lang.IllegalStateException: @Order on WebSecurityConfigurers must be unique. Order of 100 was already used, so it cannot be used on com.test.ApplicationSecurity@38b0ca8c too.

i tried to put 
@Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)

but it get same result

My main class look like this
```
@EntityScan(basePackageClasses = {Application.class, Jsr310JpaConverters.class})
@SpringBootApplication
@EnableCaching
@EnableScheduling
public classApplication {
...
   @Bean
    public WebSecurityConfigurerAdapter webSecurityConfigurerAdapter() {
        return new ApplicationSecurity();
    }
}
```

**Comment by rwinch** [comment]
What does `ApplicationSecurity` look like?

**Comment by mctdi** [comment]
i updated... code

**Comment by rwinch** [comment]
Remove 

```
@Bean
    public WebSecurityConfigurerAdapter webSecurityConfigurerAdapter() {
        return new ApplicationSecurity();
    }
```

because `@Configuration` will be picked up automatically.

**Comment by mctdi** [comment]
ok that boot

my user has role USER and can access

rest/report/members

i should not have access to it

**Comment by rwinch** [comment]
Please post the debug logs. Also ensure you aren't sending and HTTP Basic header (i.e. close your browser and open it up again)

**Comment by mctdi** [comment]
i post the log here: [](http://pastebin.com/iwNHz2ca)

**Comment by rwinch** [comment]
I need just the logs from when you make the request from the user that is role USER and should not be allowed to access the rest/report/members URL

**Comment by mctdi** [comment]
only get the sql code...

select
        count(member0_.member_id) as col_0_0_ 
    from
        member member0_
Hibernate: 
    select
        member0_.member_id as member_i1_5_,
        member0_.address as address2_5_,
        member0_.birthdate as birthdat3_5_,
        member0_.city_cityId as city_ci13_5_,
        member0_.commerce_commerceId as commerc14_5_,
        member0_.email as email4_5_,
        member0_.emergency_contact_name as emergenc5_5_,
        member0_.emergency_phone as emergenc6_5_,
        member0_.man as man7_5_,
        member0_.name as name8_5_,
        member0_.payment_gateway_key as payment_9_5_,
        member0_.phone1 as phone10_5_,
        member0_.phone2 as phone11_5_,
        member0_.postal_code as postal_12_5_ 
    from
        member member0_ limit ?
Hibernate: 
    select
        city0_.city_id as city_id1_0_0_,
        city0_.city as city2_0_0_ 
    from
        city city0_ 
    where
        city0_.city_id=?

**Comment by rwinch** [comment]
I see your issue. Spring Security considers your authorization rules in the order you specify them. So this:

```java
http.authorizeRequests().antMatchers("/rest/**").authenticated();
http.authorizeRequests().antMatchers("/rest/report/**").hasRole("ADMIN");
```

means that it first checks to see if the request starts with `/rest/``. The URL `/rest/report/members` does start with `/rest/` so the rule is the user must be authenticated. It stops there without processing any additional rules.

To fix it you can switch the ordering to have the least specific rule last. For example:

```java
http.authorizeRequests().antMatchers("/rest/report/**").hasRole("ADMIN");
http.authorizeRequests().antMatchers("/rest/**").authenticated();
```

The URL `/rest/report/members` will now match on the `hasRole("ADMIN")` rule.

**Comment by rwinch** [comment]
Given the last comment I'm closing. Please re-open if you continue to have problems

**Comment by mctdi** [comment]
thanks, solved.

**Comment by mctdi** [comment]
little question 

i have a url: 

> "/rest/users/{userId}/update/password"

because 

`http.authorizeRequests().antMatchers(HttpMethod.GET, "/rest/users/*/update/password").hasRole("USER");`

is not secure i think, any user can update the password of any other user

is it possible with the authorizeRequest or @PreAuthorize is mandatory?

**Comment by rwinch** [comment]
@mctdi In Spring Security 4.1 you can use the path variable in your expression. See http://docs.spring.io/spring-security/site/docs/4.1.x/reference/htmlsingle/#el-access-web-path-variables

**Comment by mctdi** [comment]
`http.authorizeRequests().antMatchers(HttpMethod.GET, "/rest/setup/tax").hasRole("USER");  http.authorizeRequests().antMatchers("/rest/setup/tax").hasRole("ADMIN");`

i search to provide only the get for user role and everything for admin one, is it possible?

actually with that code, admin is not allowed.
