### ISSUE TITLE
Allow a Static resources for html

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-security#3982]
it seems strange to me that

> /css/**, /js/**, /images/** and **/favicon.ico).

are the only paths allowed by default. Maybe there should be an insecure path? also seems like maybe it should be `/css/**/*.css` to validate that it is what it says it is.

`/public` would make sense, but I don't know if there's a way for security to validate things were found in the `resources/public` even though they aren't served at `/public` but just `/` that said if backwards compatibility has to be maintained maybe a new directory could be allowed. Also `/webjars/**` should be allowed if they are detected

**Comment by rwinch** [comment]
@xenoterracide Thanks for the report. This should be reported to [Spring Boot](https://github.com/spring-projects/spring-boot/issues) since it is what actually configures these defaults.
