### ISSUE TITLE
Add an IP address property in SessionInformation class to record the user IP of the related session

### ISSUE THREAD

**Issue by lucumt** [spring-projects/spring-security#3989]
### Summary

If we  use spring security to manage user log in,some times we need to find all the active sessions and the related IP address.

The reason that we need to know the IP address of session is that if user close browser,the session will not expired soon,so if we limit the max session count for user log in,then if a user close his browser directly, then the session for his browser is still available,but the total max session count will lost one!

So if I can find the IP address of the session,then I can find which session not in using now ,and I can kick off the session manually!
### Actual Behavior
1. In Spring Security the session information is stored in **[SessionInformation](https://github.com/spring-projects/spring-security/blob/master/core/src/main/java/org/springframework/security/core/session/SessionInformation.java)** class,but I found that it only contains the following properties:  
   ![2222](https://cloud.githubusercontent.com/assets/5226038/17093341/417ecdee-527b-11e6-8cfb-b57cd9273f65.png)  
2. The **registerNewSession**method in **[SessionRegistryImpl](https://github.com/spring-projects/spring-security/blob/master/core/src/main/java/org/springframework/security/core/session/SessionRegistryImpl.java)** don't provide another way to construct a **SessionInformation** instance. 
   ![2223](https://cloud.githubusercontent.com/assets/5226038/17093471/0e79c83a-527c-11e6-98a0-49445b8207c1.png)
### Expected Behavior
-  **[SessionInformation](https://github.com/spring-projects/spring-security/blob/master/core/src/main/java/org/springframework/security/core/session/SessionInformation.java)** provide a **String** property to store the IP address,or provide an **Object** property to store any external information.

``` java
  private String ip;
```
-  Add a new constructor method for **[SessionInformation](https://github.com/spring-projects/spring-security/blob/master/core/src/main/java/org/springframework/security/core/session/SessionInformation.java)**:  

``` java
public SessionInformation(Object principal, String sessionId, Date lastRequest,String ip) {
        Assert.notNull(principal, "Principal required");
        Assert.hasText(sessionId, "SessionId required");
        Assert.notNull(lastRequest, "LastRequest required");
        Assert.notNull(lastRequest, "IP required");
        this.principal = principal;
        this.sessionId = sessionId;
        this.lastRequest = lastRequest;
 this.ip = ip;
    }
```
-  Add a new overload **registreNewSession** method for Interface **[SessionRegistry](https://github.com/spring-projects/spring-security/blob/master/core/src/main/java/org/springframework/security/core/session/SessionRegistry.java)**

``` java
void registerNewSession(String sessionId, String ip,Object principal);
```
- Add a configuration tag in **[Spring Security XSD](http://www.springframework.org/schema/security/spring-security-4.0.xsd)** file to let the user choose remember the session IP address whether or not. 
### Version

**Spring Security 3.1.2**,but I hope this feature can add into the new coming version.

**Comment by lucumt** [comment]
Although I can use **[HttpSessionListener](http://www.springframework.org/schema/security/spring-security-4.0.xsd)** to store the mapping information of sessionId and IP address,but I think if we use Spring Security Framework the most effective may is to modify Spring Security Source code!

**Comment by amaralani** [comment]
Hi, is anyone working on this? can I take this?

**Comment by rwinch** [comment]
I'm not sure I understand. The principal is typically a `UsernamePasswordAuthenticationToken` which has a `remoteAddress` property.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
