### ISSUE TITLE
Add convenience method for constructing RoleHierarchy from Map

### ISSUE THREAD

**Issue by thomasdarimont** [spring-projects/spring-security#3990]
### Summary

Currently a `RoleHierarchy` needs to be constructed by creating a `RoleHierarchyImpl` which 
interprets a string based definition of a role hierarchy.
Since this mapping only maps a role to a list of implied roles this could also be backed by a simple map.

It would be great if spring security would ship with method of constructing a `RoleHierarchy` from a
map which would nicely fit with a yaml based configuration approach which can be seen in the provided example.

### Sample
See: https://gist.github.com/thomasdarimont/ee9fffdef1adb9243b12ad247478aad4

**Comment by thomasdarimont** [comment]
Hello @jgrandja thanks for taking care of it.
I didn't find the time for reworking this :-(

See you at the next PR ;-)

Cheers,
Thomas

**Comment by jgrandja** [comment]
No worries at all @thomasdarimont.
For sure, see you at the next PR!
