### ISSUE TITLE
NPE vulnerability in HttpSessionCsrfTokenRepository

### ISSUE THREAD

**Issue by tkruse** [spring-projects/spring-security#3996]
session was null in my case in:

```
HttpSession session = request.getSession();
session.setAttribute(this.sessionAttributeName, token);
```

request.getSession() creates a session when none exist, but e.g. org.apache.catalina.connector.Request returns null for getSession(true) in several cases (such as no context).

**Comment by tkruse** [comment]
In case you are wondering, what I am trying to do is to get WebSockets to run with Spring-security and SockJs. Because SockJs will not allow cookie or header-based authentication, I was trying to authenticate channel subscription instead, allowing anonymous access to my handshake endpoint. 

    ERROR o.s.w.s.m.StompSubProtocolHandler 	 Failed to send client message to application via MessageChannel in session qpgz5gxr. Sending STOMP ERROR to client.
    org.springframework.messaging.MessageDeliveryException: Failed to send message to ExecutorSubscribableChannel[clientInboundChannel]; nested exception is java.lang.NullPointerException
    Caused by: java.lang.NullPointerException
	at org.springframework.security.web.csrf.HttpSessionCsrfTokenRepository.saveToken(HttpSessionCsrfTokenRepository.java:64)
	at org.springframework.security.web.csrf.LazyCsrfTokenRepository$SaveOnAccessCsrfToken.saveTokenIfNecessary(LazyCsrfTokenRepository.java:176)
	at org.springframework.security.web.csrf.LazyCsrfTokenRepository$SaveOnAccessCsrfToken.getToken(LazyCsrfTokenRepository.java:128)
	at org.springframework.security.messaging.web.csrf.CsrfChannelInterceptor.preSend(CsrfChannelInterceptor.java:61)

This is not part of the issue, just giving you context.

**Comment by anthraxn8b** [comment]
Hi! Now I am stuck at the same position.
Is it "my mistake" that the nullpointer is thrown or is it a bug?
Can it be worked arround or do I have to wait until this will be fixed?
I am using spring security with websockets and in deed the context is empty.

**Comment by rwinch** [comment]
`HttpServletRequest.getSession()` should never return null, so this is a problem elsewhere. See https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getSession()

**Comment by tkruse** [comment]
Not sure about your response. Of course HttpServletRequest.getSession() should not return null, but it effectively does, in several (error) cases. Look at the catalina source code:
https://apache.googlesource.com/tomcat/+/fc71d6837b7d18e1aced80be6e85c314152f9c78/java/org/apache/catalina/connector/Request.java
in doGetSession(boolean create)

I do not expect a patch to fix the NPE, I would suggest just checking for null and throwing a more informative Exception, such as an IllegalStateException with Message "getSession() returned null"

**Comment by rwinch** [comment]
@tkruse Thank you for the additional information. I don't think we should guard against APIs that break their contracts. This will add lots of extra code and add up to a reasonable amount of overhead to the code. Based on the Javadoc of `getSession()` returning `null` is a breakage in the APIs and any changes, if any, should be done on the Tomcat side.

**Comment by mknet** [comment]
@tkruse I'm facing the same issue. Could you share what you did to solve your issue? Thx!

**Comment by tkruse** [comment]
@mknet  sorry, I have no more access to that codebase. You should better describe your problem in a new ticket.
