### ISSUE TITLE
PreAuthorize not took in consideration

### ISSUE THREAD

**Issue by mctdi** [spring-projects/spring-security#4010]
### Summary

I put PreAuthorize anotation in my service interface layer but it not took in consideration

### Actual Behavior

I put @PreAuthorize("hasRole('ADMIN')") in my service interface layer.
User role can access without problem

### Expected Behavior

Only admin role need to acess it

### Configuration

```
@Configuration
@EnableWebSecurity
public class ApplicationSecurity extends WebSecurityConfigurerAdapter {
        @Override
protected void configure(HttpSecurity http) throws Exception {

    http.authorizeRequests()
            .antMatchers("/login").permitAll()
            .antMatchers("/rest/**").authenticated();

    http.csrf().disable();
    http.exceptionHandling().authenticationEntryPoint(authenticationEntryPoint);

    http.formLogin().successHandler(authenticationSuccessHandler);
    http.formLogin().failureHandler(authenticationFailureHandler);
    http.logout().logoutUrl("/logout");
    http.logout().logoutSuccessUrl("/");
}
```

### Version

I use spring boot 1.4

**Comment by rwinch** [comment]
You need to add
@EnableGlobalMethodSecurity(prePostEnabled= true)

See
http://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#enableglobalmethodsecurity

**Comment by marccollin** [comment]
this annotation was in my Application class... tried to put it in class, i got same result

**Comment by rwinch** [comment]
Please produce a sample to reproduce the issue.

**Comment by marccollin** [comment]
i cleaned the project and seem ok, thanks
