### ISSUE TITLE
After updating to  4.1.1 and using MvcRequestMatcher, authorize Tag throws UnsupportedOperationException

### ISSUE THREAD

**Issue by dhajdukis** [spring-projects/spring-security#4012]
### Summary

We use Spring Security with basic authantication and freemarker template engine. We wish to display function buttons according to the user's roles. After udating Spring Security from 4.1.0.RELEASE to 4.1.1
 an exception is thrown during running the tempale:

> WARNING: 17:55:03.280 [http-listener-1(2)] WARN  javax.enterprise.web - StandardWrapperValve[dispatcher]: Servlet.service() for servlet dispatcher threw exception
> java.lang.UnsupportedOperationException: public abstract java.lang.Object javax.servlet.ServletRequest.getAttribute(java.lang.String) is not supported
> 	at org.springframework.security.web.UnsupportedOperationExceptionInvocationHandler.invoke(FilterInvocation.java:227)
> 	at com.sun.proxy.$Proxy357.getAttribute(Unknown Source)
> 	at javax.servlet.ServletRequestWrapper.getAttribute(ServletRequestWrapper.java:120)
> 	at org.springframework.web.util.UrlPathHelper.getContextPath(UrlPathHelper.java:323)
> 	at org.springframework.web.util.UrlPathHelper.getPathWithinApplication(UrlPathHelper.java:224)
> 	at org.springframework.web.util.UrlPathHelper.getPathWithinServletMapping(UrlPathHelper.java:177)
> 	at org.springframework.web.util.UrlPathHelper.getLookupPathForRequest(UrlPathHelper.java:154)
> 	at org.springframework.security.web.servlet.util.matcher.MvcRequestMatcher$DefaultMatcher.matches(MvcRequestMatcher.java:108)
> 	at org.springframework.security.web.servlet.util.matcher.MvcRequestMatcher.matches(MvcRequestMatcher.java:61)
> 	at org.springframework.security.web.access.intercept.DefaultFilterInvocationSecurityMetadataSource.getAttributes(DefaultFilterInvocationSecurityMetadataSource.java:95)
> 	at org.springframework.security.web.access.DefaultWebInvocationPrivilegeEvaluator.isAllowed(DefaultWebInvocationPrivilegeEvaluator.java:103)
> 	at org.springframework.security.taglibs.authz.AbstractAuthorizeTag.authorizeUsingUrlCheck(AbstractAuthorizeTag.java:171)
> 	at org.springframework.security.taglibs.authz.AbstractAuthorizeTag.authorize(AbstractAuthorizeTag.java:102)
> 	at org.springframework.security.taglibs.authz.JspAuthorizeTag.doStartTag(JspAuthorizeTag.java:69)

### Actual Behavior

Unexpected exception is thrown.

### Expected Behavior

The authorization should be done as before.

### Configuration

Spring version: 4.3.2.RELEASE
Freemarker version: 2.3.21

securityContext.xml:
>      <security:http use-expressions="false" disable-url-rewriting="false" entry-point-ref="basicAuthenticationEntryPoint" request-matcher="mvc">

### Version

Spring Security 4.1.1

### Sample

Partial freemarker template, that triggers the exception:

>                     <@security.authorize url="/delete" method="GET">
>                     <th>Delete</th>
>                     </@security.authorize>

**Comment by jgrandja** [comment]
Hi @dhajdukis this has been resolved in #3977. We're planning on releasing 4.1.2 this week but if you would like to move forward on this issue you can point to the snapshot version 4.1.2.BUILD-SNAPSHOT.
I'll close this issue as it's been resolved.

**Comment by dhajdukis** [comment]
Hi @jgrandja! Thank you very much and sorry for reporting a duplicate issue!

**Comment by jgrandja** [comment]
No worries @dhajdukis
