### ISSUE TITLE
smartly detect cache-control

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-security#4015]
although there's a working workaround, if I specify cacheControl in my MVC route, the default security headers for that route should not be applied. I can turn off security headers globally with spring boot but then that's global and those default headers don't get applied to anything regardless of whether or not it's defined.

http://stackoverflow.com/q/38557951/206466

https://github.com/spring-projects/spring-boot/issues/6510 says that this should be done in spring security

**Comment by xenoterracide** [comment]
as an asside, I don't know why the default is `nocache`, not `private` which would tell the proxy not to cache unless it could offer a per user cache, but there might be a reason for that.

**Comment by rwinch** [comment]
@xenoterracide Thanks for the report! 

This sounds like a duplicate of [SPR-14005](https://jira.spring.io/browse/SPR-14005) and #2953 Have you tried updating to the latest version of Spring and Spring Security?

**Comment by xenoterracide** [comment]
looks like I updated to Athens RC1 on the 8/4, removing code to disable headers,  and I don't see the  duplicate now. Looks good.

**Comment by rwinch** [comment]
Glad it is now working. Thanks for the quick follow up @xenoterracide!
