### ISSUE TITLE
SEC-141: Reference Guide Should Document Captcha Support

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#402]
["Daniel Gredler":https://jira.spring.io/secure/ViewProfile.jspa?name=gredler](Migrated from ["SEC-141":https://jira.spring.io/browse/SEC-141?redirect=false]) said:

Captcha support was added to acegi in version 0.9.0, but the reference guide does not yet document this feature.

**Comment by spring-issuemaster** [comment]
This issue is related to #976
