### ISSUE TITLE
LdapUserDetails must extend CredentialsContainer

### ISSUE THREAD

**Issue by jbaris** [spring-projects/spring-security#4029]
### Summary

I think LdapUserDetails must extend CredentialsContainer to allow erase credentials. This behavior is similar to org.springframework.security.core.userdetails.User class. When erase-credentials is true (default value), the ProviderManager executes:
```
			if (eraseCredentialsAfterAuthentication
					&& (result instanceof CredentialsContainer)) {
				// Authentication is complete. Remove credentials and other secret data
				// from authentication
				((CredentialsContainer) result).eraseCredentials();
			}
```
result is an AbstractAuthenticationToken with:
```
	public void eraseCredentials() {
		eraseSecret(getCredentials());
		eraseSecret(getPrincipal());
		eraseSecret(details);
	}
	private void eraseSecret(Object secret) {
		if (secret instanceof CredentialsContainer) {
			((CredentialsContainer) secret).eraseCredentials();
		}
	}
```
So, when principal is an LdapUserDetailsImpl, it must clear its password:
```
public class LdapUserDetailsImpl implements LdapUserDetails, PasswordPolicyData {
	...	
	public void eraseCredentials() {
		password = null;
	}
	...
}
public interface LdapUserDetails extends UserDetails, CredentialsContainer {
	...
}
```

### Actual Behavior

`public interface LdapUserDetails extends UserDetails {`

### Expected Behavior

`public interface LdapUserDetails extends UserDetails, CredentialsContainer {`

### Version

4.1.1.RELEASE

**Comment by aabadia** [comment]
+1

**Comment by jgrandja** [comment]
Thanks for the PR @jbaris. I added a test in addition to your updates. This is now merged in master.
