### ISSUE TITLE
SEC-142: sample schema references old package (dbinit.txt)

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#403]
["Andrew Clifford":https://jira.spring.io/secure/ViewProfile.jspa?name=bashbish](Migrated from ["SEC-142":https://jira.spring.io/browse/SEC-142?redirect=false]) said:

IllegalArgumentException thrown using ACL security if configuring database acl_permission table according to dbinit.txt schema example.

Solution: in /doc/xdocs/dbinit.txt need to change  net.sf.acegisecurity.acl.basic.SimpleAclEntry with org.acegisecurity.acl.basic.SimpleAclEntry

**Comment by linuxjackto1** [comment]
thanks www.movied.org
