### ISSUE TITLE
Can't find cas samples

### ISSUE THREAD

**Issue by KevinQian** [spring-projects/spring-security#4040]
Hi,

    I can't find cas samples in sample/cas folder. please tell me where it is. thanks.

**Comment by eddumelendez** [comment]
@KevinQian you can check inside of [samples/xml](https://github.com/spring-projects/spring-security/tree/master/samples/xml) folder and find cas sample

**Comment by jgrandja** [comment]
Thanks @eddumelendez for pointing that out.

@KevinQian In the future, please ask these types of questions on [Gitter](https://gitter.im/) in the spring-projects/spring-security room...instead of logging an Issue here.
Thank you.
