### ISSUE TITLE
SEC-146: LDAPS Support does not work

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#405]
["Franck Babin":https://jira.spring.io/secure/ViewProfile.jspa?name=fbabin](Migrated from ["SEC-146":https://jira.spring.io/browse/SEC-146?redirect=false]) said:

In order to use the LDAP feature for authentication and authorization over SSL I had to modify the class :
 org.acegisecurity.providers.ldap.DefaultInitialDirContextFactory

At line 132 I have modified the test:
if (url.startsWith("ldap:")) {
By:
if (url.startsWith("ldap:") || url.startsWith("ldaps:")) {

That's the only way I've been able to do it after a long debugging session.

I hope it will help.

Franck

**Comment by linuxjackto1** [comment]
thanks www.movied.org
