### ISSUE TITLE
CsrfConfigurer should support ignoringRegexMatchers()

### ISSUE THREAD

**Issue by simonwg** [spring-projects/spring-security#4054]
### Summary

The CsrfConfigurer should support ignoringRegexMatchers(). Currently only Ant matcher is supported.
### Version

4.1.x

**Comment by eleftherias** [comment]
gh-5477 added support for disabling CSRF by RequestMatcher. 
You can now use `ignoringRequestMatchers` with a `RegexRequestMatcher`.
