### ISSUE TITLE
org.springframework.security.web.firewall.RequestWrapper not declared public

### ISSUE THREAD

**Issue by anandchakru** [spring-projects/spring-security#4055]
### Trying to create an filter to handle certain conditions like `ExpiredPasswordFilter` and since `RequestWrapper` is not declared `public`, I'm unable to cast it (because `import  org.springframework.security.web.firewall.RequestWrapper` says the class is not visible)

My current (silly) Workaround is: put `ExpiredPasswordFilter` in `org.springframework.security.web.firewall` package

**Comment by rwinch** [comment]
It is intentionally encapsulated. You can cast to `FirewalledRequest` instead.
