### ISSUE TITLE
SEC-144: Separate SecurityEnforcementFilter from FilterSecurityInterceptor

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#406]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-144":https://jira.spring.io/browse/SEC-144?redirect=false]) said:

SecurityEnforcementFilter delegates to FilterSecurityInterceptor, the latter of which handles web request authorization. The former is responsible for catching any AcegiSecurityException, and causing either an AuthenticationEntryPoint to be launched, or an SC_FORBIDDEN (403 error) to be sent. Generally an AuthenticationEntryPoint will cause a 401 to be sent, or a redirect to some sort of login page.

As the two filters do not depend on each other, good OO design specifies that they should not depend on each other. Whilst both SecurityEnforcementFilter and FilterSecurityInterceptor can be avoided within a web application, doing so causes AuthenticationExceptions to propagate up the calling stack. It would be preferable if the underlaying AcegiSecurityExceptions could be caught, and an appropriate web redirect/401/403 sent instead.

This task is to rename both of the filters to more accurately reflect their purpose, and eliminate the binding between them so that the SecurityEnforcementFilter can be used on its own where desired.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
