### ISSUE TITLE
SEC-145: ReflectionSaltSource doesn't propagate exception on getSalt

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#407]
["Mathias Bogaert":https://jira.spring.io/secure/ViewProfile.jspa?name=pathos](Migrated from ["SEC-145":https://jira.spring.io/browse/SEC-145?redirect=false]) said:

Change line 70 of ReflectionSaltSource from:

throw new AuthenticationServiceException(exception.getMessage());

to

throw new AuthenticationServiceException(exception.getMessage(), exception);

**Comment by linuxjackto1** [comment]
thanks www.movied.org
