### ISSUE TITLE
SEC-147: BasicAclEntryAfterInvocationProvider should support processDomainObjectClass

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#408]
["Mathias Bogaert":https://jira.spring.io/secure/ViewProfile.jspa?name=pathos](Migrated from ["SEC-147":https://jira.spring.io/browse/SEC-147?redirect=false]) said:

The BasicAclEntryAfterInvocationProvider and BasicAclEntryAfterInvocationCollectionFilteringProivder should support checking the method return type against a processDomainObjectClass property (isAssignable), so that it's easier to have domain objects implement sort of a SecuredEntity interface (voters already have this).

**Comment by linuxjackto1** [comment]
thanks www.movied.org
