### ISSUE TITLE
RequestHeaderAuthenticationFilter should not return name of missing header.

### ISSUE THREAD

**Issue by rmkellogg** [spring-projects/spring-security#4083]
### Summary

In the event the required header is missing an exception of the format: {header} header is not found in request.  For security reasons it is generally considered bad form to tell the user what "secret" is missing and defeats the security by obscurity concept.

Suggest we simply use the text: Required header is not found in request.

### Version
Spring Security 4.12

**Comment by rwinch** [comment]
Thanks for the report @rmkellogg!

Generally speaking you shouldn't log exceptions to the user. Instead, you should handle the exception. A meaningful exception is important for developers to troubleshoot. For these reasons, I'm closing this as won't fix.
