### ISSUE TITLE
@EnableGlobalAuthentication does not inject AuthenticationManagerBuilder as expected

### ISSUE THREAD

**Issue by ammagamma** [spring-projects/spring-security#4086]
### Summary

Using `@EnableGlobalAuthentication` like in the example in the documentation leads to unsatisfied dependency.

### Actual Behavior

Running this code:
`pom.xml`:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.company</groupId>
  <artifactId>app</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>app</name>
  <url>http://maven.apache.org</url>
  <dependencies>
     <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-context</artifactId>
        <version>4.3.2.RELEASE</version>
    </dependency>
    <dependency>
	<groupId>org.springframework.security</groupId>
	<artifactId>spring-security-config</artifactId>
	<version>4.1.3.RELEASE</version>
    </dependency>
  </dependencies>
</project>
```

`App.java`:
```
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
import org.springframework.security.config.annotation.authentication.configuration.EnableGlobalAuthentication;
import org.springframework.security.config.annotation.method.configuration.EnableGlobalMethodSecurity;

@Configuration
@EnableGlobalAuthentication   // does not work
//@EnableGlobalMethodSecurity // works
public class App {
    public static void main( String[] args ) {
        ApplicationContext context = new AnnotationConfigApplicationContext(App.class);
    }
    
    @Autowired
    public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
        auth.inMemoryAuthentication().withUser("user").password("password").roles("USER");
    }
}
```

gives this error:

`Unsatisfied dependency expressed through method 'configureGlobal' parameter 0: Error creating bean with name 'org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration': Unsatisfied dependency expressed through method 'setObjectPostProcessor' parameter 0: No qualifying bean of type [org.springframework.security.config.annotation.ObjectPostProcessor] found for dependency [org.springframework.security.config.annotation.ObjectPostProcessor<java.lang.Object>]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.security.config.annotation.ObjectPostProcessor] found for dependency [org.springframework.security.config.annotation.ObjectPostProcessor<java.lang.Object>]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration': Unsatisfied dependency expressed through method 'setObjectPostProcessor' parameter 0: No qualifying bean of type [org.springframework.security.config.annotation.ObjectPostProcessor] found for dependency [org.springframework.security.config.annotation.ObjectPostProcessor<java.lang.Object>]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.security.config.annotation.ObjectPostProcessor] found for dependency [org.springframework.security.config.annotation.ObjectPostProcessor<java.lang.Object>]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}`

### Expected Behavior

According to the first example in the  [docs](http://docs.spring.io/spring-security/site/docs/4.1.3.RELEASE/apidocs/org/springframework/security/config/annotation/authentication/configuration/EnableGlobalAuthentication.html) the above code should properly autowire the `AuthenticationManagerBuilder`. It actually works with `@EnableGlobalMethodSecurity` as indicated
by the comments in the code.

Note: In the example in the docs the method `configureGlobal` misses the declaration of the Exception thrown by `auth.inMemoryAuthentication()
`
### Configuration

see `pom.xml `above

### Version

I am using Maven 3.3.9 and Java 1.8

### Sample

see above

**Comment by ammagamma** [comment]
Maybe the real question is why does `@EnableGlobalAuthentication` not import  `ObjectPostProcessorConfiguration` like `@EnableGlobalMethodSecurity` and `@EnableWebSecurity` do ? An `ObjectPostProcessor` is needed by `AuthenticationConfiguration`, which is in turn imported by `@EnableGlobalAuthentication`. The above code fails, because there is no `ObjectPostProcessor` bean.

**Comment by rwinch** [comment]
@ammagamma Thanks for the report! This is now fixed in master!
