### ISSUE TITLE
SEC-148: @Secured annotation should be @Inherited and @Documented

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#409]
["Mathias Bogaert":https://jira.spring.io/secure/ViewProfile.jspa?name=pathos](Migrated from ["SEC-148":https://jira.spring.io/browse/SEC-148?redirect=false]) said:

Spring's @Transactional annotation is inherited and documented (javadoc).

@java.lang.annotation.Inherited
@java.lang.annotation.Documented

**Comment by linuxjackto1** [comment]
thanks www.movied.org
