### ISSUE TITLE
SEC-149: Add Spring's @Transactional(readOnly = true) annotation to UserDetailsService loadUserByUsername method

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#410]
["Mathias Bogaert":https://jira.spring.io/secure/ViewProfile.jspa?name=pathos](Migrated from ["SEC-149":https://jira.spring.io/browse/SEC-149?redirect=false]) said:

Would be very handy in Spring environments.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
