### ISSUE TITLE
Token based authentication and JSR 250

### ISSUE THREAD

**Issue by raderio** [spring-projects/spring-security#4100]
### Summary

It is not clear in documentation how to set user authority when are used JSR 250 annotations.

### Actual Behavior

```
@RestController
public class ApplicationController {

    @PermitAll
    @RequestMapping(value = "/", method = RequestMethod.GET)
    public String index() {
        return "Greetings from ContextConfig Boot!";
    }

    @RolesAllowed({"ADMIN"})
    @RequestMapping(value = "/secured", method = RequestMethod.GET)
    public String secured() {
        return "Secured :)";
    }
}
```

### Configuration

```
@Configuration
@EnableWebSecurity
@EnableGlobalMethodSecurity(jsr250Enabled = true)
public class SecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
    }
}
```

### Version

4.3.3.RELEASE

Token is send in header "X-AUTH-TOKEN".
How to configure spring security when user send token in header and hase role "ADMIN" he will be allowed to access "secured"?

**Comment by rwinch** [comment]
Spring Security does not have built in support for X-AUTH-TOKEN. Please provide more details.

**Comment by raderio** [comment]
Well, it is custom header name, it could be "APP-ACCESS-Token".

**Comment by rwinch** [comment]
You need to ensure the SecurityContext has an Authentication with the proper role. Without knowing more about how your application is setup, I cannot help

**Comment by raderio** [comment]
Hi. The issue was that role is "ADMIN", but by default all roles should have prefix "ROLE_".
So, role should be "ROLE_ADMIN".
