### ISSUE TITLE
SEC-150: Exception for 'This recipient already exists for this aclObjectIdentity' should include keys

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#411]
["Mathias Bogaert":https://jira.spring.io/secure/ViewProfile.jspa?name=pathos](Migrated from ["SEC-150":https://jira.spring.io/browse/SEC-150?redirect=false]) said:

In JdbcExtendedDaoImpl, the 

// Ensure there isn't an existing record for this recipient
        if (lookupPermissionId(aclDetailsHolder.getForeignKeyId(),
                basicAclEntry.getRecipient()) != -1) {
            throw new DataIntegrityViolationException(
                "This recipient already exists for this aclObjectIdentity");
        }

exception should include the foreignkey id and class and the recipient id.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
