### ISSUE TITLE
Add Referrer-Policy Header support

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4110]
We should add support for [Referrer-Policy](https://www.w3.org/TR/referrer-policy/) via a header. This would be off by default to remain passive. Examples might be:

``` xml
<http>
    <headers>
        <!-- defaults to using "no-referrer" -->
        <referrer-policy />
    </headers>
</http>
```

``` xml
<http>
    <headers>
        <referrer-policy policy="same-origin"/>
    </headers>
</http>
```

``` java
    http
        .headers()
            // defaults to using "no-referrer"
            .referrerPolicy().and()
```

``` java
    http
        .headers()
            // defaults to using "no-referrer"
            .referrerPolicy(ReferrerPolicy.SAME_ORIGIN).and()
```

The possible values come from https://www.w3.org/TR/referrer-policy/#referrer-policies

Changes should
- Update the XML and Java Config and include tests
- Update the the rnc files used to create the schema the schema (can be generated from the config directory using `../gradlew rncToXsd`
- Update the documentation (both headers section of the docs and the namespace appendix)

NOTE: A good example of the touch points can be found in #3763

**Comment by eddumelendez** [comment]
I'm working on it
