### ISSUE TITLE
HttpSessionCache only supports a single redirect in a shared session setup

### ISSUE THREAD

**Issue by dl1ely** [spring-projects/spring-security#4111]
### Summary

Chains of more than one redirect within the same session fail as the second redirect overwrites the first one in the session, and is missing on the way back.
### Actual Behavior

In our microservice setting, accessing a protected resource `http://localhost/service/resource.txt` (1) by an unauthenticated user redirects to `http://localhost/service/oauth` (2) which redirects to `http://localhost/oauth/login` (3) for authentication. While `/service/` and `/oauth/` are separate services, they are proxied to zuul and share the same session.

The redirect (2) -> (3) overwrites the `SPRING_SECURITY_SAVED_REQUEST` key in the shared session initially created by redirect (1) -> (2). When redirecting back, the redirect (3) -> (2) succeeds and removes the `SPRING_SECURITY_SAVED_REQUEST` key from the session. The next redirect (2) -> (1) fails as the `SPRING_SECURITY_SAVED_REQUEST` key is missing in the session (and was overwritten anyway in the (2) -> (3) redirect). Spring Security falls back to redirecting to `'/'`, so in our setting the user ends up at `http://localhost/service/` instead of `http://localhost/service/resource.txt` after authentication.
### Expected Behavior

In redirect chains, `DefaultSavedRequest` objects should be saved in a LIFO (stack) manner in the session to keep the history of previous redirects. So that redirecting (3) -> (2) pops off the last `DefaultSavedRequest` from the stack in the session and the next one in the stack redirects (2) -> (1).

I want to implement a new `RequestCache` strategy implementing the stack-behaviour on top of the session. Might that be of value as a PR to Spring Security?

**Comment by dl1ely** [comment]
Implementing a new RequestCache strategy gets a little bit more complicated as i have to copy `SavedRequestAwareWrapper.java` unchanged to my own project, as it only has package visibility. This wrapper gets returned by `RequestCache.getMatchingRequest(…)`.

Any thoughts on changing the visibility of `SavedRequestAwareWrapper`?

**Comment by rwinch** [comment]
@dl1ely I wonder if we would be better off allowing the user to inject the session attribute used to save the request for `HttpSessionRequestCache`. This seems it would allow you to leverage a new instance of `HttpSessionRequestCache` with different session attributes for each `SecurityFilterChain` instance.

**Comment by dl1ely** [comment]
@rwinch Well, that is another solution that would work as long as my code manages to keep the session attribute names unique. I think there are pros and cons to both approaches. Yours offers more control but needs more work from the calling side (determing the right session attribute key for the redirect step at hand). On the other hand, it does not introduce a complete new RequestCache strategy. Both is fine.

**Comment by rwinch** [comment]
I'd like to keep the scope of `SavedRequestAwareWrapper` as it isn't currently intended for extension. Keeping it package scope ensures we can refactor as we see fit without concerns for passivity.

If adding the session attribute name is something that would work for you, please create a ticket for it and close this issue. If you are able a PR (with tests) for the issue would be appreciated as well.

**Comment by dl1ely** [comment]
That needs a new ticket? We cannot use this one?

As much as i would like to contribute a PR, i already implemented that SessionStack solution as outlined above. I would gladly convert my code to the solution you proposed and offer the corresponding PR to Spring Security, but never having contributed to Spring before i am not quite sure what is the correct springy way to "inject the session attribute". Right now there are 2-3 places where the `RequestCache` strategy is initialised as default with a `new HttpSessionRequestCache()`, offering a setter that can be used to overwrite that default with another `RequestCache` strategy. Would it suffice to add a new one-argument-constructor to `HttpSessionRequestCache` for the session attribute to use, and use that to inject another `HttpSessionRequestCache` with modified session attribute via the setter, or is that too simple?

thanks for giving some advice on that.

**Comment by rwinch** [comment]
Thanks for the response. I went ahead and created #4130 to address this. No need to submit a PR. We will ensure it gets taken care of.

**Comment by dl1ely** [comment]
Thanks, i will look at the final solution and take that as a guideline for my possible future PRs to Spring Security.
