### ISSUE TITLE
NullPointerException in WebSocketMessageBrokerSecurityBeanDefinitionParser at bootup

### ISSUE THREAD

**Issue by johnmiroki** [spring-projects/spring-security#4112]
### Summary

Using namespace config, added <websocket-message-broker>, NullPointerException is thrown by WebSocketMessageBrokerSecurityBeanDefinitionParser.java:258 at application startup
### Actual Behavior

Been used Spring Security namespace to secure a Spring MVC application, no problem. 
now on to config Spring Security for WebScocket, did the following
1. Added spring-security-messaging.jar
2. Added the following tag:

``` xml
    <websocket-message-broker>
        <intercept-message type="CONNECT" access="permitAll" />
        <intercept-message type="UNSUBSCRIBE" access="permitAll" />
        <intercept-message type="DISCONNECT" access="permitAll" />
        <intercept-message pattern="/**" access="hasRole('USER')" />
    </websocket-message-broker>
```
### Expected Behavior

Application boot up normally and WebSocket is secured
### Configuration

Entire Spring application is configured via namespace, using spring core, spring mvc, spring jpa  and spring security modules.
### Version

Spring version: 4.3.2.Release
Spring Security version: 4.2.0.RC1 and 4.1.0.Release
### Observation:

The code responsible for the NullPointerException is:

``` java
    String[] beanNames = registry.getBeanDefinitionNames();
    for (String beanName : beanNames) {
        BeanDefinition bd = registry.getBeanDefinition(beanName);
        String beanClassName = bd.getBeanClassName();
        if (beanClassName.equals(SimpAnnotationMethodMessageHandler.class
                        .getName()) || beanClassName.equals(WEB_SOCKET_AMMH_CLASS_NAME)) {
...}
```

to be exact, when beanClassName is null, the NullPointerException is thrown.

Now I've observed two occasions where beanClassName is null:
1. when configuring datasource for the app, I use bean definition inheritance for DIY purposes, it goes like:

``` xml
<bean id="parentDataSource" class="com.mchange.v2.c3p0.ComboPooledDataSource"
        destroy-method="close">

<bean id="readDataSource" parent="parentDataSource"></bean>
<bean id="writeDataSource" parent="parentDataSource"></bean>
```

Now somehow readDataSource and writeDataSource don't have their own class, thus they don't have a beanClassName, and hence the NullPointerException. 
I managed to fix this by assigning class to their bean definition like this:

``` xml
<bean id="readDataSource" parent="parentDataSource" class="com.mchange.v2.c3p0.ComboPooledDataSource"></bean>
```

However:
2. the NullPointerException is still thrown, this time, by a bean named "org.springframework.security.config.http.FilterInvocationSecurityMetadataSourceParser$DefaultWebSecurityExpressionHandlerBeanFactory#0$created#0"
I don't know where it's from and how to assign a beanClass to it.

The easiest fix to the problems is apparent:
Either add a null check guard before, or using the reversed equal check: eg:

fix1:

``` java
if (beanClassName != null && (beanClassName.equals(SimpAnnotationMethodMessageHandler.class
                        .getName()) || beanClassName.equals(WEB_SOCKET_AMMH_CLASS_NAME)))
```

fix2:

``` java
if (SimpAnnotationMethodMessageHandler.class
                        .getName().equals(beanClassName) || WEB_SOCKET_AMMH_CLASS_NAME.equals(beanClassName))
```

But i dunno if there's more bug related to beanClassName being null deep down.

**Comment by rwinch** [comment]
Thanks for the report! A fix is now merged into master :)
