### ISSUE TITLE
@Secured requires a role by default

### ISSUE THREAD

**Issue by raderio** [spring-projects/spring-security#4118]
Why [@Secured](http://docs.spring.io/spring-security/site/docs/4.0.0.RELEASE/apidocs/org/springframework/security/access/annotation/Secured.html) requires a role by default?
What if don't have any roles in applications, what I should use?

**Comment by rwinch** [comment]
`@Secured` is centered around roles. Use the more powerful `@PreAuthorize` annotation i.e. `@PreAuthorize("authenticated")`

I'm going to mark this as resolved. Please reopen if you don't think this answers your question.
