### ISSUE TITLE
SEC-151: AOP Method interception with org.springframework.aop.framework.autoproxy.BeanNameAutoProxyCreator

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#412]
["Todd Nine":https://jira.spring.io/secure/ViewProfile.jspa?name=tnine](Migrated from ["SEC-151":https://jira.spring.io/browse/SEC-151?redirect=false]) said:

When using a org.springframework.aop.framework.autoproxy.BeanNameAutoProxyCreator to create the required proxy for security, the configuration must contain the property 'proxyTargetClass' set to true.  Otherwise, the method passed to org.acegisecurity.intercept.method.aopalliance.MethodSecurityInterceptor.invoke is the proxy's caller, not the proxy's target.  Note that this introduces a requirement on CGLIB.  While this is technically not a bug, it should be noted that unexpected behavior can occur if the autoProxy is not configured correctly.  Please make a note of this in the documentation.

<bean id="autoProxyCreator" class="org.springframework.aop.framework.autoproxy.BeanNameAutoProxyCreator">
    <property name="interceptorNames">
      <list><value>securityInterceptor</value></list>
    </property>
    <property name="beanNames">
      <list><value>datalexAdapter</value></list>
    </property>
    <property name="proxyTargetClass" value="true"/>
  </bean>

**Comment by linuxjackto1** [comment]
thanks www.movied.org
