### ISSUE TITLE
SEC-152: SecurityContextHolder to support strategy pattern

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#413]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-152":https://jira.spring.io/browse/SEC-152?redirect=false]) said:

http://www.mail-archive.com/acegisecurity-developer%40lists.sourceforge.net/msg01488.html

**Comment by linuxjackto1** [comment]
thanks www.movied.org
