### ISSUE TITLE
SEC-153: CasAuthenticationToken.toString() method to use StringBuffer

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#414]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-153":https://jira.spring.io/browse/SEC-153?redirect=false]) said:

http://forum.springframework.org/showthread.php?t=20884

**Comment by linuxjackto1** [comment]
thanks www.movied.org
