### ISSUE TITLE
SEC-154: NamedEntityObjectIdentity must support CGLIB (Hibernate) modified domain objects

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#415]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-154":https://jira.spring.io/browse/SEC-154?redirect=false]) said:

CGLIB-generated classes have names such as foo.DomainObject$$EnhancerByCGLIB, which are incompatible with the NamedEntityObjectIdentity's internal representation of the classname as a String.

A workaround is to use BasicAclProvider.defaultAclObjectIdentityClass to provide a new instance of AclObjectIdentity which can correctly handle the names. Another workaround is for your domain objects to implement AclObjectIdentityAware and return the AclObjectIdentity that represents the instance.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
