### ISSUE TITLE
AuthenticationPrincipalArgumentResolver not used when argument class implements Principal

### ISSUE THREAD

**Issue by ghost** [spring-projects/spring-security#4151]
### Summary

putting an @AuthenticationPrincipal annotation on a Controller parameter, where the parameter's type implements Principal causes the servlet to throw an IllegalArgumentException

### Actual Behavior

Basically, since ServletRequestMethodArgumentResolver supports Principal objects, it gets used, and it populates the parameter with an Authentication object, causeing a casting exception when the resolving AuthenticationObject is forced into my UserDetails object

### Expected Behavior

AuthenticationPrincipalArgumentResolver should be defaulted to resolve AuthenticationPrincipal arguments, which will do the correct resolution.

The workaround is not having my UserDetails object inherit Principal, or use the actual UserDetails class in the parameter, and then cast it to my subclass, but this is silly. It makes perfect sense that a UserDetails object is also a Princial, and it is in fact retrieved via Authentication _Principal_

#### Fix

The fix would be forcing ServletRequestMethodArgumentResolver to be lower priority in argument resolution than AuthenticationPrincipalArgumentResolver 

### Version

All

**Comment by reliveyy** [comment]
Found the same issue.

**Comment by anthonyraymond** [comment]
Still an issue as of today

**Comment by sbrannen** [comment]
See comments in https://github.com/spring-projects/spring-framework/pull/25780#pullrequestreview-490415855

**Comment by eleftherias** [comment]
I can confirm that the associated issue https://github.com/spring-projects/spring-framework/pull/25780 fixes this problem.

Since this was fixed in Spring Framework 5.3, it is fixed in all supported versions.
