### ISSUE TITLE
SEC-155: BasicAclEntryCache remove from cache support

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#416]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-155":https://jira.spring.io/browse/SEC-155?redirect=false]) said:

BasicAclEntryCache needs a cache eviction method. The JdbcExtendedDaoImpl should hook into the BasicAclEntryCache and evict updated ACLs.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
