### ISSUE TITLE
SEC-156: AuthenticationSimpleHttpInvokerRequestExecutor should use getName() instead of toString()

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#417]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-156":https://jira.spring.io/browse/SEC-156?redirect=false]) said:

http://forum.springframework.org/showthread.php?t=21664

**Comment by linuxjackto1** [comment]
thanks www.movied.org
