### ISSUE TITLE
SEC-157: BeanNameAutoProxyCreator usage instructions

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#418]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-157":https://jira.spring.io/browse/SEC-157?redirect=false]) said:

http://forum.springframework.org/showthread.php?t=21756

Add to docs:

<property name="proxyTargetClass" value="true"/>

When using BeanNameAutoProxyCreator.

**Comment by spring-issuemaster** [comment]
This issue duplicates #412

**Comment by linuxjackto1** [comment]
thanks www.movied.org
