### ISSUE TITLE
Mixed content JS error on subproject pages

### ISSUE THREAD

**Issue by nlwillia** [spring-projects/spring-security#4189]
### Summary

Some of the subproject pages (ex: [spring-security-oauth](https://projects.spring.io/spring-security-oauth)) are making an http call which fails when the page is loaded via https.

### Actual Behavior

Scripted parts of the page (ex: the download box) don't render properly.  There's an error in the browser's console.

In Chrome, the console error is:

Mixed Content: The page at 'https://projects.spring.io/spring-security-oauth/#quick-start' was loaded over HTTPS, but requested an insecure script 'http://spring.io/project_metadata/spring-security-oauth?callback=jQuery110103097017087568592_1483986902372&_=1483986902373'. This request has been blocked; the content must be served over HTTPS.

**Comment by eleftherias** [comment]
This seems to be fixed now.
If you are still seeing this error please report it to https://github.com/spring-io/sagan/issues.
Sagan is the spring.io site and reference application.
