### ISSUE TITLE
SEC-158: X.509 Auth token should adopt standard behaviour w.r.t. authenticated property

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#419]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-158":https://jira.spring.io/browse/SEC-158?redirect=false]) said:

http://forum.springframework.org/showthread.php?t=21453

**Comment by linuxjackto1** [comment]
thanks www.movied.org
