### ISSUE TITLE
NPE in 4.2 on startup when using websocket-message-broker

### ISSUE THREAD

**Issue by doom777** [spring-projects/spring-security#4196]
### Summary

using `<websocket-message-broker>` crashes on startup

### Actual Behavior

WebSocketMessageBrokerSecurityBeanDefinitionParser.MessageSecurityPostProcessor throws a NullPointerException. Apparently some beans have null beanClassName, and you are doing equating by beanClassName.equals, instead of Objects.equals

Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.security.config.http.FilterInvocationSecurityMetadataSourceParser$DefaultWebSecurityExpressionHandlerBeanFactory#0; factoryMethodName=getBean; initMethodName=null; destroyMethodName=null
### Configuration
`<websocket-message-broker same-origin-disabled="true" >
		<intercept-message pattern="/**" access="isAuthenticated()" />
	</websocket-message-broker>`

### Version

4.2. It works in 4.1.2

**Comment by rwinch** [comment]
Duplicates #4112
