### ISSUE TITLE
Wrong check at SwitchUserFilter#setSwitchFailureUrl()

### ISSUE THREAD

**Issue by martin-g** [spring-projects/spring-security#4198]
### Summary

org.springframework.security.web.authentication.switchuser.SwitchUserFilter#setSwitchFailureUrl() makes a check for non-empty `this.switchUserUrl` instead of the passed `switchFailureUrl`. The error message says: `"switchFailureUrl cannot be empty and must be a valid redirect URL"` so I believe the check is wrong (copy/paste error ?!).

### Actual Behavior

Checks for non-empty `this.switchUserUrl`

### Expected Behavior

Should check for non-empty `switchFailureUrl`

### Configuration

Irrelevant

### Version

4.1.4

### Sample

https://github.com/spring-projects/spring-security/blob/9c03571bbbe74aa44d801904798e0dd165dd251f/web/src/main/java/org/springframework/security/web/authentication/switchuser/SwitchUserFilter.java#L498

**Comment by rwinch** [comment]
Thanks for the report! A fix is now merged into master :)
