### ISSUE TITLE
SEC-159: SecurityContextHolder may cause a memory leak on app re-deployment

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#420]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-159":https://jira.spring.io/browse/SEC-159?redirect=false]) said:

The context thread local reference may prevent an application classloader from being garbage collected

http://forum.springframework.org/showthread.php?t=21144

**Comment by linuxjackto1** [comment]
thanks www.movied.org
