### ISSUE TITLE
Reference document eorror of <cors> Attributes

### ISSUE THREAD

**Issue by xuyang2** [spring-projects/spring-security#4200]
### Summary

There is an error in reference document

https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#nsa-cors-attributes

### Behavior

> [[nsa-cors-ref]]
> * **ref**
> Optional attribute that specifies the bean name of a `CorsFilter`.
> 
> [[nsa-cors-configuration-source-ref]]
> * **ref**
> Optional attribute that specifies the bean name of a `CorsConfigurationSource` to be injected into a `CorsFilter` created by the XML namespace.

### Expected
The second **ref** should be **configuration-source-ref**

### Version
4.2.1.RELEASE

**Comment by rwinch** [comment]
Thanks for the report! A fix is now merged into master :)
