### ISSUE TITLE
Security Reference document bad links

### ISSUE THREAD

**Issue by gpratte-tiy** [spring-projects/spring-security#4208]
### Summary

The reference document has bad links (404) to the Spring Security project

### Actual Behavior

Spring Security Reference 4.2.1 release has a link in Chapter 1 Getting Started to the "project website" with the url https://spring.io/spring-security. This results in a 404 page not found.

There are other links to the project in the reference that have the same problem.
 

### Expected Behavior

Link should be to https://projects.spring.io/spring-security/

### Configuration

N.A.

### Version

4.2.1

### Sample

N.A.

**Comment by rwinch** [comment]
Thanks for the report. It looks like the redirect on the site is not working. I have reached out to determine what the problem is.

**Comment by rwinch** [comment]
Thanks for the report! The redirect should be fixed now
