### ISSUE TITLE
SEC-160:  NullPointerException when Initializing FilterSecurityInterceptor

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#421]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-160":https://jira.spring.io/browse/SEC-160?redirect=false]) said:

http://forum.springframework.org/showthread.php?t=21046

Using a "==" in the objectDefinitionSource causes FilterInvocationDefinitionSourceEditor to parse an empty config attribute.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
