### ISSUE TITLE
SecurityNamespaceHandler check for 4.2 version but reports about 4.1

### ISSUE THREAD

**Issue by amarkevich** [spring-projects/spring-security#4210]
### Summary

Message:
https://github.com/spring-projects/spring-security/blob/ab5af879530e0257db99f6632919aa78d56cdf00/config/src/main/java/org/springframework/security/config/SecurityNamespaceHandler.java#L89

Check:
https://github.com/spring-projects/spring-security/blob/ab5af879530e0257db99f6632919aa78d56cdf00/config/src/main/java/org/springframework/security/config/SecurityNamespaceHandler.java#L224

### Actual Behavior

Ask for version 4.1

### Expected Behavior

4.2

### Version

4.2.1.RELEASE
Typo in master too

**Comment by rwinch** [comment]
Thanks for the report! A fix is now merged into master :)
