### ISSUE TITLE
Spring Security 3.2.10 Manifest is empty

### ISSUE THREAD

**Issue by michael-simons** [spring-projects/spring-security#4216]
### Summary

I downloaded a fresh copy of Spring Security 3.2.10 from Maven Central and found the MANIFEST.MF is empty:

```
Manifest-Version: 1.0

```

I noticed that problem during  startup, Security is logging

```
4:24:48.919 [localhost-startStop-1] INFO  o.s.s.core.SpringSecurityCoreVersion - You are running with Spring Security Core null
14:24:48.923 [localhost-startStop-1] INFO  o.s.s.c.SecurityNamespaceHandler - Couldn't determine package version information.
```

It seems to work but i'm afraid it will cause problems.

Steps to reproduce:

```
wget http://repo1.maven.org/maven2/org/springframework/security/spring-security-core/3.2.10.RELEASE/spring-security-core-3.2.10.RELEASE.jar
unzip spring-security-core-3.2.10.RELEASE.jar 
more META-INF/MANIFEST.MF
```

and compare with the Manifest from 3.2.9.

**Comment by jalieven** [comment]
Doubt that this wel ever get fixed. You can bake your own with this commands: 
`jar umf ./MANIFEST.MF spring-security-core-3.2.10.RELEASE.jar`

**Comment by jzheaux** [comment]
Thanks for the tip, @jalieven! Once a version is released, bugs are normally fixed on the next maintenance release. Since `3.2.x` is already EOL'd, users are encouraged to update to a supported branch.
