### ISSUE TITLE
OAuth2RestTemplate retrieve token with MockRestServiceServer results in connection refused

### ISSUE THREAD

**Issue by tunovic** [spring-projects/spring-security#4217]
### Summary

When using OAuth2RestTemplate with MockRestServiceServer it results in connection refused for token retrieval.

### Actual Behavior

OAuth2RestTemplate with MockRestServiceServer results in connection refused for token retrieval.

### Expected Behavior

OAuth2RestTemplate with MockRestServiceServer results in retrieved token and call after with result.

### Configuration

OAuth2RestTemplate with MockRestServiceServer.

### Version

<dependency>
	<groupId>org.springframework.security.oauth</groupId>
	<artifactId>spring-security-oauth2</artifactId>
</dependency>

With Spring Boot 1.5.1.RELEASE

**Comment by rwinch** [comment]
@tunovic Thanks for the report. I understand this is a bit confusing, but OAuth2RestTemplate is not part of Spring Security. Please report this issue to https://github.com/spring-projects/spring-security-oauth/issues
