### ISSUE TITLE
SEC-161: PathBasedFilterInvocationDefinitionMap should truncate URL Query String parameters

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#422]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-161":https://jira.spring.io/browse/SEC-161?redirect=false]) said:

The concept of Ant Paths do not map directly to URLs, as being used by PathBasedFilterInvocationDefinitionMap. Namely Ant Paths refer to file system mappings, whereas URLs adopt a protocol://host/path?parameter format.

Whilst the protocol and host are not considered by either PathBasedFilterInvocationDefinitionMap nor RegExpBasedFilterInvocationDefinitionMap, there has been confusion as to how the former should handle entries appearing in the query string parameter portion of a URL (ie the URL string appearing after the first question mark symbol). It is our view that PathBasedFilterInvocationDefinitionMap should as closely as possible match to the file system mapping concept, as this is what people expect of Ant Paths. To achieve this, it is desirable to truncate any query string parameters from the URL prior to comparison.

Users wishing to match on the query string parameters should use RegExpBasedFilterInvocationDefinitionMap. Because regular expressions are not normally considered to reflect file system mappings, it is reasonable that users utilising regular expressions with RegExpBasedFilterInvocationDefinitionMap will expect to detect and handle any query string parameters in a URL. As such, RegExpBasedFilterInvocationDefinitionMap will not truncate at the question mark symbol.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
