### ISSUE TITLE
RoleHierarchyUtilsTests fail on windows due to crlf

### ISSUE THREAD

**Issue by neshkeev** [spring-projects/spring-security#4227]
### Line-ending problem for windows

The expected result for `RoleHierarchyUtilsTests#roleHierarchyFromMapWhenMapValidThenConvertsCorrectly` is crafted using `\n`, but `PrintWriter` generates string with `\r\n` on Windows, which causes the expected and actual results not to match.

### Actual Behavior

The variable `roleHierarchy` contains the following line:<br />`ROLE_A > ROLE_B\r\nROLE_A > ROLE_C\r\nROLE_B > ROLE_D\r\nROLE_C > ROLE_D\r\n`
The variable `expectedRoleHierarchy` contains the followng line: <br />`ROLE_A > ROLE_B\nROLE_A > ROLE_C\nROLE_B > ROLE_D\nROLE_C > ROLE_D\n`

### Expected Behavior

Both of the variables contain the same value regardless of the environment the test runs.

### Configuration

Run the test on a Windows machine.

### Version

The problem was introduced in the `c75a5b727945e2` commit, so the following versions are affected:
```
$ git tag --contains c75a5b727945e2
4.2.0.M1
4.2.0.RC1
4.2.0.RELEASE
4.2.1.RELEASE
```

**Comment by rwinch** [comment]
Thanks for the report this is now fixed in b64cdb57658ecc6da2dd5be0f9b112ac794d0ead
