### ISSUE TITLE
SEC-162: MethodInvocationPrivilegeEvaluator incorrectly throws exception with null Authentication

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#423]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-162":https://jira.spring.io/browse/SEC-162?redirect=false]) said:

MethodInvocationPrivilegeEvaluation should not throw an exception if a null Authentication is passed, but instead return false to indicate the current user does not have permission to the requested MethodInvocation.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
