### ISSUE TITLE
SEC-163: MethodInvocationUtils.create(Object, String, Object[]) causes ClassCastException

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#424]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-163":https://jira.spring.io/browse/SEC-163?redirect=false]) said:

In RC1, the MethodInvocationUtils.create(Object, String, Object[]) caused a ClassCastException at line 84.

In addition, there was no unit test to pick up this issue.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
