### ISSUE TITLE
SEC-164: X509AuthenticationProvider does not keep authentication details

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#425]
["Rolf Arne Corneliussen":https://jira.spring.io/secure/ViewProfile.jspa?name=rolfarne](Migrated from ["SEC-164":https://jira.spring.io/browse/SEC-164?redirect=false]) said:

When the provider authenticates a principal, that last statement reads

  return new X509AuthenticationToken(user, clientCertificate,
                user.getAuthorities());

whereas the AbstractUserDetailsAuthenticationProvider does

   result.setDetails((authentication.getDetails() != null)
            ? authentication.getDetails() : null);

The X509AuthenticationProvider should 'copy' the authentication details to the returned object.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
