### ISSUE TITLE
Spring Boot samples pom.xml is broken

### ISSUE THREAD

**Issue by andreiepure** [spring-projects/spring-security#4259]
### Summary

Pom.xml build error for the 2 Spring boot samples due to the missing version on 3 dependencies:
```
      <artifactId>spring-boot-starter-thymeleaf</artifactId>
      <artifactId>spring-boot-starter-web</artifactId>
      <artifactId>spring-boot-starter-test</artifactId>
```

### Actual Behavior
```
For artifact {org.springframework.boot:spring-boot-starter-thymeleaf:null:jar}: The version cannot be empty. (org.apache.maven.plugins:maven-resources-plugin:2.6:testResources:default-testResources:process-test-resources)

org.apache.maven.artifact.InvalidArtifactRTException: For artifact {org.springframework.boot:spring-boot-starter-thymeleaf:null:jar}: The version cannot be empty.
<stack trace>
```
### Expected Behavior

Can build and execute according to the [4.2.2. release guideline](http://docs.spring.io/spring-security/site/docs/4.2.2.RELEASE/guides/html5/helloworld-boot.html)

### Version

Spring Security 4.2.2 
S.T.S. 3.8.3

Link to culprit file: [pom.xml](https://github.com/spring-projects/spring-security/blob/master/samples/boot/insecure/pom.xml)

**Comment by andreiepure** [comment]
Update: another missing dependency is

```
<dependency>
    <groupId>org.springframework.security</groupId>
    <artifactId>spring-security-config</artifactId>
    <version>4.2.2.RELEASE</version>
</dependency>
```

**Comment by eleftherias** [comment]
The project samples-boot-insecure has been updated to use gradle and now builds successfully.
