### ISSUE TITLE
SEC-165: Refactor FilterBasedLdapUserSearch to use constructor-based injection.

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#426]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-165":https://jira.spring.io/browse/SEC-165?redirect=false]) said:

For consistency. Both context factorty and filter are required props so should be constructor injected.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
