### ISSUE TITLE
Localization (messages_ru.properties)

### ISSUE THREAD

**Issue by olezhuravlev** [spring-projects/spring-security#4262]
messages_ru.properties for Russian.

Please, change the extension of attached file from **.txt** to **.properties**
or just download the file from [Google Disk](https://drive.google.com/open?id=0B4m4gqBvyWPCMWJwOENCM2k1QUE).

[messages_ru.txt](https://github.com/spring-projects/spring-security/files/889064/messages_ru.txt)

**Comment by eleftherias** [comment]
Closing as this was already merged in PR gh-4354.
