### ISSUE TITLE
SecurityContextHolderStrategies - Make public and not final

### ISSUE THREAD

**Issue by MitchTalmadge** [spring-projects/spring-security#4267]
### Summary

I'd like to propose that Spring's SecurityContextHolderStrategy implementations be made public and not final.

The strategies in question are:

[ThreadLocalSecurityContextHolderStrategy.java](https://github.com/spring-projects/spring-security/blob/master/core/src/main/java/org/springframework/security/core/context/ThreadLocalSecurityContextHolderStrategy.java)
[InheritableThreadLocalSecurityContextHolderStrategy.java](https://github.com/spring-projects/spring-security/blob/master/core/src/main/java/org/springframework/security/core/context/InheritableThreadLocalSecurityContextHolderStrategy.java)
[GlobalSecurityContextHolderStrategy.java](https://github.com/spring-projects/spring-security/blob/master/core/src/main/java/org/springframework/security/core/context/GlobalSecurityContextHolderStrategy.java)

The reason for this is that for a developer who would like to implement a custom Strategy, they would need to write their own from scratch. It seems as though it would be beneficial to make use of inheritance. 

As an example, my goal is to create a custom `SecurityContext` implementation for use within my application. However, to do this I need to make a custom `SecurityContextHolderStrategy`, since the defaults all create instances of `SecurityContextImpl`. I realize that I could copy the code in `ThreadLocalSecurityContextHolderStrategy.java` and modify it for my use, but this feels wrong when I could easily override the `createEmptyContext()` method instead, making use of inheritance and preventing duplicate code.

I know this is a long shot, but I figured I'd make the suggestion. Alternatively, it would be useful to be able to easily replace the default `SecurityContext` implementation used throughout the application.

Thanks for your consideration.

**Comment by cocsackie** [comment]
I am not a contributor to this project, so I can't tell if it's going to end up in spring-security. On the other hand I am using spring libraries and I think that preferred way to do this would be to use DI aka IoC of spring framework, decorator pattern and composition. Yes... I know - boilerplate code. On the other hand you mentioned, that you wanted to override `createEmptyContext()` - and you would probably do that for each and every `SecurityContextHolderStrategy` in your project - a lot of same classes except names and base classes (but same behavior! that is code duplication!). What if you would want to change that behavior? You would need to change every class you made. It might be error prone (might forget to change in one of the classes) and maintenance nightmare. When using approach I mentioned you end up with one class, that accepts any `SecurityContextHolderStrategy` and some spring configuration. Even if you won't use it for all classes but one, you end up with re-usable code.

Probably my examples of problems with inheritance in this case are exaggerated, but inheritance requires intimate knowledge of base class implementation, which might change without notice, thus breaking the subclass.

**Comment by rwinch** [comment]
I would also recommend using composition rather than inheritance. This is largely why the classes are marked as final.

In addition, I'd consider a different strategy than relying on a custom `SecurityContext` implementation as you are then running against implementation specific code vs the interface.
