### ISSUE TITLE
WithSecurityContext is requiring "USER" role by default on all endpoints

### ISSUE THREAD

**Issue by naten3** [spring-projects/spring-security#4271]
### Summary

When WithSecurityContext is set up correctly, all requests still require a ROLE_USER authority. This doesn't match my normal security configuration so is inconvenient. It was difficult to diagnose.

### Actual Behavior

Endpoints cannot be accessed without ROLE_USER authority

### Expected Behavior

Required authorities are exactly the same as when the application is running. 

### Configuration

I have created a custom annotation which is annotated with @WithSecurityContext. There is a corresponding WithSecurityContextFactory configuration which provides a custom context.

### Version

Spring security test 4.1.4.RELEASE
 Spring security core 4.1.4.RELEASE

**Comment by eleftherias** [comment]
@naten3 Do you have a small sample that reproduces this issue?

I have tried to reproduce it using annotations like `@WithMockUser`, that relies on `@WithSecurityContext`, but I am not seeing the behaviour that you described.
It may be that your security configuration was not being used in your test environment.

**Comment by naten3** [comment]
Must have been something specific to our setup I couldn't find.
