### ISSUE TITLE
Inside pom.xml of spring-security-samples-boot-insecure spring-boot-starter is used without parent - spring-boot-starter-parent

### ISSUE THREAD

**Issue by 4udipayan** [spring-projects/spring-security#4278]
### Summary

Inside pom.xml of spring-security-samples-boot-insecure spring-boot-starter is used without parent - spring-boot-starter-parent

### Actual Behavior

No parent tag is mentioned so I got error saying version cannot be empty/null

### Expected Behavior

Should mention 
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>1.5.2.RELEASE</version>
  </parent>

### Version

Didn't check with other version. Getting error in 4.2.2.RELEASE

### Sample

https://github.com/spring-projects/spring-security/blob/4.2.2.RELEASE/samples/boot/helloworld/pom.xml

**Comment by eleftherias** [comment]
Closing because samples now use gradle.
