### ISSUE TITLE
SEC-167: PasswordEncoder.isPasswordValid(String encPass, String rawPass, Object salt) implementations throw NullPointers if rawPass is null.

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#428]
["Craig Baker":https://jira.spring.io/secure/ViewProfile.jspa?name=crbaker](Migrated from ["SEC-167":https://jira.spring.io/browse/SEC-167?redirect=false]) said:

Code in org.acegisecurity.providers.encoding.Md5PasswordEncoder

```
public boolean isPasswordValid(String encPass, String rawPass, Object salt) {
    String pass1 = "" + encPass;
    String pass2 = encodeInternal(mergePasswordAndSalt(rawPass, salt, false));

    return pass1.equals(pass2);
}
```

If rawPass is null then mergePasswordAndSalt will throw a NullPointer. Should check for null password from authentication.getCredentials()

This manifest itself by throwing a nullpointer when someone log into our application with an empty password. Will it is easy to prevent thought it better to be fixed at the source.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
