### ISSUE TITLE
JWT assertion grant type support

### ISSUE THREAD

**Issue by amssaravanan** [spring-projects/spring-security#4280]
### Summary

We need to implement (exactly) this with spring security and would like to know if this is supported by spring security out-of-the-box. If not, what is the recommended approach?

http://forum.spring.io/forum/spring-projects/security/oauth/124487-jwt-bearer-token-flow?p=604498#post604498

### Actual Behavior

http://forum.spring.io/forum/spring-projects/security/oauth/124487-jwt-bearer-token-flow?p=604498#post604498

**Comment by eleftherias** [comment]
The legacy forum has been shut down, so it's not clear what the request here is.

We have a sample using JWT login, which may be what you are looking for: https://github.com/spring-projects/spring-security-samples/tree/master/servlet/spring-boot/java/jwt/login

**Comment by eleftherias** [comment]
Marking this as a duplicate of gh-6053 instead.
