### ISSUE TITLE
Remove pom.xml from build

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4283]
### Summary

Gradle is mature enough now that users should be able to import the code using Gradle

**Comment by sepwu** [comment]
The docs has not been updated.
https://docs.spring.io/spring-security/site/docs/5.0.2.BUILD-SNAPSHOT/guides/html5/helloworld-javaconfig.html

**Comment by rwinch** [comment]
@sepwu Thanks for the comment. Typically it is best to create a new issue rather than comment on a closed issue. This way the comment doesn't get lost.

I went ahead and created #5026 to track this
