### ISSUE TITLE
Add unit tests to oauth2-core

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#4298]
### Summary

Unit tests need to be added to the `oauth2-core` module.

**Comment by luander** [comment]
What is the expected behavior when the following code is called:
```java
AuthorizationCodeTokenRequestAttributes
	.withCode("code")
//	.clientId(null)
	.redirectUri("http://redirect.uri/")
	.build();
```
Does it let the object be created without the clientId or should it fail with _IllegalArgumentException_?

**Comment by jgrandja** [comment]
@luander The `build()` method should throw `IllegalArgumentException` given that `clientId` is a required attribute as per [spec](https://tools.ietf.org/html/rfc6749#section-4.1.3).

**Comment by luander** [comment]
Thanks for the answer Joe. I was writing the tests for this and other classes and noticed the current behavior is not correct.

**Comment by jgrandja** [comment]
@launder Yes, the current behaviour is not correct hence the need for unit tests. Thanks for taking this on!

FYI, our current naming scheme for test methods is as follows:

_methodName_**When**&lt;Condition&gt;**Then**&lt;Expectation&gt;

You can see examples of this in the following test classes:

`AuthorizationCodeAuthenticationProcessingFilterTests`
`AuthorizationCodeRequestRedirectFilterTests`
