### ISSUE TITLE
SEC-169: SessionRegistry should expose a set of principals that have sessions

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#430]
["Brian Yarger":https://jira.spring.io/secure/ViewProfile.jspa?name=byarger](Migrated from ["SEC-169":https://jira.spring.io/browse/SEC-169?redirect=false]) said:

I'm using the ConcurrentSession suppor t, and I only allow one login per user.  We have an admin screen where we show currently logged in users/sessions.  To get that information I had to extend the SessionRegistry interface to allow access to principals that are in the session registry.  I specifically wanted principals that have non-expired sessions (I actually added two methods getAllPricipals() and getAllActivePrincipals()) but the full list would have been fine (since you can figure out if they have non-expired sessions via SessionRegistry).

I don't know if this is a common request or not, but I would bet people that use the ConcurrentSession support would like to easily get a list of the auth'd users, and this was the easiest way I could find to do it.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
