### ISSUE TITLE
Problems with 5.0 snapshots' poms

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-security#4308]
### Summary

The poms for the latest 5.0 snapshots have a few problems:

- They do not include any optional dependencies
- They include test dependencies
- They import platform-bom in their dependency management
- `commons-logging` is a required dependency

### Actual Behavior

N/A

### Expected Behavior

The poms for 5.0.0 snapshots are similar to those for 4.2.2 in that they have none of the 4 problems described above.

### Configuration

N/A

### Version

5.0.0.BUILD-SNAPSHOT, specifically 5.0.0.BUILD-20170424.000033-75

### Sample

N/A

**Comment by wilkinsona** [comment]
The presence of `commons-logging` is the most problematic in the short term. It's breaking Spring Boot's build as the build is configured to fail if a starter pulls it in transitively.

The lack of optional dependencies is also breaking the Platform's build as some of Spring Security's optional dependencies that are included in the Platform's bom are now being detected as redundant.

**Comment by rwinch** [comment]
This is now resolved.

NOTE: The test dependencies are going to stay in the pom because they don't cause any problems and the meta information is useful to users. I confirmed this is alright with @wilkinsona offline.
