### ISSUE TITLE
SEC-176: WebAuthenticationDetails requires hashCode() method

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#431]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-176":https://jira.spring.io/browse/SEC-176?redirect=false]) said:

hashCode() method required because Authentication.getDetails() increasingly is being used, and WebAuthenticationDetails is the only implementation included out-of-the-box and it is reasonable for Authentication to delegate to WebAuthenticationDetails as part of its own hashCode() method.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
