### ISSUE TITLE
JndiDnsResolver doesn't support resolving all hostnames for a service

### ISSUE THREAD

**Issue by hansvanbeneden** [spring-projects/spring-security#4311]
Recently I posted a [question on stackoverflow](http://stackoverflow.com/questions/43604856/how-to-resolve-all-active-directory-server-urls-with-jndidnsresolver) about resolving the hostnames for a service with JndiDnsResolver. I didn't got any response so I decided to try and fix it myself. 

The actual behavior is that the JndiDnsResolver.resolveServiceEntry only returns one hostname (with the highest priority and weight). I want to add a method that returns a list of hostnames ordered by priority and weight.

Example:
If the DNS server provides the following the service records:
```
_ldap._tcp.springsource.com IN SRV 10 40 88 ldap2.springsource.com.
_ldap._tcp.springsource.com IN SRV 10 70 88 ldap1.springsource.com.
_ldap._tcp.springsource.com IN SRV 20 50 88 ldap3.springsource.com.

```
Then I would expect a method that returns all the hostnames ordered by priority and weight like this:
`[ldap1.springsource.com, ldap2.springsource.com, ldap3.springsource.com]`

**Comment by eleftherias** [comment]
@hansvanbeneden I do not think a method that retrieves all hostnames belongs in the DnsResolver class. The DnsResolver should return a single hostname based on priority and weight, and the user should not need to know about the internal implementation.  
I have left a comment on your PR as well with more details.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
