### ISSUE TITLE
Build runs 49min after merge from master

### ISSUE THREAD

**Issue by simplicii** [spring-projects/spring-security#4316]
### Summary

After merging from master I cannot build anymore on official build server. 
Log file grows too big and 49min run time !?!

i.e ABAC support for spring security #4277

**Comment by rwinch** [comment]
Thanks for the report!

The build should pass now that #4317 is merged. I don't know why the build is taking so long on Travis (it takes about 7 - 8 min for me locally). Perhaps it hangs when the logs reach the limit.
