### ISSUE TITLE
SEC-170: AbstractAclVoter to support AspectJ JoinPoints

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#432]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-170":https://jira.spring.io/browse/SEC-170?redirect=false]) said:

AspectJ support is required in AbstractAclVoter, which presently only support AOP Alliance MethodInvocation secure object invocations.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
