### ISSUE TITLE
Slowness during Login

### ISSUE THREAD

**Issue by Sakthikams** [spring-projects/spring-security#4321]
### Summary

We are upgrading from 12.1.3 to Weblogic 12.2.1.2. slow response time in IE when user login first time. subsequent requests are fast.If we remove spring security ,response time is fast. rest of the browsers including edge we don't see this issue.

### Actual Behavior

During user login it takes nearly 59 to 65 seconds.

### Expected Behavior

with WLS 12.1.3 it used to be work with less that 2ms.

### Configuration

		<form-login login-page="/"
			default-target-url="${login.default.target.url}"
			always-use-default-target="true"
			authentication-failure-url="${login.authentication.failure.url}" />

### Version

Spring 3.2.9

**Comment by rwinch** [comment]
> We are upgrading from 12.1.3 to Weblogic 12.2.1.2. slow response time in IE when user login first time. subsequent requests are fast.If we remove spring security ,response time is fast. rest of the browsers including edge we don't see this issue.

You state that this goes away when  you remove Spring Security. What did you do to remove it? What are you doing after you remove Spring Security since you presumably won't be able to log in?

 > This is going to be very difficult (if not impossible) to figure out without a sample. I see you are using Spring 3.2.9. Is that the Spring version of the Spring Security version? If it is the Spring version, what version of Spring Security are you using?

**Comment by Sakthikams** [comment]
String forwardUrl = "j_spring_security_check?j_username=" + userId
				+ "&j_password=Y";
request.getRequestDispatcher(forwardUrl).forward(request, response)

above forward will handover the request to spring security. If we skip this forward, we don't see any delay in response.

spring security version is 3.2.4

**Comment by rwinch** [comment]
The fact that this only happens in IE strongly suggests the issue is not related to Spring Security as there is not custom logic in Spring Security for IE.

Have you tried profiling the application with something like YourKit?

Can you provide a sample that reproduces the issue? Without that, this issue is likely going to be closed as cannot reproduce.

**Comment by Sakthikams** [comment]
We changed the spring security form authentication model to  spring authentication manger model. It helped us to resolve the issue.

**Comment by rwinch** [comment]
@Sakthikams I'm glad you solved the problem. Can you elaborate what the issue was for others benefit?

**Comment by Sakthikams** [comment]
was earlier using spring security form authentication model(WL12.1.3) and during migration to WL 12.2.1.2 this form authentication model resulted in the slowness issue (takes 60 seconds), while logging into application from site minder on IE 11 browser. Spring security form authentication model is replaced with programmatic invocation of spring security authentication. still it's mystery why it's getting delayed on  form authentication model .
