### ISSUE TITLE
SEC-172: Allow SimpleAclEntry to take 'null' as recipient constructor argument

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#434]
["Mikko Peltonen":https://jira.spring.io/secure/ViewProfile.jspa?name=mpe](Migrated from ["SEC-172":https://jira.spring.io/browse/SEC-172?redirect=false]) said:

If I want to add only parent acl_object_identity link to a domain object, without creating any real acl entries so that I'm effecively inheriting all acl's, I can do that by calling JdbcExtendedDaoImpl.create method with 'null' recipient. 

However you can't pass null recipient to SimpleAclEntry's constructor because AbstractAclEntry's constructor asserts that recipient is not null. You can work-aroud that by constructing SimpleAclEntry with "" recipient and then calling setRecipient(null), which works.

Is there any reason not to allow 'null' for recipient constructor argument, for saving a line of code? Or is there some other way of creating just acl_object_identity and parent link without acl's?

**Comment by linuxjackto1** [comment]
thanks www.movied.org
