### ISSUE TITLE
HSTS preload attribute feature request

### ISSUE THREAD

**Issue by davidgoate** [spring-projects/spring-security#4342]
### Summary
In order to allow submission to the [HSTS preload list ](https://hstspreload.org/) the "preload" attribute must be set. This is currently not supported by the `org.springframework.security.config.annotation.web.configurers.HeadersConfigurer.HstsConfig` or `org.springframework.security.web.header.writers.HstsHeaderWriter` classes. 

It'd be great to add support for this to make this process easier.

**Comment by eleftherias** [comment]
This issue was reported and fixed later in gh-6312.
