### ISSUE TITLE
Where is an example of creating a UserDetailsService?

### ISSUE THREAD

**Issue by AlexByte** [spring-projects/spring-security#4348]

**Comment by rwinch** [comment]
See https://github.com/rwinch/spring-security-hands-on-4.1/blob/master/src/main/java/sample/security/UserRepositoryUserDetailsService.java You can find the corresponding talk at https://spring.io/blog/2016/02/23/springone2gx-2015-replay-hands-on-spring-security-4-1

**Comment by AlexByte** [comment]
The example for Spring MVC https://github.com/kolorobot/spring-mvc-quickstart-archetype
