### ISSUE TITLE
SEC-173: Improve BasicAclDao.getAcls documentation

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#435]
["Mikko Peltonen":https://jira.spring.io/secure/ViewProfile.jspa?name=mpe](Migrated from ["SEC-173":https://jira.spring.io/browse/SEC-173?redirect=false]) said:

BasicAclDao.getAcls method's JavaDoc should document the "protocol" of informing caller (BasicAclProvider) that requested AclObjectIdentity did not have any acl_permission entries, but only acl_object_identity, so that caller can traverse the inheritance hierarchy. JdbcDaoImpl seems to do this by returning one BasicAclEntry with recipient  "**_INHERITENCE_MARKER_ONLY_**".

**Comment by linuxjackto1** [comment]
thanks www.movied.org
