### ISSUE TITLE
 CORS not supported for login and logout while using spring mvc's CORS configuration

### ISSUE THREAD

**Issue by trgoofi** [spring-projects/spring-security#4358]
CORS works fine for mapping define in spring mvc but not for login and logout in spring security.

### Configuration

spring mvc config
```java
    @Override public void addCorsMappings(CorsRegistry registry) {
        registry.addMapping("/**")
            .allowedOrigins("*")
            .allowedMethods("*")
            .allowCredentials(true);
    }
```
spring security config
```java
  @Override protected void configure(HttpSecurity http) throws Exception {
      http.cors();
  }
```

### Version

`spring mvc: 4.3.7.RELEASE`
`spring security: 4.2.2.RELEASE`

**Comment by rwinch** [comment]
This configuration will only apply to endpoints that Spring MVC handles while Spring Security is handling log in and log out. If you truly want all endpoints, you can use a `CorsConfigurationSource` as demonstrated in the documentation https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#cors

**Comment by selfsecurellc** [comment]
I'm having the same issue, was this able to be solved. I've tried the documentations and it's still not working
