### ISSUE TITLE
SEC-174: IE6 redirect bug in AuthenticationProcessingFilterEntryPoint

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#436]
["Bubba Puryear":https://jira.spring.io/secure/ViewProfile.jspa?name=bubbapuryear](Migrated from ["SEC-174":https://jira.spring.io/browse/SEC-174?redirect=false]) said:

An application using the attached config files has redirect problems for Windows clients using IE (but not FireFox) if the server is configured to use ports other than 80 and 443 for HTTP and HTTPS respectively. This issue has been addressed in Acegi in other places (such as ExceptionTranslationFilter, RetryWithHttpsEntryPoint ... etc). A patch for AuthenticationProcessingFilterEntryPoint is attached which resolves this issue (tested with Tomcat 5.5 running on a Linux box with IE/Win, FireFox 1.5/Win, FireFox 1.5 Linux as clients).

It should be noted that this bit of code appears in multiple places - and they aren't all exactly the same.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
