### ISSUE TITLE
Migration XML <http> configuration to Java config

### ISSUE THREAD

**Issue by dmarcaida** [spring-projects/spring-security#4360]
### Summary

How do I do the following with Java config?

1. `use-expressions="false"`

For this, I came up with:
```
// with WebSecurityConfigurerAdapter
http.apply( new UrlAuthorizationConfigurer( getApplicationContext() ).getRegistry()
    .antMatchers( ... );
```
but this won't work for something like `ResourceServerConfigurerAdapter`.

2. `<anonymous username="guest"/>`

I guess the equivalent would be:
```
http.anonymous().principal( Object );
```
I just don't know what exactly to pass as argument.

**Comment by rwinch** [comment]
This is an example of how to do it https://github.com/spring-projects/spring-security/blob/4.2.2.RELEASE/config/src/test/groovy/org/springframework/security/config/annotation/web/builders/DisableUseExpressionsConfig.java

However, if you are migrating to using Java Config I would just use the expressions too. It is much easier and more powerful than non-expressions.
