### ISSUE TITLE
Restructure packages to align for reactive support

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#4366]
The **current** proposed package naming scheme is as follows:

**Web Support (Servlet)**

`org.springframework.security.oauth2.client.web`
`org.springframework.security.oauth2.authorization.web`
`org.springframework.security.oauth2.resource.web`

**Reactive Support**

`org.springframework.security.oauth2.client.server`
`org.springframework.security.oauth2.authorization.server`
`org.springframework.security.oauth2.resource.server`

**Comment by jgrandja** [comment]
Current base package:

**spring-security-oauth2-core** -> `org.springframework.security.oauth2.core`

**spring-security-oauth2-client** -> `org.springframework.security.oauth2.client`

**spring-security-oauth2-server** -> `org.springframework.security.oauth2.server`
** future support for server side (Authorization and Resource server)


**Web Support (Servlet)**

Client base package: `org.springframework.security.oauth2.client`

Server base package: `org.springframework.security.oauth2.server`

**NOTE:** Notice these base packages do not have `web` as a sub-package to indicate Servlet support as is typical in _springframework_ or _springframework.security_ package naming. I'm not sure if it makes sense here given OAuth2 inherently is a web-based protocol, therefore it may be redundant. These base packages, _by default_, house the Servlet support.

**Reactive Support**

Client base package: `org.springframework.security.oauth2.client.reactive`

Server base package: `org.springframework.security.oauth2.server.reactive`

The sub-package `reactive` is consistent on how _springframework_ names packages for reactive support. For example: `org.springframework.web` and `org.springframework.web.reactive`

**Comment by jgrandja** [comment]
@rwinch Based on our discussion, here is the package naming scheme we came up with.

**Web Support (Servlet)**

`org.springframework.security.oauth2.client.web`
`org.springframework.security.oauth2.authorization.web`
`org.springframework.security.oauth2.resource.web`


**Reactive Support**

`org.springframework.security.oauth2.client.server`
`org.springframework.security.oauth2.authorization.server`
`org.springframework.security.oauth2.resource.server`

`org.springframework.security.oauth2.client.reactive`
`org.springframework.security.oauth2.authorization.reactive`
`org.springframework.security.oauth2.resource.reactive`

**Comment by jgrandja** [comment]
Another package naming suggestion to consider for the Authorization Server module:

**Web Support (Servlet)**

`org.springframework.security.oauth2.provider.web`



**Reactive Support**

`org.springframework.security.oauth2.provider.server`

**Comment by rwinch** [comment]
@jgrandja While this does reflect a synonym, I'd like to stick as closely to the official [roles](https://tools.ietf.org/html/rfc6749#section-1.1). Also by calling it provider, it could be the service provider or the authorization provider. In that respect, provider is a bit like using server (is it the authorization server or the resource server).

**Comment by jgrandja** [comment]
Agreed, `provider` is too generic but I figure I put it out there as an option. Sounds like we are still good with `client`, `authorization` and `resource` sub-package naming? Should I proceed with the re-factor to follow the naming convention as specified in this [comment](https://github.com/spring-projects/spring-security/issues/4366#issuecomment-322586142)?

**Comment by rwinch** [comment]
Yes. I think that is what we should do. Please go ahead and refactor as you described (which is also the same as the current task description)
