### ISSUE TITLE
security.basic.path not working as it should

### ISSUE THREAD

**Issue by issam03** [spring-projects/spring-security#4369]
Hello,

I'm trying to add basic HTTP authentication into my gateway microservice to secure **all** the resources exposed by this service

To do so, i wanted a simple properties based solution, so i tried to update my application.properties

`security.basic.enabled = true`
`security.basic.path = /**`
`security.basic.realm = Spring`
`security.user.name = user`
`security.user.password = xxx`
`security.user.role = USER`
`security.sessions = always`

Using this configuration, only http://localhost/env is secured but http://localhost/ping (a simple resource that print "pong")  http://localhost/info are not.
Why security.basic.path = /** does not secure all the resources

Thanks,

**Comment by rwinch** [comment]
Thank you for the report. This looks like something to do with Spring Boot. Please post to https://github.com/spring-projects/spring-boot/issues
