### ISSUE TITLE
Jackson Optimization

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4370]
### Summary

There are some performance optimizations we can provide for jackson integration

**Comment by TanqiZhou** [comment]
org.springframework.security.authentication.BadCredentialsException is not whitelisted. If you believe this class is safe to deserialize, please provide an explicit mapping using Jackson annotations or by providing a Mixin. If the serialization is only done by a trusted source, you can also enable default typing. See https://github.com/spring-projects/spring-security/issues/4370 for details; nested exception is java.

**Comment by chrylis** [comment]
Since the error message points to this issue, can it please get a link to documentation on enabling default typing?

**Comment by miladamery** [comment]
> Since the error message points to this issue, can it please get a link to documentation on enabling default typing?

Hi. i have same issue and cant find how to enable default typing. i really appreciate if you provide a link or something else that says how to do it.

**Comment by jzheaux** [comment]
To (de)serialize a `BadCredentialsException`, use `CoreJackson2Module`:

```java
@Bean
public ObjectMapper objectMapper() {
    ObjectMapper mapper = new ObjectMapper()
    mapper.registerModule(new CoreJackson2Module());
    // ... your other configuration
    return mapper;
}
```

This calls `SecurityJackson2Modules.enableDefaultTyping` and adds the `BadCredentialsException` mixin.

**Comment by TanqiZhou** [comment]
Good

**Comment by koundinya-goparaju-wcar** [comment]
I am getting the following error when I try to deserialize the OAuth2AuthenticationToken 
`The class with org.springframework.security.web.authentication.WebAuthenticationDetails and name of org.springframework.security.web.authentication.WebAuthenticationDetails is not in the allowlist. If you believe this class is safe to deserialize, please provide an explicit mapping using Jackson annotations or by providing a Mixin. If the serialization is only done by a trusted source, you can also enable default typing. See https://github.com/spring-projects/spring-security/issues/4370 for details (through reference chain: org.springframework.security.core.context.SecurityContextImpl["authentication"]->org.springframework.security.oauth2.client.authentication.OAuth2AuthenticationToken["details"])`

**Comment by bmaassenee** [comment]
I think i found a bug in `WebServletJackson2Module`
as its method:
```
	public WebServletJackson2Module() {
		super(WebJackson2Module.class.getName(), new Version(1, 0, 0, null, null, null));
	}
```

Registers it self as `WebJackson2Module.class.getName()`, with the result that ObjectMapper.registerModule rejects the module to be loaded because it thinks this module is already registered

**Comment by jzheaux** [comment]
@bmaassenee, please consider filing an issue if you believe you've found a bug. If you'd include a small reproducing sample in your report, that will help resolve your issue more quickly.

**Comment by tsrgithub** [comment]
{
    "error_description": "OpenID Connect 1.0 UserInfo Error: The class with java.util.Collections$SingletonMap and name of java.util.Collections$SingletonMap is not in the allowlist. If you believe this class is safe to deserialize, please provide an explicit mapping using Jackson annotations or by providing a Mixin. If the serialization is only done by a trusted source, you can also enable default typing. See https://github.com/spring-projects/spring-security/issues/4370 for details",
    "error": "invalid_request",
    "error_uri": "https://openid.net/specs/openid-connect-core-1_0.html#UserInfoError"
}

**Comment by rizkyJabar5** [comment]
> { "error_description": "OpenID Connect 1.0 UserInfo Error: The class with java.util.Collections$SingletonMap and name of java.util.Collections$SingletonMap is not in the allowlist. If you believe this class is safe to deserialize, please provide an explicit mapping using Jackson annotations or by providing a Mixin. If the serialization is only done by a trusted source, you can also enable default typing. See #4370 for details", "error": "invalid_request", "error_uri": "https://openid.net/specs/openid-connect-core-1_0.html#UserInfoError" }

I have the same issue too. Has there been a fix for this?

**Comment by timadeshola** [comment]
I am getting this error when attempt to generate refresh token. Using Spring Boot authorization server v3
`The class with org.springframework.security.oauth2.server.authorization.authentication.OAuth2ClientAuthenticationToken and name of org.springframework.security.oauth2.server.authorization.authentication.OAuth2ClientAuthenticationToken is not in the allowlist. If you believe this class is safe to deserialize, please provide an explicit mapping using Jackson annotations or by providing a Mixin. If the serialization is only done by a trusted source, you can also enable default typing. See https://github.com/spring-projects/spring-security/issues/4370 for details`

**Comment by a1473838623** [comment]
my solution for OAuth2AuthorizationService config.
```java
    @JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@class")
    public abstract static class SynchronizedSetMixin {
    }

    @Bean
    public OAuth2AuthorizationService authorizationService(JdbcTemplate jdbcTemplate,
                                                           RegisteredClientRepository registeredClientRepository) {
        JdbcOAuth2AuthorizationService.OAuth2AuthorizationRowMapper rowMapper =
                new JdbcOAuth2AuthorizationService.OAuth2AuthorizationRowMapper(registeredClientRepository);
        JdbcOAuth2AuthorizationService.OAuth2AuthorizationParametersMapper oAuth2AuthorizationParametersMapper =
                new JdbcOAuth2AuthorizationService.OAuth2AuthorizationParametersMapper();
        JdbcOAuth2AuthorizationService authorizationService =
                new JdbcOAuth2AuthorizationService(jdbcTemplate, registeredClientRepository);
        ObjectMapper objectMapper = new ObjectMapper();

        ClassLoader classLoader = JdbcOAuth2AuthorizationService.class.getClassLoader();
        List<Module> securityModules = SecurityJackson2Modules.getModules(classLoader);
        objectMapper.registerModules(securityModules);
        objectMapper.registerModule(new OAuth2AuthorizationServerJackson2Module());

        objectMapper.addMixIn(Collections.synchronizedSet(new HashSet<>()).getClass(), SynchronizedSetMixin.class);

        rowMapper.setObjectMapper(objectMapper);
        oAuth2AuthorizationParametersMapper.setObjectMapper(objectMapper);
        authorizationService.setAuthorizationRowMapper(rowMapper);
        authorizationService.setAuthorizationParametersMapper(oAuth2AuthorizationParametersMapper);

        return authorizationService;
    }
```

**Comment by z1098416956** [comment]
不是很懂，出现的这个问题：
`java.lang.IllegalArgumentException: The class with java.util.ImmutableCollections$List12 and name of java.util.ImmutableCollections$List12 is not in the allowlist. If you believe this class is safe to deserialize, please provide an explicit mapping using Jackson annotations or by providing a Mixin. If the serialization is only done by a trusted source, you can also enable default typing. See https://github.com/spring-projects/spring-security/issues/4370 for details
	at org.springframework.security.jackson2.SecurityJackson2Modules$AllowlistTypeIdResolver.typeFromId(SecurityJackson2Modules.java:285) ~[spring-security-core-6.2.6.jar:6.2.6]
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:159) ~[jackson-databind-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:97) ~[jackson-databind-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromArray(AsArrayTypeDeserializer.java:53) ~[jackson-databind-2.15.4.jar:2.15.4]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:238) ~[jackson-databind-2.15.4.jar:2.15.4]`
	
这个是我的配置：
`@Bean
    public OAuth2AuthorizationService authorizationService(JdbcTemplate jdbcTemplate,
                                                           RegisteredClientRepository registeredClientRepository) {
        JdbcOAuth2AuthorizationService service = new JdbcOAuth2AuthorizationService(jdbcTemplate,
                registeredClientRepository);
        JdbcOAuth2AuthorizationService.OAuth2AuthorizationRowMapper authorizationRowMapper = new JdbcOAuth2AuthorizationService.OAuth2AuthorizationRowMapper(
                registeredClientRepository);
        authorizationRowMapper.setLobHandler(new DefaultLobHandler());

        ObjectMapper objectMapper = new ObjectMapper();
        ClassLoader classLoader = JdbcOAuth2AuthorizationService.class.getClassLoader();
        List<Module> modules = SecurityJackson2Modules.getModules(classLoader);
        objectMapper.registerModules(modules);
        objectMapper.registerModule(new OAuth2AuthorizationServerJackson2Module());
        objectMapper.addMixIn(Collections.synchronizedSet(new HashSet<>()).getClass(), CustomUserDetailsMixin.class);
        authorizationRowMapper.setObjectMapper(objectMapper);

        service.setAuthorizationRowMapper(authorizationRowMapper);
        return service;
    }

@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY,property = "@class")
public abstract class CustomUserDetailsMixin {

    @JsonProperty("authorities")
  //  @JsonDeserialize(using = CustomUserDeserializer.class)
    @JsonDeserialize(as = HashSet.class, contentAs = SimpleGrantedAuthority.class)
    abstract Set<SimpleGrantedAuthority> getAuthorities();

    @JsonProperty("password")
    abstract String getPassword();

    @JsonProperty("username")
    abstract String getUsername();

    @JsonProperty("accountNonExpired")
    abstract boolean isAccountNonExpired();

    @JsonProperty("accountNonLocked")
    abstract boolean isAccountNonLocked();

    @JsonProperty("credentialsNonExpired")
    abstract boolean isCredentialsNonExpired();

    @JsonProperty("enabled")
    abstract boolean isEnabled();
}


@JsonIgnoreProperties(ignoreUnknown = true)
public class CustomUserDetails implements UserDetails{


//    private NetonUserDO netonUserDO;
    public CustomUserDetails (){}
    private String role;
    private String password;
    private String userName;

    private HashSet<GrantedAuthority> authorities;
   // @JsonCreator
    public CustomUserDetails(/*@JsonProperty("role")*/String role,
                             /*@JsonProperty("password")*/String password,
                             /*@JsonProperty("username")*/ String userName) {
        this.password = password;
        this.userName = userName;
        this.role = role;
        this.authorities = new HashSet<>(List.of(new SimpleGrantedAuthority(role)));
    }
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        // 返回用户的角色或权限
        return  authorities;
    }


    @Override
    public String getPassword() {
        return password;
    }


    @Override
    public String getUsername() {
        return userName;
    }



    @Override
    public boolean isAccountNonExpired() {
        // 账户是否未过期
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        // 账户是否未锁定
        return true; // 确保这里返回 true
    }

    @Override
    public boolean isCredentialsNonExpired() {
        // 凭据是否未过期
        return true;
    }

    @Override
    public boolean isEnabled() {
        // 账户是否启用
        return true;
    }

}


`

**Comment by taraksuthar1999** [comment]
The class with com.example.authservice.security.models.CustomSecurityUserDetails and name of com.example.authservice.security.models.CustomSecurityUserDetails is not in the allowlist.

My Solution which worked for me was to create Deserializer for the class 

```java
@JsonTypeInfo(
        use = JsonTypeInfo.Id.CLASS,
        include = JsonTypeInfo.As.PROPERTY
)
@JsonDeserialize(
        using = CustomSecurityUserDeserializer.class
)
@JsonAutoDetect(
        fieldVisibility = JsonAutoDetect.Visibility.ANY,
        getterVisibility = JsonAutoDetect.Visibility.NONE,
        isGetterVisibility = JsonAutoDetect.Visibility.NONE
)
@JsonIgnoreProperties(
        ignoreUnknown = true
)
public class CustomSecurityUserDetails implements UserDetails {
.....
.....
}
```
