### ISSUE TITLE
Provide support for refresh_token grant

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#4371]
We need to provide `WebClient` support for refreshing an expired access token.

Spec references:

- **OAuth 2.0** - [Refreshing an Access Token](https://tools.ietf.org/html/rfc6749#section-6)

- **OpenID Connect 1.0** - [Using Refresh Tokens](http://openid.net/specs/openid-connect-core-1_0.html#RefreshTokens)

Related #4921

**Comment by jgrandja** [comment]
Related #4509

**Comment by gregsimons** [comment]
@jgrandja is any of the refresh token repository available in a snapshot form at the moment?

**Comment by jgrandja** [comment]
@gregsimons No not at the moment. The HTTP Client integration (e.g. #4920) needs to be implemented first before we tackle this one. We're still planning on getting this in for 5.1 release.

**Comment by rwinch** [comment]
Fixed via df4a24db3d470a652a736bb3ad66dde0946e3556
