### ISSUE TITLE
Add information on how roles map to claims in OAuth 2.0 / OIDC 1.0 Guide

### ISSUE THREAD

**Issue by mraible** [spring-projects/spring-security#4373]
### Summary

Please provide information on how roles can be stored in claims so we know how to map claims to roles and can use Spring Security annotations and `hasRole()`/`hasAuthority()` information.

### Actual Behavior

Not documented in https://github.com/spring-projects/spring-security/blob/5.0.0.M1/samples/boot/oauth2login/README.adoc.

### Version

5.0.0 M1

### Sample

https://github.com/spring-projects/spring-security/blob/5.0.0.M1/samples/boot/oauth2login/

**Comment by jgrandja** [comment]
Hi @mraible . This part of the functionality hasn't been implemented as of yet. I'm thinking we'll provide a hook in `OAuth2UserService` to do this mapping but not sure until I get to it. Of course, there will be a default implementation as well.

**Comment by jgrandja** [comment]
Hi @mraible . I've added the instructions via 67f80df.

**Comment by pdyck** [comment]
@jgrandja you removed the instructions in 86824030f293838acbfe05bbf3072101d914d89c and the `userAuthoritiesMapper` method doesn't exist anymore on the `OAuth2LoginConfigurer`. Is there a new way to map claims to authorities?
