### ISSUE TITLE
SEC-182: TokenBasedRememberMeServices should return an Authentication that can be used by concurrent session services

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#438]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-182":https://jira.spring.io/browse/SEC-182?redirect=false]) said:

http://forum.springframework.org/showthread.php?t=22087

**Comment by linuxjackto1** [comment]
thanks www.movied.org
