### ISSUE TITLE
SEC-175: WebAuthenticationDetails requires equals(Object) method

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#439]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-175":https://jira.spring.io/browse/SEC-175?redirect=false]) said:

An equals(Object) method is required as increasingly Authentication implementations are storing WebAuthenticationDetails for use by their getDetails() method, and in turn delegating equals(Object) checks to the class.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
