### ISSUE TITLE
Support custom GrantedAuthorities strategy for ActiveDirectoryLdapAuthenticationProvider

### ISSUE THREAD

**Issue by mat013** [spring-projects/spring-security#4390]
### Summary

In connection with using ActiveDirectoryLdapAuthenticationProvider it is only possible to extract memberOf in the loadUserAuthorities. In our case we would have liked to extract some other attributes in particular the department and username. However it has not been possible to extend the ActiveDirectoryLdapAuthenticationProvider because the class it is final as it is now. I tried to see if there was some other good alternatives but nothing came up, so what I ended up with was copying the class and modifying it.

But rather than extending maybe it would be beneficial to let it be possible to provide a list of extractors to an instance of an AuthenticationProvider and then when loadAuthorities is invoked all extractors are invoked and the result of all the invocation is a merged list of all GrantedAuthorities.

### Version
4.2.2.RELEASE

**Comment by jzheaux** [comment]
Thanks for the report, @mat013, and I'm sorry for such a delay in responding. This was added in 6.3 as part of #4490 and so I'm going to close this as a duplicate of that.
