### ISSUE TITLE
HttpSecurity patch matchers case sensitive

### ISSUE THREAD

**Issue by glapa** [spring-projects/spring-security#4392]
### Summary

HttpSecurity is case sensitive by default. 

### Actual Behavior

I just found out that when I'm using ` http.authorizeRequests().antMatchers("/path");` it's by default case sensitive even if I configure `pathMatcher` in `WebMvcConfigurerAdapter` as case insensitive. There is no way to override that right now.

### Expected Behavior

At least have option to configure Spring Security to use case insensitive matching by default. Desired behavior would be fetching settings from `WebMvcConfigurerAdapter`.

### Version

Spring MVC 4.3.8
Spring Security 4.2.2

**Comment by rwinch** [comment]
If you want to ensure it aligns with Spring MVC's matching, please use [MvcRequestMatcher](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#mvc-requestmatcher)

**Comment by gdubya** [comment]
In case anyone else is looking for this in the future, the default case sensitivity behaviour changed in spring-security 4.1 due to #3831 (changed from "false" to "true").
