### ISSUE TITLE
SEC-177: User requires hashCode() method

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#440]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-177":https://jira.spring.io/browse/SEC-177?redirect=false]) said:

hashCode() method required because User is the default implementation of UserDetailsService and correct hash code computation important for some cache implementations (that internally use a HashMap for example) and also for delegation from AbstractAuthenticationToken.hashCode() when User is being used as the Authentication.getPrincipal().

**Comment by linuxjackto1** [comment]
thanks www.movied.org
