### ISSUE TITLE
SEC-178: Refactor AbstractAuthenticationToken

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#441]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-178":https://jira.spring.io/browse/SEC-178?redirect=false]) said:

Main changes:
1. Move setAuthenticated(boolean) and isAuthenticated() to AbstractAuthenticationToken
2. Move setDetails(Object) and getDetails() to AbstractAuthenticationToken
3. Adapt equals(Object) method accordingly
4. Adapt hashCode() method accordingly
5. Revise all subclasses to remove behaviour now provided by superclass

**Comment by linuxjackto1** [comment]
thanks www.movied.org
