### ISSUE TITLE
SEC-179: Upgrade depedencies to Spring 2.0-M2

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#442]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-179":https://jira.spring.io/browse/SEC-179?redirect=false]) said:

Upgrade Spring JAR and mocks.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
