### ISSUE TITLE
SEC-180: BasicProcessingFilter should configurably ignore authentication failures

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#444]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-180":https://jira.spring.io/browse/SEC-180?redirect=false]) said:

Some applications require BASIC authentication to be used with an alternative authentication mechanism, such as WebDAV tickets. The existing behaviour of BasicProcessingFilter is to relaunch an AuthenticationEntryPoint if authentication fails after presentation of a BASIC authentication header. A new parameter is required, such as ignoreFailure(boolean), which will allow the BasicProcessingFilter to silently continue the FilterChain irrespective of detecting an authentication failure.

See this thread for more details: http://www.mail-archive.com/acegisecurity-developer%40lists.sourceforge.net/msg01732.html

**Comment by linuxjackto1** [comment]
thanks www.movied.org
