### ISSUE TITLE
Consider adding nonce to OIDC Authentication Request

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#4442]
Related sections in spec:

[3.1.2.1.  Authentication Request](http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)
[15.5.2.  Nonce Implementation Notes](http://openid.net/specs/openid-connect-core-1_0.html#NonceNotes)
[3.1.3.7.  ID Token Validation](http://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation)

**Comment by jgrandja** [comment]
Related #4440 - Validate `nonce` as part of ID Token Validation

**Comment by jgrandja** [comment]
The `nonce` generated by the client during the Authentication Request needs to be stored temporarily so that it can be validated during ID Token Validation. Given these storage requirements, moving this issue to 5.1

**Comment by jgrandja** [comment]
Given the [15.5.2. Nonce Implementation Notes](http://openid.net/specs/openid-connect-core-1_0.html#NonceNotes), here is a proposed implementation:

**Generate `nonce` for Authentication Request**
- Concatenate the attributes contained in `OAuth2AuthorizationRequest` along with the `HttpSession.id` and hash this to produce the `nonce`.

**Validate `nonce` during ID Token Validation**
- Use the same strategy as per above to generate the `nonce` value by hashing the concatenation of the attributes contained in `OAuth2AuthorizationRequest` along with the `HttpSession.id`. Compare this generated `nonce` with the `nonce` in the ID Token for verification.

Given this implementation, we may not need a separate storage facility for the `nonce` value as it can be deduced from the `HttpSession.id` and `OAuth2AuthorizationRequest` which is stored in the `AuthorizationRequestRepository`.

**Comment by bssaini001** [comment]
Will this feature make up for next month release ? Thanks Bhupinder

**Comment by forgo** [comment]
@jgrandja Was this implemented?

**Comment by mkheck** [comment]
Hey @jgrandja, I'll take this one on.

**Comment by hejianchao** [comment]
Is there a switch to turn off the nonce?

**Comment by jgrandja** [comment]
@hejianchao No there isn't a setting/property available to turn it off. Are you having issues with it? Why do you want it disabled?
