### ISSUE TITLE
SEC-183: Avoid unnecessary HttpSession creation when using Anonymous and Remember-Me authentication

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#445]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-183":https://jira.spring.io/browse/SEC-183?redirect=false]) said:

A small number of users use HttpSessionContextIntegrationFilter.allowSessionCreation = false, as they are using an authentication mechanism (such as BASIC) which relies upon the user agent for representing authentication information on each web request. For such users, changes made as part of SEC-168 and SEC-182 will cause issues because these changes will always create a HttpSession (in order to obtain a Session ID that in turn was needed by the concurrent session capabilities).

**Comment by linuxjackto1** [comment]
thanks www.movied.org
