### ISSUE TITLE
SEC-184: RunAsManager reference documentation refers to obsolete classes

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#446]
["Tim Nolan":https://jira.spring.io/secure/ViewProfile.jspa?name=katentim](Migrated from ["SEC-184":https://jira.spring.io/browse/SEC-184?redirect=false]) said:

Documentation for RunAsManager refers to SecurityInterceptorCallback class from previous versions

**Comment by linuxjackto1** [comment]
thanks www.movied.org
