### ISSUE TITLE
About expandability of users,roles and resources

### ISSUE THREAD

**Issue by 601345138** [spring-projects/spring-security#4463]
### Actual Behavior

It is very confusing to use my own RBAC model. If I want to use my own database table sechema, I want to find a way to extend the default implementation of loading user info, role info and authority info. I found it is very confusing to find the entrance to load my data, for example, if I use RDBMS to manage data,I want to load data from DB using ORMappring frameworks like Hibernate or Mybatis, if I use memory to save the data, I want to load data from memory.  I could not find useful code from User Reference about this.I hope you can expose the interface or abstract class so that developers can load data more conveniently and comfortable.

### Version

4.3.10

**Comment by jgrandja** [comment]
Hi @601345138. Please see `UserDetailService` in the [reference](http://docs.spring.io/spring-security/site/docs/5.0.0.M3/reference/htmlsingle/#tech-userdetailsservice).

After you create your custom `UserDetailsService`, then you can configure it via `HttpSecurity.userDetailsService()`
