### ISSUE TITLE
SEC-185: Change LdapUserSearch to allow attributes to be specified

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#447]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-185":https://jira.spring.io/browse/SEC-185?redirect=false]) said:

Currently any calls to LdapUserSearch objects are attempting to pull back all attributes from the directory. The method signature should be changed to allow the authenticator to pass the required list of attributes to it if this has been set (or null for all attributes).

**Comment by linuxjackto1** [comment]
thanks www.movied.org
