### ISSUE TITLE
SEC-186: ExceptionTranslationFilter missing in reference documentation

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#448]
["Rusty Wright":https://jira.spring.io/secure/ViewProfile.jspa?name=lumpynose](Migrated from ["SEC-186":https://jira.spring.io/browse/SEC-186?redirect=false]) said:

ExceptionTranslationFilter is missing in the reference documentation.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
