### ISSUE TITLE
OpenID Connect UserInfo request: issue accept header

### ISSUE THREAD

**Issue by ghsnd** [spring-projects/spring-security#4481]
### Summary
Asking user info using OpenID Connect fails because of the accept header.
*I'm not sure if this is an issue for Spring Security or the OpenID Connect provider I use (Gluu Server).*

### Actual Behavior
The OpenID Connect protocol allows to request information about the authenticated user to the OpenID Connect Provider (OP). This is done via the [UserInfo request](http://openid.net/specs/openid-connect-core-1_0.html#UserInfoRequest). This fails because the OP rejects the request based on the HTTP accept header, which is set to `application/json`. It works when the header is omitted.

### Expected Behavior

The OP should return the User Info.

### Details

The piece of code responsible for setting the header is [this line](https://github.com/spring-projects/spring-security/blob/c872499eee8d212b6662849e0fde057b0221e3fd/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/user/nimbus/NimbusOAuth2UserService.java#L155) in `org.springframework.security.oauth2.client.user.nimbus.NimbusOAuth2UserService`:

```java
httpRequest.setAccept(MediaType.APPLICATION_JSON_VALUE);
```

When commented out, it works.

The specification does not mention that the request may or may not contain an accept header (while it specifically mentions this for the content type in the response). So maybe the Gluu Server is too strict on this, or maybe this header is not necessary at all.

### Version

Applies at least to 5.0.0.Mx and the snapshot version. Did not check other versions.

**Comment by jgrandja** [comment]
@ghsnd Sorry for the delayed response on this. Yes, you are correct, the Accept header is not necessary. I will remove it and push the change shortly.

**Comment by jgrandja** [comment]
@ghsnd It's been pushed to master. Try it out and let me know if you have any other issues.

**Comment by ghsnd** [comment]
@jgrandja I tested it and it works. Thanks!

**Comment by jgrandja** [comment]
Excellent. No worries.
