### ISSUE TITLE
Spring Webflux : Avoid reauthentication in Basic

### ISSUE THREAD

**Issue by adrienleroy** [spring-projects/spring-security#4483]
When using spring security with spring webflux, the authenticationmanager is called everytime.
I am expecting spring security to use the session and authenticate only once as not using spring webflux : https://github.com/spring-projects/spring-security/issues/301

I am using springs security and webflux RC3.

Here is how I configure spring security : 
`@EnableWebFluxSecurity
public class ApplicationConfig {

@Bean
SecurityWebFilterChain httpSecurity(HttpSecurity http) throws Exception 
{
    return http.authorizeExchange()
            .pathMatchers("/myroute/**").authenticated()
            .anyExchange().permitAll()
            .and()
            .build();
}

@Bean
public ReactiveAuthenticationManager authenticationManager() {
    return new MyAuthenticationManager();
}`

I first post this on stackoverlow : https://stackoverflow.com/questions/45463383/spring-webflux-security-and-session-authenticate-at-each-request

**Comment by adrienleroy** [comment]
I manage to do what I want, by creating this quick and dirty AuthenticationWebFilter

[LMAuthenticationWebFilter.txt](https://github.com/spring-projects/spring-security/files/1197122/LMAuthenticationWebFilter.txt)

**Comment by dqqzj** [comment]
do you hava a demo about webflux and security? i need it very mouch! if you hava that,please help me!ok?

**Comment by eleftherias** [comment]
I'm glad to hear you figured this out.

FYI HTTP Basic Authentication does not use the session in Reactive applications #4825
