### ISSUE TITLE
Question: securing Resource Servers via OAuth in version 2?

### ISSUE THREAD

**Issue by hildo** [spring-projects/spring-security#4485]
Hi.  This is a question. not a bug report.  I've played around with the OAuth2 client support, and that's working well.  I'm looking how I can update my existing application to use this new support for OpenId (as that will be very useful for me).  My application currently uses the spring-security-oauth2 libraries and their annotations.

When I perform the migration, I assume I will no longer need the spring-security-oauth2 module dependency, as this functionality is moving into the Spring Security module itself.  So, where I am currently using the EnableOAuth2Client annotation from the old module, I would stop using that annotation and, instead, use the oauth2Login() method of the HttpSecurity object passed into my WeSecurityConfigurerAdapter.

However, I have other modules that don't use the EnableOAuth2Client annotation.  They use the EnableResourceServer annotation, to ensure that anything calling those services has a token.  Will there be equivalent changes in the Spring Security 2.0 to facilitate that?  If there is already documentation covering this, I'd be happy to read it.  I just haven't been able to find it.

For the record, I'm not interested in the EnableAuthServer annotation from the oauth2 module.  None of my code implements an AuthServer.  I'm more interested in what the expectation will be to secure resource servers, and if there is a implementation plan for it.

Thanks for any information

**Comment by vpavic** [comment]
> Will there be equivalent changes in the Spring Security 2.0 to facilitate that?

I assume you've meant Spring Security 5.0 here.

The 5.0 release is focused on providing Client support, while Resource Server should follow in 5.1 release. You can refer to [this comment](https://github.com/spring-projects/spring-security-oauth/pull/675#issuecomment-315830967) by @jgrandja for more info.

So for the time being you should still use `org.springframework.security.oauth:spring-security-oauth2` for Resource Server support. The [`2.2.0.RELEASE` was released](https://spring.io/blog/2017/07/28/spring-security-oauth-2-2-released) recently with some nice improvements.

**Comment by hildo** [comment]
Yes, I did mean that.  Apologies for any confusion.  Thanks for the advice.  It's good to hear that the modules are not mutually exclusive and can be used at the same time.  I will plan on continuing using that module for the resource server.  I'll have a look at the new release of oauth2.
