### ISSUE TITLE
hasRole does not support SpEL

### ISSUE THREAD

**Issue by manish-in-java** [spring-projects/spring-security#4486]
Please refer to [this StackOverflow post](https://stackoverflow.com/questions/45488556/dynamic-role-value-in-spring-postauthorize-annotation). Expressions like `@PreAuthorize(hasRole('ROLE_' + #user.role)` do not work as `hasRole` does not appear to support SpEL. It will be useful to have `hasRole` support SpEL as it will allow dynamic role checking in many more number of scenarios.

**Comment by eleftherias** [comment]
Closing as answered, since the linked StackOverflow post has been answered.
