### ISSUE TITLE
SEC-188: SecurityContextHolder JavaDoc error

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#449]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-188":https://jira.spring.io/browse/SEC-188?redirect=false]) said:

From acegisecurity-developer:

Javadoc for org.acegisecurity.context.SecurityContextHolder: "Associates a
given SecurityContext with the current execution thread and any new threads
the current execution thread may spawn." It can confuse users, as I know
InheritableThreadLocal no longer used in SecurityContextHolder, so
SecurityContext will not be associated with new threads which current
execution thread may spawn.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
