### ISSUE TITLE
Add RequestMatcher for the AbstractPreAuthenticatedProcessingFilter

### ISSUE THREAD

**Issue by splavs** [spring-projects/spring-security#4491]
### Summary

AbstractPreAuthenticatedProcessingFilter doesn't have RequestMatcher but AbstractAuthenticationProcessingFilter does.

We have implemented PreAuthenticatedProcessingFilter for the external authentication system, but external authentication system doesn't always send pre-authentication headers. For example for static resources.

### Actual Behavior
PreAuthenticatedProcessingFilter applied for every path handled by Spring Security.
It is not possible to exclude some paths from PreAuthenticatedProcessingFilter.

### Expected Behavior
Seems that we need to add RequestMatcher to the AbstractPreAuthenticatedProcessingFilter.
Something like we have in the AbstractAuthenticationProcessingFilter:
```
if (requiresPreAuthenticationRequestMatcher.matches(request)) ...
```

### Version
4.1.4-RELEASE

### Question
Why RequestMatcher was not added into RequestHeaderAuthenticationFilter/AbstractPreAuthenticatedProcessingFilter?
As soon as for some paths pre authentication headers could be missing and pre authentication not required.

**Comment by eleftherias** [comment]
Fixed in 62c7de0.
