### ISSUE TITLE
Create migration guide for OAuth client

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#4494]
We need to provide a migration guide for users wanting to migrate their current Spring Security OAuth client(s) to the new Spring Security 5.0 OAuth client support.

**Comment by AnandkumarSagar** [comment]
Can you please provide path to spring security migration from 4 to 5 guide.

**Comment by jgrandja** [comment]
@AnandkumarSagar This ticket is for creating a migration guide for users that are currently using the OAuth client support in Spring Security OAuth 2.x and want to migrate to the new OAuth client support in Spring Security 5.0.

FYI, OAuth client support does not exist in Spring Security 4.x. It's new in 5.0.

**Comment by jgrandja** [comment]
Closing in favour of #6733
