### ISSUE TITLE
SEC-189: Add accessor for InitialDirContextFactory field in DefaultLdapAuthoritiesPopulator

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#450]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-189":https://jira.spring.io/browse/SEC-189?redirect=false]) said:

Subclasses may required access for obtaining new contexts.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
