### ISSUE TITLE
Default login page gives 404 if config starts with http.antMatcher(ptrn)

### ISSUE THREAD

**Issue by destan** [spring-projects/spring-security#4505]
### Summary

When using `antMatcher` method immediately after `http` to configure it default login page at /login gives 404. However if I use `.authorizeRequests()` first and then use `.antMatchers()` then default login page is shown.

I would expect the default login page to work properly with:

```
		http
			.antMatcher("/secured/**")
			.authorizeRequests()
			.anyRequest()
			.hasRole("USER")
			.and().formLogin();
```

because I think calling `.antMatcher()` immediately after `http` is valid as seen here: http://docs.spring.io/spring-security/site/docs/5.0.0.M3/reference/htmlsingle/#multiple-httpsecurity

### Configuration

See sample class below.

### Version

```
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.0.M3</version>
		<relativePath/>
	</parent>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
	</dependencies>
```

### Sample

Following is the complete executable application:

```
package com.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;
import org.springframework.core.annotation.Order;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}
}

@RestController
class ExampleController {

	@GetMapping("/secured")
	String secured() {
		return "this is secured";
	}

	@GetMapping("/free")
	String free() {
		return "this is FREE";
	}

}

@Configuration
@EnableWebSecurity
class NonApiSecurityConfigurationAdapter extends WebSecurityConfigurerAdapter {

	@Autowired
	@Profile("dev")
	public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
		auth.inMemoryAuthentication()
			.withUser("user")
				.password("user")
				.roles("USER");
	}

	@Override
	protected void configure(HttpSecurity http) throws Exception {

		// This works, when call /secured it redirects to /login and the default login page is shown
		http
			.authorizeRequests()
			.antMatchers("/secured/**")
			.hasRole("USER")
			.and().formLogin();

		// When we replace above http config with the below one, and then
		// call /secured it redirects to /login and default login page at /login gives 404.
		
//		http
//			.antMatcher("/secured/**")
//			.authorizeRequests()
//			.anyRequest()
//			.hasRole("USER")
//			.and().formLogin();
	}

}
```

**Comment by rwinch** [comment]
This is expected because the first `antMatchers` states that the entire HttpSecurity is only going to work if it starts with `/secured/` and the `formLogin` is by default going to be `/login`. To resolve the issue you need to provide something like:

```java
		http
			.antMatcher("/secured/**")
			.authorizeRequests()
				.anyRequest().hasRole("USER")
				.and()
			.formLogin()
				.loginPage("/secured/login");
```

**Comment by destan** [comment]
@rwinch however when using your suggested config, we can't use default login page. right?

**Comment by destan** [comment]
to make default login page work with `http.antMatcher("/secured/**")` I added another `WebSecurityConfigurerAdapter ` and it really worked (`/secured` redirects to default login and default login page works):

```java
@Order(1)
@Configuration
@EnableWebSecurity
class NonApiSecurityConfigurationAdapter extends WebSecurityConfigurerAdapter {

	@Autowired
	@Profile("dev")
	public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
		auth.inMemoryAuthentication()
				.withUser("user")
				.password("user")
				.roles("USER");
	}

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.antMatcher("/secured/**")
			.authorizeRequests()
			.anyRequest()
			.hasRole("USER")
			.and().formLogin();
	}

}

@Order(2)
@Configuration
class NonApiSecurityConfigurationAdapterw extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http.formLogin();
	}

}
```

However strangely following didn't work (login page gives 404):

```java
@Configuration
@EnableWebSecurity
class NonApiSecurityConfigurationAdapter extends WebSecurityConfigurerAdapter {

	@Autowired
	@Profile("dev")
	public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
		auth.inMemoryAuthentication()
				.withUser("user")
				.password("user")
				.roles("USER");
	}

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.formLogin().and()
			.antMatcher("/secured/**")
			.authorizeRequests()
			.anyRequest()
			.hasRole("USER");
	}

}
```

@rwinch do you still think this is the expected/intended behavior?

**Comment by rwinch** [comment]
> @rwinch do you still think this is the expected/intended behavior?

Yes

**Comment by destan** [comment]
how so?

although it has no `antMatcher` restrictions before it, still it doesn't work at the last snippet.
why it makes any difference when I put `http.formLogin()` into another config?

**Comment by rwinch** [comment]
> why it makes any difference when I put http.formLogin() into another config?

Because "another config" does not have a restriction of "/secured/" on it and it is the configuration that is handling the form login. Each HttpSecurity is it's own configuration for a "slice" of the application.

**Comment by sasi040** [comment]
@rwinch thank you this answer helped us. 

But I have one more question if I configure multiple HttpSecurity antMatcher's and specified the order of them, the security rules are only applied first ordered configuration only. 

For example: when I tried this "http://localhost:8080/sasi" it is redirecting to login page for authentication.

whereas when i tried "http://localhost:8080/hello" it is directly hitting the restend point. 

Please see the below code: 

public class SecurityConfig {

    @EnableWebSecurity
    @Order(1)
    static class clas2 extends WebSecurityConfigurerAdapter{
        @Override
        protected void configure(HttpSecurity http) throws Exception {
            http.antMatcher( "/sasi/**" )
                    .authorizeRequests()
                    .antMatchers( "/sasi" ).hasRole( "USER" )
                    .and()
                    .formLogin();

            System.out.println("is sasi got till here!!!");
        }

    }

    @EnableWebSecurity
    @Order(3)
    static class clas1 extends WebSecurityConfigurerAdapter{
        @Override
        protected void configure(HttpSecurity http) throws Exception {
            http.antMatcher( "/hello/**" )
                    .authorizeRequests()
                    .antMatchers( "/hello/desc").permitAll()
                   .antMatchers( "/hello/name").hasRole( "USER" )
                    .antMatchers("/hello").hasRole( "USER" )
                    .and()
                    .formLogin();
        }

    }

    @Order(2)
    @EnableWebSecurity
    static class NonApiSecurityConfigurationAdapterw extends WebSecurityConfigurerAdapter {

        @Override
        protected void configure(HttpSecurity http) throws Exception {
            http.formLogin();
        }

        @Autowired
        protected void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
            auth.inMemoryAuthentication().passwordEncoder( NoOpPasswordEncoder.getInstance()).withUser("user").password("p").roles("USER")
                    .and().withUser("admin").password("p").roles("ADMIN");
            }

    }
}
