### ISSUE TITLE
invalidSessionUrl when user log in after session expires

### ISSUE THREAD

**Issue by Jovons** [spring-projects/spring-security#4507]
### Summary

when session expires, spring security somehow remembers this invalid session behavior when next time the user login again.

### Actual Behavior

when session expires and user is asked to log in again, right after the user successfully logged in, the user is directed to the url configured in `invalidSessionUrl`. And psi-probe gives hint:

session attribute: name: SPRING_SECURITY_SAVED_REQUEST | type: org.springframework.security.web.savedrequest.DefaultSavedRequest
-- | --

### Expected Behavior

user login after session expires should not trigger invalidSessionUrl behavior.

### Configuration

`        http.logout()
            .logoutSuccessUrl("/")
            .permitAll()
            .deleteCookies("JSESSIONID")
            .logoutRequestMatcher(new AntPathRequestMatcher("/logout"));`

  `      // session manage TODO.
        http.sessionManagement().invalidSessionUrl("/login?expired").maximumSessions(1).sessionRegistry(sessionRegistry)
            .expiredUrl("/");`

### Version

4.2.3.Release

**Comment by eleftherias** [comment]
Closing in favour of gh-4165.
