### ISSUE TITLE
SEC-190: CaptchaSecurityContextImpl needs to override hashcode()

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#451]
["Aaron Dressin":https://jira.spring.io/secure/ViewProfile.jspa?name=adressin](Migrated from ["SEC-190":https://jira.spring.io/browse/SEC-190?redirect=false]) said:

The HttpSessionContextIntegrationFilter only stores the SecurityContext into the session if the context has "changed" during the filter chain. It uses the hashcode() method to determine if the context has "changed". However, CapchaSecurityContextImpl does not override the default hashcode implementation from SecurityContextImpl, and therefore always returns -1 (assuming the authentication is null), even though the context is human.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
