### ISSUE TITLE
Provide fix for Google iss claim

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#4511]
Google's OpenID Connect implementation issues ID Tokens 
that omit the required `https://` scheme prefix from the `iss` claim.

We need to provide a workaround for this when creating the `IdToken`.

See [15.6.2.  Google "iss" Value](http://openid.net/specs/openid-connect-core-1_0.html#GoogleIss)

**Comment by vpavic** [comment]
@jgrandja That part of the spec is outdated. Google has been issuing ID Tokens with `https://accounts.google.com` value of `iss` claim for some time now (to my knowledge). That's also easily verifiable.

**Comment by jgrandja** [comment]
@vpavic I ran into this issue when I tried accessing `OidcUser.getIssuer()` in the recently added `InMemoryAccessTokenRepository` in `resolveAuthenticationKey()`. An exception was thrown because the `IdToken` claims (associated to the `OidcUser`) did not have the scheme in the `iss` claim. I confirmed it was `accounts.google.com`. I'm actually surprised that Google has not updated their implementation yet.

I tried using my personal and work accounts and same issue for both. Feel free trying with your google account and let me know what happens.

**Comment by vpavic** [comment]
That's interesting. I'm getting `https://accounts.google.com` value for `iss` claim in ID Tokens issued by both Token endpoint (authorization code flow) and Authorization endpoint (implicit flow).

Which exact endpoints are you using? I'm using `https://accounts.google.com/o/oauth2/v2/auth` and `https://www.googleapis.com/oauth2/v4/token`, as advertised by the [Discovery endpoint](https://accounts.google.com/.well-known/openid-configuration).

**Comment by vpavic** [comment]
@jgrandja Any further feedback on this?

This code introduced in b6212cb looks fragile, as provider might use `http://` prefix, especially in development/test/closed environments, which can result in `https://http://example.com` being generated as a value for `iss` claim.

I also don't see any downstream code breaking down if `iss` claim isn't fully inline with the spec.

**Comment by vpavic** [comment]
Looking at the [config you included in Boot PR](https://github.com/spring-projects/spring-boot/pull/10235/files#diff-8424a45804bc243e644a48fab10a7a8c) the Authorization Endpoint and Token Endpoint URIs do differ from the ones advertized in [Discovery endpoint](https://accounts.google.com/.well-known/openid-configuration) so that might indeed be related with your tokens not having scheme in the `iss` claim.

**Comment by jgrandja** [comment]
@vpavic Sorry I missed that [comment](https://github.com/spring-projects/spring-security/issues/4511#issuecomment-325269424).

The endpoint locations I'm using come from the [defaults resource](https://github.com/spring-projects/spring-security/blob/master/samples/boot/oauth2login/src/main/resources/META-INF/oauth2-clients-defaults.yml)...which are older versions. So that explains the difference between your tests and mine.

And yes I just noticed that bug now from the commit in b6212cb. Thansk for catching that!

If the `iss` claim does not contain a scheme then this [line of code](https://github.com/spring-projects/spring-security/blob/master/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/token/InMemoryAccessTokenRepository.java#L64) will break.

Would you be interested in creating a PR to resolve this?

**Comment by vpavic** [comment]
> Would you be interested in creating a PR to resolve this?

Do you have a specific kind of fix in mind?

Considering we've detected the cause of the problem you've encountered to be an outdated version of Google's Token Endpoint, combined with the fact that `2.0.0.M4` is due today, I'd simply revert the b6212cb and take a closer look at this for `2.0.0.M5`.

**Comment by jgrandja** [comment]
@vpavic That makes sense. I'll revert that commit and update the endpoint locations in the defaults file and we may revisit this in M5.
