### ISSUE TITLE
springSecurityFilterChain inside Jersey's ServletContainer

### ISSUE THREAD

**Issue by juanmbellini** [spring-projects/spring-security#4518]
### Summary

I would like to know if it's possible to register the ```springSecurityFilterChain``` (maybe as a ```ContainerRequestFilter```) in a Jersey application (instead of a servlet filter).

What I want to do is handle exceptions using JAX-RS ```ExceptionMapper```. This is the mechanism I use in my projects to return errors to the API consumer, and it would be great to have centralized all kind of errors handlers (including authentication, authorization, and others such as database shut down while executing ```loadUserByUsername(String)``` in the authentication phase).

**Comment by rwinch** [comment]
Thanks for the report!

It is not possible to register Spring Security via a `ContainerRequestFilter`. This would require a non-trivial ammount of work for Spring Security when security is already possible using a standard servlet `Filter`.

One option is to forward any errors within Spring Security to an endpoint that can be handled by JAX-RS. Alternatively, you can extract a strategy that can be used by both Spring Security and JAX-RS.
