### ISSUE TITLE
SEC-191: AclTag class should use the BeanFactoryUtils.beanNamesForTypeIncludingAncestors method to search for the AclManager

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#452]
["Csaba Szotyori":https://jira.spring.io/secure/ViewProfile.jspa?name=csaba](Migrated from ["SEC-191":https://jira.spring.io/browse/SEC-191?redirect=false]) said:

Currently the AclTag class uses the ListableBeanFactory.getBeanNamesForType method to search for the AclManager. But this method ignores bean factory hierarchies, therefore the AclManager must be in the application context of the current web application (parent application contexts are ignored).

It would be really nice to use the BeanFactoryUtils.beanNamesForTypeIncludingAncestors method for locating the AclManager, as it would allow the AclTag to work also in cases where an application context (containing the AclManager) is shared across several web applications.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
