### ISSUE TITLE
SEC-192: Concurrent login checking fails with CAS

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#453]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-192":https://jira.spring.io/browse/SEC-192?redirect=false]) said:

http://forum.springframework.org/showthread.php?t=22422

The CAS authentication provider should call setDetails on the newly created CASAuthenticationToken. Alternatively, this could be done somewhere like AbstractAuthenticationProvider.authenticate, since it is probably common to all providers. Something like:

```
public final Authentication authenticate(Authentication authentication)
    throws AuthenticationException {
    try {
        Authentication result = doAuthentication(authentication);

        if(result.getDetails() == null) {
           result.setDetails(authenitication.getDetails());
        }
    } catch (AuthenticationException e) {
        e.setAuthentication(authentication);
        throw e;
    }
}
```

**Comment by linuxjackto1** [comment]
thanks www.movied.org
