### ISSUE TITLE
SEC-193: Duplicate code in SiteminderAuthenticationProcessingFilter 

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#454]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-193":https://jira.spring.io/browse/SEC-193?redirect=false]) said:

SiteminderAuthenticationProcessingFilter seems to have quite a few methods (getDefaultFilterProcessesUrl, setDetails, filter lifecycle methods) which are the same as those in its base class, AuthenticationProcessingFilter. They can probably be safely removed.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
