### ISSUE TITLE
can somebody tell me why ProviderManager has a private AuthenticationManager parent;

### ISSUE THREAD

**Issue by lexburner** [spring-projects/spring-security#4543]
I am reading the spring-security source code，I am puzzled by this design ， why the ProviderManager  own / manage  a AuthenticationManager parent ?

**Comment by eleftherias** [comment]
Thanks for reaching out. 
This is now covered in the Spring Security [reference documentation](https://docs.spring.io/spring-security/reference/servlet/authentication/architecture.html#servlet-authentication-providermanager):
> `ProviderManager` also allows configuring an optional parent `AuthenticationManager` which is consulted in the event that no `AuthenticationProvider` can perform authentication. 

> In fact, multiple `ProviderManager` instances might share the same parent `AuthenticationManager`. This is somewhat common in scenarios where there are multiple `SecurityFilterChain` instances that have some authentication in common (the shared parent `AuthenticationManager`), but also different authentication mechanisms (the different `ProviderManager` instances).
