### ISSUE TITLE
How enable/disable @EnableGlobalMethodSecurity for @Service methods for testing scenario

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-security#4545]
Hello

All is explained in:

* [How enable/disable @EnableGlobalMethodSecurity for @Service methods for testing scenario](https://stackoverflow.com/questions/46227242/how-enable-disable-enableglobalmethodsecurity-for-service-methods-for-testing)

Not sure if a new annotation for Spring Security should be created or not. It to be applied in Testing.

**Comment by eleftherias** [comment]
I have answered this question in StackOverflow, see link in issue.

**Comment by manueljordan** [comment]
Huge thanks!, solution accepted. Have an excellent weekened!
