### ISSUE TITLE
Referenced class in oauth2login sample, does not exists

### ISSUE THREAD

**Issue by adolfoweloy** [spring-projects/spring-security#4548]
### Summary
I am trying to explore spring-security samples, but for spring-security 5.0.0.M1 the class `AbstractOAuth2UserConverter` which is referenced in `OAuth2LoginAutoConfiguration` does not exists in referenced dependencies.

I have also tried to search for this class in `spring-projects` organization without success.
Is it an issue?

**Comment by jgrandja** [comment]
@adolfoweloy `AbstractOAuth2UserConverter` was removed a while back. Please use the last release M4.
