### ISSUE TITLE
ClientRegistrationAutoConfiguration could be moved to Spring Boot

### ISSUE THREAD

**Issue by adolfoweloy** [spring-projects/spring-security#4549]
### Summary

The class`ClientRegistrationAutoConfiguration` is just available as a sample code for `oauth2login` project (within samples folder of Spring Security 5).

Shouldn't `ClientRegistrationAutoConfiguration` be moved to next Spring Boot version (milestone)?

**Comment by vpavic** [comment]
@adolfoweloy Yes, that is the end goal and there's already some work in progress - see spring-projects/spring-boot#10235

**Comment by jgrandja** [comment]
@adolfoweloy We're planning to get the auto-config classes into Boot M5 at which point these classes will be removed from the Spring Security sample.
