### ISSUE TITLE
SEC-194: RememberMeServices should be available when using BasicAuth logins

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#455]
["Geir Hedemark":https://jira.spring.io/secure/ViewProfile.jspa?name=geir](Migrated from ["SEC-194":https://jira.spring.io/browse/SEC-194?redirect=false]) said:

I am using acegi to provide security for a SOAP service. The service us used by a web frontend.

I would like to let the front end not have to store the password of the user for security purposes. Therefore I would like to use a RememberMe service. The front end would just propagate the cookie to the browser, and copy it back in to the SOAP request on the next response.

AuthenticationProcessingFilter does not match well with my needs since I have no wish to redirect the user to a different JSP page.

My opinion on this (without knowing the architecture of acegi well) would be to let BasicProcessingFilter trigger the loginFail or loginSuccess methods on a RememberMeService.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
