### ISSUE TITLE
Token request structure for Client authentication with Facebook Login

### ISSUE THREAD

**Issue by adolfoweloy** [spring-projects/spring-security#4551]
### Summary

I am trying to use Facebook Login with manual built flow (as described by Facebook Login document), following the Spring Security documentation's approach described at https://github.com/spring-projects/spring-security/tree/5.0.0.M1/samples/boot/oauth2login#facebook-login.

I have configured all the `ClientRegistration` properties for Facebook but when trying to exchange an authorization code for an access token, `NimbusAuthorizationCodeTokenExchanger` is getting `tokenResponse` without success.

### Actual Behavior

As reading method `exchange` from `NimbusAuthorizationCodeTokenExchanger` class, I have realized that we have the following client authentication approaches:

```java
ClientAuthentication clientAuthentication;
if (ClientAuthenticationMethod.POST.equals(clientRegistration.getClientAuthenticationMethod())) {
	clientAuthentication = new ClientSecretPost(clientId, clientSecret);
} else {
	clientAuthentication = new ClientSecretBasic(clientId, clientSecret);
}
```

### Expected Behavior

But when using Facebook login we should send the following request structure (as per Facebook login documentation https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow):

```
GET https://graph.facebook.com/v2.10/oauth/access_token?
   client_id={app-id}
   &redirect_uri={redirect-uri}
   &client_secret={app-secret}
   &code={code-parameter}
```

How should we send this request structure? I would like to know if it could be considered an issue and if there is something addressing this problem for future releases.

### Version

I am using Spring Security 5.0.0.M4

**Comment by jgrandja** [comment]
@adolfoweloy Although the [Facebook login](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow#confirm) documentation specifies to use a HTTP GET request when exchanging the auth code for an Access Token, HTTP POST also works. So configuring `ClientRegistration.clientAuthenticationMethod` with `ClientAuthenticationMethod.POST` works and is preferred over GET, given that GET requests may be logged (with full query parameters) by servers which contain the **client secret**.

Please use the latest release M4. This has been tested and works so I'll close this issue. If you have any other questions/concerns I can re-open.
