### ISSUE TITLE
SEC-195: Create Acegi-backed CAS3 AuthenticationHandler

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#456]
["Scott Battaglia":https://jira.spring.io/secure/ViewProfile.jspa?name=sbattaglia](Migrated from ["SEC-195":https://jira.spring.io/browse/SEC-195?redirect=false]) said:

Create an Acegi-backed CAS3 AuthenticationHandler similar to the CAS2 Password Handler to allow people to try out CAS3 by using their already defined Acegi AuthenticationManager

**Comment by linuxjackto1** [comment]
thanks www.movied.org
