### ISSUE TITLE
Provide InMemoryUserDetailsManager shortcuts 

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-security#4564]
We've notices in the Spring Boot samples that constructing and `InMemoryUserDetailsManager` for test users can be quite cumbersome. Usually looking something like this:

```java
@Bean
public UserDetailsService userDetailsService() throws Exception {
	InMemoryUserDetailsManager manager = new InMemoryUserDetailsManager();
	manager.createUser(
			User.withUsername("user").password("secret").roles("USER").build());
	return manager;
}
```

There is a convenience method that takes a `Properties`, but that's also a little hard to use in a single line. If it were changed to accept a `Map` we could do:

```java
return new InMemoryUserDetailsManager(Collections.singletonMap("user", "secret,USER"));
```

Perhaps even better would be if `String...` parameters could be supplied, then we could do:

```java
return new InMemoryUserDetailsManager("user=secret,USER");
```

**Comment by philwebb** [comment]
See https://github.com/spring-projects/spring-boot/issues/10349 for more background.

**Comment by rwinch** [comment]
@philwebb Have you seen `UserDetailsResourceFactoryBean`, `UserDetailsManagerResourceFactoryBean`, and `UserDetailsRepositoryResourceFactoryBean`? You can use `InMemoryResource` if you do not want an external resource. Does that help?

**Comment by philwebb** [comment]
I hadn't seen those no. So we'd do something like this?

```java
@Bean
public InMemoryUserDetailsManager userDetailsManager() throws Exception {
    return UserDetailsManagerResourceFactoryBean.fromResource(new InMemoryResource("user=secret,USER")).getObject();
}
```

That doesn't seem too bad to me.

**Comment by rwinch** [comment]
@philwebb Since it is a `FactoryBean` you don't need to do `.getObject()`. 

```java
@Bean
public UserDetailsManagerResourceFactoryBean userDetailsManager() throws Exception {
    return UserDetailsManagerResourceFactoryBean.fromResource(new InMemoryResource("user=secret,USER"));
}
```
I went ahead and made a convenience method to do it from a `String`

```java
@Bean
public UserDetailsManagerResourceFactoryBean userDetailsManager() throws Exception {
    return UserDetailsManagerResourceFactoryBean.fromString("user=secret,USER");
}
```
Personally, I don't really like using a String as you don't know if it works until you run it. I prefer to use the constructor. Previously, it required a `Collection`, but I added a varargs constructor as it was something I had been meaning to do anyways. So you can do something like this:

```java
@Bean
public InMemoryUserDetailsManager udm() {
    return new InMemoryUserDetailsManager(User.withUsername("user").password("secret").roles("USER").build());
}
```

You can also do something like this if you want multiple users and no need to repeat the configuration:

```java
@Bean
public InMemoryUserDetailsManager udm() {
    UserBuilder user = User.withUsername("rob").password("secret").roles("USER");
    return new InMemoryUserDetailsManager(user.build(), user.username("phil").build());
}
```

**Comment by philwebb** [comment]
Sweet thanks!

I think

```java
@Bean
public InMemoryUserDetailsManager udm() {
    return new InMemoryUserDetailsManager(User.withUsername("user").password("secret").roles("USER").build());
}
```

Is the best option for us.

**Comment by rwinch** [comment]
Thanks for the report and quick responses @philwebb It sounds as though this issue is resolved, so I'm going to close it. Please reopen if I was mistaken.
