### ISSUE TITLE
SEC-196: Update web site and documentation to reference JA-SIG CAS

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#457]
["Scott Battaglia":https://jira.spring.io/secure/ViewProfile.jspa?name=sbattaglia](Migrated from ["SEC-196":https://jira.spring.io/browse/SEC-196?redirect=false]) said:

The documentation and site all reference Yale CAS.  They should reference JA-SIG CAS and point to http://www.ja-sig.org/products/cas/

**Comment by linuxjackto1** [comment]
thanks www.movied.org
