### ISSUE TITLE
SEC-197: ConcurrentSessionController should count non-expired Sessions only

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#458]
["Brian Yarger":https://jira.spring.io/secure/ViewProfile.jspa?name=byarger](Migrated from ["SEC-197":https://jira.spring.io/browse/SEC-197?redirect=false]) said:

With ConcurrentSession support enabled, its very common for a user to close their browser without logging out, thereby locking themselves out of the app until their session expires.  

I have added a function to my admin to "logout" an active user, bascially calling SessionInformation.expireNow() for each session beloging to him.  

But, after doing this the user still can't logon because ConcurrentSessionController just counts how many SessionInformation objects are returned from getAllSessions.  Until the HttpSession expires or the logged out user hits the site again (triggering a HttpSession invalidation) the user cannot login again.  

If the ConcurrentSessionController.checkAuthenticationAllowed method counted non-expired sessions instead of all sessions, this would allow the user to log back in (even though he has an abondonded HttpSession) and continue to use the system.

**Comment by spring-issuemaster** [comment]
This issue duplicates #506

**Comment by linuxjackto1** [comment]
thanks www.movied.org
