### ISSUE TITLE
ClientRegistration Support baseUrl in template

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4589]
### Summary

Instead of needing to type `{scheme}://{serverName}:{serverPort}{contextPath}` we should also support `{baseUrl}` (or some similar variable name) that composes all of those values. This should be in addition to the existing variables.

**Comment by rwinch** [comment]
Just setting a Milestone. Can push if necessary

**Comment by jgrandja** [comment]
I'll set the new uri variable name to be `{baseRedirectUrl}`

**Comment by jgrandja** [comment]
We may want to re-consider renaming from `baseRedirectUrl` to `baseUrl`
