### ISSUE TITLE
SEC-198: AccessDeniedException removes role visibility from authz:authorize tags

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#459]
["Tim Nolan":https://jira.spring.io/secure/ViewProfile.jspa?name=katentim](Migrated from ["SEC-198":https://jira.spring.io/browse/SEC-198?redirect=false]) said:

My application has a role dependent JSP elements, where roles are determined via the authz:authorize tags.

If a URL is hit that throws an AccessDeniedException (not a usual thing I guess, but still...), the user's roles are no longer visible to the authz:authorize tags.

PS - I'll see if I can determine the cause and generate a patch.

**Comment by spring-issuemaster** [comment]
This issue depends on #513

**Comment by linuxjackto1** [comment]
thanks www.movied.org
