### ISSUE TITLE
Consider enforcing unique ClientRegistration.redirectUri

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#4592]
We should consider enforcing a unique `redirectUri` for each `ClientRegistration` as this provides more security.

**Comment by rwinch** [comment]
Personally....I think enforcing is a bit too Strong. As long as that is our default, I think we are in good shape

**Comment by jgrandja** [comment]
Yeah I guess it would be too strict. Ok let's leave as is.
