### ISSUE TITLE
AuthorizationCodeAuthenticationProvider requires JwtDecoderRegistry

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4594]
### Summary

Currently `AuthorizationCodeAuthenticationProvider` requires `JwtDecoderRegistry` which is a jwt dependency. However, I believe this should be able to authenticate just a straight OAuth2 exchange.

We should perhaps move the dependency somewhere else.

**Comment by jgrandja** [comment]
Resolved via f8a9077
