### ISSUE TITLE
Consider moving `CommonOAuth2Provider` to Spring Security

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-security#4597]
Instead of using `spring-security-oauth2-client-templates.properties` for common provider defaults, we updated the auto-config in Boot to use [this](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/client/CommonOAuth2Provider.java). This seems like it could live in Spring Security instead of the properties file.

**Comment by philwebb** [comment]
Even if `CommonOAuth2Provider` doesn't move I think that `spring-security-oauth2-client-templates.properties` should be deleted. It feels odd that there is a property file in Spring Security that defines keys in Spring Boot form.

**Comment by jgrandja** [comment]
@philwebb I added `spring-security-oauth2-client-templates.properties` to Spring Security based on my PR review [comment](https://github.com/spring-projects/spring-boot/pull/10235#discussion_r139608390) and this [comment](https://github.com/spring-projects/spring-boot/pull/10235#discussion_r139892688).

However, given that a different approach was taken in the recent PR,  `spring-security-oauth2-client-templates.properties` will be removed from Spring Security.

**Comment by philwebb** [comment]
@jgrandja Yeah, and still think it makes sense to have those default in Spring Security in case users want them without Spring Boot. I'm just don't think we should use the property name format from Boot (in case we want to evolve it).

**Comment by jgrandja** [comment]
Related #4598

**Comment by jgrandja** [comment]
@philwebb I'll take care of this at some point next week.

**Comment by jgrandja** [comment]
Thanks for the contribution @philwebb ! Much nicer approach vs. properties file. This is now in master.
