### ISSUE TITLE
SEC-199: Contacts sample throws NestedServletException (500) instead of Access denied! (403) page

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#460]
["Tim Nolan":https://jira.spring.io/secure/ViewProfile.jspa?name=katentim](Migrated from ["SEC-199":https://jira.spring.io/browse/SEC-199?redirect=false]) said:

Logged on as 

Manually entered URL http://localhost:8080/contacts/secure/del.htm?contactId=2
NB - You have to manually enter the URL, but still, the behaviour doesn't appear to be as intended

Tomcat throws:
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.acegisecurity.AccessDeniedException: Access is denied
...
root cause

org.acegisecurity.AccessDeniedException: Access is denied

**Comment by linuxjackto1** [comment]
thanks www.movied.org
