### ISSUE TITLE
EnableWebFluxSecurityTests.CustomPasswordEncoder Test Failing in Travis CI

### ISSUE THREAD

**Issue by shazin** [spring-projects/spring-security#4604]
### Summary

EnableWebFluxSecurityTests.CustomPasswordEncoder Test Failing in Travis CI with the following exception. All Tests are Succeeding when running in Local using gradlew build.

org.springframework.security.config.annotation.web.reactive.EnableWebFluxSecurityTests$CustomPasswordEncoder > passwordEncoderBeanIsUsed FAILED
    java.lang.AssertionError at EnableWebFluxSecurityTests.java:175
        Caused by: org.junit.ComparisonFailure at EnableWebFluxSecurityTests.java:175
1008 tests completed, 1 failed
:spring-security-config:test FAILED

### Actual Behavior

EnableWebFluxSecurityTests.CustomPasswordEncoder Test Failing in Travis CI

### Expected Behavior

All Tests to succeed

### Version

Current master branch

**Comment by rwinch** [comment]
Thank for the report! This is now fixed in #4607
