### ISSUE TITLE
Spring Security Snapshot Metadata

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4609]
### Summary

Spring Security is experiencing issues with Spring Security's SNAPSHOT Maven metadata due to https://www.jfrog.com/jira/browse/RTFACT-12507

Related https://github.com/spring-projects/spring-boot/issues/10559

**Comment by eleftherias** [comment]
Closing since this has been fixed in Artifactory https://www.jfrog.com/jira/browse/RTFACT-12507
