### ISSUE TITLE
SEC-200: Contacts sample - logging off twice causes IllegalStateException

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#461]
["Tim Nolan":https://jira.spring.io/secure/ViewProfile.jspa?name=katentim](Migrated from ["SEC-200":https://jira.spring.io/browse/SEC-200?redirect=false]) said:

Log on as marissa.
Copy logout URL.
Logout.
Enter logout URL manually (effectively logging out again)
Application throws: java.lang.IllegalStateException: Cannot create a session after the response has been committed

Again, not usual use-case, but could probably be handled better.

**Comment by spring-issuemaster** [comment]
This issue depends on #512

**Comment by linuxjackto1** [comment]
thanks www.movied.org
