### ISSUE TITLE
WebMvcConfigurerAdapter in Spring Web MVC is deprecated

### ISSUE THREAD

**Issue by spazbob** [spring-projects/spring-security#4612]
### Summary

Documentation for the current 5.0.0.M5 [here](https://docs.spring.io/spring-security/site/docs/5.0.0.M5/reference/htmlsingle/#hello-web-security-java-configuration) instructs use of Spring Web's WebMvcConfigurerAdapter, but this class was deprecated in Spring 5.0 [here](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/config/annotation/WebMvcConfigurerAdapter.html)

### Actual Behavior

Docs and code use deprecated classes from Spring Web.

### Expected Behavior

Docs and code should be updated to use non-deprecated classes from Spring Web.

### Configuration

N/A

### Version

Spring Security 5.0 M5

### Sample

N/A

**Comment by rwinch** [comment]
Thanks for the report! This is now fixed in master
