### ISSUE TITLE
Session is created on every request

### ISSUE THREAD

**Issue by Bessonov** [spring-projects/spring-security#4613]
@rwinch 

If understand correctly, session is created through CsrfFilter on every request:

https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/csrf/CsrfFilter.java#L90-L102

For me it's a bug or not intended behavior. There are multiple endpoints, which shouldn't be covered by this behavior, ex. /health or robots.txt. Or for me: only one endpoint should create a CSRF-Token. How I can avoid that? I don't found any way to override the CsrfFilter or CsrfConfigurer except to copy&paste. Although to limit access with final and private is a good idea, it's horrible for any extensions. Or I missing something?

Spring Boot 1.5.4
Spring Security 4.2.3

Possible relevant issues:
https://github.com/spring-projects/spring-security/issues/3004
https://github.com/spring-projects/spring-security/issues/4333
https://github.com/spring-projects/spring-security/pull/48

**Comment by rwinch** [comment]
You can use [LazyCsrfTokenRepository](https://github.com/spring-projects/spring-security/blob/4.2.3.RELEASE/web/src/main/java/org/springframework/security/web/csrf/LazyCsrfTokenRepository.java) to ensure it is done lazily.

**Comment by rwinch** [comment]
Closing. Please reopen if you have additional questions.
