### ISSUE TITLE
SEC-201: LdapProvider should not throw IllegalArgumentException for empty user password

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#462]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-201":https://jira.spring.io/browse/SEC-201?redirect=false]) said:

The Assert.hasLength should probably be changed to Assert.notNull. A null password would hopefully indicate a programming error. An empty password is a possibility.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
