### ISSUE TITLE
Typo in HttpSecurity::authorizeRequests method javadoc

### ISSUE THREAD

**Issue by bbelovic** [spring-projects/spring-security#4620]
### Summary

Typo in `HttpSecurity::authorizeRequests` method javadoc

### Actual Behavior
Javadoc in part Example Configuration is referring to user "admin" and "user", but provided code sample defines in-memory authentication for user "adminr" (with 'r' at the end) in both code samples.

<pre>
 protected void configure(AuthenticationManagerBuilder auth) throws Exception {
     auth.inMemoryAuthentication().withUser("user").password("password").roles("USER")
            .and().withUser("adminr").password("password").roles("ADMIN", "USER");
        }
</pre>
### Expected Behavior

Javadoc should be consistent with username in text and code sample. Use `admin` in both text and code sample.

### Configuration

N/A

### Version

both 4.2.3.RELEASE and 5.0.0 M5

if recognized as typo can I open pull request with fix?

**Comment by rwinch** [comment]
Thanks for the report @bbelovic! Yes this is a typo. I'd love to get a PR for it!

**Comment by rwinch** [comment]
Fixed via #4623
