### ISSUE TITLE
Provide hooks to reactive security to allow usage of JWT with providers like Auth0

### ISSUE THREAD

**Issue by tafypz** [spring-projects/spring-security#4624]
It would be nice to be able to configure ```org.springframework.security.config.web.server.HttpSecurity``` like ```org.springframework.security.config.annotation.web.builders.HttpSecurity``` so that it can be used with external Auth providers like Auth0 to secure rest APIs.

Auth0 provides a spring-security-mvc compatible library at:
https://github.com/auth0/auth0-spring-security-api

**Comment by rwinch** [comment]
@tafypz Can you elaborate on how you want to configure reactive security like the servlet counterpart? Does Auth0 provide reactive libraries?

**Comment by tafypz** [comment]
Auth0 provides a library to handle api authentication that hooks into spring-security-mvc
They do not provide a reactive library however one can extend the non reactive library to create one.
The way the current mvc library configures the security is like so:

```java
              http
                .authenticationProvider(provider)
                .securityContext()
                .securityContextRepository(new BearerSecurityContextRepository())
                .and()
                .exceptionHandling()
                .authenticationEntryPoint(new JwtAuthenticationEntryPoint())
                .and()
                .httpBasic().disable()
                .csrf().disable()
                .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS).and();
```

I have created a reactive ```BearerSecurityContextRepository```, ```JwtAuthenticationEntryPoint``` and ```AuthenticationManager```.  
However I am a bit at a loss to get webflux-security to actually use them (specifying the entrypoint), I tried to configure it like so:
```java
        return http
                .authenticationManager(authenticationManager)
                .securityContextRepository(bearerSecurityContextRepository)
                .httpBasic().disable()
                .formLogin().disable()
                .logout().disable()
                .authorizeExchange()
                    .pathMatchers("/protectedpath.json/v1/**").hasAuthority("read:protected")
                    .pathMatchers("/admin/**").hasAuthority("admin")
                .anyExchange().permitAll()
                .and()
                .build();
```

**Comment by rwinch** [comment]
I don't know that I would use `BearerSecurityContextRepository`. This is a type of authentication, so I would try to authenticate the bearer token with an authentication token. Here is the configuration taken fairly literally...

```java
ExceptionTranslationWebFilter exceptionHandling = new ExceptionTranslationWebFilter();
exceptionHandling.setServerAuthenticationEntryPoint(new JwtAuthenticationEntryPoint());

AuthenticationWebFilter authentication = new AuthenticationWebFilter(authenticationManager);
authentication.setServerSecurityContextRepository(new BearerSecurityContextRepository());
http
	.addFilterAt(exceptionHandling, SecurityWebFiltersOrder.EXCEPTION_TRANSLATION)
	.addFilterAt(authentication, SecurityWebFiltersOrder.AUTHENTICATION)
	.build();
```

Alternatively, consider something like this:

```
ExceptionTranslationWebFilter exceptionHandling = new ExceptionTranslationWebFilter();
exceptionHandling.setServerAuthenticationEntryPoint(new JwtAuthenticationEntryPoint());

AuthenticationWebFilter authentication = new AuthenticationWebFilter(bearerAuthenticationManager);
authentication.setAuthenticationConverter(bearerAuthenticationConverter);

http
	.addFilterAt(exceptionHandling, SecurityWebFiltersOrder.EXCEPTION_TRANSLATION)
	.addFilterAt(authentication, SecurityWebFiltersOrder.AUTHENTICATION)
	.build();
```

I'm going to close this, but if you have additional questions feel free to post here and/or reopen.

**Comment by tafypz** [comment]
Thanks @rwinch this did the trick.

**Comment by rwinch** [comment]
@tafypz Thanks for following up so quickly!
