### ISSUE TITLE
SEC-202: Failing to set manager password on DefaultInitialDirContextFactory causes NullPointerException

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#463]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-202":https://jira.spring.io/browse/SEC-202?redirect=false]) said:

The password should be set to some default value in the class, e.g. "manager_password_not_set"

**Comment by linuxjackto1** [comment]
thanks www.movied.org
