### ISSUE TITLE
SEC-203: Allow setting the AuthenticationManager onto the ConcurrentSessionController for inverted dependency

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#464]
["Jason Carreira":https://jira.spring.io/secure/ViewProfile.jspa?name=jcarreira](Migrated from ["SEC-203":https://jira.spring.io/browse/SEC-203?redirect=false]) said:

Preface: 

I like to split my Acegi configuration up between the core framework configuration and the web-specific stuff with the filters, concurrent session control, etc. Currently, having to set the concurrent session controller as a property of the authentication manager makes this more difficult than it should be. 

It would be good if we could pass the AuthenticationManager to the ConcurrentSessionController and have it register itself in an initialize method (or in the setter for the AuthenticationManager itself). In the meantime I've created my own helper class that just takes both of these as dependencies and has an init method to add the concurrent session controller to the authentication manager in an initialize() method.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
