### ISSUE TITLE
AuthorizationRequestRedirectFilter needs a way to customize errors

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4641]
### Summary

Currently `sendRedirectForAuthorization` can throw an `IllegalArgumentException` if the client registration is not found. This means there is a big stacktrace provided on the screen by default. We should allow some strategy to be used for handling the error (i.e. rendering an error page, forwarding to the error page, etc).

**Comment by jgrandja** [comment]
This issue is no longer valid as `IllegalArgumentException` is not thrown and instead `response.sendError()` is used.
