### ISSUE TITLE
AuthorizationRequest.getScope->getScopes?

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4644]
### Summary

Rename AuthorizationRequest.getScope to getScopes

I think it should be renamed. I realize the OAuth spec uses scope, but that is also a single String and not a Set. Since we have parsed it we should rename it to scopes to differentiate it from the OAuth Spec and to clarify it is multiple values.

**Comment by jgrandja** [comment]
I originally had `getScopes` but renamed it via 0d516ca to be consistent across the board and with spec.

**Comment by rwinch** [comment]
I don't think this is is consistent with the spec. The type for the spec is a String not a Set. Once you parse the String it is scopes. Thoughts?

**Comment by jgrandja** [comment]
Good point. If the attribute is `Set` than it should be `scopes`. This will need to be changed in `ClientRegistration`, `AuthorizationRequest`, `AccessToken`, `TokenResponse` and `OAuth2ClientAuthenticationToken`.

But the property name will remain `spring.security.oauth2.client.registration.google.scope`.
Sound good?

**Comment by rwinch** [comment]
Sounds good. I agree. If it is a String then it stays as scope
