### ISSUE TITLE
Why named SecurityToken?

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4646]
### Summary

`SecurityToken` sounds extremely generic. Why doesn't it contain OAuth in it? If it doesn't contain OAuth in it, perhaps it belongs in core (I don't think so though)? It should also contain `Abstract` in the name

**Comment by jgrandja** [comment]
It was originally named `AbstractToken` but that was too generic as well so it was renamed to `SecurityToken` to explicitly state it's a security-specific token. `AbstractToken` can be any kind of token, including non-security related.

I also feel that `SecurityToken` reads better than `AbstractSecurityToken` and aligns nicely with 

```
public interface SecurityTokenRepository<T extends SecurityToken> {

	T loadSecurityToken(ClientRegistration registration);

	void saveSecurityToken(T securityToken, ClientRegistration registration);

	void removeSecurityToken(ClientRegistration registration);

}
```

I'm not convinced that `OAuth` should be in the name, for example, `OAuth2SecurityToken`. There are quite a few classes that are OAuth-related that don't have `OAuth` in the name. It is defined in the `oauth2` sub-package as well.

**Comment by rwinch** [comment]
> I also feel that SecurityToken reads better than AbstractSecurityToken and aligns nicely with

It might read better, but we should be consistent with our naming conventions. Not many people are going to deal w/ `AbstractSecurityToken` in this respect anyways because they will need a repository that works with a concrete token.

> There are quite a few classes that are OAuth-related that don't have OAuth in the name

I believe the difference is that they refer to actual terminology used be the specification. Is security token used by the specification or is it something that we constructed?

**Comment by jgrandja** [comment]
The spec does not use the terminology Security Token, it strictly uses Access Token. Same with OIDC spec, ID Token is what is referred. They are both Security Tokens same with a JWT, hence the name.

Do you have another name suggestion?

**Comment by rwinch** [comment]
I'm thinking AbstractOAuthToken at this point
