### ISSUE TITLE
Remove ClientRegistrationProperties

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4649]
### Summary

This is possibly related to #4369 but since it is not in the sample itself, I want to ensure we remove it

**Comment by jgrandja** [comment]
@rwinch I'm not seeing how this is related to #4639?
However, I was planning on removing `ClientRegistrationProperties` as it's not needed anymore since the new Boot auto-config came into effect.

**Comment by rwinch** [comment]
I thought it could be related since one of the only places it was actually used is [in the sample](https://github.com/spring-projects/spring-security/blob/d7d64009716af8960ac0ff18b45c955dc13a832b/samples/boot/oauth2login/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/client/ClientRegistrationAutoConfiguration.java#L91) for the temporary auto config. We can keep this a separate issue.
