### ISSUE TITLE
SEC-204: Better detection of malformed text in FilterInvocationDefinitionSourceEditor

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#465]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-204":https://jira.spring.io/browse/SEC-204?redirect=false]) said:

There have been quite a few problems in the forums recently caused by reformatted XML with the newlines in the wrong place. It should be possible to detect this and at least give a warning.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
