### ISSUE TITLE
Create a HandlerMethodArgumentResolver for Access Tokens

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4651]
### Summary

We should create a `HandlerMethodArgumentResolver` for resolving access tokens by registration id

Depends on #4650

**Comment by jgrandja** [comment]
For this implementation we will need to leverage `OAuth2TokenRepository<AccessToken>` and `ClientRegistrationRepository`.

The `HandlerMethodArgumentResolver` may be implemented in these steps:

1) Obtain the `registrationId` and lookup the `ClientRegistration` via `ClientRegistrationRepository`.
2) Get the `AccessToken` by calling `OAuth2TokenRepository.loadToken()` using the `ClientRegistration` and current `Authentication`.
3) Create an instance of `AuthorizedClient` using `ClientRegistration`, `Authentication.getName()` and  `AccessToken` and resolve to this.

**Comment by unlimitedsola** [comment]
I'm currently unable to get `AccessToken` from `OAuth2AuthenticationToken` 😢

**Comment by jgrandja** [comment]
@unlimitedsola The `OAuth2AuthorizedClientService` will allow you to get the `AccessToken` for a specific Client/User association. See the [sample](https://github.com/spring-projects/spring-security/blob/master/samples/boot/oauth2login/src/main/java/sample/web/MainController.java) on how to use it.

**Comment by giang-pham** [comment]
@jgrandja I have some information that I can get using:
`oAuth2RestTemplate.getAccessToken().getAdditionalInformation().get("info")`

When I inject `oAuth2RestTemplate `inside `HandlerMethodArgumentResolver `, it's null.
I'm trying to extract that info and use it as a method argument. Can you suggest me a way to do that?

**Comment by giang-pham** [comment]
update: I figured out that I have to declare oAuth2RestTemplate or any service, repository as final and use Autowired constructor.
