### ISSUE TITLE
AuthorizationRequestRepository.removeAuthorizationRequest should return AuthorizationRequest 

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4652]
### Summary

For the primary use case we need the `AuthorizationRequest` when we perform the remove, so it would make sense for this API to return `AuthorizationRequest` when a remove is performed. This design is not unprecedented as `Map.remove` also returns the value.

**Comment by jgrandja** [comment]
If we change it to:

`AuthorizationRequest removeAuthorizationRequest(HttpServletRequest request)`

than this operation is kinda redundant?

`AuthorizationRequest loadAuthorizationRequest(HttpServletRequest request)`

**Comment by rwinch** [comment]
It isn't necessarily redundant. There may be times we need to load it without removal. Although I'm not sure why that would be.
