### ISSUE TITLE
AuthorizationCodeAuthenticationFilter.AuthorizationResponseMatcher.convert should not be part of a matcher

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4653]
### Summary

`AuthorizationCodeAuthenticationFilter.AuthorizationResponseMatcher.convert` has little to do with matching. This method should be extracted to a method in `AuthorizationCodeAuthenticationFilter`

**Comment by jgrandja** [comment]
@rwinch Yeah I didn't quite look right as a method in the `Matcher`. I did originally have it as a method in `AuthorizationCodeAuthenticationFilter`.
