### ISSUE TITLE
AuthorizationCodeAuthenticationFilter creates two AuthorizationResponseMatcher instances in the constructor

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4654]
### Summary

`AuthorizationCodeAuthenticationFilter` creates two `AuthorizationResponseMatcher` instances in the constructor. We should only have a single instance and it should be maintained in the parent class not maintained again in `AuthorizationCodeAuthenticationFilter`.

Related #4653

**Comment by jgrandja** [comment]
`AbstractAuthenticationProcessingFilter` declares `private RequestMatcher requiresAuthenticationRequestMatcher` so it's hidden from `AuthorizationCodeAuthenticationFilter` and it needs it via `getAuthorizationResponseMatcher()` which gets called from `OAuth2LoginConfigurer.createLoginProcessingUrlMatcher`.

If you can figure out another way to avoid the extra reference that would be ideal.
