### ISSUE TITLE
AuthorizationCodeAuthenticationFilter default url should start with /login/

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4659]
### Summary

To follow the conventions of the other authentication filters we should use a URL that starts with `/login/`. perhaps something like: `/login/oauth2/code` ?

**Comment by jgrandja** [comment]
Makes sense. The URL can be supplied to `AuthorizationCodeAuthenticationFilter` via `OAuth2LoginConfigurer` constructor.

I think `/login/oauth2/authorize/code` .
