### ISSUE TITLE
SEC-206: TokenBasedRememberMeServices using context root when setting cookie paths (inc code)

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#466]
["Tim Kettering":https://jira.spring.io/secure/ViewProfile.jspa?name=timster](Migrated from ["SEC-206":https://jira.spring.io/browse/SEC-206?redirect=false]) said:

In the current version of TokenBased.. it allows the cookie to create the default path based on the request.  This works fine when using the filter based authentication because the root path is usually invoked ("/j_acegi_security_check"), so the cookie gets set with the root path of "/".

However when customizing the login process, or using a controller that does not sit on the root path, the cookie gets set with a non-root path, and falls out of scope when the user browses somewhere else.  For example, if login is handled at /auth/login.action, then the cookie gets set with "/auth" path.  So when the user goes to "/foo", or even the root path "/", the cookie is no longer presented, and the remember-me functionality does not function as expected. 

The above functionality is "technically-correct", but not quite initutive for someone who may be putting together an acegi solution that deviates from the "standard" setup that is documented in the documentation.

So I'm submitting this patch where the behavior is modified so that the context root is set as the path in the cookie by default.  This should not affect how acegi works currently with the standard setup, and will allow cases like mine to work without modification.  

I thought about a more elaborate solution where the user could set the context path as a property in the bean definition, but I was not sure how the acegi developers would want to approach that (what would the default behavior be, etc).. so I'm leaving that up to the submitter to review my patch and make any necessary changes.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
