### ISSUE TITLE
Create data object Authorization(RequestResponse)Exchange

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4660]
### Summary

Just a data object that has AuthorizationRequest and AuthorizationResponse on it Name ideas AuthorizationExchange or AuthorizationRequestResponseExchange

**Comment by jgrandja** [comment]
Given that the request and response are coupled to complete the exchange, I guess we can add this data object that groups it. Not sure what other value it brings other than grouping? I'd be in favor of `AuthorizationExchange`.
