### ISSUE TITLE
AuthorizationCodeAuthenticationFilter should inject ClientRegistrationRepository in constructor

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4661]
### Summary

It is required, so ClientRegistrationRepository should be injected into the constructor. This can clean up afterPropertiesSet too

NOTE: the in memory version cannot be a default because it needs to have registrations populated to work.

**Comment by jgrandja** [comment]
It totally makes sense to have `ClientRegistrationRepository` in the constructor as it is required, however, I wasn't sure how to make this happen given that `OAuth2LoginConfigurer` creates a new `AuthorizationCodeAuthenticationFilter` in it's constructor which means `ClientRegistrationRepository` needs to be supplied to `OAuth2LoginConfigurer` constructor as well.

If you can figure out a way to do this that would be great.

**Comment by rwinch** [comment]
Thanks for the response. Probably need to refactor the `OAuth2LoginConfigurer`

**Comment by jgrandja** [comment]
@rwinch The same issue applies to `AbstractAuthenticationProcessingFilter` and  `OpenIDAuthenticationFilter`.

`AbstractAuthenticationProcessingFilter` doesn't take `AuthenticationManager` in it's constructor and instead asserts it in `afterPropertiesSet`.

`OpenIDAuthenticationFilter` also does some initialization in `afterPropertiesSet`.

Are we planning on requiring `AuthenticationManager` in `AbstractAuthenticationProcessingFilter` constructor?
