### ISSUE TITLE
SEC-205: Allow multiple URLs in DefaultInitialDirContextFactory

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#467]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-205":https://jira.spring.io/browse/SEC-205?redirect=false]) said:

The sun provider should handle this automatically. Just need to make sure the property value isn't rejected.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
