### ISSUE TITLE
OAuth + Actuator

### ISSUE THREAD

**Issue by bsideup** [spring-projects/spring-security#4673]
### Summary

Spring Boot Actuator's `/health` endpoint plays very critical role in the application deployment. Due to the automagical configuration and CoC nature of Spring Boot, it becomes very hard to understand why certain parts of the app become broken when you add/remove starters.
Currently, if one adds Spring Security OAuth with `@EnableOAuth2Sso` to the app with Spring Boot Actuator, `/health` endpoint becomes protected and breaks the deployments where it's being used to check app's status.
OAuth auth doesn't make a lot of sense for the Actuator endpoints because most of them are machine-readable. Also, `spring-boot-security-starter` does not break the `/health` endpoint.

### Actual Behavior

Adding `@EnableOAuth2Sso` to the project with Actuator breaks `/health` endpoint by forcing the authorization.

### Expected Behavior

`@EnableOAuth2Sso` applies the same semantic of "sensitive data" in Actuator and does not force the auth.

### Configuration

```
    compile 'org.springframework.boot:spring-boot-starter-actuator'
    compile 'org.springframework.boot:spring-boot-starter-security'
    compile 'org.springframework.security.oauth:spring-security-oauth2'
```

```
@EnableOAuth2Sso
```

### Version

Spring Boot 1.5.6.RELEASE

**Comment by jgrandja** [comment]
@bsideup Thanks for reporting this issue. It would be extremely helpful if you can publish a sample that reproduces this issue. In the meantime, I will try to reproduce using the specific version of Boot you specified.
I'm wondering if this is related to this [issue](https://github.com/spring-projects/spring-boot/issues/5072)?
Try this [solution](https://github.com/spring-projects/spring-boot/issues/5072#issuecomment-271510520) and see if it resolves.

**Comment by jgrandja** [comment]
@bsideup I was able to reproduce this issue and it's definitely related to filter chain ordering. In order to confirm the same issue you are having can you please provide your `@EnableResourceServer` configuration. I'm wondering if you have something similar to this?

```
@Configuration
@EnableResourceServer
public class ResourceServerConfig extends ResourceServerConfigurerAdapter {

	@Override
	public void configure(HttpSecurity http) throws Exception {
		http
			.authorizeRequests()
				.antMatchers("/**").access("#oauth2.hasScope('api.read')");
	}
}```

**Comment by bsideup** [comment]
Hi @jgrandja,

I don't have `ResourceServerConfigurerAdapter` or `@EnableResourceServer`, just simple Spring Boot app with Actuator and `@EnableOAuth2Sso`.

If I provide Groovy script - will it work as a sample?

**Comment by jgrandja** [comment]
Would prefer java but I'm a little familiar with groovy. We can start with the groovy script you have and go from there.

**Comment by jgrandja** [comment]
@bsideup Are you still having this issue? If not than let's close this. Otherwise, please provide a sample that reproduces the issue. Thanks.

**Comment by rwinch** [comment]
Thanks again for the report. I'm closing due to lack of feedback. Please reopen if you can provide a sample that reproduces the issue.
