### ISSUE TITLE
SEC-207: Implement countermeasures against session attacks

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#468]
["Michael Mayr":https://jira.spring.io/secure/ViewProfile.jspa?name=qammm](Migrated from ["SEC-207":https://jira.spring.io/browse/SEC-207?redirect=false]) said:

Hello,

First let me say that I really like Acegi. It is the best authentication and authorization framework I know.

However, on my last (and first) project using Acegi 1.0.0-RC1 I realized that Acegi is very vulnerable to session attacks. Basically Acegi's security only depends on the attacker not being able to get information contained in the cookie, the JSESSIONID. (Not using cookies wouldn't make it more secure, if someone thinks that.)

But this information can be acquired by an attacker i. e. via eavesdropping, trojans or through browser vulnerabilities.

To illustrate how easy it is to attack Acegi you can try the following with your browser (I use at least one Opera browser as it is the only browser I know that comes with support for editing cookie contents, while for the other browsers you would likely have to search a plugin that can do that.):

Computer 1 (e.g. with Firefox): log into your site with a role that has very high privileges, e.g. administrator role. Now open the cookie manager and copy the value of the JSESSIONID cookie from your site.

Computer 2 (e.g. with Opera): log into your site with a role that has close to zero privileges, e.g. spectator role. Now open the cookie manager, find the JSESSIONID cookie from your site and edit its value to the value you have just copied from Computer1. And bang, you are administrator! 

Of course this is only a pseudo attack as no serious hacker would really acquire the JSESSIONID this way but it proves that Acegi is vulnerable.

But I admit part of the problem lies in the statelessness of the HTTP protocol and the way sessions are realized on this stateless protocol. But the non-existence of countermeasures against session attacks makes me feel uncomfortable. And I think that Acegi should at least come with some configurable countermeasures if it wants to be taken seriously.

Such countermeasures against session attacks could be (also in combination):
- Change the Session ID on every request: You would have one logical session on the server but this is presented to the outside via session ids that change with every request. (I think this would require introducing a session abstraction and not using the one provided by the servlet container)
- Verify that the IP address of every request is the same as the IP address that built the session via successful login. But remember, IP addresses can also be spoofed and sometimes different users share the same IP address. (This would require storing additional information for every session or once again a session abstraction concept.)
- Verify that the user agent hasn't changed from the one used at the beginning (not very secure but sometimes helpful, would also require storing additional information for every session or a session abstraction concept.)
- Use HTTPS and the SSL-ID (very secure, also requires a session abstraction concept.)

Well, for my project I implemented a prototype of the last one. I'll attach it to this issue (file mm.zip).

Basically it provides a simple session abstraction and I reworked the 1.0.0-RC1 versions of ContextIntegrationFilter, AuthenticationProcessingFilter and SecurityEnforcementFilter to not use the standard session but this session abstraction which uses Tomcat's SSL-ID. The rest of Acegi works like before.

You would configure it like this (to give you the idea):

```
<bean id="filterChainProxy" class="org.acegisecurity.util.FilterChainProxy">
    <property name="filterInvocationDefinitionSource">
        <value>
            CONVERT_URL_TO_LOWERCASE_BEFORE_COMPARISON 
            PATTERN_TYPE_APACHE_ANT 
            /**=sessionContextIntegrationFilter,authenticationProcessingFilter,anonymousProcessingFilter,securityEnforcementFilter
        </value>
    </property>
</bean>

<bean id="httpsSessionStore" class="mm.https.TomcatHttpsSessionStore" />

<bean id="sessionContextIntegrationFilter" class="mm.https.SessionStoreContextIntegrationFilter">
    <property name="httpsSessionStore">
        <ref bean="httpsSessionStore" />
    </property>
</bean>

<bean id="authenticationProcessingFilter" class="mm.https.SessionStoreAuthenticationProcessingFilter">
    <property name="authenticationManager">
        <ref bean="authenticationManager" />
    </property>
    <property name="authenticationFailureUrl">
        <value>/login.htm</value>
    </property>
    <property name="defaultTargetUrl">
        <value>/select.html</value>
    </property>
    <property name="filterProcessesUrl">
        <value>/j_acegi_security_check</value>
    </property>
    <property name="httpsSessionStore">
        <ref bean="httpsSessionStore" />
    </property>
</bean>

<bean id="anonymousProcessingFilter" class="org.acegisecurity.providers.anonymous.AnonymousProcessingFilter">
    <property name="key">
        <value>foobar</value>
    </property>
    <property name="userAttribute">
        <value>anonymousUser,ROLE_ANONYMOUS</value>
    </property>
</bean>

<bean id="securityEnforcementFilter" class="mm.https.SessionStoreSecurityEnforcementFilter">
    <property name="filterSecurityInterceptor">
        <ref local="filterInvocationInterceptor" />
    </property>
    <property name="authenticationEntryPoint">
        <ref local="authenticationProcessingFilterEntryPoint" />
    </property>
    <property name="httpsSessionStore">
        <ref bean="httpsSessionStore" />
    </property>
</bean>
```

I'd like to hear what you think.

Regards,
Michael

**Comment by linuxjackto1** [comment]
thanks www.movied.org
