### ISSUE TITLE
SEC-209: Make AbstractProcessingFilter.eventPublisher field protected

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#469]
["Lucas Opara":https://jira.spring.io/secure/ViewProfile.jspa?name=skr3dii](Migrated from ["SEC-209":https://jira.spring.io/browse/SEC-209?redirect=false]) said:

When extending AbstractProcessingFilter class and overriding the method AbstractProcessingFilter.successfulAuthentication( ), eventPublisher attribute is not visible (private). 

In order to keep this functionality from the original method, make attribute eventPublisher protected.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
