### ISSUE TITLE
CustomUserTypesOAuth2UserService should map from client registration id to type

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4692]
### Summary

We should use the id not the a URI for mapping what happens for a particular registration

**Comment by jgrandja** [comment]
I believe the mapping by `URI`, which represents the _UserInfo Endpoint_, is correct.

For example, if we had 2 GitHub clients configured: 
`github-login` and `github-orgs` 
than we would only need to map once using `https://api.github.com/user` -> `CustomGitHubOAuth2User`.

However, if we mapped by `registrationId` than we would need to map **twice**, for example:
`github-login` -> `CustomGitHubOAuth2User`
`github-orgs` -> `CustomGitHubOAuth2User`
