### ISSUE TITLE
UserInfoRetriever should support ParameterizedTypeReference

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4693]
### Summary

UserInfoRetriever should support ParameterizedTypeReference so generics are supported

**Comment by jgrandja** [comment]
@rwinch I just noticed you assigned yourself on this one. I started working on this already as well. Sorry I missed the assignment. How far are you with this?

**Comment by jgrandja** [comment]
@rwinch Apologize again for missing that you assigned yourself this issue. Hopefully you didn't start work on it? Either way, I finished it up and pushed.
