### ISSUE TITLE
SecurityJackson2Modules deserializes "credentials" and "details" wrong

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-security#4698]
* When a null for "credentials" is serialized out as JSON, it gets deserialized back as a String value of "null".
* When a null for "details" is serialized out as JSON, it gets deserialized back as a JSON NullNode.

The point is that both of these fields should round trip back as nulls to allow for a perfect match.

For an example, see test cases in https://github.com/spring-projects/spring-session-data-mongodb/pull/18

**Comment by gregturn** [comment]
I've written a unit test that exposes `null` credentials and `null` details not being handled properly:

```
public class RoundTripMixinTests extends AbstractMixinTests {

	@Test
	public void serializingThenDeserializingShouldWork() throws IOException {
		String principalName = "Frodo";
		SecurityContextImpl context = new SecurityContextImpl();
		context.setAuthentication(new UsernamePasswordAuthenticationToken(principalName, null));

		String serialized = this.mapper.writeValueAsString(context);

		SecurityContextImpl deserialized = this.mapper.readValue(serialized, SecurityContextImpl.class);

		assertThat(deserialized.getAuthentication().getPrincipal()).isEqualTo(context.getAuthentication().getPrincipal());
		assertThat(deserialized.getAuthentication().getCredentials()).isEqualTo(context.getAuthentication().getCredentials());
		assertThat(deserialized.getAuthentication().getAuthorities()).isEqualTo(context.getAuthentication().getAuthorities());
		assertThat(deserialized.getAuthentication().getDetails()).isEqualTo(context.getAuthentication().getDetails());
	}
}
```

I'm trying to find the mixin responsible for this, so I can form a patch.

**Comment by okohub** [comment]
@rwinch 

Hello, I don't want to expose a new issue for this but problem is still existing. 

In UsernamePasswordAuthenticationTokenDeserializer:

```
	private JsonNode readJsonNode(JsonNode jsonNode, String field) {
		return jsonNode.has(field) ? jsonNode.get(field) : MissingNode.getInstance();
	}

```

this method returns MissingNode if field is not found. then:

``` 
Object credentials;
		if (credentialsNode.isNull()) {
			credentials = null;
		} else {
			credentials = credentialsNode.asText();
		}
```

credentialsNode is never null. It should be 

```
credentials.isMissingNode()
```

I can fix it with raising a new issue for this. How can we proceed?

**Comment by gregturn** [comment]
Can you craft a test case exposing the issue?

**Comment by okohub** [comment]
@gregturn @rwinch 

thanks for quick response! :)

here is the sample project with tests:

https://github.com/okohub/mixinproblem

Looks like problem is arising when using object mapper with custom inclusions. So, mixin can be changed to this condition in order to adapt custom inclusions.

```
if (credentialsNode.isNull() || credentialsNode.isMissingNode()) 
```

**Comment by gregturn** [comment]
Most of the team is on holiday this week. If you crafted a PR with a test case and solution I’m sure that would speed up merging.

**Comment by okohub** [comment]
@gregturn thanks, I opened a PR for this.
