### ISSUE TITLE
Store ClientRegistration in AuthorizationRequest to avoid re-resolving redirectUri

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4701]
### Summary

I don't like that we need to re-resolve the ClientRegistration redirectUri in OAuth2LoginAuthenticationFilter. Let's consider storing `ClientRegistration`. Internally we could always provide an implementation that stores the id of the `ClientRegistration` and then restores the `ClientRegistration` with the proper `redirectUrl` if we wanted.

**Comment by jgrandja** [comment]
@rwinch Luckily this was an easy one to fix!

`NimbusAuthorizationCodeTokenExchanger` requires the `redirect_uri` when initiating the _Token Request_ and so it used `ClientRegistration.redirectUri` when I first wrote this way back. And given the uri template variables that it may have, I had that workaround that wasn't pretty.

`OAuth2AuthorizationRequest` wasn't available downstream for `NimbusAuthorizationCodeTokenExchanger` at the time I wrote this but now it is. This fix was as simple as [this](https://github.com/spring-projects/spring-security/commit/b1d56b582167d84386c4307cf0e8672fb93bd5b2#diff-d6686189e48e95e56ba710898c61d0c2R79).
