### ISSUE TITLE
AuthorizedClient does not work for other AbstractOAuth2Token implementations

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4706]
### Summary

Is this intentional? Wouldn't we want to associate ClientRegistration with other implementations?

**Comment by jgrandja** [comment]
@rwinch As per our discussion regarding this issue, we decided to make `OAuth2UserService` a Generic which leverages the types `OAuth2AuthorizedClient` and `OAuth2User` as follows:

```
public interface OAuth2UserService<C extends OAuth2AuthorizedClient, U extends OAuth2User> {

	U loadUser(C authorizedClient) throws OAuth2AuthenticationException;

}
```

Take note of the following design changes as you review:

`OAuth2UserService` (and related impl's)
`OAuth2AuthorizedClient`
`OidcAuthorizedClient`
`OAuth2AuthenticationToken`
