### ISSUE TITLE
SEC-210: TokenBasedRememberMeServices issue with CasProcessingFilter

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#471]
["Wang Yunzhen":https://jira.spring.io/secure/ViewProfile.jspa?name=wangyz](Migrated from ["SEC-210":https://jira.spring.io/browse/SEC-210?redirect=false]) said:

While using TokenBasedRememberMeServices with CasProcessingFilter, TokenBasedRememberMeServices.loginSuccess(HttpServletRequest, HttpServletResponse, Authentication) method gets username and password from Authentication parameter, which is an instance of CasAuthenticationToken actually. As a result, the CAS service ticket opaque value, i.e. ST-2-4WQkmtILdjywaqRaIljuYOYrVPUa5hGlwUs-20, will be used as password to construct signatureValue. However, when we need to perform an auto login, TokenBasedRememberMeServices.autoLogin(HttpServletRequest, HttpServletResponse) method compares password that is decoded from value stored in cookie with user's real password which is loaded from database or somewhere else, and they are not equal at most of the time. So the cookie is always cancelled. Nobody will be remembered.

**Comment by spring-issuemaster** [comment]
This issue depends on #487

**Comment by linuxjackto1** [comment]
thanks www.movied.org
