### ISSUE TITLE
OAuth2AuthorizedClient.principalName -> AuthenticatedPrincipal type

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#4716]
At present, `OAuth2AuthorizedClient.principalName` is a `String`, however, does it make sense to change the type to `AuthenticatedPrincipal`?

**Comment by unlimitedsola** [comment]
I think the 'name' should be string, why we would like change it?

**Comment by jgrandja** [comment]
Given a user has successfully logged in via `oauth2Login`, there will be an `OAuth2AuthorizedClient` instance within the `OAuth2AuthorizedClientService` with the associated `AccessToken`.

Now the user logs out of the system but the `OAuth2AuthorizedClient` instance still remains in `OAuth2AuthorizedClientService` (assuming persistent store) so at this point having `OAuth2AuthorizedClient. AuthenticatedPrincipal` as the type does not make sense since the user is **not** authenticated anymore.

Given this logic, we will leave `OAuth2AuthorizedClient.principalName` as a `String`.
