### ISSUE TITLE
Set-Cookie header present even with STATELESS session management

### ISSUE THREAD

**Issue by muff1nman** [spring-projects/spring-security#4717]
### Summary

It appears that `Set-Cookie` is received on an initial 401 request with session management set to `SessionCreationPolicy.STATELESS`. Successful requests do not exhibit this problem. Debugging reveals that `STATELESS` session management ignored by `ExceptionTranslationFilter`.

### Actual Behavior
Request/response with unexpected `Set-Cookie` during 401:
```
$ curl -vvv  127.0.0.1:8080/airsonic/api
* About to connect() to 127.0.0.1 port 8080 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /airsonic/api HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:8080
> Accept: */*
> 
< HTTP/1.1 401 
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< WWW-Authenticate: Basic realm="Airsonic REST API"
< Set-Cookie: JSESSIONID=559AA20120DF12149D3FF0FB038C53F1;path=/airsonic;HttpOnly
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Mon, 11 Sep 2017 03:29:59 GMT
< 
* Connection #0 to host 127.0.0.1 left intact
{"timestamp":1505100599702,"status":401,"error":"Unauthorized","message":"An Authentication object was not found in the SecurityContext","path":"/airsonic/api"}
```
### Expected Behavior

Request/Response with good authentication correctly does not have `Set-Cookie`
```
$ curl -vvv -H 'Authorization: Basic YWRtaW46YWRtaW4=' 127.0.0.1:8080/airsonic/api
* About to connect() to 127.0.0.1 port 8080 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /airsonic/api HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:8080
> Accept: */*
> Authorization: Basic YWRtaW46YWRtaW4=
> 
< HTTP/1.1 204 
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< Content-Type: application/json;charset=UTF-8
< Date: Mon, 11 Sep 2017 03:30:01 GMT
< 
* Connection #0 to host 127.0.0.1 left intact
```

### Configuration

Code base currently used is here: https://github.com/muff1nman/airsonic/tree/74cc46e70ca1181523e353cac77632c60db80a8c. More specifically, here is the relevant spring security configuration: https://github.com/muff1nman/airsonic/blob/74cc46e70ca1181523e353cac77632c60db80a8c/airsonic-main/src/main/java/org/airsonic/player/security/GlobalSecurityConfig.java
### Version
Spring boot version: 1.5.6.RELEASE

**Comment by muff1nman** [comment]
Initially raised here: https://github.com/spring-projects/spring-boot/issues/1024

**Comment by rwinch** [comment]
Admittedly, `SessionCreationPolicy.STATELESS` is a big confusing. However, it only impacts the look up of a `SecurityContext`. It does not impact the `RequestCache`. You need to separately configure a `NullRequestCache`.

```java
http.requestCache().requestCache(new NullRequestCache()).and()
```
