### ISSUE TITLE
SEC-211: AnonymousProcessingFilter causes IllegalStateException after HttpSession invalidation (ie logout)

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#472]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-211":https://jira.spring.io/browse/SEC-211?redirect=false]) said:

http://forum.springframework.org/showthread.php?t=22987

After a HttpSession is invalidated, which is generally a result of a logout operation, the try..catch..finally block within AuthenticationProcessingFilter is causing an IllegalStateException with text "Cannot create a session after the response has been committed".

This bug appeared only in 1.0.0 RC2 (version 1.10 of AuthenticationProcessingFilter). It did not appear in 1.0.0 RC1.

This was fixed in CVS version 1.11 of the code, which was NOT part of 1.0.0 RC2. It was fixed as part of SEC-183 (which is unrelated to this bug).

**Comment by linuxjackto1** [comment]
thanks www.movied.org
