### ISSUE TITLE
Alternative to package private WebFluxSecurityConfiguration

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-security#4738]
Spring Boot [checks the presence of `WebFluxSecurityConfiguration`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/reactive/WebFluxSecurityConfiguration.java#L32) to figure out if `@EnableWebFluxSecurity` has been triggered by the user. This class is [now package private and broke our build](https://github.com/spring-projects/spring-security/commit/b394ae5d5e29de66c33e57d4401240de9fabb88d).

Could you please reconsider or offer an alternative for us?

Thanks

**Comment by wilkinsona** [comment]
I wonder if we could use `ServerHttpSecurityConfiguration` instead? It too is imported by `@EnableWebFluxSecurity` but is `public`.

**Comment by snicoll** [comment]
@wilkinsona I had a look to that and it's [now package private as well](https://github.com/spring-projects/spring-security/blob/master/config/src/main/java/org/springframework/security/config/annotation/web/reactive/ServerHttpSecurityConfiguration.java#L38)

**Comment by rwinch** [comment]
@snicoll It is probably more accurate to use if the presence of `WebFilterChainProxy` exists since advanced users may create `WebFilterChainProxy` without `WebFluxSecurityConfiguration`. Does that work for you?

**Comment by snicoll** [comment]
@rwinch looks sensible. I've pushed https://github.com/spring-projects/spring-boot/commit/e7cb0be6d83a349b03dcad89287ddbe41f88f443 to restore our build and will ask @mbhave for a review.

**Comment by rwinch** [comment]
Thanks for the fast response. I'm going to close this as it appears you have a fix. If you need anything else, please reopen or create a new ticket.
