### ISSUE TITLE
SEC-213: Allow custom redirects based on "redirect" parameter in AbstractProcessingFilter. successfulAuthentication()

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#474]
["Lucas Opara":https://jira.spring.io/secure/ViewProfile.jspa?name=skr3dii](Migrated from ["SEC-213":https://jira.spring.io/browse/SEC-213?redirect=false]) said:

I found something that is useful to add to the org.acegisecurity.ui.cas.CasProcessingFilter default behaviour.
When working in proxy mode, after receiving a proxy ticket and validating it to CAS, acegi will always redirect the proxied web application to its defaultTargetUrl defined in applicationContext.xml file. 

It would be nice if we could pass an extra parameter from the proxy application to the proxied one like:

/j_acegi_cas_security_check?ticket=ST-{ticket_stuff}&redirect=/redirectToWhereIWantToGoInUrlEncodedForm

and then have Acegi just redirect to the redirect url after validating the ticket.

Proposed solution: 

Change the behaviour of the method AbstractProcessingFilter. successfulAuthentication() by overriding this method in CasProcessingFilter class in order to handle the extra parameter 'redirect' and redirect to its url.

Here is an example of what I have done in a custom class extending CasProcessingFilter: 

/*
- Created on 22-Feb-06
  */
  package org.acegisecurity.ui.cas;

import java.io.IOException;
import java.net.URLDecoder;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.acegisecurity.Authentication;
import org.acegisecurity.context.SecurityContextHolder;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
- @author lucas (Last modified by $Author:   u150161  $)
- @version $Revision:   1.1  $ - $Date:   Mar 07 2006 12:50:00  $
  */
  public class AdvancedCasProcessingFilter extends CasProcessingFilter {
  protected static final Log logger = LogFactory.getLog(AdvancedCasProcessingFilter.class);
  
  protected void successfulAuthentication(HttpServletRequest request,
      HttpServletResponse response, Authentication authResult)
      throws IOException {
      if (logger.isDebugEnabled()) {
          logger.debug("Authentication success: " + authResult.toString());
      }
  
  ```
  SecurityContextHolder.getContext().setAuthentication(authResult);
  
  if (logger.isDebugEnabled()) {
      logger.debug(
          "Updated SecurityContextHolder to contain the following Authentication: '"
          + authResult + "'");
  }
  
  String targetUrl = (String) request.getSession()
                                     .getAttribute(ACEGI_SECURITY_TARGET_URL_KEY);
  request.getSession().removeAttribute(ACEGI_SECURITY_TARGET_URL_KEY);
  
  if (isAlwaysUseDefaultTargetUrl() == true) {
      targetUrl = null;
  }
  
  if (targetUrl == null) {
      targetUrl = request.getContextPath() + getDefaultTargetUrl();
      //ADDED by LOP 22/02/2006 - BEGIN
      if(request.getParameter("redirect") != null) {
          //override targetUrl with the one specified in redirect
          String redirectUrl = request.getParameter("redirect");
          targetUrl = URLDecoder.decode(redirectUrl, "UTF-8");
      }
      //ADDED by LOP 22/02/2006 - END
  }
  
  if (logger.isDebugEnabled()) {
      logger.debug(
          "Redirecting to target URL from HTTP Session (or default): "
          + targetUrl);
  }
  
  onSuccessfulAuthentication(request, response, authResult);
  
  getRememberMeServices().loginSuccess(request, response, authResult);
  
  //TODO : LOP 07/03/2006 : uncomment this when AbstractAuthenticationFilter.eventPublisher is protected
  // Fire event
  ```
  
  //      if (this.eventPublisher != null) {
  //          eventPublisher.publishEvent(new InteractiveAuthenticationSuccessEvent(
  //                  authResult, this.getClass()));
  //      }
  
  ```
  response.sendRedirect(response.encodeRedirectURL(targetUrl));
  ```
  
  }
  }

**Comment by spring-issuemaster** [comment]
This issue relates to #2006

**Comment by linuxjackto1** [comment]
thanks www.movied.org
