### ISSUE TITLE
SEC-215: FilterBasedLdapUserSearch creates invalid DN

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#476]
["Stefan Podkowinski":https://jira.spring.io/secure/ViewProfile.jspa?name=spod](Migrated from ["SEC-215":https://jira.spring.io/browse/SEC-215?redirect=false]) said:

The current Implementation of FilterBasedLdapUserSearch in HEAD will create create DNs that have a invalid comma character at the end of the final DN. E.g. "cn=Stefan Podkowinski,ou=people,dc=my,dc=org,"

Please change the following lines in
acegisecurity/acegisecurity/core/src/main/java/org/acegisecurity/providers/ldap/search/FilterBasedLdapUserSearch.java

from

userDn.append(",");
userDn.append(ctx.getNameInNamespace());

to

String nameInNS = ctx.getNameInNamespace();

if(nameInNS != null && nameInNS.length() > 0) {
   userDn.append(",");
   userDn.append(nameInNS);
}

**Comment by linuxjackto1** [comment]
thanks www.movied.org
