### ISSUE TITLE
No reactive version of AbstractSecurityWebApplicationInitializer class

### ISSUE THREAD

**Issue by getting-started-with-java** [spring-projects/spring-security#4765]
### Summary
Spring Security doesn't intercept HTTP requests when using WebFlux

When I configure a WebFlux application's security using @EnableWebFluxSecurity annotation for a web application, the HTTP requests are not intercepted by Spring Security. I have tried this using Spring Security 5.0.RC1 and Spring Framework 5.0.1.RELEASE. 
I'm using Spring's AbstractAnnotationConfigDispatcherHandlerInitializer to initialize the web application. 

There is no reactive version of AbstractSecurityWebApplicationInitializer to configure SecurityWebFilterChain for the web application based on WebFlux.

Stackoverflow links: 
1. https://stackoverflow.com/questions/47033195/spring-webflux-5-0-release-and-spring-security-5-0-m5
2. https://stackoverflow.com/questions/46325632/how-to-activate-spring-security-in-a-webflux-war-application

**Comment by rwinch** [comment]
Thanks for the report @getting-started-with-java! This is actually an issue with Spring's `AbstractAnnotationConfigDispatcherHandlerInitializer`. See https://jira.spring.io/browse/SPR-16144 for the issue and a workaround
