### ISSUE TITLE
SEC-216: new session created instead of using the old one when cookies are disabled (ie. url rewriting is used).

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#477]
["George Daswani":https://jira.spring.io/secure/ViewProfile.jspa?name=gdaswani](Migrated from ["SEC-216":https://jira.spring.io/browse/SEC-216?redirect=false]) said:

ACEGI creates a new HttpSession (instead of reusing the old one) when cookies are disabled (URL Rewriting is used by the app server instead) hence the redirects fail after login (as the old session which stored the REDIRECT URL is lost).

I've attached a simple web-app that displays this problem (deployed on Tomcat 5.5.15)

Here's an easy way to duplicate the problem

1) Turn off Cookies for the site so Tomcat is forced to use URL rewriting instead of cookies

2) Browse the index.jsp file (which has a link to "login.jsp;jsesssion=GENERATEDSESSIONA)

3) Login jsp page will show up, and said form will be posting to 

"j_acegi_security_check

**Comment by linuxjackto1** [comment]
thanks www.movied.org
