### ISSUE TITLE
SEC-223: Performance of hashCode in AbstractAuthenticationToken

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#479]
["Ulrik Sandberg":https://jira.spring.io/secure/ViewProfile.jspa?name=ulsa](Migrated from ["SEC-223":https://jira.spring.io/browse/SEC-223?redirect=false]) said:

The hashCode implementation in AbstractAuthenticationToken calculates the hashCode of its authorities:

```
public int hashCode() {
    int code = 2305;

    if (this.getAuthorities() != null) {
        for (int i = 0; i < this.getAuthorities().length; i++) {
            code = code * (this.getAuthorities()[i].hashCode() % 7);
        }
    }
    ...
```

There will be two calls to getAuthorities() for each GrantedAuthority. And this would happen every time hashCode is called on an AuthenticationToken that extends AbstractAuthenticationToken.

This would be fine if getAuthorities() simply returned a value, but it does more than that:

```
public GrantedAuthority[] getAuthorities() {
    if (authorities == null) {
        return null;
    }

    GrantedAuthority[] copy = new GrantedAuthority[authorities.length];
    System.arraycopy(authorities, 0, copy, 0, authorities.length);

    return copy;
}
```

The obvious fix for this unnecessary array copying is:

```
public int hashCode() {
    int code = 2305;
    GrantedAuthority[] authorities = this.getAuthorities();

    if (authorities != null) {
        for (int i = 0; i < authorities.length; i++) {
            code = code * (authorities[i].hashCode() % 7);
        }
    }
    ...
```

**Comment by linuxjackto1** [comment]
thanks www.movied.org
