### ISSUE TITLE
SEC-225: DefaultLdapAuthoritiesPopulator should accept an empty groupSearchBase

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#480]
["Bertrand Renuart":https://jira.spring.io/secure/ViewProfile.jspa?name=brenuart](Migrated from ["SEC-225":https://jira.spring.io/browse/SEC-225?redirect=false]) said:

DefaultLdapAuthoritiesPopulator should accept an empty groupSearchBase just as the FilterBasedLdapUserSearch does.
This would allow people to search for groups from the root without making any other assumptions to where the group definitions actually are.

Note: the fix could be as simple as replacing the Assert.hasLength() call in the constructor by Assert.notNull.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
