### ISSUE TITLE
SEC-226: Additional SearchControl properties to the FilterBasedLdapUserSearch to control

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#481]
["Bertrand Renuart":https://jira.spring.io/secure/ViewProfile.jspa?name=brenuart](Migrated from ["SEC-226":https://jira.spring.io/browse/SEC-226?redirect=false]) said:

Would be nice if the FilterBasedLdapUserSearch exposes additional properties to configure the SearchControls.

Although it is already possible to control the timeLimit and the searchScope properties, the implementation doesn't offer any way to set the remaining properties (SearchControls.derefLinkFlag, SearchControls.returningObjFlag, and others).

For the sake of illustration, I personnaly need to set the derefLink to true (which is false by default) in order to cope with an installation with multiple Active Directories where I wanted to let the server dereference the links for me...

PS: just ask if you want me to submit a patch for this...

**Comment by linuxjackto1** [comment]
thanks www.movied.org
