### ISSUE TITLE
SEC-219: FilterInvocationDefinitionSourceEditor tokenizing of URLs

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#483]
["Renat Araslanow":https://jira.spring.io/secure/ViewProfile.jspa?name=tr0nd](Migrated from ["SEC-219":https://jira.spring.io/browse/SEC-219?redirect=false]) said:

there is unable to process url like this one:
/useraction.do?action=register=ROLE_ANONYMOUS 
after proccesing acegi treat register as role name.

this
      // Tokenize the line into its name/value tokens
       String[] nameValue = StringUtils.delimitedListToStringArray(line,
                        "=");
       String name = nameValue[0];
       String value = nameValue[1];

change to this
    String name = StringUtils.substringBeforeLast( line, "=" );
    String value = StringUtils.substringAfterLast( line, "=" );

where is StringUtils - is apache commons lang 2.0 class

here is source of this methods

public static String substringBeforeLast(String str, String separator) {
    if (str == null || separator == null || str.length() == 0 ||
separator.length() == 0) {
        return str;
    }
    int pos = str.lastIndexOf(separator);
    if (pos == -1) {
        return str;
    }
    return str.substring(0, pos);
}
public static String substringAfterLast(String str, String separator) {
    if (str == null || str.length() == 0) {
        return str;
    }
    if (separator == null || separator.length() == 0) {
        return EMPTY;
    }
    int pos = str.lastIndexOf(separator);
    if (pos == -1 || pos == (str.length() - separator.length())) {
        return EMPTY;
    }
    return str.substring(pos + separator.length());
}

**Comment by linuxjackto1** [comment]
thanks www.movied.org
