### ISSUE TITLE
Support CORS with WebFlux

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-security#4832]
As recently highlighted in the [new WebFlux CORS documentation](https://github.com/spring-projects/spring-framework/commit/38040bf3f2b4aaa5c342fedcd12421a2eacc9ae5), MVC and WebFlux CORS support are almost symetrical, so that would be great to have Spring Security support for it, in a similar fashion.

**Comment by rwinch** [comment]
@sdeleuze Thanks for the report! This is fixed in master
