### ISSUE TITLE
Automatically apply .oauth2Login() 

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4837]
### Summary

The default configuration should try to automatically apply `oauth2Login` under some circumstance. Perhaps it is just if spring-security-oauth2-client is on the classpath, perhaps it is if a Bean of type `ClientRegistrationRepository` is available.

**Comment by jgrandja** [comment]
@rwinch This issue is quite old now and at this point I don't think this enhancement is needed. I'm going to close this but if you feel we should still address it then we can revisit it.
