### ISSUE TITLE
SEC-220: Allow ExceptionTranslationFilter to not catch exceptions

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#484]
["Renat Araslanow":https://jira.spring.io/secure/ViewProfile.jspa?name=tr0nd](Migrated from ["SEC-220":https://jira.spring.io/browse/SEC-220?redirect=false]) said:

its need because there is no way to throw  AcegiSecurityException  form selvlet inside.
so i propose to add hook that can be overriden in subclasses. or maybe we add some default behavior to get from some request attribute this exception? what u think?

```
    try {
        chain.doFilter(request, response);

       lastChanceToThrowAcegiSecurityException();

        if (logger.isDebugEnabled()) {
            logger.debug("Chain processed normally");
        }
    } catch (AuthenticationException authentication) {
```

**Comment by spring-issuemaster** [comment]
This issue depends on #460

**Comment by linuxjackto1** [comment]
thanks www.movied.org
