### ISSUE TITLE
SEC-221: AbstractProcessingFilter.onPreAuthentication exceptions should be caught

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#485]
["Fabio Grassi":https://jira.spring.io/secure/ViewProfile.jspa?name=fabio](Migrated from ["SEC-221":https://jira.spring.io/browse/SEC-221?redirect=false]) said:

Exceptions thrown by AbstractProcessingFilter.onPreAuthentication throws should be caught and handled through the unsuccessfulAuthentication method (which is free to re-raise them).

**Comment by linuxjackto1** [comment]
thanks www.movied.org
