### ISSUE TITLE
Update oauth2Login sample guide

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#4858]

**Comment by adolfoweloy** [comment]
@jgrandja, I was reading the document and trying to run a client against a custom oauth2 provider and noticed something that might help on the update of sample guide.

As the `filterProcessesUrl` from `OAuth2LoginAuthenticationFilter` has changed from `/oauth2/authorize/code/*` to `/login/oauth2/code/*`, I think it would be better to update the `README.adoc` from `oauth2login` sample project.

I suggest the following changes on __Default client property values__ section of the document (more specifically at the oauth2-clients-defaults.yml sample declaration)

To replace the definition of the `redirect-uri` property from:
```
redirect-uri: "{scheme}://{serverName}:{serverPort}{baseAuthorizeUri}/{clientAlias}"
```
to
```
redirect-uri: "{scheme}://{serverName}:{serverPort}/login/oauth2/code/{clientAlias}"
```
