### ISSUE TITLE
SEC-222: AbstractAuthenticationToken Hashcode computation

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#486]
["Ulrik Sandberg":https://jira.spring.io/secure/ViewProfile.jspa?name=ulsa](Migrated from ["SEC-222":https://jira.spring.io/browse/SEC-222?redirect=false]) said:

The hashCode implementations in User as well as AbstractAuthenticationToken uses the MOD operator with the value 7. 

```
public int hashCode() {
    int code = 2305;

    if (this.getAuthorities() != null) {
        for (int i = 0; i < this.getAuthorities().length; i++) {
            code = code * (this.getAuthorities()[i].hashCode() % 7);
        }
    }
    ...
```

This has the unfortunate result that when the hashCode of say a GrantedAuthority is dividable by 7, the result of the MOD will be zero. Since it multiplies all other results with itself, the hashCode will evaluate to zero.

I'm not sure of the consequences of this, but since HttpSessionContextIntegrationFilter compares the hashCode of the SecurityContext before and after the filter chain, this could cause some unexpected behaviour.

The obvious question is how often a hashCode of a String evaluates to something dividable by 7. Well, it's actually pretty common. An empty password in the principal does, for example. So does "ROLE_General.ITS" and many others.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
