### ISSUE TITLE
Rename method name to scopes from scope on ClientRegistration$Builder

### ISSUE THREAD

**Issue by kazuki43zoo** [spring-projects/spring-security#4864]
### Summary

I think better that rename method name to `scopes` from `scope` on the `ClientRegistration$Builder` because the method argument allows multiple scopes as follow:

https://github.com/spring-projects/spring-security/blob/86824030f293838acbfe05bbf3072101d914d89c/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/ClientRegistration.java#L191

WDYT?

**Comment by jgrandja** [comment]
@kazuki43zoo The `scope` and `scopes` attribute is used in a few different classes.

For example:

`ClientRegistration.scopes` -> `Set<String>`
`ClientRegistration.Builder.scope` -> `String`
`OAuth2AccessTokenResponse.Builder.scopes` -> `Set<String>`
`OAuth2AccessToken..scopes` -> `Set<String>`

The naming pattern we are following is that the attribute name will be singular for `String` type and plural for `Set` type. The current naming follows this pattern so I will close this.
Thanks for the input though.

**Comment by kazuki43zoo** [comment]
Thanks for your reply!!
I see it. However in another class, there is a place not following above rule.

e.g.)

* UserBuilder#roles
* UserBuilder#authorities

```java
public UserBuilder roles(String... roles) {
    // ...
}
```

**Comment by jgrandja** [comment]
This is not related to OAuth scopes.
