### ISSUE TITLE
Rename `UserDetailsRepositoryReactiveAuthenticationManager` to `UserDetailsServiceReactiveAuthenticationManager`

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-security#4868]
When updated [my sample codes](https://github.com/hantsy/spring-reactive-sample) to the latest Spring Boot 2.0.0.M6. I found there are lots of naming strategies are changed in Spring Security.

eg. `UserDetailsRepository` -> `ReactiveUserDetialsService`

I found naming of  `UserDetailsRepositoryReactiveAuthenticationManager` is still based on the old `UserDetailsRepository`, I think it is better to use `UserDetailsServiceReactiveAuthenticationManager` instead.

**Comment by rwinch** [comment]
Thank you for the report. While the new naming is inconsistent, it follows Spring Data naming conventions. 

It is worth mentioning that Spring Framework has made changes between reactive and imperative APIs as well. For example, the reactive equivalent of [ConversionService](https://docs.spring.io/spring-framework/docs/5.3.x/javadoc-api/org/springframework/core/convert/ConversionService.html) is [Decoder](https://docs.spring.io/spring-framework/docs/5.3.x/javadoc-api/org/springframework/core/codec/Decoder.html).

**Comment by hantsy** [comment]
But there is no `UserDetailsRepository` since last refactoring.
