### ISSUE TITLE
SEC-224: Make Authentication.getPrincipal() for CAS return the UserDetails

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#487]
["Scott Battaglia":https://jira.spring.io/secure/ViewProfile.jspa?name=sbattaglia](Migrated from ["SEC-224":https://jira.spring.io/browse/SEC-224?redirect=false]) said:

Currently, Authentication.getPrincipal() for CAS is the only implementation that returns String instead of UserDetails which is inconsistant and limits the "pluggability" of different Acegi-backed providers.  This should be changed to be consistant with the other implementations.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
