### ISSUE TITLE
Migration from 4.x to 5.x

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4874]
### Summary

Provide a Migration from 4.x to 5.x guide

#### PasswordEncoder

In the meantime, please refer to [PasswordEncoder javadoc](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/crypto/password/PasswordEncoder.html]. It refers to other implementations that will discuss migration strategies. For example, you can refer to [MessageDigestPasswordEncoder javadoc](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/crypto/password/MessageDigestPasswordEncoder.html) if you used `DigestPasswordEncoder`.

**Comment by cemo** [comment]
I have just start to migrate our existing code base to 5.x and hit some problems. Our users had their salt values on their user table and currently I can see that salt completely has disappeared. Also PasswordEncoder has gone. `DaoAuthenticationProvider` does not include a salt source and this might cause us to duplicate previous codes into our code base by extending `DaoAuthenticationProvider`. What is the best way to upgrade security configurations who are using salt source on user table on db to 5.x currently? I think this is a good addition for documentation as well.

**Comment by rwinch** [comment]
@cemo You need a data migration to migrate the salt to be part of the password to use the existing `PasswordEncoder` this is outlined in [MessageDigestPasswordEncoder](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/crypto/password/MessageDigestPasswordEncoder.html)

**Comment by rodrigorodrigues** [comment]
> @cemo You need a data migration to migrate the salt to be part of the password to use the existing `PasswordEncoder` this is outlined in [MessageDigestPasswordEncoder](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/crypto/password/MessageDigestPasswordEncoder.html)

Hi @rwinch,
I'm trying to migrate from 3 o 5 but completely lost with the configuration, could you show an example please?

Spring 3
`
    @Override
    protected void configure(AuthenticationManagerBuilder auth) throws Exception   {
        auth.userDetailsService(userDetailsService);
        auth.authenticationProvider(authenticationProvider());
    }

    @Bean
    public PasswordEncoder passwordEncoder() {
        return new ShaPasswordEncoder(256);
    }

    @Bean
    public DaoAuthenticationProvider authenticationProvider() throws Exception {
        DaoAuthenticationProvider authenticationProvider = new DaoAuthenticationProvider();
        authenticationProvider.setUserDetailsService(userDetailsService);
        authenticationProvider.setPasswordEncoder(passwordEncoder());
        ReflectionSaltSource saltSource = saltSource();
        authenticationProvider.setSaltSource(saltSource);
        return authenticationProvider;
    }

    @Bean
    public ReflectionSaltSource saltSource() {
        ReflectionSaltSource saltSource = new ReflectionSaltSource();
        saltSource.setUserPropertyToUse("salt");
        return saltSource;
    }
`
The _salt and password_ are saved on database in different fields.

Spring 5
`
    @Override
    protected void configure(AuthenticationManagerBuilder auth) throws Exception   {
        auth.userDetailsService(userDetailsService);
        auth.authenticationProvider(authenticationProvider());
    }

    @Bean
    public DaoAuthenticationProvider authenticationProvider() throws Exception {
        DaoAuthenticationProvider authenticationProvider = new DaoAuthenticationProvider();
        authenticationProvider.setUserDetailsService(userDetailsService);
        authenticationProvider.setPasswordEncoder(passwordEncoder());
        return authenticationProvider;
    }

    @Bean
    public PasswordEncoder passwordEncoder() {
        return new MessageDigestPasswordEncoder();// What should be in the parameter or should I use StandardPasswordEncoder instead?
    }
`
For the data migration if I save _{salt}+password_ would be enough or do I need to do something else?

Thanks.

**Comment by rwinch** [comment]
> For the data migration if I save {salt}+password would be enough or do I need to do something else?

Yes first migrate to using `{salt}+password` and the new version of the `PasswordEncoder`. Once you have done that, upgrade to Security 5.

**Comment by rodrigorodrigues** [comment]
Hi @rwinch ,

I have migrated the passwords and upgraded to Security 5 now got the following `IllegalArgumentException: Detected a Non-hex character at 1 or 2 position` at `DaoAuthenticationProvider line 86`, if you could help me on that I would really appreciate it, thanks


	    @Bean
	    public PasswordEncoder passwordEncoder() {
		PasswordEncoder defaultEncoder = new StandardPasswordEncoder();
		Map<String, PasswordEncoder> encoders = new HashMap<>();
		encoders.put("bcrypt", new BCryptPasswordEncoder());

		DelegatingPasswordEncoder passworEncoder = new DelegatingPasswordEncoder(
		        "bcrypt", encoders);
		passworEncoder.setDefaultPasswordEncoderForMatches(defaultEncoder);

		return passworEncoder;
	    }

Exception

	java.lang.IllegalArgumentException: Detected a Non-hex character at 1 or 2 position
		at org.springframework.security.crypto.codec.Hex.decode(Hex.java:62) ~[spring-security-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]
		at org.springframework.security.crypto.password.StandardPasswordEncoder.decode(StandardPasswordEncoder.java:105) ~[spring-security-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]
		at org.springframework.security.crypto.password.StandardPasswordEncoder.matches(StandardPasswordEncoder.java:80) ~[spring-security-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]
		at org.springframework.security.crypto.password.DelegatingPasswordEncoder.matches(DelegatingPasswordEncoder.java:198) ~[spring-security-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]
		at org.springframework.security.authentication.dao.DaoAuthenticationProvider.additionalAuthenticationChecks(DaoAuthenticationProvider.java:86) ~[spring-security-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]

**Comment by rwinch** [comment]
By invoking `passworEncoder.setDefaultPasswordEncoderForMatches(defaultEncoder);` any password that is not prefixed with a valid id will delegate to `StandardPasswordEncoder` with the entire password. So if you have something like `{not-mapped}asdfsadfsd` then `{not-mapped}asdfsadfsd` will be passed to `StandardPasswordEncoder`.

**Comment by rwinch** [comment]
If you have a password that is `{sha256}asdfsadfsd` then the entire thing is going to be passed into `StandardPasswordEncoder` which will fail with an error like that. Instead, you should add `StandardPasswordEncoder` in the encoders map and avoid using `setDefaultPasswordEncoderForMatches`. If that doesn't help, please create a question on StackOverflow that contains the encoded password value you are having trouble with.

```java
PasswordEncoder defaultEncoder = new StandardPasswordEncoder();
Map<String, PasswordEncoder> encoders = new HashMap<>();
encoders.put("bcrypt", new BCryptPasswordEncoder());
encoders.put("sha256", new defaultEncoder);

return new DelegatingPasswordEncoder(
        "bcrypt", encoders);
```

We try and discourage asking for help on GitHub as this makes it harder for users to find. In the future, please ask on StackOverflow. If you don't get help there, I don't mind pinging via GitHub issues with a link to StackOverflow.

**Comment by rodrigorodrigues** [comment]
Hi @rwinch thanks for your help appreciated, I solved the issue using `new MessageDigestPasswordEncoder("SHA-256")` instead `new StandardPasswordEncoder()`.

**Comment by aschatten** [comment]
Related issue that causes the migration to fail if Spring Security OAuth lib is used and it saves Spring Security objects in a database: https://github.com/spring-projects/spring-security-oauth/issues/662

**Comment by rwinch** [comment]
This can be closed as no longer relevant
