### ISSUE TITLE
Authentication::getName break compatibility

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-security#4877]
Normally people will implements UserDetails both with `username` and `name` , `username` is unique as id and `name` could be duplicated only for display, I use `authentication.getName()` to retrieve `username` widely,  If I upgrade to 5.0.0, it will return `name` instead of `username`, I suggest improve AbstractAuthenticationToken to use `username` as name for UserDetails
```
if ((getPrincipal() instanceof UserDetails)) {
      return ((UserDetails)getPrincipal()).getUsername();
    }
```

**Comment by jgrandja** [comment]
@quaff Thanks for the report.

However, the default behaviour for returning `username` from a `UserDetails` in `AbstractAuthenticationToken.getName()` has been preserved with the recent addition of `AuthenticatedPrincipal` in Spring Security 5.0.

Before the addition of `AuthenticatedPrincipal`, `AbstractAuthenticationToken.getName()` was implemented as follows:

```
public String getName() {
	if (this.getPrincipal() instanceof UserDetails) {
		return ((UserDetails) this.getPrincipal()).getUsername();
	}
```

With the addition of `AuthenticatedPrincipal`, `AbstractAuthenticationToken.getName()` is now implemented as follows:

```
public String getName() {
	if (this.getPrincipal() instanceof AuthenticatedPrincipal) {
		return ((AuthenticatedPrincipal) this.getPrincipal()).getName();
	}
```

`AuthenticatedPrincipal` is defined as:

```
public interface AuthenticatedPrincipal {
	String getName();
}
```

And `UserDetails` in Spring Security 5.0 now implements `AuthenticatedPrincipal` and provides a default method implementation for `AuthenticatedPrincipal.getName()` which returns `UserDetails.getUsername()`.

```
public interface UserDetails extends AuthenticatedPrincipal, Serializable {

	default String getName() {
		return getUsername();
	}
}
```

As you can see based on these changes, the original behaviour has been preserved so there are no breaking changes that I can see.

I'm going to close this but if there is something I'm missing than please let me know and I can look at it further.

**Comment by quaff** [comment]
It breaks developer's application, I already have 
```
@Getter
@Setter
public class User implements UserDetails {
	private String username;
	private String name;
	// other properties
}
```
I cannot have two version of getName(), one for my original purpose to return `name`, and the other return `username`, I have to rename `name` to other name to avoid collision, it's very intrusive and not acceptable.

**Comment by rwinch** [comment]
@jgrandja With the example, I see @quaff's point. I think we should try to preserve passivity here

**Comment by jgrandja** [comment]
I see your point @quaff given your example. I've applied the fix and it's now in master.
Thanks for reporting this.

**Comment by sirianni** [comment]
I get the compatibility issue, but the fix seems like a step backwards.

Sorry to piggyback on this bug report, but given that `UserDetails` no longer implements `AuthenticatedPrincipal` what is the common interface that application code can use across `OAuth2User` and `UserDetails`.  

I have an application where native login and OAuth2 login is supported.  There does not seem to be an appropriate way to load a consistent `Principal` into the security context such that my application code is agnostic to how the authentication took place.
