### ISSUE TITLE
SEC-227: Ability to extend LdapAuthenticationProvider

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#488]
["Bertrand Renuart":https://jira.spring.io/secure/ViewProfile.jspa?name=brenuart](Migrated from ["SEC-227":https://jira.spring.io/browse/SEC-227?redirect=false]) said:

The comments on the createUserDetails() method say:

...Can be overridden to customize the mapping of user attributes to additional user information....

Besides constructing the actual UserDetails implementation, this method also call the authoritiesPopulator to retrieve the list of granted authorities.
Unfortunately, the authoritiesPopulator field is private... which prevents the user from extending the class and provide his own implementation (field is private and there is no getter...)

Two approaches come in to my mind to solve this problem:

1/ provide a getter for the authoritiesPopulator such that child classes can access it and safely override the createUserDetails() method.

2/ or (my preferred solution), introduce the concept of UserDetailsFactory that would be responsible for returning a concrete UserDetails implementation. People could then implement their own UserDetailsFactory to return their own implementation (possibly enhanced with additional attributes from their Active Directory).

The LdapAuthenticationProvider would then be passed three arguments in his constructor: authenticator, authoritiesPopulator and userDetailsFactory.
The UserDetailsFactory would have a signature like the following:

... UserDetails createUserDetails(String username, String password, LdapUserInfo ldapUser, GrantedAuthority[] grantedAuthorities);

The sequence of operation triggered by a call to retrieveUser() would be:

  retrieveUser 
    -> authenticator.authenticate()
    -> authoritiesPopulator.getGrantedAuthorities()
    -> return userDetailsFactory.createUserDetails()

**Comment by linuxjackto1** [comment]
thanks www.movied.org
