### ISSUE TITLE
OIDC Support doesn't allow overriding user-name-attribute

### ISSUE THREAD

**Issue by mraible** [spring-projects/spring-security#4892]
### Summary

I'm trying to override the value returned from `OAuth2AuthorizedClient.getName()`. According to the [documentation for Okta](https://github.com/spring-projects/spring-security/blob/master/samples/boot/oauth2login/README.adoc#okta-login), this should be possible by specifying a `user-name-attribute`. I've tried specifying:

```
user-name-attribute: preferred_username
```

The value seems to be set property by Spring Boot:

<img width="1398" alt="screen shot 2017-12-01 at 9 47 25 am" src="https://user-images.githubusercontent.com/17892/33493421-35ddae74-d67d-11e7-93e0-97dc8ecd190f.png">

But when it's set in `org.springframework.security.oauth2.client.registration.ClientRegistration`, it's set back to `sub`. 

<img width="1398" alt="screen shot 2017-12-01 at 9 48 04 am" src="https://user-images.githubusercontent.com/17892/33493428-3ab4257c-d67d-11e7-9424-f085ff4250e7.png">

### Actual Behavior

It's not possible to override "sub" with a different attribute name.

### Expected Behavior

It should be possible to override the user-name-attribute.

### Version

Spring Boot 2.0.0.M7
Spring Security 5.0.0.RELEASE

### Sample

https://github.com/oktadeveloper/okta-spring-security-5-example

**Comment by jgrandja** [comment]
Hi @mraible This is a Spring Boot issue. I just logged the details [here](https://github.com/spring-projects/spring-boot/issues/11243).

**Comment by mraible** [comment]
😎 Thanks!
