### ISSUE TITLE
SEC-229: Allow redirects to external URLs in AbstractProcessingFilter

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#490]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-229":https://jira.spring.io/browse/SEC-229?redirect=false]) said:

Another report from third-party SSO integration (ATHENS):

I've run up against a sticking point where acegi doesn't support the
interactions we need. I've extended AbstractProcessingFilter , my
'attemptAuthentication' method begins like this:

```
public Authentication attemptAuthentication(HttpServletRequest request) throws AuthenticationException {
    String resources[] = athensProperties.getAthensResources();
    // this is from the athens api.
    ClientConfiguration conf = athensProperties.getConfiguration();
    String username = request.getParameter("ath_user");
    String token = request.getParameter("ath_ttok");
    String remoteAddr = request.getRemoteAddr();

    try {
        Authenticated auth = conf.checkToken(username, token, remoteAddr, resources);
        GrantedAuthority[] granted = new GrantedAuthority[resources.length];
        auth.log(resources);

        for (int i = 0; i < resources.length; i++) {
            granted[i] = new GrantedAuthorityImpl(resources[i]);
        }
        // NB I don't store 'auth' becuase its not serializable.
        return new UsernamePasswordAuthenticationToken(username, token, granted);
    } catch (InvalidUsernameException e) {
        // wrap up athens exceptions as their acegi equivalents
        throw new UsernameNotFoundException(username, e);
    } catch (InvalidIPaddressException e) {
        throw new AccessDeniedException(remoteAddr, e);
    // todo add exception mappings for these two
    // } catch (InvalidTokenException e) {
    // this happens when their token has expired. They get bounced
    // back to athens for a new login.
    //    response.sendRedirect(response.encodeRedirectURL(aapUrl + "&ath_err=tokExp"));
    //} catch (NoResourceAccessException e) {
    // this happens when the user doesn't have access to any of the
    // resources we provide. The redirect takes them to a list of what
    // they are allowed to access, AFAIK.
    //    response.sendRedirect(response.encodeRedirectURL(aapUrl + "&ath_err=noResAcc"));
```

If I get those last two exceptions, I'm supposed to redirect the user
back to Athens. However, I don't get access to the response in this
method. The 'unsuccessfulAuthentication' method takes over, and this
does have the ability to send this redirect, but the redirect looks
like this:

response.sendRedirect(response.encodeRedirectURL(request.getContextPath()
                + failureUrl));

Its only within the application. This leaves me with two unpalatable options:
- go down this route - adding a second filter or servlet to do the bounce, more config etc etc. Horrible and convoluted.
- simply override unsuccessfulAuthentication. Unfortunately there's a bunch of stuff going on in there which seemingly needs to happen before I redirect, so I'd have to copy the code..

Alternatively, this could be seen as a bug/missing feature in the redirect: since 'failureUrls' have to start with '/' at present, acegi could do this:

if ("".equals(failureUrl) || failureUrl.startsWith("/")) {
   // the "" is to handle people who used to use this to redirect to context root
   response.sendRedirect(response.encodeRedirectURL(request.getContextPath() + failureUrl));
} else {
   // treat it as an absolute URL.
   response.sendRedirect(response.encodeRedirectURL(failureUrl));
}

... which would let me just configure the system to handle specialized
exceptions for these two cases.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
