### ISSUE TITLE
Transaction with ReactiveSecurityContextHolder

### ISSUE THREAD

**Issue by fanliming** [spring-projects/spring-security#4907]
### Summary

spring transaction do not work.

https://spring.io/blog/2017/11/01/spring-security-5-0-0-rc1-released#reactivesecuritycontextholder

```java
Authentication authentication =
    new TestingAuthenticationToken("user", "password", "ROLE_USER");

Mono<String> messageByUsername = ReactiveSecurityContextHolder.getContext()
  .map(SecurityContext::getAuthentication)
  .map(Authentication::getName)
  .flatMap(this::findMessageByUsername)
  // In a WebFlux application the `subscriberContext`
  // is automatically setup using `ReactorContextWebFilter`
  .subscriberContext(ReactiveSecurityContextHolder.withAuthentication(authentication));
```
there is no transaction  if I do some update in this method
```java
@Transactional
findMessageByUsername
```

### Version

spring framework 5.0.2.RELEASE
sprint security 5

**Comment by rwinch** [comment]
Thanks for the report. However, this has nothing to do with Spring Security. Generally, Spring Framework does not support `@Transactional` on reactive methods. If this is something you need, you will want to discuss it with the Spring Framework team at https://jira.spring.io/browse/SPR
