### ISSUE TITLE
SEC-230: ExceptionTranslationFilter does not catch AccessDeniedException with Spring MVC M2/M3

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#491]
["Scott Rankin":https://jira.spring.io/secure/ViewProfile.jspa?name=srankin](Migrated from ["SEC-230":https://jira.spring.io/browse/SEC-230?redirect=false]) said:

I am writing a SpringMVC-based web application with Acegi Security.  I have a Spring Controller object that invokes a method that is protected by an Acegi MethodSecurityInterceptor.  When the MethodSecurityInterceptor throws an AccessDeniedException, it is getting wrapped by the Spring FrameworkServlet in a org.springframework.web.util.NestedServletException.  Because of this wrapping, the ExceptionTranslationFilter never catches an AccessDeniedException, thus causing a 500 server error to bubble up instead of a 403/redirect to authenticationEntryPoint. 

I'm not sure whose problem this is - the Acegi code could inspect the root cause of the NestedServletException, or the FrameworkServlet could pass on RuntimeExceptions without wrapping.

**Comment by spring-issuemaster** [comment]
This issue duplicates #460

**Comment by linuxjackto1** [comment]
thanks www.movied.org
