### ISSUE TITLE
CsrfAuthenticationStrategy should always (not conditionally) clear the token stored in CsrfRepository and generate a new one

### ISSUE THREAD

**Issue by miguelfgar** [spring-projects/spring-security#4919]
### Summary
CsrfAuthenticationStrategy code in _onAuthentication_ method causes csrf management to fail when an authentication entrypoint is called for the second time passing a valid authenticated session (triggering the session fixation protection). It returns an old csrf token that is not valid anymore.

### Actual Behavior
CsrfAuthenticationStrategy should **always** clear the token stored in the CsrfRepository and generate a new one (that will be placed in the current request) as this class is called always after an authentication process and thus invalidating previous csrf token if existed.
Currently this is NOT always happening. The reason is that the code in onAuthentication() method is conditional. I understand the reason behind the condition: only to generate a new csrf token and place it into the request when a previous token existed in the CsrfTokenRepository:

```java
	public void onAuthentication(Authentication authentication,
			HttpServletRequest request, HttpServletResponse response)
			throws SessionAuthenticationException {
		boolean containsToken = this.csrfTokenRepository.loadToken(request) != null;
		if (containsToken) {
			this.csrfTokenRepository.saveToken(null, request, response);

			CsrfToken newToken = this.csrfTokenRepository.generateToken(request);
			CsrfToken tokenForRequest = new SaveOnAccessCsrfToken(csrfTokenRepository,
					request, response, newToken);

			request.setAttribute(CsrfToken.class.getName(), tokenForRequest);
			request.setAttribute(newToken.getParameterName(), tokenForRequest);
		}
	}
```
However, this causes a particular scenario to fail: accessing a second time to the authentication entrypoint with a valid authenticated session.

The particular case is:

1. You access an authentication entrypoint for the first time and you obtain a sessionID and csrf token returned as a cookie.

For instance:
curl "http://localhost:8348/login" -H "Content-Type: application/x-www-form-urlencoded" --data "username=user&password=password" --compressed -i

In order to set the csrf token as a cookie I use a filter added before CsrfFilter which just retrieves the csrf token from the request and sets it as a cookie (this is a pretty common and standard practice).
The way to obtain the token to be able to publish it as a cookie is:
CsrfToken csrf = (CsrfToken) **request.getAttribute(CsrfToken.class.getName())**;

I have configured request matchers so for the authentication entrypoint itself (/login in this example) XSRF token is not validated (ignored) as I want this authentication entrypoint to be called directly in some cases (without presenting a login form where a first csrf is provided for a non authenticated session that could be validated later when the authentication entrypoint /login is called).

2. You access a second time to the same authentication entrypoint but this time passing a valid sessionId (the one obtained in the previous request) 

curl "http://localhost:8348/login" **-H "Cookie: JSESSIONID=28B3EA3997337B67B52546392DB33FFA"** --data "username=user&password=password"

In this second case, CsrfFilter retrieves the previous csrf token from the CsrfRepository (in my case an HttpSessionCsrfRepository). Then CsrfFilter places the retrieved DefaultCsrfToken into the request (which is correct). As a csrf token is not missed (is found in the CsrfTokenRepository (HttpCsrfTokenRepository in my case)), it is retrieved and set in the request as a DefaultCsrfToken. Please note that DefaultCsrfToken class does not implements lazy creation of the HttpSession by saving the csrf token to the repository when accessed by means getToken() method. Conversely, the SaveOnAccessCsrfToken getToken() method saves the token into the CsrfTokenRepository.

Later session fixation protection jumps in (as we are calling an authentication entrypoint passing a valid session id) and strategy to create a new session / change ID is applied. As a result, in my case we get a new session that does not contain an HttpCsrfRepository anymore (as we are not migrating attributes).

Later the CsrfAuthentictionStrategy jumps in and executes the onAuthentication() method I copied above. What is going to happen in our case is that no token will be found when performing: 
```java
boolean containsToken = this.csrfTokenRepository.loadToken(request) != null;
```
and so the method will just finish without generating a new token and replacing the former one in the request (that should be a SaveOnAccessCsrfToken so that when the token is accessed for the first time is stored in the HttpSessionRepository). 
So far the result is that we still have the old csrf token in the request (which is a DefaultCsrfToken, not a SaveOnAccessCsrfToken) but nothing else (CsrfAuthentication has not created a new one a place it into the request).

Finally, the filter chain arrives to the custom filter that retrieves the csrf token from the request a sets it as a cookie, by means:

```java
CsrfToken csrf = (CsrfToken) request.getAttribute(CsrfToken.class.getName());
```
What is going to happen now is that the CsrfToken retrieved from the request is the former csrf token (besides is a DefaultCsrfToken, as it was placed in the request originally) because no class replaced the former token with a new generated one.
Note that so this works correctly, the new token would be expected as a SaveOnAccessToken so that when the getToken() method is invoked the session is lazily creted and the csrfToken saved to the CsrfTokenRepository.

The former token is set as a cookie and returned to the client.
Obviously, this fails when the client tries to use the csrf token to invoke a service passing the current sessionID. Two things are wrong here:
1. From the point of view of the security is not safe to provide the csrf token from the first authentication after a second authentication is performed
2. Besides what is explained in 1) this is not going to work as no csrf token was saved previously in the CsrfTokenRepository (HttpCsrfTokenRepository in this case) in the server side, so this will fail.

### Expected Behavior

CsrfAuthenticationStrategy should **always** clear the former token, generate a new one and place it in the current request as a SaveOnAccessCsrfToken (so that when getToken() is invoked the token is lazily stored in the CsrfRepository.

I guess is wrong to keep the "if" sentence that makes this conditional that was not included in the first version of CsrfAuthenticationStrategy. 

Leaving out the condition and keeping the code like this has worked for me as a workaround with a expected behaviour for this particular scenario:

```java
	public void onAuthentication(Authentication authentication,
			HttpServletRequest request, HttpServletResponse response)
			throws SessionAuthenticationException {
		boolean containsToken = this.csrfTokenRepository.loadToken(request) != null;
		this.csrfTokenRepository.saveToken(null, request, response);

		CsrfToken newToken = this.csrfTokenRepository.generateToken(request);
		CsrfToken tokenForRequest = new SaveOnAccessCsrfToken(csrfTokenRepository,
					request, response, newToken);

		request.setAttribute(CsrfToken.class.getName(), tokenForRequest);
		request.setAttribute(newToken.getParameterName(), tokenForRequest);
	}
```

### Version

Issue found with Spring Security 4.0.4.RELEASE
(spring-security-web 4.0.4.RELEASE, aligned with Spring Boot 1.3.8 from Spring Cloud Brixton release train).

However, I guess that this issue also affects newer versions as the CsrfAuthenticationStrategy keeps this condition in its last version (and so I would expect this to fail for this scenario also).

Please see the related issue: https://github.com/spring-projects/spring-security/issues/2624
That suggests that CsrfAuthentication should place the new generated SaveOnAccessCsrfToken into the request (which is correct). However, in the issue it was suggesting to add this code **unconditionally** (without the 'if' sentence) as it was previously in original code.
However, if you see the commit where this was fixed, the 'if' sentece was added. This is for me what causes the error:

https://github.com/spring-projects/spring-security/commit/59e13e7bbb4b1f5658294c4727aef2f516e5bd4c

**Comment by rwinch** [comment]
It sounds like you have done quite a bit of customization. I'm not sure I understand the exact reason you are running into this scenario. Why are you trying to authenticate a second time? Why don't you validate CSRF on the authentication attempt to avoid CSRF log in attempts? Perhaps a sample would help me to understand better.

However, if the CSRF token is empty we should not be clearing it (there is no value to clear) and we should not be creating a new one (there wasn't one to begin with). If you need one saved, you can access the `CsrfToken` from within the `AutthenticationEntryPoinit` which will trigger it to be saved.

If you want support for saving/retrieving the token in a cookie you can update to Spring Security 4.1+ which has a [CookieCsrfTokenRepository](https://github.com/spring-projects/spring-security/blob/4.2.3.RELEASE/web/src/main/java/org/springframework/security/web/csrf/CookieCsrfTokenRepository.java). Alternatively, the class is easy to copy as is and works on its own.

I'm closing this issue as it does not seem reasonable to create a token when no token exists. If you need  a token added access the `CsrfToken` and it will be saved for subsequent requests.
