### ISSUE TITLE
SEC-231: Add another DefaultLdapAuthoritiesPopulator.getGroupMembershipRoles

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#492]
["Kurt R. Hoehn":https://jira.spring.io/secure/ViewProfile.jspa?name=khoehn](Migrated from ["SEC-231":https://jira.spring.io/browse/SEC-231?redirect=false]) said:

Modifing the getGroupMembershipRoles signature to include groupSearchBase as a parameter would make extending the DefaultLdapAuthoritiesPopulator a lot easier.  Here is a example of what I mean.

I have roles that are system wide roles but then I have roles that are established for the application that the user belongs to.  I use the seeAlso attribute of the user to determine the application the user belongs to.  So the initial role search works perfectly with the DefaultLdapAuthoritiesPopulator but I also want to do a sub search on the application that the user belongs to via a user attribute.  I extended the DefaultLdapAuthoritiesPopulator and overrode the getRolesFromUserAttributes, but for what I needed being able to use the getGroupMembershipRoles with a different groupSearchBase would have saved me from duplicating most of the code from DefaultLdapAuthoritiesPopulator.

Recommended change:

protected Set getGroupMembershipRoles(String userDn, Attributes userAttributes)
{
    return getGroupMembershipRoles( userDn, groupSearchBase, userAttributes );
}

protected Set getGroupMembershipRoles(String userDn, String searchBase, Attributes userAttributes)
{
...
}

This would not break the current the current class and would make is easier to extend the class in the future.

Thank You,

Kurt R. Hoehn

**Comment by linuxjackto1** [comment]
thanks www.movied.org
