### ISSUE TITLE
Add resource server support from client side

### ISSUE THREAD

**Issue by daniellavoie** [spring-projects/spring-security#4922]
### Summary

`Spring Security OAuth 2` had support for `OAuth2RestTemplate` that allowed clients to contact a Resource server by providing a `ResourceDetail` containing OAuth2 info.

Using `WebClient` requires the client to handle the token retrieval. Would be nice if that feature from `OAuth2RestTemplate` could be ported to Spring Security 5.

**Comment by jgrandja** [comment]
See #4921 and #4920
