### ISSUE TITLE
Eclipse or IDEA use Gradle  Cannot run

### ISSUE THREAD

**Issue by CoSaoyears** [spring-projects/spring-security#4926]
> Task :spring-security-messaging:compileTestJava
注: /Users/zhangxi/AndroidStudioProjects/MyApplication/spring-security/messaging/src/test/java/org/springframework/security/messaging/access/intercept/ChannelSecurityInterceptorTests.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

> Task :spring-security-messaging:test
objc[27530]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java (0x1040be4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1041424e0). One of the two will be used. Which one is undefined.

> Task :spring-security-oauth2-client:test
objc[27533]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java (0x105d474c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x105dcb4e0). One of the two will be used. Which one is undefined.

org.springframework.security.oauth2.client.oidc.userinfo.OidcUserServiceTests > loadUserWhenUserInfoUriInvalidThenThrowAuthenticationServiceException FAILED
    org.springframework.security.oauth2.core.OAuth2AuthenticationException at OidcUserServiceTests.java:259

org.springframework.security.oauth2.client.endpoint.NimbusAuthorizationCodeTokenResponseClientTests > getTokenResponseWhenTokenUriInvalidThenThrowAuthenticationServiceException FAILED
    java.lang.IllegalArgumentException at NimbusAuthorizationCodeTokenResponseClientTests.java:184

org.springframework.security.oauth2.client.userinfo.DefaultOAuth2UserServiceTests > loadUserWhenUserInfoUriInvalidThenThrowAuthenticationServiceException FAILE
    org.springframework.security.oauth2.core.OAuth2AuthenticationException at DefaultOAuth2UserServiceTests.java:195

org.springframework.security.oauth2.client.userinfo.CustomUserTypesOAuth2UserServiceTests > loadUserWhenUserInfoUriInvalidThenThrowAuthenticationServiceException FAILED
    org.springframework.security.oauth2.core.OAuth2AuthenticationException at CustomUserTypesOAuth2UserServiceTests.java:206

172 tests completed, 4 failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spring-security-oauth2-client:test'.
> There were failing tests. See the report at: file:///Users/zhangxi/AndroidStudioProjects/MyApplication/spring-security/oauth2/oauth2-client/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 12m 27s
168 actionable tasks: 98 executed, 70 up-to-date

**Comment by pasonzhang** [comment]
my build error is similar  to that.

**Comment by eleftherias** [comment]
I am closing this issue, since I cannot currently reproduce this.

If you continue to have problems building the project or importing it into an IDE please add the following details:
- the IDE used and the steps to import the project
- the command run
- the Java version used
- the gradle version used
- the stacktrace
