### ISSUE TITLE
The order of multiple antMatchers().hasRole() calls matters

### ISSUE THREAD

**Issue by up-to-you** [spring-projects/spring-security#4929]
### Summary

Config below forbids any url for guest role:
```kotlin
.antMatchers("/**", "/user/**").hasRole(registeredUser.role)
.antMatchers("/guest", "/guest/**").hasRole(guestUser.role)
```
however if you switch this calls - everything works as expected:
```kotlin
.antMatchers("/guest", "/guest/**").hasRole(guestUser.role)
.antMatchers("/**", "/user/**").hasRole(registeredUser.role)
```
### Actual Behavior

access by role is depends on patterns registration order

### Expected Behavior

patterns registration / verification produces independently

### Configuration

Spring boot 2.0 M7 : Web, JPA, Security

### Version

Spring boot 2.0 M7

### Sample

https://github.com/up-to-you/sdt
config/CommonConfig.kt

**Comment by php-coder** [comment]
To me it looks like an expected behavior. Perhaps, it's because I remember that from XML configuration where the order gotcha was a very famous and often seen.

**Comment by jzheaux** [comment]
Thanks for bumping this issue, @php-coder. You are correct that this is expected behavior and is unlikely to change.
