### ISSUE TITLE
Using token access for /oauth/check_token?token=

### ISSUE THREAD

**Issue by deverlex** [spring-projects/spring-security#4930]
Hi, I'm watched using check token with /oauth/check_token with basic authorization.
curl -X POST --header "Authorization: Basic <endcode_base64>" "http://localhost:9000/oauth/check_token=<token>"
It is success!

But I want to using  curl -X POST --header "Authorization: Bearer <token_access>" ......
How to custom it? Thanks.

**Comment by jgrandja** [comment]
@deverlex Please provide more detail as I don't understand your question. Also, is this question related to Spring Security OAuth 2.x or Spring Security 5.0?
