### ISSUE TITLE
Migrate Groovy to Java

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4939]
### Summary

The tests that are written in Groovy are very convenient and easy to read, but place an unnecessary burden on contributors unfamiliar with Groovy. We should migrate the Groovy tests to Java.

For the samples using Geb, take a look at https://github.com/spring-projects/spring-security/tree/b9152701a65df5b3fa78fe4bd2a946018f9ca352/samples/javaconfig/webflux-form/src/integration-test/java/sample

The following commits in Spring Session might be useful as well

https://github.com/spring-projects/spring-session/commit/1a318b89d907d01d80c9ba1b7c6ac99ca3cc3753

and

https://github.com/spring-projects/spring-session/commit/8e7c736a0aef27eda21371eaf7a237498098dcad

Anyone taking on this task I'd encourage them to break it up into multiple PRs that migrate smaller portions at a time (i.e. a sample or a package) and include

```
Migrate <what is migrated> groovy->java

(optional additional details)

Issue: gh-4939
```

I'd also encourage contributors to comment on this issue to state which piece they are going to start working on migrating. This will allow multiple people to help tackle this large issue and avoid duplicating efforts.

**Comment by michael-simons** [comment]
Next: xml-jaas

**Comment by michael-simons** [comment]
Next: javaconfig-form

**Comment by adolfoweloy** [comment]
Migrate `UserDetailsManagerConfigurerTests` test groovy->java from security-config #4949

**Comment by michael-simons** [comment]
Next: javaconfig-jdbc

**Comment by michael-simons** [comment]
I will have the rest of the samples ready by the end of the weekend.
One question though: There are more Groovy tests, also dedicated to tickets and stuff. Do you want to migrate them as well?

**Comment by rwinch** [comment]
@michael-simons We would like to migrate all Groovy within Spring Security to Java. Does that help?

**Comment by michael-simons** [comment]
Yep, that was the question. Thanks.

**Comment by rwinch** [comment]
@michael-simons Awesome. I think you were too quick for my edits so as an FYI I added a little more information above. Thanks again for your help!

**Comment by rwinch** [comment]
I'm starting on config/src/test/groovy/org/springframework/security/config/annotation/authentication

**Comment by jgrandja** [comment]
I'm starting on `/config/src/test/groovy/org/springframework/security/config/annotation/web`

**Comment by rwinch** [comment]
I'm starting on config/src/test/groovy/org/springframework/security/config/annotation/authentication

**Comment by rwinch** [comment]
I'm starting on config/src/test/groovy/org/springframework/security/config/annotation/configuration

**Comment by rwinch** [comment]
I'm starting on config/src/test/groovy/org/springframework/security/config/annotation/issue50

**Comment by rwinch** [comment]
I'm starting on config/src/test/groovy/org/springframework/security/config/annotation/method/configuration

**Comment by jgrandja** [comment]
I'm starting on `org.springframework.security.config.annotation.web.builders`

**Comment by jzheaux** [comment]
I'm starting on `org.springframework.security.config.annotation.web.configuration.sec2377`

**Comment by jzheaux** [comment]
Starting on `org.springframework.security.config.annotation.web.configurers.AnonymousConfigurerTests` (not reserving the entire package, due to size)

**Comment by jzheaux** [comment]
I'm starting on `org.springframework.security.config.debug`

**Comment by jzheaux** [comment]
I'm starting on `org.springframework.security.config.annotation.method.configuration`

**Comment by jgrandja** [comment]
I'm taking on the remaining tests in `org.springframework.security.config.annotation.web.configuration`

**Comment by jzheaux** [comment]
I'm taking `org.springframework.security.config.annotation.sec2758`

**Comment by jzheaux** [comment]
I'm taking `org.springframework.security.config.websocket`. @rwinch, I haven't played around with web sockets and Spring Security before, so let me know if there is anything I should be aware of.

**Comment by jzheaux** [comment]
I'm taking `org.springframework.security.config.doc`.

**Comment by jzheaux** [comment]
I'm taking `org.springframework.security.config.http.AccessDeniedConfigTests`. Not reserving the entire package since there are about a dozen classes in it.

**Comment by jzheaux** [comment]
Upon further review, I am going to take the entire package `org.springframework.security.config.http`. Wish me luck.

**Comment by jzheaux** [comment]
I'm taking the `org.springframework.security.config.annotation.web.configurers.Namespace*` tests.

**Comment by kostya05983** [comment]
@jzheaux , I will try to migrate org.springframework.security.config.annotation.web.configurers tests

**Comment by ghostd** [comment]
Next: integration tests for the LDAP management

**Comment by jzheaux** [comment]
I'm taking the cas sample.

**Comment by jzheaux** [comment]
I'm starting on `org.springframework.security.web.context.AbstractSecurityWebApplicationInitializerTests` (last one!)
