### ISSUE TITLE
SEC-233: AnonymousProcessingFilter - redundant creation of Authentication object causes IllegalStateException

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#494]
["Arthur Branham":https://jira.spring.io/secure/ViewProfile.jspa?name=arthur.branham](Migrated from ["SEC-233":https://jira.spring.io/browse/SEC-233?redirect=false]) said:

In the finally block of the doFilter method, it seems the WebAuthenticationDetails object is created again in order to compare against the current Security Context's Authentication object to see that it has not changed over the course of the request.  This rendundant creation can potentially cause an IllegalStateException: a session cannot be created sine the response is commited.  The response may be commited anytime down the filter pipeline.  Why create another Authentication object just to check for equality.   A references should be held before the filter chain is invoked since this is the only safe time to create a session and that reference should be used for comparison after the filter chain returns.  This will avoid the unnessary and invalid creation of a session.

**Comment by spring-issuemaster** [comment]
This issue duplicates #445

**Comment by linuxjackto1** [comment]
thanks www.movied.org
