### ISSUE TITLE
Use AuthenticationEventPublisher Bean by default

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-security#4940]
The specific use-case in Boot which led to this issue: 

Spring Boot auto-configuration now creates a `UserDetailsService` bean instead of `AuthenticationManager`. We register a `DefaultAuthenticationEventPublisher` bean [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/SecurityAutoConfiguration.java#L52) but it does not get picked up by the `AuthenticationManager`.

**Comment by rwinch** [comment]
Spring Security Java Configuration will automatically leverage any single `AuthenticationEventPublisher` Bean defined in the `ApplicationContext`
