### ISSUE TITLE
SEC-234: Allow WebAuthenticationDetails pluggable implementations

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#495]
["Arthur Branham":https://jira.spring.io/secure/ViewProfile.jspa?name=arthur.branham](Migrated from ["SEC-234":https://jira.spring.io/browse/SEC-234?redirect=false]) said:

Currently the AnonymousProcessingFilter and BasicProcessingFilter make use of the WebAuthenticationDetails object.  I see that this class can be extended, however there is no place to plug an extended implementation into any of the filters.  I am no expert with Spring, but this approach seems to go against the Spring concept of Dependency Injection.  I think a more Spring oriented approach would be to set a factory in each filter which would create prototype implementations of a WebAuthenticationDetails interface and then invoke an interface method on it such as 

public void populateInformation(HttpServletRequest request) {}.  

You could have the current WebAuthenticationDetails class be renamed to WebAuthenticationDetailsImpl.  The implementation can now be subclassed and easily plugged into either of the filters.  Subclasses can delegate the method call to super and then continue to add any additinal information.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
