### ISSUE TITLE
When use custom  Web Security Expressions meat  exception:SpelEvaluationException: EL1057E: No bean resolver registered in the context to resolve access to bean

### ISSUE THREAD

**Issue by alexli0707** [spring-projects/spring-security#4950]
### Summary
Thanks for helping first. When I using Spring Security in Spirng Boot and set Web Security Expressions according to [project doc](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#el-access-web-beans) 

### Actual Behavior

I meat this exception:

```Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1057E: No bean resolver registered in the context to resolve access to bean 'rbacService' ```

### Expected Behavior

as doc have a happy ending like this

```
http.authorizeRequests()
			.antMatchers("/user/**").access("@webSecurity.check(authentication,request)")
```

### Configuration

Here is my code,I try use @Bean as method and @Service("rbacService") both meat the same exception.
```
http
                .authorizeRequests()
                .antMatchers("/css/**", "/js/**", "/fonts/**").permitAll()  
                .antMatchers("/", "/login", "/register").permitAll()
                .anyRequest().access("@rbacService.hasPermission(authentication,request)")
                .expressionHandler(webExpressionHandler())

```

```
@Service("rbacService")
public class RbacServiceImpl implements RBACService {

    @Autowired
    AdminUserService adminUserService;

    @Override
    public boolean hasPermission(Authentication authentication,HttpServletRequest request) {
        // do something dynamic pair the url and check permission
        return hasPermission;
    }
}
```
### Version

spring-security-config:4.2.2RELEASE
spring-security-core:4.2.2RELEASE
spring-security-web:4.2.2RELEASE
spring-boot-starter-parent:1.5.9RELEASE

**Comment by rwinch** [comment]
It looks like you are providing a custom `webExpressionHandler()` You need to be sure that if it is a `DefaultWebSecurityExpressionHandler` that it is injected with an `ApplicationContext` which is how it resolves the beans.

I'm going to close this, but feel free to reopen if this doesn't resolve your issue
