### ISSUE TITLE
The project link (http://spring.io/spring-security) is broken

### ISSUE THREAD

**Issue by MottoX** [spring-projects/spring-security#4951]
It should be [https://projects.spring.io/spring-security/](https://projects.spring.io/spring-security/) instead of [http://spring.io/spring-security](http://spring.io/spring-security).

**Comment by rwinch** [comment]
Thanks for the PR! I think this really needs to be fixed here https://github.com/spring-io/sagan/issues/808

**Comment by rwinch** [comment]
Closing this since Sagan is now fixed.
