### ISSUE TITLE
SEC-235: HttpSessionContextIntegrationFilter reset the SecurityContext

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#496]
["Zheng Shuai":https://jira.spring.io/secure/ViewProfile.jspa?name=zhengshuai](Migrated from ["SEC-235":https://jira.spring.io/browse/SEC-235?redirect=false]) said:

I use HttpSessionContextIntegrationFilter to work with AuthenticationProcessingFilter in the product. But I find that every time after an unhandling exception happen, the SecurityContext in the Threadlocal SecurityContextHolder will be reset to an Authenication with null priciple.
I check the code and find following segment in HttpSessionContextIntegrationFilter class:
In the doFilter method:
                // If HttpSession exists, store current SecurityContextHolder contents

```
            // but only if SecurityContext has actually changed (see JIRA SEC-37)

            if ((httpSession != null)

                && (SecurityContextHolder.getContext().hashCode() != contextWhenChainProceeded)) {

                httpSession.setAttribute(ACEGI_SECURITY_CONTEXT_KEY,

                    SecurityContextHolder.getContext());



                if (logger.isDebugEnabled()) {

                    logger.debug("SecurityContext stored to HttpSession: '"

                        + SecurityContextHolder.getContext() + "'");

                }

            }
```

What I think that actually happened:
Before exit the filter, it will check whether the SecurityContext in the ThreadLocal SecurityContextHolder has been changed, 
 if it is changed, then store the new SecurityContext into the session
 But in Jboss 3.2.5, when an exception is countered during the request processing, the thread will be killed, 
 and the SecurityContext will not be there, 
 then when call SecurityContextHolder.getContext() will return a Context with new Authenication(normally an Authenication with null priciple). And this Authenication will be used to replace the corrent one in the session

FYI:
I am not sure whether all app servers will kill the thread when an exception is countered, but add one more check here will be more safety:
what I have done in my project is modify here to:
                if (httpSession != null
                    && SecurityContextHolder.getContext().hashCode() != contextWhenChainProceeded
                    && SecurityContextHolder.getContext().getAuthentication()!=null 
                    && SecurityContextHolder.getContext().getAuthentication().isAuthenticated()) {

**Comment by linuxjackto1** [comment]
thanks www.movied.org
