### ISSUE TITLE
OAuth2AuthorizationRequestaFilter to support custom param name when build authorization url

### ISSUE THREAD

**Issue by wodead** [spring-projects/spring-security#4960]
### Summary
When user visits the link
http://localhost:8080/oauth2/authorization/someprovider
OAuth2AuthorizationRequestRedirectFilter will generate the following authorization url
https://someprovider.com/login/oauth/authorize?response_type=code&client_id=my_client_id&scope=user&state=FcJ4j7TwRrF1t6-amfSJIvO6DxDDjXvmYq9FRVSV79c%3D&redirect_uri=call_back_url

But some oauth2 provider uses "appId" instead of "client_id" as param name. 
It will lead an issue.

A possibility to generate the following link is expected.
https://someprovider.com/login/oauth/authorize?response_type=code&appId=my_client_id&scope=user&state=FcJ4j7TwRrF1t6-amfSJIvO6DxDDjXvmYq9FRVSV79c%3D&redirect_uri=call_back_url

Thanks

**Comment by jgrandja** [comment]
@wodead `client_id` is required as per [spec](https://tools.ietf.org/html/rfc6749#section-4.1.1) and `appId` is not a standard parameter as you will notice it's not referenced in the spec at all.

Either way, issue #4911 will provide you the ability to add `appId` as a custom parameter. Closing this as a duplicate.

**Comment by wodead** [comment]
get it ！thanks
