### ISSUE TITLE
Make booleans on UserDetails false by default

### ISSUE THREAD

**Issue by ugultopu** [spring-projects/spring-security#4963]
### Summary

`org.springframework.security.core.userdetails.UserDetails` uses negatives for booleans:

- `isAccountNonExpired`
- `isAccountNonLocked`
- `isCredidentialsNonExpired`
- `isEnabled`

Then, the sample implementation (`org.springframework.security.core.userdetails.User`) provides `true` for each of these booleans:

https://github.com/spring-projects/spring-security/blob/450600cbb8bd931496804e3b17b01c0e7655e27f/core/src/main/java/org/springframework/security/core/userdetails/User.java#L82

(The following is the rest of that constructor)

```java
/**
 * Calls the more complex constructor with all boolean arguments set to {@code true}.
 */
public User(String username, String password,
		Collection<? extends GrantedAuthority> authorities) {
	this(username, password, true, true, true, true, authorities);
}
```

Had these booleans were named as negative, we wouldn't have needed to set them to `true` in the constructor, since the default value for booleans in Java is `false`:

- `isAccountExpired`
- `isAccountLocked`
- `isCredidentialsExpired`
- `isDisabled`

Then, the constructor would have been:

```java
public User(String username, String password,
		Collection<? extends GrantedAuthority> authorities) {
	this.username = username;
	this.password = password;
	this.authorities = authorities;
}
```

### Actual Behavior

Booleans are named positive in `org.springframework.security.core.userdetails.UserDetails`:

- `isAccountNonExpired`
- `isAccountNonLocked`
- `isCredidentialsNonExpired`
- `isEnabled`

### Expected Behavior

Booleans should be named negative in `org.springframework.security.core.userdetails.UserDetails` and relevant business logic change should be performed:

- `isAccountNonExpired`
- `isAccountNonLocked`
- `isCredidentialsNonExpired`
- `isEnabled`

### Version

5.0.0.RELEASE

**Comment by rwinch** [comment]
Even if we wanted to, we cannot make non-passive changes to the API. If you prefer, you can leverage the `User.UserBuilder` which uses properties like `accountExpired`, etc.

**Comment by ugultopu** [comment]
Thanks for responding. Why can't non-passive changes to the API be made? Couldn't the next major version of Spring Security make these changes, since major versions can (and will) have breaking changes?

(I am trying to learn, not to debate. I thought breaking changes can be made in major releases.)
