### ISSUE TITLE
Help needed authorizing an Oauth2 token generated with Google API libraries

### ISSUE THREAD

**Issue by javiersvg** [spring-projects/spring-security#4967]
Problem:
I am working on an application that have an front end that utilizes the Google sign in [library ](https://developers.google.com/identity/sign-in/web/) to obtain user information in the front end and generate a token to login the back-end server. When I send the token to the authorization URL (/login/oauth2/authorization/google) the filter OAuth2LoginAuthenticationFilter is throwing a 
exception because the OAuth2AuthorizationRequest could not be found given that this is the first contact between the front-end application and the server.

Question:
 Is there a way to enable the first contact to the server to be the token authorization?

Code:
Here is the line where the existence of the OAuth2AuthorizationRequest is being validated:
https://github.com/spring-projects/spring-security/blob/edccafca8444178f43f1609a96fb54712ade6a58/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/OAuth2LoginAuthenticationFilter.java#L113

**Comment by jgrandja** [comment]
@javiersvg The [OAuth 2.0 Login](https://docs.spring.io/spring-security/site/docs/5.0.1.BUILD-SNAPSHOT/reference/htmlsingle/#jc-oauth2login) feature is implemented with the [4.1.  Authorization Code Grant](https://tools.ietf.org/html/rfc6749#page-24) using `OAuth2AuthorizationRequestRedirectFilter` for triggering the `Authorization Request` and the `OAuth2LoginAuthenticationFilter` processes the `Authorization Response` on the callback, which subsequently calls the Token endpoint and UserInfo endpoint to login the user. These 2 `Filter`'s work together to achieve OAuth 2.0 Login.

Given the fact that you are using the Google sign in library to login, than you would not use the `OAuth2LoginAuthenticationFilter` or OAuth 2.0 Login feature to sign in. You need to use one or the other, but not both.

Given your question:  

> Is there a way to enable the first contact to the server to be the token authorization?

It's not completely clear to me, but if you are looking to perform authorization of the incoming access token than you are looking for Resource Server functionality. If this is the case than this feature has not been implemented yet. You can track this issue [here](https://github.com/spring-projects/spring-security/issues/4887).

I'm going to close this issue as I feel I have answered your question.

**Comment by javiersvg** [comment]
@jgrandja  thank you very much for the answer. I will track the issue.
