### ISSUE TITLE
JspAuthorizeTag should use Web Application Context instead of Root Context

### ISSUE THREAD

**Issue by splashvarun** [spring-projects/spring-security#4969]
While using authorize JSP tag for validating access rights of the user, the tag file being used is JspAuthorizeTag. This class finds WebInvocationPrivilegeEvaluator in the context to evaluate the url for validating user access. I am configuring cross cutting services in the root context and all controllers, authentication configuration and security concerns in the web application context. But this is not allowing me to use the JSP tag library in the view files.

Currently, it uses the Root context to extract the privilege evaluator as following:
`ApplicationContext ctx = SecurityWebApplicationContextUtils.findRequiredWebApplicationContext(getServletContext());`

This gives an error as the evaluator is not registered in the root context, but in the web context.

Instead, it should use the web application context as following:
`ApplicationContext ctx = RequestContextUtils.findWebApplicationContext((HttpServletRequest)getRequest(), getServletContext());`

Currently, I am using Spring Security version 5.0.0

Reference to old issue: https://github.com/spring-projects/spring-security/issues/2096

**Comment by rwinch** [comment]
Thanks for the report.

Many people configure this in the exact opposite way. For this reason we cannot change the behavior.

You can resolve the issue you are experiencing by setting a `HttpServletRequest` attribute with the name of `WebAttributes.WEB_INVOCATION_PRIVILEGE_EVALUATOR_ATTRIBUTE` with the value of the `WebInvocationPrivilegeEvaluator` you want to be used.
