### ISSUE TITLE
SEC-236: JbossAcegiLoginModule to use ApplicationContext interface

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#497]
["Zheng Shuai":https://jira.spring.io/secure/ViewProfile.jspa?name=zhengshuai](Migrated from ["SEC-236":https://jira.spring.io/browse/SEC-236?redirect=false]) said:

Previously when I try to use Acegi to take over the job of JAAS in Jboss, it always failed. There always give me ClassCastException.
When I check the source code, I find the problem is because  following line:
ClassPathXmlApplicationContext ctx = null;
Here is unreasonable to declare ctx as ClassPathXmlApplicationContext, ApplicationContext is quite enough(I try already). And this allow us to use other implementation in beanRefFactory.xml and will give more flexibility.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
