### ISSUE TITLE
SEC-237: LdapUserSearch throws exception when invoked with an empty username

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#498]
["Bertrand Renuart":https://jira.spring.io/secure/ViewProfile.jspa?name=brenuart](Migrated from ["SEC-237":https://jira.spring.io/browse/SEC-237?redirect=false]) said:

An exception will be thrown if attempt is made to authenticate a user whose username has not been given (empty string). The LdapUserSearch helper will be the first to complain because of an invalid LDAP argument in its query.

Don't know what would be the best solution to handle this case:
- either the upper layers should decide about how to handle an empty username;
- either adapt the Ldap subsystem to cope with it (provided ACEGI itself believes an empty username is valid)

**Comment by linuxjackto1** [comment]
thanks www.movied.org
