### ISSUE TITLE
FreeMarker

### ISSUE THREAD

**Issue by lettgers** [spring-projects/spring-security#4980]
I want to use spring-security in spring-boot with FreeMarker, how can I use the security tag library?

**Comment by rwinch** [comment]
You should be able to use the [Spring Security TagLib](https://docs.spring.io/spring-security/site/docs/current/reference/html/taglibs.html) support with Freemmarker by leveraging FreeMarker's [Using JSP Custom tags in FTL](https://freemarker.apache.org/docs/pgui_misc_servlet.html#autoid_63)

**Comment by lettgers** [comment]
Thank you very much for your answer. I need to try to see the result.

**Comment by lettgers** [comment]
Thank you very much for your answer. I need to try to see the result.

At 2018-02-06 02:02:27, "Rob Winch" <notifications@github.com> wrote:


You should be able to use the Spring Security TagLib support with Freemmarker by leveraging FreeMarker's Using JSP Custom tags in FTL

**Comment by rwinch** [comment]
Im going to close this. Please re-open or create a new issue if you continue to have issues
