### ISSUE TITLE
Dead links to guides in documentation

### ISSUE THREAD

**Issue by g3t0r** [spring-projects/spring-security#4981]
### Summary
Dead links to guides in Spring Security documentation, "Samples and Guides" section

### Actual Behavior
The only working link to guide in "Samples and Guides" section is working. Browser can't find rest of them are returning 404.

![](http://i.imgur.com/XjyiRJy.png)

### Version
5.0.2 SNAPSHOT

**Comment by rwinch** [comment]
Thanks for the report. This is a duplicate of #4327

**Comment by rwinch** [comment]
This is now fixed in master https://docs.spring.io/spring-security/site/docs/current-SNAPSHOT/guides/html5/helloworld-javaconfig.html
