### ISSUE TITLE
SEC-238: Add AuthenticationException to AbstractProcessingFilter.onUnsuccessfulAuthentication method signature

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#499]
["Fabio Grassi":https://jira.spring.io/secure/ViewProfile.jspa?name=fabio](Migrated from ["SEC-238":https://jira.spring.io/browse/SEC-238?redirect=false]) said:

In my opinion it would be handy and in a sense more natural if the method onUnsuccessfulAuthentication of AbstractProcessingFilter would have the same "AuthenticationException failed" parameter that has the calling method unsuccessfulAuthentication.

My use case is that I would like to log failed authentication attempts in a RDBMS. The most natural place seemed onUnsuccessfulAuthentication, which is lacking the exception parameter. I could extract the exception from the ACEGI_SECURITY_LAST_EXCEPTION_KEY session attribute or I could override unsuccessfulAuthentication instead or I could resort to event publishing to obtain the same goal, but it seems to me that adding that parameter would be cheaper and cleaner and coul have other uses.

Thanks in advance, Fabio.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
