### ISSUE TITLE
Cannot serialize OAuth2AuthenticationToken to JSON

### ISSUE THREAD

**Issue by bberto** [spring-projects/spring-security#4991]
### Summary

For a simple app with OIDC login I cannot serialize Principal/OAuth2AuthenticationToken as JSON:

```
@SpringBootApplication
@RestController
public class WebApplication {

  @RequestMapping("/user")
  public Principal user(Principal user) {
    return user;
  }
  
  public static void main(String[] args) {
    SpringApplication.run(WebApplication.class, args);
  }
  
}
```

`Failed to write HTTP message: org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: Unable to convert claim 'iat' to Instant: For input string: "Fri Feb 02 14:05:58 CET 2018"; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Unable to convert claim 'iat' to Instant: For input string: "Fri Feb 02 14:05:58 CET 2018" (through reference chain: org.springframework.security.oauth2.client.authentication.OAuth2AuthenticationToken["principal"]->org.springframework.security.oauth2.core.oidc.user.DefaultOidcUser["issuedAt"])`

### Version
Spring Boot 2.0.0.RC1
Spring Security 5.0.1.RELEASE

**Comment by jgrandja** [comment]
Looks like this is a Jackson related issue. Can you ensure the following dependency is included:

```
<dependency>
    <groupId>com.fasterxml.jackson.datatype</groupId>
    <artifactId>jackson-datatype-jdk8</artifactId>
</dependency>
```

you might need this as well

```
<dependency>
    <groupId>com.fasterxml.jackson.datatype</groupId>
    <artifactId>jackson-datatype-jsr310</artifactId>
</dependency>
```


See the [Jackson docs](https://github.com/FasterXML/jackson-modules-java8) for further info.

Let me know if this resolves your issue.

**Comment by bberto** [comment]
They're both included. I've also tried to update at jackson 2.9.4 without success.

![image](https://user-images.githubusercontent.com/3389771/35740864-71ddc8c4-0836-11e8-94c0-309d87214029.png)

I noticed that [here](https://github.com/spring-projects/spring-security/blob/e6cac604f37cd8e42cec60fb4f4662ef33e76266/oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/ClaimAccessor.java#L85
) claim is a Date, and Long.valueOf raises the NumberFormatException

**Comment by rwinch** [comment]
I'm closing this as a duplicate of #4886
