### ISSUE TITLE
Ensure Spring Security OAuth works well with Sagan

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4993]
### Summary

We should provide a pull request to [Sagan](https://github.com/spring-io/sagan/) to update to use the new Spring Security OAuth support. Along the way we should find any areas for improvements in Spring Security OAuth support and make them.

**Comment by jgrandja** [comment]
@rwinch As mentioned, @bclozel is currently in the process of upgrading Sagan to Spring Boot 2. As soon as that is complete, I'll upgrade it to use the new OAuth client support.

**Comment by jgrandja** [comment]
@bclozel I'm circling back to this issue and wondering if you have already updated Sagan to use Spring Security's OAuth client support?

**Comment by bclozel** [comment]
Hey @jgrandja thanks for reaching out!

We're now using the Spring Security OAuth client support, see the [security config class](https://github.com/spring-io/sagan/blob/4fd1f2f778b560201bc3c5dd2c69b9d30e63b4d3/sagan-site/src/main/java/sagan/site/SecurityConfig.java) and the [github client registration](https://github.com/spring-io/sagan/blob/4fd1f2f778b560201bc3c5dd2c69b9d30e63b4d3/sagan-site/src/main/resources/application.yml#L9-L25).

As far as I understand the only missing piece in our security arrangement would be to use Bearer tokens as an authentication mechanism for the API (see https://github.com/spring-io/sagan/issues/1025).

**Comment by jgrandja** [comment]
Thanks for the update @bclozel !

Bearer token authentication could be configured by adding a `BearerTokenAuthenticationFilter` as @rwinch [mentioned](https://github.com/spring-io/sagan/issues/1025#issuecomment-816173982). Let me know if you need any help with this.

**Comment by jgrandja** [comment]
Resolved as per [comment](https://github.com/spring-projects/spring-security/issues/4993#issuecomment-843030026).
