### ISSUE TITLE
Ensure Spring Security OAuth Support works with CLA tooling

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#4994]
### Summary

We should provide a pull request to [CLA tooling](https://github.com/pivotalsoftware/pivotal-cla) to update to use the new Spring Security OAuth support. Along the way we should find any areas for improvements in Spring Security OAuth support and make them.

Related #4993

**Comment by jgrandja** [comment]
See [PR](https://github.com/pivotalsoftware/pivotal-cla/pull/159)

**Comment by jgrandja** [comment]
@rwinch Is this still valid? I know we are using a new CLA tool?

**Comment by rwinch** [comment]
CLA is still used. Can you please rebase the pr? This can be closed in favor of the pr
