### ISSUE TITLE
Decrease SPRING_SECURITY_CONTEXT and SPRING_SECURITY_SAVED_REQUEST_KEY session keys size

### ISSUE THREAD

**Issue by leenusn** [spring-projects/spring-security#4999]
### Summary

The size of SPRING_SECURITY_CONTEXT and SPRING_SECURITY_SAVED_REQUEST_KEY session key is around 1,285b and 2,174b, as it is saved as object of types org.springframework.security.web.savedrequest.DefaultSavedRequest and org.springframework.security.core.context.SecurityContextImpl. This reduces the number of sessions per tomcat instance per vm significantly and increases operational costs. 

Over a period of several years we have improvised our own application session usage and came to a understanding that keeping an object vs string object in session utilizes less space on jvm heap.

We save about 20+ attributes in session, together they take way less size than that of the above two attributes coming out of spring.

By doing this we are now able to serve more sessions per vm node, which brings our operational cost down.

So please break the above types into individual string type attributes and make use of it in spring projects, or if there is an alternative, please suggest that.

### Actual Behavior

SPRING_SECURITY_CONTEXT and SPRING_SECURITY_SAVED_REQUEST_KEY session keys using more heap memory.

### Expected Behavior

SPRING_SECURITY_CONTEXT and SPRING_SECURITY_SAVED_REQUEST_KEY session keys should use less heap memory.

### Configuration

Spring project with security

### Version

We have seen this in all the versions.

### Sample

Would be present in any spring project implementing security.
![spring session](https://user-images.githubusercontent.com/7027699/35821396-c0177944-0a5d-11e8-86f0-50543ee6fae1.jpg)

**Comment by rwinch** [comment]
I'm closing this as invalid. To scale up you should transfer the state (session) from the actual server and place it in a shared datastore using something like Spring Session http://projects.spring.io/spring-session/
