### ISSUE TITLE
SEC-244: Column names instead of indexes for org.acegisecurity.userdetails.jdbc.JdbcDaoImpl

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#500]
["Rusty Wright":https://jira.spring.io/secure/ViewProfile.jspa?name=lumpynose](Migrated from ["SEC-244":https://jira.spring.io/browse/SEC-244?redirect=false]) said:

In the methods that extend MappingSqlQuery when they fetch the results from the ResultSet they do things like

username = rs.getString(1);

Wouldn't it be more flexible to use the column name instead of the column number?  For example,

username = rs.getString("username");

That way people could use different database setups as long as their column names matched what's in, for example, DEF_USERS_BY_USERNAME_QUERY.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
