### ISSUE TITLE
ServerHttpSecurity.authorizeExchange().pathMatchers(...) doesn't accept reactive EndpointRequest

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects/spring-security#5002]
`HttpSecurity.authorizeRequests().requestMatchers(EndpointRequest.to(...))` works fine with `org.springframework.security.config.annotation.web.builders.HttpSecurity` and `org.springframework.boot.actuate.autoconfigure.security.servlet.EndpointRequest`.

However, `ServerHttpSecurity.authorizeExchange().pathMatchers(EndpointRequest.to(...))` doesn't work with `org.springframework.security.config.web.server.ServerHttpSecurity` and `org.springframework.boot.actuate.autoconfigure.security.reactive.EndpointRequest`.

**Comment by rwinch** [comment]
Thank you for the report. This ticket belongs in Spring Boot, so I'm closing this in favor of spring-projects/spring-boot#11952
