### ISSUE TITLE
Cache headers only if no cache headers set

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#5004]
### Summary

We revert to the behavior of delaying writing the cache control headers it no cache control headers are set

**Comment by nealeu** [comment]
@rwinch Can you confirm that this fixes #4307 ?

**Comment by angeletos** [comment]
Any chance of fix being back ported to Spring Boot 1.5.x?

**Comment by stefanocke** [comment]
@angeletos , it will be backported to upcoming 4.2.5. See #5005

**Comment by angeletos** [comment]
Thank you @stefanocke. Any ETA for 4.2.5?
