### ISSUE TITLE
StrictHttpFirewall in 4.2.4 is documented as being since 5.0.1

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-security#5006]
https://github.com/spring-projects/spring-security/blob/f81b58112b372c48b94e9b0260ecee0853d94243/web/src/main/java/org/springframework/security/web/firewall/StrictHttpFirewall.java#L33

**Comment by rwinch** [comment]
Thanks for the report @wilkinsona! This is now fixed

**Comment by aeyates** [comment]
This class is also in 4.1.5, so the fix does not go back early enough.
