### ISSUE TITLE
SEC-239: Improve ACL support

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#501]
["Erwin Vervaet":https://jira.spring.io/secure/ViewProfile.jspa?name=klr8](Migrated from ["SEC-239":https://jira.spring.io/browse/SEC-239?redirect=false]) said:

In a large scale spring based project we've been implementing, we're using Acegi security to tackle our security concerns.

Authentication and role-based web request security are elegantly handled by Acegi.

The application also requires quite complex domain object security so our first idea was to try and use the Acegi ACL implementation for this. However, we quickly noticed a number of shortcomings with the current (1.0.0 RC2) basic ACL implementation in Acegi and in the end had to develop our own ACL system from scratch and hook it into Acegi (e.g. with a custom AfterInvocationProvider).

Below is a list of the shortcomings in the Acegi basic ACL implementation that we identified:

1) The AclManager & AclProvider interfaces lack methods to get ACLs for multiple objects
Currently these 2 interfaces only have methods to get ACL information for a single object. This can quickly lead to n+1 select problems, especially when filtering objects from a collection.

2) The ACL functionality implemented by org.acegisecurity.acl.basic is too basic
It only supports simple ACL inheritance with override. There is no support for revoking (deny) permissions, no inheritance control for particular entries, ...
As a result it's only usable in applications with very basic ACL requirements.

3) No clean domain model implementing the ACL responsabilities for org.acegisecurity.acl.basic
There is no Acl abstraction and the AclEntry is just a marker interface. BasicAclEntry is just a DTO with a permission check method. Acl hierarchy calculations are in the BasicAclProvider and actual ACL 'interpretation' code to make access decisions is copied in several places, notably BasicAclEntryAfterInvocationProvider, BasicAclEntryAfterInvocationCollectionFilteringProvider, AclTag and BasicAclEntryVoter. As a result you don't have a single point of change to customize and enhance ACL behaviour (see point 2).

4) BasicAclEntryAfterInvocationProvider & BasicAclEntryAfterInvocationCollectionFilteringProvider should share a common superclass to enforce consistent configuration
Now there is a lot of duplicate code between these 2 classes.

5) No ACL DAOs to efficiently load hierarchies of ACLs
Oracle's hierarchical query support makes it easy to load up an entire hierarchy of ACLs for a domain object (or collection of domain objects) in a signle query. However, the basic implementation does not give you any way to easily hook something like that into Acegi without resorting to shutgun surgery (see point 3).

6) It's questionable whether the list of GrantedAuthorities held by an Authentication should be cached in the object
Since this list might change frequently, it's better to reload it every time an authorization check needs to be done.

IMHO the ACL package needs a redesign to bring it up to par, especially regarding point 1. Since backwards compatiblity will be a real issue once 1.0.0 is final, I'm proposing this (minor) redesign for the 1.0.0 release.
I would also suggest to either replace the 'basic' implementation with a more usable one or to provide a second ACL implementation that is more capable.

Erwin

**Comment by linuxjackto1** [comment]
thanks www.movied.org
