### ISSUE TITLE
scope / scopes -- typo in OAuth2 documentation?

### ISSUE THREAD

**Issue by idrm** [spring-projects/spring-security#5012]
### Summary

In section "5.7.3 Spring Boot 2.0 Property Mappings" of the documentation for OAuth2 logins one of the config props is listed as `spring.security.oauth2.client.registration.[registrationId].scope`, yet the name of the field inside the ClientRegistration class is `scopes`. 

Should that read `spring.security.oauth2.client.registration.[registrationId].scopes` instead?

### Version

Current version of spring security reference documentation.

**Comment by jgrandja** [comment]
@idrm The [`OAuth2ClientProperties`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/client/OAuth2ClientProperties.java#L110) defined in Spring Boot 2.0 names the `OAuth2ClientProperties.Registration.scope` property in singular, whereas the `ClientRegistration.scopes` property defined within Spring Security 5.0 is plural. The documentation is correct and the Spring Boot auto-configuration is working as expected.
