### ISSUE TITLE
Reactive: Principal of ServerWebExchange is empty?

### ISSUE THREAD

**Issue by stphngrtz** [spring-projects/spring-security#5013]
### Summary

I'm using Spring Cloud Gateway with (reactive) Spring Security. I'm trying to access the principal via `ServerWebExchange`, which is basically a `SecurityContextServerWebExchange`, but it is empty.

### Actual Behavior

The principal is empty.

### Expected Behavior

The principal should contain the current authentication.

### Configuration

See [this repository](https://github.com/stphngrtz/spring-cloud-gateway-issue-144) and [this issue](https://github.com/spring-cloud/spring-cloud-gateway/issues/144) at Spring Cloud Gateway.

### Version

Spring Boot Starter `2.0.0.M7`
-> Spring Security `5.0.0.RELEASE`
Spring Cloud `Finchley.M5`
-> Spring Cloud Gateway `2.0.0.M5`

### Sample

See [this repository](https://github.com/stphngrtz/spring-cloud-gateway-issue-144) and [this issue](https://github.com/spring-cloud/spring-cloud-gateway/issues/144) at Spring Cloud Gateway.

**Comment by rwinch** [comment]
Thanks for the report. You need to ensure that the `Mono<Principal>` is part of the Reactor pipeline. I created a PR which fixes the sample https://github.com/stphngrtz/spring-cloud-gateway-issue-144/pull/1
