### ISSUE TITLE
Attribute SPRING_SECURITY_CONTEXT is not serializable with SAML extension

### ISSUE THREAD

**Issue by DavesMan** [spring-projects/spring-security#5017]
### Summary

When we use Spring + Spring Security with SAML extension the bean under SPRING_SECURITY_CONTEXT session key is not serializable although is it declared to be.

### Actual Behavior

This results in
**SessionContextMBeanAdapter findAttCausingNotSerializableException Miscellaneous data: Attribute "SPRING_SECURITY_CONTEXT" is declared to be serializable but is found to generate exception "java.io.NotSerializableException" with message "org.opensaml.saml2.common.impl.ExtensionsImpl". Fix the application so that the attribute "SPRING_SECURITY_CONTEXT" is correctly serializable at runtime.**

ExtensionsImpl contains IndexedXMLObjectChildrenList which is child of AbstractList - and that is not Serializable

### Expected Behavior

org.opensaml.saml2.common.impl.ExtensionsImpl should be Serializable or the context bean should not.

### Configuration

IBM WebSphere 9.0.0.6
IBM Java JDK 8

### Version

Spring 4.3.8
Spring Security 4.2.2
Spring SAML extension 1.0.2

**Comment by rwinch** [comment]
Thanks for the report. I moved this to the Spring Security SAML project https://github.com/spring-projects/spring-security-saml/issues/226
