### ISSUE TITLE
Multiple broken link

### ISSUE THREAD

**Issue by thibaultfalque** [spring-projects/spring-security#5019]
### Summary

In this [page](http://projects.spring.io/spring-security/) the getting started link provoke a 404 error; 
In this [page](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#getting-started) in the table 1: 

- Hello Spring Security Guide link is broken 
- Hello Spring Security Boot Guide link is broken 
- Hello Spring Security XML Guide link is broken 
- Hello Spring MVC Security Guide link is broken 
- Custom Login Form Guide link is broken 

### Actual Behavior

Go to this [page](http://projects.spring.io/spring-security/) and click on "getting started" link. 

### Expected Behavior

The getting started page.

**Comment by rwinch** [comment]
Thanks for the report. This appears to be a duplicate of #4327 As soon as we perform the release it will start to work again
