### ISSUE TITLE
SEC-240: Remove log4j.properties from release JARs

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#502]
["Ruslan Khafizov":https://jira.spring.io/secure/ViewProfile.jspa?name=hiron](Migrated from ["SEC-240":https://jira.spring.io/browse/SEC-240?redirect=false]) said:

log4j.properties is included in acegi-security-1.0.0-RC2.jar. In certain circumstances this prevent log4j to load user's config file, instead log4j configured from log4j.properties from acegi-security-1.0.0-RC2.jar. While it can be workarounded by passing configuration filename property to log4j or by using log4j.xml it is undesirable anyway because it takes some time to understand why log4j doesn't work.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
