### ISSUE TITLE
Sessions not working in App Engine without remember me

### ISSUE THREAD

**Issue by mlev** [spring-projects/spring-security#5021]
### Summary
In App Engine I am unable to get sessions working without enabling remember me. There seems to be a difference in the way the HttpSession gets populated for a username/password login and a remember me login. 

Without remember me enabled the SPRING_SECURITY_CONTEXT attribute of the HttpSession is always null. With remember me enabled the HttpSession gets populated - but only on the second request - i.e. after a remember me login.

It works locally in the App Engine development environment but not when deployed to a real environment. This initially made me think this was a GAE quirk but seems odd that the remember-me login gets persisted consistently.

### Actual Behavior

- When the HttpSession is populated after a username/password login the Spring Context is null when the next request comes in.
- When the HttpSession is populated after a remember-me login the Spring Context is attached to session for subsequent requests.

In both scenarios the logs say the session has been stored to the session:

1. POST to /login. UsernamePasswordAuthenticationToken written to session

[f~busker-spring-react-aws-dev/1.407671414909870650].<stdout>: 2018-02-15 11:33:59.428 DEBUG 1 --- [RequestE3403425] w.c.HttpSessionSecurityContextRepository : SecurityContext 'org.springframework.security.core.context.SecurityContextImpl@bbd51b11: Authentication: org.springframework.security.authentication.UsernamePasswordAuthenticationToken@bbd51b11: Principal: org.springframework.security.core.userdetails.User@36ebcb: Username: user; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_USER; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@fffef2ea: RemoteIpAddress: 101.164.228.117; SessionId: eAr2_gSpIvXbtgRSH5fHZg; Granted Authorities: ROLE_USER' stored to HttpSession: 'com.google.apphosting.runtime.jetty9.SessionManager$AppEngineSession:eAr2_gSpIvXbtgRSH5fHZg@850722297

2. GET “/“ - the session exists but SPRING_SECURITY_CONTEXT is null

[f~busker-spring-react-aws-dev/1.407671414909870650].<stdout>: 2018-02-15 11:33:59.614 DEBUG 1 --- [Request6D054958] w.c.HttpSessionSecurityContextRepository : HttpSession returned null object for SPRING_SECURITY_CONTEXT

3. There’s no spring context so remember-me kicks in and stores the context to the session

[f~busker-spring-react-aws-dev/1.407671414909870650].<stdout>: 2018-02-15 11:33:59.619 DEBUG 1 --- [Request6D054958] w.c.HttpSessionSecurityContextRepository : SecurityContext 'org.springframework.security.core.context.SecurityContextImpl@bbd51b11: Authentication: org.springframework.security.authentication.RememberMeAuthenticationToken@bbd51b11: Principal: org.springframework.security.core.userdetails.User@36ebcb: Username: user; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_USER; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@fffef2ea: RemoteIpAddress: 101.164.228.117; SessionId: eAr2_gSpIvXbtgRSH5fHZg; Granted Authorities: ROLE_USER' stored to HttpSession: 'com.google.apphosting.runtime.jetty9.SessionManager$AppEngineSession:eAr2_gSpIvXbtgRSH5fHZg@1495129468

4. On subsequent requests the context is loaded from HttpSession

[f~busker-spring-react-aws-dev/1.407671414909870650].<stdout>: 2018-02-15 11:36:21.235 DEBUG 1 --- [RequestBDA9DB6D] w.c.HttpSessionSecurityContextRepository : Obtained a valid SecurityContext from SPRING_SECURITY_CONTEXT: 'org.springframework.security.core.context.SecurityContextImpl@bbd51b11: Authentication: org.springframework.security.authentication.RememberMeAuthenticationToken@bbd51b11: Principal: org.springframework.security.core.userdetails.User@36ebcb: Username: user; Password: [PROTECTED]; Enabled: true; AccountNonExpired: true; credentialsNonExpired: true; AccountNonLocked: true; Granted Authorities: ROLE_USER; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@fffef2ea: RemoteIpAddress: 101.164.228.117; SessionId: eAr2_gSpIvXbtgRSH5fHZg; Granted Authorities: ROLE_USER'

### Expected Behavior

Sessions should work without requiring remember me enabled. The SPRING_SECURITY_CONTEXT should be populated on the HttpSession after the first login request.

### Configuration

I’ve recreated this using the simplest config I could manage:

```
http
    .csrf().disable()
    .formLogin()
.and()
    .authorizeRequests()
    .anyRequest().authenticated()
.and()
    .rememberMe();
```

App Engine Standard Java 8
App Engine Sessions are enabled

### Version

4.2.4 (Spring boot 1.5.10). Tried Spring boot 1.4.7 and behaved the same.

**Comment by mlev** [comment]
After a bit more digging the difference between the Login and the Remember Me paths is that on successful form login the `UsernamePasswordAuthenticationFilter` does not run the rest of the filter chain. Instead it returns/redirects/forwards based on the configured `AuthenticationSuccessHandler`. The Spring Context is still written to the session by the `SecurityContextPersistenceFilter` but in this scenario it doesn't "stick".

For a Remember Me login - the user is logged in but the chain is continued as normal so we can hit the requested endpoint. The `SessionManagementFilter` kicks in and eagerly saves the Context to the http session. This time the context is saved on the session.

**Comment by doctorseus** [comment]
I have the same problem. Running a Spring Boot / Spring Security Application with 1.4.9 on the Google App Engine Classic.

After the POST /login I see the UsernamePasswordAuthenticationFilter successfully requesting the User object from my UserDetailsService implementation and updating the SecurityContextHolder.

But after the redirect to the landing page it again says: (same as in the /login POST)
2018-03-16 15:23:33.930 DEBUG 1 --- [Request56830C79] w.c.HttpSessionSecurityContextRepository : HttpSession returned null object for SPRING_SECURITY_CONTEXT
2018-03-16 15:23:33.930 DEBUG 1 --- [Request56830C79] w.c.HttpSessionSecurityContextRepository : No SecurityContext was available from the HttpSession: com.google.apphosting.runtime.jetty9.SessionManager$AppEngineSession:amo6tcpnq7loLCY5F-p98g@157276680. A new one will be created.

Then of course it will redirect it again back to /login and there the same thing again. SecurityContextHolder is null and a new Anonymous object will be created. For me currently it does not even work when I configure .and().rememberMe().

When I compare it to my local logs then on the AppEngine it also says:
2018-03-16 15:23:34.093 DEBUG 1 --- [Request88CF1046] w.c.HttpSessionSecurityContextRepository : No SecurityContext was available from the HttpSession: com.google.apphosting.runtime.jetty9.SessionManager$AppEngineSession:amo6tcpnq7loLCY5F-p98g@872766161. A new one will be created.

**Comment by mlev** [comment]
Figured this one out - this isn't a spring issue so will close.

The issue is caused by:

- GAE deployment injects filters into web.xml (or creates one if you're not using one) - including a SaveSessionFilter 
- Spring defined filters are registered dynamically and get invoked **before** any of those defined in web.xml

So for a request that is dealt with solely in the Spring filter chain (like login) it never reaches the SaveSessionFilter. But for a request that reaches a controller method the entire filter chain is executed and changes are saved - but anything set in the Spring filters after the SaveSessionFilter has been invoked would also be lost.

It seems the only way to influence Filter ordering with Servlet 3.1 is to define them in web.xml. So to fix this I’ve had to define the important Spring filters in web.xml as DelegatingFilterProxys. e.g. 

```
    <filter>
        <filter-name>requestContextFilter</filter-name>
        <filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>requestContextFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>

    <filter>
        <filter-name>springSecurityFilterChain</filter-name>
        <filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>springSecurityFilterChain</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>
```

**Comment by osaetinevbuoma** [comment]
This is over a year old but the problem is still relevant. I was able to solve my problem by building on your experience with `rememberMe()`. Instead of giving the user the option of a remember me checkbox, I used `.and().rememberMe().alwaysRemember(true)`. Whether it's an efficient solution is another question but it helped.
