### ISSUE TITLE
Snapshot javadoc and source jars are stale

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-security#5024]
There appears to a problem with the publication of Spring Security snapshots that's causing the javadoc and source jars to be stale. For example, at the time of writing, [`spring-security-core`](https://repo.spring.io/libs-snapshot-local/org/springframework/security/spring-security-core/5.0.2.BUILD-SNAPSHOT/) contains the following files:

```
spring-security-core-5.0.2.BUILD-20180215.064622-50-javadoc.jar   15-Feb-2018 23:09  957.01 KB
spring-security-core-5.0.2.BUILD-20180215.064622-50-sources.jar   15-Feb-2018 23:09  452.36 KB
spring-security-core-5.0.2.BUILD-20180215.230911-51-javadoc.jar   15-Feb-2018 23:45  956.80 KB
spring-security-core-5.0.2.BUILD-20180215.230911-51-sources.jar   15-Feb-2018 23:45  452.36 KB
spring-security-core-5.0.2.BUILD-20180215.230911-51.jar           15-Feb-2018 23:09  411.92 KB
spring-security-core-5.0.2.BUILD-20180215.230911-51.pom           15-Feb-2018 23:09  6.83 KB
spring-security-core-5.0.2.BUILD-20180215.234526-52-javadoc.jar   16-Feb-2018 06:46  956.85 KB
spring-security-core-5.0.2.BUILD-20180215.234526-52-sources.jar   16-Feb-2018 06:46  452.36 KB
spring-security-core-5.0.2.BUILD-20180215.234526-52.jar           15-Feb-2018 23:45  411.92 KB
spring-security-core-5.0.2.BUILD-20180215.234526-52.pom           15-Feb-2018 23:45  6.83 KB
spring-security-core-5.0.2.BUILD-20180216.064654-53.jar           16-Feb-2018 06:46  411.86 KB
spring-security-core-5.0.2.BUILD-20180216.064654-53.pom           16-Feb-2018 06:46  6.83 KB
```

Note that the latest jar and pom are from build 53 but the latest sources and javadoc are from build 52. We had this problem in Boot at one point and it was caused by the [order in which the artifacts were being published](https://github.com/spring-io/artifactory-resource/issues/3).

As I'm writing this, I have a recollection that we've already discussed this for Security too, but I've searched for an existing issue and failed to find one. Sorry if this is a duplicate.

**Comment by wilkinsona** [comment]
Looking more closely at the timestamps. It looks as if `spring-security-core-5.0.2.BUILD-20180215.234526-52-javadoc.jar` and `spring-security-core-5.0.2.BUILD-20180215.234526-52-sources.jar` are actually from build 53 but they've been named incorrectly.

**Comment by rwinch** [comment]
@wilkinsona Thanks for the report. This is caused by the fact that Artifactory breaks if you deploy the pom after the jar. Unfortunately, we use JFrog's Gradle Artifactory Plugin which deployed in the incorrect order. Since we originally discovered the issue a workaround has been provided to the Gradle Artifactory Plugin. See [GAP-279](https://www.jfrog.com/jira/browse/GAP-279)

We need to update to use that version of the plugin to work around the Artifactory bug.
