### ISSUE TITLE
SEC-246: Enable late-binding of UserDetailsService on DaoAuthenticationProvider

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#503]
["Assaf Urieli":https://jira.spring.io/secure/ViewProfile.jspa?name=assaf](Migrated from ["SEC-246":https://jira.spring.io/browse/SEC-246?redirect=false]) said:

When using Acegi with DependencyInjectionInterceptorFactoryBean, I get circular dependencies around the SessionFactory.
For a full description of problem, see http://forum.springframework.org/showthread.php?t=24088

To get around the circular dependencies, I need to be able to late-bind one of the dependencies.
The simplest seems to be UserDetailsService  on DaoAuthenticationProvider.

To enable a sub-class to late-bind on DaoAuthenticationProvider, we need to replace the following line:
loadedUser = this.userDetailsService.loadUserByUsername(username);
with
loadedUser = this.getUserDetailsService().loadUserByUsername(username);

If we want to directly enable late-binding on DaoAuthenticationProvider (rather than letting an interested user subclass), we can furthermore add the following:
public class DaoAuthenticationProvider
    extends AbstractUserDetailsAuthenticationProvider
    implements BeanFactoryAware {

```
private BeanFactory beanFactory;
private String userDetailsServiceName;
private UserDetailsService userDetailsService;
...
public void setBeanFactory(BeanFactory beanFactory) throws BeansException {
   this.beanFactory = beanFactory;
}

public BeanFactory getBeanFactory() {
    return beanFactory;
}

/**
 * Allows late binding to the userDetailsService to avoid circular dependencies.
 */
public void setUserDetailsServiceName(String userDetailsServiceName) {
    this.userDetailsServiceName = userDetailsServiceName;
}

public UserDetailsService getUserDetailsService() {
    if (this.userDetailsService == null) {
        this.userDetailsService = (UserDetailsService)
                getBeanFactory().getBean(this.userDetailsServiceName, UserDetailsService.class);
    }
    return this.userDetailsService;
}

public void setUserDetailsService(UserDetailsService userDetailsService) {
    this.userDetailsService = userDetailsService;
}

 protected void doAfterPropertiesSet() throws Exception {
    Assert.isTrue(this.userDetailsService!=null||this.userDetailsServiceName!=null,
    "Either a UserDetailsService must be set, or a late-binding UserDetailsServiceName");
}
```

...

Regards,
Assaf Urieli

**Comment by linuxjackto1** [comment]
thanks www.movied.org
