### ISSUE TITLE
SEC-241: Add support for salted LDAP passwords to PasswordComparisonAuthenticator

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#504]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-241":https://jira.spring.io/browse/SEC-241?redirect=false]) said:

Only SHA encoding is supported. Support for SSHA etc would be nice.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
