### ISSUE TITLE
Can i append some information in oauth/check_token endpoint and retrieve it at authorization server?

### ISSUE THREAD

**Issue by trueKiller07** [spring-projects/spring-security#5041]
I have mentioned the problem in detail on stack-overflow.
Here is the link : https://stackoverflow.com/questions/48806722/can-i-append-some-information-in-oauth-check-token-endpoint-and-retrieve-it-at-a

I have been looking for the solution past 2 weeks. 
Please have a look.

**Comment by jgrandja** [comment]
@trueKiller07 Can you please log this issue [here](https://github.com/spring-projects/spring-security-oauth/issues)

**Comment by trueKiller07** [comment]
@jgrandja Here is the link : https://github.com/spring-projects/spring-security-oauth/issues/1298

Please have a look buddy.
