### ISSUE TITLE
Can we add custom AccessDecisionVoter in pure Authorization server?

### ISSUE THREAD

**Issue by trueKiller07** [spring-projects/spring-security#5042]
I have mentioned the problem in detail on stack-overflow.

Here is the link : https://stackoverflow.com/questions/48849961/can-we-add-custom-accessdecisionvoter-in-pure-authorization-server

I have been looking for the solution past 3 weeks.
Please have a look.

**Comment by jgrandja** [comment]
@trueKiller07 Can you please log this issue [here](https://github.com/spring-projects/spring-security-oauth/issues)
