### ISSUE TITLE
3.5 Handling Logouts Docs

### ISSUE THREAD

**Issue by zaurhasanov** [spring-projects/spring-security#5043]
### Summary
In section 3,5, there are JavaDoc links that are not working. Their responds are not found. They need update.

### Actual Behavior
Unavailability of Documentation   

### Expected Behavior
Update links

### Sample
 [https://docs.spring.io/spring-security/site/docs/current/apidocs/org/springframework/security/config/annotation/web/configurers/LogoutConfigurer.html#logoutUrl(java.lang.String)](url)

**Comment by jzheaux** [comment]
It appears the links to `current` should be `/api/` instead of `/apidocs/`, e.g.

https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/annotation/web/configurers/LogoutConfigurer.html#logoutUrl(java.lang.String)

**Comment by jzheaux** [comment]
Closing this issue as a duplicate of #4330.
