### ISSUE TITLE
Support for Cloud Gateway, Hystrix, Ribbon & Feign

### ISSUE THREAD

**Issue by thekalinga** [spring-projects/spring-security#5045]
Does spring security OAuth client currently support

* Cloud gateway filter integration, i.e populate authentication for each request, before it proxies the request
* Make use of Ribbon (via discovery client) for client side load balancing between multiple auth servers
* Hystrix for breaking the circuit when the auth server is not reachable
* OAuth token proxying downstream (like it used before) via Feign
* How will refresh token flow work

If any part/all of them are not supported, would be great if you can provide an outline on

* How to integrate Ribbon & hystix for access token lookups by oauth2 client
* When can we expect each of these features in Spring Security 5

**Comment by jgrandja** [comment]
@thekalinga The OAuth client support in Spring Security 5 is in it's early stages at the moment and does not currently provide support/integration with the mentioned Spring Cloud features.

As well, these features/integrations would not live in Spring Security 5 but would rather be built within the Spring Cloud related project. Feel free to ask these questions in the appropriate Spring Cloud project or log a new feature request.

**Comment by thekalinga** [comment]
@jgrandja Thanks for the clarification. Will attempt to find/open issues in respective individual projects.
