### ISSUE TITLE
SEC-242: Logger in AbstractProcessingFilter

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#505]
["Fabio Grassi":https://jira.spring.io/secure/ViewProfile.jspa?name=fabio](Migrated from ["SEC-242":https://jira.spring.io/browse/SEC-242?redirect=false]) said:

In AbstractProcessingFilter the protected instance logger of class Log is declared static and directly linked to AbstractProcessingFilter.class. This way it is not easy to determine if the logging comes from AbstractProcessingFilter or one of its subclasses. It would be much better if it was an instance variable linked to the class of the instance, the same way most of Spring general pourpose classes do. In other words the line

protected static final Log logger = LogFactory.getLog(AbstractProcessingFilter.class);

should be rewritten as

protected final Log logger = LogFactory.getLog(this.getClass());

Thanks in advance, Fabio.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
