### ISSUE TITLE
SEC-243: SessionRegistryImpl.getAllSessions(Object) incorrectly includes expired and destroyed sessions

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#506]
["frank liu":https://jira.spring.io/secure/ViewProfile.jspa?name=ekfliu](Migrated from ["SEC-243":https://jira.spring.io/browse/SEC-243?redirect=false]) said:

The function SessionRegistryImpl.getAllSessions(principal) returns all session associated with the principal, even it is marked as expired. This is in violation of the SessionRegistry interface contract.

The fix is to filter out any expired session information return by function sessionRegistry.getAllSessions(principal)

**Comment by linuxjackto1** [comment]
thanks www.movied.org
