### ISSUE TITLE
AbstractSecurityWebApplicationInitializer#onStartup should use template method to create root application context.

### ISSUE THREAD

**Issue by ansgarkonermann** [spring-projects/spring-security#5060]
### Summary

We would like to use our own subclass of AnnotationConfigWebApplicationContext to inject another PropertySource into the Environment used during application context initialisation. We need the ServletContext to construct this instance of our ApplicationContext subclass.

Our Spring application currently does not (yet) use Spring Security and uses a custom WebApplicationInitializer. We would like to introduce Spring Security and preferr to use the standard AbstractSecurityWebApplicationInitializer as provided by Spring Security.

### Actual Behavior
AbstractSecurityWebApplicationInitializer.onStartup is final, so we're stuck with copy/pasting the whole class just to change the type of rootAppContext 

### Expected Behavior

Enhance AbstractSecurityWebApplicationInitializer, for example by introducing a hook method createRootApplicationContext(ServletContext), which by default returns a new AnnotationConfigWebApplicationContext but can be overwritten by subclasses.

### Version

Spring Security 5.0.3.RELEASE; Spring Framework 5.0.4.RELEASE

**Comment by rwinch** [comment]
If I understand correctly, I would recommend you creating a subclass of `AbstractContextLoaderInitializer` and create your `AnnotationConfigWebApplicationContext` in there. Then you can use a subclass of `AbstractSecurityWebApplicationInitializer` default constructor to leverage the existing `AbstractContextLoaderInitializer`.

**Comment by ansgarkonermann** [comment]
:+1: 
Perfect, works like a charm. Thanks a lot. 
I owe you a beer, please ping me when you happen to visit Berlin :-)

**Comment by rwinch** [comment]
Glad that worked! No beer necessary, but do keep the feedback coming :)
