### ISSUE TITLE
Lost because of DefaultSavedRequest

### ISSUE THREAD

**Issue by mariograf** [spring-projects/spring-security#5063]
### Summary
This is the first issue I report, sorry if something is missing or wrong. Thank you in advance!

After debugging, my understanding is that org.springframework.security.web.savedrequest.DefaultSavedRequest.class is used to cache requests in case authentication fails. If no authorization is provided, a call to a secured rest endpoint will be rejected and the request will be cached.

If a subsequent call contains a valid authorization (e.g. jwt-token) in a header field (e.g. "Authorization" = "Bearer ey...") the call to the secured endpoint will be accepted but in the security filter chain the actual request will be replaced by the cached request (which does not contain the Authorization header). Accessing the "Authorization" header at the called endpoint (e.g. to read or forward the token) will result in a NullPointer.

### Actual Behavior
In class org.springframework.security.web.savedrequest.DefaultSavedRequest, method doesRequestMatch does not take headers into account when comparing a new request with a saved request. 

As a consequence in class org.springframework.security.web.savedrequest.RequestCacheAwareFilter method doFilter, replaces requests with cached requests, even if headers are different:

```
HttpServletRequest wrappedSavedRequest = requestCache.getMatchingRequest((HttpServletRequest) request, (HttpServletResponse) response);

chain.doFilter(wrappedSavedRequest == null ? request : wrappedSavedRequest, response);
```

### Expected Behavior

I would expect, that headers are also taken into account, when comparing requests, especially the "Authorization" header in this case.

### Configuration

SpringBootApp:

```
@Configuration
@EnableWebSecurity
@EnableResourceServer
public class SecurityConfig extends ResourceServerConfigurerAdapter {

[...]    

@Override
    public void configure(HttpSecurity http) throws Exception {

        http
                .sessionManagement()
                .sessionCreationPolicy(SessionCreationPolicy.NEVER).and()
                .authorizeRequests()
                .antMatchers(GET, "/testendpoint").hasAnyAuthority("appname.test")
                .anyRequest().permitAll();    
    }
}

[...]
```

### Version
   
<groupId>org.springframework.security</groupId>
<artifactId>spring-security-web</artifactId>
<version>4.2.3.RELEASE</version>

Class seems to behave exactly like that in current version as well.

### Sample

- Secure a rest endpoint via OAauth
- Call the endpoint without set "Authorization" header
- Call the endpoint again with properly set "Authorization" header
- Access "Authorization" header in endpoint method -> NullPointer
- Call the endpoint again with properly set "Authorization" header
- Access "Authorization" header in endpoint method -> Header will be set

**Comment by rwinch** [comment]
Thanks for reaching out!

> After debugging, my understanding is that org.springframework.security.web.savedrequest.DefaultSavedRequest.class is used to cache requests in case authentication fails. If no authorization is provided, a call to a secured rest endpoint will be rejected and the request will be cached.

Typically the RequestCache is used for a browser based application. The reason is that if a user types a URL and they are not authenticated they will be redirected to a log in page. Upon log in, they should be sent to the original page (this is what the RequestCache does).

It is not common for REST based architecture since a rest client can inspect the response and if the response indicates the user is not authenticated, the rest client can perform authentication and replay the request itself. This is not possible in a browser, but is with a rest client.

I'm closing this as won't fix, but please reopen or create a new ticket if you disagree.

**Comment by mariograf** [comment]
Thank you for the quick reply. I just stumbled over this in the context of rest development. 

This might also be an issue for UI-based access. If some header fields are set as a result of the login (e.g. username, jwt-token, whatever) this information will get lost. Unfortunately I'm not experienced in UI-development, so I can't evaluate that. 

Another case, were this at least might lead to confusion is during component testing. If jwt-tokens in the header are used for authentication one might wright an access test, that checks if access without a jwt-token leads to a 401 unauthorized. If a subsequent test replays the same http-call, just with a jwt-token in the header, this jwt-token will not be passed to the controller (where it could be expected and used). For sure a null check could be performed but I wouldn't expect access to a secured endpoint without any authorization header.

I would reopen this ticket (it seems I lack some rights to do so), since this puzzled me for quite a while and I don't want others to waste their time. Nevertheless, if you still think this is not an issue, please ignore this comment. Thank you!

**Comment by rwinch** [comment]
> This might also be an issue for UI-based access. If some header fields are set as a result of the login (e.g. username, jwt-token, whatever) this information will get lost. Unfortunately I'm not experienced in UI-development, so I can't evaluate that.

RequestCache is only intended for a browser which will send all of the same headers. A rest client that can send custom header (e.g. username, jwt-token, whatever) should use NullRequestCache which does nothing. It is up to the rest client to re-send the custom headers on subsequent requests.

What's more is if they header contains an invalid credential it would trigger an authentication attempt that fails. Then the client would be asked to log in. The client would log in correctly, but then the request would be replayed w/ the invalid credential in the header which would possibly cause an infinite loop.

Overall, this is not something we want to do.

**Comment by mariograf** [comment]
NullRequestCache did the trick, thank you for the clarification!
