### ISSUE TITLE
SEC-245: Support binary SHA values in PasswordComparisonAuthenticator

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#507]
["Carey Evans":https://jira.spring.io/secure/ViewProfile.jspa?name=carey](Migrated from ["SEC-245":https://jira.spring.io/browse/SEC-245?redirect=false]) said:

The LDAP server that comes with IBM i5/OS encodes userPassword as "{SHA}" followed by the binary value of the SHA checksum for the password. For example, for "password", the value is the 25 bytes { 0x7b, 0x53, 0x48, 0x41, 0x7d, 0x5b, 0xaa, 0x61, 0xe4, 0xc9, 0xb9, 0x3f, 0x3f, 0x06, 0x82, 0x25, 0x0b, 0x6c, 0xf8, 0x33, 0x1b, 0x7e, 0xe6, 0x8f, 0xd8 }.

It's pretty easy to write a PasswordEncoder that does this, at least when using ISO-8859-1, but it would be nice if PasswordComparisonAuthenticator would try this format out of the box when the retrievedPassword attribute is binary, instead of interpreting it as a string in the default character encoding.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
