### ISSUE TITLE
SEC-250: Where is the Md5PasswordDecoder???? Client requirement.

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#508]
["Jeryl Cook":https://jira.spring.io/secure/ViewProfile.jspa?name=twoencore](Migrated from ["SEC-250":https://jira.spring.io/browse/SEC-250?redirect=false]) said:

We plan to convert all our passwords using using the net.sf.acegisecurity.providers.encoding.Md5Passwor dEncoder  i preached about it for months to my clients..i should have checked it twice..but

i noticed there was no .decoding package ,..leave it up to the developer(me) who implements the security to decide what to do with the decoder....

now i am wondering where do i set the passphrase?, i hope the passphrase is not set automatically in every package ACEGI .jar...is that the reason the decoding code is left out??? i hope no,.... security is in the passphrase, and not the in the "salt" .....salt is the only public method i see..

Anway
our customer has this requirement because..
in case we have to get access to a user's account on our system..we need the decoding package..is it avaible???? I've been preaching about this framework now we may not use it cause there is no decoding... or we may just have to write our own.:P.

i hope you will put this in the next release..

---

/^\ Pharaoh /^\
http://pharaohofkush.blogspot.com/

Jeryl Cook

**Comment by linuxjackto1** [comment]
thanks www.movied.org
