### ISSUE TITLE
Add CookieServerCsrfTokenRepository

### ISSUE THREAD

**Issue by edeandrea** [spring-projects/spring-security#5083]
A cookie implementation of `ServerCsrfTokenRepository` (like `CookieCsrfTokenRepository`) is missing. In this implementation it would be nice to allow the setting of the domain as well.

**Comment by edeandrea** [comment]
I added [PR 5245](https://github.com/spring-projects/spring-security/pull/5245) for this.

**Comment by rwinch** [comment]
Thanks for creating this ticket and the PR! This is now merged into master. Please see the referenced commits for the polish that I applied
