### ISSUE TITLE
SEC-247: Allow to specify resources that shouldn't be filtered in FilterChainProxy

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#509]
["Konstantin Shaposhnikov":https://jira.spring.io/secure/ViewProfile.jspa?name=ksh](Migrated from ["SEC-247":https://jira.spring.io/browse/SEC-247?redirect=false]) said:

It would be good to allow to specify resources that shouldn't be filtered at all in FilterChainProxy, like this:

 <bean id="filterChainProxy" class="org.acegisecurity.util.FilterChainProxy">
   <property name="filterInvocationDefinitionSource">
     <value>
       CONVERT_URL_TO_LOWERCASE_BEFORE_COMPARISON
       PATTERN_TYPE_APACHE_ANT
       /**/*.css=
       /**/_.gif=
       /__/_.js=
       /**/*.png=
       /**=httpSessionContextIntegrationFilter,.. (other acegi filters) ...
     </value>
   </property>
 </bean>

Note that such declaration worked with acegisecurity 0.9.0 and it was quite useful, because ant patterns much more flexible then those provided by filter-mapping (web.xml). It would be good to restore this behavior - when right hand side is empty then no filters will be applied to request that matches specified pattern.

It is probably make sense to introduce some sort of express value - such as "#NONE#" - rather than
allowing the right hand side of the equals to be entirely empty. The alternative is to use a NullFilter, but this increases invocation time unnecessarily.

Fix should be quite easy. Main class to check is FilterInvocationDefinitionSourceEditor.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
