### ISSUE TITLE
SEC-248: HttpSessionContextIntegrationFilter doesn't work with HttpInvokerServiceExporter

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#510]
["Danielius Jurna":https://jira.spring.io/secure/ViewProfile.jspa?name=jurna](Migrated from ["SEC-248":https://jira.spring.io/browse/SEC-248?redirect=false]) said:

HttpSessionContextIntegrationFilter doesn't work if HttpInvokerServiceExporter is used.
HttpInvokerServiceExporter calls HttpResponse.getOutputStream().close(). After that you cannot set headers in response, that meanss you cannot set cookies in the response, that meanss, that your HttpSession is lost and http client must authenticate on every request.
Workaround: create filter before HttpSessionContextIntegrationFilter and create session before invoking other filters.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
