### ISSUE TITLE
@since on repackaged GlobalAuthenticationConfigurerAdapter is incorrect

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-security#5106]
### Summary

GlobalAuthenticationConfigurerAdapter was repackaged in [this commit](https://github.com/spring-projects/spring-security/commit/579282437b02b939b143dec52fd6b6059e9f51cf) but the `@since` javadoc tag was not updated to reflect that it is, effectively, a new class. 

### Actual Behavior

Javadoc suggests a class that is new in 5.0 has existed since 3.2.1. 

### Expected Behavior

Javadoc accurately describes when a class was introduced. 

### Configuration

N/A

### Version

5.0.x

### Sample

N/A

**Comment by rwinch** [comment]
Thanks for the report. This is now fixed in master and 5.0.x
