### ISSUE TITLE
Add documentation for GlobalAuthenticationConfigurerAdapter

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-security#5108]
### Summary

In the current `Spring Security Reference Documentation` about `5.0.x` there is no covering about `GlobalAuthenticationConfigurerAdapter`.  Because it works about many _schemas_ would be nice add a section and some samples about this.

### Actual Behavior

No documentation and `javadoc` is not enough.

### Expected Behavior

Find a section to learn more about this, configuration through sample codes.

### Version

`5.0.x`

**Comment by rwinch** [comment]
Thanks for the report. However, we are probably going to deprecated `AuthenticationManagerBuilder` in favor of exposing a bean of one of the following types `AuthenticationManger`, `AuthenticationProvider`, or `UserDetailsService`. This would mean that `GlobalAuthenticationConfigurerAdapter` will also be deprecated.

**Comment by manueljordan** [comment]
Oh I see, thanks for the feedback.
