### ISSUE TITLE
HttpSecurity.addFilterAt leads to duplicated BasicAuthenticationFilter

### ISSUE THREAD

**Issue by lanoxx** [spring-projects/spring-security#5113]
### Summary

When registering a Filter using the `HttpSecurity.addFilterAt()` method, the added filter gets registered with the same priority as the provided Filter class. However, that does not replace an existing Filter at this position but adds the added Filter with the same priority. I like to clarify the expected behavior of this method.

### Actual Behavior

When I create a `CustomAuthenticationFilter` that derives from `BasicAuthenticationFilter` and I register it with `http.addFilterAt(customAuthenticationFilter, BasicAuthenticationFilter.class)`, and I also use `http....and().httpBasic()`, then the resulting Filter chain has both my `CustomAuthenticationFilter` (earlier in the chain) and the `BasicAuthenticationFilter` (later in the chain).

### Expected Behavior

My initial intuition was that the `BasicAuthenticationFilter` would be replaced by my `CustomAuthenticationFilter`. I am looking for confirmation that having both Filters on the FilterChain is the expected behavior. If it is not the expected behavior, then I ask if it is the wrong aproach to use both 

    http.addFilterAt (..., BasicAuthenticationFilter.class)
        .httpBasic();

Since my `CustomAuthenticationFilter` extends the `BasicAuthenticationFilter` having the `BasicAuthenticationFilter` on the filter chain is redundant and unnecessary. I am wondering if it would make sense to check in the `HttpBasicConfigurer.configure()` method if a (possibly subclassed) instance of BasicAuthenticationFilter is already on the filter chain and skip adding another BasicAuthenticationFilter.

### Configuration

    http.addFilterAt (customAuthenticationFilter, BasicAuthenticationFilter.class);
    http.httpBasic();

### Version

    Spring Boot 1.5.9

**Comment by rwinch** [comment]
Thanks for the report. This is expected behavior. When you invoke this method for multiple Filters in the same location it just means that you do not care the specific order of the Filters. I have [updated the Javadoc](https://github.com/spring-projects/spring-security/commit/01152ede4184afadced77ebb0919e6b23d171f5b) to clarify the expected behavior. Instead, you should invoke `http.httpBasic().disable()` to disable the original filter.

**Comment by lanoxx** [comment]
Thank you for clarifying this behaviour in the documentation. 

One more question. I considered to use `httpBasic().disable()` but I was hesitant, because I was uncertain what side effects that might imply. I am worried that if i just disable it and add a subclass of BasicAuthenticationFilter to the filter chain I might miss some important setting and I end up with an incomplete configuration of basic authentication.

Based on my current understanding I think that as a minimum I would need to add my subclassed `BasicAuthenticationFilter` and an `AuthenticationEntryPoint` to get a configuration that is equivalent of what `httpBasic()` does, is there anything else I missed?

**Comment by rwinch** [comment]
@lanoxx That is all you should need to do.

**Comment by lanoxx** [comment]
I was in wrong with my above statement, despite the fact that I thought I had carefully tested it. With

    .httpBasic().authenticationEntryPoint (restAuthenticationEntryPoint).disable ()

the `ExceptionTranslationFilter` is still configured with a `Http403ForbiddenEntryPoint`. I we want to configure a custom entry point, then the following is needed instead:

    http
    //...
    .httpBasic().disable()
    .exceptionHandling ().authenticationEntryPoint (restAuthenticationEntryPoint).and ()
    //...

Replace `restAuthenticationEntryPoint` with your custom `AuthenticationEntryPoint` instance.
