### ISSUE TITLE
OAuth 2.0 section of docs should mention Spring Security OAuth

### ISSUE THREAD

**Issue by denisw** [spring-projects/spring-security#5114]
### Summary

As Spring Security 5 does not support all OAuth 2.0 functionality of Spring Security OAuth yet (most notably, support for implementing an Authorization and Resource Server), it would be great if the OAuth project (and ideally the `spring-security-oauth2-boot` legacy module, which is really hard to find) would be mentioned.

### Actual "Behavior"

When I looked into the Spring Security 5 Reference Guide, not knowing the backstory of OAuth 2.0 support, I've come to assume that the Spring ecosystem only had support for third-party OAuth 2.0 logins (Google etc.), as this is the only use case documented in the "OAuth 2.0 Login" section. 

It took me a lot of searching to find a [tutorial](https://spring.io/guides/tutorials/bookmarks/) on the Spring website that showed an implementation of an OAuth 2.0 Authorization / Resource Server, showing that it is possible after all, and even longer to find out that this tutorial as-is doesn't work with Spring Boot 2.0 and and I need to use [spring-security-oauth2-boot](https://docs.spring.io/spring-security-oauth2-boot/docs/current-SNAPSHOT/reference/htmlsingle/) for the time being. It was just then when I figured out why there is currently partial OAuth 2.0 support in Spring Security _and_ the Spring Security OAuth project. 

### Expected "Behavior"

A simple docs subsection in "OAuth 2.0 Login" saying something to the effect of "Support for implementing OAuth 2.0 Authorization Servers and Resource Servers is currently not implemented in Spring Security. Use the legacy Spring Security OAuth module for the time being, or spring-security oauth2-boot module if you are using Spring Boot 2.0" would have saved me lots of time and nerves.

**Comment by jgrandja** [comment]
@denisw On the Spring Security [project page](https://projects.spring.io/spring-security/) there is a "Related Projects" section with a link to [Spring Security OAuth](https://projects.spring.io/spring-security-oauth/).

As well, another great resource to find announcements and tutorial links is in our [blog](https://spring.io/blog).

Here is a link to a recent announcement on the [current state](https://spring.io/blog/2018/01/30/next-generation-oauth-2-0-support-with-spring-security) of OAuth 2.0 Support in Spring Security.

I'm going to close this issue as I feel I've answered your question.
