### ISSUE TITLE
oauth 2.0 "authorization_code" flow w/out mandatory `token_type` field in spring-security-oauth2-client 5.x

### ISSUE THREAD

**Issue by n0mer** [spring-projects/spring-security#5118]
### Summary

nimbus oauth 2.0 sdk requires `token_type` to be available.

### Actual Behavior

nimbus oauth 2.0 sdk throws exception when only `access_token` is present, w/out `token_type`

![2018-03-15_14h07_18](https://user-images.githubusercontent.com/1862997/37468072-4238822a-2862-11e8-8b44-3e1f58dd1f09.png)

Exception text:

> Your login attempt was not successful, try again.
> 
> Reason: [invalid_token_response] An error occurred parsing the Access Token response: Missing JSON object member with key "token_type"
> 

### Expected Behavior

Work-around to work with `access_token` only, even when `token_type` is not present.

For example, https://developer.foursquare.com/docs/api/configuration/authentication returns only `access_token`.

### Configuration

`spring.security.oauth2.client.provider.provider_id.*`, `spring.security.oauth2.client.registration.provider_id.*` in application.yaml

### Version

`spring-boot` 2.0.0.RELEASE, `spring-security` 5.0.2.RELEASE, `spring-security-oauth2-client`

```
\--- org.springframework.security:spring-security-oauth2-client: -> 5.0.2.RELEASE
     +--- com.nimbusds:oauth2-oidc-sdk:5.45 -> 5.54
     |    +--- javax.mail:mail:1.4.7
     |    |    \--- javax.activation:activation:1.1 -> 1.1.1
     |    +--- com.github.stephenc.jcip:jcip-annotations:1.0-1
     |    +--- org.apache.commons:commons-lang3:3.7
     |    +--- org.apache.commons:commons-collections4:4.1
     |    +--- net.minidev:json-smart:[1.3.1,2.3] -> 2.3 (*)
     |    +--- com.nimbusds:lang-tag:[1.4.3,) -> 1.4.3
     |    |    \--- net.minidev:json-smart:1.3.1 -> 2.3 (*)
     |    \--- com.nimbusds:nimbus-jose-jwt:[5.0,) -> 5.1
     |         +--- com.github.stephenc.jcip:jcip-annotations:1.0-1
     |         \--- net.minidev:json-smart:[1.3.1,2.3] -> 2.3 (*)
     +--- org.springframework.security:spring-security-core:5.0.2.RELEASE (*)
     +--- org.springframework.security:spring-security-oauth2-core:5.0.2.RELEASE
     |    +--- org.springframework.security:spring-security-core:5.0.2.RELEASE (*)
     |    \--- org.springframework:spring-core:5.0.4.RELEASE (*)
     +--- org.springframework.security:spring-security-web:5.0.2.RELEASE (*)
     \--- org.springframework:spring-core:5.0.4.RELEASE (*)
```

**Comment by n0mer** [comment]
https://www.oauth.com/oauth2-servers/access-tokens/access-token-response/

`token_type` is required; but still, `refresh_token` is optional

**Comment by vdzhuvinov** [comment]
The token_type parameter is required by the OAuth 2.0 standard, otherwise the response is invalid:

https://tools.ietf.org/html/rfc6749#section-5.1

**Comment by n0mer** [comment]
@vdzhuvinov totally agree. But complaint that real-world API is providing non-compliant API is not the best resolution for task assigned :)

So, again: is there any workaround - either in connect2d or in `spring-security-oauth2-client` - to enrich response with token_type (which is, anyway, always "bearer") ?

**Comment by vpavic** [comment]
@n0mer I believe you should report this with Foursquare, as their API does not implement the required aspects of spec as indicated by @vdzhuvinov.

Working around this either in Nimbus SDK or Spring Security is not a way to go since introducing such workaround brings complexity that becomes maintenance burden and raises a question where to draw a line (and the line should be as the spec indicates with `required` notation), since I'm sure many OAuth2 Servers/OpenID Providers stray away from the spec in their own unique way.

Alternatively you could provide you own `OAuth2AccessTokenResponseClient` implementation that internally knows how to deal with this non-standard API.

**Comment by jgrandja** [comment]
@n0mer Spring Security will implement to spec and will also provide hooks for you if you need to workaround things. 

As per spec, in [Section 5.1. Successful Response](https://tools.ietf.org/html/rfc6749#section-5.1):

> token_type
>          REQUIRED.  The type of the token issued as described in
>          Section 7.1.  Value is case insensitive.
> 

If you require a workaround for Foursquare, than you can provide your own implementation of `OAuth2AccessTokenResponseClient` and configure it via:

```
http
    .oauth2Login()
        .tokenEndpoint()
            .accessTokenResponseClient()
```

I'm going to close this issue as I feel I have provided you the workaround you are looking for.

**Comment by n0mer** [comment]
![image](https://user-images.githubusercontent.com/1862997/39458480-3819dda4-4cf5-11e8-947d-b46e05ad4b17.png)

so lame :)
