### ISSUE TITLE
SEC-249: Add simple logout support by supplying a LogoutFilter

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#512]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-249":https://jira.spring.io/browse/SEC-249?redirect=false]) said:

In many cases, logout is a simple matter of invalidating the session, and possibly removing remember-me cookies. This functionality could easily be supplied by the framework rather than requiring the application to supply it. A LogoutFilter with a configurable logout URL would do the business.  A specialised version which also knew how to logout of CAS could also be provided.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
