### ISSUE TITLE
Resource Server verifies JWT using JWK

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#5130]
Resource Server will initially provide support for verifying the signature ([JWS](https://tools.ietf.org/html/rfc7515)) of a JWT using a [JWK](https://tools.ietf.org/html/rfc7517) obtained from the JWK Set URI.

**Comment by dfcoffin** [comment]
When will Resource Server support for simple Bearer tokens be available?

**Comment by jgrandja** [comment]
Opaque token support will likely come after 5.1 is released.
