### ISSUE TITLE
Improvement: WebSecurityConfigurerAdapter logger instance should be protected and use the current class

### ISSUE THREAD

**Issue by lgoldstein** [spring-projects/spring-security#5136]
### Summary

Since `WebSecurityConfigurerAdapter` is an _abstract_ class that already initializes a logger instance, I think it is only natural to make it _protected_ + use the actual concrete class as its name. This way, whoever is extending the class can re-use the existing logger instead of having to create a new one.

### Version

5.0.3

### Sample

```java
public abstract class WebSecurityConfigurerAdapter implements WebSecurityConfigurer<WebSecurity {
    protected final Log logger;

    protected WebSecurityConfigurerAdapter() {
	this(false);
    }

    protected WebSecurityConfigurerAdapter(boolean disableDefaults) {
        this.disableDefaults = disableDefaults;
        this.logger = LogFactory.getLog(getClass());
    }
```

P.S. I believe this should be the general rule in **all** classes the use a logger - abstract or otherwise - thus allowing whoever extends them to re-use the existing logger instead of creating an (un-necessary) new instance.

**Comment by rwinch** [comment]
Thanks for the report. Spring has historically done this, but it has been a mistake. Exposing our loggers to subclasses was one of the main reasons we now have spring-jcl which is it's own logging abstraction that mimics the JCL APIs.
