### ISSUE TITLE
SEC-251: DefaultLdapAuthoritiesPopulator: Add filter argument {1} for username as in Tomcat JNDIRealm

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#514]
["Steve Davidson":https://jira.spring.io/secure/ViewProfile.jspa?name=smdavidson](Migrated from ["SEC-251":https://jira.spring.io/browse/SEC-251?redirect=false]) said:

Several of my customers require username rather than user DN to query for user roles.  Add filter argument {1} to DefaultLdapAuthoritiesPopulator groupSearchFilter property to allow user name substitution.  This matches Tomcat JNDIRealm configuration userPattern usage.

I would be happy to supply a patch if desired.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
