### ISSUE TITLE
Provide a way to swallow RequestRejectedException stacktrace

### ISSUE THREAD

**Issue by Glamdring** [spring-projects/spring-security#5149]
### Summary

If the HttpFirewall rejects a request, it does that by throwing an exception (as all other outcomes would not stop the execution of the filter chain). However, this exception bubbles up and eventually gets printed in the logs/console, and that's not desirable, as it's not an actual exception.

### Expected Behavior
Instead of propagating the exception, the FilterChainProxy should catch it, log a one-line warning, and respond with BAD_REQUEST.

### Version

5.0.3.RELEASE

**Comment by rwinch** [comment]
Thanks for the report! This is a duplicate of #5007

**Comment by rwinch** [comment]
PS: See the mentioned issue for ways to handle it until support is added
