### ISSUE TITLE
SEC-252: AbstractAuthenticationToken NullPointerException

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#515]
["Joe Scalise":https://jira.spring.io/secure/ViewProfile.jspa?name=joes.checkernet.com](Migrated from ["SEC-252":https://jira.spring.io/browse/SEC-252?redirect=false]) said:

On line 144 in method getName() the return statement produces a NullPointerException when trying to use X509 Authenticaito.  Whenever doFilter in X509ProcessingFilter is called and I do not have a certificate in the request (i.e. I am not on SSL) this code throws a NullPointerException which then causes a site error.

public String getName() {
        if (this.getPrincipal() instanceof UserDetails) {
            return ((UserDetails) this.getPrincipal()).getUsername();
        }

```
    return this.getPrincipal().toString(); 
}
```

If the return statement is changed to check if the principal is null first we no longer have this issue. Example: return this.getPrincipal() == null ? "" : this.getPrincipal().toString();

Also, I have security degrade to LDAP with a form entry point for users that do not have a certificate set up.  As you can imagine this also produces a NullPointerException because there is no certificate.

**Comment by linuxjackto1** [comment]
thanks www.movied.org
