### ISSUE TITLE
Support for implicit Authentication method parameter in SpEL expressions

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#5158]
### Summary

SpEL expressions in Spring Security, for example those found in `@PreAuthorize` annotations, may today refer to the current `authentication` object:

```java
@PreAuthorize("@oauth2.attribute(authentication, 'issuer') == 'carol'")
```

It would, however, be a nice convenience to be able to leave it out, and allow Spring Security to provide it:

```java
@PreAuthorize("@oauth2.attribute('issuer') == 'carol'")
```

### Proposals

Some proposals have already been made to support this feature:

#### A Wrapper Bean

Perhaps the simplest is really something that can already be done today, which is to wire in a wrapper bean that mimics the underlying bean, just with the `Authentication` parameter removed.

For example, in the case of a class called `DefaultOAuth2Expressions`, we might have:

```java
public String attribute(Authentication authentication, String issuer)
```

We, today, can simply create a wrapper bean:

```java
public class OAuth2ExpressionsBean {
    private final DefaultOAuth2Expressions expressions;

    public String attribute(String issuer) {
        return attribute(SecurityContextHolder.getContext().getAuthentication(), issuer);
    }
}
```
This has some notable downsides, including the duplicity in introduces into the code. Also, this is just a pattern. It doesn't really offer any cross-cutting support for this concern.

#### A Custom `MethodResolver`

SpEL supports plugging in one's own `MethodResolver` and `MethodExecutor`. Conceptually, an implementation of `MethodResolver` would be able to take the method signature indicated by the SpEL expression and identify methods that matched it *plus* an Authentication argument.

Then, the `MethodExecutor` implementation would provide the `Authentication` object from the appropriate context, whether it be in a reactive or imperative setting.

Some research has already been done along this line, including looking into `ReflectiveMethodResolver` to see if it can be extended or configured to suit the use case. This, however, does not initially look promising in chatting with Andy Clement. Really, we are either faced with the option of copying the code in `ReflectiveMethodResolver` (and any other internal classes it relies on), or coming up a pared-down version and risking breaking folks who are relying on the advanced method matching that is already available to them by default.

**Comment by jgrandja** [comment]
Related #5132

**Comment by jgrandja** [comment]
Invalidated - see [comment](https://github.com/spring-projects/spring-security/issues/5132#issuecomment-394504541)
