### ISSUE TITLE
Provide XML namespace support for OAuth 2.0 Client

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#5184]
We should consider providing XML namespace support that is equivalent to `HttpSecurity.oauth2Client()`.

**NOTE:** Spring Security OAuth 2.x implements this via [ResourceBeanDefinitionParser](https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/config/xml/ResourceBeanDefinitionParser.java). See the [sample xml](https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/test/resources/org/springframework/security/oauth2/config/xml/ResourceBeanDefinitionParserTests-context.xml) config.

Related #4557 #5185

**Comment by rh-id** [comment]
@jgrandja  I think i might as well take this. if i may ask currently, still no due date for this?

**Comment by jgrandja** [comment]
@rh-id Ideally, I'd like to get this into 5.3 which is due March 4. However, I'm off for a few days from Feb 26 which means I need to get this merged no later than Feb 24-25. The timeline is very tight so I would completely understand if you do not have the time to complete it this week or by Mon Feb 24. I do have time this week myself to complete it so there is no pressure. Either way, let me know so there is no duplication of effort. Thank you.

**Comment by rh-id** [comment]
@jgrandja sorry, i'll have to pass then.

**Comment by jgrandja** [comment]
No worries @rh-id. Feel free to browse the open issues at anytime you are free and interested in picking up another issue and let me know. Talk soon.
