### ISSUE TITLE
Provide Token Relay capability

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#5201]
[Spring Cloud Security](https://cloud.spring.io/spring-cloud-security/) provides the capability to relay OAuth 2.0 access tokens from the Edge Service (Zuul proxy) to downstream Resource Server(s).

We should implement the same feature as Token Relay is a common pattern required by an Edge (Proxy) Service.

**Comment by jgrandja** [comment]
Related #4920 #4921

**Comment by alwaysastudent** [comment]
Is this coming ?

**Comment by jgrandja** [comment]
@alwaysastudent This won't make it into the 5.2 release. Also, we don't have plans on directly supporting `RestTemplate` and we haven't had discussions on providing support for FeignClient either. The current support is with `WebClient`.

You can easily implement Token Relay using any HTTP client of your choosing. All you need is the `Jwt`, which you can easily resolve `JwtAuthenticationToken` in a `@Controller` handler method and than obtain the `Jwt` using `jwtAuthentication. getToken()`. At this point you have the `Jwt` and can relay `jwt.getTokenValue()` to a downstream call.

**Comment by jgrandja** [comment]
This is resolved via #7284 with the new `ServerBearerExchangeFilterFunction` in 5.2.0.
