### ISSUE TITLE
spring-security-5.0.3.RELEASE

### ISSUE THREAD

**Issue by bcartee** [spring-projects/spring-security#5212]
### Summary

Cannot follow the demo here:
https://docs.spring.io/spring-security/site/docs/current/guides/html5//helloworld-javaconfig.html
No Maven projects appear using spring-security-5.0.3.RELEASE

### Actual Behavior

No Maven projects appear

### Expected Behavior

Cannot complete the demo per the instructions.

### Configuration

Please provide any configuration you have.

### Version

Issue is with spring-security-5.0.3.RELEASE
If I try with earlier release it shows Maven projects

### Sample

NA

**Comment by eleftherias** [comment]
Confirmed that the IDE can find the helloworld-javaconfig project with the latest patch release, 5.0.19.RELEASE.
