### ISSUE TITLE
Absent sample chat application that referenced in the documentation.

### ISSUE THREAD

**Issue by findli** [spring-projects/spring-security#5233]
### Summary
This page: https://docs.spring.io/spring-security/site/docs/5.0.4.RELEASE/reference/html/websocket.html
has text: "You can find a complete working sample of WebSocket security in samples/javaconfig/chat."
So there is no sample chat application in the source code.

see: https://github.com/spring-projects/spring-security/tree/master/samples/javaconfig

**Comment by eleftherias** [comment]
Duplicate of #8593
