### ISSUE TITLE
When ProviderManager.authenticate () is used to verify, result is empty, and the authenticate method of parent is invoked to verify it, and an error is generated, calling back and forth, causing a dead cycle.

### ISSUE THREAD

**Issue by Maijh97** [spring-projects/spring-security#5235]
Hello,
When ProviderManager.authenticate () is validated, if result is empty, the call parent is tried, if the instance WebSecurityConfigurerAdapter.authenticationManagerBean situation is the result of the validation into the dead cycle and the abnormal java.lang.StackOverflowError:null.
So I suggest that we delete the call parent to verify again, and go back to verify the exception directly.

**Comment by jzheaux** [comment]
@Maijh97, would you mind sharing an example application so that I can better understand the issue you are having?
