### ISSUE TITLE
oauth:web-expression-handler is identified as an unsupported tag

### ISSUE THREAD

**Issue by KOGI** [spring-projects/spring-security#5236]
### Summary
![image](https://user-images.githubusercontent.com/1231996/38752546-6f96e58a-3f10-11e8-9598-8fd15c699d28.png)

### Expected Behavior
Should not report an error

### Version
3.1

**Comment by jgrandja** [comment]
@KOGI Can you please log this issue in the Spring Security OAuth [Issues](https://github.com/spring-projects/spring-security-oauth/issues).
Thank you.
