### ISSUE TITLE
OAuth2LoginAuthenticationFilter should handle null ClientRegistration

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#5251]
### Summary

`OAuth2LoginAuthenticationFilter` [should handle](https://github.com/spring-projects/spring-security/blob/7daa27874e99c57aa21a7a4bfaa7624853442b5d/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/OAuth2LoginAuthenticationFilter.java#L148) potential `null` `ClientRegistration`

**Comment by jgrandja** [comment]
A `null` `ClientRegistration` should never happen if the `OAuth2AuthorizationRequest` is found.

Given the current logic: 

```
OAuth2AuthorizationRequest authorizationRequest = this.authorizationRequestRepository.removeAuthorizationRequest(request);
if (authorizationRequest == null) {
	OAuth2Error oauth2Error = new OAuth2Error(AUTHORIZATION_REQUEST_NOT_FOUND_ERROR_CODE);
	throw new OAuth2AuthenticationException(oauth2Error, oauth2Error.toString());
}

String registrationId = (String) authorizationRequest.getAdditionalParameters().get(OAuth2ParameterNames.REGISTRATION_ID);
```

If there was such a case where the returned `ClientRegistration` is `null`, than the bug would be in `OAuth2AuthorizationRequestRedirectFilter` which is responsible for saving the `OAuth2AuthorizationRequest` in `AuthorizationRequestRepository`.

**Comment by rwinch** [comment]
I think there are scenarios where it could happen. For example, it could can happen if the registration was modified in the meantime. This obviously doesn't happen with our read only implementation, but other implementations may allow for editing.

**Comment by jgrandja** [comment]
The `clientRegistrationId` serves as a unique identifier so modifying it during an application runtime can result in unexpected behaviour if not all references are updated at the same time. I think this is a reasonable expectation. Even if an admin were to change a `clientRegistrationId` during a running application, there are other areas in the code where things would break, for example, `@OAuth2Client("orphaned-clientRegistrationId")`.

If the user/admin decides to change a `clientRegistrationId` during a running application, than they are responsible for changing all existing references to the `clientRegistrationId` which would include in-flight `OAuth2AuthorizationRequest`'s. However, changing `@OAuth2Client("orphaned-clientRegistrationId")` would require a code change and re-compile unless we support dynamic `registrationId` for `@OAuth2Client`.

**Comment by rwinch** [comment]
I think you code should be defensive. It is a simple check to make for a scenario that can happen.

**Comment by jgrandja** [comment]
I agree that it's a simple check but allowing a `RuntimeException` to occur is sometimes a more effective alert to the user compared to displaying an error message.

What do we do in this case `@OAuth2Client("orphaned-clientRegistrationId")`? The user will have no choice but to make the code change and recompile/redeploy.

**Comment by rwinch** [comment]
I think the discussion is what do we mean by handle exception...At this point I think throwing an `IllegalStateException` is fine. We just don't want to throw a `NullPointerException` which should not happen in Spring Security.

**Comment by jgrandja** [comment]
That makes sense. I will apply the change to throw `IllegalStateException` is such scenarios.
