### ISSUE TITLE
Typo in Spring Security 5.0.x docs

### ISSUE THREAD

**Issue by pashazadeh** [spring-projects/spring-security#5254]
In  [1. Getting Started](https://docs.spring.io/spring-security/site/docs/5.0.4.RELEASE/reference/htmlsingle/#getting-started) section, the documentation mentions it as Spring Security 4.0, which shall be 5.0.

**Comment by spring-issuemaster** [comment]
Fixed via a9ddd363aaf330f0d0f1fc9baf3716e58720be28
