### ISSUE TITLE
All links in Spring Security 5.0.4 to JavaDocs are borken

### ISSUE THREAD

**Issue by pashazadeh** [spring-projects/spring-security#5255]
There is a `/apidocs/` in all JavaDoc urls which must be changed to `/api/`.

For example [Invalid Url](https://docs.spring.io/spring-security/site/docs/current/apidocs/org/springframework/security/web/authentication/logout/LogoutHandler.html) must be changed to [valid Url](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/web/authentication/logout/LogoutHandler.html).

**Comment by jzheaux** [comment]
Thanks @pashazadeh!

This will be addressed in https://github.com/spring-projects/spring-security/issues/4330
