### ISSUE TITLE
Feature Request for Implicit Grant/Flow in OAuth2/Open ID Connect on authorization server

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [spring-projects/spring-security#5264]
The different flow types in OAuth2 / Open ID Connect may be defined in the specifications but there is no "must support" for any of the different flows. So I would like to request that it should be possible to disable certain flows by disabling the specific "response_type" values.

In our case we only want to support the authorization code flow in our application. Currently we are using the spring-security-oauth2 library and to disable the implicit grant I had to use the most ugliest hack ever made to maintain also the oauth2 exception workflow if the implicit grant gets rejected.

**Comment by jgrandja** [comment]
@Captain-P-Goldfish We haven't started work on the Authorization Server module as of yet. It's looking like we'll start that work later this year. Our efforts are focused on Client and new Resource Server support.

As far as enabling/disabling certain grants/flows in the Authorization Server, we will provide the capability to **easily** enable/disable. The likely default configuration will be disabled for all and it's up to the user's Authorization Server `@Configuration` to explicitly enable the required grant(s).

I'm going to close this issue as I feel I have answered your question.
If not please let me know.

**Comment by Captain-P-Goldfish** [comment]
thx for the fast response.
maybe it would be a good idea if there were a ticket-board or something similiar where users could post some feature requests in advance. Could help in some ways.

And I thought the goal is to provide the authorization server also until early 2019, isn't that correct?

**Comment by jgrandja** [comment]
@Captain-P-Goldfish New feature requests can be posted here. However, it might be a bit early to post feature requests for Authorization Server as we won't be starting that work until 5.1 is released which at this point is looking like July or Aug.

Also, the initial priority features that will be implemented for Authorization Server are listed [here](https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Features-Matrix#authorization-server-support).
