### ISSUE TITLE
URL Link is broken

### ISSUE THREAD

**Issue by blusky10** [spring-projects/spring-security#5265]
https://docs.spring.io/spring-security/site/docs/5.0.4.RELEASE/reference/htmlsingle/#jc-logout

The JavaDoc links in section **5.5 Handling Logouts** all return **404 Not Found** errors.

**Comment by dfcoffin** [comment]
The correct URL is:

https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/annotation/web/configurers/LogoutConfigurer.html

**Comment by eleftherias** [comment]
Closing since this is fixed in 5.1 and 5.2 versions.
