### ISSUE TITLE
WebSecurityConfiguration should autowire PermissionEvaluator

### ISSUE THREAD

**Issue by candrews** [spring-projects/spring-security#5272]
This issue effectively reopens #4077.

`GlobalMethodSecurityConfiguration` autowires `PermissionEvaluator` from the context:
https://github.com/spring-projects/spring-security/blob/4.1.3.RELEASE/config/src/main/java/org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.java#L154

`WebSecurityConfiguration` should do the same thing.

Currently, it's surprising that when a `PermissionEvaluator` is set up, it just works (with no configuration other than declaring the `PermissionEvaluator` bean) when used from Java annotations but the same expression always returns denied (as that's what the default configuration does) when used from in a web context (such as in a JSP sec: expression).

Using thymeleaf spring security extras, you can conditionally show elements like this:
`<div sec:authorize="hasPermission(#vars.study,'DELETE')">`

The DefaultWebSecurityExpressionHandler that ends up being used has a type of `org.springframework.security.access.expression.DenyAllPermissionEvaluator` instead of the permission evaluator.

This behavior worked as expected with the commit accepted from my pull request, 3bf6bf10de959810c33ecbeaf68ded4f1dde53d0, but some polish was done that made it no longer work, 8a66d0c78d9f51e2294229ff3c4038dfe5008c73.

Thanks again in advance for looking into this issue.

**Comment by rwinch** [comment]
Thanks for the report. A fix is now pushed to master and 5.0.x

**Comment by candrews** [comment]
Thank you for addressing the issue so quickly!

**Comment by rwinch** [comment]
No problem. Thanks for the report! If you get a chance it would be nice to hear if the changes work for you. The SNAPSHOTs should be published within 30 minutes if you want to give it a try.

**Comment by candrews** [comment]
I tested just now with spring security 5.0.5.BUILD-SNAPSHOT by means of adding
```
<dependency>
 <groupId>org.springframework.security</groupId>
 <artifactId>spring-security-bom</artifactId>
 <version>5.0.5.BUILD-SNAPSHOT</version>
 <scope>import</scope>
</dependency>
```
to my pom.xml. The version I got was: using https://repo.spring.io/snapshot/org/springframework/security/spring-security-bom/5.0.5.BUILD-SNAPSHOT/spring-security-bom-5.0.5.BUILD-20180430.173119-29.pom

Unfortunately, the bug was still reproducible - I'm getting a DenyAllPermissionEvaluator instead of the expected one.

I believe the reason why this is happening is because your code isn't in there... I checked the source jar and `org.springframework.security.config.annotation.web.builders.WebSecurity` doesn't have the changes from your commit. It also looks like the build failed (the commit has a red x on it).

**Comment by rwinch** [comment]
Thanks for the fast follow up. You are right that the build was failing. It should have published recently. Can you try again and force updates?

**Comment by candrews** [comment]
I tested again just now, updating snapshots and the problem isn't resolved. It would appear that a new snapshot has yet to be published.

**Comment by rwinch** [comment]
I'm closing this due to no more feedback. In the tests and the external sample project I provided it works.

**Comment by candrews** [comment]
I confirm - it works fine.

My apologies for my delayed reply.

**Comment by rwinch** [comment]
@candrews Thanks for the follow up and thanks again for raising this issue!
