### ISSUE TITLE
security-api-url in index.adoc is not correct.

### ISSUE THREAD

**Issue by blusky10** [spring-projects/spring-security#5274]
https://github.com/spring-projects/spring-security/blob/master/docs/manual/src/docs/asciidoc/index.adoc

security-api-url is defined as below.
:security-api-url: http://docs.spring.io/spring-security/site/docs/current/apidocs/

but it is correct. (apidocs -> api)
:security-api-url: http://docs.spring.io/spring-security/site/docs/current/api/

Because of this, all URLs are broken.

**Comment by jzheaux** [comment]
Thanks, @blusky10! 

This will be addressed with https://github.com/spring-projects/spring-security/issues/4330
