### ISSUE TITLE
The oauth2 API does not offer a way to set the accept header for the userInfo endpoint

### ISSUE THREAD

**Issue by paulspeijers** [spring-projects/spring-security#5285]
### Summary
I'm implementing a scenario in which I use Open ID connect to authenticate with ORCID (https://members.orcid.org/api/tutorial/read-orcid-records). The workflow is as follows:

1. Get authorization code
2. Get access token (using openid scope)
3. Get user details from ORCID person: https://api.sandbox.orcid.org/v2.1/[ORCID iD]/person, like email address, firstname, surname and publication name
4. Create a  DefaultOidcUser object that is used as a security principle within the Authentication.
5. Get user details from our own data store (iRODS).
6. Use user details to set the Authentication.details.

I have a number of issues with this setup. In this issue I will focus on the following:

Spring security does not offer a way to set an "accept" header for the userInfo endpoint, within the request sent within the org.springframework.security.oauth2.client.oidc.userinfo.OidcUserService

Currently within OidcUserService the user attributes are obtained at line 61 using: this.userInfoResponseClient.getUserInfoResponse(userRequest, typeReference);
However, within the userRequest provided here there is no way to set an accept header. By default the following orcid endpoint returns XML:
https://api.sandbox.orcid.org/v2.1/[ORCID iD]/person

However, I need to set the accept header in order to the endpoint to return JSON

### Workaround
I currently use the following workaround, which makes it hard for me to migrate to new spring security versions:
Fork OidcUserService and NimbusUserInfoResponseClient. Within the latter set httpRequest.setAccept("application/json") within getUserInfoResponse

### Actual Behavior

The API does not offer a possibility to set the "accept" header to application/json

### Expected Behavior

The API offers a possibility to set the "accept" header to application/json

### Configuration
We are running our frontend and backend within Tomcat 8 servers
In front of that environment we have an NGINX 1.13 webserver
We are authenticating with orcid API 2.1 using open id connect: https://members.orcid.org/api/tutorial/read-orcid-records

The configuration of oauth is:
spring.security.oauth2.client.registration.orcid.redirect-uri-template={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.orcid.scope=/read-limited openid
spring.security.oauth2.client.registration.orcid.client-name=ORCID
spring.security.oauth2.client.registration.orcid.authorization-uri=https://sandbox.orcid.org/oauth/authorize
spring.security.oauth2.client.registration.orcid.token-uri=https://sandbox.orcid.org/oauth/token
spring.security.oauth2.client.registration.orcid.jwk-set-uri=https://sandbox.orcid.org/oauth/jwks
spring.security.oauth2.client.registration.orcid.user-info-uri=https://api.sandbox.orcid.org/v2.0/{sub}/person

### Version
We are using the 5.0.3.RELEASE of the following dependencies:
spring-security-web
spring-security-config
spring-security-oauth2-core
spring-security-oauth2-client
spring-security-oauth2-jose
spring-security-saml2-core

**Comment by jgrandja** [comment]
@paulspeijers The current implementation of `OidcUserService` only supports JSON responses. Even if we allowed the `Accept` header to be set with `application/xml` it still would not work since `NimbusUserInfoResponseClient` relies on JSON content type.

To meet your requirements, you can define your own custom implementation of `OidcUserService` that handles processing of XML response data and configure it using:

```
@Override
protected void configure(HttpSecurity http) throws Exception {
	http
		.oauth2Login()
			.userInfoEndpoint()
				.oidcUserService(this.customOidcUserService())
				...
}
```

See the [reference](https://docs.spring.io/spring-security/site/docs/5.0.4.RELEASE/reference/htmlsingle/#oauth2login-advanced-oidc-user-service) for more details.


This will require your implementation to integrate an XML processor for un-marshalling the response.

I would also double check to see if you can configure the responses to come back in JSON format. Reading the [ORCID docs](https://members.orcid.org/api/tutorial/read-orcid-records), it states:

> You can help make life easier for your users by retrieving data from their ORCID records to populate your forms, systems, and more. Using the ORCID API, you can read biographical and research activities information on ORCID records. **Responses can be returned in XML or JSON format**.

I'm going to close this issue as I feel I have provided you a solution on how you can integrate your custom XML-based `OidcUserService`.

**Comment by paulspeijers** [comment]
@jgrandja I don't want to set the header to application/xml, but the problem is that ORCID by default returns XML. With ORCID you can configure the responses to come back in JSON format but in order to do so you need to override that behavior by setting the accept header. I am using JSON everywhere within my application so I really don't like to be parsing XML for this very specific scenario.

**Comment by jgrandja** [comment]
@paulspeijers Sorry for the confusion on my part. I'll have a fix in place for you shortly that sets the Accept header to application/json. You can track issue #5295. The plan is to release 5.0.5 on May 8.

**Comment by paulspeijers** [comment]
@jgrandja. That's great to hear, thanks a lot for your good ideas and your responsiveness. I'm looking forward to phasing out some of my custom solutions :-)
