### ISSUE TITLE
The user-info-uri does not support URI variables

### ISSUE THREAD

**Issue by paulspeijers** [spring-projects/spring-security#5286]
### Summary
I'm implementing a scenario in which I use Open ID connect to authenticate with ORCID (https://members.orcid.org/api/tutorial/read-orcid-records). The workflow is as follows:

1. Get authorization code
2. Get access token (using openid scope)
3. Get user details from ORCID person: https://api.sandbox.orcid.org/v2.1/[ORCID iD]/person, like email address, firstname, surname and publication name
4. Create a  DefaultOidcUser object that is used as a security principle within the Authentication.
5. Get user details from our own data store (iRODS).
6. Use user details to set the Authentication.details.

I have a number of issues with this setup. In this issue I will focus on the following:

The userInfoUri for ORCID contains a variable part which the spring security oauth2 mechanism does not support:
ORCID offers the following userInfoUri: https://api.sandbox.orcid.org/v2.1/[ORCID iD]/person
Within this userInfoUri the [ORCID ID] part is variable and needs to be substituted by the subject ("sub" claim) from the authorization token. This token I obtain using the OidcScopes.OPENID scope.

### Workaround
I currently use the following workaround, which makes it hard for me to migrate to new spring security versions:

Within the clientRegistration I configured the following userInfoUri with a {sub} placeholder:
https://api.sandbox.orcid.org/v2.0/{sub}/person

I fork the NimbusUserInfoResponseClient and there, within getUserInfoResponse, I replace a variable part of the uri (clientRegistration.getProviderDetails().getUserInfoEndpoint().getUri()) with the subject obtained from the authorization code:
uri = uri.replace("{sub}", userInfoRequest.getIdToken().getSubject());

### Actual Behavior

The API does not offer a possibility to use a userInfoUri with variable parts

### Expected Behavior

The API offers a possibility to use a userInfoUri with variable parts

### Configuration
We are running our frontend and backend within Tomcat 8 servers
In front of that environment we have an NGINX 1.13 webserver
We are authenticating with orcid API 2.1 using open id connect: https://members.orcid.org/api/tutorial/read-orcid-records

The configuration of oauth is:
spring.security.oauth2.client.registration.orcid.redirect-uri-template={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.orcid.scope=/read-limited openid
spring.security.oauth2.client.registration.orcid.client-name=ORCID
spring.security.oauth2.client.registration.orcid.authorization-uri=https://sandbox.orcid.org/oauth/authorize
spring.security.oauth2.client.registration.orcid.token-uri=https://sandbox.orcid.org/oauth/token
spring.security.oauth2.client.registration.orcid.jwk-set-uri=https://sandbox.orcid.org/oauth/jwks
spring.security.oauth2.client.registration.orcid.user-info-uri=https://api.sandbox.orcid.org/v2.0/{sub}/person

### Version
We are using the 5.0.3.RELEASE of the following dependencies:
spring-security-web
spring-security-config
spring-security-oauth2-core
spring-security-oauth2-client
spring-security-oauth2-jose
spring-security-saml2-core

**Comment by jgrandja** [comment]
@paulspeijers The `OidcUserService` does not support URI variables in the `user-info-uri`. I haven't seen a variable `URI` for the UserInfo Endpoint on a Provider. Typically the UserInfo Endpoint is static and simply requires an Access Token that provides access to the currently authenticated users info. It seems redundant to me to have the `sub` claim as part of the `URI`.

To meet your requirements, you can define your own custom implementation of `OidcUserService` that uses a variable `URI` for the UserInfo Endpoint. The `OidcUserRequest` passed into `OidcUserService.loadUser()` gives you access to the `OidcIdToken` so you can retrieve the `getSubject()` and use that to build the `URI`. 

You can configure your custom `OidcUserService` as follows:

```
@Override
protected void configure(HttpSecurity http) throws Exception {
	http
		.oauth2Login()
			.userInfoEndpoint()
				.oidcUserService(this.customOidcUserService())
				...
}
```

See the [reference](https://docs.spring.io/spring-security/site/docs/5.0.4.RELEASE/reference/htmlsingle/#oauth2login-advanced-oidc-user-service) for more details.

I'm going to close this issue as I feel I have provided you a solution on how you can integrate your custom `OidcUserService`.

**Comment by jgrandja** [comment]
@paulspeijers I'm re-opening this issue to see if other users require the uri variable support for `user-info-uri`. I feel like this is an edge case at the moment. But let's see if other users report the same issue.

Users can vote for it by adding a +1 reaction to the first comment.

**Comment by jgrandja** [comment]
@paulspeijers With the recent release of Spring Security 5.1, you can now fully customize the UserInfo request using a `Converter<OAuth2UserRequest, RequestEntity<?>>`. For example, you can add a path parameter to the uri and set the value with the `sub` claim as per your use case. See the [reference](https://docs.spring.io/spring-security/site/docs/5.1.1.RELEASE/reference/htmlsingle/#oauth2login-advanced-oauth2-user-service) for more details.

I'm going to close this issue as 5.1 provides the flexibility you need.

**Comment by paulspeijers** [comment]
Great news @jgrandja. Thanks for the heads up, we'll give it a go!
