### ISSUE TITLE
The configured oauth2 authenticationProvider is not respected

### ISSUE THREAD

**Issue by paulspeijers** [spring-projects/spring-security#5287]
### Summary
I'm implementing a scenario in which I use Open ID connect to authenticate with ORCID (https://members.orcid.org/api/tutorial/read-orcid-records). The workflow is as follows:

1. Get authorization code
2. Get access token (using openid scope)
3. Get user details from ORCID person: https://api.sandbox.orcid.org/v2.1/[ORCID iD]/person, like email address, firstname, surname and publication name
4. Create a  DefaultOidcUser object that is used as a security principle within the Authentication.
5. Get user details from our own data store (iRODS).
6. Use user details to set the Authentication.details.

I have a number of issues with this setup. In this issue I will focus on the following:

The configured oauth2 authenticationProvider is not respected. I want to implement the above mentioned step 5, and get user details from iRODS and store them within the Authentication.details.
For this I wanted to extend the OidcAuthorizationCodeAuthenticationProvider. I tried to enable my own class as follows within my extension of WebSecurityConfigurerAdapter:

```
@Autowired
private OidcAuthorizationCodeAuthenticationProviderOrcid oidcAuthorizationCodeAuthenticationProviderOrcid;

@Override
protected void configure(AuthenticationManagerBuilder auth) throws Exception {
  auth.authenticationProvider(oidcAuthorizationCodeAuthenticationProviderOrcid);
}
```

I based this solution on the following article: http://www.baeldung.com/spring-security-authentication-provider

However when I debug the OAuth2LoginAuthenticationFilter it does not seem to execute the configured authenticationProvider at the following line:
L159: this.getAuthenticationManager().authenticate(authenticationRequest)

### Workaround
Currently I abuse the OAuth2AuthorizedClientService mechanism and use that to implement the above mentioned behavior. However, this is not what it's intented for and it makes it hard for me to migrate to new spring security versions:

### Actual Behavior

Spring security ignores any custom oauth2 authentication providers.

### Expected Behavior

Spring security respects any custom oauth2 authentication providers.

### Configuration
We are running our frontend and backend within Tomcat 8 servers
In front of that environment we have an NGINX 1.13 webserver
We are authenticating with orcid API 2.1 using open id connect: https://members.orcid.org/api/tutorial/read-orcid-records

The configuration of oauth is:
spring.security.oauth2.client.registration.orcid.redirect-uri-template={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.orcid.scope=/read-limited openid
spring.security.oauth2.client.registration.orcid.client-name=ORCID
spring.security.oauth2.client.registration.orcid.authorization-uri=https://sandbox.orcid.org/oauth/authorize
spring.security.oauth2.client.registration.orcid.token-uri=https://sandbox.orcid.org/oauth/token
spring.security.oauth2.client.registration.orcid.jwk-set-uri=https://sandbox.orcid.org/oauth/jwks
spring.security.oauth2.client.registration.orcid.user-info-uri=https://api.sandbox.orcid.org/v2.0/{sub}/person

### Version
We are using the 5.0.3.RELEASE of the following dependencies:
spring-security-web
spring-security-config
spring-security-oauth2-core
spring-security-oauth2-client
spring-security-oauth2-jose
spring-security-saml2-core

**Comment by jgrandja** [comment]
@paulspeijers Based on your requirement:

> 5. Get user details from our own data store (iRODS).

> I want to implement the above mentioned step 5, and get user details from iRODS and store them within the Authentication.details

We do not allow overriding the `OidcAuthorizationCodeAuthenticationProvider`. The main extension point for fetching user details is the `OAuth2UserService`. So for your scenario, you would implement `OAuth2UserService<OidcUserRequest, OidcUser>` and fetch the details from iRODS and ultimately store this information in either `DefaultOidcUser` or an extension of `DefaultOidcUser` with your custom attributes. Than you can always retrieve this information from `Authentication.getPrincipal()` (returns `DefaultOidcUser` or your extension).

You can define your own custom implementation of `OidcUserService` and configure it as follows:

```
@Override
protected void configure(HttpSecurity http) throws Exception {
	http
		.oauth2Login()
			.userInfoEndpoint()
				.oidcUserService(this.customOidcUserService())
				...
}
```

See the [reference](https://docs.spring.io/spring-security/site/docs/5.0.4.RELEASE/reference/htmlsingle/#oauth2login-advanced-oidc-user-service) for more details.

I'm going to close this issue as I feel I have provided you the main extension point for your use case.

**Comment by paulspeijers** [comment]
@jgrandja. The problem of fetching the iRODS information from within the OidcUserService is that I cannot access the Authentication object there. One the one hand I could get the information and add it to the DefaultOidcUser, but I could not set is as the details part of the Authentication. I would need another place for that, which is probably either a custom AuthenticationProvider, or a custom Filter, and I would prefer the former (because it's a more local change).

**Comment by jgrandja** [comment]
@paulspeijers Why do you need to set `Authentication.details`? This is not the correct place to set user specific information. I would recommend extending `DefaultOidcUser` or implementing `OidcUser` and storing all your user information there.

**Comment by paulspeijers** [comment]
Hi @jgrandja I did some study about the difference between the principle and the details and the difference was not really clear to me. At the end I was under the assumption the following applied:
- The principle is the user representation from the underlying identity provider, and is essentially some form of credentials to authenticate with
- The details is the actual user information obtained from your application's data store, with stuff like email address, address and phone number

Some items that lead to this assumption:
- The term UserDetailsService implies it is fetching the Authentiation.details
- It helps me to think about security as a two step process 1 get principle and put them in Authentication.principle, 2 get details and put them in Authentication.details. That way I can easily check within my application for a situation in which a user is authenticated but no details have been fetched yet. Our signup flow is that a user first logs in with an ORCID or SAML identity provider, then needs to agree on some legal terms, and then a user within iRODS is created and put in the details section.

How would you distinguish between these 2?

**Comment by paulspeijers** [comment]
@jgrandja Yes it does thanks. What I still wonder is the following:
I will then get 2 flavors of user principals:
- A user based on DefaultOidcUser when authenticating against ORCID
- A user based on SAMLCredential when authenticating against SAML

One the one hand, functionally for me this is the same user with the same attributes. One the other hand I do think it would be good to extend these classes so I don't lose any potentially valuable information from the underlying authentication provider.

Because Java does not offer multiple inheritance I only one option to accomplish this. Namely to extend the above mentioned classes (DefaultOidcUser and SAMLCredential), and then have both classes implement 1 interface that exposes all user attributes I need within my application (such as email address, firstname, surname and publication name).

Would this be the way to go?

A reason for me to implement it like I did was that it allowed me to simply set the authentication provider information information as a principle, and then create a User based on these different principals and set it as a details object.

**Comment by jgrandja** [comment]
@paulspeijers You don't need to extend `DefaultOidcUser` as I had previously mentioned. Given your implementation scenario, you also have the option to implement `OidcUser` instead.

**Comment by anandmuthu-vnix** [comment]
@jgrandja  In **spring-security-oauth2:2.0.12.RELEASE**, we use to interpret the OAuth2ClientAuthenticationProcessingFilter and obtain the user info from OAuth resource server and merge it with the User Info in the App server.

```
@Override
public Authentication attemptAuthentication(HttpServletRequest request, HttpServletResponse response) throws AuthenticationException, IOException, ServletException {
        OAuth2Authentication authentication = (OAuth2Authentication) super.attemptAuthentication(request, response);
        **saveOAuthUserProfile(authentication);**
        return authentication;
    }
```
We also use AuthoritiesExtractor (in UserInfoTokenServices) to update the User Roles based on the user information in the DB.

How can we achieve a similar solution with spring-security-oauth2-client:5.0.4.RELEASE? Though we have customized the UserInfoService, it is not getting invoked.

**Comment by anandmuthu-vnix** [comment]
> Currently I abuse the OAuth2AuthorizedClientService mechanism and use that to implement the above mentioned behavior. However, this is not what it's intented for and it makes it hard for me to migrate to new spring security versions:

@paulspeijers How did you solve using OAuth2AuthorizedClientService?

**Comment by jgrandja** [comment]
@anandmuthu-vnix 

> How can we achieve a similar solution with spring-security-oauth2-client:5.0.4.RELEASE? Though we have customized the UserInfoService, it is not getting invoked.

I'm assuming you meant `OAuth2UserService` instead of `UserInfoService`? ...spring-security-oauth2-client:5.0.4.RELEASE does not contain a `UserInfoService`. 

If you're looking how to configure a `OAuth2UserService` please see the [reference](https://docs.spring.io/spring-security/site/docs/5.0.5.RELEASE/reference/htmlsingle/#oauth2login-advanced-oauth2-user-service).

**Comment by paulspeijers** [comment]
@anandmuthu-vnix I'm registering my own OAuth2AuthorizedClientService as follows:

```
  @Override
  protected void configure(HttpSecurity http) throws Exception {
    http.regexMatcher(".*oauth2.*")
        .authorizeRequests().anyRequest().permitAll().and().oauth2Login()
        .authorizedClientService(oAuth2AuthorizedClientService()).loginPage("/login")
        .defaultSuccessUrl("/login/handle").userInfoEndpoint().oidcUserService(oidcUserService);
  }

  private OAuth2AuthorizedClientService oAuth2AuthorizedClientService() {
    return new OAuth2AuthorizedClientServiceOrcid(clientRegistrationRepository(),
        userDetailsService);
  }
```
