### ISSUE TITLE
OAuth2 authentication fails when performed behind a webserver

### ISSUE THREAD

**Issue by paulspeijers** [spring-projects/spring-security#5288]
### Summary
I'm implementing a scenario in which I use Open ID connect to authenticate with ORCID (https://members.orcid.org/api/tutorial/read-orcid-records). The workflow is as follows:

1. Get authorization code
2. Get access token (using openid scope)
3. Get user details from ORCID person: https://api.sandbox.orcid.org/v2.1/[ORCID iD]/person, like email address, firstname, surname and publication name
4. Create a  DefaultOidcUser object that is used as a security principle within the Authentication.
5. Get user details from our own data store (iRODS).
6. Use user details to set the Authentication.details.

I have a number of issues with this setup. In this issue I will focus on the following:

OAuth2 authentication fails when performed behind a webserver.

Within OidcAuthorizationCodeAuthenticationProvider the following check is performed:
L134: if (!authorizationResponse.getRedirectUri().equals(authorizationRequest.getRedirectUri())) {

However, when you're behind a webserver these don't match and the authentication fails:
authorizationResponse.getRedirectUri() = https://webserverurl/login/oauth2/code/orcid
authorizationRequest.getRedirectUri() = https://tomcaturl:8080/login/oauth2/code/orcid

We also support SAML authentication and the spring-security SAML solution offers a mechanism for this:
SAMLContextProviderLB

### Workaround
In order to fix this problem I now apply the following hack:
I created a WebserverRequestFilter which extends AbstractPreAuthenticatedProcessingFilter
Within this filter I wrap the request in a HttpServletRequestWrapper in which I override the getRequestURL method. Within this method I return the host, port and scheme from the x-forwarded-host and x-forwarded-proto headers, when available.

Within my extension of WebSecurityConfigurerAdapter I configure the filter as follows:
```
@Override
protected void configure(HttpSecurity http) throws Exception {
  http.addFilter(new WebserverRequestFilter())
  ...
```

I also checked out Tomcat's RemoteIpValve mechanism as a more permanent solution, but it does not support host names at this time of writing:
https://tomcat.apache.org/tomcat-7.0-doc/api/org/apache/catalina/valves/RemoteIpValve.html
  
### Actual Behavior
Spring security ignores any custom oauth2 authentication providers.

### Expected Behavior

Spring security respects any custom oauth2 authentication providers.

### Configuration
We are running our frontend and backend within Tomcat 8 servers
In front of that environment we have an NGINX 1.13 webserver
We are authenticating with orcid API 2.1 using open id connect: https://members.orcid.org/api/tutorial/read-orcid-records

The configuration of oauth is:
spring.security.oauth2.client.registration.orcid.redirect-uri-template={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.orcid.scope=/read-limited openid
spring.security.oauth2.client.registration.orcid.client-name=ORCID
spring.security.oauth2.client.registration.orcid.authorization-uri=https://sandbox.orcid.org/oauth/authorize
spring.security.oauth2.client.registration.orcid.token-uri=https://sandbox.orcid.org/oauth/token
spring.security.oauth2.client.registration.orcid.jwk-set-uri=https://sandbox.orcid.org/oauth/jwks
spring.security.oauth2.client.registration.orcid.user-info-uri=https://api.sandbox.orcid.org/v2.0/{sub}/person

### Version
We are using the 5.0.3.RELEASE of the following dependencies:
spring-security-web
spring-security-config
spring-security-oauth2-core
spring-security-oauth2-client
spring-security-oauth2-jose
spring-security-saml2-core

**Comment by paulspeijers** [comment]
Thanks @rwinch for the suggestion. It sounds like I can use it to get rid of some custom code. Is this something you would recommend using throughout your entire web application, or just for some specific security related URLs?

**Comment by rwinch** [comment]
@paulspeijers I would recommend using ForwardedHeaderFilter or something like IpValve for anything that is behind a proxy server. This ensures your URLs are correct. An important note is that for security reasons it is absolutely critical that your proxy server ensures only valid X-Forwarded headers are set. You don't want a malicious user setting the X-Forwarded headers to something else. This is pretty standard setup for a proxy server, but I wanted to emphasize that point.

I'm going to close this issue as resolved as this is expected behavior. Please reopen if you have additional issues getting it to work
