### ISSUE TITLE
Provide support for configuring `aud` for resource servers

### ISSUE THREAD

**Issue by tnwang** [spring-projects/spring-security#5292]
There is no way to configure the `aud` claim for a Resource Server in legacy OAuth using a property - only through code today.

Allowing configuration of this property through Spring Security/Spring Boot would help simplify usage of Spring Security for resource servers.

**Comment by jzheaux** [comment]
@tnwang since you are looking for legacy OAuth, then would you please add post this in [`spring-security-oauth2-boot`](https://github.com/spring-projects/spring-security-oauth2-boot/issues)? Thanks!

**Comment by jgrandja** [comment]
@jzheaux I believe @tnwang is looking for a similar feature in the new OAuth support.

**Comment by jzheaux** [comment]
@jgrandja In that case, do you think the best place for this ticket is [spring-boot](https://github.com/spring-projects/spring-boot/issues)?

**Comment by jgrandja** [comment]
@jzheaux Yes this should be logged in Spring Boot. I originally logged it here as we didn't have the `OAuth2TokenValidator` as of yet. Now that it's in 5.1, can you please log a ticket with Boot.

The one important thing to keep in mind is that the user should be able to configure 1..* `aud` claims.

**Comment by rwinch** [comment]
I'm not sure that this is something we should do in boot. Adding every bell and whistle to a property config makes things complicated and yet often still doesn't support every use case. I'd prefer us to allow the user to expose it as a Bean. Most users do not need to configure the claim validation via properties. It's likely going to be fixed for a particular deployment.

**Comment by jgrandja** [comment]
> Adding every bell and whistle to a property config makes things complicated and yet often still doesn't support every use case

@rwinch has a good point here. We do need to ensure the property hierarchy doesn't get too complicated and overwhelming to the user. So on second thought, I think we should hold off on the Boot  property.

As @rwinch mentioned, it would be simple for the user to expose a bean using an implementation we provide and they simply supply the `aud` claim.
