### ISSUE TITLE
SEC-271: Spring 2-based configuration simplification of Acegi Security

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#532]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-271":https://jira.spring.io/browse/SEC-271?redirect=false]) said:

It would be desirable if Acegi Security could be configured using the new Spring 2 namespaces feature. It is expected that most users will adopt the new XML format, rather than the historical <bean>s approach. As such, a migration to constructor injection should also be undertaken in order to eliminate the opportunity for objects to be in an inconsistent state.

Uri Boness has volunteered to work on this task.

**Comment by spring-issuemaster** [comment]
This issue depends on #843
This issue depends on #845
This issue depends on #844
