### ISSUE TITLE
Support jCasbin as the authorization backend to provide ACL, RBAC, ABAC at the same time

### ISSUE THREAD

**Issue by veotax** [spring-projects/spring-security#5320]
[jCasbin](https://github.com/casbin/jcasbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in casbin's language) can be persisted in files or database.
4. multiple models like ACL, BLP, RBAC, ABAC, RESTful are supported.

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

I saw there's a need for all the models (ACL, RBAC, ABAC) here: https://github.com/spring-projects/spring-security/pull/4277, and I think jCasbin is a good choice. What do you think? Thanks.

**Comment by nmrony** [comment]
@rwinch Any updates on this?

**Comment by Kiddinglife** [comment]
really need this!!

**Comment by rwinch** [comment]
I don't think there is anything special that needs to be done here. This can be done using Spring Beans. Create a bean that performs the check and then invoke it using [SpEL](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#expressions).

**Comment by veotax** [comment]
Hi @rwinch , do you have any example code to show the usage?

**Comment by rwinch** [comment]
https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#el-access-web-beans

**Comment by rwinch** [comment]
Given there hasn't been any feedback, I'm assuming that a Bean based approach works just fine. Unless I hear otherwise, this issue will be closed.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
