### ISSUE TITLE
Handling error: InvalidClientException, Unauthorized grant type: password

### ISSUE THREAD

**Issue by jxin19** [spring-projects/spring-security#5329]
### Summary
If 'authorized_grant_types' data field of table 'oauth_client_details' includes WHITE SPACE, should occur an error that "Unauthorized grant type" then below.

Tokenendpoint
`OAuth2AccessToken token = getTokenGranter().grant(tokenRequest.getGrantType(), tokenRequest)`

Specific occurred location is 'validateGrantType' method of 'AbstractTokenGranter' class.
that method doesn't handle to 'trim()' for elements of 'clientDetails.getAuthorizedGrantTypes()'.

### Solution
1. remove WHITE SPACE within 'authorized_grant_types' data field of table 'oauth_client_details'.
2. call 'BaseClientDetails.getAuthorizedGrantTypes' method then handles to 'trim()'.

### Version
spring-boot-starter-security:2.0.1.RELEASE

**Comment by jgrandja** [comment]
@jxin19 See  [A.10. "grant_type" Syntax](https://tools.ietf.org/html/rfc6749#appendix-A.10)

The `grant_type` should be one of `authorization_code`, `client_credentials` or `password` (for `implicit` use `response_type=token`).

You need to ensure your saved client configuration follows this syntax. The whitespace in the `authorized_grant_types` data column is a misconfiguration. Please ensure your saved configuration does not contain whitespace and follows the syntax.

I'm going to close this but if you're still having an issue please log in the [Spring Security OAuth](https://github.com/spring-projects/spring-security-oauth/issues) issues.

**Comment by jxin19** [comment]
@jgrandja 
Thanks your reply. Your're right.
My explanation is not enough.
Some practices recommend input 'authorized_grant_types' data field of the table to multiple grant types then occurred an error if includes WHITE SPACE.
e.g. "authorization_code, password, implicit, refresh_token"

Sorry but I figure out that error why occurred so difficult. so that I wrote here. 😁
