### ISSUE TITLE
Automatically add CsrfServerLogoutHandler if csrf enabled

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#5337]
### Summary

The configuration DSL should automatically add CsrfServerLogoutHandler if csrf is enabled

See #4840

**Comment by rwinch** [comment]
> Should we build a DelegatingServerLogoutHandler that can delegate to multiple ServerLogoutHandlers?

@edeandrea Thanks for reaching out! Yes I think that would be the ideal way of handling it.

**Comment by edeandrea** [comment]
Seems the `DelegatingServerLogoutHandler` ticket is already raised in #4839

**Comment by edeandrea** [comment]
I've added #5379 for this.
