### ISSUE TITLE
Form-based login doesn't work in WebFlux + OAuth example

### ISSUE THREAD

**Issue by mraible** [spring-projects/spring-security#5348]
### Summary

The [oauth2login-webflux](https://github.com/spring-projects/spring-security/tree/master/samples/boot/oauth2login-webflux) works great for logging into Okta. However, it also presents a regular login form that doesn't work.

### Actual Behavior

If you try to login with “user” and the generated password in the console. You get an error:

```
Whitelabel Error Page

This application has no configured error view, so you are seeing this as a fallback.

Sat May 12 16:51:00 MDT 2018
There was an unexpected error (type=Internal Server Error, status=500).
Unable to resolve the Client Registration Identifier. It must be provided via @OAuth2Client("client1") or @OAuth2Client(registrationId = "client1”).
```

### Expected Behavior

Logging in with "user" and the generated password works, or the login form is hidden when using OAuth login.

### Version

5.1.0.BUILD-SNAPSHOT

### Sample

https://github.com/mraible/webflux-oauth2

**Comment by rwinch** [comment]
Thanks for the report! I improved this so that the default log in page no longer displays the form log in. However, I want to improve this even further once we support getting an access token for users who have logged in via other mechanisms. For that reason, I'm keeping this issue open.

**Comment by mraible** [comment]
@rwinch I'm OK if you close this. :)

**Comment by rwinch** [comment]
Thanks for the reminder. Yes it can be closed :)
