### ISSUE TITLE
Multi-tenancy support for OAuth2

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#5351]
### Summary

Today, it isn't clear how to best configure Spring Security to support a multi-tenant OAuth2 client.

Here is an example of one approach out in the wild:

https://github.com/thomasdarimont/spring-boot-2-keycloak-oauth-example/blob/feature/mulit-tenancy/src/main/java/demo/SpringBoot2App.java#L127

Though whether `JwtDecoder` is the ideal place and how tenants might possibly be treated in a more first-class way is yet to be seen. Opening this issue to get the conversation started.

**Comment by jgrandja** [comment]
Related #5385

**Comment by metacubed** [comment]
In a multi-tenant configuration, each tenant would likely come with its own set of allowed issuers. A tenant-specific request would trust only a subset of the issuers configured for the resource server.

We would need to introduce a selection mechanism to pick the allowed issuer(s) for a request. This `IssuerListSelector` could have custom implementations that are specific to the resource server.

For example, the `keycloak-auth` project uses the `request.getServerName()` to decide which decoder implementation to use. Other request attributes could also be used, such as the request sub-domain, a header, etc.

**Comment by canayozel** [comment]
@jzheaux since this is released with spring security 5.2.0 is there any documentation or example to follow ?

**Comment by jzheaux** [comment]
@canayozel Multi-tenancy support for clients is had through multiple client registrations: https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#oauth2login-custom-provider-properties

For resource server, we have [a sample](https://github.com/spring-projects/spring-security/tree/master/samples/boot/oauth2resourceserver-multitenancy), but are [still on the hook for adding documentation](https://github.com/spring-projects/spring-security/issues/7532).

**Comment by bertramn** [comment]
Hmm not too sure how the [multi tenant example](https://github.com/spring-projects/spring-security/blob/master/samples/boot/oauth2resourceserver-multitenancy/src/main/java/sample/OAuth2ResourceServerSecurityConfiguration.java) is of use to anyone wanting to run a Resource Server that can validate JWTs from different issuers. It just flip-flops the `AuthenticationManager` back and forth between paths. And I thought we finally could replace our custom implementation.

**Comment by jzheaux** [comment]
@bertramn, you are right that 5.2.x doesn't support any specific multi-tenancy model for resource servers. `AuthenticationManagerResolver` gives applications a place to address their multi-tenancy use case, be it whatever it may. In 5.2.x, there is just the interface and DSL hook.

#7724 demonstrates one way Spring Security might be able to support your use case for JWTs and multiple issuers - feel free to comment over there how well that implementation simplifies your customizations.

**Comment by 20fps** [comment]
@jzheaux thank you for the example of multi-tenancy. But what about the case with dynamic tenants creation, does spring-security help to resolve this? In this case we have to get tenant from JWT, but we need to right converters etc. manually, am I wrong?

**Comment by 20fps** [comment]
Thanks a lot for this video https://www.youtube.com/watch?v=ke13w8nab-k
It answered all of my questions on multi-tenancy
