### ISSUE TITLE
Enables oauth2-Client to receive code and state for different parameter names via configuration in ClientRegistration.

### ISSUE THREAD

**Issue by XYUU** [spring-projects/spring-security#5367]
### Summary
Enables oauth2-Client to receive code and state for different parameter names via configuration in ClientRegistration.

### Actual Behavior
Some third-party OAuth2.0 service parameter names do some simple modifications, such as: The code name is auth_code.

### Expected Behavior
Expect to be able to pass the authorization correctly, an exception will now occur, and there is no configuration available.

OAuth2AuthorizationResponseUtils is now accepted with a fixed parameter name.

**Comment by jgrandja** [comment]
@XYUU Can you provide me a link to the OAuth 2.0 Provider API docs that uses `auth_code` instead of `code` for the parameter name. As you are aware, this is not the standard parameter name defined in the [spec](https://tools.ietf.org/html/rfc6749#section-4.1.2).

**Comment by XYUU** [comment]
@jgrandja https://docs.open.alipay.com/284/106001/

**Comment by XYUU** [comment]
You see Taobao, not Alipay. Alipay is a payment platform similar to PayPal in the United States.
Taobao is similar to eBay or Amazon in the United States.
Alipay receives a callback parameter named "auth_code".
So we need a hook to modify the name of the callback parameter.

![image](https://user-images.githubusercontent.com/9715021/40755702-1135d0c4-64b2-11e8-9981-94d5eed440e9.png)

**Comment by jgrandja** [comment]
> Alipay is a payment platform similar to PayPal in the United States.

So Alipay is not an OAuth 2.0 Provider?

**Comment by XYUU** [comment]
Alipay is a payment platform and also provides OAuth2.0 service.

![image](https://user-images.githubusercontent.com/9715021/40830966-5c9674e8-65ba-11e8-8ee2-52c324d944ee.png)

I said "Alipay is a payment platform similar to PayPal in the United States." I wanted to introduce Alipay to you because I saw you confuse it with Taobao.

**Comment by jgrandja** [comment]
@XYUU There hasn't been any demand for allowing the customization of the Authorization Response parameters. And looking at Alipay's Authorization Response it contains the parameters `auth_code`, `app_id`, `scope`, `source`, which is not at all compliant to a standard [OAuth 2.0 Authorization Response](https://tools.ietf.org/html/rfc6749#section-4.1.2).

Based on all of this I am very reluctant to add this customization.

However, here is a custom solution I can propose to you. I believe what you need to do is create a custom `Filter` that sits in front of the `OAuth2LoginAuthenticationFilter` that simply wraps the `HttpServletRequest` using a custom extension of `HttpServletRequestWrapper`. The custom `HttpServletRequestWrapper` would simply adapt calls to `getParameter()`, `getParameterMap()`, `getParameterValues()`, etc. and provide the custom logic. For example, when `getParameter("code")` is called than you would return `getParameter("auth_code")`. I believe this solution should work and allow `OAuth2LoginAuthenticationFilter` to process the `authorization_code` that is actually coming from the `auth_code` parameter.
