### ISSUE TITLE
Makes oauth2-client compatible with responses without token_type

### ISSUE THREAD

**Issue by XYUU** [spring-projects/spring-security#5369]
### Summary
Make oauth2-client compatible with no "token_type": "Bearer" response. Some third-party OAuth2.0 Service do not have token_type.

### Actual Behavior
Now that the oauth2-client must have a token_type, these third-party OAuth2.0 services cannot be accessed.

### Expected Behavior
Expect to ignore the token_type parameter check.

**Comment by jgrandja** [comment]
@XYUU As per the [spec](https://tools.ietf.org/html/rfc6749#section-5.1):

> token_type
         REQUIRED.  The type of the token issued as described in Section 7.1.  Value is case insensitive.

If you need to override this behaviour you can provide your own implementation of `OAuth2AccessTokenResponseClient` that ignores the `token_type` response parameter. This [sample](https://docs.spring.io/spring-security/site/docs/5.0.5.RELEASE/reference/htmlsingle/#oauth2login-advanced-token-client) demonstrates how to configure your own implementation.

**Please note:** Spring Security's goal is to provide **spec-compliant** implementations only. However, if user's need to deviate from the spec than we will ensure that there is a hook for you to provide your own custom implementation.

I'm going to close this issue as I've provided you a solution on how to configure your custom implementation.
