### ISSUE TITLE
Add an extraction method that can specify OAuth2AccessTokenResponse, OAuth2User for the client in ClientRegistration.

### ISSUE THREAD

**Issue by XYUU** [spring-projects/spring-security#5371]
### Summary
Add an extraction method that can specify OAuth2AccessTokenResponse, OAuth2User for the client in ClientRegistration.

### Actual Behavior
It is not possible to extract response information from some third-party services.

**Comment by jgrandja** [comment]
@XYUU I'm not sure I understand what you are looking for here? However, based on your comment:

> It is not possible to extract response information from some third-party services.

Are you looking to extract response data from the **Token Response** and **UserInfo Response**?

If so, you can provide your own implementation of [`OAuth2AccessTokenResponseClient`](https://docs.spring.io/spring-security/site/docs/5.0.5.RELEASE/reference/htmlsingle/#oauth2login-advanced-token-client) and [`OAuth2UserService`](https://docs.spring.io/spring-security/site/docs/5.0.5.RELEASE/reference/htmlsingle/#oauth2login-advanced-oauth2-user-service).
This gives you full-control in the request and response flow.
