### ISSUE TITLE
Add the ability to specify a custom implementation of the OAuth2AuthorizationRequestUriBuilder for the client in ClientRegistration.

### ISSUE THREAD

**Issue by XYUU** [spring-projects/spring-security#5372]
### Summary
Add the ability to specify a custom implementation of the OAuth2AuthorizationRequestUriBuilder for the client in ClientRegistration.

### Actual Behavior
There is only one default implementation and it is not compatible with some third-party OAuth2 services.

### Expected Behavior
Expect to be compatible, preferably in ClientRegistration.

**Comment by jgrandja** [comment]
This is a duplicate of #4911
