### ISSUE TITLE
Use same ClientRegistration for either login or getting an access token

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#5380]
### Summary

Ideally the same ClientRegistration could be used for either getting an access token or log in. Right now getting an access token redirects to a different endpoint.

**Comment by jgrandja** [comment]
This can be achieved using a custom `OAuth2AuthorizationRequestResolver`, which was introduced in 5.1. The `OAuth2AuthorizationRequest.redirectUri` can be updated to the appropriate value during the Authorization Request phase. See the [reference](https://docs.spring.io/spring-security/site/docs/5.1.1.RELEASE/reference/htmlsingle/#oauth2Client-authorization-request-resolver) for further details.

**Comment by rwinch** [comment]
This should work out of the box. In fact, this was resolved via #5856
