### ISSUE TITLE
OidcUserService should leverage DefaultOAuth2UserService

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#5390]
### Summary

Rather than copying `NimbusUserInfoResponseClient` the code should just delegate to `DefaultOAuth2UserService`

**Comment by XYUU** [comment]
I implemented this feature in my PR, but because my PR was not focused enough, it was rejected.
https://github.com/spring-projects/spring-security/pull/5353
Can I split the code needed for this issue from this PR to mention a new PR?

**Comment by jgrandja** [comment]
@XYUU Thanks for the offer but I already started this issue.

**Comment by jgrandja** [comment]
Good catch @rwinch! This cleaned up nicely :)
