### ISSUE TITLE
Errors while processing claimed identity are logged as DEBUG and swallowed

### ISSUE THREAD

**Issue by igoyak** [spring-projects/spring-security#5391]
### Summary

If an OpenIDConsumerException is throws while processing a claimed identity, the reason for the error is logged as DEBUG, and another exception is thrown without including the information from the first one: 

https://github.com/spring-projects/spring-security/blob/b3ca5986791ac5c97022d64646df1a6e1ec2a8b7/openid/src/main/java/org/springframework/security/openid/OpenIDAuthenticationFilter.java#L149-L151

### Actual Behavior

If an OpenIDConsumerException is thrown, it is impossible to find the reason without turning on debug logging. 

### Expected Behavior

If an OpenIDConsumerException is thrown, it should be possible to find the reason without turning on debug logging. An error should be logged with level ERROR.

**Comment by rwinch** [comment]
Closing as outlined in the PR
