### ISSUE TITLE
Enable us to filter mappings for the DelegatingPasswordEncoder in PasswordEncoderFactories

### ISSUE THREAD

**Issue by pcornelissen** [spring-projects/spring-security#5405]
### Summary

The PasswordEncoderFactories#createDelegatingPasswordEncoder method creates a DelegatingPasswordEncoder with a large number of passwordEncoders. It would be nice to be able to filter this list to get rid of unwanted encoders without loosing the benefit of getting new ones automatically.

### Actual Behavior

The list of encoders is created in the factory method without a way to filter or influence it.

### Expected Behavior

It would be nice to be able to filter this list to blacklist insecure or unwanted password encoders before passing it to the delegatingPasswordEncoder constructor.
Alternatively the list creation could be put into its own method which is accessible, so we can use this as starting point and call the constructor of the delegatingPasswordEncoder on our own.

(I know that I can create the list completely on my own, but then I can't benefit from new additions or even removals automatically)

### Configuration
Java 8

### Version

Spring boot 2.0.2

### Sample
Simple example:
```
	public static Map<String, PasswordEncoder> createDefaultEncoders() {
		 encoders = new HashMap<>();
		encoders.put(encodingId, new BCryptPasswordEncoder());
		encoders.put("ldap", new LdapShaPasswordEncoder());
		encoders.put("MD4", new Md4PasswordEncoder());
		encoders.put("MD5", new MessageDigestPasswordEncoder("MD5"));
		encoders.put("noop", NoOpPasswordEncoder.getInstance());
		encoders.put("pbkdf2", new Pbkdf2PasswordEncoder());
		encoders.put("scrypt", new SCryptPasswordEncoder());
		encoders.put("SHA-1", new MessageDigestPasswordEncoder("SHA-1"));
		encoders.put("SHA-256", new MessageDigestPasswordEncoder("SHA-256"));
		encoders.put("sha256", new StandardPasswordEncoder());

		return encoders;
	}

	public static PasswordEncoder createDelegatingPasswordEncoder() {
		String encodingId = "bcrypt";
		Map<String, PasswordEncoder> encoders = createDefaultEncoders();
		return new DelegatingPasswordEncoder(encodingId, encoders);
	}

```

**Comment by rwinch** [comment]
> It would be nice to be able to filter this list to blacklist insecure or unwanted password encoders before passing it to the delegatingPasswordEncoder constructor.

The Map provides how passwords are matched and does not impact how they are encoded. This means that changing the Map (i.e. removing insecure encoders) from `DelegatingPasswordEncoder` is not going to impact the security of the system since the encoding is always done using the preferred `PasswordEncoder`.

I'm closing this as won't fix as keeping the logic encapsulated is preferred and exposing the Map does not provide any additional security benefits since removing mappings does not improve the security of the passwords.
