### ISSUE TITLE
OpenID Connect single logout support

### ISSUE THREAD

**Issue by skyflyer** [spring-projects/spring-security#5415]
### Summary

[OpenID Connect Session specification](http://openid.net/specs/openid-connect-session-1_0.html#RPLogout) defines RP-Initiated logout, which, upon successful termination of user's session on the RP redirects the end-user (client) to the OP (OpenID Provider).

It would be great if OAuth2 infrastructure dealing with OpenID Connect would be able to support this use case as well.

Additionally, it would be great if configuration of OpenID Connect provider could be done via a single property, specifying only the "well known" configuration endpoint, such as `https://<provider-fqdn>/.well-known/openid-configuration`

### Expected Behavior

To be able to configure the `end-session-uri` property of the `spring.security.oauth2.client.provider` in the `application.yml` (or `application.properties` or through code) and have the appropriate logout handler redirect to that endpoint after the logout.

**Comment by jgrandja** [comment]
@skyflyer This issue has already been logged #5350

**Comment by skyflyer** [comment]
My search fu wasn't working, apparently. Sorry about the duplicate.
