### ISSUE TITLE
Associate Refresh Token to OAuth2AuthorizedClient

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#5416]
If the optional Refresh Token is returned in the Token Response, it should be associated to the `OAuth2AuthorizedClient`. This will enable the `refresh_grant` to be performed when the current Access Token becomes invalid or expires.

**Comment by jgrandja** [comment]
Related #4371

**Comment by zcwang3** [comment]
What's the estimation release time of Spring security 5.1.0 official release?
Or do we have plan to migration this new feature enhancement into 5.0.8?
