### ISSUE TITLE
Document error in 'expression-based.adoc'

### ISSUE THREAD

**Issue by henryL1N** [spring-projects/spring-security#5442]
### Summary
Document error in [/docs/manual/src/docs/asciidoc/_includes/authorization/expression-based.adoc](https://github.com/spring-projects/spring-security/blob/5.1.0.M1/docs/manual/src/docs/asciidoc/_includes/authorization/expression-based.adoc)

Line 38:
```
| Returns `true` if the current principal has any of the supplied roles (given as a comma-separated list of strings)
```
Should be:
```
| Returns `true` if the current principal has any of the supplied authorities (given as a comma-separated list of strings)
```

### Version
5.1.0.M1

**Comment by jzheaux** [comment]
Fixed by 8edd811d0d86bab799f052dc13c6eb78dbbb5484
