### ISSUE TITLE
When I customize an implementation class of the ObjectPostProcessor, there is a conflict.

### ISSUE THREAD

**Issue by jimlgx** [spring-projects/spring-security#5445]
https://github.com/spring-projects/spring-security/blob/71986e5f424ed44c475d21af54a8cf51962b9bdd/config/src/main/java/org/springframework/security/config/annotation/web/configuration/WebSecurityConfigurerAdapter.java#L375

**Comment by eleftherias** [comment]
Hi @jimlgx, could you provide some more information on what you're trying to accomplish?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
