### ISSUE TITLE
Override toString() in all RequestMatcher implementations

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-security#5446]
It would improve Spring Security's diagnostics and make debugging a little easier if all `RequestMatcher` implementations overrode `toString()`. Based on `find . -name "*RequestMatcher.java" | xargs grep -L 'String toString()'`, the following do not currently do so:

- `MvcRequestMatcher`
- `AnyRequestMatcher`
- `ELRequestMatcher`
- `RegexRequestMatcher`

**Comment by rwinch** [comment]
Thanks for the report @wilkinsona! The changes are now pushed to master
