### ISSUE TITLE
Apache Commons File Upload Stream API no longer works with Spring 5

### ISSUE THREAD

**Issue by bamaro1** [spring-projects/spring-security#5456]
### Summary

Apache Commons File Upload Stream API no longer works with Spring 5

### Actual Behavior

When posting a multipart file to a Spring 5 rest endpoint, Apache Commons File Upload is not able to retrieve any FileItemIterators from Spring's HttpServletRequest. 

### Expected Behavior

A FileItemIterator should be returned when posting a multipart file to a Spring 5 REST endpoint.

### Configuration

Only configuration item: 
spring.http.multipart.enabled=false

### Version

This works perfectly in Spring 4 (Springboot 1.5.14-RELEASE) but breaks in Spring 5 (Springboot 2.0.3-RELEASE).

### Sample

Sample project attached
[sample.zip](https://github.com/spring-projects/spring-security/files/2134534/sample.zip)

**Comment by DarkTeToN** [comment]
> Only configuration item:
> spring.http.multipart.enabled=false

You should try with this one:
spring.**servlet**.multipart.enabled=false

**Comment by rwinch** [comment]
I'm closing this as invalid because it is not a Spring Security issue. If others are having this issue, please report to Spring Framework at https://github.com/spring-projects/spring-framework/issues
