### ISSUE TITLE
Created exception is not throwing

### ISSUE THREAD

**Issue by milovtim** [spring-projects/spring-security#5462]
### Summary
Exception object was created but not throwing (and not used later).

### Actual Behavior
It some sort of *programmer's typo*: create exception object and forget it

### Expected Behavior
An exception must propagate to caller in order DigestAuthenticationFilter to work properly

### Configuration
No configuration required -- it's obvious code-level mistake.

### Version
Found in latest 5.1.0.M1. Still exists in earlier versions and in master for the moment issue was created.

### Sample
[link to line in class](https://github.com/spring-projects/spring-security/blob/a1c93b1cce804072f34bc54f7c9aef5b736a1793/web/src/main/java/org/springframework/security/web/authentication/www/DigestAuthenticationFilter.java#L433)

**Comment by ThomasVitale** [comment]
I'd like to fix this issue
