### ISSUE TITLE
Ditch the "ROLE_" prefix an use type-safe objects instead

### ISSUE THREAD

**Issue by HerrDerb** [spring-projects/spring-security#5468]
Spring-security is tightly coupled on roles for authorization. 

**Currently**
The characteristic of a role is the "ROLE_" prefix. Meaning the type of  `GrantedAuthority` is only defined through it's `authority` string which needs to be parsed.
The method security annotation is used this way: `@Secured("ROLE_admin)` which leads to a `SecurityConfig` which again is only defined through it's `attrib` string which needs to be parsed. Even the generic `SimpleGrantedAuthority` has a string member named `role`, which introduces an unnecessary context.

**Desired**
A type save object `Role extends GrantedAuthority` is used. The "ROLE_" prefix is only used for external inputs. Inside of the spring-security ecosystem we only handle `Role` objects and elimintate the "ROLE_" prefix.
A `@HasRole` annotation exists that is used this way: `@HasRole("admin")` which leads to a `RoleConfigAttribute` which, again, is type-safe.

**Benefits** 
Eliminate type-unsafe string characteristics which are prone to errors.
This uncouples the whole role based system, allows better integration for a permission based system (which equivalent would have a `Permission extends GrantedAuthority` object and a `@HasPermission` annotation) and event makes it possible to easily combine the both of it if necessary.

**Comment by rwinch** [comment]
Thank you for the feedback

> Spring-security is tightly coupled on roles for authorization.

This is not true. Authorization can be performed on any type of authority.

We cannot switch to relying on the type because  [GrantedAuthority.getAuthority](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/core/GrantedAuthority.html#getAuthority--) must be unique:

> If the GrantedAuthority can be represented as a String and that String is sufficient in precision to be relied upon for an access control decision by an AccessDecisionManager (or delegate), this method should return such a String.
