### ISSUE TITLE
Provide more control for setting the Strict-Transport-Security header

### ISSUE THREAD

**Issue by mahanhz** [spring-projects/spring-security#5471]
**StrictTransportSecurityServerHttpHeadersWriter** sets the **Strict-Transport-Security** header if it detects that the scheme is **https**.

This approach prevents the header being set when the configuration consists of SSL Termination at the load balancer.

Could this be adjusted so that we can set this value ourselves?

Also in **ServerHttpSecurity.HeaderSpec.HstsSpec** methods **maxAge()** and **includeSubdomains()** return void instead of HstsSpec which affects the fluidity of configuration.

**Comment by rwinch** [comment]
Thanks for the report @mahanhz!

> Could this be adjusted so that we can set this value ourselves?

You should setup your server to respond to X-Forwarded headers using something like `ForwardedHeaderFilter`.

> Also in ServerHttpSecurity.HeaderSpec.HstsSpec methods maxAge() and includeSubdomains() return void instead of HstsSpec which affects the fluidity of configuration.

Thanks can you create a separate issue for this? Perhaps you would be interested in submitting a PR?

**Comment by rwinch** [comment]
Closing this since users should setup the server to work behind a proxy server properly.

**Comment by mahanhz** [comment]
Thanks for the info. I'll look into the ForwardedHeaderFilter.

However I still think it is better to give users the flexibility of setting the headers themselves.

**Comment by rwinch** [comment]
The ForwardedHeaderFilter should be used to ensure other things are working properly (i.e. URL construction leveraging the current scheme) anyways.

You can always configure a static header writer if you prefer, but the spec is clear that HSTS should only be set when it is secure.
