### ISSUE TITLE
Provide set of ObjectMapper

### ISSUE THREAD

**Issue by trebouys** [spring-projects/spring-security#5472]
There is no way to instanciate a custom ObjectMapper in JwtAccessTokenConverter. It should be possible to override the default ObjectMapper witch is created by JsonParserFactory.create() by a custom ObjectMapper We need to set our ObjectMapper to encode and decode token (principally due to serializing LocalDateTime). 

It missing a public void setObjectMapper(ObjectMapper mapper) in order to override the default ObjectMapper

**Comment by rwinch** [comment]
Thanks for the report. I moved this issue to the correct repository. Please see https://github.com/spring-projects/spring-security-oauth/issues/1418
