### ISSUE TITLE
Selectively disable csrf by RequestMatcher

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#5477]
`CsrfConfigurer` can already be selectively disabled using ant patterns:

```java
csrf().ignoringAntMatchers("/no-csrf/**")
```

Being able to ignore by a `RequestMatcher` would lend more power to the user as other parts of the request would now become available as well:

```java
csrf().ignoringRequestMatchers(request -> request.getHeader("Authorization") != null)
```

**Comment by chrylis** [comment]
I came here to request this specific feature. Any chance of a backport to 4.3? (As far as I can tell, `CsrfConfigurer` should be able to expose an `ignoringRequestMatchers` there with no API difficulty.)

**Comment by jzheaux** [comment]
Probably not, @chrylis. There are no plans for a 4.3.x series of releases and the 4.2.x series is really just for bug fixes at this point.

You can do this by customizing the csrf filter outside of the DSL, though:

```java
RequestMatcher myMatcher =
    new AndRequestMatcher(
        CsrfFilter.DEFAULT_CSRF_MATCHER, 
        new NegatedRequestMatcher(/* your logic */));
csrfFilter.setRequireCsrfProtectionMatcher(myMatcher);
```
And then either use `addFilter`:

```java
CsrfFilter csrfFilter = new CsrfFilter(...);
// your customizations
http.addFilter(csrfFilter);
```

Or use `withObjectPostProcessor`:

```java
http
    .withObjectPostProcessor(new ObjectPostProcessor<CsrfFilter>() {
        public CsrfFilter postProcess(CsrfFilter csrfFilter) {
            // your customizations
        }
    });
```

**Comment by chrylis** [comment]
My current approach has been to implement a custom matcher

```
.requireCsrfProtectionMatcher(new ExemptOAuthRequiresCsrfMatcher())
```

so it's working, but upgrading to 5 is not an option until authorization is implemented.

**Comment by rwinch** [comment]
Can you clarify what you mean? Is there something Spring Security 5 is missing that is preventing an updated?

> so it's working, but upgrading to 5 is not an option until authorization is implemented.

**Comment by chrylis** [comment]
@rwinch The project in question is an OAuth2 authorization server.

**Comment by rwinch** [comment]
Yes. You are correct. You would need to use the old support for an authorization server at this point.
