### ISSUE TITLE
Add Bearer Token Support to SecurityMockMvcRequestPostProcessor

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#5485]
It's very convenient when testing basic authorization to do this:

```
this.mockMvc(get("/").with(httpBasic("user", "password")));
```

Similar support for bearer tokens:

```
this.mockMvc(get("/").with(bearerToken("token")));
```

Seems reasonable [1].

[1] - https://github.com/jzheaux/spring-security/blob/48cb2e996c0a95755bfffa0018efd148cb09e160/samples/boot/oauth2resourceserver/src/integration-test/java/sample/OAuth2ResourceServerApplicationTests.java#L116

**Comment by rwinch** [comment]
NOTE: We may not need this anymore since HttpHeaders now has setter methods for bearer and basic auth. I think the thing we do need is an easier way to consume the methods on MockMvc which is something we should log to Spring Framework

**Comment by jzheaux** [comment]
Per @rwinch's comment, this is already taken care of via `HttpHeaders`.
