### ISSUE TITLE
OAuth2 ClientRegistration scope can be null / empty

### ISSUE THREAD

**Issue by mhyeon-lee** [spring-projects/spring-security#5494]
### Summary

Allows scope of OAuth2 ClientRegistration to be null.

- The scope setting in the RFC document is defined as Optional.
https://tools.ietf.org/html/rfc6749#section-4.1.1

    > scope:  OPTIONAL.  The scope of the access request as described by Section 3.3.

- When the client omits the scope parameter, validation is determined by the authorization server.
https://tools.ietf.org/html/rfc6749#section-3.3

    > If the client omits the scope parameter when requesting
   authorization, the authorization server MUST either process the
   request using a pre-defined default value or fail the request
   indicating an invalid scope.  The authorization server SHOULD
   document its scope requirements and default value (if defined).

### Actual Behavior

Config ClientRegistration scope is null.

``` java
ClientRegistration.withRegistrationId(REGISTRATION_ID)
			.clientId(CLIENT_ID)
			.clientSecret(CLIENT_SECRET)
			.clientAuthenticationMethod(ClientAuthenticationMethod.BASIC)
			.authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
			.redirectUriTemplate(REDIRECT_URI)
			.scope((String[]) null)
			.authorizationUri(AUTHORIZATION_URI)
			.tokenUri(TOKEN_URI)
			.clientName(CLIENT_NAME)
			.build();
```

### Expected Behavior

Build ClientRegistration  success.

### Version

5.0.6

**Comment by jgrandja** [comment]
@mhyeon-lee Yes, the `scope` is OPTIONAL as per spec. However, it is required based on the **OAuth 2.0 Login** feature. The user needs to specify either `openid` (required) if using an OpenID Connect provider (and any other scopes they may require). Also, if the provider is not OpenID Connect compliant, than the user needs to specify the `scope` required to access the `UserInfo` endpoint.

**Comment by mhyeon-lee** [comment]
@jgrandja 
The following OpenID Connect provider(OidcAuthorizationCodeAuthenticationProvider) checks if `openid` exist in scopes.
So even if it allow nulls for scopes configuration, it will need an "openid" scope when using OpenID Connect.
https://github.com/spring-projects/spring-security/blob/master/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/oidc/authentication/OidcAuthorizationCodeAuthenticationProvider.java#L108

---

If the authorization server of the OAuth2 Login feature does not support scope processing, it may also need an option to handle all the data provided by the authorization server.

**Comment by jgrandja** [comment]
> So even if it allow nulls for scopes configuration, it will need an "openid" scope when using OpenID Connect.

Yes, that is what I'm saying in my previous comment `openid` scope is required when configuring a `ClientRegistration` against an OpenID provider.

I'm not sure I understand your last comment?

**Comment by mhyeon-lee** [comment]
I mean, because OidcAuthorizationCodeAuthenticationProvider checks the "openid" scope, ClientRegistration does not need to restrict scope to the required value.
This is because ClientRegistration's scope can be set to null when not using OpenID.

If oidcAuthenticationProviderEnabled is checked and it is true as below, what if we check "openid" in scopes and allow null otherwise?

``` java
if (oidcAuthenticationProviderEnabled) {
    if (this.scopes == null || !this.scopes.contains(OidcScopes.OPENID)) {
          throw new IllegalArgumentException("....");
    }
}
```

**Comment by jgrandja** [comment]
> This is because ClientRegistration's scope can be set to null when not using OpenID.

This is not true. If the user is configuring the client for a standard OAuth 2.0 Provider they still need to set the scope(s) required that will provide access to the UserInfo endpoint. Have you seen the GitHub or FaceBook [sample](https://github.com/spring-projects/spring-security/tree/5.0.6.RELEASE/samples/boot/oauth2login)?

The bottom line is that `ClientRegistration.scope` **is required**, whether using an OpenID Connect provider or a standard OAuth 2.0 provider (like GitHub or Facebook). If `scope` is not provided than the OAuth 2.0 Login feature will not work.

Also, even though the spec states that `scope` is optional, it doesn't mean the OAuth implementation will make it optional. Whether it being an Authorization Server or Client implementation, the `scope` could be implemented as required for that implementation. This is the case for the OAuth 2.0 Login feature.

I'm curious why you are looking to make `scope` optional. Do you have a specific use case where you are using the OAuth 2.0 Login feature that **does not require** `scope`?

**Comment by mhyeon-lee** [comment]
Yes, I know I need scope for Google or Facebook OAuth2 Login.

I am working with the OAuth2 Authorization Server inside the company where I work.
We are migrating from [spring-security-oauth](https://github.com/spring-projects/spring-security-oauth) to the new oAuth2 client for spring-security.

The Internal Authorization Server does not support the scope parameter.
Since the scope setting of ClientRegistration is a required value, it is setting a meaningless value now.
It still works, so it is okay if this proposal is rejected. However, I made a suggestion that I would like to be closer to the RFC Specification.

---

There is another OAuth2 Login that does not use scope.
https://developers.naver.com/docs/login/api/

I wish you refer to that.
- scope required "N"
- description: No need to send as an internal break value to handle access tolerance
![2018-07-12 3 22 17](https://user-images.githubusercontent.com/5206572/42591850-d79219c6-8582-11e8-96d1-3f5310928fb6.jpg)

**Comment by mhyeon-lee** [comment]
OAuth2 Login services, such as facebook and github, which are the most `open(public)` and used, may require scope to protect information.

However, OAuth2 login for the company's internal information system may not necessarily require scope.

The company internal information system may not necessarily require scope in the following cases:
1. Company internal information system Since the employees can be trusted when providing services, there may be no need for restrictions.
2. You may not need to repeat the check in OAuth2 Login because you have agreed on the contract for the employee information provision scope.

**Comment by jgrandja** [comment]
@mhyeon-lee Even though `scope` is required in order for `oauth2Login()` to work, this is really up to the user to ensure the proper scopes (if any) are configured for the provider they are using.

So we'll stick with the spec and keep `scope` optional. This has been merged to master. Thanks for all your feedback!

**Comment by mhyeon-lee** [comment]
Thank you for your consideration.
