### ISSUE TITLE
Return Type Of RectiveUserDetailService 

### ISSUE THREAD

**Issue by ankurpathak** [spring-projects/spring-security#5503]
package com.ankurpathak.springsessionreactivetest;

import org.springframework.security.core.userdetails.ReactiveUserDetailsService;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import reactor.core.publisher.Mono;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class CustomReactiveUserDetailsService extends ReactiveUserDetailsService {

    public static final String USERNAME_NOT_FOUND_MESSAGE = "Username %s not found.";

    @Override
    public Mono<? extends UserDetails> findByUsername(String username) {
        return users.stream()
                .filter(user -> Objects.equals(username, user.getEmail()) || Objects.equals(username, String.valueOf(user.getId())))
                .findFirst()
                .map(CustomUserDetails::new)
                .map(Mono::just)
                .orElseThrow(() -> new UsernameNotFoundException(String.format(USERNAME_NOT_FOUND_MESSAGE, username)));
    }

    public static final List<User> users = new ArrayList<>();

    static {
        users.add(User.getInstance().id("1").firstName("Ankur").lastName("Pathak").addRole(Role.ROLE_ADMIN).email("ankurpathak@live.in").password("password"));
        users.add(User.getInstance().id("2").firstName("Amar").lastName("Mule").addRole(Role.ROLE_ADMIN).email("amarmule@live.in").password("password"));
    }
}

Return type should be Mono<? extend UserDetail> to allow broader returns by inheritance. In absence of' this we will have to have ugly casting or hack of some type. This will also support the principal
of preferring Composition over Inheritance.

**Comment by ankurpathak** [comment]
In absence of above we have to do some hack of this type:
@Override
    public Mono<UserDetails> findByUsername(String username) {
        return users.stream()
                .filter(user -> Objects.equals(username, user.getEmail()) || Objects.equals(username, String.valueOf(user.getId())))
                .findFirst()
                .map(CustomUserDetails::new)
                .map(x-> (UserDetails)x)
                .map(Mono::just)
                .orElseThrow(() -> new UsernameNotFoundException(String.format(USERNAME_NOT_FOUND_MESSAGE, username)));
    }

**Comment by rwinch** [comment]
Even if we wanted to, we cannot change the code as this is a non passive change. Additionally, it is generally bad practice to return a value with a wildcard since it forces programmers using the code to deal with wildcards. This is the same reason that `Optional.orElseThrow` doesn't use a wildcard.

You can rewrite your code like this:

```java
public Mono<UserDetails> findByUsername(String username) {
	return Flux.fromIterable(users)
			.filter(user -> Objects.equals(username, user.getEmail()) || Objects.equals(username, String.valueOf(user.getId())))
			.next()
			.switchIfEmpty(Mono.defer(() -> Mono.error(new UsernameNotFoundException(String.format(USERNAME_NOT_FOUND_MESSAGE, username)))))
			.map(CustomUserDetails::new);
}
```

You probably want to consider using a different data structure as well since this is O(n) vs a Map which would be O(1).
