### ISSUE TITLE
spring boot 2.0.3 oauth2 google and facebook authentication

### ISSUE THREAD

**Issue by dani-t** [spring-projects/spring-security#5513]
### Summary

spring boot 2.0.3 oauth2 google and facebook authentication

### Expected Behavior

After checking a few resources and the spring security oauth2 docs https://docs.spring.io/spring-security/site/docs/current/reference/html5/#jc-oauth2login I am expecting that all this code will configure the application as an @EnableWebFlux with @EnableWebFluxSecurity and will configure the default ClientRepository with the clients provided in properties file.

They say when you access your app you will get a list with the clients you added. Instead I receive a basic authentication mechanism. Any idea what is happening or am I doing something wrong?

### Configuration

```
compile group: 'org.springframework.boot', name: 'spring-boot-starter-security', version: '2.0.3.RELEASE'
compile group: 'org.springframework.boot', name: 'spring-boot-starter-webflux', version: '2.0.3.RELEASE'
runtime('org.springframework.boot:spring-boot-devtools')
compile group: 'org.springframework.security', name: 'spring-security-config', version: '5.0.6.RELEASE'
compile group: 'org.springframework.security', name: 'spring-security-oauth2-client', version: '5.0.6.RELEASE'
compile group: 'org.springframework.security', name: 'spring-security-oauth2-jose', version: '5.0.6.RELEASE'

@SpringBootApplication
public class App{

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}

spring.security.oauth2.client.registration.google.client-id=x
spring.security.oauth2.client.registration.google.client-secret=y
spring.security.oauth2.client.registration.facebook.client-id=x
spring.security.oauth2.client.registration.facebook.client-secret=y
```

### Version

2.0.3

**Comment by jgrandja** [comment]
@dani-t WebFlux support for `oauth2Login()` was added added recently. Have you seen this [sample](https://github.com/spring-projects/spring-security/tree/master/samples/boot/oauth2login-webflux)?

**Comment by jgrandja** [comment]
I just found out that Boot has added the auto-configuration support to 2.1.M1. See this [issue](https://github.com/spring-projects/spring-boot/issues/13142)

**Comment by hartmut-co-uk** [comment]
Hi, I'm just experimenting with `2.1.0.BUILD-SNAPSHOT`.
With the new auto-configuration (amazing by the way) - if I'd like to have different routes from e.g.
`/oauth2/authorization/github`
 `/login/oauth2/code/github`
Where / how would I be able to overwrite that configuration?

**Comment by hartmut-co-uk** [comment]
have struggled a bit to get it working with the current SNAPSHOT version.
Had to add following both dependencies:
```
compile "org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure:2.0.1.RELEASE"
compile "org.springframework.security:spring-security-oauth2-client"
```

By the way the `OAuth2LoginSpec` is missing `and()` for chaining...
`public ServerHttpSecurity and() { return ServerHttpSecurity.this; }`

**Comment by hartmut-co-uk** [comment]
done, https://github.com/spring-projects/spring-security/issues/5598

**Comment by jgrandja** [comment]
@dani-t Have you tried this with Boot 2.1.M1?  The M1 release includes the auto-configuration support for WebFlux `oauth2Login()`.

I'd appreciate if you could close this issue after you have confirmed that it works (as it should) with  Boot 2.1.M1

**Comment by jgrandja** [comment]
@dani-t I'm going to close this issue due to lack of feedback. If you are still having an issue than we can re-open.
