### ISSUE TITLE
Support configurable OAuth2AuthorizationRequestResolver

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#5521]
We need to allow the capability for the user to configure an `OAuth2AuthorizationRequestResolver` via `http.oauth2Login().authorizationEndpoint().authorizationRequestResolver(resolver)` as well as `http.oauth2().client().authorizationCodeGrant().authorizationRequestResolver(resolver)`.

Related #4911

**Comment by zcwang3** [comment]
We are working for a project with 5.0.7, and find that we need this improvement for some specific feature requirement.

What's the estimation release time of Spring security 5.1.0 official release?
Or do we have plan to migration this new feature enhancement into 5.0.8?

**Comment by zcwang3** [comment]
got it.
Thanks very much.
