### ISSUE TITLE
Support OAuth2 UsernameExtractor in ProviderDetails.UserInfoEndpoint

### ISSUE THREAD

**Issue by mhyeon-lee** [spring-projects/spring-security#5526]
### Summary

Sometimes it is difficult to extract the `username` with only the `userNameAttributeName` of UserInfoEndpoint.

I know that it supports CustomUserType to handle complex user responses. 
[31.5.2 Configuring a Custom OAuth2User](https://docs.spring.io/spring-security/site/docs/5.0.6.RELEASE/reference/htmlsingle/#oauth2login-advanced-custom-user)

However, it would be nice if you could simply provide a way to easily extract username in DefaultOAuth2User.

* Use-Case

1. userInfo In response, extract the address from email and use it as username.
    > mhyeon.lee@navercorp.com  -> extract: mhyeon.lee

2. Some 3rd party UserInfo provider respond to nested structures. 
It is difficult to extract with 1 depth usernameAttributeKey.
``` json
{
  "resultcode": "00",
  "message": "success",
  "response": {
    "email": "openapi@naver.com",
    "nickname": "OpenAPI",
    "profile_image": "https://ssl.pstatic.net/static/pwe/address/nodata_33x33.gif",
    "age": "40-49",
    "gender": "F",
    "id": "32742776",
    "name": "Open API",
    "birthday": "10-01"
  }
}
```

Similarly, spring-security-oauth2 provides a PrincipalExtractor.
[PrincipalExtractor in spring-security-oauth2](https://github.com/spring-projects/spring-security-oauth2-boot/blob/master/spring-security-oauth2-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/UserInfoTokenServices.java#L117)

### Sample

``` java
public class DefaultOAuth2User implements OAuth2User, Serializable {
    private final String nameAttributeKey;
    private final UsernameExtractor nameExtractor;

    @Override
    public String getName() {
	// return  this.getAttributes().get(this.nameAttributeKey).toString();
        Object name = this.getAttributes().get(this.nameAttributeKey);
        return this.nameExtractor.extract(name);
    }

```

**Comment by jgrandja** [comment]
Thanks for the feedback @mhyeon-lee.

> Some 3rd party UserInfo provider respond to nested structures.
It is difficult to extract with 1 depth usernameAttributeKey

Yes agreed but what I was thinking is that `nameAttributeKey` could be a nested path and the implementation would support this via an enhancement to `ClaimAccessor`, for example, `ClaimAccessor.getClaimAsString(nestedPath)` or something similar.

Your suggested `UsernameExtractor` is another idea to account for.

It is difficult to account for all the different possible structures that a token can have. I do feel this is a need but it will require some further thought. Any other ideas are appreciated?

**Comment by mhyeon-lee** [comment]
@jgrandja 
I have suggested two requirements, one of which is complex response structure processing, which is possible if nestedPath is supported.

However, The remaining proposal, value extraction problem, needs to be solved.

You may be aware of the problem, but I will write some more about the value extraction requirements.
Since the username of the Authentication can be a meaningful identifier of the client service, there can be various restrictions.

For example, a use case might have the following requirements:
1. I want to extract the username from the email address.  (e.g. loginId / mention ... )
   >  email: mhyeon.lee@navercorp.com   ->  username:  mhyeon.lee
2. To prevent duplicate usernames from occurring in different case, use username only in lower case.
   > MHYEON.LEE,  Mhyeon.lee, mhyeon.LEE ->  mhyeon.lee
3. Because of the limitation of client service, username can not contain dot(.), so it is replaced with dash(-).
    >  mhyeon.lee -> mhyeon-lee


It would be nice to be able to implement the provided interface and register it as a bean, or set it in JavaConfig to transform the desired username.

**Comment by jgrandja** [comment]
@mhyeon-lee 

> The remaining proposal, value extraction problem, needs to be solved.

Have you considered using a delegation-based strategy to solve this for your use case?

See this [sample](https://docs.spring.io/spring-security/site/docs/5.0.6.RELEASE/reference/htmlsingle/#oauth2login-advanced-map-authorities-oauth2userservice)

The sample is based around custom authorities mapping, however, you can use this same pattern to extract anything from the userInfo attributes and modify/transform and ultimately return a new instance of `OidcUser` or `OAuth2User`.

Would this work for your use case?

**Comment by jgrandja** [comment]
@mhyeon-lee Yes, that's exactly how to do it. Great work! 
I'm glad we found a solution for you. I'll close this issue as you suggested.
