### ISSUE TITLE
Move OAuth2BodyExtractors.oauth2AccessTokenResponse()

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#5528]
`OAuth2BodyExtractors.oauth2AccessTokenResponse()` currently lives in the `oauth2-core` module, however, the `BodyExtractor` of an `OAuth2AccessTokenResponse` would only ever be used by an  OAuth Client.

We should move this method (or class) to the `oauth2-client` module.

**Comment by rwinch** [comment]
I think it makes sense to have it live in the same jar as `OAuth2AccessTokenResponse`

**Comment by jgrandja** [comment]
`NimbusReactiveAuthorizationCodeTokenResponseClient` uses `OAuth2BodyExtractors.oauth2AccessTokenResponse()` which is all part of client functionality.

Do you foresee `OAuth2BodyExtractors.oauth2AccessTokenResponse()` being used outside of an OAuth client?

**Comment by rwinch** [comment]
I don't see any reason to move it. It does not require any new dependencies, so keeping it closer to `OAuth2AccessTokenResponse` makes more sense to me.

**Comment by jgrandja** [comment]
I don't foresee `OAuth2BodyExtractors.oauth2AccessTokenResponse()` being used outside of an OAuth client, hence my reasoning on it being moved.

**Comment by rwinch** [comment]
Why is OAuth2AccessTokenResponse in oauth2 core?

**Comment by jgrandja** [comment]
The Authorization Server will create `OAuth2AccessTokenResponse` and return it to the client.

**Comment by rwinch** [comment]
I can see users with authorization servers needing to test the response and wanting to use this.

**Comment by jgrandja** [comment]
> I can see users with authorization servers needing to test the response and wanting to use this.

This make sense. Closing this.
