### ISSUE TITLE
Favor ApplicationContext#getBean

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#5538]
A couple of the OAuth2 configurer classes use

```java
Map<String, T> : BeanFactoryUtils#beansOfTypeIncludingAncestors(ApplicationContext, Class<T>)
```
to retrieve the desired bean from the application context. In most cases, the code subsequently selects a single item from the map or errors if the map has more than one entry.

`ApplicationContext#getBean(Class<T>)` may suffice for this behavior.

Typically, `beansOfTypeIncludingAncestors` can be a way to get beans lazily, as `AuthenticationConfiguration` does. Or it is a way to fully customize the resolution logic when more than one of the same type is a legitimate use case.

If the OAuth2 configurer code wants to eagerly pull these values, then calling `getBean` may prove less code, especially in circumstances where the code is throwing an error when there are duplicate beans:

```java
Map<String, ClientRegistrationRepository> clientRegistrationRepositoryMap = BeanFactoryUtils.beansOfTypeIncludingAncestors(
		builder.getSharedObject(ApplicationContext.class), ClientRegistrationRepository.class);
if (clientRegistrationRepositoryMap.isEmpty()) {
	throw new NoSuchBeanDefinitionException(ClientRegistrationRepository.class);
} else if (clientRegistrationRepositoryMap.size() > 1) {
	throw new NoUniqueBeanDefinitionException(ClientRegistrationRepository.class, clientRegistrationRepositoryMap.size(),
			"Expected single matching bean of type '" + ClientRegistrationRepository.class.getName() + "' but found " +
					clientRegistrationRepositoryMap.size() + ": " + StringUtils.collectionToCommaDelimitedString(clientRegistrationRepositoryMap.keySet()));
}
return clientRegistrationRepositoryMap.values().iterator().next();
```
could be reduced to

```java
builder.getSharedObject(ApplicationContext.class)
		.getBean(ClientRegistrationRepository.class);
```

**Comment by jgrandja** [comment]
@jzheaux I'm not sure why I had that extra logic for getting `ClientRegistrationRepository` `@Bean` as I'm aware that `context.getBean()` would do the same thing. Maybe it was left over code? Either way, thanks for catching that!
