### ISSUE TITLE
Default login page is not rendered correctly when using SSL

### ISSUE THREAD

**Issue by georgmittendorfer** [spring-projects/spring-security#5539]
### Summary

When using SSL and accessing the spring security default login page via https it is not rendered correctly as one of the stylesheets is not used.

The reason for this is that this stylesheet is linked via a http link. Changing that to https fixes the issue for me.

The code for the login page seems to be hardcoded/generated in org.springframework.security.web.server.ui.LoginPageGeneratingWebFilter#createPage

Currently generated link:

    <link href="http://getbootstrap.com/docs/4.0/examples/signin/signin.css" rel="stylesheet" crossorigin="anonymous">

Possible fix:

    <link href="https://getbootstrap.com/docs/4.0/examples/signin/signin.css" rel="stylesheet" crossorigin="anonymous">​ 

### Actual Behavior

Login page not rendered correctly if using ssl/https.

### Expected Behavior

Login page should be rendered correctly.

### Configuration

N/A

### Version

5.0.6

### Sample

See https://iri.trytes.eu (url might only be temporarily available with this bug).

**Comment by rwinch** [comment]
Thanks for the report. This is now fixed in master
