### ISSUE TITLE
Add support for getting end_session_endpoint from OIDC Configuration

### ISSUE THREAD

**Issue by mraible** [spring-projects/spring-security#5540]
### Summary

Okta has an `end_session_endpoint` property that can be used to construct a global logout that happens on the client. Example code [https://developer.okta.com/blog/2018/06/18/spring-boot-angular-auth-code-flow#logout-with-okta](here). 

It would be nice if Spring Security's OIDC support provided a way to access this `end_session_endpoint`. This property is present in [`./well-known/openid-configuration`](https://dev-669532.oktapreview.com/oauth2/default/.well-known/openid-configuration).

### Version

5.1.0.BUILD-SNAPSHOT

### Sample

https://github.com/oktadeveloper/okta-spring-boot-react-crud-example/compare/spring-security-5.1

**Comment by jgrandja** [comment]
Related #5350

**Comment by jgrandja** [comment]
@mraible Thanks for the report!

There currently is OpenID Connect Discovery code in `OidcConfigurationProvider`. One of our tasks is to extract that bit of code so it can be re-used in other places within Spring Security.

We'll get this in for 5.1

**Comment by jgrandja** [comment]
@mraible This is now available via 057587e.

To access `end_session_endpoint` do this:

`ClientRegistration.getProviderDetails().getConfigurationMetadata().get("end_session_endpoint")`

**Comment by mraible** [comment]
@jgrandja Is it possible to inject the `ClientRegistration` into a RestController? It doesn't seem like it.

**Comment by rwinch** [comment]
@mraible You can pass in the `ClientRegistrationRepository` and look it up. 

```java
@Autowired
public void setClientRegistrationRepository(ClientRegistrationRepository registrations) {
    this.registration = registrations.findByRegistrationId("okta");
}
```

Alternatively you could use `SpeL` to get the `ClientRegistration` itself. 

```java
public void setClientRegistration(
    @Value("#{@clientRegistrationRepository.findByRegistrationId('okta')}") ClientRegistration clientRegistration) {
    this.registration = clientRegistration;
}
```
