### ISSUE TITLE
Improve Error Message for OIDC with incorrect client id / secret

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#5541]
### Summary

Right now the error message for incorrect client id / secret propagates  as an AuthenticationException while it should fail with a 500. The error message is `[invalid_token_response] An error occurred parsing the Access Token response: Missing JSON object member with key "token_type"` which is not informative

**Comment by jgrandja** [comment]
@rwinch I wasn't able to reproduce the same error message. I changed my google client to have an invalid secret and the error produced was `[invalid_client] Unauthorized` and 401 status.

Can you please expand on the scenario on how that error was produced.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
