### ISSUE TITLE
Add state attribute generator to ClientRegistration

### ISSUE THREAD

**Issue by avskor** [spring-projects/spring-security#5542]
### Summary

Add state attribute generator to `ClientRegistration`. Our authorization server required base64 encoded UUID as state attribute

**Comment by jgrandja** [comment]
@avskor We've recently added `OAuth2AuthorizationRequestResolver` which you can use to override `OAuth2AuthorizationRequest.state` and set your own generated `state`.

Here are a couple of tests that demonstrate the overriding of value(s) in the `OAuth2AuthorizationRequest`:

[OAuth2ClientConfigurerTests](https://github.com/spring-projects/spring-security/blob/master/config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2ClientConfigurerTests.java#L184)

[OAuth2AuthorizationRequestRedirectFilterTests](https://github.com/spring-projects/spring-security/blob/master/oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/web/OAuth2AuthorizationRequestRedirectFilterTests.java#L306)

Sample code

```java
OAuth2AuthorizationRequest.from(defaultAuthorizationRequest)
	.state("your-generated-state")
	.build();
```

I'm going to close this issue as I feel I've provided you a solution to your use case. If you have any other questions we can re-open if necessary.
