### ISSUE TITLE
Create OpenID Connect Discovery Client

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#5543]
Create OpenID Connect Discovery Client which is capable of requesting [Provider Metadata](http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata) via the supplied `issuer`.

Related #5523, #5540, #5350

**NOTE:** There is existing logic for OpenID Connect Discovery in `OidcConfigurationProvider`. We should extract this logic to allow for re-use in Client and Resource Server.

**Comment by jgrandja** [comment]
We're going to hold off on this feature for 5.1. This [branch](https://github.com/jgrandja/spring-security/tree/gh-5543-discovery-client) contains this feature and we'll consider adding it in a later release.

**Comment by pthorson** [comment]
Note: `OidcConfigurationProvider` moved to `ClientRegistrations` in https://github.com/spring-projects/spring-security/commit/742716fae3695317f4587ca41b91710ebce40a56

**Comment by jgrandja** [comment]
Closing as this is not needed at the moment.

**Comment by nevmerzhitsky** [comment]
Sorry, why did you not include the OpenID Connect Discovery Client to the library? There is an automated way to take `jwks_uri` key from the URLs like `oauth2/.well-known/openid-configuration` by the lib to pass it into `createRemoteJWKSet()`?
