### ISSUE TITLE
Hello Spring Security instructions in the docs do not work

### ISSUE THREAD

**Issue by Kallaste** [spring-projects/spring-security#5549]
I am just learning Spring and Spring Security and was attempting to follow the instructions in the docs here: [link](https://docs.spring.io/spring-security/site/docs/5.0.6.RELEASE/guides/html5/helloworld-javaconfig.html).

It says to import the sample application by doing the following:

> Start STS and import the sample application into STS using the following steps:
> 
>     File→Import
>     Existing Maven Projects
>     Click Next >
>     Click Browse…​
>     Navigate to the samples (i.e. SPRING_SECURITY_HOME/samples/xml/insecure) and click OK
>     Click Finish

This doesn't work. I downloaded the sample code, but when I try to import it, it is not recognized as a Maven project. There is no pom file in the SPRING_SECURITY_HOME/samples/xml/insecure directory. There is a Gradle file.

Do I need to install Gradle and use that instead? I think there should be a version that works with Maven, ideally. Does it exist somewhere else? 

Edit: I created a pom for the application based on the Gradle file, and the project runs. I am having a lot of problems related to dependency versioning, however, and still have not been able to get through the basic hello world example. Accurate instructions in the docs and a working pom would be helpful.

Edit 7 days later: Well, it has been a week, and I think I may not get a response to this thread. I actually I did work through the example several days ago, I just wanted to mention that many parts of the instructions are totally wrong. Really almost everything is wrong. The code you end up with if you follow the guide is not even the same as the working code in the linked source folder. (You can see both the guide and its supposed source here: https://docs.spring.io/spring-security/site/docs/5.0.6.RELEASE/reference/htmlsingle/ . The source is different than what is listed in the guide.)

You might want to either correct your docs or remove these guides entirely. Incorrect instructions and no support is sometimes worse than no instructions at all.

**Comment by pthorson** [comment]
Yes, there is an existing issue related to the project now using Gradle and these guides mention of maven (and STS for that matter).

In the interim, I would suggest that the now 3 year old guides mention that they are outdated and also not reference the latest security release. The fact that these show up under current with refs to 5.1.1 RELEASE makes understanding spring security more difficult than necessary.

**Comment by rwinch** [comment]
Thanks this is a duplicate of #5026 However, we are rewriting the entire reference in #2567

Closing in favor of #5026
