### ISSUE TITLE
Please explain in the docs that in order to use `org.springframework.security.data.repository.query.SecurityEvaluationContextExtension` you need `org.springframework.security` :  `spring-security-data`

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-security#5556]
Please explain in the docs that in order to use `org.springframework.security.data.repository.query.SecurityEvaluationContextExtension` you need `org.springframework.security` :  `spring-security-data`. It's not clear from reading the section [on accessing the `java.security.Principal` from SpEL](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#data) that you need to add the `spring-security-data` library to the classpath.

**Comment by rwinch** [comment]
@joshlong Thanks for the suggestion. Would you like to send a PR?
