### ISSUE TITLE
[Question] How to register custom AuthenticationProvider in reactive programming model

### ISSUE THREAD

**Issue by kkocel** [spring-projects/spring-security#5565]
I'm trying to register my own `AuthenticationProvider`. 

My config:
```kotlin
@EnableWebFluxSecurity
class SecurityConfig {

  @Bean
  fun customAuthenticationProvider(): CustomAuthenticationProvider {
    return CustomAuthenticationProvider()
  }

  @Bean
  fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http.authorizeExchange()
        .anyExchange().authenticated()
        .and().build()
  }
}
```

But since I use webflux I cannot use `WebSecurityConfigurerAdapter`.

What is correct way to enable such  `AuthenticationProvider`?

**Comment by kkocel** [comment]
@rwinch @rstoyanchev Hey guys maybe you can help me out with this?

**Comment by rwinch** [comment]
Reactive Spring Security does not use an AuthenticationProvider. You can create a Bean of type `ReactiveAuthenticationManager` instead.

**Comment by d3btech** [comment]
@rwinch If I provide a custom `AuthenticationManager` do I need to provided a `ReactiveUserDetailsService` ? In my use case I purposely do not want to provide a `ReactiveUserDetailsService`. Please suggest.
