### ISSUE TITLE
Consider renaming OidcConfigurationProvider

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#5584]
We should consider renaming `OidcConfigurationProvider` to `OidcProviderConfiguration` to align more closely to the spec -> [OpenID Provider Configuration](http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig)

**Comment by rwinch** [comment]
or even something that includes ClientRegistration in it too

**Comment by jgrandja** [comment]
Resolved via 742716f
