### ISSUE TITLE
NimbusAuthorizationCodeTokenResponseClient: IllegalArgumentException: errorCode cannot be empty

### ISSUE THREAD

**Issue by jbiblio** [spring-projects/spring-security#5594]
### Summary
If exchanging authorization code against access_token by `NimbusAuthorizationCodeTokenResponseClient` fails, and response from provider does not contain "error" attribute, the authorization fails with an unspecific `IllegalArgumentException`.

### Actual Behavior
We've tried to authorize against Facebook. I'm not sure what went wrong, yet, but I've got an `IAE` here:

    ERROR (ajp task-72:) [io.undertow.request] UT005023: Exception handling request to /oauth/login/oauth2/code/FACEBOOK_xVJohUEMdcwEFCQwtKdr1wMg: 
    java.lang.IllegalArgumentException: errorCode cannot be empty
        at org.springframework.util.Assert.hasText(Assert.java:276)
        at org.springframework.security.oauth2.core.OAuth2Error.<init>(OAuth2Error.java:60)
        at 
     org.springframework.security.oauth2.client.endpoint.NimbusAuthorizationCodeTokenResponseClient.getTokenResponse(NimbusAuthorizationCodeTokenResponseClient.java:115)
        at 
  
  org.springframework.security.oauth2.client.endpoint.NimbusAuthorizationCodeTokenResponseClient.getTokenResponse(NimbusAuthorizationCodeTokenResponseClient.java:67)
        at 
  
  org.springframework.security.oauth2.client.authentication.OAuth2LoginAuthenticationProvider.authenticate(OAuth2LoginAuthenticationProvider.java:121)

There's a null-check in `com.nimbusds.oauth2.sdk.ErrorObject.parse(JSONObject)`, resulting in an invalid `OAuth2Error` object.

### Expected Behavior
A more robust error handling would be nice. I'll try to reproduce on Monday, but nonetheless the framework could be a little more robust in such error cases, e.g. don't insist on presence of certain parameters, or log the issue if an expectation fails.

### Version
spring-security-oauth2-client-5.0.3,
oauth2-oidc-sdk-5.54,

**Comment by jgrandja** [comment]
Thanks for the report @jbiblio. This fix is now in master.
