### ISSUE TITLE
Add Support for Rememberme with OAuth2 Login

### ISSUE THREAD

**Issue by asaikali** [spring-projects/spring-security#5597]
I would like to use the spring security remember me features with OAuth2 Login.

**Comment by rwinch** [comment]
Can you elaborate on what is preventing this from working now?

**Comment by asaikali** [comment]
was chatting with @jgrandja and he wanted to write some samples / tests to verify this all still works. Opened the ticket at his request.

**Comment by rwinch** [comment]
I spoke with Joe and he said this was a reminder for himself more than anything. The remember me support makes more sense on the authorization server for SSO scenarios like this. For that reason, I'm going to close this.
