### ISSUE TITLE
`spring-security-oauth2-client` Severe NullPointerException Leaving the Session in Invalid/Broken State

### ISSUE THREAD

**Issue by hartmut-co-uk** [spring-projects/spring-security#5599]
### Summary
With Spring Security OAuth2 - A NPE on `removedValue` leaves the session in a invalid/broken state:
https://github.com/spring-projects/spring-security/blob/bc3467c11810ffc4649653ae426c0e911470c0d0/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/WebSessionOAuth2ReactiveAuthorizationRequestRepository.java#L83-L87

### Actual Behavior
A _failed_ oauth2 authorization code grant login attempt the stored state / oauth2 code produces following NPE:
```
java.lang.NullPointerException: data
	at java.util.Objects.requireNonNull(Objects.java:228) ~[na:1.8.0_172]
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.next(FluxHandleFuseable.java:416) ~[reactor-core-3.2.0.M3.jar:3.2.0.M3]
	at org.springframework.security.oauth2.client.web.WebSessionOAuth2ReactiveAuthorizationRequestRepository.lambda$removeAuthorizationRequest$3(WebSessionOAuth2ReactiveAuthorizationRequestRepository.java:87) ~[spring-security-oauth2-client-5.1.0.M2.jar:5.1.0.M2]
```

...therefore leaving the session in a broken state - any request but logout seems to result in a 500 due to the NPE.
Only after manual logout / session cookie deleted client-side - requests can be served again.

### Expected Behavior
`WebSessionOAuth2ReactiveAuthorizationRequestRepository .removeAuthorizationRequest` null safe
\+ clear invalid state/session?!? (resulting in 401? / redirect to login to try again..?)

### Configuration
nothing specific

### Version
spring-security-oauth2-client:5.1.0.M2

### Sample
Slightly tricky to reproduce - was testing with adding twitter oauth - where I experienced the failed oauth redirect - anyway I think the source code itself can be be refactored to be null safe without a sample? Can try to produce something if required. Please let me know!

**Comment by rwinch** [comment]
Thanks for the report! I believe this is enough information.

**Comment by rwinch** [comment]
Thanks again for the report! This is now fixed in master
