### ISSUE TITLE
OAuth2 support and spring-security-oauth2

### ISSUE THREAD

**Issue by heruan** [spring-projects/spring-security#5606]
I've read [this announcement](https://spring.io/blog/2018/07/30/spring-security-5-1-0-m2-released) which points here to give feedback.

I'm excited to see OAuth2 support coming in Spring Security core, but how this relates to [`spring-security-oauth2`](https://github.com/spring-projects/spring-security-oauth)?

A quick glimpse at it and it seems they are two different implementation. Is there a migration guide for those who are using the "old" implementation?

**Comment by heruan** [comment]
Yes, thank you!

It would be useful to add Spring Security 5.1 to the [OAuth 2.0 Features Matrix](https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Features-Matrix) to make it easier to follow feature development in 5.1 and know when to migrate.

**Comment by eleftherias** [comment]
The [OAuth 2.0 Feature Matrix](https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Features-Matrix) has been updated to include Spring Security 5.1, in revision `778da4d`.
We have also created gh-6733 to introduce migration guidance for Spring Security's OAuth 2.0 Support.
Therefore, I am closing this issue.
