### ISSUE TITLE
Broken link at Spring security architecture at spring.io

### ISSUE THREAD

**Issue by trevormarshall** [spring-projects/spring-security#5626]
### Summary

Broken link at Spring security architecture at spring.io

Mistakenly reported at https://jira.spring.io/projects/INFRA/issues/INFRA-21 by Ramon Anger while Trevor was on PTO

### Actual Behavior

Link at https://spring.io/projects/spring-security#learn (bottom of page) returns with a 404 error.

### Expected Behavior

The link should return https://spring.io/guides/topicals/spring-security-architecture/

The correct link is on the https://spring.io/guides#gs page in the "Topical Guides Section" - the "Spring Security Architecture" link to the topical guide is correctly configured as https://spring.io/guides/topicals/spring-security-architecture/, per @leriksen

**Comment by rwinch** [comment]
Thanks for the report. This appears to be a duplicate of https://github.com/spring-io/sagan/issues/844
