### ISSUE TITLE
Security Configuration - frame options overrides authorizeRequests? [helpwanted]

### ISSUE THREAD

**Issue by stefan0001** [spring-projects/spring-security#5630]
### Summary

When using `frameOptions`  together with `authorizeRequests`. The authentication does not work.

### Goal
Secure all paths with basic auth.
Set `SAMEORIGIN` frameOptions for `/foo/**`
### Actual Behavior

When using  `antMatcher` to set the `frameOptions` for special endpoints the `authorizeRequests` gets overriden. Looks like `/foo/**` is protected. But `/bar/**` is not protected. (look at config below)

### Expected Behavior

I tought  `http.authorizeRequests().anyRequest().authenticated();` protects all paths.
So `/bar/**` should also be protected.

### Configuration

Exmaple config:
``` 
@Configuration
@EnableWebSecurity
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests().anyRequest().authenticated();
        http.httpBasic();
        http.formLogin().disable();
        http.csrf().disable();
        http.antMatcher("/foo/**").headers().frameOptions().sameOrigin();
    }
}

```

### Version

Using 
Sping Boot 2.0.3
Spring Cloud Finchley.RELEASE
Spring Security Core 5.0.6

**Comment by eleftherias** [comment]
@stefan0001 by setting `http.antMatcher("/foo/**")` you are setting the security configuration to only be invoked when matching the provided ant pattern `"/foo/**"`.   
Your configuration `.authorizeRequests().anyRequest().authenticated()` will only be invoked on any request that matches `"/foo/**"`.  
It is equivalent to
```
http
    .antMatcher("/foo/**")
        .authorizeRequests()
            .anyRequest().authenticated()
        ...
```
In order set the frame options for just `"/foo/**"`, you can use a second security configuration. You can find an example in the [Multiple HttpSecurity section](https://docs.spring.io/spring-security/site/docs/5.1.5.RELEASE/reference/htmlsingle/#multiple-httpsecurity) of the documentation.
