### ISSUE TITLE
OAuth2LoginAuthenticationProvider uses OAuth2AuthorizationCodeAuthenticationProvider

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#5633]
The `OAuth2LoginAuthenticationProvider` performs most of the same logic that exists in `OAuth2AuthorizationCodeAuthenticationProvider`. We should re-factor to allow for reuse.

**Comment by rwinch** [comment]
Related to this is that OAuth2LoginAuthenticationToken could extend OAuth2AuthorizationCodeAuthenticationToken which seems logical and would allow the existing OAuth2 Log In code to be passive.

**Comment by pdelert** [comment]
@jgrandja @rwinch can I take this enhancement ?

**Comment by jgrandja** [comment]
@pdelert That would be great! Thank you.

**Comment by pdelert** [comment]
@jgrandja here are my small changes, please have a look here #7356

**Comment by rh-id** [comment]
hi @jgrandja , @pdelert . do you mind if i takeover this issue?

**Comment by jgrandja** [comment]
That would be great @rh-id. But let's wait for confirmation from @pdelert as they have an open PR #7356 but I haven't heard back from them in a while. Please wait 1-2 weeks for a confirmation and if we don't hear from them then go ahead with the PR. Thanks!

**Comment by rh-id** [comment]
hi @jgrandja i had created PR #8170
