### ISSUE TITLE
ServerHttpSecurity.oauth2() is missing in Spring Security 5.1.0.M2

### ISSUE THREAD

**Issue by vann586** [spring-projects/spring-security#5658]
### Summary

I believe that the ServerHttpSecurity.java in the Spring Security 5.1.0.M2
included with Spring Boot 2.1.M1 is an older version and it is missing several
methods such as the oauth2 method.

Because of the missing oauth2 method, the oauth2resourceserver-webflux sample
failed to compile.

### Actual Behavior

The SecurityConfig.java failed to compile with the following error:

```java

java: cannot find symbol

symbol: method oauth2()

location: class
org.springframework.security.config.web.server.ServerHttpSecurity

```

### Expected Behavior
The SecurityConfig.java should compile with no errors.

### Version
Spring Security 5.1.0.M2

**Comment by jzheaux** [comment]
Hi, @vann586, thanks for the report.

The sample you are referencing was not added until after M2 was cut [1] [2]. As such, I would not expect it to compile against Spring Boot 2.1.M1.

Can you confirm that you are definitely using 5.1.0.M2?

[1] - https://github.com/spring-projects/spring-security/issues/5605
[2] - https://github.com/spring-projects/spring-security/tree/5.1.0.M2/samples/boot

**Comment by vann586** [comment]
Hi @jzheaux ,
Thanks for quick response. I did verified that I used 5.2.0.M2 as shown in the below image. Can you recommend how I can get the lastest Spring Security lib?

![image](https://user-images.githubusercontent.com/19257387/44038875-c04b0454-9ee5-11e8-8d56-02b0b62f680b.png)

**Comment by jzheaux** [comment]
@vann586 The reactive support you are looking for (resource server, I'm supposing) is slated for RC1, which ships next week if that works for you ([currently slated for the 20th](https://github.com/spring-projects/spring-security/milestone/113)).

The only way to get it right now would be to build from master.

**Comment by vann586** [comment]
@jzheaux , I am fine for waiting for next week release. Thanks.
