### ISSUE TITLE
Broken Link in Sping Project#Learn page

### ISSUE THREAD

**Issue by rhdsmnd** [spring-projects/spring-security#5675]
### Summary

There's a broken link on this [page](https://spring.io/projects/spring-security#learn).

### Actual Behavior

Clicking on the "Spring Security Architecture" guide gets redirected to this [broken link](https://spring.io/guides/gs/spring-security-architecture/).

### Expected Behavior

Clicking on the "Spring Security Architecture" redirects to [this link](https://spring.io/guides/topicals/spring-security-architecture/)

**Comment by rwinch** [comment]
Thanks for the report. This is a duplicate of https://github.com/spring-io/sagan/issues/844
