### ISSUE TITLE
Question: unable to manually authenticate with ReactiveSecurityContextHolder

### ISSUE THREAD

**Issue by somatoko** [spring-projects/spring-security#5692]
Hi everyone, just a simple question.

I'm trying to manually authenticate a user after a successful registration, however after a redirect
to a protected page user gets routed to a login page. If the user uses the login form he can access protected pages, so all configs seems to be ok there. The problem is probably with how the manual authentication is done, that is described below.

```Java
// Inside the handler method
userService
  .registerNewUser(user) // returns Mono<DomainUser>
  .flatMap(u => {
    // ... setup authorities and principal
    Authentication authentication = new UsernamePasswordAuthenticationToken(principal, u.getPassword(), authorities);
    return ReactiveSecurityContextHolder.getContext()
      .doOnSuccess(c -> c.setAuthentication(authentication))
      .subscriberContext(ReactiveSecurityContextHolder.withAuthentication(authentication));
  })
  .thenReturn("redirect:/success");
```
As I understand it, the newly created `SecurityContext` instance isn't saved anywhere, so the `Principal` can't be picked up by the `AuthorizationWebFilter`. What am I missing here?

**Comment by rwinch** [comment]
In Reactive Spring Security you need to ensure that you invoke `WebSessionServerSecurityContextRepository` to save the context in the session.

**Comment by rwinch** [comment]
I'm going to close this as answered since I am pretty sure this is answered. Please feel free to reopen if it does not answer your question
