### ISSUE TITLE
Upgrade to oauth2-oidc-sdk:jar 5.64.4

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-security#5704]
I've reported a [dependency management issue](https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/issues/253/duplicate-dependency-for-java-mail) to the  OAuth 2.0 SDK with OpenID Connect extensions project that got fixed today with a new release coming our way today.

If you can, that would be great to squeeze that upgrade so that the manual exclude for the duplicated jar can be removed in Spring Boot, see https://github.com/spring-projects/spring-boot/issues/14137

(It's not required for Spring Boot 2.1.0 M2 at all but I thought it was worth reporting before your RC1)

**Comment by rwinch** [comment]
Sorry I did not notice this until after we had released this morning. I'm glad it isn't a blocker for Boot at least.

This is now updated in master and will be included in Spring Security 5.1.0.RC2
