### ISSUE TITLE
Flatten ServerHttpSecurity.oauth2()

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#5712]
We should remove ServerHttpSecurity.oauth2() in favor of oauth2 prefix. For example, ServerHttpSecurity.oauth2().client() becomes ServerHttpSecurity.oauth2Client().

This has some benefits:
* reduces indentation for users
* there really isn't any shared configuration between the code under oauth2 so it isn't required to be in a hierarchy 
* oauth2Login is currently confusing. It makes sense there since there is formLogin but it also makes sense associated with oauth2.

**Comment by jgrandja** [comment]
Related #5715
