### ISSUE TITLE
SEC-308: Lookup of headers in SavedRequestAwareWrapper is not case insensitive

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#572]
["John Hampton":https://jira.spring.io/secure/ViewProfile.jspa?name=jhampton](Migrated from ["SEC-308":https://jira.spring.io/browse/SEC-308?redirect=false]) said:

According to the servlet spec, lookups using HttpServletRequest.getHeader and getHeaders should be case insensitive.  The current implementation of SavedRequest uses a HashMap to store saved headers.  The result is that the lookup of headers by name is case sensitive when SavedRequestAwareWrapper delegates to a SavedRequest.

We use a library that relies on the User-Agent header for rendering.  We experienced problems with rendering on the first page after login.  After debugging we found that the library was not able to get the correct value for the User-Agent due to the case sensitivity of the SavedRequest implementation.  I am attaching a patch that fixes this problem.  The patch is against the 1.0.1 tag.

After redirect after login:
request.getHeader("User-Agent") returns null;
request.getHeader("user-agent") returns the correct value;

Normal Request:
request.getHeader("User-Agent") returns the correct value;
request.getHeader("user-agent") returns the correct value;

**Comment by spring-issuemaster** [comment]
This issue duplicates #577
