### ISSUE TITLE
HttpSession returned null object for SPRING_SECURITY_CONTEXT

### ISSUE THREAD

**Issue by 7000014349** [spring-projects/spring-security#5732]
1.Question Description：
We use Spring-security-saml2 and Azure Active Directory to do the Authentication,when I send a saml request,the response is too slow(a few minutes),the error information in the Log is as followings:
2.Log Information:
[App-Log.zip](https://github.com/spring-projects/spring-security/files/2317548/App-Log.zip)

3.the spring-security.xml file:

[spring-security.zip](https://github.com/spring-projects/spring-security/files/2317499/spring-security.zip)

4. The Version of Spring pakage:
The spring-security-saml2-core :1.0.0
The Spring-web:4.1.6
The Spring-security-core:3.2.7
The Spring-security-web:3.2.7

what is the reason of this situation?
From the log,I think the it has some problem in getting session information
Is there another way to manage session ,maybe not use Spring-security session

**Comment by rwinch** [comment]
@7000014349 Please use https://github.com/spring-projects/spring-security-saml for SAML issues/enhancements and [StackOverflow with the spring-security](https://stackoverflow.com/questions/tagged/spring-security) tag for questions.
