### ISSUE TITLE
invalid_redirect_uri_parameter with OAuth2 client 5.0.7 on Weblogic 12

### ISSUE THREAD

**Issue by gillius** [spring-projects/spring-security#5756]
### Summary

Using spring-security-oauth2-client-5.0.7 with a custom OAuth2 Provider, in some configurations of Weblogic, the redirect URI matching is not generating the same URL on both sides and an error invalid_redirect_uri_parameter is returned. This might occur only when using standard ports. This occurred when running behind a load balancer so the server was running on a separate port.

### Actual Behavior

The method `org.springframework.security.oauth2.client.web.OAuth2AuthorizationRequestRedirectFilter#expandRedirectUri` has special code that if the scheme is https and port is 443, then drop the port from the baseUrl, resulting in a redirectUri such as `https://server.example.com/login/oauth2/code/reg`.

The method `org.springframework.security.oauth2.client.web.OAuth2LoginAuthenticationFilter#convert` uses `request.getRequestURL().toString()` to obtain the URI from the HttpServletRequest. However, the port 443 was appended to the URL, such as `https://server.example.com:443/login/oauth2/code/reg`.

Because the two URIs do not compare with equals method, Spring Security rejects the authentication at OidcAuthorizationCodeAuthenticationProvider.java line 134:

`if (!authorizationResponse.getRedirectUri().equals(authorizationRequest.getRedirectUri()))`

Overriding the value of redirectUriTemplate in ClientRegistration is expected to resolve the issue.

### Expected Behavior

Spring Security should not be so sensitive to formatting differences of the URI from the servlet implementation.

### Version

Spring Security 5.0.7, Spring 5.0.8, Weblogic 12.2.1.1.0

**Comment by gillius** [comment]
Changing redirectUriTemplate is not always an option because it requires changes on OAuth authorization server side to allow the change in allowed redirect URIs. At this moment I cannot test that workaround due to waiting for OAuth provider to change their settings, but I suspect it should work.

Looking at the code I also don't see any mechanism to override or modify this code. The best possible case I can see is implementing a AuthorizationRequestRepository and modifying the "immutable" object to add the 443 to the redirectUri, but it looks very brittle to upgrades since any copy code written will fail if new fields are added, not to mention it's very hacky to mutate the request in the repository that should be passing through data unmodified.

**Comment by gillius** [comment]
I can now confirm the workaround to change the redirectUri sent to the auth server by changing the redirectUriTemplate to not use {baseUrl} by instead manually enter in the load balancer domain with port :443 added to it. I tried to workaround by adjusting frontend host/port settings in Weblogic and it didn't impact Weblogic adding :443 to the HttpServletRequest.getRequestURL.

**Comment by jgrandja** [comment]
@gillius Thanks for the report.
I do see an issue on how the `OAuth2AuthorizationRequest.redirectUri` is built and than compared to the `OAuth2AuthorizationResponse.redirectUri`.

I'm glad you figured out that the workaround is to explicitly configure the `redirect-uri-template` without the use of the `{baseUrl}` variable.

I'll apply this fix soon.
Thanks again.

**Comment by gillius** [comment]
I found another workaround as well if a hardcoded redirectUriTemplate won't work -- if you implement your own ClientRegistrationRepository, in conjunction with a custom login page, you can have full control. Unfortunately, ClientRegistrationRepository takes only a String; however, with a custom redirect page you can compute what you want and "encode" that into the registration name (i.e. redirect to /oauth2/authorization/spring.io.443) and build a custom repository "on the fly", if you can't get the servlet container to form the URL properly from Host and proxy headers when hosted behind a load balanced domain, for example, and you still want to support potentially a direct connection.

**Comment by jgrandja** [comment]
> if you can't get the servlet container to form the URL properly from Host and proxy headers when hosted behind a load balanced domain

Are you aware of the `ForwardedHeaderFilter`? You can configure this `Filter` if your app is behind a load balancer. See [reference](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#appendix-proxy-server) for more details.

**Comment by gillius** [comment]
I am familiar with that filter. However, our load balancers can't support TLS greater than 1.0, so when TLS 1.0 was deprecated, the load balancers were switched into TCP mode and SSL was implemented by Weblogic. That means the load balancers cannot inject any headers as they balance only at TCP level. Instead, we use the Frontend Host/Port settings in Weblogic to specify the load balanced domain, and that is the cause of the problem -- Weblogic injects port 443 into the URL it builds via Servlet API, hence the defect caused by OAuth2AuthorizationRequestRedirectFilter dropping the "standard" port.

**Comment by rwinch** [comment]
We should not ignore the port when comparing the values. Instead, we need to ensure the correct port is communicated to the application.

Did you try searching your server documentation for SSL termination setup? There should be something in there that allows you to configure the HttpServletRequest.

**Comment by gillius** [comment]
I feel that it is correctly communicated to the application and that Spring Security is in error. OAuth2AuthorizationRequestRedirectFilter is given port 443 and it explicitly filters it out, but OAuth2LoginAuthenticationFilter does not perform the same step. From a servlet API perspective, Weblogic is consistent in that getPort and getRequestURL both return port 443.

It looks like the code in OAuth2AuthorizationRequestRedirectFilter was a workaround to some other application server perhaps that returned 443 port but not in getRequestURL? I see issue #4836 introduced this code, which is reported a defect. The reported defect is that -1 was seen in URL, but the code seems to remove standard ports 80 and 443.

I notice also this code is not in this file in 5.1.x Spring Security (maybe it was refactored somewhere else though).

**Comment by jgrandja** [comment]
@rwinch Agreed, we won't ignore the port when comparing. @gillius Is correct - there is an inconsistency between `OAuth2AuthorizationRequestRedirectFilter` and `OAuth2LoginAuthenticationFilter` on how the comparison happens. I've spotted where the bug is and will fix shortly.

**Comment by jgrandja** [comment]
@gillius I've applied the fix via 9a49795
