### ISSUE TITLE
[question] Get logged in users with spring reactive/webflux security

### ISSUE THREAD

**Issue by bkolb** [spring-projects/spring-security#5762]
I am trying to build a small example with the reactive stack of spring. I want to keep track of "active users", how would I do that? `ServerHttpSecurity` offers a `authenticationSuccessHandler` for `formLogin` and a `logoutSuccessHandler` for logout. But `httpBasic` seems to offer nothing alike. How would I get notified if a session would time out? 
In classic spring I would have used the `SessionRegistry` and configure it in `httpSecurity` for that, but that seems to be no longer available in the reactive stack.

**Comment by rwinch** [comment]
The best approach would be to leverage a custom `WebSessionStore` that allowed additional operations based upon the username. Spring Session is likely the best place for this. I created https://github.com/spring-projects/spring-session/issues/1176 You can reach out on that issue for additional details and discussion if you are interested in contributing a PR
