### ISSUE TITLE
providedSessionAuthenticationStrategy will always be null in SessionManagementConfigurer

### ISSUE THREAD

**Issue by kaarelm** [spring-projects/spring-security#5763]
The `providedSessionAuthenticationStrategy` cannot be set in `SessionManagementConfigurer`, so the `if` statement in [SessionManagementConfigurer.java#L594](https://github.com/spring-projects/spring-security/blob/8510e9a28536b6dd8f59b0492521020b1cbe1e82/config/src/main/java/org/springframework/security/config/annotation/web/configurers/SessionManagementConfigurer.java#L594)  will always be true.
This resulted from the fix done [here](https://github.com/spring-projects/spring-security/commit/e68d8bfaeaae7e244bf3a27ce6dbec530b0c940c#diff-27b7ea8d7c19c219bbe7ddf1320a929a) but maybe the intended code was
```java
this.providedSessionAuthenticationStrategy = sessionAuthenticationStrategy;
```
instead of
```java
this.sessionFixationAuthenticationStrategy = sessionAuthenticationStrategy;
```
If not I guess the if statement and the added variable can be removed.

**Comment by jgrandja** [comment]
Thanks for catching that @kaarelm!
I've applied the changes and is now  in master.
