### ISSUE TITLE
SubjectDnX509PrincipalExtractor is documented with incorrect regular expression

### ISSUE THREAD

**Issue by sunflower-seed** [spring-projects/spring-security#5770]
https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/authentication/preauth/x509/SubjectDnX509PrincipalExtractor.java#L39

In the source from above and **also** in the documentation this example is mentioned:

`emailAddress=(.?),`

I believe this wont work, because an valid E-Mail consists of more than one character.

I propose to change it to

`emailAddress=(.*?),`

which works in my use case.

**Comment by rwinch** [comment]
@sunflower-seed Thanks for the report! Would you be interested in submitting a PR to fix this?

**Comment by sunflower-seed** [comment]
I'll have a look at it. May take some time.

**Comment by sunflower-seed** [comment]
Hopefully catched all occurencies and hopefully did all github !@!/$ right....

https://github.com/spring-projects/spring-security/pull/5988

**Comment by rwinch** [comment]
Thanks for the PR I merged your PR (#5770) and this is fixed in master
