### ISSUE TITLE
Allow PrincipalExtractor to be customized when using x509 authentication

### ISSUE THREAD

**Issue by unlimitedsola** [spring-projects/spring-security#5771]
spring-security provides a couple of methods to configure x509 authentication, e.g. `subjectPrincipalRegex`.
But if the user wants to extract principal programmatically, there's no method to replace `PrincipalExtractor`  for already created `X509AuthenticationFilter`.
Creating a `X509AuthenticationFilter` from scratch is painful in my opinion.

**Comment by rwinch** [comment]
Thanks for the report @unlimitedsola! Would you be interested in submitting a PR for this?
