### ISSUE TITLE
Overriding UserDetailsService does nothing for client_credentials grant

### ISSUE THREAD

**Issue by Gabology** [spring-projects/spring-security#5778]
### Summary

Like the title says, invoking `userDetailsService` on `AuthorizationServerEndpointsConfigurer` in the `configure` callback still causes the default `ClientDetailsUserDetailsService` to be invoked, making it impossible to add extra details to the principal authenticated with the client_credentials grant.

### Actual Behavior

`ClientDetailsUserDetailsService` is invoked to fetch details about the principal.

### Expected Behavior

That the configured `UserDetailsService` would be invoked.

### Sample

```
@Configuration
@EnableAuthorizationServer
class AuthorizationServerConfig @Autowired constructor(
    private val userDetailsService: UserDetailsService,
) : AuthorizationServerConfigurerAdapter() {

    override fun configure(endpoints: AuthorizationServerEndpointsConfigurer) {
        endpoints.userDetailsService(userDetailsService)
    }
```

**Comment by jgrandja** [comment]
@Gabology Can you please log this issue in the [Spring Security OAuth](https://github.com/spring-projects/spring-security-oauth/issues) repo. Thanks.
