### ISSUE TITLE
SEC-317: AJAX support for the ACEGI framework

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#578]
["Brian Pontarelli":https://jira.spring.io/secure/ViewProfile.jspa?name=voidmain](Migrated from ["SEC-317":https://jira.spring.io/browse/SEC-317?redirect=false]) said:

This is to track an enhancement that allows ACEGI to be more easily integrated with AJAX applications. Here is a summary of the changes thus far:
1. Changed ExceptionTranslationFilter to handle a regular expression in order to match URLs and determine whether or not a request URL is an AJAX request or not. For example:

.+_update|.+_cancel|.+_edit

Most folks will want to make this simpler by making all of their AJAX URLs something like this:

.+_ajax.+

Once the ExceptionTranslationFilter has determined that a URL is an AJAX URL it forwards the request by using a new entry point called AJAXAuthenticationProcessingFilterEntryPoint. This is important because a forward must be used so that the AJAX in the browser doesn't get confused by a 302 response code from the browser.
1. Changed the AbstractProcessingFilter and added a number of new properties:
2. ajaxAuthenticationFailureUrl
3. ajaxDefaultTargetUrl
4. ajaxFilterProcessesUrl

Since the ExceptionTranslationFilter has forwarded the request to an AJAX login form, the application must submit the AJAX login form to a different URL than the standard login form. The default URL is "j_ajax_acegi_security_check". The APF inspects this URL to determine if the login is an AJAX login. It then proceeds with authentication. If the authentication fails, the request is forwarded to the ajaxAuthenticationFailureUrl. If the authentication is successful, the request is forwarded to the either the previously saved URL or the ajaxDefaultTargetUrl.
1. In order to handle saved requests via a forward changed SavedRequest so that I could construct a forward URI rather than a redirect URL. The most major change made was the SavedRequestAwareWrapper. Previously it would determine whether or not it was proxying requests to the original request or handling the saved request. This seemed like it was dangerous and made it difficult for because it doesn't provide visibility about whether or not the saved request was being used. The constructor now throws an exception if the SavedRequest is not being used. From this exception it can be determined in the SavedRequest filter if the URL was correct or not. To tie all of the saved request handling together, in the APF if the authentication was successful and there was a saved request the request is now forwarded to the saved request URI. This meant that in order for this to work, acegi needed to be configured in web.xml to handle FORWARDs. Once the request was forwarded, Acegi would construct the wrapper and then let the request go on to its intended target, which in my case is WebWork.

**Comment by spring-issuemaster** [comment]
This issue depends on #621
