### ISSUE TITLE
How can I retrieve OAuth2RefreshToken?

### ISSUE THREAD

**Issue by MasatoshiTada** [spring-projects/spring-security#5828]
### Summary

I'm trying Spring Security 5.1 RC1 to create OAuth2 Resource Server and Client.
Authorization Server is Keycloak.
To logout from Keycloak, refresh token is required.

I found OAuth2RefreshToken class([at]since  5.1), but it seems there is no way for me to retrieve it as I read the source codes.

### Version
- spring-security-oauth2-core:5.1.0.RC1

### Sample

```java
MultiValueMap<String, String> formParams = new LinkedMultiValueMap<>();
formParams.add("client_id", "my-client-id");
formParams.add("client_secret", "my-client-secret");
formParams.add("refresh_token", "my-refresh-token"); // Currently hard-coded😱

HttpHeaders httpHeaders = new HttpHeaders();
httpHeaders.add(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_FORM_URLENCODED_VALUE);

RequestEntity<MultiValueMap<String, String>> requestEntity =
        new RequestEntity<>(formParams, httpHeaders, HttpMethod.POST,
                URI.create("http://my-host:port/auth/realms/my-realm/protocol/openid-connect/logout"));

ResponseEntity<String> responseEntity = restTemplate.exchange(requestEntity, String.class);
```

**Comment by rwinch** [comment]
You can retrieve it using `@RegisteredOAuth2AuthorizedClient("client-id") OAuth2AuthorizedClient authorizedClient` in a Spring MVC controller. Then the refresh token is available on it as `authorizedClient.getRefreshToken()`

**Comment by rwinch** [comment]
I'm closing this as answered. If you have additional questions, the preferred way to ask questions is on StackOverflow where the entire community helps to answer questions

**Comment by MasatoshiTada** [comment]
Thank you so much! This was my lack of research🙇‍♂️
