### ISSUE TITLE
SEC-323: User can't really change the queries from: acl.basic.jdbc.JdbcDaoImpl

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#584]
["David Leal Valmaña":https://jira.spring.io/secure/ViewProfile.jspa?name=dleal](Migrated from ["SEC-323":https://jira.spring.io/browse/SEC-323?redirect=false]) said:

I have detected that it is not possible to really change the queries associated with the class: org.acegisecurity.acl.basic.jdbc.JdbcDaoImpl vía Spring configuration, because internally I don't know exactly were there is some instance created from this JdbcDaoImpl outside from the Application Context container defined.

I have defined the following bean:

 <bean id="org.acegisecurity.acl.basic.jdbc.JdbcDaoImpl"
      class="org.acegisecurity.acl.basic.jdbc.JdbcDaoImpl" singleton="true">
      <property name="dataSource"><ref bean="dataSource"/></property>
      <property name="aclsByObjectIdentityQuery">
         <value>${aclsByObjectIdentityQuery}</value>
      </property>
      <property name="objectPropertiesQuery">
         <value>${objectPropertiesQuery}</value>
      </property>  
   </bean>

with the purspose of adding a prefix to all tables (ONLY, see: http://opensource.atlassian.com/projects/spring/browse/SEC-316). So on the applicationContext.properties (loaded via PropertyPlaceholderConfigurer class) I have defined the queries:

objectPropertiesQuery=SELECT CHILD.ID, CHILD.OBJECT_IDENTITY, CHILD.ACL_CLASS, PARENT.OBJECT_IDENTITY as PARENT_OBJECT_IDENTITY FROM lra_acl_object_identity as CHILD LEFT OUTER JOIN lra_acl_object_identity as PARENT ON CHILD.parent_object\=PARENT.id WHERE CHILD.object_identity \= ?
aclsByObjectIdentityQuery=SELECT RECIPIENT, MASK FROM lra_acl_permission WHERE acl_object_identity \= ?

Such configuration is taken into account only if all instance created during the execution are created inside of the application context, otherwise the user configuration has not priority.

What I have detected is that there are more than one bean created during my execution, but only one time after bean creation the setObjectPropertiesQuery() is invoked, so the other times are created without respecting the configuraiton of the application context.

Looking into the log file I get:

[2006-18-20 07:18,  2156]DEBUG[org.acegisecurity.acl.basic.jdbc.JdbcDaoImpl$ObjectPropertiesMapping] - <RdbmsOperation with SQL [SELECT CHILD.ID, CHILD.OBJECT_IDENTITY, CHILD.ACL_CLASS, PARENT.OBJECT_IDENTITY as PARENT_OBJECT_IDENTITY FROM acl_object_identity as CHILD LEFT OUTER JOIN acl_object_identity as PARENT ON CHILD.parent_object=PARENT.id WHERE CHILD.object_identity = ?] compiled>

but, it is also loaded a second time, outside of the continer:

[2006-18-20 07:18,  2484]DEBUG[org.acegisecurity.acl.basic.jdbc.JdbcDaoImpl$ObjectPropertiesMapping] - <RdbmsOperation with SQL [SELECT CHILD.ID, CHILD.OBJECT_IDENTITY, CHILD.ACL_CLASS, PARENT.OBJECT_IDENTITY as PARENT_OBJECT_IDENTITY FROM lra_acl_object_identity as CHILD LEFT OUTER JOIN lra_acl_object_identity as PARENT ON CHILD.parent_object=PARENT.id WHERE CHILD.object_identity = ?] compiled>

so there are to object created one with default definition, so the set method was not invoked and the second time with my definition, you can see the prefix: lra_ on table name.

I am adding the stack trace of the error:

PreparedStatementCallback; bad SQL grammar [SELECT CHILD.ID, CHILD.OBJECT_IDENTITY, CHILD.ACL_CLASS, PARENT.OBJECT_IDENTITY as PARENT_OBJECT_IDENTITY FROM acl_object_identity as CHILD LEFT OUTER JOIN acl_object_identity as PARENT ON CHILD.parent_object=PARENT.id WHERE CHILD.object_identity = ?]; nested exception is java.sql.SQLException: Table 'lra.acl_object_identity' doesn't exist

org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [SELECT CHILD.ID, CHILD.OBJECT_IDENTITY, CHILD.ACL_CLASS, PARENT.OBJECT_IDENTITY as PARENT_OBJECT_IDENTITY FROM acl_object_identity as CHILD LEFT OUTER JOIN acl_object_identity as PARENT ON CHILD.parent_object=PARENT.id WHERE CHILD.object_identity = ?]; nested exception is java.sql.SQLException: Table 'lra.acl_object_identity' doesn't existjava.sql.SQLException: Table 'lra.acl_object_identity' doesn't exist at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2926) at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1571) at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1666) at com.mysql.jdbc.Connection.execSQL(Connection.java:2978) at com.mysql.jdbc.Connection.execSQL(Connection.java:2902) at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:933) at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1027) at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:92) at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:535) at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:476) at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:528) at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:553) at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:574) at org.springframework.jdbc.object.SqlQuery.execute(SqlQuery.java:102) at org.springframework.jdbc.object.SqlQuery.execute(SqlQuery.java:189) at org.springframework.jdbc.object.SqlQuery.execute(SqlQuery.java:197) at org.acegisecurity.acl.basic.jdbc.JdbcDaoImpl.getAcls(JdbcDaoImpl.java:162) at org.acegisecurity.acl.basic.BasicAclProvider.lookup(BasicAclProvider.java:199) at org.acegisecurity.acl.basic.BasicAclProvider.getAcls(BasicAclProvider.java:104) at org.acegisecurity.acl.basic.BasicAclProvider.getAcls(BasicAclProvider.java:163) at org.acegisecurity.acl.AclProviderManager.getAcls(AclProviderManager.java:96) at org.acegisecurity.afterinvocation.BasicAclEntryAfterInvocationCollectionFilteringProvider.decide(BasicAclEntryAfterInvocationCollectionFilteringProvider.java:145) at org.acegisecurity.afterinvocation.AfterInvocationProviderManager.decide(AfterInvocationProviderManager.java:74) at org.acegisecurity.intercept.AbstractSecurityInterceptor.afterInvocation(AbstractSecurityInterceptor.java:151) at org.acegisecurity.intercept.method.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:68) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:170) at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:170) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:176) at $Proxy2.findAll(Unknown Source) at com.schinvest.lra.business.TestSecuritySchiCustomerService.testFindAllSchiCustomersLikeAsLra(TestSecuritySchiCustomerService.java:58)

I have checked this problem, under: Acegi 1.0.1 and with the SNAPSHOT of 19/06/2007) with Spring 1.2.6 and Spring 1.2.8

Please let me know any patch about a solution to this problem, because our standar require to add a prefix for tables.

Thanks in advance,

David Leal

P.S.: I have detected this problem only for this class, but it possible occurs for other classes that allow query configuration: org.acegisecurity.userdetails.jdbc.JdbcDaoImpl and with org.acegisecurity.acl.basic.jdbc.JdbcExtendedDaoImpl

**Comment by spring-issuemaster** [comment]
This issue depends on #576
