### ISSUE TITLE
oauth autoconfigure doesn't take existing UserDetailsService into account

### ISSUE THREAD

**Issue by berndgoetz** [spring-projects/spring-security#5851]
### Summary

When using @EnableResourceServer (and @EnableOAuth2Sso potentially) an existing UserDetailsService bean is not taken into account when setting up a UserAuthenticationConverter (which is a DefaultUserAuthenticationConverter by default that has a setUserDetailsService method.

### Actual Behavior

My custom UserDetailsService is not picked up.

### Expected Behavior

It is picked up.

### Configuration

I'm using Okta, and 

`security:
  oauth2:
    client:
      client-id: xxx
      client-secret: yyy
      access-token-uri: https://dev-abcdef.oktapreview.com/oauth2/default/v1/token
      user-authorization-uri: https://dev-abcdef.oktapreview.com/oauth2/default/v1/authorize
      scope: openid profile email
    resource:
      user-info-uri: https://dev-abcdef.oktapreview.com/oauth2/default/v1/userinfo
      token-info-uri: https://dev-abcdef.oktapreview.com/oauth2/default/v1/introspect
      prefer-token-info: false`

### Version

Spring Boot 2.0.5.RELEASE
Spring Security: org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure:2.0.5.RELEASE

### Sample

See https://github.com/berndgoetz/spring-sec-oauth2-rs-user-details-service

Run it as a Spring Boot application, Application class main method. Add the "okta" profile for the start. Edit the application.yml and put your Okta domain in there.

Run http://localhost:8082/me to get an exception that shows that the custom user details service wasn't picked up.

**Comment by rwinch** [comment]
Thanks for the report!

This is not part of Spring Security codebase, so the issue doesn't really belong here. Can you please create a ticket at https://github.com/spring-projects/spring-security-oauth2-boot/issues

Thanks and thanks again for the report!

**Comment by berndgoetz** [comment]
True, thanks. I've put it [there](https://github.com/spring-projects/spring-security-oauth2-boot/issues/47)
