### ISSUE TITLE
SEC-325: Add support for Groups

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#586]
["Matt Raible":https://jira.spring.io/secure/ViewProfile.jspa?name=mraible](Migrated from ["SEC-325":https://jira.spring.io/browse/SEC-325?redirect=false]) said:

http://forum.springframework.org/showthread.php?p=53307

<quote from="raible">I attended a BOF at The Spring Experience where there was much debate about having a "Groups" concept in Acegi. Colin was for it, Ben against. However, in the end, I believe Ben said it'd only take 10 minutes to add - so he'd do it.</quote>

<quote from="alex">It's a semantic thing. People who want an "administrative" / "management" interface for security would like to see groups etc. I would not modify the GrantedAuthority concept to not recognise groups - I would merely add a GROUP table which the out-of-the-box DAOs would recognise and then generate additional GrantedAuthority[]s accordingly.</quote>

**Comment by spring-issuemaster** [comment]
This issue duplicates #533
