### ISSUE TITLE
Fix JDK 10 & 11 builds

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#5860]
### Summary

Due to a Jenkins misconfiguration the build was not actually running on JDK 10 or 11. When Jenkins was fixed the build broke. We need to fix the build for JDK 10 and 11

**Comment by rwinch** [comment]
We haven't fixed JDK 11 yet, so reopening

**Comment by bberto** [comment]
Building with OpenJDK 11 from master I get this:
```
> Task :spring-security-itest-ldap-embedded-apacheds-default:integrationTest

org.springframework.security.LdapServerBeanDefinitionParserTests > apacheDirectoryServerIsStartedByDefault FAILED
    org.springframework.beans.factory.BeanCreationException at LdapServerBeanDefinitionParserTests.java:38
        Caused by: java.lang.NoClassDefFoundError at LdapServerBeanDefinitionParserTests.java:38
            Caused by: java.lang.ClassNotFoundException at LdapServerBeanDefinitionParserTests.java:38
```

so I think this issue should be reopened. TravisCI builds with openjdk8

**Comment by rwinch** [comment]
@bberto If you have found an issue in master, please create a new issue with details on how to reproduce. Please note that we run our build in Jenkins which builds against JDK 8, 9, 10, 11, and 12 so there is likely some other difference causing the problem. That means the more details you can provide the more likely we will be able to figure out the issue. Thanks!
