### ISSUE TITLE
SEC-326: Refactor out cookie management.

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#587]
["Paul Benedict":https://jira.spring.io/secure/ViewProfile.jspa?name=paul4christ79](Migrated from ["SEC-326":https://jira.spring.io/browse/SEC-326?redirect=false]) said:

I perform authentication and logging out in custom code. Thus I do not use the AuthenticationProcessingFilter or LogoutFilter, but I do use the RememberMeProcessingFilter. It would be easier for me to explicitly generate the appropriate cookies if the cookie creation was refactored out into a RememberMeCookieGenerator class, which the Filter would then be bound to. The methods I am targetting are the creation in loginSuccess() and the deleting of it in cancelCookie().

**Comment by spring-issuemaster** [comment]
This issue is related to #849
