### ISSUE TITLE
Remove Deprecated EvaluationContextExtensionSupport Usage

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#5886]
### Summary
Remove Deprecated EvaluationContextExtensionSupport Usage

**Comment by Bas83** [comment]
I'm kinda desperate for some support that seems related to this. I have a StackOverflow question open at https://stackoverflow.com/questions/53410526/migrating-spring-boot-2-0-1-to-2-1-0-with-evaluationcontextextensionsupport-and
Any help is greatly appreciated.

**Comment by jzheaux** [comment]
@Bas83 Sorry you hare having trouble! I responded with a suggestion on your SO question.
