### ISSUE TITLE
Webflux JWT : provide a means to set authenticationConverter as in spring mvc

### ISSUE THREAD

**Issue by Rorschachdb** [spring-projects/spring-security#5902]
### Summary

To provide an authenticationConverter in a MVC application is quite simple whereas with Webflux you need to implement a complete AuthenticationManager

### Actual Behavior
If I want to change the Authentication conversion I have to implement a whole authentication manager

```
@Configuration
@EnableWebFluxSecurity
public class MySecurityChainConfigurer {
    @Bean
    public SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http, ReactiveAuthenticationManager myCustomAuthenticationManagerGoesHere) {
        http
             .authorizeExchange()
               .anyExchange()
               .authenticated()
            .and()
              .oauth2ResourceServer()
                .jwt().authenticationManager(myCustomAuthenticationManagerGoesHere);
        return http.build();
    }
}
```

### Expected Behavior
An Authorization converter in standard MVC security is configured like this :

```
@Configuration
public class MyWebSecurityConfigurer extends WebSecurityConfigurerAdapter {

    @Autowired
    private Converter<Jwt, AbstractAuthenticationToken> myJwtAuthenticationConverter;

    @Override
    public void configure(final HttpSecurity http) throws Exception {
        http
           .authorizeRequests()
           .anyRequest().authenticated()
           .and()
           .oauth2ResourceServer()
           .jwt().jwtAuthenticationConverter(myJwtAuthenticationConverter);
    }
}
```

Would'nt it be nice to have a similar behaviour.

In my context of development I create micro services which mixes MVC and Webflux microservices and I use libraries for common bean configurations, It would be nice to be able to share similar configuration for both kind of projects.

### Version
5.1.0

**Comment by rwinch** [comment]
Fixed via #5924
