### ISSUE TITLE
Consider (re)introducing ClientRegistrationRepository#findAll

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-security#5917]
For starters, I'm aware that `ClientRegistrationRepository#getRegistrations` previously existed and was removed in #4582.

I believe the same functionality should be reintroduced since the framework silently forces `Iterable` API on `ClientRegistrationRepository` implementations by doing this in `DefaultLoginPageGeneratingFilter`:

https://github.com/spring-projects/spring-security/blob/fe080cadbe96c8a9ceb0c30ca2ed630928e520e9/config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2LoginConfigurer.java#L577-L580

This prevents users from:

- creating their own dynamic login page based on `ClientRegistrationRepository` without resorting to a similar hack
- reusing default login page with their custom `ClientRegistrationRepository` implementation without implementing `Iterable` as well

IMO the argument outlined in #4582 (performance issues) is flawed since `ClientRegistrationRepository` is a framework API and therefore the developers should be using it responsibly. In practice, an OAuth 2.0 client apps will very rarely manage more than a handful of registrations. Besides, performance considerations wise, the lack of `#findAll` doesn't actually prevent anyone from stuffing unreasonable amount of registrations in `InMemoryClientRegistrationRepository` and eating up memory.

This applies to the reactive side of things as well.

I would provide a PR to address this if the proposal is acceptable.

**Comment by rwinch** [comment]
We won't be doing this because it is not functionality that Spring Security needs. If a user needs that functionality, they need to provide their own implementation. We don't need to introduce paging logic (which requires sorting as well) either.

**Comment by vpavic** [comment]
> We won't be doing this because it is not functionality that Spring Security needs.

Hmm, doesn't the `Iterable` approach from the snippet in issue description show exactly the opposite? That's very hacky IMO and I've listed two use cases which clearly show why it's limited.

Also does this mean you don't have any plans to provide a more capable implementation like `JdbcClientRegistrationRepository`? I was about to propose this and submit a PR. I'm asking this because such implementation almost warrants new operations added to `ClientRegistrationRepository`, like `#save` operation. If you don't plan to do so, then `ClientRegistrationRepository` was poorly named and it should've been named something like `ClientRegistrationProvider` instead. Then perhaps `ClientRegistrationRepository` could've been an extension in a similar manner like `UserDetailsManager` is to `UserDetailsService`.

As I've stated in the Boot issue I don't like that the framework (and that applies to both Spring Security and Spring Boot) encourages people to manage secrets in an insecure (i.e. static) way. That's why I don't consider `InMemoryClientRegistrationRepository` to be a production grade implementation, similarly like `InMemoryUserDetailsManager` isn't either.

**Comment by rwinch** [comment]
So let's circle back with the use cases:

> creating their own dynamic login page based on ClientRegistrationRepository without resorting to a similar hack

User's can implement any additional methods that they need. They are not limited to APIs that Spring Security defines. So this is not true. For example, a user can create a ClientRegistrationRepository that adds a findAll method with or without paging and leverage that.

> reusing default login page with their custom ClientRegistrationRepository implementation without implementing Iterable as well

Users are quite unlikely to leverage the default log in page. It does not match the rest of the application. Even if they do want to leverage it, implementing Iterable is not much different than a findAll method on some other interface so I'm not quite sure why this is a problem.

**Comment by vpavic** [comment]
> User's can implement any additional methods that they need. They are not limited to APIs that Spring Security defines. So this is not true.

Of course users are not limited to Spring Security APIs, and that they can provide their own implementations, that's not the point. I'd expect from a framework to support incremental development (which would also IMO be in the spirit of Spring), and not require you to provide your own implementations for multiple components at once by silently forcing some API (in this case `Iterable`).

> implementing Iterable is not much different than a findAll method on some other interface so I'm not quite sure why this is a problem.

Actually I came across this while preparing a demo where I wanted to show the users how to supply a `ClientRegistrationRepository` implementation backed by a persistent data store and register it as a bean. To my surprise this didn't work as default login page didn't provide any login links since `OAuth2LoginConfigurer#getLoginLinks` ignored my implementation due to not implementing `Iterable`. Now, I'm well aware of Spring Security's inner workings so I knew where to look for a problem - someone else might not be as this `Iterable` requirement isn't expressed or documented anywhere.

**Comment by rwinch** [comment]
> Now, I'm well aware of Spring Security's inner workings so I knew where to look for a problem - someone else might not be as this Iterable requirement isn't expressed or documented anywhere.

Even though I would find it unlikely order for most people to implement things, this is a valuable point. Can you create a ticket for making it more obvious that this is the contract?

**Comment by vpavic** [comment]
I've opened #5927.
