### ISSUE TITLE
Control logging level

### ISSUE THREAD

**Issue by aukhatov** [spring-projects/spring-security#5919]
https://github.com/spring-projects/spring-security/blob/fe080cadbe96c8a9ceb0c30ca2ed630928e520e9/web/src/main/java/org/springframework/security/web/FilterChainProxy.java#L201

I think you should control logging level in configuration file.

**Comment by rwinch** [comment]
I don't understand the comment. Logging is controlled via the logging frameworks configuration. This is a very common pattern in Java code.

Can you please clarify your concern?

**Comment by aukhatov** [comment]
I mean, why do you check debug level like this `if (logger.isDebugEnabled())` ?

**Comment by rwinch** [comment]
It's a [Code Guard](https://commons.apache.org/proper/commons-logging/guide.html#Code_Guards) to prevent unnecessarily evaluating the creation of the String contained within the if statement that is passed to the logger.

**Comment by rwinch** [comment]
I'm going to mark this question as closed. If you believe it is not answered, then please reopen or create a new ticket
