### ISSUE TITLE
Oauth controller not work with para meeter

### ISSUE THREAD

**Issue by arjundevrana** [spring-projects/spring-security#5923]
public String index(Model model,
						@RegisteredOAuth2AuthorizedClient OAuth2AuthorizedClient authorizedClient,
						@AuthenticationPrincipal OAuth2User oauth2User)

This controller not call with para meeter @RegisteredOAuth2AuthorizedClient OAuth2AuthorizedClient authorizedClient,
						@AuthenticationPrincipal OAuth2User oauth2User

**Comment by jgrandja** [comment]
@arjundevrana It's not clear to me the issue you are having. Can you please provide more detail?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
