### ISSUE TITLE
NimbusReactiveJwtDecoder has hardcoded RS256 algorithm.

### ISSUE THREAD

**Issue by nkragel** [spring-projects/spring-security#5926]
### Summary

`org.springframework.security.oauth2.jwt.NimbusReactiveJwtDecoder` in `org.springframework.security:spring-security-oauth2-jose` has hardcoded RS256 algorithm that is not useful.

### Expected Behavior

NimbusReactiveJwtDecoder must have possibility to set custom algorithm, like RS512, etc.

### Version

5.1.0.RELEASE

**Comment by jzheaux** [comment]
Thanks, @nkragel! This will be addressed in #5937.
