### ISSUE TITLE
Correct Way To Parse Request Body To Json IN Web Filter To Make Authentication(In CustomAuthenticationConverter) Reactively

### ISSUE THREAD

**Issue by ankurpathak** [spring-projects/spring-security#5931]
Inside ServerFormLoginAuthenticationConverter in ReactiveWebSecurity we convert ServerWebExchange
to Authentication by using method getFormData().
But What If I send my username and password as JSON like:
{
      "username": "ankurpathak@live.in",
      "password" : "password"
}

What is the correct way to parse this request body in JSON to Authentication If I write Custom AuthenticationConverter.

**Comment by ankurpathak** [comment]
I cam across this file in Spring Framework source code:
https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/test/java/org/springframework/http/codec/json/Jackson2JsonDecoderTests.java
And have done this way:
public class ServerRestLoginAuthenticationConverter implements Function<ServerWebExchange, Mono<Authentication>> {

    public ServerRestLoginAuthenticationConverter() {
    }

    public Mono<Authentication> apply(ServerWebExchange exchange) {
        return exchange.getRequest()
                .getBody()
                .map(Flux::just)
                .map(body -> {
                    Jackson2JsonDecoder decoder = new Jackson2JsonDecoder();
                    ResolvableType elementType = forClass(LoginRequestDto.class);
                    return decoder.decodeToMono(body, elementType, MediaType.APPLICATION_JSON, Collections.emptyMap()).cast(LoginRequestDto.class);
                }).next()
                .flatMap(x -> x)
                .map(this::createAuthentication);

    }

    private UsernamePasswordAuthenticationToken createAuthentication(LoginRequestDto data) {
        String username = data.getUsername();
        String password = data.getPassword();
        return new UsernamePasswordAuthenticationToken(username, password);
    }

}
Am I correct?? Or correct me.

**Comment by rwinch** [comment]
That looks to be correct. However, I would move the creation of `Jackson2JsonDecoder` into a member variable so it can be reused.

**Comment by rwinch** [comment]
I'm closing this as it seems to be answered.

In the future please ask questions on StackOverflow as this helps ensure the entire community can help answer the questions.

**Comment by ankurpathak** [comment]
Yes you can. If I ask quetions on StackOverflow is it answered by Team @Pivotal.
I asked here because of @vpavic comment on this post, he explained this is the
right way to do it:
https://github.com/spring-projects/spring-session/issues/1215

**Comment by rwinch** [comment]
The benefit of asking on StackOverflow is that the entire community (including the Spring team) answers questions. Different Spring Projects have different policies. For example, the Spring Boot team is typically fairly strict about requiring StackOverflow for questions. Often I will answer questions, but we prefer it is asked on StackOverflow as it is easier for others to find and help.
