### ISSUE TITLE
Support For ReactiveAnonymousAuthentication In Reactive Web Security

### ISSUE THREAD

**Issue by ankurpathak** [spring-projects/spring-security#5934]
I coudn't find the support for Reactive Anonymous Authentication In Reactice Web Security.
We should add support for Reactive Annonymous Authentication and Reactive Remember
Me Authentication. This will make the security for Servlet Stack and Netty Stack similar.

**Comment by rwinch** [comment]
Thanks for the suggestion. Would you be interested in providing a PR for this?

**Comment by ankurpathak** [comment]
Sure I will work on PR but I need some clues from you before that:
In Servlet Based Security we have AbstractAuthenticationFilter and
1. AnonymousAuthenticationFilter extends it
2. RemembeMeAuthenticationFilter also extend it
And then we plug in these filters into filter chain

But In FluxBasedSecurity we don't have equivalent of AbstractAuthenticationFilter. We have one
AuthenticationWebFilter and user different AuthenticationConverter based on type of Authentication like
HttpBasis, Form etc. How we will plug all kind of Authentication like Anonymous, RemberMe in One Filter. If you can clear this point, I am good to go and will start work on PR.

**Comment by rwinch** [comment]
I think it just becomes a new WebFilter that is placed after AuthenticationWebFilter and populates AnonymousAuthenticationToken if the Authentication is empty. There is no need to force it into using a `ReactiveAuthenticationManager` since we are not really authenticating anonymous users.

**Comment by rwinch** [comment]
I'd like to stick with one thing at a time. Let's focus this issue on anonymous support.

**Comment by ankurpathak** [comment]
@rwinch Ya sure we can have this issue for Anonymous thing. But we already have very old issue for RememberMe Here at:
https://github.com/spring-projects/spring-security/issues/5504

**Comment by rwinch** [comment]
@ankurpathak I responded there.

**Comment by ankurpathak** [comment]
@rwinch Here is my PR for this issue:
https://github.com/spring-projects/spring-security/pull/6198
Please guide me if it reuires improvements, modifications or corrections.
