### ISSUE TITLE
Support For Pluging In Custom Implementation Of SecurityContext

### ISSUE THREAD

**Issue by ankurpathak** [spring-projects/spring-security#5943]
Currently we have only one implementation of SecurityContext called SecurityContextImpl and it
stores only authentication. How can we plug in another implementation of SecurityContext may be
called ExtendedSecurityContextImpl which stores authentication and domain context??
@jgrandja Talks about in his talk  Architecture Deep Dive in Spring Security at Spring One 
Conference between 17:00 to 18:00 minute.
https://www.youtube.com/watch?v=AdsnM6OTepc
But how we can plug my custom implementation of SecurityContext in Spring Security.

**Comment by rwinch** [comment]
If you set a different implementation on `SecurityContextHolder.setContext(SecurityContext)`, then it will be what is saved.

**Comment by rwinch** [comment]
I'm closing this as answered. If you have additional questions, please ask them on StackOverflow as this is preferred since more users monitor StackOverflow and you will likely get help faster

**Comment by ankurpathak** [comment]
@rwinch I already know that. I was looking for something different. SecurityContextPersistenceFilter
filter calls loadContext method on SecurityContextRepository. at line:
            SecurityContext contextBeforeChainExecution = this.repo.loadContext(holder);
 SecurityContextRepository call createEmptyContext() on SecurityContextHolder.
SecurityContextHolder calls getContext() on SecurityContextHolderStrategy and this final
getContext() method directly starts creating SecurityContextImp instances. I was looking
for some spring.factories mechanism to tell it with SecurityContext implementation to use.

**Comment by rwinch** [comment]
> SecurityContextPersistenceFilter
filter calls loadContext method on SecurityContextRepository. at line:
SecurityContext contextBeforeChainExecution = this.repo.loadContext(holder);

It loads the `SecurityContext` that was saved. The `SecurityContext` that is saved is whatever is set on the `SecurityContextHolder.getContext()` contained previously and was saved using the `SecurityContextRepository. In short, if you invoke `SecurityContextHolder.setContext(customContext)`, `this.repo.loadContext(holder)` will return `customContext` on the next request.

You can also set a custom `SecurityContextHolderStrategy` to allow creating a custom `SecurityContext` when `SecurityContextHolder.createEmptyContext()` is invoked. To do this use the system property `spring.security.starategy` and set it to the class name that implements `SecurityContextHolderStrategy`. This feature is not very common and most people do not need this feature, so I'd consider alternatives before doing this.

**Comment by ankurpathak** [comment]
Well ya this is the right, elegant and awesome way of doing it. Thanks for 
all your help.
