### ISSUE TITLE
SEC-336: Add setters for LogoutFilter

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#597]
["Willis Blackburn":https://jira.spring.io/secure/ViewProfile.jspa?name=willisblackburn](Migrated from ["SEC-336":https://jira.spring.io/browse/SEC-336?redirect=false]) said:

LogoutFilter is the only filter that requires constructor arguments.  All the other filters are Spring-friendly and have setters.  Looked at the source and can't find any particular reason why LogoutFilter can't take setters too.  I can submit a patch.

**Comment by spring-issuemaster** [comment]
This issue duplicates #605
