### ISSUE TITLE
spring-security breaks ResourceUrlEncodingFilter when using servlet context

### ISSUE THREAD

**Issue by vandykej17** [spring-projects/spring-security#5993]
### Summary
When using a ResourceUrlEncodingFilter along with spring-security, my resources do not contain the hash as expected. If I comment out the spring-security config everything works as expected.

### Actual Behavior
No hash gets appended on my resource url.
![image](https://user-images.githubusercontent.com/6785860/47168627-fb85af00-d2c6-11e8-8630-f758f7d06a3a.png)

### Expected Behavior
When I use spring-security along with the ResourceUrlEncodingFilter I am expecting that my url to get my css file includes a hash at the end.
![image](https://user-images.githubusercontent.com/6785860/47168528-bd888b00-d2c6-11e8-92fd-17f7b49c3fea.png)

### Configuration
I have a very simple application with a ResourceUrlEncodingFilter, VersionResourceResolver, and a very basic spring-security filter. 

### Version
4.0.0.RELEASE

### Sample
https://github.com/vandykej17/spring-framework-issues/commits/SPR-12550-Security

### More details
In both cases, the url being passed into encodeURL is `/main/static/style.css`. When adding the hash to the url, it attempts to find a resource handler that matches the requested url.  In order to match the resource handler, my servlet context (`main`) must be stripped off. When using a security filter, encoder cannot figure out the servlet context correctly.

I think this is because inside the `UrlPathHelper` class it uses the request to figure out the servlet context. The issue is my request is of type `SecurityContextHolderAwareRequestWrapper` and when I call `getRequestURI()` on that request, it returns `/WEB-INF/views/home.jsp`.  That does not have my servlet context.

Without the security filter, the `UrlPathHelper` class has a request of type `RequestFacade` and when I call `getRequestURI()` on that request, it returns `/main/home`. That correctly figures out the servlet context, removes it from my url, becoming `/static/style.css` which correctly matches my resource handler.

The application I am using originated from this ticket:
https://jira.spring.io/browse/SPR-12550#comment-162808

**Comment by vandykej17** [comment]
I have a fix for my application, but it is not the greatest idea. It at least works though.
https://github.com/vandykej17/spring-framework-issues/commit/3171a5ecee3ff650927d0fc12d83747b8999e186

**Comment by rwinch** [comment]
I was able to reproduce this without Spring Security by using a no-op `HttpServletRequestWrapper` in a `Filter`. You can find my changes at https://github.com/rwinch/spring-framework-issues/tree/SPR-12550-Security/SPR-12550

I'm going to reopen the original JIRA
