### ISSUE TITLE
Please support builder DSLs that leverage the availability of lambdas

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-security#6001]
Spring Framework 5 assumes Java 8 and supports Kotlin, in addition to Groovy. All 3 languages are lambda capable. It would be nice if we could have a configuration DSL that supports context, something like 

```
http.httpBasic ( options -> ... ) ; 
```

or even

```
http
  .httpBasic ( o -> ) 
  .csr( ... ) 
  .pathMatchers ( config -> .. ) 
  ..

```

**Comment by rwinch** [comment]
Closing this in favor of gh-5557
