### ISSUE TITLE
Spring Security 5.2 Themes

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#6004]
### Summary

The themes for Spring Security 5.2 are:

* OAuth2
  * Opaque token support
  * Expanding supported grant types
  * Supporting other key types
  * multi tenancy
* [SAML service provider MVP](https://github.com/spring-projects/spring-security/issues/6019)
* Documentation
* RSocket
* JDK 12 Compatibility
* Configuration improvements 
  * Kotlin DSL https://github.com/spring-projects/spring-security/issues/5558
  * Using lambda's in Java https://github.com/spring-projects/spring-security/issues/5557

NOTE: This is a living document and may be changed

**Comment by eleftherias** [comment]
Additional details on the Spring Security 5.2 release can be found in the [release notes](https://github.com/spring-projects/spring-security/releases/tag/5.2.0.RELEASE), [release announcement](https://spring.io/blog/2019/10/01/spring-security-5-2-goes-ga) and [reference documentation](https://docs.spring.io/spring-security/site/docs/5.2.0.RELEASE/reference/htmlsingle/#new).
