### ISSUE TITLE
Each WebSecurityConfigurerAdapter implementation triggers creation of a different filter chain

### ISSUE THREAD

**Issue by elefeint** [spring-projects/spring-security#6008]
### Summary
Multiple implementations of WebSecurityConfigurerAdapter coming from different libraries are not possible to combine in an annotation or java configuration-driven world; the first one always wins, and the rest are effectively invisible.

### Actual Behavior
For each implementations of WebSecurityConfigurerAdapter, a new filter chain gets created, then whichever one is ordered first is applied to web requests, and the others ignored.

<pre>
c.e.e.WebSecurityConfigurerAdapter1      : Adapter 1 picked up: org.springframework.security.config.annotation.web.builders.HttpSecurity@23b719b8
c.e.e.WebSecurityConfigurerAdapter2      : Adapter 2 picked up: org.springframework.security.config.annotation.web.builders.HttpSecurity@5f279f0f
o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: org.springframework.security.web.util.matcher.AnyRequestMatcher@1, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@3d3dfe34, org.springframework.security.web.context.SecurityContextPersistenceFilter@7eb45e3b, org.springframework.security.web.header.HeaderWriterFilter@46d02a9e, org.springframework.security.web.csrf.CsrfFilter@2a6ad07f, org.springframework.security.web.authentication.logout.LogoutFilter@1c4e68ca, <b>FILTER 1</b>, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@4b760162, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@7f3507f1, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@51c41d9c, org.springframework.security.web.session.SessionManagementFilter@663bd502, org.springframework.security.web.access.ExceptionTranslationFilter@776fdb7f]
o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: org.springframework.security.web.util.matcher.AnyRequestMatcher@1, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@69a36e68, org.springframework.security.web.context.SecurityContextPersistenceFilter@550f46b3, org.springframework.security.web.header.HeaderWriterFilter@6a8bc4cd, org.springframework.security.web.csrf.CsrfFilter@382d6a40, org.springframework.security.web.authentication.logout.LogoutFilter@46b682d3, <b>FILTER 2</b>, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@6e8a0757, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@5a930be7, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@572d6cb4, org.springframework.security.web.session.SessionManagementFilter@6a3434d, org.springframework.security.web.access.ExceptionTranslationFilter@201375b0]

...

Security filter chain: [
  WebAsyncManagerIntegrationFilter
  SecurityContextPersistenceFilter
  HeaderWriterFilter
  CsrfFilter
  LogoutFilter
  <b>UselessFilter1</b>
  RequestCacheAwareFilter
  SecurityContextHolderAwareRequestFilter
  AnonymousAuthenticationFilter
  SessionManagementFilter
  ExceptionTranslationFilter
]
</pre>

### Expected Behavior
Multiple WebSecurityConfigurrerAdapter implementations should apply to the same security filter chain, unless specific path matchers are specified in it.

The example below is contrived, of course -- if applying multiple filters in the same project were the actual requirement, they could easily be done in a single WebSecurityConfigurerAdapter. A more realistic scenario is that a dependency introduces a filter, and the project pulling that dependency in would like to define its own security configuration to, say, restrict some URLs while leaving the others public.

Viable workarounds for client projects are to define their own WebSecurityConfigurerAdapter and apply a filter from a dependency library there. But this approach removes the benefits of bringing autoconfigured dependencies and starters, effectively forcing the client library to configure all security manually.

My usecase is implementation of spring-cloud/spring-cloud-gcp#1016: we need to provide a starter that automatically extracts user identity from an pre-authenticated IAP header, but the user should retain ability to configure their own additional security configuration (extra filters, different security chains on more specific URL patterns etc.).

 
### Version
For the sample app below:
org.springframework.security:spring-security-web:jar:5.0.9.RELEASE:compile
org.springframework.boot:spring-boot-starter-security:jar:2.0.6.RELEASE:compile

When I originally ran into the issue:
org.springframework.security:spring-security-web:jar:5.1.1.RELEASE:compile

### Sample
Minimal app reproducing behavior: https://github.com/elefeint/multiple-web-security-configurer-adapters

I believe #3022 and #5745 were trying to get at the same issue.

**Comment by rwinch** [comment]
This is behaving as designed. If you want to apply defaults to it see https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#jc-custom-dsls
