### ISSUE TITLE
AuthenticationSuccessEvent not published for oauth2Login()

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-security#6009]
On running the [OAuth2 Sample](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-samples/spring-boot-sample-oauth2-client/src/main/java/sample/oauth2/client/SampleOAuth2ClientApplication.java), there was no `AuthenticationSuccessEvent` since the `ProviderManager` seems to be using a `NullEventPublisher`.

**Comment by ismarslomic** [comment]
*FailureEvents are published though. So the issue is related to *SuccessEvents only

**Comment by jgrandja** [comment]
An `AuthenticationManagerBuilder` `@Bean` is registered via  `AuthenticationConfiguration.authenticationManagerBuilder()`. It's also associated with the   `AuthenticationEventPublisher` registered in the context using `AuthenticationManagerBuilder.authenticationEventPublisher()`.

However, `WebSecurityConfigurerAdapter.setApplicationContext()` initializes 2 instances of `AuthenticationManagerBuilder`, but does not associate it with the `AuthenticationEventPublisher` registered in the context.

We need to ensure that the initialization and association of the `AuthenticationEventPublisher` (registered in the context) is consistent between `AuthenticationConfiguration` and `WebSecurityConfigurerAdapter`.

**Comment by ismarslomic** [comment]
@jgrandja thanks! I will gladly retest and report back, when you have a fix. Any idea on how complex and time consuming it will be? Just so I know if I should wait for a fix, or go ahead and use something else for Audit logging.

**Comment by jgrandja** [comment]
@ismarslomic The fix has been applied to master and backported to 5.1.2 and 5.0.10.

**Comment by ismarslomic** [comment]
I can confirm `AuthenticationSuccessEvent`s er being published, and I can also find `AUTHENTICATION_SUCCESS` events from Actuator endpoint `/auditevents`. Thanks a lot for quick fix!
