### ISSUE TITLE
ldap-server XML directive should support UnboundIdContainer

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6011]
On the Java config side, the code selects an in-memory container based on dependencies on the classpath, choosing between `ApacheDSContainer` and `UnboundIdContainer`.

XML should have this support, too, in order to simplify transition, should a user need to switch to the unbound id container without needing to jump over to the Java DSL as well.

**Comment by eddumelendez** [comment]
Hi @jzheaux 

I am looking into this issue. I am wondering which should be the approach to test it

* Create an example of that specific use case
* Add a submodule for `unboundid` to test it with a different classpath than `apacheds` and then merge it into `spring-security-config`

Thanks in advance

**Comment by jzheaux** [comment]
Hi, @eddumelendez 

First, yes, I like the idea of an example. I think that it would be compelling to enhance the existing ldap sample with instructions on how the user can modify the dependency list and see the sample use unboundid instead of apacheds.

Regarding tests, there really isn't a simple way yet to induce a selection between the two. I lean towards introducing a Gradle test task that would run with a different classpath. So, for example, there might be a task called "unboundidTest". By "submodule", do you mean introducing something like "unboundid-test" alongside "main", "test", and "integration-test"?

Eventually, it would be nice to have a way to target which to use, independent from the classpath, but `LdapServerBeanDefinitionParser` doesn't support this, and it's a bit gnarly to set it up directly for a unit test. Though, technically, constructing an `LdapServerBeanDefinitionParser` directly might be an option, too.

**Comment by eddumelendez** [comment]
@jzheaux my current implementation is based on classpath detection. What if used this issue to improve `LdapServerBeanDefinitionParser` and support `embedded-server` attribute which will be `APACHEDS` or `UNBOUNDID` but by default will be always `APACHEDS` to maintain the backward compatibility. WDYT?

**Comment by jzheaux** [comment]
@eddumelendez I guess my concern with that is it would never be used outside the project. For example, a user would only need that setting if they themselves had `apacheds` and `unboundid` both on the classpath, which seems a bit unlikely.

That said, in light of the level of effort given the other two scenarios, yes, I think that it's reasonable to addition.

**Comment by eddumelendez** [comment]
@jzheaux sorry for the delay. I already submitted a draft for this. still thinking about the testing for `unboundid`. we can continue the discussion in the draft :)
