### ISSUE TITLE
Default claim set converter for NimbusJwtDecoder should parse scopes

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6014]
By default, `NimbusJwtDecoderJwkSupport` uses `MappedJwtClaimSetConverter.withDefaults()` to create the `Converter` used to normalize claims. It correctly only converts Jwt standard claims, which excludes scope.

The design of this API, however, gives us the flexibility to introduce an additional converter, for example `ScopeConverter`, which looks at a configurable scope claim.

Then, the Nimbus JwtDecoder could introduce this additional converter:

```java
Map<String, Converter<Object, ?>> scopeConverters = new HashMap<>();
scopeConverters.put("scope", new ScopeConverter());
scopeConverters.put("scp", new ScopeConverter());

MappedJwtClaimSetConverter.withDefaults(scopeConverters);
```

**Comment by jgrandja** [comment]
@jzheaux Is this still valid? Do we really need `ScopeConverter`?

**Comment by jzheaux** [comment]
Closing due to lack of interest
