### ISSUE TITLE
Facebook Login Failing in Spring Boot 2.1.0.RC1

### ISSUE THREAD

**Issue by ankurpathak** [spring-projects/spring-security#6017]
@jgrandja Whilte trying linkedin login sample provided by you,
https://github.com/spring-projects/spring-security/issues/5983
 My facebook login started failing. So i debugged it with minimum
configuration, and it fails in DefaultOAuth2UserService at line 108 with message:

[invalid_user_info_response] An error occurred while attempting to retrieve the UserInfo Resource: Could not extract response: no suitable HttpMessageConverter found for response type [java.util.Map<java.lang.String, java.lang.Object>] and content type [text/javascript;charset=UTF-8]

So I thought facebook is returning wrong Content-Type header, so i directly called the user info
endpoint:
https://graph.facebook.com/me?fields=id,name,email
 with postman to check content type returned by facebook and results were:
1. application/json;charset=UTF-8 -> application/json;charset=UTF-8
2. application/json-> application/json
Thus facebook is returning correct Content-Type.
So I think this is some bug in Spring Security version used with Spring Boot 2.1.0.RC1 which is 5.1.1.
Because this minimum configuration was working in Spring Boot 2.0.6.RELEASE which uses Spring
Security 5.0.6 I guess.
Or I am mising something.
The minimum sample I am using is availabe at:
https://github.com/ankurpathak/facebook-login

**Comment by jgrandja** [comment]
@ankurpathak I also tested calling Facebook's UserInfo Endpoint using Postman and the `content-type` returned is `text/javascript; charset=UTF-8`. See screenshot below.

![user-info-facebook](https://user-images.githubusercontent.com/10884212/47458240-16649180-d7a7-11e8-9c7d-02928eab3200.png)

> 2. application/json-> application/json 
Thus facebook is returning correct Content-Type.

Can you double check the response headers in Postman because this is not consistent with what I got.

Either way, the reason you're getting this error now is that in 5.1, the `DefaultOAuth2UserService` uses a `RestTemplate` and it doesn't find the matching `HttpMessageConverter` for the `content-type` since `application/json` is not returned but is expected. This really should be reported to Facebook to fix.

As an FYI, before the 5.1 release, the `DefaultOAuth2UserService` directly used `MappingJackson2HttpMessageConverter` so you wouldn't have run into this issue even though the `content-type` is not correct.

I've put together a [facebook sample](https://github.com/jgrandja/oauth2login-demo/tree/facebook) that is a workaround to this issue. But keep in mind this is a workaround to get you moving but it really should be fixed on Facebook's end.

I'll close this ticket but we can re-open if you have further issues.

**Comment by ankurpathak** [comment]
@jgrandja 1. Remove ;charset=UTF-8 in Accept=application/json;charset=UTF-8 and
send it as just Accept=application/json, you will get correct ContentType in respone.
2. Or Not send any Content-Type or Accept Header, you will get correct ContentType in
respone.
So can't we make RestTemplate not sent that UTF-8 part in Accept Header, its creating problem.

**Comment by jgrandja** [comment]
@ankurpathak Interesting behaviour with Facebook. Thanks for providing the info for the fix - 
I removed the `charset` from `Accept`.
This is now in master and will get into 5.1.2

**Comment by ankurpathak** [comment]
@jgrandja Thanks for fixing. How can I try it now?? 5.1.2 not available in maven central.

**Comment by jgrandja** [comment]
You can try it with [5.1.2.BUILD-SNAPSHOT](https://docs.spring.io/spring-security/site/docs/5.1.2.BUILD-SNAPSHOT/reference/htmlsingle/#spring-boot-with-maven).

You will need to configure the [Spring Snapshot Repository](https://docs.spring.io/spring-security/site/docs/5.1.2.BUILD-SNAPSHOT/reference/htmlsingle/#maven-repositories) in your POM.

**Comment by ankurpathak** [comment]
I followed the steps provided in 5.1.2.BUILD-SNAPSHOT.by updating my pom of Spring Boot with:
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>11</java.version>
        <spring-security.version>5.1.2.BUILD-SNAPSHOT</spring-security.version>
    </properties>
But now project is not even building with mvn clean install -U and failing with below stack trace:

[ERROR] Non-resolvable import POM: Could not find artifact org.springframework.security:spring-security-bom:pom:5.1.2.BUILD-SNAPSHOT in spring-snapshots (https://repo.spring.io/snapshot) @ org.springframework.boot:spring-boot-dependencies:2.1.0.RC1, /home/ankur/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.1.0.RC1/spring-boot-dependencies-2.1.0.RC1.pom, line 2856, column 25
[ERROR] 'dependencies.dependency.version' for org.springframework.security:spring-security-test:jar is missing. @ line 51, column 21
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.github.ankurpathak:facebook-login:0.0.1-SNAPSHOT (/home/ankur/Development/projects/facebook-login/pom.xml) has 2 errors
[ERROR]     Non-resolvable import POM: Could not find artifact org.springframework.security:spring-security-bom:pom:5.1.2.BUILD-SNAPSHOT in spring-snapshots (https://repo.spring.io/snapshot) @ org.springframework.boot:spring-boot-dependencies:2.1.0.RC1, /home/ankur/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.1.0.RC1/spring-boot-dependencies-2.1.0.RC1.pom, line 2856, column 25 -> [Help 2]

The seeing the stack trace I can only see their is something wired with this parent pom and missing some version for spring-security-test.
You can try with this sample:
https://github.com/ankurpathak/facebook-login
By going into parent pom of spring boot spring-boot-starter-parent-2.1.0.RC1.pom at line 2856 I see
this maven coordinates
<dependency>
                <groupId>org.springframework.security</groupId>
                <artifactId>spring-security-bom</artifactId>
                <version>${spring-security.version}</version>
                <type>pom</type>
                <scope>import</scope>
</dependency>
But at this url for 5.2.0.BUILD-SNAPSHOT in Spring SNAPSHOT repo no POM is their:
https://repo.spring.io/snapshot/org/springframework/security/spring-security-bom/5.2.0.BUILD-SNAPSHOT/
But at this url for 5.1.1.BUILD-SNAPSHOT in Spring SNAPSHOt repo we have a pom:
https://repo.spring.io/snapshot/org/springframework/security/spring-security-bom/5.1.1.BUILD-SNAPSHOT/
So I think snapshot is not properly build or pushed. Can you put more on this or correct me.

**Comment by jgrandja** [comment]
@ankurpathak This is not a Spring Boot issue so you should not log the issue there. I'll take a look at this today and get back to you.

**Comment by jgrandja** [comment]
@ankurpathak You can track the `spring-security-bom` issue #6032 for progress. After it's resolved you can re-try the snapshot build.
