### ISSUE TITLE
SEC-341: Retrieving User after AuthenticationException

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#602]
["Mark Kimball":https://jira.spring.io/secure/ViewProfile.jspa?name=mwkimball](Migrated from ["SEC-341":https://jira.spring.io/browse/SEC-341?redirect=false]) said:

In AbstractUserDetailsAuthenticationProvider the authenticate() method calls the additionalAuthenticationChecks() method in a try block and can catch an AuthenticationException.  The code in the catch block (line 147 for rel 1.0.1) calls the retrieveUser() and additionalAuthenticationChecks() methods.  If the user details used for the call in the try block came from the cache, I understand why this makes sense.  However, if cacheWasUsed is false, the call to retrieve the user details obtains the exact same user details.

Perhaps the catch block should only repeat those method calls if cacheWasUsed is true, and throws the caught AuthenticationException if cacheWasUsed is false.

**Comment by spring-issuemaster** [comment]
This issue duplicates #589
