### ISSUE TITLE
Remove PowerMock Dependency

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6025]
PowerMock does not have a GA release that is compatible with JDK 12, nor is one currently planned.

Let's convert tests that are currently using PowerMock so that we can move forward with JDK 12.

**Comment by jzheaux** [comment]
Note that PowerMock released a 2.0.0 version that addresses the JDK 12 issue. because of this, we don't need this as immediately, but will keep it open as there is still value in reducing dependencies. For example, [if Mockito adds support for static methods](https://github.com/mockito/mockito/issues/1013), it would be nice to use only one mocking library going forward.

**Comment by rwinch** [comment]
We can remove the need for powermock for mocking classpath by using https://github.com/spring-projects/spring-boot/tree/b43827d6264a3eb4e9558c6e1dd7f89e537caa96/spring-boot-project/spring-boot-tools/spring-boot-test-support/src/main/java/org/springframework/boot/testsupport/classpath

**Comment by eleftherias** [comment]
Mockito has added support for static methods as of 3.4.0 https://github.com/mockito/mockito/releases/tag/v3.4.0
