### ISSUE TITLE
OAuth2 Bearer token not in compliance with the specs in spring security 5

### ISSUE THREAD

**Issue by viplavfauzdar** [spring-projects/spring-security#6031]
### Summary

It appears that with spring security 5 there has been a change wherein the bearer token CANNOT have the keyword "Bearer" before the token in the authorization header. This is not in compliance with the specifications as per RFC 6750, sec 2.1.

### Actual Behavior

invalid_token error if the bearer token has "Bearer" before the token in the Authorization header. The token is accepted if no "Bearer" keyword. 

### Expected Behavior

It should expect "Bearer" before the token

### Version

spring boot 2.0.2, spring-security-oauth2 2.3.4

**Comment by rwinch** [comment]
@viplavfauzdar Thanks for the report. I realize it is a bit confusing, but this issue is part of a separate project. Can you please create it at https://github.com/spring-projects/spring-security-oauth/issues

**Comment by rwinch** [comment]
Closing as invalid since this is part of another project
