### ISSUE TITLE
POM's not published for spring-security-bom

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#6032]
The POM's for [5.1.2.BUILD-SNAPSHOT](https://repo.spring.io/libs-snapshot/org/springframework/security/spring-security-bom/5.1.2.BUILD-SNAPSHOT/) and [5.2.0.BUILD-SNAPSHOT](https://repo.spring.io/libs-snapshot/org/springframework/security/spring-security-bom/5.2.0.BUILD-SNAPSHOT/) have not been published for `spring-security-bom`.

The `spring-build-conventions` plugin was recently updated to `0.0.20.RELEASE`, which contains an [update](https://github.com/spring-gradle-plugins/spring-build-conventions/commit/c245529dc812e8b04d543911c614131a86ce5e2b) to the `MavenBomPlugin`. It may be related.

**Comment by ankurpathak** [comment]
@jgrandja Any timeline for this issue to get resolved, as its a blocker in trying snapshot  5.1.2 and  5.2..

**Comment by jgrandja** [comment]
Resolved via 2bc156e and dca3645

**Comment by jgrandja** [comment]
@ankurpathak This has been resolved for 5.1.2.BUILD-SNAPSHOT and 5.2.0.BUILD-SNAPSHOT.
Give it a try now.

**Comment by ankurpathak** [comment]
@jgrandja Thanks. Now working like a champ.
