### ISSUE TITLE
XSD documentation for csrf element's token-repository-ref attribute is misleading

### ISSUE THREAD

**Issue by evpaassen** [spring-projects/spring-security#6037]
### Summary

The XML schema definition has an minor issue when it comes to describing the default for the `token-repository-ref` attribute of the `<csrf>` element. This has been the case for many versions now.

### Actual

The documentation reads: 

> The CsrfTokenRepository to use. The default is HttpSessionCsrfTokenRepository

### Expected

It should say: 

> The CsrfTokenRepository to use. The default is HttpSessionCsrfTokenRepository wrapped by LazyCsrfTokenRepository.

You can see the `HttpSessionCsrfTokenRepository` is wrapped here: https://github.com/spring-projects/spring-security/blob/8a475e39be67d34b463b62322959bef71645a126/config/src/main/java/org/springframework/security/config/http/CsrfBeanDefinitionParser.java#L87

The documentation is misleading because overriding the attribute with a reference to a plain `HttpSessionCsrfTokenRepository` will lead to eager token generation, while leaving it default would lead to lazy generation. 

_One scenario in which eager CSRF token generation might be necessary is when Thymeleaf 3 commits a part of the response before accessing the CSRF token. See https://github.com/spring-projects/spring-security/issues/3906#issuecomment-222729442._

### Version

4.x, 5.x

----

I'd be happy to submit a PR, if I'd know where I'd need to fix this and for which versions. I think the xsd is generated from this file for version 5.1:

https://github.com/spring-projects/spring-security/blob/8a475e39be67d34b463b62322959bef71645a126/config/src/main/resources/org/springframework/security/config/spring-security-5.1.rnc#L741

**Comment by rwinch** [comment]
Thanks for offering to submit a PR! Yes this is where to update it. You can then generate the xsd using `./gradlew spring-security-config:rncToXsd`

**Comment by evpaassen** [comment]
I created PR #6038 to address this issue.
