### ISSUE TITLE
Calirfy spring-security/openid is not OpenID Connect

### ISSUE THREAD

**Issue by gburboz** [spring-projects/spring-security#6041]
In [spring-security/openid](/spring-projects/spring-security/tree/master/openid) add README.md file to clarify this component implements `Final OpenID 2.0 specifications (Obsolete)` from [openid.net specifications](https://openid.net/developers/specs/) which is not same as  `OpenID Connect specification`

**Comment by jgrandja** [comment]
@gburboz Have you seen the reference doc for the [`spring-security-openid`](https://docs.spring.io/spring-security/site/docs/5.1.1.RELEASE/reference/htmlsingle/#spring-security-openid) module and section [7.3.4 OpenID Support](https://docs.spring.io/spring-security/site/docs/5.1.1.RELEASE/reference/htmlsingle/#ns-openid)? Both references provide links to the OpenID 2.0 specifications.

We typically don't put README in the modules. All documentation is in the reference or javadoc.

I'm going to close this issue as I feel the existing references are pretty clear to which specification(s) the associated features implement.
