### ISSUE TITLE
Provide a TaskScheduler variant for DelegatingSecurityContextExecutor

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-security#6043]
### Summary

Spring Security provides a `DelegatingSecurityContextRunnable` abstraction for `Runnable` that can be used for async and scheduled tasks. The primary contract for task scheduling is `TaskScheduler` and there's no such wrapper available at the moment.

### Actual Behavior

Users are configuring a `DelegatingSecurityContextScheduledExecutorService` for support of `@EnableScheduling` which is not the primary contract that `@EnableScheduling` expects.

### Expected Behavior

Spring Security provides a `TaskScheduler` variant or the documentation routes users to expose a `TaskScheduler` bean rather than exposing a `ScheduledExecutorService` bean.

This relates to https://github.com/spring-projects/spring-boot/issues/15032 - Spring Framework considers `ScheduledExecutorService` as a fallback of the primary `TaskScheduler` API. It would be nice if Spring Security aligns to that, either in code or in guiding users in the documentation.

**Comment by rwinch** [comment]
Thanks I think we should provide a DelegatingSecurityContextTaskScheduler variant. I think this will be a good first timer issue.

The class `DelegatingSecurityContextTaskScheduler` should be created in the same package as [DelegatingSecurityContextSchedulingTaskExecutor](https://github.com/spring-projects/spring-security/blob/5.1.1.RELEASE/core/src/main/java/org/springframework/security/scheduling/DelegatingSecurityContextSchedulingTaskExecutor.java). The code will be very similar except it will  implement `TaskScheduler`.

We should also create tests for this.

Finally the [documentation](https://github.com/spring-projects/spring-security/blob/5.1.1.RELEASE/docs/manual/src/docs/asciidoc/_includes/servlet/additional-topics/concurrency.adoc) should be updated to include a reference to the new class.

**Comment by avirekghatia** [comment]
I am a first-timer taking this issue if that's okay and will create a PR. Thanks!

**Comment by rwinch** [comment]
Thank you @avirekghatia! The issue is all yours. Let me know if you need any help working on this issue.

**Comment by richardvaldiviesomacias** [comment]
Is this still open?

**Comment by richardvaldiviesomacias** [comment]
👍

**Comment by avirekghatia** [comment]
@rwinch @richardvaldiviesomacias , I think I need a little more reading on the project before I can fix this. If you want to take this issue @richardvaldiviesomacias , feel free. Thank you.

**Comment by richardvaldiviesomacias** [comment]
Sure I will give it a try. Thanks @avirekghatia

**Comment by richardvaldiviesomacias** [comment]
Good afternoon

I finished this issue. I forked the repository and I working on it. How/What is the procedure to request a PR. I am sure that I will do some corrections but I want to send it now. Here is the file from the repository: https://github.com/richardvaldiviesomacias/spring-security. Branch's name gh-6043-TaskScheduler-variant

**Comment by rwinch** [comment]
@richardvaldiviesomacias Thanks for working on this! No problem on needing some corrections that is part of the process! Please go ahead and [submit the PR](https://help.github.com/articles/creating-a-pull-request/) and we can review and refine from there.

**Comment by richardvaldiviesomacias** [comment]
@rwinch I got the latest from Master (without my changes) and it is failing when I run the integration.

**Comment by rwinch** [comment]
@richardvaldiviesomacias Thanks for the ping. I responded on the PR.
