### ISSUE TITLE
The pathMapping overloading is ignored in the OAuth Approval form rendering of the action attribute

### ISSUE THREAD

**Issue by stephaneeybert** [spring-projects/spring-security#6049]
### Summary

The `pathMapping` is effective except for the action attribute of the `OAuth Approval` form rendered in the response to the `/auth/authorize` request.

### Actual Behavior

The action attribute of the `OAuth Approval` form rendered in the response to the `/auth/authorize` request ignores the overloading to `/auth/authorize` and displays the original one `/oauth/authorize`

### Expected Behavior

The action attribute of the `OAuth Approval` form rendered in the response to the `/auth/authorize` request should also display the same value is the one given in the `pathMapping` overload.

### Configuration

	@Override
	public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
		endpoints
		.authenticationManager(authenticationManager)
        .tokenServices(tokenServices())
        .allowedTokenEndpointRequestMethods(HttpMethod.GET, HttpMethod.POST)
		.tokenEnhancer(jwtAccessTokenConverter())
        .accessTokenConverter(jwtAccessTokenConverter())
		.userDetailsService(userDetailsService);

		endpoints
		.pathMapping("/oauth/authorize", RESTConstants.SLASH + DomainConstants.AUTH + RESTConstants.SLASH + DomainConstants.AUTHORIZE)
		.pathMapping("/oauth/token", RESTConstants.SLASH + DomainConstants.AUTH + RESTConstants.SLASH + DomainConstants.TOKEN);
	}

### Version

```
<dependency>
  <groupId>org.springframework.security.oauth.boot</groupId>
  <artifactId>spring-security-oauth2-autoconfigure</artifactId>
  <version>2.0.6.RELEASE</version>
</dependency>
```

### Sample

`endpoints.pathMapping("/oauth/authorize", "/auth/authorize")
`

**Comment by jgrandja** [comment]
@stephaneeybert Can you please log this issue with the [Spring Security OAuth](https://github.com/spring-projects/spring-security-oauth/issues) project.

Also, if you can provide a sample that reproduces the issue this would be very helpful.
Thanks.
