### ISSUE TITLE
For CommonOAuth2Provider: Add support for UAA

### ISSUE THREAD

**Issue by ghillert** [spring-projects/spring-security#6068]
### Summary

In `CommonOAuth2Provider` we provide support for:

- Google
- GitHub
- Facebook
- Okta

I believe we should also explicitly support [Pivotal UAA](https://github.com/cloudfoundry/uaa) as it is one of very few viable production-ready OSS providers for OAuth2 / OpenID Connect (OIC) that can be run _on-premise_.

It seems to get some adoption in other OSS projects as well, e.g.

JHipster - https://www.jhipster.tech/using-uaa/
Federal Government* - https://github.com/bhits/consent2share#technology-stack

It might also be useful to incorporate a UAA example into the Spring Security Documentation itself, e.g. the following sample application by Josh Cummings/Joe Grandja:

https://github.com/jzheaux/messaging-app

 \* Substance Abuse and Mental Health Services Administration

**Comment by tanjie123** [comment]
😊

**Comment by jgrandja** [comment]
@ghillert I'm going to close this as we won't be updating `CommonOAuth2Provider` for the same reason explained for Apple in this [comment](https://github.com/spring-projects/spring-security/issues/9047#issuecomment-701516346).
