### ISSUE TITLE
java.lang.IllegalStateException: Only one connection receive subscriber allowed.

### ISSUE THREAD

**Issue by hfgbarrigas** [spring-projects/spring-security#6071]
### Summary
Trying oauth2 client_credentials integration with webclient but getting the IllegalStateException.

### Configuration
Using a custom provider. Here's the configuration:

```
spring:
  security:
    oauth2:
      client:
        registration:
          iam:
            client-id: my_client_id
            client-secret: my_secret
            provider: as
            clientAuthenticationMethod: basic
            authorizationGrantType: client_credentials
        provider:
          as:
            token-uri: https://my_authorization_server/as/oauth/token
```

My web security is as follows:

```
http
                .authorizeExchange()
                .pathMatchers(resourceServerProperties.getPublicEndpoints().toArray(new String[]{}))
                .permitAll()
                .anyExchange().authenticated()
                .and()
                .csrf()
                .disable()
                .oauth2ResourceServer()
                .jwt()
                .jwtDecoder(nimbusReactiveJwtDecoder)
                .and()
                .and()
                .oauth2Client()
```

Configuring webclient as follows:

```

ServerOAuth2AuthorizedClientExchangeFilterFunction oauth = new ServerOAuth2AuthorizedClientExchangeFilterFunction(clientRegistrationRepo,
                authorizedClientRepo);

        oauth.setDefaultClientRegistrationId(iamReactiveClientProperties.getDefaultClientRegistrationName());
        oauth.setDefaultOAuth2AuthorizedClient(true);

        return WebClient
                .builder()
                .exchangeStrategies(ExchangeStrategies
                        .builder()
                        .codecs(clientDefaultCodecsConfigurer -> {
                            clientDefaultCodecsConfigurer.defaultCodecs().jackson2JsonEncoder(new Jackson2JsonEncoder(objectMapper, MediaType.APPLICATION_JSON));
                            clientDefaultCodecsConfigurer.defaultCodecs().jackson2JsonDecoder(new Jackson2JsonDecoder(objectMapper, MediaType.APPLICATION_JSON));
                        }).build())
                .clientConnector(clientHttpConnector(iamReactiveClientProperties))
                .filter(oauth)
                .build()

```

Webclient usage:

```
webClient
                .get()
                .uri("https://link")
                .accept(MediaType.APPLICATION_JSON)
                .retrieve()
                .bodyToMono(User.class)
                .log()
```

Logs:

> 10:50:23.023Z [reactor-http-nio-2] INFO  r.M.FlatMap.1 - | onSubscribe([Fuseable] MonoFlatMap.FlatMapMain)
> 10:50:23.023Z [reactor-http-nio-2] INFO  r.M.P.2 - | onSubscribe([Fuseable] MonoPeekTerminal.MonoTerminalPeekSubscriber)
> 10:50:23.023Z [reactor-http-nio-2] INFO  r.M.P.2 - | request(unbounded)
> 10:50:23.023Z [reactor-http-nio-2] INFO  r.M.FlatMap.1 - | request(unbounded)
> 10:50:23.023Z [reactor-http-nio-2] INFO  r.M.P.2 - | onContextUpdate(Context2{interface org.springframework.web.server.ServerWebExchange=org.springframework.web.server.adapter.DefaultServerWebExchange@5011f74c, interface org.springframework.security.core.context.SecurityContext=MonoFlatMap})
> 10:50:23.023Z [reactor-http-nio-2] INFO  r.M.FlatMap.1 - | onContextUpdate(Context2{interface org.springframework.web.server.ServerWebExchange=org.springframework.web.server.adapter.DefaultServerWebExchange@5011f74c, interface org.springframework.security.core.context.SecurityContext=MonoFlatMap})
> 10:50:23.023Z [reactor-http-nio-2] INFO  r.M.P.2 - | onContextUpdate(Context2{interface org.springframework.web.server.ServerWebExchange=org.springframework.web.server.adapter.DefaultServerWebExchange@5011f74c, interface org.springframework.security.core.context.SecurityContext=MonoFlatMap})
> 10:50:23.023Z [reactor-http-nio-2] INFO  r.M.FlatMap.1 - | onContextUpdate(Context2{interface org.springframework.web.server.ServerWebExchange=org.springframework.web.server.adapter.DefaultServerWebExchange@5011f74c, interface org.springframework.security.core.context.SecurityContext=MonoFlatMap})
> 10:50:23.023Z [reactor-http-nio-2] INFO  r.M.P.2 - | onContextUpdate(Context2{interface org.springframework.web.server.ServerWebExchange=org.springframework.web.server.adapter.DefaultServerWebExchange@5011f74c, interface org.springframework.security.core.context.SecurityContext=MonoFlatMap})
> 10:50:23.023Z [reactor-http-nio-2] INFO  r.M.FlatMap.1 - | onContextUpdate(Context2{interface org.springframework.web.server.ServerWebExchange=org.springframework.web.server.adapter.DefaultServerWebExchange@5011f74c, interface org.springframework.security.core.context.SecurityContext=MonoFlatMap})
> 10:50:23.023Z [reactor-http-nio-2] INFO  r.M.P.2 - | onContextUpdate(Context2{interface org.springframework.web.server.ServerWebExchange=org.springframework.web.server.adapter.DefaultServerWebExchange@5011f74c, interface org.springframework.security.core.context.SecurityContext=MonoFlatMap})
> 10:50:23.023Z [reactor-http-nio-2] INFO  r.M.FlatMap.1 - | onContextUpdate(Context2{interface org.springframework.web.server.ServerWebExchange=org.springframework.web.server.adapter.DefaultServerWebExchange@5011f74c, interface org.springframework.security.core.context.SecurityContext=MonoFlatMap})
> 10:50:23.023Z [reactor-http-nio-2] INFO  r.M.P.2 - | onContextUpdate(Context2{interface org.springframework.web.server.ServerWebExchange=org.springframework.web.server.adapter.DefaultServerWebExchange@5011f74c, interface org.springframework.security.core.context.SecurityContext=MonoFlatMap})
> 10:50:23.023Z [reactor-http-nio-2] INFO  r.M.FlatMap.1 - | onContextUpdate(Context2{interface org.springframework.web.server.ServerWebExchange=org.springframework.web.server.adapter.DefaultServerWebExchange@5011f74c, interface org.springframework.security.core.context.SecurityContext=MonoFlatMap})
> 10:50:23.023Z [reactor-http-nio-2] INFO  r.M.P.2 - | onContextUpdate(Context2{interface org.springframework.web.server.ServerWebExchange=org.springframework.web.server.adapter.DefaultServerWebExchange@5011f74c, interface org.springframework.security.core.context.SecurityContext=MonoFlatMap})
> 10:50:23.023Z [reactor-http-nio-2] INFO  r.M.FlatMap.1 - | onContextUpdate(Context2{interface org.springframework.web.server.ServerWebExchange=org.springframework.web.server.adapter.DefaultServerWebExchange@5011f74c, interface org.springframework.security.core.context.SecurityContext=MonoFlatMap})
> 10:50:24.024Z [reactor-http-nio-2] ERROR r.M.FlatMap.1 - | onError(java.lang.IllegalStateException: Only one connection receive subscriber allowed.)
> 10:50:24.024Z [reactor-http-nio-2] ERROR r.M.FlatMap.1 - 
> java.lang.IllegalStateException: Only one connection receive subscriber allowed.
> 	at reactor.netty.channel.FluxReceive.startReceiver(FluxReceive.java:277)
> 	at reactor.netty.channel.FluxReceive.subscribe(FluxReceive.java:127)

### Version
Spring version: 5.1.1.RELEASE
Reactor Netty version: 0.8.2.RELEASE
Reactor Core version: 3.2.2.RELEASE

### Sample

https://github.com/hfgbarrigas/oauth2client-webflux-error-sample

**Comment by rwinch** [comment]
The problem seems that Spring Security is not handling a redirect properly. The redirect is happening when the request for a token is being submitted to http://dev.hold.co/as/oauth/token To fix it change your configuration to use https `token-uri: https://dev.hold.co/as/oauth/token`

I will investigate how to get a proper error message to the user. In the meantime, hopefully this helps you make some progress.

**Comment by rwinch** [comment]
The reason for the strange error message is [SPR-17482](https://jira.spring.io/browse/SPR-17482). If [you update](https://github.com/hfgbarrigas/oauth2client-webflux-error-sample/pull/1) to Spring Framework 5.1.3.BUILD-SNAPSHOT the error is now a 401. 

```
HTTP/1.1 500 Internal Server Error
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Length: 133
Content-Type: application/json;charset=UTF-8
Expires: 0
Pragma: no-cache
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1 ; mode=block

{
    "error": "Internal Server Error",
    "message": "401 Unauthorized",
    "path": "/test",
    "status": 500,
    "timestamp": "2018-11-14T02:13:55.091+0000"
}

```

This makes sense since the token was unable to be gotten. We should obviously improve our error message, but at least now all the pieces make sense.

**Comment by rwinch** [comment]
@hfgbarrigas Yes please do create a new ticket with these details. Thanks!

**Comment by hfgbarrigas** [comment]
Here: [6087](https://github.com/spring-projects/spring-security/issues/6087)

Thank you.

**Comment by rwinch** [comment]
Thanks. I'm closing this in favor of the two Spring Security issues we created and the fixed Spring Framework JIRA
