### ISSUE TITLE
fix typo in reference docs: not JacksonJacksonModules but SecurityJacksonModules 

### ISSUE THREAD

**Issue by dongmyo** [spring-projects/spring-security#6076]
### Summary

a typo error in spring security reference
not `JacksonJacksonModules` but `SecurityJacksonModules`

https://github.com/spring-projects/spring-security/blob/master/docs/manual/src/docs/asciidoc/_includes/servlet/architecture/jackson.adoc

### Actual Behavior

To use it, register the `JacksonJacksonModules.getModules(ClassLoader)` ...

### Expected Behavior

To use it, register the `SecurityJacksonModules.getModules(ClassLoader)` ...

### Version

5.1.1.RELEASE

**Comment by jzheaux** [comment]
@dongmyo, thanks for the report! Would you like to submit a PR with the correction?
