### ISSUE TITLE
Failure to generate client credentials token with WebClient in test

### ISSUE THREAD

**Issue by DarrenForsythe** [spring-projects/spring-security#6083]
### Summary

I am writing an Autoconfiguration lib to centralize some security configuration such as user auth mapping, JWT Validation etc.

As part of this I'm trying to generate a JWT using my IDP provider, however it will always fail due to an exception in the in the HttpSessionOAuth2AuthorizedClientRepository as the HttpServletRequest is null.

I did ask the question on [StackoverFlow](https://stackoverflow.com/questions/53190850/spring-security-5-1-get-token-for-client-credentials-flow-with-webclient), but I am unsure if it is an issue or I am misreading the docuemtnation on WebClient and its support for client credentials flow. 

I'm using an Interface `IdpSecurityAdapter` to apply client specific configurations and feed into a singular `WebSecurityConfigurationAdapter` in the autoconfiguration. 

All other tests I've generated i.e. around the loading and execution of the Autoconfiguration work, usage of the interface to apply client specifc security to a singular `WebSecurityConfigurationAdapter` all pass.

### Actual Behavior

The configured `WebClient` will always fail to generate a JWT via my IDP Provider as the HttpServletRequest is null.

### Expected Behavior

The WebClient sucessfully calls the IDP provider and gets a JWT to call secured API

### Configuration

```
@SpringBootTest(classes = WebITApplication.class,
        webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ExtendWith(SpringExtension.class)
@ActiveProfiles("web-it")
class WebJwtIt {

    @LocalServerPort
    private int port;

    @Autowired
    private WebClient webClient;

    @Test
    void testIdpJwt() {

        String response = webClient.get().uri("http://localhost:" + port + "/web/it")
                .attributes(ServletOAuth2AuthorizedClientExchangeFilterFunction.clientRegistrationId("ping")).retrieve()
                .bodyToMono(String.class).block();
        assertThat(response).isEqualTo("pass");
    }

    @RestController
    @SpringBootApplication
    @ImportAutoConfiguration(IdpAutoConfiguration.class)
    static class WebITApplication implements IdpSecurityAdapter {

              @Bean
    WebClient webClient(ClientRegistrationRepository clientRegistrations,
            OAuth2AuthorizedClientRepository authorizedClients) {
        ServletOAuth2AuthorizedClientExchangeFilterFunction oauth = new ServletOAuth2AuthorizedClientExchangeFilterFunction(
                clientRegistrations, authorizedClients);
        // (optional) explicitly opt into using the oauth2Login to provide an access token implicitly
        // oauth.setDefaultOAuth2AuthorizedClient(true);
        // (optional) set a default ClientRegistration.registrationId
        // oauth.setDefaultClientRegistrationId("client-registration-id");
        return WebClient.builder().apply(oauth.oauth2Configuration()).build();
    }
        public static void main(String args[]) {

            new SpringApplicationBuilder().profiles("web-it").build().run(WebITApplication.class, args);
        }

        @GetMapping
        public String secured() {
            return "secured";
        }

        @GetMapping("/web/it")
        public String securedOne() {
            return "pass";
        }

        @Override
        public void configure(final HttpSecurity httpSecurity) throws IdpSecurityAdapterException {
            try {
                httpSecurity.oauth2Client();
            } catch (Exception e) {
                throw new IdpSecurityAdapterException("Failed to Configure Oauth2Client", e);
            }
        }

        @Override
        public IdpProvider getIdpProvider() {
            return IdpProvider.MyIdp;
        }
    }
```
Yml props, 

```
spring:
  security:
    oauth2:
      client:
        registration:
          idp:
            clientId: id
            clientSecret: secret
            authorization-grant-type: client_credentials
            scope: read
        provider:
          idp:
            authorization-uri: myidp/authorization.oauth2
            token-uri: myidp/token.oauth2
            user-info-uri: myidp/userinfo.openid
            user-name-attribute: name
```

WebClient is bean'd directly, 

```
    @Bean
    WebClient webClient(ClientRegistrationRepository clientRegistrations,
            OAuth2AuthorizedClientRepository authorizedClients) {
        ServletOAuth2AuthorizedClientExchangeFilterFunction oauth = new ServletOAuth2AuthorizedClientExchangeFilterFunction(
                clientRegistrations, authorizedClients);
        // (optional) explicitly opt into using the oauth2Login to provide an access token implicitly
        // oauth.setDefaultOAuth2AuthorizedClient(true);
        // (optional) set a default ClientRegistration.registrationId
        // oauth.setDefaultClientRegistrationId("client-registration-id");
        return WebClient.builder().apply(oauth.oauth2Configuration()).build();
    }
```

Using the WebClient as, 

```
webClient.get().uri("http://localhost:" + port + "/web/it")
                .attributes(ServletOAuth2AuthorizedClientExchangeFilterFunction.clientRegistrationId("idp")).retrieve()
                .bodyToMono(String.class).block();
```

### Version

Spring Boot 2.1 release.

### Sample

Not yet.

**Comment by rwinch** [comment]
I think I need some more context. What is happening is that since no user is authenticated, the WebClient is trying to read/write to the HttpSession from the HttpServletRequest. This means you have a a couple options:

1) You can populate the RequestContextHolder with a mock (in a servlet container t this is done using a Filter automatically for you). 
2) You can run as an authenticated user in which case, the HttpSession is no longer used for read/writes. This can be done by annotating the test using `@WithMockUser`. Keep in mind that the access token is stored and be used across any shared ApplicationContexts at that point.

Let me know if this helps or not. If not, throw together a complete sample and I can try and provide you more concrete help.

**Comment by DarrenForsythe** [comment]
Ah that's got me a step closer than I was before, I think I understand. I was poorly assuming that WebClient wasn't dependent on some sort of Session/Authenticated user being there. e.g. I assumed it could be used like the old `OAuth2RestTemplate` without any container/servlet/etc. being there. 

Thank you @rwinch  for the response 👍

**Comment by rwinch** [comment]
It can be, but the default configuration assumes that the request/response is there. There is a third option where you configure it using something like [this](https://github.com/rwinch/webclientoauth2-cli/blob/master/src/main/java/sample/WebClientOAuth2Application.java)

Of course at that point it doesn't integrate with your servlet application.

I'm going to close this as it appears you have moved passed this issue.
