### ISSUE TITLE
WebClientReactiveClientCredentialsTokenResponseClient should fail if not 2xx status

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#6089]
### Summary

If anything but a 2xx status is returned (i.e. a redirect) when trying to get the token, we should fail

See #6071

**Comment by raphaelDL** [comment]
maybe something like this? 🤔

```java
return this.webClient.post()
					.uri(tokenUri)
					.accept(MediaType.APPLICATION_JSON)
					.headers(headers(clientRegistration))
					.body(body)
					.exchange()
					.filterWhen(response -> Mono.just(!response.statusCode().is2xxSuccessful()))
					.flatMap(response -> response.body(oauth2AccessTokenResponse()))
					.map(response -> {
						if (response.getAccessToken().getScopes().isEmpty()) {
							response = OAuth2AccessTokenResponse.withResponse(response)
								.scopes(authorizationGrantRequest.getClientRegistration().getScopes())
								.build();
						}
						return response;
					});
		});
´´´

**Comment by rwinch** [comment]
Thanks for the comment!

* You can simplify it using .filter which does not require a `Mono`
* We should `switchIfEmpty` with a `Mono.error` that contains a message stating that the attempt to get the token returned an unsuccessful status along with the status code.

Would you like to take this one @raphaelDL?

**Comment by raphaelDL** [comment]
yup

**Comment by rwinch** [comment]
Thanks @raphaelDL! As always let me know if you have any questions!

**Comment by raphaelDL** [comment]
Not completely sure how to approach this, if I filter the response just after I call exchange, I won't be able to recover the status at the end when calling swtchIfEmpty. Should I replay the mono values ?

I tried this:

´´´java
return this.webClient.post()
					.uri(tokenUri)
					.accept(MediaType.APPLICATION_JSON)
					.headers(headers(clientRegistration))
					.body(body)
					.exchange()
					.map(response ->{
						if(!response.statusCode().is2xxSuccessful()){
							throw
									WebClientResponseException.create(response.rawStatusCode(),
											"Cannot get token, expected 2xx HTTP Status code",
											null,
											null,
											null
									);
						}; return response;
					})
					.flatMap(response -> response.body(oauth2AccessTokenResponse()))
					.map(response -> {
						if (response.getAccessToken().getScopes().isEmpty()) {
							response = OAuth2AccessTokenResponse.withResponse(response)
								.scopes(authorizationGrantRequest.getClientRegistration().getScopes())
								.build();
						}
						return response;
					});
		});
´´´

and my test should be annotated with
´@Test(expected = WebClientResponseException.class)´

what do you think @rwinch  ???


Also, when using `org.springframework.web.reactive.function.client.DefaultWebClient´  and calling retrieve instead of exchange  we can use the onStatus method, I has a very nice implementation default but it's private :( 


```java
@Override
		public ResponseSpec onStatus(Predicate<HttpStatus> statusPredicate,
				Function<ClientResponse, Mono<? extends Throwable>> exceptionFunction) {

			if (this.statusHandlers.size() == 1 && this.statusHandlers.get(0) == DEFAULT_STATUS_HANDLER) {
				this.statusHandlers.clear();
			}
			this.statusHandlers.add(new StatusHandler(statusPredicate, exceptionFunction));

			return this;
		}

´´´

**Comment by rwinch** [comment]
I'd change it slightly:

```java
.exchange()
.flatMap(response -> {
	// extract the contents of this into a method named oauth2AccessTokenResponse but has an argument for the response
	if(!response.statusCode().is2xxSuccessful()){
		throw WebClientResponseException.create(response.rawStatusCode(),
			"Cannot get token, expected 2xx HTTP Status code",
			null,
			null,
			null
			);
	};
        return response.body(oauth2AccessTokenResponse());
})
```

We are avoiding retrieve because it doesn't have the ability to use a BodyExtractor. Additionally, we don't want to be able to have full control over how the errors are handled, but using retrieve means that if there is an error it will create it's own exception.

**Comment by raphaelDL** [comment]
I understand, ok, I use your suggestion :)

**Comment by rwinch** [comment]
Sounds great. Thanks again for working on this!
