### ISSUE TITLE
OAuth2ResourceServerConfigurerTests should avoid MockWebServer

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6104]
Now that there is support to create a `JWTProcessor` using a `RestOperations`, several of the tests in `OAuth2ResourceServerConfigurerTests` that relied on a `MockWebServer` can now rely on a mock `RestOperations`, making the tests faster.

Or, as an alternative, they could be configured to use a single key instead of a JWK Set, where applicable.

**Comment by govi20** [comment]
if this is a trivial change, I would like to work on it.

**Comment by rwinch** [comment]
This should be pretty easy. The issue is yours

**Comment by govi20** [comment]
I had a look into `OAuth2ResourceServerConfigurerTests`.
There are two options suggested by @jzheaux 

1. Replace MockWebServer with the mock of the `MockWebServer`

**Comment by jzheaux** [comment]
@govi20 Many of these tests use a common spring configuration, [declared there in the tests class itself](https://github.com/spring-projects/spring-security/blob/master/config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests.java#L157). In most cases, the reference to `WebServerConfig` will be removed along with the line [to configure its mock response](https://github.com/spring-projects/spring-security/blob/master/config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests.java#L158).

For example, in the case of this test:

```java
@Test
public void getWhenUsingDefaultsWithValidBearerTokenThenAcceptsRequest()
		throws Exception {

	this.spring.register(WebServerConfig.class, DefaultConfig.class, BasicController.class).autowire();
	this.authz.enqueue(this.jwks("Default"));
	String token = this.token("ValidNoScopes");

	this.mvc.perform(get("/").with(bearerToken(token)))
			.andExpect(status().isOk())
			.andExpect(content().string("ok"));
}
```

I would change this to:

```java
@Test
public void getWhenUsingDefaultsWithValidBearerTokenThenAcceptsRequest()
		throws Exception {

	this.spring.register(SingleKeyConfig.class, BasicController.class).autowire();
	String token = this.token("ValidNoScopes");

	this.mvc.perform(get("/").with(bearerToken(token)))
			.andExpect(status().isOk())
			.andExpect(content().string("ok"));
}
```

Many of the tests don't actually need to be configured with a JWK Set URI to confirm their functionality since that is not what they are testing. [In those cases](https://github.com/spring-projects/spring-security/blob/master/config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests.java#L154), a single key is preferred. 

[When the JWK Set endpoint is being tested](https://github.com/spring-projects/spring-security/blob/master/config/src/test/java/org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurerTests.java#L180), then it should use a `RestOperations`, as you have outlined.

For example, this test:

```java
@Test
public void getWhenUsingDefaultsWithBadJwkEndpointThenInvalidToken()
	throws Exception {

	this.spring.register(WebServerConfig.class, DefaultConfig.class).autowire();
	this.authz.enqueue(new MockResponse().setBody("malformed"));
	String token = this.token("ValidNoScopes");

	this.mvc.perform(get("/").with(bearerToken(token)))
			.andExpect(status().isUnauthorized())
			.andExpect(invalidTokenHeader("An error occurred while attempting to decode the Jwt: Malformed Jwk set"));
}
```

Could change to:

```java
@Test
public void getWhenUsingDefaultsWithBadJwkEndpointThenInvalidToken()
	throws Exception {

	this.spring.register(RestOperationsConfig.class).autowire();
	mockRestOperationsToHaveResponse("malformed");
	String token = this.token("ValidNoScopes");

	this.mvc.perform(get("/").with(bearerToken(token)))
			.andExpect(status().isUnauthorized())
			.andExpect(invalidTokenHeader("An error occurred while attempting to decode the Jwt: Malformed Jwk set"));
}
```

**Comment by jzheaux** [comment]
@govi20 Wanted to see if you had any other questions. And are you still wanting to work on this?

**Comment by govi20** [comment]
Yes. I will give it a try on upcoming Saturday, Sunday.

**Comment by govi20** [comment]
@jzheaux I have started working on it. are we planning to remove `WebServerConfig(MockWebServer)` from every test case of targeted class? or there are scenario's for which we may need. is there any caveat?

**Comment by jzheaux** [comment]
@govi20 Nice!

Yes, let's keep it for just one "happy path" `jwkSetUri` test. The reason is that when a `RestOperations` is wired, it actually changes out Nimbus's `ResourceRetriever` for a custom one. Having one where we just wire the URI will demonstrate that we work without the `RestOperations` customization.

Looking through the tests just now, after your changes you might not have a "happy path" `jwkSetUri` test left over. If that is the case, feel free to add one like, `getWhenUsingJwkSetUriThenAcceptsRequest` that uses `WebServerConfig` and a valid JWT.

**Comment by govi20** [comment]
I have removed `WebServerConfig` from some test cases, from some test cases I could remove this config. Also, I am unable to figure out the `RestOperations` functionality,  `restTemplate.exchange` will need active endpoint. I know I am terribly slow, If it needs to be fixed earliest, someone else can work on it.

**Comment by jzheaux** [comment]
@govi20 Your pace is just fine, thanks for checking in.

What I'd do is mock `RestOperations` using Mockito. Are you having problems with that approach?

**Comment by jzheaux** [comment]
@govi20 How are things coming? Are you able to mock `RestOperations`?

Here is an idea if you are stuck:

```java
private void mockRestOperationsToHaveResponse(String response) {
	RestOperations rest = this.spring.getContext().getBean(RestOperations.class);
	when(rest.exchange(any(RequestEntity.class), eq(String.class)))
			.thenReturn(new ResponseEntity<>(response, HttpStatus.OK));
}
	
static class RestOperationsConfig extends WebSecurityConfigurerAdapter {
	private final RestOperations rest = mock(RestOperations.class);
	
	// ...

	@Bean
	RestOperations rest() {
		return this.rest;
	}
}
```
