### ISSUE TITLE
Update to Gradle 4.10.2

### ISSUE THREAD

**Issue by raphaelDL** [spring-projects/spring-security#6106]
With current version of Gradle 4.10.1 when I run a task with

`./gradlew ...`

I get these warnings:

`> Configure project :spring-security-aspects
The Task.deleteAllActions() method has been deprecated. This is scheduled to be removed in Gradle 5.0.`

`> Configure project :spring-security-samples-javaconfig-x509
Found slf4j-api dependency but no providers were found.  Did you mean to add slf4j-simple? See https://www.slf4j.org/codes.html#noProviders .`

What if we do the next?

1) Upgrade Gradle
`./gradlew wrapper --gradle-version 4.10.2 `

2) Update `buildSrc/src/main/groovy/aspectj/AspectJPlugin.groovy`

from `javaCompileTask.deleteAllActions()`
to
`javaCompileTask.setActions new ArrayList(0)` or `javaCompileTask.setActions Arrays.asList()`

3) Update `/samples/javaconfig/x509/spring-security-samples-javaconfig-x509.gradle`
Remove ` compile 'org.slf4j:slf4j-api'`

**Comment by rwinch** [comment]
@raphaelDL I am not sure I understand this issue. Did you try to update to Gradle 4.10.2 and it failed? I know there are warnings, but that seems distinct from the subject of `Update to Gradle 4.10.2`. Can you help me understand please?

**Comment by rwinch** [comment]
Thanks. Yes. We'd love to update to a newer version of Gradle and (in separate PRs as you mentioned) remove the deprecated APIs.
