### ISSUE TITLE
java.lang.IllegalArgumentException: exchange cannot be null

### ISSUE THREAD

**Issue by hfgbarrigas** [spring-projects/spring-security#6111]
### Summary
When executing an external http request with WebClient using _client_credentials_ I get the mentioned exception. The request is done outside of an exchange of external origin, e.g: 

```

@RequestMapping(value = "/test", produces = {"application/json"}, method = RequestMethod.GET)
    public Mono<ResponseEntity<Void>> test() {
        webClient
                .get()
                .uri("https://api-dev.hold.co/iam/v1/user/6")
                .accept(MediaType.APPLICATION_JSON)
                .retrieve()
                .bodyToMono(Object.class)
                .map(ResponseEntity::ok)
                .log()
                .subscribeOn(Schedulers.elastic())
                .subscribe();

        return Mono.just(ResponseEntity.ok().build());
    }

```

After debugging found that on line 47 of **WebSessionServerOAuth2AuthorizedClientRepository** forces the authorized request _exchange_ not to be null. I'll debug further to understand why the exchange is null at that point, and if its expected to fail. _getAuthorizedClients_ seems to to be able to deal with a nullable session.

### Actual Behavior
java.lang.IllegalArgumentException: exchange cannot be null

### Expected Behavior
Able to the deal with authorized requests in the background.

### Version
**5.1.2.BUILD-SNAPSHOT**
### Sample

https://github.com/hfgbarrigas/oauth2client-webflux-error-sample

**Comment by rwinch** [comment]
For Reactor Context to work you need to return the `Mono` of `WebClient`. So use...

```
return webClient
                .get()
                .uri("https://api-dev.hold.co/iam/v1/user/6")
                .accept(MediaType.APPLICATION_JSON)
                .retrieve()
                .bodyToMono(Object.class)
                .map(ResponseEntity::ok);
```

**Comment by hfgbarrigas** [comment]
Right, but then we can't really make anything outside the request pipeline.

E.g: Deal with an external request processing after saving it.

```
this.repository.save(something)
.doOnSuccess(aVoid -> this.notifications.sendNotification(notificationDetails))
```

I do realize that this can be achieved in different approaches, but in this particular case, without explicitly passing around the `ServerWebExchange` through _subscriberContext(ctx -> ctx.put())_ we can't leverage authorization.

Why is ServerWebExchange mandatory?

**Comment by rwinch** [comment]
It is only mandatory for the particular `ServerOAuth2AuthorizedClientRepository` implementation you are using. This is necessary because it supports storing values in a `WebSession` which is only accessible from the `ServerWebExchange`.

If you don't need support for saving in a `ServerWebExchange`, then you can change the implementation. For example, [this application](https://github.com/rwinch/webclientoauth2-cli) is a CLI application and [uses UnAuthenticatedServerOAuth2AuthorizedClientRepository](https://github.com/rwinch/webclientoauth2-cli/blob/master/src/main/java/sample/WebClientOAuth2Application.java#L23)

**Comment by hfgbarrigas** [comment]
After reading your comment decided to do a bit more digging. Found the default ServerOAuth2AuthorizedClientRepository used, which is AuthenticatedPrincipalServerOAuth2AuthorizedClientRepository that deals delegates to different repository implementations based on the _principal_ being authenticated or not.

**WebSessionServerOAuth2AuthorizedClientRepository** - Requires an existing _ServerWebExchange_ since the principal will be authenticated.

**UnAuthenticatedServerOAuth2AuthorizedClientRepository** - Does not require a ServerWebExchange since the principal will be anonymous.

Thankfully, **AuthenticatedPrincipalServerOAuth2AuthorizedClientRepository** does have a setter to override the default _anonymousAuthorizedClientRepository_, because the default for anonymous principals is **WebSessionServerOAuth2AuthorizedClientRepository** (line 20 of AuthenticatedPrincipalServerOAuth2AuthorizedClientRepository). In my opinion, making the default **UnAuthenticatedServerOAuth2AuthorizedClientRepository** should provide better results since everything will work out of the box (spring?. 

Thanks, you may close this issue if you're not keen on changing the default.

**Comment by rwinch** [comment]
@hfgbarrigas Thanks for the follow up.

The default was chosen in Boot and is quite deliberate as we feel like it covers more use cases. The existing setup works for users who are not authenticated. Please keep in mind that anything that leverages a Reactor Context will fail if it is not chained as I described above.

Given the above, I'm going to close the report. Thanks again for the report and taking the time to help make Spring better!
