### ISSUE TITLE
WebFlux and OAuth2 Custom Roles

### ISSUE THREAD

**Issue by ayudovin** [spring-projects/spring-security#6123]
I used SSO based on Google and WebFlux and I don't know how to add own role in authentication. Now I have only ROLE_USER which was provided by google.
Can you give me any advice ?

**Comment by ayudovin** [comment]
@jgrandja, thank you for your help. It works!!!

**Comment by rwinch** [comment]
Thanks for the feedback @ayudovin! I'm closing this since you got it working

**Comment by suchorski** [comment]
What if the roles change when a user is logged in. E.g. if I remove a role from another user. How to force the refresh of this user because he lost a role and he doesn't have access to some resource anymore.
