### ISSUE TITLE
Remove unused compile dependency in javaconfig x509 sample

### ISSUE THREAD

**Issue by raphaelDL** [spring-projects/spring-security#6130]
When building the project a warning is thrown stating that `org.slf4j:slf4j-api` is defined in `samples/javaconfig/x509/spring-security-samples-javaconfig-x509.gradle` but no implementation is given.

If we remove it we get rid of this warning and have a cleaner building process

Should we remove it?

**Comment by jgrandja** [comment]
@raphaelDL `org.slf4j:slf4j-api` is actually used as it's brought in as a transitive dependency for `org.slf4j:jcl-over-slf4j`, `org.slf4j:jul-to-slf4j`, and `org.slf4j:log4j-over-slf4j`.

What's the exact warning message you're getting when you run the build?

**Comment by raphaelDL** [comment]
oh god, that’s what I thought... 

‘> Configure project :spring-security-samples-javaconfig-x509 Found slf4j-api dependency but no providers were found. Did you mean to add slf4j-simple? See https://www.slf4j.org/codes.html#noProviders .’

**Comment by jgrandja** [comment]
@raphaelDL I see `logback.xml` in the project but no `logback-classic.jar` dependency declared. I think you can add this dependency and remove the other 3x dependencies. See [Binding with a logging framework at deployment time](https://www.slf4j.org/manual.html#swapping).

Give that a try and I think it should resolve the warning.

**Comment by raphaelDL** [comment]
You're all right, it worked.... I pushed a change @jgrandja. Thank you very much for your suggestion

**Comment by raphaelDL** [comment]
I dropped
```
	compile 'org.slf4j:jcl-over-slf4j'
 	compile 'org.slf4j:jul-to-slf4j'
 	compile 'org.slf4j:log4j-over-slf4j'
 	compile 'org.slf4j:slf4j-api'
```

and put
```
compile 'ch.qos.logback:logback-classic'
```
instead
