### ISSUE TITLE
SEC-353: Acegi only checks current class interfaces against rules

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#614]
["Carlos Sanchez":https://jira.spring.io/secure/ViewProfile.jspa?name=carlos](Migrated from ["SEC-353":https://jira.spring.io/browse/SEC-353?redirect=false]) said:

A implements I
B extends A

If method definition specifies I methods ( eg. I.myMethod() ) and the invoked class is B then method is not securited.

MethodDefinitionMap 201-202

```
    // Add attributes explicitly defined for this method invocation's interfaces
    Class[] interfaces = method.getDeclaringClass().getInterfaces();
```

**Comment by spring-issuemaster** [comment]
This issue duplicates #360
