### ISSUE TITLE
SEC-355: Scheme not supported in AbstractProcessingFilter.defaultTargetUrl

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#616]
["Damien Hollis":https://jira.spring.io/secure/ViewProfile.jspa?name=dphollis](Migrated from ["SEC-355":https://jira.spring.io/browse/SEC-355?redirect=false]) said:

The JavaDoc for AbstractProcessingFilter states that the defaultTargetUrl supports absolute URLs by starting with a scheme name (the JavaDoc says: The <code>defaultTargetUrl</code> will be treated as relative to the web-app's context path, and should include the leading <code>/</code>. Alternatively, inclusion of a scheme name (eg http:// or https://) as the prefix will denote a fully-qualified URL and this is also supported.)

However, the actual code that builds the redirect URL looks like:

```
        targetUrl = request.getContextPath() + getDefaultTargetUrl();
```

and therefore the full URL just gets appended to the contextPath.

As an aside, it would also be useful if the code for determining the targetUrl was factored out so that it could be overridden easily. 

Regards,
Damien

**Comment by spring-issuemaster** [comment]
This issue duplicates #557
