### ISSUE TITLE
Fix broken link about Squashing Commits

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6181]
The [contribution guidelines](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#squash-commits) link to a guide about squashing commits, but [that link](http://book.git-scm.com/4_interactive_rebasing.html) is broken.

Let's change it to https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by mibo** [comment]
Fixing documentation is not so popular.
At least this is my explanation why this 'first-timer' is open longer then a day  ;o)
However I want to contribute and I additionally know that documentation is important.

Here is the PR: https://github.com/spring-projects/spring-security/pull/6203

For the case is missed something please let me know.

**Comment by rwinch** [comment]
Thanks for the PR @mibo! This is now merged into master

We hope to see you contribute again soon! If you are looking for issues we have been adding help wanted label to issues that are a bit less challenging. Of course if you find any issue you want to work on, just mention it in the comments and we can go from there. Thanks again for taking the time to help make the Spring community better!
