### ISSUE TITLE
Spring Security helloworld-boot instructions are out of date

### ISSUE THREAD

**Issue by davidnewcomb** [spring-projects/spring-security#6184]
### Summary
Documentation is out of date

### Version

The page:
https://docs.spring.io/spring-security/site/docs/current/guides/html5/helloworld-boot.html

### Problem

Section "Obtaining the sample project" tells you to download [Spring Security Distribution](https://github.com/spring-projects/spring-security/archive/5.1.2.RELEASE.zip).

Section "Import the insecure sample application" tells you to import an **Existing Maven Projects**. The zip above does not contain any pom.xml files. Quite a bit of the page is maven focused. I think it has been converted to a Gradle project.

### What I want
Please can you add instructions on how to get the project running using Gradle. With maven you can build from any sub-folder, not sure you can do that with Gradle. Anyway it means that I'm now side tracked from following your tutorial and into the pain of figuring out how to set things up so I can run your tutorial.

**Comment by rwinch** [comment]
Thanks for the report @davidnewcomb! Sorry for your trouble. We have a duplicate of #5026 and more generally in #2567

I'm closing this as a duplicate. If you disagree, please reply/repopen this ticket.
