### ISSUE TITLE
Add Max Session to WebFlux

### ISSUE THREAD

**Issue by bentenzheng** [spring-projects/spring-security#6192]
When i am using webflux , how can i achieve a similar effect ,get all login user session ,
like as : 
   http.sessionManagement() .maximumSessions(1).sessionRegistry(getSessionRegistry()).maxSessionsPreventsLogin(false)

**Comment by rwinch** [comment]
We do not currently support max sessions in WebFlux. I converted this issue into a ticket for that support

**Comment by rwinch** [comment]
@ankurpathak Sure! The ticket is yours

**Comment by ankurpathak** [comment]
@rwinch What is equivalent of SessionRegistry in reactive world?
I think we would need ReactiveSessionRegistry for this issue as using SessionRegistry may be non
blocking for InMemoryImplementatio but may be blocking for SessionRegistry implemenation for
Redis, Mongo, JDBC in Spring Session.

**Comment by mukeshkamboj** [comment]
@rwinch 
Do we have any solution?

**Comment by ankurpathak** [comment]
@mukeshkamboj @rwinch I am not working on this.

**Comment by issilin** [comment]
@rwinch 
Still relevant? May I suggest a solution?

**Comment by Johannes-Rost** [comment]
Is this ticket still considered relevant?
The ability to control the number of parallel sessions is often requested in reviews as a security function.

**Comment by rishisc** [comment]
Is there any workaround for it in webflux

**Comment by Danushka96** [comment]
Any progress of this issue?

**Comment by SuveenVundavalli** [comment]
Hi, any progress or suggestions on this?

**Comment by yangdq1** [comment]
Hi, any progress or suggestions on this issue ?

**Comment by maradanasai** [comment]
Hi, any progress or suggestions on this?

**Comment by RajeevKumarMarrapu** [comment]
Hi, any progress or suggestions on this?

**Comment by dgallego58** [comment]
this seems to be a long way, since authorization server is focused in Oauth2 patterns  with spring security team i don't see coming this feature soon

**Comment by JonnyDeates** [comment]
Any Progress on this?

**Comment by marcusdacoregio** [comment]
Hi everyone, that has been no progress yet on this. Please give a thumbs up to the root comment if you would like to see this feature in Spring Security, this helps us prioritize issues.

If anyone is interested in working on this feature, you are welcome.

**Comment by jsantana3c** [comment]
the example seems to not be working on the 3.3.0-RC1 (I'm using OAuthLogin),

this is my config:

```java
 @Bean
    SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
        http
                .authorizeExchange(authorizeRequests -> authorizeRequests
                        .anyExchange()
                        .authenticated()
                )
                .sessionManagement(sessions -> sessions
                        .concurrentSessions(concurrency -> concurrency
                                .maximumSessions(SessionLimit.of(1))
                                .maximumSessionsExceededHandler(new PreventLoginServerMaximumSessionsExceededHandler())
                        )
                )
                .csrf(ServerHttpSecurity.CsrfSpec::disable)
                .oauth2Login(withDefaults())
                .logout(logout -> logout
                        .logoutSuccessHandler(oidcLogoutSuccessHandler())
                )
                .oauth2Client(withDefaults());

        return http.build();
    }

@Bean
    ReactiveSessionRegistry reactiveSessionRegistry() {
        return new InMemoryReactiveSessionRegistry();
    }

```

**Comment by marcusdacoregio** [comment]
Hi @jsantana3c, can you provide a minimal, reproducible sample?

**Comment by jsantana3c** [comment]
Here you go,
I created both authorization server and gateway

https://github.com/joaquinjsb/security-oauth-example

**Comment by joaquinjsb** [comment]
looks like it was an error in my end, I just created the https://github.com/spring-projects/spring-security/pull/15066, which fixes a two login need, because it doesn't filter the "current session".

while it looks like working, my integration with SSO looks like not working properly, because no session is being deleted on the authorization server, any idea on how to implement it ? (I already tried with back channel / logout) but seems like session invalidation / deletion doesn't generate an event on the other side?
