### ISSUE TITLE
ExceptionTranslationWebFilter should handle AuthenticationException

### ISSUE THREAD

**Issue by edeandrea** [spring-projects/spring-security#6202]
On the servlet side, `ExceptionTranslationFilter` handles both `AccessDeniedException` and `AuthenticationException` by sending them to the `AuthenticationEntryPoint`. On the reactive side `ExceptionTranslationWebFilter` only does this for `AccessDeniedException`. 

`ExceptionTranslationWebFilter` should handle `AuthenticationException` in the same manner as it's servlet-based counterpart.

If this ticket is deemed valid I'm happy to supply a PR for it.

**Comment by rwinch** [comment]
I don't think we have a need for it at this point. Are you having issues with the way things are working?

**Comment by edeandrea** [comment]
I'm not in front of the computer right now so I don't have the exact stack trace, but when configuring reactive security to use oauth2ResourceServer - if I pass in a malformed token my app throws a 500 instead of a 401.

I can reply back on Monday with a sample on how to reproduce.

**Comment by rwinch** [comment]
ok thank you @edeandrea!

**Comment by edeandrea** [comment]
Actually I think you are correct. I think though what is missing (& what I had to build to prove this to myself!) is a reactive version of `UserDetailsChecker`.

Now that I have that built out I'm happy to submit a PR for that (along with a modified version of `UserDetailsRepositoryReactiveAuthenticationManager` which includes a `ReactiveUserDetailsChecker`).

**Comment by rwinch** [comment]
Thanks for the response @edeandrea! I'm going to close this and we can discuss other changes via another ticket. Can you please create a new ticket to discuss your proposal around `UserDetailsChecker`?

**Comment by edeandrea** [comment]
I opened #6219 for the `UserDetailsChecker`
