### ISSUE TITLE
Spring Boot + spring-security-oauth2-resource-server should not throw a ClassNotFoundException once it supports more than one token format

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6209]
While it's true that Resource Server effectively requires `spring-security-oauth2-jose` at this point, it shouldn't once it supports more than one token format.

When `spring-boot-starter-security` and `spring-security-oauth2-resource-server` are used together, without further configuration, the application throws the following exception:

```
Caused by: java.lang.ClassNotFoundException: org.springframework.security.oauth2.jwt.JwtDecoder
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 111 more
```

In all likelihood, this will be taken care of naturally when coordinating with the boot team to add support for a second token format.

**Comment by rwinch** [comment]
@jzheaux There is a [spring-boot-starter-oauth2-resource-server](https://github.com/spring-projects/spring-boot/tree/v2.1.1.RELEASE/spring-boot-project/spring-boot-starters/spring-boot-starter-oauth2-resource-server) that should resolve this. There is a [ticket](https://github.com/spring-io/start.spring.io/issues/18) for adding it to start.spring.io

**Comment by rwinch** [comment]
It seems like that would be the case. Won't that naturally sort itself out or is this just to ensure we validate that?

**Comment by jzheaux** [comment]
This is just to ensure we validate that. Agreed that it should naturally sort itself out.

**Comment by edeandrea** [comment]
The Spring Boot team is doing a check on their side as well (see spring-projects/spring-boot#15372).

**Comment by jzheaux** [comment]
Confirmed by creating a project using the describing configuration and observing that it ran without error.
