### ISSUE TITLE
SEC-361: <auth:authorize ifNotGranted="ROLE_ANONYMOUS"> doesn't work sometimes

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#622]
["Eugene":https://jira.spring.io/secure/ViewProfile.jspa?name=sever](Migrated from ["SEC-361":https://jira.spring.io/browse/SEC-361?redirect=false]) said:

web.xml:
...........
<error-page>
  <error-code>404</error-code>
  <location>/common/documentnotfound.do</location>
</error-page>
...........
If the requested page not found tomcat redirect user to the pointed url (documentnotfount.do) and in this case <auth:authorize ifNotGranted="ROLE_ANONYMOUS"> doesn't work.

SecurityContextHolder.getContext() = org.acegisecurity.context.SecurityContextImpl@ffffffff: Null authentication (AuthorizeTag.java: 129)
SecurityContextHolder.getContext().getAuthentication() = null (AuthorizeTag.java: 129)
granted = [](AuthorizeTag.java: 80)
evaledIfNotGranted = ROLE_ANONYMOUS (AuthorizeTag.java: 82)
grantedCopy = [](AuthorizeTag.java: 86)

**Comment by spring-issuemaster** [comment]
This issue duplicates #567
