### ISSUE TITLE
Update GitHub Labels

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#6225]
### Summary
We should update the GitHub labels for Spring Security. There are lots of labels we have that are not used/needed. We might want to consider aligning with Spring Boot's label conventions.

NOTE: http://www.dorukdestan.com/github-label-manager/

**Comment by rwinch** [comment]
### Summary

Spring Boot and Spring Framework are using some nice conventions for the GitHub labels. We should try and do the same.

Here is the proposal:

```
status: blocked
status: declined
status: duplicate
status: feedback-provided
status: feedback-reminder
status: first-timers-only
status: ideal-for-contribution
status: invalid
status: on-hold
status: pending-design-work
status: superseded
status: waiting-for-feedback
status: waiting-for-triage

for: external-project
for: merge-with-amendments
for: stackoverflow
for: team-attention

type: blocker
type: bug
type: dependency-upgrade
type: documentation
type: enhancement
type: regression
type: task

is: backported
is: backport

in: acl
in: aspects
in: cas
in: config
in: core
in: crypto
in: data
in: docs
in: ldap
in: messaging
in: oauth2-client
in: oauth2-resource-server
in: openid
in: remoting
in: taglibs
in: test
in: web
```

**Comment by jzheaux** [comment]
I like it. Some notes about the proposal:

I was hoping that Issue search would not require an exact match on labels, but in Spring Framework, a search for `label:waiting-for-triage` returns nothing, but `label:"status: waiting-for-triage"` returns appropriately. Adding this extra syntax will make it harder for folks to search for issues to contribute to. Is that something we want to try and address?

If I wanted to do some more work on our Jenkins integration, what labels would I use? Just "type: enhancement"? In the past, I'd use "Build and Admin".

Once a first-time contributor begins work, we'd drop the "status: first-timers-only" label, correct? I would have imagined we'd then add a "status: in-progress" label or similar. What do you have in mind?

**Comment by jzheaux** [comment]
I like the new labels, @rwinch, thanks for doing this.
