### ISSUE TITLE
Why Jwt is the only supported format for bearer tokens in Spring Security?

### ISSUE THREAD

**Issue by ShanyouYu-Sean** [spring-projects/spring-security#6231]
### Summary
Seems Jwt is the only supported format for bearer tokens in Spring Security 5.1.+, why? Is there any plans implement a way to verify normal bearer token with userinfo endpoint or token introspect endpoint? 

### Actual Behavior
Cannot verify normal bearer token with userinfo endpoint or token introspect endpoint in Spring Security 5.1.+.

### Expected Behavior
Provide a way to verify normal bearer token with userinfo endpoint or token introspect endpoint.

### Version
Spring Security 5.1.2.RELEASE

**Comment by jgrandja** [comment]
@ShanyouYu-Sean Token Introspection (opaque token) support is planned for 5.2. You can track the progress in #5200.
