### ISSUE TITLE
AuthenticatedReactiveAuthorizationManager support for AnonymousAuthenticationToken

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#6235]
### Summary

`AuthenticatedReactiveAuthorizationManager` should filter out anonymous authentication by leveraging `AuthenticationTrustResolver`.

**Comment by mibo** [comment]
Hi @rwinch I would take this one.

**Comment by rwinch** [comment]
@mibo Thanks for you volunteering! The issue is yours :) Let me know if you need any help.

**Comment by mibo** [comment]
@rwinch I checked https://github.com/spring-projects/spring-security/pull/6198 and created following PR: https://github.com/spring-projects/spring-security/pull/6267

Can you please check if this solution fit and give feedback. Thanks.
