### ISSUE TITLE
SEC-364: TokenBasedRememberMeServices not properly using context path when setting cookie paths (SEC-206 only partially fixed) 

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#625]
["Randy Puro":https://jira.spring.io/secure/ViewProfile.jspa?name=randypuro](Migrated from ["SEC-364":https://jira.spring.io/browse/SEC-364?redirect=false]) said:

SEC-206 addressed an issue to ensure the context path is properly used when setting remember me cookie paths by using the code:

cookie.setPath(request.getContextPath());

However, http://java.sun.com/j2ee/1.4/docs/api/javax/servlet/http/HttpServletRequest.html#getContextPath() states that 'For servlets in the default (root) context, this method returns "" '.

An empty cookie path results in inconsistent behavior between ie and firefox: ie presumes "/" whereas firefox presumes the leading path for the current request.

If request.getContextPath() returns "", the cookie path should be set to "/" to properly reflect a cookie set for the root context.
This fix should be applied to both methods: makeValidCookie and makeCancelCookie of TokenBasedRememberMeServices.

**Comment by spring-issuemaster** [comment]
This issue depends on #466
