### ISSUE TITLE
if use oauth2Login can not use loginform

### ISSUE THREAD

**Issue by YINZHU2016** [spring-projects/spring-security#6250]
I want to use loginForm() and oauth2Login() in the spring boot. But in httpsecurity, I can only use one of these 2 lines. How do I get them to work together?

My scenario is that I made a authserver based on spring security. I want this authserver to support local user login as well as third-party user login, such as google, facebook, etc. But I don't know how to integrate this. Is there an example like this?
Thank you

**Comment by jgrandja** [comment]
@YINZHU2016 `formLogin` and `oauth2Login` should work together. What specific issue are you having? Can you share a sample so I can take a look at your configuration?

**Comment by jgrandja** [comment]
Closing due to lack of feedback.
