### ISSUE TITLE
Unable to authenticate using access_token request parameter

### ISSUE THREAD

**Issue by mattcopas** [spring-projects/spring-security#6253]
### Summary

According to the oauth2 specification, use of url?access_token=$TOKEN is allowed (and is required when using token based auth over WebSockets, as no request headers can be sent)

### Actual Behavior
When running the oauth2resource server example - https://github.com/spring-projects/spring-security/tree/5.1.2.RELEASE/samples/boot/oauth2resourceserver

everything works fine if you run `curl localhost:8080 -H "Authorization: Bearer $TOKEN"`

However if you run `curl localhost:8080?access_token=$TOKEN` then a 401 response code is returned.

### Expected Behavior
The Hello, subject message should be returned when using ?access_token=$TOKEN

### Configuration

Gradle 5.0, running app using gradle bootRun 
### Version
5.1.2

### Sample
NA, see https://github.com/spring-projects/spring-security/tree/5.1.2.RELEASE/samples/boot/oauth2resourceserver

**Comment by jgrandja** [comment]
@mattcopas This feature is available since 5.1. Take a look at `DefaultBearerTokenResolver` and the configuration options available. For your use case, you need the following configuration:

```java
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {
	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.authorizeRequests()
				.anyRequest().authenticated()
				.and()
			.oauth2ResourceServer()
				.jwt();
	}

	@Bean
	public BearerTokenResolver bearerTokenResolver() {
		DefaultBearerTokenResolver resolver = new DefaultBearerTokenResolver();
		resolver.setAllowUriQueryParameter(true);
		return resolver;
	}
}
```

I'm going to close this issue as I feel I have answered your question.
