### ISSUE TITLE
Document BearerTokenResolver in reference

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#6254]
There is no documentation for `BearerTokenResolver` and it's default implementation `DefaultBearerTokenResolver` in the reference. We should document and provide code samples on how to use and customize.

**Comment by kostya05983** [comment]
Hello @jgrandja , I can take this one, If I understand correctly, I should add docs in docs module of spring security, shouldn't I? And where can I put code samples of this?

**Comment by jzheaux** [comment]
@kostya05983 Thanks for volunteering - yes, you'd place docs in the docs module.

As for a sample, you could add one that goes alongside the other oauth2resourceserver samples, though there are quite a few already. Unless you feel customizing a bearer token resolver to be quite nuanced, I'd lean towards just sticking with snippets in the documentation.

Does that sound doable?

**Comment by kostya05983** [comment]
@jgrandja , thanks for guide, yes, it do.
