### ISSUE TITLE
Validate ClientRegistration.scopes

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#6256]
We should validate `ClientRegistration.scopes` to ensure it contains valid characters as per [spec](https://tools.ietf.org/html/rfc6749#section-3.3).

Related [spring-boot#15398](https://github.com/spring-projects/spring-boot/issues/15398)

**Comment by kabronkline** [comment]
With this fix I'm unable to supply resource as a scope parameter to ADFS and Azure STS. 

https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/overview/ad-fs-openid-connect-oauth-flows-scenarios

scope = [resource url]//[scope values e.g., openid]

With this fix the '//' is rejected for having invalid characters.

https://learn.microsoft.com/en-us/azure/active-directory/develop/scopes-oidc

Notice scope "https://graph.microsoft.com/.default" which has invalid characters.
