### ISSUE TITLE
Remove Servlet Spec 2.5 Support for HttpSessionSecurityContextRepository

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6261]
Related to #6220 

`HttpSessionSecurityContextRepository` adds a request wrapper for supporting Servlet Spec 3's startAsync methods.

Because Spring Framework 5.x has moved its baseline to Servlet Spec 3.1, the code should always use this wrapper [instead of checking the servlet spec version first](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/context/HttpSessionSecurityContextRepository.java#L130).

Also, [the Servlet 2.5 tests](https://github.com/spring-projects/spring-security/blob/master/web/src/test/java/org/springframework/security/web/context/HttpSessionSecurityContextRepositoryServlet25Tests.java) for this feature should be removed.

**Comment by dongmyo** [comment]
@jzheaux I'd like to take it

**Comment by jzheaux** [comment]
Thanks, @dongmyo! It's yours.
