### ISSUE TITLE
Remove Servlet 2.5 and 3.0 Support for Remember Me

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6263]
Related to #6220 

The `AbstractRememberMeServices` attempts to [use the setHttpOnly method only if that method is available in javax.servlet.http.Cookie](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/authentication/rememberme/AbstractRememberMeServices.java#L97).

Since Spring Framework 5.0 has a Servlet Spec baseline of 3.1, this check is no longer necessary.

We should always use the setHttpOnly method and remove [any corresponding Servlet 2.5 or 3.0 tests](https://github.com/spring-projects/spring-security/blob/master/web/src/test/java/org/springframework/security/web/authentication/rememberme/AbstractRememberMeServicesServlet3Tests.java).

**Comment by studyforbetter** [comment]
can you tell me how to use it by xml configer ,

**Comment by jzheaux** [comment]
@studyforbetter there isn't anything special to do for XML in this case. `CookieCsrfTokenRepository` is configured by both the Java config as well as the XML config in the same way.

**Comment by dongmyo** [comment]
@jzheaux I'd like to take it
