### ISSUE TITLE
Remove Servlet 3.0 Support in AbstractRequestMatcherRegistry

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6264]
Related to #6220 

`AbstractRequestMatcherRegistry` [checks first to make sure that the class `javax.servlet.ServletRegistration` is present](https://github.com/spring-projects/spring-security/blob/master/config/src/main/java/org/springframework/security/config/annotation/web/AbstractRequestMatcherRegistry.java#L164).

Since Spring Framework 5.x increases it's Servlet Spec baseline to 3.1, this check is no longer necessary, and the class can assume its availability.

The task here, then, is to remove the check. Since `isServlet30` is effectively always true now, the class should now always [postProcess the `ObjectPostProcessor`](https://github.com/spring-projects/spring-security/blob/master/config/src/main/java/org/springframework/security/config/annotation/web/AbstractRequestMatcherRegistry.java#L177) instead of conditionally.

**Comment by farooqkhan003** [comment]
@jzheaux can I pick this?

**Comment by jzheaux** [comment]
It's yours, @farooqkhan003!
