### ISSUE TITLE
GrantedAuthorityFromAssertionAttributesUserDetailsService is hard to extend

### ISSUE THREAD

**Issue by ThrawnCA** [spring-projects/spring-security#6268]
### Summary

The `GrantedAuthorityFromAssertionAttributesUserDetailsService` class is difficult to extend. Its `convertToUppercase` flag is write-only, and its logic is contained within a single complex method.

### Actual Behavior

- `convertToUppercase` has a setter method, but no getter.
- `loadUserDetails` converts an Assertion into a UserDetails, with no intermediate methods.

### Expected Behavior

- `convertToUppercase` should have a getter method, OR conversion of a single `Object` to `SimpleGrantedAuthority` should occur in a protected helper method.
- `loadUserDetails` should call an overridable (`protected` and non-final) method to retrieve a list of `GrantedAuthority`.

### Version

Currently using 5.1.1.RELEASE, but the problem applies to the latest commit 57353d18e5cf8adbc321b6cb8bba99692c5efe55

### Sample

I'll submit a pull request for this.

**Comment by ThrawnCA** [comment]
We want to be able to use comma-separated values in our CAS attributes instead of using lists. We use PWM to manage our LDAP directory, and it's non-trivial to store list attributes that way.

**Comment by rwinch** [comment]
Thanks. I think it makes sense for you to extend `AbstractCasAssertionUserDetailsService` instead of modifying `GrantedAuthorityFromAssertionAttributesUserDetailsService`.

**Comment by ThrawnCA** [comment]
That's what we'll probably do, yes. It's just that a lot of the logic is the same, so it would make sense (to me) to refactor GrantedAuthorityFromAssertionAttributesUserDetailsService to be reusable.

**Comment by rwinch** [comment]
I don't think it makes sense since you are overriding the only method implemented by `GrantedAuthorityFromAssertionAttributesUserDetailsService`

I'm going to close this. If you disagree please comment why and we can reopen to discuss.

**Comment by rwinch** [comment]
Unfortunately, we must strike a balance between the number of extension points we provide as this limits our ability to refactor. The amount of code necessary to customize the code is very small. Another option you might be able to use is to delegate to `GrantedAuthorityFromAssertionAttributesUserDetailsService` and modify the result it returns and then return that in your custom implementation.
