### ISSUE TITLE
Simplify Configuring Realm Name for WebFlux Applications

### ISSUE THREAD

**Issue by tensberg** [spring-projects/spring-security#6270]
### Summary

I'd like to be able to change the HTTP BASIC Realm configured by the WebFlux `ServerHttpSecurity http.httpBasic()`. It looks to me like there is no way to get at the underlying `HttpBasicSpec.entryPoint` to change the default.

### Actual Behavior

`ServerHttpSecurity http.httpBasic()` always uses the default realm *Realm*.

### Expected Behavior

Add API `ServerHttpSecurity http.httpBasic().realmName("myRealm")` similar to `HttpSecurity` to change the realm.

### Configuration

```
@Bean
    public SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
        http
            .authorizeExchange()
                .anyExchange().authenticated()
                .and()
            .httpBasic()
        return http.build();
    }
```

### Version

Spring Boot 2.1.1.RELEASE
Spring Security 5.1.2.RELEASE

**Comment by rwinch** [comment]
@tensberg Thanks for the report! Would you be interested in submitting a PR for this?

**Comment by ankurpathak** [comment]
@rwinch i would like to take this one.

**Comment by ankurpathak** [comment]
@rwinch I was free and wanted something to code. So I completed this issue and providing a pull 
request. I won't mind even if dosen't get accepted and chance get passed to @tensberg .
https://github.com/spring-projects/spring-security/pull/6279
