### ISSUE TITLE
Minor Code Enhancement In UsernamePasswordAuthenticationFilter with Optionals

### ISSUE THREAD

**Issue by ankurpathak** [spring-projects/spring-security#6271]
Improve UsernamePasswordAuthenticationFilter to extract username and password from request by using Java 8 Optional. I have created this issue so that I can refer it in my pull request fir same.

**Comment by ankurpathak** [comment]
Code improvement it has are:
```
                String username = Optional.ofNullable(obtainUsername(request)).orElse("");
		String password = Optional.ofNullable(obtainPassword(request)).orElse("");
```

**Comment by rwinch** [comment]
Thanks for creating the ticket. I'm closing this. Please see https://github.com/spring-projects/spring-security/pull/6272#issuecomment-446751377
