### ISSUE TITLE
Got different access tokens for grant type client_credentials authorization when access the token url many times

### ISSUE THREAD

**Issue by AI-PaaS** [spring-projects/spring-security#6275]
### Summary
I can get the access token using  client_credentials grant type and also can access the service with the access token. But, if the first token is not expired, i access the token_uri again, and i got another different access token, and can not use the second token access services.

I use jwt token store.

Can token uri return the same token if the token is not expired?

**Comment by jgrandja** [comment]
@AI-PaaS Is this question based on the [Spring Security OAuth](https://spring.io/projects/spring-security-oauth) project? Given your statement:

> I use jwt token store

Can you provide more detail please. What version are you using? Also, a minimal sample that reproduces the issue would be helpful.

**Comment by AI-PaaS** [comment]
Is this question based on the Spring Security OAuth project? Yes.

   compile(group: 'org.springframework.boot', name: 'spring-boot-starter-web') {
        exclude(module: 'spring-boot-starter-tomcat')
        exclude(group: 'org.apache.tomcat.embed')
        exclude(group: 'org.springframework.boot',module:'spring-boot-starter-logging')
        exclude group: 'ch.qos.logback', module: 'logback-core'
    }
    providedCompile(group: 'org.springframework.boot', name: 'spring-boot-starter-tomcat'){
    	exclude(group: 'org.springframework.boot',module:'spring-boot-starter-logging')
    	exclude group: 'ch.qos.logback', module: 'logback-core'
    }

    compile(group: 'org.springframework.boot', name: 'spring-boot-starter-security'){
    	exclude(group: 'org.springframework.boot',module:'spring-boot-starter-logging')
    	exclude group: 'ch.qos.logback', module: 'logback-core'
    }
    compile(group: 'org.springframework.security', name: 'spring-security-jwt', version: '1.0.3.RELEASE'){
    	exclude(group: 'org.springframework.boot',module:'spring-boot-starter-logging')
    	exclude group: 'ch.qos.logback', module: 'logback-core'
    }
    compile(group: 'org.springframework.security.oauth', name: 'spring-security-oauth2', version: '2.0.8.RELEASE') {
        exclude(module: 'jackson-mapper-asl') // We already have a more recent jackson via Spring Boot
        exclude(group: 'org.springframework.boot',module:'spring-boot-starter-logging')
        exclude group: 'ch.qos.logback', module: 'logback-core'
    }
    compile(group: 'org.springframework.boot', name: 'spring-boot-starter-data-redis', version: '1.5.17.RELEASE'){
       exclude(group: 'org.springframework.boot',module:'spring-boot-starter-logging')
       exclude group: 'ch.qos.logback', module: 'logback-core'
    }
    compile(group: 'org.springframework.session', name: 'spring-session-data-redis', version: '1.3.3.RELEASE'){
    	exclude(group: 'org.springframework.boot',module:'spring-boot-starter-logging')
    	exclude group: 'ch.qos.logback', module: 'logback-core'
    }
    compile(group: 'org.springframework.session', name: 'spring-session', version: '1.3.3.RELEASE'){
    	exclude(group: 'org.springframework.boot',module:'spring-boot-starter-logging')
    	exclude group: 'ch.qos.logback', module: 'logback-core'
    }    
    
The auth server is:

package com.cmi.oauth2.sso;

import java.security.Principal;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.filter.OrderedCharacterEncodingFilter;
import org.springframework.boot.web.support.SpringBootServletInitializer;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.data.redis.connection.RedisClusterConfiguration;
import org.springframework.data.redis.connection.RedisConnectionFactory;
import org.springframework.data.redis.connection.RedisSentinelConfiguration;
import org.springframework.data.redis.connection.jedis.JedisConnectionFactory;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.http.HttpMethod;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
import org.springframework.security.config.annotation.method.configuration.EnableGlobalMethodSecurity;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.builders.WebSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.security.oauth2.config.annotation.configurers.ClientDetailsServiceConfigurer;
import org.springframework.security.oauth2.config.annotation.web.configuration.AuthorizationServerConfigurerAdapter;
import org.springframework.security.oauth2.config.annotation.web.configuration.EnableAuthorizationServer;
import org.springframework.security.oauth2.config.annotation.web.configurers.AuthorizationServerEndpointsConfigurer;
import org.springframework.security.oauth2.config.annotation.web.configurers.AuthorizationServerSecurityConfigurer;
import org.springframework.security.oauth2.provider.code.AuthorizationCodeServices;
import org.springframework.security.oauth2.provider.token.TokenStore;
import org.springframework.security.oauth2.provider.token.store.JwtAccessTokenConverter;
import org.springframework.security.oauth2.provider.token.store.JwtTokenStore;
import org.springframework.security.web.csrf.CsrfFilter;
import org.springframework.security.web.util.matcher.AntPathRequestMatcher;
import org.springframework.session.FindByIndexNameSessionRepository;
import org.springframework.session.data.redis.RedisOperationsSessionRepository;
import org.springframework.session.data.redis.config.annotation.web.http.EnableRedisHttpSession;
import org.springframework.session.security.SpringSessionBackedSessionRegistry;
import org.springframework.stereotype.Controller;
import org.springframework.util.StringUtils;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.cors.CorsConfiguration;
import org.springframework.web.cors.UrlBasedCorsConfigurationSource;
import org.springframework.web.filter.CorsFilter;

import com.cmi.oauth2.sso.common.RequestBodyReaderAuthenticationFilter;
import com.cmi.oauth2.sso.config.ConfidentialClientProperties;
import com.cmi.oauth2.sso.config.CustomLogoutSuccessHandler;
import com.cmi.oauth2.sso.config.PublicClientProperties;
import com.cmi.oauth2.sso.config.TrustedClientProperties;
import com.cmi.oauth2.sso.entrypoint.LoginAuthorizeEntryPoint;
import com.cmi.oauth2.sso.handler.LoginFailureHandler;
import com.cmi.oauth2.sso.handler.LoginSuccessHandler;
import com.cmi.oauth2.sso.handler.LoginSuccessSSOHandler;
import com.cmi.oauth2.sso.redis.ClusterProperties;
import com.cmi.oauth2.sso.redis.RedisAuthenticationCodeServices;
import com.cmi.oauth2.sso.redis.SentinelProperties;
import com.cmi.oauth2.sso.redis.SingleProperties;
import com.cmi.oauth2.sso.user.CustomUserDetailsService;

import redis.clients.jedis.JedisPoolConfig;

@ComponentScan(basePackages = "com.cmi.oauth2.sso")
@SpringBootApplication
@Controller
public class OauthSSOApplication extends SpringBootServletInitializer {

	private static final Logger log = LoggerFactory.getLogger(OauthSSOApplication.class);
	public static final String FORM_BASED_LOGIN_ENTRY_POINT = "/login";
	public static final String EXP_LOGIN_ENTRY_POINT = "/iboss";
	public static final String TOKEN_BASED_AUTH_ENTRY_POINT = "/**";
	public static final String TOKEN_REFRESH_ENTRY_POINT = "/oauth/token";
	public static final String LOGIN_ERROR_POINT = "/error";
	
	@RequestMapping("/user")
	@ResponseBody
	public Principal user(Principal user) {
		return user;
	}

	@Value("${spring.redis.mode}")
	private String redisMode;
	@Value("${spring.redis.password}")
	private String redisPasswd;

	@Autowired
	SingleProperties singleProperties;

	@Autowired
	SentinelProperties sentinelProperties;

	@Autowired
	ClusterProperties clusterProperties;

	@Bean
	@Order(Ordered.HIGHEST_PRECEDENCE)
	public RedisConnectionFactory redisConnectionFactory() {
		JedisConnectionFactory redisConnectionFactory = null;
		switch (redisMode) {
		case "sentinel":
			redisConnectionFactory = new JedisConnectionFactory(
					new RedisSentinelConfiguration(sentinelProperties.getMaster(), sentinelProperties.getNodes()));
			break;
		case "cluster":
			redisConnectionFactory = new JedisConnectionFactory(
					new RedisClusterConfiguration(clusterProperties.getNodes()));
			break;

		default:
			redisConnectionFactory = new JedisConnectionFactory();
			redisConnectionFactory.setHostName(singleProperties.getHost());
			redisConnectionFactory.setPort(singleProperties.getPort());
			redisConnectionFactory.setTimeout(singleProperties.getTimeout());
		}
		if (!StringUtils.isEmpty(redisPasswd))
			redisConnectionFactory.setPassword(redisPasswd);
		JedisPoolConfig jedisPoolConfig = new JedisPoolConfig();
		redisConnectionFactory.setUsePool(true);
		jedisPoolConfig.setMaxTotal(10000);
		jedisPoolConfig.setMaxIdle(100);
		redisConnectionFactory.setPoolConfig(jedisPoolConfig);

		return redisConnectionFactory;
	}

	@Bean
	public RedisTemplate<Object, Object> redisTemplate(RedisConnectionFactory redisConnectionFactory) {
		RedisTemplate<Object, Object> redisTemplate = new RedisTemplate<>();
		redisTemplate.setConnectionFactory(redisConnectionFactory);
		return redisTemplate;
	}

	@SuppressWarnings({ "unchecked", "rawtypes" })
	@Bean
	SpringSessionBackedSessionRegistry sessionRegistry() {
		FindByIndexNameSessionRepository repository = new RedisOperationsSessionRepository(
				redisTemplate(redisConnectionFactory()));
		return new SpringSessionBackedSessionRegistry(repository);
	}

	@Bean
	@Order(Ordered.HIGHEST_PRECEDENCE)
	public OrderedCharacterEncodingFilter filterRegistrationBean() {
		OrderedCharacterEncodingFilter filter = new OrderedCharacterEncodingFilter();
		filter.setForceEncoding(true);
		filter.setEncoding("UTF-8");
		return filter;
	} 
	
	@Bean
	public LoginAuthorizeEntryPoint entryPoint(){
		return new LoginAuthorizeEntryPoint(FORM_BASED_LOGIN_ENTRY_POINT);
	}
	
	public static void main(String[] args) {
		log.info("Begin to starting the sa-sso-server......");
		ApplicationContext context = SpringApplication.run(OauthSSOApplication.class, args);
		log.info("The sa-sso-server started!......{}", context.getApplicationName());
	}

	/**
	 * An opinionated WebApplicationInitializer to run a SpringApplication from
	 * a traditional WAR deployment. Binds Servlet, Filter and
	 * ServletContextInitializer beans from the application context to the
	 * servlet container.
	 *
	 * @link http://docs.spring.io/spring-boot/docs/current/api/index.html?org/
	 *       springframework/boot/context/web/SpringBootServletInitializer.html
	 */
	@Override
	public SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		return application.sources(OauthSSOApplication.class);
	}

	@Configuration
	@EnableAsync
	@Order(2)
	@EnableWebSecurity
	@EnableRedisHttpSession
	@EnableGlobalMethodSecurity(prePostEnabled = true)
	public class SecurityConfig extends WebSecurityConfigurerAdapter {

		@Autowired
		CustomUserDetailsService customUserDetailsService;

		@Autowired
		CustomLogoutSuccessHandler customLogoutSuccessHandler;

		@Autowired
		LoginFailureHandler loginFailureHandler;
		
		@Autowired
		LoginSuccessSSOHandler loginSuccessSSOHandler;
		
		
		
		@Autowired
		OrderedCharacterEncodingFilter charsetFilter;

		@Override
		@Autowired // <-- This is crucial otherwise Spring Boot creates its own
		public void configure(AuthenticationManagerBuilder auth) throws Exception {
			auth.userDetailsService(customUserDetailsService);
		}

		@Override
		public void configure(WebSecurity web) throws Exception {
			// allow options methods
			web.ignoring().antMatchers(HttpMethod.OPTIONS);
		}  
		
		@Bean
		public CorsFilter corsFilter() {
			final UrlBasedCorsConfigurationSource urlBasedCorsConfigurationSource = new UrlBasedCorsConfigurationSource();
			final CorsConfiguration corsConfiguration = new CorsConfiguration();
			corsConfiguration.setAllowCredentials(true);
			corsConfiguration.addAllowedOrigin("*");
			corsConfiguration.addAllowedHeader("*");
			corsConfiguration.addAllowedMethod("*");
			urlBasedCorsConfigurationSource.registerCorsConfiguration("/**", corsConfiguration);
			return new CorsFilter(urlBasedCorsConfigurationSource);
		}

		@Override
		public void configure(HttpSecurity http) throws Exception {
			// 不能禁用session
			http.antMatcher("/**").addFilterBefore(charsetFilter, CsrfFilter.class)
					// 使用自定义用户服务
					.userDetailsService(customUserDetailsService)
					// 跨域
					.cors()
					// support cross domain
					.and()
					// diable crsf
					.csrf().disable().formLogin().loginPage(FORM_BASED_LOGIN_ENTRY_POINT)
					.failureHandler(loginFailureHandler).successHandler(loginSuccessSSOHandler).permitAll()
					// token
					.and() 
					// login请求放过
					.authorizeRequests().antMatchers(FORM_BASED_LOGIN_ENTRY_POINT, LOGIN_ERROR_POINT).permitAll() // Login
					// 获取token请求放过 // end-point
					.antMatchers(TOKEN_REFRESH_ENTRY_POINT).permitAll().antMatchers("/**/*.js/**").permitAll()
					.antMatchers("/**/*.css/**").permitAll().antMatchers("/**/*.jpg/**", "/**/*.png/**", "/**/*.ico/**")
					.permitAll().antMatchers("/**/validate/**").permitAll().antMatchers("/**/userInfo/**").permitAll().antMatchers("/**/*.html/**").permitAll()
					.antMatchers("/**/changePwd/**").permitAll()
					// 新的
					.and()
					// 不允许ajax请求
					.httpBasic().disable()
					// 所有请求都必须认证过
					.authorizeRequests().anyRequest().authenticated()
					// 退出请求
					.and() 
					.exceptionHandling().authenticationEntryPoint(entryPoint())
					.and()
					// 退出成功后 
					.logout().clearAuthentication(true).invalidateHttpSession(true)
					.logoutSuccessHandler(customLogoutSuccessHandler).permitAll();
			http.sessionManagement().maximumSessions(100).maxSessionsPreventsLogin(false)
					.expiredUrl(FORM_BASED_LOGIN_ENTRY_POINT).sessionRegistry(sessionRegistry());
			//http.exceptionHandling().accessDeniedHandler(new LoginAccessDeniedHandler());
		}

	}

	@Configuration
	@Order(1)
	@EnableWebSecurity
	@EnableGlobalMethodSecurity(prePostEnabled = true)
	public class ExceptionLoginConfig extends WebSecurityConfigurerAdapter {

		@Autowired
		CustomUserDetailsService customUserDetailsService;

		@Autowired
		CustomLogoutSuccessHandler customLogoutSuccessHandler;

		@Autowired
		LoginFailureHandler loginFailureHandler;

		@Autowired
		LoginSuccessHandler loginSuccessHandler;
		
		@Autowired
		OrderedCharacterEncodingFilter charsetFilter;

		@Override
		@Autowired // <-- This is crucial otherwise Spring Boot creates its own
		public void configure(AuthenticationManagerBuilder auth) throws Exception {
			auth.userDetailsService(customUserDetailsService);

		}

		@Override
		public void configure(WebSecurity web) throws Exception {
			// allow options methods
			web.ignoring().antMatchers(HttpMethod.OPTIONS);
		}

		@Bean
		public RequestBodyReaderAuthenticationFilter authenticationFilter() throws Exception {
			RequestBodyReaderAuthenticationFilter authenticationFilter = new RequestBodyReaderAuthenticationFilter();
			authenticationFilter.setAuthenticationFailureHandler(loginFailureHandler);
			authenticationFilter.setAuthenticationSuccessHandler(loginSuccessHandler);
			authenticationFilter
					.setRequiresAuthenticationRequestMatcher(new AntPathRequestMatcher(EXP_LOGIN_ENTRY_POINT));
			authenticationFilter.setAuthenticationManager(authenticationManagerBean());
			return authenticationFilter;
		}

		@Bean
		public CorsFilter corsFilter() {
			final UrlBasedCorsConfigurationSource urlBasedCorsConfigurationSource = new UrlBasedCorsConfigurationSource();
			final CorsConfiguration corsConfiguration = new CorsConfiguration();
			corsConfiguration.setAllowCredentials(true);
			corsConfiguration.addAllowedOrigin("*");
			corsConfiguration.addAllowedHeader("*");
			corsConfiguration.addAllowedMethod("*");
			urlBasedCorsConfigurationSource.registerCorsConfiguration("/**", corsConfiguration);
			return new CorsFilter(urlBasedCorsConfigurationSource);
		}

		@Override
		public void configure(HttpSecurity http) throws Exception {
			// 不能禁用session
			http.antMatcher(EXP_LOGIN_ENTRY_POINT).addFilterBefore(charsetFilter, CsrfFilter.class)
					.userDetailsService(customUserDetailsService)
					// 跨域
					.cors()
					// support cross domain
					.and()
					// diable crsf
					.csrf().disable()
					
					
					// login请求放过
					.authorizeRequests().antMatchers(EXP_LOGIN_ENTRY_POINT).permitAll() // Login 
					// 获取token请求放过 // end-point
					.and()
					// 允许http请求 
					.exceptionHandling().authenticationEntryPoint(entryPoint())
					.and()
					.httpBasic().disable();
			http.sessionManagement().maximumSessions(100).maxSessionsPreventsLogin(false)
					.expiredUrl(EXP_LOGIN_ENTRY_POINT).sessionRegistry(sessionRegistry());
		}
	}

	@Configuration
	@EnableAuthorizationServer
	public class AuthorizationServerConfig extends AuthorizationServerConfigurerAdapter {

		@Value("${config.oauth2.privateKey}")
		private String privateKey;

		@Value("${config.oauth2.publicKey}")
		private String publicKey;

		@Autowired
		PublicClientProperties publicClientProperties;

		@Autowired
		ConfidentialClientProperties confidentialClientProperties;

		@Autowired
		TrustedClientProperties trustedClientProperties;

		@Autowired
		private AuthenticationManager authenticationManager;

		@Bean
		public JwtAccessTokenConverter tokenEnhancer() {
			log.info("Initializing JWT with public key:\n{}", publicKey);
			JwtAccessTokenConverter converter = new JwtAccessTokenConverter();
			converter.setSigningKey(privateKey);
			converter.setVerifierKey(publicKey);
			return converter;
		}

		@Bean
		public TokenStore tokenStore() {
			return new JwtTokenStore(tokenEnhancer());
		}

		@Bean
		public AuthorizationCodeServices authorizationCodeServices() {
			return new RedisAuthenticationCodeServices(redisConnectionFactory());
		}

		/**
		 * Defines the security constraints on the token endpoints
		 * /oauth/token_key and /oauth/check_token Client credentials are
		 * required to access the endpoints
		 *
		 * @param oauthServer
		 * @throws Exception
		 */
		@Override
		public void configure(AuthorizationServerSecurityConfigurer oauthServer) throws Exception {
			oauthServer.tokenKeyAccess("isAnonymous() || hasRole('ROLE_TRUSTED_CLIENT')") // permitAll()
					.checkTokenAccess("hasRole('TRUSTED_CLIENT')"); // isAuthenticated()
		}

		/**
		 * Defines the authorization and token endpoints and the token services
		 *
		 * @param endpoints
		 * @throws Exception
		 */
		@Override
		public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
			endpoints

					// Which authenticationManager should be used for the
					// password grant
					// If not provided, ResourceOwnerPasswordTokenGranter is not
					// configured
					.authenticationManager(authenticationManager)
					// Use JwtTokenStore and our jwtAccessTokenConverter
					.tokenStore(tokenStore()).accessTokenConverter(tokenEnhancer());

			endpoints.authorizationCodeServices(authorizationCodeServices());
		}

		@Override
		public void configure(ClientDetailsServiceConfigurer clients) throws Exception {
			if (log.isDebugEnabled()) {
				log.debug(" ==============  publicClientProperties.getRedirectUris()  :  "
						+ publicClientProperties.getRedirectUris());
				log.debug(" ==============  confidentialClientProperties.getRedirectUris()  :  "
						+ confidentialClientProperties.getRedirectUris());
				log.debug(" ==============  trustedClientProperties.getRedirectUris()  :  "
						+ trustedClientProperties.getRedirectUris());
			}
			clients.inMemory()

					// Confidential client where client secret can be kept safe
					// (e.g. server side)
					.withClient(confidentialClientProperties.getClientID())
					.secret(confidentialClientProperties.getClientSecret()).autoApprove(true)
					.authorizedGrantTypes("client_credentials", "authorization_code", "refresh_token")
					.authorities("ROLE_USER")
					.scopes("read", "write").redirectUris(confidentialClientProperties.getRedirectUris())
					.accessTokenValiditySeconds(36000).and()

					// Public client where client secret is vulnerable (e.g.
					// mobile apps, browsers)
					.withClient(publicClientProperties.getClientID()) // No
					.authorities("ROLE_USER")													// secret!
					.autoApprove(true).authorizedGrantTypes("implicit").scopes("read")
					.redirectUris(publicClientProperties.getRedirectUris()).accessTokenValiditySeconds(36000).and()

					// Trusted client: similar to confidential client but also
					// allowed to handle user password
					.withClient(trustedClientProperties.getClientID()).secret(trustedClientProperties.getClientSecret())
					.authorities("ROLE_TRUSTED_CLIENT","ROLE_USER").autoApprove(true)
					.authorizedGrantTypes("client_credentials", "password", "authorization_code", "refresh_token")
					.scopes("read", "write").redirectUris(trustedClientProperties.getRedirectUris())
					.accessTokenValiditySeconds(36000);
		}

	}

}

**Comment by jgrandja** [comment]
@AI-PaaS Pasting the code in this issue would still require effort on my end to put together a compiling version of your sample. What I meant is to publish a minimal sample in a GitHub repo and share it with me along with detailed instructions on what you are performing on your end to reproduce the issue.

Also, I'm going to close this issue as it should be logged in the [Spring Security OAuth](https://github.com/spring-projects/spring-security-oauth/issues) repo. Please log it there with the details and sample repo.

Regarding your question:

> Can token uri return the same token if the token is not expired?

Is there a reason you need to fetch a new access token if the current one has not expired?
Also, I don't think the Token Endpoint would return an existing access token that is not expired.
