### ISSUE TITLE
None of the org.springframework.security.oauth2.core have the proper equals/hashcode implemented

### ISSUE THREAD

**Issue by dmusicant-eagle** [spring-projects/spring-security#6282]
### Summary

I've been attempting to test an implementation of OAuth2 in Spring Boot 2.x, and am finding it incredibly cumbersome due to the fact that none of the classes used to hold state/data/response/request have an equals or hashCode implementation. This is not a good design.

### Actual Behavior

Classes such as these (see below) do not have equals or hashCode:

    org.springframework.security.oauth2.core.OAuth2Error
    org.springframework.security.oauth2.core.endpoint.OAuth2AuthorizationResponse
    org.springframework.security.oauth2.core.endpoint.OAuth2AuthorizationRequest

And there's many more.

### Expected Behavior

Domain and DTO classes would have an implemented equals/hashCode.

### Configuration

Java 11
Spring Boot 2.1.1.RELEASE
Spring Security 2.3.4.RELEASE
Spring OAuth Client: 5.1.2.RELEASE

### Version

Spring Boot 2.1.1.RELEASE
Spring Security 2.3.4.RELEASE
Spring OAuth Client: 5.1.2.RELEASE

### Sample

See: https://github.com/spring-projects/spring-security/blob/master/oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/endpoint/OAuth2AuthorizationResponse.java

**Comment by jgrandja** [comment]
@dmusicant-eagle I don't agree that all domain classes should implement `equals` and `hashCode`. It really depends if they intend to be used in `Collection`(s) and such.

As far as `OAuth2AuthorizationRequest` and `OAuth2AuthorizationResponse`, these are framework specific classes and are not intended to be used by the application directly.

It would be more helpful to understand why you need `OAuth2AuthorizationRequest`, `OAuth2AuthorizationResponse` and `OAuth2Error` to implement `equals` and `hashCode`? You mentioned that you've been using them to test the implementation? Can you please be more specific on your use cases.

**Comment by jgrandja** [comment]
@dmusicant-eagle I'm going to close this based on lack of feedback. We can re-open if you can provide more details around my comment.
