### ISSUE TITLE
Nice to have: release notes linked to from this repo

### ISSUE THREAD

**Issue by larrywest42** [spring-projects/spring-security#6291]
### Summary

It would be useful to have release notes for Spring Security, summarizing the bug fixes and enhancements made in a given release, linked to from the repo and/or project page.

### Actual Behavior

I've found no release notes for Spring Security except via spring.io/blog, such as
* [Spring Security 5.0.8 and 4.2.8 release](https://spring.io/blog/2018/09/11/spring-security-5-0-8-and-4-2-8-released)

These are good, but it would be convenient to have them linked to here, perhaps on the Wiki

### Expected Behavior

I'd expect to find release notes for each release.

But there are no notes linked to or mentioned in

* The [GitHub releases tab here](https://github.com/spring-projects/spring-security/releases)
* The [Spring Security page at spring.io](https://spring.io/projects/spring-security)
* The [GitHub wiki page here](https://github.com/spring-projects/spring-security/wiki) &mdash; including no mention in the [Release Process](https://github.com/spring-projects/spring-security/wiki/Release-Process).
* The [README.adoc](https://github.com/spring-projects/spring-security/blob/master/README.adoc) file here.

### Configuration

Browsing & googling.

### Version

I have found no release notes mentioned here for any version of Spring Security.

### Example

_N/A_

**Comment by rwinch** [comment]
Thanks for the report @larrywest42! I'm curious what you are looking for over the changelog which can be found when selecting a milestone within the GitHub UI?

**Comment by eleftherias** [comment]
Release notes are included in the [GitHub releases tab](https://github.com/spring-projects/spring-security/releases), since version 5.2.0.M2.
