### ISSUE TITLE
Nice to have: hasAnyAuthority() and hasAnyRole() in AuthorizeExchangeSpec 

### ISSUE THREAD

**Issue by andysworkshop** [spring-projects/spring-security#6306]
### Summary

Non-reactive spring security provides `hasAnyAuthority()` and `hasAnyRole()` for allowing access if the user has any of the provided authorities/roles. It would be great to see this supported in the reactive API as well.

### Actual Behavior

The named methods do not exist on `org.springframework.security.config.web.server.ServerHttpSecurity.AuthorizeExchangeSpec`

### Expected Behavior

The named methods would be provided.

### Configuration

Not applicable.

### Version

5.1.2

### Sample

Not applicable.

**Comment by rwinch** [comment]
@andysworkshop Thanks for the report! Would you be interested in submitting a PR?

**Comment by andysworkshop** [comment]
Hi @rmartinus, go for it mate 👍

For reference the method signatures in imperative spring security are in the [SecurityExpressionRoot](https://docs.spring.io/spring-security/site/docs/4.2.5.RELEASE/apidocs/org/springframework/security/access/expression/SecurityExpressionRoot.html) class.
