### ISSUE TITLE
Add preload support to Strict-Transport-Security

### ISSUE THREAD

**Issue by OArtyomov** [spring-projects/spring-security#6312]
Strict-Transport-Security configuration
  Problem: 
Response header "Strict-Transport-Security" should contain value "max-age=31536000;includeSubdomains; preload". There is no possibility to do it in class HstsConfig now. Only "max-age=31536000; includeSubdomains" supportable.

**Comment by rwinch** [comment]
Thanks for the ticket. Would you be willing to submit a PR for this? If you need help, I'd be glad to guide you through the process

**Comment by ankurpathak** [comment]
I would like to take this one.

**Comment by rwinch** [comment]
@ankurpathak Thank you the issue is yours.

**Comment by ankurpathak** [comment]
Pull request for the issue:
https://github.com/spring-projects/spring-security/pull/6321
