### ISSUE TITLE
ReactiveManagementWebSecurityAutoConfiguration Prevent's oauth2Login from being defaulted

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#6314]
If `org.springframework.boot:spring-boot-starter-actuator` is on the classpath than `ReactiveManagementWebSecurityAutoConfiguration` will build a `SecurityWebFilterChain`, which will get `@Autowired` to `WebFluxSecurityConfiguration.securityWebFilterChains`. This configuration path will result in a bypass of `OAuth2ClasspathGuard.shouldConfigure()`, which is called for the [default configuration](https://github.com/spring-projects/spring-security/blob/master/config/src/main/java/org/springframework/security/config/annotation/web/reactive/WebFluxSecurityConfiguration.java#L98) of `SecurityWebFilterChain`.

So if `oauth2-client` is actually on the classpath and the required properties are configured, than `ServerHttpSecurity.oauth2Login()` will not be applied.

Related [spring-cloud-security#171](https://github.com/spring-cloud/spring-cloud-security/pull/171)

/cc @rwinch @spencergibb

**Comment by spencergibb** [comment]
For the sample app I'm doing the following temporarily:
```
spring:
  autoconfigure:
    exclude: org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
```

**Comment by jgrandja** [comment]
@spencergibb I have a workaround for you [here](https://github.com/jgrandja/oauth2login-gateway/commit/51a28f91b7a71d71522d14d0cb5f1fa717033f42)

**Comment by jgrandja** [comment]
Closing in favour of [spring-boot#17949](https://github.com/spring-projects/spring-boot/issues/17949)
