### ISSUE TITLE
Add quiet period to Jenkins builds

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6322]
When two builds for the same branch run very close together, sonar can at times get caught in a race condition, and one of those runs will fail.

Each branch has its own sonar project now, so this won't happen when builds from two different branches are close together, but it can still happen for the same branch.

To reduce the likelihood of this happening, we can implement a quiet period with Jenkins so that builds for the same branch are separated by a few seconds or minutes.

**Comment by rwinch** [comment]
We no longer use Jenkins, so closing this as invalid
