### ISSUE TITLE
AuthenticationManager's authentication is invalid

### ISSUE THREAD

**Issue by clevertension** [spring-projects/spring-security#6324]
### Summary

when we have a authentication manager with parent exist , 
if parentAuthenticationManager.authentication() is success, but childAuthenticationManager.authentication() throw the failure event

### Actual Behavior

we can login to the system successfully with any password

### Expected Behavior

it should throw the failure exception and publish the failure event and disallow user to login

### Configuration

see the example

### Version

5.1.2.RELEASE

### Sample

https://github.com/clevertension/spring-security-event-publish

**Comment by rwinch** [comment]
This is behaving as expected. If you want it to fail, the parent `AuthenticationManager` should fail.

**Comment by clevertension** [comment]
the username check is ok with the parent AuthenticationManager, then this user can login with any password? it is too weak to protect, i think the success should be all check pass no the only parent check pass, we should not care about the authentication manager orchestration

**Comment by clevertension** [comment]
let me clarify the requirement with my demo project
i create a ** UserNameCheckProvider** to check if the username is started with fuck, then i create a userDetailsService with specific username and password

![image](https://user-images.githubusercontent.com/346723/50870554-71477580-13f3-11e9-9732-85bb7092b056.png)

so now, my expectation is we can only allow user to login with (username="user" and password="password"), but the actually behavior is we can login with (username != startswith("fuck) and any password), i can't accept this condition

**Comment by rwinch** [comment]
Thank you for the additional details on your requirements.

Perhaps it is better to prevent such usernames from being created in the first place?

If that doesn't work, you can use [DaoAuthenticationProvider.setPreAuthenticationChecks](https://github.com/spring-projects/spring-security/blob/575d943f1af11fca767781b2b0c549d1cd36433f/core/src/main/java/org/springframework/security/authentication/dao/AbstractUserDetailsAuthenticationProvider.java#L334) to perform any checks you want before the username/password is validated.

For example:


```java
@Bean
public AuthenticationProvider authenticationProvider() {
    // @formatter:off
	UserDetails user = User.withUsername("user")
        .password("password")
        .roles("USER")
        .build();
    // @formatter:on
	UserDetailsService uds = new InMemoryUserDetailsManager(user);
	DaoAuthenticationProvider result = new DaoAuthenticationProvider();
    result.setUserDetailsService(uds);
    result.setPreAuthenticationChecks(u -> {
        boolean notAllowed = isBadWord(u.getUsername());
        if (notAllowed) {
            throw new AccountStatusException("Not allowed");
        }
        // additional checks ....
    });
    return result;
}
```

I'm closing this as answered. If you feel like it has not been addressed, please comment on here and we can reopen.
