### ISSUE TITLE
Invalid processing of remember-me token values that contains '+' sign

### ISSUE THREAD

**Issue by vteraz** [spring-projects/spring-security#6333]
### Summary
Hi
I decided to upgrade Spring Security from version 4.2.2 to version 5.1.2
But I have an issue: tokens series that contain plus sigh - '+' - are not working any more.  
I've checked the sources and realised that this is all because `URLDecoder` in `AbstractRememberMeServices.decodeCookie` converts plus sign to space. 
As a result tokens that was generated using version 4 are not valid in version 5
Which means version 4 is not fully compatible with version 5

The question is - **was it conscious decision to use `URLDecoder` and eliminate some signs in token or this is bug?**

### Actual Behavior
As an input we have token series - `QLy184g36FUR5pL2Px+CvA==`. The same series is saved in DB. 
But method `decodeCookie` returns series - `QLy184g36FUR5pL2Px CvA==`. That's why token can't be found

### Expected Behavior
As an input we have token series - `QLy184g36FUR5pL2Px+CvA==`. The same series is saved in DB. 
Method `decodeCookie` **should return the same value** - `QLy184g36FUR5pL2Px+CvA==`

### Version
**5.1.2**

Thanks.

**Comment by rwinch** [comment]
Thanks for the feedback @vteraz! You are right that this was a non-passive change made in Spring Security 5.0. This was intentional to resolve #252 If you need to revert to the old behavior you can override the methods.

**Comment by rwinch** [comment]
Closing as this is expected
