### ISSUE TITLE
Minor spelling mistake on topic in Github repository

### ISSUE THREAD

**Issue by franzwong** [spring-projects/spring-security#6335]
https://github.com/spring-projects/spring-security
Under the description of the repository, you can see the topic "fraework" instead of "framework"

**Comment by jzheaux** [comment]
Thanks, @franzwong! Would you be interested in submitting a PR for this?

**Comment by franzwong** [comment]
@jzheaux That belongs to the configuration of GitHub repository. So I am not able to create a PR for that.

**Comment by jzheaux** [comment]
@franzwong Ah, I misunderstood you earlier. Thanks for the extra explanation, that's fixed now.
