### ISSUE TITLE
OAuth2 resource server jwk-set-uri requires authentication

### ISSUE THREAD

**Issue by cloudxpc** [spring-projects/spring-security#6337]
Hello,

i got one confuse and it is so detail so that i cannot find help from google. so i came. I'm using spring boot 2.1.1.RELEASE with security oauth2. Refer to the documentation 29.3.2 Resource Server, and i involve pom:
 ```
       <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-oauth2-resource-server</artifactId>
        </dependency>
```
spring.security.oauth2.resourceserver.jwt.jwk-set-uri could be set for loading jwk from authorization server. but what about if authorization server requires authentication? I can see this behavior done by NimbusJwtDecoderJwkSupport class. In order to use different jwsAlgorithm i've to create bean:
```
    @Bean
    public JwtDecoder jwtDecoder(){
        return new NimbusJwtDecoderJwkSupport("http://localhost:8086/oauth/token_key", "HS256");
    }
```
and it seems that a private class RestOperationsResourceRetriever of NimbusJwtDecoderJwkSupport is used for communication. But i cannot see it sends authentication info to authorization server such as client-id, client-secret and so on.
```
    public Resource retrieveResource(URL url) throws IOException {
            HttpHeaders headers = new HttpHeaders();
            headers.setAccept(Collections.singletonList(MediaType.APPLICATION_JSON_UTF8));

            ResponseEntity response;
            try {
                RequestEntity<Void> request = new RequestEntity(headers, HttpMethod.GET, url.toURI());
                response = this.restOperations.exchange(request, String.class);
            } catch (Exception var5) {
                throw new IOException(var5);
            }

            if (response.getStatusCodeValue() != 200) {
                throw new IOException(response.toString());
            } else {
                return new Resource((String)response.getBody(), "UTF-8");
            }
        }
```
how can i correctly set configuration in order to get jwt key from authorization server? BTW, i know there is spring security oauth2 autoconfigure project. But it seems there is no need to involve it just for resource server configuration. Could someone correct me please that would be very appreciated!

**Comment by jzheaux** [comment]
Sorry that you are having trouble, @cloudxpc, hopefully, I can help!

To add authentication to the JWKS request, you'd want to wire your own `RestOperations` using `NimbusJwtDecoderJwkSupport#setRestOperations`. [`RestTemplateBuilder`](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/web/client/RestTemplateBuilder.html) may turn out to be helpful for you.

Also, for the future, StackOverflow tends to be a better place for support requests, so I'd encourage you to post further or future questions there. Thanks!

**Comment by cloudxpc** [comment]
Thank you @jzheaux
