### ISSUE TITLE
Spring Security OAuth2 impossible to add multiple security filter chain

### ISSUE THREAD

**Issue by akuma8** [spring-projects/spring-security#6345]
Hi, 
Is it a normal behavior to not be able to add multiple SecurityFilterChain of type `org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfigurer`? 
Example in a multi modules application secured with Spring Security Oauth2, I would like to configure several filters (1 by module), like: 
```
@Configuration
@Order(2)
public class Module1SecurityFilterChain extends ResourceServerConfigurerAdapter {

   @Override
   public void configure( HttpSecurity http ) throws Exception {
      http.sessionManagement().sessionCreationPolicy( STATELESS );
      http.antMatcher( "/module1/**")
            .authorizeRequests()
            .antMatchers( "/module1/resource").authenticated()
            .antMatchers( "/module1/test" ).authenticated()
            .anyRequest().access( "#oauth2.hasScope('webclient')" );
   }
}
```
And
```
@Configuration
@Order(1)
public class Module2SecurityFilterChain extends ResourceServerConfigurerAdapter {

   @Override
   public void configure( HttpSecurity http ) throws Exception {
      http.sessionManagement().sessionCreationPolicy( STATELESS );
      http.antMatcher( "/module2/**")
            .authorizeRequests()
            .antMatchers( "/module2/resource").authenticated()
            .antMatchers( "/module2/test" ).authenticated()
            .anyRequest().access( "#oauth2.hasScope('webclient')" );
   }
}
```
And so on...

But I am surprised to see that only one filterChain is registered. Is it normal or I am doing something wrong? 
I am using Spring Security Oauth2 v2.3.4.RELEASE
Thanks

**Comment by jzheaux** [comment]
@akuma8 thanks for reaching out, it's a good question.

I stumbled onto it on StackOverflow, so I've left my comments there: https://stackoverflow.com/questions/53999591/spring-security-oauth2-how-to-add-multiple-security-filter-chain-of-type-resour/54012754#54012754
