### ISSUE TITLE
OAuth2 reactive callback invalid_redirect_uri_parameter behind reverse proxy

### ISSUE THREAD

**Issue by trecloux** [spring-projects/spring-security#6347]
### Summary

When using OAuth2/OIDC in reactive mode behind a reverse proxy, callback uri fails with error code invalid_redirect_uri_parameter

### Actual Behavior

Before redirecting user to OAuth2 server, redirect URI is computed using `org.springframework.web.util.UriComponentsBuilder#fromHttpRequest` which uses `org.springframework.web.util.UriComponentsBuilder#adaptFromForwardedHeaders`.
When user comes back from OAuth2 server, current URI is compared with stored one, but URI is computed using `org.springframework.web.util.UriComponentsBuilder#fromUri` which does not use `X-Forwarded-*` headers

### Expected Behavior

Compute URI using same mechanism.

### Version

5.1.1.RELEASE

I will submit a pull request

**Comment by rwinch** [comment]
Thanks for the issue and the PR. I'm closing this for the same reasons I outlined in your PR https://github.com/spring-projects/spring-security/pull/6348#issuecomment-452386870
