### ISSUE TITLE
IllegalArgumentException: Detected hex code at position

### ISSUE THREAD

**Issue by peterwkc85** [spring-projects/spring-security#6350]
### Summary
Throw IllegalArgumentException: Detected non hex code at position when decrypt. 

### Actual Behavior
Throw IllegalArgumentException: Detected non hex code at position when decrypt. 

### Expected Behavior
No exception. Decrypt successful

### Configuration
JDK 1.8

### Version
<dependency>
    		<groupId>org.springframework.security</groupId>
    		<artifactId>spring-security-crypto</artifactId>
    		<version>5.1.2.RELEASE</version>
</dependency>

### Sample
```java
public class Cryptographer {

	private TextEncryptor encryptor;
	private static Cryptographer crypto;

	private Cryptographer() {
	}
	
	public static Cryptographer getInstance() {
		if (crypto == null) {
			Security.setProperty("crypto.policy", "unlimited");
			crypto = new Cryptographer();
		}

		return crypto;
	}

	public void generateEncryptedPwd(final String encryptPwd, String filePath) {
		try {
			final String salt = KeyGenerators.string().generateKey();
			encryptor = Encryptors.text(encryptPwd, salt);
			Path encryptedPath = new File(filePath);
			Files.write(encryptedPath, encryptor.encrypt(encryptPwd).getBytes());
		} catch (IOException ex) {
			throw new RuntimeException(ex);
		}
	}

	public String decryptPwd(String filePath) {
		String decryptedStr="";
		try {
			File fr = new File(filePath);
			Scanner sc = new Scanner(fr);
			decryptedStr = sc.nextLine();
			decryptedStr = encryptor.decrypt(decryptedStr);
		} catch (IOException ex) {
			throw new RuntimeException(ex);
		}
		return decryptedStr;
	}

	public static void main(String[] args) {
		Cryptographer.getInstance().generateEncryptedPwd("abcd", "out.txt");
		Cryptographer.getInstance().decryptedPwd("out.txt");
	}
}
```

**Comment by jzheaux** [comment]
@peterwkc85 thanks for the report. I wasn't quite clear on your use case, so I added a `main` method to your sample. Does it correctly reflect the problem?

Running the above sample passes for me, so I think I'm misunderstanding your use case. Could you clarify?

**Comment by peterwkc85** [comment]
Adding a main method is my use case scenario but i don't know why it got such error. Let me post my all code. 

 ```
 crypt.generateEncryptedPwd("demouser", ".\\credential\\phptravels_demo.txt");
 @DataProvider(name = "loginCredentials")
    public Object[][] getLoginCredentials() {
    	return new Object [][] {{"user@phptravels.com", crypt.decrypt("".\\credential\\phptravels_demo.txt"")}};
}
```
    
This is my use case where i write the encrypted password to file and decrypt from file. Please help. Thanks.

**Comment by jzheaux** [comment]
@peterwkc85 Without knowing more detail, I won't be able to guess. Let's move this over to StackOverflow, which is a better place for support questions anyway. Feel free to link that SO question here.

**Comment by jzheaux** [comment]
@peterwkc85 I noticed your conversation with @rwinch [here](https://github.com/spring-projects/spring-security/issues/6364#issuecomment-452793832).

Instead of you trying to maintain several conversations at once, it would be better to take this conversation over to StackOverflow.

Will you please post your question there and link it to this and the other ticket you logged? I think that will get you your answer faster and be better long-term for other folks with the same or similar issue.

**Comment by peterwkc85** [comment]
How to retrieve the encryptor password or using the encryptor password?

**Comment by jzheaux** [comment]
@peterwkc85 Github really isn't the best place for support questions. I'm happy to help you further - please post your question to StackOverflow, and then add a link to your StackOverflow question here. Thanks!
