### ISSUE TITLE
 '#oauth2.xxx' expressions not evaluated with multiple RequestMatchers

### ISSUE THREAD

**Issue by akuma8** [spring-projects/spring-security#6351]
In a multi modules app I've defined 5 RequestMatchers mapped to the same FilterChain, like below:

 ```
   @Configuration
    public class Module1SecurityFilterChain extends ResourceServerConfigurerAdapter {
   
       @Override
       public void configure( HttpSecurity http ) throws Exception {
          http.sessionManagement().sessionCreationPolicy( STATELESS );
          http.requestMatchers().antMatchers( "/module1/**")
                .and()
                .authorizeRequests()
                .antMatchers( "/module1/resource").authenticated()
                .antMatchers( "/module1/test" ).access( "#oauth2.isClient()")
                .anyRequest().access( "#oauth2.hasScope('webclient')" );
       }
    }
```

And module2:

```
    @Configuration
    public class Module2SecurityFilterChain extends ResourceServerConfigurerAdapter {
   
       @Override
       public void configure( HttpSecurity http ) throws Exception {
          http.sessionManagement().sessionCreationPolicy( STATELESS );
          http.requestMatchers().antMatchers( "/module2/**")
                .and()
                .authorizeRequests()
                .antMatchers( "/module2/resource").authenticated()
                .antMatchers( "/module2/test" ).access( "#oauth2.isClient()")
                .anyRequest().access( "#oauth2.hasScope('webclient')" );
       }
    }
```
And enabled method security:

```
    @Configuration
    @EnableGlobalMethodSecurity( prePostEnabled = true, securedEnabled = true )
    public class MethodSecurityConfiguration extends GlobalMethodSecurityConfiguration {
    
        @Override
        protected MethodSecurityExpressionHandler createExpressionHandler() {
            return new OAuth2MethodSecurityExpressionHandler();
        }
    }
```

The problem is that all `#oauth2.xx` expressions are evaluated only for the 1st module requestmatcher `/module1/**` and ignored in others. When I authenticate a user and try to access to `/module1/test` the access is denied as expected whereas when accessing to `/module2/test` access is granted (it should also be denied). 

Could someone explains me why ? Spring Security makes me crazy...
Thanks again.

**Comment by jzheaux** [comment]
Hi, @akuma8. I saw your SO post, thank you for reaching out again, we're here to help. Would you please do me two favors?

1. Please avoid cross-posting support requests. StackOverflow is a great place for help, and team members all allocate dedicated time to be on there answering questions. Posting there will make it clearer for community members who run into similar issues.
2. However, if you are reporting this as a bug, then it will help the team to have you post it in [the correct repository](https://github.com/spring-projects/spring-security-oauth). This particular project is a bit different than the rest because it is a plugin, so it isn't part of Spring Security proper.

**Comment by jzheaux** [comment]
Here is @akuma8's original SO question, for reference: https://stackoverflow.com/questions/54030887/spring-security-oauth2-oauth2-xxx-expressions-not-evaluted-with-multiple-req

**Comment by jzheaux** [comment]
@akuma8 also, feel free to find me in https://gitter.im/spring-projects/spring-security-oauth if you want to chat

**Comment by jzheaux** [comment]
@akuma8 I've logged an issue, https://github.com/spring-projects/spring-security/issues/6359 related to this. Would you be interested in submitting a PR?
