### ISSUE TITLE
AbstractRequestMatcherRegistry should throw an exception when matchers are supplied after anyRequest

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6359]
The following configuration:

```java
http
    .authorizeRequests()
        .anyRequest().authenticated()
        .mvcMatchers("/myendpoint").permitAll();
```

is invalid since matchers are processed in the order they are declared. When a request comes in, regardless of its contents, `anyRequest` will always match it before the filter checks the `/myendpoint` matcher.

Having the matchers in this order is a bit like:

```java
if (true) { 
    // do this
} else if (request == '/myendpoint') {
    // do that
}
```

This is clearly erroneous and the code should fail fast so that the user can correct the misconfiguration.

If `anyRequest()` is invoked then no further calls to `antMatchers`, `mvcMatchers`, `regexMatchers` or `requestMatchers` should be allowed. For any further calls, we should throw an exception with a helpful error message.

**Comment by ankurpathak** [comment]
Here is a pull request:
https://github.com/spring-projects/spring-security/pull/6365
