### ISSUE TITLE
Regression from `5.1.1.RELEASE` and `5.1.2.RELEASE` for event publishing for unsuccessful events.

### ISSUE THREAD

**Issue by bjoernhaeuser** [spring-projects/spring-security#6362]
Thank you very much for all the work you have put into this project!

### Summary

Regression from `5.1.1.RELEASE` and `5.1.2.RELEASE` for event publishing for unsuccessful events.

I think this could changes the behavior:

https://github.com/spring-projects/spring-security/commit/8ef65ce5c59708bbb293314be9308d50f6e053a8

I am not certain if this is the intended behavior and if this is the case what I need to configure differently.

### Actual Behavior

As far as I can see this is that happens:

* Authentication Manager gets instantiated with having a parent Authentication Manager
* Both Authentication Managers have a event publisher set 
* Unsuccessful events get published twice, once on the authentication manager and once on the parent authentication manager

### Expected Behavior

* Event gets only published once

### Configuration

I hope this enough - otherwise it would get a bit complicated :)

```java
@Configuration
public class WebSecurityConfiguration extends WebSecurityConfigurerAdapter
{
    private final List<AuthenticationProvider> authenticationProviders;

    @Autowired
    public WebSecurityConfiguration(List<AuthenticationProvider> authenticationProviders)
    {
        this.authenticationProviders = authenticationProviders;
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception
    {
        http
            .authorizeRequests()
                .antMatchers("/actuator/**").permitAll()
                .anyRequest().authenticated()
            .and()
                .csrf().disable();
    }

    @Override
    protected void configure(AuthenticationManagerBuilder auth) throws Exception
    {
        authenticationProviders.forEach(auth::authenticationProvider);
    }

    @Override
    @Bean
    public AuthenticationManager authenticationManagerBean() throws Exception
    {
        return super.authenticationManagerBean();
    }
}
```

### Version

* Spring Boot 2.1.1
* Spring Security 5.1.2 (not working)
* Spring Security 5.1.1 (working)

**Comment by jgrandja** [comment]
Thanks for the report @bjoernhaeuser. This is related to #6281 which has been resolved.

See #6316 for the backport patch scheduled for 5.1.3.

I'm going to close this issue as the upcoming 5.1.3 release will resolve this issue.

**Comment by bjoernhaeuser** [comment]
Thank you very much for the swift response. Sorry that I was not able to find the referenced issue :(
