### ISSUE TITLE
how to use hasAnyRole in webflux security

### ISSUE THREAD

**Issue by sunwenjieIT** [spring-projects/spring-security#6366]
### webflux use security without any api like hasAnyRole in spring-boot-starter-web

Hello, I use webflux with spring security, but cant find any api like hasAnyRole to set multi role in one matchers().

spring boot version 2.0.7
spring-boot-starter-security version 2.0.7

**Comment by rwinch** [comment]
This is a duplicate of gh-6310 For now you can workaround this using

```java
http
    .authorizeExchange()
        .anyExchange().access(new AuthorityReactiveAuthorizationManager<>("ROLE_A", "ROLE_B"))
...
```
