### ISSUE TITLE
Allow the ability to deny login based on the Oauth2 client for certain user roles

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-projects/spring-security#6378]
### Summary

Allow the ability to deny login based on the Oauth2 client for certain user roles. This is currently possible, but a bit hacky to implement.

### Actual Behavior

In my Spring Boot 2.x application, I have 2 Oauth2 clients. Certain user roles are only allowed to log on via a certain Oauth2 client. See https://stackoverflow.com/questions/54097966/spring-oauth2-authorization-server-differentiate-users-on-clients/54113838#54113838 for somebody that has a similar question

The way I have implemented this now is by overriding the `OAuth2Authentication getOAuth2Authentication(ClientDetails client, TokenRequest tokenRequest)` method in `ResourceOwnerPasswordTokenGranter`. I had to copy some pieces from the original method to be able to put my own code in the middle. I basically added code at line 84: https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/password/ResourceOwnerPasswordTokenGranter.java#L84

At that point I have access to the Oauth2 client id (via `client.getClientId()`) and the user details (via `userAuth.getPrincipal()`). If they don't match like I want, I throw an `InsufficientAuthenticationException`.

### Expected Behavior

To avoid copying part of the methods, it would be great if there was a callback method introduced that passes in the `client` and `Principal` object so that there is no need to copy parts of the original method.

### Version

I am using Spring Boot 2.0.6 with Spring Security Oauth 2.2.3

**Comment by jgrandja** [comment]
@wimdeblauwe Since your issue references the [Spring Security OAuth](https://spring.io/projects/spring-security-oauth) project, can you please log the issue [here](https://github.com/spring-projects/spring-security-oauth/issues). Thank you.
