### ISSUE TITLE
Invalid html in default login page

### ISSUE THREAD

**Issue by bestwmm** [spring-projects/spring-security#6417]
### Summary
Invalid html in spring-security/web/src/main/java/org/springframework/security/web/authentication/defaultLoginPageGeneratingFilter.java::generateLoginPageHtml.

### Actual Behavior
div class="container" at line 237 is not closed.  Closing div required around line 291 before "</body>".

Page does not validate, but Chrome gracioiusly display the page correctly.

### Expected Behavior
Pass validation test.

### Configuration
n/a

### Version
org.spring.framework.boot,l artifactID spring-boot-starter-security version 2.1.0.RELEASE

**Comment by rwinch** [comment]
Thanks for the report @bestwmm! Would you be interested in submitting a PR for this?

**Comment by bestwmm** [comment]
What’s a PR?  (Pull Request + submission with fix?)

**Comment by rwinch** [comment]
Yes. If you are wanting to learn more, GitHub has more information on what a [Pull Request (PR)](https://help.github.com/articles/about-pull-requests/) is. If you are unable to help, that is fine, but your help is always welcome :)

**Comment by ankurpathak** [comment]
@rwinch I would like to take this one.

**Comment by rwinch** [comment]
Thanks @ankurpathak! The issue is yours.

@bestwmm If you are wanting to help out with another issue, please use the Help Wanted tag to find issues we feel are good for contributions.

**Comment by bestwmm** [comment]
> Here is pull request for issue:
> #6448

Thank you.
