### ISSUE TITLE
Consider renaming OidcIdTokenDecoderFactory

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#6425]
We may need to rename `OidcIdTokenDecoderFactory` and `ReactiveOidcIdTokenDecoderFactory` to be more specific, given that both factories create `JwtDecoder` using `ClientRegistration.ProviderDetails.jwkSetUri` for it's key source. There will likely be other factory implementations that create `JwtDecoder` using a different key source, e.g. statically configured key(s).

#5465 may provide some ideas around the possible rename.

Related #6379

**Comment by raphaelDL** [comment]
Something like:

OidcIdTokenDecoderWithJwkSetUriFactory

🤔

**Comment by jgrandja** [comment]
Yeah I was thinking something similar - with JwkSet in the name - but I'm not convinced we want it in the name. This one can wait until #5454 is done which I'm starting work on.

If you're looking for another ticket to work on and having trouble finding one let me know.

**Comment by raphaelDL** [comment]
yup maybe another one, please

**Comment by jgrandja** [comment]
Closing this as the current names make sense and therefore no need to rename.
