### ISSUE TITLE
Support PKCE for Client

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#6446]
We should add client support for [PKCE](https://tools.ietf.org/html/rfc7636).

Related #4943

**Comment by sdoxsee** [comment]
Hi @jgrandja. Added a PR but it's definitely not "ready-to-go". I've added some questions to the PR that can be discussed. Thanks.

**Comment by jgrandja** [comment]
Thanks @sdoxsee ! I will get to this within the next 2 days. Just need to address a couple other issues first.
