### ISSUE TITLE
remember me don't work

### ISSUE THREAD

**Issue by zacader** [spring-projects/spring-security#6450]
remember me don't work .  remember me cookie has Already generated，but when I re-opened the browser visit website, I re-entered the login interface.

my code is here, i don't know what's going wrong.

spring boot version is   2.1.2.RELEASE
spring sercurity version  is   5.1.3 RELEASE
database is sqlserver

```java
@Configuration
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {

    @Resource(name = "MyUserDetailsServiceImpl")
    private UserDetailsService userDetailsService;

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests()
                .antMatchers("/login", "/static/**", "/test").permitAll()
                .anyRequest()
                .authenticated()
                
                .and()
                .formLogin()
                .loginPage("/login")
                .defaultSuccessUrl("/main")
                .failureUrl("/login?failed")
                
                .and()
                .logout()
                .logoutUrl("/logout")
                .logoutSuccessUrl("/login?logout")
                
                .and()
                .rememberMe()
                .rememberMeParameter("loginkeeping")
                .key("yeaGem")

                .and()
                .csrf()
                .disable();

    }
    
    @Override
    protected void configure(AuthenticationManagerBuilder auth) throws Exception {
        auth.userDetailsService(userDetailsService()).passwordEncoder(passwordEncoder());
    }


    @Bean
    @Override
    protected UserDetailsService userDetailsService() {
        return userDetailsService;
    }


    @Bean
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder();
    }


}

@Service("MyUserDetailsServiceImpl")
public class UserDetailsServiceImpl implements UserDetailsService {

    @Resource
    private PasswordEncoder passwordEncoder;

    @Resource
    private CheckersRespository checkersRespository;
    
    @Override
    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
        Checkers checker = checkersRespository.getChecker(username);

        return new User(username, passwordEncoder.encode(checker.getPin()),
                    AuthorityUtils.commaSeparatedStringToAuthorityList(""));


    }


}
```

**Comment by ankurpathak** [comment]
@zacader Can u please provide a Sample 
application.

**Comment by zacader** [comment]
Here is my project [https://github.com/zacader/springbootsecurity](url)    @ankurpathak 
Who can help me solve this problem? I don't know how to solve it.

**Comment by zacader** [comment]
it seems that TokenBasedRememberMeServices.processAutoLoginCookie()  Identified remember me
cookie is invalid and throw 
`InvalidCookieException("Cookie token[2] contained signature '"
					+ cookieTokens[2] + "' but expected '" + expectedTokenSignature + "'");`
Why is this happening?

**Comment by ankurpathak** [comment]
@zacader I don't have SQL Server on my Machine. I was looking for some running simple(can use inmemory database" so I can reproduce the case to  look into it.

**Comment by zacader** [comment]
I have a lot of work to do now, and I will submit a sample when I am free. @rwinch

**Comment by zacader** [comment]
Here is my sample https://github.com/zacader/springbootsecurityh2  @rwinch

**Comment by zacader** [comment]
If my code doesn't have any problems, I really don't know what the problem is. I'm still a novice and I don't know how to solve it. Here is bug repetition video https://github.com/zacader/springbootsecurityh2/blob/master/bug_Demonstration.rar ,
Still in use is my sample https://github.com/zacader/springbootsecurityh2.
Browser：chrome
operating system: win10  x64
I couldn't think of any other details I could provide.
@rwinch

**Comment by zacader** [comment]
I think i did not used incognito and logout . I have implemented remember me use apache shiro.  shiro's 
remember me is working fine. But i still want to know what the problem is, hope to get help.
@rwinch

**Comment by rwinch** [comment]
@zacader The videos you provided do not work for me. Given this is a question rather than a bug/feature enhancement, I'm closing this. Please create a question on StackOverflow.

A few suggestions:

* Try clearing your cookies
* Try another browser
* Include the HTTP request/response for when you log in and when you try to use the remember me feature
* Include logs from Spring Security

You could also try adding a debug point to RememberMeAuthenticationFilter and step through the code to see what is happening.

If you end up finding a bug, please create a new issue with all the details. Otherwise, please post a question to StackOverflow. You may post the link to the question here if you do not get help.
