### ISSUE TITLE
Consider having HeaderWriters check before writing

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6454]
Related to https://github.com/spring-projects/spring-security/issues/5193

`CacheControlHeaderWriter` checks first before writing its corresponding headers.

Since `HeaderWriterFilter` writes headers at the end of a request, it makes sense that each `HeaderWriter` implementation would check whether its corresponding headers have already been written before overriding them.

That is, instead of doing:

```java
response.setHeader(name, value)
```

do:

```java
if (!response.hasHeader(name)) {
    response.setHeader(name, value);
}
```

**Comment by ankurpathak** [comment]
I will be working on this.

**Comment by ankurpathak** [comment]
Here is a pull request:
https://github.com/spring-projects/spring-security/pull/6456
