### ISSUE TITLE
Autoconfiguration of spring security is not working in spring boot 2.1.2.RELEASE

### ISSUE THREAD

**Issue by Aroj** [spring-projects/spring-security#6460]
### Actual Behavior

Endpoints are not getting secured by default even after including sprint security starter in pom.xml from spring boot version 2.1.2.RELEASE.
I am not even getting the below line when using spring boot version 2.1.2.RELEASE on application startup 
   Using default security password: ce6c3d39-8f20-4a41-8e01-803166bb99b6

### Expected Behavior

Endpoints should get secured the moment spring security jar is in the classpath 

### Configuration

Java version used is 1.8
Added below dependency in pom.xml 
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-security</artifactId>
</dependency>

### Version

its occurring in spring boot 2.1.2.RELEASE but not occurring in prior versions

**Comment by jzheaux** [comment]
@Aroj since we have tests to verify scenarios like these, would you please provide a [minimal sample](http://sscce.org/) that reproduces the issue so we can see what we missed?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
