### ISSUE TITLE
exposing setAuthenticationConverter in FormLoginSpec  

### ISSUE THREAD

**Issue by favetelinguis** [spring-projects/spring-security#6475]
Some login flows requires more parameters then user/pwd. If using a cutom login page with additional parameters it would be nice if one could supply a custom `ServerAuthenticationConverter`. The alternative now is to write a fully custom WebFilter to replace the FormLoginSpec.

**Comment by favetelinguis** [comment]
Is [this](https://stackoverflow.com/questions/54310662/pass-additional-login-parameters-from-custom-webflux-loginform?noredirect=1#comment95454689_54310662) SO question a better explanation? If not just tell what I should add to clear the issue.

**Comment by rwinch** [comment]
The SO link you provided doesn't seem to work on additional parameters, so I'm not sure how it relates to your question.

Perhaps you can provide me with a complete sample that illustrates the pain you are currently having?

**Comment by joao-rebelo** [comment]
Lets imagine my Authorization header is in the format: "Basic user:password:myExtension".
Without being able to inject the custom ServerAuthenticationConverter how could we parse this Header value?
I'm having a similar issue, and going to work around as explained in that SO link, but a better solution should be available.

**Comment by joao-rebelo** [comment]
Also to provide custom Authentication Failure Handler to the HTTP Basic doesn't seem to be possible, unless using the hack described in the above SO link.
Shouldn't all these classes "hardcoded" created at ServerHttpSecurity.HttpBasicSpec::configure be somehow possible to inject? Somehow more in a Spring way..

**Comment by rwinch** [comment]
>Lets imagine my Authorization header is in the format: "Basic user:password:myExtension".
Without being able to inject the custom ServerAuthenticationConverter how could we parse this Header value? 

If you are using a header it isn't a formLogin issue, so that isn't an example of how why formLogin needs a custom converter.

**Comment by joao-rebelo** [comment]
> > Lets imagine my Authorization header is in the format: "Basic user:password:myExtension".
> > Without being able to inject the custom ServerAuthenticationConverter how could we parse this Header value?
> 
> If you are using a header it isn't a formLogin issue, so that isn't an example of how why formLogin needs a custom converter.

you are right, I'm mentioning the httpBasic, and this issue was initially opened for formLogin.
But actually the problem happens in both cases where the classes used are not possible to inject / extend in a "Spring" natural way.

**Comment by rwinch** [comment]
The configuration DSL is not intended to provide all the bells and whistles. Instead it is intended to provide the most common configurations. If you have the need to do something complex, then create the Filter and add it explicitly.
