### ISSUE TITLE
OAuth2LoginSpec discovers ReactiveOAuth2AccessTokenResponseClient @Bean

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#6477]
We should allow for a `@Bean` of type `ReactiveOAuth2AccessTokenResponseClient<OAuth2AuthorizationCodeGrantRequest>` to be discovered by `OAuth2LoginSpec`.

This will allow the user to register a `WebClientReactiveAuthorizationCodeTokenResponseClient` `@Bean` with a configured `WebClient` via `WebClientReactiveAuthorizationCodeTokenResponseClient.setWebClient()`.

**Comment by darthCodr** [comment]
Hello @jgrandja Does this have to do with autowiring that bean?

I’ll like to work on it regardless.

**Comment by jgrandja** [comment]
@darthCodr Yes, it's all about wiring the `ReactiveOAuth2AccessTokenResponseClient` `@Bean` if the application has registered it, otherwise same behaviour as today. Take a look at `getOauth2UserService()` or `getOidcUserService()` - it will follow the same pattern.
Please add a test as well. Thanks for taking this on!

**Comment by jgrandja** [comment]
@darthCodr 

> Will my implementation be in `createDefault()`

Yes, this is exactly where you would apply the change.

> Is there a particular method name you would like me to use?

Let's go with `ReactiveOAuth2AccessTokenResponseClient getAccessTokenResponseClient()`

> If the bean is null, should I return null?

It should behave as it currently does today, which is defaulting to `WebClientReactiveAuthorizationCodeTokenResponseClient client = new WebClientReactiveAuthorizationCodeTokenResponseClient()` in `createDefault()`.

**Comment by darthCodr** [comment]
Hello, @jgrandja 
I currently have this:

`		private ReactiveOAuth2AccessTokenResponseClient<OAuth2AuthorizationCodeGrantRequest> getAccessTokenResponseClient() {
			ResolvableType type = ResolvableType.forClassWithGenerics(ReactiveOAuth2AccessTokenResponseClient.class, OAuth2AuthorizationCodeGrantRequest.class);
			ReactiveOAuth2AccessTokenResponseClient<OAuth2AuthorizationCodeGrantRequest> bean = getBeanOrNull(type);

			if (bean ==  null) {
				return new WebClientReactiveAuthorizationCodeTokenResponseClient();
			}
			return bean;
		}`

At what point do I invoke/call `getAccessTokenResponseClient()`?

**Comment by jgrandja** [comment]
You would call it in `createDefault()` and pass it when instantiating `OAuth2LoginReactiveAuthenticationManager`

**Comment by darthCodr** [comment]
Hello @jgrandja I have implemented this and it's fine. 
I'm a bit confused as to where to implement the tests. Kindly assist. Many thanks.

**Comment by jgrandja** [comment]
The tests should go in `OAuth2LoginTests`. Thanks.

**Comment by darthCodr** [comment]
Hello @jgrandja. I found some existing tests in `OAuth2LoginTests` that check `ReactiveOAuth2AccessTokenResponseClient<OAuth2AuthorizationCodeGrantRequest>`. I don't know how to test it without messing up existing code. Is there an implementation I could use as a guide? I would appreciate.

Sincere apologies for the delay.

**Comment by jgrandja** [comment]
@darthCodr 

> I know this might be an urgent fix. Should I do a PR regardless then work through the tests together with you from there?

No worries, it's not urgent. It's planned for 5.2.0.M2 so we have some time. The tests need to go with the PR so let's keep working through it.

> Is there an implementation I could use as a guide?

Take a look at `OAuth2LoginTests.oauth2LoginWhenCustomJwtDecoderFactoryThenUsed()`.

Note how it registers:

```java
		@Bean
		public ReactiveJwtDecoderFactory<ClientRegistration> jwtDecoderFactory() {
			return jwtDecoderFactory;
		}
```

and `jwtDecoderFactory` was declared as:

`ReactiveJwtDecoderFactory<ClientRegistration> jwtDecoderFactory = spy(new JwtDecoderFactory());`

and than in the test we verify that the actual `@Bean` got called:

`verify(config.jwtDecoderFactory).createDecoder(any());`

This is the same type of test logic you need to apply for `ReactiveOAuth2AccessTokenResponseClient`.

Let me know if this helps?

**Comment by darthCodr** [comment]
Thanks a lot for your help @jgrandja
I did a PR gh-6530

Kindly check. Thanks.

**Comment by darthCodr** [comment]
Hello @jgrandja the PR failed.  I can't place what I did wrong. I would appreciate your help with the tests. Many thanks.

**Comment by jgrandja** [comment]
@darthCodr The issue is with this line

`verify(tokenResponseClient).getTokenResponse(any()).thenReturn(Mono.just(accessTokenResponse))`

change it to the following and it will pass

`verify(tokenResponseClient).getTokenResponse(any())`

You will notice a few lines above the `verify` we mock the response with `when`

`when(tokenResponseClient.getTokenResponse(any())).thenReturn(Mono.just(accessTokenResponse))`

Also, since you're putting the test in `oauth2LoginWhenCustomJwtDecoderFactoryThenUsed` we should rename it to keep it generic so we can reuse in this instance. Please rename the following:

`oauth2LoginWhenCustomJwtDecoderFactoryThenUsed` -> `oauth2LoginWhenCustomBeansThenUsed`

`OAuth2LoginWithJwtDecoderFactoryBeanConfig` -> `OAuth2LoginWithCustomBeansConfig`

Thank you!

**Comment by d3jie** [comment]
@jgrandja All checks finally passed. Grateful for the help and the opportunity to contribute.
