### ISSUE TITLE
Add StaticHeadersWriter.setIgnoreIfContainsHeader(boolean)

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#6478]
### Summary

We should add a property to StaticHeadersWriter that indicates it should skip adding a header if the header already exists.

**Comment by ankurpathak** [comment]
I would like to take this one.

**Comment by ankurpathak** [comment]
@rwinch With this issue:
https://github.com/spring-projects/spring-security/issues/6454
and corresponding pull request:
https://github.com/spring-projects/spring-security/pull/6456
now be will be lready checking for if header already exists
before writing header in any HeaderWriter.

**Comment by ankurpathak** [comment]
@mickaeltr We can modify method something like this to acheive:
public void writeHeaders(HttpServletRequest request, HttpServletResponse response) {
		for (Header header : headers) {
			for (String value : header.getValues()) {
				if(!hasHeader(response, header.getName(), value)){
					response.addHeader(header.getName(), value);
				}
			}
		}
	}

	private boolean hasHeader(HttpServletResponse response, String headerName, String headerValue) {
		return response.containsHeader(headerName) && response.getHeaders(headerName).contains(headerValue);
	}

But I thing best will to add flag to skip all headers values at once as per @rwinch suggestion.

**Comment by mickaeltr** [comment]
@ankurpathak In my case, I think that still would not work

I would like my static `Cache-Control` to be: `max-age=0, no-cache, must-revalidate`

I would like to override it, for example with: `max-age=3600`

With your implementation, I understand that I would get `max-age=3600, no-cache, must-revalidate` instead of only `max-age=3600`.

So I am more in favor of an ignoreIfContainsHeader flag, as suggested by @rwinch. Besides that would avoid breaking backward compatibility.

**Comment by ankurpathak** [comment]
@mickaeltr This will cover your case I think.
```
for (Header header : headers) {
			if (!response.containsHeader(header.getName())) {
				for (String value : header.getValues()) {
					response.addHeader(header.getName(), value);
				}
			}
		}
```

**Comment by mickaeltr** [comment]
Yes that would work for me. 👍
However that would break backward compatibility… I am not sure what is the policy about that.

**Comment by rwinch** [comment]
@ankurpathak Thanks for pointing that out. You are right this is a duplicate. 


@mickaeltr You are right to worry about passivity. We will move that discussion to the existing tickets though
