### ISSUE TITLE
WebFlux OIDC expired id token causes 500 status code

### ISSUE THREAD

**Issue by bdemers** [spring-projects/spring-security#6484]
### Summary

For testing I've created a mock OAuth IdP which returns expired (along with otherwise invalid) ID tokens.  These tokens cause 500 status codes to be returned, I would expect any invalid token to result in a 401 status code.

Similar errors also cause 500s, for example if the [expire date is before the issued date](https://github.com/spring-projects/spring-security/blob/ec970c9b8e7c2d669bc80b1bd21ad3ba91a20461/oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/AbstractOAuth2Token.java#L57).

### Version
5.1 and 5.2-SNAPSHOT

**Comment by jgrandja** [comment]
@bdemers I think this is related to #5562

**Comment by bdemers** [comment]
@jgrandja Agreed! though the id token JWT _could_ be invalid after it is received.

Thanks for linking them!

**Comment by jgrandja** [comment]
@bdemers As discussed, would you mind checking to see if this is still an issue on your end?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by bdemers** [comment]
@jgrandja sorry for the delay!
I just tested this again, and I can confirm it is still an issue.

I have some ugly 🤢 code to work around it:

```java
OidcAuthorizationCodeReactiveAuthenticationManager oidc = new OidcAuthorizationCodeReactiveAuthenticationManager(client, oidcUserService) {
        @Override
        public Mono<Authentication> authenticate(Authentication authentication) {
            return wrapOnErrorMap(super.authenticate(authentication));
        }
};
// ...


private static Mono<Authentication> wrapOnErrorMap(Mono<Authentication> authentication) {
    return authentication.onErrorMap(ReactiveOktaOAuth2ServerHttpServerAutoConfig::shouldWrapException,
                                         e -> new UnknownOAuthException("An error occurred while attempting to authenticate: ", e));
}

private static boolean shouldWrapException(Throwable e) {
    return e instanceof IllegalStateException
            || e instanceof JwtException
            || e instanceof AuthenticationException;
}

@ResponseStatus(HttpStatus.UNAUTHORIZED)
static class UnknownOAuthException extends AuthenticationException {
        UnknownOAuthException(String message, Throwable cause) {
            super(message, cause);
        }
}
```

Thoughts ideas?  It's been a while since I looked at this maybe I'm just missing some exception -> response code mapping 

I'm guessing any (or almost any) exception thrown should result in a 40x?

**Comment by jgrandja** [comment]
@bdemers Apologies for the delay. The fix I have in place will resolve this issue along with #5562. Instead of returning 500 status, a 302 status will be returned and redirected to `/login?error`. This is the same behaviour for the servlet version of `oauth2Login()`.
