### ISSUE TITLE
antPathMacher doesn't mache my uri.

### ISSUE THREAD

**Issue by xingfudeshi** [spring-projects/spring-security#6488]
### Summary

i am currently using spring cloud gateway，and using spring security for the access control.(reactive).
i would like give all permission to an uri(exclude it from filter so any one can visit it without login)，the uri is:/image/myImage/view/some md5 value.jpg，but when i configured it as below:
.pathMatchers("/**/view/*").permitAll()
it seems dose not match my uri.

but when i create a antPathMacher，and call the match method like matcher.match("/**/view/*","/image/myImage/view/fyiffdfuuuu553467.jpg")，i will get true as returned value.

**Comment by xingfudeshi** [comment]
spring security 2.0.×

**Comment by jzheaux** [comment]
@xingfudeshi I appreciate what you've done here to reduce this to a very simple and self-contained explanation - I wonder if `/**/**/view/*` works?

Either way, these types of questions are better suited for StackOverflow. If my above suggestion isn't what you need, would you please do me the favor of posting this question to StackOverflow and add to your explanation all matchers listed underneath `authorizeExchanges()`? 

Also, please remember that reactive uses `PathPatternParserServerWebExchangeMatcher`, not `AntPathRequestMatcher`.
