### ISSUE TITLE
Make the ActiveDirectoryLdapAuthenticationProvider class non final

### ISSUE THREAD

**Issue by saagar2000** [spring-projects/spring-security#6490]
Can you please make the ActiveDirectoryLdapAuthenticationProvider non final ?
We can extend the ActiveDirectoryLdapAuthenticationProvider and override the doAuthentication() to perform additional checks before calling the ldap piece.

**Comment by rwinch** [comment]
Thanks for the report. This is a duplicate of gh-3191. Let's move the discussion over there
