### ISSUE TITLE
Overriding GlobalMethodSecurityConfiguration.customMethodSecurityMetadataSource

### ISSUE THREAD

**Issue by jkapec** [spring-projects/spring-security#6491]
In previous Spring versions, bean overriding was allowed, but Spring 5 brings disabling by default. Its OK, but not for creating custom `methodSecurityMetadataSource` definition. I use it for custom annotation defining rules for authorization.
When I override `customMethodSecurityMetadataSource` in my confuiguration extending `GlobalMethodSecurityConfiguration `, I get already defined exception:
```
org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'methodSecurityInterceptor' defined in class path resource [org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration; factoryMethodName=methodSecurityInterceptor; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.class]] for bean 'methodSecurityInterceptor': There is already ...
```
Used code to override:
```
/**
 * Custom configuration of method level security.
 */
@Configuration
@EnableGlobalMethodSecurity(securedEnabled = true, prePostEnabled = true)
public class MethodSecurityConfig extends GlobalMethodSecurityConfiguration {

    @Override
    protected MethodSecurityMetadataSource customMethodSecurityMetadataSource() {
        return new AuthorizeAnnotationSecurityMetadataSource();
    }
}
```

There should be some configurer or looking for bean of instance `MethodSecurityMetadataSource` in method `customMethodSecurityMetadataSource`. Then it will be added to delegate with other sources:
https://github.com/spring-projects/spring-security/blob/5c2ee09bc3a0fe0a14b0aa86d1946542c4ca2aab/config/src/main/java/org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.java#L306

Or even `@ConditionalOnMissingBean` on beans defined in this configuration file will be enough to enable custom bean definition

**Comment by rwinch** [comment]
Thanks for the report. To speed things up a bit can you put together a complete sample and post a link the the project?

> Or even @ConditionalOnMissingBean on beans defined in this configuration file will be enough to enable custom bean definition

We cannot use conditionals in Spring Security's code base because that is a Boot dependency which Spring Security doesn't rely on.

**Comment by jkapec** [comment]
Safe solution can be for example changing in bean initialization method `methodSecurityMetadataSource` to use new `MethodSecurityMetadataSourceConfigurer`:
```
public abstract class MethodSecurityMetadataSourceConfigurer {
	public abstract MethodSecurityMetadataSource getApplicationMethodSecurityMetadataSource();
}
```
then it should like:
```
	@Autowired(required=false)
	MethodSecurityMetadataSourceConfigurer metadataSourceConfigurer;

	@Bean
	public MethodSecurityMetadataSource methodSecurityMetadataSource() {
		List<MethodSecurityMetadataSource> sources = new ArrayList<MethodSecurityMetadataSource>();
		ExpressionBasedAnnotationAttributeFactory attributeFactory = new ExpressionBasedAnnotationAttributeFactory(
				getExpressionHandler());
		
		if (metadataSourceConfigurer != null && metadataSourceConfigurer.getApplicationMethodSecurityMetadataSource() != null) {
			sources.add(metadataSourceConfigurer.getApplicationMethodSecurityMetadataSource());
		}

		MethodSecurityMetadataSource customMethodSecurityMetadataSource = customMethodSecurityMetadataSource();
		...
	}
```

If someone need to use own source, it is enough to create custom `MethodSecurityMetadataSourceConfigurer` bean.

**Comment by rwinch** [comment]
@jkapec Do you have a complete sample that reproduces the issue?

**Comment by SparkMonkey** [comment]
I used the following code as work around :

```
@ComponentScan(basePackages = {"foo.bar"}, excludeFilters = @ComponentScan.Filter(type = FilterType.ASSIGNABLE_TYPE, value = GlobalMethodSecurityConfiguration.class))`
public class BarApplication {
    public static void main(String[] args) {
        SpringApplication.run(NeovaBanqueApplication.class, args);
    }
}
```

So i can do the following without trouble :

```
@Configuration
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class MethodSecurityConfig extends GlobalMethodSecurityConfiguration {

    @Override
    protected MethodSecurityExpressionHandler createExpressionHandler() {
        BarMethodSecurityExpressionHandler expressionHandler = new BarMethodSecurityExpressionHandler();
        // expressionHandler.setPermissionEvaluator(new CustomPermissionEvaluator());
        return expressionHandler;
    }
}
```

**Comment by ieugen** [comment]
I've also encountered this issue while configuring a custom expression evaluator.

**Comment by rwinch** [comment]
Note: We are still waiting on a complete sample to reproduce the problem.

**Comment by SparkMonkey** [comment]
What do you mean by a complete sample ? You mean an entire project ? How ?

I can do it. It's just an empty spring boot 2.1.4 project, with spring security and the code in previous comments.

**Comment by rwinch** [comment]
> I can do it. It's just an empty spring boot 2.1.4 project, with spring security and the code in previous

Thanks that would be very much appreciated.

NOTE: While it seems trivial to ask for the Spring Security team to create the sample, it is important to remember that all the little things we do adds up. FOr this reason, we prioritize issues that have complete samples.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Tugdual** [comment]
I had the same problem on my project. It's not with Spring Boot, but if it can help...

My custom config was ignore because another GlobalSecurityMethodConfiguration was imported before. 
Everything worked just fine after removing the `@Import(OtherCustomConfig.class)` (an d merging it with my custom config)

**Comment by SparkMonkey** [comment]
I failed to reproduce at home from a brand new project.

I'll retry on the environment on which the problem occured soon.

**Comment by martin-g** [comment]
This issue is the same as https://github.com/Activiti/Activiti/issues/2387. There is a reproducer at https://github.com/rasheedamir/vouchers-service

**Comment by rwinch** [comment]
Thanks for the sample to reproduce @martin-g! @jgrandja can you please take a look at this?

**Comment by martin-g** [comment]
The reproduce is not really mine! 
I was just googling for the same issue, found both issues and decided to link them.

**Comment by jgrandja** [comment]
@martin-g The [sample](https://github.com/rasheedamir/vouchers-service) you provided does not raise an exception on application startup. Also, the sample that @rwinch has requested should be an absolute minimal code sample that reproduces the issue - the sample you provided has quite a bit of code and dependencies.

As @rwinch has stated in this [comment](https://github.com/spring-projects/spring-security/issues/6491#issuecomment-494153303), we do require a [minimal sample](https://stackoverflow.com/help/mcve) in order to efficiently troubleshoot and resolve. @jkapec Are you able to provide a sample?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by H-Lo** [comment]
Hi @jkapec,
I had the same issue as you have. Finally I found I had used @EnableGlobalMethodSecurity 2 times.
When removed one of those, the exception disappeared.
I know you mentioned very simple project, but no harm to check.
Also if anyone else comes here, it might help.
BR,
Hrvoje

**Comment by kodiba** [comment]
Hi all,
I can confirm @H-Lo's solution that also was the source of my problem. I did add a custom MethodSecurityConfig with @EnableGlobalMethodSecurity for my project which already contained a WebSecurityConfigurerAdapter with said @EnableGlobalMethodSecurity annotation as well. By removing the latter the exception no longer occured.

**Comment by thomaslevans-wf** [comment]
> Hi @jkapec, I had the same issue as you have. Finally I found I had used @EnableGlobalMethodSecurity 2 times. When removed one of those, the exception disappeared. I know you mentioned very simple project, but no harm to check. Also if anyone else comes here, it might help. BR, Hrvoje

Can also confirm @H-Lo 's solution resolved this issue for me.
