### ISSUE TITLE
Add support for HeaderWriterFilter to write headers at the beginning of the request

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6501]
Related to https://github.com/spring-projects/spring-security/issues/6414

Let's add some support to `HeaderWriterFilter` for writing headers at the beginning of the request:

```java
public void setShouldWriteHeadersEagerly(boolean shouldWriteHeadersEagerly) {
    this.shouldWriteHeadersEagerly = shouldWriteHeadersEagerly;
}
```

Which would then allow folks to post process the `HeaderWriterFilter` and configure it:

```java
http
    .headers()
        .withObjectPostProcessor(new ObjectPostProcessor<HeaderWriterFilter>() {
            public HeaderWriterFilter postProcess(HeaderWriterFilter filter) {
                filter.setShouldWriteHeadersEagerly(true);
                return filter;
            }
        }  
```

`HeaderWriterFilter` writes headers at the end of the request. However, headers cannot be written after an include. 

If the user uses `servletContext.getRequestDispatcher(path).include(request, response)`, for example, then the security headers will not get written.

Spring Security is able to wrap `HttpServletRequest` so that `request.getRequestDispatcher(path).include(request, response)` is captured, but it is not possible to do the same with `ServletContext`.

**Comment by ankurpathak** [comment]
I would like to take this one.

**Comment by jzheaux** [comment]
It's yours, @ankurpathak!

**Comment by ankurpathak** [comment]
Pull request for the issue:
https://github.com/spring-projects/spring-security/pull/6509
