### ISSUE TITLE
Clarify quick start section in README

### ISSUE THREAD

**Issue by mamachanko** [spring-projects/spring-security#6502]
The quick start section of the README points to https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/ saying:

> We recommend you visit Spring Security Reference and read the "Getting Started" page.

However, there is no _Getting Started_ page in the docs.

**Comment by rwinch** [comment]
Thanks for the report. I have made this part of our larger documentation efforts See gh-2567
