### ISSUE TITLE
Question regarding *Spec naming convention

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-security#6507]
It may be too late to change this anyhow, but what's the history behind the use of `*Spec` for a number of configurationish objects? In particular, this collides with Spock conventions and seems like a likely source of build conflicts.

**Comment by rwinch** [comment]
I'm not sure how it will cause build conflicts but you are right here isn't much we can do about this now. This convention comes from Spring Framework.

**Comment by rwinch** [comment]
Closing as answered. If you have follow ups, please feel free to respond and/or reopen
