### ISSUE TITLE
SEC-391: GrantedAuthorityImpl should allow role in role

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#653]
["Wolfgang Aigner":https://jira.spring.io/secure/ViewProfile.jspa?name=wof](Migrated from ["SEC-391":https://jira.spring.io/browse/SEC-391?redirect=false]) said:

It should be possible to add other roles in GrantedAuthorityImpl. This would allow more clear structure of roles.

For example: roleA contains roleB+roleC

**Comment by spring-issuemaster** [comment]
This issue is related to #533
