### ISSUE TITLE
Add section on reactive security in Spring Security Architecture

### ISSUE THREAD

**Issue by paskos** [spring-projects/spring-security#6539]
### Summary

Securing reactive web apps is absent from [Spring Security Architecture](https://spring.io/guides/topicals/spring-security-architecture) topical guide.

**Comment by rwinch** [comment]
Thanks for the report. That guide is not part of the security project itself, but its own repository at https://github.com/spring-guides/top-spring-security-architecture If you want something in that document changed, I would suggest creating a ticket there.

For what it is worth, we are working on efforts to rewrite the entire reference as part of gh-6539. During that rewrite we will be ensuring to include architecture discussions as well.
