### ISSUE TITLE
Where is HttpCookieOAuth2AuthorizationRequestRepository ?

### ISSUE THREAD

**Issue by dennysfredericci** [spring-projects/spring-security#6549]
Hi Folks,

I found the section below in spring [security reference](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2Client-authorization-request-repository).

> If you would like to provide a custom implementation of AuthorizationRequestRepository that stores the attributes of OAuth2AuthorizationRequest in a Cookie, configure it as shown in the following example:
> ```
> 
> @EnableWebSecurity
> public class OAuth2LoginSecurityConfig extends WebSecurityConfigurerAdapter {
> 
> 	@Override
> 	protected void configure(HttpSecurity http) throws Exception {
> 		http
> 			.oauth2Login()
> 				.authorizationEndpoint()
> 					.authorizationRequestRepository(this.cookieAuthorizationRequestRepository())
> 					...
> 	}
> 
> 	private AuthorizationRequestRepository<OAuth2AuthorizationRequest> cookieAuthorizationRequestRepository() {
> 		return new HttpCookieOAuth2AuthorizationRequestRepository();
> 	}
> }
> 
> ```

Where is the HttpCookieOAuth2AuthorizationRequestRepository class? I didn't find this class in spring-security repository, maybe was removed or renamed...

**Comment by dennysfredericci** [comment]
Looks like we never had an official implementation of HttpCookieOAuth2AuthorizationRequestRepository...

https://github.com/spring-projects/spring-security/issues/5313

**Comment by jgrandja** [comment]
@dennysfredericci 

> Where is the HttpCookieOAuth2AuthorizationRequestRepository class?

An implementation was never provided. This is just a sample code snippet showing how to configure a custom `AuthorizationRequestRepository`.

I'm going to close this is answered.
