### ISSUE TITLE
permitAll does'nt work

### ISSUE THREAD

**Issue by ssjsyswa** [spring-projects/spring-security#6551]
### Summary

I set HTTP OPTIONS Request permitAll,But Request also had been intercepted

### Configuration

springboot , vue.js

### Version

Version  :<artifactId>spring-boot-starters</artifactId>
               <version>2.0.6.RELEASE

### Sample

I had  set   
1:) 
HttpSecurity.requestMatchers().antMatchers(HttpMethod.OPTIONS)
                .and()
                .cors()
                .and()
                .csrf().disable();

2:)
CorsRegistry.addMapping("/**").allowedOrigins("*").allowCredentials(true)
            .allowedMethods("GET", "POST", "DELETE", "PUT", "OPTIONS").maxAge(3600).allowedHeaders("*");

3:)
HttpSecurity.addFilterBefore(
                new LoginAuthenticationFilter(
                    new AntPathRequestMatcher("/login"),
                    authenticationManager(),
                    loginAuthenticationHandler),
                UsernamePasswordAuthenticationFilter.class)

I want to keep all the RequestMethod of OPTIONS out of loginFilter, but it does't work

**Comment by clevertension** [comment]
@ssjsyswa it seems that your have misconfigure the cors in step2, can you provide a demo so i can dig more about your problem

**Comment by eleftherias** [comment]
Closing due to lack of feedback.
