### ISSUE TITLE
Handle "query" value for ClientRegistration.ProviderDetails.UserInfoEndpoint.authenticationMethod

### ISSUE THREAD

**Issue by jclagache** [spring-projects/spring-security#6561]
### Summary
Valid values for the ClientRegistration.ProviderDetails.UserInfoEndpoint.authenticationMethod property are [header, form and query](https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#oauth2Client-client-registration).
This property defines the authentication method used when requesting the "UserInfo" resource.

### Actual Behavior
For now, only the "header" and "form" values affect the request : 
- header : add the access token to the http request "AUTHORIZATION" header
- form : add the access token to the http request "access_token" form parameters

### Expected Behavior

the query value should add the access token to the http request query parameters

### Configuration

spring.security.oauth2.client.provider.[providerId].user-info-authentication-method=query

### Version

springBootVersion=2.1.2.RELEASE
version=5.2.0.BUILD-SNAPSHOT

### Sample

https://github.com/jclagache/spring-security/tree/query-method
The [convertWhenAuthenticationMethodQueryThenGetRequestWithAccessTokenQueryParameter](https://github.com/jclagache/spring-security/blob/6443db16473b014c1acfb6aa2b4bc93504c244c7/oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/userinfo/OAuth2UserRequestEntityConverterTests.java#L66) test should pass.

**Comment by jgrandja** [comment]
@jclagache Direct support for adding `access_token` as a query parameter was intentionally left out of the current implementation as this method of transport is not secure. Access tokens passed as query parameters may be leaked via a browser's history and can also be logged in server logs. Please see [Section 3.3.2](https://tools.ietf.org/html/draft-ietf-oauth-security-topics-05#section-3.3.2) for more detail.

If you still want the option to pass the `access_token` via a query parameter, you may implement `Converter<OAuth2UserRequest, RequestEntity<?>>` and set it via `DefaultOAuth2UserService.setRequestEntityConverter()`. See the [reference doc](https://docs.spring.io/spring-security/site/docs/5.1.4.RELEASE/reference/htmlsingle/#oauth2login-advanced-oauth2-user-service) for more detail.

I'm going to close this issue as the current implementation works as designed.
