### ISSUE TITLE
ServerOAuth2AuthorizedClientExchangeFilterFunction does not refresh expired "client credentials" tokens where no refresh token is available

### ISSUE THREAD

**Issue by frzme** [spring-projects/spring-security#6564]
### Summary

When using the WebClient together with the `ServerOAuth2AuthorizedClientExchangeFilterFunction`, configured with a `InMemoryReactiveClientRegistrationRepository` and an `UnAuthenticatedServerOAuth2AuthorizedClientRepository` which holds information about clients which use the "client_credentials" oauth flow the access tokens are never refreshed.

### Actual Behavior

Access tokens are not refreshed.

### Expected Behavior

Since no refresh token is available but all nescessary information is there for client credentials tokens the token should be discarded and a new one should be requested based on the ClientRegistration.

### Version

The issue occurs with spring-security-oauth2-client-5.1.3.RELEASE

### Workaround

A potential workaround seems to be to provide a ServerOAuth2AuthorizedClientRepository which returns empty when loading an AuthorizedClient with an expired token.

**Comment by jgrandja** [comment]
@frzme Looks like this is a duplicate of #5893.
I'm going to close this but if it's not related we can re-open.
