### ISSUE TITLE
OAuth2ClientConfiguration discovers client_credentials OAuth2AccessTokenResponseClient

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#6572]
We should allow for a `@Bean` of type `OAuth2AccessTokenResponseClient<OAuth2ClientCredentialsGrantRequest>` to be discovered by `OAuth2ClientConfiguration`. This would than be associated with `OAuth2AuthorizedClientArgumentResolver.setClientCredentialsTokenResponseClient()`.

Ultimately, this will allow the user to register a `DefaultClientCredentialsTokenResponseClient` `@Bean` with a configured `RestOperations` and/or `Converter<OAuth2ClientCredentialsGrantRequest, RequestEntity<?>>`.

**Comment by jgrandja** [comment]
@fritzdj Thanks for taking this on! To start off, please get familiar with the [Contributing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md) guidelines.

After you setup your spring-security fork in your local dev environment, get familiar with `OAuth2ClientConfiguration` as this is where you will need to apply the updates. Also, take a look at `OAuth2ClientConfigurationTests` to see how to go about writing the test.

Let me know whenever you have any questions.
Thanks!

**Comment by clevertension** [comment]
@fritzdj are you working on this issue? if not, i can provide a PR :stuck_out_tongue:

**Comment by fritzdj** [comment]
Go for it @clevertension. I should have time later this week if you don't get to it.

**Comment by clevertension** [comment]
:thumbsup:, it's yours, go ahead and nice coding

**Comment by fritzdj** [comment]
@jgrandja, can you please respond to my questions from https://gitter.im/spring-projects/spring-security?at=5c81cda88f294b134a0768d2 - I'm not sure which platforms worka best for these types of questions

**Comment by jgrandja** [comment]
@fritzdj 

> I'm not sure which platforms works best for these types of questions.

It's best to keep the questions/dialogue either in this issue or the submitted PR.

> I'm still questioning how to best handle refreshing access tokens

Thanks for catching this! This needs to be implemented in a separate PR so I've logged #6609 to track it.
