### ISSUE TITLE
Spring Security 5 docs references distribution zip, which does not exist

### ISSUE THREAD

**Issue by pashazadeh** [spring-projects/spring-security#6602]
In [Sample Applications](https://docs.spring.io/spring-security/site/docs/5.2.0.BUILD-SNAPSHOT/reference/html5/#sample-apps) part of documentations, the documents mention a distribution zip file. But as far as I saw, there is no such thing for Spring Security 5 (or I couldn't find it).  

I have searched [Spring Repos](https://repo.spring.io/release/) and couldn't find the distribution zip file.

**Comment by stasmihailov** [comment]
apps are present in https://github.com/spring-projects/spring-security/tree/master/samples/xml

**Comment by eleftherias** [comment]
Fixed in gh-6603.
