### ISSUE TITLE
WebSecurityConfigurerAdapter#ignoring().antMatchers(XXX) is maked ineffective when @ComponentScan(basePackages = {"xxx"}) with @SpringBootApplication.

### ISSUE THREAD

**Issue by bahuwang** [spring-projects/spring-security#6607]
### Actual Behavior

When configuration web.ignoring().antMatchers("/userlogin") with @ComponentScan(basePackages = {"xxx"}) with @SpringBootApplication,a message for "error: Unauthorized"  display.
### Version

spring boot 2.1.3.RELEASE

### Sample

package com.example.comscandemo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@ComponentScan(basePackages = {"com.comscan"})
@SpringBootApplication
public class ComscandemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(ComscandemoApplication.class, args);
    }

}

package com.example.comscandemo.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.web.builders.WebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;

@Configuration
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    public void configure(WebSecurity web) throws Exception {
        web.ignoring().antMatchers("/userlogin");
    }
}

package com.example.comscandemo.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class AuthController {

    @GetMapping("/userlogin")
    public void login() {
        System.out.println("userlogin");
    }

    @GetMapping("/userlogout")
    public void logout() {
        System.out.println("userlogout");
    }
}

**Comment by jzheaux** [comment]
Just double-checking here, @bahuwang, your component scanner says:

```java
@ComponentScan(basePackages = {"com.comscan"})
```

But your packages are:

```java
package com.example.comscandemo.*
```

Did everything get pasted correctly?

**Comment by bahuwang** [comment]
There are two packages,"package com.example.comscandemo" and "package com.comscan", the package
"package com.comscan" is even empty. I just want to  describe this case.

**Comment by jzheaux** [comment]
Okay, @bahuwang. Would you please provide a sample that reproduces your issue? That should eliminate any confusion on my side about packages.

**Comment by bahuwang** [comment]
Thank you,@jzheaux.I have uploaded a file #6607.zip to my baidu disk.Its link is "https://pan.baidu.com/s/14VJuw03NLilyaoZ1h-kj7g" and "fetch code" is v3ma. The folder comscandemo-src is sample code and image are screenshots ofcomparison test result.

**Comment by bahuwang** [comment]
If add a @ComponentScan with @SpringBootApplication,you must scan the package manually.
