### ISSUE TITLE
OAuth2AuthorizedClientArgumentResolver should refresh access token when expired and authorization_code

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#6610]
If the `OAuth2AuthorizedClient.accessToken` is expired for a `authorization_code` `OAuth2AuthorizedClient.clientRegistration` and `OAuth2AuthorizedClient.refreshToken` is available than the `OAuth2AuthorizedClientArgumentResolver` should handle refreshing the access token.

This functionality  already exists in `ServletOAuth2AuthorizedClientExchangeFilterFunction.authorizeWithRefreshToken()` (Servlet) and `ServerOAuth2AuthorizedClientExchangeFilterFunction.authorizeWithRefreshToken()` (Reactive).

**NOTE:** This functionality needs to be implemented in both the Servlet and Reactive `OAuth2AuthorizedClientArgumentResolver`.

**Comment by mkheck** [comment]
I'm on it! Thanks Joe.

**Comment by jgrandja** [comment]
Great, thanks @mkheck. Let me know if you have any questions along the way.

**Comment by jgrandja** [comment]
Closing this as invalid - see [comment](https://github.com/spring-projects/spring-security/issues/6609#issuecomment-491067618)
