### ISSUE TITLE
Simplify MediaTypeRequestMatcher construction

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6612]
`MediaTypeServerWebExchangeMatcher` is very easy to use because it simply takes a list of `MediaType`s in its constructor:

```java
public MediaTypeServerWebExchangeMatcher(MediaType... mediaTypes) {
    // ...
}
```

However, `MediaTypeRequestMatcher`, the servlet equivalent, requires the user to supply a `ContentNegotiationStrategy` as well:

```java
public MediaTypeRequestMatcher(ContentNegotiationStrategy contentNegotiationStrategy,
    MediaType... mediaTypes) {
    // ...
}
```

It would be nice if `MediaTypeRequestMatcher` were as easy to use as `MediaTypeServerWebExchangeMatcher`.

**Comment by clevertension** [comment]
@jzheaux are you working on this issue?if not, i think i can provide a PR :grin::grin:

**Comment by jzheaux** [comment]
It's yours, @clevertension

**Comment by clevertension** [comment]
@jzheaux so the `ContentNegotiationStrategy contentNegotiationStrategy` can be null now?

**Comment by jzheaux** [comment]
@clevertension I was thinking that the class could default to a `HeaderContentNegotiationStrategy`. See the JavaDoc for some common usages.
