### ISSUE TITLE
SEC-407: Hitting LogoutFilter's URL when not logged in causes NPE

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#662]
["Matt Raible":https://jira.spring.io/secure/ViewProfile.jspa?name=mraible](Migrated from ["SEC-407":https://jira.spring.io/browse/SEC-407?redirect=false]) said:

After upgrading to 1.0.3, I'm getting the following error when running
some tests:

[INFO] [talledLocalContainer] ERROR - StandardWrapperValve.invoke(260)
| Servlet.service() for servlet jsp threw exception
[INFO] [talledLocalContainer] java.lang.NullPointerException
[INFO] [talledLocalContainer]   at
org.acegisecurity.ui.rememberme.TokenBasedRememberMeServices.logout(TokenBasedRememberMeServices.java:295)
[INFO] [talledLocalContainer]   at
org.acegisecurity.ui.logout.LogoutFilter.doFilter(LogoutFilter.java:98)

Here's what I have in my security.xml context file:

   <bean id="filterChainProxy" class="org.acegisecurity.util.FilterChainProxy">
       <property name="filterInvocationDefinitionSource">
           <value>
               CONVERT_URL_TO_LOWERCASE_BEFORE_COMPARISON
               PATTERN_TYPE_APACHE_ANT

/**=httpSessionContextIntegrationFilter,logoutFilter,authenticationProcessingFilter,securityContextHolderAwareRequestFilter,rememberMeProcessingFilter,anonymousProcessingFilter,exceptionTranslationFilter,filterInvocationInterceptor
           </value>
           
           
       </property>
   </bean>

   <bean id="httpSessionContextIntegrationFilter"
class="org.acegisecurity.context.HttpSessionContextIntegrationFilter"/>

   <bean id="logoutFilter" class="org.acegisecurity.ui.logout.LogoutFilter">
       <constructor-arg value="/index.jsp"/> 
       <constructor-arg>
           <list>
               <ref bean="rememberMeServices"/>
               <bean
class="org.acegisecurity.ui.logout.SecurityContextLogoutHandler"/>
           </list>
       </constructor-arg>
       <property name="filterProcessesUrl" value="/logout.jsp"/>
   </bean>

The problem appears to be caused by trying to logout before you've
tried to login.  This worked fine in previous releases where the
LogoutFilter was present.

**Comment by spring-issuemaster** [comment]
This issue duplicates #668
