### ISSUE TITLE
How to refresh expired access_token automatically  when token relaying from zuul downstream  inner microservices in spring cloud G?

### ISSUE THREAD

**Issue by andyzhaozhao** [spring-projects/spring-security#6636]
### Summary
I have  written a sample https://github.com/andyzhaozhao/cloud-oauth2-jwt-sample 
There are 4 models in the sample:
*  eureka：Eureka Server
*  zuul: as an Oauth2 client , zuul->resource,zuul->openfeign->resource
*  resource: normal microservice as a resource server
* openfeign: as a resource server, openfeign->resource

1.  http://localhost:8080/dc  . everything is right.
2.  http://localhost:8080/openfeign/dc . when the access_token is expired, a problem happened: the access_token is not refresh automatically ?

### Actual Behavior
1. register a client which the access_token_validity is 10sec and refresh_token_validity is 72000sec. so the access_token will expired quickly.
2. visit http://localhost:8080/openfeign/dc  from chrome browser. 
3. after 10sec then visit http://localhost:8080/openfeign/dc .There's a exception: 401
@jgrandja

**Comment by jzheaux** [comment]
@andyzhaozhao Currently, Spring Security's refresh logic is [embedded inside](https://github.com/spring-projects/spring-security/blob/master/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/reactive/function/client/ServletOAuth2AuthorizedClientExchangeFilterFunction.java#L290) of a couple of `ExchangeFilterFunction`s that are handy for `WebClients`, as that was our first use case. 

That said, the request [to extract this logic](https://github.com/spring-projects/spring-security/issues/6711#issue-426080440) is [common](https://github.com/spring-cloud/spring-cloud-security/issues/175#issue-418371556), so it's something we'll likely be looking at.

In the meantime, no, `OAuth2AuthorizeClientService` doesn't refresh the token for you; you would need to do that yourself.
