### ISSUE TITLE
Introduce ReactiveAuthenticationManagerResolver

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6723]
Like `AuthenticationManagerResolver` in #6722, a reactive equivalent would be nice.

**Comment by rhamedy** [comment]
@jzheaux can I work on this?

**Comment by jzheaux** [comment]
@rhamedy I'm glad you're interested!

It would be great to be done in conjunction with https://github.com/spring-projects/spring-security/issues/6727. Could you work on both?

**Comment by rhamedy** [comment]
@jzheaux yes I would be interested in both. I actually commented on the other issue before seeing this 😂
