### ISSUE TITLE
Multi-tenancy for Reactive Resource Server

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6727]
Related to #5351.

Let's add the reactive equivalent of Resource Server's multi-tenancy support.

**Comment by rhamedy** [comment]
@jzheaux Can I work on this? ☺️

**Comment by jzheaux** [comment]
Yes, sir, it's yours!

**Comment by rhamedy** [comment]
Hi @jzheaux 

Started working on this ticket and would be helpful to get some direction from your end. Looking through your PR [PR 6563](https://github.com/spring-projects/spring-security/pull/6563)

- Added
```
@FunctionalInterface
public interface ReactiveAuthenticationManagerResolver<C> {
	Mono<ReactiveAuthenticationManager> resolve(C context);
}
```

- The `Reactive` equivalent of `OAuth2ResourceServerConfigurer` is `ServerHttpSecurity.OAuth2ResourceServerSpec`? Is that correct? Curious what is the design decision behind `ServerHttpSecurity` which contains many nested classes? 🤔

- Declared the `ReactiveAuthenticationManagerResolver` in `ServerHttpSecurity.OAuth2ResourceServerSpec` parametrizing it with `ServerHttpRequest` and added the following

```
public OAuth2ResourceServerSpec reactiveAuthenticationManagerResolver(
		ReactiveAuthenticationManagerResolver<ServerHttpRequest> reactiveAuthenticationManagerResolver) {
	Assert.notNull(reactiveAuthenticationManagerResolver, "reactiveAuthenticationManagerResolver cannot be null");
	this.reactiveAuthenticationManagerResolver = reactiveAuthenticationManagerResolver;
	return this;
}
```

- The changes to the `configure` method of `ServerHttpSecurity.OAuth2ResourceServerSpec` is a little tricky as I am struggling to understand the `Reactive` equivalent of `BearerTokenAuthenticationFilter`. Could be `BearerTokenServerWebExchangeMatcher`?  

- Your PR includes a `sample boot` `oauth2-resourceservier-multitenancy`. What is the requirement for the `Reactive` equivalent? Update existing/Add new one/Do nothing?🤔 

I have read a few articles and Spring blogs on `Reactive` programming and I feel like I could use some more. Do you recommend any resource/tutorial/sample/article that could help me understand the `Spring Reactive` in deeper level? 

Thank you for your usual support 🙂 

Raf.

**Comment by jzheaux** [comment]
> OAuth2ResourceServerSpec

Yes, that's correct. We haven't broken things out yet just because there hasn't yet been the need. 

> BearerTokenAuthenticationFilter equivalent

Actually, there isn't a special filter on the reactive side. The programming model is a bit more simplified on the reactive side. You can see the filter set up just as an [`AuthenticationWebFilter`](https://github.com/spring-projects/spring-security/blob/master/config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java#L1229).

> Reactive sample equivalent

Nothing for the time being - thanks for asking

> articles

This may sound silly, but I'm a lot more of a learn-by-doing person, so I haven't read much more than the [Project Reactor docs](https://projectreactor.io/docs/core/release/reference/). But let me ask the team, and I'll get back to you.
