### ISSUE TITLE
why not org.springframework.security.web.access.expression.WebExpressionConfigAttribute  is not public ?

### ISSUE THREAD

**Issue by ttjkst** [spring-projects/spring-security#6738]
please change org.springframework.security.web.access.expression.WebExpressionConfigAttribute to public

**Comment by jzheaux** [comment]
@ttjkst Can you explain what you are trying to achieve? Making that public might not be the right solution.

**Comment by ttjkst** [comment]
Ｉwant to customized my FilterInvocationSecurityMetadataSource which it can read mata-source from database.And I want to reuse
org.springframework.security.web.access.expression.WebExpressionConfigAttribute code.

**Comment by jzheaux** [comment]
Thanks for the extra detail. Since this is actually a duplicate, let's continue our conversation over on https://github.com/spring-projects/spring-security/issues/1964.
