### ISSUE TITLE
Support for Reactive CAS implementation

### ISSUE THREAD

**Issue by thirunar** [spring-projects/spring-security#6741]
I'm trying to implement **CAS** authentication using `spring-security`. Ours is a reactive app and it seems like `spring-security` doesn't have `WebFilter` for CAS authentication. I also see that `java-cas-client` library doesn't have any reactive support. 

Is there a plan to have a reactive wrapper for CAS authentication in spring-security or Is there documentation to have our own reactive implementation for CAS authentication?

I would love to raise a PR if I get some point to start with.

Thank you!!

**Comment by jzheaux** [comment]
@thirunar It looks like you found https://github.com/spring-projects/spring-security/issues/5887. If you'd like to begin a PR, then that would be a good ticket to work from.

As Rob said, there would need to be a reactive CAS library as well.
