### ISSUE TITLE
Reactive Clear-Site-Data Support

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6743]
Related to #4187 

It would be nice to have the reactive equivalent of Clear Site Data support.

**Comment by sayembd** [comment]
@jzheaux can I please take this issue?

**Comment by jzheaux** [comment]
For sure! It's yours, @sayembd

**Comment by sayembd** [comment]
Hi @jzheaux, I have just added a PR: #6777. Feedback/improvement suggestions are highly appreciated!
