### ISSUE TITLE
Spring Boot 2 upgrade causes "At least one redirect_uri must be registered with the client."

### ISSUE THREAD

**Issue by smitchell** [spring-projects/spring-security#6758]
### Summary

After upgrading an existing authentication server to Spring Boot 2, the shared custom login page in the authentication service no longer redirects the user back to the original protected URI.

### Actual Behavior

1. The user attempts to access a protected, proxied web resource.
2. The user is redirected to the shared, custom login page in the authentication service.
3. The user posts her credentials.
4. Instead of being redirected back to the original website, the error below displays on the page.

```
OAuth Error
error="invalid_request", error_description="At least one redirect_uri must be registered with the client."
```

### Expected Behavior

Upon successful authentication, the browser should be redirected back to the original website.

### Configuration

I scoured our production authentication service for configuration settings specific to the redirect URI but found none. We use a custom ClientDetails object, and its getRegisteredRedirectUri() method always returns an empty Set. Despite that, users get redirected to the original URI after Login. That is no longer the case after upgrading to Spring Boot 2.

I have not been able to recreate the "At least one redirect_uri must be registered with the client." error with a unit test. I would like to be able to do that so I could set a breakpoint and step through what is happening.

### Version

The working production code is running 1.5.13.RELEASE. The updated code is running 2.1.3.RELEASE.

### Sample

See the AuthenticationTests class. I would like to be able to recreate the problem there.

https://github.com/smitchell/spring-security-5-upgrade_sso-auth-server

**Comment by smitchell** [comment]
The other piece to the puzzle is our Zuul/Ribbon proxy server, which is still 1.5.13.RELEASE. I think the answer to how I can write a unit test in the authentication service lies in understanding the interaction with Zuul, or more specifically, the Spring Security 4 @EnableOAuthSso annotation on our proxy service. 

```
  @Configuration
  @EnableOAuth2Sso
  @Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)
  @Slf4j
  protected static class SecurityConfiguration extends WebSecurityConfigurerAdapter {
    @Value("${proxy.permitAll.matches}")
    private String[] matches;
    @Value("${proxy.logoutSuccessUrl}")
    private String logoutSuccessUrl;

    @Override
    protected void configure(HttpSecurity http) throws Exception {
      http
          .logout()
          .invalidateHttpSession(true).permitAll()
          .logoutSuccessUrl(logoutSuccessUrl)
          .and()
          .authorizeRequests()
          .antMatchers(matches).permitAll()
          .anyRequest().authenticated()
          .and()
          .csrf().disable(); //TODO turn this back on
    }
  }
```

**Comment by jzheaux** [comment]
@smitchell, these are good questions. Since your questions are about the `spring-security-oauth` project, would you do me a favor and copy this over to https://github.com/spring-projects/spring-security-oauth? 

I'm happy to copy it myself, but this way, it will preserve the history of who asked the question.

**Comment by smitchell** [comment]
@jzheaux - Josh, I opened a spring-security issue last night. Can it be moved or should I create a new one and refer to it? https://github.com/spring-projects/spring-security/issues/6758

**Comment by jzheaux** [comment]
Would you please create a new one over in `spring-security-oauth`? Thanks!

**Comment by smitchell** [comment]
@jzheaux This issue was moved to https://github.com/spring-projects/spring-security-oauth/issues/1656
