### ISSUE TITLE
Expose GENSALT_DEFAULT_LOG2_ROUNDS as public constant

### ISSUE THREAD

**Issue by Addvilz** [spring-projects/spring-security#6760]
### Summary

Allow public access to default number of rounds currently defined at `org.springframework.security.crypto.bcrypt.BCrypt#GENSALT_DEFAULT_LOG2_ROUNDS`

This would allow adaptive default for library users with increased factor.

Ex. `GENSALT_DEFAULT_LOG2_ROUNDS + 2`.

Whenever the default is updated by the library, factor locally would also bump, allowing for "strength relative to default".

**Comment by eleftherias** [comment]
Thanks for the suggestion, but this is not a feature we would like to add.
We encourage users to choose the encryption strength based on the security requirements for their application.
If an application requires customizing this value, it should use a value intentionally chosen to meet their specific needs and not depend on the defaults that Spring Security uses.
