### ISSUE TITLE
Introduce a Map-based AuthenticationManagerResolver

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6762]
Recently, #6722 introduced a contract for resolving an `AuthenticationManager` via some context, like a request.

A natural implementation for this would be one that contained a `Map<RequestMatcher, AuthenticationManager>` and selected the `AuthenticationManager` from the configured `Map`.

This aligns with other request-matching API implementations like `DelegatingAuthenticationEntryPoint`  and `RequestMatcherDelegatingAccessDeniedHandler`.

**Comment by clevertension** [comment]
i can't find `AuthenticationMatcher` in the repo, do you mean `AuthenticationManager`?

**Comment by jzheaux** [comment]
Good catch, @clevertension. I've updated the description.
