### ISSUE TITLE
can I use AccessDecisionManager and SecurityMetadataSource with web flux 

### ISSUE THREAD

**Issue by umi-soft** [spring-projects/spring-security#6763]
### Summary

can I use `AccessDecisionManager` and `SecurityMetadataSource` with web flux ，
i want to use with spring cloud gateway。 but how to do?

**Comment by nealeu** [comment]
This is a question better asked on StackOverflow.  

You can check out the webflux samples such as https://github.com/spring-projects/spring-security/tree/5.1.x/samples/boot/hellowebflux-method/src/main/java/sample, which I suspect gives you what you need.
