### ISSUE TITLE
Switch to proxy-less configuration by leveraging @Configuration(proxyBeanMethods = false)

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-security#6818]
As part of our Spring efficiency effort, we have recently migrated almost all `@Confguration` in Spring Framework 5.2 and Spring Boot 2.2 to be usable without CGLIB proxies. It would be great for end users and consistent from a portfolio perspective if Spring Security 5.2 could do the same.

[This Spring Framework commit](https://github.com/spring-projects/spring-framework/commit/1a8b3fba9421461869d65318470b3432b62c1f9b) introduced a new `proxyBeanMethods` boolean attribute on `@Configuration` that when set to `false` avoid to create a CGLIB proxy for configuration classes. To be able to use this new capability you "just" have to replace eventual `@Bean` method invocations that where relying on CGLIB by explicit method parameter that will be injected without proxy.

@bclozel did that work on Spring MVC and Spring WebFlux configuration via [this commit](https://github.com/spring-projects/spring-framework/commit/47c8d1de7bde543089792cb9517ec540993b113c). You can also take inspiration from [Spring Boot autoconfigurations](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure)  which have been almost all updated with `@Configuration(proxyBeanMethods = false)`. As a bonus, this would make Spring Security configurations GraalVM native image friendly for free ;-)

A possible process is to manually look through each `@Configuration` annotated class, do a "find usage" on each `@Bean` annotated method, replace invocation by parameter injection, and turn each `@Configuration` to `@Configuration(proxyBeanMethods = false)`. Notice that if you need more flexibility with the bean retrieved, you can leverage `ObjectProvider<Foo>` parameters [like that](https://github.com/spring-projects/spring-boot/blob/36c1c051b8106371d37f8a747cea0e369a8e5c84/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/cache/CaffeineCacheConfiguration.java#L50).

Side notes: I found https://github.com/spring-projects/spring-security/issues/6613 on a connected topic, but targeting Spring Security 6.0 which will be too late for what is discussed here. Notice also that we took the decision to do breaking changes to Spring MVC and WebFlux configuration classes given the fact this topic is high priority for the Spring Boot 2.2 release train.

**Comment by rwinch** [comment]
We can use https://github.com/wilkinsona/spring-boot-development-eclipse-plugin to help find places that need replaced

**Comment by rwinch** [comment]
Thanks for the report @sdeleuze! The changes are now merged into master
