### ISSUE TITLE
Spring Security with Client Cert

### ISSUE THREAD

**Issue by readonlynetwork** [spring-projects/spring-security#6826]
Please add support to get raw certificate for check via HttpSecurity.x509() or new service for arbitrary code 
Sometimes the subject name checking is not enought.
- raw public key checking
- subject alternative names checking

**Comment by rwinch** [comment]
@readonlynetwork If you need more flexibility, I suggest you create your own version of [X509AuthenticationFilter](https://github.com/spring-projects/spring-security/blob/5.1.5.RELEASE/web/src/main/java/org/springframework/security/web/authentication/preauth/x509/X509AuthenticationFilter.java)
