### ISSUE TITLE
OAuth2IntrospectionAuthenticationToken should be marked as @Transient

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6829]
By default, Resource Server should be stateless. This is achieved in its JWT support via the `@Transient` annotation:

```java
@Transient
public class JwtAuthenticationToken
```

For introspection, it would be better if `OAuth2IntrospectionAuthenticationToken` did the same thing:

```java
@Transient
public class OAuth2IntrospectionAuthenticationToken
```

It'd also be good to add a test to confirm that by default no session is created when an app is configured for introspection.

**Comment by huytn12** [comment]
I can help you with this

**Comment by jzheaux** [comment]
Awesome, @huytn12. It's yours!

**Comment by florian42** [comment]
Submitted PR for review: https://github.com/spring-projects/spring-security/pull/6918
