### ISSUE TITLE
Jwt DSL Configuration should accept an AuthenticationManager

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6832]
In Reactive Resource Server, one can switch out the JWT authentication manager:

```java
http
    .oauth2ResourceServer()
        .jwt()
            .authenticationManager(...)
```

It'd be nice to have this same feature on the Servlet side. This `AuthenticationManager` would be used by the `BearerTokenAuthenticationFilter` instead of any shared one.

**Comment by clevertension** [comment]
@jzheaux can i working on this issue?

**Comment by jzheaux** [comment]
Actually, in this case, I nearly have a PR ready myself, I just failed to mark it in progress. Thanks for checking, though, @clevertension!

**Comment by clevertension** [comment]
@jzheaux it's good, thanks for reply :smiley:
