### ISSUE TITLE
DelegatingSecurityContextAsyncTaskExecutor causes potential memory leak

### ISSUE THREAD

**Issue by zulname** [spring-projects/spring-security#6837]
I am using a DelegatingSecurityContextAsyncTaskExecutor to pass the security context on to async threads. The threads are taken from a Pool which is configured as:

	  @Bean
	  public TaskExecutor threadPoolTaskExecutor() {
		final ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
		executor.setCorePoolSize(10);
		executor.setMaxPoolSize(100);
		executor.setQueueCapacity(50);
		executor.setThreadNamePrefix("Leak-");
		executor.initialize();

		return new DelegatingSecurityContextAsyncTaskExecutor(executor);
	  }

That basically is working. However, when the application is stopped or the server is shut down an exception is thrown when the threads are to be cleared.

	03-May-2019 08:28:10.561 WARNUNG [Thread-4] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [leak] appears to have started a thread named [Leak-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
	 java.base@11.0.2/jdk.internal.misc.Unsafe.park(Native Method)
	 java.base@11.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	 java.base@11.0.2/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	 java.base@11.0.2/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
	 java.base@11.0.2/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
	 java.base@11.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
	 java.base@11.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	 java.base@11.0.2/java.lang.Thread.run(Thread.java:834)
 
The problem does not appear when the spring boot app is booted with the embedded tomcat.

The problem as well does not appear when the TaskExecutor is not using a DelegatingSecurityContextAsyncTaskExecutor

	  @Bean
	  public TaskExecutor threadPoolTaskExecutor() {
		final ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
		executor.setCorePoolSize(10);
		executor.setMaxPoolSize(100);
		executor.setQueueCapacity(50);
		executor.setThreadNamePrefix("Leak-");
		executor.initialize();

		return executor;
	  }

However, the SecurityContext is needed in the Threads.

Versions used:
- spring boot 2.1.4.RELEASE
- [tomact 9.0.17](https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.17/) (both the embedded and the locally installed tomcat)

I attached a fairly basic application using maven as a [zip file](https://github.com/spring-projects/spring-security/files/3141016/leakBug.zip).
1. install tomcat
2. download, extract and build (mvn clean install) the project
3. call (e.g. via postman or curl) http://localhost/leak/api/customers/save/foo/bar
4. verify in the console the customer was saved (logging)
5. stop the application via the tomcat application manager or shutdown the tomcat
6. check in the catalina.log of tomcat

I had a look at the hanging thread after the app was stopped in tomcat with visualvm. The thread "Leak-1" is in state 'WAITING'. 
![screenshot](https://user-images.githubusercontent.com/50229862/57125368-7ad16080-6d89-11e9-8156-f636d2704e4d.jpg)

I cannot really identify the object the thread is waiting for. I am not profound in finding / analyzing memory leaks.

Could anyone please check whether that is a bug in spring security?

**Comment by rwinch** [comment]
Thanks for reaching out! `ThreadPoolTaskExecutor` is a `DisposableBean` which means that to shut it down properly `ThreadPoolTaskExecutor.destroy()` must be invoked. 

In sample where you are only using `ThreadPoolTaskExecutor` (i.e. not using `DelegatingSecurityContextAsyncTaskExecutor`) the `ThreadPoolTaskExecutor` is exposed as a bean. Since it is a Bean and implements `DisposableBean`, Spring will automatically invoke it's `destroy()` method.

In the sample where you are using `DelegatingSecurityContextAsyncTaskExecutor`, the `ThreadPoolTaskExecutor` is not exposed as a bean so it will not invoke `destroy()`. The solution is to do something like this:

```
  @Bean
  public ThreadPoolTaskExecutor threadPoolTaskExecutor() {
	ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
	executor.setCorePoolSize(10);
	executor.setMaxPoolSize(100);
	executor.setQueueCapacity(50);
	executor.setThreadNamePrefix("Leak-");
    // no need to invoke initialize because it is an initializing bean
    // which automatically invokes afterPropertiesSet which in turn
    // invokes initialize
	return executor;
  }

  @Bean
  public DelegatingSecurityContextAsyncTaskExecutor taskExecutor(ThreadPoolTaskExecutor delegate) {
     return new DelegatingSecurityContextAsyncTaskExecutor(delegate);
  }
```

A few notes:
* DelegatingSecurityContextAsyncTaskExecutor has no knowledge of if the delegate implements InitializaingBean or DisposableBean (nor does it know if it implements Closable, etc) and nor should it. It is only concerned with the API it delegates to
* You can then autowire using qualifiers.
* If you cannot control how it is autowired, you can use `@Primary`.

Let me know if this helps.

**Comment by zulname** [comment]
Thanks very much. That solved the reported problem. There is one remaining exception which I have not reported above but still persists. When stopping the app or shutting it down I get the following warning.

	06-May-2019 08:35:12.794 WARNUNG [http-nio-11003-exec-16] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [leak] registered the JDBC driver [org.h2.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
	
However, that seems to be related to [tomcat and the respective JDBC driver](https://stackoverflow.com/questions/3320400/to-prevent-a-memory-leak-the-jdbc-driver-has-been-forcibly-unregistered) as he thread http-nio-11003-exec-16 is not the async thread I configured.

In my app in question which uses an oracle db it presents itself as:

	06-May-2019 08:20:51.344 WARNUNG [http-nio-11003-exec-9] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [main-app] registered the JDBC driver [oracle.jdbc.OracleDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
	06-May-2019 08:20:51.346 WARNUNG [http-nio-11003-exec-9] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [main-app] appears to have started a thread named [oracle.jdbc.driver.BlockSource.ThreadedCachingBlockSource.BlockReleaser] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
		java.base@11.0.2/java.lang.Object.wait(Native Method)
		oracle.jdbc.driver.BlockSource$ThreadedCachingBlockSource$BlockReleaser.run(BlockSource.java:327)

In case you would agree we can close this issue. Thanks again for your help!

**Comment by rwinch** [comment]
I don't think I'm in a good position to answer your question authoritatively as it seems unrelated to Spring Security. However, it does seem like it could be the same issue. I'd suggest reaching out to Spring Framework or Tomcat to investigate the issue further.

Given this...I'm going to close the issue.

**Comment by drahkrub** [comment]
Another possibility:

    @Bean
    public TaskExecutor threadPoolTaskExecutor() {

        final ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setCorePoolSize(10);
        executor.setMaxPoolSize(100);
        executor.setQueueCapacity(50);
        executor.setThreadNamePrefix("Leak-");
        executor.initialize();

        return new DelegatingSecurityContextAsyncTaskExecutor(executor) {
            public void shutdown() {
                executor.destroy();
            }
        };
    }
