### ISSUE TITLE
oauth2 open 2 login page redirect not correct

### ISSUE THREAD

**Issue by BerserkGuts** [spring-projects/spring-security#6846]
**scenario**
     I have an oauth2 server  implemented by using @EnableAuthorizationServer and two oauth client implemented by using @EnableOAuth2Sso. Eeverything goes well when I only open one login page at a time and login into system.
**problem**
- When I request one url then redirect to login page,I don't login in immediately，I just open a new tab of same browser and request same url，and redirect to login page again.Then I input username and password,the first login page login successfully and redirect to the right url,second login page login successfully but goes 404.If these two login use different username then the second user will overwrite first one in oauth2 server session,but in oauth2 client still the first user 
-  When I request one url of oauth client A  then redirect to login page,I don't login in immediately，I just open a new tab of same browser and request one url of oauth client B，and redirect to login page again.Then I input username and password,the first login page  logined successfully but redirect to client B!

**My requirements**
    I know these problems come from the redirect url is saved in session and same browser shares this session.To differ session between browser tabs is no sense because user need to login again when open new tab but they want sso.It's difficult to set a default redirect url since my oauth2 server is an independent system.So I just want to block the second login behavior after first login success.Is there any suggestion?

**Comment by jgrandja** [comment]
@BerserkGuts This question is mean for the [Spring Security OAuth](https://spring.io/projects/spring-security-oauth) project and therefore should be logged [here](https://github.com/spring-projects/spring-security-oauth/issues).

Also, we prefer questions be posted on StackOverflow, as issues are meant for bug reports and new feature requests or enhancements.

I'm going to close this issue but feel free to log this question on StackOverflow
