### ISSUE TITLE
SEC-424: MethodDefinitionMap - Can't access inherited methods

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#685]
["Luc Boudreau":https://jira.spring.io/secure/ViewProfile.jspa?name=lucboudreau](Migrated from ["SEC-424":https://jira.spring.io/browse/SEC-424?redirect=false]) said:

See : http://forum.springframework.org/showthread.php?p=94634

The MethodDefinitionMap can't secure any inherited method. Line 123 of the java file has to be modified as follows :
### Eclipse Workspace Patch 1.0
# P acegisecurity
# Index: core/src/main/java/org/acegisecurity/intercept/method/MethodDefinitionMap.java

RCS file: /cvsroot/acegisecurity/acegisecurity/core/src/main/java/org/acegisecurity/intercept/method/MethodDefinitionMap.java,v
retrieving revision 1.6
diff -u -r1.6 MethodDefinitionMap.java
--- core/src/main/java/org/acegisecurity/intercept/method/MethodDefinitionMap.java  17 Nov 2005 00:56:09 -0000  1.6
+++ core/src/main/java/org/acegisecurity/intercept/method/MethodDefinitionMap.java  9 Jan 2007 14:45:34 -0000
@@ -165,7 +165,7 @@
                 + "] with attributes [" + attr + "]");
         }
-        Method[] methods = clazz.getDeclaredMethods();
- ```
     Method[] methods = clazz.getMethods();
   List matchingMethods = new ArrayList();
  
   for (int i = 0; i < methods.length; i++) {
  ```

**Comment by spring-issuemaster** [comment]
This issue duplicates #360
