### ISSUE TITLE
SecurityContextRequestPostProcessorSupport small-improvements

### ISSUE THREAD

**Issue by ch4mpy** [spring-projects/spring-security#6857]
1. `SecurityContextRequestPostProcessorSupport` does not define abstract method. There is no need for it to be abstract
2. `SecurityContextRequestPostProcessorSupport` is stateless. There is no need for it to be a parent class, it can be a collaborator or an interface instead
3. both `SecurityContextRequestPostProcessorSupport` and `TestSecurityContextRepository` could be of great use to framework users wishing to extend testing features.

I'm asking to change `SecurityContextRequestPostProcessorSupport` an `TestSecurityContextRepository` visibility to `public`.

I also propose to modify existing request post-processors so that it use `SecurityContextRequestPostProcessorSupport` as collaborator instead of extending it.

**Comment by rwinch** [comment]
Can you describe what you are trying to achieve that is not simple at this time?

**Comment by ch4mpy** [comment]
I can't contribute test `MockMVC` request post-processor or `WebTestClient` extending something else (breaks existing patterns as all other security related `RequestPostProcessor`s extend `SecurityContextRequestPostProcessorSupport`).

Use case at the very bottom ofhttps://github.com/ch4mpy/spring-security/blob/gh-6634--jwt-reactive-flow/test/src/main/java/org/springframework/security/test/web/servlet/request/SecurityMockMvcRequestPostProcessors.java, `JwtRequestPostProcessor` definition

**Comment by ch4mpy** [comment]
@rwinch, I won't be able any longer to execute changes you would request. When opening this ticket,  I thought a week would have been enough to solve it. I now have to go at sea, with almost no Internet connection for the coming two month, sorry. I hope I managed to give modification rights to Spring team.

Please note there are two commits on this branch:
* first removes all dependencies from request post-processors to SecurityContextRequestPostProcessorSupport as parent and add it as collaborator on the only few requiring it
* second holds visibility modifications and moves of newly public classes to their own files

**Comment by rwinch** [comment]
I'm closing this as invalid because user's can easily delegate to the existing public APIs to achieve the same things. For example:

```java

@Override
public MockHttpServletRequest postProcessRequest(MockHttpServletRequest request) {
	Authentication authentication = ...;
	return SecurityMockMvcRequestPostProcessors.authentication(token).postProcessRequest(request);
}
```
