### ISSUE TITLE
Repeating configure cors of http security doesn't work.

### ISSUE THREAD

**Issue by JokerSun** [spring-projects/spring-security#6862]
In my case, I will construct a dev environment for a web developer, then she hopes to debug in local, so I write the spring security config like this:
```
@Order(1)
@Configuration
public class DemoConfig extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.authorizeRequests()
			.anyRequest()
			.permitAll()
			.and();
	}
}

@Configuration
@Profile(WebProfile.WEB_PROFILE_DEV)
@Order(2)
class DevWebSecurityConfig extends WebSecurityConfig {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.cors()
			.and();
	}

	@Bean
	@Profile(WebProfile.WEB_PROFILE_DEV)
	CorsConfigurationSource corsConfigurationSource() {
		CorsConfiguration configuration = new CorsConfiguration();
		configuration.addAllowedOrigin(CorsConfiguration.ALL);
		configuration.setAllowCredentials(true);
		configuration.setAllowedMethods(Arrays.asList("GET", "POST", "DELETE", "OPTIONS"));
		configuration.setMaxAge(3600L);
		UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
		source.registerCorsConfiguration("/**", configuration);
		return source;
	}
}
```

The code is very simple that allows cors if the 'dev' profile is active, but it doesn't work.
So, I change my code to this:
```
@Order(1)
@Configuration
public class DemoConfig extends WebSecurityConfigurerAdapter {

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.authorizeRequests()
			.anyRequest()
			.permitAll()
			.and()
			.cors()
			.and();
	}

	@Bean
	@Profile(WebProfile.WEB_PROFILE_DEV)
	CorsConfigurationSource corsConfigurationSource() {
		CorsConfiguration configuration = new CorsConfiguration();
		configuration.addAllowedOrigin(CorsConfiguration.ALL);
		configuration.setAllowCredentials(true);
		configuration.setAllowedMethods(Arrays.asList("GET", "POST", "DELETE", "OPTIONS"));
		configuration.setAllowedHeaders(Arrays.asList("Token", "Content-Type"));
		configuration.setMaxAge(3600L);
		UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
		source.registerCorsConfiguration("/**", configuration);
		return source;
	}
}
```
OK, it work, but why.
I can't understand why repeating configure http security doesn't work.

**Comment by rwinch** [comment]
`DemoConfig` and `DevWebSecurityConfig` are different slices of the application and only the first slice that matches will be executed. This means that for the first configuration `DemoConfig` is being used for the request which does not have cors enabled. One way to fix it is to enable cors in the `DemoConfig`. Another is to add a `@Profile` to `DemoConfig` so it is disabled if the developer profile is enabled.

Keep in mind doing profiles like that (i.e. such that you flex configuration significantly between dev and prod) tends to make you find issues after you deploy to production.

If you still have issues, please move this to StackOverflow which is better for asking for help vs reporting a bug or requesting a feature.

**Comment by JokerSun** [comment]
@rwinch Thanks for your reply, I have split my configuration into 'dev' and 'prod' already, that works well.
