### ISSUE TITLE
Add OAuth2LoginSpec.authenticationSuccessHandler

### ISSUE THREAD

**Issue by rexave** [spring-projects/spring-security#6863]
In imperative spring security configuration, we can customize the `successHandler` of an `oAuth2Login` configuration with
`org.springframework.security.config.annotation.web.configurers.AbstractAuthenticationFilterConfigurer#successHandler`

I didn't find this feature in reactive branch of spring security on `org.springframework.security.config.web.server.ServerHttpSecurity#oauth2Login`

### Version
spring security 5.1.5

Can you port this feature in reactiv implementation ?
How can I change the behavior of spring security after a successful oAuth ?
Maybe with a `org.springframework.security.config.web.server.ServerHttpSecurity#addFilterAt` ? But how can i know the authentication was successful ?

**Comment by rwinch** [comment]
This sounds like a reasonable enhancement request. Would you be interested in submitting a Pull Request?

As you mentioned you can work around this using `addFilterAt`. See https://github.com/spring-projects/spring-security/blob/e7f93f221d4b828d336627f5147a3edd02a8c28d/config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java#L814 for what needs to be done

**Comment by dnl50** [comment]
I would like to submit a pull request in case @rexave is not interested!

**Comment by rexave** [comment]
of course @dnl50 
Your help is appreciated :) I didn't had the time lately  =]
