### ISSUE TITLE
OAuth2LoginAuthenticationFilter should set AuthenticationDetails

### ISSUE THREAD

**Issue by ddevrien** [spring-projects/spring-security#6866]
### Summary

`OAuth2LoginAuthenticationFilter` is not setting a `WebAuthenticationDetails` on the `OAuth2AuthenticationToken` object that is returned. It does set a WebAuthenticationDetails on the authenticationRequest but this instance is lost later on.

 I'm doing some post-processing in a `AuthenticationSuccessHandler ` using a custom WebAuthenticationDetails which is currently only working for form login, not for OAuth2 login.

### Actual Behavior

AuthenticationDetails is always null when using OAuth2 login

### Expected Behavior

An instance of  `WebAuthenticationDetails` is set.

**Comment by rwinch** [comment]
Thanks for reaching out @ddevrien! Would you be interested in submitting a Pull Request for this?

**Comment by ddevrien** [comment]
PR made: https://github.com/spring-projects/spring-security/pull/6884
I'm not really familiar with Github and I wasn't sure how to reference a PR to this issue 😃
