### ISSUE TITLE
addFilterAt use a SecurityWebFiltersOrder converted to int instead of int

### ISSUE THREAD

**Issue by rexave** [spring-projects/spring-security#6873]
### Summary

It is impossible to **add** a custom filter because it replace the default filter.

### Actual Behavior

in `org.springframework.security.config.web.server.ServerHttpSecurity#addFilterAt`

`.addFilterAt(myFilter, SecurityWebFiltersOrder.AUTHENTICATION)`
add the filter "somewhere around" `AuthenticationWebFilter` :)

### Expected Behavior

`.addFilterAt(myFilter, SecurityWebFiltersOrder.AUTHENTICATION+50)`
or
`.addFilterAt(myFilter, 722)`
or
`.addFilterAfter(myFilter, OtherFilter.class)`

### Configuration

```
http
    .cors().and()
    .csrf().disable()
    .securityMatcher(ServerWebExchangeMatchers.pathMatchers("/**"))
        .authorizeExchange()
            .pathMatchers("/login/**").permitAll()
            .pathMatchers("/oauth/**").permitAll()
            .pathMatchers("/logout").permitAll()
            .pathMatchers("/**").authenticated()

        .and()

            .oauth2Login()

        .and()
            .logout()
                .logoutUrl("/logout")
                .logoutSuccessHandler(new HttpStatusReturningServerLogoutSuccessHandler(HttpStatus.OK))
        .and()
            .addFilterAt(myFilter, SecurityWebFiltersOrder.AUTHENTICATION)
```

### Version

5.1.5.RELEASE

**Comment by rwinch** [comment]
Thanks for the report! Support for `addFilterBefore` and `addFilterAfter` was added in gh-6138
