### ISSUE TITLE
Allow http basic auth to be configured using nested builder

### ISSUE THREAD

**Issue by eleftherias** [spring-projects/spring-security#6885]
Support nested builder
------
Currently HTTP basic authentication can be configured in the following way.
```
http
	.httpBasic()
	.realmName("Realm");
```

We should allow configuration using a nested builder, as follows.
```
http
	.httpBasic(httpBasicConfig -> httpBasicConfig.realmName("Realm"));
```
The remaining methods should also be available in the nested builder, `authenticationEntryPoint`, `authenticationDetailsSource`.

Remove need for `and()`
------
Any subsequent configurations to HttpSecurity will **not** need to be chained using `and()`.
```
http
	.httpBasic(httpBasicConfig -> httpBasicConfig.realmName("Realm"))
	.cors();
```

Nest `disable()`
------
HTTP basic authentication should be disabled using a nested builder as well
```
http
    .httpBasic(HttpBasicConfigurer::disable);
```
note: `HttpBasicConfigurer` may not be the appropriate class name.

**Comment by rwinch** [comment]
To keep things simple I'd say we should hold off on `httpBasic(HttpBasicConfigurer::disable)` since users will be able to do `httpBasic(httpBasicConfig -> httpBasicConfig.disable())`.

**Comment by eleftherias** [comment]
@rwinch I believe those are equivalent (assuming that we continue to use the `HttpBasicConfigurer`). The IDE will actually prompt you to replace the lambda with the method reference.

**Comment by rwinch** [comment]
Oops. My mistake. You are right :)
