### ISSUE TITLE
UnAuthenticatedServerOAuth2AuthorizedClientRepository cannot be used within running request handlers

### ISSUE THREAD

**Issue by jjstreet** [spring-projects/spring-security#6888]
### Summary
`UnAuthenticatedServerOAuth2AuthorizedClientRepository` throws an assertion failure because `ServerWebExchange` is not null when trying to use a client_credential protected resource during a web request. The associated `OAuth2AuthorizedClientResolver` ends up grabbing and providing the current ServerWebExchange from the current context.

### Actual Behavior

I attempted to use an `UnAuthenticatedServerOAuth2AuthorizedClientRepository` instance for a oauth2 server exchange filter function to let me use client_credential access tokens during the processing of a users request. This was described by several publications as a viable choice for client_credential type flows. As stated above, this causes `UnAuthenticatedServerOAuth2AuthorizedClientRepository` to fail an assertion that the ServerWebExchange is null. I was able to trace the ServerWebExchange attribute from the ClientRequest and tracked it to `OAuth2AuthorizedClientResolver.currentServerWebExchange()`.

### Expected Behavior

I was expecting no failed assertion.

### Workaround/Potential solution

Remove Assertion that current server web exchange is null, if this type of repository should be allowed within a user request.

### Configuration

Spring WebFlux with Netty
Spring Boot 2.1.5
Spring Security 5.1.7

### Related Question

It seems that according to the java docs for `UnAuthenticatedServerOAuth2AuthorizedClientRepository`, I am using the class correctly, but it may really only should be used during server to server communication outside of a user request process.

**Comment by rwinch** [comment]
Thanks for the report @jjstreet! @jgrandja will look at this soon

**Comment by jjstreet** [comment]
I can see a need for client_credential protected resources to be accessible both during and outside of a user request. To keep my complexity low, Id like to reuse WebClient instances, especially if they are wrapped by a business-oriented class. Therefore, I think being able to use this repository in both cases is beneficial. Especially since the other implementations of `ServerOAuth2AuthorizedClientRepository` aren't usable outside a user request.

**Comment by jgrandja** [comment]
@jjstreet 

> ...trying to use a client_credential protected resource during a web request

`UnAuthenticatedServerOAuth2AuthorizedClientRepository` is not meant to be used in the context of a web request. The javadoc states:

> Provides support for an unauthenticated user. **This is useful when running as a process with no 
 user associated to it**.

`UnAuthenticatedServerOAuth2AuthorizedClientRepository` is meant to be used **outside of a web request** only. For example, in a java application that acts as a CLI or a background async process.

For web applications, you should be using `AuthenticatedPrincipalServerOAuth2AuthorizedClientRepository` in the context of a request.

I'm going to close this issue as works as designed. We can re-open if you are still having issues with your setup.

**Comment by jgrandja** [comment]
@awilhelmer It's not totally clear to me the issue you are having as you mention more than one thing? Also, questions should be posted on StackOverflow. If you have an issue with a specific feature or are looking for a new feature than please log a new issue instead of posting to a closed issue.

Have you read up on the reference documentation to see what features are available. I would recommend starting [here](https://docs.spring.io/spring-security/site/docs/5.2.0.RELEASE/reference/htmlsingle/#oauth2).
