### ISSUE TITLE
SEC-428: Security interceptor does not work with schema based aop:config

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#689]
["Jonny Wray":https://jira.spring.io/secure/ViewProfile.jspa?name=jwray](Migrated from ["SEC-428":https://jira.spring.io/browse/SEC-428?redirect=false]) said:

When configuring security method interceptors using the schema based aop:config the acegi interceptor is not invoked. This was discussed on the forum at http://forum.springframework.org/showthread.php?t=33742.  Example configuration, that does not work. The securityInterceptor is not called but the transactionInterceptor is.

<aop:config proxy-target-class="true">
    <aop:pointcut id="serviceMethods" expression="execution(* net.fiveprime.services.*.*(..))"/>
    <aop:advisor advice-ref="transactionInterceptor" pointcut-ref="serviceMethods" order="1" />
    <aop:advisor advice-ref="securityInterceptor" pointcut-ref="serviceMethods" order="2" />  
/aop:config

changing the configuration to the pre-spring 2.0 method 

<bean class="org.springframework.aop.framework.autoproxy.BeanNameAutoProxyCreator">
   <property name="proxyTargetClass" value="true" />  
   <property name="beanNames" value="*Services, cacheManager"/>
   <property name="interceptorNames">
   <list>
    <value>transactionInterceptor</value>
    <value>securityInterceptor</value>
    </list>
     </property>
</bean>

and both transaction and security interceptors are invoked.

**Comment by spring-issuemaster** [comment]
This issue depends on #360
