### ISSUE TITLE
Mock Jwt Support should accept a fully-configured Jwt

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6896]
A tester can configure a mock request with a `Jwt` like so:

```java
this.mvc.perform(get("/")
    .with(jwt()))
// ...
```

Or like so:

```java
this.mvc.perform(get("/")
    .with(jwt(jwt -> jwt.subject("sub"))))
// ...
```

It'd be nice to also accept a fully-configured `Jwt`:

```java
Jwt jwt = // ...
this.mvc.perform(get("/")
    .with(jwt(jwt)))
// ...
```

Both on the servlet side as well as the reactive side:

```java
Jwt jwt = // ...
this.client
    .mutateWith(mockJwt(jwt))
// ...
```

**Comment by sandmannn** [comment]
Hi, I would like to pick this up

**Comment by jzheaux** [comment]
Thanks, @sandmannn! It's yours.

**Comment by jzheaux** [comment]
@sandmannn how are things coming? Do you have any questions?

**Comment by sandmannn** [comment]
I think servlet and reactive can be addressed in different PRs. Lets start iterating on servlet part in this PR https://github.com/spring-projects/spring-security/pull/6923 
What would be the best place to put tests for it? Up to now I found only https://github.com/sandmannn/spring-security/blob/d0f5b428847c1050d38da7d2af98eb2cda6a9b9e/samples/boot/oauth2resourceserver/src/test/java/sample/OAuth2ResourceServerControllerTests.java where the existing jwt() calls are used in  `mockMvc.perform(get(....).with(jwt()))` style, as you specified in original post.

**Comment by jzheaux** [comment]
I'd recommend placing them in https://github.com/spring-projects/spring-security/blob/master/test/src/test/java/org/springframework/security/test/web/servlet/request/SecurityMockMvcRequestPostProcessorsJwtTests.java
