### ISSUE TITLE
SEC-429: @Secured on implementation classes

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#690]
["Jonny Wray":https://jira.spring.io/secure/ViewProfile.jspa?name=jwray](Migrated from ["SEC-429":https://jira.spring.io/browse/SEC-429?redirect=false]) said:

The behavior of @Secured and the org.acegisecurity.intercept.method.aopalliance.MethodSecurityInterceptor is not consistent with core spring. In order for the @Secured annotations to be used the interceptor needs the property proxyTargetClass set to true. This is case even if the target class has an interface. With core spring using proxyTargetClass=true is only needed when the class to be intercepted does not have an interface.

This is related to this closed issue SEC-151

**Comment by spring-issuemaster** [comment]
This issue depends on #689
