### ISSUE TITLE
Firebase Authentication oauth2login

### ISSUE THREAD

**Issue by ELIASIVANCARRILLO** [spring-projects/spring-security#6905]
Hi all

Is it possible to implement Firebase based authentication using Oauth2Login with Spring boot 2.1?? I want to implement social login with Google, Facebook and TW, all of these through Firebase authentication.

Thanks

**Comment by jgrandja** [comment]
@ELIASIVANCARRILLO Questions are better suited on StackOverflow. Please search on StackOverflow first and if you can't find the answer than please post your question there.

We prefer to use GitHub issues for bug reports or new feature and enhancement requests.
