### ISSUE TITLE
OAuth2AuthorizedClientResolver discards any refresh_token in clientCredentialsResponse() 

### ISSUE THREAD

**Issue by aaronjwhiteside** [spring-projects/spring-security#6912]
### Summary

`OAuth2AuthorizedClientResolver` discards any `refresh_token` in `clientCredentialsResponse()` 

The spec states that 
> A refresh token SHOULD NOT be included.

https://tools.ietf.org/html/rfc6749#section-4.4.3

Which means it's possible but not recommend to send a `refresh_token` for the Client Credentials Grant type.

> 4. SHOULD NOT   This phrase, or the phrase "NOT RECOMMENDED" mean that
   there may exist valid reasons in particular circumstances when the
   particular behavior is acceptable or even useful, but the full
   implications should be understood and the case carefully weighed
   before implementing any behavior described with this label.

https://tools.ietf.org/html/rfc2119

If a refresh token is supplied in the response it should not be discarded by the client.

### Actual Behavior

`refresh_token`'s in Client Credentials Grant are discarded.

### Expected Behavior

`refresh_token`'s in Client Credentials Grant should not be discarded.

`OAuth2AuthorizedClientResolver.clientCredentialsResponse()` should be changed to pass the refresh token to the `OAuth2AuthorizedClient` constructor.

### Version

5.1.5.RELEASE

**Comment by jgrandja** [comment]
@aaronjwhiteside I'm closing this as a client configured for `client_credentials` should **renew** an expired access token by fetching a new one instead of **refreshing** using a refresh token. Please see the [comment](https://github.com/spring-projects/spring-security/issues/6913#issuecomment-497759618) for additional details.
