### ISSUE TITLE
ServerOAuth2AuthorizedClientExchangeFilterFunction does not deal with expired client_credentials tokens

### ISSUE THREAD

**Issue by aaronjwhiteside** [spring-projects/spring-security#6913]
### Summary

`ServerOAuth2AuthorizedClientExchangeFilterFunction` does not deal with expired `client_credentials` tokens

### Actual Behavior

Tokens obtained via

```java
ClientRegistration clientRegistration = ClientRegistration
    .withRegistrationId("xxx")
    .authorizationGrantType(AuthorizationGrantType.CLIENT_CREDENTIALS)
    // etc...
```

And have expired are not refreshed or re-requested.

This causes the filter to make requests to resources with expired tokens, indefinitely. 

Obviously those requests fail..

### Expected Behavior

It is possible but not recommended for a provider to return a `refresh_token` for a `grant_type` of `client_credentials`, due to https://github.com/spring-projects/spring-security/issues/6912 if a provider does return a `refresh_token` it is discarded and never used to refresh the expired `client_credentials` token.

If a `refresh_token` is supplied the normal `ServerOAuth2AuthorizedClientExchangeFilterFunction.refreshAuthorizedClient()` flow should be followed.

However if no `refresh_token` is supplied and the `client_credentials` token has expired a new `client_credentials` token should be requested from the provider..

And the old one should be removed from the `ServerOAuth2AuthorizedClientRepository` and not used in subsequent requests.

### Version

5.1.5.RELEASE

**Comment by jgrandja** [comment]
@aaronjwhiteside This feature has been implemented via #5893. It's been available since 5.2.0.M1 release.
