### ISSUE TITLE
BCrypt passwordEncoder rely on toString()

### ISSUE THREAD

**Issue by ublanquet-concord** [spring-projects/spring-security#6917]
Security guidelines recommend you don't use strings for sensitive data like password, but the current BCrypt implementation rely on it.

http://docs.oracle.com/javase/6/docs/technotes/guides/security/crypto/CryptoSpec.html#PBEEx
> It would seem logical to collect and store the password in an object of type java.lang.String. However, here's the caveat: Objects of type String are immutable, i.e., there are no methods defined that allow you to change (overwrite) or zero out the contents of a String after usage. This feature makes String objects unsuitable for storing security sensitive information such as user passwords. You should always collect and store security sensitive information in a char array instead.

**Comment by kostya05983** [comment]
@jzheaux  What do you think about it? Can I take this in develop?

**Comment by jzheaux** [comment]
Actually, @kostya05983, this is a duplicate of https://github.com/spring-projects/spring-security/issues/3238 - thank you, though, for your interest. You can take a look at [issues tagged with "status: ideal-for-contribution"](https://github.com/spring-projects/spring-security/issues?q=is%3Aissue+is%3Aopen+label%3A%22status%3A+ideal-for-contribution%22) for additional ideas.
