### ISSUE TITLE
Allow for configuring an Authentication Converter for OAuth Resource Server opaque tokens

### ISSUE THREAD

**Issue by bdemers** [spring-projects/spring-security#6963]
### Summary

The new opaque token support is great!

I'd love it if the API matched the JWT equivalent with regards to configuration an authentication converter.  For example:
```java
httpSecurity.oauth2ResourceServer().jwt().jwtAuthenticationConverter(...)
```

Maybe something like:
```java
httpSecurity.oauth2ResourceServer().opaqueToken().tokenAuthenticationConverter(...)
```
Where the converter would take a `Map<String, Object>` of claims.

Basically just allowing the additional processing to convert custom claims into authorities, similar to what how OAuth2IntrospectionAuthenticationProvider works:

https://github.com/spring-projects/spring-security/blob/b1195e7789521845752b91677285f9ff5eeeb6b0/oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/OAuth2IntrospectionAuthenticationProvider.java#L129-L135

Since this is possible already for JWT tokens adding something similar for opaque tokens would be great.

Thanks!

**Comment by rwinch** [comment]
Thanks for the report @bdemers! @jzheaux will look at this soon

**Comment by jzheaux** [comment]
@bdemers, thanks for the report! Glad to hear you like the support.

This feature definitely appears useful, and we're looking into addressing it in https://github.com/spring-projects/spring-security/issues/6830.

**Comment by jzheaux** [comment]
Closing in favor of #6830
