### ISSUE TITLE
Add DefaultAuthenticationManagerResolver

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#6976]
There ought to be a simple way to configure multi-tenancy for common use cases like by domain, by path, and by header.

Being able to do something like

```java
@Bean 
public AuthenticationManagerResolver<HttpServletRequest> byHeader
        (Converter<String, AuthenticationManager> lookupByTenant) {
    return DefaultAuthenticationManagerResolver.resolveByHeaderValue
            ("X-Tenant-Id", lookupByTenant);
}
```

might be nice.

**Comment by rwinch** [comment]
Some thoughts...perhaps create `DefaultAuthenticationManagerResolver` which allows injecting a Converter for the request to be converted into an id and then another Converter for the id to be converted into a manager. Then static factory methods on it that resemble byHeader as shown above

**Comment by jzheaux** [comment]
We could achieve the same thing with:

```java
static <T> AuthenticationManagerResolver<HttpServletRequest> byRequestConverter
        (Converter<HttpServletRequest, T> requestConverter, 
                Converter<T, AuthenticationManager> resolver)
```

However, I do like the idea of a concrete implementation that can hold state. I've updated the PR accordingly.
