### ISSUE TITLE
Allow deep customize for nonstandard OAuth 2.0 provider.

### ISSUE THREAD

**Issue by zhangyanwei** [spring-projects/spring-security#7004]
I've reported `spring-security` related issue in the wrong place (in `spring-boot` project).
The link of that issue I wanted to report: https://github.com/spring-projects/spring-boot/issues/17148

I have pointed out that wechat not only the authentication URL does not follow the specification, but other aspects also not follow, however, I can customize them without `javassist`.

In my opinion, do not need to support the nonstandard OAuth 2.0 providers, but make the code more flexible to allow the developers can deep customize them.

The spring security version I'm using is **5.1.5.RELEASE**.

**Comment by jgrandja** [comment]
@zhangyanwei 

> make the code more flexible to allow the developers can deep customize them

There already is quite a bit of flexibility in customizing. Can you be more specific on what exactly you are trying to customize?

**Comment by zhangyanwei** [comment]
Wechat requires the query parameters in the authentication URL to keep a specific order, but there is no way to customize the build method in `OAuth2AuthorizationRequest$Builder`.

And `OAuth2AuthorizationRequest` hasn't public constructor for outside creation.

**Comment by jgrandja** [comment]
@zhangyanwei `OAuth2AuthorizationRequestResolver` provides the capability to fully customize the Authorization Request. Please review the sample code in the [reference doc](https://docs.spring.io/spring-security/site/docs/5.1.5.RELEASE/reference/htmlsingle/#oauth2Client-authorization-request-resolver).

I'm going to close this issue as the link provided shows you how to customize.

**Comment by zhangyanwei** [comment]
@jgrandja I have read the documentation and code, but I meant to build a URL (`authorizationRequestUri` field in `OAuth2AuthorizationRequest` class) with ordered query parameters.

For example, WeChat requires the authentication URL is:

https://open.weixin.qq.com/connect/oauth2/authorize?appid=APPID&redirect_uri=REDIRECT_URI&response_type=code&scope=SCOPE&state=STATE#wechat_redirect

If I changed the query parameters' order, like this:

https://open.weixin.qq.com/connect/oauth2/authorize?redirect_uri=REDIRECT_URI&appid=APPID&response_type=code&scope=SCOPE&state=STATE#wechat_redirect

* `appid` and `redirect_uri` got swapped.

That will not works.
BTW, 
1. It also requires `#wechat_redirect` fragment contains in the URL, otherwise may cause unknown errors in the WeChat client. 
1. WeChat is using `appid` instead of `client_id`.

The problem I've met is: I can't use the builder of `OAuth2AuthorizationRequest` to do it since there is no way for me to tell the builder to keep the order of query parameters and append the fragment into the URL(This has done in `buildAuthorizationRequestUri`).

**Comment by jgrandja** [comment]
@zhangyanwei 

> I meant to build a URL (authorizationRequestUri field in OAuth2AuthorizationRequest class) with ordered query parameters.

The documentation shows how you can build the full URL for `authorizationRequestUri`:

> The following example shows a variation of the `customAuthorizationRequest()` method from the preceding example, and instead overrides the `OAuth2AuthorizationRequest.authorizationRequestUri` property.

```java
private OAuth2AuthorizationRequest customAuthorizationRequest(
        OAuth2AuthorizationRequest authorizationRequest) {

    String customAuthorizationRequestUri = UriComponentsBuilder
            .fromUriString(authorizationRequest.getAuthorizationRequestUri())
            .queryParam("prompt", "consent")
            .build(true)
            .toUriString();

    return OAuth2AuthorizationRequest.from(authorizationRequest)
            .authorizationRequestUri(customAuthorizationRequestUri)
            .build();
}
```

The code snippet above shows this. You have full control on building the custom URL `customAuthorizationRequestUri` and than setting it in `OAuth2AuthorizationRequest.Builder.authorizationRequestUri`.

**Comment by zhangyanwei** [comment]
@jgrandja Thank you for your patience. I haven't even noticed it, I'll be more careful.

**Comment by jgrandja** [comment]
@zhangyanwei No worries. We do want to ensure that our API's provide flexibility for customizations even when the provider doesn't comply with the related specifications. So please do let us know if you run into a situation where there isn't an option to customize and we'll do our best to accommodate.
