### ISSUE TITLE
SEC-440: Documentation:  Correction in CAS chapter (section 18.3.2) of Acegi Security documentation for v1.0.3

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#701]
["Mat Lowery":https://jira.spring.io/secure/ViewProfile.jspa?name=mat.lowery](Migrated from ["SEC-440":https://jira.spring.io/browse/SEC-440?redirect=false]) said:

In the Acegi Security documentation for CAS (http://acegisecurity.org/docbook/acegi.html#cas-server-3), the instructions
say:

"Copy Acegi-security.jar file into /localPlugins/lib."

I believe they should say:

"Copy Acegi-security.jar and Acegi-security-cas.jar files into /localPlugins/lib."

Otherwise, you'll get a java.lang.ClassNotFoundException: org.acegisecurity.adapters.cas3.CasAuthenticationHandler.

**Comment by spring-issuemaster** [comment]
This issue duplicates #698
