### ISSUE TITLE
Internal BadCredentialException/UsernameNotFoundException

### ISSUE THREAD

**Issue by pyoung36** [spring-projects/spring-security#7022]
### Summary

Our Monitoring agent is picking up on BadCredentialsException and UsernameNotFoundException thrown internally by spring-security despite valid credentials being supplied and access ultimately being granted. We believe we can work around by implementing our own DaoAuthenticationProvider, but we would very much like to avoid having to maintain replacements for core spring code.

### Actual Behavior

During BasicAuthenticationFilter, a ProviderManager iterates through each of the possible AuthenticationProviders it will check it against the credentials supplied by client. Each time it fails to match we will see BadCredentialsException/UsernameNotFoundException(they appear in pairs) via monitoring software. This occurs even when AbstractUserDetailsAuthenticationProvider.hideUserNotFoundExceptions is set to true.

We would expect that exceptions related to invalid credentials are only thrown after the client supplied credentials have been checked against all possible valid credentials, not after each match in the valid credentials collection fails. Is it possible that instead of using a List<AuthenticationProviders> you use something that allows getting key-value pairs instead of a list that requires iteration?

### Configuration

We are customizing the BasicAuthenticationFilter by extending WebSecurityConfigurerAdapter with the following configuration. 
```
    @Override
    protected void configure(final HttpSecurity http) throws Exception {
        http
            .cors()
            .and()
            .csrf()
            .disable()
            .anonymous()
            .disable()
            .sessionManagement()
            .sessionCreationPolicy(SessionCreationPolicy.STATELESS)
            .and()
            .authorizeRequests()
            .antMatchers("/rest/**")
            .hasAnyRole(apiProperties.getAuthRoles().stream().toArray(String[]::new))
            .and()
            .httpBasic();
    }

	
    @Autowired
    public void registerGlobalAuthentication(final AuthenticationManagerBuilder auth) {

        Stream
                .of(basicAuthServiceAccountProperties.getServiceAccounts())
                .map(Map::entrySet)
                .flatMap(Set::stream)
                .map(Entry::getValue)
                .filter(Objects::nonNull)
                .forEach((serviceAccount) -> {
                    try {
                        auth
                            .inMemoryAuthentication()
                            .withUser(serviceAccount.getUserName())
                            .password(encoder.encode(serviceAccount.getPassword()))
                            .roles(serviceAccount.getRoles());
                    } catch (Exception e) {
                        log.error("Failed to load users into authentication manager.");
                    }
                });

    }
```

### Version

spring-boot-starter-parent = 2.1.5.RELEASE
spring-boot-starter-security = 2.1.5.RELEASE
spring-security-core = 5.1.5.RELEASE

We observe the same behavior in 2.0.3 and 2.1.4. 

### Sample

Unfortunately this is proprietary code. I have supplied as much as I can. I will keep a close eye and fulfill any additional requests/questions, though. Additionally, here is the stack monitoring is picking up on. 

![spring_sec_call_stack](https://user-images.githubusercontent.com/52006378/59782951-12810480-928d-11e9-8902-6461a825e03e.png)

###Conclusion

We are hoping to hear any of the below, from best to worst. Thank you for your hard work! :)

1. A fix will get implemented in an upcoming release
2. There is a configuration change we can make that we have overlooked.  
3. A fix will never get implemented for reasons, and we hack together some kind of work around

**Comment by pyoung36** [comment]
Do I need to supply more information?

**Comment by rwinch** [comment]
Thanks for the report. This is the intended behavior as the code is trying to authenticate a user against the provider and it fails.

Can you explain what problems this is causing you?

**Comment by pyoung36** [comment]
It is creating situations during incident response where anyone who is not familiar with this internal behavior sees transaction traces like below which distract them from finding the real issues. It has been a general thorn in our side but was deemed low priority until recently as new management wants to see cleaner traces. 

Is there an alternative to httpBasic that does not use that ProviderManager, maybe? Thanks for responding.


![bad_creds_pp](https://user-images.githubusercontent.com/52006378/60348796-4d222580-998e-11e9-8a33-a0dc392bb368.png)

**Comment by rwinch** [comment]
ProviderManager is implemented such that it will try each AuthenticationProvider in turn. How would a Map help?

It sounds as though you have multiple DaoAuthenticationProvider instances each trying to authenticate the users. If that is the case, I'm not sure what you can do to avoid exceptions being thrown during authentication other than providing your own AuthenticationProvider implementation that tries multiple UserDetailsService instances. Note that creating a custom AuthenticationManager won't help because the DaoAuthenticationProvider will still throw an Exception.

Even if you mask the authentication related exceptions there are going to be other sources of exceptions throughout security that might cause similar concerns. My suggestion is to look at error logs to troubleshoot incidents. Since these exceptions are never logged to error, it should not interfere with troubleshooting.

**Comment by rwinch** [comment]
I'm going to close this as invalid. Exceptions are allowed to be thrown if they are handled properly (which they are in this case). Incidents should use error logs to troubleshoot (not Exceptions that are being cleanly handled).

**Comment by pyoung36** [comment]
Thank you. Providing our own DaoAuthenticationProvider accomplishes what we desire.
