### ISSUE TITLE
Fix docs typo WebSecurityConfigurationAdapter->WebSecurityConfigurerAdapter

### ISSUE THREAD

**Issue by him-bhar** [spring-projects/spring-security#7026]
https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#multiple-httpsecurity

Checking latest documentation of spring security, section (6.10) multiple-httpsecurity.

First line says:
We can configure multiple HttpSecurity instances just as we can have multiple <http> blocks. The key is to extend the **_WebSecurityConfigurationAdapter_** multiple times.

Whereas, the correct class is **_WebSecurityConfigurerAdapter_**.

Can you please correct the documentation to remove this confusion.

**Comment by jzheaux** [comment]
@him-bhar is there a reason that you closed the issue?

Would you be interested in submitting a PR with the corrected documentation?

**Comment by kostya05983** [comment]
Hello, @jzheaux, I want to participate and submit a PR in documentation. Where can I start?

**Comment by jzheaux** [comment]
@kostya05983 thanks for your interest!

You can find the incorrect reference by searching here in GitHub: https://github.com/spring-projects/spring-security/search?q=WebSecurityConfigurationAdapter&unscoped_q=WebSecurityConfigurationAdapter

The PR you'd want to do would be to update that reference in that file to say `WebSecurityConfigurerAdapter` instead.

There are some general [contribution guidelines](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md) that should answer any other questions, but please feel free to ping me if anything else isn't clear.

**Comment by kostya05983** [comment]
Thanks for response, @jzheaux I submitted a PR.

**Comment by him-bhar** [comment]
Sorry guys checked after a long time. I was working on a different version of spring boot. So wasn't sure if class name hasn't actually changed. Looks like initial observation was correct. :)

**Comment by him-bhar** [comment]
Will keep an eye on such more issues.
