### ISSUE TITLE
SEC-442: AbstractProcessingFilter.obtainFullRequestUrl is static and cannot be overridden

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#703]
["Jon Osborn":https://jira.spring.io/secure/ViewProfile.jspa?name=jonnio](Migrated from ["SEC-442":https://jira.spring.io/browse/SEC-442?redirect=false]) said:

The static nature of the method means that the saved request url returned for redirect cannot be overridden. This means that the saved request cannot be adjusted as may be required by certain implementations. For example, the saved request URI is the INTERNAL uri which may not match the actual browser request due to front end proxy appliances, etc. The redirect issued to the browser in these cases must be either a fully qualified URL OR a RELATIVE url to maintain the correct client context.

This could be resolved by
1) adding a new protected method that returns the SavedRequest from the session.
2) add a new protected method with a signature similar to : protected String obtainFullRequestUrl( HttpServletRequest request, SavedRequest savedRequest );
3) call method created in 2) from the existing static obtainFullRequestUrl for compatibility.
4) modify AbstractProcessingFilter.successfulAuthentication() such that it calls the protected method, thus allowing clients to override the saved url for a context appropriate url.

**Comment by spring-issuemaster** [comment]
This issue is related to #669
