### ISSUE TITLE
Why the Custom AuthenticationEntryPoint dos'n working in the ClientCredentialsTokenEndpointFilter

### ISSUE THREAD

**Issue by lix1898** [spring-projects/spring-security#7030]
### Summary
Why the Custom AuthenticationEntryPoint  dos'n  working in the ClientCredentialsTokenEndpointFilter
version： spring-security5.1.5

### Actual Behavior
After configuring CustomAuthenticationEntryPoint.

when visit the 'http://localhost:60001/oauth/token' to refresh token with error client_secret，
ClientCredentialsTokenEndpointFilter.authenticationEntryPoint  still is the OAuth2AuthenticationEntryPoint 

### Expected Behavior
ClientCredentialsTokenEndpointFilter.authenticationEntryPoint  = CustomAuthenticationEntryPoint

### Configuration
```
public void configure(HttpSecurity http) throws Exception {
        http.formLogin()
                .loginPage("/login")
                .loginProcessingUrl("/user/login")
                .successHandler(authenticationSuccessHandler)
                .failureHandler(authenticationFailureHandler)
            .and()
                .authorizeRequests().antMatchers("/login","/user/login","/user/logout","/oauth/token").permitAll()
            .and()
                .exceptionHandling().accessDeniedHandler(accessDeniedHandler)
            .and()
                //  CustomAuthenticationEntryPoint dos'n   working in the ClientCredentialsTokenEndpointFilter
                 // authenticationEntryPoint is not null，debug can see CustomAuthenticationEntryPoint
                .exceptionHandling().authenticationEntryPoint(authenticationEntryPoint)

        ;
    }
```

**Comment by jgrandja** [comment]
@lix1898 Could you please log this issue with the [Spring Security OAuth](https://github.com/spring-projects/spring-security-oauth/issues) issues. Also, please provide a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the issue. I would also recommend searching and/or posting on StackOverflow. Thank you.
