### ISSUE TITLE
How to authenticate user using refresh token if user was logged in before.

### ISSUE THREAD

**Issue by santhoshgs** [spring-projects/spring-security#7031]
I am using spring security Oauth2 api's to authenticate the user. I have configured Google as authenticator  in my application and used oauth2Login() on HttpSecurity in WebSecurityConfigurerAdapter. 
Very first login of user generates both access token and refresh token from google.. So, am trying to understand can we authenticate the user when he tries to login for the second time using the  refresh token generated from the first login, so that user need not to enter his username/password again. 
So, far i googled to find any possible way to achieve it, but could not find anything. 
Please let me know how we can achieve this.

### Version
Spring boot version - 2.1.5
Spring outh2 version - 2.1.0

**Comment by jgrandja** [comment]
@santhoshgs The [`refresh_token`](https://tools.ietf.org/html/rfc6749#section-6) grant is used to refresh an expired access token - it's not meant to be used for authentication. Also, please post questions on StackOverflow as we prefer to keep issues for bug reports and feature requests. Thank you.
