### ISSUE TITLE
SecurityConfigurer.init Javadoc should state that applying other configurers should be performed in this method

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#7038]
### Summary

The [Javadoc for SecurityConfigurer.init()](https://docs.spring.io/spring-security/site/docs/4.2.12.RELEASE/apidocs/org/springframework/security/config/annotation/SecurityConfigurer.html#init-B-) should clarify that applying configurers should be performed in init as well.

**Comment by clementkng** [comment]
Hi @rwinch, could I try taking a stab at this issue?

**Comment by rwinch** [comment]
@clementkng Thanks for volunteering! Yes the issue is yours.

**Comment by clementkng** [comment]
> applying configurers should be performed in init as well

@rwinch I'm a little confused by this statement. Where else are configurers applied? Does this statement mean that each `configure(SecurityBuilder)` is invoked (in the top of the spec, describing the `SecurityConfigurer` interface)?

**Comment by rwinch** [comment]
Most of the methods on `HttpSecurity` apply a configurer. For example, invoking `formLogin` invokes a configurer. If you are to do that within another Configurer..it must be done in the init method
