### ISSUE TITLE
spring oauth2Login() + google authentication - Why browser logout of google and accessing application in new browser taking to login page

### ISSUE THREAD

**Issue by santhoshgs** [spring-projects/spring-security#7044]
I am using spring boot + spring security Oauth2 + google for authentication. I have used outh2Login() from spring security for google login. I could do google login and get the access token. But, once i login to google via my application , it also gets logged into browser. If i logout the google browser and continue using my application in the same browser, everything works fine. but, if i use new browser to access my application, it's taking me to login page and asking me to login to google.

Please let me know, why google browser logout affecting my application ?

**Comment by jgrandja** [comment]
@santhoshgs As mentioned in this [comment](https://github.com/spring-projects/spring-security/issues/7031#issuecomment-505602391), please post questions on [StackOverflow](https://stackoverflow.com/) as we prefer to keep GitHub issues for bug reports and feature requests only.
