### ISSUE TITLE
NimbusJwtDecoder.withPublicKey() does not work with JWT that contains kid

### ISSUE THREAD

**Issue by firnkes** [spring-projects/spring-security#7049]
### Summary
When using NimbusJwtDecoder.withPublicKey() to decode a JWT token that contains a kid the decoding always fails as the provided PublicKey does not match.

### Actual Behavior

``` Signed JWT rejected: Another algorithm expected, or no matching key(s) found ``` is raised, because no match key is found (JWT token contains key, provided public key not).

### Expected Behavior
As I specify the public key to used, the jwt token should be tried to be verified using this key. There is no need to find a matching key.
### Version

5.2.0.M2

### Sample

```
String verificationKey = "someKey";
String token = "someTokenWithKid";

KeyFactory kf = KeyFactory.getInstance("RSA");
byte[] decoded = Base64.getDecoder().decode(verificationKey);
EncodedKeySpec keySpec = new X509EncodedKeySpec(decoded);
RSAPublicKey publicKey = (RSAPublicKey) kf.generatePublic(keySpec);
NimbusJwtDecoder decoder = NimbusJwtDecoder.withPublicKey(publicKey).build();
decoder.decode(token);

```

**Comment by jzheaux** [comment]
Thanks for the report, @firnkes, I agreed that this would be an improvement on the default Nimbus behavior.

I've submitted #7055 accordingly.
