### ISSUE TITLE
Add OAuth2LoginSpec.authenticationFailureHandler

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-security#7051]
It appears to be possible in MVC but not Webflux.

**Comment by rwinch** [comment]
Similar to [OAuth2LoginSpec.authenticationSuccessHandler](https://github.com/spring-projects/spring-security/blob/5.2.0.M3/config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java#L722-L726) we should add OAuth2LoginSpec.authenticationFailureHandler

**Comment by eddumelendez** [comment]
I will take a look into it :)
