### ISSUE TITLE
Constant time array comparison is implemented five times

### ISSUE THREAD

**Issue by larsgrefer** [spring-projects/spring-security#7058]
https://github.com/spring-projects/spring-security/blob/ce79ef263493500cf6822d8ba605bfd02fc807b2/crypto/src/main/java/org/springframework/security/crypto/password/AbstractPasswordEncoder.java#L62-L70

https://github.com/spring-projects/spring-security/blob/ce79ef263493500cf6822d8ba605bfd02fc807b2/crypto/src/main/java/org/springframework/security/crypto/password/StandardPasswordEncoder.java#L112-L120

https://github.com/spring-projects/spring-security/blob/ce79ef263493500cf6822d8ba605bfd02fc807b2/crypto/src/main/java/org/springframework/security/crypto/password/Pbkdf2PasswordEncoder.java#L151-L159

https://github.com/spring-projects/spring-security/blob/ce79ef263493500cf6822d8ba605bfd02fc807b2/crypto/src/main/java/org/springframework/security/crypto/scrypt/SCryptPasswordEncoder.java#L155-L163

https://github.com/spring-projects/spring-security/blob/ce79ef263493500cf6822d8ba605bfd02fc807b2/crypto/src/main/java/org/springframework/security/crypto/bcrypt/BCrypt.java#L918-L926

**Comment by jzheaux** [comment]
@larsgrefer, thanks for the report. It might be nice to update these to use `MessageDigest.isEqual` instead.

Would you be able interested in submitting a PR?

**Comment by larsgrefer** [comment]
I can provide a PR for this.
