### ISSUE TITLE
v5.2.0.M3 docs contain Deprecated example code

### ISSUE THREAD

**Issue by pluttrell** [spring-projects/spring-security#7062]
### Summary

The [Spring Security v5.2.0.M3 docs](https://docs.spring.io/spring-security/site/docs/5.2.0.M3/reference/htmlsingle/#webflux-oauth2-resource-server-authorization-extraction) provides the following example:
```
static class GrantedAuthoritiesExtractor extends JwtAuthenticationConverter {
    protected Collection<GrantedAuthority> extractAuthorities(Jwt jwt) {
        Collection<String> authorities = (Collection<String>)
                jwt.getClaims().get("mycustomclaim");

        return authorities.stream()
                .map(SimpleGrantedAuthority::new)
                .collect(Collectors.toList());
    }
}
```

The `Collection<GrantedAuthority> extractAuthorities(Jwt jwt)` method is now deprecated. From looking at the source, it appears there's a new recommended way to introduce our own custom authority logic.

**Comment by jzheaux** [comment]
Thanks for the report, @pluttrell! Would you be interested in submitting a PR to update the docs?

**Comment by pluttrell** [comment]
@jzheaux I was thinking about submitting one, but wasn't 100% sure what the authors intent is and didn't want to lead people in the wrong direction.

**Comment by jzheaux** [comment]
I see, @pluttrell, I can understand you wanting to first assess the author's intent. Yes, I think you've understood it correctly, and the documentation just lagged behind #6277. 

Let me know if you'd like to provide a PR, and I'd be happy to assist.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
