### ISSUE TITLE
Custom FilterInvocationSecurityMetadataSource in JavaConfig

### ISSUE THREAD

**Issue by larsgrefer** [spring-projects/spring-security#7065]
see spring-projects/spring-boot#3317
see #2672
see https://docs.spring.io/spring-security/site/docs/3.2.9.RELEASE/reference/htmlsingle/faq.html#faq-dynamic-url-metadata

Please provide an "easy" way, to provide a custom `org.springframework.security.web.access.intercept.FilterInvocationSecurityMetadataSource`
when using Java configuration.

We're currently trying to migrate an old Spring application to Spring Security 5.1.5. In this process we'd like to migrate the current xml-based configuration to a `WebSecurityConfigurerAdapter` subclass.

The urls handled by the appication represent Objects in a remote storage which has its own ACL system. Therefore we implemented our own `FilterInvocationSecurityMetadataSource` which queries the remote storage for the correct access restrictions for each object/url.

Ideally we'd like to do something like this:

```java
@Override
protected void configure(HttpSecurity http) throws Exception {
    http.authorizeRequests().securityMetadataSource(myCustomMetadataSource);
}
```

Another option I looked into is using a custom `AbstractInterceptUrlConfigurer` in order to override its `createMetadataSource()` method, but the class is package-private and its public subclasses are final.

**Comment by rwinch** [comment]
You should be able to do something like this:

```java
.authorizeRequests()
	...
	.withObjectPostProcessor(new ObjectPostProcessor<FilterSecurityInterceptor>() {
		@Override
		public FilterSecurityInterceptor postProcess(FilterSecurityInterceptor filter) {
			filter.setSecurityMetadataSource(createMetadataSource());
			return filter;
		}
	});
```

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by larsgrefer** [comment]
Using the `ObjectPostProcessor` to override the `FilterInvocationSecurityMetadataSource` works 👍
