### ISSUE TITLE
SEC-446: disabling form login with SiteMinder

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#707]
["Jeremy Wilkerson":https://jira.spring.io/secure/ViewProfile.jspa?name=jjwilker](Migrated from ["SEC-446":https://jira.spring.io/browse/SEC-446?redirect=false]) said:

The manual for Acegi, when talking about Siteminder authentication, says:

"If you additionally want to support form-based authentication (i.e. in your development environment where Siteminder is not installed), specify the form's username parameter as well - just don't do this in production!"

But actually, if the username parameter isn't specified in production, form login will still be possible because SiteminderAuthenticationProcessingFilter will use a default value.

I think it's important to be able to disable form login when an app is running in production, just to be safe. Theoretically, a user cannot even reach the app without authenticating through Siteminder first, but it is possible that Siteminder won't intercept requests because it is not configured correctly.

I implemented a solution by adding a boolean property to SiteminderAuthenticationProcessingFilter to disable form login, but of course I'm hoping others will see the value of this change and it will be incorporated into future releases.

**Comment by spring-issuemaster** [comment]
This issue is related to #917
