### ISSUE TITLE
Spring Security is not working after upgrading to spring boot 2.1.4.RELEASE

### ISSUE THREAD

**Issue by edseppp** [spring-projects/spring-security#7087]
Spring security was working fine on spring boot 2.0.8.RELEASE, after upgrading to spring boot 2.1.4.RELEASE it fails to checks for access token and displays the data without having a token. 

**Actual Behavior**
I can access any endpoints without access token. It doesn't check for token at all. 

**Expected Behavior**
To receive access denied if the token is invalid or missing when accessing any endpoint.

**Configuration**
Java version used is 1.11
and added below dependency in pom.xml

org.springframework.boot
spring-security-oauth2-autoconfigure

**Version**
its occurring in spring boot 2.1.4.RELEASE but not occurring in 2.0.8.RELEASE

**Comment by jzheaux** [comment]
@edseppp, thanks for the report. Would you do me the favor of logging this instead in [the OAuth2 Boot project](https://github.com/spring-projects/spring-security-oauth2-boot/issues)? Also, would you please post a sample program in that new ticket of what isn't working for you?
