### ISSUE TITLE
How Can I get the access_token string in OAuth2 Client

### ISSUE THREAD

**Issue by andyzhaozhao** [spring-projects/spring-security#7094]

**Comment by jzheaux** [comment]
If I understand your question correctly, this is already in the documentation: https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#oauth2Client-registered-authorized-client

Is there something missing from that explanation?

As a side note, support questions are better suited for StackOverflow. Either way, thanks for reaching ou.t
