### ISSUE TITLE
userCache Do not call custom caches

### ISSUE THREAD

**Issue by antusen** [spring-projects/spring-security#7095]
![image](https://user-images.githubusercontent.com/49021590/61032330-d0626300-a3f3-11e9-82cc-fc2f806ac5b5.png)
![image](https://user-images.githubusercontent.com/49021590/61032564-423aac80-a3f4-11e9-9a92-be5a416e9252.png)
![image](https://user-images.githubusercontent.com/49021590/61032468-17505880-a3f4-11e9-8f73-98ece98110c3.png)
![image](https://user-images.githubusercontent.com/49021590/61051817-922d6980-a41c-11e9-9a44-ec85a5e060ff.png)

**I see that there's UserDetails information in the session, and it calls the contents of the session。**
**UserDetail stored in redis does not call**
@rwinch

**Comment by rwinch** [comment]
What you are reporting is not clear to me. Please provide a detailed description of how to reproduce, what you are observing, and what you expect to happen.

**Comment by antusen** [comment]
httpSession
![image](https://user-images.githubusercontent.com/49021590/61345906-8f51cf00-a889-11e9-962b-7a0ec90596ea.png)
I failed to update the cache with userCache.
I want to modify the user details of any user. For example, I modified the role of any user, need to update the role, how to update?
@rwinch

**Comment by rwinch** [comment]
This still isn't clear to me. If you modify a user, you need to update the `UserCache`.

**Comment by antusen** [comment]
Annotations @ PreAuthorize, when using login successfully passed AbstractUserDetailsAuthenticationProvider will load to userCahce populated userDetails. After not in use AbstractUserDetailsAuthenticationProvider,

It reads UserDetails through securityconttimpl. So you can update Cahce with userCahe, but still @preauthorize the UserDetails at login, not the modified UserDetails

**Comment by rwinch** [comment]
Please provide a sample with directions on how to reproduce the problem, what you expect to happen, and what is actually happening.

**Comment by antusen** [comment]
Thank you very much, I no longer use UserCache. Currently in use spring-session.
