### ISSUE TITLE
SEC-449: Refactor LDAP provider to make use of Spring LDAP

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#710]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-449":https://jira.spring.io/browse/SEC-449?redirect=false]) said:

As the LDAP functionality provided by Acegi expands, it makes sense make use of Spring LDAP and try to be compatible whenever possible.

**Comment by spring-issuemaster** [comment]
This issue depends on #819
This issue depends on #868
