### ISSUE TITLE
JwtGrantedAuthoritiesConverter should allow configuring the authorities claim name

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#7100]
Related to #6945

It would be nice if an application could indicate a custom claim name for `GrantedAuthority`s without creating a custom converter.

Something like:

```java
JwtGrantedAuthoritiesConverter converter = new JwtGrantedAuthoritiesConverter();
converter.setAuthoritiesClaimName("authorities");
```

Would be easier to do than:

```java
Converter<Jwt, List<GrantedAuthorities>> converter = jwt -> {
    List<String> authorities = (List<String>) jwt.getClaim("authorities");
    return authorities.stream()
        .map(authority -> "SCOPE_" + authority)
        .map(SimpleGrantedAuthority::new)
        .collect(Collectors.toList());
};
```

So, let's add a setter to `JwtGrantedAuthoritiesConverter` called `setAuthoritiesClaimName` so that the converter knows which claim to look for.

**Comment by andifalk** [comment]
Hi @jzheaux 
has anybody already claimed this first timers issue?
Would make sense to implement this one together with https://github.com/spring-projects/spring-security/issues/7101. If this is ok for you I would be glad to take over implementation for both.

**Comment by jzheaux** [comment]
@andifalk, it's yours!
