### ISSUE TITLE
Improve OAuth2 Resource Server tests

### ISSUE THREAD

**Issue by henriquels25** [spring-projects/spring-security#7118]
### Summary

The tests for the OAuth2 Resource Server [sample](https://github.com/spring-projects/spring-security/blob/master/samples/boot/oauth2resourceserver/src/test/java/sample/OAuth2ResourceServerControllerTests.java) only include GET requests.

I believe it would be useful to add examples for other HTTP methods (POST, PUT, PATCH, DELETE) because the code for testing them is different. 

### Sample

In this [project](https://github.com/henriquels25/spring-security/blob/integration_tests_post_resource_server/samples/boot/oauth2resourceserver/src/test/java/sample/OAuth2ResourceServerControllerTests.java) it's possible to see that if the same technique used for testing the GET requests is used for a POST, the test fails without sending the CSRF token in the request.

In this [example](https://github.com/henriquels25/spring-security/blob/post_requests_example/samples/boot/oauth2resourceserver/src/test/java/sample/OAuth2ResourceServerControllerTests.java), I created a working POST request test example based on the sample, based on the explanation contained on [this](https://stackoverflow.com/questions/57103518/spring-security-oauth2-resource-server-tests) StackOverflow question.

**Comment by jzheaux** [comment]
@henriquels25 I agree that additional tests would be helpful; would you be interested in submitting a PR?

**Comment by henriquels25** [comment]
@jzheaux I submitted a PR with examples for a POST request. I didn't create examples for the other HTTP methods to keep the sample small, as the code for testing them is not different.
