### ISSUE TITLE
Oauth2RestTemplate problem with obtaining access token with usage of refresh token

### ISSUE THREAD

**Issue by Dzionek95** [spring-projects/spring-security#7124]
Hello,

During my implementation of client microservice for oAuth2 I faced problem related with using OAuth2RestTemplate. My scenario is that this microservice is consumer and there is no rest endpoints. I have technical hardcoded user in properties which is able to get access token (with refresh token) with grant_type password. Logic that is responsible for obtaining access token with usage of refresh token is inside `AccessTokenProviderChain` in method posted below:
`	public OAuth2AccessToken obtainAccessToken(OAuth2ProtectedResourceDetails resource,
			AccessTokenRequest request)
			throws UserRedirectRequiredException, AccessDeniedException {

		OAuth2AccessToken accessToken = null;
		OAuth2AccessToken existingToken = null;
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();

		if (auth instanceof AnonymousAuthenticationToken) {
			if (!resource.isClientOnly()) {
				throw new InsufficientAuthenticationException(
						"Authentication is required to obtain an access token (anonymous not allowed)");
			}
		}

		if (resource.isClientOnly() || (auth != null && auth.isAuthenticated())) {
			existingToken = request.getExistingToken();
			if (existingToken == null && clientTokenServices != null) {
				existingToken = clientTokenServices.getAccessToken(resource, auth);
			}

			if (existingToken != null) {
				if (existingToken.isExpired()) {
					if (clientTokenServices != null) {
						clientTokenServices.removeAccessToken(resource, auth);
					}
					OAuth2RefreshToken refreshToken = existingToken.getRefreshToken();
					if (refreshToken != null && !resource.isClientOnly()) {
						accessToken = refreshAccessToken(resource, refreshToken, request);
					}
				}
				else {
					accessToken = existingToken;
				}
			}
		}
		// Give unauthenticated users a chance to get a token and be redirected

		if (accessToken == null) {
			// looks like we need to try to obtain a new token.
			accessToken = obtainNewAccessTokenInternal(resource, request);

			if (accessToken == null) {
				throw new IllegalStateException(
						"An OAuth 2 access token must be obtained or an exception thrown.");
			}
		}

		if (clientTokenServices != null
				&& (resource.isClientOnly() || auth != null && auth.isAuthenticated())) {
			clientTokenServices.saveAccessToken(resource, auth, accessToken);
		}

		return accessToken;
	}`

as you can see refresh token logic is triggered only if `OAuth2ProtectedResourceDetails.isClientOnly()` is returning false and when `SecurityContextHolder.getContext().getAuthentication()` is returning `Authentication` object. In my scenario this method is returning null so I'm not able to use refresh token logic. So I came up with idea to create it by hand and inject it to `SecurityContextHolder`. However this solution is very dirty in my opinion. Anyone have faced such issue? Maybe do you have some solution for that or maybe there is another way to use Oauth2RestTemplate and I'm not aware of?

I'm using spring-security-oauth2 v2.3.6.RELEASE

**Comment by jzheaux** [comment]
@Dzionek95, thanks for reaching out. 

This sounds like something that would be better as [a question on StackOverflow](https://stackoverflow.com/questions/ask). If you think this is a genuine bug in the codebase, please log an issue to https://github.com/spring-projects/spring-security-oauth with what you'd like to see fixed.
