### ISSUE TITLE
AuthenticationWebFilter allow subclasses override for special requirements

### ISSUE THREAD

**Issue by loyayz** [spring-projects/spring-security#7129]
AuthenticationWebFilter should allow subclasses override for special requirements.

**Comment by rwinch** [comment]
Please provide more details on what you are trying to do but unable to do.

**Comment by rwinch** [comment]
Given you also sent gh-7130 I'm guessing you want flexibility in how to match on the exchange. This is already possible by injecting a custom `requiresAuthenticationMatcher` so there is no need to provide a protected method
