### ISSUE TITLE
Upgrade org.aspectj jrt|tools|weaver to 1.9.4

### ISSUE THREAD

**Issue by fhanik** [spring-projects/spring-security#7139]
Component: `org.aspectj.aspectjrt'
Current version: 1.9.3
Next available version: 1.9.4

Component: `org.aspectj.aspecttools'
Current version: 1.9.3
Next available version: 1.9.4

Component: `org.aspectj.aspectweaver'
Current version: 1.9.3
Next available version: 1.9.4

**Comment by jzheaux** [comment]
We may need to hold off on this dependency upgrade since 1.9.4 causes a problem on the JDK9 build.
