### ISSUE TITLE
Spring security 4.2.12 can't add security headers when using zuul and tomcat from spring boot 1.5.21

### ISSUE THREAD

**Issue by mmerrill3** [spring-projects/spring-security#7146]
### Summary

The default spring security headers are not added to responses since zuul (spring-cloud-zuul 1.4.7) writes the response from the downstream into the HttpServletResponse.  Tomcat checks if the response is committed (which it is), so it will not add the headers to the response.  This is in catalina's Reponse object's addHeader method.

### Actual Behavior

The filter HeaderWriterFilter performs the servlet filter chain before applying the headers with the delegate class HeaderWriterResponse, via the writeHeaders() method.  This method is invoked, but after the response is committed already by Zuul's SendResponseFilter.  So, when the method writeHeaders() is actually invoked, it's a no-op since the response is already written to the output stream.

### Expected Behavior

The default security headers should be added to the spring boot responses.

### Version

spring boot 1.5.21
spring security 4.2.12
spring netflix 1.4.7
### Sample

Registering this kind of bean as a zuul post processing filter to run before SendResponseFilter will add the headers:

```
package org.springframework.security.web.header;

import com.netflix.zuul.ZuulFilter;
import com.netflix.zuul.context.RequestContext;
import com.netflix.zuul.exception.ZuulException;
import com.netflix.zuul.http.HttpServletResponseWrapper;

import static org.springframework.cloud.netflix.zuul.filters.support.FilterConstants.POST_TYPE;

import javax.servlet.ServletResponse;
import javax.servlet.http.HttpServletResponse;

import org.springframework.stereotype.Component;
import org.springframework.util.ReflectionUtils;

@Component
public class ZuulAddSecurityHeadersBeforeCommitFilter extends ZuulFilter {
	
	//unfortunately, this is needed since spring security now runs adding security filters after the filter chain is done.
	//zuul writes the response, so you can't add headers after the response is written.
	//This filter will add the security headers if they are enabled from spring security, before the response is written
	
	protected static final String ZUUL_ADD_SECURITY_BEFORE_COMMIT_RAN = "ZuulAddSecurityHeadersBeforeCommitFilter.ran";


	@Override
	public boolean shouldFilter() {
		RequestContext ctx = RequestContext.getCurrentContext();
		return !ctx.getBoolean(ZUUL_ADD_SECURITY_BEFORE_COMMIT_RAN, false);
	}

	@Override
	public Object run() throws ZuulException {
		try {
			HttpServletResponse responseWrapper = RequestContext.getCurrentContext().getResponse();
			if(responseWrapper instanceof HttpServletResponseWrapper) {
				HttpServletResponseWrapper zuulWrapper = (HttpServletResponseWrapper) responseWrapper;
				ServletResponse response = zuulWrapper.getResponse();
				if(response instanceof HeaderWriterFilter.HeaderWriterResponse) {
					HeaderWriterFilter.HeaderWriterResponse wrapper = (HeaderWriterFilter.HeaderWriterResponse) response;
					wrapper.writeHeaders();
				}
			}
			
		} catch (Exception ex) {
			ReflectionUtils.rethrowRuntimeException(ex);
		} finally {
			RequestContext.getCurrentContext().set(ZUUL_ADD_SECURITY_BEFORE_COMMIT_RAN);
		}
		return null;
	}

	@Override
	public String filterType() {
		return POST_TYPE;
	}

	@Override
	public int filterOrder() {
		return 0;
	}

}
```

**Comment by rwinch** [comment]
I'm not sure what you expect Spring Security to do. If the response is committed, Spring Security cannot add the headers (it will get an Exception). Can you provide a minimal project that demonstrates the issue?

**Comment by mmerrill3** [comment]
@rwinch I hear you in that spring-security is behaving as expected given the current implementation.  This came about b/c of an upgrade to spring-boot.  We went from an older version to 1.5.21, and that manifested itself b/c the old behavior of HeaderWriterFilter was to write the security headers first, and then call the filter chain.  Now, with the most up to date spring-security, the security headers don't get added until after calling the filter chain.  The filter chain commits the response message (zuul in this case, but it could be anything else really), so the headers will not get added.  My issue is that the old spring-security implementation added the filters, and the new spring-security does not, due to the ordering of operations. 

Maybe a way to address this is to allow for the old behavior to take place with HeaderWriterFilter through configuration?  Always write the security headers before invoking the filter chain, if so desired?  

At the very least, this can serve as an example for other developers to use on how to add the security headers when another filter in the filter chain (especially zuul) commits the response message.

**Comment by rwinch** [comment]
@mmerrill3 Thanks for the feedback. I think it makes sense to add an eager flag to the `HeaderWriterFilter`. Would you be interested in submitting a PR?

**Comment by mmerrill3** [comment]
@rwinch I can set up a PR soon on this.

**Comment by mmerrill3** [comment]
@rwinch good news, the current head of master has this commit which takes care of the issue I was having:
https://github.com/spring-projects/spring-security/commit/ac13b55ecd93b9eaf40866aabb043b14dd4f3350#diff-57c0f670220b7f4e45a0d1252a99b482
I will close this as this commit does exactly what I need, which is be able to configure the order of operations.
