### ISSUE TITLE
Add RequestMatcher.matcher(HttpServletRequest)

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#7148]
### Summary

Anyone wanting to take this on can request to take the whole thing on or just one step (but it must be the first step that has not been completed).

#### Step 1

We should add a default method to `RequestMatcher` that looks like this:

```java
default MatchResult matcher(HttpServletRequest request) {
	boolean match = matches(request);
    return new MatchResult(match);
}

```

The `MatchResult` should look similar to `ServerWebExchangeMatcher.MatchResult` except it uses servlet request and non-reactive types.

#### Step 2

Then implementations of `RequestVariablesExtractor` should be updated to implement the `matcher` method and `RequestVariablesExtractor` should be deprecated. 

#### Step 3

Usage of `RequestVariablesExtractor` or types that are assigned to `AntPathRequestMatcher` should be replaced with the new method.

**Comment by bou1der** [comment]
I would like to work on this if its available.

**Comment by eddumelendez** [comment]
@bou1der I already have the step1. would you like to work with me on this?

**Comment by eddumelendez** [comment]
@bou1der [this](https://github.com/eddumelendez/spring-security/tree/gh-7148) is the branch I am using.

**Comment by bou1der** [comment]
@eddumelendez yeah and thanks! I will take a look at the branch later today. If you have a good handle on it, don't let me slow you down. I can help out as much or little as needed.
