### ISSUE TITLE
Remove internal Optional usage in favor of null checks

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#7155]
### Summary

While some prefer the readability of using the Optional API, the GC overhead of creating additional objects (including intermediate objects) can cause significant decrease in performance There are some simple [benchmarks](https://gist.github.com/mp911de/7f203d787c6fdaf97dc91e6dc3aa73d3) that illustrate the problem.

We should replace Stream usage with for loops throughout Spring Security's code base.

Related gh-7154

**Comment by eddumelendez** [comment]
Hi @rwinch, do you think this is good for `first-timers-only`?

**Comment by rwinch** [comment]
Thanks for asking @eddumelendez I think it is likely a lot of code to touch for a first timers.
