### ISSUE TITLE
Default Login Page Bootstrap CSS on Closed Network

### ISSUE THREAD

**Issue by lafual** [spring-projects/spring-security#7165]
Hi,

We are using WebFlux with Spring's default login pages. However the CSSs that are used are on the internet and we are on a  network with no internet access.

Our project has the relevant Bootstrap CSS files embedded. How can I cause the default login mechanism to use these files?

(I know that I can implement my own Thymeleaf version to get around this. I just don't want to go through the hassle of rebuilding .m2 from a POM on an internet PC and having the .m2 checked by our security team before importing into our closed network).

**Comment by rwinch** [comment]
There isn't intended to be a way to customize this behavior. The default log in page is meant to be a reasonable default. If you want to customize the page, then you can do so by creating your own log in page (i.e. using thymeleaf as you suggested).

**Comment by lafual** [comment]
Thanks for taking the time to respond. I will proceed with Thymeleaf.
