### ISSUE TITLE
SessionAuthenticationStrategy make HttpSecurity.sessionManagement().maximumSessions(1) unavailability

### ISSUE THREAD

**Issue by HomminLee** [spring-projects/spring-security#7166]
I am not good at English. So, please forgive my grammatical mistakes.

I have a problem while config `HttpSecurity.sessionManagement().maximumSessions(1)`. I hope a user only have one valid session at the same time.

 If I login at browser A，and then login at browser B. It's run perfect and session in browser A will invalid.

But if I login at browser A,  then login at browser A(
In other words, I'm called the `/login` interface twice in the same browser.), then login at browser B. I found both browsers can access the restricted interfaces.

---

I viewed source code, found there have three `SessionAuthenticationStrategy`: `ConcurrentSessionControlAuthenticationStrategy`, `ChangeSessionIdAuthenticationStrategy`, `RegisterSessionAuthenticationStrategy`. I tried to debug with source code and the following happened:

While the second time login at browser A, `ConcurrentSessionControlAuthenticationStrategy` find the same sessionId, so it do noting. But `ChangeSessionIdAuthenticationStrategy` change sessionId into a new sessionId, and `RegisterSessionAuthenticationStrategy` think it's a new session and store. so there is two session in session registry.

Did I miss some configuration to resolve this problem?

My spring security version is 5.1.5.RELEASE. Think you very much!

**Comment by rwinch** [comment]
> But if I login at A browser, then login at A browser, then login at B browser. I found two session is both valid.

Can you explain by what you mean by this? How do you login A browser and login A browser again?

**Comment by HomminLee** [comment]
Thank you for taking the time to look at my issue.I tried to complete my question.

**Comment by rwinch** [comment]
Thank you. Can you please provide a minimal sample to reproduce the issue?

**Comment by HomminLee** [comment]
I created a simple project to verification my problem, and get the same happening. It only included a security configuration and a rest controller. I upload my code at [https://github.com/HomminLee/security-session-demo](https://github.com/HomminLee/security-session-demo). Also, I write down the steps in README.md.

**Comment by eleftherias** [comment]
Thank you for the sample and detailed explanation.
We are working on a fix for this, but in the meantime there are 2 options you can use to prevent this problem from happening.

Option 1
You can prevent any additional users from logging in when the maximum number of sessions has been reached, by using `maxSessionsPreventsLogin(true)`.
You configuration would look like this.
```
http
    .sessionManagement()
        .maximumSessions(1)
            .maxSessionsPreventsLogin(true);
```

Option 2
You can change your session fixation strategy to `newSession()` or `migrateSession()`. This will expire the existing session when a new session is created in the same browser.
Your configuration would look like this.
```
http
    .sessionManagement()
        .maximumSessions(1)
            .and()
        .sessionFixation()
            .newSession();
```
If you are using `newSession()` or `migrateSession()`, you will also need a `HttpSessionEventPublisher` bean.
```
@Bean
public HttpSessionEventPublisher httpSessionEventPublisher() {
    return new HttpSessionEventPublisher();
}
```
