### ISSUE TITLE
SEC-461: HttpSessionContextIntegrationFilter with cloneFromHttpSession = true causes problems at login

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#722]
["Scott Rankin":https://jira.spring.io/secure/ViewProfile.jspa?name=srankin](Migrated from ["SEC-461":https://jira.spring.io/browse/SEC-461?redirect=false]) said:

The cloneFromHttpSession feature of the HttpSessionContextIntegrationFilter is fantastic - just what I needed, but it has a bug. 

On line 172, it checks to see if the clone feature is turned on and then asserts that the context from the session is an instance of Cloneable.  However, the context from the session might be null at this point.  The check for cloneFromHttpSession should be moved inside the next if() statement so that it only checks when the context in the session is non-null.

**Comment by spring-issuemaster** [comment]
This issue duplicates #684
