### ISSUE TITLE
ServerHttpSecurity: oauth2Login() ignores securityContextRepository()

### ISSUE THREAD

**Issue by ilgrosso** [spring-projects/spring-security#7222]
In org.springframework.security.config.web.server.ServerHttpSecurity.OAuth2LoginSpec#configure, the line

https://github.com/spring-projects/spring-security/blob/2055466ad76696ebfb62b091de6a5fd8a81b382d/config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java#L1141

does not take into account `ServerHttpSecurity.this.securityContextRepository` (which has the same default value, but can be customized by invoking `securityContextRepository()`) and blindly creates a new instance of `WebSessionServerSecurityContextRepository`.

**Comment by jzheaux** [comment]
The JavaDoc for `ServerHttpSecurity#securityContextRepository` states:

> It does not impact how the {@code SecurityContext} is saved which is configured on a per {@link AuthenticationWebFilter} basis

The way that `HttpBasicSpec` and `FormLoginSpec` are configured is as follows:

```java
http
    .httpBasic()
        .securityContextRepository(...)
```

and

```java
http
    .formLogin()
        .securityContextRepository(...)
```

Given the JavaDoc and the way that other authentication mechanisms work, it would seem to be preferable instead to add a `securityContextRepository` method to the `oauth2Login` DSL:

```java
http
    .oauth2Login()
        .securityContextRepository(...)
```

Would you be willing to provide a PR along those lines instead? It would be one that introduces `securityContextRepository(...)` to `OAuth2LoginSpec`.

**Comment by ilgrosso** [comment]
@jzheaux thanks for review; here's the new PR: #7244
