### ISSUE TITLE
TokenBasedRememberMeServices.processAutoLoginCookie (TokenBasedRememberMeServices.java:134) java.lang.NullPointerException

### ISSUE THREAD

**Issue by codeconsole** [spring-projects/spring-security#7251]
TokenBasedRememberMeServices assumes user exists when it could not for various reasons:

1. The user could have been deleted (Most likely)
2. The cookie could be invalid

https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/authentication/rememberme/TokenBasedRememberMeServices.java#L123-L124

There is no check and such an exception is not handled gracefully. 
At the very least, it should throw a InvalidCookieException

**Comment by eleftherias** [comment]
Closed via commit https://github.com/spring-projects/spring-security/commit/26ae590c688248b6f5fbc26704659ce68df48b4f
