### ISSUE TITLE
Ensure filter order is maintained when using springSecurity() along with other filters

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-security#7265]
```
MockMvcBuilders.webAppContextSetup(this.context).apply(springSecurity())
	.addFilter(filter).build();
```

For the above setup, when using `springSecurity()` with other filters, the spring security filter always gets applied after the other filters. The workaround for now is to add the filter manually as follows:

```
MockMvcBuilders.webAppContextSetup(this.context).apply(springSecurity())
	.addFilters(springSecurityFilterChain, filter).build();
```

**Comment by rwinch** [comment]
Thanks for the report @mbhave! This is now merged into master and back ported to 5.1.x
