### ISSUE TITLE
Support configuring oauth2 resource server properties issuer-uri and jwk-set-uri at the same time

### ISSUE THREAD

**Issue by lpetit-yseop** [spring-projects/spring-security#7274]
### Summary
This ticket is about extending the configuration of oauth2 resource server to support, out-of-the-box, that both `issuer-uri` and `jwk-set-uri` be set, in a backwards compatible way.
The general idea is that `jwk-set-uri` would be used to obtain JWK sets, while `issuer-uri` would be used to provider issuer validation support by default.

### Actual Behavior
Currently, one must choose between using `issuer-uri` configuration or `jwk-set-uri`.
By using `jwk-set-uri`, we drop the possibility to have out-of-the-box validation of the `iss` issuer claim when validating incoming access tokens.

### Expected Behavior
The expected behavior is to not have `issuer-uri` and `jwk-set-uri` configurations be mutually exclusive.
The current behavior could be preserved, with the added behavior if both are set:
- The `jwk-set-uri` is used to retrieve the JWK Set URL
- The `iss` issuer claim of access tokens is validated using the value set in `issuer-uri`.

### Configuration
Issue not tied to a specific configuration.

### Version
The current actual behavior that is describes corresponds to both the `2.1.x` and the `2.2.x` lines of development.

### Sample
With the given configuration properties:
```properties
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://idp.example.com
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://idp.example.com/oauth2/default/v1/keys
```
Then Spring Boot would use `https://idp.example.com/oauth2/default/v1/keys` for fetching the JWK sets, and would validate that every incoming access token `iss` issuer claim equals `https://idp.example.com`.

**Comment by jzheaux** [comment]
@lpetit-yseop Thanks for the report.

Could you clarify why setting the `issuer-uri` is insufficient? Does your Authorization Server not support the OIDC discovery or OAuth2 metadata endpoints?

**Comment by lpetit-yseop** [comment]
> @lpetit-yseop Thanks for the report.
> 
> Could you clarify why setting the `issuer-uri` is insufficient? Does your Authorization Server not support the OIDC discovery or OAuth2 metadata endpoints?

Sure, but first of all, I think that as long as there is support for `jwk-set-uri`, my point remains valid: why make this mode less secure?

My issue is that I work on a product that will be run on-premises, and I want to provide support for both modes: with `issuer-uri` and with `jwk-set-uri`. And I'm not happy to document that the user will not have the JWT `iss` checked if they use the `jwk-set-uri`. I am aware that I could add the relevant check by adding code to my application. Just pondering with you if it wouldn't best be done in the spring security framework.

Even if one has an authorization server that supports `issuer-uri`, there is currently an important drawback to this: the startup of the application might fail if the authorization server, for any reason, cannot be reached.

This has already caused me problems on my local machine, when I startup a whole stack via Docker Compose: my application is faster to start than my Keycloak authorization server, and so, even tho the dependencies are correctly set, since Docker does not wait for successful health check to start dependencies, my application does not start.

I also see this could be a problem when whole environments are started via e.g. Terraform: let's hope the authorization server is ready to serve its OpenId Discovery endpoint before any other microservice that will start concurrently, …

I don't know if I'm over reacting here. I guess it might depend on whether the fix for this situation is easy or complex to achieve.

**Comment by jzheaux** [comment]
>  why make this mode less secure?

Good point, `issuer-uri` property could be interpreted in both ways separately: 1. lookup the jwk set uri and 2. perform issuer validation. In circumstances where the jwk set uri is already known, then the lookup can be skipped.

Along those lines, though, have you already tried the following?

```java
@Autowired
void addValidator(JwtDecoder jwtDecoder) {
    OAuth2TokenValidator<Jwt> validator = JwtValidators.createDefaultFromIssuer(issuerUri);
    ((NimbusJwtDecoder) jwtDecoder).setJwtValidator(validator);
}
```

> maybe the problem lies in spring boot not being resilient to the temporary unavailability of the discovery endpoint, but that is a problem for a separate issue, I guess.

Yes, I agree that there may be an improvement that can be done along these lines, though it's a tricky balance. On the other side of this coin, it's nice to get immediately alerted to configuration mistakes. 

Because of the customization that building a more resilient call would likely entail - resulting in a more complex API - I believe your first proposal is more palatable.

**Comment by jzheaux** [comment]
@lpetit-yseop Since this is a Spring Boot feature at this point, I've created another ticket https://github.com/spring-projects/spring-boot/issues/17920 and we can have any further conversations over there.
