### ISSUE TITLE
client_credentials grant type is allowed with client without a secret

### ISSUE THREAD

**Issue by watsta** [spring-projects/spring-security#7289]
### Summary
As the title says, it's possible to retreive an access token with the `client_credentials` grant type (with form authentication enabled in `AuthorizationServerSecurityConfigurer`) when the client does not have a client secret. This might cause the misuse of this grant type or might open up security vulnerabilities.

### Actual Behavior
client_credentials grant type can be used with client without a client secret:
```
curl -X POST \
  http://localhost:8080/oauth/token \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id=clientId&grant_type=client_credentials'
```
```
{
    "access_token": "a1e1b1e9-3526-4a67-8ec6-3c7168cc378e",
    "token_type": "bearer",
    "expires_in": 99,
    "scope": "profile"
}
```
### Expected Behavior
Either a runtime exception when trying to retreive a token with the `client_credentials` grant when the client doesn't have a secret or simply handle the request as if it was invalid.

### Configuration
```java
@Configuration
@EnableAuthorizationServer
public class AuthServerConfig extends AuthorizationServerConfigurerAdapter {
    @Autowired
    private TokenStore tokenStore;

    @Override
    public void configure(AuthorizationServerSecurityConfigurer security) {
        security.allowFormAuthenticationForClients();
    }

    @Override
    public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
        endpoints.tokenStore(tokenStore);
    }

    @Override
    public void configure(ClientDetailsServiceConfigurer clients) throws Exception {
        clients.inMemory()
                .withClient("clientId")
                .authorizedGrantTypes("client_credentials")
                .scopes("profile")
                .accessTokenValiditySeconds(100);
    }
}
```

### Version
`2.3.6.RELEASE`

**Comment by jgrandja** [comment]
@watsta In your `AuthServerConfig`, you have not configured a `client_secret` for the client via `clients.inMemory()...`. This is obviously not recommended as the maintainer of the Authorization Server application should never configure a client or user with empty secret. As far as I see it, the vulnerability is exposed from the application misconfiguration.

Even if the Authorization Server application exposed a Client Registration page, it would be responsible for validating the user input to ensure it complies with the data constraints for the client to be registered.

Also as an FYI, this issue should be logged with the Spring Security OAuth [issues](https://github.com/spring-projects/spring-security-oauth/issues).

I'm going to close this but if you still see issues with this please log a ticket there and we can discuss further.

**Comment by watsta** [comment]
Hi @jgrandja , thanks for your reply!
I agree that this is a vulnerability exposed from misconfiguration, though I was on the standpoint that we could mitigate this risk in spring-security. But I also understand you and agree that this is the responsibility of the developer of the authorization server, so I'm not going to open a ticket, I just wasn't sure if you were aware of this.
Sorry for logging this at the wrong project!
