### ISSUE TITLE
NimbusJwtDecoderJwkSupport only sets 'application/json' Accept header

### ISSUE THREAD

**Issue by BoukeNijhuis** [spring-projects/spring-security#7290]
### Summary

The NimbusJwtDecoderJwkSupport is not able to retrieve the JWK Set because it gets a HTTP 406 (Not Accepted). It tries to retrieve it from an endpoint that only produces the media-type application/jwk-set+json. This media-type is the proper media-type for this kind of endpoint as specified in https://tools.ietf.org/html/rfc7517. This new behaviour is introduced around the release of version 5.1.

### Actual Behavior

The NimbusJwtDecoderJwkSupport gets a HTTP 406 when trying to retrieve a JWK Set from an endpoint that only produces the media-type application/jwk-set+json.

### Expected Behavior

The NimbusJwtDecoderJwkSupport gets a HTTP 200 when trying to retrieve a JWK Set from an endpoint that only produces the media-type 'application/jwk-set+json'. 

### Configuration

The endpoint produces only the media-type application/jwk-set+json. This looks like this in the code: 
`@GetMapping(value = "/jwk", produces = com.nimbusds.jose.jwk.JWKSet.MIME_TYPE)`

### Version

It seems the change in behaviour is introduced here:

https://github.com/spring-projects/spring-security/commit/16fe1c5b52633399ff51ed022d23024ab65d0a70 (line 183)

In this commit the RestOperationsResourceRetriever is introduced in the NimbusJwtDecoderJwkSupport class. Before this commit a DefaultResourceRetriever was used. The latter uses an HttpURLConnection to retrieve the JWK Set (WITHOUT an Accept request header). The former uses a RestOperations (WITH an Accept request header with the value 'application/json;charset=UTF-8').

### Sample

I tried to find a public endpoint that only produces the media-type application/jwk-set+json. I was not able able to find one and therefore I cannot provide a working sample to demonstrate this problem.

### Proposed solution

Add the media-type 'application/jwk-set+json' to the Accept request header in the RestOperationsResourceRetriever.

**Comment by jzheaux** [comment]
Note that `NimbusJwtDecoder` in 5.2 likely exhibits the same behavior.

**Comment by jgrandja** [comment]
@BoukeNijhuis Thank you for the report!

I agree with your proposed solution...

> Add the media-type `application/jwk-set+json` to the Accept request header in the `RestOperationsResourceRetriever`.

Would you be interested in submitting a PR?

**Comment by BoukeNijhuis** [comment]
I am interested in submitting a PR. I will try this today.
