### ISSUE TITLE
SessionManagementFilter invalidSessionStrategy always trigger at the first visit

### ISSUE THREAD

**Issue by RobertoHuang** [spring-projects/spring-security#7296]
Hi，When I configure the session config, the first time the permitAll request is accessed after the project starts, the invalidSessionStrategy is always fired, even if the request is permitAll. Session configuration is as follows
![image](https://user-images.githubusercontent.com/20842825/63519893-4fd06f80-c526-11e9-8715-0a025e4fa048.png)

How can I solve this problem?

**Comment by okohub** [comment]
@RobertoHuang 

In SessionManagementFilter, invalidSessionStrategy is called if there are ***no security context or authentication***, plus (+)
```
request.getRequestedSessionId() != null && !request.isRequestedSessionIdValid()
```
We can think that, you are sending sessionIds which are not active, not representing or belonging to an existing session. There are two quick solutions for your problem;
1. Check your cookies and headers, do not send this.
2. If you are not aware of authentication, move your permitAll mappings to WebSecurity ignoring matchers. Spring Security will not hit these paths. Like that;
```
web.ignoring().antMatchers("/foo/**");
```
But, I also wonder why SessionManagementFilter is not aware of authorized or unauthorized mappings. I don't know why, let's ask it to @rwinch :)

**Comment by rwinch** [comment]
Sessions don't just store authentication for use with authorization. They also store things like CSRF tokens so it doesn't really matter if the value is permitAll. Even if that were not the case, we do not want to couple something session management to authorization.
