### ISSUE TITLE
How to prevent exceptions from multiple queries to API in Spring Security OAuth2

### ISSUE THREAD

**Issue by Freeongoo** [spring-projects/spring-security#7313]
I am developing a REST application.
Spring security out of the box oauth2 authorization is used.

But there are problems when the current authorization cookie has expired or deleted and many requests to various api are executed in parallel.
For example:

	/api/books
	/api/categories
	/api/authors

After these three requests were sent asynchronously, these requests are redirected to authorization.

As a result, I get this picture:
	
	/api/books
	/api/categories
	/api/authors
	http://127.0.0.1:8081/login
	http://127.0.0.1:8081/login
	http://127.0.0.1:8081/login
	http://127.0.0.1:8081/oauth/authorize?client_id=client&redirect_uri=http://127.0.0.1:8081/login&response_type=code&state=9PO7rO
	http://127.0.0.1:8081/oauth/authorize?client_id=client&redirect_uri=http://127.0.0.1:8081/login&response_type=code&state=d2O7j1
	http://127.0.0.1:8081/oauth/authorize?client_id=client&redirect_uri=http://127.0.0.1:8081/login&response_type=code&state=9541sf
	http://127.0.0.1:8081/login?code=w7lmSA&state=9PO7rO (one of these queries returns status 401)
	http://127.0.0.1:8081/login?code=gf41sd&state=d2O7j1 (one of these queries returns status 401)
	http://127.0.0.1:8081/login?code=kj74sx&state=9541sf (one of these queries returns status 401)

And it turns out that always one of the last three queries contains an error with status 401 (message: "Authentication Failed: Could not obtain access token")

And I do not understand why this error occurs.

Can you clarify what needs to be done in this situation? Can spring itself solve this problem? It may be necessary to somehow configure additionally.

**Comment by jgrandja** [comment]
@Freeongoo Can you please provide more information. Which version are you using? What would be most helpful is if you could provide a [complete and minimal sample](https://stackoverflow.com/help/mcve) that reproduces the issue and share it via a GitHub repository. This will allow us to efficiently troubleshoot and help resolve the issue. The sample should contain the minimum amount of code to reproduce the issue along with detailed steps on how to reproduce.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
