### ISSUE TITLE
It seems that the password credentials constant is missing.

### ISSUE THREAD

**Issue by ziponia** [spring-projects/spring-security#7336]
https://github.com/spring-projects/spring-security/blob/master/oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2/core/AuthorizationGrantType.java

I think that password credentials should be provided as a constant for external use.

Also, the refresh token entry is missing from the description. (Line 29)

**Comment by jgrandja** [comment]
@ziponia Support for the `password` grant will soon be merged via #7013, which adds `AuthorizationGrantType.PASSWORD`.
