### ISSUE TITLE
SEC-473: Make TokenBasedRememberMeServices extensible

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#734]
["Aleksei Valikov":https://jira.spring.io/secure/ViewProfile.jspa?name=lexicore](Migrated from ["SEC-473":https://jira.spring.io/browse/SEC-473?redirect=false]) said:

Currently it's hard to extend TokenBasedRememberMeServices due to its private-style access to fields.

Could you please do the following:
1. Add getter for authenticationDetailsSource.
2. Use gettes instead of direct field access.
3. Refactor cookie processing in autoLogin into a separate protected method like processCookie(request, response, cookieValue)
4. Make cancelCookie method at least protected.

**Comment by spring-issuemaster** [comment]
This issue is related to #849
This issue is related to #826
