### ISSUE TITLE
Cannot deserialize session attribute [SPRING_SECURITY_CONTEXT] for session [404630F8152816150D9DE5CF83E4B7A1] Exception loading sessions from persistent storage

### ISSUE THREAD

**Issue by phearun008** [spring-projects/spring-security#7409]

**Comment by jzheaux** [comment]
Sorry to hear you are having trouble, @phearun008. Will you please provide a minimal sample via GitHub that reproduces the bug you are reporting?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
