### ISSUE TITLE
Update the default strength for password encoders

### ISSUE THREAD

**Issue by larsgrefer** [spring-projects/spring-security#7411]
I propose to increase the default strength for some password encoders.

The BCrypt encoder currently uses `10` as default strength, with which it only takes ~80ms to encode a password (on my Early 2015 MacBook Pro). I think the default should be increased to (at least) 12.

The Argon2 encoder only needs ~40ms, so its defaults should be increased too.

The SCrypt encoder needs ~80ms with its default parameters.

**Comment by larsgrefer** [comment]
The Spring Security Reference Documentation says:
> It is recommended that the "work factor" be tuned to take about 1 second to verify a password on your system.

**Comment by jzheaux** [comment]
Thanks, @larsgrefer for checking on this.

@rwinch do we have a hardware profile that we target when determining when to increase this? My concern would be if we bump the number up to early, lots of folks suddenly see password hashing taking quite a bit longer than 1 second.

**Comment by larsgrefer** [comment]
MacBook Pro (2021, M1 Pro):

```
BCryptPasswordEncoder : 73ms
SCryptPasswordEncoder : 28ms
Argon2PasswordEncoder : 6ms
Pbkdf2PasswordEncoder : 295ms
```
