### ISSUE TITLE
How to activate CSRF protection on GET requests?

### ISSUE THREAD

**Issue by lyml** [spring-projects/spring-security#7433]
Hi,

We are attempting to use Spring security to protect our project from CSRF requests. We activated it using `http.cors().and().csrf()` and it works fine for POST and PUT requests but we couldn't get it to verify our GET requests.

Any input on how to configure that?

**Comment by andifalk** [comment]
@lyml  You can override the default CSRF configuration using a Java configuration.
Please look into https://docs.spring.io/spring-security/site/docs/current/reference/html5/#overriding-defaults for details. So no real issue here.

**Comment by jzheaux** [comment]
Thanks for your interest, @lyml, and also to @andifalk for an informative answer.

@lyml if you have further questions about this, would you please post to [StackOverflow](https://stackoverflow.com/questions/ask) with a `spring-security` tag instead? The team monitors this SO tag regularly, and that's our preferred support platform. FFR, let's keep GitHub just for issues and feature requests.
