### ISSUE TITLE
Add AuthorizePayloadsSpec.Access hasAuthority

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#7435]
### Summary

We should add Add `AuthorizePayloadsSpec.Access` `hasAuthority(String)` method.

**Comment by eddumelendez** [comment]
Hi @rwinch I can take this issue. Some friends are starting contributing so I can work this one with them. /cc @munilvc

**Comment by rwinch** [comment]
Thanks @eddumelendez! That would be great. We'd like to try and have this done by Friday if possible. Do you think that could happen?

**Comment by eddumelendez** [comment]
we will work on it in the next hours :)
