### ISSUE TITLE
Does the authentication server support Webflux

### ISSUE THREAD

**Issue by yangle94** [spring-projects/spring-security#7436]
Can you give me an example?

**Comment by jgrandja** [comment]
@yangle94 Please post questions on StackOverflow as we use GitHub issues for tracking bugs and feature enhancements. See [guidelines](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues).

Also, please provide a lot more detail on your post so user's understand what you are asking. The question you have is too high-level.
