### ISSUE TITLE
TokenStore Options

### ISSUE THREAD

**Issue by yasser-kfupm** [spring-projects/spring-security#7438]
Hi, I am new to spring-security and I am trying to build oauth2 server backed with MongoDB. I tried to find MongodbTokenStore similar to JdbcTokenStore but I could not. 

is there any ready TokenStore Implementation for MongoDB?

Thanks in advance.

**Comment by jgrandja** [comment]
@yasser-kfupm We prefer questions to be posted on StackOverflow as we use GitHub issues to track bugs and feature enhancements. Please see [guidelines](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues).

Also, the question you have is related to the [Spring Security OAuth](https://github.com/spring-projects/spring-security-oauth) GitHub project, which is separate from Spring Security 5.x.

To answer your question, there is no MongoDB `TokenStore` implementation.

FYI, please see this [post](https://spring.io/blog/2018/01/30/next-generation-oauth-2-0-support-with-spring-security) for details on Spring Security's OAuth support.
