### ISSUE TITLE
Authorization Server support update?

### ISSUE THREAD

**Issue by jgiokas** [spring-projects/spring-security#7439]
In this [page](https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Features-Matrix) first FAQ it's mentioned that support for Authorization Server should come early 2019. Since now we are mid 2019 and soon entering into late 2019 is there any update for this feature? 

I know that you might not have hard deadlines but even a new estimation would help for some teams plans. Thanks

**Comment by jgrandja** [comment]
@jgiokas The team has been discussing the plan for Authorization Server support as of late. We will provide a more concrete update after Spring One which is Oct 7-11. Please stay tuned for an update in late October.

**Comment by krnbr** [comment]
@jgrandja 
is the Authorization Server going to come with new Spring security? Looks like not coming, but I saw someone mentioning as if it will be released with version 5.3

**Comment by jgrandja** [comment]
@krnbr Spring Security has decided to not support authorization servers. Please see the latest [announcement](https://spring.io/blog/2019/11/14/spring-security-oauth-2-0-roadmap-update) for further details.
