### ISSUE TITLE
OAuth 2 Autoconfiguration 401 Error for preflight request

### ISSUE THREAD

**Issue by rolaca11** [spring-projects/spring-security#7444]
### Summary

OAuth 2 Autoconfigurer doesn't take into account the _preflight_ requests sent by browsers typically before requests with _Authorization_ header.

### Actual Behavior

The browser sends a request with method _OPTIONS_ with some _Access-Control-Allow-*_ headers. Even though the request has been set up for HTTP Basic authentication, this _preflight_ request doesn't have this yet.

Because of this, Spring Security _falsely_ responds with a 401 status and the message "access-denied"

### Expected Behavior

The browser sends a request with method _OPTIONS_ with some _Access-Control-Allow-*_ headers. Even though the request has been set up for HTTP Basic authentication, this _preflight_ request doesn't have this yet.

Spring Security realises that this is only a preflight request and responds with a status code of 200, allowing the browser to continue with the real request.

### Configuration

The configuration comes from the _org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure_. More specifically, from class **org.springframework.security.oauth2.config.annotation.web.configuration.AuthorizationServerSecurityConfiguration:89**, where only the _fullyAuthenticated_ option is passed and there is no exception set for when a _preflight request_ arrives.

### Version

The version is: _org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure:2.1.8.RELEASE_

### Sample

https://bitbucket.org/rolaca11/spring-security-sample/
In this project, the _/rest/oauth/token_ resource should be queried.

**Comment by rolaca11** [comment]
I tried implementing a workaround, where I register a filter checking for _preflight_ requests, which solves the immediate problem of these kinds of requests resulting in 401 Unauthorized status.

However, in order for it to have an effect, I need to set the highest precedence to the configuration bean. This, however, hijacks the request from the desired filter chain as well, resulting in all kinds of errors along the way, when the browser sends the real authentication request.

**Comment by jgrandja** [comment]
@rolaca11 Please do not double post. This issue should have originally been logged to the Spring Security OAuth project. Closing in favour of [spring-security-oauth#1749](https://github.com/spring-projects/spring-security-oauth/issues/1749)

**Comment by rolaca11** [comment]
Sorry, didn't mean to double post. I just found the proper repository after I created this issue and didn't find a close button. 

Close #7444
