### ISSUE TITLE
SEC-485: org.acegisecurity.ui.rememberme.TokenBasedRememberMeServices cannot customize tokenExpiryTime for each login

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#746]
["zhouyanming":https://jira.spring.io/secure/ViewProfile.jspa?name=quaff](Migrated from ["SEC-485":https://jira.spring.io/browse/SEC-485?redirect=false]) said:

please see http://opensource.atlassian.com/projects/spring/browse/SEC-470 again

currently just can customize tokenValiditySeconds for all login not for every single login

**Comment by spring-issuemaster** [comment]
This issue is related to #731
