### ISSUE TITLE
WebFluxSecurityConfiguration does not configure oauth2Client

### ISSUE THREAD

**Issue by mbhave** [spring-projects/spring-security#7470]
In Spring Boot, for the servlet case, the auto-configuration configures both `oauth2Login` and `oauth2Client`. If there's a reason for not configuring `oauth2Client` in Spring Security for the reactive case, we should look at aligning things in Boot's auto-configuration.

**Comment by jgrandja** [comment]
Thanks @mbhave.
I've updated `WebFluxSecurityConfiguration` to be consistent with the defaults in `OAuth2WebSecurityConfiguration.OAuth2WebSecurityConfigurerAdapter`.
