### ISSUE TITLE
Tomcat 8.0.33 crashing with spring security

### ISSUE THREAD

**Issue by venkateshyella** [spring-projects/spring-security#7479]
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f5e79885cb8, pid=3364, tid=0x00007f5df6fef700
#
# JRE version: OpenJDK Runtime Environment (8.0_222-b10) (build 1.8.0_222-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.222-b10 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [core.so+0x7cb8]  socket_send+0x98
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /opt/apache-tomcat-8.0.33/bin/hs_err_pid3364.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Sep 23, 2019 11:55:39 -0700 [5979 1] com.newrelic INFO: New Relic Agent: Loading configuration file "/opt/apache-tomcat-8.0.33/newrelic/./newrelic.yml"
Sep 23, 2019 11:55:40 -0700 [5979 1] com.newrelic INFO: New Relic Agent: Writing to log file: /opt/apache-tomcat-8.0.33/newrelic/logs/newrelic_agent.log
[GC (Allocation Failure) [ParNew: 545344K->35317K(613440K), 0.0337966 secs] 545344K->35317K(5174784K), 0.0338674 secs] [Times: user=0.12 sys=0.01, real=0.04 secs] 
[GC (CMS Initial Mark) [1 CMS-initial-mark: 0K(4561344K)] 35327K(5174784K), 0.0046687 secs] [Times: user=0.01 sys=0.00, real=0.00 secs] 
[CMS-concurrent-mark-start]
[CMS-concurrent-mark: 0.001/0.001 secs] [Times: user=0.01 sys=0.00, real=0.00 secs] 
[CMS-concurrent-preclean-start]
[CMS-concurrent-preclean: 0.005/0.005 secs] [Times: user=0.03 sys=0.00, real=0.01 secs] 
[CMS-concurrent-abortable-preclean-start]
23-Sep-2019 11:55:44.925 WARNING [main] org.apache.catalina.startup.SetAllPropertiesRule.begin [SetAllPropertiesRule]{Server/Service/Connector} Setting property 'keepAlivetimeout' to '60000' did not find a matching property.
23-Sep-2019 11:55:44.940 WARNING [main] org.apache.catalina.startup.SetAllPropertiesRule.begin [SetAllPropertiesRule]{Server/Service/Connector} Setting property 'keepAlivetimeout' to '60000' did not find a matching property.
23-Sep-2019 11:55:45.033 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.33
23-Sep-2019 11:55:45.033 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Mar 18 2016 20:31:49 UTC
23-Sep-2019 11:55:45.033 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.33.0
23-Sep-2019 11:55:45.033 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
23-Sep-2019 11:55:45.033 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            3.10.0-957.27.2.el7.x86_64
23-Sep-2019 11:55:45.033 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
23-Sep-2019 11:55:45.033 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.el7_6.x86_64/jre
23-Sep-2019 11:55:45.034 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_222-b10
23-Sep-2019 11:55:45.034 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
23-Sep-2019 11:55:45.034 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /opt/apache-tomcat-8.0.33
23-Sep-2019 11:55:45.034 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /opt/apache-tomcat-8.0.33

**Comment by eleftherias** [comment]
@venkateshyella Can you please provide more information on how this error occurs? What would be most helpful is if you could provide a [complete and minimal sample](https://stackoverflow.com/help/mcve) that reproduces the issue and share it via a GitHub repository. This will allow us to efficiently troubleshoot and help resolve the issue. The sample should contain the minimum amount of code to reproduce the issue along with detailed steps on how to reproduce.

**Comment by fhanik** [comment]
@venkateshyella You'd want to take a look `/opt/apache-tomcat-8.0.33/bin/hs_err_pid3364.log`

My suggestion is that you disable your NewRelic agent while you are trouble shooting

```C [core.so+0x7cb8] socket_send+0x98```

Tells you that the JVM crashed during an attempt to send data on a socket while executing native code. This is probably unrelated to Spring Security.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
