### ISSUE TITLE
When use default JdbcDaoImpl , trouble with mysql8's keywords 'groups' 

### ISSUE THREAD

**Issue by lionliu6** [spring-projects/spring-security#7483]
#7291 # Summary

mysql8 keep 'groups' as keyword, so when using default UserDetailsService 'JdbcDaoImpl', error on.

### Actual Behavior

JdbcDaoImpl use table : 

`create table groups (
    id bigint generated by default as identity(start with 0) primary key,
    group_name varchar_ignorecase(50) not null
);
`

when query `select * from groups` , error occurs.
`
 SQL [1064] [42000]: You have an error in your SQL syntax; 
check the manual that corresponds to your MySQL server version for
 the right syntax to use near 'groups
`

 and sql used is using final String.

### Expected Behavior

If possible , with `JdbcDaoImpl` and it's manager , deployers may set custom sql or using custom table name.

Thanks.

### Version
5.1.6.RELEASE

**Comment by eleftherias** [comment]
Thanks for the report. This is a duplicate of gh-5253.
