### ISSUE TITLE
Authentication/Authorization support for RSocket Protocol

### ISSUE THREAD

**Issue by shazin** [spring-projects/spring-security#7485]
Similar to Authentication/Authorization support for Websocket there needs to be support for RSocket protocol as well in Spring Security.

**References**

- https://docs.spring.io/autorepo/docs/spring-security/4.0.x/reference/html/websocket.html
- http://www.rsocket.io

**Comment by eddumelendez** [comment]
[this commit](https://github.com/spring-projects/spring-security/commit/5a4eded696a32be563cf403e3073e5643c3b27ad) was introduced as a part of rsocket support in spring-security

**Comment by rwinch** [comment]
There is support added. See the commit that is referenced above
