### ISSUE TITLE
AbstractUserDetailsReactiveAuthenticationManager default Scheduler should be disposed

### ISSUE THREAD

**Issue by robotmrv** [spring-projects/spring-security#7492]
### Summary
AbstractUserDetailsReactiveAuthenticationManager creates new parallel `Scheduler` which creates `Thread`s with `daemon=false`.
```java
Scheduler scheduler = Schedulers.newParallel("password-encoder");
```
As states `Schedulers.newParallel` javadoc 
> daemon – false if the Scheduler requires an explicit Scheduler.dispose() to exit the VM.

### Actual Behavior
default `Scheduler` is not disposed 
1. on `AbstractUserDetailsReactiveAuthenticationManager` bean destruction 
2. or if custom `Scheduler` was set

### Expected Behavior
default `Scheduler` should be disposed 
1. on `AbstractUserDetailsReactiveAuthenticationManager` bean destruction 
2. or if custom `Scheduler` was set

### Version
`5.2.0.BUILD-SNAPSHOT`

**Comment by rwinch** [comment]
@robotmrv I went ahead and changed this fix to use a daemon thread instead. We don't need the thread to block shutting down the JVM.

**Comment by robotmrv** [comment]
@rwinch 
I thought about this solution (https://github.com/spring-projects/spring-security/commit/cb5c58eeaadee97d9b622454428dc6a9169ab1a1#r35174748) 
`Schedulers.newParallel("password-encoder", Schedulers.DEFAULT_POOL_SIZE, true)` 
but there is another problem  
if user wants to refresh application context, default scheduler will not be disposed so unused redundant `Threads` will be present.  
So for this case it should be disposed in anyway

**Comment by rwinch** [comment]
Thanks. Then perhaps it should be a static member variable w/ the default values

**Comment by robotmrv** [comment]
yes, static default `Scheduler` will solve that problem
