### ISSUE TITLE
Update to Jetty 9.4.22.v20191022

### ISSUE THREAD

**Issue by davidkarlsen** [spring-projects/spring-security#7507]
See issue https://github.com/eclipse/jetty.project/issues/4141
Running on java 12 + spring security 5.1.6 + jetty 9.4.21 - same mix worked with jetty 9.4.20

**Comment by joakime** [comment]
Jetty has been able to replicate this issue without spring-security in the mix.
A fix is being reviewed and a new release is likely.

**Comment by spring-issuemaster** [comment]
Fixed via 8fa16ce63e3ca8bfedbb6e19af89498704aa005d
