### ISSUE TITLE
MS SQL Server  Invalid object name 'authorities'. (keywords)

### ISSUE THREAD

**Issue by svatos-jirka** [spring-projects/spring-security#7530]
Hi,

### Summary
We use MS SQL Server 2017. We got serious exception:

bad SQL grammar [insert into authorities (username, authority) values (?,?)]; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'authorities'.

It looks like, that native sql query (bellow) contains "keywords" "authorities:

public static final String | DEF_INSERT_AUTHORITY_SQL | "insert into authorities (username, authority) values (?,?)"

Second Idea:
Native sql query doesnt respect fact, that MS SQL Server  is multi DB machine. So prefix of table "authorities" is missing. Maybe it should be "DATABASE_NAME.authorities" ...

### Actual Behavior
Implementation JdbcUserDetailsManager of Spring security core 5.0.4 contains fixed native query which contains "authorities" word.

### Expected Behavior
Maybe: replace sql native query with something more compatible with MS SQL Server. 

### Configuration
Spring security core 5.0.4
MS SQL Server 2017
Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

### Sample
JdbcUserDetailsManager  detailsManager = ....
 detailsManager.createUser(
                new User("admin", encoder.encode("admin"), authorities));
   this ends with exception

**Comment by svatos-jirka** [comment]
Solved:

For unknown reason, the table "authorities" was mising DB in case MS SQL Server.
If we use H2, the table "authorities" is created.

**Comment by jzheaux** [comment]
@svatos-jirka thanks for the report.

Sorry, but I can't tell if you are still having an issue. In your last comment, you say that you've "solved" your issue.

Is there anything you'd like to be investigated or fixed? If not, please close the issue.

**Comment by svatos-jirka** [comment]
I think, that good question is, why table "authorities" is not created in
MS SQL DB only.
Maybe "create table script" failed, but I dont know, how to investigate.

with best regards
jiri

út 29. 10. 2019 v 21:18 odesílatel Josh Cummings <notifications@github.com>
napsal:

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by svatos-jirka** [comment]
> If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

Hi,

I can use manager.setCreateAuthoritySql, it works. But we are use diferent databases (h2 and ms sql). In this case, I have to use some condition to manager.setCreateAuthoritySql(MS SQL script,...) or manager.setCreateAuthoritySql(H2 SQL script,....).

We solved this issue by add special schema script for MS SQL DB.

**Comment by rwinch** [comment]
That makes sense. We don't plan on providing SQL for all database types, so this is something that is up to users to provide. I'm closing this issue. If you find a passive concrete improvement, please create a new ticket.
