### ISSUE TITLE
Add hasAnyIpAddress expression for url authorisation

### ISSUE THREAD

**Issue by ziebamarcin** [spring-projects/spring-security#7535]
### Summary
Add new method for configuring Ip Address white list instead of single ip Address authorisation 

### Actual Behavior
There is only one method for authorising URLs only for specified IP addresses and it take single `String` argument. It is complicated to configure URL authorization for more than one Ip address (it can be done by custom expression like `access("hasIpAddress('192.168.0.1') or hasIpAddress('202.12.0.1')")` but it is not scalable if you have more ip address specified)

### Expected Behavior
It should be possible to configure authorisation for more than one Ip address

**Comment by jzheaux** [comment]
@ziebamarcin thanks for the suggestion. 

What about declaring a bean instead?

```java
access("@ipAddressMatcher.matches(request)")
```
and
```java
@Bean 
public RequestMatcher ipAddressMatcher(List<String> ipAddresses) {
    List<IpAddressMatcher> whitelist = Stream.of(ipAddresses)
        .map(IpAddressMatcher::new).collect(Collectors.toList());
    return new OrRequestMatcher(whitelist);
}
```

The nice thing about this approach is that you aren't hardcoding a bunch of IP addresses into SpEL expressions.

**Comment by ziebamarcin** [comment]
That is nice idea, I didn't know this approach with `@` and bean. 

But what I have suggested in PR also applies to common approach in Spring Security e.g.
```
hasAnyAuthority(String... authorities)
```
or
```
hasAnyRole(String... roles)
```
Of course I agree with your suggestion but I think that adding new method is also good solution. @jzheaux What do you think?

**Comment by jzheaux** [comment]
I do see the appeal of aligning with `hasAnyRole` et al, but I believe that exposing a bean is preferred in this case.

I've got a bit more detail in https://github.com/spring-projects/spring-security/pull/7536#issuecomment-560942262, but if you feel like there is more to discuss, feel free to comment here.
