### ISSUE TITLE
InMemoryClientRegistrationRepository: Factory method threw exception; nested exception is java.lang.NoSuchFieldError: PASSWORD

### ISSUE THREAD

**Issue by kacperduras** [spring-projects/spring-security#7545]
Thread on SO: [here](https://stackoverflow.com/questions/58449315/inmemoryclientregistrationrepository-factory-method-threw-exception-nested-exc/)

### Summary

I am using `spring-boot` with `spring-security` and OAuth2 authorization in my standalone application, but I have an [unexpected error](https://gist.github.com/kacperduras/8d270f35554b72591f5f4841ff3fbbf0), who I can't fix. This is associated with `ClientRegistrationRepository` and my factory method. I tried to make own implementation of this interface, but I had same problem. So, I came back to previous version (`5.1.6.RELEASE`), and it works!

### Version

- spring-boot-starter: **2.1.9.RELEASE**
- spring-security-core, spring-security-web, spring-security-config, spring-security-oauth2-client, spring-security-oauth2-jose: **5.2.0.RELEASE** (worked version: `5.1.6.RELEASE`)

### Samples

[here](https://gist.github.com/kacperduras/a7b9202b51bcc2336cc800a511287a21)

**Comment by jgrandja** [comment]
@kacperduras Spring Boot `2.1.9.RELEASE` is meant to work with Spring Security `5.1.6.RELEASE`. See [spring-security.version](https://github.com/spring-projects/spring-boot/blob/v2.1.9.RELEASE/spring-boot-project/spring-boot-dependencies/pom.xml#L181)

If you would like to use Spring Security `5.2.0.RELEASE` than you need to use Spring Boot `2.2.0.RELEASE`.

I'm going to close this ticket as I believe I answered your issue.
