### ISSUE TITLE
SEC-493: Improve org.acegisecurity.ui.AbstractProcessingFilter to support variable redirection

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#755]
["zhouyanming":https://jira.spring.io/secure/ViewProfile.jspa?name=quaff](Migrated from ["SEC-493":https://jira.spring.io/browse/SEC-493?redirect=false]) said:

If not specify 'defaultTargetUrl' in configuration,then use httpRequest.getHeader("Referer") ,and finally use httpRequest.getParameter("targetUrl") if exists.

**Comment by spring-issuemaster** [comment]
This issue is related to #752
