### ISSUE TITLE
SEC-494: Add IgnoredChannelProcessor for org.acegisecurity.securechannel.ChannelDecisionManagerImpl

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#758]
["zhouyanming":https://jira.spring.io/secure/ViewProfile.jspa?name=quaff](Migrated from ["SEC-494":https://jira.spring.io/browse/SEC-494?redirect=false]) said:

when use ajax,switch http and https may cause cross domain exception.
I need:
in page  https://localhost:8443/account/login,dwr is https://localhost:8443/dwr/
in page http://localhost:8080/index,dwr is http://localhost:8080/dwr/
so I add a IgnoredChannelProcessor with key 'IGNORED_CHANNEL'

CONVERT_URL_TO_LOWERCASE_BEFORE_COMPARISON
\A/struts/._\Z=IGNORED_CHANNEL
\A/dwr/._\Z=IGNORED_CHANNEL
\A/account/._\Z=REQUIRES_SECURE_CHANNEL
\A/._\Z=REQUIRES_INSECURE_CHANNEL

**Comment by spring-issuemaster** [comment]
This issue duplicates #596
