### ISSUE TITLE
Can i use  RedisTokenStore to change the information of authentication 

### ISSUE THREAD

**Issue by planitian** [spring-projects/spring-security#7591]
After user login,Oauth2 store the authentication in redis. then i hava a demand that i want change the information of authentication that in redis. I can logout and login to change ,but  I think it is not  grace. so can i use  RedisTokenStore to change the information of authentication ?

I  find that RedisTokenStroe has public method that can read authentication,can store authentication,so it implies that I can read authtication first,and then change the authtication,finally store the authtication that i has changed.

**Comment by rwinch** [comment]
Issue moved to [spring-projects/spring-security-oauth #1796](https://github.com/spring-projects/spring-security-oauth/issues/1796) via [**ZenHub**](https://www.zenhub.com/)

**Comment by planitian** [comment]
@rwinch Thank you very much
