### ISSUE TITLE
The problem in the org.springframework.security.access.expression.SecurityExpressionRoot

### ISSUE THREAD

**Issue by LeeHainie** [spring-projects/spring-security#7601]
Code:

        private Set<String> getAuthoritySet() {
		if (roles == null) {
			roles = new HashSet<>();
			Collection<? extends GrantedAuthority> userAuthorities = authentication
					.getAuthorities();

			if (roleHierarchy != null) {
				userAuthorities = roleHierarchy
						.getReachableGrantedAuthorities(userAuthorities);
			}

			roles = AuthorityUtils.authorityListToSet(userAuthorities);
		}

		return roles;
	}

The "roles = new HashSet<>();" is  unnecessary and inefficiency.
Hope it can be modified.

**Comment by LeeHainie** [comment]
In line 161.

**Comment by eleftherias** [comment]
Thank you for the report @LeeHainie. 
I agree that `roles = new HashSet<>();` is unnecessary.
Are you interested in submitting a PR to remove it?

**Comment by LeeHainie** [comment]
Yes, I'd love to.

**Comment by eleftherias** [comment]
Closed in 4b4c6e6.
