### ISSUE TITLE
Spring security Remember me token not removed over logout

### ISSUE THREAD

**Issue by misisol** [spring-projects/spring-security#7619]
Hi.
Im using Remember me token for my application server.

`    @Bean
    public RememberMeServices rememberMeServices()  {
        TokenBasedRememberMeServices result = new TokenBasedRememberMeServices("High3lf8LooD", userDetailsService);
        result.setAlwaysRemember(true);
        result.setCookieName("remember-me");
        result.setParameter("remember-me");
        result.setTokenValiditySeconds(365*24*60*60);
//        result.setUseSecureCookie(true);
        return result;
    }`

Before upgrading to spring boot 2.2, Remember me get deleted logically on logout. 
But not after the upgrade. Even if I delete it on Logout explicitly, it doesn't get deleted after logout.
`                        .logout()
                           .logoutUrl("/user/logout")
                            .logoutSuccessHandler(customLogoutSuccessHandler)
                             .logoutSuccessUrl("/user/login")
                            .deleteCookies("remember-me")`

**Comment by eleftherias** [comment]
@misisol I was not able to reproduce this issue.
Do you have a minimal sample that demonstrates this behaviour?

**Comment by misisol** [comment]
This is all I got for the remember me token system : 
<img width="1203" alt="Screen Shot 2019-11-07 at 9 16 47 AM" src="https://user-images.githubusercontent.com/26188869/68363328-c0f3ec00-013f-11ea-88b3-beebbcc0e29b.png">
<img width="1127" alt="Screen Shot 2019-11-07 at 9 17 16 AM" src="https://user-images.githubusercontent.com/26188869/68363334-c5b8a000-013f-11ea-8d2f-b3263f97b320.png">

**Comment by eleftherias** [comment]
@misisol Thank you for sharing your code.
Looking at what you have provided I don't see anything that would cause the cookie to remain after logout.
If you can create a minimal sample that reproduces this issue, then we can help you debug it.

**Comment by misisol** [comment]
I've checked it again, but this time without using the Serviceworker ( We're using it for PWA ).
This time it works as expected.
But after activating the Serviceworker again, it won't.
What does it has to do with the serviceworker?

My architecture goes as below:
- if the user selects on logout -> user gets logout and redirected to login page.
- when a user is redirected to login page, if the user is logged in or has remember-me token ( which tries autoLogin and if successfull ) gets redirected to events page.

Now what happens with serviceworker enabled goes like this :
- the user clicks on logout button -> the user gets redirected to login page -> the login page GET response comes with a 302 redirect , which refers to events page;  and the user is still logged in.

<img width="1339" alt="Screen Shot 2019-11-08 at 10 41 32 AM" src="https://user-images.githubusercontent.com/26188869/68456967-624c7200-0214-11ea-8dab-4a0fbb164109.png">

<img width="1178" alt="Screen Shot 2019-11-08 at 10 42 35 AM" src="https://user-images.githubusercontent.com/26188869/68457022-81e39a80-0214-11ea-882a-a7c34c6b4881.png">

<img width="1104" alt="Screen Shot 2019-11-08 at 10 43 01 AM" src="https://user-images.githubusercontent.com/26188869/68457111-bd7e6480-0214-11ea-8153-34e062adf4f6.png">
<img width="1326" alt="Screen Shot 2019-11-08 at 10 43 24 AM" src="https://user-images.githubusercontent.com/26188869/68457122-c2dbaf00-0214-11ea-85c9-049562d7e944.png">
<img width="1165" alt="Screen Shot 2019-11-08 at 10 43 52 AM" src="https://user-images.githubusercontent.com/26188869/68457128-c5d69f80-0214-11ea-8fcb-ca14502841d5.png">
<img width="1219" alt="Screen Shot 2019-11-08 at 10 44 02 AM" src="https://user-images.githubusercontent.com/26188869/68457141-c96a2680-0214-11ea-9c0f-202bc5aa5cd2.png">
<img width="1091" alt="Screen Shot 2019-11-08 at 10 44 05 AM" src="https://user-images.githubusercontent.com/26188869/68457150-cc651700-0214-11ea-9c3d-043cdf749082.png">

**Comment by eleftherias** [comment]
@misisol Can you please provide us with a minimal sample that reproduces this issue?
This will allow us to efficiently troubleshoot and help resolve the issue.

You may also find it helpful to post a question on StackOverflow, since someone in the community using Serviceworker with Spring Security may have seen this before.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
