### ISSUE TITLE
SEC-500: Provide a getFilterProcessesUrl (protected or public) method in org.acegisecurity.ui.logout.LogoutFilter so that subclasses can access this parameter

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#762]
["Bora Erbas":https://jira.spring.io/secure/ViewProfile.jspa?name=bora.erbas](Migrated from ["SEC-500":https://jira.spring.io/browse/SEC-500?redirect=false]) said:

Provide a getFilterProcessesUrl (protected or public) method in org.acegisecurity.ui.logout.LogoutFilter so that subclasses can access this parameter.

**Comment by rwinch** [comment]
This issue depends on #672
This issue duplicates #672
