### ISSUE TITLE
Add custom ServerHttpHeadersWriter  to HeadersSpec 

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#7636]
### Summary

We should add the ability to have a custom `ServerHttpHeadersWriter` to `HeaderSpec`.

```java
@Bean
SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
	http
		// ...
		.headers(headers ->
			headers
				.writer(serverHttpHeadersWriter)
		);
	return http.build();
}
```

**Comment by ankurpathak** [comment]
@rwinch I would like to take this one.

**Comment by jzheaux** [comment]
It's yours, @ankurpathak!

**Comment by jzheaux** [comment]
Hi, @ankurpathak, will you still be able to take a look at this?

**Comment by ankurpathak** [comment]
@jzheaux I will submit pr in this week

**Comment by ankurpathak** [comment]
@jzheaux @rwinch Here is a pull request for the issue:
https://github.com/spring-projects/spring-security/pull/8028
@jzheaux Sorry for the delayed work as I got busy with my professional project.
