### ISSUE TITLE
Unable to use OAuth client without adding server security

### ISSUE THREAD

**Issue by ipsi** [spring-projects/spring-security#7646]
### Summary
I would like to be able to use the OAuth client without having to include all the server side configuration, e.g., if security is provided externally by route services.

I ran into this specifically with `io.pivotal.spring.cloud:spring-cloud-services-starter-config-client`, which needs to pull in Spring Security OAuth2, because AFAICT it connects to the SCC Server via OAuth.

I realise that `io.pivotal.spring.cloud:spring-cloud-services-starter-config-client` is using `org.springframework.security.oauth:spring-security-oauth`, which is deprecated, but as far as I can tell, the behaviour is the same in Spring 5.

In this case, our client application does _not_ have a direct dependency on Spring Security, so we had to add more code purely to disable HTTP Basic Auth, but this feels like it shouldn't be necessary - we do not and will not use Spring Security to provide security for the application as a whole, so it would be nice if the OAuth2 client project didn't pull that configuration in as well (which I believe is provided by the `spring-security-web` project?).

I realise this is probably a lot harder than it sounds, and it's possible that `io.pivotal.spring.cloud:spring-cloud-services-starter-config-client` could be doing something differently.

### Version

3.2.10, but the issue would also be present in Spring Security 5.2.1, as the `oauth2-client` depends on `web`.

**Comment by jgrandja** [comment]
@ipsi Can you provide more details on your use case? For example, are you simply using the client to obtain an access token using `client_credentials` and than using the token to call a protected resource with `WebClient`? Please be specific so we can answer your question correctly.

**Comment by jgrandja** [comment]
@ipsi As discussed offline (Slack), I'm going to close this issue since you'll be raising this with the Spring Cloud Services team.
