### ISSUE TITLE
Document Spring Security Ldap: Class LdapUtils is missing information

### ISSUE THREAD

**Issue by TranNgocKhoa** [spring-projects/spring-security#7648]
### Summary

API Document  `org.springframework.security.ldap.LdapUtils` in ` spring-security-ldap` module is missing.
Link: https://docs.spring.io/autorepo/docs/spring-security/5.2.x-SNAPSHOT/api/org/springframework/security/ldap/LdapUtils.html

> public static java.lang.String getRelativeName(java.lang.String fullDn,
                                               javax.naming.Context baseCtx)
                                        throws javax.naming.NamingException
> Obtains the part of a DN relative to a supplied base context.
> If the DN is "cn=bob,ou=people,dc=springframework,dc=org" and the base context name is "ou=people,dc=springframework,dc=org" it would return "cn=bob".
> Parameters:
> fullDn - the DN
> baseCtx - the context to work out the name relative to.
> Returns:
> **the**
> Throws:
> javax.naming.NamingException - any exceptions thrown by the context are propagated.

return section show only "the".

Hope it will be fixed in next release. Thank you!

**Comment by jzheaux** [comment]
Thanks for reaching out, @TranNgocKhoa.

That text is determined in https://github.com/spring-projects/spring-security/blob/master/ldap/src/main/java/org/springframework/security/ldap/LdapUtils.java#L93

Would you be interested in submitting a PR to add the missing documentation?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
