### ISSUE TITLE
cannot be cast to class org.springframework.security.web.savedrequest.SavedRequest

### ISSUE THREAD

**Issue by 13940344135** [spring-projects/spring-security#7649]
versions：spring security 5.1.5

Spring MVC as the authentication server, spring webflux will be redirected to the spring MVC login page when they are not authenticated, they use redis to share the session.

The problem now is that
When redirected, the webflux service saves the following information to the session to recover the interrupted request:
sessionAttr: SPRING_SECURITY_SAVED_REQUEST,

When the MVC server receives the request, the following error occurs:
java.lang.ClassCastException: class java.lang.String cannot be cast to class org.springframework.security.web.savedrequest.SavedRequest

The exception code location is as follows:
Public class HttpSessionRequestCache implements RequestCache {
・・・・・・
    Public SavedRequest getRequest(HttpServletRequest currentRequest,
              HttpServletResponse response) {
・・・・・・
        Return (SavedRequest) session.getAttribute(this.sessionAttrName);

Why can't SavedRequest be converted?
Not storing SPRING_SECURITY_SAVED_REQUEST in the session will successfully redirect to the login page, but that will also lose the ability to restore requests, I need it.

**Comment by jzheaux** [comment]
See https://github.com/spring-projects/spring-security/issues/7653
