### ISSUE TITLE
SEC-504: Files missing on acegi-security-sample-tutorial.war

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#765]
["Aldo Barroso Cores Junior":https://jira.spring.io/secure/ViewProfile.jspa?name=aldo.bsb](Migrated from ["SEC-504":https://jira.spring.io/browse/SEC-504?redirect=false]) said:

The files listed below (mentioned on http://www.acegisecurity.org/petclinic-tutorial.html) are missing in acegi-security-sample-tutorial.war.

[acegi-security-sample-tutorial.war]\acegilogin.jsp
[acegi-security-sample-tutorial.war]\accessDenied.jsp
[acegi-security-sample-tutorial.war]\WEB-INF\users.properties
[acegi-security-sample-tutorial.war]\WEB-INF\applicationContext-acegi-security.xml

**Comment by rwinch** [comment]
This issue duplicates #749
