### ISSUE TITLE
spring security config suddently requires network access

### ISSUE THREAD

**Issue by fabianfrz** [spring-projects/spring-security#7650]
### Summary

The XML parser fails to load the configuration because the server has no internet access

### Actual Behavior

Spring runs into a timeout after 3 minutes and then it fails to load the XML file.
 
```
Offending resource: ServletContext resource [/WEB-INF/applicationContext.xml]; nested exception is org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 12 in XML document from ServletContext resource [/WEB-INF/spring/security.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 12; columnNumber: 57; cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'http'.
```

### Expected Behavior

spring security loads the xsd from the local jar file

### Configuration

Spring security configuration snippet:

```
<b:beans xmlns="http://www.springframework.org/schema/security"
         xmlns:b="http://www.springframework.org/schema/beans"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:util="http://www.springframework.org/schema/util"
         xsi:schemaLocation="http://www.springframework.org/schema/beans
         http://www.springframework.org/schema/beans/spring-beans.xsd
         http://www.springframework.org/schema/security
         http://www.springframework.org/schema/security/spring-security.xsd
         http://www.springframework.org/schema/util
         http://www.springframework.org/schema/util/spring-util.xsd">

    <http use-expressions="true" create-session="never">
...
```

### Version

Broken: 5.2.1.RELEASE

Spring Security config jar in project: spring-security-config-5.2.1.RELEASE.jar

**Comment by TheLawful** [comment]
The mapping for spring-security.xsd was initially changed to https:// in 5.2. I wrote a bug ticket about that I don't find anymore, but changing the schemaLocation entry to

https://www.springframework.org/schema/security/spring-security.xsd

(https) should fix it. Upcoming releases will understand both http:// and https://.

**Comment by jzheaux** [comment]
Closing as a duplicate of https://github.com/spring-projects/spring-security/pull/7623

**Comment by TheLawful** [comment]
Found the ticket.
https://github.com/spring-projects/spring-security/issues/7560
