### ISSUE TITLE
Connect2id exception: JSON object member with key "scope" has null value

### ISSUE THREAD

**Issue by ghostd** [spring-projects/spring-security#7651]
Hi,

I use Spring Security 5 (with Spring Boot 2.2.1) to make some oauth authorizations. One of my partners returns this kind of oauth response (the scope attribute is set to null):
```json
{"access_token":"valid access token with a lot of characters","expires_in":1800,"
token_type":"bearer","scope":null,"refresh_token":"valid refresh token"}
```

With this response, i get an error with the following exception:

```
Caused by: com.nimbusds.oauth2.sdk.ParseException: JSON object member with key "scope" has null value
	at com.nimbusds.oauth2.sdk.util.JSONObjectUtils.getGeneric(JSONObjectUtils.java:128)
	at com.nimbusds.oauth2.sdk.util.JSONObjectUtils.getString(JSONObjectUtils.java:399)
	at com.nimbusds.oauth2.sdk.token.BearerAccessToken.parse(BearerAccessToken.java:228)
	at com.nimbusds.oauth2.sdk.token.AccessToken.parse(AccessToken.java:273)
	at com.nimbusds.oauth2.sdk.token.Tokens.parse(Tokens.java:179)
	at com.nimbusds.oauth2.sdk.AccessTokenResponse.parse(AccessTokenResponse.java:199)
	at com.nimbusds.oauth2.sdk.TokenResponse.parse(TokenResponse.java:75)
	at org.springframework.security.oauth2.core.web.reactive.function.OAuth2AccessTokenResponseBodyExtractor.parse(OAuth2AccessTokenResponseBodyExtractor.java:68)
...
```

I already reported the [bug](https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/issues/281/) to connect2id.

For now, i had to copy/paste `OAuth2AccessTokenResponseBodyExtractor` (which is not public) to change the `parse` method as follow:
```java
    private static TokenResponse parse(Map<String, Object> json) {
        try {
            // WORKAROUND
            // https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/issues/281/
            if (json.containsKey("scope") && json.get("scope") == null) {
                json.remove("scope");
            }
            // END OF WORKAROUND
            return TokenResponse.parse(new JSONObject(json));
        }
        catch (ParseException pe) {
            OAuth2Error oauth2Error = new OAuth2Error(INVALID_TOKEN_RESPONSE_ERROR_CODE,
                    "An error occurred parsing the Access Token response: " + pe.getMessage(), null);
            throw new OAuth2AuthorizationException(oauth2Error, pe);
        }
    }
```

Would you agree to integrate this workaround into the next patch version (5.2.2?) ?
* i don't know how many times ConnectId project will need to fix that (although i'm confident they'll fix it quickly according to their first comment)
* even if they fix it nearly, their next version will be a minor version (i guess), and AFAIK spring security won't be able to upgrade in a version compliant with the next Spring Boot version (ideally, i'd like to not maintain this raw copy/paste until the Spring Boot 2.3)

Regards

Edit: the bug has been fixed in [version 6.18.1](https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/src/master/CHANGELOG.txt)
My question remains to know if i have to keep the raw copy until the next minor of Spring Boot

**Comment by jzheaux** [comment]
Thanks, @ghostd, for taking the initiative to reach out to Nimbus. That's great that they were able to meet your needs.

You are correct that we won't take that upgrade until 5.3, which is currently scheduled for March.

Have you considered overriding the `oidc-oauth2-sdk` dependency yourself in your pom?

As for the workaround, while copying 100 lines of code is not ideal, we also won't change any public APIs until 5.3 either.

**Comment by ghostd** [comment]
Hi,

I overrided the SDK and it works for my case.

I don't know if i can close this issue or if you wish to keep it open to track the upgrade.

Cheers

**Comment by jzheaux** [comment]
Thanks for the info, @ghostd!

Closing in favor of https://github.com/spring-projects/spring-security/issues/7667
