### ISSUE TITLE
error in javadoc for oauth2ResourceServer

### ISSUE THREAD

**Issue by ah1508** [spring-projects/spring-security#7670]
Documentation for `HttpSecurity oauth2ResourceServer(Customizer<OAuth2ResourceServerConfigurer<HttpSecurity>> oauth2ResourceServerCustomizer)` method is wrong : 

```java
protected void configure(HttpSecurity http) throws Exception {
	http
		.authorizeRequests(authorizeRequests ->
			authorizeRequests
				.anyRequest().authenticated()
		)
		.oauth2ResourceServer(oauth2ResourceServer ->
			oauth2ResourceServer
				.jwt(jwt ->
					jwt
						.jwtAuthenticationConverter(jwtDecoder())
				)
		);
}

@Bean
public JwtDecoder jwtDecoder() {
	return JwtDecoders.fromOidcIssuerLocation(issuerUri);
}
```

`jwtAuthenticationConverter` methd expects a converter, not a decoder.

**Comment by eleftherias** [comment]
Thanks for the report @ah1508 ! Would you be interested in submitting a PR to fix the Javadoc?

**Comment by Andrej37** [comment]
> Thanks for the report @ah1508 ! Would you be interested in submitting a PR to fix the Javadoc?

Привет
