### ISSUE TITLE
SEC-507: [patch] Support JSR-250 @RolesAllowed annotation

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#768]
["Usama Rashwan":https://jira.spring.io/secure/ViewProfile.jspa?name=usama_ra](Migrated from ["SEC-507":https://jira.spring.io/browse/SEC-507?redirect=false]) said:

This patch provides support for the JSR-250 @RolesAllowed annotation.

See this thread for more details:

http://forum.springframework.org/showthread.php?t=41001

**Comment by rwinch** [comment]
This issue is related to #690

**Comment by spring-issuemaster** [comment]
This issue is related to #690

**Comment by spring-issuemaster** [comment]
This issue is related to #690

**Comment by spring-issuemaster** [comment]
This issue is related to #690
