### ISSUE TITLE
Disabling logout in WebFlux does nothing

### ISSUE THREAD

**Issue by eleftherias** [spring-projects/spring-security#7682]
### Summary

Although there is a function to disable logout in WebFlux, it does not work.

### Actual Behavior

When disabling logout, a "/logout" page is still generated.

### Expected Behavior

When disabling logout, no "/logout" should be generated.

### Configuration

```
@EnableWebFluxSecurity
static class SecurityConfig {
	@Bean
	SecurityWebFilterChain springSecurity(ServerHttpSecurity http) {
		http
			.logout()
				.disable();

		return http.build();
	}
}
```

**Comment by spring-issuemaster** [comment]
Fixed via 0d24e2b8cfc872327656907e4fc889351bcaacc7
