### ISSUE TITLE
Rest httpBasic authentication problem when using custom UserDetailsService

### ISSUE THREAD

**Issue by misisol** [spring-projects/spring-security#7698]
### Summary

I wanted to authenticate the user in httpBasic and I didn't need to create a session or go for JWT or whatever.
So I've implemented the UserDetailsService and WebSecurityConfigurerAdapter
First I came with creating some In memory users as below and every thing worked as expected : 

```
> @Configuration
>  @EnableWebSecurity
> @EnableGlobalMethodSecurity(prePostEnabled = true)
>  public class SpringSecurityConfig extends WebSecurityConfigurerAdapter {
> 
>   @Autowired
>     public void configureGlobal(AuthenticationManagerBuilder authentication)
>             throws Exception
>     {
>         authentication.inMemoryAuthentication()
>                 .withUser("admin")
>                 .password(passwordEncoder().encode("welcome1"))
>                 .authorities("ADMIN");
>     }
> 
>     @Bean
>     public PasswordEncoder passwordEncoder() {
>         return new BCryptPasswordEncoder();
>     }
> 
>  @Override
>     protected void configure(HttpSecurity http) throws Exception {
>         http.csrf().disable()
>                 .authorizeRequests()
> //                .antMatchers("/app/**").hasRole("ADMIN")
>                 .anyRequest().authenticated()
>                 .and().httpBasic().realmName("Quick Poll")
>                 .and().sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS);
>     }}
```

> `curl -i -u admin:welcome1 -X GET http://localhost:8001/app/managementMain
`

Then I wanted to replace in memory users with the real ones in my Mongo database. 
So I replaced the configureGlobal to this One : 

```

>  @Autowired
>     AuthenticationService userDetailsService;
> 
>     @Override
>     protected void configure(AuthenticationManagerBuilder auth) throws Exception {
>         auth.userDetailsService(userDetailsService)
>                 .passwordEncoder(passwordEncoder());
>     }

```

And the AuthenticationService is the class which has implemented UserDetailsService Interface : 

```
> @Component
> public class AuthenticationService implements UserDetailsService {
> 
> 	@Autowired
> 	AccountRepo accountRepo;
> 
> 	@Override
> 	public UserDetails loadUserByUsername(String email)
> 			throws UsernameNotFoundException{
> 	    
> 		boolean enabled = true;
> 		boolean accountNonExpired = true;
> 		boolean credentialsNonExpired = true;
> 		boolean accountNonLocked = true;
> 		Account account = accountRepo.findOneByDefinedId(email);
> 
> 		System.out.println(email);
> 		if(account==null){
> 			System.out.println("account is null");
> 		}else{
> 			System.out.println("account is not null");
> 		}
> 
> 		try {
> 			// User is a class impementing UserDetails InterFace ,, Spring class.
> 			UserExtended userdetails = new UserExtended(
> 				account.getEmail(),
> 				account.getPassword(),
> 				enabled,
> 				accountNonExpired,
> 				credentialsNonExpired,
> 				accountNonLocked,
> 				getAuthorities(account),
> 				account.getName(),
> 				account.getId());
> 
> 			return userdetails;
> 
> 		} catch (UsernameNotFoundException e) {
> 			return new UserDetails() {
> 				@Override
> 				public Collection<? extends GrantedAuthority> getAuthorities() {
> 					return null;
> 				}
> 
> 				@Override
> 				public String getPassword() {
> 					return null;
> 				}
> 
> 				@Override
> 				public String getUsername() {
> 					return null;
> 				}
> 
> 				@Override
> 				public boolean isAccountNonExpired() {
> 					return false;
> 				}
> 
> 				@Override
> 				public boolean isAccountNonLocked() {
> 					return false;
> 				}
> 
> 				@Override
> 				public boolean isCredentialsNonExpired() {
> 					return false;
> 				}
> 
> 				@Override
> 				public boolean isEnabled() {
> 					return false;
> 				}
> 			};
> 
> 		}catch (Exception e) {
> 			throw new RuntimeException(e);
> 
> 		}
> 	}
> 
> 	public List getAuthorities(Account account) {
> 		List authList = new ArrayList();
> 		authList.add(new SimpleGrantedAuthority(account.getRole()));
> 
> 		return authList;
> 	}
> 	
> }
```

### Actual Behavior And Expected Behavior

After the changes to custom UserDetailService and running the command

> `curl -i -u admin:welcome1 -X GET http://localhost:8001/app/managementMain
`
I get 401 status code which goes for unsuccessful authentication.
The point is that the loadUserByUsername is getting called and the user is being found by the provided method, and the UserExtended is being returned successfully, but authentication is NOT.
(UserExtended  extends User ).

After that I've managed to use a create a class and implement **AuthenticationProvider** for my use case which is done without any problem. ( If you need it I can post it below).
I've found this a **bug** to report.

### Version

Spring boot 2.2.1
Spring security 5.2.1

**Comment by fhanik** [comment]
Hi @misisol 

This appears to be a question around configuration, rather than a bug in the Spring Security codebase.
You can review [existing questions[1]](https://stackoverflow.com/search?q=%5Bspring-security%5D+custom+userdetailsservice) on StackOverflow, or perhaps ask a new one.

Remember, if you provide a link to a usable sample you may get a better response.

There are [some posts [2]](https://www.ekiras.com/2016/04/authenticate-user-with-custom-user-details-service-in-spring-security.html) that cover the topic as well.

I will be closing this issue reasoning it's a question. If you feel I have done so in error, please open a new issue with a sample highlighting the bug itself.

Thank you for your contributions to Spring Security

[1] https://stackoverflow.com/search?q=%5Bspring-security%5D+custom+userdetailsservice
[2] https://www.ekiras.com/2016/04/authenticate-user-with-custom-user-details-service-in-spring-security.html
