### ISSUE TITLE
SEC-513: Create extended user management facility with UserDetailsManager interface.

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#770]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-513":https://jira.spring.io/browse/SEC-513?redirect=false]) said:

I had to implement something along these lines using LDAP for a client recently and thought it would make sense to add this kind of facility to Acegi since it's quite a commonly requested feature and is reasonably straightforward to achieve by extending existing interfaces and classes. The interface extends UserDetailsService by adding methods for creating, updating and deleting users and for password changes.

**Comment by rwinch** [comment]
This issue depends on #862
This issue depends on #819
This issue is related to #533

**Comment by spring-issuemaster** [comment]
This issue depends on #862
This issue depends on #819
This issue is related to #533

**Comment by spring-issuemaster** [comment]
This issue depends on #862
This issue depends on #819
This issue is related to #533

**Comment by spring-issuemaster** [comment]
This issue depends on #862
This issue depends on #819
This issue is related to #533
