### ISSUE TITLE
SEC-516: Redirect on a POST Url for a saved request does not make much sense

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#772]
["Martino Piccinato":https://jira.spring.io/secure/ViewProfile.jspa?name=martino.piccinato](Migrated from ["SEC-516":https://jira.spring.io/browse/SEC-516?redirect=false]) said:

Default behaviour for CasProcessingFilter is to always redirect to the URL generated SavedRequest. found in session, In my opinion this make sense just if the saved original request is a GET method request.

Imagine a session that expire while a user is filling in a POST form, after having finished to fill in the form the user will press submit generating a POST request, as the session has expired he's not authenticated anymore so his POST request will be saved in ACEGI_SAVED_REQUEST session parameter and he'll be redirect to cas login page, on successfull authentication, after ticket check, he'll be redirected again to a URL generated from the previously saved POST request but this make no sense in general because it's very likely that important parameters are encoded in the body of the request that cannot be used in a redirect.

In my opinion the best approach would be toredirect on URL generated by SavedRequest just on GET SavedRequest and to redirect to "defaultTargetUrl" on non GET SavedRequest, I really can't imagine a situation where redirecting to a POST SavedRequest URL would be needed. 
Neverthless I understand this breaks a default behaviour the filter is having now so I think it could be just added a boolean switch to choose among the two behaviours. I include some code I'm using in my application below.

Another, more flexible, solution would be to have a TargetResolver interface/bean used by AbstractProcessingFilter with a single method

public String determineTargetUrl(SavedRequest savedRequest);

I think there might be other cases for using this.
Also: I don't think  "obtainFullUrl" should be static and maybe giving access to SavedRequest through at least a protected method wouldn't be bad.
If you think some of these ideas are valuable I can provide better code for this and/or patch against current acegi version.

AbstractProcessingFilter:

```
private static String METHOD_GET = "GET";

/** Contains an optional URL to redirect invalid saved request */
private String invalidSavedRequestTargetUrl;

/** Whether or not to redirect just on GET SavedRequest , default to false */
private boolean justUseGetSavedRequests = false;

protected String determineTargetUrl(HttpServletRequest request) {

    String targetUrl = null;

     if (alwaysUseDefaultTargetUrl) {
         targetUrl = getDefaultTargetUrl();
     }  else {
          SavedRequest savedRequest = (SavedRequest) request.getSession()
                                                      .getAttribute(AbstractProcessingFilter.ACEGI_SAVED_REQUEST_KEY);


      if (justUseGetSavedRequests && !savedRequest.getMethod().equals(METHOD_GET)) {
        if (invalidSavedRequestTargetUrl != null) {
            targetUrl = invalidSavedRequestTargetUrl;
        } else {
            targetUrl = getDefaultTargetUrl();
        }
    }
    }

    return targetUrl;
}

/**
 *  Gets the URL to redirect when a non GET method SavedRequest is found in session, used if 
    *   #getJustUseGetSavedRequests() returns <code>true</code>
 *  
 * @return the invalidSavedRequestTargetUrl
 */
public String getInvalidSavedRequestTargetUrl() {
    return invalidSavedRequestTargetUrl;
}

/**
 * Sets the URL to redirect when a non GET method SavedRequest is found in session, used if 
    *   #getJustUseGetSavedRequests() returns <code>true</code>
 * 
 * @param invalidSavedRequestTargetUrl the invalidSavedRequestTargetUrl to set
 */
public void setInvalidSavedRequestTargetUrl(String invalidaRequestTargetURL) {
    this.invalidSavedRequestTargetUrl = invalidaRequestTargetURL;
}

/**
 *  Gets whether or not to redirect on SavedRequest URL in case of non GET SavedRequest
 *  
 * @return the invalidSavedRequestTargetUrl
 */
public boolean getJustUseGetSavedRequests() {
    return justUseGetSavedRequests;
}

/**
 * Sets whether or not to redirect to SavedRequest URL in case of non GET SavedRequest
 * 
 * @param justUseGetSavedRequest <code>true</code> if the filter has to redirect just on 
     * GET method <code>SavedRequest</code>, <code>false</code> otherwise.
 */
public void setjustUseGetSavedRequests(boolean justUseGetSavedRequest) {
    this.justUseGetSavedRequests = justUseGetSavedRequest;
}
```

**Comment by rwinch** [comment]
This issue is related to #752
This issue is related to #755

**Comment by spring-issuemaster** [comment]
This issue is related to #752
This issue is related to #755

**Comment by spring-issuemaster** [comment]
This issue is related to #752
This issue is related to #755

**Comment by spring-issuemaster** [comment]
This issue is related to #752
This issue is related to #755
