### ISSUE TITLE
Upgrade com.nimbusds:nimbus-jose-jwt dependency

### ISSUE THREAD

**Issue by elefeint** [spring-projects/spring-security#7720]
### Summary

Upgrade `com.nimbusds:nimbus-jose-jwt` to version 7.9 or higher (it is currently [7.8.1](https://github.com/spring-projects/spring-security/blob/bc2aedac69d30585e18f6f761ae363223d8571fc/gradle/dependency-management.gradle#L59), which seems to be the final bugfix version for 7.8 branch)

There is a medium severity validation security vulnerability ([snyk](https://app.snyk.io/vuln/SNYK-JAVA-COMNIMBUSDS-536068), [blog](https://connect2id.com/blog/nimbus-jose-jwt-7-9)) on lower versions.

**Comment by fhanik** [comment]
I've requested input from @jzheaux. I remember there may be some incompatibilities that need to be resolved prior to fixing this.

**Comment by MichaelVetter** [comment]
The security vulnerability is fixed in version 7.8.1 (see #7570) but it is helpful that you upgraded the version.

**Comment by jzheaux** [comment]
Correct, @MichaelVetter, because Spring Security was on 7.8.1, there's no security issue. It's always the goal to upgrade to the latest possible, though, so this was a good ticket either way.

**Comment by elefeint** [comment]
Ah, so it was a false positive because CVE did not get updated. Good to know, thanks!
