### ISSUE TITLE
Saml2 Xml Sample

### ISSUE THREAD

**Issue by csyperski** [spring-projects/spring-security#7749]
### Summary

There are many of us migrating away form the spring-security-saml as it is no longer maintained, and I would really like to see an XML based sample of how to get up and running with the Saml Sp implementation that is now part of 5.2.0+.  I believe a sample XML project would help many of us make the transition.  

### Actual Behavior

There currently aren't any xml-based samples using Saml.

### Expected Behavior

I'd love to see an example, to help me get up and running with Saml that uses XML config (not just SpringBoot).  

### Version

5.2.0+

Thanks for your consideration!

**Comment by amergey** [comment]
Is there any way to use xml configuration for saml ? 
currently sample are showing spring boot way of configuring saml like this
```
@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
				
				.oauth2Login(Customizer.withDefaults())
				.saml2Login(customizer -> customizer
						.authenticationManager(configuredSaml2AuthManager()));
}
```
What is the equivalent with xml config ? 
I can find it for auth2 but not for saml2

```
<http>
   <oauth2-login/>
<!-- how can we configure saml ? -->
</http>
```

**Comment by jzheaux** [comment]
Hi, @amergey. There is no support for `<saml2-login>`, yet. 

Would you be able to file a ticket, if that's a feature that you need? Since XML support won't necessarily expose all the things that `saml2Login()` does, it would be helpful for you to describe the specific things you need to configure in XML.

**Comment by amergey** [comment]
Hi, I have filed https://github.com/spring-projects/spring-security/issues/9012

**Comment by marcusdacoregio** [comment]
Closing in favor of https://github.com/spring-projects/spring-security/issues/9012
