### ISSUE TITLE
JdbcUserDetailsManager does not implements UserDetailsPasswordService

### ISSUE THREAD

**Issue by hbourada** [spring-projects/spring-security#7750]
### Summary
`JdbcUserDetailsManager` does not implements `UserDetailsPasswordService` like `InMemoryUserDetailsManager`

### Actual Behavior
We ca not upgrade password encoding when using  `JdbcUserDetailsManager`

### Expected Behavior
JdbcUserDetailsManager is not easy to extends because sql fields are `private` as `createUserSql`  and not getters for them. 

### Version
5.2

**Comment by jzheaux** [comment]
Thanks for the report, @hbourada. 

It does make sense to implement `UserDetailsPasswordService` for upgrading passwords in a database; however, this is risky specifically for `JdbcUserDetailsManager` from a backward compatibility standpoint. If `JdbcUserDetailsManager` were to implement `UserDetailsPasswordService`, it would break applications whose `password` column was too narrow to accept the newly encoded password.

You might consider something like:

```java
@Component
public class MyJdbcPasswordService implements UserDetailsPasswordService {
    private final JdbcUserDetailsManager jdbc;

    public MyJdbcPasswordService(JdbcUserDetailsManager jdbc) {
        this.jdbc = jdbc;
    }

    public UserDetails updatePassword(UserDetails user, String newPassword) {
        UserDetails newUser = new User(user.getUsername(), newPassword, ...
        this.jdbc.updateUser(newUser);
        return newUser;
    }
}
```

And then exposing your `JdbcUserDetailsManager` instance as a bean.

Will this approach work for you?

**Comment by hbourada** [comment]
Thank's for your response
The same problem occurs with the suggested code if password column is too narrow to accept the new encoded password.
We can make a defensive approach if we can't update to new password and log a warning to tell user that UserDetailsPasswordService was not able to update password and let previous one.
Regards

**Comment by jzheaux** [comment]
@hbourada Agreed that the provided code doesn't work if the column is too narrow; that's why it's not going to be added into Spring Security. 

If your password column is too narrow, I'd recommend widening it in order to accept the encoded value. Either way, it sounds like you've got a solution, but feel free to continue posting to the ticket if you feel like there is more to discuss.

**Comment by hbourada** [comment]
I didn't saw the retro-compatibility problem, for that we can have an enabled flag which defaulted to false which give change ti consumer to activate this option.
I attach a version of modified version of `JdbcUserDetailsManager`
[JdbcUserDetailsManager.txt](https://github.com/spring-projects/spring-security/files/4482565/JdbcUserDetailsManager.txt)

**Comment by jzheaux** [comment]
Thanks for sharing, @hbourada, though I guess I'm not quite understanding. While a flag may be an option, I don't see this as an improvement over delegation.

For example, a simpler rendition of the earlier snippet is:

```java
@Bean 
UserDetailsPasswordService userDetailsPasswordService(UserDetailsManager manager) {
    return (user, newPassword) -> {
        UserDetails newUser = new User(user.getUsername(), newPassword, ...
        manager.updateUser(newUser);
        return newUser;
    }
}
```

Though a flag would be fewer lines of code, compare this to the fact that with a flag, the developer would need to know that, even though `JdbcUserDetailsService` implements `UserDetailsPasswordService`, they need to also set a flag for it to actually work. This is scary when considering the fact that if the developer forgets to set the flag, passwords will silently not get updated.

**Comment by hbourada** [comment]
You said:
_It does make sense to implement UserDetailsPasswordService for upgrading passwords in a database; however, this is risky specifically for JdbcUserDetailsManager from a backward compatibility standpoint._
and:
_Though a flag would be fewer lines of code, compare this to the fact that with a flag, the developer would need to know that, even though JdbcUserDetailsService implements UserDetailsPasswordService, they need to also set a flag for it to actually work_
The flag is for retro-compatibility to not break old projects.
As`InMemoryUserDetailsManager` implements `UserDetailsPasswordService` it's more coherent to do it also for  `JdbcUserDetailsService` IMHO.

**Comment by jzheaux** [comment]
Agreed, @hbourada, that the flag addresses the compatibility issue. It raises security issues, though, which is why I don't think it should be added. Thank you for the suggestion, though.

**Comment by jzheaux** [comment]
I think something else might be going on with your code, @onlinebaba. `updateUser` first deletes all authorities associated with a user and then reinserts them. Perhaps the deletes are failing first. 

You might consider asking your question on [StackOverflow](https://stackoverflow.com) for increased visibility.

**Comment by jzheaux** [comment]
I'm open to the idea of deprecation, @geirhe. Maybe we call it `JdbcUserPasswordDetailsManager`. Would you consider submitting a new PR that introduces the new class?
