### ISSUE TITLE
Migrate from spring-security-oauth

### ISSUE THREAD

**Issue by huehnerlady** [spring-projects/spring-security#7790]
Hi,

I want to migrate from Spring-security-oauth to spring security as the oauth lib is deprecated.
I found this [Migration Guide](https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide)

Unfortunately this is not sufficient for me to understand the migration process of my code, I could not really find examples either.
My [stackoverflow question](https://stackoverflow.com/questions/59426750/deprecate-spring-security-oauth-as-a-client) did not receive any response either.

Where can I find help to migrate to the newest oauth version?

**Comment by huehnerlady** [comment]
What I am actually trying to achieve is using something like described [here](https://github.com/spring-projects/spring-security-oauth/issues/311) with the new spring-security mechanism. 

Unfortunately I am stuck and do not understand how to change the code to accommodate this.

**Comment by jzheaux** [comment]
@huehnerlady I've responded on StackOverflow. Let's go ahead and move the rest of our conversation over there.
