### ISSUE TITLE
DefaultAuthenticationEventPublisher should allow configuring a default event

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#7825]
`DefaultAuthenticationEventPublisher` will drop any exceptions that it doesn't have mapped. This means that an application needs to use `setAdditionalExceptionMappings` to provide any mappings not provided by default.

It would be nice to be able to configure a default event that gets fired for any unmapped exceptions:

```java
DefaultAuthenticationEventPublisher publisher = new DefaultAuthenticationEventPublisher();
publisher.setDefaultAuthenticationFailureEvent(AuthenticationFailureBadCredentialsEvent.class);
```

With the above configuration, an `AuthenticationFailureBadCredentialsEvent` would be fired in the event that the published exception doesn't map to anything in `DefaultAuthenticationEventPublisher`s mappings.

`DefaultAuthenticationEventPublisher` would change at around this point:

```java
if (constructor != null) {
    try {
        event = constructor.newInstance(exception, authentication);
    } catch // ...
}
```

Where the event gets constructed.

**Comment by zeeshanadnan** [comment]
@jzheaux if nobody is currently working on this can i work on this for my first contribution?

**Comment by jzheaux** [comment]
Yes, sir! It's yours.
