### ISSUE TITLE
Introduce OAuth2Authorization success/failure handlers

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#7840]
This ticket addresses the Servlet implementation of #7699

**Comment by philsttr** [comment]
@jgrandja Feel free to tag me as a reviewer on the implementation if you want an extra set of eyes.

**Comment by jgrandja** [comment]
@philsttr I just submitted the PR for the Servlet implementation #7986. I'm planning on merging this by end of next week. If you have time to review that would be great. No worries if you're busy next week.

**Comment by jgrandja** [comment]
@philsttr I forgot to mention...when I was implementing the Servlet version, I noticed a code path that may not be valid. This specific [test](https://github.com/spring-projects/spring-security/blob/e5fca61810650db1b204f4d8137e8bacbf7e1fbf/oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/web/reactive/function/client/ServerOAuth2AuthorizedClientExchangeFilterFunctionTests.java#L638) throws an `OAuth2AuthorizationException` directly from the `ExchangeFunction`, which ultimately branches into this [code path](https://github.com/spring-projects/spring-security/blob/e5fca61810650db1b204f4d8137e8bacbf7e1fbf/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/reactive/function/client/ServerOAuth2AuthorizedClientExchangeFilterFunction.java#L626). I'm not sure this scenario could happen. Maybe I'm missing something that you are seeing? Could you look at this again and provide some clarification?

**Comment by philsttr** [comment]
That scenario will not happen by the classes and functionality _provided by spring security out-of-the-box_.

I specifically added that code path to allow downstream filters to be able to inspect a resource server response and throw an `OAuth2AuthorizationException` to trigger the logic in the upstream filter function.  This could be utilized by applications talking to a non-compliant resource server.  For example, maybe their resource server returns a 400 status... or maybe it's an rpc-style server that returns an error in the response body.

**Comment by jgrandja** [comment]
Gotchya! That makes sense. Ok I will add it back into the Servlet impl.

**Comment by jgrandja** [comment]
@philsttr There were some package tangles in the Servlet and Reactive implementations. I resolved it via c8cc971. When you get a chance, take a look at the changes and let me know if you have any concerns. Thanks.

**Comment by philsttr** [comment]
@jgrandja LGTM!
