### ISSUE TITLE
Consider adding JwtClaimValidator

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#7860]
`JwtClaimValidator` could be a nice generalization of `JwtIssuerValidator`. Something like:

```java
public JwtClaimValidator(String claim, Predicate<T> test)
```
Where `claim` is the name of the claim to validate, `test` is the test to perform, and `T` is the claim value's type.

**Comment by zeeshanadnan** [comment]
If no one is working on it i would like to work on it.

**Comment by jzheaux** [comment]
@zeeshanadnan sounds great! It's yours.
