### ISSUE TITLE
Broken Link in Documentation

### ISSUE THREAD

**Issue by sulimanalruz** [spring-projects/spring-security#7868]
This page

https://docs.spring.io/spring-security/site/docs/4.2.13.RELEASE/apidocs/org/springframework/security/config/annotation/web/socket/AbstractSecurityWebSocketMessageBrokerConfigurer.html

Contains a broken link to 

https://docs.spring.io/spring/docs/3.2.x/javadoc-api/org/springframework/web/socket.config.annotation.AbstractWebSocketMessageBrokerConfigurer.html

I believe it should be

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/socket/config/annotation/AbstractWebSocketMessageBrokerConfigurer.html

**Comment by jzheaux** [comment]
Since the 4.x series is no longer supported, I'm going to close this ticket.

That said, the links are no longer present at all in the supported Javadocs, so I've created https://github.com/spring-projects/spring-security/issues/10954 to address that.
