### ISSUE TITLE
Error in WebSecurityConfigurer Javadoc

### ISSUE THREAD

**Issue by XSun771** [spring-projects/spring-security#7876]
in this javadoc
[href](https://docs.spring.io/spring-security/site/docs/4.0.x/apidocs/org/springframework/security/config/annotation/web/WebSecurityConfigurer.html)

> Allows customization to the WebSecurity. In most instances users will use EnableWebSecurity and a create Configuration that extends WebSecurityConfigurerAdapter which will automatically be applied to the WebSecurity by the EnableWebSecurity annotation.

"and a create Configuration"  is there a error in usage of create?

it's difficult for me to understant... I am not a native English speaker... and I looked up "create" and  can find only verb meaning. Obviously, it's impossible to use a verb in that sentence...

Thanks.

**Comment by eleftherias** [comment]
Thanks for the report @XSun771! 
You are correct that this was a grammatical mistake.
It has been fixed in 171e0d0.
