### ISSUE TITLE
SEC-528: Support reCAPTCHA

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#789]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-528":https://jira.spring.io/browse/SEC-528?redirect=false]) said:

reCAPTCHA is a web service that provides CAPTCHA services and concurrently digitizes old books for Internet Archive. We should support it in addition to JCAPTCHA. A Java integration is available at http://tanesha.net/projects/recaptcha4j/.

**Comment by rwinch** [comment]
This issue depends on #976

**Comment by spring-issuemaster** [comment]
This issue depends on #976

**Comment by spring-issuemaster** [comment]
This issue depends on #976

**Comment by spring-issuemaster** [comment]
This issue depends on #976
