### ISSUE TITLE
SEC-532: ACL Improvements

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#793]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-532":https://jira.spring.io/browse/SEC-532?redirect=false]) said:

General enhancements to ACL functionality.

**Comment by rwinch** [comment]
This issue depends on #791
This issue depends on #807
This issue depends on #863
This issue depends on #915
This issue depends on #929
This issue depends on #788
This issue depends on #833
This issue depends on #850
This issue depends on #743

**Comment by spring-issuemaster** [comment]
This issue depends on #791
This issue depends on #807
This issue depends on #863
This issue depends on #915
This issue depends on #929
This issue depends on #788
This issue depends on #833
This issue depends on #850
This issue depends on #743

**Comment by spring-issuemaster** [comment]
This issue depends on #791
This issue depends on #807
This issue depends on #863
This issue depends on #915
This issue depends on #929
This issue depends on #788
This issue depends on #833
This issue depends on #850
This issue depends on #743

**Comment by spring-issuemaster** [comment]
This issue depends on #791
This issue depends on #807
This issue depends on #863
This issue depends on #915
This issue depends on #929
This issue depends on #788
This issue depends on #833
This issue depends on #850
This issue depends on #743
