### ISSUE TITLE
site: typo in snippet code 'jwtAuthenticationConveter' -> 'jwtAuthenticationConverter'

### ISSUE THREAD

**Issue by amarkevich** [spring-projects/spring-security#7969]
### Summary

Section "Extracting Authorities Manually"[1]

1. https://docs.spring.io/spring-security/site/docs/current/reference/html/oauth2.html#oauth2resourceserver-jwt-authorization-extraction

### Actual Behavior

`return jwtAuthenticationConveter;`

### Expected Behavior

`return jwtAuthenticationConverter;`

### Configuration

none

### Version

current

**Comment by jzheaux** [comment]
Thanks, @amarkevich, would you be interested in submitting a PR to correct the typo?

**Comment by amarkevich** [comment]
@jzheaux I can but unable to find the sources

**Comment by jzheaux** [comment]
Thanks for your willingness, @amarkevich. I think the reason you couldn't find it is that this has already been fixed in `master` via 0295b51e78302eed1fe37ffeb763e8afce0fb1ac and just not yet backported to `5.2.x`. 

I've just now backported via 5ce0ce3f3888ec7a6eab730e59a8c9a3f48c1d08.
