### ISSUE TITLE
SEC-536: X509AuthenticationProvider (and CasAuthenticationProvider) do not check UserDetails status (locked, enabled etc)

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#797]
["Gerr Magnus Mes":https://jira.spring.io/secure/ViewProfile.jspa?name=gerr_mes](Migrated from ["SEC-536":https://jira.spring.io/browse/SEC-536?redirect=false]) said:

X509AuthenticationProvider do not check UserDetails.isAccountNonLocked, UserDetails.isEnabled(), UserDetails.isAccountNonExpired, UserDetails.isCredentialsNonExpired . Why ?

**Comment by rwinch** [comment]
This issue is related to #798

**Comment by spring-issuemaster** [comment]
This issue is related to #798

**Comment by spring-issuemaster** [comment]
This issue is related to #798

**Comment by spring-issuemaster** [comment]
This issue is related to #798
