### ISSUE TITLE
Basic auth header without user results in exception

### ISSUE THREAD

**Issue by PatrikSteuer** [spring-projects/spring-security#7976]
### Summary
When providing a basic auth header without any user/password combination an `java.lang.StringIndexOutOfBoundsException: String index out of range: -1` is thrown.

### Actual Behavior
When a Basic Auth Web Request is executed with following header: `Authorization: Basic ` an index out of range exception is caused. By these [lines within the BasicAuthenticationConverter](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/authentication/www/BasicAuthenticationConverter.java#L86-L90)

This exception causes an http 500 respones.

### Expected Behavior
Expected would be a http 401 as result of the original web request 

### Version
spring-security: 5.2.2.RELEASE

**Comment by zeeshanadnan** [comment]
@eleftherias if no one is working on this i would like to take it.

**Comment by eleftherias** [comment]
Thanks @zeeshanadnan! The issue is yours.
