### ISSUE TITLE
SEC-543: Review concurrency issues in SessionRegistryImpl

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#802]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-543":https://jira.spring.io/browse/SEC-543?redirect=false]) said:

See SEC-484.

**Comment by rwinch** [comment]
This issue is related to #745

**Comment by spring-issuemaster** [comment]
This issue is related to #745

**Comment by spring-issuemaster** [comment]
This issue is related to #745

**Comment by spring-issuemaster** [comment]
This issue is related to #745
