### ISSUE TITLE
Nimbus Opaque Token Introspectors should not use HTTPResponse

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#8024]
The 7.x series of Nimbus changes `javax.mail` to an optional dependency.

Due to methods like this inside Nimbus's `HTTPMessage`:

```java
public javax.mail.internet.ContentType getContentType() {
    // ...
}
```

Different runtimes [may fail to load this class](https://github.com/spring-projects/spring-security/issues/7641) without also specifying the `javax.mail` dependency.

It seems a bit odd to include `javax.mail` as a dependency for `oauth2-resource-server`, and so it would be better to not have to add it. This is achievable with [one change in Nimbus](https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/issues/291/javaxmail-doesnt-seem-to-be-truly-optional) and one change in Spring Security, which is to stop using Nimbus's `HTTPResponse`.

**Comment by jgrandja** [comment]
Related #7994 #8007

**Comment by jzheaux** [comment]
Looking into this a little deeper, while the test suite does pass with the described changes, any time a class is referred to in a method body or signature, even if that method isn't invoked, the classloader may still load that class.

Given that, `JSONObjectUtils` also refers to `javax.mail` classes. This class is used by many other classes in Nimbus, which will make it tricky for Spring Security to avoid its usage.

As such, I'm going to close this ticket since it can't resolve the classloading concern completely.
