### ISSUE TITLE
Tab switching does not work in documentation code samples

### ISSUE THREAD

**Issue by eleftherias** [spring-projects/spring-security#8025]
### Summary

In the documentation, we show code samples and allow the user to choose which language they want to see them in (Java, XML, Kotlin).

Some of our code samples are only available in two languages, for example Java and Kotlin, while others are available in all three languages.

The plugin we are using to switch between samples does not work (clicking the language toggle does nothing) in this case. 
It is expecting all samples to have the same number of language options.

**Comment by eleftherias** [comment]
Depends on https://github.com/spring-io/spring-asciidoctor-extensions/pull/45

**Comment by rwinch** [comment]
Closed via gh-8058
