### ISSUE TITLE
Add request cache that uses cookie

### ISSUE THREAD

**Issue by eleftherias** [spring-projects/spring-security#8034]
### Summary

Currently we have the ability to store a user's initial request using `HttpSessionRequestCache`. This causes the `HttpSession` to be read on every request.
We should provide an alternative that stores the initial request in a cookie instead of in the `HttpSession`.

**Comment by zeeshanadnan** [comment]
Hi @eleftherias hope you are doing well in these tough times. If no one is working on this issue i would like to give it a try.

**Comment by eleftherias** [comment]
Thanks @zeeshanadnan! The issue is yours.

**Comment by zeeshanadnan** [comment]
@eleftherias sorry for being late. I have submitted a pull request.
