### ISSUE TITLE
SEC-547: acls BasicLookupStrategy user too many (> 1) databasse connections

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#807]
["Simon van der Sluis":https://jira.spring.io/secure/ViewProfile.jspa?name=svanders](Migrated from ["SEC-547":https://jira.spring.io/browse/SEC-547?redirect=false]) said:

BasicLookupStrategy opens an additional connection to the database for each ACL level of ACL parent that needs to be retrieved from the database.

The error is in the private inner class ProcessResultSet (implements ResultSetExtractor) in the method extractData(ResultSet), at the end of the method

// Lookup parents, adding Acls (with StubAclParents) to "acl" map
if (parentIdsToLookup.size() > 0) {
    lookupPrimaryKeys(acls, parentIdsToLookup, sids);
}

lookupPrimaryKeys(acls, parentIdsToLookup, sids); creates another ProcessResultSet which as per Spring JDBC template classes grabs another connection to the database.  In a round about way this recursively uses one database connection per ACL -> parent ACL relationship to be looked up.

In our case we have some test data where we have an ACL with a hierarchy of 16 parents, so for each level of the hierarchy a new connection to the DB is used  Our test set up had only 10 connections in the pool, which is how we found it.

I'm currently trying to fix this, as it's causing us problems.  As part of the fix I'm writing some unit tests for BasicLookupStrategy (as there currently are none), not sure if I'll be able to get DB connection checking usage into the unit tests, but will investigate.

I'll add my fixes to this Issue when they are ready.

This issue should probably be added to 
http://opensource.atlassian.com/projects/spring/browse/SEC-532

**Comment by sumanmitra** [comment]
I know this issue is closed but I am having connection leak when using Hikari cp. I posted the details in stackoverflow. Can you guys please have a look?
https://stackoverflow.com/questions/64695847/spring-security-acl-connection-leak
