### ISSUE TITLE
SEC-546: Change ProviderManager to prevent hiding LockedExceptions when using multiple providers

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#808]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-546":https://jira.spring.io/browse/SEC-546?redirect=false]) said:

Provider manager doesn't currently differentiate between different types of exceptions thrown when iterating through the list of providers. If one throws a LockedException then it will proceed to the next provider and the LockedException will not be the last exception thrown. It would be more logical if it didn't try further providers at this point. The same applies to other account status exceptions (expired etc) and also concurrent login exceptions.

**Comment by rwinch** [comment]
This issue relates to #2166

**Comment by spring-issuemaster** [comment]
This issue relates to #2166

**Comment by spring-issuemaster** [comment]
This issue relates to #2166

**Comment by spring-issuemaster** [comment]
This issue relates to #2166
