### ISSUE TITLE
Support Resource resolution for jwk-set-uri

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-security#8092]
The new 5.3.0 release includes the very useful Boot property for setting a specific JWT key in `public-key-location`. However, this has a hard-coded assumption of an X509-format pubkey. The `jwk-set-uri` property points to a JWK Set, but it is unconditionally handed off to a `RestTemplate` for resolution.

It would be helpful if the JWK Set could be specified using `classpath:my.jwk` so that for development or testing a local JWK JSON object could be used out of local resources. The logic in `NimbusJwtDecoder` (particularly around `RestOperationsResourceRetriever`) looks like it may be adaptable to supporting Resource paths, or conversely the `Resource#toURL()` could be processed at launch and fed to it.

Does either of these approaches sound like a practical option for allowing "canned" JWK use for testing?

**Comment by jzheaux** [comment]
@chrylis it's an interesting idea, thanks for sharing

> It would be helpful if the JWK Set could be specified using classpath:my.jwk so that for development or testing a local JWK JSON object could be used out of local resources.

I'm a little hesitant to add something to the public API that would only be for testing or for local use. 

For testing, it seems like it would be sufficient to mock the `JwtDecoder` or the `RestOperations`.

For development, you can use `new NimbusJwtDecoder(JWTProcessor)`, probably providing an `ImmutableJWKSet` instance when configuring the `ConfigurableJWTProcessor`.

> The logic in NimbusJwtDecoder (particularly around RestOperationsResourceRetriever) looks like it may be adaptable to supporting Resource paths, or conversely the Resource#toURL() could be processed at launch and fed to it.

`RestOperationsResourceRetriever` is intended for use with a `RestOperations` whose primary implementation, `RestTemplate`, states:

> Synchronous client to perform HTTP requests

So, I feel like adapting that to pull from a file system would be a little confusing for developers.

Potentially, something like `NimbusJwtDecoder.withJwkSetLocation` and a separate builder could be added, though, again I'd prefer not to add it until there is a clear production need.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by bossqone** [comment]
I was able to solve this issue with tips mentioned above. Maybe it will be useful for someone else as well.
```java
@Bean
public JwtDecoder jwtDecoder(final OAuth2ResourceServerProperties properties) throws Exception {
	// this workaround is needed because spring boot doesn't support loading jwks from classpath/file (only http/https)
	// using standard 'spring.security.oauth2.resourceserver.jwt.jwk-set-uri' configuration property
	// relevant issue: https://github.com/spring-projects/spring-security/issues/8092
	final String issuerUri = properties.getJwt().getIssuerUri();
	final String jwkSetUri = properties.getJwt().getJwkSetUri();
	final JWSAlgorithm jwsAlgorithm = JWSAlgorithm.parse(properties.getJwt().getJwsAlgorithm());

	final File file = ResourceUtils.getFile(jwkSetUri);
	final JWKSet jwkSet = JWKSet.load(file);
	final JWKSource<SecurityContext> jwkSource = new ImmutableJWKSet<>(jwkSet);
	final ConfigurableJWTProcessor<SecurityContext> jwtProcessor = new DefaultJWTProcessor<>();
	final JWSKeySelector<SecurityContext> jwsKeySelector = new JWSVerificationKeySelector<>(jwsAlgorithm, jwkSource);
	jwtProcessor.setJWSKeySelector(jwsKeySelector);

	// Spring Security validates the claim set independent from Nimbus
	// copied from 'org.springframework.security.oauth2.jwt.NimbusJwtDecoder.JwkSetUriJwtDecoderBuilder.processor'
	jwtProcessor.setJWTClaimsSetVerifier((claims, context) -> {
	});

	final NimbusJwtDecoder nimbusJwtDecoder = new NimbusJwtDecoder(jwtProcessor);
	nimbusJwtDecoder.setJwtValidator(JwtValidators.createDefaultWithIssuer(issuerUri));

	return nimbusJwtDecoder;
}
```
