### ISSUE TITLE
Security Filter ConcurrentSessionFilter's registration is confusing

### ISSUE THREAD

**Issue by ghusta** [spring-projects/spring-security#8105]
### Summary

It's not very clear in which order the security filter `ConcurrentSessionFilter` is registered.

### Actual Behavior

The different security filters are registered in `org.springframework.security.config.annotation.web.builders.FilterComparator`, each with a different order.

But `ConcurrentSessionFilter` is registered **3 times**. As the filters are stored in a Map, only the last one is retained however.

Also in the documentation, at [Security Filters](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#servlet-security-filters) it is written twice, which is not possible.

There's also a mistake in the javadoc for _org.springframework.security.config.annotation.web.HttpSecurityBuilder#addFilter_

### Expected Behavior

`ConcurrentSessionFilter` should only be registered once.

### Version

All versions including 5.3

**Comment by jzheaux** [comment]
Good catch, @ghusta. I've removed the ambiguity and cleaned up the documentation.

**Comment by ghusta** [comment]
Thanks !
