### ISSUE TITLE
Document description error

### ISSUE THREAD

**Issue by bergturing** [spring-projects/spring-security#8119]
### Summary
![image](https://user-images.githubusercontent.com/26686731/76768712-5c742800-67d6-11ea-8204-c041f8758f7b.png)
Here should be BasicAuthenticationFilter

### Version
5.3.1.BUILD-SNAPSHOT

**Comment by rwinch** [comment]
Thanks for the report @beamerblvd Would you be interested in submitting a PR?

**Comment by dadikovi** [comment]
Hi! This looks like an ideal very-first PR for me! 
I assume all the information I need for it is in the code of conduct and the contribution guide...
