### ISSUE TITLE
SEC-551: Use JDK 1.4 for regular expressions

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#812]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-551":https://jira.spring.io/browse/SEC-551?redirect=false]) said:

This will allow the ORO dependency to be removed from the project.

**Comment by rwinch** [comment]
This issue depends on #811

**Comment by spring-issuemaster** [comment]
This issue depends on #811

**Comment by spring-issuemaster** [comment]
This issue depends on #811

**Comment by spring-issuemaster** [comment]
This issue depends on #811
