### ISSUE TITLE
SEC-552: Refactor authorities populator interfaces and implementations

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#813]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-552":https://jira.spring.io/browse/SEC-552?redirect=false]) said:

We should look at reducing duplication in authorities populator interfaces. See SEC-133, for example. The portlet module has it's own versions. CAS, X509 and Ldap all have different authorities populators which are essentially doing the same job.

**Comment by rwinch** [comment]
This issue is related to #837

**Comment by spring-issuemaster** [comment]
This issue is related to #837

**Comment by spring-issuemaster** [comment]
This issue is related to #837

**Comment by spring-issuemaster** [comment]
This issue is related to #837
