### ISSUE TITLE
Make EnableReactiveMethodSecurity compatible with Kotlin Coroutines

### ISSUE THREAD

**Issue by TonCherAmi** [spring-projects/spring-security#8143]
Current implementation of `PrePostAdviceReactiveMethodInterceptor` makes it impossible to use `@Pre/PostAuthorize` with suspending functions:

```java
// PrePostAdviceReactiveMethodInterceptor::invoke
if (!Publisher.class.isAssignableFrom(returnType)) {
    throw new IllegalStateException("The returnType " + returnType + " on " + method + " must return an instance of org.reactivestreams.Publisher (i.e. Mono / Flux) in order to support Reactor Context");
}
```

This may be related to spring-projects/spring-framework#22462

Spring boot version: `2.2.1.RELEASE`

**Comment by rwinch** [comment]
Could you please provide a complete sample?

**Comment by TonCherAmi** [comment]
@rwinch [here you go](https://github.com/TonCherAmi/spring-security-coroutine-demo/tree/master/src/main/kotlin/com/example/demo).

Upon making a request,
```sh
curl -X POST -v -u admin:qwerty localhost:8080/api/test -d "xzcvxzcv"
```

an exception is thrown:
```json
{
  "timestamp": "2020-03-18T19:57:41.277+0000",
  "path": "/api/test",
  "status": 500,
  "error": "Internal Server Error",
  "message": "The returnType class java.lang.Object on public java.lang.Object com.example.demo.handlers.TestHandler.test(org.springframework.web.reactive.function.server.ServerRequest,kotlin.coroutines.Continuation) must return an instance of org.reactivestreams.Publisher (i.e. Mono / Flux) in order to support Reactor Context",
  "requestId": "38010f7a-4"
}
```

**Comment by rwinch** [comment]
Thanks for the detailed sample. I don't think this can work at the moment because the `ReactiveSecurityContextHolder` leverages Reactor's [Context](https://projectreactor.io/docs/core/release/reference/#context) which as far as I know requires the return types to be `Mono` or `Flux` at this point. Any method that breaks this chain would mean we would not have access to the `Authentication` and cannot perform any security checks.

@simonbasle Can you comment if Reactor's Context works with (or could work with) Kotlin Coroutines?

**Comment by simonbasle** [comment]
IIRC Kotlin Coroutines' have their own concept of context which can be bridged over to Reactor's `Context` when adapting a `Flux`/`Mono` (and should be when using the official bridges IIRC, if that is still a thing). maybe @sdeleuze will have more insight into that.

**Comment by TonCherAmi** [comment]
Interop between coroutine context and Reactor context should be possible according to this issue kotlin/kotlinx.coroutines#284

**Comment by rwinch** [comment]
Thanks for the additional details @simonbasle and @TonCherAmi We will look into this one once https://github.com/spring-projects/spring-framework/issues/22462 is addressed.

**Comment by sdeleuze** [comment]
Indeed we still need to complete the Coroutines story with AOP and annotation based security and transaction support.

@rwinch I will synchronize with you asap we make progress on this issue.

**Comment by sdeleuze** [comment]
@rwinch @eleftherias I have just merged `@Transactional` Coroutines support in Spring Framework (see https://github.com/spring-projects/spring-framework/commit/5429c7afebaa3255ea80197224023c29c7d552ec), where the changes should give you some hints about what to do on `PrePostAdviceReactiveMethodInterceptor` side.

Notice that Coroutines and Reactor conversion is context aware so this is automatically handled.

I don't think updates on Spring AOP side are needed.

**Comment by rt-works** [comment]
can still confirm the issue in the spring boot 2.4.1

**Comment by danthonywalker** [comment]
Is there a way we can workaround this by implementing our own `PrePostAdviceReactiveMethodInterceptor` or something? Or do we just have to for now do `fun endpoint(): Mono<Any> = mono {}`?

**Comment by rt-works** [comment]
> Is there a way we can workaround this by implementing our own `PrePostAdviceReactiveMethodInterceptor` or something? Or do we just have to for now do `fun endpoint(): Mono<Any> = mono {}`?

It didn't really work out, did it? For me the same exception.

**Comment by cardechr** [comment]
Has anyone found a workaround for this?

**Comment by 6oP** [comment]
> @danthonywalker
> 
> > Is there a way we can workaround this by implementing our own `PrePostAdviceReactiveMethodInterceptor` or something? Or do we just have to for now do `fun endpoint(): Mono<Any> = mono {}`?
> 
> It didn't really work out, did it? For me the same exception.

Try to  remove "suspend" from your endpoint function. mono{} starts new corotine
