### ISSUE TITLE
How Active is support on stackoverflow.com 

### ISSUE THREAD

**Issue by favetelinguis** [spring-projects/spring-security#8162]
When reaching out for support regarding spring security I get refered to stackoverflow.com. However once I ask a questions regarding spring security there it rarely get answered. What is The best support chanel? And could you please provider som support for https://stackoverflow.com/questions/60778556/testing-spring-security-oauth2login-enabled-applications-throws-illegalargumente

**Comment by jzheaux** [comment]
Good observations, @favetelinguis, and thanks for asking. This is something that we are wanting to get better at. Incidentally, I followed your link and offered an answer.

The way we are working it is a team member is "on-call" for a week. They monitor Gitter, StackOverflow, and Git, balancing that with the rest of their responsibilities. Ideally, Git is for issues and feature requests, StackOverflow is for questions, and Gitter is for discussions. We aren't perfect at that, but that's the ideal.

The reason we consider StackOverflow a better platform for help is the ability for the community to weigh in with answers. Our team's quickness to respond isn't determined by the platform, so we might as well direct you to a platform where you have the larger Spring Security community (including us) available to you.
