### ISSUE TITLE
Revamp OAuth 2.0 Login/Client reactive documentation

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#8174]
The OAuth 2.0 Login and OAuth 2.0 Client reference documentation for Reactive Applications is completely out-of-date compared to the Servlet Applications. This needs to be updated so both are in sync.

Related #8173

### Servlet Applications

[OAuth 2.0 Login](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2login)
[OAuth 2.0 Client](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2client)

### Reactive Applications

[OAuth 2.0 Login](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#webflux-oauth2-login)
[OAuth 2.0 Client](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#webflux-oauth2-client)

**Comment by densongeorge** [comment]
is this still out of date?
