### ISSUE TITLE
SEC-558: Refactor LDAP UserDetails mapping strategy

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#819]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-558":https://jira.spring.io/browse/SEC-558?redirect=false]) said:

Both the existing authentication framework and the user management code (LdapUserDetailsManager) require mapping from Ldap contexts to (and in the latter's case from) UserDetails objects. The existing code performs a single mapping to the UserDetails object and loads the authorities separately. The user management code does both in a single operation, creating the final UserDetails object. It would be preferable if these strategies were interchangeable. This could be achieved if interfaces such as LdapAuthenticator and LdapUserSearch returned DirContextAdapter (or DirContextOperations) instances rather than LdapUserDetails objects and the creation of the final object (using the mapper class) was delayed until the authorities had been loaded.

**Comment by rwinch** [comment]
This issue is related to #821
This issue is related to #877

**Comment by spring-issuemaster** [comment]
This issue is related to #821
This issue is related to #877

**Comment by spring-issuemaster** [comment]
This issue is related to #821
This issue is related to #877

**Comment by spring-issuemaster** [comment]
This issue is related to #821
This issue is related to #877
