### ISSUE TITLE
Remove empty Appendix Section from docs

### ISSUE THREAD

**Issue by asaikali** [spring-projects/spring-security#8196]
[Appendix Section](https://docs.spring.io/spring-security/site/docs/5.3.0.RELEASE/reference/html5/#appendix) in docs is empty it should be removed.

**Comment by rwinch** [comment]
This is actually a mistake in the hierarchy. The following sections should be in the Appendix:

* Security Database Schema
* The Security Namespace
* Spring Security Dependencies
* Spring Security FAQ

**Comment by akohli96** [comment]
@rwinch May I take on this one?

**Comment by jzheaux** [comment]
It's yours, @akohli96, thanks for volunteering!
