### ISSUE TITLE
Security database schema section of docs contains unrelated content

### ISSUE THREAD

**Issue by asaikali** [spring-projects/spring-security#8197]
[22. Security Database Schema](https://docs.spring.io/spring-security/site/docs/5.3.0.RELEASE/reference/html5/#appendix-schema) sections contains unrelated sections, these sections should be moved into thier own chapters.

* [The security namespace](https://docs.spring.io/spring-security/site/docs/5.3.0.RELEASE/reference/html5/#appendix-namespace) 
* [22.6. Spring Security Dependencies](https://docs.spring.io/spring-security/site/docs/5.3.0.RELEASE/reference/html5/#appendix-dependencies)
* [22.7. Spring Security FAQ](https://docs.spring.io/spring-security/site/docs/5.3.0.RELEASE/reference/html5/#appendix-faq)

**Comment by rwinch** [comment]
Thanks for the report. This is a duplicate. Please see https://github.com/spring-projects/spring-security/issues/8196#issuecomment-605076142
