### ISSUE TITLE
Spring Security FAQ should be moved into Intro Part of the docs

### ISSUE THREAD

**Issue by asaikali** [spring-projects/spring-security#8198]
[22.7. Spring Security FAQ](https://docs.spring.io/spring-security/site/docs/5.3.0.RELEASE/reference/html5/#appendix-faq) should be more easily discoverable, suggest moving it to the Introduction part of the documentation.

**Comment by rwinch** [comment]
I think we want to keep Servlet/Reactive specific FAQ in its own location. If there are things that are general, then it can be in the intro. The intro FAQ could have a link to the specific FAQ sections

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by asaikali** [comment]
Take the question at https://docs.spring.io/spring-security/site/docs/5.3.0.RELEASE/reference/html5/#appendix-faq-general-questions or https://docs.spring.io/spring-security/site/docs/5.3.0.RELEASE/reference/html5/#appendix-faq-requirements both don't have anything to do with servlets or webflux. I see Introduction part of the docs as the one that most users will look at and that it can have content that covers both webflux and servlets. FAQ's should be easy to find so putting it in the introduction helps with discoverability. Also currently there is no FAQ in the WebFlux part of the docs, if the size of the FAQ in the introduction gets too large you can then refactor into three FAQ.

**Comment by rwinch** [comment]
It seems like we agree that this should be 3 separate FAQs then?

**Comment by rwinch** [comment]
The FAQ is now part of the docs
