### ISSUE TITLE
Navigation highlighting does not match link

### ISSUE THREAD

**Issue by jxblum** [spring-projects/spring-security#8200]
In the Spring Security, `5.3.1.BUILD-SNAPSHOT` Reference Documentation, the (left) navigation highlighting is off by 1.

I am using the Google Chrome on Mac OS X.

For example, when I click on `6.3. Web — spring-security-web.jar` then `6.4 - Config - spring-security-config.jar` highlights.  If I click `Config - …` then the `LDAP - …` menu item highlights and so on.

See screen shot:

<img width="1402" alt="Screen Shot 2020-03-23 at 12 20 29 PM" src="https://user-images.githubusercontent.com/5247119/77589932-d3ca4b80-6ea9-11ea-99f5-2d815c5eea65.png">

**Comment by rwinch** [comment]
Thanks for the report. I am wondering if this is a bug in the JavaScript we use when working with sections that are short.
