### ISSUE TITLE
Allow Samples to Run Independently 

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#8216]
### Summary

Right now samples need to be imported with Spring Security. We should allow the samples to be ran independently. The sample should look just like a user would use for their own project (i.e. no strange Gradle plugins). We should also ensure we run our integration tests against the samples that are using the current source. We could potentially do this using an init.gradle that points to a local deployment of Spring Security's jars.

**Comment by jzheaux** [comment]
Closed in favor of #8217
