### ISSUE TITLE
SEC-561: Remove response buffering from AbstractProcessingFilter

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#822]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-561":https://jira.spring.io/browse/SEC-561?redirect=false]) said:

This was introduced during the search for a fix for SEC-398, but doesn't achieve the desired aim. It should probably be rolled back.

**Comment by rwinch** [comment]
This issue is related to #655

**Comment by spring-issuemaster** [comment]
This issue is related to #655

**Comment by spring-issuemaster** [comment]
This issue is related to #655

**Comment by spring-issuemaster** [comment]
This issue is related to #655
