### ISSUE TITLE
Update tests to use absolute paths

### ISSUE THREAD

**Issue by eleftherias** [spring-projects/spring-security#8260]
### Summary

The changes made for spring-projects/spring-framework#24556 in Spring Framework 5.2.4 break our tests that do not use absolute paths in mock endpoints.
We should change our tests to use absolute paths, as was done in later versions by b33ed416e1f4866da0ed13ef207d0c9f3ac13b51.

**Comment by spring-issuemaster** [comment]
Fixed via 298d40b7a562d807250ab1151584ce1a5b257074
