### ISSUE TITLE
Cannot configure cache lifespan of RemoteJWKSet 

### ISSUE THREAD

**Issue by alan-kan-dragon** [spring-projects/spring-security#8261]
### Summary
Module: spring-security-oauth2-jose
There is no way to configure the `RemoteJWKSet` cache lifespan even [it actually allows a `DefaultJWKSetCache` to be passed in](https://github.com/spring-projects/spring-security/blob/master/oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoder.java#L285) because [`JwkSetUriJwtDecoderBuilder` class is final](https://github.com/spring-projects/spring-security/blob/master/oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/NimbusJwtDecoder.java#L214). 

### Actual Behavior

Currently, the way to build a JwtDecoder from a JWK set URI is:
```java
NimbusJwtDecoder.withJwkSetUri(uri)
                .jwsAlgorithms(algo)
                .restOperations(restTemplate)
                .build()
``` 
So, it means it is only flexible to the algorithm and the HTTP client and that's all.

### Expected Behavior
I would like to know if it can be open by any chance so that I can inherit it and override the `processor()` method for customization

### Version

5.2.2.RELEASE

**Comment by jzheaux** [comment]
I believe this will be covered in #8332
