### ISSUE TITLE
AuthorizeRequestsDsl doesn't allow HTTP Method to be specified

### ISSUE THREAD

**Issue by adamu** [spring-projects/spring-security#8307]
### Summary

`AbstractRequestMatcherRegistry` provides the [`mvcMatchers(HttpMethod method, String... mvcPatterns)`](https://github.com/spring-projects/spring-security/blob/b93528138e2b2f7ad34d10a040e6b7ac50fc587a/config/src/main/java/org/springframework/security/config/annotation/web/AbstractRequestMatcherRegistry.java#L161) function to allow creation of an `MvcMatcher` for a specific HTTP verb, but there is no corresponding `authorize()` function in [`AuthorizeRequestsDsl`](https://github.com/spring-projects/spring-security/blob/2fb3d3d5a2ce1b15829fd36a77db0ab8e34b5b2a/config/src/main/kotlin/org/springframework/security/config/web/servlet/AuthorizeRequestsDsl.kt).

### Actual Behavior

If we want to create an MvcMatcher that matches an HTTP Verb for use with the DSL, we have to construct the matcher manually using a similar method to `AbstractRequestMatcherRegistry`'s protected [`createMvcMatchers()`](https://github.com/spring-projects/spring-security/blob/b93528138e2b2f7ad34d10a040e6b7ac50fc587a/config/src/main/java/org/springframework/security/config/annotation/web/AbstractRequestMatcherRegistry.java#L170-L191) method, or otherwise use the non-DSL [`authorizeRequests()`](https://github.com/spring-projects/spring-security/blob/2fb3d3d5a2ce1b15829fd36a77db0ab8e34b5b2a/config/src/main/java/org/springframework/security/config/annotation/web/builders/HttpSecurity.java#L1254)

### Expected Behavior

Should be able to specify the HTTP method using the `authorize()` function:

```kotlin
authorizeRequests {
    authorize(POST, "/admin/**", hasRole("ADMIN"))
}
```

### Version

5.3.0.RELEASE

**Comment by adamu** [comment]
Here is part of the log:

```
DEBUG: Created Pull Request #XX(branch="renovate/aws-java-sdk-monorepo")
DEBUG: Checking #XX for automerge(branch="renovate/aws-java-sdk-monorepo")
{
  "automerge": false,
  "automergeType": "pr",
  "automergeComment": "automergeComment"
}
DEBUG: No automerge(branch="renovate/aws-java-sdk-monorepo")
```

And the config (abbreviated):


```
{
  "configFile": ".github/renovate.json",
  "config": {
    "extends": [
      "config:base"
    ],
    "automerge": false,
    "packageRules": [
      {
        "updateTypes": [
          "patch"
        ],
        "automerge": true
      }
    ]
  }
}
```

**Comment by eleftherias** [comment]
Thanks for the report @adamu.
I agree that with your suggestion of being able to specify the HTTP method in `authorize`.
We would need to add 2 additional functions `authorize(method: HttpMethod, pattern: String, access: String)` and `authorize(method: HttpMethod, pattern: String, servletPath: String, access: String)`.
Would you be interested in submitting a PR?

**Comment by adamu** [comment]
Hi @eleftherias. To be honest I'm not sure how a good implementation would look. It looks like re-using `createMvcMatchers()` would be a good idea, but that method is `protected`, so it may be necessary to duplicate it?

**Comment by eleftherias** [comment]
@adamu I can see us reusing `ExpressionUrlAuthorizationConfigurer.mvcMatchers`.

With the current setup we have 
```
val mvcMatchersAuthorizeUrl = requests.mvcMatchers(rule.pattern)
```

We could update this so that if a user has specified the HTTP method, then we include it in the MVC matcher

```
requests.mvcMatchers(rule.httpMethod, rule.pattern)
```

This would also involve updating `PatternAuthorizationRule` to include an `HttpMethod` field.
