### ISSUE TITLE
I configured maximumSessions (1) and then when second session sign in, both sessions expired

### ISSUE THREAD

**Issue by marxli** [spring-projects/spring-security#8308]
First of all, I'm sorry. My English is poor. I may have grammar mistakes. 
As the title says, configuring maximumSessions (1) when I use spring security 5.2.2 will invalidate both sessions, but it will work when I reduce the version to 5.1.6.
I looked at the code, and the new version changed the writing of the allowableSessionsExceeded method. Is this related?
This is easy to reproduce, please contact me if you need to provide a demo

**Comment by XueQian** [comment]
@marxli 嗨，请问您怎么解决这个问题了？ 看到您自己close 这个issue了，thanks
