### ISSUE TITLE
HttpSecurityDsl does not support addFilterBefore and addFilterAfter

### ISSUE THREAD

**Issue by mengelbrecht** [spring-projects/spring-security#8316]
### Summary

`HttpSecurityBuilder` allows adding a filter before or after a specific filter using the `addFilterBefore` and `addFilterAfter` function. However, these are missing in `HttpSecurityDsl` as it only supports the `addFilterAt` function.

### Actual Behavior

As a workaround these functions can be called by directly accessing the `http` property of the `HttpSecurityDsl`:
```kotlin
http {
    http.addFilterBefore(..., ...)
    http.addFilterAfter(..., ...)
}
```

### Expected Behavior

The functions should be available in the `HttpSecurityDsl`:
```kotlin
http {
    addFilterBefore(..., ...)
    addFilterAfter(..., ...)
}
```

### Version

`5.3.1.RELEASE`

**Comment by eleftherias** [comment]
Thanks for the report @mengelbrecht.
Are you interested in submitting a PR to add these 2 functions?

**Comment by mengelbrecht** [comment]
@eleftherias yes, I will work on a PR
