### ISSUE TITLE
BCryptPasswordEncoder.encode() throws NPE

### ISSUE THREAD

**Issue by alan-czajkowski** [spring-projects/spring-security#8317]
https://github.com/spring-projects/spring-security/blob/1de0cf5057d755bcf25ef0db60297d42e2852f45/crypto/src/main/java/org/springframework/security/crypto/bcrypt/BCryptPasswordEncoder.java#L108

`BCryptPasswordEncoder.encode()` throws a Null Pointer Exception (NPE) when passing in a _null_ `rawPassword` and then `rawPassword.toString()` is called inside the method.

This method can and should be made _null_-safe, either:
- check for null and return null, or
- throw some kind of exception

**Comment by rwinch** [comment]
@alan-czajkowski We don't want to return null for the encoding, but I'd be open to returning an `IllegalArgumentException`. Would you be willing to submit a PR?

**Comment by alan-czajkowski** [comment]
@rwinch I'll submit a PR

**Comment by alan-czajkowski** [comment]
@rwinch done
