### ISSUE TITLE
Consider adding ClientRegistration.providerDetails.issuerUri

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#8326]
We should consider adding a new attribute `ClientRegistration.providerDetails.issuerUri`, which would be used for [OpenID Connect Discovery 1.0](https://openid.net/specs/openid-connect-discovery-1_0.html) or [OAuth 2.0 Authorization Server Metadata](https://tools.ietf.org/html/rfc8414).

Related #8321 see [comment](https://github.com/spring-projects/spring-security/issues/8321#issuecomment-608383092)

**Comment by ThomasVitale** [comment]
Hi @jgrandja, can I take this task?

**Comment by jgrandja** [comment]
That would be great @ThomasVitale ! Please go ahead.

**Comment by ThomasVitale** [comment]
Thanks @jgrandja, I'll start working on it then.

**Comment by ThomasVitale** [comment]
@jgrandja Besides adding the attribute and making it settable from the builder, which use cases should I support (and test)?

**Comment by jgrandja** [comment]
@ThomasVitale `CommonOAuth2Provider` will need to have a default issuerUri set for `GOOGLE` and `OidcIdTokenValidator` will need to get updated similar to this resent update 32ce94d

**Comment by ThomasVitale** [comment]
@jgrandja Thanks, I'll submit a PR for an early review in a couple of days.

**Comment by ThomasVitale** [comment]
@jgrandja I submitted a PR here: https://github.com/spring-projects/spring-security/pull/8501
