### ISSUE TITLE
Allow specify header in ServerBearerTokenAuthenticationConverter

### ISSUE THREAD

**Issue by TJReinert** [spring-projects/spring-security#8337]
### Summary

I'd like to be able to use the current ServerBearerTokenAuthenticationConverter but want to use a different header (`HttpHeaders.PROXY_AUTHORIZATION`) for my Spring Cloud Gateway Instance.

### Actual Behavior

Authentication must be taken from the `HttpHeaders.AUTHORIZATION`.

### Expected Behavior

I should be able to supply what Header I would like to extract my token from. If not specified default to `HttpHeaders.AUTHORIZATION`.

### Version

All versions, enhancement request.

### Notes

These changes are straight forward and I can open a PR for these changes if deemed necessary.

**Comment by jzheaux** [comment]
That makes sense, @TJReinert, would you be interested in submitting a PR to add that feature?

**Comment by TJReinert** [comment]
Sure thing. Please coach me if there are improvements desired -- first submission to an opensource project.
