### ISSUE TITLE
Encoded password does not look like BCrypt

### ISSUE THREAD

**Issue by nejatian** [spring-projects/spring-security#8380]
### Summary
I have a problem with authenticating users using spring boot API and JWT

### Actual Behavior

I see this error in my console  
`WARN 24692 --- [nio-8080-exec-1] o.s.s.c.bcrypt.BCryptPasswordEncoder     : Encoded password does not look like BCrypt`
and 
```
{
    "timestamp": "2020-04-13T02:09:43.728+0000",
    "status": 401,
    "error": "Unauthorized",
    "message": "Unauthorized",
    "path": "/authenticate"
}
```
in post man
### Expected Behavior

I expect to get token 

### Version
<spring.version>5.2.6.BUILD-SNAPSHOT</spring.version>
		<spring-security.version>5.3.2.BUILD-SNAPSHOT</spring-security.version>

**Comment by jzheaux** [comment]
Since Spring Security's JWT support doesn't use the `PasswordEncoder`, there's probably most configuration that you'll need to share to determine if this is a bug or not.

Would you please provide a minimal sample (a GitHub repo, for example) that reproduces the issue?

**Comment by nejatian** [comment]
I have solved my problem by importing 
 org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder.BCryptVersion
 to my code.
