### ISSUE TITLE
Compatibility with Spring Framework 5.2.x

### ISSUE THREAD

**Issue by fpagliar** [spring-projects/spring-security#8387]
### Summary

SpringSecurity 5.3.1 documentation states that it is built against Spring Framework 5.2.5 and any **newer** version should work. 

Is there a hard dependency on the patch version? 
I need to upgrade to Spring Security 5.3 but I'm running an earlier patch of the framework (5.2.x).

**Comment by rwinch** [comment]
Spring is quite passive, so you should be able to just update Spring Framework without any issue. Were you having a problem? If so, I'd recommend you consider submitting a ticket with Spring Framework.

We don't run tests on previous versions so I'd recommend using the guidelines provided. If it does work, there is no harm. However, if something is broken we will tell you to update.
