### ISSUE TITLE
SEC-580: AlwaysTestAfterMaxRequestsCaptchaChannelProcessor does not check for humanity

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#841]
["Calin Vaida":https://jira.spring.io/secure/ViewProfile.jspa?name=calin](Migrated from ["SEC-580":https://jira.spring.io/browse/SEC-580?redirect=false]) said:

AlwaysTestAfterMaxRequestsCaptchaChannelProcessor channel processor does not check the humanity feature and is based only on the fact that the thresold has not been reached. This cause a problem when we are running for the first time through the filters, because the initial value of property humanRestrictedResourcesRequestsCounts is 0 (having the same value as after a successful captcha validation)  from  CapthcaSecurityContextImpl class and even if the captcha validation does fail the processor will ignore that as long as the thresold is not reached. 
In this situation with captcha validation failing I can go further to the next filter and I am not redirected  to the captcha entry point as I've been expected. 
My guess is that will be better  if the AlwaysTestAfterMaxRequestsCaptchaChannelProcessor will take in consideration also humanity when does decide to go further or not:
I have written further what I am thinking that must be change in this processor.
to replace this line:
 boolean isContextValidConcerningHumanity(CaptchaSecurityContext context) {
  ->          if (context.getHumanRestrictedResourcesRequestsCount() < getThresold()) {
with:
                 if (context.isHuman() && context.getHumanRestrictedResourcesRequestsCount() < getThresold()) {

Than solve my problem and seems to work just fine for me.

**Comment by spring-issuemaster** [comment]
This issue is related to #976

**Comment by spring-issuemaster** [comment]
This issue is related to #976

**Comment by spring-issuemaster** [comment]
This issue is related to #976
