### ISSUE TITLE
saml2login sample project looping bug

### ISSUE THREAD

**Issue by leozleung** [spring-projects/spring-security#8446]
**Describe the bug**
after input user and password, the request is being post to simpleSAMLphp and redirect back and looping start

**To Reproduce**
1. git clone the project
2. run ./gradle :spring-security-samples-boot-saml2login:bootRun
3. open localhost:8080
4. input user and password
5. looping start

**Expected behavior**
authentication success and being able to stay at index.html

**Comment by leozleung** [comment]
it works when i use another machine to checkout and run the sample. so close it.

**Comment by rwinch** [comment]
Thanks for the follow up @leozleung!
