### ISSUE TITLE
[Doc] Show what is the replacement for the deprecated macSigner in the migration guide 

### ISSUE THREAD

**Issue by LifeIsStrange** [spring-projects/spring-security#8457]
I am a user of https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-jwt/src/main/java/org/springframework/security/jwt/crypto/sign/MacSigner.java

It has been marked as deprecated in the code and link to the following migration guide ->
https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide

I believe that macSigner has been replaced for JWT with nimbus but from my understanding nimbus work specially for JWT.

I am currently using macSigner for generating a SHA256 hash for any string. This is juste a hash generation and my use case has nothing to do with the special case of JWTs.

So what is the replacmet of macSigner for generating a hash not related to JWT ?

I can't find mention of this (common ?) use case in the migration guide, hence the issue.

**Comment by LifeIsStrange** [comment]
Well I found out that macSigner was also coupled to JWT anyway.
So the issue is just that I dont know which class to use in springsecurity in order to encode and decode a sha256 hash without using JWT special classes.

This is not a spring security issue hence the closing

**Comment by rwinch** [comment]
Glad you figured it out @LifeIsStrange and thanks for the fast follow up!
