### ISSUE TITLE
SEC-587: HttpSessionContextIntegrationFilter does not store the SecurityContext when a redirect occurs further down the filter chain

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#848]
["Matt Clark":https://jira.spring.io/secure/ViewProfile.jspa?name=mclark00](Migrated from ["SEC-587":https://jira.spring.io/browse/SEC-587?redirect=false]) said:

I'm experiencing a problem where redirects further down the filter chain from the security context cause Acegi to fail to store the SecurityContext in the session.  This causes obvious problem when the user's subsequent request comes in.  I've verified this in the debugger.  Here is the sequence:

1) Authentication form submits
2) HttpSessionContextIntegrationFilter creates a new SecurityContext
3) Login occurs, so SecurityContext now contains the Authentication object we need
4) A redirect happens during page rendering (a natural part of Wicket's response)
5) The OnRedirectUpdateSessionResponseWrapper's (inner class to the filter) sendRedirect
   method fires, and it does two things.  First, it checks to see if it should store the
     SecurityContext in the session, but does not because the context's hashcode has not changed since the start
     of the request.  Second, it sets the sessionUpdateDone variable to true;
6) The filter finishes processing, clears the SecurityContextHolder so the thread is clean,
     and then checks to see if it should store the SecurityContext.  It does not, because
     the sessionUpdateDone variable was set to true.

THUS - the securitycontext never gets stored in the session.

**Comment by spring-issuemaster** [comment]
This issue is related to #655

**Comment by spring-issuemaster** [comment]
This issue is related to #655

**Comment by spring-issuemaster** [comment]
This issue is related to #655
