### ISSUE TITLE
Add documentation/support for "Sign in with Apple"

### ISSUE THREAD

**Issue by Ditscheridou** [spring-projects/spring-security#8485]
Im currently writing a server which has the requirement to be able to use the "Sign In With Apple" feature. Initially i was confident that i can use the oauth2-client, just register the required properties and that it will work ootb. But Apple requires several adjustments for the "response_type" and "response_mode" properties so they support "form_post", which currently cant be configured in the client (at least i couldnt find any documentation about it). It would be nice if you could provide a sample or a enhancement for the library so we can use it like the other oidc provider.

**Comment by jgrandja** [comment]
@Ditscheridou 

> But Apple requires several adjustments for the "response_type" and "response_mode" properties so they support "form_post", which currently cant be configured in the client

There is support for `form_post`. Have you had a chance to review the reference documentation? We ensured that all features are documented so please take a look there to see what features are available.

I'll point you to the relevant documentation to get you going:

- [ClientRegistration](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2Client-client-registration) - See `ClientAuthenticationMethod.POST`

- [Spring Boot 2.x Property Mappings](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2login-boot-property-mappings)

- [Customizing the Authorization Request](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#customizing-the-authorization-request)

- [Customizing the Access Token Request](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#customizing-the-access-token-request)

- [Customizing the Access Token Response](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#customizing-the-access-token-response)

I'm going to close this issue as a duplicate of #6020, as its meant to address the implementation of custom client adaptors for providers that are not spec compliant.

Either way, the customizations are available in `oauth2-client`, so it should be possible to "Login with Apple" using a custom configuration. If you notice a customization is not available for your use case, please let me know and we can address it.
