### ISSUE TITLE
Examine SAML2 error code when assertion has invalid signature

### ISSUE THREAD

**Issue by eleftherias** [spring-projects/spring-security#8492]
## Scenario
A SAML2 response assertion has an invalid signature.

## Behavior
[This commit](https://github.com/spring-projects/spring-security/commit/545286188d7a9053edf5c5adcb26c3a271fbcd5e) changed the expected `Saml2AuthenticationException` error code in the integration tests.

We should examine whether the correct error code in this case is `invalid_signature` or `invalid_assertion`.

If the correct error code is `invalid_signature` then this commit may be reverted.

**Comment by jzheaux** [comment]
Thanks, @eleftherias, this commit looks good. The information in the exception is now in the `Saml2Exception` `cause`.
