### ISSUE TITLE
Add support to publish and consume SAML metadata

### ISSUE THREAD

**Issue by dawi** [spring-projects/spring-security#8500]
Currently it is not possible to publish and consume [SAML metadata](https://en.wikipedia.org/wiki/SAML_metadata).

This is stated in the documentation:

> Saml 2 Login - Not Yet Supported
> Dynamic metadata generation
> 
> Service Provider Metadata
> The Spring Security SAML 2 implementation does not yet provide an endpoint for downloading SP metadata in XML format.

Are there any plans to support this feature anytime soon?

**Comment by eleftherias** [comment]
@dawi Can you confirm whether this is a duplicate of gh-8484?

**Comment by dawi** [comment]
Oh really, this is indeed a duplicate of gh-8484. :) I haven't seen this ticket before.
