### ISSUE TITLE
authorization_code grant should use same ServerRequestCache

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security#8536]
`ServerHttpSecurity.OAuth2ClientSpec.configure()` registers `OAuth2AuthorizationRequestRedirectWebFilter` and `OAuth2AuthorizationCodeGrantWebFilter` for the `authorization_code` grant flow. However, these `WebFilter` 's do not share a `ServerRequestCache`.

We should apply the necessary changes so that the configured `ServerRequestCache` is used by both `WebFilter` 's.

Related #8120

**Comment by parikshitdutta** [comment]
Hi @jgrandja, can I look into it as well?

**Comment by jgrandja** [comment]
Thanks @parikshitdutta. The issue is yours.

**Comment by parikshitdutta** [comment]
Hi @jgrandja, regret taking more time, super cyclone massacred our place. Anyways, please have a look at PR #8587. I will look forward to your feedback.

Thank you.

**Comment by jgrandja** [comment]
I'm really sorry to hear this @parikshitdutta. I hope you and your family are ok? There is no rush for this feature as it's scheduled for 5.4, which is being released early Sep. I will review later this week. Take care  of yourself and family.

**Comment by parikshitdutta** [comment]
Hi @jgrandja, We are blessed to be safe and secure, but it has devastated our place. Things are getting back to normal. Thanks for asking and caring for us.

I will look forward to your feedback as you finish reviewing changes. On a separate note, is there a way, I can get used to the release calendar and planned features for forthcoming releases?

**Comment by jgrandja** [comment]
Hey @parikshitdutta - you can see the scheduled releases [here](https://github.com/spring-projects/spring-security/milestones).

I'm glad to hear things are getting back to normal. I wish you and your family luck.
