### ISSUE TITLE
Unused field in Md4PasswordEncoder

### ISSUE THREAD

**Issue by justmehyp** [spring-projects/spring-security#8537]
It seems that the following line in `Md4PasswordEncoder` is redundant:

https://github.com/spring-projects/spring-security/blob/1e211b6558f558a465d3653c38cd5d46694226be/crypto/src/main/java/org/springframework/security/crypto/password/Md4PasswordEncoder.java#L86

**Comment by rwinch** [comment]
It is not clear to me what you mean. Can you provide more details?

**Comment by justmehyp** [comment]
@rwinch    Sorry that I didn't make it clear at one time. When I read the source code of class `org.springframework.security.crypto.password.Md4PasswordEncoder`, I guessed that it was implemented by `org.springframework.security.crypto.password.Digester`, but I found that `private Digester digester;` was defined in class `Md4PasswordEncoder`, but it was never used. So I think this line of code is redundant

**Comment by justmehyp** [comment]
This is my PR related to this issue:   [https://github.com/spring-projects/spring-security/pull/8553](https://github.com/spring-projects/spring-security/pull/8553)

**Comment by rwinch** [comment]
Thanks for the PR! I'm closing this a duplicate of the PR
