### ISSUE TITLE
no 'addFilterBefore` in kotlin dsl

### ISSUE THREAD

**Issue by pdeva** [spring-projects/spring-security#8541]
**Expected Behavior**

there should be `addFilterBefore` method for http security kotlin dsl, for the equivalent of `http.addFilterBefore` method.

**Current Behavior**

only `addFilterAt` is present in the dsl, but not `addFilterBefore`

**Context**

i have this code, i want to convert to dsl, but i cannot due to lack of equivalent method

```
http.addFilterBefore(JWTCookieFilter(jwtTokenManager), UsernamePasswordAuthenticationFilter::class.java)
```

**Comment by eleftherias** [comment]
Thanks for the report @pdeva.

This was already brought up and fixed in gh-8316.
This functionality is available in version 5.4.0-M1 and will be available in GA releases starting with 5.4.0.
