### ISSUE TITLE
SEC-595: Allow for usage of passed user credentials for LDAP role lookup

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#856]
["Arie van Wijngaarden":https://jira.spring.io/secure/ViewProfile.jspa?name=vanwijngaarden](Migrated from ["SEC-595":https://jira.spring.io/browse/SEC-595?redirect=false]) said:

Situation:
- Anonymous binding is not allowed on the given LDAP server.
- Don't want to use "manager" credentials to perform LDAP searches because it requires a special account.

Problem:
Although user authentication can be done without manager credentials using a BindAuthenticator, the role lookup using DefaultLdapAuthoritiesPopulator requires in this case manager credentials. If it would be possible to use the (already authenticated) user credentials for this, a manager account would not be necessary.

Solution:
Adapt DefaultLdapAuthoritiesPopulator to optionally use the credentials of the user for which the authorization takes place for the group lookup. See attachment (change of the 1.0.5 version) for details.

**Comment by rwinch** [comment]
This issue depends on #855

**Comment by spring-issuemaster** [comment]
This issue depends on #855

**Comment by spring-issuemaster** [comment]
This issue depends on #855

**Comment by spring-issuemaster** [comment]
This issue depends on #855
