### ISSUE TITLE
Typo in title of SAML2 Sample Readme

### ISSUE THREAD

**Issue by sgilson** [spring-projects/spring-security#8562]
The title of the file samples/boot/saml2login/README.adoc is currently "OAuth 2.0 Login Sample". It should be "SAML 2.0 Login Sample".

**Comment by rwinch** [comment]
Thanks for the report. I saw you sent a pull request at https://github.com/spring-projects/spring-security/pull/8561 but you delete the branch. Any particular reason you did that? Would you be interested in submitting a pull request?

**Comment by sgilson** [comment]
Hi @rwinch , thanks for the response. After I submitted the PR, I realized I wasn't in a position to sign the Contributor License Agreement quite yet. I wasn't exactly sure what the right course of action was.

**Comment by rwinch** [comment]
Thanks for the fast response. Please feel free to resubmit and indicate it as an obvious fix using `@pivotal-issuemaster This is an Obvious Fix` That will make the bot happy.

**Comment by sgilson** [comment]
Terrific. Reopened at #8581

**Comment by rwinch** [comment]
Closing in favour of gh-8581
