### ISSUE TITLE
Unable to convert claim 'iss' of type 'class java.lang.String' to URL

### ISSUE THREAD

**Issue by dinsceg** [spring-projects/spring-security#8563]
I am having string value in iss claim but spring security is expecting iss value as URL.. Is it possible to change something to accept string value instead of URL while validating idtoken in spring security.

**Comment by eleftherias** [comment]
Thanks for getting in touch, it looks like you have posted [this question](https://stackoverflow.com/questions/61906629/spring-oidc-getting-unable-to-convert-claim-iss-of-type-class-java-lang-str) on StackOverflow, so let's continue the discussion there.
As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.md#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
