### ISSUE TITLE
Use String to specify custom HTTP method in mock request

### ISSUE THREAD

**Issue by eleftherias** [spring-projects/spring-security#8592]
In Spring Framework 5.2.7, `MockServerHttpRequest` will accept a custom HTTP method as a `String` parameter.
Going forward we should use 
```
MockServerHttpRequest.method("CUSTOM-HTTP-METHOD", "/")
```
when testing a request with a custom HTTP method.

The test `matchesRequireCsrfProtectionWhenNonStandardHTTPMethodIsUsed` will need to be updated.

Reference: https://github.com/spring-projects/spring-framework/issues/25109

**Comment by midumitrescu** [comment]
hi @eleftherias , 

I would be willing to help with the implementation. 

I started comparing some refactoring ideas, in which:

```
interface HttpMethod {}

enum HttpMethods implements HttpMethod {} 
class NonStandardHttpMethod implements HttpMethod {}
```

One can find the comparison under https://github.com/midumitrescu/httpmethod-refactorings 

I haven't considered changing MockServerHttpRequest to allow for 
```
MockServerHttpRequest.method("CUSTOM-HTTP-METHOD", "/")
```

The biggest issue I see is that 
```
MockServerHttpRequest extends AbstractServerHttpRequest
```
which brings from HttpRequest: 

```
	@Nullable
	default HttpMethod getMethod() {
		return HttpMethod.resolve(getMethodValue());
	}

	String getMethodValue();
```

It feels somehow weird to me that, for example, for  **CONNECT** or **CUSTOM-HTTP-METHOD**  
```
getMethodValue()
```
should return a valid String but 

```
getMethod()
```
should return **null**. 

One can write the code to work, but this feels anyways a bit weird.

**Comment by midumitrescu** [comment]
Actually, I played arround now with: 

```
public final class MockServerHttpRequest extends AbstractServerHttpRequest {

	private final String httpMethodValue;
```

One needs to change the type also in the Builder, of course, but the change is not THAT invasive. 

The big advantage is that the constructor is private, so one can be sure that clients initialize instances only through the builder.

```
			
			public DefaultBodyBuilder(String methodValue, URI url) {
				this.methodValue = methodValue;
				this.url = url;
			}
	
	
			public DefaultBodyBuilder(HttpMethod method, URI url) {
				this(method.name(), url);
			}
```

enables easy refactoring of the class.

I will create tomorrow some tests and create a MR, if that's OK.

**Comment by eleftherias** [comment]
Hey @midumitrescu, I see you have already left a comment on the Spring Framework issue.
It looks like the classes you are mentioning, `MockServerHttpRequest`, `HttpMethod`  are all part of Spring Framework.
Is there a change you a proposing for Spring Security as well?

**Comment by midumitrescu** [comment]
hey @eleftherias  :)

Sorry, I was myself confused. 

The original ticket got closed and I assumed the work will be continued here. 
I am not seeing anything in spring-security related remotely to allowing extensible HTTP method names.

Should I delete my commets and move them in the original ticket?
