### ISSUE TITLE
Broken link in Spring Security reference document

### ISSUE THREAD

**Issue by donhuvy** [spring-projects/spring-security#8593]
**Describe the bug**
Broken link in Spring Security reference document.

**To Reproduce**
Go to https://docs.spring.io/spring-security/site/docs/5.3.2.RELEASE/reference/html5/#websocket

Presss broken link: 
https://github.com/spring-projects/spring-session/tree/master/samples/boot/websocket

**Expected behavior**
The content is correct.

**Sample**
(No existing)

**Comment by jzheaux** [comment]
@donhuvy thanks for the report!

Would you like to submit a PR to fix the broken link?

**Comment by donhuvy** [comment]
oh no,

**Comment by dkodippily** [comment]
@jzheaux  @donhuvy I would like to submit a PR to fix this, it's my first time trying to give back to the community, apart from given guidelines any advice for me ?
