### ISSUE TITLE
BeanCurrentlyInCreationException when used spring security with spring boot 2.3.0.RELEASE and spring.main.lazy-initialization: true and management.server.port

### ISSUE THREAD

**Issue by dante-ricalde** [spring-projects/spring-security#8596]
**Describe the bug**
I get the following error:

Caused by: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'authenticationPrincipalArgumentResolverConfigurer': Requested bean is currently in creation: Is there an unresolvable circular reference?

When I start a minimal spring boot application with spring-security added as dependency and 
the following properties configured:

management.server.port=8082
spring.main.lazy-initialization=true

There is a circular reference problem between these two configurations: ServerHttpSecurityConfiguration and DelegatingWebFluxConfiguration

I also want to reference this issue: https://github.com/spring-projects/spring-boot/issues/21580
opened to spring boot with the same error.
Could you please help with this error and break that cycle error in this configuration ServerHttpSecurityConfiguration???

**To Reproduce**
Start the sample application Running the class: DemoApplication 

**Sample**
[demo.zip](https://github.com/spring-projects/spring-security/files/4684540/demo.zip)

I have uplodaded the sample to my own repo:
https://github.com/dante-ricalde/tests/blob/master/demo.zip

**Comment by rwinch** [comment]
Thanks for the excellent sample. I created https://github.com/spring-projects/spring-framework/issues/25166 and gh-8613 The first issue is for Spring Framework and I think it is the root of the problem. The second issue is a workaround in Spring Security. I'm going to close this issue since there are separate tickets for the action items.

**Comment by wilkinsona** [comment]
Thanks for tracking this one down, @rwinch.
