### ISSUE TITLE
Missing Reactive SwitchUserWebFilter for user impersonation

### ISSUE THREAD

**Issue by aotrzonsek** [spring-projects/spring-security#8599]
**Expected Behavior**

Add the possibility to impersonate a user in Reactive applications as it is possible by using the SwitchUserFilter.

**Current Behavior**

It is not possible to switch the user context, at least I couldn't find anything equivalent.

**Context**

It’s a common use-case that some admin users should be able to log in as any other user. 
In our applications we have used this feature for customer support analysis where the analyst can access the system as the real user.

**Comment by rwinch** [comment]
Thanks for the report @aotrzonsek Would you be interested in submitting a pull request?

**Comment by aotrzonsek** [comment]
Sure why not, I have to implement it anyway. I will add a comment after I have finished the implementation.

**Comment by aotrzonsek** [comment]
All issues found during the code review have been removed.
