### ISSUE TITLE
SEC-597: AclImpl.setParent() throws Exception when changing parent to null

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#860]
["Emanuel":https://jira.spring.io/secure/ViewProfile.jspa?name=derkaiser](Migrated from ["SEC-597":https://jira.spring.io/browse/SEC-597?redirect=false]) said:

I think it should be possible to change the parent of a directory to null:

Sample Scenario:
Filebrowser that manages a directory structure (the directories are secured by acegi). Now i want to move a nested directory to Root-Level. The parent-property of the corresponding ACL has to be changed to NULL.

Solution:
Simply change:

```
public void setParent(Acl newParent) {
    aclAuthorizationStrategy.securityCheck(this, AclAuthorizationStrategy.CHANGE_GENERAL);
    Assert.notNull(newParent, "New Parent required");
    Assert.isTrue(!newParent.equals(this), "Cannot be the parent of yourself");
    this.parentAcl = newParent;
}
```

to

```
public void setParent(Acl newParent) {
    aclAuthorizationStrategy.securityCheck(this, AclAuthorizationStrategy.CHANGE_GENERAL);
    Assert.isTrue(newParent == null || !newParent.equals(this), "Cannot be the parent of yourself");
    this.parentAcl = newParent;
}
```

**Comment by rwinch** [comment]
This issue duplicates #833
