### ISSUE TITLE
HttpSessionCsrfTokenRepository does not set csrfToken value in response header

### ISSUE THREAD

**Issue by Jovons** [spring-projects/spring-security#8620]
After reading reference, I think for usage cases, when csrfToken is set in response header (not cookie), should use HttpSessionCsrfTokenRepository instead of CookieCsrfTokenRepository. So I had this:
```
        http.csrf()
                .ignoringAntMatchers("/api/**")
                .csrfTokenRepository(new HttpSessionCsrfTokenRepository());
```
According to javadoc:
```
/**
	 * Sets the header name that the {@link CsrfToken} is expected to appear on and the
	 * header that the response will contain the {@link CsrfToken}.
	 *
	 * @param headerName the new header name to use
	 */
	public void setHeaderName(String headerName) {}
```
However, I observed from browser network window, `X-CSRF-TOKEN` never appears in the response header. And during debug step by step, I never found a statement, when headerName is set in response, not in `saveToken` (`addCookie` is called in `CookieCsrfTokenRepository` `saveToken` method).

**Comment by rwinch** [comment]
@Jovons That is the name of the HTTP request header that a client can provide a valid token on. It is not intended to appear on the response headers.

**Comment by Jovons** [comment]
> @Jovons That is the name of the HTTP request header that a client can provide a valid token on. It is not intended to appear on the response headers.

Hi rwinch, by using HttpSessionCsrfTokenRepository instead of Cookie, there is no CSRF token in response. It was in Set-Cookie when used Cookie.

**Comment by rwinch** [comment]
Yes. `HttpSessionCsrfTokenRepository` stores the expected token in session which is linked by the session id in a cookie and `CookieCsrfTokenRepository` stores the expected token directly in a cookie. Both need the client to specify the actual token so it can be compared against the expected value. The value can be provided in the request parameters or as a header.
