### ISSUE TITLE
Support A Well-Known URL for Changing Passwords

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security#8657]
**Expected Behavior**
Spring Security should support https://wicg.github.io/change-password-url/index.html

**Comment by evgeniycheban** [comment]
@rwinch I would like to work on this.

**Comment by rwinch** [comment]
Thank you for volunteering! The issue is yours

**Comment by evgeniycheban** [comment]
@rwinch I've submitted PR.

Please take a look when you have a moment.

**Comment by maradanasai** [comment]
Hi @evgeniycheban Thanks for working on this. I see there are no examples on how to use this feature. Checked your repo https://github.com/evgeniycheban/spring-security-well-known-change-password-demo but couldn't find anything here. Can you please provide a demo example?
