### ISSUE TITLE
ProviderManager#checkState() throws NullPointerException

### ISSUE THREAD

**Issue by yukihane** [spring-projects/spring-security#8689]
**Describe the bug**

When use [`java.util.List.of()`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/List.html#of(E)), [`ProviderManager#checkState()`](https://github.com/spring-projects/spring-security/blob/5.3.3.RELEASE/core/src/main/java/org/springframework/security/authentication/ProviderManager.java#L148) throws `NullPointerException`.

`checkState()` uses `List#contains(null)` since https://github.com/spring-projects/spring-security/issues/7713#issuecomment-569741294, but [it may throws `NullPointerException`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/List.html#contains(java.lang.Object)):

> NullPointerException - if the specified element is null and this list does not permit null elements ([optional](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Collection.html#optional-restrictions))

**To Reproduce**

    new ProviderManager(List.of(myProvider));

**Expected behavior**

`NPE` is not thrown.

**Comment by jzheaux** [comment]
@yukihane thank you for the suggestion that the exception be refined. It's a nice improvement to be able to replace an NPE with a more helpful error message.

Would you be interested in submitting a PR to change this check into a for loop?
