### ISSUE TITLE
Kotlin Configuration DSL: Add addFilterBefore() and addFilterAfter() functions

### ISSUE THREAD

**Issue by gonozalviii** [spring-projects/spring-security#8692]
**Expected Behavior**

I would like to use `addFilterBefore()` and `addFilterAfter()`. Currently only the `addFilterAt()` function is available in the DSL.
Also please use reified types to allow writing `addFilterBefore<BasicAuthenticationFilter>(myFilter)`.
Or let the function at least take a KClass instead of a Class so we can omit the `.java`

**Current Behavior**

The 2 mentioned functions are missing, the existing one takes a Java Class as in Input.

**Context**

I currently have the use the `addFilterBefore()` outside the dsl scope which splits the configuration in half.

**Comment by eleftherias** [comment]
Thanks for the report @gonozalviii.

This was already brought up and fixed in gh-8316.
This functionality is available in version 5.4.0-M1 and will be available in GA releases starting with 5.4.0.
