### ISSUE TITLE
Support SAML 2.0 SP Metadata Endpoints

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#8693]

**Comment by jeanblanchard** [comment]
A side-note: Currently, the entityId for the Service Provider is set to `{baseUrl}/saml2/service-provider-metadata/{registrationId}`, which looks like a metadata URL, but is not bound to an actual endpoint, so that's a bit strange. At least I was surprised and initially thought something was wrong.

**Comment by scho** [comment]
I've just tested RC-1 and was very happy to see this feature :)
One question though:
Is it intended, that the URI patterns like `{baseUrl}` or `{registrationId}` are not replaced with the actual values?
