### ISSUE TITLE
SEC-612: Account authentication policy support

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#873]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-612":https://jira.spring.io/browse/SEC-612?redirect=false]) said:

Listen for authentication success and authentication failure events, and update tables accordingly. Integrate with account locking capabilities. Provide a querying interface to retrieve all events associated with a user after a particular date.

We also might want to consider logging authorizations as well, although that is probably a separate issue. We will certainly need to consider archival issues if we did that.

**Comment by spring-issuemaster** [comment]
This issue is related to #770
