### ISSUE TITLE
Support JWTBearer Client Assertion Authentication

### ISSUE THREAD

**Issue by visweshwar** [spring-projects/spring-security#8735]
**Expected Behavior**

One of the protocols support by OAuth is Client Assertion as authentication

A client uses an assertion to authenticate to the authorization server's token endpoint by using the "client_assertion_type" and "client_assertion" parameters

https://tools.ietf.org/html/rfc7521#section-6.1

**Current Behavior**
 
No Support

**Context**

This is something supported by jose.nimbus  and as consumer and provider of OAuth we want to secure our authentication to the token endpoint using this protocol.

**Comment by jgrandja** [comment]
Closing as duplicate #6881
