### ISSUE TITLE
SEC-613: Tag libraries require rename

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#874]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-613":https://jira.spring.io/browse/SEC-613?redirect=false]) said:

The authz tag library uses the old URL format:

<%@ taglib prefix="authz" uri="http://acegisecurity.org/authz" %>

Make tag library use new format:

<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags" %>

**Comment by spring-issuemaster** [comment]
This issue depends on #823
