### ISSUE TITLE
Fix dead links in OAuth 2.0 Migration Guide

### ISSUE THREAD

**Issue by LeBezout** [spring-projects/spring-security#8770]
Hi, 

I report some broken links in the **OAuth 2.0 Migration Guide** <https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide>

### Links to fix (404)

* https://docs.spring.io/spring-security-oauth2-boot/docs/current/reference/htmlsingle/#boot-features-security-oauth2-single-sign-on
* https://docs.spring.io/spring-security-oauth2-boot/docs/current/reference/htmlsingle/#boot-features-security-oauth2-resource-server
* https://docs.spring.io/spring-security-oauth2-boot/docs/current/reference/htmlsingle/#oauth2-boot-resource-server-authorization

### Fix

`https://docs.spring.io/spring-security-oauth2-boot/docs/current/reference/htmlsingle/` => `https://docs.spring.io/spring-security-oauth2-boot/docs/current/reference/html5/`

Or implement redirection like <https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#webflux-oauth2resourceserver-jwt-authorization>

_Originally posted by @LeBezout in https://github.com/spring-projects/spring-security/issues/2976#issuecomment-650168031_

**Comment by jzheaux** [comment]
Thanks for the report, @LeBezout! I've taken care of the links.

And thank you also for the suggestion to add the same redirection to OAuth2 Boot. Would you mind [adding a ticket there](https://github.com/spring-projects/spring-security-oauth2-boot/issues/new) so that we can track it?
