### ISSUE TITLE
Support custom filter in Server Kotlin DSL

### ISSUE THREAD

**Issue by eleftherias** [spring-projects/spring-security#8783]
We should add support for adding a custom filter in the Server Kotlin DSL.
Similar to `ServerHttpSecurity`, we should have 3 ways to add a filter, `addFilterAt`, `addFilterBefore` and `addFilterAfter`.

The configuration should look like this
```
@Bean
open fun springWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        addFilterAfter(TestWebFilter(), SecurityWebFiltersOrder.SECURITY_CONTEXT_SERVER_WEB_EXCHANGE)
    }
}
```

**Comment by evgeniycheban** [comment]
I can take this.

**Comment by eleftherias** [comment]
Thanks @evgeniycheban! The issue is yours.
