### ISSUE TITLE
JwtGrantedAuthoritiesConverter authorityPrefix must alway be present

### ISSUE THREAD

**Issue by ShevaDavid** [spring-projects/spring-security#8798]
Why can't I set "blank" to authorityPrefix in JwtGrantedAuthoritiesConverter?

**Comment by eleftherias** [comment]
Thanks for the report @ShevaDavid.

This was brought up in gh-8421.

The fix was included in Spring Security 5.2.4, 5.4.0-M1, which are already available. 
It will also be included in 5.3.4 (scheduled for August 5).
