### ISSUE TITLE
There's two copies of Saml2Utils

### ISSUE THREAD

**Issue by fpagliar** [spring-projects/spring-security#8834]
**Current Behavior**

There's a copy pasted version of Saml2Utils.
You can find this class under `saml2.provider.service.servlet.filter` and under `saml2.provider.service.authentication`.
Both have the same exact code.

It would be good to consolidate them, given that if there's a fix on the encoding, right now there's risk that it might make it to part of the framework but not all of it.

**Comment by jzheaux** [comment]
Thanks for the suggestion, @fpagliar.

There's no intent to make `Saml2Utils` public, which is why the class was copied so that it can remain package-private.

**Comment by mathewm3** [comment]
Can we make **Saml2Utils** class public so that it can be used during implementation. Also, it will avoid duplicating the same file in multiple packages.
