### ISSUE TITLE
JdbcOAuth2AuthorizedClientService + Oracle => ClassCastException: [B cannot be cast to oracle.sql.BLOB

### ISSUE THREAD

**Issue by Taraskin** [spring-projects/spring-security#8862]
**Describe the bug**
When using **JdbcOAuth2AuthorizedClientService** with Oracle DB (>10g) got _ClassCastException: [B cannot be cast to oracle.sql.BLOB_ at step: **insertAuthorizedClient()**.

**To Reproduce**
Pre-Conditions:
- Spring Security **5.3.2.RELEASE**
- Configure **OAuth2** to use **JdbcOAuth2AuthorizedClientService** to persist Authorized Clients
- Create (Oracle) DB scheme, using [oauth2-client-schema.sql](https://github.com/spring-projects/spring-security/blob/5.3.x/oauth2/oauth2-client/src/main/resources/org/springframework/security/oauth2/client/oauth2-client-schema.sql)

**Expected behavior**
Persist/update Authorized Clients in Oracle DB (_>10g_) according to existing logic.

**Sample**
Used official _Spring 5.3.2.RELEASE_ code snapshots - to point to the place(s) where issue happened:
1. [JdbcOAuth2AuthorizedClientService](https://github.com/spring-projects/spring-security/blob/5.3.x/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/JdbcOAuth2AuthorizedClientService.java):
in 
_saveAuthorizedClient(OAuth2AuthorizedClient authorizedClient, Authentication principal)_ line **137**
call of _insertAuthorizedClient(authorizedClient, principal);_ 

```
private void insertAuthorizedClient(OAuth2AuthorizedClient authorizedClient, Authentication principal) {
		List<SqlParameterValue> parameters = this.authorizedClientParametersMapper.apply(
				new OAuth2AuthorizedClientHolder(authorizedClient, principal));
		PreparedStatementSetter pss = new ArgumentPreparedStatementSetter(parameters.toArray());

		this.jdbcOperations.update(SAVE_AUTHORIZED_CLIENT_SQL, pss);
}
```

2. [JdbcTemplate](https://github.com/spring-projects/spring-framework/blob/5.2.x/spring-jdbc/src/main/java/org/springframework/jdbc/core/JdbcTemplate.java):
2.1 in 
_protected int update(final PreparedStatementCreator psc, @Nullable final PreparedStatementSetter pss)_ line: **862**:
`return updateCount(execute(psc, ps -> {`
2.2 in 
_public <T> T execute(PreparedStatementCreator psc, PreparedStatementCallback<T> action)_ line **617**:
`T result = action.doInPreparedStatement(ps);`

caused: ` ClassCastException: [B cannot be cast to oracle.sql.BLOB`

**Comment by jgrandja** [comment]
@Taraskin Have you tried configuring a custom mapper via `JdbcOAuth2AuthorizedClientService.setAuthorizedClientParametersMapper()`?

As mentioned in this [comment](https://github.com/spring-projects/spring-security/issues/8539#issuecomment-631030998):

> It is very difficult to provide an implementation that works out of the box for all databases. This implementation strives to use standard sql datatypes and is a simplified JDBC implementation. However, it is designed to be customizable so user's can provide customizations for database vendors that deviate from the standard sql types.

Providing a custom `JdbcOAuth2AuthorizedClientService.setAuthorizedClientParametersMapper()` is the solution for the issue you are facing.

I'm going to close this but if you are still having issues after you have tried out the proposed solution we can re-open and discuss further.

**Comment by Taraskin** [comment]
@jgrandja Yes, I've already used this way to solve an issue. Thank you for a response.
