### ISSUE TITLE
InitializeUserDetailsBeanManagerConfigurer#InitializeUserDetailsManagerConfigurer.getBeanOrNull optimization

### ISSUE THREAD

**Issue by dawn9117** [spring-projects/spring-security#8866]
**Expected Behavior**
When multiple UserDetailsServices found, throw NoUniqueBeanDefinitionException.

**Current Behavior**
When I registered more than one UserDetailsService, InitializeUserDetailsBeanManagerConfigurer#InitializeUserDetailsManagerConfigurer.getBeanOrNull returned null.

**Comment by rwinch** [comment]
Please provide more details around when and why you would want this to happen.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
