### ISSUE TITLE
Make class public: LazyPasswordEncoder, DefaultPasswordEncoderAuthenticationManagerBuilder

### ISSUE THREAD

**Issue by dawn9117** [spring-projects/spring-security#8869]
Make class public: LazyPasswordEncoder, DefaultPasswordEncoderAuthenticationManagerBuilder

**Comment by rwinch** [comment]
Can you explain why you think this should be changed?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
