### ISSUE TITLE
Add hasAnyAuthority(String...) and hasAnyRole(String...) to authorizeRequests in Kotlin DSL

### ISSUE THREAD

**Issue by koishikawa11** [spring-projects/spring-security#8892]
**Expected Behavior**

The Kotlin DSL has methods for conveniently specifying the access `hasAuthority(String)` and `hasRole(String)` in `authorizeRequests`.
I think it would be convenient to have method for `hasAnyAuthority(String...)` and `hasAnyRole(String...)`.

**Current Behavior**

In the current version it is necessary to create access like `"hasAnyAuthority('$anyAuthorities')"`.

**Comment by eleftherias** [comment]
Thanks for the suggestiong @koishikawa11.
Are you interested in submitting a pull request for this feature?

**Comment by koishikawa11** [comment]
Yes, I would like to create a pull request.
