### ISSUE TITLE
Make #oauth2. expressions compatible with JwtAuthenticationToken

### ISSUE THREAD

**Issue by JayChandler** [spring-projects/spring-security#8895]
**Expected Behavior**

OAuth2MethodSecurityExpressionHandler should work with JwtAuthenticationToken

**Current Behavior**

Currently there is a check in OAuth2ExpressionUtils 

`if (authentication instanceof OAuth2Authentication)` which prevents the #oauth2 expressions to work on jwt tokens

@PreAuthorize("#oauth2.hasAnyScope('dealer:read', 'api:admin')") 
won't work but this will
@PreAuthorize("hasAnyAuthority('SCOPE_dealer:read', 'SCOPE_api:admin')")

**Comment by jzheaux** [comment]
Thanks for the suggestion, @JayChandler. However, [`OAuth2MethodSecurityExpressionHandler` is from the deprecated Spring Security OAuth project](https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/expression/OAuth2MethodSecurityExpressionHandler.java#L27), and there's no intention to port over this feature to Spring Security proper.

It's advised that you just use Spring Security from this point onward as well as the default expressions (`hasAnyAuthority`, etc.).

If you are migrating from Spring Security OAuth to Spring Security, then [wiring your own expression handler](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#globalmethodsecurityconfiguration) may simplify the transition.

Or, you can achieve comparable behavior by publishing a bean and referencing it in your expressions:

```java
@Bean 
public MyOAuth2ExpressionsBean oauth2() {
    // ...
}

// ...

@PreAuthorize("@oauth2.hasAnyScope(...)")
```
