### ISSUE TITLE
Open cross-domain and 500 at the same time

### ISSUE THREAD

**Issue by An0nymous0** [spring-projects/spring-security#8904]
**Describe the bug**
500 does not return cross-domain related header information

**To Reproduce**
1. 
```
 @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.cors().and()
                .csrf().disable()
                .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS).and()
                .authorizeRequests()
                .requestMatchers(CorsUtils::isPreFlightRequest).permitAll()
                .antMatchers("/**").permitAll()
                .anyRequest().authenticated()
    }
```
2.
```
    @Bean
    CorsConfigurationSource corsConfigurationSource() {
        final UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        source.registerCorsConfiguration("/**", new CorsConfiguration().applyPermitDefaultValues());
        return source;
    }
```
3. Request an interface where an exception occurs

4. Missing cross-domain http header
status code 500:
![image](https://user-images.githubusercontent.com/6836030/89300160-5d7cf780-d69a-11ea-99ed-13462528ab6e.png)
---
![image](https://user-images.githubusercontent.com/6836030/89300253-7d142000-d69a-11ea-8fae-c0aeb268db42.png)

**Expected behavior**
status code 404:
![image](https://user-images.githubusercontent.com/6836030/89300288-8c936900-d69a-11ea-994f-c6e47a14206a.png)

**Comment by jzheaux** [comment]
Thanks for the report, @An0nymous0. I think the situation would be clearer if you could supply a minimal sample. Are you able to do that?
