### ISSUE TITLE
SEC-631: form-login page doesn't use spring messageSource for i18n translations

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#891]
["Noah Levitt":https://jira.spring.io/secure/ViewProfile.jspa?name=nlevitt](Migrated from ["SEC-631":https://jira.spring.io/browse/SEC-631?redirect=false]) said:

I'm using latest daily snapshot of spring-security with spring 2.5.1.

form-login page doesn't use spring messageSource for translations. 

Other jsp's get translated messages successfully, but my form-login page doesn't. 

I can get translations using fmt:setBundle, but then I don't get to use the nice stuff spring does.

**Comment by spring-issuemaster** [comment]
This issue is related to https://jira.spring.io/browse/SPR-487
This issue is related to #761

**Comment by spring-issuemaster** [comment]
This issue is related to https://jira.spring.io/browse/SPR-487
This issue is related to #761

**Comment by spring-issuemaster** [comment]
This issue is related to https://jira.spring.io/browse/SPR-487
This issue is related to #761

**Comment by spring-issuemaster** [comment]
This issue is related to https://jira.spring.io/browse/SPR-487
This issue is related to #761

**Comment by spring-issuemaster** [comment]
This issue is related to https://jira.spring.io/browse/SPR-487
This issue is related to #761
