### ISSUE TITLE
NoClassDefFoundError: AuthMetadataFlyweight at o.s.s.r.m.SimpleAuthenticationEncoder

### ISSUE THREAD

**Issue by bclozel** [spring-projects/spring-security#8948]
As of RSocket 1.1.0 (see rsocket/rsocket-java#906), the previously deprecated `Flywheight` classes have been removed.
Spring Framework requires RSocket 1.0+ as a result as of Spring Framework 5.3 (see spring-projects/spring-framework#25548).

Right now [a smoke test still fails in Spring Boot](spring-projects/spring-boot#22725) with the following:

```
java.lang.NoClassDefFoundError: io/rsocket/metadata/security/AuthMetadataFlyweight
	at org.springframework.security.rsocket.metadata.SimpleAuthenticationEncoder.encodeValue(SimpleAuthenticationEncoder.java:71) ~[spring-security-rsocket-5.4.0-RC1.jar:5.4.0-RC1]
```

**Comment by jzheaux** [comment]
Fixed via 94cf4d1de7b6df95482d1fc65fdc024816733296 and 1069e91645504b703b0826f4709813795960e2f3
