### ISSUE TITLE
Incomplete documentation about session management using java configuration

### ISSUE THREAD

**Issue by havinhphu188** [spring-projects/spring-security#8979]
https://docs.spring.io/spring-security/site/docs/5.3.4.RELEASE/reference/html5/#session-mgmt

Spring Security supports XML configuration and Java configuration. 
But in this section (session management), there is only documentation using XML configuration

**Comment by rwinch** [comment]
Thanks @havinhphu188 Would you be interested in submitting a PR?

**Comment by akohli96** [comment]
Hello @rwinch , may I take this?

**Comment by rwinch** [comment]
Please do!
