### ISSUE TITLE
Clickjacking demo in docs: YouTube link in X-Frame-Options section leads to private video

### ISSUE THREAD

**Issue by Grez** [spring-projects/spring-security#8986]
In section Section [5.2.2 Security HTTP Response Headers > X-Frame-Options](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#headers-frame-options) there is link that leads to private video.

> For example, using clever CSS styling users could be tricked into clicking on something that they were not intending ([video demo](https://www.youtube.com/watch?v=3mk0RySeNsU)).

<img width="998" alt="Screenshot 2020-08-27 at 23 46 01" src="https://user-images.githubusercontent.com/638592/91498113-7d7d9080-e8bf-11ea-9bcd-c482e9dc318d.png">

**Comment by eleftherias** [comment]
Thanks @Grez! This is now fixed.
