### ISSUE TITLE
Simplify saml2Login Samples

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#8990]
Let's simplify the Boot and JavaConfig saml2Login samples to not sign AuthnRequests.

Let's also simplify their `RelyingPartyRegistrationRepository` configuration.

**Comment by dawi** [comment]
I am currently trying to migrate from https://spring.io/projects/spring-security-saml to the new spring security saml integration, but I am getting endless redirects after the IDP login. Now I have seen, this simplification and gave it another try, but I am still facing the endless redirects. Maybe it would be great to provide a minimal Keycloak example as well. :)

**Comment by jzheaux** [comment]
Hi, @dawi, sorry to hear you're having trouble. 

I've recently tested the existing Boot sample against a local Keycloak instance using Spring Security 5.4.1, and I was able to do it without specialized configuration. Because of that, I'm not sure that a new sample will help much.

Two things might help here for your situation, though. 

First, endless redirects are usually caused when the relying party errors during authentication and forwards to `/error` to show the error message. `/error`, like all endpoints, is protected by default, so Spring Security redirects to Keycloak again. And, because the asserting party knows you're logged in, it redirects back, and the loop restarts. Often, this loop can be broken by adding `.antMatchers("/error").permitAll()` to your `authorizeRequests` configuration.

Second, increase your logs `org.springframework.security` to `DEBUG` and `org.springframework.security.saml2` to `TRACE`. The additional information may help to see what is failing when your relying party receives a SAML assertion.

**Comment by dawi** [comment]
Hi @jzheaux, thank you for your quick response. :)

You are right, the redirect loop is caused by forwarding to `/error`.

Therefore I have updated the configuration of my minimal example as follows:

```
protected void configure(HttpSecurity http) throws Exception {
    http
        .authorizeRequests().antMatchers("/error").permitAll().and()
        .authorizeRequests().anyRequest().authenticated().and()
        .saml2Login()
    ;
}
```

After login, I now the Browser displays "http://localhost:8080/saml/SSO" with a Whitelabel Error Page:

> Whitelabel Error Page
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> 
> Wed Oct 14 20:50:59 CEST 2020
> There was an unexpected error (type=Forbidden, status=403).

I also adjusted the log levels as you suggested, but I still have no clue, what the issue could be. :/

Suspicious logs are:

```
CsrfFilter: Invalid CSRF token found for http://localhost:8080/saml/SSO
SignatureSupport: No KeyInfoGenerator was supplied in parameters or resolveable for credential type org.opensaml.security.x509.X509Credential, No KeyInfo will be generated for Signature
```

But I am not sure if they are real issues. :/

I still believe that a working minimal example would be helpful. :)

**Comment by jzheaux** [comment]
Glad you got it working, @dawi. 

Correct, unless you are customizing the endpoint where your application wants to receive assertions, setting the `assertionConsumerServiceLocation` is unnecessary.
