### ISSUE TITLE
SEC-640: Add namespace support for FilterInvocationDefinitionSource configuration

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#900]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-640":https://jira.spring.io/browse/SEC-640?redirect=false]) said:

This would be similar to the filter-chain-map used to configure FilterChainProxy and would allow classes like FilterInvocationDefinitionSourceEditor to be deprecated.

**Comment by spring-issuemaster** [comment]
This issue is related to #792
