### ISSUE TITLE
Inconsistent version naming for Spring Security Core 5.4.0

### ISSUE THREAD

**Issue by veita** [spring-projects/spring-security#9010]
**Describe the bug**
Version 5.4.0 of Spring Security Core is named `5.4.0` whereas the versions before, like other Spring libraries, had the version number suffix `.RELEASE`, e.g. `5.3.4.RELEASE`. I wonder if 5.4.0 is indeed a release version. ;-)

**To Reproduce**
Go to https://repo1.maven.org/maven2/org/springframework/security/spring-security-core/

**Expected behavior**
I expected the version number `5.4.0.RELEASE`

**Comment by jgrandja** [comment]
@veita The versioning scheme for Spring projects recently changed so 5.4.0 is correct as releases no longer specify a modifier, eg. `RELEASE`.

Please see this [post](https://spring.io/blog/2020/04/30/updates-to-spring-versions) for further details.
