### ISSUE TITLE
Add <saml2-login> support in xml configuration

### ISSUE THREAD

**Issue by amergey** [spring-projects/spring-security#9012]
**Expected Behavior**

Similarly to oauth2-login, it should be possible to configure saml2-login in xml.

We would need something like this 

```
<http>
       <saml2-login authentication-manager-ref="xxxxx" relying-party-registration-repository-ref="xxxxx">
</http>
```

to be able to configure spring security similarly to what is done with boot. Of course authentication-manager-ref or relying-party-registration-repository-ref would be optional as described in documentation configuring in java with spring-boot.

**Current Behavior**

Currently we do not know how to configure saml with xml in spring-security without spring-boot

**Comment by abhishek-bafna-amdhan** [comment]
@marcusdacoregio It is still unclear how to configure relying-party-registration-repository-ref
