### ISSUE TITLE
set failureHandler do not redirect /login?error and show error message

### ISSUE THREAD

**Issue by swiftloop** [spring-projects/spring-security#9015]
**Describe the bug**
 formLogin().failureHandler() method  set FormLoginConfigurer field `failureUrl`  null,so, I do not redirect /login?error and show error message.

`	public final T failureHandler( 
			AuthenticationFailureHandler authenticationFailureHandler) {
		this.failureUrl = null;
		this.failureHandler = authenticationFailureHandler;
		return getSelf();
	}
`

**Comment by eleftherias** [comment]
@swiftloop Could you please provide some more information?

What is the expected behaviour and how does that compare to the behaviour that you are seeing?

**Comment by swiftloop** [comment]
![image](https://user-images.githubusercontent.com/16313995/93446958-67824f00-f904-11ea-9b1e-27316f56eae0.png)
![image](https://user-images.githubusercontent.com/16313995/93447113-a1ebec00-f904-11ea-8a78-2dff2afcbde0.png)
In the DefaultLoginPageGeneratingFilter.
![image](https://user-images.githubusercontent.com/16313995/93447393-ef685900-f904-11ea-999c-c048b296a2a7.png)

I expect:
![image](https://user-images.githubusercontent.com/16313995/93448236-f479d800-f905-11ea-937e-8a7e6df83f53.png)

but:
 is 302 redirected to login

What should I do?

**Comment by eleftherias** [comment]
@swiftloop The `failureUrl` is intended to be `null` if you set a custom `failureHandler`.

It seems like you need to permit all users to access the URL that your failure handler is redirecting to.

For example, if you wanted to use a failure handler that redirects to "/login-failure"
<pre>
http
	.authorizeRequests((authorize) -> authorize
		<b>.mvcMatchers("/login-failure").permitAll()</b>
		.anyRequest().authenticated()
	)
	.formLogin((formLogin) -> formLogin
		.failureHandler(new SimpleUrlAuthenticationFailureHandler("/login-failure"))
	);
</pre>

Also, note that the default failure URL is "/login?error".

**Comment by swiftloop** [comment]
Emmm, thanks for your suggestion.
 Acually, the thing that I want is when there is a verification error, which can redirect to login and show error message (such as "Bad Credentials") on the default login page.
 However, after setting "failureHandler", it cannot show error message. Because "failureUrl" is null and "isErrorPage" in "DefaultLoginPageGeneratingFilter" is false now.
 So shall I need to use customized UI to solve this problem?

before setting "failureHandler":
![image](https://user-images.githubusercontent.com/16313995/93547130-ef189e00-f996-11ea-988a-2049d3f78925.png)


after setting "failureHandler":
![image](https://user-images.githubusercontent.com/16313995/93547070-d14b3900-f996-11ea-955b-def920a49620.png)

**Comment by eleftherias** [comment]
@swiftloop 
As you mention, if you set a custom `failureHandler`, Spring Security removes the default authentication failure behaviour, because it assumes you are doing something custom.

Could you share some more details on what you are trying to accomplish by customizing the `failureHandler`?
It seems like the default behaviour might be suitable for your use case.

**Comment by swiftloop** [comment]
It turns out that I didn't follow the rules of spring security. count the number of verification error and  disable user account
