### ISSUE TITLE
JdbcOAuth2AuthorizedClientService is dependend on non-standard driver behaviour

### ISSUE THREAD

**Issue by queueseven** [spring-projects/spring-security#9023]
**Describe the bug**
I'm using the `JdbcOAuth2AuthorizedClientService` with the [MariaDB java connector](https://github.com/mariadb-corporation/mariadb-connector-j). Authorization fails with a `SQLSyntaxErrorException`:

> Can only convert a byte[] to BINARY, VARBINARY or LONGVARBINARY

**To Reproduce**
Use the `JdbcOAuth2AuthorizedClientService` with the [MariaDB java connector](https://github.com/mariadb-corporation/mariadb-connector-j).

**Expected behavior**
No exception should be thrown.

The problem is these two lines:

> parameters.add(new SqlParameterValue(Types.BLOB, accessToken.getTokenValue().getBytes(StandardCharsets.UTF_8)));

> parameters.add(new SqlParameterValue(Types.BLOB, refreshTokenValue));

According to the JDBC specification, a driver has to implement conversions between `byte[] <=> BINARY, VARBINARY, LONGVARBINARY` and `java.sql.Blob <=> BLOB`. While some drivers implement a conversion between `byte[]` and `BLOB`, it's a non-standard behaviour and you can't rely on it.

So, in this case, the `byte[]`s should be wrapped in an appropriate `java.sql.Blob` type.

**Comment by jgrandja** [comment]
@queueseven Please see this [comment](https://github.com/spring-projects/spring-security/issues/8862#issuecomment-661955579) and this [one](https://github.com/spring-projects/spring-security/issues/8539#issuecomment-631030998). You need to provide a custom configuration of `JdbcOAuth2AuthorizedClientService`.

I'm going to close this as a duplicate.
