### ISSUE TITLE
Include Port in DNS SRV type lookups

### ISSUE THREAD

**Issue by KathrynN** [spring-projects/spring-security#9030]
**Expected Behavior**

JndiDnsResolver should be all I need to discover a service given the domain and service-type.

**Current Behavior**

JndiDnsResolver only gives me the service hostname / ip address, but not which port.

**Context**

I'm building a system using SRV DNS service discovery with randomly assigned ports (to allow multiple services to be able to stack on one server).  This non-static port means that I have to rewrite the JndiDnsResolver myself to capture the port, even though the JndiDnsResolver has the method to do it.

I think it would be a quick fix, and am happy to share what I've done, which will add an additional method to the JndiDnsResolver that also captures the port without changing the result for older methods.

Or, if anyone knows if this is already implemented and I'm using the wrong version of spring boot security, let me know that too! 👍 
```
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-remoting</artifactId>
            <version>5.3.4.RELEASE</version>
        </dependency>
```

**Comment by eleftherias** [comment]
@KathrynN That makes sense to me.

Are you interested in submitting a pull request with your changes?

**Comment by KathrynN** [comment]
Absolutely!  I will send it up over the weekend (I'm not feeling very well today).  Thanks!

**Comment by KathrynN** [comment]
I have popped in a pull request (as you can see above!) but I can't build the master branch on my machine, let alone run the tests.  I will try to have a go over next week when I have recovered enough to wrangle gradle into submission.
