### ISSUE TITLE
5.4.0 Inconsistent version naming

### ISSUE THREAD

**Issue by ufo525** [spring-projects/spring-security#9033]
**Describe the bug**
I am not sure whether this is an intended change or bug.

**To Reproduce**
https://mvnrepository.com/artifact/org.springframework.security/spring-security-core

5.4.0 didn't follow the previous x.x.x.RELEASE naming convention

**Comment by jzheaux** [comment]
Thanks for checking, @ufo525. This is a duplicate of #9010, please see the details there.
