### ISSUE TITLE
SEC-646: can't get @Secured annotations to work  using spring-security in a spring-2.5 app

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#907]
["Cameron Braid":https://jira.spring.io/secure/ViewProfile.jspa?name=cameronbraid](Migrated from ["SEC-646":https://jira.spring.io/browse/SEC-646?redirect=false]) said:

I'm using security:annotation-driven/

Here is the error message :

[22:35:21]WARN  [AbstractSecurityInterceptor] Could not validate configuration attributes as the ObjectDefinitionSource did not return a ConfigAttributeDefinition Iterator

NOTE : There is a binary incompatability between spring-security between spring 2.0 and spring-2.5.  Rather than compiling spring-security against the spring-2.5 jars I made a patch to change spring-security so that when compiled against spring-2.0, it is binary compatible with spring-2.5.  See http://jira.springframework.org/browse/SEC-627

If you apply the patch on that task, you can get spring-security running with spring 2.5, then you can run my demo app which I will attach in a zip

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-4459

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-4459

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-4459

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-4459

**Comment by spring-issuemaster** [comment]
This issue depends on https://jira.spring.io/browse/SPR-4459
