### ISSUE TITLE
Create a Spring Security Cookbook

### ISSUE THREAD

**Issue by Buzzardo** [spring-projects/spring-security#9139]
**Expected Behavior**

Describe common scenarios that users of Spring Security encounter and show solutions for those scenarios.

**Current Behavior**

We do not have a cookbook at present.

**Context**

Some people benefit from a cookbook style of presentation. Hopefully, we can help a few more users than we would otherwise.

**Comment by Buzzardo** [comment]
PR 9140 has a first draft.

https://github.com/spring-projects/spring-security/pull/9140

**Comment by rwinch** [comment]
Closing for the same reasons mentioned in the PR
