### ISSUE TITLE
Exposing Beans for defaultMethodExpressionHandler can prevent Method Security #4020 - IS BACK

### ISSUE THREAD

**Issue by spolito** [spring-projects/spring-security#9142]
I find that this previously closed issue #4020 is back.  https://github.com/spring-projects/spring-security/issues/4020

It appears to be the same except that I only have trouble with one specific Repo, which happens to be of the same entity type as the entity that TargetedPermissionEvaluator is protecting.  The repo in question is autowired.  When I comment it out the TargetedPermissionEvaluator works as expected.  But when the repo is active, the TargetedPermissionEvaluator will fail silently.  The failure is that it is not invoked and acts as if there is no security at all.

I am running the following versions:
<spring-boot.version>2.2.5.RELEASE</spring-boot.version>
<hibernate.version>5.4.12.Final</hibernate.version>

IDE is Eclipse 2020-03 (4.15.0)  Build id: 20200313-1211

**Comment by jgrandja** [comment]
@spolito Can you please provide a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue and publish it to a GitHub repo. This will help us troubleshoot the issue.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by spolito** [comment]
I am sorry that I have not responded.   I can easily recreate the issue,
but our project is massive and I am not sure how to trim it down to
something useful to you.  Do you need a running, standalone project, or can
I just send you certain files?   Can you let me know what you feel like you
need?

For now, I can attach our POM and some of the files used in the scenario.
Can I email them to this address?
