### ISSUE TITLE
Unable to set refresh token expiry time when building OAuth2AccessTokenResponse

### ISSUE THREAD

**Issue by spc16670** [spring-projects/spring-security#9148]
I am implementing OAuth2AccessTokenResponseClient and I do not see a way of setting refresh token expiry time on OAuth2AccessTokenResponse...

**Describe the bug**
Unable to set refresh token expiry time when building OAuth2AccessTokenResponse

**To Reproduce**
OAuth2AccessTokenResponse.withToken(accessToken)
                .expiresIn(expiresIn)
                .refreshToken(refreshToken).build();

**Expected behavior**
OAuth2AccessTokenResponse.withToken(accessToken)
                .expiresIn(expiresIn)
                .refreshToken(refreshToken)
                .refreshTokenExpiresIn(refreshTokenExpiresIn)
                .build();

**Comment by jgrandja** [comment]
@spc16670 This was just added last week. See #9146
