### ISSUE TITLE
Allow to configure the header value as a regular expression pattern in a request matcher

### ISSUE THREAD

**Issue by ShivakumarSwamy** [spring-projects/spring-security#9180]
**Expected Behavior**

Allow to configure the expected header value as a regular expression pattern in a request matcher regardless of the http method. Similar to `RegexRequestMatcher`

**Current Behavior**

Currently, `RequestHeaderRequestMatcher` allows to match an expected header value as String. 

**Context**

***What are you trying to accomplish?***
Recently, came across a requirement which required to match the expected header value with a regular expression pattern, in-order to support custom token(s) with custom scheme(s) in `Authorization` header.

**Comment by eleftherias** [comment]
Thanks for reaching out @ShivakumarSwamy.

In this situation, I suggest creating a custom `RequestMatcher`.
Within the Spring Security codebase, we have a similar situation where we match the "Bearer" scheme and for that we created a `BearerTokenRequestMatcher`.

I'm going to close this issue, but feel free to continue the discussion here if you run into problems.
