### ISSUE TITLE
Match requests based on servlet dispatcher type

### ISSUE THREAD

**Issue by eleftherias** [spring-projects/spring-security#9205]
Add a matcher to match requests and apply security rules based on the servlet Dispatcher type (FORWARD,INCLUDE,REQUEST,ASYNC,ERROR).

**Context**

This will allow users to define what happens in the case of an ERROR dispatch. 
This may help in cases such as gh-9181.

**Comment by nmck257** [comment]
Created PR #9278 - let me know if I missed any functionality?
