### ISSUE TITLE
OAuth2AuthorizationRequest additionalParameters urlencoding

### ISSUE THREAD

**Issue by pyorama** [spring-projects/spring-security#9213]
**Describe the bug**
Got invalid url If defining for example json-string as additional parameter for OAuth2AuthorizationRequest.
In addition if defining already urlencoded parameter for OAuth2AuthorizationRequest - still got invalid url because the parameter is now urlencoded again.

**To Reproduce**

Case 1:
Define custom oauth authorization requst with extra parameter as described in: https://www.baeldung.com/spring-security-custom-oauth-requests
Add parameter 'claims' with value: '{"userinfo":{"name":null}}'

-> the resulting redirect url is invalid because the claims parameter value is not urlencoded

Case 2:
Define custom oauth authorization requst with urlencoded parameter.
Add parameter 'claims' with value: '%7B%22userinfo%22%3A%7B%22name%22%3Anull%7D%7D'

-> the resulting redirect url is invalid because the claims parameter is now double urlencoded as: 
  claims=%257B%2522userinfo%2522%253A%257B%2522name%2522%253Anull%257D%257D

**Expected behavior**
Setting extra parameter should produce valid urlencoded request parameter for the redirect url.

**Sample**

**Comment by jgrandja** [comment]
@pyorama This has already been resolved via #7871. See this test:
https://github.com/spring-projects/spring-security/blob/2abf59b695b3ad14719299ed17ff47b181eed802/oauth2/oauth2-core/src/test/java/org/springframework/security/oauth2/core/endpoint/OAuth2AuthorizationRequestTests.java#L334
