### ISSUE TITLE
Add permissionsPolicy header in HeadersConfigurers

### ISSUE THREAD

**Issue by kris2kris** [spring-projects/spring-security#9262]
Hello,

The http header Feature-Policy has been renamed to Permissions-Policy (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy).
HeadersConfigurers must be changed to add the correct header.

Kind regards
Chris

**Comment by eleftherias** [comment]
Thanks @kris2kris.

Instead of replacing feature-policy, we should allow both feature-policy and permissions-policy for backwards compatibility.

Are you interested in creating a pull request to add the feature-policy header to the configurer?

**Comment by kris2kris** [comment]
Hi  @eleftherias 

I was not sure between replace or add because it could be a security problem if people are not aware that their headers are not correct... but I'm ok to not remove feature-policy
I will make a merge request when I can, probably this weekend

**Comment by eleftherias** [comment]
Thanks @kris2kris!

We can deprecate feature-policy and add a warning to let users know that they should use permissions-policy instead.

Feel free to reach out if you have any questions.

**Comment by eleftherias** [comment]
Closed via #9265
