### ISSUE TITLE
Add AuthorizationDecision to Authorization events

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#9286]
It would be nice if `AuthorizationFailureEvent` and `AuthorizedEvent` each held a reference to the `AuthorizationDecision` that was made.

The new constructor should not take a `Collection` of `ConfigAttribute`s.

**Comment by parikshitdutta** [comment]
Thanks @jzheaux for assigning #9288 and pointing me to this one.

I was thinking to keep reference of ```Authentication``` in event classes. To my understanding, ```AuthorizationSuccessEvent``` should be raised if ```AuthorizationDecision.isGranted()```, otherwise ```AuthorizationFailureEvent``` should be raised.

I mean, either it is ```granted``` or not, there is nothing more in ```AuthorizationDecision```.

Please share your thought.

**Comment by jzheaux** [comment]
> I mean, either it is granted or not, there is nothing more in AuthorizationDecision.

Since `AuthorizationDecision` can be subclassed, we can't say that there is nothing more in it.

For example, if you take a look at https://github.com/spring-projects/spring-security/issues/9287, there's value in including the reasons that an authorization decision was made.

**Comment by parikshitdutta** [comment]
> Since `AuthorizationDecision` can be subclassed, we can't say that there is nothing more in it.

Totally! as an after-thought I knew it coming :), thanks for sharing your thought. 
Please assign this to me as well.
