### ISSUE TITLE
DelegatingAuthorizationManager Should Fire Events

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#9288]
Firing success and failure events from `DelegatingAuthorizationManager` would simplify auditing. `AuthorizationSuccessEvent` and `AuthorizationFailureEvent` should be suitable.

**Comment by parikshitdutta** [comment]
Hi @jzheaux,
Please assign me the task, I can take it.

Thank you.

**Comment by jzheaux** [comment]
Thanks, @parikshitdutta, it's yours!

I think you may want to consider #9286 as well.

**Comment by parikshitdutta** [comment]
Hi @jzheaux, Please have a look at my submitted PR #9527, I will look forward to your feedback.

Thank you.
