### ISSUE TITLE
gradle install cannot download  org.bouncycastle:bcpkix-jdk15on, reason HTTP:401

### ISSUE THREAD

**Issue by debrutal** [spring-projects/spring-security#9308]
**Describe the bug**
I am not sure about the location of this ticket, since the reason is a 401 on `https://repo.spring.io`.

Building the project like instructed using `gradlew install` fails due to unauthenticated access on dependency org.bouncycastle:bcpkix-jdk15on.

stacktrace from `gradlew install`

`
gradlew install
> Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
> Task :spring-security-crypto:compileJava FAILED

> FAILURE: Build failed with an exception.

> What went wrong:
> Execution failed for task ':spring-security-crypto:compileJava'.
> Could not resolve all files for configuration ':spring-security-crypto:optional'.
   > Could not resolve org.bouncycastle:bcpkix-jdk15on:1.+.
     Required by:
         project :spring-security-crypto
      > Failed to list versions for org.bouncycastle:bcpkix-jdk15on.
         > Unable to load Maven meta-data from https://repo.spring.io/libs-snapshot/org/bouncycastle/bcpkix-jdk15on/maven-metadata.xml.
            > Could not get resource 'https://repo.spring.io/libs-snapshot/org/bouncycastle/bcpkix-jdk15on/maven-metadata.xml'.
               > Could not GET 'https://repo.spring.io/libs-snapshot/org/bouncycastle/bcpkix-jdk15on/maven-metadata.xml'. Received status code 401 from server: Unauthorized

> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to 
> get full insights.

> * Get more help at https://help.gradle.org

> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings

> BUILD FAILED in 49s
> 3 actionable tasks: 3 executed

> A build scan cannot be produced as an error occurred gathering build data.
> Please report this problem via https://ge.spring.io/help and include the following via copy/paste:
> 
> ----------
> Gradle version: 6.7.1
> Plugin version: 3.2
> 
> org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':spring-security-crypto:optional'.
>         at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.wrapException(ErrorHandlingConfigurationResolver.java:104)
>         at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.access$000(ErrorHandlingConfigurationResolver.java:48)
>         at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getRoot(ErrorHandlingConfigurationResolver.java:203)
>         at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationResult.getRootComponent(Resolve> ConfigurationResolutionBuildOperationResult.java:59)
>         at com.gradle.scan.plugin.internal.b.e.a.h$a.b(SourceFile:116)
>         at com.gradle.scan.plugin.internal.b.e.a.h$a.a(SourceFile:70)
>         at com.gradle.scan.plugin.internal.b.e.a.h.a(SourceFile:51)
>         at com.gradle.scan.plugin.internal.b.e.a.g.a(SourceFile:149)
>         at com.gradle.scan.plugin.internal.b.e.c.a(SourceFile:142)
>         at com.gradle.scan.plugin.internal.k.a.f.a(SourceFile:12)
>         at com.gradle.scan.plugin.internal.k.a$c.finished(SourceFile:154)
>         at com.gradle.scan.plugin.internal.k.a.a(SourceFile:65)
>         at com.gradle.scan.plugin.internal.k.j.a(SourceFile:58)
>         at com.gradle.scan.plugin.internal.k.d.a(SourceFile:103)
>         at com.gradle.scan.plugin.internal.k.f.a(SourceFile:48)
>         at com.gradle.scan.plugin.internal.p.a$a.a(SourceFile:31)
>         at com.gradle.scan.plugin.internal.p.a$a.a(SourceFile:20)
>         at com.gradle.scan.plugin.internal.p.a.c(SourceFile:67)
> Caused by: java.lang.RuntimeException: Problems reading data from Binary store in /tmp/gradle2657087511002168528.bin offset 9096 exists? true
>         at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:132)
>         at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.lambda$create$0(StreamingResolutionResultBuilder.java:188)
>         at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory$SimpleStore.load(CachedStoreFactory.java:101)
>         at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:186)
>         at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.create(StreamingResolutionResultBuilder.java:158)
>         at org.gradle.api.internal.artifacts.result.DefaultResolutionResult.getRoot(DefaultResolutionResult.java:48)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver$ErrorHandlingResolutionResult.getRoot(ErrorHandlingConfigurationResolver.java:201)
>         at org.gradle.api.internal.artifacts.configurations.ResolveConfigurationResolutionBuildOperationResult.getRootComponent(ResolveConfigurationResolutionBuildOperationResult.java:59)
>         at com.gradle.scan.plugin.internal.b.e.a.h$a.b(SourceFile:116)
>         at com.gradle.scan.plugin.internal.b.e.a.h$a.a(SourceFile:70)
>         at com.gradle.scan.plugin.internal.b.e.a.h.a(SourceFile:51)
>         at com.gradle.scan.plugin.internal.b.e.a.g.a(SourceFile:149)
>         at com.gradle.scan.plugin.internal.b.e.c.a(SourceFile:142)
>         at com.gradle.scan.plugin.internal.k.a.f.a(SourceFile:12)
>         at com.gradle.scan.plugin.internal.k.a$c.finished(SourceFile:154)
>         at com.gradle.scan.plugin.internal.k.a.a(SourceFile:65)
>         at com.gradle.scan.plugin.internal.k.j.a(SourceFile:58)
>         at com.gradle.scan.plugin.internal.k.d.a(SourceFile:103)
>         at com.gradle.scan.plugin.internal.k.f.a(SourceFile:48)
>         at com.gradle.scan.plugin.internal.p.a$a.a(SourceFile:31)
>         at com.gradle.scan.plugin.internal.p.a$a.a(SourceFile:20)
>         at com.gradle.scan.plugin.internal.p.a.c(SourceFile:67)
> Caused by: java.lang.IllegalStateException: Corrupt serialized resolution result. Cannot find selected module (19) for optional -> org.bouncycastle:bcpkix-jdk15on
>         at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.DefaultResolutionResultBuilder.visitOutgoingEdges(DefaultResolutionResultBuilder.java:83)
>         at org.gradle.api.internal.artifacts.ivyservice.resolveengine.result.StreamingResolutionResultBuilder$RootFactory.deserialize(StreamingResolutionResultBuilder.java:238)
>         at org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.DefaultBinaryStore$SimpleBinaryData.read(DefaultBinaryStore.java:130)
>         ... 21 more
`

**To Reproduce**

* option 1
Visit `https://repo.spring.io/libs-snapshot/org/bouncycastle/bcpkix-jdk15on/maven-metadata.xml`

* option 2
`curl https://repo.spring.io/libs-snapshot/org/bouncycastle/bcpkix-jdk15on/maven-metadata.xml`

* option 3
```shell
git clone git@github.com:spring-projects/spring-security.git
cd spring-security
gradlew install
```
 
**Expected behavior**

Dependency should be downloaded

**Sample**

**Comment by jzheaux** [comment]
I believe this will be resolved with https://github.com/spring-gradle-plugins/spring-build-conventions/issues/90

**Comment by marcusdacoregio** [comment]
Hi @debrutal. Did the problem gets resolved?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
