### ISSUE TITLE
@Nullable @NonNull partial patches?

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-security#9312]
are partial  patches welcome for adding `org.springframework.lang.Nullable` and `org.springframework.lang.NonNull`?. If so are they to be applied to a classes published interface? package private methods? should they both be applied? or just one or the other?

**Comment by jzheaux** [comment]
Could be a duplicate of https://github.com/spring-projects/spring-security/issues/8389, so we should likely coordinate over there.

**Comment by xenoterracide** [comment]
yeah, seems about the same.
