### ISSUE TITLE
Spring Security MessageSource files lack of 'ExceptionTranslationFilter.insufficientAuthentication'

### ISSUE THREAD

**Issue by Venus-WXP** [spring-projects/spring-security#9315]
this.messages.getMessage("`ExceptionTranslationFilter.insufficientAuthentication`", "Full authentication is required to access this resource")
All of messages_locale.properties files lack of this item.

**Comment by jzheaux** [comment]
Good catch, @Venus-WXP! Are you able to contribute any translations in a PR?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by sjohnr** [comment]
Hi @Venus-WXP,

Looking at the `ExceptionTranslationFilter`, this message is already able to be localized through `MessageSource`, but as you noted, we lack several translations. Are you able to add a translation for one or more languages in your own messages_xyz.properties?

For watchers, we would love a contribution on this issue so don't hesitate if you are able to contribute one or more translations for the message: "Full authentication is required to access this resource"

Currently supported locales are:

- de
- en
- ja

Missing locales (that currently have other messages) are:

- ca
- cs_CZ
- es_ES
- fr
- it
- ko_KR
- lt
- mn_MN
- nl
- pl
- pt_BR
- pt_PT
- ru
- uk_UA
- zh_CN
- zh_TW

**Comment by rubensa** [comment]
Added pull request for Spanish https://github.com/spring-projects/spring-security/pull/9822
