### ISSUE TITLE
[SAML] Allow to override metadata file name on Saml2MetadataFilter

### ISSUE THREAD

**Issue by GitHanter** [spring-projects/spring-security#9317]
Currently `writeMetadataToResponse` method on Saml2MetadataFilter is `private`, we may need it `protected`, so we can allow developer to customize the SP metadata file name.

**Comment by jzheaux** [comment]
Thanks for the suggestion, @GitHanter.

How would your application determine the name of the file? I'm wondering if something more involved than `Saml2MetadataFilter#setMetadataFilename` is needed.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by GitHanter** [comment]
> Thanks for the suggestion, @GitHanter.
> 
> How would your application determine the name of the file? I'm wondering if something more involved than `Saml2MetadataFilter#setMetadataFilename` is needed.

We name it as `sp-<registrationId>-metadata.xml`, but I think the we should give developer a chance to change the metadata file name.

**Comment by jzheaux** [comment]
Thanks, @GitHanter, that makes sense.

It would be nice to have a setter that supports the `{registrationId}` placeholder as other SAML configuration values do.

Would you be able to provide a PR to add `Saml2MetadataFilter#setMetadataFilename(String)`, where the filter resolves `{registrationId}` placeholders? Then, you could do:

```java
Saml2MetadataFilter filter = new ...
filter.setMetadataFilename("sp-{registrationId}-metadata.xml");
```

**Comment by GitHanter** [comment]
@jzheaux Sure, I'll do the PR this weekend.
