### ISSUE TITLE
Kotlin DSL extension for HttpSecurity#rememberMe

### ISSUE THREAD

**Issue by unlimitedsola** [spring-projects/spring-security#9319]
As the title suggests. I found out the Kotlin DSL extension covers most of the configurations but the `rememberMe()` section. Not sure if there are any reasons that we are missing this?

**Comment by eleftherias** [comment]
Thanks for reaching out @unlimitedsola.

Are you interested in submitting a pull request to add the `rememberMe()` support to the Kotlin DSL?

**Comment by IvanPavlov1995** [comment]
I'd like to try to submit a pull request for this issue, can I take it?

**Comment by eleftherias** [comment]
Thanks @IvanPavlov1995! The issue is yours.

**Comment by eleftherias** [comment]
Hey @IvanPavlov1995, are you still interested in submitting a pull request for this issue?

**Comment by IvanPavlov1995** [comment]
Hello @eleftherias, yes, but for now I'm too busy so I'm not able to do it during February. If anyone else want to take this issue it would be OK, otherwise I'll return to this in March

**Comment by eleftherias** [comment]
Closed via 857830f
