### ISSUE TITLE
SEC-673: Spring IDE Tooling Support

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#932]
["Ben Alex":https://jira.spring.io/secure/ViewProfile.jspa?name=balex](Migrated from ["SEC-673":https://jira.spring.io/browse/SEC-673?redirect=false]) said:

Enhance namespaces to include the additional metadata required for inbuilt Spring IDE tooling support. Similarly review the existing BeanDefinitionParsers for compliance with Spring IDE conventions and implementation requirements.

**Comment by spring-issuemaster** [comment]
This issue depends on #1109
