### ISSUE TITLE
SAML2: Signature not retrieved from URL parameters when using HTTP-REDIRECT binding

### ISSUE THREAD

**Issue by willemsrb** [spring-projects/spring-security#9325]
**Describe the bug**
When using the HTTP-REDIRECT binding the Signature (URL parameters Signature and SigAlg) are not retrieved from
the URL. 

**To Reproduce**
Use HTTP-REDIRECT binding. The OpenSamlAuthenticationProvider will throw an exception that the response or the
assertions are not signed. When looking at the code is seems only an embedded signature in the Response seems accepted (or signed Assertions), but when using the HTTP-REDIRECT binding the Response should not be signed in that way according to the SAML2 specification; the Signature should be in the URL parameters.

We have used Keycloak as an SAML2 IDP. However you must disable the 'force to POST' setting to reproduce. Microsoft ADFS as an IDP will also fail as it will respect the HTTP-REDIRECT binding that is provided in the Service provider metadata XML.

**Expected behavior**
The Signature should be retrieved from the URL when processing a GET request and stored somewhere in the Saml2AuthenticationToken. The signature should then not be expected within the Response when processing the token.

**Sample**
Not available at this moment

**Comment by willemsrb** [comment]
Thanks you very much for the reply. My apologies for not seeing that part
of the specification. You are correct and I have configured the POST
binding instead.

 It would be nice if the relying party configuration would then disallow
the usage of this binding for the ACS.

Op di 5 jan. 2021 om 17:07 schreef Josh Cummings <notifications@github.com>

**Comment by jzheaux** [comment]
Good point, @willemsrb. Would you be able to contribute a PR that asserts that the ACS binding is not Redirect?

**Comment by willemsrb** [comment]
Sorry for the late answer, but i'll try to do that in the next week if time
allows
