### ISSUE TITLE
Exception when declaring multiple AuthenticationManager beans

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-security#9332]
Backport of gh-9256

**Comment by spring-issuemaster** [comment]
Fixed via 429caeacc905a6fc5c676ecb58a477da0e4e3067

**Comment by ibaskine** [comment]
@eleftherias Do you know ETA of 5.4.3?

**Comment by jzheaux** [comment]
@ibaskine you can follow the date [here](https://github.com/spring-projects/spring-security/milestone/199).
