### ISSUE TITLE
Is not possible build Spring Security: java.lang.IllegalStateException: Could not load file 'etc/nohttp/allowlist.lines'

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-security#9346]
**Describe the bug [Problem]**
Is not possible Build `Spring Security`

**To Reproduce**

In MacOS and Windows I have the following situation

I have STS 4.9.0.RELEASE for a workspace dedicated for Spring Security. 
And configured for Java 8 according with the [Building from Source](https://github.com/spring-projects/spring-security#building-from-source) section.

Therefore for the IDE itself:

![01](https://user-images.githubusercontent.com/2552795/104732617-7ee31480-570b-11eb-8c20-0f92cc72e9c6.png)

**NOTE**: From above - I removed the JRE 15 included in the IDE to avoid problems

![02](https://user-images.githubusercontent.com/2552795/104732624-80acd800-570b-11eb-8092-527491a64899.png)

![03 0](https://user-images.githubusercontent.com/2552795/104732628-81de0500-570b-11eb-9531-d6957863f26b.png)

Prior to import `Spring Security` I did 

* git clone
* added remote repository 
* git fetch 
* git merge upstream/master
 
So I am sure I have the latest and stable code of the project

Then `Spring Security` is imported and furthermore to be sure, I change for the `Spring Security` project its JRE from 15 to 8 as follows:

![03 5 1](https://user-images.githubusercontent.com/2552795/104733450-b56d5f00-570c-11eb-99e6-6cf9f052db54.png)

![03 5 2](https://user-images.githubusercontent.com/2552795/104733456-b8684f80-570c-11eb-9116-c090b861fc5c.png)

And furthermore is mandatory fix the following:

Remove JRE 15 (I)
![05](https://user-images.githubusercontent.com/2552795/104736521-17c85e80-5711-11eb-8679-ee7a7a412f0a.png)

Remove JRE 15 (II)
![06](https://user-images.githubusercontent.com/2552795/104736525-1a2ab880-5711-11eb-85bc-2bec9cd42da7.png)

Add JDK 8 (I)
![07](https://user-images.githubusercontent.com/2552795/104736528-1b5be580-5711-11eb-8e84-73c670d8416d.png)

Add JDK 8 (II)
![08 0](https://user-images.githubusercontent.com/2552795/104736567-29aa0180-5711-11eb-8368-13eb8e8f04c8.png)

The importation project was successful and configured fine to work with JDK 8.

Just in case I do the following:

![08 5](https://user-images.githubusercontent.com/2552795/104738781-f4eb7980-5713-11eb-935f-1f0dc7a5b71a.png)

Now according with the [Building from Source](https://github.com/spring-projects/spring-security#building-from-source) section is time to execute `./gradlew install`, therefore through the IDE

It works fine as follows:

![09](https://user-images.githubusercontent.com/2552795/104738930-2106fa80-5714-11eb-9bf9-b2d6defa7b4b.png)

![10](https://user-images.githubusercontent.com/2552795/104738939-23695480-5714-11eb-88db-8c0113978c9a.png)

![11](https://user-images.githubusercontent.com/2552795/104738940-2401eb00-5714-11eb-8c1e-86a2a59bc6a8.png)

![12](https://user-images.githubusercontent.com/2552795/104738943-249a8180-5714-11eb-8af7-ae6cbda2c6db.png)

Therefore all the required dependencies are downloaded and available.

Now according with the [Building from Source](https://github.com/spring-projects/spring-security#building-from-source) section is time to execute `./gradlew build`, therefore through the IDE

![13](https://user-images.githubusercontent.com/2552795/104739153-675c5980-5714-11eb-88f7-a17beb6f0992.png)

So the process starts:

![14](https://user-images.githubusercontent.com/2552795/104739267-8529be80-5714-11eb-86fb-c695c3f037a4.png)

But it fails with:

![15](https://user-images.githubusercontent.com/2552795/104739360-9d99d900-5714-11eb-93a6-f24702926e0c.png)

The message is:

```
Execution failed for task ':checkstyleNohttp'.
> java.lang.IllegalStateException: Could not load file 'etc/nohttp/allowlist.lines' 
```

![16](https://user-images.githubusercontent.com/2552795/104740416-eef69800-5715-11eb-9993-a868a8cd5ef8.png)

The same happens in other Machine on Windows 10, with a dedicated and isolated workspace for Spring Security.

![88](https://user-images.githubusercontent.com/2552795/104740715-43017c80-5716-11eb-8546-4a70fe0798e6.png)

**Expected behavior**
It should Build without any problem.

**Comment by manueljordan** [comment]
If through the IDE I do the following:

![Screen Shot 2021-01-18 at 9 32 59 AM](https://user-images.githubusercontent.com/2552795/104929695-38432380-5972-11eb-8105-281b81d2dcb6.png)

It to represent the `./gradlew build -x test` command execution then it fails with again with:

![Screen Shot 2021-01-18 at 9 33 11 AM](https://user-images.githubusercontent.com/2552795/104929784-5577f200-5972-11eb-9ca0-36f309c73c15.png)

But through a `Terminal` with `./gradlew build -x test` passes.

```
...
> Task :spring-security-test:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 9m 36s
633 actionable tasks: 125 executed, 4 from cache, 504 up-to-date

A build scan was not published as you have not authenticated with server 'ge.spring.io'.
```

So, why fails in the IDE and not in the Terminal?

**Comment by jzheaux** [comment]
Thanks for the report, @manueljordan. I was able to reproduce the error you described, and I will take a look.

In the meantime, it sounds like you have a workaround, which is to build from the terminal.

**Comment by manueljordan** [comment]
Thank you. Being curious, did you get the same error in the same STS IDE or perhaps with other?.

Not sure if the error would be based on the IDE , it because through the Terminal works fine

**Comment by jzheaux** [comment]
What appears to be happening is Eclipse isn't propagating the working directory through to the underlying `NoHttpCheck` Checkstyle task when running `build -> checkstyleNohttp`.

However, when running `checkstyleNohttp` directly as a Run Configuration, Eclipse propagates the working directory correctly.

As a workaround, then, you can configure the `build` Run Configuration in Eclipse to skip the `checkstyleNohttp` task. In `Project -> Run Configurations`, find or create a Gradle Task where the task is `build`. Then, in its Project Settings, add `-xcheckstyleNohttp` as a program argument.

You can then run `checkstyleNoHttp` separately.

**Comment by jzheaux** [comment]
I'm not sure what else can be done on the Spring Security side of things as this appears to be related to how Eclipse, Gradle, and Checkstyle work together.

I'm going to close this task as answered; however, please feel free to add more details if you feel like there's something we can help with.

**Comment by manueljordan** [comment]
Hi @jzheaux 

> I'm not sure what else can be done on the Spring Security side of things as this appears to be related to how Eclipse, Gradle, and Checkstyle work together.

Should be add a call or refer to Martin Lipert to this post?
