### ISSUE TITLE
Use var for Java when same documentation page uses val for Kotlin

### ISSUE THREAD

**Issue by yilativs** [spring-projects/spring-security#9349]
Documentation  uses old java 8 style and for code samples and at same time uses Kotlin val style.

Here is an example 
Java  (now)
`PasswordEncoder passwordEncoder =  PasswordEncoderFactories.createDelegatingPasswordEncoder();`
Kotlin(now)
`val passwordEncoder: PasswordEncoder = PasswordEncoderFactories.createDelegatingPasswordEncoder()`

Please, use Java 11 style so java section should be:
`var passwordEncoder =  PasswordEncoderFactories.createDelegatingPasswordEncoder();
`

**Comment by eleftherias** [comment]
Thanks for reaching out @yilativs.

Could you point me to some documentation on Java 8 vs Java 11 style in Kotlin?
I'm not aware of there being different style conventions for different target Java versions.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
