### ISSUE TITLE
Add SpringOpaqueTokenIntrospector

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#9354]
The extent to which the Nimbus library is used in `Nimbus(Reactive)OpaqueTokenIntrospector` is minimal enough that there's value in creating Nimbus-free versions in order to [simplify](https://github.com/spring-projects/spring-security/issues/9120) [dependency](https://github.com/spring-projects/spring-security/issues/8733) [management](https://github.com/spring-projects/spring-security/issues/8608) with `com.nimbusds:oauth2-oidc-sdk`.

These Nimbus-free versions would become the default.

The existing classes use Nimbus for parsing the introspection HTTP response. These new implementations would instead rely on `RestTemplate` or `WebClient` to parse the response as a `Map` of attributes. Now as a `Map`, the `convertClaimSet(TokenIntrospectionSuccessResponse)` would become `convertClaimSet(Map)`.

For testing, all the tests in `Nimbus(Reactive)OpaqueTokenIntrospector` should be applicable for `Spring(Reactive)OpaqueTokenIntrospector`.

**Comment by mkheck** [comment]
Hi @jzheaux, I'd like to take this one.

**Comment by jgrandja** [comment]
@jzheaux You might want to consider [OAuth2TokenIntrospectionHttpMessageConverter](https://github.com/spring-projects-experimental/spring-authorization-server/blob/beb123335800f7a9f5eb5160568b5b1d7d108118/oauth2-authorization-server/src/main/java/org/springframework/security/oauth2/core/http/converter/OAuth2TokenIntrospectionHttpMessageConverter.java#L57) as part of this implementation.

**Comment by jzheaux** [comment]
Agreed - I'll adjust once https://github.com/spring-projects/spring-security/pull/9903 is merged.

**Comment by jzheaux** [comment]
Thanks, @jgrandja, I'll take a look.
