### ISSUE TITLE
Add JavaDoc to AesBytesEncryptor

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#9361]
Related to #3879.

It would be helpful to have JavaDoc in `AesBytesEncryptor` that explains its default behavior. For example, the `(String, CharSequence)` constructor should clarify that it uses a 16-byte IV. Each constructor should show an example of how to invoke it.

**Comment by prashanttholia** [comment]
Hi @jzheaux @rwinch ,
I have raised a pull request to update javadoc for AesBytesEncryptor constructors. The updates include following points, as discussed above and in gh-3879 - 
- Mention default IV length and encryption mode.
- Link relevant constructors that allow usage of custom IV length and encryption mode.
Kindly review it.
