### ISSUE TITLE
Add 'AnyEdit Eclipse' plugin screenshots to improve details for settings for contribution

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-security#9378]
In the  [Mind the whitespace](https://github.com/spring-projects/spring-security/blob/master/CONTRIBUTING.adoc#mind-the-whitespace) section appears 7 bullet points and later does mention about the `AnyEdit Eclipse plugin`

**Expected Behavior**

Get more details about how to configure correctly `AnyEdit Eclipse plugin`, through some screenshots about the correct settings, would be valuable for newcomers that want contribute to this project.

Seems that plugin resolve many of the 7 bullet points mentioned at the top of this post

**Current Behavior**

There are no indications

**Context**

If I want contribute to this project through STS, would be nice have all the bullet points well configured to avoid problems if I send a PR

I know this request is not critical, but would be valuable to have all the settings well configured

**Comment by rwinch** [comment]
At this time a better plugin would be the [spring java format plugin](https://github.com/spring-io/spring-javaformat) which takes care of all the whitespace needs. Perhaps you could submit a PR that directs users to that?

**Comment by manueljordan** [comment]
When I created a Test class and I executed `./gradlew build` I got many errors about:

- format
- wrong import packages
- missing this references

Now I see that all come from that plugin

Please, could you confirm that plugin covers all about the 7 bullet points and other "things"? It to remove by complete the `AnyEdit Eclipse plugin` and do mention to the other one. Even with your confirmation I am going to play with that plugin to confirm and avoid confusions for the developers

**Comment by manueljordan** [comment]
I fixed this situation, both plugins are need it. Let me improve the documentation for this week or the other.

Is viable add Figures right? It to share and indicate the correct order for import packages in STS/Eclipse. If yes, please give/indicate me the correct structure and nomenclature about the directory names (where to store the figures) and files (figures) names.

Thanks for your understanding.

**Comment by rwinch** [comment]
The project now uses the spring java format plugin.
