### ISSUE TITLE
Introduce JdbcTokenStore

### ISSUE THREAD

**Issue by boyan-velinov** [spring-projects/spring-security#9381]
**Expected Behavior**

Introduce JdbcTokenStore, as the one in Spring Security OAuth 2.x

**Current Behavior**

Missing way to cache tokens in stateless app running in several instance.

**Context**

Currently we are using JdbcTokenStore, provided by Spring Security OAuth 2.x, in order to cache the tokens, which later on are used to accomplish long running processes on behalf of the user.

Here is the current application setup:

- App is running on several instances in Cloud Foundry
- App uses postgre as backing service
- App receives oauth tokens
- App acts on behalf of the user, by using the tokens, to call Cloud Controller. Actual computing and external calls can be done on different app instances.

More details and code snippets can be found in the stackoverflow question: https://stackoverflow.com/questions/65904062/tokenstore-in-spring-security-5-x-after-removal-of-spring-security-oauth-2-x

**Comment by jgrandja** [comment]
@boyan-velinov This has already been implemented in `5.3.0` via `JdbcOAuth2AuthorizedClientService`. See #7655 and #7889
