### ISSUE TITLE
Add `Cross-Origin-Opener-Policy` and `Cross-Origin-Embedder-Policy` security headers

### ISSUE THREAD

**Issue by eddumelendez** [spring-projects/spring-security#9385]
**Expected Behavior**

Allow to add `Cross-Origin-Opener-Policy` and `Cross-Origin-Embedder-Policy` headers via dsl and xml.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy

**Current Behavior**

This currently can be provided by https://docs.spring.io/spring-security/site/docs/5.5.x/reference/html5/#headers-custom

**Context**

Given the values provided by those headers, it would great to provide them explicitly.

I can provide a PR for this in the next weeks if adding them make sense.

**Comment by eleftherias** [comment]
Closed via #10141
