### ISSUE TITLE
ReactiveAuthorizationManager + Reactive Method Security

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#9401]
We should provide an implementation of Reactive Method Security that leverages `ReactiveAuthorizationManager` similar to gh-9289 The implementation should support:

* gh-4841 It should support SpEL expressions that return both Boolean and `Mono<Boolean>`
* It should support `Mono<Authentication>`
* It should support reactive and non reactive arguments. Reactive types should not be subscribed to unless they are used.
* It should support not resolving the `Mono<Authentication>` if it was not used (i.e. if `permitAll` was used there is no need to resolve the `Authentication`)
* [x] gh-5664

For full support this may require updates to SpEL support to support Reactor (i.e. it likely needs to support lambdas) but beans can easily return reactive types that would be supported by SpEL.

Related to #9289, #5249, and https://github.com/spring-projects/spring-security/issues/4841

Once #9289 is addressed, we could consider applying the same model to reactive method security.

**Comment by evgeniycheban** [comment]
@jzheaux I can take this.

**Comment by jzheaux** [comment]
Great, @evgeniycheban! It's yours. I'd recommend waiting until #9630 is merged before proceeding.

**Comment by rwinch** [comment]
@evgeniycheban Thanks for volunteering to work on this issue. I've updated the description to include more detailed requirements. I think you can start on this issue before we merge [the mentioned PR](https://github.com/spring-projects/spring-security/issues/9401#issuecomment-831469591), but base it off the branch with gh-9630

**Comment by mkrzywanski** [comment]
What is the status of this ticket?

**Comment by evgeniycheban** [comment]
> What is the status of this ticket?

Waiting for review.
