### ISSUE TITLE
SEC-689: Session Fixation protection should be available to all authentication mechanisms.

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#941]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-689":https://jira.spring.io/browse/SEC-689?redirect=false]) said:

This was implemented in AbstractProcessingFilter for SEC-399. This could be made more general by using a separate filter (as also mentioned in this issue). The http namespace element can be extended to include a session-fixation-protection attribute, set to true by default. Also a migrate-session-attributes might be required.

**Comment by spring-issuemaster** [comment]
This issue is related to #660
