### ISSUE TITLE
Update contribution guidelines to require JDK 11 to build

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#9418]
As part of updating Spring Security's build to require JDK 11, the contribution guidelines should be updated.

**Comment by manueljordan** [comment]
Hi @jzheaux 

The `build.gradle` file, should be updated too? Currently, it has:

```
plugins.withType(JavaPlugin) {
		project.sourceCompatibility='1.8'
	}
```

**Comment by jzheaux** [comment]
Good question, @manueljordan. No, this should not be updated as Spring Security 5 guarantees Java 8 source compatibility.

Even though Spring Security may require compilation with JDK 11, it should not require JDK 11 to use it in a project.

**Comment by manueljordan** [comment]
>Even though Spring Security may require compilation with JDK 11, it should not require JDK 11 to use it in a project.

Interesting perspective

**Comment by jzheaux** [comment]
@manueljordan This is the kind of long-term compatibility that the Spring Framework has become known for. You can see another example of the same thing from [when Java 8 APIs started getting introduced](https://spring.io/blog/2015/04/03/how-spring-achieves-compatibility-with-java-6-7-and-8). Even though Spring Framework required Java 8 to build it, Java 6 applications could still use it just fine.

**Comment by manueljordan** [comment]
@jzheaux  - Thanks for information and the interesting link, I appreciate that
