### ISSUE TITLE
I want to customize state parameter with Oauth2client

### ISSUE THREAD

**Issue by junaidsubhni** [spring-projects/spring-security#9420]

**Comment by jgrandja** [comment]
@junaidsubhni Please provide details so I can better understand your request.

Why do you want to customize the `state` parameter? What is your specific use case?

**Comment by jzheaux** [comment]
Looks like you asked this on Stackoverflow as well, @junaidsubhni: https://stackoverflow.com/questions/66115098/customize-state-parameter-with-oauth2client-using-spring-security/66129580#66129580

I've gone ahead and replied over there.
