### ISSUE TITLE
Authentication(Web)Filter should return a 500 on AuthenticationServiceExceptions

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#9429]
When `(Reactive)AuthenticationManager` throws or resolves to an `AuthenticationServiceException`, `Authentication(Web)Filter` should instead return a 500 HTTP response.

**Comment by Kehrlann** [comment]
Hey there 👋 I'm interested in picking this one up.

**Comment by Kehrlann** [comment]
Hey @jzheaux , a few questions regarding this.

Here's my interpretation of the story (for `AuthenticationFilter`):

### When the user does not override the `failureHandler`

When the `AuthenticationManager` throws an `AuthenticationServiceException` ;
Then the exception is re-thrown, ultimately producing a HTTP 500

### When the user provides a custom `failureHandler`

When the `AuthenticationManager` throws an `AuthenticationServiceException` ;
That exception is passed to the user's failureHandler and process by that

---

Let me know if I'm missing something.
