### ISSUE TITLE
Alternative for Oauth classes removed in spring security 5

### ISSUE THREAD

**Issue by rakotkar** [spring-projects/spring-security#9432]
Are below classes removed in spring security by spring boot 2.4.1

import org.springframework.security.oauth2.common.OAuth2AccessToken import org.springframework.security.oauth2.provider.OAuth2Authentication import org.springframework.security.oauth2.provider.OAuth2Request import org.springframework.security.oauth2.provider.token.AuthorizationServerTokenServices import org.springframework.security.oauth2.provider.token.TokenStore

they can neither be found in

<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-client</artifactId>
        </dependency>
nor in

<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
        </dependency>
Where can we find these if using spring boot 2.4.1 ?

**Comment by jgrandja** [comment]
@rakotkar Support was removed in Spring Boot 2.x in favour of Spring Security 5’s first-class [OAuth support](https://docs.spring.io/spring-security/site/docs/5.4.2/reference/html5/#oauth2).

See the initial [announcement](https://spring.io/blog/2018/01/30/next-generation-oauth-2-0-support-with-spring-security) for further details.
