### ISSUE TITLE
Multiple Pre or PostAuthorization Annotations

### ISSUE THREAD

**Issue by vincent-simpson** [spring-projects/spring-security#9452]
I'm opening this issue for discussion on this older issue from a few years back: https://github.com/spring-projects/spring-security/issues/3183

I'm wondering what thoughts are about the expected behavior of multiple annotations. I would think it is analogous to combining each of the expressions with "and". 

I'm regards to implementation, I would think an approach similar to how multiple caching annotations can be used with the Caching annotation is the right way to go with this.

**Comment by jzheaux** [comment]
This is resolved in https://github.com/spring-projects/spring-security/pull/9630.
