### ISSUE TITLE
Upgrade to Gradle 6.8.2

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-security#9458]
Consider to upgrade the `gradle/wrapper/gradle-wrapper.properties` file to 

* `distributionUrl=https\://services.gradle.org/distributions/gradle-6.8.2-bin.zip`

**Comment by eleftherias** [comment]
Thanks for the suggestion @manueljordan.
I agree that we can use the latest gradle version.
Additionally, is there a particular feature in this version that you think this project should be using?

**Comment by manueljordan** [comment]
Hi @elefeint 

>Additionally, is there a particular feature in this version that you think this project should be using?

Well, I created this suggestion because, yesterday when I tried to import the project in STS through BuildShip, the plugin shown a warning message about the support/features for 6.6x and suggested use 6.8.x. That's all. Furthermore yesterday SF upgraded to 6.8.2

I am assuming that 6.6.8 has all the same features than 6.6.x and some extra features and improvements against 6.6.x
