### ISSUE TITLE
Filter Chain from child contexts are not applied

### ISSUE THREAD

**Issue by fdw** [spring-projects/spring-security#9464]
**Describe the bug**
I'm using Spring Boot 2.4.2 with Spring Security 5.4.2.
The application has a main context, with a `WebSecurityConfigurerAdapter` that contains authorization configuration for the actuators:
```
class SecurityConfiguration : WebSecurityConfigurerAdapter() {
    override fun configure(http: HttpSecurity) {
        http.csrf().disable()
            .cors().and()
            .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS).and()
            .httpBasic().and()
            .requestMatchers().antMatchers("/actuators/**").and()
            .authorizeRequests()
            .requestMatchers(EndpointRequest.to(CustomHealthEndpoint::class.java)).permitAll()
            .requestMatchers(EndpointRequest.to(InfoEndpoint::class.java)).hasAnyRole(Roles.ONE, Roles.TWO)
            .requestMatchers(EndpointRequest.to(PrometheusScrapeEndpoint::class.java)).hasAnyRole(Roles.ONE)
            .requestMatchers(EndpointRequest.toAnyEndpoint()).hasRole(Roles.THREE)
    }
```
This works fine, so far.

It also has several child contexts, each with their own `DispatcherServlet`. Their URLs depend on configuration and thus are not known beforehand. I wanted to introduce an additional authorization requirement for their whole path. The code accordingly looks like this:
```
@Configuration
@Order(2)
class SecurityConfiguration : WebSecurityConfigurerAdapter() {
    override fun configure(http: HttpSecurity) {
        http.requestMatchers().antMatchers("/**").and()
            .authorizeRequests()
            .anyRequest().hasAnyRole(Roles.ADMIN, Roles.API)
    }
}
```
However, while the configuration seems to be executed, it is not applied to calls. Debug log shows: `Security filter chain: no match` where I expected some classes. (For reference, requests to `/actuators` do show a a Security filter chain.)

**To Reproduce**
* Have such a setup
* Send a request to one of the child contexts without authentication

**Expected behavior**
The request should be denied with a 401.

**Sample**
https://github.com/fdw/spring-problem

**Comment by rwinch** [comment]
@fdw Spring Security requires that the [`FilterChainProxy`](https://docs.spring.io/spring-security/site/docs/5.4.x/reference/html5/#servlet-filterchainproxy) is registered with the Servlet Container. In a typical Spring Boot application, Spring Security's [`FilterChainProxy is registered with the Servlet Container automatially`](https://docs.spring.io/spring-security/site/docs/5.4.x/reference/html5/#servlet-hello-auto-configuration). However, due to the fact that the child `ApplicationContext` is setup manually it is not automatically registering the `FilterChainProxy` found in the child `ApplicationContext`. This means that, similar to how [the code already exposes](https://github.com/fdw/spring-problem/blob/74b44c60fae669f3befe6713cedb58f0ae738545/child/src/main/kotlin/com/example/child/config/ChildConfiguration.kt#L22) the `DispatcherServlet`, you will need to expose a Bean that registers the `springSecurityFilterChain` Bean with the Servlet Container. For example:

```java
    @Bean
    fun springSecurityRegistration(applicationContext: WebApplicationContext, dispatcher: ServletRegistrationBean<DispatcherServlet>): FilterRegistrationBean<Filter> {
        val springSecurityFilterChain = DelegatingFilterProxy(DEFAULT_FILTER_NAME, applicationContext)
        return FilterRegistrationBean(springSecurityFilterChain, dispatcher)
    }
```

**Comment by fdw** [comment]
Thank you very much for your help! I really appreciate it :)

Unfortunately, I couldn't get your fix to work. I've added some tests, and it seems to me that in one child context, all requests are allowed (whether authorized or not), and in the other, all are denied (both authorized and not). Do you have any idea why that happens?

**Comment by rwinch** [comment]
I've updated the branch of the pull request with small commits and comments about what needed to be changed.

**Comment by fdw** [comment]
Thank you so much, that worked!

> However, I would reiterate that I would consider trying to accomplish what you want a different way.

Believe me, I'm with you. We just haven't found another way yet. Our service offers onle a few capabilities, but for different subjects, so we thought encapsulating the capabilities in a Spring context and having multiple, similar contexts was a good idea. To add to that, the subjects themselves are configurable, so we can't really hardcode anything.

**Comment by joris-lambrechts** [comment]
@fdw is there any way you could share the changes from the pull request?

From what I gather after some hours, defining a `FilterRegistrationBean` is not possible inside the child context. The filters and servlets are registered with Tomcat before the child context is created. Adding a `FilterRegistrationBean` for filter `FilterChainProxy` gets me only so far. What I'm stuck on is getting the `SecurityFilterChain`s from the child context in that `FilterChainProxy`. I tried it with a mutable list and a custom `FilterChainProxy`, it works but I don't really like the mutability of the list.

I'm migrating a Spring application to Spring Boot and running into the same problem. Merging all the ApplicationContexts to one is currently too big of a change. Also, the version I'm going with is Spring Boot 1.5.9 as that contains the same Spring version as the project now has. Once that all works, we will migrate to the latest 2.x.
