### ISSUE TITLE
Reactive support for old implementation of authorization server

### ISSUE THREAD

**Issue by VuDo98** [spring-projects/spring-security#9465]
**Expected Behavior**

It should works the same as the old implementation but hopefully reactive. You will also need to replace `@EnableAuthorizationServer`  with `@EnableReactiveAuthorizationServer`

**Context**

Goal: Support projects with older version of spring looking to convert to reactive and/or waiting for `Spring Authorization Server` project to be released with reactive implementation.

Please checkout this repository: [spring-reactive-authorization-server](https://github.com/VuDo98/spring-reactive-authorization-server)

**Comment by eleftherias** [comment]
Thanks for reaching out @VuDo98. 
The authorization server support was part of the legacy [Spring Security OAuth project](https://github.com/spring-projects/spring-security-oauth), which is [deprecated](https://spring.io/blog/2020/05/07/end-of-life-for-spring-security-oauth).
That means we are not adding any more features to that project.
We are working on experimental Authorization Server support in the [Spring Authorization Server project](https://github.com/spring-projects-experimental/spring-authorization-server), although [WebFlux support is not on the roadmap](https://github.com/spring-projects-experimental/spring-authorization-server/issues/152#issuecomment-727957644) as of now.

**Comment by VuDo98** [comment]
@eleftherias Hi, I am actually not asking for reactive support but I am asking if my implementation of the deprecated authorization would be an acceptable temporary reactive support and would you guys be able to have a quick look at my work to review it. I already did the work and I pretty much keep the old logic but just coded it reactively. I believe there are many projects still use the deprecated version and it will take a long time for the new authorization server to be released and support webflux.

**Comment by eleftherias** [comment]
Hi @VuDo98
Given that the legacy Spring Security OAuth project is deprecated and we aren't adding new features, it doesn't make sense to add reactive support.
This applies whether it is in the spring-security-oauth repository or a different repository.
