### ISSUE TITLE
once https - always https

### ISSUE THREAD

**Issue by guai** [spring-projects/spring-security#9466]
**Describe the bug**
I have `http.headers().httpStrictTransportSecurity` **disabled**.
No _https_ even configured. No certificate - nothing.
I can browse my resorces via **http** ok until I try to access any of them via _https_.
In this case HSTS header being send and browser does not want to use **http** anymore unless its state cleared explicitly.
And no resource being served of cause, since _https_ does not configured properly.

**To Reproduce**
* make new spring-boot app with `http.headers().httpStrictTransportSecurity` **disabled**.
* add static resource.
* request it first via **http** - should be served.
* request it via _https_ - get error.
* request it via **http** again - be redirected and get error again.

**Expected behavior**
HSTS to be turned off when it told to. Or even HSTS not to be enabled unless _https_ actually set up and there is a secure server to redirect to.

**Comment by rwinch** [comment]
> No https even configured. No certificate - nothing.
> I can browse my resorces via http ok until I try to access any of them via https.
> In this case HSTS header being send and browser does not want to use http anymore unless its state cleared explicitly.

Can you help me understand how this happens? If you don't have https enabled at all, then you should get an error that it could not connect to the port.

Can you show me an example request/response including all the headers?

Can you provide a sample?

**Comment by guai** [comment]
"you should get an error"
I do. it tries to go to 8080 with encripted data it seems. And it fails of cause.
"Can you provide a sample"
[here you go](https://github.com/guai/hsts-example)
I put a log and some screenshots there.
1) I cleaned the hsts for localhost
2) http
3) https
4) http again

**Comment by rwinch** [comment]
Invoking httpStrictTransportSecurity().disable() will ensure that the Strict-Transport-Security header is not sent back. Your screenshots do not indicate that it is being sent back (it shows the request headers). What is interesting is the https image shows err_ssl_protocol_error which demonstrates that you are trying to use https protocol on a port that is configured for http. It is my guess that you would not even connect to an HTTP connector when using https (I believe that is what the port is stating). I'd suggest trying from a command prompt and other browsers to see if it appears to behave the same way. If that doesn't help, please provide all the request/response details (including headers) for each of the requests. If you do not see the Strict-Transport-Security header, then Spring Security is behaving properly.

**Comment by guai** [comment]
"you are trying to use https protocol on a port that is configured for http"
I'm not. I don't want https in any way, but I still get it.
There is an error in [the log](https://github.com/guai/hsts-example/blob/main/log.log)
```
2021-02-20 11:55:15.727  INFO 18680 --- [nio-8080-exec-1] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x03F0xe7Y0x810xb1>0x9f0xe7z0x05=0xcc0x070xe1U0xc520x18(0x910x1d0xb00xd9Ux+m0xfb`0x0e0x1aR]. HTTP method names must be tokens
```
which I think means that https-encrypted request goes to http port.

**Comment by rwinch** [comment]
Can you try removing Spring Security and seeing if you are still getting the error?

**Comment by guai** [comment]
Isn't HSTS is on by default now? I think I'll get HSTS even earlyer if I try.

**Comment by guai** [comment]
Yep. After cleaning HSTS cache in the the browser (MS Edge) the first request to **http** went ok. I got the requested index.html
Then I hit F5 to reload it and got 307 status and a redirect to _https_

**Comment by rwinch** [comment]
If you still get the problem without Spring Security on your classpath, then how can Spring Security be the problem?

**Comment by guai** [comment]
Because it have some code in it to turn HSTS off, which it kinda does, but not completely

**Comment by guai** [comment]
And its not actually the same problem. The issue is about the case when any https request turns HSTS back on, not about HTST pre se

**Comment by rwinch** [comment]
It disables sending the header. The header is not sent when it is invoked, so this is not a bug.

**Comment by guai** [comment]
how is this not a bug?
redirect with`Non-Authoritative-Reason: HSTS`
I made you an example did you even try it?

**Comment by 2is10** [comment]
A 307 Internal Redirect with `Non-Authoritative-Reason: HSTS` is [a built-in Chrome behavior](https://stackoverflow.com/questions/70705778/chrome-redirects-and-makes-2-requests-of-the-same-page-307-internal-redirect). It means Chrome made no server request at all. I don’t know what precisely triggers that behavior. To see how your server actually handles the same request, try a different browser or `curl`.
