### ISSUE TITLE
Migrate JUnit 4 to 5

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/spring-security#9467]
To take in advantage all the features of JUnit 5. Would be considered a migration/upgrade?

Only two kotlin files works with JUnit 5, but nothin for Java

![Screen Shot 2021-02-20 at 1 20 13 PM](https://user-images.githubusercontent.com/2552795/108604892-9eaacf80-737e-11eb-8c3a-0c42b12144da.png)

**Comment by rwinch** [comment]
Thanks for the report @manueljordan! I am planning on taking care of this in the near future by using https://github.com/openrewrite/rewrite-testing-frameworks

**Comment by manueljordan** [comment]
Hi @rwinch - very interesting. Thanks for that link. 

Ok I am going to wait in peace that migration.
