### ISSUE TITLE
SEC-699: Make TargetUrlResolverImpl parameter non-optional

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#948]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-699":https://jira.spring.io/browse/SEC-699?redirect=false]) said:

Currently you have to actually inject this object to make use of the parameter (see SEC-213), since it is null by default (the javadoc implies otherwise). This was because the default parameter name of "redirect" might commonly be used for other purposes. We should change it to a more specific name (e.g. "spring-security-redirect") and make it non-nullable.

It should also be added as an option to the namespace for form login.

**Comment by spring-issuemaster** [comment]
This issue is related to #474
