### ISSUE TITLE
Missing statement in docs for JdbcUserDetailsManager example

### ISSUE THREAD

**Issue by IvanAgafonov** [spring-projects/spring-security#9481]
In section https://docs.spring.io/spring-security/site/docs/5.4.5/reference/html5/#servlet-authentication-jdbc-bean in Example 69. JdbcUserDetailsManager forgot the return statement.

![image](https://user-images.githubusercontent.com/29808839/109670904-a3dcfb00-7b84-11eb-938c-9ce3a4a33854.png)

**Comment by eleftherias** [comment]
Thanks for the report @IvanAgafonov!
Are you interested in submitting a pull request to fix it?
