### ISSUE TITLE
HttpSecurityConfigurer should have a no-parameter method for authorizeHttpRequests

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#9498]
In #8996, `authorizeHttpRequests(Customizer)` was introduced.

For consistency with the rest of the DSL, `authorizeHttpRequests()` should also be added.

**Comment by dratler** [comment]
Hi @jzheaux ,
is this still open for the grab ?

**Comment by jzheaux** [comment]
Thanks, @dratler! It's yours.
