### ISSUE TITLE
DelegatingSecurityContextTaskScheduler does not allow to use a specific SecurityContext

### ISSUE THREAD

**Issue by gbaso** [spring-projects/spring-security#9514]
**Expected Behavior**

`DelegatingSecurityContextTaskScheduler` should have a constructor accepting a `TaskScheduler` and a `SecurityContext`.

**Current Behavior**

Unlike similar classes like `DelegatingSecurityContextAsyncTaskExecutor` and `DelegatingSecurityContextScheduledExecutorService`, `DelegatingSecurityContextTaskScheduler` does not extends `AbstractDelegatingSecurityContextSupport` and does not contains a `SecurityContext` field. As of now, it's just a plain wrapper.

Looking at past issues, it looks like `DelegatingSecurityContextTaskScheduler` was requested in #3125 and introduced in #6043

**Comment by jzheaux** [comment]
Thanks for the report, @gbaso. I agree that `DelegatingSecurityContextTaskScheduler` should wrap the `Runnable` instances it receives in `DelegatingSecurityContextRunnable`s.

Would you be able to provide a PR with that change?

**Comment by gbaso** [comment]
@jzheaux I submitted #9532 to fix the issue
