### ISSUE TITLE
OpenID Connect Oauth2 client only accepts ID Tokens signed with alg:RS256

### ISSUE THREAD

**Issue by JesseEstum** [spring-projects/spring-security#9522]
**Describe the bug**
Unless I'm really missing something (which I won't rule out ;)), the OpenID Connect Oauth2 client will explode when it receives an ID token signed by any algorithm other than RS256.  Furthermore, the cardinality of the ClientRegistration -> Supported Signature Algorithm mapping seems to be 1:1 but I think it should be 1:many.  Should the OpenID Provider choose to change signature algorithms, it should not break the client.

https://github.com/spring-projects/spring-security/blob/master/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/oidc/authentication/OidcIdTokenDecoderFactory.java#L87 shows the issue, whereby:
1. `jwsAlgorithmResolver` is declared as a 1:1 function of `ClientRegistration` to `JwsAlgorithm`
2. `SignatureAlgorithm.RS256` is assumed to be signature algorithm

**To Reproduce**
1. Configure a spring boot app using OpenID Connect authentication
2. Configure a client registration in the OpenID Provider that uses an encryption algorithm *other than* `RS256` -- `ES256` is a good example
3. Attempt to execute an Oauth2 authorization code login flow
4. Observe an error message like `[invalid_id_token] An error occurred while attempting to decode the Jwt: Signed JWT rejected: Another algorithm expected, or no matching key(s) found`

**Expected behavior**
The `OidcIdTokenDecoderFactory` should be capable of working with either a predefined list of acceptable signature algorithms _or_ support any algorithm for which a key exists in the OpenID Provider's JWKS.

**Sample**

Reproduction with a full OpenID Connect integration is non-trivial.  Subsequent to opening the issue I'll attempt to spin up a unit test or code fragment to isolate the issue and demonstrate it.

**Comment by jgrandja** [comment]
@JesseEstum I believe the error message is related to an application misconfiguration.

> `[invalid_id_token] An error occurred while attempting to decode the Jwt: Signed JWT rejected: Another algorithm expected, or no matching key(s) found`

If the `jwsAlgorithmResolver` is returning `ES256` for a specific `ClientRegistration` and the provider's JWKS endpoint does not return a `ES256` key than it will fail.

Please review the [reference](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2login-advanced-idtoken-verify) on how to configure `OidcIdTokenDecoderFactory`.

If you're still having issues then I'll need you to put together a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue. I know this can be challenging using an external provider but this [sample](https://github.com/spring-projects-experimental/spring-authorization-server/tree/master/samples/boot/oauth2-integration) will make it much easier.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by JesseEstum** [comment]
Thank you, @jgrandja !  The link you provided did work for explicitly setting the expected ID Token signature algorithm to something other than RS256.  This solves my acute problem.

More broadly, though, is there any mechanism to support an arbitrary signature algorithm or a predefined collection of signature algorithms for a single OpenID Provider?  For example, if my OP uses `ES256` today but decides to change to `ES384` next week then my app would break.  If the OP has the right `ES384` keys published in its JWKS, couldn't spring-security just use them to authenticate the token?

Perhaps spring-security is designed to assert trust at a (Client Registration, Signature Algorithm)-pair level, not at a Client Registration level.  Is that the design intent of the library?

**Comment by channyeintun** [comment]
@jgrandja  Thank you, This solves my problem.

**Comment by jgrandja** [comment]
@JesseEstum 

> is there any mechanism to support an arbitrary signature algorithm or a predefined collection of signature algorithms for a single OpenID Provider? For example, if my OP uses `ES256` today but decides to change to `ES384` next week then my app would break

The Spring Boot property `spring.security.oauth2.client.provider.[providerId].jwk-set-uri` (see [ClientRegistration](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2Client-client-registration)) enables key rotation support.

For example, let's say the provider is signing tokens using `ES256` today and tomorrow it rotates the primary signing key and starts using `ES384`, then the `NimbusJwtDecoder` associated with `OidcIdTokenDecoderFactory` will ultimately fetch the **new set** of keys from `jwkSetUri` and verify the signature. **The re-fetch happens if it can't find the key in it's internal cache**.

I'm not seeing any issue here so I'm going to close this as works as expected.

Again, if you are experiencing an issue then please put together a minimal sample as mention in this [comment](https://github.com/spring-projects/spring-security/issues/9522#issuecomment-808332496).

**Comment by ldwqh0** [comment]
@jgrandja 
Thanks.
but how the "key rotation support"  work?
it not work for me.
