### ISSUE TITLE
SAML2: Impossible to change the signature algorithm from sha256 to sha256-rsa-MGF1

### ISSUE THREAD

**Issue by leneinz** [spring-projects/spring-security#9563]
I cant find a way to modify the used signature algorithm to something different than sha-256. (In my case sha256-rsa-MGF1)
Maybe its just missing in the docs?

**Comment by jzheaux** [comment]
Thanks for reaching out, @leneinz. This will be added [in the 5.5 release](https://github.com/spring-projects/spring-security/issues/8952).
