### ISSUE TITLE
SecurityExpressionHandler#createEvaluationContext should defer lookup of Authentication

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#9667]
Like `AuthorizationManager`, it would be nice to be able to defer the looking up `Authentication` in `SecurityExpressionHandler`.

A default `createEvaluationContext` method could be added:

```java
default EvaluationContext createEvaluationContext(Supplier<Authentication> authentication, T invocation) {
    return createEvaluationContext(authentication.get(), invocation);
}
```

And then `DefaultXXXSecurityExpressionHandler`s would be updated to defer evaluation until the authentication was inspected.

**Comment by evgeniycheban** [comment]
@jzheaux I can take this.

**Comment by evgeniycheban** [comment]
@jzheaux I've opened the PR, please take a look.

**Comment by jzheaux** [comment]
In order to accommodate changing to `Supplier<Authentication>` in `SecurityExpressionRoot`, the `protected Authentication authentication` member variable is changed to `private Supplier<Authentication> authentication`.

Classes that extend `SecurityExpressionRoot` and access the `protected` member variable should instead call `getAuthentication()`.
