### ISSUE TITLE
Prevent CI from running on forks

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-security#9701]
The project's GitHub Actions CI build has a hard dependency on some secrets (e.g. `GRADLE_ENTERPRISE_CACHE_USERNAME`), which causes the build to fail on the forks, causing unnecessary noise.

I've been greeted by one such build failure after syncing my fork today:
https://github.com/vpavic/spring-security/runs/2476329503?check_suite_focus=true

**Comment by jzheaux** [comment]
I see that in `pr-build-workflow` there is the following declaration:

```
if: github.repository == 'spring-projects/spring-security'
```

I wonder if the same pattern can be applied to the jobs in `continuous-integration-workflow`.

Also, note that forks can disable actions via `Settings > Actions`.
