### ISSUE TITLE
response.sendError(401, “error message”) not working after upgrading springboot to 2.4.4

### ISSUE THREAD

**Issue by kushalagrawal** [spring-projects/spring-security#9766]
I am using `AuthenticationEntryPoint` to handle the Authentication issues.To deliver the exception reason to the end-user.

    response.sendError(responseCode, "error Reason")

I recently upgraded the spring boot from "2.2.11.RELEASE" to "2.4.4". Since then it is not working anymore. It is not providing the "error reason" in the response received by the client now. Is there any change recently introduced in spring-boot which I am missing?

**Comment by Manas-nighrunkar** [comment]
Hello, how did you resolve this issue? stuck with same problem

**Comment by kushalagrawal** [comment]
Hey Manas, This was because of an issue with their base64-related change in the SAML AuthnRequest signature. You can upgrade to the latest version for this issue to be fixed.

**Comment by Manas-nighrunkar** [comment]
Still facing the problem in latest update
