### ISSUE TITLE
spring-security-core depends on spring-security-crypto

### ISSUE THREAD

**Issue by wilkinsona** [spring-projects/spring-security#9767]
In 5.5.0, `spring-security-core` has started declaring a dependency on `spring-security-crypto` in addition to embedding `spring-security-crypto`'s classes. This resulted in a number of Spring Boot's starters containing duplicates of the crypto classes. We've worked around it [by excluding `spring-security-crypto`]( https://github.com/spring-projects/spring-boot/commit/33a5c31fe3cee6db58ebffa7f60bc0d82cfb11c6).

**Comment by rwinch** [comment]
@wilkinsona This is fixed in 5.5.1-SNAPSHOT and 5.6.0-SNAPSHOT by spring-security-core depends on spring-security-crypto without embedding the classes. 
Could you give one of those a try to ensure the problem is resolved?
