### ISSUE TITLE
SEC-739: Remove siteminder specific provider code

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#977]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-739":https://jira.spring.io/browse/SEC-739?redirect=false]) said:

This is now superceded by the options available using pre-authentication. See SEC-657

**Comment by spring-issuemaster** [comment]
This issue is related to #917
