### ISSUE TITLE
Migrate Kotlin tests from Java Mockito to Mockk

### ISSUE THREAD

**Issue by eleftherias** [spring-projects/spring-security#9785]
[Mockk](https://mockk.io/) is a mocking library for Kotlin.
Most of our Kotlin tests currently rely on Java Mockito to create mocks. 
We should migrate these tests to use Mockk instead.

This will fix many of the "Unchecked cast" warnings we get in the Kotlin tests:
```
Unchecked cast: AuthorizationRequestRepository<*>! to AuthorizationRequestRepository<OAuth2AuthorizationRequest>
```

For an example where we already use Mockk see [KotlinEnableReactiveMethodSecurityTests.kt](https://github.com/spring-projects/spring-security/blob/main/config/src/test/kotlin/org/springframework/security/config/annotation/method/configuration/KotlinEnableReactiveMethodSecurityTests.kt).

**Comment by theexiile1305** [comment]
Added a pull request for fixing this issue #9839
