### ISSUE TITLE
Spring Security Sample not found

### ISSUE THREAD

**Issue by sylvermeister** [spring-projects/spring-security#9789]
**Describe the bug**
I followed the link from https://docs.spring.io/spring-security/site/docs/current/reference/html5/#servlet-hello

The page linked from docs is return 404.

**To Reproduce**
Just click on the link from docs of spring io

**Expected behavior**
Display sample codes for spring security

**Sample**

> The completed application can be found at samples/boot/helloworld For your convenience, you can download a minimal Spring Boot + Spring Security application by clicking here.

1. Click on the "samples/boot/helloworld" link from the page.

**Comment by nagarajasr** [comment]
samples have been moved to their own repository
check this: https://github.com/spring-projects/spring-security-samples

**Comment by jzheaux** [comment]
Thanks for the report, @nagarajasr. This is a duplicate of #9784.

**Comment by sylvermeister** [comment]
@nagarajasr  @jzheaux 
Thank you for your reply.

I want to help fixing the wrong link being pointed from docs.spring.io.

How do we edit the link from being pointed to the wrong repository?
