### ISSUE TITLE
Remove links that point to unmigrated samples

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security#9817]
In 5.5, `gh-samples-url` points to `https://github.com/spring-projects/spring-security/tree/5.5.0/samples`, but the samples have moved to `spring-security-samples`, so the links are broken.

For links that point to samples that have not yet been migrated, the link should be removed and a ticket should be added to `spring-security-samples` to ensure that the sample gets migrated.

Since this first released in 5.5, these links should be backported to the 5.5 documentation as well.

**Comment by marcusdacoregio** [comment]
Created ticket https://github.com/spring-projects/spring-security-samples/issues/22 to map not migrated samples.

Closing as this issue was solved in https://github.com/spring-projects/spring-security/pull/9826/commits/53310998f5961bd65a46f864c8d3b7f4ccba705e
