### ISSUE TITLE
How to upgrade to OpenSaml4AuthenticationProvider

### ISSUE THREAD

**Issue by dawi** [spring-projects/spring-security#9824]
After upgrading to `Spring Boot 2.5.0` which includes `Spring Security 5.5.0` I noticed that `OpenSamlAuthenticationProvider` is deprecated and that I should use `OpenSaml4AuthenticationProvider` instead. However it is not enough to just change the class, because `spring-security-saml2-service-provider` still depends on `Open SAML 3.4.6` for backward compatibility reasons (9095).

So I assume that I have to exclude `Open SAML 3.4.6` and add the `Open SAML 4.1.0` dependency manually?

The other option would be to ignore the deprecation warning and use `OpenSamlAuthenticationProvider` until it get's removed. At least everything will work then, and I don't have to handle the dependencies manually.

Regards
Daniel

**Comment by jzheaux** [comment]
Thanks for reaching out, @dawi. You should be able to manage the dependency like [in this sample](https://github.com/spring-projects/spring-security-samples/blob/main/servlet/spring-boot/java/saml2-login/build.gradle).

**Comment by thmarti** [comment]
Hi @jzheaux your link leads to a 404 page...

**Comment by dawi** [comment]
The relevant links are:
* [Example Project](https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/saml2/login)
* [Dependency Configuration](https://github.com/spring-projects/spring-security-samples/blob/0e4e7c73731ed7818318e828b2b94fffef2275af/servlet/spring-boot/java/saml2/login/build.gradle#L16)

**Comment by RTK3300** [comment]
Aren't there files missing in that sample project? I only see a controller and the Application file, but no SecurityConfig file? Only branch version 5.6 and 5.7 seem to have a SecurityConfig file? 

I'm upgrading an old Spring boot 2.4 (Spring Security 5.4) application to a newer version of Spring Boot (2.7 or 3.1). Is manually setting these constraints still the recommended path or is there a better way?
