### ISSUE TITLE
SEC-719: Refactor portlet code to make more use of core classes

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#983]
["Luke Taylor":https://jira.spring.io/secure/ViewProfile.jspa?name=luke](Migrated from ["SEC-719":https://jira.spring.io/browse/SEC-719?redirect=false]) said:

There is quite a lot of duplication between the portlet integration module and the core (especially with the preauthenticated provider code tat we now have). Here are a few suggested changes:
1. I'd like to replace the PortletAuthoritiesPopulator with an
   AuthenticationUserDetailsService (already in the preauth package, but
   may be moved elsewhere). The DaoPortletAuthoritiesPopulator would be
   replaced with the UserDetailsByNameServiceWrapper implementation,
   which is effectively the same in its functionally.
2. The logic for getUsernameFromPrincipal() in
   PortletAuthenticationProvider is already available in
   AbstractAuthenticationToken.getName() - can we remove this method and
   just call getName() on the token?
3. ContainerPortletAuthoritiesPopulator uses a list of roles, which can
   be set and will be checked for on the request. There is now a strategy
   in the preauth package "MappableAttributesRetriever" which does this and
   has implementations which can take a configured list of role names or
   can do things like read the roles from a web.xml file on initialization.
   The portlet.xml file has similar concepts to web.xml so the same strategy-based
   approach is probably justified here.

At the moment, the portlet interceptor is passing the PortletRequest
object to the populator by putting it in the "details" property of the
authentication token, so that it can extract the authorities. This
could probably make use of the
PreAuthenticatedGrantedAuthoritiesUserDetailsService instead, which
looks for an instance of GrantedAuthoritiesContainer in
the details object and pulls the authorities out of that if it finds
one. The portlet implementation could be modified to use a custom
version of AuthenticationDetailsSource in the same way as the preauth
module does - the implementation does the work of pulling the
preauthenticated authorities out of the request using isUserInRole
against each of the mappable roles it knows about.
1. If the above changes were made, the portlet provider would really
   just be a specialization of the PreauthenticatedAuthenticationProvider.
   It might not be necessary to have a separate provider class and token,
   or a slight customization might be all that's required.
2. Is there any need for the portlet module to have its own cache
   classes - these appear to be the same as the core ones?

**Comment by spring-issuemaster** [comment]
This issue depends on #984
This issue depends on #964
