### ISSUE TITLE
Spring Security Guide link returns 404

### ISSUE THREAD

**Issue by crynis** [spring-projects/spring-security#9896]
### Summary
Hey spring team! Im not sure whether this is the right place to report this small issue. 
Shortly said, I tried since days to reference the very nice guide for spring security from the spring portal. (https://spring.io/guides/topicals/spring-security-architecture/). But I just keep getting 404. Is it under maintainance or a bug? 

### Steps to reproduce
1. Go to spring.io
2. Click from to top navigatoin Learn -> Guides
3. Search "Spring Security Architecture"
4. Click on it.

**Comment by marcusdacoregio** [comment]
Hi @crynis, thanks for reporting this problem.

It seems that there was a problem with the `spring.io` caches that have been resolved already.
I'll close this as solved but feel free to discuss here if you face this problem again.
