### ISSUE TITLE
Document alternative to #oauth2 expression object

### ISSUE THREAD

**Issue by chrylis** [spring-projects/spring-security#9943]
I previously used the old Spring Security OAuth2 module, which provided [an expression object `#oauth2`](https://docs.spring.io/spring-security/oauth/apidocs/org/springframework/security/oauth2/provider/expression/OAuth2SecurityExpressionMethods.html) with `hasScope` and similar convenience features. As best I can tell, this has been removed with the v5 rewrite, but _lots_ of documentation and the top search results refer to this style.

It would be helpful to explain in the documentation that the expression object is no longer available and identify the alternative (is it simply `hasRole('SCOPE_foo')`)? (Alternately, the `hasScope` syntax in particular was conveniently expressive, but I can understand a desire not to unnecessarily add API surface area now that a standardized mapping is available.)

**Comment by jgrandja** [comment]
@chrylis Configuring authorization is already documented in the [reference](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver-jwt-authorization).

For example, if a protected resource authorizes on the scope `read` then the configuration would be:

`authorizeRequests.mvcMatchers("/resource/**").hasAuthority("SCOPE_read")`

> It would be helpful to explain in the documentation that the expression object is no longer available

I don't think it makes sense to reference legacy API in the new API reference.

I'm going to close this as I feel configuring scope-based authorization is well documented in the reference.
