### ISSUE TITLE
Consider adding springFrameworkVersion property

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-security#9954]
We should be able to access the `springFrameworkVersion` property in the project, like we have with `springBootVersion`. This would help better documentation links when pointing to the API or Reference docs.

Related [PR comment](https://github.com/spring-projects/spring-security/pull/9826#discussion_r653029117).

**Comment by marcusdacoregio** [comment]
@rwinch do you think adding such property in the `gradle.properties` file could be the solution here or you have another suggestion?

**Comment by rwinch** [comment]
I think that seems reasonable.
