### ISSUE TITLE
SEC-734: Latest Changes in SEC-99 breaking existing implementations of MethodDefinitionSource. 

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security#997]
["Alexander Gavrilov":https://jira.spring.io/secure/ViewProfile.jspa?name=lucker](Migrated from ["SEC-734":https://jira.spring.io/browse/SEC-734?redirect=false]) said:

introduced into interface method public ConfigAttributeDefinition getAttributes(Method method, Class targetClass); is the narrowed case of ObjectDefinitionSource#getAttributes(Object object) and it is not required to be in all implementations of MethodDefinitionSource. We have our own implementation, which return ConfigAttributeDefinition depending on object, not the object type. It is possiple to puth method down to the AbstractFallbackMethodDefinitionSource or introduce new internal interface, which extends MethodDefinitionSource to introduce new method.

**Comment by spring-issuemaster** [comment]
This issue is related to #360
