### ISSUE TITLE
logoutSuccessUrl in DefaultLoginPageGeneratingFilter is not set

### ISSUE THREAD

**Issue by skuhnert** [spring-projects/spring-security#9973]
**Describe the bug**
Relogin after logout leads to an error (404).

**To Reproduce**
* Startup a minimal webapp with spring-boot integration (see Sample)
* Login with user / _password from console-log_
* Klick on the logout-link
* Login again with user / _password from console-log_
* see error page

**Expected behavior**
Seeing the welcome page after 2nd login.

**Sample**
https://github.com/comlinegmbh/spring-security-missing-default-url-demo

**Woraround**
Please take a look in DemoApplication.java. If you remove the comments in line 27 (@PostConstruct), the relogin succeded.

Imo the standard configuration should take care of the logoutSuccessUrl.
Maybe directly in the DefaultLoginPageGeneratingFilter (see init() Methods) or by calling setLogoutSuccessUrl in FormLoginConfigurer.initDefaultLoginFilter?

**Comment by eleftherias** [comment]
Thanks for the report @skuhnert! 
This is now fixed and backported to the 5.5 and 5.4 branches.

**Comment by skuhnert** [comment]
Thanks for the quick fix!
