### ISSUE TITLE
Docs should point to samples in minor version branches

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-security#9986]
**Expected Behavior**
Spring Security docs links that point to Spring Security Samples should point to the minor version branches instead of the version tags. Instead of pointing to `5.5.1` for example, it should point to `5.5.x`.

This way we don't have to release Spring Security Samples every time a Spring Security release is done. 

This should be backported to `5.5.x`.

**Current Behavior**

Today the docs are pointing to a specific version tag that doesn't have related samples release

**Comment by gtiwari333** [comment]
This is still an issue. 

eg: https://docs.spring.io/spring-security/site/docs/current/reference/html5/#servlet-saml2login


The SAML 2 example is referring to non-existent  branch **5.5.1**.
> https://github.com/spring-projects/spring-security-samples/tree/5.5.1/servlet/spring-boot/java/saml2-login

**Comment by marcusdacoregio** [comment]
Hi @gtiwari333. 

The **current** in the docs link of Spring Security refers to `5.5.1`. Since this was merged for `5.6.0-M1` and `5.5.2` it should be fixed when we do the next release. 

You can refer to the docs for the snapshot release, like so: https://docs.spring.io/spring-security/site/docs/5.5.2-SNAPSHOT/reference/html5/#servlet-saml2
